### ISSUE TITLE
The selected marker does display over meny and ruler

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10021]
The dotted line that marks the selected entites and attribute currently is displayed over the ruler, top-menu and the fab-button. This should be changed.

 **The selected marker over ruler.**
![bild](https://user-images.githubusercontent.com/62853826/114680417-764fa980-9d0d-11eb-9285-6563bb34e70e.png)

**The selected marker over fab-button**
![bild](https://user-images.githubusercontent.com/62853826/114680616-a8610b80-9d0d-11eb-86e5-c959d1247285.png)

**Comment by a19nikbo** [comment]
Fixed
