### ISSUE TITLE
revisit hash generation

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10039]
Found a trend that new hashes always start with a 1, we should revisit the hash generation.

I was thinking we could try using the `atob()` and `btoa()` JS methods to get a base64 hash. The replacement can remain I think.

**Comment by a13zanal** [comment]
We have found why hash always starts with 1 and come up with the solution by removing for (). But should check more about atob () and btoa () for a better solution.

**Comment by b19ponka** [comment]
Found the cause for why new hashes always start with a 1, made an optional solution and will try to make a better solution including atob() and btoa() functions
