### ISSUE TITLE
insertParam is left undefined in showDugga.php which throws errors in certain courses

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10040]
We need to define insertParam in showdugga.php.

Currently datorgrafik's assignments do not throw this error, it would be interesting to know why

**Comment by b18jacha** [comment]
It's because $insertparam is first defined in a query that tries to find a variant that could be bind to the same $duggaid. And demo-courses has no variants binded to their duggaid.

**Comment by e15marol** [comment]
It never enters the foreach conditional on line 78 in showdugga.php, where the insertparam is defined. As b18jacha said, because it's trying to retrieve a variant that is not set in the database.

**Comment by a18osken** [comment]
Does the foreach conditional need to be entered now that we store variant locally? If so we must make sure that the entry condition can be fulfilled
