### ISSUE TITLE
The dropdown menu in properties in the options menu always shows "normal" after pressing save.

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#10050]
It doesn't matter if you choose any other property alternative in the dropdown menu and press save, it always shows "normal" even if the value is set to something else.

https://user-images.githubusercontent.com/62895155/114733711-e24d0480-9d43-11eb-943c-4e4b56a40e37.mp4

**Comment by a19nikbo** [comment]
Fixed
