### ISSUE TITLE
Document Canvas installation and create a GH Wiki page

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10054]
To aid in future projects where we are likely to work further with canvas integration we should document the installation progress so that future webservers can be prepped without the need for research.

**Comment by B18mohah** [comment]
Commands to install the libraries 

sudo apt-get install software-properties-common
sudo apt-add-repository ppa:brightbox/ruby-ng
sudo apt-get update
sudo apt-get install ruby2.6 ruby2.6-dev
sudo apt install postgresql zlib1g-dev libxml2-dev libsqlite3-dev ibpq-dev libxmlsec1-dev curl build-essential

curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs 
sudo npm install -g npm@latest

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list

sudo apt update
sudo apt install yarn
sudo yarn set version 1.19.1

sudo -u postgres createuser $MYACCOUNT
sudo -u postgres psql -c "alter user $MYACCOUNT with superuser" postgres
sudo gem install bundler -v 2.2.15
