### ISSUE TITLE
Fix text underline, for key attributes

### ISSUE THREAD

**Issue by a19karwa** [HGustavs/LenaSYS#10068]
When changing an attribute to a key attribute, it should have a text underline to indicate that it is a key!
![image](https://user-images.githubusercontent.com/81557429/114850833-76b97480-9de1-11eb-923c-7b4ad902c14b.png)

It should look something like this:
![image](https://user-images.githubusercontent.com/81557429/114850864-7f11af80-9de1-11eb-8c80-3537faddca61.png)

**Comment by a19nikbo** [comment]
Fixed
