### ISSUE TITLE
make sure the database row gets updated when resubmitting an assignment

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10064]
I'm not sure if the `useranswer` row gets updated when resubmitting at the moment, since synching the database is a bit of a mess. But we must make sure that this actually happens so that we can alter the answers of a hand-in and that alteration overwrites the old submission.

**Comment by a18osken** [comment]
Might very likely relate to and be solved by issue #10017

**Comment by a19frebo** [comment]
Solved in issue #10017
