### ISSUE TITLE
CodeViewer: Re-work of before/after in Edit Example

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#1007]
There needs to be a rework of the before/after list, where you choose what example comes next with the next/previous example button
Instead of the separate lists for each page which decides the next example there should be a global order in one drop-down menu and changing the order of examples should be easy, e.g. drag-drop.
The important part of this solution is that it should be light-weight html code creating this (as per customer-Henke's request) and that the name of this re-ordering is better then Before/After as those names gives no description of before/after what.

**Comment by HGustavs** [comment]
Even simpler html than drag and drop would be a list without dragging and dropping
Im thinking like the list view in windows, keeping the database mostly the same.
http://www.jennessent.com/images/generate_grid_4.gif

**Comment by HGustavs** [comment]
Im thinking this can be done with a simple service and without changing the database, move to top, move to bottom, move up, move down and add to bottom.... and two lists, all available examples and current ordered list.

**Comment by c13caral** [comment]
this is now solved
