### ISSUE TITLE
Code standard: Enums

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10071]
Hello! It seems `elementTypes` are not currently used correctly in the code.

We created an enum here:
https://github.com/HGustavs/LenaSYS/blob/beefa604ccab07743539eff9e4bab82c3752ce51/DuggaSys/diagram.js#L74-L79

But use magic numbers here:
https://github.com/HGustavs/LenaSYS/blob/beefa604ccab07743539eff9e4bab82c3752ce51/DuggaSys/diagram.js#L222-L233

I know that the element creation uses an index based array so the 0th element should be `elementTypes.ENTITY` and so on, removing the `elementTypes.NO_SELECTED` completely.

https://github.com/HGustavs/LenaSYS/blob/beefa604ccab07743539eff9e4bab82c3752ce51/DuggaSys/diagram.js#L754-L766

**Comment by a19nikbo** [comment]
Fixed
