### ISSUE TITLE
Delete multiple items at once in sectioned page

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10079]
Currently when deleting an item from the sectioned page, you have to press the delete item button on the screen and then confirm it. This has to be done for every item. It would be nice if there would be a way to delete multiple items at once. 
![image](https://user-images.githubusercontent.com/81559946/114870478-842e2900-9df8-11eb-833c-e052bff2ff07.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
