### ISSUE TITLE
Resize functionality fix needed

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10096]
The resize functionality is temporarily broken. This is because a drawElement() function call is used without passing "ctx" as an argument in the mmoving() function.

![image](https://user-images.githubusercontent.com/81541557/114893228-cd3ca800-9e0d-11eb-829e-2dea6b7c8763.png)

This is an easy fix. All that needs to be done is to add ctx as the second argument like:
drawElement(data[index], ctx)

**Comment by a19hammi** [comment]
We should move the `canvas.getContext()` into the `drawElements()` function so that fetching the context when needing to draw any element is not needed. In order to still allow use of custom fonts we should pass font settings as argument **_instead_**. Font style and font size should be sufficient.

**Comment by a19nikbo** [comment]
Fixed
