### ISSUE TITLE
Diagram does not avoid crossing lines automatically

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#10092]
Seeded version of diagram engine (from https://github.com/HGustavs/DiagramEngine/) avoids crossing lines, but the current LenaSYS code does not.

![test2](https://user-images.githubusercontent.com/6978801/114888086-3b32a080-9e09-11eb-8441-dab8d43fd649.gif)

**Comment by a19nikbo** [comment]
The weird thing is that this works on Firefox, but not on any other browser we've tried.

**Comment by HGustavs** [comment]
Seems to be a sorting quirk....

since browsers differ in the implementation of sorting this may result in problems when sorting ...

if return 1 and return -1 are swapped in the code the lines are un-crossed in chrome but never in firefox

**Comment by HGustavs** [comment]
// If lines cross swap otherwise keep as is
    if(axis==0||axis==1){
          // Left side
          ay=parent.y1+(((parent.y2-parent.y1)/(ends.length+1))*(ends.indexOf(a)+1));
          by=parent.y1+(((parent.y2-parent.y1)/(ends.length+1))*(ends.indexOf(b)+1));
          if(axis==0) parentx=parent.x1
          else parentx=parent.x2;

          if(linetest(toElementA.cx,toElementA.cy,parentx,ay,toElementB.cx,toElementB.cy,parentx,by)===false) return 1
    }else if(axis==2||axis==3){
          // Top / Bottom side
          ax=parent.x1+(((parent.x2-parent.x1)/(ends.length+1))*(ends.indexOf(a)+1));
          bx=parent.x1+(((parent.x2-parent.x1)/(ends.length+1))*(ends.indexOf(b)+1));
          if(axis==2) parenty=parent.y1
          else parenty=parent.y2;

          if(linetest(toElementA.cx,toElementA.cy,ax,parenty,toElementB.cx,toElementB.cy,bx,parenty)===false) return 1
    }

**Comment by HGustavs** [comment]
In this specific case the 1 is sorted to the top in firefox but to the bottom in chrome or vice versa.

**Comment by HGustavs** [comment]
if (navigator.userAgent.indexOf("Chrome") !== -1){
        sortval=1;
    }else{
        sortval=-1;
    }

    // If lines cross swap otherwise keep as is
    if(axis==0||axis==1){
          // Left side
          ay=parent.y1+(((parent.y2-parent.y1)/(ends.length+1))*(ends.indexOf(a)+1));
          by=parent.y1+(((parent.y2-parent.y1)/(ends.length+1))*(ends.indexOf(b)+1));
          if(axis==0) parentx=parent.x1
          else parentx=parent.x2;

          if(linetest(toElementA.cx,toElementA.cy,parentx,ay,toElementB.cx,toElementB.cy,parentx,by)===false) return sortval
    }else if(axis==2||axis==3){
          // Top / Bottom side
          ax=parent.x1+(((parent.x2-parent.x1)/(ends.length+1))*(ends.indexOf(a)+1));
          bx=parent.x1+(((parent.x2-parent.x1)/(ends.length+1))*(ends.indexOf(b)+1));
          if(axis==2) parenty=parent.y1
          else parenty=parent.y2;

          if(linetest(toElementA.cx,toElementA.cy,ax,parenty,toElementB.cx,toElementB.cy,bx,parenty)===false) return sortval
    }

    return -sortval;

**Comment by HGustavs** [comment]
...Not proud of this fix but... it at the very least sorts the same way on chrome and on firefox on my machine. Unclear what happens in safari on iphone/ipad etc.

Perhaps there is a better fix that does not rely on browser detection?

I do not know the reason for this particular quirk.

**Comment by a19frelu** [comment]
The code you suggested seems to work fine with a bunch of different browsers, but not with Safari unfortunately. This is not a major problem for us in group 3 because no one is using Safari anyway. How do you look att this @HGustavs ?

The tested browsers are:
- Mozilla Firefox
- Google Chrome
- Brave
- Opera
- Safari (Only one not working)

**Comment by a19hammi** [comment]
fixed in #10562
