### ISSUE TITLE
Solve error in diagram_IOHandler.js

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10100]
We've had an error running, ever since we replaced the diagram drawing engine with the new one, that shows up on the window loading. While it has so far not led to any problems there's the fact that another `.js` file is attempting to use the old system. We should investigate this and make sure it does not lead to future problems.

![image](https://user-images.githubusercontent.com/81571224/114980774-3dd6d980-9e8d-11eb-9a5b-8e04b38fa4be.png)

**Comment by a19nikbo** [comment]
Fixed
