### ISSUE TITLE
Remove unused code in sectioned.js

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10104]
In pullrequest #9864 there was some code that was removed. However, it didn't merge with the later version of the system for some reason and this code needs to be removed. The picture below shows the code that needs to be removed in sectioned.js. 
![image](https://user-images.githubusercontent.com/81559946/114989640-e853fa00-9e97-11eb-84ea-469cb4e4a557.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
