### ISSUE TITLE
Diagram: Random id maker - check that the id is unique

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10117]
Currently does the function `makeRandomID`  generate a random string, but there is no check if the id isn't already in use. Even if the chance that the same id will be generated two times is slim, but for error prevention this should be checked.

**Comment by HGustavs** [comment]
This is likely to be slow especially with large diagrams.

If we use base64 strings ... we get quite large numbers very very fast.

https://www.youtube.com/watch?v=gocwRvLhDf8

....We could use even longer strings than youtube.... every additional character makes a difference.
