### ISSUE TITLE
Remove unused parameters

### ISSUE THREAD

**Issue by a19steis** [HGustavs/LenaSYS#10121]
The onMouseModeEnabled and onMouseModeDisabled functions are currently using the mouseModes enum instead of the parameter variable. The parameter variable should simply be removed.

https://github.com/HGustavs/LenaSYS/blob/4dbd977d9a425779289f95752fee982e2f09f8b7/DuggaSys/diagram.js#L685-L711

**Comment by a19nikbo** [comment]
Fixed
