### ISSUE TITLE
Check template files for user data 

### ISSUE THREAD

**Issue by a19rebsa** [HGustavs/LenaSYS#10122]
Not sure if there could be user data being stored in the template files (LenaSYS/DuggaSys/templates/). These files should be looked through to see if there is any data being stored about students. What you find should be commented in this issue.

**Comment by a19gusba** [comment]
How should data related to feedback be used? Should feedback stay on lenasys or move to canvas, it currently contains information such as grades. Exists in multiple templates but example in "3d-dugga.js:109".

Information in showFacit contains the variable "userStats" does this contain personal information?

**Comment by a17alfja** [comment]
Affected files

Feedback & Facit:
most .js files in templates

Groups:
group-assignment.js

Logged-in checks:
daily-minutes.js
generic_dugga_file_recieve.js
group-assignement.js

**Comment by a18osken** [comment]
> How should data related to feedback be used? Should feedback stay on lenasys or move to canvas, it currently contains information such as grades. Exists in multiple templates but example in "3d-dugga.js:109".
> 
> Information in showFacit contains the variable "userStats" does this contain personal information?

Feedback will move to canvas in its entirety

**Comment by a19rebsa** [comment]
Created issues for logins in daily-minutes.js, generic_dugga_file_recieve.js, group-assignement.js (#10142, #10144, #10145). Not sure about how feedback and groups are supposed to work, will look into this.
