### ISSUE TITLE
Look for uses of personal information in showDugga.php

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10136]
We need to check where/if the showDugga.php file writes to or reads from personal information in the database.

**Comment by a19frebo** [comment]
Row 92 Selects from databse based on user ID
Row 95 Binds parameter to user ID in the query on row 92

Both row 92 and 95 might be moved to showduggaservide.php from issue #10091 

Row 173 Selects username based on user ID for logging

Row 183 Both username and user ID is logged with "logDuggaLoadEvent()"

**Comment by a19kevkh** [comment]
Row 193 user ID is used to check if user has readaccess

Row 206 Uses user ID to check if the user is a super user

Row 285 User ID is logged with "makeLogEntry()"

Row 318 Checks if user ID is not equal to "UNK"

Row 398 Uses user ID to check if the user is a super user
