### ISSUE TITLE
Clicking on background when holding ctrl still deselects all selected lines

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10131]
This should work the same way as with elements. If a line is selected and you click on the white background when ctrl is held down it should not deselect anything. This is to mitigate user error since it's easy to accidentally miss a line when clicking because they are so small.

**Comment by HGustavs** [comment]
I suggest making the click distance for lines quite large.

It is better to over-detect line clicks than under-detecting such clicks.

**Comment by a19nikbo** [comment]
Fixed
