### ISSUE TITLE
"Create user" -dialog, remove attributes: SSN, Term, PID

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10149]
SSN in the create user dialog should be removed along with any code related to it. 
Term and PID should be investigated to see if it is used for something or if it can be removed without breaking something. 

![image](https://user-images.githubusercontent.com/81559946/115212322-ac6f9d80-a100-11eb-878d-6c53439fa534.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
