### ISSUE TITLE
Remove login-lock and examine score variable in daily-minutes.js

### ISSUE THREAD

**Issue by a19rebsa** [HGustavs/LenaSYS#10144]
In the template file daily-minutes.js there is code for showing the login-lock when not logged in. This should be removed. Also the variable "score" in the saveClick() function should be examined to see if it is needed for saving the dugga, this could maybe otherwise be some type of personal information.

**Comment by a19kevkh** [comment]
Removed login-lock when not logged in and also removed the variable score in the saveClick() function.

**Comment by a19frebo** [comment]
When we tested this we saw that the dugga is not working properly at all even before our changes. This dugga template does not seem to be complete. For example the variable elapsedTime is not defined.
