### ISSUE TITLE
Remove/Replace personal information in showdugga.php

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10140]
Any use of data that can be tied to a person need to be replaced with using data that can not identify said person. Furthermore if personal information is saved we should no longer do that either. This may require altering the db tables and may be broken out into smaller issues, especially pertaining to database alterations.

**Comment by a18osken** [comment]
@a19frebo  and @a19kevkh  has compiled a list of these occurrences here #10136

**Comment by a19gusba** [comment]
how should the functions "logDuggaLoadEvent()" and "makeLogEntry()" be used? Atm they use $userID as parameter. Should these functions be updated to not require userid or should the functions be removed.


logDuggaLoadEvent($cid, $userid, $username, $vers, $quizid, EventTypes::pageLoad);
makeLogEntry($userid,1,$pdo,$cid." ".$vers." ".$quizid." ".$duggafile);

**Comment by a18osken** [comment]
We have not yet figured out what exactly is being logged, I think these logging functions are to keep track of user activity, which if it is the case will be superfluous as students won't have logins.
