### ISSUE TITLE
Remove login-lock and examine score variable in generic_dugga_file_receive.js

### ISSUE THREAD

**Issue by a19rebsa** [HGustavs/LenaSYS#10142]
In the template file generic_dugga_file_receive.js there is code for showing the login-lock when not logged in. This should be removed. Also the variable "score" in the saveClick() function should be examined to see if it is needed for saving the dugga, this could maybe otherwise be some type of personal information.

**Comment by a19frebo** [comment]
Removed the login-lock.
Removed the variable "score" from both the global section and from the saveClick() function, since it was never used when saving the dugga.
