### ISSUE TITLE
Add functionality to assignment login dialog

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10141]
Now that the assignment login dialog is in place we want to compare the password input to the database and show the matching assignment hand-in

**Comment by HGustavs** [comment]
we must make sure that no data is sent if password is incorrect and that we get some kind of informative error message.

What does it look like currently when we log in without proper credentials?

**Comment by a18osken** [comment]
Currently we do not load any assignment while logging in and I was thinking we keep it as such when the wrong password is entered. As a sidenote, if all the passwords share the same length we could do a quick regex to check for the length for some QoL?  
![loginrn](https://user-images.githubusercontent.com/62884391/115215338-b34bdf80-a103-11eb-94cc-aafe52e9243d.png)

**Comment by a19simma** [comment]
hashpassword is stored in a $_SESSION variable, maybe this is not appropriate for security reasons?

**Comment by HGustavs** [comment]
It is fine to store password in session since session is not shared with client
