### ISSUE TITLE
Diagram: Mark selected mode in toolbar.

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10162]
Currently when the user is hovering over a mode in tool-bar an darker background. The background should stay dark when the mode is selected.

**For exampel (line-mode selected)**
![bild](https://user-images.githubusercontent.com/62853826/115222294-dfb72a00-a10a-11eb-90e6-4cd42c184d15.png)

**Comment by a19nikbo** [comment]
Fixed
