### ISSUE TITLE
Merge performed incorrect or missplaced line?

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10164]
https://github.com/HGustavs/LenaSYS/blob/cd5eab6a42b631e4e96c4f26b321df102ddbd499/DuggaSys/diagram.js#L1216

Error message displayed when line CAN be added.

**Comment by a19chrel** [comment]
This issue is connected with #10156 and has a ongoing pull request #10170 where this error is corrected.
