### ISSUE TITLE
"Fab" button overflow

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10179]
When using a phone i landscape mode, the fab button menu goes beyond the screen. This needs to be fixed. This could be done by making the options go along the bottom instead of along the side.  
![image](https://user-images.githubusercontent.com/81559946/115243812-98896300-a123-11eb-8073-803259656f6d.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
