### ISSUE TITLE
Change cursor style for the different elements

### ISSUE THREAD

**Issue by a19steis** [HGustavs/LenaSYS#10175]
Considering that we have "ghost" elements following the cursor when choosing relation/attribute or entity we no longer need a specific cursor to know which element is chosen.

I suggest that we change the current cursor which is triggered by choosing an element into its original style, namely "default".

https://github.com/HGustavs/LenaSYS/blob/4dbd977d9a425779289f95752fee982e2f09f8b7/DuggaSys/diagram.js#L663-L683

**Comment by a19nikbo** [comment]
Fixed
