### ISSUE TITLE
the "Files" page is not working and is a blank page

### ISSUE THREAD

**Issue by a13chrju** [HGustavs/LenaSYS#1019]
the page as of now is blank with no information whatsoever.

the javascript file is constructed in a way that the buttons for adding new files and links are only displayed if there is a file created for the chosen course. the buttons should be there even if no files exists otherwise you can't add any at all if you dont do it directly in mysql. 

files don't even get uploaded and directories aren't created after inserting a new file or link, only "insert" statements are completed and imported to the DB.

furthermore, links to the stylesheets and javascript files aren't correct.

**Comment by HGustavs** [comment]
I believe that this may be due to problems with permissions.

The filereceive service should write the file if it is able due to permissions.

**Comment by HGustavs** [comment]
Showdoc is used to read the file.

Similar functionality to showdoc is needed for issue #1008

**Comment by a13chrju** [comment]
yes, I will (or someone) have to fix the "showdoc.php" file that reads the files aswell

**Comment by HGustavs** [comment]
It should work by the file name, if the file name you give exists as a global file you get that file but if there is a local file with the same name it gets precedence. As for local and global I think that the kind of file is decided on upload.

This way you can have newer versions of a file, and older versions of the same course see the old file....as long as the file name is the same.

**Comment by a13chrju** [comment]
aha okey, yeah I had to change a lil to have the buttons up from the beginning and the global function kinda stopped working but I fixed it with the attribute. I will look into it

**Comment by a13chrju** [comment]
might come a follow up on this later
