### ISSUE TITLE
Change colour in swimlanes

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10228]
Currently, the swimlanes have a yellow/orange text that kind of blur together with the gray backround. There should be a higher contrast between the colours to make it more readable. This should follow the LenaSYS colour scheme which can be found here: https://github.com/HGustavs/LenaSYS/wiki/CodeViewer
![image](https://user-images.githubusercontent.com/81559946/115401555-d00f1280-a1ea-11eb-8013-befcae3611d8.png)

**Comment by a19isada** [comment]
The same problem occurs when something has been handed in: 
![image](https://user-images.githubusercontent.com/81559946/115402090-617e8480-a1eb-11eb-924c-e7b0f203c9c4.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
