### ISSUE TITLE
Separating states with long time span in-between 

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10223]
As of right now you could do a change on an element, wait for an hour and then edit it again and this would count as a single soft change. I've introduced a stored timestamp variable inside each StateChange object but we lack logic to use it. Therefore I recommend introducing some form of "maximum time limit" before storing a soft change as a hard one instead!

**Comment by HGustavs** [comment]
Since all changes between timer steps are lost if we close the window (or for example if browser crashes) I suggest that the timer should be relatively short. For example a few seconds.

**Comment by a19hammi** [comment]
fixed in #10778
