### ISSUE TITLE
Fab button has same margin to poopup button when big as when small

### ISSUE THREAD

**Issue by a18danli** [HGustavs/LenaSYS#10220]
![Skärmavbild 2021-04-20 kl  14 10 38](https://user-images.githubusercontent.com/80164222/115395999-caaec980-a1e4-11eb-904e-48d3c7be91db.png)

**Comment by a18danli** [comment]
This is the small button in a small screen, but the margin to the next button is to big to click on the "message button".

**Comment by a19isada** [comment]
This was only implementad at a local level and it was decided to wait with the implementation of a smaller button until later
