### ISSUE TITLE
Person-element always get a bigger ID than other elements

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10234]
For some reason the Person element is given a 12-letter long id instead of only 6 letters.
I assume it is given two id's at once??
Even when swapping positions with another element it is still only the person element that has this problem.

While this technically doesn't introduce weirdness right now I think we should solve this ASAP.
We could assume this might introduce weirdness at a later stage in development.

**Comment by a19hammi** [comment]
With moving positions I mean swapping the data array position and not the makeRandomID function call which is the very first ID to be generated. It most likely is linked to being the first ID to be generated.

**Comment by a19hammi** [comment]
While looking through it i found the issue. We have a missing line here as there should be a `return str` after pushing to the array:
https://github.com/HGustavs/LenaSYS/blob/c287eb7306416d9744d5c1404b1c0b156ad8287d/DuggaSys/diagram.js#L448-L450

But personally I believe this could be a lot shorter and contain a lot less branching statements...
https://github.com/HGustavs/LenaSYS/blob/c287eb7306416d9744d5c1404b1c0b156ad8287d/DuggaSys/diagram.js#L445-L460

Here's a suggested change that I made, not tested or anything but much simpler branching when it comes to the while loop contents:
```js
while (true)
{
  // Generate new ID
  for (var i = 0; i < 6; i++)
  { 
    str += characters.charAt(Math.floor(Math.random() * charactersLength)); 
  } 
   
  // Make sure the generated ID does not match any existing
  if (!randomidArrray.includes(str))
  {
    randomidArray.push(str);
    return str;
  }
  else str = "";
}
```

**Comment by a19nikbo** [comment]
Fixed
