### ISSUE TITLE
Change remove sign to trashcan

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10233]
Currently, the sign to remove multiple items is a dash. This should be changed to a trashcan to make it obvious what the button does. 
![image](https://user-images.githubusercontent.com/81559946/115408990-a1e10100-a1f1-11eb-96b7-5533bf3818f6.png)

**Comment by HGustavs** [comment]
Yes this is a good idea

**Comment by a19isada** [comment]
This functionallity is going to be changed so this is unessesary
