### ISSUE TITLE
Diagram: Gridsystem should follow the panning and extent to the right

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10238]
First, when the gridsystem is drawn it currently is not extented to the right border of the window. The width is not 100%.

![bild](https://user-images.githubusercontent.com/62853826/115416977-862d2900-a1f8-11eb-8967-59e04d1e846c.png)

Also, the gridsystem should follow the padding in the diagram. Currently it is placed static on the page.

**Comment by a19nikbo** [comment]
Fixed
