### ISSUE TITLE
Code standard not followed by diagram

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#10243]
The diagram code is not consistent when following the code standard. 

The code standard for LenaSYS is K&R, and much of the code does not follow this style.

https://en.wikipedia.org/wiki/Indentation_style#K&R_style

A few examples

```
for (var i = 0; i < data.length; i++) <--- should be up here
 {   <--- A curly brace here indicates a function and not a for-loop
```

```
   } <--- else should be at most one space character from this curly brace, no new line
    else if(event.target.classList.contains("node")){
```

```
                  } <---- else should be here
                    else if (mouseMode == mouseModes.POINTER) <--- curly brace should be here
                    { 
```

**Comment by HGustavs** [comment]
This is much better!

The reviewers must keep an eye at the code standard when reviewing submitted code. It seems like this was not done, and several distinct code standards were used in a number of places.

**Comment by a19nikbo** [comment]
Fixed
