### ISSUE TITLE
Drag and hold to draw line BUG

### ISSUE THREAD

**Issue by a19karwa** [HGustavs/LenaSYS#10254]
If you are on drawline selection, you can now click on one element and drag to another to temporarily create a line between them, if you afterwards click outside the elements the line between them will disappear.

![image](https://user-images.githubusercontent.com/81557429/115543944-41f66300-a2a2-11eb-95e2-d1db916bdaca.png)

**Comment by a19nikbo** [comment]
Fixed in another issue
