### ISSUE TITLE
CodeViewer: all examples should have proper impword display

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#1025]
For instance, the datattype var doesn't highlight the same in all examples ( pink in some, black in some ), this should be fixed

**Comment by HGustavs** [comment]
It is important that we can highlight the different languages differently....

apart from that I do not have any strongly voiced opinions on the topic of highlighting.

Var can (for natural reasons) be a reserved word in javascript but not in html or glsl

**Comment by a18kaswi** [comment]
Can't get hold of the one requesting the change, closing.
