### ISSUE TITLE
Navbar options disappears when in mobile view

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10263]
When a teacher is visiting the sectioned page, some of the options in the navbar disappears. This needs to be fixed. This could be fixed by making a "hamburger" menu or it could be fixed by doing something else that fits well with the site. 
![image](https://user-images.githubusercontent.com/81559946/115552174-4889d800-a2ac-11eb-8e43-a253bb417283.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
