### ISSUE TITLE
Template 3 icon does not represent code

### ISSUE THREAD

**Issue by b12alela** [HGustavs/LenaSYS#1026]
The template 3 icon shows a layout that differs from the one used in the code, in fact the icon is a mirror image of how it is specified in the code.

Possible solutions: rotate the template icon 180 degrees.

**Comment by HGustavs** [comment]
Compared to issue #1073 ... does this template reflect any "reality" in a course or is it the icon that better represents how it is used in a course?

**Comment by f12danjo** [comment]
Fixed by [#1436](https://github.com/HGustavs/LenaSYS/pull/1436)
