### ISSUE TITLE
Make ruler follow grid

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10306]
We've just made it so that the grid follows the panning when you click-drag on the background canvas. It was nice having the numbers on the ruler live update when the grid was static, but it looks a bit weird now that they're not synced. It would be better if they didn't live-update, but instead that the lines and numbers on the ruler panned left and right on the top bar, and up and down on the side bar as you panned the canvas.

**Comment by a19hammi** [comment]
fixed in #10510
