### ISSUE TITLE
Copy-Paste elements

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10309]
While me and @a19chrel were doing some user testing we discovered that we almost instantly wanted to be able to copy-paste diagrams. A keyboard shortcuts like CTRL+C, CTRL+X and CTRL+V is something that is really missing! We should implement some form of copy paste, either using the native OS or some form of clipboard object in the code.

**Comment by a19hammi** [comment]
Using the native clipboard would allow for the user to copy element data and paste it in a chat or something similar.
This would allow people to share individual or a group of elements as a string, and it could also let us paste elements FROM a string that is in the clip-board.

**BIG NOTE:** IF we decide to read from a native clip-board, then we MUST sanitize the input data!

**Comment by a19nikbo** [comment]
Fixed
