### ISSUE TITLE
Check if there are several logins to the same hashed assignment

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10312]
We should create some kind of token to see if there are several users currently logged in on a hashed assignment, this is to enable functionality to synchronize group assignments later.

**Comment by a19gusba** [comment]
How should groups work? Should the teachers provide an url to the group with a hash or should one student create a hash and share with the others in the group?

**Comment by a19gusba** [comment]
found problems when a student closes the browser in ways such as using the task manager or turning off the computer the javascript event that triggers whenever the tab closes doesn't get called when using the two methods mentioned.
