### ISSUE TITLE
Remove all feedback for assignments on the students side 

### ISSUE THREAD

**Issue by a19rebsa** [HGustavs/LenaSYS#10313]
All feedback that has to do with a student should be removed from the students view. Right now you can't see the feedback in the GUI but there is still code for getting the feedback etc. This should be looked through and removed.  If you are logged in as a teacher you should still be able to write feedback on assignments.

**Comment by a18osken** [comment]
The feedback functionality for a teacher is nice to keep as a reference for the future goal of sending feedback written in LenaSYS to the Canvas feedback. There is no need to specifically reinstate the ability to write feedback right now.

**Comment by a19kevkh** [comment]
We will kill everything related to feedback. Leave no survivors!
