### ISSUE TITLE
Pressing enter to confirm changes

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10310]
For people who do not want to move the mouse around for simple actions like saving a new property like names to elements it would be really useful if ENTER could be pressed to automatically interact with the "Save" button in the properties field set in the options menu. We already have logic that knows if the properties fields have context or not so it shouldn't be too difficult!

**Comment by a19chrel** [comment]
Agree, the less mouse movements the better. 

As you said, this selection check if an INPUT or simular is in focus.
https://github.com/HGustavs/LenaSYS/blob/0ef028bbe421f3a952af02f310665c6048c6b631/DuggaSys/diagram.js#L686

**Comment by a19nikbo** [comment]
Fixed
