### ISSUE TITLE
Create an iframe with the lenasys assignment in the canvas... assignment

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10319]
The integration towards canvas should be used through iframes... I think that currently canvas is already supporting this in that their assignments are in iframes... look into this. But basically we want the asisgnment to be shown in canvas, no need to be redirected to Lenasys.

**Comment by b18jacha** [comment]
Yes, canvas has built-in iframe that we can use, we will try this out

**Comment by e15marol** [comment]
Canvas does indeed support iframes, currently on the test server there are no assignments with iframes but we will try and add one.

**Comment by e15marol** [comment]
We've successfully created an assignment within an iframe. http://canvas.webug.his.se/courses/1/pages/bit-dugga-1

**Comment by e15marol** [comment]
You can not script inside the html editor, that is because it is not whitelisted, so it is filtered out.

**Comment by b18jacha** [comment]
We had problems setting the height in canvas but we tried using viewport-relative-lengths and it seems to work flawlessly!

**Comment by a19rebsa** [comment]
It seems to work fine so closed this issue
