### ISSUE TITLE
Score should not be stored in the database

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10317]
There is no real way of having a highscore across different students without saving some kind of personal information. The score variables should no longer be stored in the database. We could leave the functionality though and later have the score be a localStorage item, but we ought to put that functionality low on the priority list.

**Comment by a19simma** [comment]
Score should be null in the database on new duggor saves. 
![image](https://user-images.githubusercontent.com/81557282/115841413-0b912300-a41d-11eb-806a-09414894920d.png)
