### ISSUE TITLE
Find a way to track local changes in a group assignment

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10314]
We should explore how easy it is to track local user activity in a hypothetical group assignment. So that later on we may synchronize several users if for example some changes have been made locally.

This is very exploratory and we must strike a balance between keeping a nice synchronous flow in the assignment while also not making the machine catch fire.

**Comment by a19simma** [comment]
🔥

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/115845320-02a25080-a421-11eb-9441-b49d2807fac9.png)
