### ISSUE TITLE
Create student and teacher account for canvas testing

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10328]
For testing canvas from different user perspectives we should make accounts with different accessibility on the site.

**Comment by a19arvka** [comment]
Accounts have been made and added to the course "Webbutveckling - datorgrafik".
I've used the *Test users* table information as login id & student mail. I have kept their password to be the same as the one they had on LenaSys. 
The accounts and their specified role will be announced in the Discord server.
