### ISSUE TITLE
Accidental deletion of if-statements in removeElements

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10339]
There's missing if-statements that was removed in my previous pull request #10293.
Inside `removeElements(elementArray, stateMachineShouldSave = true)` there's two  missing if-statements `if (stateMachineSouldSave)` that should prevent the state machine from storing the deletion of elements if the second parameter is false.

Right now undoing creation of elements will first remove them, and then re-add them on the following undo.

**Comment by a19nikbo** [comment]
Fixed
