### ISSUE TITLE
Initial state: Premade data set state OR Empty slate?

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10334]
Currently there's no way to go ALL the way back via the state machine. We need an INITIAL state that we originate from.
This state needs to be stored inside the state machine if we use a **default set of elements** when making a new diagram file.

If we instead go with a **blank slate** then don't need to store the initial state in our state machine but will need to create our example elements to perform tests on. I therefore recommend we create a function to generate the diagram that we're currently using. This function should then call our own createElement() functions so that they're recorded by the state machine correctly.

Cut short, we have two options what I know of. @HGustavs has said that both is fine so I will leave this one up for discussion in the group so that we then can decide which one is the most appropriate!

**Comment by HGustavs** [comment]
I think that the empty state is a subset of having to start from some other state.

For some assignments we would like to have the option to give the students an existing diagram to modify.

This can be handled by marking some point in a history as un-passable. It would be possible to revert to any state after the read only state but no state behind that point.

If the history is an array we can simply have a property saved with the history called something like readonly 0 if start from empty but if the history for example has 10 history states that we want to protech this variable contains the number 10

**Comment by a19nikbo** [comment]
Fixed
