### ISSUE TITLE
So Postgresql is not mysql

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10333]
Canvas runs on Postresql. It would be good if someone became the lead expert in the field in regards to Postgresql so that we know how that works when we need data from canvas concerning students

**Comment by HGustavs** [comment]
It does not matter. We have no access to the underlying database of the canvas installation used at the university. I am not even sure that it is hosted at the university or by some other entity.

The plan is to make modules that can call canvas using LTI web services

http://www.imsglobal.org/activity/learning-tools-interoperability

**Comment by HGustavs** [comment]
Specifically for assignments

https://canvas.instructure.com/doc/api/file.assignment_tools.html

Most of every other interaction can be handled through iframes

**Comment by a18osken** [comment]
Good stuff! I'll update concerning issues with this new information tomorrow.
