### ISSUE TITLE
Exiting out of mouse states

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10335]
Pressing ESCAPE when we're in a mouse state, like BOX-SELECT for example should in my opinion exit and return us to the pointer state. This feels like a natural workflow option.

**Comment by HGustavs** [comment]
If mouse state is in a single variable e.g 0 for no action 1 for drawing entity 2 for selection box etc it should just entail setting that variable to 0.

Any solution more complicated than that is probably a bug.

**Comment by a19nikbo** [comment]
Fixed
