### ISSUE TITLE
You should not be able to use the right mouse button to create lines between elements

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10345]
It should only be possible to create new lines between elements with the left mouse button.

**Comment by a19nikbo** [comment]
Unsure if this is an issue with specifically Brave or if it's the same with other browsers. Further testing required.

**Comment by a19steis** [comment]
This is also a problem in Chrome and Firefox.

**Comment by a19nikbo** [comment]
Fixed
