### ISSUE TITLE
Diagram: Display message

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10355]
Currently can we only show one message at the time. This can be an issue if actions are made rapidly, the user wont have the chance to read the message.

Currently
![bild](https://user-images.githubusercontent.com/62853826/115851215-fd480480-a426-11eb-910c-cdc5266bb4cd.png)

Maybe something like this could be an solution, that the not closed messages is translated above the new one.
![bild](https://user-images.githubusercontent.com/62853826/115852049-f077e080-a427-11eb-93f2-362a340eeefa.png)

**Comment by a19nikbo** [comment]
Fixed
