### ISSUE TITLE
Document AJAXService

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10360]
Currently, there is no documentation of AJAXService. This documentation should be created.

**Comment by a20chrjo** [comment]
What should the documentation describe?

@a19isada

**Comment by a19isada** [comment]
The documention should describe how it should be used. Currently it is unknown how to use it. @a20chrjo

**Comment by a20chrjo** [comment]
@a19isada I found where this was mentioned on Discord, thanks for the help!

> William [a18willi] — 04/23/2021
> Henrik [gush]  Finns det någon dokumentation kring AJAXSservice? Vi skulle behöva updatera tabellen "listentries" när användaren trycker på en knapp på hemsidan, men vi har lite svårt att lista ut hur saker hänger ihop.

> 
> Henrik [gush] — 04/23/2021
> Nej inte mycket dokumentation utöver själva koden.
> Man skickar med ett antal parametrar och vilken tjänst i tjänstefilen man vill anropa
> exv en jänst skulle kunna heta ADDP och då finns det motsvarande if-sats som exekverar om  tjänstenamnet är ADDP och så finns det kod högst upp som hämtar alla parametrarna
> Jag tänker det kan vara värt att göra en issue för att skapa den dokumentationen

**Comment by a20chrjo** [comment]
Which files is talked about here?

@b18phika @a18willi

**Comment by b18phika** [comment]
@a20chrjo 
The AJAXService function can be found at line 885 in dugga.js.
There are a bunch of functions that "take care" of the data that's returned from the backend, for example, "success: returnedCourse" (line 946), so if the whole dataflow is to be documented, I'd include those as well. 

The code that handles requests from AJAXService and returns the data, is as far as I know scattered in the files named *service.php.

**Comment by b19alest** [comment]
Document with documentation about AJAXService:
https://docs.google.com/document/d/1RlAVhk055e_hi9mFxcld_j5sShOYqZ9zZJEvw9O2xR8/edit?usp=sharing

@a19anjst
