### ISSUE TITLE
Set regions in code to make certain areas of the code hide-able

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10368]
With the ability to "fold" regions of code would make it easier to focus on the specifics parts of the code that matter when working. This way we could fast go past regions without a bunch of scrolling!

The way to make regions is as follow:
```js
//#region REGION_NAME
function thisIsAVeryLongFunctionName(andImAnParameter) {
  hereWehaveAnotherFunctionCallWithLongName();
  var andHereIsAVariable = 10;
}

function thisIsAnotherVeryLongFunctionName(anotherOne, andAnotherOne) {
  hereWehaveAnotherFunctionCallWithLongNameAgain();
  var andHereIsAnotherVariable = 10;
}
//#endregion REGION_NAME

**Comment by a19hammi** [comment]
Pull request will open after weekly merge to circumvent merge conflicts on huge scales.

**Comment by a19nikbo** [comment]
Fixed
