### ISSUE TITLE
Pasting multiple elements on top of each other and then moving one of the stacked elements bug

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10365]
Pasting multiple elements on top of each other without moving the mouse, and then trying to move one of the stacked elements makes the element flip out.

**Comment by HGustavs** [comment]
Are we talking about copy/paste or just moving elements?

**Comment by HGustavs** [comment]
A screenshot would be very helpful

**Comment by a19nikbo** [comment]
As far as I know, it's specifically when pasting copied element(s) on top of each other.

![pasteExample](https://user-images.githubusercontent.com/81541557/115879628-2c23a200-a44a-11eb-9c20-29b1b97fd47d.gif)

**Comment by a19nikbo** [comment]
Fixed
