### ISSUE TITLE
Generate ID's for pre-made data contents

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10364]
Right now we have several lines of ids that are stored in global space that are only used in a single place of our code. Not only that but we could literally just use the makeRandomID() on that one single place as-well. Unnecessary variables!

**Comment by HGustavs** [comment]
These variables are necessary to know which id-s to connect the relationship ends to...

but I think we can use the history approach and explicitly store the identifiers and not generate identifiers dynamically.

**Comment by a19nikbo** [comment]
Fixed
