### ISSUE TITLE
Unnecessary if-statement in diagram.js

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10372]
This region in the code checks if the selected element is *not* INPUT, SELECT or TEXTAREA.

https://github.com/HGustavs/LenaSYS/blob/c8b65aa1b513777e678cbe350d396adb2fda0c7a/DuggaSys/diagram.js#L752-L786

Right after that we have this code that checks if the selected element *is* INPUT, SELECT or TEXTAREA.

https://github.com/HGustavs/LenaSYS/blob/c8b65aa1b513777e678cbe350d396adb2fda0c7a/DuggaSys/diagram.js#L788-L793

Logically, if the first if-statement evaluates to false, that means that the second must evaluate to true. This means that a simple "else" would be enough instead of the second if-statement.

**Comment by HGustavs** [comment]
Seems much cleaner at least
