### ISSUE TITLE
Diagram: Double print of weak-entities text-element

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10381]
Currently does the weak-entities in the diagram contains 2 text-elements. If you check the linked code, the text element is added both in the weak-string and the str-string. Which makes the element to contain 2 text elements.
https://github.com/HGustavs/LenaSYS/blob/4246ce29590582df51d2c592809e450a59f04313/DuggaSys/diagram.js#L1941-L1956

**Comment by a19nikbo** [comment]
Fixed
