### ISSUE TITLE
Diagram cardinality

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#10387]
One of the major features missing from the diagram editor is the use of cardinality on association ends.

Either 1 or N for ER diagrams

<img width="388" alt="Screenshot 2021-04-25 at 21 04 16" src="https://user-images.githubusercontent.com/6978801/116006299-ec57e880-a60a-11eb-9eab-b86fbb73c9ab.png">

**Comment by a19nikbo** [comment]
Fixed
