### ISSUE TITLE
Diagram: Locking entities, relations and attributes in place.

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10380]
An option for elements that lock them into place, meaning that they can't be moved would be nice. So that you can not accidentally move an element. I suggest that this option is toggleable on multiple elements at once.

**Comment by HGustavs** [comment]
Low priority, until we finish the complete diagram basic functionality.

**Comment by a19steis** [comment]
Should all the elements be locked into place? or only specific elements. I.e chosen ones maybe?

**Comment by a19hammi** [comment]
> 
> 
> Should all the elements be locked into place? or only specific elements. I.e chosen ones maybe?

No, it should be an alternative in the properties for each element, just like name and type, as of now.
Having a key bind to lock would also be nice but that's for future changes.

**Comment by a19hammi** [comment]
fixed in #10666
