### ISSUE TITLE
Change the color of the toolbar to fit the LenaSYS color scheme

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10393]
We chose the same color for the toolbar as the options panel, but when embedded in a dugga it looks like a separate system. To make it fit the color scheme of LenaSYS we should change the toolbox color to a fitting shade of purple.

**Comment by a19chrel** [comment]
We should also use the defined varibles for the colors. That are defined in Shared/css/style.css

https://github.com/HGustavs/LenaSYS/blob/8b6deb54b26c44172bfcc3b10ac2ef3f84dc7417/Shared/css/style.css#L5-L47

**Comment by a19nikbo** [comment]
Fixed
