### ISSUE TITLE
Fix contrast issues in create announcement

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10405]
In create announcement, this text colours is not suitible with the white background. This colour needs to be changed to something more appropriate using the LenaSYS colour scheme which can be found here: https://github.com/HGustavs/LenaSYS/wiki/CodeViewer
![image](https://user-images.githubusercontent.com/81559946/116070393-db4fbb80-a68c-11eb-9666-64f79908937f.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
