### ISSUE TITLE
Pressing enter when an input field is focused should defocus the input field

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10400]
Pressing enter saves the changes to the properties of an element or line, and to be more clear about the success of this action we should defocus the text field when enter is pressed.

**Comment by a19steis** [comment]
We should also add the same display message as when we manually click "save".

**Comment by a19nikbo** [comment]
Yes, do that as part of this issue as well

**Comment by a19nikbo** [comment]
Fixed
