### ISSUE TITLE
Typo in old feedback

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10418]
"Old feedbacks" should be changed to "Old feedback" since the plural of feedback is feedback.  
![image](https://user-images.githubusercontent.com/81559946/116079149-c2003c80-a697-11eb-96e9-cb43a874fbfc.png)

**Comment by a19isada** [comment]
The same applies here: 
![image](https://user-images.githubusercontent.com/81559946/116079340-f70c8f00-a697-11eb-88af-6a3832f637d7.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
