### ISSUE TITLE
Add a success message when drawing a line between elements.

### ISSUE THREAD

**Issue by a19steis** [HGustavs/LenaSYS#10412]
Currently, when we try to draw a line between two entities we correctly receive an error message.

![image](https://user-images.githubusercontent.com/81557235/116075128-da218d00-a692-11eb-8cc1-1b9394e8abdc.png)

We should also display a successful message when we correctly draw a line between an entity and a relation / attribute.

**Comment by a19nikbo** [comment]
Fixed
