### ISSUE TITLE
Let teachers write feedback in LenaSYS and then send it to Canvas

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10426]
It would be nice to allow the teacher to write feedback while viewing the hand-in in lenaSYS and then have that feedback get sent to Canvas and shown as the hand-in feedback there. We could explore this possibility. It is important to not save any data in LenaSYS however.

**Comment by a16erilj** [comment]
How to test the code.
Visit showdugga.php as teachers (and students?) to check if feedback area is only shown to the teachers.

How to test commenting at the current state. 
- You need to have the secret in the correct place.
- Uncomment line 39 to 45.
- (Optional: change the comment at line 41 in testpage.php).
- Run testpage.php (The script will run each time the page is loaded).
- Login as Kristina Larsson at Canvas (It's possible to masquerade as Kristina Larsson through Admin also).
- Go to http://canvas.webug.his.se/courses/1/assignments/1?module_item_id=7 to check after the comment.

**Comment by a16erilj** [comment]
This assignment have been slit up to multiple smaller parts #10568, #10569, #10571 and #10578
