### ISSUE TITLE
Problem with primary key in table vers

### ISSUE THREAD

**Issue by b13alebr** [HGustavs/LenaSYS#1043]
The table vers has cid, coursecode and vers as primary key. Coursecode should not be part of the primary key because the coursecode of a course can be changed. The primary key will be unique with only cid and vers so it should not be a problem to remove coursecode as a part of the key. "unique" should be added to the column vers.

**Comment by a13karsi** [comment]
I'll take a look at this!

**Comment by a13oscwe** [comment]
@a13karsi do you have any news on this issue?

**Comment by a13karsi** [comment]
Didn't have time last week to get on this issue but I'll make sure to get to it today or tomorrow

**Comment by a13karsi** [comment]
Seems safe to remove coursecode from pk chain.
