### ISSUE TITLE
Move highscore functionality to localstorage

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10435]
Right now highscore is in a spot where it is impossible to make a highscore list without giving away personal information. We could however move the individual score to localstorage so that a user can view their own score on an assignment

**Comment by HGustavs** [comment]
Yes this is a good idea to test.

**Comment by b19ponka** [comment]
If the Hight Score is only connected to a submission through a hash, and is only compared to other High Score with the same hash (same persons score is listed). Is there still a need to store it locally? Furthermore, if the Hight Score is only displayed when a submission is passed and you can’t upload a new submission if it’s already passed. What is the need for a personal Hight Score? Some more detail about how this new Hight Score functionality is supposed to work, and for what purpose, would be much appreciated.

**Comment by a19rebsa** [comment]
The information that we got from the meeting with Henrik was that it is pretty useless to have a public highscore list with the hashes, but we could fix a highscore-list with personal highscore. That would make more sense.
