### ISSUE TITLE
Update the installer test-data inserts to comply with altered tables

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10434]
As we've changed several tables it would be nice to have the installer up to date as well.

**Comment by HGustavs** [comment]
I agree.

I suggest not doing this too often but one towards the half-time seminar and once towards the end of the course seems fine

**Comment by b18jacha** [comment]
> I agree.
> 
> I suggest not doing this too often but one towards the half-time seminar and once towards the end of the course seems fine

Should we keep uid or have uid as NULL?

**Comment by HGustavs** [comment]
Remind me, what does the uid do is it used in more than one location?

**Comment by b18jacha** [comment]
We are working in userAnswer and Submission, It's used to link the userID

**Comment by HGustavs** [comment]
If it is no longer used it is best to keep the column and set it to some value for example null, or UNK. This way if some module tries to read this information it does not crash.
