### ISSUE TITLE
Large void in sectioned in mobile view

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10430]
When in mobile view, this space takes up a large part of the screen which causes some of the names of the "duggor" to be cut off. This space can either be removed or shortened, depending on how it looks. 
![image](https://user-images.githubusercontent.com/81559946/116101302-03034b80-a6ae-11eb-8cd6-ccfbb6a39743.png)

**Comment by HGustavs** [comment]
Yes that seems like a bug.

Is it the same size if we add more tabs or is it just the first tab?

**Comment by HGustavs** [comment]
Ooops. Clicked on the close button by accident.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
