### ISSUE TITLE
Personal information stored in resulted.js/.php

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10443]
Currently the result editor for teachers looks like this
![resulted](https://user-images.githubusercontent.com/62884391/116211753-7061bb80-a744-11eb-888f-c1fe531ec5e7.png)

It's a smorgasbord of personal information, names, SSN's and so on. This should go away~

I don't know if we want to show these assignment results tied to hashes instead or just remove the functionality... start with removing the user-info either way.

In addition if there are queries made with personal information we should determine if these are needed or if the queries can be altered.

**Comment by HGustavs** [comment]
It should just contain a list of any saved assignments without personal information.

We need a way to see how many assignments that have been saved and at which date they have been saved.

This way we can resolve the situation if someon "forgets" their password or if we want an overview for number of submissions for an assignment.

**Comment by HGustavs** [comment]
It should be possible to see for example how many submissions have been made of assignment 1... and it should be possible for the teacher to visit that link to see the answer (without knowing which person that submitted that result).

**Comment by HGustavs** [comment]
Furthermore, if we get better interaction with canvas as a canvas module perhaps we need to store some information linking this information to canvas data.

**Comment by a18osken** [comment]
Since the current form is based so heavily on personal information I propose we remove its current implementation and make a new form that autofills with assignment hand-ins from a dropdown selection of assignments. The table could be something akin to this: 
![mockedup](https://user-images.githubusercontent.com/62884391/116253891-2d6a0d00-a771-11eb-9f78-367c52e7e320.png)
Maybe add a fifth column with a link to view the hand-in.

**Comment by a18osken** [comment]
I'm going to make new issues regarding the creation of this new form and its functions
