### ISSUE TITLE
Error Message using context instead of argument values

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10446]
Context[0] and Context[1] are not in all cases containing values and we have possible NullReferences when accessing this function and context is empty.

https://github.com/HGustavs/LenaSYS/blob/8b6deb54b26c44172bfcc3b10ac2ef3f84dc7417/DuggaSys/diagram.js#L1605-L1610

Would love one could also sneak in a change at this place and replace it with a call to `addObjectToLines(line)`! :)

https://github.com/HGustavs/LenaSYS/blob/8b6deb54b26c44172bfcc3b10ac2ef3f84dc7417/DuggaSys/diagram.js#L1599-L1603

**Comment by a19nikbo** [comment]
Fixed
