### ISSUE TITLE
Bind settings together into an object?

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10450]
I think we should move all user settings into an object for all settings to put all the data together.
This would make it easy to find setting names as well in editors since we could simply write the name of our settings object name and context highlight would display all available settings to change.

This would be a substantial improvement to looking through all our public variables one after one to look specifically for settings that should be changed by GUI or other events.

Example:

    diagramSettings.
        [  diagramSettings.useGridSnapping  ]
        [  diagramSettings.showGrid         ]
        [  diagramSettings.showRuler        ]

**Comment by HGustavs** [comment]
I am fine with this change as it allows us to save the settings in local storage (or together with the diagram).

Im thinking the zoom and view positions should be there also, so if we return to the page the view can then be saved  in local storage  (or with the diagram if we prefer that option).

**Comment by a19hammi** [comment]
fixed in #10691
