### ISSUE TITLE
URL hash can generate with slashes

### ISSUE THREAD

**Issue by e15marol** [HGustavs/LenaSYS#10457]
![Skärmklipp](https://user-images.githubusercontent.com/18677403/116232449-6fd41f80-a75a-11eb-828a-c0f10e0cbb81.PNG)

The URL hash can generate with slashes, which is something that should be avoided.

**Comment by HGustavs** [comment]
https://en.wikipedia.org/wiki/Base64#Variants_summary_table

I think you are not using a web safe variant of base64...

The "youtube" variant that we discussed using in some other issue does not use slashes see RFC 4648 §5

**Comment by a18osken** [comment]
We do have a replace function, but something with this hash seems to have broken it, slashes are to be replaced with underscores. I think because this hash had two slashes in a row perhaps? We must try to recreate this bug so that the function can be amended.

**Comment by a18osken** [comment]
Actually, looking at the code to generate the hash it seems we do not use the btoa() function which was advised, rebuilding the hash generation around this should solve this issue as btoa() is web safe base64.
