### ISSUE TITLE
Make line cardinalities zoom with the rest of the elements.

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#10455]
As it is now, the cardinalities of the lines will be the same size at all times independently of which zoom level the elements have. 

![Skärmavbild 2021-04-27 kl  11 57 48 (kopia)](https://user-images.githubusercontent.com/62895155/116225854-98f0b200-a752-11eb-80a7-cf3bd26218af.jpg)

![Skärmavbild 2021-04-27 kl  11 56 34 (kopia)](https://user-images.githubusercontent.com/62895155/116225874-9e4dfc80-a752-11eb-801b-23ebcbc925a1.jpg)

The cardinalities should zoom with the elements to prevent the diagram to look messy when zoomed out.

**Comment by HGustavs** [comment]
Use the same size as the size of the text in the attributes / entities etc

**Comment by a19nikbo** [comment]
Fixed
