### ISSUE TITLE
Maximum zoom-in always zooms to the same position

### ISSUE THREAD

**Issue by a19steis** [HGustavs/LenaSYS#10468]
When you zoom in fully the "camera" always ends up on the same position in the diagram, regardless of where the mouse pointer is located.

when the page is loaded
![image](https://user-images.githubusercontent.com/81557235/116251015-8c7a5280-a76e-11eb-9a2c-2cf7b1026845.png)

Zooming in with the scroll wheel when already fully zoomed in allows for an extra step that doesn't zoom any more but just changes the "camera" position.

![image](https://user-images.githubusercontent.com/81557235/116252241-ad8f7300-a76f-11eb-9f07-675870defc6c.png)

fully zoomed in after "extra" step
![image](https://user-images.githubusercontent.com/81557235/116251287-d3684800-a76e-11eb-892c-9785baeff361.png)

**Comment by a19hammi** [comment]
fixed in #10564
