### ISSUE TITLE
The position of the cardinality isn't when zooming

### ISSUE THREAD

**Issue by a19matma** [HGustavs/LenaSYS#10472]
When zooming, the position of the cardinality is not correctly offsetted.

![image](https://user-images.githubusercontent.com/81557380/116259258-f2b6a380-a775-11eb-829f-0cf19af0cf89.png)

**Comment by HGustavs** [comment]
Firstly the angle is greater on the right side of the line in this case, so it should be placed to the right of the line.
If the entity symbol was placed further to the right the opposite would be true and the symbol should be on the other side.

Also we want the position to be dependent on that angle, if the angle to the next line is small we should push the symbol out further to account for this "pinching" effect.

Thirdly, as is shown in this case the cardinality symbol should be at leas the height of the letter from the connecting point.

Fortunately, Vector math is very helpful here. We can make a unit vector of the line from the connection point and multiply this unit vector with the text height and line angle.

**Comment by a19nikbo** [comment]
Fixed, positioning depending on line angles is part of another issue
