### ISSUE TITLE
Missing data - groupdugga table needs to be added

### ISSUE THREAD

**Issue by e15marol** [HGustavs/LenaSYS#10477]
Currently there is a query to fetch data from groupdugga, which hasn't had its table created yet in the database. 

`[Wed Apr 28 09:52:39.468194 2021] [php:error] [pid 7248:tid 1816] [client ::1:62354] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lena1.groupdugga' doesn't exist in C:\\xampp1\\htdocs\\lenasys\\LenaSYS\\DuggaSys\\showDuggaservice.php:81`

**Comment by a18osken** [comment]
MySQL updates needs to be done locally to your environments database, if you go to `Lenasys/Shared/SQL` you will find a .sql file called `createTables`.  It contains the query to create the table. Make sure to be connected to your localhost database and have the correct default schema selected.
