### ISSUE TITLE
Returning to assignment hand-ins in Canvas

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10474]
It is currently unclear if we are to be able to return to our assignment hand-ins in the canvas iframe or if you'd have to use the hash to be redirected to dugga instead.

**Comment by HGustavs** [comment]
Im thinking that if one returns it could remember the hash in local storage together with the assignment variant?

**Comment by HGustavs** [comment]
When deeper integration with canvas has been achieved I imagine that this can be handled by canvas sending some kind of identifier.
