### ISSUE TITLE
Double clicking on an elements text area could be a shortcut to change the propertyname of the element. 

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#10480]
If double clicking on the text area it could be focused on the text input field in the option-pane to be able to change the name of the element in a faster way. This combined with the already implemented save and blur functionality when pressing enter after name changes would be a nice touch to the diagram.

**Comment by a19steis** [comment]
We are working on a solution that handles the amount of clicks that are registered so double click does not interfere with a single click.

**Comment by a19hammi** [comment]
fixed in #10604
