### ISSUE TITLE
Trying to move an element when a line is behind it cancels the movement and selects the line instead

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10486]
![issue_example](https://user-images.githubusercontent.com/81541557/116383829-84c2b880-a817-11eb-9e19-e671a2d38848.gif)

**Comment by a19chrel** [comment]
@a19hammi this issue should be closed, due to it is already fixed in #10538

**Comment by a19hammi** [comment]
fixed in #10538
