### ISSUE TITLE
Filter by assignment in resulted

### ISSUE THREAD

**Issue by a19rebsa** [HGustavs/LenaSYS#10496]
Right now in the view where teachers edit student results you can only filter by grades (see picture below). We want to be able to filter by assignments as well, so this filtering should be added. This could be done by a list or radiobuttons instead of a dropdown. 

![dropdown](https://user-images.githubusercontent.com/62889999/116400828-c6a92a00-a82a-11eb-8c24-6c04ff7da1aa.PNG)

**Comment by a19rebsa** [comment]
Mockup for how it could look with added filtering for filter by subcourse and assignment. 

![mockup2](https://user-images.githubusercontent.com/62889999/116881369-7a435d00-ac23-11eb-8df4-ba57828072b2.PNG)

**Comment by a13zanal** [comment]
Another mochup with radio buttons.
![Skärmbild 2021-05-03 153135](https://user-images.githubusercontent.com/62987694/116882229-7bc15500-ac24-11eb-8a26-803fc40096e7.png)

**Comment by a13zanal** [comment]
Another mockup with multiple.
![Skärmbild 2021-05-03 155533](https://user-images.githubusercontent.com/62987694/116885176-e0ca7a00-ac27-11eb-8d32-f6680a429261.png)

**Comment by a19rebsa** [comment]
Should we keep the "Mail students"-button? Feels like it's not necessary anymore when students should not log in to do assignments?
