### ISSUE TITLE
Create a new results table based on useranswer hashes

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10500]
The current resulted.js/php/services table shown below 
![resulted](https://user-images.githubusercontent.com/62884391/116406183-af6d3b00-a830-11eb-84fa-905d0d369774.png)
needs to be replaced with a table showing the following:
- Hand-In Nr - Really nothing to do with the hand-in itself, just number the entries in the table
- Hand-In Hash 
- Hand-In Password - gömd som default - klicka på show för att visa.
- Submitted Date
- Grade
- Hand-In link - for the teacher to view the hand-in

**Comment by a18osken** [comment]
It would also be cool to be able to sort on these things I guess, at least the submission date

**Comment by a19gusba** [comment]
Got some prototypes of how the new table could look like/function

![image](https://user-images.githubusercontent.com/62884429/116882244-811e9f80-ac24-11eb-83ff-944f5794a33c.png)

**Comment by a19gusba** [comment]
by clicking on the password blocker you can toggle between revealing and hiding the password

![image](https://user-images.githubusercontent.com/62884429/116882341-a6131280-ac24-11eb-8b60-1fdb046fc786.png)

**Comment by a19gusba** [comment]
Have also tried to implement two sorting functions that can sort by duggaName and date in case this new table doesnt cooperate well the the already exisiting sortabletable.

![image](https://user-images.githubusercontent.com/62884429/116882535-da86ce80-ac24-11eb-8f1e-ce1485937885.png)

**Comment by a19gusba** [comment]
Also tried adding basic sort/filer buttons

![image](https://user-images.githubusercontent.com/62884429/116885670-6fd79200-ac28-11eb-870f-d0548ec70bbb.png)

**Comment by a19gusba** [comment]
How do you want the filter/sort to work? Drop down, multiple selection buttons, radio buttons etc. Also what other sorting options should be added

**Comment by a17alfja** [comment]
![image](https://user-images.githubusercontent.com/81559713/116971040-4450b800-acb9-11eb-9755-eb551537afdb.png)

**Comment by a17alfja** [comment]
we are also working on a version that uses the sortableTable class, but we have some issues with filtering that needs to be fixed.

**Comment by a19gusba** [comment]
![image](https://user-images.githubusercontent.com/62884429/116986456-188bfd00-acce-11eb-9f7e-be2ffbbd708d.png)

Prototype completed. 

https://gyazo.com/ad1f921486789d010b983c2b8a6c7623

**Comment by a17alfja** [comment]
![image](https://user-images.githubusercontent.com/81559713/117256536-1bf8c300-ae4b-11eb-8dff-b0bffce9e93a.png)

**Comment by a17alfja** [comment]
![table](https://user-images.githubusercontent.com/81559713/117256716-4f3b5200-ae4b-11eb-8f8f-689935fe1591.png)

**Comment by a17alfja** [comment]
Prototype that uses sortableTable is complete. You can filter by assignment and subcourse in the drop down menu and sort by assignment and submission date.

**Comment by a17alfja** [comment]
Sorting:
https://gyazo.com/1058c9280906357725e17012c26572de
Filter:
https://gyazo.com/4fd7eb137650d62c3a5dc930ee4da34c
localstorage (both sort and filter are stored):
https://gyazo.com/a572b5354baf99b605e47ba58e7d9345
