### ISSUE TITLE
Who is the creator in listentries

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#10505]
It is a bit unclear as to who the creator is in listentries... truth be told we are not entirely sure exactly where listentries is used, but we need to figure out if it is a student or if it is a teacher, we can't save a student user id.
![image](https://user-images.githubusercontent.com/62884391/116409867-8c448a80-a834-11eb-911c-546f03b7506a.png)
As far as teachers go it would be alright to keep it around I guess.

**Comment by a19kevkh** [comment]
listentries are connected with a lot of other tables and we are still unsure when it is used. We are thinking that "uid" from the user table can be both teacher or student. But teachers might be the only users allowed to use listentries. If that is the case, then there might not be any need to change the table.

**Comment by a19frebo** [comment]
An entry in th elistentries table is created when a teacher adds a new "dugga" to a course. This means that only a teachers uid will be in the creator column.
