### ISSUE TITLE
If at least one element or line is selected, pressing escape should deselect all. If nothing is selected it should exit the current mouse mode

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10520]
Escape would work well as a "deselect all" key, but it's really clunky to have to go back to the mouse mode you're using every time you press it. We should detect if anything is selected and deselect everything if escape is pressed. If nothing is selected, it should go back to default mouse mode.

**Comment by a19hammi** [comment]
fixed in #10526
