### ISSUE TITLE
Diagram: While changed functionallity an parameter was forgotten

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10524]
When the commit [1d7f38a](https://github.com/HGustavs/LenaSYS/commit/1d7f38a86b68abc90982aefeedd8c5bdf180925e) was made, the parameter "stateMachineShouldSave" was forgotten to be included, this broke the stateMachine while pasting elements.

Currently when the user is pasting in elements with lines. The lines creation is saved as seperate states. And then the pasted state.

In the function `pastedClipboard()` it passes the secound parameter (stateMachineShouldSave) to `addLines()` with is never used in the function. Therefore the `addObjectToLines()` will go the the default state and save the state.
https://github.com/HGustavs/LenaSYS/blob/8d359a262a324883b2f53e39606b9602cd81dc53/DuggaSys/diagram.js#L3034-L3042

**Comment by a19hammi** [comment]
fixed in #10532
