### ISSUE TITLE
Remove/replace personal information from showdoc.php

### ISSUE THREAD

**Issue by a19rebsa** [HGustavs/LenaSYS#10535]
The file showdoc.php needs to be looked over for usage of personal information (data that can be tied to a student), not sure how this file is used so look through it and remove/replace the personal information where it's possible.

**Comment by a19arvka** [comment]
What counts as "personal information" in this sense? 
Don't worry, I have found some interesting segments of code in Showdoc.php that I will focus on. However, some pieces of code I am not sure about. For example, an 'uid' query is made to see if the signed in person is a teacher. 
I shouldn't remove that functionality right?

**Comment by a19rebsa** [comment]
A teacher should still be able to log in and so that functionality should not be removed

**Comment by a19arvka** [comment]
Is a filename considered personal information? By that I mean, making a query to find the filename of a file submission.
