### ISSUE TITLE
Student data still left in access editor

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10547]
In #9834 , the students were removed but it seems as data is still being sent to the page, it's just not displayed. This needs to be investigated and if it is being sent, it needs to no longer send it.

**Comment by b18phika** [comment]
We can confirm that student data is being sent to the client when accessing the access editor for a course. 

Note that the following screenshot doesn't show the entire list:
![image](https://user-images.githubusercontent.com/81557308/116697664-c55f3500-a9c3-11eb-9414-efc88c874c62.png)

**Comment by a18willi** [comment]
To follow up on what @b18phika posted, the information sent seems to specifically be of all students in the table "user_course" with a matching  "cid"  to the "courseid" in the url.
