### ISSUE TITLE
accessed.php - Adding a user gives error message and email is not saved in database

### ISSUE THREAD

**Issue by b13alebr** [HGustavs/LenaSYS#1055]
When a user is added you type in the user's email address, the first part before the @-sign is saved in the database as username but the complete email address is not saved at all, the column "email" in the database has null as value. Also when the user is created a pop-up windows says that the user does not exist.

**Comment by a13karsi** [comment]
Ah, we might need to add the @ character to the regular expression in dugga.js in  /shared

**Comment by a13chrju** [comment]
but it works to insert a @ into the database they just forgot to add the whole input field into the email attribute, I got it to work :)

**Comment by a13karsi** [comment]
Awesome, I just checked the regular expression did allow @ so no worries about that part!

**Comment by a13chrju** [comment]
fixed in https://github.com/HGustavs/LenaSYS/pull/1062
