### ISSUE TITLE
Last item created should have some indication

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10556]
Last item created should have some indication that it was the last created item. This could be by glowing or by flashing in some way. There can however be another better solution to this.

**Comment by b18phika** [comment]
Henrik suggested changing the color/icon/border for items that were created less than a week ago, so everybody can easily spot new items. Creating a few different ideas and asking others for their opinions might be a good way to find what works best. 
I'm not sure if the date at which an object was created is currently stored in the database. If it's not, that column should be added. 
If you decide to add a column it is very important that the code checks for null-values (which old items will have) so older courses still works.

**Comment by a19danla** [comment]
There is/was a function for this in earlier branches. Think that its related to returnedSection in section.js. If you search for glow there seems to be an function doing just this,
