### ISSUE TITLE
Make a template of an A4-sheet to the diagram.

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#10555]
It might be a good idea to make a button to be able to toggle the template on and off.

**Comment by a19vikth** [comment]
There is a few design options to the template. Im not sure which is the best.
1:
![al 1](https://user-images.githubusercontent.com/62886372/116993527-e2ec1180-acd7-11eb-99a6-4d26a56687ec.PNG)

2:
![al 2](https://user-images.githubusercontent.com/62886372/116993529-e384a800-acd7-11eb-8567-31b3f6c45509.PNG)

3:
![al 3](https://user-images.githubusercontent.com/62886372/116993530-e384a800-acd7-11eb-839d-91d5f1c970d5.PNG)

4:
![al 4](https://user-images.githubusercontent.com/62886372/116993531-e41d3e80-acd7-11eb-9242-d3fea6046f71.PNG)

**Comment by a19frelu** [comment]
In my opinion the 1:st example with the fully dotted frame combined with the background color of example 3 is the best way to implement the template of the A4-sheet. In this way it is clear what is covered by the sheet and what is not.

**Comment by a19hammi** [comment]
fixed in #10668
