### ISSUE TITLE
Remove the option to set cardinality to and from the elements that should not have it

### ISSUE THREAD

**Issue by a19steis** [HGustavs/LenaSYS#10554]
We should remove the option to set cardinality to and from a relation.

![image](https://user-images.githubusercontent.com/81557235/116673921-41e21b80-a9a4-11eb-879f-a9444a7562c9.png)

The end result should probably look something like this:

![image](https://user-images.githubusercontent.com/81557235/116674049-6fc76000-a9a4-11eb-828d-dcae55bc9896.png)

We should also remove the option to set cardinality to and from an attribute

![image](https://user-images.githubusercontent.com/81557235/116674123-8a99d480-a9a4-11eb-975e-d9cc66681df5.png)

**Comment by a19frelu** [comment]
My suggestion is that this issue is removed.
