### ISSUE TITLE
Newly created course adds items at the bottom

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10550]
When a new course is created, new items are added at the bottom of the page instead of in the middle of the screen. If you revisit the course after, it works as normal. This needs to be investigated.

**Comment by a19danla** [comment]
The fuctionality for placing newly created item in the middle of the screen there seems to be 2 issues.
The one mentioned above and a problem when there is more than 50ish items, mentionend in issue #10552.

We're currently looking into #10552 and might need to change the code abit which might solve this issue as well.

**Comment by a19danla** [comment]
This the same issue as #10552
