### ISSUE TITLE
Fab button covers edit buttons

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10551]
Currently, the fab button covers some of the edit buttons. The fab button needs to be moved a bit so that it doesn't cover them. 
![image](https://user-images.githubusercontent.com/81559946/116673474-bbc5d500-a9a3-11eb-9907-a5a0a466479f.png)

**Comment by b19wilfo** [comment]
@HGustavs Should we move the bottom fabbutton so it does not cover the deadline or is it ok that it just doesn't cover the edit button.
