### ISSUE TITLE
Create feedback area for teachers in their assignments at showdugga.php

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10568]
Currently there are no area where teachers can send send feedback to the student whom have done the assignment. So create an feedback area in showdugga.php that only the teachers may access and also looks good on Desktop and Mobile.

Sub issue of #10426

**Comment by a19rebsa** [comment]
How is this supposed to look like? Should this be in each dugga? Before the feedback was located in resulted.

**Comment by a19rebsa** [comment]
Also an argument for not placing the feedback area in each handed in assignment is that this feels like an extra step for teachers when they could give feedback more easily to many assignments via resulted

**Comment by a16erilj** [comment]
If you are talking about giving the same feedback to multiple  students at the same time then placing a text area for feedback resulted could be a good solution. 

Since we are talking about in individual submission so would it be nice to see the submission when commenting. So a feedback area in showdugga.php would be nice.

**Comment by a19rebsa** [comment]
Ok, so for this issue we only need to the the actual feedback area for the hand-ins and not the actual functionality for the feedback to be sent to canvas right?
