### ISSUE TITLE
Create a local instance of Canvas in Virtualbox in order to test the Canvas installation WIKI

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10579]
Currently there is an WIKI about how to install Canvas on the server. This WIKI should be tested in order to see if inexperienced canvas installers can use it.

This guide can be found here [How to install Canvas on Ubuntu v20](https://github.com/HGustavs/LenaSYS/wiki/Canvas-installation)

Virtual box requirements
- Change network setting in virtual instance to "bridged network"
- 4GB ram & 4 CPU cores
- 22GB SSD (HDD is alright but long install time)
- Patient

Ubuntu installation recommendation
- Swedish keyboard (US is default)
- Install the the SSH package (Allows you to ssh into Ubuntu with putty, which in turn allows you to copy paste)

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118964140-79226780-b967-11eb-84cb-8db18a01ad86.png)
Getting this error when running `sudo yarn install --pure--lockfile`

**Comment by a19simma** [comment]
`curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -`
needed to be run as sudo

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118970860-01f0d180-b96f-11eb-9b8a-28eb0fd4f791.png)
Bash was a bit confusing to write

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118972182-8ee85a80-b970-11eb-9bc6-bf74281bfaa6.png)
Does not prompt for information

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118973508-0a96d700-b972-11eb-960c-2e4675cca17a.png)

**Comment by a19simma** [comment]
`cp config/database.yml.example config/database.ymlpostgres`  postgres should not be there? got a file does not exist error

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118974389-11721980-b973-11eb-8f5a-2a1a252d7fd8.png)
permission denied un-rooted and running as root causes this error.

**Comment by a19simma** [comment]
Needed to run `sudo chmod -R 777 /var/www/canvas`

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118975518-5fd3e800-b974-11eb-81b2-761de46ede52.png)

**Comment by a19simma** [comment]
This is what the `pg_hba.conf` has been changed to
![image](https://user-images.githubusercontent.com/81557282/118975674-898d0f00-b974-11eb-9291-ee79359372f5.png)

**Comment by a19simma** [comment]
Success 
![image](https://user-images.githubusercontent.com/81557282/118992378-e09ae000-b984-11eb-9430-f9addb7971e5.png) 😃

**Comment by a19simma** [comment]
Wiki has been amended with notes for the issues I encountered.
