### ISSUE TITLE
Cardinalities can be hidden behind elements

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10575]
As of now cardinalities can be invisible if an element is placed on top of it. The cardinality should probably be pushed aside to make space for the element. If any other solution seems more fit feel free to go with that instead!

https://user-images.githubusercontent.com/81571224/116850609-3b94af00-abf1-11eb-8de2-a746def4a174.mp4

**Comment by HGustavs** [comment]
The cardinalities should be placed towards the end of the indicated side but can be pushed along the line if many cardinalities are in too close proximity. See issue #10577

**Comment by a19hammi** [comment]
fixed in #10622
