### ISSUE TITLE
Create a course that with assignments that can be used for testing (Group 1)

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10574]
We need a course that is linked to our Group 1 LenaSYS on the server for testing the integration between LenaSYS and Canvas.
- Create the course Webbutveckling - datorgrafik IT118G with a tag group 1.
- Create all the assignment that are in LenaSYS Webbutveckling - datorgrafik IT118G on our Canvas Webbutveckling - datorgrafik IT118G.
- Iframe the LenaSYS assignment from our [LenaSYS ](http://project-g1.webug.his.se) to Canvas assignment.
- It should be text submitted so that the student can paste the URL/hash and Password.

**Comment by a19kevkh** [comment]
Created course G1- Webbutveckling - datorgrafik.

**Comment by a19frebo** [comment]
Created all assignments for the course, and Iframed all assignments along with a text submission for each assignment.
