### ISSUE TITLE
Install SLL cerification on the server

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10576]
Web-browsers today complain about the connection being insecure when visiting a site without SSL. 

- Install the certification so the web-browsers stop complaining!!!

You can follow the wiki on LenaSYS [How to install SSL](https://github.com/HGustavs/LenaSYS/wiki/Getting-a-free-ssl-certificate-and-installing-it-when-not-having-access-to-port-80)

**Comment by a19frebo** [comment]
We could not install an SSL certificate so we changed all the IFrame links to http:// instead of https://.
