### ISSUE TITLE
Create Students and Teachers on Canvas for Group 1 

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10572]
As the other groups are also going to use Canvas so is it time for us to create Students and Teachers that are only for us.
- 6 Students
- 2 Teachers
- Give our users login the prefix g1

Also note down the password and usernames to our work/group folder (not Github!!!)

**Comment by a19kevkh** [comment]
Created 6 students and assigned them to the "webbutveckling-datorgrafik" course.

**Comment by a19frebo** [comment]
Created 2 teachers and assigned them as teachers to the "webbutveckling-datorgrafik" course. Also added all logins to a document on group 1's google drive.

**Comment by B18mohah** [comment]
Good work
