### ISSUE TITLE
Demo diagram

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#10577]
I have adapted a diagram from "Fundamentals of Database Systems" which has all of the necessary properties of an ER diagram.

I suggest we add a version of this diagram as our demonstration diagram. 

So that we are sure that we can draw any ER diagram.

**Comment by HGustavs** [comment]
<img width="615" alt="Screenshot 2021-05-03 at 09 41 31" src="https://user-images.githubusercontent.com/6978801/116851972-c2e32200-abf3-11eb-98d5-49037f01eef9.png">

**Comment by HGustavs** [comment]
I may update this diagram slightly to add more features and variants.

**Comment by HGustavs** [comment]
We can add screenshots here to showcase how close the current version of the system is to the goal diagram.

**Comment by HGustavs** [comment]
It would be very interesting to know how large the json data file is for this document when the demo model has been created.

**Comment by a19hammi** [comment]
fixed in #10617
