### ISSUE TITLE
Recursive relations should not allow connections to another element

### ISSUE THREAD

**Issue by a18nadma** [HGustavs/LenaSYS#10570]
![image](https://user-images.githubusercontent.com/49141885/116848134-3d0fa880-abec-11eb-98f0-99c81653f8d8.png)
You can still add a line to the default elements that already has a line.

**Comment by HGustavs** [comment]
Recursive relations should be possible but I am on the fence if we should support ternary recursive relations

**Comment by a19hammi** [comment]
In simpler words, **max** two entities connected to each relation.

**Comment by a19hammi** [comment]
Relevant #10619

**Comment by a19chrel** [comment]
Waiting for #10619 to complete this issue, this issue depends alot on the solution of that issue.

**Comment by a19hammi** [comment]
fixed in #11196
