### ISSUE TITLE
Add the option of using OAuth2 for autentication

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10584]
Currently so is the only option of using the API trough a static Master-key on the server side so we would like to add the option of using OAuth2 which is an client side verification for accessing the Canvas resources. 

Link to the [Canvas OAuth2](https://canvas.instructure.com/doc/api/file.assignment_tools.html)

**Comment by HGustavs** [comment]
Since we will not be given any information on the canvas server or modify anything, I think that this may be a solution that may be unworkable. So I would not prioritize this solution.

**Comment by a16erilj** [comment]
@HGustavs This was part of an URL API solution that used a Master-key. From what i have read so does OAuth2 not require a master-key. Instead so does it give each user that signs in the privileges they have on canvas. So it could be used for webscraping and commenting on the assignments. 

The main flaw with this solution is that the users are required to login to Canvas to get their temporary token.
