### ISSUE TITLE
Reset button in Rapport inlämning at showdugga.php does not work 

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10599]
Currently so does the reset button for "Rapport inlämning" nothing since it does not clear the uploads. As @HGustavs  mentions so mean that it's kinda deceptive. So removing the button would be for the best.

**Comment by HGustavs** [comment]
I say we can remove it since the functionality is kind of deceptive, it only clears the upload formm, and does not modify the uploads in any way.

**Comment by a16erilj** [comment]
Alright then we will change the issue to removing it.
