### ISSUE TITLE
Receiptbox - Remove the receipt numbers when saving a dugga

### ISSUE THREAD

**Issue by e15marol** [HGustavs/LenaSYS#10592]
We no longer need the generated receipt numbers, so these should be removed.

![Skärmklipp](https://user-images.githubusercontent.com/18677403/116863973-638f0d00-ac07-11eb-850f-eb0e05f65b7d.PNG)

**Comment by HGustavs** [comment]
The exclamation point "undefined" is for when the submission date has not been exceeded? We should probably remove that part if we are submitting early?
