### ISSUE TITLE
Fix the text distance in Rapport inlämmningen

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10594]
Current when uploading a pdf or zip file is the text distance not the same as titles.
Fix this.

**Comment by a19arvka** [comment]
Need a screenshot, can't recreate this bug in any way. I have tried on both Chrome and Firefox. I have also tried with a pdf containing max allowed characters

**Comment by a16erilj** [comment]
Have tried to recreate this issue to no wail. So we will close it for now
