### ISSUE TITLE
Individual delete button for each file uploaded in rapport inlämmning at showdugga.php

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10600]
There is no way to delete a individual file in "rapport inlämmning" showdugga.php. Add some buttons with the function to delete the connected file. 

This is includes individual files in zip uploads.

**Comment by b19ponka** [comment]
Also look at filerecive_dugga.php

**Comment by b19ponka** [comment]
Works great but, when presented to the customer, this was not a feature that they wanted
