### ISSUE TITLE
Fix indentation in Shared/style.css

### ISSUE THREAD

**Issue by a13denli** [HGustavs/LenaSYS#1060]
Weekly merge fix

**Comment by HGustavs** [comment]
Does the code standard contain definitions for css?

It is difficult to review this issue if there is no gold standard for indentation of css.

I suggest that the code standard is also updated to reflect.

**Comment by a13denli** [comment]
I can create a new issue for creating a code standard for css, but I already fixed this issue(before I saw your comment). I just needed to fix a few extra tabs here and there.
