### ISSUE TITLE
Missing weak key functionality 

### ISSUE THREAD

**Issue by b19phier** [HGustavs/LenaSYS#10618]
How it should look like in our demo
![image](https://user-images.githubusercontent.com/81567393/116887959-305e7500-ac2b-11eb-87a3-71273e753de2.png)

How it looks like without weak key
![image](https://user-images.githubusercontent.com/81567393/116887983-38b6b000-ac2b-11eb-9c62-1bc6e65a0804.png)

**Comment by a19hammi** [comment]
fixed in #10699
