### ISSUE TITLE
Lines should have different connection points on recursive relationships.

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#10619]
It would be easier to select the different lines and it also looks a lot better if the lines have different connection points as shown under. 

How it is now.

![Skärmavbild 2021-05-03 kl  16 36 11](https://user-images.githubusercontent.com/62895155/116890658-2722d780-ac2e-11eb-9dfa-66d2151e7610.png)

What it should look like. 

<img width="485" alt="Skärmavbild 2021-05-03 kl  16 36 35" src="https://user-images.githubusercontent.com/62895155/116890723-343fc680-ac2e-11eb-9d25-494118c1b857.png">

**Comment by a19matma** [comment]
True, it would look nicer, but getting this to work with our automatic repositioning on the lines when elements are moved around will be quite difficult. More discussion needed imo.

**Comment by a19frelu** [comment]
This question has come up for discussion again after the request has come from the customer to implement this.

**Comment by a19hammi** [comment]
fixed in #11198
