### ISSUE TITLE
Small fix needed so that determineLineSelect() doesn't alter original backlayer-values

### ISSUE THREAD

**Issue by a19matma** [HGustavs/LenaSYS#10621]
Currently the function determineLineSelect() alters the backlayer line ID's instead of just copying them when replace() is called. (This is my fault).
It's supposed to just store and manipulate the copied line and not the actual reference to the backlayer-lines.

Summary: The backlayer-line ID's shouldn't be altered, only the copy of them should!

**Comment by a19hammi** [comment]
fixed in #10634
