### ISSUE TITLE
Handle undefined hash in  showdugga.php

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10633]
Some times you can get the hash undefined, during these cases so is it required to clear the local storage in order for the assignment to work correctly again.

Create something that checks if the hash value is undefined and if it is undefined renew the hash in local storage for the assignment in question.

**Comment by b18jacha** [comment]
Can't replicate this undefined hash :(

**Comment by e15marol** [comment]
Can't replicate this issue, it might just have been a case where your database was not up to date.

**Comment by a16erilj** [comment]
Since it's not possible to replicate this issue so is it possible that it have already been solved or have a different activation then we thought. So we will close it for now
