### ISSUE TITLE
Visible highscore in Biträkningsdugga 1 & Biträkningsdugga 2

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10637]
Currently so is the high-score visible in Biträkningsdugga 1 & Biträkningsdugga 2. Remove it.
![bild](https://user-images.githubusercontent.com/81558891/116998337-598c0d80-acde-11eb-80a6-f6036dc16bad.png)

**Comment by a19gusba** [comment]
tried to get the same highscore output but couldnt find any way to do it. Probably already solved in another issue!

**Comment by a17alfja** [comment]
We couldn't get the high-score to appear no matter how we tried. This has most likely been resolved in another issue.

**Comment by a16erilj** [comment]
This issue have been most likely been solved since it no longer appears in our local nor remote instance. So I will be closing this issue down
