### ISSUE TITLE
Selected line looks different for the single line and double lines

### ISSUE THREAD

**Issue by a18nadma** [HGustavs/LenaSYS#10647]
Double lines:
![image](https://user-images.githubusercontent.com/49141885/117007062-7aa62b80-ace9-11eb-9f01-90c65464101f.png)

Single lines:
![image](https://user-images.githubusercontent.com/49141885/117007915-762e4280-acea-11eb-9cc0-aa9b040574f8.png)

the outline and selection looks different and would be best to keep the consistency if both have a line border or none of them have a border.

**Comment by a19nikbo** [comment]
This is because tempLines[0] is null when clicked. Probably because of how the ID handling is set up for double lines.

**Comment by a19frelu** [comment]
There is also a problem where the box surrounding the single line is kept around the single line even if you click in on a double line right after. 


https://user-images.githubusercontent.com/62895155/117010168-d0c89e00-acec-11eb-8937-aa0deacab889.mov

**Comment by a19hammi** [comment]
fixed in #10654
