### ISSUE TITLE
Create assignment in Canvas for the master branch

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10644]
Webbutveckling – datorgrafik assignements (Uppgifter) should look like G1 - Webbutveckling - datorgrafik assignements (Uppgifter). These assignments should be linked project.webug.his.se 

It should look like this 
![bild](https://user-images.githubusercontent.com/81558891/117006561-e340d880-ace8-11eb-8775-3a23a6934712.png)

**Comment by a19kevkh** [comment]
Created course MasterBranch - Webbutveckling - datorgrafik.

**Comment by a19frebo** [comment]
Created all assignments for the course, and Iframed all assignments along with a text submission for each assignment. Also added students and teachers to the course
