### ISSUE TITLE
Teachers do not get a variant when signed in

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10650]
Seems like teachers do not get any variants when signed in and visiting a dugga. So they are unable to get view the assignment in it's whole. Fix so that teachers are able to get an eagle-eye over their assignments. 

![bild](https://user-images.githubusercontent.com/81558891/117010823-7d0a8480-aced-11eb-8f0b-58003d6a36c1.png)

**Comment by a13zanal** [comment]
Maybe found another issue when we solved this issue. We get an error alert when we enter a saved url as a teacher. @a16erilj ?

![](https://cdn.discordapp.com/attachments/837266494047780877/839416969559670794/unknown.png)
