### ISSUE TITLE
There should be a way to see if a element is locked (visually)

### ISSUE THREAD

**Issue by a19aleda** [HGustavs/LenaSYS#10657]
<h3>This issue should not be worked on before issue https://github.com/HGustavs/LenaSYS/issues/10380 is complete and has been merged into the weekly branch.</h3>

Right now you can lock elements so that they can't be moved around, however there is no real way of telling if a element is locked or not. This should be fixed :)

**Comment by a19hammi** [comment]
fixed in #10703
