### ISSUE TITLE
style.css - .form-control and .textinput

### ISSUE THREAD

**Issue by b13alebr** [HGustavs/LenaSYS#1065]
The input elements with type text has the two classes "form-control" and "textinput" on the loginbox and in duggasys. The problem is that they have duplicates of some css styles, for instance "font-size" is set two times in "textinput" and one time in "form-control", this gives the input fields conflicts between three different font-sizes. It's the same thing with "border-radius". Maybe these two classes can be put together into one class without the duplicates?

**Comment by HGustavs** [comment]
There are __several__ unnecessary parts in the css.
My suggestion is to boil the css down to the bare essentials and to keep the styles as localized as we can i.e. there should be __one__ place for the css for each form control.
