### ISSUE TITLE
Create a pop-up window asks if the user wants to continue on saved hash or create new submission

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10660]
Currently so is there no list with previous visited hashes in each assignment. It would be great if a popup window that contains all locally stored hashes for the assignment pop-up window when visiting it.

Simply create a pop-up window that contains all visited hashes with dates and links for the assignment you are in.

**Updated description:** It would most likely be better with a would you like to continue on your saved issue or create a new one if a hash is already stored.

**Comment by b18jacha** [comment]
Won't this let users choose the easiest variant?

**Comment by a16erilj** [comment]
@b18jacha Good catch, This solution should maybe not clear the variant and refresh everything else? so that it's not possible to use create new submission for changing the variant.

**Comment by a18osken** [comment]
>Good catch, This solution should maybe not clear the variant and refresh everything else? so that it's not possible to use create new submission for changing the variant.

The Reset button does this already though. I am starting to question the necessity of this issue as there's no real need for a user to have the option to delete their submission when LenaSYS is made in such a way that the latest submission is always the one that is graded. 

Furthermore, when in a canvas iframe, the ability to navigate lenaSYS should be removed. Right now we already return to a locally stored assignment if the save button has been pressed. The user experience feels a bit cluttered as well if we are to have this popup then a log-in popup for password and so on...

This option to continue or start anew feels more and more redundant as  the functionality already seem to exist.

**Comment by a16erilj** [comment]
Seems like it's time to revive this issue since we are going to move load dugga button to the course meny. Which means that this solution would most likely be appropriate again.

**Comment by b18jacha** [comment]
@a16erilj If we start on a new one even tho something is in localstorage. We should get same variant right?

**Comment by a16erilj** [comment]
Yes you should use the same variant that is on the local storage the only thing that should change is the hash.

Here is a mockup how the popup could look like 
![bild](https://user-images.githubusercontent.com/81558891/118822027-145c0400-b8b8-11eb-8c77-39e4d662d65f.png)
