### ISSUE TITLE
Feedback error in Random clipping dugga

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10678]
For some reason so is the error Feedback is undefined present at only Random clipping dugga?
Check what it's about and fix it
![bild](https://user-images.githubusercontent.com/81558891/117124884-278bb180-ad99-11eb-8381-11a317863911.png)

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/117276515-448ab800-ae5f-11eb-8fed-eb40465fbcda.png)
Can't reproduce the error 😦

**Comment by a16erilj** [comment]
Since it have not been possible to reproduce this problem during our these last weeks so are it most likely fixed or extremely hard to reproduce since we have done many changes since then.

So I will be closing this issue down
