### ISSUE TITLE
noUploadForTeacher error is present att almost all assignments

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10675]
The error noUploadForTeacher is show at all assignment when signed in as teacher expect Rapport inlämning which it most likely was crated for. Fix it so that the error noUploadForTeacher disappear. 

![bild](https://user-images.githubusercontent.com/81558891/117123952-fc549280-ad97-11eb-9528-947e25371b37.png)

**Comment by b19ponka** [comment]
As of now, noUploadForTeacher-function only exists in generic_dugga_file_receive.js, which Rapport inlämning is based on.
