### ISSUE TITLE
Selected elements should be on top of other non selected elements. 

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#10677]
As it is now, the selected element/elements are not always in the top of the stack of elements. Same thing with the dotted line around the selected elements.

![Skärmavbild 2021-05-05 kl  11 40 22](https://user-images.githubusercontent.com/62895155/117124048-1f7f4200-ad98-11eb-9351-59d73f880044.png)

**Comment by a19hammi** [comment]
fixed in #10711
