### ISSUE TITLE
Hidden items do not show up on swimlanes after made public again

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#10687]
If you hide an item, it disappears from the swimlane, as it should. But when you make it public again, it does not show up on the swimlanes. This needs to be fixed.

**Comment by b19wilfo** [comment]
When testing we have found that the duggor that are shown in the swimlane are all assigned a "moment" which is a number, but when we add a new dugga they are not assigned a "moment" and are therefore not shown in the swimlane. The same goes for items that are hidden and then made public again, they lose their "moment" number and can therefore not be shown. We are trying to find out why this occurs.

Co-author: @a19danla

**Comment by b19wilfo** [comment]
The problem was template literals in sectioned.js that had not been implemented properly.

Co-author: @a19danla
