### ISSUE TITLE
Search after cause of visiblity error pop-window

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10695]
The programmers in #10656 found something called "error reading dugga visibility". Search after what causes it and fix it if possible.
![bild](https://user-images.githubusercontent.com/81558891/117154823-87478400-adbc-11eb-8368-e3e9095a58bf.png)

**Comment by a19rebsa** [comment]
This error pops up when you are logged in as a teacher and you're visiting an already handed in assignment. Going to look in to what causes it.

**Comment by a19rebsa** [comment]
Couldn't really solve the issue with preventing this type of "error" to occur. Showduggaservice is called an extra time when logged in as a teacher and going to an already handed in assignment. Do not know why, but the third time showduggaservice runs this problem happens. Nothing else in the dugga is affected by this error the third time tho... We did a fix in the mean time for not getting this alert.
