### ISSUE TITLE
Figure out why uploading files does not work for Rapport inlämning in Ubuntu environment

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10704]
For some reason so does uploading files to the server not work. Figure out the reason why and try to fix it.

It's currently believed that it have something to do with invalid file paths.

**Comment by a19simma** [comment]
10.0.2.2 replaces localhost when testing from VM. Could be useful in the future.

**Comment by a19simma** [comment]
Moving over to the new weekly merge makes the upload inaccessible, will check for solutions tomorrow.

**Comment by a19simma** [comment]
@a16erilj Well, I don't know what the weekly merge did, but it works fine on my ubuntu vm now without any changes.
![image](https://user-images.githubusercontent.com/81557282/118258002-9eb6f900-b4af-11eb-90e2-dac05d2312c7.png)

**Comment by a19simma** [comment]
Unless I missunderstood the problem?

**Comment by a16erilj** [comment]
Intressent, from our testing on the live envoriment at http://project.webug.his.se and http://project-g1.webug.his.se so didn't uploaded files become listed. How are you running LenaSYS in your Ubtunu environment?

**Comment by a19simma** [comment]
You're right, uploading on the live version does not work. This is the case for uploading from both windows and linux clients however.

**Comment by a19simma** [comment]
Setting up an ubuntu server on VM, installing git etc for test environment.

**Comment by a19simma** [comment]
Getting some "Failed to connect to the database" after installtion

**Comment by a16erilj** [comment]
Have you gotten around this problem?

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118652934-5bc68f80-b7e7-11eb-9c4c-5cd20f83b970.png)
Continuing on it's a problem with installing the extensions. Working on it.

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118654228-a09ef600-b7e8-11eb-9c9b-e34de0f0dad1.png

apparently php7.4-obdc wasn't installed.

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118659438-99c6b200-b7ed-11eb-9e45-ee260ab1e369.png)
Got git bash working. Had to learn it 😛

**Comment by a19simma** [comment]
Same problem as the live server, file does get selected when attempting to upload.

**Comment by a16erilj** [comment]
I see, the question is then what is causing the problem?

Those that found the problem said it was most likely a path issue since paths in Linux and Windows are written in can be written in different

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118669942-77856200-b7f6-11eb-8331-a34c6b82bb16.png)
Getting this error message occasionally

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118672714-bf0ced80-b7f8-11eb-912a-82607572df8b.png)
Uploading seems to work fine

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118680279-e36bc880-b7fe-11eb-925c-4043c2c39e0a.png)
after removing uid it seems to solve the database problem. Getting another error now

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118684009-22e7e400-b802-11eb-899a-a92327f21e5b.png)
Upload is working, but getting this error instead

**Comment by a16erilj** [comment]
Interesting that the upload works while you are getting a 500 error, since it would indicate that it was unable to fulfil the request.
[Error 500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500)

**Comment by a19simma** [comment]
Yes, the ajax call is breaking 
![image](https://user-images.githubusercontent.com/81557282/118797957-64799d00-b89d-11eb-80ea-a3be1404bb12.png)

**Comment by a19simma** [comment]
reverted everything and getting the same error now still, so it's the AJAX call, probably not getting the PDUGGA param from the POST 
![image](https://user-images.githubusercontent.com/81557282/118799865-88d67900-b89f-11eb-89d7-6fe454bda698.png)

**Comment by a19simma** [comment]
The really funny thing is how this isn't a problem on windows at all...

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118804226-b5d95a80-b8a4-11eb-8562-b6a99b608415.png)
windows seems to have a similar ajax call but it doesn't throw an error

**Comment by a19simma** [comment]
What the Linux ajax call seems to be missing:
Deadline field
Release Field
FILES is empty, which contains the information of which files to display on reload.
isFileSubmitted is true on Windows but false on Linux
Variants field is empty on Linux but has values on Windows

**Comment by a19simma** [comment]
Adding an upload tmp directory did not fix the issue.

**Comment by a19simma** [comment]
Going to try to update php to 8.0 on the server

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/118830117-fcd44980-b8be-11eb-9b5a-92b8bbf35d3e.png)
zip-archive wasn't downloaded on the server. It works now 

![image](https://user-images.githubusercontent.com/81557282/118830185-0958a200-b8bf-11eb-8bf9-796426b19f1c.png)

**Comment by a19simma** [comment]
@HGustavs 😠
