### ISSUE TITLE
Diagram: Keybinding for stepForward()

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10719]
There is currently a keybinding for `stepBack()` that takes us back in the history. An keybinding should also be added to  `stepForward()` function in the stateMachine.

**Keep in mind:** The `stepForward()` has not been added yet, still awaits review - pull-request (#10716 ).

**Comment by a19matma** [comment]
Awaiting bugfix with regards to ctrl+z.
https://github.com/HGustavs/LenaSYS/issues/10739

**Comment by a19matma** [comment]
Apparently this has already been solved

**Comment by a19hammi** [comment]
> 
> 
> Apparently this has already been solved

@a19chrel ?
