### ISSUE TITLE
Diagram: Buttons in the tool-bar for stepBack() and stepForward for the stateMachine

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10718]
Currently there is only a keybind for stepBack() to access the functionallity to move backwards in the history. There should be added something like buttons in the GUI so the end user can find this functionallity. This should be added for both stepBack() and stepForward() so the user can navigate through the history.

The buttons should also contain tool-tip with the coresponding keybinding.

**Keep in mind:** Currently there is no key-binding for stepBack()

**Comment by a19hammi** [comment]
fixed in #10773
