### ISSUE TITLE
Find the cause for split is undefined and fix it

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10721]
Some programmers get the error split is undefined. Find the cause for it and fix it.

**Comment by a19simma** [comment]
The feedback field was undefined. added a check if it's undefined before it does operations on the field.

**Comment by a19simma** [comment]
![image](https://user-images.githubusercontent.com/81557282/117278562-29b94300-ae61-11eb-925d-e40bbf482cac.png)
no errors
