### ISSUE TITLE
Login: After loading a hash url

### ISSUE THREAD

**Issue by e15marol** [HGustavs/LenaSYS#10720]
When you load a hash url to login for a saved dugga, if you can't or wont enter the password and simply click away the popup, you can not from there login using the login button in the topright corner.
![Skärmklipp1](https://user-images.githubusercontent.com/18677403/117275981-e362e480-ae5e-11eb-8d29-75bf5b5e277a.PNG)
![Skärmklipp2](https://user-images.githubusercontent.com/18677403/117275991-e65dd500-ae5e-11eb-998e-38132f062ac4.PNG)

**Comment by a16erilj** [comment]
Seems like something that should be checked and if it can be replicated so should it be fixed.

**Comment by b18jacha** [comment]
Since the popup login menu will be removed from canvas we are trying to redirect to original dugga page instead.
