### ISSUE TITLE
Be able to resize and move the A4 representation

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10732]
It's difficult to fit a larger diagram within the A4 representation.
Since the size of an A4 is about the ratio between the width and height, as long as you multiply the two dimensions by the same factor it should still be accurate.

![image](https://user-images.githubusercontent.com/81541557/117298125-4b252980-ae77-11eb-9804-3a9be2e7074a.png)

**Comment by a19nikbo** [comment]
@a18nadma 
Not sure if moving the representation should be a separate issue or part of this one.

**Comment by a19hammi** [comment]
fixed in #11036
