### ISSUE TITLE
Right-clicking when adding elements bug.

### ISSUE THREAD

**Issue by a19karwa** [HGustavs/LenaSYS#10730]
Currently you can place out elements by right clicking, doing so will make the default right-clicking dropdown menu to pop out, perhaps we should change so that you cannot place out elements by right clicking?

![image](https://user-images.githubusercontent.com/81557429/117297181-34ca9e00-ae76-11eb-9bf7-bc9dcb0d825b.png)

**Comment by a19hammi** [comment]
fixed in #10780
