### ISSUE TITLE
Demo course

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1073]
I suggest adding some information from a "real" course to test the dugga and code viewer systems.
The most advanced and varied course that uses the "old" version is "shaderprogrammering".
If the shaderprogrammering course can be entered into the system and if navigation works for that course we are very close a working system.
[Shaderprogrammering 2015](http://wwwlab.iit.his.se/gush/Shaderprogrammering/)

We cannot be sure that everything works as intended if we do not add real data as example content.

The testing data in the database/code examples right now is too limited to test if the course content works as we want it to.

**Comment by c13caral** [comment]
We have now implemented real code examples in code viewer.

**Comment by a13oscwe** [comment]
We have semi-real code examples for duggasys as well but we have not added "shaderprogramming"

**Comment by HGustavs** [comment]
It would be great if we could add just a few (one or two?) examples from shaderprogrammering as it has significantly different content, with webgl code highlighting and iframes in content boxes.

**Comment by a13alfbe** [comment]
Will this be possible to achieve when we are in a "feature-freeze"? Doesn't this require some additional implementations to work properly?

**Comment by c13caral** [comment]
this is now solved in code viewer :+1:

**Comment by a12majca** [comment]
testdata for duggasys is added now.

**Comment by a13arnhe** [comment]
Old issue concerning testing of the new system. If testing of specific functions are needed now, a new issue more specific to todays development should be created.
