### ISSUE TITLE
Changes to snap-to-grid functionality

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10749]
Entities should snap according to the squares in the grid, other elements should snap to half a square.

Both of these examples are acceptable snapping points

![unknown (2)](https://user-images.githubusercontent.com/81541557/117305671-46647380-ae7f-11eb-9567-064158bb349f.png)
![unknown (3)](https://user-images.githubusercontent.com/81541557/117305710-4feddb80-ae7f-11eb-8b45-09c30bb6ea29.png)

**Comment by a19hammi** [comment]
fixed in #10903
