### ISSUE TITLE
Retiring old code viewer issues.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1074]
I think that old issues such as  #164 can be re-tested and retired if no longer relevant.....

This also applies to issues such as #162 and #169

**Comment by a13jorla** [comment]
Issue #164 is a closed issue but when looking at it i wonder if the new studens have altered the funktion of these buttons. So maby we should have a relook on it.

**Comment by c13caral** [comment]
We have looked at the issue to see if we could found more issues that is out dated och no longer relevant. We have closed the issue that is no longer relevant. And we are going to time to time check the issue so all of them is relevant and not out dated

**Comment by HGustavs** [comment]
I consider this issue as done.
