### ISSUE TITLE
Move copy paste into local storage 

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#10752]
Copy-Paste should be moved into the browser local storage where save states for each diagrams should be able to have their own settings & copy-paste-clipboard stored.

**Comment by a19matma** [comment]
Possible bug in main: Move an element, copy it with ctrl+c, then paste it resulting in fault in save state in statemachine:
![image](https://user-images.githubusercontent.com/81557380/117657813-4f648600-b19a-11eb-8330-4fd7283233c2.png)

**Comment by a19hammi** [comment]
fixed in #10951
