### ISSUE TITLE
A submitted file without any files in it should be able to be hidden by teachers

### ISSUE THREAD

**Issue by a19anjst** [HGustavs/LenaSYS#10758]
Unintended submitted files should be able to be hidden by teachers (resulted.php). They should be able to be hidden manually one by one.

**Comment by b18phika** [comment]
This also applies to other types of "duggor" not just where files are supposed to be uploaded.

**Comment by a19isada** [comment]
This issue should make it impossible to save an empty "dugga" #10706 and therefore teachers should not have to hide them

**Comment by b18phika** [comment]
@a19isada I'm not sure, but I think it'd be good to also have the ability to hide just partially completed "duggor", which aren't ready to graded, although you should be able to save them.
