### ISSUE TITLE
HTML document type

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1075]
In some of the courses, html pages are used as content.
Do we have support for displaying and uploaded html documents?

I thought there was an issue about this.. but I could not find it among the previous issues.

For example:

http://wwwlab.iit.his.se/gush/Shaderprogrammering/Ex17/Ex17.htm
http://wwwlab.iit.his.se/gush/Shaderprogrammering/Ex18/Ex18.htm

**Comment by c12jenek** [comment]
Displaying html pages is possible, uploading is not yet implemented

**Comment by HGustavs** [comment]
There is a difference between showing html code and showing a web page.

**Comment by a13jorla** [comment]
By using the play button you can see how the html page looks like. But you can also put a html page in one box and see how it looks there. Is that an answer to your question @HGustavs .

**Comment by HGustavs** [comment]
is that with an iframe?

**Comment by HGustavs** [comment]
... or by including the html directy?

**Comment by HGustavs** [comment]
what does the menu look like for choosing the html file? I did not see it yesterday when the system was demoed for me....

**Comment by HGustavs** [comment]
If this has been implemented I think we can close this issue.

**Comment by c13caral** [comment]
We have added iframe and the kind is kalled preview

![skarmavbild 2015-05-26 kl 14 01 42](https://cloud.githubusercontent.com/assets/11715450/7812129/df8efc0a-03af-11e5-91c4-2e8e593d1b0f.png)

**Comment by c13caral** [comment]
I am sorry I forgot to show you when you were here

**Comment by a14jimso** [comment]
I have tested this, and it is possible to either display the code with the type code, or to display a preview of the page by choosing preview.
