### ISSUE TITLE
Bug: Deleting an element while using line tool.

### ISSUE THREAD

**Issue by a19matma** [HGustavs/LenaSYS#10767]
If the line tool is chosen, and an element is selected, pressing delete/backspace will cause a visual bug where the "ghost line" as well as the selection box for the deleted element remains present, and "stuck" until another tool is chosen.
![image](https://user-images.githubusercontent.com/81557380/117326024-8fbdbe80-ae91-11eb-970a-892eaef2f332.png)

**Comment by a19nikbo** [comment]
It's not really a visual bug considering it produces the error:

> Uncaught TypeError: Cannot read property 'cx' of undefined

And panning with the middle mouse button while this is happening causes all lines to have a fixed position on the screen.

**Comment by a19vikth** [comment]
I think it make sense to only be able to delete lines when in line creation mode

**Comment by a19hammi** [comment]
fixed in #10837
