### ISSUE TITLE
CodeViewer: Did not work from master, cause was unknown, error handling and debug needed

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#1076]
CodeViewer code works on the weekly link;
http://webblabb.iki.his.se:8080/codesys/cv18/CodeViewer/EditorV50.php?exampleid=1&courseid=1&cvers=2013
however not from the master
http://webblabb.iki.his.se:8080/master/CodeViewer/EditorV50.php?exampleid=1&courseid=1&cvers=2013
Seems to be a database fault/mishap/unconsistency, could quite possibly be more underlying issues but unsure as debug and error handling is very sketchy indeed

**Comment by HGustavs** [comment]
The code below does not work if retdata['before'] is null.
```
TypeError: retdata.before is undefined
if(retdata['before'].value!=null&&retdata['after'].value!=null){
```
This code needs to work even if a we get an error from the service.....

Perhaps `retdata['before']!=null` works better?

**Comment by HGustavs** [comment]
While were at it... it would be nice if we could see the row number in the debug information e.g. printing a magic constant, or at least __LINE__ as part of the error message to give more information to the person that is debugging.
```
__LINE__ 	The current line number of the file.
__FILE__ 	The full path and filename of the file with symlinks resolved. If used inside an include, the name of the included file is returned. 
```

**Comment by c12jenek** [comment]
init_db.sql in this week contains none of our inserts, create a file which does this

**Comment by b12simsa** [comment]
#1359 Subissue for 'retData['before'] = null' crash.

**Comment by a13jorla** [comment]
We have broken down this issue in sub issues and are now closing this issue.
