### ISSUE TITLE
Bug: pasting a copied element while moving another

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10768]
This is the error you get, and a lot of other subsequent errors as well.

![image](https://user-images.githubusercontent.com/81541557/117331096-b03c4780-ae96-11eb-8d81-9d42e484e815.png)

How to reproduce:
**1. Copy an element
2. Move an element
3. While still moving the element, paste the copied element**

**Comment by a19karwa** [comment]
Close issue?
