### ISSUE TITLE
Make element resize node resize depending on zoom

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10772]
Right now they're very large when zoomed out and very small when zoomed in:

![image](https://user-images.githubusercontent.com/81541557/117337319-84709000-ae9d-11eb-8d16-8cd41b031f11.png)

![image](https://user-images.githubusercontent.com/81541557/117337266-7753a100-ae9d-11eb-816b-610197bc2ca1.png)

**Comment by a19hammi** [comment]
fixed in #10814
