### ISSUE TITLE
Exam where we should add teachers to superuser rows

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10781]
Currently so have we wrongly assigned some permissions to superusers only. Check what superuser permission rows that should possibly be changed into teachers rows, note them down and (change them where it's appropriate).

A tip would to check with github to see what our Group 1 have changed compared to the old LenaSYS

**Comment by a19rebsa** [comment]
Where are we supposed to make these changes? What actions and parts of the site should only superusers have access to? And vice versa with teachers?
