### ISSUE TITLE
Move function noUploadForTeacher() to dugga.js from generic_dugga_file_receive.js

### ISSUE THREAD

**Issue by b19ponka** [HGustavs/LenaSYS#10786]
As noticed by one of our developers: 
"Maybe the function noUploadForTeacher() should be in dugga.js instead?" @b18jacha

**Comment by b19ponka** [comment]
Take a look at previous issue #10675 solution (pull req #10774) and see if something needs to be reverted

**Comment by e15marol** [comment]
There is no need for the noUploadForTeacher function to be elsewhere other than in the template for reports (generic_dugga_file_receive because it is the only assignment where you can upload. I would recommend closing this issue.

**Comment by a16erilj** [comment]
If this is the case then we will close this issue
