### ISSUE TITLE
Diagram: stepForward trys to restore state that does not exists.

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10789]
There was an bug that was added with the stepForward(), the statement in the beginning of the functions does not work correctly.

Currently the statement is this.
https://github.com/HGustavs/LenaSYS/blob/4de8a3ca1403d7e1d408765887e702073927dce5/DuggaSys/diagram.js#L474

Should be something like this
`        if (this.historyLog.length == 0 || this.currentHistoryIndex == (this.historyLog.length -1)) return;`

**Comment by a19hammi** [comment]
fixed in #10847
