### ISSUE TITLE
Install speed-grader and check if it support Iframes

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10784]
Our teacher uses speed-grader to check the grades and a quick way to implement LenaSYS into speed-grader would be through iframes so check if it would be possible to have iframes inside speed-grader.

Smaller part of #10762

**Comment by a18osken** [comment]
Speed grader comes pre-bundled with canvas. The test environment we have for canvas does not support the built-in doc-viewer of Speed grader but that would not matter. It does not natively support iframes but it seems quite plausible to hijack the assignment body through a javascript injector such as greasemonkey, this will be explored in issue #10775
