### ISSUE TITLE
Entering an incorrect hash when loading a dugga

### ISSUE THREAD

**Issue by e15marol** [HGustavs/LenaSYS#10813]
Entering an incorrect hash when loading a dugga leads to a 404 page with a hyperlink that leads to nowhere, either handle this by warning that the hash is not in the database or something similar to give feedback to the user.
![Skärmklipp1](https://user-images.githubusercontent.com/18677403/117446572-8d646e80-af3c-11eb-97b9-85e1c22dc807.PNG)
![Skärmklipp2](https://user-images.githubusercontent.com/18677403/117446598-93f2e600-af3c-11eb-9669-71a4c2b49d23.PNG)

**Comment by b18jacha** [comment]
Maybe same solution as #10808
