### ISSUE TITLE
Document how teachers are added in LenaSYS

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10820]
Some documentation about how teachers are added into LenaSYS would be great. So search for how they are added and document this down.

**Comment by c20adael** [comment]
Take a look at if some documentation has been done or if we still need to do this.

**Comment by b20hanwa** [comment]
A guide is created for how to add users to LenaSYS, this guide can be found in the LenaSYS Wiki.

The guide: [Guide](https://github.com/HGustavs/LenaSYS/wiki/Adding-users-to-LenaSYS).

**Comment by a20behta** [comment]
Looks good, clear file name and instructions shown.
