### ISSUE TITLE
Frågedugga 1 saving the dugga unchecks the answer

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10825]
Frågedugga 1 when saving the dugga so is the answer unchecked. Fix this
![bild](https://user-images.githubusercontent.com/81558891/117626465-6a71ce80-b177-11eb-823d-44c1280d69fb.png)

**Comment by a19gusba** [comment]
since the way this dugga is saved is quite different from other duggas we had to create a new functionality to get the old answer and display it
