### ISSUE TITLE
Explore the mobile view for our group files (G1 Canvas)

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10824]
Mobile is today a huge market so it's possible that some users will primary use a mobile to do their assignments. Check with you phones with the most popular web-browsers (Chrome, Safari, Firefox, Opera and Samsung internet) to look after oddities and things that would need to improve (Small buttons, things that disappeared that are needed and so on) for all our assignments in Canvas.
This is about G1 - Webbutveckling - datorgrafik in Canvas

Note these things down into this issue.

**Comment by a16erilj** [comment]
Also make screenshots for each problem... otherwise it will be impossible to judge the severity of the issue and also to compare to when fixed.

**Comment by a20behta** [comment]
issue has not been updated since 2021. vauge, never mentioned 
closing issue
