### ISSUE TITLE
Make handle hash great again

### ISSUE THREAD

**Issue by b19ponka** [HGustavs/LenaSYS#10830]
Handle hash function is not being used correctly

**Comment by HGustavs** [comment]
If we are talking a several-character base64 hash... a colision would be very very improbable.... if it works for youtube I think we can be fairly sure it is enough for our use case. As long as the length is suitable e.g. 2 characters in base 64 may result in a colision but 6 or eight characters will most likely never happen even on youtube.

**Comment by a19arvka** [comment]
I will still try to fix this. We looked up the odds, it's 1 : 5 000 000 000 to get the same hash **under the circumstance that the system and database works correctly**. However, we need to consider what could happen if there was a fault in the database. An SQL injection for example? If we don't have a second method checking the validity of a randomly generated string any server/database faults could lead to loss of data and incorrect error message being printed to a student.

**Comment by a19arvka** [comment]
I managed to fix it. No functionality was changed. I just added more conditions to differentiate a hash generation collision from just re-saving a dugga.
