### ISSUE TITLE
Add text description to dropdown menu on mobile phone

### ISSUE THREAD

**Issue by a19anjst** [HGustavs/LenaSYS#10836]
![Skärmbild (375)](https://user-images.githubusercontent.com/62884743/117644002-4dde9200-b189-11eb-8b76-5f7977453b13.png)

**Comment by a19isada** [comment]
Do you mean making the menu wider and adding text next to the icons?
@a19anjst

**Comment by a19isada** [comment]
This is how i interpret it to kind of look like, with the text added next to the icons. Is this the idea of what it should look like?
To me this looks rather big and clumsy, but if it's your call @a19anjst 

![image](https://user-images.githubusercontent.com/81559946/117649456-d4966d80-b18f-11eb-8674-d6b6df6ed7e4.

**Comment by HGustavs** [comment]
Yes that would work
roughly the same size of the text as Färgduggor 1HP
