### ISSUE TITLE
A4 horisontal 

### ISSUE THREAD

**Issue by a19karwa** [HGustavs/LenaSYS#10846]
Currently you can toggle an a4 template, perhaps it would be useful to have an horisontal a4 template aswell in the toggle?

![image](https://user-images.githubusercontent.com/81557429/117660596-a881e900-b19d-11eb-9bf2-e8bef4247b39.png)

**Comment by a19steis** [comment]
Do we want a vertical A4 and a horizontal A4 sheet to both show up upon toggle?

or do we want seperate toggles for each?

**Comment by a19hammi** [comment]
fixed in #10919
