### ISSUE TITLE
Pressing (ctrl + Y) one to many times will freeze the whole page

### ISSUE THREAD

**Issue by a19karwa** [HGustavs/LenaSYS#10847]
If you make some changes, and press ctrl + y one to many times the whole page will freeze. 
![image](https://user-images.githubusercontent.com/81557429/117661401-9c4a5b80-b19e-11eb-8bb0-b470f09a6703.png)

Video of page freezing:

https://user-images.githubusercontent.com/81557429/117661974-5346d700-b19f-11eb-9024-db0f800769e3.mp4

**Comment by a19chrel** [comment]
This issue should already be solved in #10789 and i can't replicate this problem. Should be nice if @a19karwa could check if this problem still exists.

**Comment by a19karwa** [comment]
Yes, this was fixed after the issue was created. This issue can now be closed as it is fixed. @a18nadma

**Comment by a19hammi** [comment]
fixed in #10791
