### ISSUE TITLE
Save and Reset button won't be enabled in Frågedugga, Random css dugga & Random clipping dugga

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10844]
For some reason so does the Save and Reset buttons not become enabled in Frågedugga, Random css dugga & Random clipping dugga when the student interacts with the dugga. Checkout why and fix it if possible

![bild](https://user-images.githubusercontent.com/81558891/117656665-e8929d00-b198-11eb-86af-0d22c93e15f6.png)

**Comment by a16erilj** [comment]
Not that they have become disabled. Rather that they won't become enabled after the student have interacted with the dugga. 
The buttons are disabled by default in order to stop empty submissions and should become enabled once the student / not inlogged user does a interaction with the dugga.

**Comment by a16erilj** [comment]
Kinda similar to Biträkningsdugga 1 where if a button is pressed then save and reset buttons will become enabled.

**Comment by a19rebsa** [comment]
Ok!
