### ISSUE TITLE
Fix sh/index.php redirection 

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10865]
Currently so does sh/index.php redirect all calls that does not contain parameter a to 404 page. Fix it so that all parameter can be used

**Comment by a16erilj** [comment]
The parameters in querstion are a & c

a should be able to be used without c
c should be able to be used without a
a && c should be able to be used together
If no a || c then send them to the error page 404

**Comment by b18jacha** [comment]
> The parameters in querstion are a & c
> 
> a should be able to be used without c
> c should be able to be used without a
> a && c should be able to be used together
> If no a || c then send them to the error page 404

Thanks for clarification!
