### ISSUE TITLE
Discussion: Fix zoom cap

### ISSUE THREAD

**Issue by a19karwa** [HGustavs/LenaSYS#10876]
Is 0.125x zoom really necessary? You can barely see the elements, in my opinion we should cap it to 0.5x.
![image](https://user-images.githubusercontent.com/81557429/117783131-8bebbc80-b242-11eb-8d79-39accb4cd39e.png)
![image](https://user-images.githubusercontent.com/81557429/117782970-69f23a00-b242-11eb-8afe-ef0da952efcf.png)
![image](https://user-images.githubusercontent.com/81557429/117782837-4dee9880-b242-11eb-9974-d41e8a38ec67.png)

**Comment by a19phith** [comment]
I would think that the last zoom out should be between 0,5 and 0,25

**Comment by a19chrel** [comment]
I do not see the problem with the levels of zoom, but the scroll event that handels the zoomIn and zoomOut for the scroll wheel maybe needs a cooldown of some sort, if you got an sensitive scroll wheel you will directly zoom out or in to the max. An cooldown on the event should fix this.

**Comment by a19chrel** [comment]
I also suggest some changes to the lines in the grid on max zoom out.

**Comment by a19phith** [comment]
Yes sounds good maybe?

**Comment by a19frelu** [comment]
I do not see any good usage of either the 4X zoom, it is in my opinion enough with 2X zoom, or the 0,125 zoom out. It could easily be reduced to 0,25 or even something like 0,33.

**Comment by a19phith** [comment]
with more inspections to our diagram i would consider 0.5 to be the max zoom out. Just because of the visbility and considering that the chance of making extremly large diagrams are not that big

**Comment by a19hammi** [comment]
I think having 4x is good for development use. But 0.125 is way too much to zoom out.

**Comment by a19steis** [comment]
I think the 4x zoom in has its use as hamlet stated, but anything other than 0.5x zoom out seems to be exaggerated.

**Comment by a19hammi** [comment]
fixed in #10990
