### ISSUE TITLE
Make a decent "Replay" button in diagram.

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#10906]
In this exact moment it looks a little bit... different than the others. 

![Replay button](https://user-images.githubusercontent.com/62895155/117820548-f0227680-b26a-11eb-9056-5f55c95f9f72.png)

**Comment by a19frelu** [comment]
My suggestion is that it should be similar to the existing ones to maintain continuity.

**Comment by a19hammi** [comment]
fixed in #10922
