### ISSUE TITLE
Examen why LadExport in resulted.php does not work and if it's possible to fix it

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10902]
A dear thing that allows the teachers to export the assignment data have broken down. So check why this have occurred and document down the ways it could be fixed onto this issue

![bild](https://user-images.githubusercontent.com/81558891/117817644-1692e280-b268-11eb-9d0b-bbdefdffcecb.png)

**Comment by a17alfja** [comment]
![image](https://user-images.githubusercontent.com/81559713/117935667-3f68b580-b304-11eb-802e-af8e848a4a3b.png)
As the export only contains grade information for assignments, is it even needed anymore?
If it is necessary, is canvas integration needed?

**Comment by a17alfja** [comment]
As grade is not information stored in the table, export function needs to reworked completely or removed.

**Comment by a16erilj** [comment]
This issue was spun of into #10972 where we are going to remove LadExport
