### ISSUE TITLE
Document how to add users (Teachers and Students) to courses in Canvas on to a MD

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10900]
A guide on how to add users (Teachers and Students) to courses in Canvas would be educational for newbies. So create a guide in md format called add_users_to_course.md in canvas documentation.

Pictures are allowed (^o^)

**Comment by a19frebo** [comment]
This issue was solved when we did the documentation for issue #10828

**Comment by a16erilj** [comment]
You guys are quick. Then I will be closing this issue down
