### ISSUE TITLE
Small bug: Exiting Replay-mode with Esc not always working

### ISSUE THREAD

**Issue by a19matma** [HGustavs/LenaSYS#10910]
When in Replay-mode, if the most recent mouse-click was on one of the slides in the Replay-mode the "Press Escape to Exit"-action doesn't work. In order for it to work we first have to click somewhere else on the purple bar next to the slides, and then press Esc to exit.

Picture of the slides: 
![image](https://user-images.githubusercontent.com/81557380/117826584-8e650b00-b270-11eb-90b5-b0b58325a9c6.png)

**Comment by a19hammi** [comment]
fixed in #10938
