### ISSUE TITLE
Make it possible to view the table within a time frame in resulted.php

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10926]
We have a nice table that list all the submissions that have been done. However it's not possible to limit the view to a set timeframe for example from 10/5-21 to 12/5-21. So create sorting function that does this for resulted.php and add it among the sort options.

**Comment by HGustavs** [comment]
This can be added as a search option.

Sortabletable allows any search condition with any number of input boxes so it should be simple to impelent

**Comment by a16erilj** [comment]
Here is a mock-up image of how the interval could look like.

The idea is that the interval selection should look at the table dates and allow the user to limit the search result to a set interval.

**Comment by a19gusba** [comment]
at first we used the jquery datepicker but later found out how simple it was to use the HTML type="date".

**Comment by a19gusba** [comment]
We are also using the javascript "Date" object which is very flexible to use, also used this object in previous issues related to time managment
