### ISSUE TITLE
Make it possible to use Course and Assingment at the same time in sh/index.php

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10934]
Great progress have been done with fixing the sh/index.php as most of it functions have been repaired. Now it seems like there is only the ability to combine course and assignment that does not work any longer. So check why it no longer works and fix it if possible. 

Original issue for Course and Assignment combination can be found at #9913 and it's branch #10009

**Comment by a19simma** [comment]
Assisted to advice on solution implemented from https://github.com/HGustavs/LenaSYS/pull/10009
