### ISSUE TITLE
Exiting the hash redirection takes you to a null/error page

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10955]
For some reason so does exiting the hash redirection so are you redirected into a null/error page. Make it so that you are redirected to the previous page.

Redirection age
![bild](https://user-images.githubusercontent.com/81558891/117984773-68a33900-b338-11eb-98e3-dcf66425d29e.png)
Null / Error page
![bild](https://user-images.githubusercontent.com/81558891/117983783-8fad3b00-b337-11eb-86af-e67bca9821cf.png)

**Comment by a19taral** [comment]
by previous page, do you mean the same URL but without the hash element at the end?

**Comment by a16erilj** [comment]
Previous page in this case would most likely be the page before sh/index.php since it is the main way to get the saved assignments. 
The load dugga button which handles loading the loading function will be moved to sectioned since it would fit for that place. 

So the thought is if a user load a dugga from sectioned through our load dugga button then the user should be returned to the same sectioned page when exiting the login/password request.

Load dugga from this page
![bild](https://user-images.githubusercontent.com/81558891/118626372-1d22dc00-b7cb-11eb-818e-e304654853e3.png)
Cancelling login 
![bild](https://user-images.githubusercontent.com/81558891/118626499-375cba00-b7cb-11eb-9e50-f99c59fae705.png)
Returned to previous page
![bild](https://user-images.githubusercontent.com/81558891/118626383-1f853600-b7cb-11eb-99ee-e58fdf96bb2b.png)
