### ISSUE TITLE
Diagram: Save / Export / Load - JSON-files

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10960]
The diagram should have functioallity for save, export and load. This is a big issue so i suggest that we split it into smaller pieces.

- [x] **Save** - Save an JSON-file with the `initial-state` and the `historyLog` (this will be used when turning in an assigment)
- [x] **Export** - Exports an JSON-file that contain `data` and `lines` that when loading will be set as the `initial-state`.
- [x] **Load** - Loads an JSON-file to restore the diagram corresponding with the file. This should be possible with both save (with history) and export-files (without history).

**Comment by HGustavs** [comment]
Is there a way to combine export and save into the same function to reduce code complexity?

It seems to me that having two separate code parts for nearly the same functionality is over-complicated?

This way save and export is just the same thing but externally loading/saving the save data.

So load and import would be basically the same and save/export would also be nearly the same code

**Comment by HGustavs** [comment]
Im thinking export could be a simplified history with only the last modification for each element in the history. Since the export and save are nearly identical apart from the number of history steps, the loading/importing would then be more or less identical??

**Comment by a19hammi** [comment]
There was a request for export and save to do different changes.
Export was for downloading the resulting image as a json while save is for saving the editable work file that is possible to continue working on just like any .txt file.

**Comment by a19hammi** [comment]
fixed in #10973
