### ISSUE TITLE
Investigate where select statements needs to be commented out

### ISSUE THREAD

**Issue by a19anjst** [HGustavs/LenaSYS#10961]
Investigate in what files certain select statements can be commented out as they may not be in use for anything. Don't delete anything and do not touch update or insert statements. When done make a comment here so I can create new issues based on what code you find that needs to commented out. 
Look in following files:
contribution.php
contributionservice.php
sectioned.js 
sectionedservice.php
accessed.js
accessed.php
accessedservice.php
resulted.php
resultedservice.php
resulted.js

**Comment by b18phika** [comment]
For the most part, there might be columns that are no longer being used and can be commented out from SELECT-statements. There are probably not many (if any) that can be commented out entirely.

**Comment by a19anjst** [comment]
As mentioned there might be columns within the SELECT statements that aren't used but whole SELECT statements that are not used is very unlikely

**Comment by a19kimgr** [comment]
Nothing in resulted.js and sectioned.js
row 116 , 389, 397, 401, 697, in accessed.js. Thats it for the .js files.

**Comment by a19anjst** [comment]
I will leave the issue open until I have created all the issues for this ^^

**Comment by a20novra** [comment]
i want to work on this @c20adael

**Comment by c20adael** [comment]
go ahead mate

**Comment by a20novra** [comment]
I checked all file above and there is no more unused variable. @c20adael

**Comment by c20adael** [comment]
It has been investigated and concluded that there are no more unused variables.
