### ISSUE TITLE
Delete buttons should be "removed"

### ISSUE THREAD

**Issue by a19anjst** [HGustavs/LenaSYS#10964]
All the delete buttons should be commented out in the course page as the delete function no longer works and is not needed.
![Skärmbild (402)](https://user-images.githubusercontent.com/62884743/118250254-8c848d00-b4a6-11eb-8697-1702691ccbaf.png)

**Comment by a19isada** [comment]
The delete function works. It's the multi delete function that does not work. If you select an item and then press a delete button, the delete function does not work @a19anjst

**Comment by a19anjst** [comment]
Still is not needed according to Henrik, only hide is needed
