### ISSUE TITLE
Change color of the text in the swimlane

### ISSUE THREAD

**Issue by a19anjst** [HGustavs/LenaSYS#10963]
Right now the blue swimlane text looks like they are links. Change the color of the text to black.
![Skärmbild (401)](https://user-images.githubusercontent.com/62884743/118247952-0cf5be80-b4a4-11eb-9bbe-46f7e2be779b.png)

**Comment by a19klafr** [comment]
The blue text color is because of guesstimation duggas.. If color needs to be changed, choose another color than black since that is the original color for the curses with updated dates and deadlines
