### ISSUE TITLE
Remove LadExport and comment out/remove assoisated code in resulted.php

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10972]
As we have removed personal data so are it no longer possible to create an LadExport that could be used by the teachers for ladoc. So LadExport should be removed and its assoisated code should be commented out/removed.

![bild](https://user-images.githubusercontent.com/81558891/118269855-8353ea00-b4bf-11eb-8f80-c9fbec1b762b.png)

**Comment by HGustavs** [comment]
Yes no need for this.

Make sure that all export code is removed from sortabletable.

**Comment by a17alfja** [comment]
![image](https://user-images.githubusercontent.com/81559713/118813651-a7447080-b8af-11eb-8555-e91bd93f5b63.png)
found a "legend" button that doesn't do anything.
Remove in another issue?
