### ISSUE TITLE
Remove filter by and comment out / remove associated code in resulted.php

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10975]
We no longer store grades in our database so the ability to sort after grades should be removed. Remove it and comment out / remove associated code in resulted.php

![bild](https://user-images.githubusercontent.com/81558891/118276606-24df3980-b4c8-11eb-96a1-19e7c84117bd.png)

**Comment by HGustavs** [comment]
A filter would be nice but keyword search in all columns, e.g. if one would search for 2020-01-01 we would get only those hand-ins made on that date.

**Comment by a19simma** [comment]
@a16erilj Thoughts?

**Comment by HGustavs** [comment]
Filters are built into sortableltable so a text-based filter should be trivial to implement. The default filter may work, but it may need additional conversion to text for allowing sort on dates.
