### ISSUE TITLE
Add Student-teachers to showdugga.php

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#10982]
Seems like we have a role called Student-teachers in LenaSYS so maybe we should add it to showdugga. Begin with give them permission to change variant but also no able to save / reset the dugga

**Comment by HGustavs** [comment]
Well. 

Not necessarily "show" the dugga as showing it would be needed for editing it, but to edit the dugga (duggaed.*) information in the assignment e.g. to correct an error in an assignment text for example
