### ISSUE TITLE
Messages appear over replay bar

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10999]
This is a very minor issue, but it could be very disruptive to the user's workflow since you have to either wait for all of them to disappear or manually click each one in order to gain access to the replay bar. Especially if there are many messages.

![image](https://user-images.githubusercontent.com/81541557/118473285-13856f80-b70a-11eb-9949-698efa73abc7.png)

**Comment by a19hammi** [comment]
fixed in #11000
