### ISSUE TITLE
Ctrl + a in line creation and then pressing delete only deletes the lines

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10994]
**After pressing ctrl + a**
![image](https://user-images.githubusercontent.com/81541557/118469145-bab3d800-b705-11eb-86d4-bafe89a412af.png)

**After pressing delete**
![image](https://user-images.githubusercontent.com/81541557/118469194-c7383080-b705-11eb-8d1a-58173f3bcc9b.png)

**After switching to another mode by clicking on one of the icons, a line is created. Presumably because those were the first two elements to have been added to context when selecting everything**
![image](https://user-images.githubusercontent.com/81541557/118469236-d15a2f00-b705-11eb-9cfd-e10e69ef94bf.png)

**Comment by a19chrel** [comment]
Due to how the line creation works (take context[0] and context[1] and create a line between them) i sugesst that we disable CTRL + A while in this mode. Otherwise an remake of the line creation-mode is needed.

**Comment by a19hammi** [comment]
fixed in #11009
