### ISSUE TITLE
Diagram: Cardenality on Entity => Attribute

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#10997]
It should not be possible to add cardinality between attribute and entity.

![bild](https://user-images.githubusercontent.com/62853826/118471308-ea63df80-b707-11eb-90a2-2abf4072bb1e.png)

**Comment by HGustavs** [comment]
Good catch.

Only lines between relationship symbols and entitites should have cardinalities.

**Comment by HGustavs** [comment]
* lines between two relationships should not be possible.
* lines between two attributes should be possible but not support cardinalities

Are there other edge cases for lines?

**Comment by a19hammi** [comment]
fixed in #11034
