### ISSUE TITLE
Include lines in box selection?

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#10998]
It was originally decided that lines should not be included in box selection, but that was before the ability to delete lines had been implemented. Box selection would be a good tool for deleting multiple lines at once, instead of having to individually click each line that you want to delete.

**Like in this instance, for example**
![image](https://user-images.githubusercontent.com/81541557/118472437-20ee2a00-b709-11eb-80fe-8525c653328c.png)

**Comment by a19hammi** [comment]
fixed in #11043
