### ISSUE TITLE
Make commits / issues / etc as separate areas under the graph in contribution

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#11008]
In issue #9837, commits/issues/etc should be as seperate areas under the graph. It's a bit unclear how this should be implemented. Should the yellow area be coloured differently based on how many % of total events are issue kind of like this? 
![123](https://user-images.githubusercontent.com/81559946/118496639-99aeaf80-b724-11eb-8301-dc0e2b2d279d.png)

or should there be different lines with rectangles for each of the type of event like this?
![image](https://user-images.githubusercontent.com/81559946/118496235-3a509f80-b724-11eb-9014-824c4784a539.png)

Or maybe something else?

**Comment by HGustavs** [comment]
The scale is not very important, we just want to see if there has been any activity.

If a person participates at some specific time with some kind of activity and some other time with some other activity we want to see that

**Comment by b18phika** [comment]
Regarding the scale of the clock. If we call the center 0 and the circle 1. The hour with the most activity should be at the same "value" for everyone, regardless of how much activity that is. The same applies to the hour with the least amount of activity. For example, the hour with the most activity should be at 0.8, and the hour with the least activity should be at 0,2, or whatever looks good.

**Comment by a19anjst** [comment]
You should be able to see that if you work all day but make commits at 17 and not after. You should be able to see if you work continuously during the day or not. When working with issues, commits etc. How far out in the graph the yellow part reaches does not matter. Only it is in the right field. Issues separately, commits separately, etc. When is it a person has worked, not how much.

**Comment by a20behta** [comment]
@HGustavs how does the mockup shown last year look? are they acceptable?

**Comment by c20adael** [comment]
yes this mockup is acceptable

**Comment by b20hanwa** [comment]
@a20vicad this still needs to be worked on.

**Comment by c20adael** [comment]
I will start to look at this but it needs some researching.

**Comment by c20adael** [comment]
![image](https://user-images.githubusercontent.com/80856978/167123242-0e8a53e0-004e-45f9-896a-10df0449b973.png)
Still testing how I can use the function that is in place can be used

**Comment by c20adael** [comment]
I have fixed the visual part. There is however a problem. Its impossible to access the points that appear behind the other polygons. I recommend creating a new issue that tries to fix this by scaling the polygons separately or making the rectangles smaller/merge. Also the filled in polygons needs to be discussed as they should not block the points in the different polygons.

![image](https://user-images.githubusercontent.com/80856978/167400721-05b8805e-0425-4cf1-ab06-cb5bce3de5aa.png)

**Comment by c20adael** [comment]
Also I realized that the percentage that places the points further out on 
the diagram scales with the all of the activities of that kind. 
This meaning that if all of the commits that exist in the data
happened on the same hour, the point will be all the way out on the diagram edge. 

If this is correct then this is fine. But it looks a little weird if there is only one point.

![image](https://user-images.githubusercontent.com/80856978/167402506-89544229-d220-417e-887f-b37bd1496044.png)
