### ISSUE TITLE
Close options panel on double-clicking the background

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#11006]
What about implementing that when clicking outside of any element/anywhere on the background the option panel closes. 
Now it is just closing when clicking on the panels "fab button (+)", option text or by pressing "O/o" but you can open it by double clicking on an element to change the name etc.

I believe the workflow could improve by closing the panel when clicking anywhere on the background. 

Unnecessary or YEY?

**Comment by HGustavs** [comment]
The easy way is to try it out and see if it is worse when performing some normal workflow.

**Comment by a19hammi** [comment]
Double-clicking on the background is something that feels more sound.
I like being able to have the options panel open and look through different elements, without having it close if I miss the element by a pixel. This feels like the better in-between option! 👍

**Comment by a19frelu** [comment]
Seems completely reasonable in my opinion too.

**Comment by a19hammi** [comment]
fixed in #11039
