### ISSUE TITLE
Keyword search for columns in resulted

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#11003]
It would be appreciated if it was easy to search after something in resulted. So create a search row where you can write a keyword, type of match and which column

![bild](https://user-images.githubusercontent.com/81558891/118483227-0ec6b880-b716-11eb-9c7c-851cb33686a3.png)

**Comment by HGustavs** [comment]
Perhaps this is what the search field in the menu is doing?

I really like the dropdown for matching for example a date... the default should be matching all columns though

**Comment by a16erilj** [comment]
The search in navbar is currently broken from what I have tested. So the question is if this search function should be in the navbar (replace the old one) or be placed at the page (and remove search from navbar).

**Comment by HGustavs** [comment]
I prefer moving this from the search bar since it is more clear within the page and also allows us to have a dropdown for different options.

The searching is handled automatically by sortabletable, so only a generic callback is necessary for the search functionality
