### ISSUE TITLE
Camera moves when using mouse wheel after x0.25

### ISSUE THREAD

**Issue by a18nadma** [HGustavs/LenaSYS#11010]
https://user-images.githubusercontent.com/49141885/118606876-3706f380-b7b8-11eb-9f36-a21ee42cde9e.mp4

This doesn't happen when using the zoom out button, only when using the mouse scroll wheel

**Comment by a19chrel** [comment]
What i could find when testing this is that the zoomfactor does not change, but the camera change on scroll does trigger, Could @a18nadma check if the problem is corresponding with my findings or if the diagram becomes smaller.

**Comment by a18nadma** [comment]
I can confirm that the diagram is not becoming smaller, I will changes the issue to put focus on not letting the camera move!

**Comment by a19hammi** [comment]
fixed in #11018
