### ISSUE TITLE
Error is thrown, noticed when reviewed issue #10986

### ISSUE THREAD

**Issue by b19ponka** [HGustavs/LenaSYS#11013]
![Screenshot 2021-05-18 094006](https://user-images.githubusercontent.com/62886839/118611367-0d9c9680-b7bd-11eb-86c6-6d26b19138be.png)

**Comment by a19frebo** [comment]
This error is thrown because there are two SESSION variables that are not initialized, and if they are read while not initialized this error is thrown.
