### ISSUE TITLE
Bug allowing user to create, place and interact with ghost elements

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#11030]
I cannot say for sure how this even happens of exactly what it is that has to be done to be replicated. But it seems placing a relation, then trying to place another but holding down the mouse and releasing it ON TOP OF an entity causes the element to be created to change into a ghost element instead of ERRelation. It ALSO seems to trigger the create line mode and insert a ghost line DESPITE me never enabling line creation mode during the session. GIF replay here:

https://user-images.githubusercontent.com/81571224/118648069-5286f400-b7e2-11eb-8b4d-89d81792606d.mp4

**Comment by b20thelo** [comment]
I close this since we have removed the ghost element as per request by Henrik.
