### ISSUE TITLE
Weak key underlines not scaling with zoom

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#11046]
**Zoomed in**
![image](https://user-images.githubusercontent.com/81541557/118779165-13f94400-b88b-11eb-9ba2-76874714df85.png)

**Zoomed out**
![image](https://user-images.githubusercontent.com/81541557/118779251-27a4aa80-b88b-11eb-8ed4-0e2f9ff3bcbe.png)

The underline should be the same size in relation to the text regardless of the zoom level

**Comment by a19hammi** [comment]
fixed in #11050
