### ISSUE TITLE
Load Dugga button on coursepages

### ISSUE THREAD

**Issue by e15marol** [HGustavs/LenaSYS#11047]
Currently there is an issue with the Load Dugga button where if you enter anything but a correct hash, you are taken to a 404 page.
![Skärmklipp](https://user-images.githubusercontent.com/18677403/118780741-a3ebbd80-b88c-11eb-96ca-9890c272ac3d.PNG)

**Comment by e15marol** [comment]
@b19ponka If this is intended, you may close this issue.

**Comment by b19ponka** [comment]
> @b19ponka If this is intended, you may close this issue.

It is. It was a request by the customer to prevent bots/spam.
