### ISSUE TITLE
Box surrounding selected elements not on top of other elements

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#11051]
The selected element is on top of non-selected elements while moving it, but not the box around the selected element. 

![Skärmavbild 2021-05-19 kl  10 48 07 (2)](https://user-images.githubusercontent.com/62895155/118784911-a819da00-b890-11eb-882e-1642255b3c8b.png)

**Comment by a19hammi** [comment]
fixed in #11054
