### ISSUE TITLE
No contour on elements in 0.25x zoom. 

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#11059]
The contour is still visible in 0.5x zoom. 

![Skärmavbild 2021-05-19 kl  12 27 13](https://user-images.githubusercontent.com/62895155/118798133-9854c280-b89d-11eb-984d-a402f2dcecc0.png)

But not in 0.25x zoom.

![Skärmavbild 2021-05-19 kl  12 26 46](https://user-images.githubusercontent.com/62895155/118798169-a30f5780-b89d-11eb-92ff-2045c39b749e.png)

**Comment by a19phith** [comment]
if i remember correctly we where going to remove the 0.25x zoom out right? so i dont really see the point of tweaking anything on zoom out 0.25x

**Comment by a19frelu** [comment]
I recall something similar, but I do not know if something changed along the path, because we only removed the previous 0.125x zoom so I thought we scrapped the idea to remove the 0.25x zoom, but I am not sure.


**_Image from W19-main:_**
![Skärmavbild 2021-05-20 kl  09 20 31](https://user-images.githubusercontent.com/62895155/118937226-96e2d300-b94d-11eb-9489-fd7206d17977.png)

**Comment by a19hammi** [comment]
fixed in #11097
