### ISSUE TITLE
Comment out lastname, firstname and ssn in accessedservice.php (NOT INSERT OR UPDATE. DON'T TOUCH!)

### ISSUE THREAD

**Issue by a19anjst** [HGustavs/LenaSYS#11070]
Decided to put them all in the same issue so people don't work on the same file at the same time

Row 105 - if-statement containing ssn, first- and lastname
Rows 163,165 - SELECT with WHERE on ssn (ssn=:usernameorssn2)
Rows 181,182 - SELECT with WHERE on ssn (ssn=:ssn)
Rows 186,187 - Variables for first- and lastname 
Row 297 - SELECT with ssn, first- and lastname
Rows 316-317 - first- and lastname added to array
Row 329 - SELEECT with first- and lastname
Row 337 - first- and lastname added to array

**Comment by a20behta** [comment]
issue already merged in and completed closing issue
