### ISSUE TITLE
Box selection collision detection for elements have an offset on the y-axis

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#11080]
As you can see in the image below, the selection of elements from underneath using box selection has an offset. The box, relatively speaking, is nowhere near where it should be for a collision to be detected. This is true for all element types.

![image](https://user-images.githubusercontent.com/81541557/118876864-0628da80-b8ee-11eb-9ee4-758c7afc3afd.png)

**Comment by a19hammi** [comment]
fixed in #11093
