### ISSUE TITLE
Loading a dugga with a hash requires a password every time that you refresh

### ISSUE THREAD

**Issue by e15marol** [HGustavs/LenaSYS#11095]
When a dugga has been loaded more than once (through URL with hash), with password included, it should no longer require the entry of password whenever reloading the URL. Simply refreshing the page requires you to enter the password again.

**Comment by a16erilj** [comment]
This is something that we added back since the old solution enabled bad actors to access submissions with the hash alone. How this could be solved is something is currently under consideration.
