### ISSUE TITLE
Make it possible to chose what columns are shown

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#11107]
It should be possible for teachers to chose what columns are shown. Similarly to how teachers can chose what dugga that are shown so should they be able to chose what columns should be shown. 

Dugga filter
![bild](https://user-images.githubusercontent.com/81558891/119101119-f0fc9a80-ba18-11eb-85c8-61c2d95c53b4.png)

**Comment by a19simma** [comment]
Last weekly merge coming up and it wasn't solved yet. Can close the issue and remove me from it so it can be completed at a later time by someone else. 😛

**Comment by a20vicad** [comment]
Working on it. A very advanced issue for a complete beginner.

**Comment by a20vicad** [comment]
Issue, out of my capabilities. Existing code is very specific to only one dropdown menu as far as I can tell. Good luck someon else.

**Comment by a20behta** [comment]
removing week one branch and waiting with creating a new one untill sub issues are solved and merged

**Comment by a20behta** [comment]
implemented into weekly merge
