### ISSUE TITLE
Make it possible to sort after Times submitted and Times accessed

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#11104]
It seems not possible to sort after Times submitted and Times accessed. 

Make it possible after them.
![bild](https://user-images.githubusercontent.com/81558891/119097279-d3c5cd00-ba14-11eb-8f48-497325460348.png)

**Comment by a18osken** [comment]
could this be because all of the values in those two columns are null?

**Comment by a19rebsa** [comment]
You can sort on times submitted, but not on times accessed
