### ISSUE TITLE
Remove the old buttons in resulted

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#11109]
Since most of the functions that the old buttons provided have been moved down onto the page instead of being in the navbar so remove these buttons and comment out / remove the associated code.

![bild](https://user-images.githubusercontent.com/81558891/119105043-4044ca00-ba1d-11eb-8586-5ae7d15d79a1.png)

**Comment by b19ponka** [comment]
![Screenshot 2021-05-24 095107](https://user-images.githubusercontent.com/62886839/119314915-901dce00-bc75-11eb-8bff-9d4da2f07939.png)
Also remove the old assignment filter
