### ISSUE TITLE
Collect the information when the last time a teacher visited the submission

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#11113]
We want the information when was the last time a teacher visited a submission. This should then be displayed in resulted.

A small example
![bild](https://user-images.githubusercontent.com/81558891/119113502-72f2c080-ba25-11eb-9955-8cf86076905f.png)

**Comment by c20adael** [comment]
This issue will get split in to smaller parts. One visual, one database part and one JS part.

**Comment by a20behta** [comment]
implemented and works as expected 
placed in weekly merge
