### ISSUE TITLE
Remove the FAB button on the diagram UI

### ISSUE THREAD

**Issue by a18nadma** [HGustavs/LenaSYS#11118]
![image](https://user-images.githubusercontent.com/49141885/119115920-00371480-ba28-11eb-9efb-907c479cf721.png)

This is just code being reused and is not needed.

**Comment by a19chrel** [comment]
Keep in mind that the `toggleReplay()` uses this button while changeing the UI. So we don't accidentally make any bugs what will crash the diagram.
https://github.com/HGustavs/LenaSYS/blob/d92a4ad5a587d8babb6c340b4a4b8f0f2ee9d4b7/DuggaSys/diagram.js#L3090-L3146

**Comment by a19hammi** [comment]
fixed in #11132
