### ISSUE TITLE
Bug: Round positional values for elements.

### ISSUE THREAD

**Issue by a18nadma** [HGustavs/LenaSYS#11117]
The documentation of the diagrams has coordinate decimals. those are not neccessary and should be removed.

**Comment by a19hammi** [comment]
All elements should only have integer values as positions/sizes.

**Comment by HGustavs** [comment]
Or if there is a reason for decimals, perhaps one decimal or two. But currently we have 9 decimals e.g. 431.6666666664

**Comment by a19hammi** [comment]
fixed in #11145
