### ISSUE TITLE
Change the snap to grid icon

### ISSUE THREAD

**Issue by a18nadma** [HGustavs/LenaSYS#11115]
![image](https://user-images.githubusercontent.com/49141885/119115028-fe208600-ba26-11eb-9be4-2cee3df3b9d9.png)

It was requested to make a more clearer icon for Snap to grid. A suggestion of what it could look like has been added.

**Comment by a19hammi** [comment]
> It was requested to make a more clearer icon for Snap to grid. A suggestion of what it could look like has been added.

It was specifically requested to use the magnet symbol on top of a grid. We should use this design specifically.

**Comment by a19hammi** [comment]
fixed in #11139
