### ISSUE TITLE
Diagram: Change color of element-background and stroke

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#11119]
Make it possible to change colors of the elements. We currently got part support for this, as shown below.

We already has an array of colors that should be possible to pick from.
https://github.com/HGustavs/LenaSYS/blob/d92a4ad5a587d8babb6c340b4a4b8f0f2ee9d4b7/DuggaSys/diagram.js#L900

Also the element-types has a default color and stroke that currently is not in use.
https://github.com/HGustavs/LenaSYS/blob/d92a4ad5a587d8babb6c340b4a4b8f0f2ee9d4b7/DuggaSys/diagram.js#L990-L995

**Comment by a19chrel** [comment]
Also this changes should be saved in the history(stateMachine)

**Comment by a19hammi** [comment]
fixed in #11151
