### ISSUE TITLE
Double clicking not generating properties

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#11152]
If the first click while double clicking is on the background and the second click is on an element, no properties are generated in the options panel. This is because the generateContextProperties() function returns immediately if wasDblClicked is true. It needs to check if both clicks were on an element as well.

**Comment by a20micro** [comment]
Found that the start of the function returns if a certain boolean is set, which will always be set in the case of a double click, preventing properties from being shown. Simply removing the initial IF statement which always returns (in case where the initial click is on the background, and the second click is on the element) solved the issue of missing properties.

Research about the wasDblClicked is now needed as it isn't ever used, only declared.

**Comment by b20thelo** [comment]
Tested on the webserver. Confirmed that it now works.
