### ISSUE TITLE
Select & Move labels in diagram

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#11155]
Example from draw.io on how it looks. No need for advanced calculations. Just have  a relative x and y to center of line.

https://user-images.githubusercontent.com/81571224/119369589-a139ff80-bcb4-11eb-892f-39de36562a0a.mp4

**Comment by b20thelo** [comment]
The solution needs to be worked on further before being approved for merging so therefore the pull request 11363 was denied.

**Comment by c20emili** [comment]
https://user-images.githubusercontent.com/81320323/162904413-242f4bb9-ed4a-4b5e-95c4-03c7960873e4.mp4

**Comment by b19karhj** [comment]
The label should be able to be moved above and below the line on Y-Axis. (Atm the label can only be moved on X-Axis shown in the video).

**Comment by c20emili** [comment]
removed unnessecary zoomfact that caused issues label will stay on the line even when zoomed.
https://user-images.githubusercontent.com/81320323/163206219-cfbdeec3-019a-4e9a-8937-12ff8bd6f6db.mp4

**Comment by b20thelo** [comment]
Progress made. Left to finish in this issue is the possibility to deattach the label from the line and moving it within a specified distance from the line. Shown in the first video in this issue.

**Comment by b20thelo** [comment]
Closing this as new issue will be opened for the remaining steps.
