### ISSUE TITLE
Restrict number of characters allowed when putting labels on lines

### ISSUE THREAD

**Issue by a19karwa** [HGustavs/LenaSYS#11168]
Currently you can add as many characters as you want when putting labels on lines, if the label intersect with another line it gets drawn over the line, see highlight on picture below...

![image](https://user-images.githubusercontent.com/81557429/119359461-f15f9480-bca9-11eb-824b-ef481b87373d.png)
![image](https://user-images.githubusercontent.com/81557429/119359483-f9b7cf80-bca9-11eb-8043-600a92c1816f.png)

**Comment by a19phith** [comment]
should we have a fixed value for the length of the text? or should we just make the text intersect with the line it belongs to?

**Comment by a19karwa** [comment]
I would say both might be good to implement.

**Comment by a19hammi** [comment]
fixed in #11173
