### ISSUE TITLE
Table not displaying the rows correctly in Mobile browsers

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#11172]
The good folks at #10823 found a issue with browsing the table to the sides. This creates a table within a table somehow.

Look after the cause and try to fix it if possible.
![bild](https://user-images.githubusercontent.com/81558891/119495100-4fe84980-bd62-11eb-970e-66dcee48acb6.png)

**Comment by a13zanal** [comment]
Looks like the code creates 4 different tables, and when you reduce the width or are in mobile mode then one of it appears for some reason.

![image](https://user-images.githubusercontent.com/62987694/119500297-ee2ade00-bd67-11eb-9924-e9da361efaa2.png)
