### ISSUE TITLE
Moving element while lines are selected and pressing undo leaves a selection box

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#11180]
Having lines selected while moving elements and then pressing undo leaves a selection box around the previously selected lines:

![1](https://user-images.githubusercontent.com/81541557/119514166-1836cd00-bd75-11eb-8cb6-bd8c763073dc.gif)

**Comment by b20matad** [comment]
This problem seems to be solved.

**Comment by b20thelo** [comment]
Closing since this has been resolved through other changes made by group 1.
