### ISSUE TITLE
Check after unexpected problems with our LenaSYS instance on our G1 Server

### ISSUE THREAD

**Issue by a16erilj** [HGustavs/LenaSYS#11193]
We have now updates our server to the latest version of our groups LenaSYS. So some people should explore it to see if everything work as intended and note down unexpected things with images onto this issue.

[Link to our server](http://project-g1.webug.his.se/DuggaSys/courseed.php)

**Comment by a19rebsa** [comment]
Could not really find any unexpected problems with the parts of the website that we have been working on in group 1. 👍

**Comment by a20behta** [comment]
issue is no longer relevant. closing issue
