### ISSUE TITLE
Code viewer dark mode does not work

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#11207]
Dark mode and light mode need to be handled consistently in the code viewer (and  the rest of lenasys as well).

Currently, as far as I know, dark mode only works in code viewer, but some parts do not use dark mode.

<img width="540" alt="Screenshot 2022-03-29 at 16 36 00" src="https://user-images.githubusercontent.com/6978801/160636765-dd966bb6-8639-444b-a2bd-43ad10ed85b9.png">

This needs to be handled consistently and correctly

**Comment by a20sarle** [comment]
Specification of "This needs to be handled consistently and correctly" is needed.

**Comment by a20sarle** [comment]
This issue regarding CodeViewer reference #11449 (update design according to Material Design) and #11314 (documentation of current dark mode colors).
