### ISSUE TITLE
Contribution stopped working after final merge because of an error in sortableTable.js

### ISSUE THREAD

**Issue by a19anjst** [HGustavs/LenaSYS#11203]
Something is wrong at row 406 with checked. If checked is removed it works. Unsure why checked is used. 
![Skärmbild (441)](https://user-images.githubusercontent.com/62884743/119959872-ae9d0580-bfa4-11eb-9c29-0db1c8beb942.png)

**Comment by c20adael** [comment]
Undersök detta problem. Är detta löst?

**Comment by a20behta** [comment]
old issue closing as no longer relevant
