### ISSUE TITLE
Connection and usage between canvas and lenasys

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11219]
Document made researching the integration and connection between canvas and lenasys. 

For future use and understanding for integration and using canvas login.

**Comment by a20behta** [comment]
@b20jonlu upload a pdf version of the document already sent to me

**Comment by HGustavs** [comment]
Lenasys is included in canvas using the following things:

#1 in canvas, an iframet is used to link canvas to lenasys
#2 In that iframe we use the sh url shortener (in lenasys manin folder) to arrrive at specific pages in lenasys for example tests
#3 We use the web link submission in canvas and make a hash in lenasys as a workaround for making submissions of assignments from lenasys to canvas

**Comment by HGustavs** [comment]
Related to issue #11230 imho

**Comment by a20sarle** [comment]
Referene to #11340

**Comment by b20jonlu** [comment]
[canvas _ lenasys koppling.pdf](https://github.com/HGustavs/LenaSYS/files/8416559/canvas._.lenasys.koppling.pdf)


>

**Comment by a20behta** [comment]
everything uploaded and includes connectivity. closing issue
