### ISSUE TITLE
Really annoying bug in code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#11226]
When embedded into canvas (unclear if it happens in other situations)

We get the following errors when clicking a code example

<img width="599" alt="Screenshot 2022-04-01 at 09 20 17" src="https://user-images.githubusercontent.com/6978801/161215088-cf449334-2382-455c-9bfe-46a386156fc6.png">

I assume that there is some code on or around row 184 that is the culprit.

No cookies should be used in the code viewer so I assume that these rows that work with the cookies should just be removed.

**Comment by b20sebka** [comment]
Can't find a way to replicate this bug in my local clone so I have no way of testing it.

**Comment by a20behta** [comment]
@b20sebka This  is a issue for Group2 no need to continue

**Comment by a20sarle** [comment]
First step is to research how and if the bug can be recreated.

**Comment by a20sarle** [comment]
Check/research if "cookie guest" has been removed from previous versions of LenaSYS, if that's the case the issue has most likely already been solved.

**Comment by a20sarle** [comment]
Compare with previous versions of LenaSYS (go to LenaSYS / DuggaSYS / codeviewer.php ---> "history" and choose an older commit, then go to browse files)
![image](https://user-images.githubusercontent.com/81631818/163192722-9de6d536-c673-4bae-937e-3496667c197a.png)

![image](https://user-images.githubusercontent.com/81631818/163192621-02a2b7fc-6243-496d-9cc5-666690f35222.png)

**Comment by b20idawa** [comment]
I have found a way to test this issue.

For example, you create an HTML file that contains an iframe. The iframe that has created must contain a link to a page on LenaSYS. The example uses Javascript Example: Collect in the web programming course. The file should then be used in a code example with the "preview" setting. Each time the page reloads, the same alert will be displayed, the same alert that was displayed on Canvas.

<img width="1339" alt="Skärmavbild 2022-04-21 kl  13 48 21" src="https://user-images.githubusercontent.com/81676911/164451698-5f5fadfd-abb4-4675-9503-5731f9a53c0f.png">
<img width="604" alt="Skärmavbild 2022-04-21 kl  13 48 41" src="https://user-images.githubusercontent.com/81676911/164451745-1bc893ea-0345-4617-8a5a-a1e137f686ff.png">

**Comment by a18gusjo** [comment]
I might be wrong but my conclusion is that this probably isn't a problem in the most recent version of LenaSYS. When debugging the problem at https://dugga.iit.his.se/DuggaSys/codeviewer.php?exampleid=6503&courseid=7&coursename=Webbprogrammering&cvers=82518&lid=10769
and searching for "cookie_guest" the following is found at row 67: _<script> alert("Unknown error type: [8] Undefined index: cookie_guest\n error on line 184 in file /var/www/html/Dugga/DuggaSys/codeviewer.php"); </script><header>_ 

![image](https://user-images.githubusercontent.com/102605031/164715999-c999931d-32aa-4e02-ab12-abc508f3b811.png)

This statement does not exist in codeviewer.php or any file in branch G2-2022-#merge4 which probably means that this isn't a issue anymore.

**Comment by a20willa** [comment]
After many tries, we can only conclude this issue is not relevant for the current version of lenasys. It might be a problem on the side of canvas, but we have no control over that part. The issue is thus concluded to be already solved.
