### ISSUE TITLE
Too restrictive dialog when creating new course version

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#11222]
![image](https://user-images.githubusercontent.com/4948661/161211619-d66fa4fe-e2b0-4017-bc6c-e5f69df41e21.png)

This dialog is too restrictive. We must be able to have version id longer than 6 characters and I'm not sure why we don't allow characters other than digits? THe following should be ok I think

- 789231311
- spring-3214
- 123123-123123

Version name also needs to be less restrictive. I think the following would be OK version names

- VT-22
- VT-22lp2
- Spring

**Comment by a20novra** [comment]
jag want to work with this @c20adael  @a20behta

**Comment by a20behta** [comment]
@a20novra Looks good can begin work

**Comment by a20novra** [comment]
![1](https://user-images.githubusercontent.com/81618150/161734104-88615325-a203-4a70-a48a-b2088fa638cd.jpg)
![2](https://user-images.githubusercontent.com/81618150/161734123-8ef96495-4070-4fcd-8901-ae6e138f13f4.jpg)
![3](https://user-images.githubusercontent.com/81618150/161734148-c0017964-e339-42d4-97af-955e6f05b31f.jpg)


When i try to change Version Name Regexp i get this error, but i can't find header.php file. (OBS! it create the new version anyway but i cant understand why we get error)

**Comment by c20adael** [comment]
The file seems to be named navheader.php. You should investigate that file since it exists in the folder that is specified. @a20novra

**Comment by c20adael** [comment]
i dont know why an "n" is missing from the filepath

**Comment by a20behta** [comment]
@a20novra New branch created from new weekly branch. 
can continue developement from here

**Comment by a20novra** [comment]
I think this issue should be divided into twp parts. The first part should be about RegEx, and the other part should be about why when we try to copy content from exsiting course we get error massage .
