### ISSUE TITLE
Hide login button

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#11220]
We want the login button to be hidden.

![image](https://user-images.githubusercontent.com/4948661/161209788-3e2291d2-ba8d-4d26-9f3f-84a6bb76cf87.png)

Since LenaSYS removed login for regular users it is annoying and misleading to show a login button for everyone.

The proposed solution is to remove the icon and guest login name but leave the actual button functionality. This way regular users do not see the button but teachers who still are able to log in can use the hidden button to get privileged access to LenaSYS

**Comment by HGustavs** [comment]
I suggest we show the login name when logged in as a user but not "Guest"

**Comment by b20eripe** [comment]
@a20behta Jag tar den

**Comment by a20behta** [comment]
@b20eripe Looks good start work

**Comment by a20behta** [comment]
merged with current look

Hovering over the same area causes green view indicating login posibility:
![image](https://user-images.githubusercontent.com/102468604/161972654-b90f53cb-944c-4c6e-81e7-03e72b63863d.png)

Not hovering results in blending in with the background
![image](https://user-images.githubusercontent.com/102468604/161972839-b17182cd-43b7-4440-bad1-119946b0c14f.png)

closing issue as merged into main
