### ISSUE TITLE
Superuser/teachers cannot view duggas when logged in

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#11227]
Superuser/teachers cannot view duggas when logged in:

![image](https://user-images.githubusercontent.com/4948661/161215910-47689a2e-78be-48ad-9766-5ccb654b4c74.png)

The system gives an error as shown above and end up serving an empty dugga.

![image](https://user-images.githubusercontent.com/4948661/161216107-8f424941-a3fe-42ec-a580-771e8ba8c709.png)

**Comment by a20behta** [comment]
@b20jonlu use the branch for continued development
