### ISSUE TITLE
Something seems broken with navheader

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#11221]
![image](https://user-images.githubusercontent.com/4948661/161210665-6ac5c1df-6f73-4f7d-ae1f-e68e65c41fc0.png)

When login in as a teacher/superuser error messages such as the one provided is shown.

**Comment by b20hanwa** [comment]
I need help with this issue @a20behta @c20adael

**Comment by b20hanwa** [comment]
I can´t recreate this issue. If you can provide more information about the issue that would be great! @a97marbr

**Comment by a20behta** [comment]
issue cannot be recreated. Issue is not relevant anymore.

**Comment by a20behta** [comment]
issue cannot be recreated. Issue is not relevant anymore.

**Comment by a97marbr** [comment]
I believe this issue occurs when LenaSYS is accessed through an iframe, for example from a canvas installation.
