### ISSUE TITLE
Accessing links to external services such as youtube or github not working from canvas-integrated course page

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#11229]
Accessing links to external services such as youtube or github not working from canvas-integrated course page.

Proposed solution: Add an option that allows links to be opened as new tab/page. If the option to open link as a new tab/page is used the link should be presented in a different way than other links in LenaSYS.

Provide mockup example on how the design differs between:
- a regular link
- a link that opens in a new tab

**Comment by a20samul** [comment]
Added pdf file with suggestions on displaying self referencing- and external links.
[Mockup links.pdf](https://github.com/HGustavs/LenaSYS/files/8417054/Mockup.links.pdf)

**Comment by b20thelo** [comment]
Feedback from Henrik.

Henrik wants Youtube and Github links to open up in new tabs by default, so when a link is created it recognizes that the link includes those domains. He also wants a button further to the right side for all links that open in a new tab.

**Comment by a20chrka** [comment]
As mentioned, this issue has been resolved in issue #11836. Therefore this issue is now closed.
