### ISSUE TITLE
Manual resize of code window causes other code windows to also resize.

### ISSUE THREAD

**Issue by a20linth** [HGustavs/LenaSYS#11238]
In a code dugga with a template that has three or more windows, resizing one of the windows can cause the other windows to be resized in odd ways.

https://user-images.githubusercontent.com/102609651/161233638-ce8cc671-3a28-4f6d-81a2-8b0ff74d6fb2.mp4

**Comment by a18gusjo** [comment]
Researched the bug, and it is probably a problem in the function reziseBoxes() at the if-statement that is associated with templateId 4

 "else if (templateId == 4) {
		getLocalStorageProperties(templateId, boxValArray);

		$(boxValArray['box1']['id']).resizable({
			containment: parent,
			handles: "e,s",
			start: function (event, ui) {
				document.getElementsByTagName("iframe")[0].style.pointerEvents = "none";
			},
			resize: function (e, ui) {
				alignBoxesWidth(boxValArray, 1, 2);
				alignBoxesHeight3boxes(boxValArray, 1, 2, 3);
				document.getElementById("box2wrapper").style.left = " ";
			},
			stop: function (e, ui) {
				setLocalStorageProperties(templateId, boxValArray);
				document.getElementsByTagName("iframe")[0].style.pointerEvents = "auto";
			}
		});"
