### ISSUE TITLE
Icons are removed even tho there are space for them when resizing window

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11243]
When resizing a window, many icons on the gray bars is removed if the window gets too small. There are no reason for the icons to be removed here, as they would fit. 

[![Image from Gyazo](https://i.gyazo.com/8d297e6e1909be88a4dda970dadceede.gif)](https://gyazo.com/8d297e6e1909be88a4dda970dadceede)

**Comment by AnasDORBANI** [comment]
Check the icons container's display in the media query.

**Comment by HGustavs** [comment]
Related to issue #11246
