### ISSUE TITLE
Reset view in diagram

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#11249]
Unclear if this feature exists, but we need a reset view to default extents so that the whole diagram is visible in the view.

Currently if we zoom too far out or too far in, we have a hard time reaching the current diagram.

The best solution currently is refreshing the page which gets us to the full diagram view.

I suggest an icon like the full screen icon on youtube together with the zoom icons.

<img width="122" alt="Screenshot 2022-04-01 at 13 13 58" src="https://user-images.githubusercontent.com/6978801/161252854-58d5c593-b57b-4b15-b3c5-ed248517d98c.png">

If the feature is already implemented I would just like to have the icon for it.

<img width="104" alt="Screenshot 2022-04-01 at 13 15 22" src="https://user-images.githubusercontent.com/6978801/161252972-8a7039b1-16a3-4ad8-b0a4-b546a1f0f384.png">

**Comment by a16linas** [comment]
Made a button with the function of resetting zoom view

**Comment by b20thelo** [comment]
Tested on the webserver. Confirmed that it works as it should.

**Comment by b20thelo** [comment]
After the solution was pushed to merge further testing were made and there are still issues with the zoom even though it is better then original solution.

**Comment by b20thelo** [comment]
Other issues fixed the remaining issues with the zoom.
