### ISSUE TITLE
Refactoring is needed in showDugga.php

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11240]
There is a lot of commented code that needs to be checked and could be removed.

**Comment by HGustavs** [comment]
Yes.

This is a task for all files not just this file specifically.

**Comment by HGustavs** [comment]
Related to issue #11242

**Comment by a17nikjo** [comment]
Starting to refactor the file and remove commented code that serves no purpose.

**Comment by a20novra** [comment]
jag jobbar på det här @a20behta

**Comment by a17nikjo** [comment]
54   - 94   related too setting up for the password promt
152 - 168 labeled as old code, primarly does console logging. - Code removed.
206 - 250 creates a login promt

**Comment by a20vicad** [comment]
Some of the commented out code was seems to hold a testing purpouse and this gets to stay.
![image](https://user-images.githubusercontent.com/102599327/164203844-b303bb76-33d0-4cd4-acf7-7bde46022c51.png)
