### ISSUE TITLE
Many issues in hambuger menu above code viewer

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11247]
There are many issues regarding the hamburger menu which pops up if the window gets too small. 
These are:

- Clicking it does not work the first time, but after the second click it works
- The color is wrong on the options, may be linked to #11207
- There are no indication that the options are clickable. Hovering over an option does not show a mouse pressing icon, but the default typing one instead

These issues could probably be divided to have their own issues.

![image](https://user-images.githubusercontent.com/81626616/161251449-f15cf778-4a72-475c-abbb-28886069666e.png)

**Comment by HGustavs** [comment]
Related to issue #11246
