### ISSUE TITLE
Researching using css grid in code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#11246]
Currently the code viewer has quite complex CSS for handling responsivity in the views.

I would like to see some research into using css grid instead, and if css grid can make the code simpler without breaking the formatting or the refactoring rule.

The hunch is that we can reduce the amount of css code needed considerably, and also supporting better views on mobiles or even allowing an "embedded into canvas" view that is more suited than the current one.... and this final adaptation to canvas would not be worthwhile without investigating css grid first.

**Comment by a20linth** [comment]
My report concerning the possibility of implementing CSS grid in the codeviewer and questions to the customer about the topic can be found in issue #11256
