### ISSUE TITLE
Color of hamburger menu options and other elements does not match well with background

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11254]
Reference to #11247. The text does not match well with the background.

![image](https://user-images.githubusercontent.com/81626616/161259515-514ed2c3-08a5-4059-a6ca-aa4f00987388.png)

Also an reference to #11246 (too complex CSS might have caused this error)

**Comment by HGustavs** [comment]
In dark mode does it look the same?

**Comment by a20willa** [comment]
The screenshot was actually taken when in darkmode, but it looks correct if it's put into light mode. 
![image](https://user-images.githubusercontent.com/81626616/161295737-66ab1fe5-2ab6-493d-be6f-373e736a9b7e.png)

**Comment by a20willa** [comment]
This issue was originally specific for the hamburger menu but we have noticed the issue is in other places too. We have decided to extend the issue to account for **all** other instances where this is a problem.

**Comment by a20sarle** [comment]
Tested and changes are implemented with reasonable quatntity of code.
![image](https://user-images.githubusercontent.com/81631818/162438235-4397d165-06db-4917-8bad-820bdcd4d038.png)
![image](https://user-images.githubusercontent.com/81631818/162438246-63e6c754-db2d-4ffb-9d46-4e3176e5d5f6.png)
![image](https://user-images.githubusercontent.com/81631818/162438268-dc39fff2-7020-4788-98e0-43b89828887f.png)
