### ISSUE TITLE
Two finger trackpad movement in diagrams on Mac zooms crazy fast

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#11259]
When two finger gesture moving on diagram on Mac trackpad, the diagram zooms but so fast that the zooming feature is nearly useless.

Unclear if same thing happens when one uses two finger gesture on PC

**Comment by HGustavs** [comment]
Is it possible to define two finger guesture as scrolling and pinch as zoom (seems to at least partially work like that in for example google docs)

**Comment by a20jonda** [comment]
Same zoom problem on Windows 11 (both scroll zooming and pinch zooming)

**Comment by a20jacmi** [comment]
Scroll and pinch are working as suggested. However, there is no general way to make a distinction between the utilisation of the mousewheel or the trackpad, that will work on all browsers.

We're working on a solution that will slow down the zoom-function. It looks pretty good but we're giving it some more time to see if we can make it better.

**Comment by b20thelo** [comment]
Sets a timeout that doesn't allow zoom events to trigger more than once every 75 ms. To slow down zoom on a touchpad.
