### ISSUE TITLE
Diagram editor seems to allow us to draw incorrect relationship lines

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#11257]
<img width="256" alt="Screenshot 2022-04-01 at 15 33 34" src="https://user-images.githubusercontent.com/6978801/161273961-c3ad115c-5509-48b0-802f-953b718a6340.png">

While testing the diagram I noticed that the default diagram has the cardinalities drawn on the wrong end of the symbol.

Any cardinality numbers should be drawn at the entity ends.

The (managess ?) relationship has the cardinalities drawn at the relationship side.

**Comment by a20micro** [comment]
Found that the error happens when adding a line from the relationship node to a different node, but not the other way around. Simply swapping the logic which determines the initial node should be a feasible solution.

**Comment by b20thelo** [comment]
Tested on the webserver. Confirmed that it works as it should.

**Comment by b20thelo** [comment]
This issue was solved in a better way in issue #11292 therefore this solution made here were never merged in the end.
