### ISSUE TITLE
Diagram research file diagram_IOHandler.php

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#11252]
Make a summary of what diagram_IOHandler.php does and affect, at the top of the document.

**Comment by a20jonda** [comment]
#11296 same file issue

**Comment by a20jonda** [comment]
Wrote a description in the top of the file on the current functioning stuff the file does and added small dividing descriptions for the looping and print:ing php for better readability. Then added a comment on the small and not declared javascript part which purpose is not yet understood.

**Comment by b20thelo** [comment]
Pull request merge 1 was denied since it does more than what was requested and also affects code structure. Will not be included in this week's merge.  Revert structural changes of code. Ask group leader in case of questions.
