### ISSUE TITLE
Diagram dugga types - Mockup

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11276]
Create mockup examples to #11232

**Comment by a19meram** [comment]
[Mockup issue #11232 -_ 11276.pdf](https://github.com/HGustavs/LenaSYS/files/8409330/Mockup.issue.11232.-_.11276.pdf)

**Comment by HGustavs** [comment]
I like to have the maximum amount of space for the diagram. At the same time we want to be able to:

* See the text at the same time as the diagram and while reading text still scrolling.
* Text description must allow scrolling if large.
* Accordion on left side of screen like variant B is my current best suggestion
* Vertical accordion for general description i.e. You should make the corresponding diagram from the text in the description beside the diagram etc etc.

Variant A

<img width="774" alt="Screenshot 2022-04-05 at 13 06 48" src="https://user-images.githubusercontent.com/6978801/161740921-1ffe234f-0b1d-48c5-a70d-0b94331deeb7.png">

Variant B

<img width="776" alt="Screenshot 2022-04-05 at 13 06 42" src="https://user-images.githubusercontent.com/6978801/161740927-49e8de33-4db1-4b4c-b990-44690e72c5b9.png">

**Comment by b20thelo** [comment]
Closed down as a new sub-issue was made by mistake and coding was already made in that issue branch. Handling of this issue continue in #11364.
