### ISSUE TITLE
Go trough all files under install folder and check that code standard is followed throughout the code

### ISSUE THREAD

**Issue by a19simru** [HGustavs/LenaSYS#11272]
@a20behta @c20adael Simon would like this issue.

**Comment by a19simru** [comment]
Note: not fix all files in install. Check and document all files in install if they need fixing.

**Comment by a19simru** [comment]
[AllCodeStandardIssuesInInstall.txt](https://github.com/HGustavs/LenaSYS/files/8425071/AllCodeStandardIssuesInInstall.txt)
My findings, basically all good, only very minor problems.

**Comment by a20behta** [comment]
documentation upploaded and ready for futere refactoring. 
Tag used for future use
