### ISSUE TITLE
showDugga.php only works sometimes.

### ISSUE THREAD

**Issue by a17nikjo** [HGustavs/LenaSYS#11284]
This seems to be related to $rand_idx = array_rand($versarr, 1);

Issue created based on problems found in issue #11240

**Comment by a17nikjo** [comment]
Solved an issue where the array passed to array_rand could be empty. Also merged the created if statement with the ifstatment bellow and removed $rand_idx since the value from array_rand was only used once.

**Comment by a20behta** [comment]
Merged into completed branch.
