### ISSUE TITLE
Codeviewer: Words in the description box get highlighted

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1128]
Words in the description box gets highlighted in the same way as the words in the code box.

![highlight in description box](https://cloud.githubusercontent.com/assets/11715509/7344830/adac8ac8-eccf-11e4-802d-01ebf0e734a3.png)

Is this supposed to happen?

**Comment by c12jenek** [comment]
Not unless it's a codebox from markdown, this is a bug that needs fixin', along with the highlighting of words containing the sequence var, e.g variable, variety or any other important word

**Comment by HGustavs** [comment]
I would say yes.

If I talk about a word in a description box i would like it to be highlighted in the same manner as in the code viewer.

It is not a bug.

**Comment by HGustavs** [comment]
Closing issue.
