### ISSUE TITLE
Icons are in the wrong direction in the "edit file" page

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11302]
The icons direction are not constent with the rest of the webpage in the "edit file" page. Press the pen icon in the code viewer and press the plus icon. 
![image](https://user-images.githubusercontent.com/81626616/161550557-5e59d4c1-8eae-4ddc-b948-9f918786b9eb.png)

**Comment by a18gusjo** [comment]
This might not be a bug. It seems like the direction of the icons only change when the window size is small and not only in the "edit file" - page. I will investigate further.

**Comment by a18gusjo** [comment]
![bug](https://user-images.githubusercontent.com/102605031/161727944-95ea7b56-86df-4005-9a0f-8076ab8649ab.png)

**Comment by a20willa** [comment]
This issue is not an issue! Closing it!
