### ISSUE TITLE
Pressing the reset button can cause a white box to appear

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11306]
Dragging all code windows to the top right and pressing the reset button will cause some strange white box. 

![image](https://user-images.githubusercontent.com/81626616/161558133-eff3df94-3f2d-42dc-81bd-71de4588390c.png)

**Comment by b20sebka** [comment]
managed to fix so the white box no longer appears when moving boxes and clicking reset at the expense of the white box almost always appearing when resizing the bottom box.

**Comment by b20sebka** [comment]
Fixed this issue only for template 4 which is used in "Javascript Example 2" as it was shown in the screenshot. Problem may occur in all other templates as well so this needs to be fixed there as well. I am on it.
