### ISSUE TITLE
Redundant scrollbar in previews of HTML

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11319]
There will always be a scrollbar next to the preview of an html. This does not need to be here as it can barely be moved. 
![image](https://user-images.githubusercontent.com/81626616/161619905-50ad1fa7-13a4-40f0-ac50-22c58653add7.png)

Note that this bug was found in the canvas environment. Use a frame to test this issue, and check if the same issue occurs without a frame too.

Extra note that in this case the most right one is the bug where the mouse hovers over!

**Comment by a19xinhu** [comment]
jag hitta inte issue som det visade i mac system.

**Comment by a20willa** [comment]
This issue could not be recreated after the merge today, and we have decided to close the issue instead.
