### ISSUE TITLE
make duggor more ux-friendly

### ISSUE THREAD

**Issue by a12majca** [HGustavs/LenaSYS#1131]
i think we could make some improvements here.

**Comment by a12majca** [comment]
I started with the dugga-instructions, they're now inside a box (which you can choose to show/hide), less line-width, added header, fixed some miss spelling. Also on dugga 2 you can now se the color white if that's the color you're asked to represent in hex-values.

**Comment by HGustavs** [comment]
I am unsure as to what the comment above means, so perhaps I am too verbose here and this is just a miss-understanding....

There is a problem with showing the colors as they look using html, since you can right click on the element and do "show computed styles" and get the right answer. So we opted for using images to show the colors.

The goal of the task is to come up with the hex of a color without aids.

We cant be too helpful.

**Comment by a12majca** [comment]
Regarding the color: I only added a 1px black border to the image to solve the problem if the image is the same color as the background  (for example white image and white background).  
![skarmavbild 2015-04-28 kl 10 59 24](https://cloud.githubusercontent.com/assets/11715536/7366445/92ea9558-ed98-11e4-8fcb-8f77f1e055ba.png)

**Comment by HGustavs** [comment]
Looks great.

What does the whole screen look like?

Is this more like a side-bar than a dialog?

If it is a side-bar I want it flat, if it is a dialog I want some shadows to indicate that it is at a higher level.

**Comment by a12majca** [comment]
just let us know how you want it and we will modify it. my though was simply that the instructions didn't need to take up all that space. maybe we can use the right side of the screen to show other things (such as a clock ticking etc..) right now it looks like this: 
![skarmavbild 2015-04-29 kl 09 28 38](https://cloud.githubusercontent.com/assets/11715536/7386746/7b6f058e-ee57-11e4-8d9d-5dba68c4e7e2.png)
![skarmavbild 2015-04-29 kl 09 29 11](https://cloud.githubusercontent.com/assets/11715536/7386748/7ffc005c-ee57-11e4-9df4-94af19436cac.png)
![bild 2](https://cloud.githubusercontent.com/assets/11715536/7386751/8651ec32-ee57-11e4-847e-e634380beaef.JPG)
![bild 1](https://cloud.githubusercontent.com/assets/11715536/7386753/89812abc-ee57-11e4-94e8-47b654cc523c.JPG)

**Comment by HGustavs** [comment]
It looks __really__ nice.

The only change I would make is to make the desktop version adapt to the width of the display more, so that it gets wider but narrower when compared to the screenshot.
