### ISSUE TITLE
Documentation of dark mode color scheme

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11314]
The wiki currently only reflects the "light" version of the webpage, but the dark mode is not yet documented. Because the entirety of lenasys has not yet implemented dark mode it would not be feasible to create an Image file such as the one the wiki currently use as the schema may be updated. As such, start by making a markdown document which lists all the current colors of dark mode, and upload it to the wiki. Follow the name convention of the [current schema ](https://github.com/HGustavs/LenaSYS/wiki/CodeViewer).

**Comment by a20willa** [comment]
This has been uploaded to the wiki

**Comment by a20andlj** [comment]
Matched colors against a scheme in codeviewer dark mode.
