### ISSUE TITLE
Fixing tag background "highlighting" for html

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11317]
For a lack of a better word, it seems like the "highlighting" of two tags are inconsistent when hovering over a tag. In some cases it works but in other it does not. A background is for example added in the screenshot below where it does work:

![image](https://user-images.githubusercontent.com/81626616/161616573-58477a01-9a8c-477f-aae9-8ab4cf60a97b.png)

So why not here?

![image](https://user-images.githubusercontent.com/81626616/161616635-dbcd3ac8-894c-49db-bb05-c69fdb9585fd.png)

Further more, only the bottom tag is only highlighted, not both. 

I've noticed that html updates when hovering over any tag, but only some act upon it? Look into this to see if it's an error.

**Comment by a20linth** [comment]
This issue is fixed in #12084

**Comment by b20sebka** [comment]
Duplicate issue that has been fixed.
