### ISSUE TITLE
Create interface for canvas link

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11323]
the interface for clicking needs to be created and placed onto the correct place

**Comment by c20adael** [comment]
relating to this issue #11230

**Comment by c20adael** [comment]
In this issue we need you to create the button in html. A temp svg can be used as the button for now. Another issue will handle the design of the svg

**Comment by a17nikjo** [comment]
In function confirmBox(operation, item = null) we can add functionallity for clicking the button.

Button Is Created in sectioned.js, it can easily be copied from the trashcan button edited to fit the purpose. Will require a new .svg icon.

**Comment by c20adael** [comment]
new issue adding functionality. #11377

**Comment by a17nikjo** [comment]
Done in sectioned.php
-Created Dialog for displaying generating link aswell as promting user that it was pasted to clipboard.

Done in sectioned.js
-Created new button left of the cogwheel (icon being made seperate issue). Search for "Generate Canvas Link Button"
-Created function for opening/closing dialog. When opening also changes the link text to desired string. Recommended add the canvas link functionallity too this function. Search for "showCanvasLinkBox".

**Comment by HGustavs** [comment]
Do we have a mock up of this interface?

**Comment by a17nikjo** [comment]
Dialog was made using same standard as trashcans dialog. Icon was given a seperate issue.

Attaching image of what it currently looks like
![NewButton](https://user-images.githubusercontent.com/102593975/161967481-8844913a-8f6e-4015-a07c-99e26d388b64.png)
![Dialog](https://user-images.githubusercontent.com/102593975/161967485-f5c5555f-c10f-4f4a-81a5-cb651531aee3.png)
.

**Comment by a17nikjo** [comment]
Added icon made in issue #11375 and fixed so the link gets pasted to user clipboard.

Still need to get the actuall link, this will be solved in a seperate issue.
