### ISSUE TITLE
Moving timer.js and clickcounter.js too dugga.js

### ISSUE THREAD

**Issue by a17nikjo** [HGustavs/LenaSYS#11325]
When checking if the files timer.js and clickcounter.js existed in issue #1911, it was found out that they had already been removed. However they are still referenced by the following files. 
duggaed.php
showDugga.php
testDugga.php
validateHash.php

Check if this causes any problems and if they can just be removed / commented out.

**Comment by a17nikjo** [comment]
Files appears to exist, on hold while working on issue #1911.

**Comment by a17nikjo** [comment]
In issue #1911 we found out the files are still in use but could be moved therefor issue changed to moving, we still have to make sure it works afterwards to make sure backwards compatability. We also also have to make sure all places that implement timer.js and clickcounter.js implement dugga.js.

**Comment by a17nikjo** [comment]
Possible sulotion of migrating files done. Needs futher testing before being merged.
timer.js and clickcounter.js content moved into dugga.js.
duggaed.php
showDugga.php
testDugga.php
validateHash.php
All implement dugga.js however still needs testing to make sure everything works after migration.

Testing currently not posssible due to lack of duggas. On hold until testing can be done.

**Comment by a20vicad** [comment]
After migration, initally everything appears to function properly. Keeping an eye on it for further testing.

**Comment by a20behta** [comment]
merged into master during weekly merge
