### ISSUE TITLE
Webserver installation

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11330]
Configuration of webserver

**Comment by a20behta** [comment]
@a16linas check file Lenasys/shared/sql/init_db.sql

**Comment by a16linas** [comment]
Issue has been solved. Root user needed proper credentials in the database. Now we're able to create and link database to websever. Use localhost as hostname and root username with the password given by the teachers

**Comment by a16linas** [comment]
Issue is still present, the shared webserver project.webug.his.se cannot initialize the database.

**Comment by a16linas** [comment]
Issue has been solved. Apparently the init.db does not handle dashes (-) very well when trying to create a new database in install.php. Also changed the default directory for when accessing the webserver so it starts at the top of the LenaSYS repository.
