### ISSUE TITLE
Illogical if statement in dugga.js

### ISSUE THREAD

**Issue by a20sacka** [HGustavs/LenaSYS#11349]
checks for difference on variables already set to the same on the line above it 
Lines in question are around 984 and 987.

apara[key] is set to the same as old, then immediately after checks for a difference between the two

![image](https://user-images.githubusercontent.com/102584289/161723408-bc9c4411-a171-46d9-9bcd-2cdaa6fbad19.png)

**Comment by a20behta** [comment]
Merged and completed
