### ISSUE TITLE
Clicking the "Zoom IN" and "Zoom OUT" buttons in Diagram Dugga zooms from origo.

### ISSUE THREAD

**Issue by a20edwth** [HGustavs/LenaSYS#11342]
The buttons' zoom points are in the origo(top left corner) rather than in the center of the screen.

**Comment by b20thelo** [comment]
Tested on the webserver. Confirmed that it works as it should.

**Comment by b20thelo** [comment]
While testing this feature we agreed that it was better than the existing solution from before, but still isn't the final solution. Needs a bit more tweaking. 

The feature uses the screen width as a coordinate instead of counting the actual coordinate in the center of the current screen.
