### ISSUE TITLE
Duplicate plus sign in course editor for teachers

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11357]
The plus sign at the top may not be there as it's function is identical to the bottom one. 
![image](https://user-images.githubusercontent.com/81626616/161745327-21b1ac2e-5457-4739-b9b1-e46c6f481ab8.png)

**Comment by HGustavs** [comment]
It was done this way since some people in the previous course years liked it this way. Unclear if it was students or teachers.... that is the reason for this duplicate functionality. No problem from my end, as long as both buttons run exactly the same code.
