### ISSUE TITLE
Diagram: Add dugga description on left side of diagram. 

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#11364]
Teacher should be available to create a diagram dugga.

// Comment from @HGustavs moved here from issue 11276 (this issue is closed)
I like to have the maximum amount of space for the diagram. At the same time we want to be able to:

* See the text at the same time as the diagram and while reading text still scrolling.
* Text description must allow scrolling if large.
* Accordion on left side of screen like variant B is my current best suggestion
* Vertical accordion for general description i.e. You should make the corresponding diagram from the text in the description beside the diagram etc etc.

Variant A

<img width="774" alt="Screenshot 2022-04-05 at 13 06 48" src="https://user-images.githubusercontent.com/6978801/161740921-1ffe234f-0b1d-48c5-a70d-0b94331deeb7.png">

Variant B

<img width="776" alt="Screenshot 2022-04-05 at 13 06 42" src="https://user-images.githubusercontent.com/6978801/161740927-49e8de33-4db1-4b4c-b990-44690e72c5b9.png">

**Comment by HGustavs** [comment]
I am thinking that we do this through dugga parameters e.g. for file upload dugga we specify that we use a filelinlk.

```
{"type":"md","filelink":"Deluppgift5_Sammansattning_2016.md", "submissions":[{"fieldname":"Ind-sammansattning-report","type":"pdf", "instruction":"Upload your report in PDF format here."},{"fieldname":"Ind-sammansattning-zip","type":"zip", "instruction":"Upload your zipped files here."}]}
```

So something like "type":"EER","Errors":"none" ... for EER type diagram without showing errors.

**Comment by b20thelo** [comment]
Comment from HGustav was deleted and moved to issue #11401

**Comment by a19meram** [comment]
One or more problems with some code! More code research needed to make the muckups possible

**Comment by i19matla** [comment]
See Merons comment, some issues with the system.

**Comment by i19matla** [comment]
Made some findings about the problem, for example in feedback_dugga.html As we were told the instruction text is supposed to come from the section "Show files" in the system (logged in) but the instruction text is coded directly in for example feedback_dugga.html Teacher instructions is probably needed before continuation on this issue for some explanation how they work with the system and how it is supposed to work.

**Comment by b19karhj** [comment]
Will try and get a hold of @HGustavs  tomorrow or as soon as possible to sort this out so the implementation can continue.

**Comment by b20thelo** [comment]
Pull request #11519 was rejected as the description didn't show up.

**Comment by a19meram** [comment]
new pullrequest uppdated. It should show description left side now. pull request #11595
