### ISSUE TITLE
Contribution database installation

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11378]
The test data is given however there is no information about how the database can be integrated into the system. 

@HGustavs has said that there is a specific name for the webserver. 

Research is required for what that name is and how integration is possible.
Upload documentation onto this issue for future development. 
Update Wiki for future users/devs

**Comment by HGustavs** [comment]
The data is read on line 21 in the contributionservice.php file.

```
log_db = new PDO('sqlite:..\..\BGHdata_2021_05.db');
```

The question is however how we can support more than one file, such as allowing support for different students in the mobile development course or final year projects. In that case each repository has one file.

**Comment by a20sacka** [comment]
Instructions on how to get contributions.php to load:

* acquire the "GHdata_Projekt.db" file which you will receive by asking the person responsible for the file(will not get uploaded online as it is a data protection law issue).

* Navigate to the top directory of your **LenaSYS** project

* Put the "GHdata_Projekt.db" into the directory but renamed to "BGHdata_2021_05.db". The top directory should look like the picture below: 
![image](https://user-images.githubusercontent.com/102584289/161967103-0c0e9edc-6b35-465d-a7cb-64808640c7db.png)

* Log in as a user able to view data on contribution(not guest) can for example be the user **Toddler**.

* You can now navigate to contribution.php and load the page.
