### ISSUE TITLE
Documentation on the code standard for the php files in the shared folder

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11376]
Go through the files an check if the code standard is being followed.

**Comment by a19simru** [comment]
[AllCodeStandardIssuesInInstallPhpFilesOnly.txt](https://github.com/HGustavs/LenaSYS/files/8426368/AllCodeStandardIssuesInInstallPhpFilesOnly.txt)
Documentation complete. Really not allot to report. A lot of these files were completely flawless.
