### ISSUE TITLE
Investigate why null is recieved as hash/hash password when saving dugga

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11373]
This happened specifically on the dugga 1 in demo-course and has not been tested elsewhere.
http://project-g3.webug.his.se/DuggaSys/showDugga.php?did=22&courseid=1894&coursename=Demo-Course&coursevers=52432&moment=3011&segment=3001&highscoremode=1&comment=null&deadline=2020-06-30%2000:00:00&cid=1894

![image](https://user-images.githubusercontent.com/80856978/161915237-47f127db-2d44-4db2-8c4c-92d637d40a47.png)

**Comment by b20eripe** [comment]
@c20adael I can investigate this

**Comment by HGustavs** [comment]
Could it be that the code returns before the answer is received?

On very fast or very slow networks this may occur if we are processing the data before it arrives or if it not arrives on time.

**Comment by a20behta** [comment]
@b20eripe You can begin with this issue. 
The issue occured on a local webserver and thereby the network should not affect the results. 

check if the changes are saved and if so where and if they can be loaded.

**Comment by b20eripe** [comment]
Found out some errors in dugga.js. New issue created on that subject #11433. This one is put on hold until that one is solved.

**Comment by b20eripe** [comment]
![Skärmbild från 2022-04-07 15-14-17](https://user-images.githubusercontent.com/102593527/162207660-b7bddcd3-3579-4b81-8117-7fa43a0d55cc.png)
![Skärmbild från 2022-04-07 15-14-55](https://user-images.githubusercontent.com/102593527/162207669-fdcb10c5-b7e8-402b-a8d1-69a61e971481.png)

Hash setting function was commented out. Removing the comment makes the hashing working again

**Comment by a20behta** [comment]
changes merged are in group branch
