### ISSUE TITLE
Need to Create a SVG for the Copy link issue

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11375]
#11323 #11230 These two issues relate to this

**Comment by a19simru** [comment]
![CopyIcon-Transparent](https://user-images.githubusercontent.com/102595769/161939982-2738f3f4-1d48-46a7-8bf3-f64d0dcd6e39.svg)
@c20adael @a20behta The finished copy icon with transparent background for downloading stuff from LeanSYS.

**Comment by a19simru** [comment]
![CopyIcon-Transparent2 0](https://user-images.githubusercontent.com/102595769/161943308-2d685b17-5f44-4511-85cf-c9473b801e28.svg)
@c20adael @a20behta I made a slightly more minimalistic version. The previous one may have been a bit high detail for such a small image.

**Comment by c20adael** [comment]
> ![CopyIcon-Transparent2 0](https://user-images.githubusercontent.com/102595769/161943308-2d685b17-5f44-4511-85cf-c9473b801e28.svg) @c20adael @a20behta I made a slightly more minimalistic version. The previous one may have been a bit high detail for such a small image.

yes this one looks good. Use this one in issue #11323

**Comment by a20behta** [comment]
this has been accepted and implemented
