### ISSUE TITLE
QuizID not saved when submitting dugga result

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1137]
When saving a duggaresult the quizID is not saved. 
Example:
If doing dugga1, the column "quiz" in userAnswer should be set to 1. As it is now it is null.

**Comment by a13chrju** [comment]
in the userAnswer table the attribute "quiz"  has a foreign key that references the ID of the quiz, the id of each quiz is incremented by one everytime it gets created so it should be a specific value for the same dugga type, it's only referenced to the id of the test.

**Comment by b12erijo** [comment]
Shouldn't each entry in userAnswer be bound to a specific quiz? I'm not sure i get your point.

**Comment by a13chrju** [comment]
yes but i'm just saying that all Useranswers if for example. dugga1 shouldn't have a 1 in quizID since the attribute is a primary key in the quiz table...

**Comment by b12erijo** [comment]
Yes that is true, i misinterpreted the purpose of the quiz table at first.

**Comment by b12erijo** [comment]
Thanks for pointing it out :)

**Comment by a13chrju** [comment]
it's cool :)
