### ISSUE TITLE
Reset button does not update zoom message

### ISSUE THREAD

**Issue by a20edwth** [HGustavs/LenaSYS#11386]
Reset button does not update zoom-message-box.
Before pressing reset button:
![9346738664486dd51c698182030e77e9](https://user-images.githubusercontent.com/102611046/161960073-2761dbf8-d4c8-437c-89a9-e74365a51aa6.png)
After pressing reset button:
![d476f0c72d41c6a8d0595fa5788f420a](https://user-images.githubusercontent.com/102611046/161960095-97b3a878-f747-454f-95dd-4dee3919f8c3.png)

**Comment by b20thelo** [comment]
The problem here was solved by solution #11058. Therefore we close this issue.
