### ISSUE TITLE
Delete button in elements on canvas in diagram

### ISSUE THREAD

**Issue by a20edwth** [HGustavs/LenaSYS#11387]
Deleting a element or line in the diagram can only be done through a keyboard press ("delete").  
Adding a delete button in the toolbar supports mouse interaction. (using the diagram without a keyboard)

**Comment by a20edwth** [comment]
Suggested visual representation of the delete button in the options menu of a element:
![11475895909ea6f62c8c136a9dec1836](https://user-images.githubusercontent.com/102611046/162008645-64d7f935-856f-4cd4-a5e7-38435ff379b7.png)

**Comment by b20thelo** [comment]
@HGustavs What are your opinions on the suggestion above for a physical button to delete objects and not just the delete button on the keyboard?

**Comment by HGustavs** [comment]
Not a bad idea. Question is if this is the best solution.

I would like something that would not require opening the tool bar to know that the delete button is present.

How about a cross icon at the top right corner of any selection (one or more elements).


<img width="478" alt="Screenshot 2022-04-06 at 22 49 53" src="https://user-images.githubusercontent.com/6978801/162068529-d92ca0c0-21e9-44f3-b55c-8f062c2cdec8.png">

If one clicks the cross the selected items would be deleted. This way no menu needs to be opened to delete the item. We can also delete the items with minimal mouse movement.

**Comment by a20edwth** [comment]
@b19karhj @b20thelo Video that shows the design and functionality of the delete button:
https://user-images.githubusercontent.com/102611046/162414596-c871de78-09ec-43e2-8244-050a8b305acd.mp4

**Comment by b19karhj** [comment]
@a20edwth Looks like a very good solution.

**Comment by b19karhj** [comment]
Remove the dotted frame around the object but keep the X.

**Comment by b19karhj** [comment]
The X need to be larger. And the placement should be like this 
![bild](https://user-images.githubusercontent.com/81624541/164230255-343ebae3-6e13-4b10-ad87-355def6b674b.png)

**Comment by b20thelo** [comment]
Closed as solution was approved by Henrik
