### ISSUE TITLE
Icons for diagram isn't uniform and doesn't show off features in a good way

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11395]
![image](https://user-images.githubusercontent.com/81772705/161987795-a3669a0e-122b-46f8-b720-567c39f8018d.png)
- Lines in icons have different thicknesses (for example zoom reset)
- There are two grid icons with different grids.
- A4 in icon for toggle A4 template is very small and the lines are very thin
- New suggestion for redirect camera to center
- Toggle forward/backward icons doesn't follow standards for redo undo icons
- Toggle replay icon looks like a refresh icon which can be confussing. 

Create mockup for new set of icons.

**Comment by HGustavs** [comment]
Think about homologating with the rest of Lenasys not just the local module.

**Comment by a20samul** [comment]
Suggestion so far.

<img width="37" alt="suggestion" src="https://user-images.githubusercontent.com/81613484/162044611-2a4ad2a8-7288-4712-aa0b-95784a62425f.png">

**Comment by HGustavs** [comment]
This looks better imho.

**Comment by a20samul** [comment]
Progression thus far. The lines have been properly sized and the icons have been updated to further match their intended functionality. 

<img width="34" alt="s2" src="https://user-images.githubusercontent.com/81613484/162196832-93951577-fa78-4c46-bf5c-8cd45009e4d0.png">
