### ISSUE TITLE
Create a mockup for drag and dropping into code viewer

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11397]
Reference to #7768. There should be type of mockup to try if the drag and drop feature can be implemented. This mockup should simply be how it would look if we drag and drop something into the code viewer. **The actual implementation is not needed for this issue!!!** 

Two things should happen when a file is dragged into the code viewer: 
1. We need to a-knowledge it, perhaps some kind of "border" or similar when hovering. For example, in github a green border will wrap around the comment window if a file is draged into it.
2. We then need to show some kind of dialog to choose what type of file we just draged in (txt, php, js, etc. )

I should mention that this issue is highly dependant on the result of #7768. We may check first that it may be possible, otherwise this issue will not be necessary.

**Comment by a20andlj** [comment]
To simple mockups on how it could look like if a drag and drop function would be implemented into LenaSYS

Mockup png1:
![mockup_drag_n_drop_LenaSYS](https://user-images.githubusercontent.com/82219160/162419854-34b24b0c-8e10-4762-94b0-257c8fae52c0.png)

Mockup png2:
![mockup_drag_n_drop_LenaSYS_alert](https://user-images.githubusercontent.com/82219160/162420059-65191d06-5930-4cd1-b3f0-f67d30799799.png)

**Comment by a20willa** [comment]
We now have more info on how this might be viable. A similar function has been made in #11475 pull request, where the basic function is implemented. The steps of putting the contents of file into the codeviewer needs to be added through other means, but this provides a solution to actually get the file into the browser.  

The code can be found in duggaed.js and duggaed.php

**Comment by a20willa** [comment]
These are the supported file types which will should be accepted when dropping into codeviewer. 
![image](https://user-images.githubusercontent.com/81626616/164400377-1a18c653-4269-4a2e-9a6b-81995f190397.png)

**Comment by a20willa** [comment]
The mockup is complete, and thus the issue will be closed.

**Comment by a20sarle** [comment]
@HGustavs What does the customer think about the mock-up? Should this be implemented or is there a need for futher mock-ups and/or other wishes?

**Comment by a20willa** [comment]
Customer was happy with said mockup. Reference to https://github.com/HGustavs/LenaSYS/issues/7768.
