### ISSUE TITLE
Create the visual component for last time teacher accessed submissions in resulted.php

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11393]
this issue is created from the bigger issue #11113

**Comment by c20adael** [comment]
What i want you to do is to create a new column that is supposed to hold the last visited value.
@a20novra

**Comment by a20novra** [comment]
![4](https://user-images.githubusercontent.com/81618150/162162390-d860c797-3018-4d1b-8e7a-cd63bc9d4fea.jpg)
Teacher Visited column is added.

**Comment by a20behta** [comment]
visual component added and works as expected
