### ISSUE TITLE
Diagram: Research for how to fix export of diagram for teacher

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11401]
Teachers should be able to create a diagram and then export it to upload into a new dugga through JSON format. 

Moved comment from Henrik into this issue instead.
"I am thinking that we do this through dugga parameters e.g. for file upload dugga we specify that we use a filelinlk.

```
{"type":"md","filelink":"Deluppgift5_Sammansattning_2016.md", "submissions":[{"fieldname":"Ind-sammansattning-report","type":"pdf", "instruction":"Upload your report in PDF format here."},{"fieldname":"Ind-sammansattning-zip","type":"zip", "instruction":"Upload your zipped files here."}]}
```

So something like "type":"EER","Errors":"none" ... for EER type diagram without showing errors."

**Comment by HGustavs** [comment]
Yes, i am thinking that any imported diagram is part of this structure, together with any parameters such as showing drawing errors.

**Comment by HGustavs** [comment]
so somewhere in this structure it would day: diagram:"here we would paste the exported json data"

The exporter could even generate this data on its own during the export, reducing the need for hands-on editing of the test.

**Comment by a20micro** [comment]
So if I understand this correctly, for the teacher, there should be a feature to input a .Json file, containing the data of a diagram, which then is translated into a diagram in the diagram view?

**Comment by b19karhj** [comment]
@a20micro Yes that's is how I have understood it.

**Comment by a20micro** [comment]
#11477 has been created as a result of dividing this issue up.
#11478 has been created as a result of dividing this issue up.

Further issuing will be required as these two issues are completed.
