### ISSUE TITLE
Create html examples

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11408]
Reference to #11402. We need to create some html examples which cover the different areas we might need to test. Try to cover typical html code and how it would look. 

**Check where you are to place these examples in the original issue!**

**Comment by a20andlj** [comment]
To solve this issue, it must first be solved so that the files that are uploaded are saved and can be accessed even after a merge.

**Comment by a20sarle** [comment]
Window users should be assigned due to permission settings.

**Comment by b20sebka** [comment]
Was fixed in #11402
