### ISSUE TITLE
Create mockups of how the contribution.php could change repositories.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11407]
this is a issue created from the bigger issue #11228

**Comment by b20hanwa** [comment]
![MockupTabs](https://user-images.githubusercontent.com/81630271/162193047-f3aa4948-f9ce-4ccb-9d9b-c842cc7e0209.png)

Mockup of tabs for different repositories. When user howers over one of the tabs for repositories, all of the tabs for repositories appears. User can then click on desired tab.

**Comment by b20hanwa** [comment]
![MockupChoosing](https://user-images.githubusercontent.com/81630271/162194454-7d34b0d6-4b83-4e01-9cad-d05d2c19a08f.png)

Mockup of when user has clicked the tab for last years repositories. Now a tab for choosing year appers, and the user can choose desired year.

**Comment by b20hanwa** [comment]
Are these two mockups a representation of what you wanted for the contribution page when it comes to choosing repositories? @HGustavs

**Comment by a20behta** [comment]
prefer tabs of some sort and drop down in some form.
tabs for course followed by dropdown for the year, 
current year being the standard.

**Comment by c20adael** [comment]
Yess this looks good.
