### ISSUE TITLE
Contributioncontainer div in contribution.js does not generate for some devices. 

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11400]
Research why this is happening.

related installation #11378

Can you post pictures on the differences when it works and when it does not.

**Comment by a20caros** [comment]
![image](https://user-images.githubusercontent.com/81676918/162140868-e3b236de-6882-419b-b9a9-81267c4d3a45.png)
A picture of a device that not generate the contributionscontainer div

**Comment by a20novra** [comment]
![400](https://user-images.githubusercontent.com/81618150/162142925-b4aab5f1-2473-48da-8087-85a95a3c63b6.jpg)
A picture of a device that generate the contributionscontainer div

**Comment by a20behta** [comment]
issue fixed and merged into master
