### ISSUE TITLE
Creating login page and pop up for contribuiton

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11416]
TLDR: Mockup implemented and created as a pop up if someone who is not logged in wants to access contribution.

#11415 required to be accepted before development can being.

Details: when a user tires to access  DuggaSys/contribution.php it requires them to be logged in. If they are not logged in the user will be promted to log in. implement that pop up based on mock up accepted.

**Comment by a20behta** [comment]
related to issue #11223

**Comment by c20adael** [comment]
@a20sacka When @a20caros has updated #11415 you should be good to go.

**Comment by a20sacka** [comment]
Added functionality that wasnt documented:
The exit(big red) button that leaves the login screen now redirects you to previous page to avoid getting an empty contribution page.

**Comment by a20sacka** [comment]
Made it so if a user isnt logged in they will get a pop up that requires them to log in and then get contribution loaded. If they are already logged in they will not get the popup and get contribution loaded directly.

Will now work on the "github user part"

**Comment by a20sacka** [comment]
now working from branch G3-2022-W4-#11416 after merge https://github.com/HGustavs/LenaSYS/tree/G3-2022-W4-%2311416
