### ISSUE TITLE
Problem when collapsing nested squirrely brackets

### ISSUE THREAD

**Issue by a20linth** [HGustavs/LenaSYS#11428]
An issue occurs when a pair of squirrely brackets gets collapsed with a nested pair of collapsed squirrely brackets inside of it. When the brackets are reopened, the pair of nested squirrely brackets should still be closed but they are not.

https://user-images.githubusercontent.com/102609651/162171720-1146fa27-1f2f-4054-a5bd-6102b06bc02e.mp4

**Comment by HGustavs** [comment]
I think this issue has been partially fixed in an issue from a previous year.

**Comment by a19xinhu** [comment]
I found the function which change the "display" to hide the code. I can also write the condition about checking the code which row have class "closed-block" already. The question now is i don't know how to make the computer know which rows need to keep "display:none", because the function run when you click the button. It only knows the block point to the button you clicked.

**Comment by a20sarle** [comment]
> I think this issue has been partially fixed in an issue from a previous year.

@HGustavs Do you happen to know or have a guess of what the issue title might have been?

**Comment by a20sarle** [comment]
> I found the function which change the "display" to hide the code. I can also write the condition about checking the code which row have class "closed-block" already. The question now is i don't know how to make the computer know which rows need to keep "display:none", because the function run when you click the button. It only knows the block point to the button you clicked.

What was the function name and in what files did you work in?

**Comment by a20sarle** [comment]
Reference Implement collapsible html tags #11369.

**Comment by a20sarle** [comment]
More and summed up documentation can be found in this commit: https://github.com/HGustavs/LenaSYS/commit/27ae08c46e081a41f5fad0cfdf85537f1c51534b .

The last commit to G2-2022-W6-#11428 neutralised the other commits and next one to pick up on this issue and if using the same branch is starting from a cloned version of G2-2022-#merge6 where nothing has changed.
