### ISSUE TITLE
Add functionality to the column that should hold last visited date in resulted.php

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11424]
The column has been added on to the site #11393. continue to add the functionality so that the last visited date is shown for each entry. 

This is part of the issue #11113

**Comment by a20novra** [comment]
i researched in resulted.js, resulted.php,  and resultedservice.php. I found out that we should create a new column in userAnswer table to save teachers last visited time value. When we are done with this part then we can show it on the table as we want

**Comment by a20novra** [comment]
changed SELECT query that islocated in resultedService.php to fetch data that exist in last_Time_techer_visited column (LINE 29)

**Comment by a20novra** [comment]
![0](https://user-images.githubusercontent.com/81618150/162918575-23cfef3a-929c-49d8-bd8c-837e80626044.jpg)

**Comment by a20behta** [comment]
merged into weekly branch looks good
