### ISSUE TITLE
When creating a new code example and choosing a new template, the example will not load

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11427]
If a new example is created and then a template is picked, the page does not update correctly and is left blank until the edit example button it pressed and any setting is changed. Once something has been changed everything will work as normal.

This issue is caused by a fix in #11422.

**Comment by HGustavs** [comment]
Normally there is some kind of an error message in the console if execution stops.

**Comment by a20patpe** [comment]
Here is a screenshot of the error message.
![image](https://user-images.githubusercontent.com/102600690/162211901-09f37e77-0090-4dfb-b697-b89df238afb1.png)

However this piece of code is functional for ever example, including the newly created once(after the settings of them have been changed).

**Comment by a20patpe** [comment]
To illustrate the issue:
![Animation](https://user-images.githubusercontent.com/102600690/162216677-6192f46b-338c-4991-9920-72ebda628021.gif)

**Comment by a20willa** [comment]
Fixed in #11422.

**Comment by a20sarle** [comment]
@a20willa What needs to be done in order to continue with this issue and remove the "on hold" label?

**Comment by a20willa** [comment]
This issue is fixed and thus will be closed.
