### ISSUE TITLE
Diagram:Create a working exit button for the “replay” mode.

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#11442]
At the moment there is only one way to exit the replay mode (where you can check each step of the user's changes to the diagram), and that is by pressing the escape key.

![bild](https://user-images.githubusercontent.com/81624541/162205989-d9a5b162-ed5b-48e2-950e-5db3ff54546a.png)

Make an exit button which takes you back to the same step as escape does.

**Comment by b19karhj** [comment]
Redesign the replay button as its very hard to see what it does just by looking at it.

**Comment by a20samul** [comment]
Created a working exit button with intended functionality present and modified the replay-button icon.

<img width="257" alt="exitButton" src="https://user-images.githubusercontent.com/81613484/162401848-c06ef409-1161-4319-90b0-c211b6c656ff.png">
