### ISSUE TITLE
The yellow plus button on duggaed.php seems to be blocking the pen icon

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11448]
Right next to the yellow button there is something blocking the pen icon. This is to the right of the yellow button. This needs to ne investigated and fixed.

<img width="960" alt="duggaedblockering" src="https://user-images.githubusercontent.com/80856978/162378608-1240398e-8974-4772-a282-899c029a48a8.png">

**Comment by a20vicad** [comment]
Margin should be used when separating blocks on the outside, padding for inside a block to move content from the edges. Changing to marging -> It no longer covers other buttons.
