### ISSUE TITLE
Diagram: Better tooltip description for the diagram tools.

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#11440]
Some of the descriptions of the tooltips are a bit vague and not true.
For example: The zoom in icon description is "increases size of all elements" which is not true and a bit confusing.

![bild](https://user-images.githubusercontent.com/81624541/162202086-f8bf1c33-6bd6-46d4-9187-f52982bca811.png)

Make a better tool description for:
Zoom in
Zoom out
Zoom reset
Toggle snap to grid
Toggle step forward
Toggle step backwards
Toggle replay

**Comment by a20edwth** [comment]
Changed tooltip descriptions of the toolbar and added tooltip descriptions to the buttons in replay-mode.

Instructions for testing:
1) Click "Demo-Course"
2) Click "Diagram Dugga"
3) Hover over buttons in toolbar and buttons in replay-mode and read descriptions.

**Comment by b20thelo** [comment]
Closing as last update from Edwin was approved and pushed.
