### ISSUE TITLE
Ruler and A4 template does not match well/ruler does not show a known unit of length.

### ISSUE THREAD

**Issue by a20jonda** [HGustavs/LenaSYS#11453]
![image](https://user-images.githubusercontent.com/102598258/162387291-5c82296d-9d1b-47d5-949b-d3a711ee844e.png)

**Comment by a20jonda** [comment]
set ruler to millimeter

**Comment by a20jonda** [comment]
The A4 measurements will also be changed to match ruler.

**Comment by b20thelo** [comment]
The grid should be aligned to cm marks.
