### ISSUE TITLE
Box selection selects all elements touching the box, which create inconvenience.

### ISSUE THREAD

**Issue by a20jonda** [HGustavs/LenaSYS#11451]
![image](https://user-images.githubusercontent.com/102598258/162381415-d941dac5-6f9d-40c1-b095-42d6a7bb0f4f.png)

**Comment by a20jonda** [comment]
Alla element som är helt täckta borde bara väljas istället

**Comment by a19hammi** [comment]
_Imagine this is a whispering bird_
So, the reason why it selects the lines is so that when you press the `delete` button the lines are ALSO deleted from the diagram. Otherwise, you will only delete the elements which will cause some weird shinanigans.
_Now imagine the bird flew away_
