### ISSUE TITLE
Deselect a single object in Box selection mode in Diagrams

### ISSUE THREAD

**Issue by b20matad** [HGustavs/LenaSYS#11455]
When multiple objects are selected you cannot deselect a specific element by pressing ctrl+mouse1 while in Box-selection.
<img width="497" alt="image" src="https://user-images.githubusercontent.com/102598238/162390876-66f5912a-59e0-4ab4-95ab-ea71b1bc62f7.png">

**Comment by a20jacmi** [comment]
After some research we found out that deselect was already in place, but with "alt" pressed. We're looking into a solution to select and deselect with "ctrl".

**Comment by b20thelo** [comment]
@b20matad or @a20jacmi . Please add a comment with the solution that you came up with here. It will make it easier for testing. It can be similar to the comment written in the pull request but a bit more detailed.

**Comment by b20matad** [comment]
Enabled the posibility to select/deselect multiple elements when pressing "ctrl"+"mouse1". The issue concerned "box selection mode" but now works for all mouse modes.

This is done by adding an else if, which deselects an element if it's already selected when clicked, to two different functions: "updateSelectedLine()" and "updateSelection". And also a small change to an if-statement in the mouse-event function "ddown()" which allows "updateselection()" to run if an element is already selected. when clicked.
