### ISSUE TITLE
Dugga name missing

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#11468]
![Screenshot 2022-04-08 at 11 21 48](https://user-images.githubusercontent.com/4948661/162406957-75cb03e8-bf52-4e92-be8d-d7b6d98a9f54.png)

When opening bit-dugga the dugga is named "undefined".

Does this problem occur in more duggas? I think an investigation could be in order.

**Comment by c20adael** [comment]
Research where the dugga is suppose to get this data from and why it doesn't get it now.

**Comment by a20vicad** [comment]
I can have a look at it @c20adael

**Comment by a20vicad** [comment]
![image](https://user-images.githubusercontent.com/102599327/162703509-98cf17d1-d84b-4105-bf74-1946a4f91aa8.png)
The name of the dugga can now be seen in the instructions tab.
![image](https://user-images.githubusercontent.com/102599327/162703701-a2c5a9a5-8194-4cae-a3ab-6c39ec0a8721.png)
Also in the top-bar-thingy.

**Comment by a20behta** [comment]
weekly merged done and included into master. tests done,
