### ISSUE TITLE
Holding down backwards / forward button in a dugga can show the wrong examples

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11466]
When holding down the backward button, if a dugga is the last or the first one in the list, the dugga will be shown multiple times until there is 5 examples. 
![image](https://user-images.githubusercontent.com/81626616/162404029-798367f0-3648-44d2-84e2-94971c65e262.png)

**Comment by a20patpe** [comment]
Accidentally pushed the solution to this into the group branch, testing was done retroactively and the fix worked.
The commit can be found at: 033303ce53f9f8b08e578586398744cbacf87f40

**Comment by a20sarle** [comment]
Issue has been fixed. Closing.
