### ISSUE TITLE
Allowing .json files to be saved to database

### ISSUE THREAD

**Issue by a20micro** [HGustavs/LenaSYS#11478]
as part of issue #11401 it should be possible to select an existing .json diagram file as an initial diagram - on load. Currently, JSON files are not part of the allowed files.

![CurrentAllowedTypes](https://user-images.githubusercontent.com/95532115/162680562-e94e287d-43a8-4b2d-8a57-4475a629cdf9.png)

.json files should be allowed for both saving and fetching to/from the database.

Note: Testability is limited on local machines as the database created by user on installation of LenaSYS probably doesn't match the hard-coded name the system is currently looking for.

**Comment by b20thelo** [comment]
Included on latest weekly merge and pushed to master
