### ISSUE TITLE
CodeViewer: Template 3, wrong default value?

### ISSUE THREAD

**Issue by a13alfbe** [HGustavs/LenaSYS#1147]
The default height for box 1 in Template 3 seems to be wrong
![untitled](https://cloud.githubusercontent.com/assets/11715493/7347238/c7e8dd8a-ece6-11e4-8b35-32218c41c9a2.png)

**Comment by a13jorla** [comment]
Does not seem to be a issue at this time. Seem to be fixed (hight: -webkit-calc(100%);). But the resizing seems to breakup sometimes in firefox.
