### ISSUE TITLE
Creating a line on a attribute with itself should not be possible

### ISSUE THREAD

**Issue by a20edwth** [HGustavs/LenaSYS#11479]
Currently it is not possible to create a line on the same entity, but it is possible to create a line on the same attribute

Not possible on entities:

https://user-images.githubusercontent.com/102611046/162441783-7f035e1b-d6f0-4dc2-880f-ae3eadeb6e93.mov

Possible on attributes:

https://user-images.githubusercontent.com/102611046/162441828-0724dc8e-97d0-47b2-9701-a515ae6c6de2.mov

It is not just a wrong message but an existing object:

https://user-images.githubusercontent.com/102611046/162441853-92bf0323-f630-4dad-808f-af0b818a3332.mov

**Comment by b20thelo** [comment]
Tested on live-server, issue handled well and an error message displayed when a element tries to make a link between itself. Semantical and syntax of the code are all good! 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/77247277/162744894-30d0ad82-3547-451a-89cb-264b7313e3ed.png">
