### ISSUE TITLE
Edit button in mobile view?

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11487]
Does the teachers actually use the edit button in mobile view inside the codeviewer? If not, we could remove the icon, since it would be very clunky to change code in your phone.

The customer may be asked here, incase it is still needed.

**Comment by b20idawa** [comment]
This is what LenaSYS looks like today in mobileview before the edit button has been removed.


<img width="292" alt="Skärmavbild 2022-04-13 kl  14 09 59" src="https://user-images.githubusercontent.com/81676911/163177991-9a2eeee0-18fa-49a1-af6b-45380b856445.png">

**Comment by b20idawa** [comment]
This is what LenaSYS looks like in mobileview after the edit button has been removed. The edit button is not visible anymore in mobileview. 


<img width="292" alt="Skärmavbild 2022-04-13 kl  14 11 53" src="https://user-images.githubusercontent.com/81676911/163178509-4385c903-efe2-4abf-856f-833e4aa0ad9e.png">

**Comment by b20idawa** [comment]
How to test the issue:

1. Log in as a teacher

2. Choose the webprogramming course

3. Select "PHP example 1"

4. Check that the edit button is visible

5. Then select "inspect the page" and select mobileview

6. For example, select "iPhone 12 pro"

7. Check that the edit button is no longer visible

8. The result should look like the picture below.
<img width="292" alt="Skärmavbild 2022-04-13 kl  14 11 53" src="https://user-images.githubusercontent.com/81676911/163327869-d6b5b6af-cb43-452c-b018-2113c1aabe0a.png">

**Comment by a20willa** [comment]
Closing Issue as it has been solvled.
