### ISSUE TITLE
Cant get rid of dugga list once shown

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11489]
When the dugga list is shown after holding down the forward or back button, there is no way to get rid of it, unless you go out and in of the dugga. Perhaps there should be a close button or simulare for it? 

![image](https://user-images.githubusercontent.com/81626616/162617374-58deece4-6f41-49fd-a639-4b592c958ba4.png)

**Comment by a20joabo** [comment]
This drop-down in particular only appears inside of the code-viewer.
The issue can be tested by following these steps: 

1. Open the code viewer
2. Hold down the "_Previous example_"-button and a drop down will appear:
![image](https://user-images.githubusercontent.com/102584401/162743517-589d6ef9-2485-4496-b89c-163036f5636f.png)

4. Clicking outside the drop-down will now remove it.
5. Repeat for the "_Next example_"-button.
