### ISSUE TITLE
Duplicate code in AJAXService

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1148]
The same block of code gets run twice in AJAXService, resulting in each parameter being sent twice to the service.

**Comment by HGustavs** [comment]
I assigned highpriority and bug to this issue to get it confirmed quickly... as bugs in this code may affect all parts of the system...

**Comment by a13karsi** [comment]
This is confirmed, apparently we're getting the para string twice. I've looked at the code and I think I have a fix in mind which would accomodate the old and new code (which I don't really get, people need to comment more!)

However, I'm waiting for a pull request of mine to be merged which updates dugga.js before I can submit a new update.
