### ISSUE TITLE
Dugga deadlines are rendered differently depending on screen width

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#11494]
Dugga deadlines are rendered differently depending on screen width.

This is potentially not a bug, but it gives rise to uncertainty when viewing on different devices since information is removed for smaller devices.
![lenasys_date1](https://user-images.githubusercontent.com/4948661/162682730-45e52dda-f768-4ac2-8458-5b569e82045c.png)
![lenasys_date2](https://user-images.githubusercontent.com/4948661/162682734-0af07ed5-ab86-42d8-b59b-99c3634fc6b4.png)

Could a vertical presentation of the full date be useful for smaller devices? Are there other ways of presenting the deadlines consistently for all device sizes?

**Comment by a97marbr** [comment]
Make sure to test this for different screen sizes. Will the proposed solution work well on cellphones/tablets?

**Comment by a20behta** [comment]
merge with weekly branch. can close now
