### ISSUE TITLE
Research database file upload

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11496]
Understand how the database file upload works.

**Comment by a20micro** [comment]
It would seem the file upload is mainly done on the fileed.php page.
![FileUploadOrigin](https://user-images.githubusercontent.com/95532115/162898376-ba7fc628-822a-460c-9774-93f56b56da7d.png)
 
Here the user can choose 3 different types of upload, global, course local and version specific. The saving of these files are being done in two places, the database as well as in a local folder.  
![UploadExampleFolder](https://user-images.githubusercontent.com/95532115/162899730-960527b1-75b0-43ce-9e0b-6d652845a624.png)

![UploadExampleDB](https://user-images.githubusercontent.com/95532115/162899745-4c1ff1d5-5f65-4ac6-80d0-2bff9e20214c.png)

In the database, the "filelink" table holds all the relevant meta-data for the file, such as which course it belongs to (1894 = demo course, chosen on the courseed.php site at the start), if it's a global file and the file size. Note that the content of the file isn't saved in the database at all, and the database is only used as a way to match the filename and check access to local files.

The file itself is saved locally, in the /LenaSYS/courses folder. This folder contains folders matching the course ID in the database.
![CID](https://user-images.githubusercontent.com/95532115/162901066-1f98113d-5df4-4868-a208-321cec1150ad.png)

![FoldersCourses](https://user-images.githubusercontent.com/95532115/162901450-d99d3440-5030-4af4-80fa-4d99743a1669.png)

As we can see from the above screenshots, the current local machine contains files from courses 1, 2 and global. Global is a special folder which will always be fetched from, meaning it doesn't matter what course you're editing files from, so if the "isGlobal" flag is set, it will automatically be placed in the "Global" local folder. If a given course doesn't have a folder before adding a new file to that course, a local map will be created as well.

If adding a version specific course, a sub-folder in the course folder will be created, fetched from the coursekeys table.
![CourseVers](https://user-images.githubusercontent.com/95532115/162903530-7c1e24e6-bfa2-4b24-8a91-6baafab0b22d.png)

![Part1](https://user-images.githubusercontent.com/95532115/162904563-b9972c8f-1963-4665-b1d5-460249190c0d.png)
![Part2](https://user-images.githubusercontent.com/95532115/162904573-34f53a49-7285-4616-8df5-0e2206118f37.png)
(note the file path indicating a new course folder & version specific folder has been created)

When fetching files, a relative local path would be enough, but a SQL query to the database should also be done to check permission in terms of course ID, if it's version specific and if it exists at all.

Deleting files from the fileed.php site works as expected in the database, removing entries from the filelink table. However, it doesn't delete from the local machines (js doesn't allow cause of security reasons). Should probably be moved to a different location to prevent old files clogging the folder.
