### ISSUE TITLE
Downloaded markdown files does not have plus signs (+) but rather the HTML code &#43;

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#11493]
Downloaded markdown files does not have plus signs (+) but rather the HTML code &#43; 

Potentially related to #11491

**Comment by a20vicad** [comment]
![image](https://user-images.githubusercontent.com/102599327/162755387-bd0d6018-4731-4cc0-abf6-8c295ab6a6bc.png)
There is code (now commented out) that changes + to %2B (Hex-code for +)

**Comment by a97marbr** [comment]
Is there any history regarding this line of code?
```
content = content.replace(/\+/g,'%2B');
```
It seems like this code has been added to solve something ... why else add this line of code only for plus signs? Can we find when the code was added?

**On a side note.** Very good to add code snippets when discussing an issue, but refrain from using images for code snippets. It is very frustrating not to be able to copy & past from the code snippets above.

**Comment by a20vicad** [comment]
![image](https://user-images.githubusercontent.com/102599327/162896973-9acea120-8b69-42ac-a575-a1239facb580.png)
Yes there seems to be history.

**Comment by a97marbr** [comment]
I wonder why? Will the plus sign go missing completely if the culprit line-of-code is removed? The old commit msg seem to indicate this.

**Comment by a97marbr** [comment]
Yes the replacement seems straight forward. 

What I'm curious about is the result for the downloaded markdown file. Will the file contain the + sign? The original bug seem to indicate that the + sign is lost if the string replacement is not present.

So when you are testing the solution ... are you checking that the downloaded file contains the + sign?

**Comment by a20vicad** [comment]
The file contains a "+"-sign but it is downloaded as a txt file.

**Comment by a97marbr** [comment]
Ok then I would say that removing the string replacement is the solution.

The fact that the markdown file is downloaded as `.txt` I believe is a different issue.

**Comment by a20behta** [comment]
merged in weekly merge.
