### ISSUE TITLE
Show files page doesn't show files when working on local host

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11497]
Make files visible when working on localhost. 
Link: http://localhost/LenaSYS/DuggaSys/fileed.php?courseid=1894&coursename=Demo-Course&coursevers=52432

**Comment by a16linas** [comment]
Found potential solution, adding a toString() to the row[key] before toUpperCase() seems to solve the issue in fileed.js line 581

**Comment by b20thelo** [comment]
Closed as it was solved during last week merge. Pullrequest #11580
