### ISSUE TITLE
Layout is not equivalent to reset button

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11508]
The layout when going into a example is not the same as when pressing the reset button. This makes no logical sense, and should be fixed to the same as the reset button.

When going into dugga:
![image](https://user-images.githubusercontent.com/81626616/162714393-b98a7287-5eaf-4313-ba47-f1936749cecb.png)

When pressing reset:
![image](https://user-images.githubusercontent.com/81626616/162714437-3f8b2f69-3c62-4ab3-8f90-281cca425055.png)

**Comment by a19xinhu** [comment]
add function resetBox() at the end of function returned(), it make dugga reset layout when it upon loading.

Go in to dugga it will automatically reset to default layout.
