### ISSUE TITLE
contribution database documentation 

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11516]
The database given for contribution to work has no documentation or clear indication of how the tables are constructed. 
it seems to be a sqlite file so no forein keys are present however information is clearly connected between the different tables. 
currently all information avaliable is the create tables sql commands and the raw data from each table. 
if @HGustavs or @a97marbr do not have any documentation on the current state of the database it needs to be created. 

below is a text file with the specified sql commands to created each table and their respective columns. 
[contribution_createTable.txt](https://github.com/HGustavs/LenaSYS/files/8464474/contribution_createTable.txt)

information required. 
    - what/where is each table used
    - are the tables connected in any way?
           - what connects each table to eachother (unoffical foreign key)
           - some type of diagram (UML or other) for documentation.

@HGustavs or @a97marbr also need to inform about how the informaition is saved and placed in the database, how adding or removing tables are possible and what future changes are avaliable to create.

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/162958567-9f33e8fd-f54a-406a-8f9b-4fd7b0472b7f.png)
Database file opened with DB Browser for SQLite, fields seems self explanatory?
@a20behta

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/163169942-00eed835-4e82-4bf0-8baf-7fbcd8b4879f.png)
![bild](https://user-images.githubusercontent.com/102593527/163170562-6163078d-a479-4cd0-9317-6ea923fb5e90.png)


Contribution works with an hardcoded database file which contains all different contributions added to Github. It uses prepared select statements and changes the placeholders to the user/course/other to examine and then runs the SELECT and returns the result as an array. Included picture is from a function that gets all issues created by a user at a specific time intervall.

@a20behta

**Comment by a20behta** [comment]
Looks good nice work
