### ISSUE TITLE
sh - shorter url-links and Canvas search function integration with LenaSYS should be name independent

### ISSUE THREAD

**Issue by a20sarle** [HGustavs/LenaSYS#11512]
This issue relates to both #10566 and #11219 where information about how hotlinks, search and LenaSYS integration with Canvas can be found. The previous documentations should describe how iframes are chosen and shown to be displayed in Canvas' own iframe.

Today there's most likely a long link-name used to choose which iframe to be shown in Canvas' own iframe on the course and assignment pages. The goal is to make this link as short as possible. Todays' solution and hotlink is most likely based upon the course name which results in varying issues.

What happens if a course and/or src/file in iframe change name? Can Canvas' iframe still find the right examples and courses in LenaSYS? (Better to link / use id that's not based on name).

Imagine if Canvas iframe has linked a course with the name "database" and it changes name to "data systems". In this case all the previous connections should still be the same and the iframe on Canvas should continously link to the same source. If a new course named "database systems" is added, the "link-search"/src for the course "databse" should still be linked exactely as before.

Once an "LenaSYS-iframe-source" has been found/connected with an iframe in Canvas the link should be constant and never changed even if the course name is changed or multiple courses with similar names has been created.

**Comment by a20sarle** [comment]
The src-link is related to the serach query in the iframe on Canvas.
![image](https://user-images.githubusercontent.com/81631818/162740219-8bb56e51-d698-490b-9432-8ff9e60e4b39.png)

**Comment by a17nikjo** [comment]
Related to issue #11377 
Some comments from HGustav can be found here.

**Comment by a17nikjo** [comment]
in /sh/index.php we create links starting with " header("Location: /DuggaSys/", however these links do not work when testing locally. A fix is adding .. infront liko so  "header("Location: ../DuggaSys/". This allows for testing on localhost.

**Comment by a20linth** [comment]
The URL shortener currently looks like this:
<p><iframe src="https://dugga.iit.his.se/sh?c=Demo-Course;a=daily-minutes" width="800" height="1200"></iframe></p>

but if course id(cid) and assignment id(id) are instead used, the url shortener could look like this:
<p><iframe src="https://dugga.iit.his.se/sh?c=1894;a=20" width="800" height="1200"></iframe></p>

Courses (course) have an unique id (cid) for every course that cannot be modified.
![image](https://user-images.githubusercontent.com/102609651/163979105-e0f52bfb-fafd-4d71-b3b1-d15299c72e68.png)

Assignments (quiz) have an unique id (id) for every assignment that cannot be modified.
![image](https://user-images.githubusercontent.com/102609651/163979168-e3cbc8de-07bd-4336-a1ee-5e4db3c072a8.png)

The functions that manage the SH are located in sh/index.php (GetAssignment(), GetCourse(), CourseAndAssignment()). GetAssignment is used to access submitted assignments, with the submissions hash value. GetCourse is used to access courses, with the course name. CourseAndAssignment is used to access assignments for specified courses, with the course name and assignment name.

**Comment by a20linth** [comment]
QUESTIONS TO CUSTOMER @HGustavs 

Should the old SH URLs still be valid or should only the new SH URLs work? E.g., the two URLs https://dugga.iit.his.se/sh?c=Demo-Course;a=daily-minutes and https://dugga.iit.his.se/sh?c=1894;a=20 should direct to the same address, or only https://dugga.iit.his.se/sh?c=1894;a=20 should work.

Should new issues be created for replacing old URLs with the new ID based SH URLs when they are implemented or is the idea that the old URLs should be replaced over time with SH URLs?

**Comment by HGustavs** [comment]
Definitely the text based one since we may create another assignment with the same name but different identifier and remove the first one, so the c=1894 a=20 is of no use to us.

**Comment by a20linth** [comment]
Testing:
These SH URLs should link to their coresponding urls:

http://project-g2.webug.his.se/sh/?c=demo-course 
should link to:
http://project.webug.his.se/DuggaSys/sectioned.php?courseid=1894&coursevers=52432&embed

http://project-g2.webug.his.se/sh/?c=demo-course&a=daily%20minutes
should link to:
https://project-g2.webug.his.se/DuggaSys/showDugga.php?courseid=1894&cid=1894&coursevers=52432&did=20&moment=3009&embed

**Comment by a20willa** [comment]
The intention here is to use a name and a identifier for said name. Even if the name change, the identifier may not, UNLESS the name does no longer contain any resemblance to the identifier. The identifier may no longer lead to the same place in that case.

The part after the `c?` is the identifier in SH links, or in other words the search query. 
`http://project-g2.webug.his.se/sh/?c=XML`

# Unique identifiers
If we a course with the name:
`XML SAX`

And then use this query:
`http://project-g2.webug.his.se/sh/?c=XML`

The course may from that point always be found using only XML as the query, because it's **the only course which shows up when searching for XML**. That is, keyword XML only exist in exactly one course at the time this query was made. Effectively, we have now set XML as the identifier. 

```
FULL NAME = IDENTIFIER

XML SAX = XML
````

Now, if at a later date add another course:
```
XML SAX
+XML CSS
````
The XML SAX course will still use the SAME unique identifier! The identifier will always work if the combination of letters in the name has ANY resemblance to the identifier!
```
FULL NAME -> NEW NAME = IDENTIFIER

1. XML SAX -> SAX XML = XML
2. XML SAX -> XML = XML
3. XML SAX -> XM = XML
4. XML SAX -> X = XML
````

But if none of the resemblance exist:
```
XML SAX -> NEW COURSE != XML
```
The XML identifier is no longer usable. 

# Many results for same query
If two or more results appear when we use the following search query (assuming the query has never been made before):
```
QUERY: 'XML'

Results: 
1. XML SAX
2. XML CSS
````
There should be some kind of error. This is because the query XML may not be used as an identifier for two courses! We must add more letters to the query to make the identifier unique!
```
QUERY: 'XML S' <-- THIS WILL BECOME THE IDENTIFIER

Results: 
1. XML SAX 
````
Thus, the first time a query is made, we should add it as the unique identifier if it only shows exactly ONE result!

**Comment by a20linth** [comment]
Database has been modified (/install/install.php to update database)
Testing (click links as they are listed):
1) http://project-g2.webug.his.se/sh/?c=d : Error 404
2) http://project-g2.webug.his.se/sh/?c=dd : Error 404
3) http://project-g2.webug.his.se/sh/?c=demo : Demo-Course
4) http://project-g2.webug.his.se/sh/?c=demo : Demo-Course
5) http://project-g2.webug.his.se/sh/?c=demo-course&a=gga : Error 404
6) http://project-g2.webug.his.se/sh/?c=demo-course&a=ggaa : Error 404
7) http://project-g2.webug.his.se/sh/?c=demo-course&a=gga%201 : Demo-Course Dugga 1
8) http://project-g2.webug.his.se/sh/?c=demo-course&a=gga%201 : Demo-Course Dugga 1

**Comment by a20linth** [comment]
### The following functionality is currently not implemented

- [ ] The prevention of creating multiple SH URLs linked to the same course or assignment.

- [ ] Making SH links invalid when the course and/or assignment name has no recemblance with the SH parameters.

- [ ] Deleting or changing id for courses and assignments should update SH links according to requirements.

**Comment by a20linth** [comment]
Testing instructions for the latest pull-request: https://github.com/HGustavs/LenaSYS/wiki/SH-Documentation#testing-instructions

**Comment by a20linth** [comment]
A wiki page has been created for SH Documentation. https://github.com/HGustavs/LenaSYS/wiki/SH-Documentation

The Wiki contains a description of how the SH links work, how the SH links are created (with a diagram showing the methods) and testing instructions for the SH methods.
