### ISSUE TITLE
Database installation guide need to be created in the wiki section of Github.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11534]
The guide should be based from the information commented in the issue #11378

**Comment by b20hanwa** [comment]
A guide for installation is uploaded to Wiki, you can see the guide on this link:
[](https://github.com/HGustavs/LenaSYS/wiki/Contribution-database-installation)

Is the guide understandable? @c20adael @a20behta

**Comment by c20adael** [comment]
yep This looks good.
