### ISSUE TITLE
Edit button does not show in template 10

### ISSUE THREAD

**Issue by a20linth** [HGustavs/LenaSYS#11536]
The edit button does not show in template 10 when being logged in as a teacher with writing access. The edit button shows in other templates

**Comment by a20patpe** [comment]
The functions of adding things to the different boxes is hardcoded and template 10 is not included in this hardcoding. 
Search for: templateid == 9 in codeviewer.js. 
Below that there should be a templateid == 10. :)

**Comment by a20linth** [comment]
Testing:
1) Login as a teacher account (username: stei password: password)
2) Enter Demo-Course
3) Create a new code dugga
4) Select template 10
Expected result: The edit button should be showing if you are logged in as a teacher
