### ISSUE TITLE
Diagram: Ghost element should not exist after you place an element on the diagram

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#11549]
When you selected an element to paste in the diagram, it appears as ghost before and after you have painted it out. 
![bild](https://user-images.githubusercontent.com/81624541/162951554-67c72a15-36a9-43e7-ab6f-468bb21a5154.png)
The ghost element to the right should not be there.

**Comment by b20thelo** [comment]
Also when holding down the mouse button on the canvas and pulling to the side the canvas should be moved. No new element should be added.

**Comment by b20thelo** [comment]
Disabling ghost entities also removed lines when being drawn therefore this issue needs another solution and previous pull request were denied.
