### ISSUE TITLE
Mockups for dropdown menu hide and show 

### ISSUE THREAD

**Issue by a19meram** [HGustavs/LenaSYS#11554]
- 
![image](https://user-images.githubusercontent.com/77247277/162955804-d206aab1-47b9-4326-8253-66cb0618ca38.png)

- 
![image](https://user-images.githubusercontent.com/77247277/162955933-8492d1bc-dc96-4aff-b317-7a7ccd384f28.png)

- The user chooses which functionality he wants to work with and hide the others 
- All can be displayed or all can be not diplayed if the user chooses to

**Comment by b20thelo** [comment]
Great idea but I will close this as it isn't what Henrik want (according to what he expressed previously on customer meeting when we showed a similar suggestion while wanting to include UML entity)
