### ISSUE TITLE
Implement dugga filter functionality for resulted

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11557]
Implementation is needed for the filter that handles the dugga type. It should follow the example from #11381 in how it functions.

**Comment by a20johba** [comment]
The previous code only updated the filter when a search was made. Moved the previous code to a new function that runs every time a checkbox is changed in the dugga filter menu. The filter should now have an immediate effect on the table when a checkbox is checked/unchecked. I also rewrote a minor part of the rowFilter() function to ensure proper functionality and to slightly improve readability.
