### ISSUE TITLE
Save functionality dugga edit isn't consistent.

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11558]
Found under "Tillgängliga duggor" at /DuggaSys/sectioned.php?
![image](https://user-images.githubusercontent.com/81772705/162964105-fb26c5af-de0f-4868-b75a-bff5921fc1f8.png)
Allows clicking on save and Alert is shown.

Found under "Show test" at DuggaSys/duggaed.php?
![image](https://user-images.githubusercontent.com/81772705/162964188-3650c1be-f9e3-454b-8f42-dbf0669ea8c0.png)
Save greyed out

Make sure both dialogues work as last image.

**Comment by a20jonda** [comment]
found in DuggaSys/courseed.php using method in DuggaSys\courseed.js

![image](https://user-images.githubusercontent.com/102598258/163954223-4644b1fd-b7df-4375-8213-18fa09fe6bfa.png)
Save not grayed out.

**Comment by a20jonda** [comment]
Functions of interest are 
- duggaed.js / validateDuggaName() 
- setioned.js / validateSectName(name)
- courseed.js / elementIsValid(element)

**Comment by a20jonda** [comment]
![image](https://user-images.githubusercontent.com/102598258/164227830-0cc5504d-14a6-4059-843a-cb010c1c8c9c.png)
Regex will be changed to include dashes, otherwise Demo-Course will need to change its default name.

**Comment by i19matla** [comment]
merged and done

**Comment by a20jonda** [comment]
Still working on this
