### ISSUE TITLE
General: Alert should be displayed on all duggas if changes has been made by the student.

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#11553]
If the student has made **changes** in a dugga, An alert msg should be displayed, if the student deicide to leave the page.
![bild](https://user-images.githubusercontent.com/81624541/162955591-f5665306-d9b4-453c-9e31-2516174bc731.png)

This issue should follow the same standards we used in #11242 where developers created their own file and linked it in the main issue.

**Comment by c20adael** [comment]
#11485

**Comment by c20adael** [comment]
An alert has been added in the diagram dugga referred to in the previous comment. This should be made to a global alert for all duggas

**Comment by a17nikjo** [comment]
In showDugga.php window.onbeforeunload is set this makes it so whenever a dugga is shown this is added instead of having to add it in the <body>.

**Comment by c20adael** [comment]
this is done
