### ISSUE TITLE
Changing from one template to another with more boxes breaks the template

### ISSUE THREAD

**Issue by a20linth** [HGustavs/LenaSYS#11563]
When a new template with more boxes is applied to an example code dugga, the number of boxes from the previous template remains which causes there to be missing boxes.
![image](https://user-images.githubusercontent.com/102609651/162974956-42895118-9b46-4774-bce3-bc0a6616b17f.png)
![image](https://user-images.githubusercontent.com/102609651/162974974-524ef8a2-5a81-4b92-a10f-46d635a172b8.png)
![image](https://user-images.githubusercontent.com/102609651/162974984-9be04467-03c3-43cb-9fbd-ba992362c078.png)

**Comment by a20linth** [comment]
This issue is being solved in issue #9552 which makes this issue irrelevant

**Comment by a20sarle** [comment]
Duplicate of issue. Closing.
