### ISSUE TITLE
Unexpected behavior by comments of // type 

### ISSUE THREAD

**Issue by a13erisc** [HGustavs/LenaSYS#1158]
When these comments are used, linenumbers increase by 2 instead of 1.

**Comment by HGustavs** [comment]
Great catch!

**Comment by HGustavs** [comment]
It has to be one of the row++ lines that is over-adding. My prime candidate is this section starting on line 970. 
Try to remove the row++ there and see what happens, if it is better, worse or the same.

```
	        c=instring.charAt(i);
            if (c=='\n'||c=='\r'||c=='') {
                row++;
                break;
            }else{
                str+=c;                
            }
            i++;
```

**Comment by a13erisc** [comment]
Yes, that solved it.
