### ISSUE TITLE
Create the proposed mockup from the referred issue on contribution.php

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11593]
#11123

**Comment by c20adael** [comment]
https://stackoverflow.com/questions/2828109/show-div-from-another-website check this out. It locks like it can maybe work

**Comment by a20caros** [comment]
The suggestion to get id from github to print the element does not work either as github does not allow it

**Comment by c20adael** [comment]
In this issue we should only create a pop-up box on the page that could hold the information. You dont need the actual information. See if we can get the visual part to work.

**Comment by a20caros** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/81676918/164237813-802c564e-594e-4a50-8fd9-7641170f9bd9.png">
A div displays when hovering over the commit links
<img width="534" alt="image" src="https://user-images.githubusercontent.com/81676918/164238080-3db97a24-b76a-463e-9d7f-f789d77aef4b.png">
When you move the mouse away from the links, the div disappears
