### ISSUE TITLE
Linux machines not loading contribution test database. 

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11598]
When trying to load the contribution databases into either the webserver or a devs ubuntu machine it seems to not load anything, similar to no database. 
  * user access is given same as apache 
  * tried restarting apache
  * used the same method as on windows machines

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/163178627-40a85144-9aee-4fb2-9e58-c3b3dfae99fe.png)

Found an error with wrong slashes in the address. Windows doesn't care but Linux got mad. Adjusted the code

**Comment by a20behta** [comment]
changes made into weekly branch
