### ISSUE TITLE
When pressing enter to search on fileed.php and duggaed.php it behaves badly.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11590]
Then using the search bar in the navheader.php that is used on these pages it is supposed to search for what you wrote. But instead it seems to reload the pages. It behaves different on both of the pages. 
The searching part works without needing the enter press.

On fileed.php it just looks like it reloads the page without actually searching.
Before searching:
![image](https://user-images.githubusercontent.com/80856978/163130091-d7da339f-e94f-4044-9e6a-933244c7f9f3.png)
After searching: Same view/ reloaded page.

On duggaed.php it seems to do a reload of the page and then it fails to load the data from the database and it is all white.
Before searching:
![image](https://user-images.githubusercontent.com/80856978/163130701-aceef2c0-0bc2-4ba9-b646-014196bf7be5.png)
After searching:
![image](https://user-images.githubusercontent.com/80856978/163130920-0466df7c-43df-4f1c-8371-14c398888f53.png)

**Comment by a20behta** [comment]
merged into weekly branch
