### ISSUE TITLE
Hide diagram functionality in non-diagram duggor.

### ISSUE THREAD

**Issue by a20micro** [HGustavs/LenaSYS#11614]
As the teachers should be able to import initial diagram for duggor of type diagrams (#11401), a drop-down menu connected to the database was added to the "Edit Dugga" screen. 
![image](https://user-images.githubusercontent.com/81772705/164428600-926b2a92-3f8c-4b62-8566-e5a07a490dd1.png)

This "Add diagram to dugga", "Diagram types allowed", "Error check" segment is supposed to only show up for duggor of type diagram.

**Comment by i19matla** [comment]
Merged and done
