### ISSUE TITLE
Create icons for UML

### ISSUE THREAD

**Issue by c20emili** [HGustavs/LenaSYS#11617]
The new UML buttons need icons that keeps the theme of the toolbar. 
diagram_UML_entity.svg
![image](https://user-images.githubusercontent.com/81320323/163199829-2ae0304c-fb51-43d1-8532-f9790ad8397b.png)
diagram_inheritance.svg 
![image](https://user-images.githubusercontent.com/81320323/163199891-952add29-c0af-427e-8352-c38a86d852ef.png)

**Comment by b20thelo** [comment]
Icons has been approved and merged.
