### ISSUE TITLE
Filtering out non-json files from the "Edit Dugga - Add diagram to dugga" menu 

### ISSUE THREAD

**Issue by a20micro** [HGustavs/LenaSYS#11618]
As part of issue #11401 teachers should be able to import diagrams to be shown on-load for students doing the dugga. Currently, the drop-down menu is connected to the filelink table in the database, but all files are shown.  

![AllItemsShown](https://user-images.githubusercontent.com/95532115/163200484-47b34126-5fd7-4104-81bb-fe870e5a0bd9.png)

Only .json files should be shown in this list to be selected.

**Comment by a16linas** [comment]
Pull request has been accepted and branch has been merged. Closing issue

**Comment by b20thelo** [comment]
Feedback from Henrik.

Wants the code to be written so that if in the future new file formats will be added that should be possible by adding another value in an array.

Example: {json, txt}
