### ISSUE TITLE
Wiki: Add entries about files connnected to diagram to wiki.

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#11626]
Add entries about files about diagram files to wiki. It should be an overview of what the files do and how they work. The important rule is,  It should be info that helps a lot of people who take over next year, so info about small functions that does not do much should not be added.

**Talk to Therese or me if she cant be reached, and we will assign you to this issue.**
Make a comment about which files you write about in the wiki here.

**Comment by a20jonda** [comment]
added diagram_IOHandler.php and its short description from the file to the diagram wiki.

**Comment by a20jonda** [comment]
added diagram_IOHandler.js and its description from the file to the diagram wiki.

**Comment by a20jonda** [comment]
![image](https://user-images.githubusercontent.com/102598258/164417732-e580228e-a7b4-4627-bb30-5dbc4b31ff68.png)
Wiki:n blir en enstaka page med allt samlat uppdelade av headers
