### ISSUE TITLE
Diagram: Adapt diagram description so it works for Canvas as well.

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11623]
The dugga description for the diagram should show in a good way when LenaSYS is integrated into Canvas.
It should also be possible to change the width of the description as possible in this example: https://dugga.iit.his.se/DuggaSys/codeviewer.php?exampleid=6166&courseid=4&coursename=Databaskonstruktion&cvers=22521&lid=10264

A suggestion from Henrik was to pop it out in a separate window if it doesn't look good as it is with the new solution.

**Comment by a19meram** [comment]
- In the first video we have a video clip that illustrates how the assignment description can be changed in width with a pull on the middle part of the digram and the description
-

https://user-images.githubusercontent.com/77247277/163347753-5a06a091-c89e-49e3-8a0a-b132af08b71a.mp4


https://user-images.githubusercontent.com/77247277/163347843-e969e5b8-03c9-4413-bfc4-80fa81a6fca9.mp4

- Some problems with the canvas part. We cannot get access through the files to show the diagram on our local environment

**Comment by b20thelo** [comment]
Try other solution with hide and seek description instead. 
Should be able to view html and text documents.

**Comment by b20thelo** [comment]
FInal solution approved by Henrik.
