### ISSUE TITLE
Add the functionality so that the user can use the new buttons on contribution.php

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11630]
the issue related #11592

**Comment by b20eripe** [comment]
Related issue #11736 is solved, used for testing of this issue

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/164468757-202938c8-0f95-48c9-b4b4-3c43c0ce2f57.png)

Dynamic indexing of different course year and all db files in those directories. 1 array with all relevant years and an 2D-array containing strings of all databases with their year.

These 2 will be used as data in two selections of which course to view.

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/164705758-ee801694-4b53-4742-919b-dd738caf47a8.png)

Added dynamic loading of choices of year for the course selection

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/164707252-75a476a6-582b-401a-950f-15624835bca7.png)
Improved the indexing of years to only include the year and not the filepath

**Comment by a20behta** [comment]
merged into weekly branch. closing issue
