### ISSUE TITLE
Filter overlapp when editing student result

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11633]
![image](https://user-images.githubusercontent.com/102468604/163347382-4e2ca20a-0e69-4ba1-ae04-8335cd0be669.png)
When logged in as a teacher and editing student result switching from one colum filter followed by pressing the second one it results in both being visable. 
tested on Webbutveckling-Datorgrafik and DemoCourse. 

both have the same issue .

when one is pressed the other one should be closed.

**Comment by HGustavs** [comment]
Yes that solution is my preferred solution also.

**Comment by c20adael** [comment]
@a20vicad Can you send a picture of how it looks now after merge?

**Comment by c20adael** [comment]
https://github.com/HGustavs/LenaSYS/pull/11644#issue-1204343372

**Comment by a20behta** [comment]
@c20adael currently our group branch looks the following vide

https://user-images.githubusercontent.com/102468604/163958770-2759eb20-2839-4db9-ba13-59aa8bd16766.mp4

o

**Comment by c20adael** [comment]
@a20behta yep that looks good! also like the sound when pressing the buttons xD

**Comment by a20behta** [comment]
Merged into weekly branch
