### ISSUE TITLE
When viewing the courseed.php from a mobile perspective the title does not wrap around.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11641]
![image](https://user-images.githubusercontent.com/80856978/163357281-d15de15f-0c40-4394-bacc-cfdf0809cf9c.png)
This title should wrap around and it would be nice to place the logo in the center above the text.

**Comment by HGustavs** [comment]
I think we can remove the title completely?

We do not want wrapping. We want it to be hidden using ellipsis or similar technique.

**Comment by c20adael** [comment]
@b20hanwa See if you can remove the title if the spacing is too tight.

**Comment by b20hanwa** [comment]
> @b20hanwa See if you can remove the title if the spacing is too tight.

I'm on it!

**Comment by a20behta** [comment]
Changes merged in however seems like title is not removed

**Comment by a20behta** [comment]
merged into weekly branch. closing issue
