### ISSUE TITLE
Odd behavour on top row when resizing box

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11651]
When a code window is dragged to the top of another, the text will become smaller.

![image](https://user-images.githubusercontent.com/81626616/163866209-84e28357-b411-4315-9204-9e551aae2ec8.png)

**Comment by HGustavs** [comment]
Most likely a bug?

**Comment by a20willa** [comment]
Text seems to disappear behind a layer at the top. The text is actually not getting smaller!
