### ISSUE TITLE
Icons code be a litte lower

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11652]
The icons could be moved down a little in code viewer, as they are a bit too close to the top of the ppage. 
![image](https://user-images.githubusercontent.com/81626616/163867244-c63200ca-4d33-4e55-a9c8-66e85c4b8039.png)

**Comment by b20sebka** [comment]
![bild](https://user-images.githubusercontent.com/102599780/164220657-a227a0bc-c206-476f-a462-ff210ca6a945.png)
Is this a bug? The buttons are place normal for me.

**Comment by a20sarle** [comment]
@a20willa What needs to be solved to remove the "on hold" label?

**Comment by a20willa** [comment]
@a20sarle is this fixed?

**Comment by a20sarle** [comment]
Let's get someone to check out this issue and try to replicate it. If it still canät be replicated we can close the issue.

**Comment by a20muhal** [comment]
Seems normal to me on my machine
