### ISSUE TITLE
Adding some kind of indication when holding down back or forward icons

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11655]
Currently, if you hold down either the backwards or forward buttons, a list of duggas appears. However, an indication when holding down the button would be good. How do I know I actually am holding down the button in the below clip? 

[![Image from Gyazo](https://i.gyazo.com/4cd424187b53440f39d5ab46574877dd.gif)](https://gyazo.com/4cd424187b53440f39d5ab46574877dd)

**Comment by HGustavs** [comment]
Also I think that the "FORW" text should not be there?
