### ISSUE TITLE
Resize copy icon to fit window

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11657]
In #11217 a fix was made that made sure that the copy overlay no longer overlap. As a effect, the icon is instead cut off if the window is too small. A fix would be to make the overlay fit to the screen by changing it's size. 

![image](https://user-images.githubusercontent.com/81626616/163872976-79e782a8-c1e4-4b9a-81dd-ccfda609b4a5.png)

![image](https://user-images.githubusercontent.com/81626616/163873101-3fbe893f-4d7d-4a22-b573-e2b18a433bd7.png)

**Comment by HGustavs** [comment]
This size is real size?

I would say that it is too large. A suitable size for the icon would be same as the button, the text can remain as is. 

This way clipping is much less likely.

**Comment by b20idawa** [comment]
How to test the issue:

1. Log out of the site

2. Select the webprogramming course

3. Select JavaScript Example 1
<img width="1339" alt="Skärmavbild 2022-04-19 kl  13 31 15" src="https://user-images.githubusercontent.com/81676911/163994216-496edfff-1164-46dc-8611-24d0340628d4.png">

4. Minimize the windows for the codeviews at the right of the page (see the video below)

5. Press the copy button on both codeviews and check that the copy notification is clearly visible in both codeviews.

6. The result should look like the movie below.

https://user-images.githubusercontent.com/81676911/163994453-43f5e447-bb33-461b-8425-3e00662cde26.mov
