### ISSUE TITLE
Animation for disapearing icons

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11654]
The title of the window in code viewer have an animation when a window is resized, but the icons does not. Perhaps adding it for them too would make things more consistent. 

In this case, I mean the "copy" button, but the same may be done for other icons which also is disappearing. 

[![Image from Gyazo](https://i.gyazo.com/f54c6f7b82cb90c01bf69c7f54e64644.gif)](https://gyazo.com/f54c6f7b82cb90c01bf69c7f54e64644)

**Comment by HGustavs** [comment]
Do we know if resizing is compatible with the css grid?

If not, this animation will most likely not work at all when grid is implemented?

**Comment by a20andlj** [comment]
This issue will not be relevante and is closed now because we are working with a css grid solution.
