### ISSUE TITLE
Icons move in odd ways when window is resized

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11653]
When a window is resized, some icons are removed, but the ones left also move up slightly. 

[![Image from Gyazo](https://i.gyazo.com/d62a1b36ee309417a7a8ea75bbaea7b8.gif)](https://gyazo.com/d62a1b36ee309417a7a8ea75bbaea7b8)

**Comment by b20idawa** [comment]
How to test the issue:

1. Log out of the site

2. Select the webprogramming course

3. Select PHP example 1
<img width="892" alt="Skärmavbild 2022-04-19 kl  10 41 48" src="https://user-images.githubusercontent.com/81676911/163962051-d144db2a-a0cc-461c-84d7-1799084fea5b.png">

4. Reduce the window for one of the codviewes (see video below)

5. Make sure the icons do not move up when the title text disappears

6. The result should look like to the video below

https://user-images.githubusercontent.com/81676911/163962227-5475d808-a430-4fe2-911c-1cd610645033.mov
