### ISSUE TITLE
Implement the toggle for darkmode

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11659]
The darkmode mockup is now implemented, but the toggle does not work yet. Reference at issue #11316.

**Comment by b20fanfa** [comment]
@HGustavs How much css may we change? We may have to modify large amount of code to make this function work. Do you know if there is a way to do this without changing too much code?

One thing we have in mind was overriding the `prefers-color-scheme` to force the webbrowser to use either the dark or white theme. However, we have yet found a good way to implement this.  Is this a good way to proceed?

**Comment by a20willa** [comment]
Closing issue, the original issue is not big enough to be divided into smaller parts.
