### ISSUE TITLE
List of duggas is removed right after letting go 

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11656]
Currently, if you hold down either the backwards or forward buttons, a list of duggas appears. However, when letting go of the mouse button the menu will disappear. What should happen here is that as soon as we click outside the menu if it's already open, it should disappear, but right now it auto closes.

[![Image from Gyazo](https://i.gyazo.com/fc43a82a64575ff6f81e059f96be0019.gif)](https://gyazo.com/fc43a82a64575ff6f81e059f96be0019)

**Comment by HGustavs** [comment]
That interface is quite bad looking.

I suggest making the text nicer looking. It is not easy to read the labels. 

Perhaps more margins between the menu items?

**Comment by a19xinhu** [comment]
After adding new code, the drop bar will not disappear when you hold 1s on the button which id is "afterbutton" or "beforebutton".
