### ISSUE TITLE
Fetching variant data, from database, in showdugga.php and extract the file name.

### ISSUE THREAD

**Issue by a20micro** [HGustavs/LenaSYS#11664]
The initial diagram, when opening "showdugga.php", should be the assigned .json diagram file, selected via the "edit dugga" menu.
Currently the initial digram data is hard-coded in diagram.js
![CurrentData](https://user-images.githubusercontent.com/95532115/163961916-6ac11b1d-6613-4c8f-a2eb-6834abaee282.png)

For students to view different initial diagrams, the first step is extracting the file to be loaded from the variant table. (in example below, diagram(10).json)

![jsonParamsDB](https://user-images.githubusercontent.com/95532115/163963227-daa9e48b-03bf-4765-90cd-adddd5c76ae6.png)

To do this, the data must be fetched within the scope of diagram.js and the text string must be spliced to extract the file name.

**Comment by a16linas** [comment]
ShowDugga.php now outputs the filename and filepath to the attached json diagram. Will add onto this on issue #11666 where we implement the file content into the diagram

**Comment by a20micro** [comment]
Functionality updated as Javascript doesn't allow dynamic file fetching and requires user input to create file objects (safety reasons). Functionality moved to showDugga.php and rather than returning the file name, returns the entire file content as a text string.

**Comment by a16linas** [comment]
We would like this issue removed since we've now merge it into #11666 and will continue working there
