### ISSUE TITLE
File name is makes pulling branches impossible 

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11669]
An error in a filename is making it impossible to pull branches. **This must be fixed**!!!!!!

**Comment by HGustavs** [comment]
Please clarify which file name we are talking about for the sake of documentation

**Comment by b20fanfa** [comment]
A svg image was created which was loaded into the Shared / icons folder.
It was mistakenly named "Dark: lightmode_toggle.svg" but changed to "ThemeToggle.svg".
