### ISSUE TITLE
Create dynamic loading, of initial diagram, in digram.js

### ISSUE THREAD

**Issue by a20micro** [HGustavs/LenaSYS#11666]
As part of issue #11401, students should be able to see an assigned diagram on load if the dugga is of type "diagram dugga". Currently, the initial diagram is hard-coded in diagram.js

![CurrentData](https://user-images.githubusercontent.com/95532115/163965455-69b22a5c-86c8-4665-abec-7ba9ac64274c.png)

To create a dynamic initial diagram, the diagram.js file should have conditional loading of demoData and only if there's no assigned .json diagram file. To comply with previous issues, this should be done via passing a string as an argument, which would be the .json file's filename/filepath.

**Comment by a16linas** [comment]
A fix has been made for this issue since when the ER/UML feature was implemented, the fetching of diagram json files got some bugs, pull request #11923 can fix this

**Comment by i19matla** [comment]
merged and done
