### ISSUE TITLE
Diagram: Dashed box appears before selection made

### ISSUE THREAD

**Issue by i19matla** [HGustavs/LenaSYS#11672]
![image](https://user-images.githubusercontent.com/81630339/163973006-c6a92eb3-3953-4bba-9cef-1c6b89da4c35.png)
Make the dashed selection box appear after the selection been done. The dashed box should be seen after the mouse button is released.

**Comment by b19karhj** [comment]
The entitys should be marked while they are selected by the other box, when the mouse button is released then the inner box with x should appear.
