### ISSUE TITLE
Add fileed.php and fileed.js to Wiki documentation.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11679]
Document what fileed does and its key functions. Why is fileed partof this website

**Comment by b20jonlu** [comment]
@c20adael Should i create a new page for fileed or should i put it under an existing page?

**Comment by b20jonlu** [comment]
Created the wiki page, it is possible to go into greater depth on certain areas if it is needed. I didn't write about certain things i wasn't sure of such as the event handlers, i also didn't bother going into detail about functions which can be understood simply by looking such as the sort and filter functions.

**Comment by c20adael** [comment]
good job!
