### ISSUE TITLE
Diagram: Should not be possible to draw lines from two entity elements to the same attribute element.

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11688]
![image](https://user-images.githubusercontent.com/81772705/164014018-cb534e0e-705e-45a8-b645-ff336d87c966.png)

Error found in ER model: It should not be possible to draw lines from two entity elements to the same attribute element as it goes against the ER rules.

Other errors that go against ER rules should also be eliminated. If a new error is found add a description of it as a new comment and fix it as well.

**Comment by b20thelo** [comment]
This issue is kind of related to issue #11479 (solved with pullrequest #11576).

**Comment by i19matla** [comment]
Found a separate problem related to this, when there is a chain of interconnected attributes. A new issue will be created to solve that problem.

**Comment by i19matla** [comment]
Merged and done
