### ISSUE TITLE
Footer missing in codeview and overlay areas in dugga examples

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11682]
Reference to #11316. The footer overlay some content in the sectioned page in lennasys. 

![image](https://user-images.githubusercontent.com/81626616/164002192-25afbf51-d083-4d00-8361-47416c24381d.png)

**Comment by HGustavs** [comment]
I would say it is too much screen realestate to add a footer for only one icon. Can we not put this icon in the menu bar together with other icons?

**Comment by a20willa** [comment]
The footer is not needed, thus issue is clossed
