### ISSUE TITLE
Choosing window in hamburger menu leaves unused white space 

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11685]
When clicking on hamburger menu and choosing a option, the window selected will be shown but half the screen will be white, where the other opption should be. 

![image](https://user-images.githubusercontent.com/81626616/164004940-2aa7d59a-17a6-4c06-b858-0b4f03889b4c.png)

**Comment by HGustavs** [comment]
This seems like a minor bug, consider this a target if we have performed the move to css grid, and leave as is otherwise is my recommendation.

**Comment by a20sarle** [comment]
Reference #11246 (research CSS grid regarding code viewer) and #11403 (first test to implement CSS grid).
Putting this issue on hold untill' both the issues mentioned are completed.
