### ISSUE TITLE
When trying to create a new course by copying a previous course something goes wrong.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11694]
When doing this nothing is shown on the page and it looks like no course is created. 
Before doing this it looks like this: 
![image](https://user-images.githubusercontent.com/80856978/164026567-bda5a28f-f416-479b-adf0-960faf806a7e.png)

And after trying to copy a course it looks like this:
![image](https://user-images.githubusercontent.com/80856978/164026883-5e633747-6521-48e1-a3ac-a078f9af7508.png)

To create a new course you have to press this plus button:
![image](https://user-images.githubusercontent.com/80856978/164027491-bda0e284-1f55-42ce-b002-94fa85002980.png)

**Comment by c20adael** [comment]
@a20novra worked on another issue when discovering this. #11222

**Comment by HGustavs** [comment]
This is a very important bug. 

I would preoritize finding the reason for this problem.

**Comment by a20novra** [comment]
@c20adael you can close this issue!
