### ISSUE TITLE
Edit button still not showing in template 10

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11708]
Another issue (#11607) accidently broke a fix in #11536. The code need to be adjusted to fix the issue.

**Comment by HGustavs** [comment]
Screenshot please to confirm that this is indeed a bug

**Comment by a20willa** [comment]
The edit button (among other icons) are missing in the below image
![image](https://user-images.githubusercontent.com/81626616/164219558-e9cde900-d51d-4d81-b671-182ae8357704.png)
