### ISSUE TITLE
Research why webbprogrammering does not respond when pressing on background element.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11707]
#11637 was suppose to fix this but only does so in some cases

**Comment by a17nikjo** [comment]
problem solved was related to the class name being different for the href.
Now searches for the href among the children of the parent node of the background object.

**Comment by HGustavs** [comment]
Screenshot to clarify. Not clear what view and in what cases this is a problem

**Comment by a20behta** [comment]
@HGustavs This is related to a seperate issue  #11637 which uses background area for mobile use. 

solution is merged into weekly branch waiting untill weekly merge into master to close issue

**Comment by a20behta** [comment]
issue solved and merged into weekly merge
