### ISSUE TITLE
Diagram: Remove or fix?

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11728]
![image](https://user-images.githubusercontent.com/81772705/164246705-353f8cbe-8dbb-45b8-b34e-1029faa750d0.png)

Remove the submission section or fix so that the minusbutton is presented in a better way.

**Comment by HGustavs** [comment]
Low priority.

Do not remove functioinality but feel free to make this prettier.

But not a priority since this is not meant to be used on mobile platforms anyhow.
