### ISSUE TITLE
Make IFRAMES respect dark mode

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11724]
Reference to #7761 and #11725. Iframes will keep their current white background in codeviewer even if it's in darkmode. The contents of the IFRAME however should also be darkmode.

**Comment by b20idawa** [comment]
It is possible to implement darkmode on iframes to a certain extent, but it will not follow the standard that LenaSYS has for darkmode.

It is not possible to implement code that changes to darkmode for example wikipedia that follows the LenaSYS standard for darkmode. But websites that have already implemented darkmode will show the page in darkmode in the iframes. An alternative solution is to use filters and invert () together with grayscale () to change web pages in iframes.

The image below shows two different iframes where one is Wikipedia and the other one is LenaSYS.
<img width="1340" alt="Skärmavbild 2022-04-21 kl  13 37 48" src="https://user-images.githubusercontent.com/81676911/164450111-821a9a8a-b431-4ad8-b6c7-14f5307e7b33.png">

The image below shows what the different iframes look like when the user uses darkmode without any code having been implemented
<img width="1334" alt="Skärmavbild 2022-04-21 kl  13 38 35" src="https://user-images.githubusercontent.com/81676911/164450223-cf863c5e-18ed-467a-b5a1-d38fd18bcc8b.png">


The image below shows what the different iframes look like when the user uses darkmode and code has been implemented. The code that it used:
`iframe {
     filter: grayscale (1) invert (0.85);
}`
The problem with this solution is that websites that already has implemented darkmode will be inverted too with this code. 

<img width="1335" alt="Skärmavbild 2022-04-21 kl  13 39 05" src="https://user-images.githubusercontent.com/81676911/164450275-a6aad4fe-4323-4650-a2d9-dcb9c94b4c7b.png">

**Comment by a20willa** [comment]
Closing issue as @b20idawa has concluded it would be very inconsistent if implemented. ALL websites cannot use the same standard as lenasys.
