### ISSUE TITLE
Boxes overlap in HTML Example 1: Basic canvas graphics

### ISSUE THREAD

**Issue by a20linth** [HGustavs/LenaSYS#11734]
One of the cogwheels in HTML Example 1: Basic canvas graphics overlaps with another box.

![image](https://user-images.githubusercontent.com/102609651/164267240-1865d7b5-ada2-41be-876c-1b179385718e.png)

**Comment by a20sarle** [comment]
@HGustavs  Should this be put on hold for the same reasons as issue #11685 (untill' CSS grid research issue #11246 has been finished)?

**Comment by b20sebka** [comment]
If this issue can not be replicated now after css grid was implemented this issue can be closed.

**Comment by b20idawa** [comment]
It looks like this issue has been resolved already. Does not seem to be a problem anymore
<img width="1438" alt="Skärmavbild 2022-05-03 kl  13 25 28" src="https://user-images.githubusercontent.com/81676911/166444852-9f740e23-ec63-46ca-bde1-f3aee0f3a319.png">

**Comment by b20sebka** [comment]
Issue was resolved when css grid was implemented, no longer an issue.
