### ISSUE TITLE
The different courses does not seem to be correctly centered.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11732]
This is more clear when the screen is not very wide but seems to still be there when viewed at fullscreen.

![image](https://user-images.githubusercontent.com/80856978/164260494-39a4f67a-fcfe-4fdb-be41-a695c96c5aff.png)

**Comment by a20caros** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/81676918/164410021-0f2f6eca-084a-4ca0-9b60-8a86d04ba6d4.png">
When a user logs in, menu selections are centered. It is the gear that is also shown that makes the menu centered correctly

**Comment by a20caros** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/81676918/164455428-a6e5bcc6-5ff1-4363-8514-9ac7e9913255.png">
Deleted a margin-right: 15px when not logged in. Needed only when you are logged in to the page as it is a gear symbol that should also be centered together with the text

**Comment by a20behta** [comment]
merged into weekly branch. closing issue
