### ISSUE TITLE
Split contribution database into smaller databases

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11736]
Team was given a single database file which represents test data for one course. 
To implement multible database integration it requires multible databases which can be tested. 

Need to move some info from the current database and split it into seperate databases

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/164412666-16ee662f-1994-40f9-9caa-bc55756821cb.png)
Separated the contribution database into database files for each contributing user. The files are shared via local file transfer since it contains GDPR sensitive entries.
