### ISSUE TITLE
The javascript code in the Shader examples runs when clicking the link in the selection page

### ISSUE THREAD

**Issue by a18gusjo** [HGustavs/LenaSYS#11749]
When redirected to a shader example in codeviewer the "alert( "I'm JavaScript!" );" - code runs by default:

https://user-images.githubusercontent.com/102605031/164455087-abd866cf-afa0-4d1e-b02f-1a2dc1ba7b18.mov

**Comment by HGustavs** [comment]
This is not from the iframe?

**Comment by a18gusjo** [comment]
Nvm, I will close this issue. Discussed it with William and as you say, it is normal behavour.
