### ISSUE TITLE
Mockup needs to be created for how the teacher shall handle account creation requests.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11741]
On the contribution.php site the teacher should be able to accept or deny the creation of accounts requested from students. How can this look.

**Comment by a20vicad** [comment]
Proposed button placement (First the buttons need to be better arranged)
![image](https://user-images.githubusercontent.com/102599327/164423870-42d201d6-abc7-44e5-8971-0a6a691717dd.png)

Pop up
![image](https://user-images.githubusercontent.com/102599327/164424102-e78212fa-33d4-4f63-bf79-bcd13e16b38e.png)

**Comment by c20adael** [comment]
I thinck you should move the button "users" to the right top corner and change the title to Account requests.

**Comment by a20vicad** [comment]
How's this?

**Comment by c20adael** [comment]
@HGustavs Is this the desired way to hadle the creation of the github logins accounts?

**Comment by HGustavs** [comment]
Yes. This is very much like how I imagined it.

Not sure about using a dialog for this. Perhaps through a "sidebar menu" like the yellow sidebar in the diagram view.

**Comment by a20caros** [comment]
Mockup for this issue with two different color suggestions.
<img width="407" alt="image" src="https://user-images.githubusercontent.com/81676918/164712762-a82d5dc2-161e-4f43-916b-bdf476034ccf.png">
<img width="409" alt="image" src="https://user-images.githubusercontent.com/81676918/164712941-3f773ef2-7486-4d2a-b62b-cd16c1138d84.png">
 Proposal 1
<img width="407" alt="image" src="https://user-images.githubusercontent.com/81676918/164713029-38386478-5ca0-49b7-ad38-07c70026d58f.png">
<img width="405" alt="image" src="https://user-images.githubusercontent.com/81676918/164713062-7e3f94e7-da28-414e-94af-2544b62a4801.png">
Proposal 2

**Comment by a20behta** [comment]
Second proposal looks good. 
if @HGustavs want something different let us know

**Comment by HGustavs** [comment]
Looks fine!

**Comment by HGustavs** [comment]
Do not re-invent any new types of wheels. Try to reuse script from orange side bar from diagram module.
