### ISSUE TITLE
What is version ID and Version name used for.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11740]
This issue originates from #11694

**Comment by a20novra** [comment]
version ID is primary key in the table vers, which mean that we can't remove it. Version name show that which semester belong to this course, till example which (HT, VT, ST, spring, sommar, fall and ... .) 
![9999](https://user-images.githubusercontent.com/81618150/164425635-1fa4d330-5a8e-4ea8-819a-1650bf52c213.jpg)

**Comment by a20novra** [comment]
@c20adael
