### ISSUE TITLE
Check if possible to create default toolbar in diagram dugga to show teachers when they are logged in.

### ISSUE THREAD

**Issue by c20emili** [HGustavs/LenaSYS#11748]
currently the toolbar for in diagram dugga depends on the version of the dugga the student have and the teachers don't have that when they're logged in so check if its possible to create a default toolbar setting so the teachers dont have a weird toolbar. connected to issue #11643. 
Teachers toolbar
![image](https://user-images.githubusercontent.com/81320323/164451808-ae79ce25-546c-4bcf-8725-24a3f2bf18c4.png)
Student toolbar
![image](https://user-images.githubusercontent.com/81320323/164451918-f05a12f6-7c92-48df-abd1-9db4d919c4e9.png)

**Comment by HGustavs** [comment]
Im thinking we go by a selection in the menu whether we are making an ER/UML/Either etc type diagram and the menu depends on this choice. Or am I missing something. I dont understand what the difference is exactly.

**Comment by i19matla** [comment]
Issue merged
