### ISSUE TITLE
There exists a margin on the start page that seems to serve no purpose.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11754]
Why does the margin on the right of the divs exist?
Can they be removed?
![image](https://user-images.githubusercontent.com/80856978/164468004-7fad2a8f-603f-438a-9cb8-1131e809dd40.png)

**Comment by a20caros** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/81676918/164678628-2d851b1c-b486-42b6-af1e-499efc7cb23c.png">
Can't see any reason to keep padding-right and margin-right on the list. The difference when you keep the code is that the list is moved a few pixels to the left, which means that the list is not centered in the middle. For this reason, padding-right and margin-right are removed

**Comment by a20behta** [comment]
merged into weekly branch. closing issue
