### ISSUE TITLE
Teachers should have a selction meny to be able change diagram types when they are logged in on diagram dugga.

### ISSUE THREAD

**Issue by c20emili** [HGustavs/LenaSYS#11758]
Since the students diagram type is decided by the variant of the dugga and the teachers don't get the same information when they are logged in (at least toddler doesn't) the teachers should have a meny to be able to select the diagram type availible on the toolbar when logged in. connected to issue #11748.

**Comment by b20thelo** [comment]
Closed because this was a misunderstanding and we later realised that this functionality isn't needed.
