### ISSUE TITLE
Expanding darkmode to dialogs

### ISSUE THREAD

**Issue by a20willa** [HGustavs/LenaSYS#11777]
In the dugga viewer (sectioned.php) there are a dialog which pops up when pressing the "cogg" icon. The dialog does currently not use darkmode however, and thus should be implemented. 

There may be other places where this is true too. The same should be applied for **all** dialogs on lenasys. 

![image](https://user-images.githubusercontent.com/81626616/165036099-93631fe7-59a4-4c9d-aae8-2feb0d003be2.png)
![image](https://user-images.githubusercontent.com/81626616/165036178-d7d7328c-9ac1-4330-8dd1-c08ae1db8344.png)

**Comment by b20idawa** [comment]
How to test the issue:

1. Log in as a teacher

2. Select the web programming course

3. Press the gear at the right of any example
<img width="1288" alt="Skärmavbild 2022-04-25 kl  10 34 42" src="https://user-images.githubusercontent.com/81676911/165051812-fe5797d0-e35c-4323-960e-31b9b4e5151b.png">

4. Switch to dark mode

5. Check that the result looks like the image below
<img width="509" alt="Skärmavbild 2022-04-25 kl  10 35 15" src="https://user-images.githubusercontent.com/81676911/165051872-c38aa1e1-1171-4c22-b576-adfd2d9a0e9e.png">

**Comment by b20idawa** [comment]
How to test the issue:

1. Make sure you are logged out

2. Select darkmode on your computer

3. Open the login box and make sure it has darkmode (ie dark background and white text, see example image below)

4. Log in as a teacher

95. Click on the highlighted buttons as shown in the image
<img width="1305" alt="Skärmavbild 2022-04-25 kl  13 52 20" src="https://user-images.githubusercontent.com/81676911/165084043-6eb6d30a-d056-4822-b642-2c6c945af38f.png">

6 Check that all the dialog boxes that are displayed have dark mode according to the example image below

7. Select the web programming course

8. Click on the highlighted buttons as shown in the image
<img width="1305" alt="Skärmavbild 2022-04-25 kl  13 55 09" src="https://user-images.githubusercontent.com/81676911/165084491-782dc8f1-37f5-4c14-8159-bff319b16e0b.png">


9. Check that all the dialog boxes that are displayed have darkmode

Example of darkmode 
<img width="496" alt="Skärmavbild 2022-04-25 kl  13 58 14" src="https://user-images.githubusercontent.com/81676911/165084579-33134198-1581-4868-bf59-a1c60c4525f4.png">
