### ISSUE TITLE
Create the proposed mockup for contribution account handling.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11778]
Create the frontend part of this mockup. #11741
Go with the yellow design.

**Comment by a20caros** [comment]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/81676918/165096762-9a6029a5-9673-42c0-a39e-ddb42492bea5.png">
A screenshot of the side menu

**Comment by a20behta** [comment]
merged into weekly branch. closing issue
