### ISSUE TITLE
Create a new dugga that tries to load its instruction from a markdown file.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11773]
related to issue #10698

**Comment by a20vicad** [comment]
![image](https://user-images.githubusercontent.com/102599327/165043002-b0bb0fc4-699a-48a2-9871-0997da9b651a.png)
This is a created dugga that loads it's instructions from a markdown file. Success! I think.

**Comment by a20vicad** [comment]
A ""preliminary"" version of this specific issue has been made. It is now possible to make a "testdugga" that gets it's instructions from a markdown. 

More info in pull request
