### ISSUE TITLE
Accessibility software wants to add "alt" information about the image.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11789]
This is so that the screen reader can read the information about the image. We should add alternative information about the images in question. 

There is multiple places on the website where this is the case.
![image](https://user-images.githubusercontent.com/80856978/165061204-e94877a9-6754-48aa-b686-a9b65f93235a.png)

![image](https://user-images.githubusercontent.com/80856978/165061326-ee7ca8e5-c61a-490f-8dd6-473d9ba9a586.png)

![image](https://user-images.githubusercontent.com/80856978/165061778-9df36246-37bf-483b-b3f0-7e4de42e9cda.png)

**Comment by c20adael** [comment]
relating to #9800

**Comment by a17nikjo** [comment]
Added the nessessary tags.

**Comment by a20behta** [comment]
issue merged into weekly merge
