### ISSUE TITLE
Smallprogressbar in teacherview.php doesn't show correct 100% of the bar

### ISSUE THREAD

**Issue by c13marme** [HGustavs/LenaSYS#1179]
When the credit reach over 7.5(100%) for a student, the progressbar meter will go over bar for exampel when a student have 15 credit that is 200%.

**Comment by a13freas** [comment]
This is fixed now by changes in the DB.

**Comment by a13erilj** [comment]
Fixed with issue: 6b72a8578d4880fb1cfc6d6e6d2d613695912e81
