### ISSUE TITLE
There seems to be a function onklick when pressing the titles of the table.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11806]
If you hover over the table headers in the picture the mouse changes to a pressing hand. This seems to be because there is a onklick feature to sort the table depending on what you press. But is does not work.
![image](https://user-images.githubusercontent.com/80856978/165096560-91e32f50-e32b-4069-890d-2c460b4e7e89.png)

**Comment by c20adael** [comment]
This happens on the contribution page

**Comment by b20hanwa** [comment]
The code for this table can be found in _contribution.js_, starting on row 1082.
There is also one line for the table in _contribution.php_ on row 44.
I also think that _contributionservice.php_ is used, but I don't really understand how. Same goes for _sortebleTable.js._ 


Sence I don't fully understand the code, I won't be able to solve this issue.
