### ISSUE TITLE
CodeViewer: Code fonts

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#1180]
The code documents should be viewed in a different font, same font as the markdown code boxes (implemented soon by Daniel)

**Comment by HGustavs** [comment]
Fixed with.

Is there a condensed fixed width font that is web-safe to use?

courier takes up a __lot__ of space

**Comment by c12jenek** [comment]
How about Verdana? Is the same one as Notepad++

**Comment by a13alfbe** [comment]
I'm thinking that a monospaced font would be nice.

**Comment by HGustavs** [comment]
perhaps a css stack like this one:
font-family: Andale Mono,AndaleMono,monospace;
