### ISSUE TITLE
Zoom RESET button moves the position of the camera to the diagram's origo in addition to reseting the zoom.

### ISSUE THREAD

**Issue by a20chrka** [HGustavs/LenaSYS#11810]
This is a problem because the user/creator of the diagram may choose to add all entities far away from origo, say x: 2000 and y: 3000 for example. This will render the button entirely useless since the workspace is nowhere close to x: 0, y: 0.
Therefore, zoom reset should only restore the zoom factor to 1x, as the name of the button suggests, without repositioning the camera.

**Comment by HGustavs** [comment]
Good idea
