### ISSUE TITLE
contribution login remove forgot password

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11820]
When popup login on contribution has a forgot password location, this should not be the case but rather the teacher needs to delete and reaccept the account creation as we are not allowed to save information to verify identity. 

link and functionality needs to be removed. 
![image](https://user-images.githubusercontent.com/102468604/165253053-20e7aeab-ab35-4314-a7b6-708bd904c787.png)

**Comment by HGustavs** [comment]
Yes we need to remove this. Good catch.

**Comment by a20behta** [comment]
Placed on hold untill new implementation of login is included.
