### ISSUE TITLE
Contribution hardcoded Hgustav as first student

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11825]
After splitting  the databases it noticed that all databases loaded in Hgustavs as the first student. 
seems like the first location is hardcoded. 

remove and let it load dynamically instead of hardcoded. 
seems only default however needs to explore more
![image](https://user-images.githubusercontent.com/102468604/165261874-7839dd9d-0284-4332-80e8-7c109c0121fb.png)

**Comment by HGustavs** [comment]
Hgustavs used to be the default if no student is logged in, so this needs to be changed to the currently logged in student I think.
