### ISSUE TITLE
Redirect camera to center

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#11822]
Redirect camera to center will instead be named Reset view. When clicked all elements should be viewed. 

![image](https://user-images.githubusercontent.com/81772705/165255041-c49a7bd6-9509-4795-aa8b-0a775119a7bf.png)

**Comment by a20edwth** [comment]
Changed redirect camera to center so the zoomfactor is set appropriate to the size of the diagram.

Instructions for testing:
1) Click "Demo-Course"
2) Click "Diagram Dugga"
3) Change the size of the diagram and click Redirect camera to center.

**Comment by i19matla** [comment]
Because of the label close, i close this issue now. Can´t see it is merged.
