### ISSUE TITLE
Mockup, dynamically choose database contribution

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11827]
When implementing the backen for dynamically chosen databases, the structure used does not fit how the structure of loading in the database. 

A new mockup is needed to make confirm how the new look will be. 

a single dropdown for years followed by a popout on the loaded in files in each year/directory should be used.

**Comment by a20johba** [comment]
![image](https://user-images.githubusercontent.com/102599568/165271475-2a43c3ba-9962-4ab4-9462-e34301fe507f.png)
Mockup of the new dropdown menu. The user can hover the mouse over a year and it should display all available files in a new menu to the side

**Comment by a20johba** [comment]
I was unable to find a good way to implement a multi-level dropdown menu. Unfortunately it seems that this is not a natively supported feature and implementing it requires custom code to be written. This is probably doable but I lack the HTML/Javascript knowledge for this. Instead, I added a quick fix that hides the course dropdown menu until a year has been selected.

**Comment by b20hanwa** [comment]
This issue is not relevant anymore sence the costumer wanted a different design for the dropdown menu. You can read about this in issue #11879.
