### ISSUE TITLE
Logging support in code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1183]
Im not sure if this issue has been reported previously... but it would be nice if we could get logging to work for the code examples so we see whom has been viewing the code examples.

I believe that the dugga-system has logging functionality working, it is "just" a question of hooking it up to the code viewer.

**Comment by f12danjo** [comment]
Fixed by [#1341](https://github.com/HGustavs/LenaSYS/pull/1341).
