### ISSUE TITLE
Quick fixes on high score list

### ISSUE THREAD

**Issue by a13karsi** [HGustavs/LenaSYS#1184]
The high score list lists the same person many times if that person has taken a dugga many times, it looks nicer if the list only shows the best score (quickest time) for each person and can list more user names associated with scores.

**Comment by HGustavs** [comment]
I really like this service.

...but...

Not all "dugga"-s are time-based.

It would be nice if we could score differently on different "duggas" i.e. by the javascript submitting a "score" depending on factors... such as the number of clicks in bit-counting. The more clicks the more guesses.... which should give lower scores.

**Comment by a13karsi** [comment]
That's a good idea. I think we were going to implement the timer in all of the duggas but your click counter sounds like a really good idea too.  This service is just at its infancy just yet though so there's a lot of room for improvement!

**Comment by HGustavs** [comment]
Im thinking that each dugga is responsible for its own scoring e.g. that we supply a framework and example code for submitting highscores, and that each dugga decides what to submit in some cases it is time, in some case clicks and in other cases something completely different.

**Comment by a13karsi** [comment]
I'll make sure to talk with Erik about this (He's the magician behind most of the highscore code)
