### ISSUE TITLE
Fix the button alignment for the top bar and remake the dropdown to be of the standard type.

### ISSUE THREAD

**Issue by c20adael** [HGustavs/LenaSYS#11879]
![image](https://user-images.githubusercontent.com/80856978/165743574-fbbaa160-46fa-4c3f-a853-c4fb99d2a080.png)

**Comment by c20adael** [comment]
Also try to fix the big gap between the two most right buttons.

**Comment by b20eripe** [comment]
Seems to be a CSS problem related to the buttons belonging to different classes
