### ISSUE TITLE
contribution login dedicated css

### ISSUE THREAD

**Issue by a20behta** [HGustavs/LenaSYS#11898]
currently the popup login on contribution copies the already established code for login. 
it needs to be seperated and placed into dedicated css html which can be used to completly seperate the contribution login for the rest of the page

**Comment by a20sacka** [comment]
I created the following flow chart for what happens during the login process on the contribution.php page if you are not logged in, I will implement support for these in css/javascript in a more concise way than everything done purely in javascript. 
<img width="529" alt="ContributionGUIFlow" src="https://user-images.githubusercontent.com/102584289/167101780-5c914823-4440-436f-a6c2-0c3eb73a3a62.png">

**Comment by a20sacka** [comment]
after finishing the issue this is the final flowchart of the login process
![image](https://user-images.githubusercontent.com/102584289/167488570-7933605e-f9b6-44ec-b3b3-db7638ef625e.png)
