### ISSUE TITLE
ER-Table generation needs to consider foreign keys for each entity in the diagram.

### ISSUE THREAD

**Issue by a20chrka** [HGustavs/LenaSYS#11915]
Sub-issue to: issue #11744

In ER, there are different rules for how you should handle relations between entities when creating an ER-Table based on an ER-model/diagram, specifically how to handle "1-1", "1-N" and "N-M" relations. Look up the rules for how to handle these, and implement functionality accordingly. (This may be of use: https://www.gatevidyalay.com/er-diagrams-to-tables/)

All code regarding the generation of the ER-table string is found in lenasys/DuggaSys/diagram.js, in the function "generateErTableString()".

I suspect that this issue may need further splitting, since each type of relation are resolved differently.

**Comment by a20gabpa** [comment]
The solution has been merged.
