### ISSUE TITLE
ER and UML checkboxes functionality needs rework

### ISSUE THREAD

**Issue by a16linas** [HGustavs/LenaSYS#11920]
Currently when allowing both ER and UML diagram type in variant editor, the diagram doesn't get rendered until you zoom in/out and then it renders the default diagram template. However, if only one of them is selected, the diagram is rendered as expected. Also, having none of them selected shouldn't be allowed.

![bild](https://user-images.githubusercontent.com/37794783/165778029-7950bd3f-af64-4d90-9093-3f3efba9008d.png)

![bild](https://user-images.githubusercontent.com/37794783/165777710-13f36646-fb29-4b16-80b8-c723799e1e93.png)

**Comment by c20emili** [comment]
The problem is not in the ER/UML types. The problem lies in that the json string changes length and currently the way the file is found is by counting characters. So if anything other than the diagram type change the file does not get found because the name becomes wrong.
