### ISSUE TITLE
Whitespace in templates

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#11936]
Many templates have a whitespace where the background does not stretch the whole box
![image](https://user-images.githubusercontent.com/102599780/165939591-c3b25e41-832a-42c0-9946-984832f7b56d.png)
This one in particular is in template 3

**Comment by b20sebka** [comment]
![image](https://user-images.githubusercontent.com/102599780/165953666-5f0ece8c-e73a-429b-a837-5af7c75527e2.png)
the box follows the grid but the background does not stretch the entire way. Think this has been an issue before grid layout was implemented.

**Comment by b20idawa** [comment]
How to test the issue:

1. Select the web programming course
2. Select JavaScript Example 1
<img width="1386" alt="Skärmavbild 2022-05-02 kl  11 38 58" src="https://user-images.githubusercontent.com/81676911/166214911-a0b79e32-65ff-4d0c-a9de-7400153dbbd5.png">
3. Check that the whitespace is removed in both lightmode and darkmode
4. The result should look like the pictures below
<img width="1397" alt="Skärmavbild 2022-05-02 kl  11 39 37" src="https://user-images.githubusercontent.com/81676911/166215015-77cbf97d-84c6-4a2a-ab76-0f41d296fc14.png">
<img width="1386" alt="Skärmavbild 2022-05-02 kl  11 39 46" src="https://user-images.githubusercontent.com/81676911/166214975-18c9efb9-ba2f-4ece-9c3c-68ff1bc8419e.png">

**Comment by b20sebka** [comment]
Was not closed after merge.
