### ISSUE TITLE
Remove contriution database from github

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#11943]
Contribution database is available in github, it should not.
![image](https://user-images.githubusercontent.com/102599327/165942801-8baa209a-4386-4380-889c-27f76a8a8a82.png)

**Comment by b20eripe** [comment]
@b20hanwa Test this by merging with mergeW5 and then verify that this specific .db file is removed as it should

**Comment by b20eripe** [comment]
Fixed
