### ISSUE TITLE
When pressing the gear the background turns into white

### ISSUE THREAD

**Issue by b20idawa** [HGustavs/LenaSYS#11955]
When you press the gear at the home page the background at the homepage turns into white. This should not happen. 

https://user-images.githubusercontent.com/81676911/165950449-5a0af224-5f77-45e3-b887-1bee447c4341.mov

**Comment by b20idawa** [comment]
How to test the issue:

1. Log in as a teacher
2. Select darkmode on the website
3. Press the gear at the right of any course
<img width="1369" alt="Skärmavbild 2022-05-02 kl  10 03 02" src="https://user-images.githubusercontent.com/81676911/166203536-8031e807-dc8b-45ba-979c-460966efb7c5.png">

4. Check that the background of the list of courses is still black
5. The result should look like the picture below
<img width="1373" alt="Skärmavbild 2022-05-02 kl  10 05 13" src="https://user-images.githubusercontent.com/81676911/166203589-fb5a50d0-558f-4ba9-a405-a478136b1314.png">

**Comment by b20sebka** [comment]
Was not closed after merge.
