### ISSUE TITLE
Version ID box has dark background in darkmode

### ISSUE THREAD

**Issue by b20idawa** [HGustavs/LenaSYS#11957]
When press the gear in the navbar one field has dark background in darkmode
<img width="886" alt="Skärmavbild 2022-04-29 kl  15 14 46" src="https://user-images.githubusercontent.com/81676911/165951540-e124f839-24d3-4a58-a23e-a5091433848c.png">

<img width="496" alt="Skärmavbild 2022-04-29 kl  15 10 41" src="https://user-images.githubusercontent.com/81676911/165951429-cc8d0273-da80-4021-8436-1dbc67d713f3.png">

**Comment by b20fanfa** [comment]
### For testing: 

1. Click on a program, e.g. Webprogramming.
2. Click on darkmode toogle.
3. Click on the gearwheel located at the top of the navigation bar. This is the first field that should look like in the image. (It should have a light gray background). 
<img width="481" alt="Skärmavbild 2022-05-02 kl  10 46 10" src="https://user-images.githubusercontent.com/81618770/166209121-92a3e6fb-4ee1-403c-b3a9-e669b7cc7b13.png">

**Comment by a20willa** [comment]
Tested according to test-description.
Code refactoring - ok
Code standard - ok
Meet issue goal - yes

**Comment by b20sebka** [comment]
This was not closed after merge.
