### ISSUE TITLE
The Fab button menu is placed behind other elements on the page

### ISSUE THREAD

**Issue by b20idawa** [HGustavs/LenaSYS#11952]
The Fab button menu is placed behind other elements on the page
<img width="552" alt="Skärmavbild 2022-04-29 kl  14 51 47" src="https://user-images.githubusercontent.com/81676911/165948157-a429ec46-8858-4530-9752-773979d1c0c0.png">

**Comment by b20sebka** [comment]
Issue only happens when page is smaller than normal but not yet mobile view, not important to fix.
