### ISSUE TITLE
Link in new tab icon is black in darkmode

### ISSUE THREAD

**Issue by b20idawa** [HGustavs/LenaSYS#11950]
The "link in new tab" icon is still black in darkmode and should be white instead to match the other icons
<img width="372" alt="Skärmavbild 2022-04-29 kl  14 47 27" src="https://user-images.githubusercontent.com/81676911/165947488-8240b428-a6d6-4068-a988-8388ec42e590.png">

**Comment by b20sebka** [comment]
fixed in issue #11961
