### ISSUE TITLE
Github redirect

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#11967]
When you press the lenaSYS title in the main screen you get redirected to the github. Small QOL change of making it open in a new tab

https://user-images.githubusercontent.com/102599780/166196661-7f88c127-d7c7-47ab-b37a-9546e835bddc.mp4

**Comment by b20idawa** [comment]
How to test the issue:

1. Open LenaSYS
2. Press the LenaSYS icon
<img width="1374" alt="Skärmavbild 2022-05-02 kl  09 24 19" src="https://user-images.githubusercontent.com/81676911/166199110-3fbc1371-4aae-4a8e-b983-449d1e8bd9e6.png">
3. Check that the github link opens in a new tab

**Comment by a20willa** [comment]
Tested according to test-description.
Code refactoring - ok
Code standard - ok
Meet issue goal - yes

**Comment by b20sebka** [comment]
Was not closed after merge.
