### ISSUE TITLE
Change so that table have no decimals in contribution.php

### ISSUE THREAD

**Issue by b20hanwa** [HGustavs/LenaSYS#11968]
![ContributionDecimals](https://user-images.githubusercontent.com/81630271/166197212-117ce80a-948a-4443-abab-294991865e42.png)

This table should not contain any decimals.

**Comment by a20caros** [comment]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/81676918/166199310-29a6cabb-18f1-432b-9adb-c0d652499e5c.png">

<img width="558" alt="image" src="https://user-images.githubusercontent.com/81676918/166199266-0f1aa64a-5874-4733-acbe-a927e34e6408.png">
Now only the table row has rank decimals


To test it go to the contribution page and scroll down to the second last table on the page. Check that there are no decimals
