### ISSUE TITLE
Undo function 

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#11960]
An undo function when choosing the examples would be good if someone were to accidentaly delete an example and wanted it back.

**Comment by a20andlj** [comment]
Testing:
1. Login as a teacher.
2. Delete an example
3. Press Yes - a recycle icon should appear besides the + and the ghost icons.
4. Press the recycle icon
5. The example should reappear

Testing 2:
1. Delete another example
2. Press yes
3. Wait for 60 seconds - then the recycle icon should disappear and the example should still be deleted.

**Comment by b20sebka** [comment]
Was not closed after merge.
