### ISSUE TITLE
Hourly activities in contribution not working

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#11972]
This graph does not seem to function properly. Some info is visible at startup. However, when trying to enter specific weeks this information is no longer available.
![image](https://user-images.githubusercontent.com/102599327/166199576-86514824-bd35-4d6a-b819-9a1aef0d523c.png)

**Comment by b20jonlu** [comment]
This is already fixed in this issue https://github.com/HGustavs/LenaSYS/issues/11878
