### ISSUE TITLE
The snap is to sensitive for label displacements

### ISSUE THREAD

**Issue by c20emili** [HGustavs/LenaSYS#11981]
It is to hard to select the middle position because the snap is to sensitive

https://user-images.githubusercontent.com/81320323/166203007-d91dff83-60a0-498f-9414-e63028b7095c.mp4

.

**Comment by c20emili** [comment]
changed the snapping distance for easier to select the line in the middle.
#11981

https://user-images.githubusercontent.com/81320323/166203848-1ad8f4b1-c2ec-4d38-a5fb-e6e227e1ab94.mp4

**Comment by b20thelo** [comment]
Tested on three different computers and works well. Approved by Christian
