### ISSUE TITLE
Fix a new icon for box-selection tool

### ISSUE THREAD

**Issue by a20samul** [HGustavs/LenaSYS#11989]
The box-selection tool has a new way of showcasing its functionality. 
- Update the icon so it represents the new way that the functionality is displayed.

<img width="378" alt="boxselectionfunction" src="https://user-images.githubusercontent.com/81613484/166207544-83f8b208-f925-43e8-9547-2ff05116c0aa.png">

**Comment by b20thelo** [comment]
New icon approved by Christian.
