### ISSUE TITLE
There is a bug with Important Word.

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1198]
![tesr](https://cloud.githubusercontent.com/assets/11715450/7366868/821956bc-ed9b-11e4-86d5-ad517433e9ef.jpg)

If you add "var" like a Important Word. Then var in the word variable will also be highlighted

**Comment by HGustavs** [comment]
This is most definitely a bug that we need to look at if it is fixable.

Don't put too much time into this since there are other more severe issues to work on, but if there is a quick simple fix I dont mind fixing it.

**Comment by HGustavs** [comment]
I think that it works if one enters var"space" rather than just var?

**Comment by b12simsa** [comment]
This might be fixed, at least I cannot recreate the bug.

**Comment by c13caral** [comment]
This is no longer relevant. I will now close this issue
