### ISSUE TITLE
Dark mode in pages

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12007]
![bild](https://user-images.githubusercontent.com/102599780/166214584-91278a53-4669-451f-8c5f-cd69a0d0d05c.png)
the dark/light switch does not work on the pages these redirect to and they are not defaulted to dark mode if dark mode is the current mode.

**Comment by b20fanfa** [comment]
## For testing: 

1. Log in as a teacher. 
2. Enter a program, e.g. Webprogramming. 
3. In the navigation bar there are 4 icons. Go to each page and see that there is dark mode on all pages.
<img width="198" alt="Skärmavbild 2022-05-03 kl  11 53 13" src="https://user-images.githubusercontent.com/81618770/166434604-8725c37e-a5f4-47c1-9d09-6c7e7e21f2d7.png">

### There are some specials, which need to be checked a little more closely:
4. Go to this icon: <img width="36" alt="Skärmavbild 2022-05-03 kl  11 55 29" src="https://user-images.githubusercontent.com/81618770/166434732-6e1b37e0-ce0f-4f68-815c-f36e5fd32650.png">
4.1 When you click on both buttons, the background should have a dark color.
<img width="376" alt="Skärmavbild 2022-05-03 kl  11 56 58" src="https://user-images.githubusercontent.com/81618770/166434905-2b61c285-0395-426c-828d-486ae440865d.png">
4.2 When hovering over the search bar, a "pop up" appears that should have a black background with white text in dark mode.
<img width="298" alt="Skärmavbild 2022-05-03 kl  13 21 35" src="https://user-images.githubusercontent.com/81618770/166444289-6872c903-33f2-4573-9309-fa5eefcc870c.png">

5. Go to this icon: <img width="36" alt="Skärmavbild 2022-05-03 kl  11 57 25" src="https://user-images.githubusercontent.com/81618770/166434968-b8ffd1f5-6763-43d6-8f7e-3fcbafae271c.png">
5.1 Scroll to the bottom of the page and see that the tables are the same color as the others (purple).
Also check that the background of the table is dark.

<img width="1128" alt="Skärmavbild 2022-05-03 kl  12 00 18" src="https://user-images.githubusercontent.com/81618770/166435295-6d24ac01-8f2f-476a-9177-838b2c32ff26.png">

**Comment by b20sebka** [comment]
This was not closed after merge.
