### ISSUE TITLE
Unable to edit or create new versions of courses

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#1201]

**Comment by a13karsi** [comment]
You can, it's in the section editor

**Comment by c13chrjo** [comment]
Yeah, but the changes doesn't apply for me.

**Comment by c13chrjo** [comment]
This may be fixed when we clear the entries in the database tomorrow

**Comment by a13oscwe** [comment]
Merging this issue with issue #1217 and closing.
