### ISSUE TITLE
Dark mode issue

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12012]
![bild](https://user-images.githubusercontent.com/102599780/166215522-aa17423f-2641-4fe5-8ee1-16d43978bc28.png)
When clicking the speaker icon this tab opens and it does not follow the current color mode.

**Comment by b20fanfa** [comment]
## For testing
1. Enter a program, e.g. Web programming
2. Click on the "announcement" icon, which is located in the navigation bar.
3. Click the toggle button a few times to see both modes.

*This is what the icon looks like:*
<img width="57" alt="Skärmavbild 2022-05-02 kl  13 33 41" src="https://user-images.githubusercontent.com/81618770/166227353-fef1d1e8-6ede-40a2-8351-893ebe0050d4.png">
 
### Results: 
In dark mode: 
<img width="1075" alt="Skärmavbild 2022-05-02 kl  13 37 48" src="https://user-images.githubusercontent.com/81618770/166227717-7e1db2f6-d7ea-46a9-9678-e1a0bfd3220b.png">

In light mode: 
<img width="1078" alt="Skärmavbild 2022-05-02 kl  13 37 40" src="https://user-images.githubusercontent.com/81618770/166227727-95d78aec-0b10-445c-81f5-cf84614204aa.png">

**Comment by b20sebka** [comment]
Was not closed after merge.
