### ISSUE TITLE
The cancel button is wrong placed 

### ISSUE THREAD

**Issue by b20idawa** [HGustavs/LenaSYS#12018]
The cancel button in the dialog box that appear when you press the gear button should be better placed. The button is not in a straight line with the save button
<img width="933" alt="Skärmavbild 2022-05-02 kl  11 55 51" src="https://user-images.githubusercontent.com/81676911/166216935-e21805a2-db7a-4787-b5d6-f4841f9c2e78.png">

**Comment by b20sebka** [comment]
This was not closed after merge.
