### ISSUE TITLE
In some template one codebox look "disable"

### ISSUE THREAD

**Issue by b20idawa** [HGustavs/LenaSYS#12015]
In some template one codebox look "disable".
<img width="1394" alt="Skärmavbild 2022-05-02 kl  11 49 43" src="https://user-images.githubusercontent.com/81676911/166216311-5d62d87f-2682-4a0f-8f31-3ece28ca0507.png">

**Comment by b20sebka** [comment]
Duplicate issue. same as #11930 which is fixed.
