### ISSUE TITLE
Can not open examples as designer

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12011]
When logged in as designer you can not open any examples.

https://user-images.githubusercontent.com/102599780/166215287-db89e26a-344d-41f0-bc33-5906316d6210.mp4

**Comment by a20linth** [comment]
Testing:

1) Login as a designer account (username: mestr password: password)
2) Enter Webbprogrammering course
3) Open any of the listed code dugga

Excpected result: The code example content should be visible and the user should have write access

**Comment by b20sebka** [comment]
Was not closed after merge.
