### ISSUE TITLE
Moving "moments"/"headers"/"i don't know what" does not move the duggas bellow with them.

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12020]
Pressing the header however, hides all duggas bellow.
![image](https://user-images.githubusercontent.com/102599327/166217365-7d466cc3-5eb6-4a3e-a150-0044df3e896b.png)

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/166237700-20d3ad18-8ca7-49ff-abbf-ae2723064846.png)

All data is saved in two arrays, one for courses and one for duggor

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/166428764-1398077f-8033-4b0e-bc56-af0f6c35a55c.png)

Also saved in local storage together with a lot of other data. pos is the position of the specific dugga

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/166446600-030ec40a-b149-476f-bd21-8d83942fac46.png)


Should these elements be movable? Why are the positions stored in local data and not only in a db-file? What purpose should a movement fulfill, to change categories of an dugga?

**Comment by a20vicad** [comment]
It does not seem like this should be done. This issue will soon be closed and another similar one will be made.
