### ISSUE TITLE
"+" button is in different places

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12061]
The yellow "+" button is in different places on almost all pages. There might already be an issue like this but anyways.
![image](https://user-images.githubusercontent.com/102599327/166426278-86667870-66da-4d39-82e3-881f3954b6c9.png)

**Comment by c20adael** [comment]
The code below is some of the styling that handles the fab button. As you can see there is some differences and apparently a .fixed-action-button2 that I need to check where it is being used.  
`/* FAB container */

.fixed-action-button {
  position: fixed;
  bottom: 24px;
  right: 24px;
  z-index: 1;
  touch-action: none;
}

.fixed-action-button.sectioned {
  right: 115px;
}

.fixed-action-button2 {
  position: absolute;
  top: auto;
  right: 24px;
  z-index: 1;
  touch-action: none;
}

.fixed-action-button2.sectioned2 {
  right: 125px;
}

.fixed-action-button3 {
  position: absolute;
  top: auto;
  right: 24px;
  z-index: 1;
  touch-action: none;
}


/* Fix mobile-view for top FAB-button and Sectionlist heading */
@media screen and (max-width: 680px) {
  .fixed-action-button2{
    display:none !important;
  }

}

#Courselist div.fixed-action-button a:hover {
  text-decoration: none;
}`

**Comment by c20adael** [comment]
I have added a new class instead of the previous class that was specific to the sectioned.php file. Now every button on the website has the extra margin to that the appear in the correct spot.
