### ISSUE TITLE
Pressing around the back button moves it but does not "activate" it

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12065]
There is a larger area around this button that can be pressed that makes the button "go down" without actually going back.
![image](https://user-images.githubusercontent.com/102599327/166430085-f677bc84-bca7-4713-b26a-becf1b9ea4c5.png)

**Comment by a20johba** [comment]
Changed the return button to be more similar to the dugga-related buttons, making it only appear interactive when hovering over the image. For some reason the bug still exists within a 1 pixel border around the image that I was not able to solve. This issue does not appear in the dugga-related buttons despite using the same code, so perhaps it is related to the image or the css code? Another issue may be necessary to solve this.

I also noticed that the same bug exists in the home button. A new issue should be created to solve this.
