### ISSUE TITLE
Commit tree and Weekly bar chart "scroll" differently. In the contribution page

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12086]
The Commit tree chart's scroll function is built into the chart. But on the Weekly bar chart overflows over the whole <div>

We want the Weekly bar chart to be the same as the Commit tree chart.
![image](https://user-images.githubusercontent.com/102599327/166447843-7a7d2f54-c1ab-4def-a6a4-5a6b6eb5154d.png)

**Comment by b20eripe** [comment]
They both are SVGs that are built in slightly different ways. Will research to find which of them to use.
