### ISSUE TITLE
You can't press the "X" on selected elements (when you try to remove it) when placing lines.

### ISSUE THREAD

**Issue by a20chrka** [HGustavs/LenaSYS#12104]
When the linemode is used and you have selected the first element it should be connected to, you cannot press the "X" on the element nor press the delete button on the keyboard.

![image](https://user-images.githubusercontent.com/102599740/166473391-c38bd9d6-d551-4329-91e0-c8362e3e44af.png)

**Comment by b20matad** [comment]
After enabling the possibility to delete objects, in line creation mode, we've decided this is not a good solution; since when you mark an element in line creation mode a ghost line is created from this element. We will instead remove the delete button while in line creation mode.

**Comment by b20matad** [comment]
How our solution looks and behaves.





https://user-images.githubusercontent.com/102598238/166882881-9a54615b-d04a-465f-b24d-952d84d18b57.mov
