### ISSUE TITLE
Opening duggas cause error messages

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12121]
like so. This is a major issue. Research this
![image](https://user-images.githubusercontent.com/102599327/166674726-346a4e7a-9eed-46e3-a7ae-bb0e3eca22a6.png)

**Comment by b20jonlu** [comment]
Able to replicate issue on [project.webug.his.se](http://project.webug.his.se/DuggaSys/showDugga.php?did=1&courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732&moment=2002&segment=2001&highscoremode=1&comment=null&deadline=2015-01-30%2015:30:00&cid=2). This issue does not appear on my localhost version of the same page.

**Comment by a20vicad** [comment]
The first groups solution for the diagramdugga is in pull req. #12123

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/167399898-ab311be5-8030-41e7-a515-24db948c1b3e.png)

Commenting out line 82, 83 and 84 removes this error. Doesn't seem to create new problems. These are used at other places in the code so some research is needed to understand if they really are needed.

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/168038547-f7b05c1a-9222-49a3-8e47-52b8b9eb5e76.png)

![bild](https://user-images.githubusercontent.com/102593527/168038777-78c66eac-816c-4062-85ec-4d75476f5009.png)

After merge on 2022-05-11 these error has been solved but new ones have erupted. The error is that these lines tries to read an file but is directed at a directory. Will research.

**Comment by b20hanwa** [comment]
This issue was solved by group 2.
