### ISSUE TITLE
You can't close the options menu unless you select an element first

### ISSUE THREAD

**Issue by a20chrka** [HGustavs/LenaSYS#12127]
You can always open it, however. But for some reason you can't press the options button again until an element has been selected.

**Comment by a20jacmi** [comment]
Now the menu can be closed/opened in any situation. We've also added functionality to close/open the menu by double clicking in the container, while in pointer-mode.

Changes are made in "diagram.js" for the following functions:
toggleOptionsPane()
mdown()
