### ISSUE TITLE
Courses hidden when not logged in.

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12149]
![image](https://user-images.githubusercontent.com/102599780/166871988-e06b3cef-5007-430b-975d-9f43b91b4029.png)
Customer thinks there is a bug where the courses have an opacity of 0.25 because when you are not logged in it thinks you are not registered in any course. 
When not logged in it should instead think that you are registered in every course and the opacity should be normal.

**Comment by b20sebka** [comment]
If a student is not registered in a course it should not show up at all. No opacity, no line through the text it should not be shown at all if you are not registered in it.

**Comment by a20linth** [comment]
Testing:

1) Logout of any currently logged in user
2) Home page should show all public courses
![image](https://user-images.githubusercontent.com/102609651/166897744-710d3d8f-f7f6-4486-b7ca-04ce464e73a5.png)
3) Login as a teacher account (username: stei password: password)
4) Home page should show all public and hidden courses
![image](https://user-images.githubusercontent.com/102609651/166898061-c8537ada-44fb-443f-9584-8074a87140cc.png)
5) Login as a student account (username: keree password: password)
6) Home page should only display courses registered to the student
![image](https://user-images.githubusercontent.com/102609651/166898943-d42b61fc-7422-4c62-807d-62dc2854be61.png)

**Comment by b20idawa** [comment]
Tested according to test-description.
Code refactoring - ok
Code standard - ok
Meet issue goal - yes
