### ISSUE TITLE
Research mobile view

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12147]
Is it possible to check whether an iPad is landscape or portrait mode? Is it possible to check explicitly if something is a phone using css? What is the best way to check and answer these questions?

**Comment by b20sebka** [comment]
It should for example be possible for an iPad in portrait mode to be recognized as a computer screen that is standing up straight.

**Comment by a18gusjo** [comment]
Is it possible to check whether an iPad is landscape or portrait mode? -
I am no css-expert but it seem to possible check whether an iPad is landscape or portrait modeusing media queries. One solution to this seem to be: 
@media (orientation: portrait) { … }
@media all and (orientation: portrait) { … }
which detects the orientation of the screen (https://www.w3.org/TR/mediaqueries-3/#orientation).

Is it possible to check explicitly if something is a phone using css? -
Media queries seem efficient for this as well. Check which max width of the screen resolution is one way to solve the problem:
@media only screen and (max-device-width: 480px){
 /* in mobile css commands */ 
}(https://www.codegrepper.com/codeexamples/css/how+to+detect+mobile+device+in+css).

What is the best way to check and answer these questions?
It seems like a good way to not force tablets to be in mobile view is to check for screen width. In that way, tablets can still use "regular screen" css.

@b20sebka does this answer your questions?
