### ISSUE TITLE
Dugga variant preview doesn't work as it should

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#12141]
When you create a diagram dugga variant and you want to preview it to see what it would look like for the student, it doesn't work as it should.

Preview button found here
![image](https://user-images.githubusercontent.com/81772705/166806633-8ca1b4fa-a497-49d0-a067-ec9baf973e46.png)

A few things that need to be looked at are:
- Even though the diagram variant in this example was set to only use ER (UML disabled) both functionalities are available in the preview (only in preview, not when you access the dugga as a student). It doesn't read the parameters correctly but instead show teachermode as the teacher is logged in.
- The hide/show button for the description is misplaced (only in preview, not when you access the dugga as a student). As a result this functionality doesn't work as it should there.
![image](https://user-images.githubusercontent.com/81772705/166807475-3bdae18e-df70-4b83-a4cc-7af5b56ba3ae.png)

The preview functionality should instead show the parameters generated in the param section. Parameters are shown here in the variant list:
![image](https://user-images.githubusercontent.com/81772705/166807008-1062c70c-433c-4cbf-a189-ffd7b54588f0.png)

**Comment by b20thelo** [comment]
The "hide/show button" was fixed in another issue. Not merged yet

**Comment by a20samul** [comment]
### Preview issue with the arrow fixed. refer to:
- #12408

<img width="678" alt="preview" src="https://user-images.githubusercontent.com/81613484/168063202-91dffbd8-a84d-43ed-8ae5-2865893a45cb.png">

**Comment by c20emili** [comment]
Part of the reason why the preview does not work is that the functionality that fetches the diagram and instructions files lays in showdugga.php rather than diagram.php. To solve this they need to be moved and the variabels $cid, $vers and $quizid needs to be fetched differently. A different part of why the preview does not work is that it does not execute the template(diagram_dugga).js file for which i don't know a solution right now.

**Comment by c20emili** [comment]
There is a solution for the issue but since it needs to move a significant part of the code that is in a wrong file (diagram specifik code that is in a global file for all duggas), the solution will have to wait after merge to ensure no one is changing the code that will be moved during the move.
