### ISSUE TITLE
Implement login for teacher in contribution

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12157]
Related to #11896 and #12008

Currently it is only implemented for users.

**Comment by a20sacka** [comment]
Added so if you exist on the "USER" table but dont have superuser status youre not allowed to login, this can be changed so all users on the "USER" table are allowed to log in with more priviliges than a normal git-student user. This is how it looks if you attempt to log in with a non super user 
![image](https://user-images.githubusercontent.com/102584289/166935487-9db7282a-ba6c-4e87-a600-e56ed27dc6a1.png)


If you now try to log in with a user that exists on the "git_user" table youre allowed to but your stored session variables dont get stored in the same variables as a teacher/super/one who logged in with someone who exists on the "user" table. The rest of the contribution file will need to take this into account for what is shown; Following is an example of where the user who logged in with the "git_user" table gets their session variables stored 
![image](https://user-images.githubusercontent.com/102584289/166936203-d5301a64-b159-480e-a24d-e44a8292b0c2.png)


Currently the check for viewing contribution content is done with 2 separate checks, in the future we might want to combine these into one dedicated check for viewing contribution data 
![image](https://user-images.githubusercontent.com/102584289/166936653-8b7df6e4-6f2b-49c2-9c41-0d2f22b9a495.png)
