### ISSUE TITLE
Reimplement dark mode in fileed.php

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12155]
After merge dark mode did not follow in fileed.php. Reimplement the dark mode.

**Comment by b20fanfa** [comment]
After fixing an earlier issue, one of the changes did not follow. 
To be a little more specific, it was this one. The background color became too light gray. It needs to be fixed.
<img width="1333" alt="Skärmavbild 2022-05-05 kl  10 27 08" src="https://user-images.githubusercontent.com/81618770/166887325-5ce5ce0b-a172-4be0-86f0-9d5dbd0d0b7c.png">
