### ISSUE TITLE
ER-Table generation: Allow the user to decide which candidate-key to be used as primary key.

### ISSUE THREAD

**Issue by a20chrka** [HGustavs/LenaSYS#12158]
Main issue: #11744 

If there are multiple candidate-keys connected to the same element (see image below), only one should be generated in the ER-Table.
![image](https://user-images.githubusercontent.com/102599740/166882951-dabff59d-74eb-4edb-b8ad-c2cd0dc494b6.png)

 Needless to say but in reality (when creating the table by hand), the creator of the table decides which candidate key becomes the primary key. It should be the same for the automatic ER-Table generation. 

Until the customer says otherwise, create a checkbox for candidate key attributes in Options -> properties that represents if the key is chosen as primary key or not. Preferably, the checkbox should appear to the right of the "Variant-dropdown" (marked in red below), only when "key" is chosen:
![image](https://user-images.githubusercontent.com/102599740/166882609-8ef24d04-b056-42a6-a090-26587aa350bb.png)

Alternatively, add another "Variant", in the dropdown list:
![image](https://user-images.githubusercontent.com/102599740/166883331-4ff1a387-73bc-45e7-b6b7-0b8e7977eac0.png)

**Comment by a20gabpa** [comment]
The solution has been merged.
