### ISSUE TITLE
[Research whitetheme.css and blacktheme.css] Implement the research that was found

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12152]
Research if dark mode can be implemented in a better way than two css files that it switches between. Is it possible to have everything in one file without large refactoring?

**Comment by b20fanfa** [comment]
In Lenays, today, there are many different css files that do many different things. With this issue in mind, we will focus on three CSS files: "style.css, blackTheme.css and whiteTheme.css". This is not the correct way to use css files when it comes to dark mode. During the development of Lenasys, dark mode has become more sought after but has not yet been fully implemented. A separate file has been created for dark mode and one for light mode.
Research has been done,  the market says that you should use one css file that should contain the essentials (in styling) on ​​the page. If you want dark mode, you create a new css file that has a purpose for just that. The problem now is that we have created another css file that is only for light mode, we do not strive for this.

What is to be tested is:
- [ ] Move all code from whiteTheme.css to style.css. (NOTE, nothing should be deleted).
- [ ] Make sure nothing collides with each other or duplicates.
- [ ] Delete whiteTheme.css in the files in which it is used.
- [ ] Make sure the style.css file connects correctly with the dark mode toggle / blackTheme.css file.

We are waiting for a response from a customer if this is an okay way to work. But we're getting started.
If that does not work, we will not continue with this. Then we will have it as we have it now.
