### ISSUE TITLE
Deleted items come back when a new one is added

### ISSUE THREAD

**Issue by b20idawa** [HGustavs/LenaSYS#12166]
When you delete items, they come back when you add a new one. The deleted items also come back when you refresh the webpage. see the videos..

https://user-images.githubusercontent.com/81676911/166888112-52792f14-b0a9-475c-9654-0caa17df6ab0.mov

https://user-images.githubusercontent.com/81676911/166888293-45e5ad4a-dd15-4f3d-b665-5e2915342f59.mov

**Comment by a19xinhu** [comment]
I find the reason about this issue.
function deleteItem(item_lid = null)  at  section.js have code about delete function but it need to wait 60s. 
After you click "Yes", you can not leave this website or refresh. Otherwise the delete function will not work.

**Comment by a19xinhu** [comment]
Clicking the delete button will temporarily add display:none to the code. The idea of the solution is to find a way to figure out why adding a New Code will remove the display style of the Code you want to delete.

**Comment by b20sebka** [comment]
Has been fixed
