### ISSUE TITLE
Add colorblind-friendly colors for elements in the diagram.

### ISSUE THREAD

**Issue by a20chrka** [HGustavs/LenaSYS#12177]
This issue includes research on what colors to use for colorblind users. If I recall correctly, there are different types of colorblindness that needs to be considered.

Until the customer says otherwise, simply add the colorblind-friendly colors to the list shown below:
![image](https://user-images.githubusercontent.com/102599740/166898463-2a68cf4e-5f22-4ea0-afb9-e16a55450e88.png)

**Comment by a20samul** [comment]
Added the colour blind-friendly version of already pre-existing colours. Colours were extracted from the IBM colour blind palette. (Note that the text-color should be changed to white on colours black and newPink)

<img width="464" alt="colorBlindSafePalette" src="https://user-images.githubusercontent.com/81613484/167109388-fdca2fd8-036e-4861-bcbd-c6081d208427.png">
