### ISSUE TITLE
Description field design

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#12182]
The description field needs some rework. 
<img src="https://user-images.githubusercontent.com/81772705/166869336-65eff1c3-b1de-45a5-a305-fbd4bf43297f.png" height="500" />

Suggested solution
<img src="https://user-images.githubusercontent.com/81772705/166901687-12f63ca9-40da-4330-abd4-aa5fb9cd34e0.png" height="500" />

- Change Instructions to General information
- Add a grey field on top of the description container that also says Instructions according to standards at LenaSYS.
- Add a border around the description field so that it follows standards for different sections on dugga pages.

**Comment by a20chrka** [comment]
Test passed, looks good.
