### ISSUE TITLE
Behaviour of selection box in different scenarios.

### ISSUE THREAD

**Issue by a20jacmi** [HGustavs/LenaSYS#12180]
When the mouse hover over the options pane and comes back to the container the selection box disappears. It reemerges when the container is clicked.

https://user-images.githubusercontent.com/102599629/166900406-25035f59-49ee-44a9-a583-a6ce86ea3299.mov

When edge creation is chosen the selection box disappears, but this doesn't happen when "placing an element" is chosen.

https://user-images.githubusercontent.com/102599629/166900421-29bd82a6-d642-41f6-8150-df62b24fcd40.mov

**Comment by b20matad** [comment]
Problems solved by:
Options panel don't call "mdown()" on mouse down anymore.
All selected object are deselected if switching to "PLACING_ELEMENT" mousemode.
