### ISSUE TITLE
Double-click on UML-inheritance element does not work.

### ISSUE THREAD

**Issue by a20chrka** [HGustavs/LenaSYS#12203]
With all other elements, if you double-click on them, the option-panel will pop out. This does not work with the UML-inheritance element.

The UML-inheritance element looks like this and can found if if you hold down the mouse-button on the ER-Relation symbol:
![image](https://user-images.githubusercontent.com/102599740/167081031-51372b4c-56bb-44ea-96d0-fb7aefdb1bbc.png)

Note: You must be logged in as a teacher (the Toddler account) to access the feature in the default diagram.

**Comment by a20jacmi** [comment]
Now this element works as the other ones. It just needed the same initial setup as the other placable elements. This was found under generateContextProperties(). We just compared the "ER" element and copied the missing code to the "UMLRelation".
