### ISSUE TITLE
Stop duplicte files from being uploaded when uploading more than one file at the same time.

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#12219]
Sub issue created from #11993.

Still get duplicate files if you upload serveral files at once. The files regarding how the selected files are saved are not well documented. Created this sub issue as the main issue is now fixed for one file at the time.

**Comment by b19karhj** [comment]
Reworked the solution to fit for both one and multiple files, Will push the new solution with the orginal branch, So this issue can be closed as it will be solved in main issue. So files #11993

**Comment by i19matla** [comment]
Closed on assagnees request.
