### ISSUE TITLE
It's not currently possible to press ENTER to log in to contribution

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12233]
When trying to login or create an account you have to press the button with the mouse. It gives an "error-msg" when trying to press ENTER. I'm thinking it should be possible.

![image](https://user-images.githubusercontent.com/102599327/167128726-bf859d1f-c7f2-4e39-9d96-d3b428258e26.png)

**Comment by a20caros** [comment]
Solved the problem of being able to click ENTER in the login menu on the contribution page

To test issue
1. Go to the contribution page
2. Click the login button
2. Enter your username and click ENTER
3. Enter the password and click ENTER
4. Can you log in?
<img width="301" alt="image" src="https://user-images.githubusercontent.com/81676918/167402043-2700155c-f100-4029-b191-b30fa22e4bb3.png">

5. Try logging in with the proci eller andras-marki user, you will need to enter a new password, after the password has been entered click ENTER
<img width="374" alt="image" src="https://user-images.githubusercontent.com/81676918/167402307-88bdecd8-667a-49cc-87e0-090b88986995.png">

If it is possible to click ENTER in all these places to move on, the issue works
