### ISSUE TITLE
Create an icon for the turning on/off error button

### ISSUE THREAD

**Issue by c20emili** [HGustavs/LenaSYS#12241]
Sub issue for #12236 
Create an icon for the turning on/off error button

**Comment by a20samul** [comment]
Several mockups were tried and made. The one approved by issue ansvarig and deemed to represent the functionality the error checking functionality the best was the magnifying glass with the X inside:

The icons that were tried and made:
<img width="114" alt="errorCheckMockup2" src="https://user-images.githubusercontent.com/81613484/167372690-d5347bec-6ef3-4920-96e9-e1b6d0205fe0.png">
