### ISSUE TITLE
Create testdata for CodeViewer

### ISSUE THREAD

**Issue by a13alfbe** [HGustavs/LenaSYS#1224]
At the moment there is a lot of missing/incomplete data in the database. 
Create new and complete testdata to use for the codeexamples.

**Comment by HGustavs** [comment]
The way I see it is that there are two candidate courses for this.
http://wwwlab.iit.his.se/gush/Shaderprogrammering/
and 
http://wwwlab.iit.his.se/gush/XML_API/

These two courses use the system slightly differently. Shaderprogrammering is by far the most advanced, with different views and different content in the various views, and syntax highlighting in all views.

XML API uses the more basic features but uses PHP and XML which gives the syntax highlighter more to work with.

I would choose a diverse subset from each course and see how far the ststem is able to represent each type of content.

**Comment by HGustavs** [comment]
There is a bit more information in issue #1073.

Perhaps it is a good idea to retire either this issue or that issue.

**Comment by a13alfbe** [comment]
@f12danjo and I are working with this issue and #741. We have used examples from XML API and http://wwwlab.iki.his.se/~gush/Webbprogrammering/. 
We will use examples from "Shaderprogrammering" aswell.

**Comment by c13caral** [comment]
This is now solved :+1:
