### ISSUE TITLE
Possibility to add name/description to dugga variants

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#12252]
Add a new field under "Dugga edit" where all properties for the dugga are set. The teacher can then add a short text(restrict the length to maybe 100-200 characters) that describes the dugga variant(should be available for all dugga types, not just diagram). 
The text input should be restricted in length and it should be shown in a new column in the variant list section:
![image](https://user-images.githubusercontent.com/81772705/167212614-f3893cd4-1d35-4ff5-8ea2-772fc5110163.png)

Purpose of feature: 
- If the teacher started to create a diagram version and wants to close down but not discard the changes they can save the variant with a comment and come back later to finish it.
- The teacher can write a comment to themselves to remember what the variant includes. 

This field will also be good during the project as we can create different tests for the diagram and name them with different test names to remember what the test is for.
<hr>
Asked Markus if this feature would be liked by teachers and he told me to do ahead and create an issue for it.

**Comment by b19karhj** [comment]
William is added to the team. This is not a one man job.
