### ISSUE TITLE
overlapping codeviewer nav

### ISSUE THREAD

**Issue by a20sarle** [HGustavs/LenaSYS#12259]
The code viewer nav is overlapping in a strange way when resized.

![image](https://user-images.githubusercontent.com/81631818/167361463-34865ca0-97ce-49ec-965e-6849bcb92e69.png)

https://user-images.githubusercontent.com/81631818/167361557-b6bf7f25-c899-484b-bbed-1ca3ba5d4946.mp4

**Comment by b20idawa** [comment]
The issue  #12052 resolves this problem

**Comment by a20joabo** [comment]
This issue can no longer be replicated and should thereby be considered solved.
