### ISSUE TITLE
Small margin differences in dark mode vs. light mode

### ISSUE THREAD

**Issue by a20sarle** [HGustavs/LenaSYS#12284]
Small margin differences in dark mode around the message of the day div.

On other pages there are similar issues where it at times affect positioning of certain elements.

![Screenshot_20220509-120837_Messenger](https://user-images.githubusercontent.com/81631818/167389132-b072bd3e-3731-443b-9ca4-f844f44a0f7f.jpg)
![Screenshot_20220509-120850_Messenger](https://user-images.githubusercontent.com/81631818/167389136-45222cde-197c-4f03-9f4c-82750d745738.jpg)

**Comment by b20idawa** [comment]
I think this issue already has been resolved: #12132
