### ISSUE TITLE
Codeviewer Markdown create documentation

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1228]
Create a document describing the markdown implementation, also review the comments written in the code (codeviewer.js).

**Comment by HGustavs** [comment]
It would be super-nice if it would be possible to show a markdown legend by clicking somewhere in the markdown editor... like a dropdown or something like that which lists the available markdown strings and their effect.

It should be possible to show this without losing what you have written so far.

**Comment by b12simsa** [comment]
Right now you can´t really write anything directly in the editor, you rather create a file, upload it to the folder, and connect the filename with the example in the database, the content of the file is then loaded into the description box. Maybe this is another thing to discuss during a customer meeting?

**Comment by f12danjo** [comment]
Closed since documentation for markdown has been implemented. A markdown legend is not relevant for the code viewer as it functions right now. If we were to implement an editor this would become relevant.
