### ISSUE TITLE
Can't use the forward or backward button in mobile view

### ISSUE THREAD

**Issue by a20sarle** [HGustavs/LenaSYS#12288]
Seems like the svg / png is moved and the phone tries to read the press functionality as if the img should be copied. Implement the press functionality of the backward and forward buttons in another way to have the same functionality or create some other solution. Maybe even remove the functionality on phone?
![20220509_123206](https://user-images.githubusercontent.com/81631818/167393113-e5c7e2f9-ff68-4954-85f9-faddc975611d.jpg)

**Comment by b20idawa** [comment]
Is this even possible in mobile view?

**Comment by a19xinhu** [comment]
I think it is because there is no onmouseup, onmousedown function at mobil. So i use ontouchstart and ontouchend.
