### ISSUE TITLE
Hamburger menu double click

### ISSUE THREAD

**Issue by a20sarle** [HGustavs/LenaSYS#12296]
The hamburger menu needs to be clicked twice before the menu items show (at least in mobile view). Items should show after one click.
![Screenshot_20220509-133738_Samsung Internet](https://user-images.githubusercontent.com/81631818/167402535-e95c3f08-15a7-4fa1-bc7b-9a3e9be4860b.jpg)

**Comment by b20idawa** [comment]
I thin this issue is already resolved with this issue: #12173
