### ISSUE TITLE
Fix overlaping issues in circle diagram

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12303]
In contribution the most up to date verison of "hourly activities" the different contributions overlap eachother. This hides some information.
#11008

**Comment by c20adael** [comment]
> I have fixed the visual part. There is however a problem. Its impossible to access the points that appear behind the other polygons. I recommend creating a new issue that tries to fix this by scaling the polygons separately or making the rectangles smaller/merge. Also the filled in polygons needs to be discussed as they should not block the points in the different polygons.
> 
> ![image](https://user-images.githubusercontent.com/80856978/167400721-05b8805e-0425-4cf1-ab06-cb5bce3de5aa.png)
