### ISSUE TITLE
Change following files to conform to codestandard

### ISSUE THREAD

**Issue by a13oscwe** [HGustavs/LenaSYS#1231]
Rebundling the issues into this one issue.
We need to reformat code to conform to the code standards set in the codestandard.md file.

Following files need looking at:

showdoc.php
showDuggaservice.php
showDugga.php
sectionedservice.php
sectioned.php
sectioned.js
resultlistedservice.php
resultlisted.php
resultlisted.js
resultservice.php
resulted.php
resulted.js
filerecieve.php
fileedservice.php
fileed.js
duggaedservice.php
duggaed.php
duggaed.js
courseedservice.php
courseed.php
courseed.js
accessedservice.php
accessed.php
accessed.js
courseed.php

**Comment by c13chrjo** [comment]
Issues already exists and there should not be one big issue of this according to @HGustavs

**Comment by a13oscwe** [comment]
Reopening seperate issues.

**Comment by HGustavs** [comment]
It is a good idea to do this litte by little, which reduces the risk for merge problems.... starting out with one or two dialogs each week e.g. doing accessed.js / accessed.php and accessed.html this week and a few others next week.

The more refactoring done at the same time, the more merge problems. ...Little by little... is a safer plan.
