### ISSUE TITLE
Code Viewer: Document the code

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1232]
We have to comment the code.
The comments should answer question like:
What does the function do?

If there are some parameters you could also describe them to.
And if you like you can be more detailed and describe important variables and if-set or while-loops.

Just think that someone that haven't write the code should understand what the function do by only read the comments for example.

**Comment by a13jorla** [comment]
Made this branch CodeView-#1232-comented-code. Place your comments into this branch so we do not overwrite comments from eachother.

**Comment by f12danjo** [comment]
Documentation done.
