### ISSUE TITLE
Automatic update of other tabs when login out in another tab.

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#12329]
When you are logged into LenaSYS in multiple tabs and you log out in one tab, you still can see logged in pages in other tabs. 

You can even start doing changes and see values in dropdowns. The page won't update until you click on a submit button.  
The image below is after I logged out in another tab.
<img src="https://user-images.githubusercontent.com/81772705/167571826-4e3c91cc-c69f-44ea-b1c1-beff3467b48f.png" height="300"/>

When it comes to dugga variants maybe this isn't such a big issue. But there are other pages in LenaSYS that might have more important details and these shouldn't be able to be viewed by others if a computer is left with tabs open. 

A suggestion would be to check if there is some kind of event listener that monitors if the logout has been clicked n another tab.

**Comment by a20willa** [comment]
For testing:
1. Open TWO instances of lenasys
2. Login in as a teacher in both of them
3. Try logging out in one of the instances. The other instance should also logout!
