### ISSUE TITLE
The user's focus is directed to new content added to the page

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12335]
Newly added objects/elements should be more clearly "highlighted" in coruseed.

**Comment by a20caros** [comment]
Things on the page that should have focus:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/81676918/167579319-c8617df8-14a2-4484-9c2f-3665be49878c.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/81676918/167579494-950c29ae-2703-4860-a830-e2306c5a698a.png">
______________________________________________________________
<img width="523" alt="image" src="https://user-images.githubusercontent.com/81676918/167580596-bd31f5aa-17aa-437a-a8f8-fd2b92f95ecd.png">
When you select an element to hide, there are no indications that it has been changed
_______________________________________________________________________
<img width="417" alt="image" src="https://user-images.githubusercontent.com/81676918/167580954-67bb68a1-3e3c-4904-966b-e52fdb063784.png">
__________________________________________________________________
<img width="247" alt="image" src="https://user-images.githubusercontent.com/81676918/167581257-4eadfea8-db9f-4478-9790-25fadde6f17f.png">
When you add someone from this menu, nothing is indicated
______________________________________________________________
<img width="169" alt="image" src="https://user-images.githubusercontent.com/81676918/167581581-d4c153f4-7341-4c8e-b958-de2317394767.png">
______________________________________________________________
<img width="202" alt="image" src="https://user-images.githubusercontent.com/81676918/167582372-ea105413-81f1-4d31-9e17-938c642f5890.png">

**Comment by a20caros** [comment]
The solution of this issue:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/81676918/168089682-753c65d9-3fbd-43a7-b1a2-69506e85c333.png">
