### ISSUE TITLE
Changes to the rows of the tables. 

### ISSUE THREAD

**Issue by a20muhal** [HGustavs/LenaSYS#12334]
![image](https://user-images.githubusercontent.com/102594578/167575753-a41e314f-cd1a-4c0b-87f9-d39af897177e.png)

We want changes to the colors of the rows in the table to a more distinct color (not to much). Maybe a change to the color when you hover aswell.

**Comment by HGustavs** [comment]
Agree, this is not clear enough, contrast-wise.
