### ISSUE TITLE
Find out why these popups appear and find a solution

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12339]
After last merge, these popups started appearing when opening duggas in webserver as a super user. Find out their purpouse and fix potential problems.

![image](https://user-images.githubusercontent.com/102599327/167584147-755b665b-a5f2-471d-940c-eed2f745a442.png)

**Comment by HGustavs** [comment]
This should be given a priority. Error messages should not appear at any time when used normally.

**Comment by a19simru** [comment]
Currently trying to find a good way of reading data in showDugga.php. Research continues.

**Comment by a20vicad** [comment]
This is still very much an issue that the first group is still working on.

**Comment by a19simru** [comment]
Disappointing lack of progress today. Can't get php debugging to work  properly to read variables in program time.

**Comment by b20jonlu** [comment]
This issue might have been fixed by this pull request https://github.com/HGustavs/LenaSYS/pull/12450

**Comment by b20hanwa** [comment]
This issue was solved by group 2.
