### ISSUE TITLE
Move functions from contribution login to a separate file

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12337]
Make a new file that contains the loginscript for contribution.php and contribution_loginbox.php. Also move the contribution specific AJAX from dugga.js

**Comment by HGustavs** [comment]
All functionality should be generic.

Same architecture for all files, we call ajax using the same interface in all locations.

this way for example we can globally move from ajax to javascript fetch by changing a single file. No ajax calls should be made directly without passing this generic interface.

Unclear if this is the issue that is described or not. if not, please clarify.

**Comment by a20sacka** [comment]
> All functionality should be generic.
> 
> Same architecture for all files, we call ajax using the same interface in all locations.
> 
> this way for example we can globally move from ajax to javascript fetch by changing a single file. No ajax calls should be made directly without passing this generic interface.
> 
> Unclear if this is the issue that is described or not. if not, please clarify.

You are right, a lot of ajaxservices got condensed into one function now for contribution_loginbox_service.php
