### ISSUE TITLE
Linjedugga "cursor" can't be used properly

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12341]
In Linjeduggor there is a "box" for doing the dugga. When hovering over this box a new cursor appears. This cursor however is wierdly placed and that means you cannot "use" the left part of the "box".
![image](https://user-images.githubusercontent.com/102599327/167585677-7f9592d6-698a-47b6-bf8b-8f1c0ba82564.png)

**Comment by HGustavs** [comment]
This is a bug. Probably has to do with a deprecated manner of reading mouse coordinates.
