### ISSUE TITLE
"Your changes may not be saved" opens twice

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12346]
When trying to press the back button in a dugga, the popup appears twice.
![image](https://user-images.githubusercontent.com/102599327/167593619-7c84b61f-d2f4-407c-8ac7-505cc79b0f2a.png)

**Comment by HGustavs** [comment]
I have not tested this myslelf but we want this feature as un-obtrusive as possible.

**Comment by b20eripe** [comment]
Back button in browser does not give this error but clicking the site back button creates two alerts

**Comment by b20eripe** [comment]
![bild](https://user-images.githubusercontent.com/102593527/167625412-16f6100b-3732-41b5-b1fa-a8bb517095d7.png)

navigateToUrl was called twice on click. Removed one of them
