### ISSUE TITLE
Login: Forgot password doesn't work

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1236]
The forgot password function doesn't work.

**Comment by b14davbo** [comment]
Students will never be able to get an email since the smtp port is blocked on the server, we have no good solution to this right now. One way would be to store all forgot password requests in a database table and then the teacher manually has to send the student a new password?

Any other ideas?

**Comment by a15tobli** [comment]
New screens added for forgotten password in merge #2528.
