### ISSUE TITLE
UML element styling

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#12373]
When using enter to add a new line in the UML entity the line spacing is set to high. Lower the spacing between the lines.
At the moment the UML entity becomes too big when writing multiple attributes or functions.
![image](https://user-images.githubusercontent.com/81772705/167642662-3f5cc5af-328e-4986-8c67-4488b4f62cc9.png)
Maybe it can look a bit more like this
![image](https://user-images.githubusercontent.com/81772705/167643605-d1faa706-8b1a-441d-8526-9d76fc00409d.png)

Also, check if the standard is that the class name is centred and attributes and operations/functions use left alignment.
When googling UML class diagrams the majority of the UML entity looks like this:
![image](https://user-images.githubusercontent.com/81772705/167644212-e6fda41f-25e8-400f-888f-e78b72890547.png)

Another thing that needs to be fixed is that at the moment we use "-" in front of both attribute and function. There are situations when you don't want this. If you look in the image above there are "+" in front of the functions. Maybe the "-" shouldn't be added automatically at all in front of the attribute and function and instead, the user will have to specify that themself when needed. This also solves the issue if the user wants to point out the primary key using "#" in front of the attribute.

**Comment by a20edwth** [comment]
Made changes to the appearance of UML elements.

Instructions for testing:
1) Click "Demo-Course"
2) Click "Diagram Dugga"
3) Add an UML entity and add attributes and functions to it
4) Compare how it looks with the description in the issue
