### ISSUE TITLE
Focus is directed to new content from fabbtn on the first page

### ISSUE THREAD

**Issue by a20caros** [HGustavs/LenaSYS#12371]
When a new course is created, the added element must be marked with a color
<img width="463" alt="image" src="https://user-images.githubusercontent.com/81676918/167638075-76fca126-a86d-49c5-ada1-c7b0e0362c6f.png">

**Comment by a20novra** [comment]
![10](https://user-images.githubusercontent.com/81618150/168090222-581d052e-5d68-4317-a801-e566df215cda.jpg)
TEST!
