### ISSUE TITLE
Focus is directed to new content from fabbtn

### ISSUE THREAD

**Issue by a20caros** [HGustavs/LenaSYS#12370]
When creating a new item, the added element should be highlighted with a color
<img width="315" alt="image" src="https://user-images.githubusercontent.com/81676918/167636731-4714154b-c509-4e76-8f30-c0341bbbbb94.png">
<img width="183" alt="image" src="https://user-images.githubusercontent.com/81676918/167636940-af592184-d169-4c1c-a7ba-001db006ae78.png">

**Comment by c20adael** [comment]
https://github.com/HGustavs/LenaSYS.git
Here i have solved the issue. You can now create new tests etc.
