### ISSUE TITLE
Everything in UMV should be changed to english

### ISSUE THREAD

**Issue by c13emmjo** [HGustavs/LenaSYS#1237]
Now the buttons and info are in swedish this should be changed into english

**Comment by a13erilj** [comment]
This does NOT include changing the language of data in the database

**Comment by HGustavs** [comment]
Since we strive to use realistic data it is unavoidable that some of the data is in Swedish, but we need to make sure that everything else is in English.

**Comment by a13ottne** [comment]
FFS... DONE
