### ISSUE TITLE
Export and save button has the same functionality. 

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#12374]
In the export section in the options tool panel, both the Save and Export button downloads the current diagram JSON file. 
Remove one of the buttons unless in the code you can see a difference between the two.
![image](https://user-images.githubusercontent.com/81772705/167644734-0697563d-91d5-4359-91d9-626894806138.png)

**Comment by b20matad** [comment]
There is a difference in functionality, we changed the names of the buttons to clarify this in the latest merge. #12145

**Comment by a20chrka** [comment]
> There is a difference in functionality, we changed the names of the buttons to clarify this in the latest merge. #12145

With that said, I'm closing this issue.
