### ISSUE TITLE
"Try again" text remains even after "returning" in contribution login

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12380]
Trying to login as a nonexisting user, then beginning to create a password for an existing one and returning to start. Here the "try again" text will still be up.
https://user-images.githubusercontent.com/102599327/167838001-29251e4e-1e3a-4d8c-9add-57d33757ea32.mp4

**Comment by a20sacka** [comment]
https://user-images.githubusercontent.com/102584289/168165890-60b840e9-725d-42e8-8b0f-716ecc286d08.mp4

issue has been fixed
