### ISSUE TITLE
Make page load in new tab

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12403]
![image](https://user-images.githubusercontent.com/102599780/167845302-1092980b-7d71-4eb8-bf5d-e357a7e79df9.png)
Make this button redirect to a new tab instead of loading on the current page

**Comment by a20sarle** [comment]
Suspecting that this calss should be removed from element.
![image](https://user-images.githubusercontent.com/81631818/168242575-20cf8f49-865a-4cf6-a6c0-1db6df556c91.png)

**Comment by a20sarle** [comment]
Searched in file sectioned.php and sectioned.js when trying to find the line where `target="_blank "` should be added. Found the right line of code in navheader.php (does not show as a source in inspect).
