### ISSUE TITLE
Markdown support?

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1243]
If we look at the description content used in

http://wwwlab.iit.his.se/gush/XML_API/
http://wwwlab.iit.his.se/gush/Shaderprogrammering/
http://wwwlab.iki.his.se/~gush/DatabasKonstruktion/
http://wwwlab.iki.his.se/~gush/Webbprogrammering/

Are there any features missing from the markdown code to support the description content from those courses?

This is somewhat related to issue #1224. Do we have sufficient markdown commands for representing a real course?

**Comment by b12simsa** [comment]
I think we have enough markdown for the provided descriptions, but it would be nice if we could demonstrate what we have. Also some advice/thought on the implementation would be appreciated, since I am not sure it handles more complex input especially well.
