### ISSUE TITLE
Button is too small should not be displayed in mobile view

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12441]
![image](https://user-images.githubusercontent.com/102599780/168017839-d482a0ea-1541-4294-92a3-be8fd4e25160.png)
The download button does not work in mobile view and is too small

**Comment by a20andlj** [comment]
I have researched this issue. I do not see the point with this button really. Is it needed? Is is useful for the teachers?
Can it just be removed?

**Comment by b20sebka** [comment]
Customer wants this button to work where you can download every course material. Button should be hidden in mobile view.
