### ISSUE TITLE
Cannot login, when on the contribution page

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12447]
Trying to login as a super user from this page, it does not work and "returns" to the same (non-logged in )view
![image](https://user-images.githubusercontent.com/102599327/168024581-274ce7c1-4130-411c-8ef8-56c047f18399.png)

**Comment by a20johba** [comment]
The problem seemed to be that the login was successful, but the navheader was not setup to show the user name and logout button properly when logged in as a github user (not lenasys). Made a change to the navheader to verify if the user if a git user if the "normal" verification fails. This isn't perfect as the user will still be logged in to the git account if they then go to another page such as courseed, but at least the course options are missing. That could be a separate issue: To logout the git user when leaving the contribution page.
