### ISSUE TITLE
Add the same functionality as labels on lines have for cardinality on lines.

### ISSUE THREAD

**Issue by a20chrka** [HGustavs/LenaSYS#12470]
When placed like this, it looks fine:
![image](https://user-images.githubusercontent.com/102599740/168068683-9e3ffae8-1ade-4203-bb40-8543d28c1e9a.png)

But when you move either the entity or the relation at certain angles, the "N" blends in with the line:
![image](https://user-images.githubusercontent.com/102599740/168069977-9b8709db-ecdf-44ee-bb32-7b020db05c55.png)

The "N" should have the same functionality as the label, meaning it should have a white background.

**Comment by a20edwth** [comment]
Made a white background for the cardinality (1, N) on lines. 

Instructions for testing:
1) Click "Demo-Course"
2) Click "Diagram Dugga"
3) Look at the cardinality (1, N) and see if there is a white background that hides the line its on
