### ISSUE TITLE
Hide "instructions" and "general information" areas when no text file is found.

### ISSUE THREAD

**Issue by a20chrka** [HGustavs/LenaSYS#12476]
![image](https://user-images.githubusercontent.com/102599740/168071628-6f10bc82-bf3d-475c-acd2-d5cee8bd7820.png)

If no file is present (like the image above), then the "instructions" and "general information" areas should not be visible:
![image](https://user-images.githubusercontent.com/102599740/168072458-3b87e32d-fc0f-4919-81aa-cc3569dd275f.png)

Instead, the diagram's iframe should use the extra space, making it bigger.
If only one of them has a text file, then only that one should be visible.

**Comment by a20samul** [comment]
Partial solution has been implemented in #12456
Waiting for it to merge in.

**Comment by a20samul** [comment]
Just found out that the preview does not work as intended, refer to #12141 
So no code implementation is visible in there. To see changes one must:
1. Enable the chosen diagram  
2. Log out as teacher
3. Refresh and go back to diagram dugga as a student.
