### ISSUE TITLE
When updating element/section with "ENTER" to save, the element does not get highlighted

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12514]
![image](https://user-images.githubusercontent.com/102599327/168263798-84bee2cb-37f6-4ecc-a3f2-e51ec153d577.png)

**Comment by c20adael** [comment]
I have found why this is. It is because the updateItem() function that is being run to actually update is not followed by the newly added highlighting method used when clicking the save button. Working on a fix for this.

**Comment by c20adael** [comment]
Problem after merge, Found where this was and have fixed it. Code was removed
