### ISSUE TITLE
Popup "+" menu "hides" too easily.

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12542]
When trying to add a new element to a course the list of elements that popup seems "too narrow" and gets hidden if your mouse leaves the list even a little bit. Either make the invisible area wider, or give it a delay before its hidden.

It now also is not possible to "reach" the popup before it closes.
![image](https://user-images.githubusercontent.com/102599327/168549141-4fc62b7e-a68c-4a70-bf0b-7835307cb072.png)

**Comment by b20hanwa** [comment]
This issue is solved by group 2.
