### ISSUE TITLE
Add backend functionality for account requests in contribution

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12554]
Currently you have to manually change account status in the data base (101 = pending, 0 = accepted, 102 = denied). The buttons bellow should change the status. (Only a superuser should be able to accept/deny/delete users)
![image](https://user-images.githubusercontent.com/102599327/168563470-eea02711-170b-4038-8018-c6c30c975b80.png)

Related: #12518

**Comment by b20eripe** [comment]
Made some progress but not in time for merge. I have saved the code written so far and will resume work with the new branch after this weeks merge

**Comment by b20eripe** [comment]
All functionality finished
