### ISSUE TITLE
Adjust icon sizes, hover effect and alignment.

### ISSUE THREAD

**Issue by b20thelo** [HGustavs/LenaSYS#12583]
The size of the icon does not match the entire surface they are in. Since some icons have become more detailed than when they were first created, it is better to use the entire surface for better clarity.

Things to fix:

- Adjust so that icons use the whole area with fitting padding.
![image](https://user-images.githubusercontent.com/81772705/168755824-7bab9718-a97d-43c9-9905-034fddfa0dd4.png)
- Adjust zoom tools as they are not currently centered correctly
- Adjust the hover effect so that the icon doesn't go outside it. 
<img src="https://user-images.githubusercontent.com/81772705/168756695-ce199f3b-7834-4d63-a13b-26a0db787de6.png" height="200"/><img src="https://user-images.githubusercontent.com/81772705/168758751-7f386484-c8df-407b-a319-ede5f1dfd24d.png" height="200"/>

**Comment by b19karhj** [comment]
create new issue to see if all new icons look good.
