### ISSUE TITLE
Deleted elements return after moving another element

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12599]
In a course homepage. After deleting an element, it returns if you move another element. This is because of the "undo deletion" feature. It should however not get "activated" when doing such a small change.
![image](https://user-images.githubusercontent.com/102599327/168783592-c77b6064-c6fd-4bb0-bd56-fc2c32b2a804.png)

**Comment by a19simru** [comment]
Has found a unimplemented function that seams to be meant to resolve this problem. Currently trying to look for a apropriate place to implement it to se if it works.
