### ISSUE TITLE
Style issues with UML-Class

### ISSUE THREAD

**Issue by b20matad** [HGustavs/LenaSYS#12593]
There are a few small style issues on the UMLEntity:

1. The text in attributes and functions are moving into the border while zooming in, and moving to the right while zooming out.
<img width="420" alt="image" src="https://user-images.githubusercontent.com/102598238/168766814-da6b3e91-262e-4477-910c-16b618d79756.png">

2. The selection box around the UML class isn't evenly margined.
<img width="312" alt="image" src="https://user-images.githubusercontent.com/102598238/168767130-08afaf03-ba1f-4922-90ce-301736a7cd82.png">

3. The standard notation for attributes and functions are to begin with a lowercase letter, therefore default text should begin with lowercase.

**Comment by a20jacmi** [comment]
These things have now been implemented in "diagram.js" -> "drawElement()".
