### ISSUE TITLE
Trying to delete "undeletable" duggas in duggaed should give an 'error'

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12615]
This is the popup that appears if you try to remove a file that for some reason can not be deleted. A similar popup should apear when trying to do the same in duggaed.
![image](https://user-images.githubusercontent.com/102599327/168816324-671a051f-7633-44a3-8809-05fc32b6f152.png)

**Comment by a17nikjo** [comment]
Been searching for the problem but can not find it, please provide clearer description of where the problem is located.

**Comment by a20vicad** [comment]
In fileed, a popup (above pic) appears if you are not allowed to delete the file. A similar popup should appear if you try to do the same in duggaed.

**Comment by a17nikjo** [comment]
Solution seems too be already found in issue #12638.

**Comment by a17nikjo** [comment]
If the SQL can not delete the item an error promt is now shown.
