### ISSUE TITLE
New mobile view

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12621]
Reference to #12488 
Check above issue for information

**Comment by a19xinhu** [comment]
I think add media query for Iphone 5, Iphone 6 and Ipad is enough.  By limiting the height and width of the screen.

**Comment by a19xinhu** [comment]
Finnally decide to change all min-device-width value to 320px , max-device-width value to 480px.

**Comment by a19xinhu** [comment]
Added 4 mobile specific css conditions: iPhone4/5/6 and iPad Mini.
