### ISSUE TITLE
Unnecessary space

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12640]
![image](https://user-images.githubusercontent.com/102599780/169020464-8942e41f-a7f8-4a4c-8a36-ce2a92c8f228.png)
Remove the space between the course bar and the back button

**Comment by a20joabo** [comment]
This issue only occurs when logged in as a teacher.

**Comment by a20joabo** [comment]
![image](https://user-images.githubusercontent.com/102584401/169046532-7f3823fc-006a-4444-ab79-17113737fa17.png)
