### ISSUE TITLE
Yellow color is too bright in dark mode

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12680]
![image](https://user-images.githubusercontent.com/102599780/169062904-e976e156-7ed4-4c71-acd8-56c3dbbfdb4e.png)
Customer thinks the yellow in dark mode is too bright.
Research is needed to find a good replacement

**Comment by a20sarle** [comment]
According to Material Design the primary color should be 500 and elements which should be accented (secondary color) should be of value 400.

The closest colours to match the rules are the two following ones:
![image](https://user-images.githubusercontent.com/81631818/169301616-d6651cff-3fcc-4029-a7be-9edc1feb2090.png)

**Comment by a20sarle** [comment]
@HGustavs Should the primary color be changed to match the rules?
