### ISSUE TITLE
Text is dark-on-dark when it should be light-on-dark

### ISSUE THREAD

**Issue by b20sebka** [HGustavs/LenaSYS#12683]
![image](https://user-images.githubusercontent.com/102599780/169063406-40ec81d0-3597-4427-982a-7431f039e53b.png)
As customer explains it the text is "dark color on dark background" where it should be "light color on dark background" in dark mode.
Research colors that could be a replacement

**Comment by b20idawa** [comment]
I have a suggestion for a better color that is more visible than before. The color is now light on dark background. The color that is used in the picture is: #d8b5e8 
<img width="1151" alt="Skärmavbild 2022-05-19 kl  14 28 40" src="https://user-images.githubusercontent.com/81676911/169293316-c197e3b5-1846-483a-80b3-0660a784f066.png">
