### ISSUE TITLE
There is no "back" button in code examples

### ISSUE THREAD

**Issue by a20vicad** [HGustavs/LenaSYS#12729]
There should be a back button on code example page.
![image](https://user-images.githubusercontent.com/102599327/169287373-14b43670-eb90-40fc-942f-b85aa342c573.png)

**Comment by a20caros** [comment]
This is the solution for the issue
<img width="217" alt="image" src="https://user-images.githubusercontent.com/81676918/169295206-fd44d671-8ec2-45fe-a600-69a812268a4e.png">
