### ISSUE TITLE
Dugga exempel

### ISSUE THREAD

**Issue by c13andka** [HGustavs/LenaSYS#1277]
When you want to add new param for duggas, there should be an example above  the first inputbox so that you don't have to go into to the file to see an example, 

This can be made by doing a general function inside every dugga that will give you an example for that dugga. The name should be the same in everydugga (name of function) if no example is available, there should stand a text: "No example available"

**Comment by c13andka** [comment]
Maybe there is a better way to do this. we should maybe not prioritate this

**Comment by a13denli** [comment]
Completed
