### ISSUE TITLE
Implement quiz dugga

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1283]
I believe a dugga should be implemented consisting only of questions and choices between several answers. Seeing as this is probably the most common form of online test. The functionality for this already exists in "kryss.js" but it is not yet implemented as a dugga. Should this be implemented to be it's own type of dugga, e.g dugga7(we could really use more descriptive names on those though)? I think it would be a good idea.

**Comment by a13chrju** [comment]
maerged in https://github.com/HGustavs/LenaSYS/pull/1475
