### ISSUE TITLE
Change the color for the important word #1285

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1284]
Change the color for the important words when the words is not in a row that is important row.
I mean that is now it is only a gray border that shows that this is a important word. We want it to pop more, but not as much as when the word is in a important row

![skarmavbild 2015-05-05 kl 13 42 29](https://cloud.githubusercontent.com/assets/11715450/7471907/c98c2b32-f32c-11e4-84c0-a62a6d39f639.png)

Important words in a non-important row

**Comment by a13jansa** [comment]
Wrong issue nr
