### ISSUE TITLE
Code Viewer: The left part of the code gets hidden.

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1287]
This is from example 14
![skarmavbild 2015-05-05 kl 14 55 25](https://cloud.githubusercontent.com/assets/11715450/7472858/e4da8d02-f336-11e4-95a8-ac2783e149ca.png)

**Comment by c12jenek** [comment]
This might have to do with the tokeniser error message which pops up when entering the page, which is related to the untouchable tokenizer funciton

**Comment by c12jenek** [comment]
The error message I get is "Tokenizer Error: Bad Number: 50p at row 6" along with ~10 more like it, seems like it's supposed to be 50px. So the css example ruins the fun for everyone

**Comment by a13jorla** [comment]
Have not seen this for a while now so we are closing this issue.
