### ISSUE TITLE
Code Viewer:  There is a gap at the end of the code examples 

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1288]
This is from the code example 14. But there are several code example with this issue.

![skarmavbild 2015-05-05 kl 14 59 02](https://cloud.githubusercontent.com/assets/11715450/7472924/7b723f80-f337-11e4-83e7-bdf5e4565a2c.png)

**Comment by a13jorla** [comment]
This seems now to be a testing issue, trying to see if it appeares again in some browsers.
