### ISSUE TITLE
Code Viewer: Too long titles cause issue with heading

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1289]
I think it is because of the name of the example code is too big. Maybe overflow can fix it?

![skarmavbild 2015-05-05 kl 15 04 37](https://cloud.githubusercontent.com/assets/11715450/7473027/26a485a2-f338-11e4-8f3e-82a21fe5d912.png)

**Comment by f12danjo** [comment]
Fixed by [#1506](https://github.com/HGustavs/LenaSYS/pull/1506).
