### ISSUE TITLE
Diagram: Last two tooltips goes beyond bottom of the screen.

### ISSUE THREAD

**Issue by b19karhj** [HGustavs/LenaSYS#12890]
The tooltips for check and include needs their position corrected as they fall off the screen.

![image](https://user-images.githubusercontent.com/81624541/170230869-bc61d3b1-b34f-47d6-ad81-71ece11b3414.png)
![image](https://user-images.githubusercontent.com/81624541/170230912-985ad1db-83b4-4166-9174-67d9b16c273a.png)

**Comment by a21aldsa** [comment]
They were all pushed down to accommodate for the top tool tip spilling out over the top. So I ended up pushing them all up (making it so the bottom two don't spill over downward) and then giving the top tool tip an ID and giving that ID its own top value in css. 

This seemed more elegant than adding IDs to just the bottom two tool tips or something along those lines.
