### ISSUE TITLE
Tokenizer Errors on JavaScript example 2

### ISSUE THREAD

**Issue by a13erisc** [HGustavs/LenaSYS#1291]
"Tokenizer Error: Bad Number" is thrown several times on this example.

**Comment by HGustavs** [comment]
Without quotes from the offending file it is difficult to ascertain what the cause is. Please quote some code from that file in the issue.

**Comment by a13alfbe** [comment]
The tokenizer seems to have problems with values like "100px" for example. The only thing left is from "100px" is the "p". I think it might have something to do with it being inside the curly brackets since it works fine with inline css like: \<div style="width:300px">\</div>

**Comment by HGustavs** [comment]
I think that the best solution is to make sure that the tokenizer views 100px and 100% as a number.

There is a part of the tokenizer that I think is allows var x = 0xFF;  adapting that code to also accept 100px as a number can probably solve it... It may be a jerry-rigged way of doing this, but that is my best solution.

**Comment by a13erisc** [comment]
I'm a bit unsure on how to solve this, because of the importance and complexity of tokenize(). Would it be preferable to work around this function, rather than inside of it? I've found a cheap solution which solves the majority of the problems, but at the same time ruins the purpose of this if-statement. 

Changed the following on row 1051
```javascript
if (currentCharacter>='a'&&currentCharacter<='z'){
```
with
```javascript
if (currentStr>='a'&&currentStr<='z'){
```

**Comment by HGustavs** [comment]
Nope, that makes it much worse.
Im thinking along the lines of adding something like this:


```
    		        c=instring.charAt(i);
            }while(c>='0'&&c<='9');
        }
        if((c=='p'||c=='P')&&(instring.charAt(i)=='x'||instring.charAt(i)=='X')){
        		str+=c;
        		i++;
        		c=instring.charAt(i);
        		str+=c;
        		i++
        		c=instring.charAt(i);
        		
        }else if (c>='a'&&c<='z'){
            str += c;
            i += 1;
            error('Bad Number: ',str,row);
        }
        n=+str;
        if(isFinite(n)){
						maketoken('number',n,from,i,row);		            		
        }else{
            error('Bad Number: ',str,row);
        }
```

with that code we are nearly where we need to be.... what is lacking is stopping the code from writing "bad number" and calling maketoken maketoken('number',str,from,i,row);	...

**Comment by HGustavs** [comment]
The rows I added is the if that checks for px at the end of a number.... which makes it possible for us to test for "px" ... and discarding "p" and "py" and "pb".

Just noticed a bug in the code above.... it should read "instring.charAt(i+1)" instead of  "instring.charAt(i)" ...

also.. I did that code on the fly, without testing it..... so it could contain more bugs, but the final solution should be something along those lines.....

**Comment by a13erisc** [comment]
Right now we are a bit confused over how tokens should be handled in this case. 
```css
#0f0
```
Should this be split up in tokens of #, 0, f, 0 or #, 0, f0?

**Comment by HGustavs** [comment]
The tokenizer should probably view this as an atom. i.e. the same way that we handle 200px.

**Comment by a13erisc** [comment]
So the entire "#0f0" is a token? And same applies for "200px"?
