### ISSUE TITLE
Priorities between microservices

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#12921]
We need to prioritize the different services and start with the most important services that are most crucial to the workings of the system as a whole.

The first service that is converted can/will be used as documentation of the conversion process.

**Comment by c21alest** [comment]
Use documentation of available ms: https://github.com/HGustavs/LenaSYS/blob/g2-2023-v6/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md
