### ISSUE TITLE
Code Viewer: Regular expression bug replaceAll().

### ISSUE THREAD

**Issue by a13alfbe** [HGustavs/LenaSYS#1293]
There seems to be a bug when a unclosed parathesis is used in an important word such as "scale(" the error occurs on line 999 in codeviewer.js.

Just add a new important word with the example editor like "scale(" to test this.

**Comment by a13jorla** [comment]
There should not be any not closed brackets. So the question is, should there be fault handling for this? @HGustavs

**Comment by b12simsa** [comment]
#1557 Suggested fix.

**Comment by f12danjo** [comment]
Fixed by [#1557](https://github.com/HGustavs/LenaSYS/pull/1557)
