### ISSUE TITLE
Fix bugg with "show which courses that are prereq"

### ISSUE THREAD

**Issue by a13erilj** [HGustavs/LenaSYS#1294]
There is a bugg with the prereq in the studentView.php
The issue that exists is that the hover effect does not cover the whole div.
It will stop working if you hold between Program name and course link.
Related to issue: #487

**Comment by c13marme** [comment]
The cause of the problem is, when a div have margin for example.

**Comment by c13marme** [comment]
Bugg fix was solved in issue #1328
