### ISSUE TITLE
Github Folder Structure for Github Integration

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#12951]
We suggest using a file structure such as

Folder in Lenasys / Github Repository

"Inlämningsuppgifter inbäddat innehåll 2,0 hp (U-G-VG)"
or
"Complete Examples"

Inside those folders we have (for example)

Canvas Animate.html
Canvas Animate.md
Canvas Animate_preview.png
Canvas Gradient.html
Canvas Gradient.md
Canvas Gradient_preview.html

if we have a .md file this should automatically be used as the instruction part of the code example if we have a preview html or preview png this should be shown as the preview content.

**Comment by b21sebgr** [comment]
We have made a filestructure showcased in the forked https://github.com/b21sebgr/Webbprogrammering-Examples from the repo https://github.com/HGustavs/Webbprogrammering-Examples. The ordering in the course are handled by the "Index.txt" file where the number in front are what type the row are (0 are heading, 1 are section and so on...) and then the name of the file, by switching the order this rows comes in we change the ordering in the course when this is uploaded to the server

**Comment by a21lukpo** [comment]
Can you check if this structure is ok or do we need to change anything in the forked repo? https://github.com/b21sebgr/Webbprogrammering-Examples
@HGustavs

**Comment by b21sebgr** [comment]
https://github.com/b21sebgr/Webbprogrammering-Examples/tree/master/CodeExamples this is the current suggestion on how the git repo should look like, all codeexamples should be inside the folder codeexample, the folders in there is all the moments, the folders in the moment is all the sections for that moment, the folders inside a section is all the codeexamples for that section, the files in all those folders are the files that makes up the codeexamples. What do you think @HGustavs ?

**Comment by a21olljo** [comment]
Henrik has supplied a reference case in issue #13875, which will be the file structure used.
