### ISSUE TITLE
Lenasys / Github Markdown Test Document / Documentation

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#12952]
The same document that should be used for testing should contain both github and lenasys markdown tags.

Development of test document for Markdown supporting both Lenasys Markdown and Github Markdown.

If it is impossible to support both due to incompatibilities in the code, the example should still contain both.

It is unclear if the code standard or other documentation has a complete example for the lenasys markdown if such a document exists it should be used as a base for the improved version.

Link any preexisting document of lenasys markdown standard in the repository to this issue for the sake of documentation.

**Comment by a21rammo** [comment]
Seems to be resolved for all cases: code blocks, images and links

https://github.com/HGustavs/LenaSYS/pull/13122
https://github.com/HGustavs/LenaSYS/issues/13024
https://github.com/HGustavs/LenaSYS/issues/13027

**Comment by a21rammo** [comment]
@HGustavs I would like to close this issue, if there is no further comments from you.
