### ISSUE TITLE
CTRL z reverts all colour changes.

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#12957]
CTRL z will revert all colour changes first simultaneously. It dose this even if other changes happend after the last colour change.

**Comment by b21eriho** [comment]
The actual issue at hand is the fact that colors are not appended to the undo-redo-structure at all. This isn't handled in the same way as other attributes since those are input fields so the color works differently

**Comment by c21adano** [comment]
are you able to add colours to the undo-redo-structure or is it not possible due to them working differently?

**Comment by b21eriho** [comment]
Only saw this now after already fixing this, but yes the fix was to add the color-change-event to the undo-redo-structure correctly, it was a single line that had been missed or accidentally removed
