### ISSUE TITLE
Model pushnotification service

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#12966]
This service needs to be modelled. Related to issue #12920 

* Which parameters does the service receive?

**Comment by c21alest** [comment]
No pushnotificationservice.php found

**Comment by c21alest** [comment]
Inside the /Shared folder there is a [pushnotificationshelper.php](https://github.com/HGustavs/LenaSYS/blob/master/Shared/pushnotificationshelper.php), maybe this is the service?

**Comment by d21erisu** [comment]
Might be pushnotifications.php   https://github.com/HGustavs/LenaSYS/blob/master/DuggaSys/pushnotifications.php  

Not sure tho

**Comment by b21ricni** [comment]
Since pushnotifications have the most similar name, that's the one  we'll work with. Services isn't necessarily the in the original name of the file.
