### ISSUE TITLE
Model profile service

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#12967]
This service needs to be modelled. Related to issue #12920 

* Which parameters does the service receive?

**Comment by a19hakja** [comment]
Start with a UML class diagram and a textual description of the files functionality.

**Comment by b21hamwe** [comment]
Jag (b21hamwe) och a21oscgu har diskuterat oss fram tillsammans med våra kollegor att if statements kommer att
beskrivas som metoder i dessa modeller även om det traditionellt enligt UML klassdiagrams notation vanligtvis inte gör det.
Detta för att kunna beskriva profileService filen då majoriteten av filen består utav if statements.
