### ISSUE TITLE
Error handling for database query

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#12996]
in diagram.php:
right now there is no error handling when queries are performed against the database. We want to check if the query actually succeeded or failed before fetching the data and if it fails inform the user.

**Comment by HGustavs** [comment]
Are we doing database stuff directly in diagram.php?

**Comment by b21oscpe** [comment]
Check if this issue was migrated into diagramservices.php

**Comment by b21matfi** [comment]
There is no queries that can be moved, the querie that is left is the one that fetches the data from the diagramservices.php.

**Comment by b21oscpe** [comment]
What do you mean by moved? Are you looking in diagram.php or diagramservices.php?

**Comment by b21oscpe** [comment]
We have moved the backend code to diagramservices.php, try to look there instead

**Comment by b21matfi** [comment]
I checked diagram.php to see if all the queries are moved to diagramservices.php and added error handling where it was missing in the diagramservices.php
