### ISSUE TITLE
#12926 - Create a github integration when creating a new course

### ISSUE THREAD

**Issue by a21rammo** [HGustavs/LenaSYS#12991]
When a teacher creates a new course it contains two different input labels currently. Extends this to three input labels which one should contain a url for github repository. The third input label should also contain a reg expression, insuring that it follows the github.com pattern.

**The button to create a new course:**
![image](https://user-images.githubusercontent.com/102600501/229506530-29571d99-6040-4f84-accd-5de55e256eb7.png)

**An example of how it can look like:** 
![image](https://user-images.githubusercontent.com/102600501/229507060-d4ada97a-ed75-4639-a337-ec47dbdaa342.png)

**Comment by a21rammo** [comment]
#12926 - Subissue

**Comment by c21sebar** [comment]
Not a" yes or no" option, no animation, just the url or no url

**Comment by c21sebar** [comment]
Good job!
