### ISSUE TITLE
HTML tags won't show in php-files

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#1300]
![1](https://cloud.githubusercontent.com/assets/11722176/7489308/956f558c-f3d5-11e4-9603-0955ed0da081.png)
A php-file viewed in the codeviewer and the same file in Notepad++.

**Comment by HGustavs** [comment]
It seems like the < and > are not escaped in the output....
if we write <html> it is interpreted as a tag. We must write &lt;htlm&gt;

**Comment by HGustavs** [comment]
The tag is there but interpreted as html.

**Comment by f12danjo** [comment]
Yes, exactly and it is the same in the description boxes. Which can cause trouble with the code blocks.

**Comment by b12simsa** [comment]
Added a suggested fix in #1352.
