### ISSUE TITLE
#12929 Github markdown support 

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13004]
What is the difference style in Github and Lenasys Markdown support currently?

#12929 
Look at these as a priority, rest is stretch goals after.

> links first
> after that images
> finally code blocks

**Comment by d21emijo** [comment]
![image](https://user-images.githubusercontent.com/102797583/229814208-512d5eeb-d674-40a5-99a0-cc1d0739a653.png)

This works in regex tester when switching $1 and $2, but when testing on webserver only 1 letter gets parsed in the link from $1
and $2 doesnt seem to be used at all

![image](https://user-images.githubusercontent.com/102797583/229818544-cb0bdad5-932c-441c-a38f-e62dd02fa036.png)

**Comment by b21geoyo** [comment]
### Github link format:

[Google](https://www.google.com)

### LenaSYS link format:

!!!https://www.google.com, Google!!!

### Github image format:

![Alt img text](Link to image)


### LenaSYS image format:

Does not work when I tested it. However the format is supposed to be: |||src, thumbnail in width px here,  full width here|||

### Github code blocks:

Inline `code` has `back-ticks around` it

```
Code block in here surrounded by three backticks
```

### LenaSYS code blocks:
LenaSYS code blocks is the same as github for code block and for inline code block

**Comment by a21rammo** [comment]
seems to be resolved
