### ISSUE TITLE
How does the filstructre look like now, inorder to create a new course?

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13003]
To solve #12951 we need to know how current structure looks like.

**Comment by a21lukpo** [comment]
Filer att komma ihåg: Sectioned.php, Codeviewer.php, codeexample i databas

**Comment by a21lukpo** [comment]
To create a new course you currently have to be logged in and then press the "+" icon in the lower right corner. After that you have to fill in a Course Name which only allows letters and Course Code which only allows 2 letters, 3 digits, 1 letter in this order. This is then verified in a function called "validateForm". If both of these inputs are correct the "validateForm" function calls the "createNewCourse" function. This function then sends the data to the "course" table in the database. These 3 functions can be found in the "courseed.js" file.
![image](https://user-images.githubusercontent.com/102577654/229828562-6db1187a-4abb-4641-9fbe-ac58813294a7.png)

![image](https://user-images.githubusercontent.com/102577654/229827701-011863d9-8ef7-42ac-9342-0c6803ac7947.png)

**Comment by b21sebgr** [comment]
Filerna sparas på webbservern och namnet på filerna sparas i databasen i tabellen "codeexample", filerna sparas under LenaSYS/courses/<kurs kod>/<filnam>, det kan även sparas globalt och då byts kurs koden ut till "global"
