### ISSUE TITLE
#12992 - FETCH data from a Github repository

### ISSUE THREAD

**Issue by a21rammo** [HGustavs/LenaSYS#13001]
Sub-issue of #12992 - FETCH data from a Github repository

When it comes to automating creating course, the first step is to fetch data from a repository.  So an idea of a approach is maybe doing a HTTP GET request for the url, to get the data which is needed to solve the issue.
 Documentation of Github repository GET request with response schema. This is an example: 
````js
{
  "type": "file",
  "encoding": "base64",
  "size": 5362,
  "name": "README.md",
  "path": "README.md",
  "content": "encoded content ...",
  "sha": "3d21ec53a331a6f037a91c368710b99387d012c1",
  "url": "https://api.github.com/repos/octokit/octokit.rb/contents/README.md",
  "git_url": "https://api.github.com/repos/octokit/octokit.rb/git/blobs/3d21ec53a331a6f037a91c368710b99387d012c1",
  "html_url": "https://github.com/octokit/octokit.rb/blob/master/README.md",
  "download_url": "https://raw.githubusercontent.com/octokit/octokit.rb/master/README.md",
  "_links": {
    "git": "https://api.github.com/repos/octokit/octokit.rb/git/blobs/3d21ec53a331a6f037a91c368710b99387d012c1",
    "self": "https://api.github.com/repos/octokit/octokit.rb/contents/README.md",
    "html": "https://github.com/octokit/octokit.rb/blob/master/README.md"
  }
}
````
Documentation: https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28

This is a subissue, main issue: #12992

**Comment by e21krida** [comment]
Proposal: Using Github API to establish connection and fetch relevant information.

**Comment by e21krida** [comment]
https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api?apiVersion=2022-11-28
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

It appears that we can potentially make a non-personal token to access specific read-only repositories, we will experiment more with this tomorrow. Another option is to open an organization-account to handle the future repositories for courses, is this something @HGustavs is willing to do? Or should we continue with the experimentation tomorrow before a decision is made? And would you be okay overall with us experimenting with using the API to solve the automation of fetching individual repos?

**Comment by a21olljo** [comment]
Investigating using Octokit to send requests to GitHub REST  API 
https://github.com/octokit/octokit.js/#usage

**Comment by HGustavs** [comment]
To get contents of a specific known file we can use php file_get_contents 

https://raw.githubusercontent.com/HGustavs/LenaSYS/master/testfiles/README.md

**Comment by a21rammo** [comment]
![image](https://user-images.githubusercontent.com/102600501/229807776-95d6fc22-3b21-4f9d-b609-fc5c1911a8df.png)

**Comment by c21sebar** [comment]
We should find a solution that works apart from GitHub, what if at a later time the repo is moved away from GitHub we should not be locked behind a GitHub api to fetch files to the webserver to integrate into LenaSys.
A php solution may be a good start, something like this may be worth investigate in combination with file_get_content?
https://www.javatpoint.com/php-download-file
https://www.javatpoint.com/php-file-upload

**Comment by HGustavs** [comment]
I do believe that php download file outputs the file... perhaps there is a way to redirect this to a file in the local file system?

We want to download the file from github only if that file has changed, and we want to check only periodically at set intervals for example once every 10 minutes all other times the user sees the (lenasys) locally stored cached copy.

So:

Github will ban anyone that hammers files or apis. So downloading directly at the number of requests that we are doing is much higher than what github allows.

Also as an additional feature we could add a "refresh" button for logged in users to refresh the download automatically (at a shorter interval than the example of 10 minutes above). So If I know that I have updated some example on github I can push a button (next to cog wheel?) to manually refresh that example.

<img width="732" alt="Screenshot 2023-04-05 at 09 45 46" src="https://user-images.githubusercontent.com/6978801/230015230-f9b451e3-8772-4ed6-960e-c4353cee8084.png">

Also, if for some reason connection with github is lost, we still want our machine to serve the existing code examples

**Comment by e21krida** [comment]
@HGustavs Could this not be simplified by using javascript -> window.open() with the actual download link for a specific repo, e.g. (https://github.com/HGustavs/LenaSYS/archive/refs/heads/master.zip), therefor we could use HTML to feed a specific repo-link to download, i.e. create a graphical userface for this.

**Comment by a21olljo** [comment]
After completing issue #13070, which are related to this issue. I will continue by developing a method to structure the data collected by traversing the repo, which currently is all stored in an array. This structure or file tree should mirror that found in the repository, to easier search for specifik files and/or automatically create courses on LenaSYS.

**Comment by b21leowa** [comment]
This issue is now merged, I close this issue now
