### ISSUE TITLE
Previous Github integration work

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13010]
Previously there has been issues on github integration. Unclear as to how much of these issues that have been implemented (provide links to this issue). From  #12926 

Find out what has been done and how far they reached. Can we continue on their creation or where do we stand now?

**Comment by a21henhe** [comment]
We found the following issues: #11775 and #7763 but not entirely sure if these issues are related to the github integration and/or the relevance of this (for instance since rawgit have been shutdown) @HGustavs . Although there seems to be no previous work done on these issues

**Comment by a21rammo** [comment]
Closing this issue @a21henhe
