### ISSUE TITLE
Stop it from changeing text color when writing

### ISSUE THREAD

**Issue by b21sebgr** [HGustavs/LenaSYS#13014]
Investigate and fix the changeing of color in the box where the github name should be written in (check correctnes in both dark and light mode) currently the text goes almost invisible in darkmode

Bug found in DuggaSys/contribution.php

![image](https://user-images.githubusercontent.com/102599253/229743232-593f0c76-9487-4ca1-90db-9242c6ac5b7c.png)

![image](https://user-images.githubusercontent.com/102599253/229743402-163446c9-f9f3-47b9-adcf-ef783d1f10df.png)

**Comment by c21sebar** [comment]
Can this also be related to previous work of students with GitHub integration #13010 ?
