### ISSUE TITLE
New code example should not affect existing order of code examples

### ISSUE THREAD

**Issue by a21rammo** [HGustavs/LenaSYS#13017]
## order should be uneffected
"We do not want to number code examples (since we get problems if we want to make a new example between example 1 and 2)"

Need some clarification, should we remove the part which says "example 1", "example 2" etc? @HGustavs 

![image](https://user-images.githubusercontent.com/102600501/229751509-bc69efe4-1f2e-478b-bdb7-e201dbc431a7.png)

The picture above should the "Complete canvas example 1" be removed?

**more like this:** 

![image](https://user-images.githubusercontent.com/102600501/229752021-4e64ebc1-003a-45e1-aa45-b07a13cd65c2.png)

## order should also  be uneffected by new folders
We also dont want to change the order when new folders/items are added as noted in the comment :
https://github.com/HGustavs/LenaSYS/issues/13018#issuecomment-1495787827

From the closed issue https://github.com/HGustavs/LenaSYS/issues/13018

**Comment by a21rammo** [comment]
This is a subissue to: #12927

**Comment by HGustavs** [comment]
Im thinking that 
"Example 1: Book Your Santa"

Would be the name of a sub-folder in github?

No need to remove anyting, we call the heading in lenasys the same thing as the name of the file or folder on github.

**Comment by a21rammo** [comment]
I'd imagine something like would look approachable and structured. Having all markdown and html in one folder for each section sounds a bit lousy longterm. Making subfolder for each content seems more manageable approach.

![image](https://user-images.githubusercontent.com/102600501/229789931-6a1ccdc4-e182-4c87-b581-fa130a77d1f5.png)
