### ISSUE TITLE
Implement GitHub Markdown code block

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13027]
Implement GitHub Markdown code block style to work with LenaSys Markdown style

**Comment by a21rammo** [comment]
#13004 This issue might contain useful infomation. To test if the implementation of Github markdown works for Lenasys markdown. You will need to go into the course (the one i'm using is demo course).  First click the "cable" symbol:

![image](https://user-images.githubusercontent.com/102600501/230047401-fec201e8-ebe4-4f4c-917c-5c5ae92d4787.png)

**Click the "+" symbol**

![image](https://user-images.githubusercontent.com/102600501/230047606-3a9d9e3b-5d0b-4552-b37e-870558f093d0.png)


**Add dummy empty file:**

***The dummy file must be a .md file!***



Go and try to edit the new md file and you should see a markdown and to the right of it is a markdown preview:
![image](https://user-images.githubusercontent.com/102600501/230048463-2a9457f4-1006-4133-8db7-fa200173d785.png)

**Comment by b21geoyo** [comment]
Single handedly solved Github flavored markdown code blocks in LenaSYS by doing nothing because it was already supported. LenaSYS uses the same formatting for codeblocks.

![image](https://user-images.githubusercontent.com/102578996/230099179-2aa8a4d7-c8d6-4f70-bffc-ee49fd613e44.png)

**Comment by b21leowa** [comment]
If Lenasys already support code blocks, then close this issue.

**Comment by a21rammo** [comment]
done
