### ISSUE TITLE
Implement GitHub Markdown image style

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13025]
Implement GitHub Markdown image to work with LeanaSys Markdown style

**Comment by a21rammo** [comment]
#13004 This issue might contain useful infomation. To test if the implementation of Github Markdown works for Lenasys markdown. You will need to go into the course (the one i'm using is demo course).  First click the "cable" symbol:

![image](https://user-images.githubusercontent.com/102600501/230047401-fec201e8-ebe4-4f4c-917c-5c5ae92d4787.png)

**Click the "+" symbol**

![image](https://user-images.githubusercontent.com/102600501/230047606-3a9d9e3b-5d0b-4552-b37e-870558f093d0.png)


**Add dummy empty file:**

***The dummy file must be a .md file!***



Go and try to edit the new md file and you should see a markdown and to the right of it is a markdown preview:
![image](https://user-images.githubusercontent.com/102600501/230048463-2a9457f4-1006-4133-8db7-fa200173d785.png)

**Comment by b21geoyo** [comment]
It currently seems like there is an issue with LenaSYS markdown image format. Check issue #13082 for more info.

**Comment by b21leowa** [comment]
I have solved it so now you can upload an image to the markdown file. But to fix it I had to change from | to % as seen below

<img width="818" alt="image" src="https://user-images.githubusercontent.com/102594255/230322144-28bb1be0-516a-4afc-b2e6-7f1315199574.png">

**Comment by b21leowa** [comment]
This issue is not solved because I haven't implemented Github Markdown image style. But I will work on it now.
