### ISSUE TITLE
dugga.js

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#13040]
As a first step in modern javascript migration check if ajaxservice makes use of fetch (with await) the modern javascript way to call web services or if it makes use of the older htttprequest object or jquery ajax queue.

If not make it use fetch as a part of migration (unclear whether this is a previously resolved issue)

**Comment by b21kurar** [comment]
![image](https://user-images.githubusercontent.com/129070844/230044864-2556281a-2d6f-449c-aa65-2f1bf8532582.png)
This is the code under the AJAXService() function. When searching the file, there is no reference of any "fetch". Is it safe to assume that the it uses ajax queue?
