### ISSUE TITLE
Log service usage/distribution from dugga.js

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13058]
To write tests and get an understanding of how/what/when different services are used, logging code should be created, and called through the AJAXService() function in dugga.js

It may be advisable to write the code directly into the AJAXService function, or maybe a separate file called by the function. However it should be easy to comment out, as it should **not** be part of production/user usage. This is because constantly logging every action will slow the system down. As such it is advisable that the code should be easy to reactivate from dugga.js, since logging will be done for most of our work with microservices.

This should save the logs to a file, and then be followed by repeated usage of LenaSYS. 
Important to ensure that the same actions result in the same output to the log.

**Comment by b21kurar** [comment]
Been doing some investigation on dugga.js and what is sent when using the system. 
kind=PDUGGA seems to do a lot of work, it appears to be the parameters that decides what dugga is opened.

**Comment by b21kurar** [comment]
In dugga.js there appears to already exist a lot of console.log statements, these could be used to verify tests.

I have also created a branch where a log is printed out for each AJAXService call with the parameters.
g2-2023-v1-log_investigation

**Comment by b21kurar** [comment]
The parameters in AJAXService(opt, apara, kind)

opt: Probably option, usually GET, POST or others like them
apara: array of parameters
kind: kind of LenaSYS page, such as: PDUGGA, SECTION

**Comment by c21alest** [comment]
All logged data displayed in the console as shown in this comment

> Here is an example of apara values for PHP example dugga:
> [![apara.png](https://camo.githubusercontent.com/08484f340bfba8a02d1b6368a0a6303c95ea5ba37b595c96f08e758a727fc36d/68747470733a2f2f692e706f7374696d672e63632f6e7a30684d3778562f61706172612e706e67)](https://postimg.cc/wyRpG13n)

will be sent to a log.js or log.php (according to issue #13121 ) that will display this data in an easy way and also generate a csv for more in depth logging information.

**Comment by c21alest** [comment]
Here is a graphical explanation of this logging solution that also tries to describe #13121 
[![dugga-js-logging-comonents-and-communication.png](https://i.postimg.cc/QMsHRbmV/dugga-js-logging-comonents-and-communication.png)](https://postimg.cc/DSjvG1tK)

**Comment by b21kurar** [comment]
Discussions have been made with @c21alest and @b21hamwe, these are the results.

@c21alest suggested different solutions that may work, such as showing the logs at the top of the page, or saving the logs to a database or saving to a separate file that can then be read by a presentation page.

Considering different ways to log data, it is important that the user isn't affected by the logging (other than performance issues), that means that usage of LenaSYS must not be altered (the user shouldn't see logs and shouldn't have to click something to get it to log).

This data should (after some discussing) be saved as a separate file (CSV, XML, or other) that is then parsed and presented in a more readable manner. This could be a specific .php file that can present the logs with tables ( as per @b21hamwe s suggestion).

The usage should be in the following manner: Add logging code (activate logging), usage of LenaSYS, close LenaSYS, read logs.

How it is presented can come to change, but as of now it is important to choose an appropriate way to file the data, and then to "reassemble" it to readable logs.

**Comment by b21kurar** [comment]
This issue should focus on the "assembling" of the data. That means, the result of this issue should be the code to how the data should be saved to a file and possibly the reassembling as well.

**Comment by c21alest** [comment]
After implementation of such a solution the dugga.js sends a POST to a PHP file (logging.php) with the log data as JSON. This JSON data is then written to two JSON files, one that stores only the latest log (logs/latestlog.json) and another one that contains all logs (log.json). A further improvement could be to store different log files for each day if that is needed in the future.

**Comment by b21kurar** [comment]
We have now discovered that there already is logging functionality in LenaSYS, the logs are found under log/loglena6.db which is a sqlite database. This will be used further along. However, it should be noted that the work done in the branch `g2-2023-v2-#13058` could still be useful in case of additions to current logging functionality.

**Comment by b21kurar** [comment]
Closing this, the work related to the issue was completed. However, we will focus on the existing logging functionality as of now.
