### ISSUE TITLE
Add support for GitHub in Moments in LenaSys

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13069]
A course page should not pull all data from github, some folders on github should not automaticly become a task/moment/heading in LenaSys, only selected folder should be imported.

Add support to point to a folder in the github repo for the course page in the "moment". 
Can we add support in the existing "moment" type or do we need to add another "GitHub" type?
![image](https://user-images.githubusercontent.com/102595788/230053507-b34898eb-ac44-4669-a073-f0baf2f3c625.png)
![image](https://user-images.githubusercontent.com/102595788/230054862-5095e7cf-0dfa-4c98-b970-f75ff75e0e23.png)

This would be a requirement for the traversal inorder to know what filesystem to start to loop thorugh and the download and compare if changes has been made.

**Comment by d21emijo** [comment]
![image](https://user-images.githubusercontent.com/102797583/231194697-1101f6e8-9259-4c3c-b726-ef65e966fade.png)
added a github icon

in the hidden section somehow github icon is slightly visable?
´´´
onclick='confirmBox(\"openConfirmBox\", this);'>`;
´´´
new onclick needs to be made for github support

**Comment by d21emijo** [comment]
This button will act as a "setting/control" panel for the GitHub implementation, for future implementation the functionality of the click needs to be changed, as it now it only works in the same way as the trashcan.
