### ISSUE TITLE
Primary, secondary (and tertiary) colours for light & darkmode

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13065]
As the title suggests we need to choose which colours should be used across the diagram.php file for design purposes.
As it is right now colours vary where they should not.

Use this as reference. The colors will apply to the "diagram-drawing" part of the page.
[https://m3.material.io/styles/color/the-color-system/key-colors-tones](https://m3.material.io/styles/color/the-color-system/key-colors-tones)

**Comment by c21theti** [comment]
Vad är det jag ska ändra färg på och ska jag ändra de befintliga f'rgerna som finns?

**Comment by b21oscpe** [comment]
No changed are required, as of now just decide what colors (rgb, hexcode, etc.) are going to be used for the lightmode and darkmode modelling. This includes entities, arrows, background and so on.

**Comment by c21theti** [comment]
![Capture2](https://user-images.githubusercontent.com/102578329/230072079-a019f88e-8a5a-439e-930d-afcaaacd41a0.JPG)
There are already available colors for the diagrams for both dark and light mode that works and looks good. 
![Capture](https://user-images.githubusercontent.com/102578329/230072350-c91b0faa-cb98-4745-b42b-f97749b9b439.JPG)
I have found are a few things that could be changed. For example the X is barely visible and needs to be changed to white color. Also the arrows need to be in white color so they are visible. Another suggestion is to change the background slightly to a lighter color. 

Another suggestion is to add two templates so the user can change color for all entites in one click to make the diagram making easier. For example default and color mode. Examples below are from Lucidchart

![Opera Snapshot_2023-04-05_140032_lucid app](https://user-images.githubusercontent.com/102578329/230074217-b24a6643-0aa1-4c98-8325-2be4f7134e38.png)

![Opera Snapshot_2023-04-05_135831_lucid app](https://user-images.githubusercontent.com/102578329/230073899-a1e5386c-2568-4398-b41f-4079fb930b2c.png)

**Comment by b21oscpe** [comment]
Looks good.
