### ISSUE TITLE
Investigate a suitable testing system

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13062]
Related to issue #13059 
We need to decide on how a reasonable testing system will look and be used.

A suggestion could be a simple test.php that collects tests from separate files (e.g microservice1test.php, microservice2test.php ,etc...) and then outputs results showing which tests passed/failed sorted by which microservice

E.g
Microservice 1
test 1 pass
test 2 fail

Microservice 2
test 1 fail
test 2 pass

etc...

(microservices should have a name that represents their function, please don't just call them microservices1)

**Comment by b21kurar** [comment]
I believe this could be a scalable solution, since new microservices could easily be added as new test files, and the main test.php can search for all test files in a test folder.

**Comment by b21kurar** [comment]
Could however use some consideration on microservices calling other microservices, I expect it to be easy to add tests to the already existing microservices tests, and it should be easy to locate them based on coherent naming of microservices.

**Comment by d21erisu** [comment]
I think having a specific file per microservice with the sole purpose of testing that specific service seems like a great idea. If the files have appropriate names it will be easy to see what services have tests and to modify them. Also easy to add and remove tests if necessary.

**Comment by HGustavs** [comment]
What standard testing tools are there that are applicable and do these tools have standard data files for defining tests of microservices?

Perhaps we can use data format from commercial/open source testing tools, in order to be close to "real" testing environments? In that case we can at some point integrate with external testing tools. Currently the plan is to be independent lenasys testing tools, but in the future we may want to be inclusive?

**Comment by d21erisu** [comment]
I'm thinking that some form of black box testing might be good as well? To see that the correct microservice is used. But at the same time we want to test that the microservice itself does what is expected.

**Comment by b21kurar** [comment]
> I'm thinking that some form of black box testing might be good as well? To see that the correct microservice is used. But at the same time we want to test that the microservice itself does what is expected.

The black box testing would probably just cover the current service right? As I see it, that black box test would test multiple microservices at once. As such we need to then find a suitable way to test individual microservices. This is however just an assumption from me.

**Comment by d21erisu** [comment]
Using already existing testing tools (commercial/open-source) seems like a good idea. 

The testing tools: JUnit, Selenium and TestNG are recommended so i will read more about them

**Comment by d21erisu** [comment]
Also what types of tests are we interested in, unit tests seems good, treating each microservice as a unit and testing each one of them. This is white box and made by the developer. Are we more interested in making automated tests?
Integration testing and end to end testing(E2E) might be relevant as well

**Comment by b21kurar** [comment]
I would agree with unit testing, as you describe. Automated testing will help a lot when implementing microservices, so that would be good. 

Any considerations regarding testing between microservices?

Also, make sure that the testing tools are applicable for our languages

**Comment by b21kurar** [comment]
Now I will be the first to tell you that I am not very well versed in testing, but the way I imagine it is having a separate test file that one writes assertion-tests. Such as in JUnit, might help to look in the documentation https://junit.org/junit5/docs/current/user-guide/

**Comment by b21kurar** [comment]
So that when we write tests, we give values/parameters to the service and write out the expected result in the assertion. As such when converting services to microservices, we should still have the same results.

**Comment by b21kurar** [comment]
The issue here is that JUnit is for Java (as far as I know), but we could maybe borrow their "syntax" and try to make a very basic veresion for PHP/Javascript?

Thoughts on that?

**Comment by b21kurar** [comment]
Example of things to strip away, the annotation system. Not really relevant for us right now I believe.

**Comment by b21ricni** [comment]
JS have test library's, don't know if it relevant or not

**Comment by d21erisu** [comment]
> Now I will be the first to tell you that I am not very well versed in testing, but the way I imagine it is having a separate test file that one writes assertion-tests. Such as in JUnit, might help to look in the documentation https://junit.org/junit5/docs/current/user-guide/

Will look into that

**Comment by d21erisu** [comment]
> The issue here is that JUnit is for Java (as far as I know), but we could maybe borrow their "syntax" and try to make a very basic veresion for PHP/Javascript?
> 
> Thoughts on that?
Yes,
If we are to "use" and follow the so that we in the future might be able to evolve and use the service, then its good to follow their syntax I believe. 
I don't know how it will be in practice to "convert" but it seems like it's a good idea to try and make it possible as best as we can. So using their syntax seems like a good idea.

**Comment by d21erisu** [comment]
> The issue here is that JUnit is for Java (as far as I know), but we could maybe borrow their "syntax" and try to make a very basic veresion for PHP/Javascript?
> 
> Thoughts on that?

Yes,
If we are to "use" and follow the so that we in the future might be able to evolve and use the service, then its good to follow their syntax I believe.
I don't know how it will be in practice to "convert" but it seems like it's a good idea to try and make it possible as best as we can. So using their syntax seems like a good idea.

**Comment by b21ricni** [comment]
Looking through ways to test js and php seem to mostly be made through frameworks, is the goal to write a Js,Php code that can do the test?

**Comment by d21erisu** [comment]
Some form of assertion test would be optimal for our situation, using the already existing system to "declare" what input is expected and how the new microservices should work. If the output is the expected output, the test succeeds, else it fails. Would suit us really well.

**Comment by b21kurar** [comment]
> 

The goal is to define a standard so that we can then implement an (autonomous) testing system.
This is to make it easier when integrating microservices later

**Comment by b21kurar** [comment]
Something I have not considered yet is integration testing, is that something anyone has thoughts on?

**Comment by b21kurar** [comment]
> > Looking through ways to test js and php seem to mostly be made through frameworks, is the goal to write a Js,Php code that can do the test?
> 
> The goal is to define a standard so that we can then implement an (autonomous) testing system. This is to make it easier when integrating microservices later

To clarify, we want to know **how** to write a test file, so that we can now **what** to implement for the testing system.

**Comment by d21erisu** [comment]
> 

Maybe if the unit tests are deemed insufficient we might consider doing integration tests. Might be good to keep in mind that we might want to do them as well.

**Comment by b21ricni** [comment]
> > > Looking through ways to test js and php seem to mostly be made through frameworks, is the goal to write a Js,Php code that can do the test?
> > 
> > 
> > The goal is to define a standard so that we can then implement an (autonomous) testing system. This is to make it easier when integrating microservices later
> 
> To clarify, we want to know **how** to write a test file, so that we can now **what** to implement for the testing system.

Assertion testing
So following the structure from JUnit we would wanna make a file that reads from the file sending and receiving file. If the data match we get an ok and if it doesn't it gives a negative?

**Comment by b21kurar** [comment]
> > > > Looking through ways to test js and php seem to mostly be made through frameworks, is the goal to write a Js,Php code that can do the test?
> > > 
> > > 
> > > The goal is to define a standard so that we can then implement an (autonomous) testing system. This is to make it easier when integrating microservices later
> > 
> > 
> > To clarify, we want to know **how** to write a test file, so that we can now **what** to implement for the testing system.
> 
> Assertion testing So following the structure from JUnit we would wanna make a file that reads from the file sending and receiving file. If the data match we get an ok and if it doesn't it gives a negative?

Precisely, but I want to make reiterate that JUnit is a suggestion. There may be a proper testing system speicifically for PHP and/or Javascript that has a better format. Don't know how far you've been looking into that, but the documentation for different testing systems might be a good place to look. Might be many similiaraties?

**Comment by b21kurar** [comment]
> > > > > > Looking through ways to test js and php seem to mostly be made through frameworks, is the goal to write a Js,Php code that can do the test?
> > > > > 
> > > > > 
> > > > > The goal is to define a standard so that we can then implement an (autonomous) testing system. This is to make it easier when integrating microservices later
> > > > 
> > > > 
> > > > To clarify, we want to know **how** to write a test file, so that we can now **what** to implement for the testing system.
> > > 
> > > 
> > > Assertion testing So following the structure from JUnit we would wanna make a file that reads from the file sending and receiving file. If the data match we get an ok and if it doesn't it gives a negative?
> > 
> > 
> > Precisely, but I want to make reiterate that JUnit is a suggestion. There may be a proper testing system speicifically for PHP and/or Javascript that has a better format. Don't know how far you've been looking into that, but the documentation for different testing systems might be a good place to look. Might be many similiaraties?
> 
> Sir, i think this is what we looking for, its an addon but we still need to write test code: https://phpunit.de/getting-started/phpunit-10.html

This looks good to me! 
@HGustavs what are your thoughts on either using this system as is, or should we "copy" it as an in-house? Not really sure about the legality of it all. 

It seems that PHPUnit is licensed under BSD-3.

**Comment by b21kurar** [comment]
I think that for now, we use the format for the tests given by that documentiation, and write a testing system around it.

**Comment by b21ricni** [comment]
> I think that for now, we use the format for the tests given by that documentiation, and write a testing system around it.

So do we still write documentation for something? or do we follow https://phpunit.de/getting-started/phpunit-10.html

**Comment by b21kurar** [comment]
I believe for the our current testing needs we might only need the following functionality:

* assert - make sure that two values are equal, we will only test with JSON format for now. 
* login(user, pwd) - login as a user, is needed for pre-requisites of tests. Some functionality is only allowed by certain users
* send(array, service) - send values via POST to a service
* readOutput() - read the HTTP JSON response

**Comment by b21kurar** [comment]
There may be more functionality needed later, as such it might still be relevant to investigate additions. As of now for the microservices, I believe that is all.

**Comment by b21ricni** [comment]
> There may be more functionality needed later, as such it might still be relevant to investigate additions. As of now for the microservices, I believe that is all.

I don't think much more test are necessary than what we got. You have my approval sir
