### ISSUE TITLE
CodeViewer: icon for the draggable edit example box.

### ISSUE THREAD

**Issue by a12jiyba** [HGustavs/LenaSYS#1306]
I think we should add a icon on the top of the edit example box so the users can see that the box is draggable.

maybe something like this:
![test](https://cloud.githubusercontent.com/assets/11715023/7489758/8a8a180a-f3da-11e4-88da-96ee7ebfd20c.jpg)

**Comment by HGustavs** [comment]
Im against having a single box draggable, if all boxes are draggable that is fine, but if this requires an additional file specific javascript, I prefer a general "apply once works everywhere" approach. 

My view is that all such boxes should automatically by draggable or none of them should be.

**Comment by a13jorla** [comment]
Should there be an icon as in the pic(upper left corner)? @HGustavs . As for today all the boxes are draggable.

**Comment by c13caral** [comment]
Today we changed the code. Today it is now only possible to drag the boxes if the user klick on the purple head on the window. Should we implement the mouse ikon too? @HGustavs

**Comment by a13jorla** [comment]
Closing this issue since we have a draggable icon for the boxes on the pointer.
