### ISSUE TITLE
LenaSYS markdown image format not working

### ISSUE THREAD

**Issue by b21geoyo** [HGustavs/LenaSYS#13082]
When you try to use LenaSYS markdown to add an image it does NOT appear in the markdown preview. An invisible table tag appears instead.

The cause of the problem can be that because tables and images uses the pipe symbol to be added. There can be a missing checker in the code in the markdown.js file to differentiate between the two.

![image](https://user-images.githubusercontent.com/102578996/230074028-2b62351f-932c-4112-88bc-3d20eb98910e.png)

**Comment by a21rammo** [comment]
@b21leowa isn't this solved? https://github.com/HGustavs/LenaSYS/pull/13122
