### ISSUE TITLE
The "remove entity"-button is barely visible in darkmode

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13086]
![afb19ee861e828274b54e2ea700e2ed7](https://user-images.githubusercontent.com/102578165/230076171-c0745121-a12a-4807-8dac-bb59a21f6fbc.png)

**Comment by c21theti** [comment]
![image](https://user-images.githubusercontent.com/102578329/231144441-01c87da0-f12e-483d-b87d-36ffebf169e4.png) I changed the color to yellow instead of white so the X is visible even if there is an entity behind it

**Comment by c21theti** [comment]
Does yellow look good or should i change to red so it's more visible

**Comment by b21oscpe** [comment]
Change to red.

**Comment by b21oscpe** [comment]
for both

**Comment by c21theti** [comment]
![image](https://user-images.githubusercontent.com/102578329/231147272-4f53f129-2c69-42da-a71c-c164daf41f8e.png)
Changed to red
