### ISSUE TITLE
Grey out/remove unfitting options in "Edit Item" dialog

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1308]
In the edit item dialog, some of the options are not suitable for all item types. E.g. you can now set a grade system and highscore for a header. The options that are not fit for the item type should be either greyed out or removed completely.

**Comment by HGustavs** [comment]
Do we mean inconsistent and not unfitting? If we mean unfitting I do not quite understand the issue.

**Comment by b12erijo** [comment]
Yes i meant just that, couldn't find the word for it :)
