### ISSUE TITLE
remove preloaded diagram

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13080]
everytime you open diagram.php or the dugga version a old diagram is already draw on the page. This appears to some kind of old save in the code.

Find the old save and either comment out the save or remove it, the save maybe linked to other things so test with commenting it out first.

![preloadeddiagram](https://user-images.githubusercontent.com/102599332/230072953-8c36120a-6996-4719-beea-9edc855aa7fe.PNG)

**Comment by b21eriho** [comment]
I've found the part which draws this diagram, it is drawn from the database in a hard-coded way. Should I remove this in entirety or comment it out?

**Comment by c21adano** [comment]
comment out, if nothing breaks from the comment then it should be safe to remove. So comment out see if anything breaks then remove.

**Comment by b21eriho** [comment]
Note that the implementation present runs from line 25 to 95, I cannot claim to have understood it in entirety yet though it seems to be well-written code for querry-ing the database for a saved diagram which feels like something that may have to be rewritten at a later date if removed. 

However I will of course remove it if you are certain I just felt this information was useful for you.

**Comment by HGustavs** [comment]
We want similar test case that  can be loaded for other diagram types.

So rather than removing perhaps generalizing into a test diagram button/dropdown to easily produce testing diagrams of different types to interact with?

We want testing of diagram features to be extremely fast and easy.
