### ISSUE TITLE
Change color on Read Only text on server settings 

### ISSUE THREAD

**Issue by a21lukpo** [HGustavs/LenaSYS#13106]
Read Only text on server settings is black color, should be white so its possible to see the text. Only an issue in darkmode

![image](https://user-images.githubusercontent.com/102577654/230093310-7c213317-eece-48ce-9c3d-fde9d1134cec.png)
![image](https://user-images.githubusercontent.com/102577654/230093341-91dd4145-666d-41fb-823c-7bcb076cd24b.png)

**Comment by c21sebar** [comment]
pull request #13107

**Comment by b21leowa** [comment]
Pull request #13107 is merged to g3-2023-v1 and therefore I close this issue
