### ISSUE TITLE
ER entities appear slightly above where they should when placed

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13125]
https://user-images.githubusercontent.com/102578165/230330914-d0caee94-7a17-4f31-a2ac-5ae8198edc49.mp4

This issue is similar to / the same as #13083

**Comment by b21oscpe** [comment]
This isssue seems to occur only for some, investigate if this is unique to different computer/screens or if its a bug in the code.

**Comment by HGustavs** [comment]
Is it dependent on grid sizes? Or whether or not snap-to-grid is enabled?
