### ISSUE TITLE
Error message in "Edit Item" dialog after changing item type to link

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1313]
If i change the item type to link and then back again to any type, the link option remains filled in somehow. In case of illegal characters in this option i get the "llegal characters removed in link" message.

**Comment by HGustavs** [comment]
We use the "bug" tag and not bracksts in the issue title.

**Comment by b12erijo** [comment]
Noted and changed, thanks!

**Comment by b13alebr** [comment]
I think this is fixed after my changes on the "edit item" dialog

**Comment by a13denli** [comment]
Seems to be working for me. Can you confirmed, so we can close this issue?
