### ISSUE TITLE
Fix Darkmode bug in login screen

### ISSUE THREAD

**Issue by b21sebgr** [HGustavs/LenaSYS#13142]
as seen in the image below the background color is white in darkmode but the background should be black and the text should be white in the login popup in "DuggaSys/courseed.php"

![image](https://user-images.githubusercontent.com/102599253/230384610-40af4700-559c-4aae-a799-35751d7567b2.png)

**Comment by c21sebar** [comment]
Seems like this is solved thorugh the solution from issue #13146
