### ISSUE TITLE
Fix Red background in add popup

### ISSUE THREAD

**Issue by b21sebgr** [HGustavs/LenaSYS#13143]
when writing wrong in the field below they all turn red, this makes it hard to read the text and will create a issue for the darkmode, better i to make a red border that can easily be removed when input no longer is incorrect and therefore always have black background in darkmode, this happens when i got to "DuggaSys/sectioned.php" and press on the button shown below

![image](https://user-images.githubusercontent.com/102599253/230385900-e667a7e8-bbce-4d01-a68b-0d41c2645fb5.png)

![image](https://user-images.githubusercontent.com/102599253/230385526-d637b1a5-6822-4733-bead-5b2be36cf08a.png)

**Comment by a21rammo** [comment]
@a21hugni @a21lukpo  closing this now
