### ISSUE TITLE
Change github url to match regexp in input field

### ISSUE THREAD

**Issue by c21rebja** [HGustavs/LenaSYS#13147]
Make sure that the breadthFirstTraversal url matches the regex in the github input field.
Translate the url input in the window to an api link from which we can get the repository. 

From this:
![image](https://user-images.githubusercontent.com/102578746/230391942-14102c75-32de-414e-8988-0766daf6292b.png)

To this:
![image](https://user-images.githubusercontent.com/102578746/230392015-30459947-9a98-4a01-a8b9-db970e657f57.png)

(issue creation collaborator @g21emmka )

**Comment by a21rammo** [comment]
I think its better to await till the logic is first implemented and then implement the regex to match the input field. Meaning once we're sure of that the BFS metod and that approach is working, then we can implement regexp.
