### ISSUE TITLE
Course version ID should be auto-generated

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1318]
There is no reason the version ID of a course should be specified by the user, it should be generated automatically instead. The relevant dialogs should get updated after this change has been implemented.

**Comment by b12erijo** [comment]
This should probably be brought up with the customer first to ensure there actually is no purpose to it.

**Comment by HGustavs** [comment]
The version id is the same as the "anmälningskod" so it should be entered by the user. This way the course can be connected to the corresponding information in the course-viewer component.

**Comment by b12erijo** [comment]
Closing the issue as this seems like a bad idea due to the above mentioned reason.
