### ISSUE TITLE
Error messages for github integration

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#13194]
I like issue #13175 which provides error messages.

We want two levels of error handling.

If the link is wrong or if github does not reply we want the logged in users (that created the course or edited the course) to see an error message. So the user knows that the link is wrong or not working at the moment.

The error message needs to be as unobtrusive as possible. Especially if we have repeated errors for example if github is down for a week we do not want error messages every page refresh....

There are two cases for ordinary (non-logged-in) users

Ordinary users should automatically be served the local offline copy if the online copy is not available.
Ordinary users should get an error message (repository not yet available or something of that nature) if no local copy exists.

**Comment by RaymondSWE** [comment]
An example of error handler should be like status 5XX (server-related, I think 502 - bad gateway is a good choice). The error message for status 5XX should be: "The github link for this course isn't working".

There's a super easy way to implement an alert/toaster. The Javascript language has a function called "alert(MESSAGE)". 

There is an example of a error handler, there is usally many different scenarios which should all be handled in their own rightful way.

**Comment by a21rammo** [comment]
An example of error handler should be like status 5XX (server-related, I think 502 - bad gateway is a good choice). The error message for status 5XX should be: "The github link for this course isn't working".

There's a super easy way to implement an alert/toaster. The Javascript language has a function called "alert(MESSAGE)".

There is an example of a error handler, there is usally many different scenarios which should all be handled in their own rightful way.
