### ISSUE TITLE
Find older tests

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13199]
Finding older tests may help in defining how new tests should be written, or may be used completely as is.

**Comment by b21ricni** [comment]
Current strategy to find old logs and testing is to look in to git commit history, Should we do it for ever File or a few?
Service files have higher chance to have them, but assuming people could be lost making them, the test could be done anywhere.

**Comment by b21kurar** [comment]
> Current strategy to find old logs and testing is to look in to git commit history, Should we do it for ever File or a few? Service files have higher chance to have them, but assuming people could be lost making them, the test could be done anywhere.
> 
> edit: Disclaimer, not checking further back than 2021 for more relevant testing and code

Try to keep related to services if possible, as they are more relevant for us. However, any standardised way of testing is welcome! :)

**Comment by b21ricni** [comment]
> Try to keep related to services if possible, as they are more relevant for us. However, any standardised way of testing is welcome! :)

Me and @a21oscgu currently found two methods: Log testing is the most used one, but also found control test https://github.com/HGustavs/LenaSYS/commit/1bdb89a1fe368ff5519ecae7b8c420dc18b442b2

We currently have two txt files with where to find the log testing

**Comment by a21oscgu** [comment]
Issue är klar och merged @b21kurar
