### ISSUE TITLE
Implement logging presentation procedure

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13192]
Implementation of results in issue #13121

**Comment by b21kurar** [comment]
Should be discussed with assignee of issue #13058

**Comment by b21hamwe** [comment]
Me (b21hamwe) and a21jeaha has been testing different attack angles to tackle how we could implement a logging procedure

**Comment by a21jeaha** [comment]
b21kurar informed us that there already exists a logging function implemented in LenaSYS. 
with this information at hand, the issue will change its focus to accommodate that function instead.

**Comment by b21hamwe** [comment]
The work we have done will be pushed to this issue either way.

**Comment by a21jeaha** [comment]
the code associated with loglena can be found in basic.php
![image](https://user-images.githubusercontent.com/102600391/231963509-9c412ba4-8368-4a88-b776-ad3fcbdcadc6.png)

**Comment by b21hamwe** [comment]
Researching basic.php

**Comment by a21jeaha** [comment]
even though the functions that add information are used no data seems to be added to the database 

![image](https://user-images.githubusercontent.com/102600391/231973907-6359f697-c263-495a-8e9a-d4ac20dee896.png)
![image](https://user-images.githubusercontent.com/102600391/231973950-814dbd39-46fd-44de-b3fc-7c5378ba1dd2.png)
![image](https://user-images.githubusercontent.com/102600391/231974052-646c9e99-33ee-401c-a3cd-553656b2a9b4.png)
![image](https://user-images.githubusercontent.com/102600391/231974203-f1ec8d89-3fc0-40fa-88b5-a11f1fda9797.png)

**Comment by a21jeaha** [comment]
disregard my previous comments, the system log function is up and working. i was checking the wrong file..

**Comment by b21kurar** [comment]
Updated the name of this issue since it is focused on the presentation of the logs in loglena6.db

**Comment by b21kurar** [comment]
This issue is completed
