### ISSUE TITLE
Study potential microservice documents and document all unique occurrences

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13201]
Many of our "found" microservices probably have a lot of duplicates, a full list of all unique microservices with a small description of their functionality would be helpful.

**Comment by HGustavs** [comment]
A complete list would allow us to figure out naming conventions.

An advantage with the "monolithic" services e.g. duggaedservice.php is that it is very easy to find the file.

We want it to be as easy to find files by just looking at the file names, even if one has not previously worked with that specific microservice.

**Comment by b21kurar** [comment]
Related issue #13044

**Comment by a21ponkr** [comment]
Will work more on this tomorrow, so far I have added: Accessed service, Fileed service and Highscore service

**Comment by a21ponkr** [comment]
This issue is complete and merged and should be closed
