### ISSUE TITLE
Have not tested it but does the markdown parser support writing html code in a code block?

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1320]

**Comment by HGustavs** [comment]
The html code should replace < with &amp;lt; so that html code is displayed properly in markdown code boxes also.

**Comment by b14rebst** [comment]
Html-code is displayed properly as far as we can see, is this issue still relevant? @HGustavs

**Comment by HGustavs** [comment]
...I think it may have been solved. Either by accident or by conscious action....
