### ISSUE TITLE
Too many buttons in buttons-panel

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13217]
To accommodate for buttons being added to the buttons-panel we need to make sure that too many buttons does not become an issue(a problem). A solution to this would be to make the buttons-panel scrollable however alternative ideas are welcome for discussion.

![d07cc48de69154dc8a6adccf780fbda3](https://user-images.githubusercontent.com/102578165/231441532-cc33548a-dba4-4698-ad2f-6a6a672fcaf0.png)

**Comment by b21oscpe** [comment]
This may be a non-issue, needs to be investigated. Apparently the menu changes depending on what type of modeling you are working on? I'm unsure.

**Comment by c21adano** [comment]
That is suppose to be for the dugga version of the site, which used a pop out function before but it seems someone disabled it. A scroll function or similer would be needed if all diagram typs are shown at the same time, which it is in the diagram.php file.

**Comment by d21matbo** [comment]
## The solution to this issue has a major flaw as can be seen in the connected branch

It is possible to implememt a working scrollbar however when doing so the tooltips are no longer visible.

To visualize the issue the following picture shows that the tooltips are acually there, only that they can not escape the borders of their parent.
![image](https://user-images.githubusercontent.com/102599161/231747066-698c79ff-951c-49d9-8cc7-f9bab71bd70c.png)

For reference before the scrollbar was implemented the tooltips can escape the borders of their parent as visualized below
![image](https://user-images.githubusercontent.com/102599161/231747754-d71f30ff-1eaf-4681-828b-6b03868f0cf1.png)

**Comment by b21oscpe** [comment]
Our suggested solution to this is to move the "zoom"-container outside of the toolbelt to make place
