### ISSUE TITLE
Create mock-up diagram: UML

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13214]
This issue is related to https://github.com/HGustavs/LenaSYS/issues/13204

NOTE: This issue regards creating a UML model.

We want to be able to load a mock-up of a selected modeling language from a dropdown menu.

The purpose of this is to showcase the elements included in the modeling language as well as simplify development testing.

Instructions:

  1. Create an example model in diagram.php with the modeling tools available. Make sure to use as many tools as possible to showcase all functionality. (You are allowed to look at models online for reference but keep in mind that these may have copyright so copying is not allowed.)
  2. Export the model through **Options -> Export.**
  3. Leave the output as a comment to this issue.

The exported file/diagram will be used as "value" for the dropdown later.

**Comment by b21matfi** [comment]
![image](https://user-images.githubusercontent.com/102650424/231708630-9c8a81f8-5b23-4c76-b857-92b514c5bb01.png)
Can not generate file. this is how far i have come, this can be improved.

**Comment by a21aldsa** [comment]
My current, in progress, solution for this issue uses the already existing function loadDiagram to load up a UML diagram from a JSON that i exported. Currently, this JSON is just sitting in diagram.js as a one long line. I strongly this should be made into its own file but I am unsure if I am even allowed to create new files. Should I create a new file for storing just the JSON for this mockup UML diagram?

**Comment by b21oscpe** [comment]
_"1. Export the model through Options -> Export.
2. Leave the output as a comment to this issue."_

As mentioned I only want you to place the file as a comment in this issue.

**Comment by a21aldsa** [comment]
[updatedUMLDiagramTemplate.txt](https://github.com/HGustavs/LenaSYS/files/11222011/updatedUMLDiagramTemplate.txt)

Oh, my bad. Here is the file, note that github does not support JSON files so I posted it as a TXT.

**Comment by a21aldsa** [comment]
sure

[updatedUMLDiagramTemplate.zip](https://github.com/HGustavs/LenaSYS/files/11222395/updatedUMLDiagramTemplate.zip)
