### ISSUE TITLE
Change triangle arrow in darkmode

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13210]
Related: #13209

The triangle arrow should always have a white inside, the darkmode version changes this to black which makes it look like the arrow is black.
![blackarrow](https://user-images.githubusercontent.com/102599332/231428068-e787d299-e71b-4698-91de-86a00aacf992.PNG)

A black triangle arrow will be added with issue#13209 and the white arrow needs to be changed to make them look distinct in both light and dark mode.

**Comment by b21oscpe** [comment]
What happened to this issue? Was it simply not linked to its PR? Closing it for now

**Comment by c21adano** [comment]
The black arrow with white outline exist in our current version.
