### ISSUE TITLE
Change Github button on course page

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13220]
Right now the Github button is visible on every type on the coursepage.
Divide them for diffrent types and functionality. The  Github setting for a course-example should behave, look and work differently from the moment type.
* Make Github button visible on "moment" type.
* Make Github button visible on "course-example" type.

**Comment by d21emijo** [comment]
![image](https://user-images.githubusercontent.com/102797583/231769329-cc52070d-0412-4020-a739-b7f8fbd2ec10.png)
Added 2 diffrent Github icons 
1 for moments
1 for the code examples
