### ISSUE TITLE
GitHub Button clickable functions, show screen with information/settings

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13223]
For Issue https://github.com/HGustavs/LenaSYS/issues/13431
From #13220 
Add so that the GitHub button is clickable and show a screen

For the Moment-Github button
Github-Folder link:                "link"-text input OR dropdown from the CourseRepo
Filepath:                                 "text that show filepath on webserver"
Order of items                       "file that controls the order of the examples"

For the course-example Github button
Template                          template X
number of files                 number of files

For each file in the code-example
Name:                                "Name.type"
GithubUrl                            "GitHubDownloadUrl"

**Comment by d21emijo** [comment]
added a screen to github moments

![image](https://user-images.githubusercontent.com/102797583/232798608-5e2dcedf-a109-4194-be1c-0946e3686d57.png)

**Comment by d21emijo** [comment]
for 
"
For the course-example Github button
Template template X
"
something similar to 
![image](https://user-images.githubusercontent.com/102797583/233069522-714e3db8-a9b3-4cf6-912c-0b110b98616d.png)
from duggasys
