### ISSUE TITLE
Update FetchGithubRepo.php static url to dynamic url 

### ISSUE THREAD

**Issue by a21rammo** [HGustavs/LenaSYS#13225]
Reference: https://github.com/HGustavs/LenaSYS/issues/13222

The next step will be to update the BFS metod which currently holds a static url. So a method should fetch the url from the logged in user to fetch correct github content. This will be in a another issue. FetchGithubRepo.php:

![image](https://user-images.githubusercontent.com/102600501/231463654-88fefe66-340e-40ec-ba7d-5974b7b4b252.png)

Current display of github content: https://cms.webug.se/root/G3/LenaSYS/recursivetesting/FetchGithubRepo.php

**Comment by c21sebar** [comment]
https://github.com/HGustavs/LenaSYS/pull/13350
This is merged and solves this issue
