### ISSUE TITLE
Overlapping highlights

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#1323]
![overlapping](https://cloud.githubusercontent.com/assets/11715479/7491901/c3cdebd2-f3ee-11e4-9dd7-2626234fff8f.jpg)
Hightlights are overlapping, doesn't look pretty :-1:

**Comment by b12alela** [comment]
This has to do with the border ignoring the lineheight, which means it goes outside its boundaries. This actually is only the borders colliding. I'll see to a fix for this.

**Comment by a13erisc** [comment]
To be honest, this seems to be too much work for a very minor fix. Using line-height will only cause further problems.

**Comment by h14marma** [comment]
This issue seem to have been resolved. Is this perhaps also an ancient issue?

**Comment by a14jimso** [comment]
This is now fixed.
