### ISSUE TITLE
Document functional requirements for codeviewerService

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13233]
Related to issue #13208

**Comment by a21oscgu** [comment]
I've read the code multiple times. I think that it's hard to read.

**Comment by a20fanma** [comment]
the file perform many updates for each thing. Like 'EDITEXAMPLE' in row 160 has 3 performing updates. If it is possible to spilt the updates into each functional requirement? Or does it need to be one whole functional requirement?

**Comment by b21kurar** [comment]
It's a big file!

Try focusing on the if statements with `strcmp()` and focus on explaining what the file does.
The `isset($_POST)` may also be relevant to document.

From line 343 and below it is not necessary to document, this is just functionality to send values as JSON.
