### ISSUE TITLE
Document functional requirements for showDuggaservice

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13245]
Related to issue #13208

**Comment by b21ricni** [comment]
Is this standard? 
https://www.jamasoftware.com/requirements-management-guide/writing-requirements/functional-requirements-examples-and-templates

**Comment by d21erisu** [comment]
What the code enables the user to do not what the code does.

**Comment by b21ricni** [comment]
Service folder do not show if save should be event, onclick ect. Will try to find where it saves

**Comment by d21erisu** [comment]
Seems like it saves on click and locally

**Comment by d21erisu** [comment]
It's hard to specify exactly what is functional and non-functional. It's easy to realize that when trying to write a functional requirement you have actually written a non-functional one. Or simply have been describing the code and not the “functionality”

**Comment by d21erisu** [comment]
I created issue#13294 which is to convert to markdown format https://github.com/HGustavs/LenaSYS/issues/13294
