### ISSUE TITLE
Mock-up for github course module.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#13258]
The consensus is that when we select a repo for the course, a list of folders in that repo is connected to the course (physically or spiritually).

For each module such as 
* Complete Examples or
* Webbapplikation - Steg 1 och Steg 2 Navigering och Validering

We select from a dropdown the folder that we want to synchronize with that module.

I would like a mock-up for this interface so we can decide the general layout.

**Comment by a21rammo** [comment]
There is already some buttons implemented in heading and each code example. Is this the correct mock-up that henrik wants?

**Comment by b21geoyo** [comment]
![Mock-up-moment-sync](https://user-images.githubusercontent.com/102578996/233325965-27e1566f-bde0-4f3e-b346-bc6e0eb562ea.PNG)

@a21rammo
