### ISSUE TITLE
Solve API request blocked from github

### ISSUE THREAD

**Issue by a21rammo** [HGustavs/LenaSYS#13262]
A suggestion from henrik was to solve the api request block by checking commits. If the commits have changed then a fetch with the traversal should occur otherwise no fetching should occur if no commits has changed. This is done by looking at the html page and not via github apis call.

**Comment by e21krida** [comment]
I fail to see how this is possible to begin with, do you want me to create a scrapper for the website?

**Comment by c21rebja** [comment]
@HGustavs  Hi! Which link would you like to use to import the github repo to LenaSYS? Right now we have implemented a REGEXP for the url that ends with .git (for example: https://github.com/HGustavs/LenaSYS.git). 
Would you rather use the url from the "search bar" at the top of the page (for example: https://github.com/HGustavs/LenaSYS)?
// @c21rebja & @g21emmka

**Comment by HGustavs** [comment]
I prefer the URL version https://github.com/HGustavs/LenaSYS

**Comment by a21rammo** [comment]
> I fail to see how this is possible to begin with, do you want us to create a scraper for the website?

Don't know if the question is directed to me or @HGustavs. But a way I would solve it is by storing the latest commit inside of a local cache or database. So the API request checks first the commit hash which is saved in local cache (I'm guessing, its the SHA that you have FETCHED currently). If it matches the latest commit hash, skip api request otherwise call it.

**Comment by g21emmka** [comment]
@HGustavs Hi again! I solution depends on DOM Document to navigate through the page, to make this work we have to install DOM on the server. Is that okey? 

/ @g21emmka & @c21rebja
