### ISSUE TITLE
Permission denied when uploading files

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1327]
There is a permission denied error when trying to upload files. The code is probably just fine but the webserver needs permission to create new files.

**Comment by a13oscwe** [comment]
Which folder/files are involved?

**Comment by a13oscwe** [comment]
I tried changing the server permissions on filerecieve.php and the folder "/courses" to www-data and it seems to work. The changes have been made on our weekly test directory on the server "/var/www/html/duggasys".

**Comment by a13chrju** [comment]
@a13oscwe sweet! :+1:

**Comment by c13andka** [comment]
dont work for me :(

**Comment by a13oscwe** [comment]
Changed permissions abit.
filerecieve.php has 655 with owner/grp www-data
/courses has 755 with owner/grp www-data
seems to work for me.

**Comment by a13oscwe** [comment]
@HGustavs should we move the "upload" folder called "courses" to outside the git directory or is it ok to just add all files inside to the .gitignore file?

**Comment by HGustavs** [comment]
I would go with the git-ignore route as that promotes good behavior more than an external folder.

**Comment by a13oscwe** [comment]
Added courses/* to gitignore file.

**Comment by a13denli** [comment]
Seems to be working for me aswell. Maybe we can close this issue?

**Comment by a13oscwe** [comment]
Fixed so closing.
