### ISSUE TITLE
Present the logs in a usable format

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13277]
Use the log from loglena6.db and present it in a suitable format

**Comment by b21kurar** [comment]
This issue is a change in direction from issue #13192 
the work from that issue should be able to be transfered to this

**Comment by a21jeaha** [comment]
well this explains some of the problem of why no new data is added to the database, the existing table does not correlate with the INSERT that is executed.

![image](https://user-images.githubusercontent.com/102600391/231985394-9dc9c372-3066-481b-9cff-7e37ec082c55.png)
![image](https://user-images.githubusercontent.com/102600391/231985602-6e574b5e-4ac3-40a9-8d99-f14aaf5d2b23.png)

**Comment by b21hamwe** [comment]
<img width="442" alt="image" src="https://user-images.githubusercontent.com/102579060/231993286-073508cc-a6d6-4113-bc1f-572fe74d551a.png">

Found interesting logging functionality in fileedservice.php.
Potential functionality that we can reuse.

**Comment by a21jeaha** [comment]
created a file which contains dummy data. this can be used as a substitute until the the database receives real log data.
 
[loglena6.zip](https://github.com/HGustavs/LenaSYS/files/11231012/loglena6.zip)

**Comment by b21kurar** [comment]
Isn't there already data in the log? May still be relevant to use dummy data, but I just remember seeing data inside the db.

**Comment by a21jeaha** [comment]
there was a bit of information in the table userHistory, the rest were empty. the file is created now either way :p

**Comment by b21kurar** [comment]
Yes! Sounds good!

**Comment by a21jeaha** [comment]
disregard my previous comments, the log-system is working. i was just using the wrong file..

**Comment by a21jeaha** [comment]
@b21hamwe  dont forget that the "new PDO" string contains a local variable used in basic.php, for now i hardcoded it to this 
![image](https://user-images.githubusercontent.com/102600391/232040854-d564843b-d8e7-430c-aa75-d1b24a6ee1d3.png)
![image](https://user-images.githubusercontent.com/102600391/232041216-056b8179-1954-49bf-9295-4b9d7dc5cb45.png)

**Comment by a21jeaha** [comment]
i have access to the information on the database, i just need to figure out how to make it readable 
![image](https://user-images.githubusercontent.com/102600391/232051050-1c2aa5d3-ab9d-40e1-9355-4b80bdfa51a5.png)

**Comment by b21hamwe** [comment]
Final product has been pushed to the branch, further information comes from JP in a second.

**Comment by a21jeaha** [comment]
@b21kurar @a19hakja i would like to make an notation on the fact that the logging system that is in place now. cannot easily be "commented out" by just removing one line. it uses functions in the file basic.php, but is called from a number of files (i dont know if its only the files in the folder DuggaSys that make these function calls are made though).

**Comment by b21kurar** [comment]
> @b21kurar @a19hakja i would like to make an notation on the fact that the logging system that is in place now. cannot easily be "commented out" by just removing one line. it uses functions in the file basic.php, but is called from a number of files (i dont know if its only the files in the folder DuggaSys that make these function calls are made though).

Yes this was a requirement for the "previous"-implementation, however since this is an already existing system we shouldn't have to worry about it too much. The idea of "commenting out" was to not slow the system down

**Comment by a21jeaha** [comment]
right, as long as it is an issue that were aware of :)
