### ISSUE TITLE
Check functionality for ER-table generation

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13299]
How well does the ER-table generation translate models into tables? Is there anything that does not work as intended? Attach a screenshot and a comment if anything is found.

**Comment by b21matfi** [comment]
I don't understand the issue can you explain it alittle more?

**Comment by b21matfi** [comment]
is it for loading in diagrams or? only creation of the diagram?

**Comment by b21oscpe** [comment]
I sent you a PM

**Comment by b21matfi** [comment]
thank you

**Comment by b21matfi** [comment]
![image](https://user-images.githubusercontent.com/102650424/232031882-7e1f35e9-c536-405d-803c-0edd2cc5ffcc.png)

candidate and primary look the same, can not tell the difference 
and this is from the information 
![image](https://user-images.githubusercontent.com/102650424/232031933-f7ffc1c5-5db5-4934-a1c6-ace566be04ba.png)
not sure if this is an issue but seems like it there should be a way to seperate them

**Comment by b21oscpe** [comment]
Discussions between participants has lead us to believe it is working fine with minimal or no issues.

**Comment by a21aldsa** [comment]
> Discussions between participants has lead us to believe it is working fine with minimal or no issues.

Loads just fine. It is very off center though, as is the IE.

**Comment by a21aldsa** [comment]
> ![image](https://user-images.githubusercontent.com/102650424/232031882-7e1f35e9-c536-405d-803c-0edd2cc5ffcc.png)
> 
> candidate and primary look the same, can not tell the difference and this is from the information ![image](https://user-images.githubusercontent.com/102650424/232031933-f7ffc1c5-5db5-4934-a1c6-ace566be04ba.png) not sure if this is an issue but seems like it there should be a way to seperate them

As far as I can tell, candidate are shown as regular attributes, the only thing setting them aside is the fact that they could be used as primary keys, but a table has only one primary key. In my opinion, there is no reason for having a candidate key as an option.

**Comment by a21aldsa** [comment]
Source: https://eng.libretexts.org/Bookshelves/Computer_Science/Databases_and_Data_Structures/Database_Design_(Watt)

Adrienne Watt
[British Columbia Institute of Technology](https://www.bcit.ca/)

Chapter 8
