### ISSUE TITLE
Add state diagram entity button to togglePlacementType

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13301]
The state diagram entity button needs to be added to the function togglePlacementType in diagram.js.

Currently the button is not active in the code due to conflicts, this issue is not prevalent at the moment due to this and should be looked at further when the conflict is resolved.

**Comment by b21oscpe** [comment]
I believe this issue is resolved?

**Comment by c21adano** [comment]
seems like it
