### ISSUE TITLE
Present log feature: Sort by different titles

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13329]
It would be nice to have sorting functionality for this system based on clicking the titles of each column, both ascending and descending.

Default sorting should be from time, where the latest should be at the top

![image](https://user-images.githubusercontent.com/129070844/232477257-1d661392-abfe-4ab5-8bb2-dc23a3f08d92.png)

**Comment by a21oscgu** [comment]
I'm currently having problem with functions in PHP.
"Uncaught ReferenceError: a is not defined at HTMLButtonElement.onclick (log.php:16:492)".
I have no idea why the function won't run.

**Comment by a21oscgu** [comment]
Nevermind I solved the problem.

**Comment by a21oscgu** [comment]
Default sorting is reversed right now, based on my observation.

I tried one method in order to sort the table: [Sorting and Ordering tables with PHP](https://youtu.be/MlJVt3rTj1Q). It didn't work the way I wanted.

**Comment by a21oscgu** [comment]
Default sorting is not a problem anymore.
I'm still working on the sorting functionality. I don't know if it's possible to solve.

**Comment by b21kurar** [comment]
What is the problem with the other sorting functionality? Are the rows of the tables not able to use `ORDER BY`? Is it changing the sorting when clicking? Are some of the rows not reasonable to sort by (`userAgent` may be superfluous).

**Comment by a21oscgu** [comment]
Short answer while I'm working: the sorting functionality is possible to solve.
