### ISSUE TITLE
Inconsistencies with selected lines highlight in both light and darkmode

### ISSUE THREAD

**Issue by d21matbo** [HGustavs/LenaSYS#13333]
When selecting a line to change its properties the colour changes to visualise that it is selected.
However there appears to be some inconsistencies with this effect.

### For lightmode everything except the number for the cardinality and Icons:Triangle is changed
![image](https://user-images.githubusercontent.com/102599161/232478701-82dec100-029a-419f-afd1-cd0c60c14e18.png)
![image](https://user-images.githubusercontent.com/102599161/232480087-db8d6aae-5e47-40c5-9c8d-23c9c60bc737.png)

### For darkmode only the label is changed
![image](https://user-images.githubusercontent.com/102599161/232480482-bf36b99e-0797-4e02-aea8-74a2de53289e.png)

**Comment by b21oscpe** [comment]
Everything selected should be highlighted purple
