### ISSUE TITLE
Present log feature: Search bar

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13330]
A search bar would be good to add at the top, which can filter out the results based on the query.

A "simple" solution could be just find if the query occurs in any row, and present them in the results.
![image](https://user-images.githubusercontent.com/129070844/232477539-b097686d-878d-41a6-a57c-642550f15b14.png)

**Comment by a21ponkr** [comment]
![hesten](https://user-images.githubusercontent.com/102595853/232795723-f8438482-a570-4130-9d5f-0c8eb38d64c8.png)

Looks like this as of now, definitely needs fixing.

**Comment by a21ponkr** [comment]
Searching for example "Fileed" works now, however it still shows up as two tables.
![hesten2](https://user-images.githubusercontent.com/102595853/232802725-db45e117-6ebe-474c-90d0-cf02b243000d.png)

**Comment by a21ponkr** [comment]
Search randomly stopped working without having done any changes since yesterday

**Comment by b21kurar** [comment]
> Is it needed to make the search bar in Javascript?

I didn't see this comment, but no it should not. We try to keep the code standard of the other services. We will change this logging system to follow a microservice architecture soon

**Comment by a21ponkr** [comment]
Then I need to rethink my solution

**Comment by a21ponkr** [comment]
So, I made it in Javascript anyway because I could not find a decent solution for it to be in only PHP, however if someone else finds a way they can comment it here, thanks.

**Comment by a21ponkr** [comment]
![good enough](https://user-images.githubusercontent.com/102595853/233471829-7a3621d4-89ae-490d-9d72-09854337ded0.png)

**Comment by a21ponkr** [comment]
Fixed column title not showing up when i search
