### ISSUE TITLE
seperate and lable the values of the log "info" variable to make it readable 

### ISSUE THREAD

**Issue by a21jeaha** [HGustavs/LenaSYS#13342]
The "info" variable that is used in the table "serviceLogEntries" which can be found "https://cms.webug.se/root/"groupnumber"/students/"studentid"/log/" is built up of different values added onto a single string, see the images below.

![image](https://user-images.githubusercontent.com/102600391/232683336-3fd1408a-efe4-4b10-b873-84310f08210e.png)
![image](https://user-images.githubusercontent.com/102600391/232685619-00ba296e-b4e6-4620-ae06-555f9360348a.png)

These need to be separated and labeled accordingly in the table that presents that information. These changes are to be conducted in the file log.php, which is found in the folder "https://cms.webug.se/root/"groupnumber"/students/"studentid"/LenaSYS/Shared"  

the expected output should look something like this 

Option: xxxxxxxx
quizID: xxxxxx
versionID: xxxxx

Keep in mind that the content of the info variable is not set, so the solution needs to be dynamic. It might not be possible to conduct these changes in log.php, should that be the case a possible solution could be to label the values upon the variables creation. But this would mean that changes would have to be conducted in several files. 
You should contact the group-leaders of G2 to discuss possible solutions, before making any changes outside of log.php.

If more information is needed contact me @a21jeaha.

**Comment by b21kurar** [comment]
Is the $info variable used anywhere else other than the logging system? Is it attainable to update all $info variables in all services to a more readable standard? (JSON, named values, or other?)

**Comment by a21jeaha** [comment]
this is where it is used.

Folder \LenaSYS\DuggaSys
--------------------------
accessedservice.php
codeviewerService.php
courseedservice.php
diagramservice.php
duggaedservice.php
fileedservice.php
filereceive.php
filereceive_dugga.php
filereceive_preview.php
highscoreservice.php
profileservice.php
sectionedservice.php
showDuggaservice.php

Folder \LenaSYS\errorpages\
---------------------------
404.php	

Folder \LenaSYS\Shared\
--------------------------------
basic.php
log.php

**Comment by b21kurar** [comment]
As long as we can ensure that no other part of the system will break because of the changes, it should be fine. I can't really see/think of any reason this would be used outside the logging database.

**Comment by b21kurar** [comment]
I will create a separate issue for updating the `$info` variable, while this issue should focus on the presentation of that value in `log.php`

**Comment by b21kurar** [comment]
@a21jeaha are there any values in the database represented in JSON format? The question is, if we change the `$info` representation to JSON, will this work with the database and `log.php`?

**Comment by a21jeaha** [comment]
yes there is 
![image](https://user-images.githubusercontent.com/102600391/233608853-6079fba1-f0a5-45ce-ab3f-fce33f12d106.png)
this is represented in jason format. so i presume it will work.
