### ISSUE TITLE
Link the created files to the database

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13348]
We need to add/update the created files to the database so we can use them in LeanSys.

**Comment by a21olljo** [comment]
It should also be mentioned that we use a method separately to the one used in the wiki for uploading, but we save the files in the same folder however. Reusing the current system of linking files, will save a lot of work with implementation of maintaining files, along with being good programming practice. 
https://github.com/HGustavs/LenaSYS/wiki/Database-file-upload#4-fetching-files

**Comment by c21sebar** [comment]
I might have made a duplication of this issue and splitting it up into two parts. https://github.com/HGustavs/LenaSYS/issues/13439 https://github.com/HGustavs/LenaSYS/issues/13348

**Comment by c21sebar** [comment]
This is to add the files to the MySQL database so we can use them in other functions and inside of LenaSYS
The issue https://github.com/HGustavs/LenaSYS/issues/13439 connects the files to the SQLite db
