### ISSUE TITLE
Change state diagram state icon

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13389]
The state diagram state currently reuses the IE icon due to them matching, but we want them to be distinct from each other.

Update the state diagram state icon to have rounded corners.

Left is IE icon and Right is State icon
![changestatedigaramstateicon](https://user-images.githubusercontent.com/102599332/233027753-236cc78b-939c-43ce-bcfe-a2ee7899b2bc.PNG)

**Comment by b21matfi** [comment]
do you want me to create a new svg file or use the same just with rounded corners?

**Comment by c21adano** [comment]
Its upto you, do whatever you feel like would be easier.

**Comment by b21matfi** [comment]
Okey, Thank you
