### ISSUE TITLE
Write tests for services in diagramservice

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13397]
Go through the code, focusing on services, and write tests that traverses all paths in the code.
A step by step text file containing what actions to perform and evaluate the tests.

You should do thorough research of the logs, testing out different actions and what values are sent, if logging in or not changes behaviour. The models and functional requirements may also be applicable.

Follow the template in the README under `backend-models/service-tests/README.md`

See the process of work done in issue #13343!!!

Ignore "Retrieve Information"

**Comment by b21kurar** [comment]
This maybe should be done at a later time, depending on the work of other groups. Confirm before starting this.

**Comment by a19hakja** [comment]
This file seems broken somehow, While input can be seen, there is no response coming from it >:(

input:
![image](https://user-images.githubusercontent.com/83954156/236795095-3a734ee1-fb5c-4f89-baaf-a64d597812ee.png)

output(?):
![image](https://user-images.githubusercontent.com/83954156/236795204-b22d2158-632a-4ac8-b9e9-32caf0b041fc.png)

**Comment by a19hakja** [comment]
The same problem can be replicated on https://cms.webug.se/LenaSYS/DuggaSys/diagram.php aswell, so this seems to be a problem merged since last week

**Comment by c21alest** [comment]
@a19hakja is this error solved? Can you continue with this issue?
