### ISSUE TITLE
Write tests for services in codeviewerService

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13392]
Go through the code, focusing on services, and write tests that traverses all paths in the code.
A step by step text file containing what actions to perform and evaluate the tests.

You should do thorough research of the logs, testing out different actions and what values are sent, if logging in or not changes behaviour. The models and functional requirements may also be applicable.

Follow the template in the README under `backend-models/service-tests/README.md`

See the process of work done in issue #13343!!!

Ignore "Retrieve Information"

**Comment by b21ricni** [comment]
Will not be able to produce any visible work by the end of the day, but getting a grasp of what we need to do and note. hopefully will come somewhere by the end of the day

**Comment by b21ricni** [comment]
For the first time since the beginning of dawn, i finally made progress!

**Comment by b21ricni** [comment]
So far as i understand, It fetches data from codeexempel where example id matches the chosen id, it updates templateid in codeexempel. It also updates data in box, it inserts, delete data in impwordlist.

So i assume this file is for editing the created templates for when creating new code exempels, havnt found where you can change them tho

**Comment by b21ricni** [comment]
i did something :)
********************
*Update templateid:*
********************
Templateid have eleven ids[0,1,2,3,4,5,6,7,8,9,10], need to do test for each to check that they all work

//Prints out so we know starting value
SELECT exampleid, templateid FROM codeexample;

//Update, test if templates work
UPDATE codeexample SET templateid = (Number you wanna test) where exampleid = (exampleId of testsubject);

//Prints out so we can see if update was successfull
SELECT exampleid, templateid FROM codeexample;

**Comment by b21ricni** [comment]
If example name is changed in MySql it stays the same in the menu where you can select the codexample, but when you enter the code example you can see the changed name on top, the menu file have a visual name stored elsewhere

**Comment by b21ricni** [comment]
It also seems we can create and store example codes that are hidden to anyone, might be a bug

**Comment by d21erisu** [comment]
Regarding insertions into tables, counting the number of objects in table before insert, doing insert and then doing a count again can't test if the insert was successful.

**Comment by b21ricni** [comment]
We following a temporarily structure so we can get through the code a bit faster, seems to work for now but need to confirm with leader if its an acceptable structure

**Comment by d21erisu** [comment]
> We following a temporarily structure so we can get through the code a bit faster, seems to work for now but need to confirm with leader if its an acceptable structure

It has come to our attention that the template might not be "correct" and that we will change the structure which is why we are following our own.

**Comment by b21ricni** [comment]
So the uppers have decided to change what they ask for in the tests. So we are back to square one, but at least we know the code by head so it should be at least a little bit less painful, worst case we'll end up chain-smoking outside the library

**Comment by d21erisu** [comment]
> So the uppers have decided to change what they ask for in the tests. So we are back to square one, but at least we know the code by head so it should be at least a little bit less painful, worst case we'll end up chain-smoking outside the library

The porgress we have made so far might be useful to some extent. It needs rework to fit the template.

**Comment by b21ricni** [comment]
The creators of the code has successfully made it a pain to be able to get the json data for editcontent and edittitle, top 10 "i wanna cry" moments :)

**Comment by d21erisu** [comment]
> Is there nothing to be found in the response in the browser inspector?

as soon as we press save it refreshes the page thus updating and losing the content in the browser inspector.

**Comment by b21ricni** [comment]
We'll try to find a solution tomorrow, nothing we tried have worked so far. Worst case scenario we'll need to run a program that downloads the json

**Comment by b21ricni** [comment]
So we have three possible solutions. Wireshark, https://www.tassos.gr/joomla-extensions/convert-forms/docs/how-to-automatically-save-each-submission-to-a-json-file, or potentially removing the refresh function temporarily

**Comment by d21erisu** [comment]
We are trying to use wireshark, unclear if it will work as intended

**Comment by b21ricni** [comment]
Its soon been an issue we stared at for over a week with minimal progress, feels bad man

**Comment by d21erisu** [comment]
> We are trying to use wireshark, unclear if it will work as intended

wireshark did not work

**Comment by b21ricni** [comment]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/102578233/234576013-a4d2b816-4d4a-4a13-858c-e472d8190b5a.png">

So no files are found anymore after merge?

**Comment by b21ricni** [comment]
Added delay on reload and all the problems just disappeared

**Comment by d21erisu** [comment]
![image](https://user-images.githubusercontent.com/102599162/234581177-6f3e30ff-2c86-453d-ba84-5a02c0f8a4bd.png)


by changing set timeout to a higher value, we have time enough to retrieve the json data

**Comment by b21ricni** [comment]
Reminder to set setTimeout("location.reload()", 500); again, currently on 10000

**Comment by b21ricni** [comment]
New issue, in codeexample, you cant target the change text 99% of the time to change it. And when we can target it you can't save by pressing enter, you also can't save it that way, the value turns null

<img width="464" alt="image" src="https://user-images.githubusercontent.com/102578233/234598187-1a71bec8-7cc1-46f1-acde-fffd97777959.png">

**Comment by d21erisu** [comment]
We tried to re-install Lenasys since the other group has made some changes. However nothing changed for the better, it actually got worse.

**Comment by b21ricni** [comment]
Thinking of adding a "onkeypress" function

**Comment by b21ricni** [comment]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/102578233/234606786-5356ca18-854c-4aed-a66e-0877d959f0f9.png">
This is pain in a bottle

**Comment by b21ricni** [comment]
Not sure how to test codeexampleservice.php row: 373 - 385, its the function to display information in the drop down

**Comment by b21ricni** [comment]
After having a conversation with JP about what is missing and what not in the document we reach the conclusion that we might need to add mySQL code as well to double check that the data works. Conveniently thats the first thing we did so we just need to merge the documents in a nice and clean way.

there might be an issue with { (checklogin = true) 
&& (hasAccess($userid, $courseId, 'w') || hasAccess($userid, $courseId, 'st')) == true} give $writeAccess="w";, else $writeAccess="s";
but neither have a clue how to fix it, we'll come back to it when document is done and do one final check to see that its okay

**Comment by a19hakja** [comment]
We're currently working on a testAPI which purpose is to implement functionality that bypasses these conditions. This should things easier for testing in general. @c21alest I believe is currently working on this API and may have more relevant information.

We also recently installed something called php curl, which is supposed to make it easier to test stuff. Once again @c21alest is probably your guy to talk to this about.

**Comment by b21ricni** [comment]
If the testAPI is currently under development, should we put the creation of the documentation on hold or should we try to install php curl and contact  @c21alest about how to continue the testing?

**Comment by d21erisu** [comment]
> If the testAPI is currently under development, should we put the creation of the documentation on hold or should we try to install php curl and contact @c21alest about how to continue the testing?

We could convert the document we have now to txt so that it at least is available in the group branch and accessible through github. At the moment only a few have access to the document. We can make the unfinished version available for everyone.

**Comment by b21ricni** [comment]
Roses are red, violets are blue, we can't continue without an answer or two

**Comment by d21erisu** [comment]
> Roses are red, violets are blue, we can't continue without an answer or two

It has come to our attention that it's specified in the issue description that part "Retrieve information" shall be ignored. So now we can complete it :)
