### ISSUE TITLE
Write tests for services in accessedservice

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13393]
Go through the code, focusing on services, and write tests that traverses all paths in the code.
A step by step text file containing what actions to perform and evaluate the tests.

You should do thorough research of the logs, testing out different actions and what values are sent, if logging in or not changes behaviour. The models and functional requirements may also be applicable.

Follow the template in the README under `backend-models/service-tests/README.md`

You should see the process of work done in issue #13343!!!

**Comment by a20fanma** [comment]
I have spent time on this issue, and I have made some progress. I have studied the issue #13343, how to write the tests, and I found out it is difficult to follow the template. Should I write the tests, where I describe what the tests needs to perform or should I describe and give same examples how to implement the tests? So far, I have only described the tests and what data is used/needed.

**Comment by c21alest** [comment]
Old PR: #13551
