### ISSUE TITLE
Create svg for state icon

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13405]
Related: #13389
Create an svg file for state diagram state icon, it currently uses the IE icon but need its own distinct icon.

The state diagram state has rounded corners and the svg icon should reflect that. 

![233027753-236cc78b-939c-43ce-bcfe-a2ee7899b2bc](https://user-images.githubusercontent.com/102599332/233063978-8a8f82f2-e0aa-48d3-aa67-f141ea7f8582.png)

**Comment by b21oscpe** [comment]
This issue is no longer needed as it was solved in another issue
