### ISSUE TITLE
Site icon and better site title

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#1343]
I would be nice with a site icon (the icon on the tab in the web browser the codeviewer is open in) and a proper site title (right now the title is "Result Editor"). Perhaps the title should always be the title of the code example currently viewed in the codeviewer.
![1](https://cloud.githubusercontent.com/assets/11722176/7512708/14763bc8-f4af-11e4-9184-07b5d8c70510.png)

**Comment by c12jenek** [comment]
The title is change in pull request #1344 to Code Editor v5, hope that an okay name!

**Comment by f12danjo** [comment]
Fixed by [#1671](https://github.com/HGustavs/LenaSYS/pull/1671).
