### ISSUE TITLE
Cleanup of code and functions in FetchGithubRepo.php

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13447]
Seems unnecessary to have 3 functions for this. Split up to make each one work seperatly or combine them into one. 

```php
 function getNewCourseGitHub($githubURL)
    {
        getGitHubURL($githubURL);
    }


    function getGitHubURL($url)
    {
        $urlParts = explode('/', $url);
        // In normal GitHub Repo URL:s, the username is the third object separated by a slash
        $username = $urlParts[3];
        // In normal GitHub Repo URL:s, the repo is the fourth object separated by a slash
        $repository = $urlParts[4];
        // Translates the parts broken out of $url into the correct URL syntax for an API-URL 
        $translatedURL = 'https://api.github.com/repos/'.$username.'/'.$repository.'/contents/';
        bfs($translatedURL, $repository);
    }


    function bfs($url, $repository)
    {
```

Combine everything into bfs OR make the function getNewCourseGitHub run bfs and make the getGitHubURL function return $translatedURL and use that function as input parameter in bfs. Do we ever run BFS without the explode function? Do we want the explode function as a separate function or can we bake it all into bfs?
If we keep the functions at least change name to explodeURL or splitGithubURL or something more relevant so there is easier to know what the difference is from getNewCourseGitHub getGitHubURL  .

**Comment by c21sebar** [comment]
https://github.com/HGustavs/LenaSYS/issues/13542

**Comment by a21rammo** [comment]
While cleaning up the code, make sure that naming convention for folder, files and function are easy to understand and clean.

**Comment by e21krida** [comment]
@a21rammo Anything in particular you have in mind? I was thinking about renaming the folder "recursivetesting" to something more proper, anything else?

**Comment by a21rammo** [comment]
Sry for late answer, but yeah the folder was one of the things i had in my mind.

**Comment by e21krida** [comment]
@a21rammo No worries, i decided not to after discussion with @c21sebar since this can potentially cause massive merge-conflicts, this will have to be done at a later date. I'll close this issue since the PR was merged in correctly.
