### ISSUE TITLE
Code example - Update database with the new relevant files that are fetched

### ISSUE THREAD

**Issue by a21rammo** [HGustavs/LenaSYS#13451]
You have the freedom to do whatever you want with databases in sqlite aslong as you can solve how code-example should be refreshed.

**Comment by c21sebar** [comment]
See https://github.com/HGustavs/LenaSYS/issues/13439 and https://github.com/HGustavs/LenaSYS/issues/13348 for more information on how the files are linked with SQlite and MySQL

**Comment by b21sebgr** [comment]
this is solved by fetchgithubfile function
