### ISSUE TITLE
The refresh button on moment type needs a URL to function

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13456]
For issue:
- https://github.com/HGustavs/LenaSYS/issues/13431

From issue :
- https://github.com/HGustavs/LenaSYS/issues/13450

Save the info to db which directory is chosen in the dropdownlist, so other functions know where to look.

**Comment by RaymondSWE** [comment]
This issue is to store the users selected option (for example, a specific folder) so that when the "refresh" button is clicked, only the chosen folder or file gets downloaded or updated.
