### ISSUE TITLE
Refresh in moment - Refreshbutton for moment

### ISSUE THREAD

**Issue by a21rammo** [HGustavs/LenaSYS#13452]
Create a refreshbutton for moment, reuse the icon that is used for code example.

The icon:
![image](https://user-images.githubusercontent.com/102600501/233332977-96c04d3b-41b3-4226-8567-36e90fce3366.png)

**Comment by RaymondSWE** [comment]
its done and merged.

**Comment by a21rammo** [comment]
its merged now
