### ISSUE TITLE
Create a dropdown list to choose a folder to refresh/update/download based on the metadata from the course-GitHub link 

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13450]
For issue https://github.com/HGustavs/LenaSYS/issues/13431
Create a dropdown list to choose a folder to refresh/update/download based on the metadata from the course-GitHub link

**Comment by d21emijo** [comment]
![image](https://user-images.githubusercontent.com/102797583/234008591-7aeca3a6-f948-4751-bffe-59635d23c129.png)
make insert before test

**Comment by d21emijo** [comment]
![image](https://user-images.githubusercontent.com/102797583/234015518-809e99b1-55ef-4f36-905b-e43f53ea7d59.png)

only use the directorys like examples, from "repoFileType" in the "gitRepos" table

**Comment by d21emijo** [comment]
## way to get data in to the db
![image](https://user-images.githubusercontent.com/102797583/234594184-0a6a98ad-a117-4579-a48e-d78d586af536.png)
When creating a course and using a github link,  the data will be saved on the sqlite db in the table "gitFiles"

## the data will be saved in the "gitFiles" tables
```
CREATE TABLE gitFiles (
                cid INTEGER,
                fileName VARCHAR(50),
    fileType VARCHAR(50),
                fileURL VARCHAR(255),
    downloadURL VARCHAR(255),
    fileSHA VARCHAR(255),
    filePath VARCHAR(255),
                PRIMARY KEY (cid, fileName)
        );
```
here we want to use the "fileName" to display all the diffrent options, but only show the options where "fileType" is the "dir" type,
![image](https://user-images.githubusercontent.com/102797583/234596153-5dc2f317-e3f9-44c3-82dc-6787ef568bd5.png)

**Comment by d21emijo** [comment]
### TODO
+ the dropdown currently doesnt do anything and has no option value
```
                    foreach($rows as $row){
                    echo "<option value=''>" .$row['fileName']. "</option>";
                    }
```
+ The table gitFiles can't use the same names as the cid and filename together makes the primary key

**Comment by d21emijo** [comment]
# Test
1. Get data into the sqliteDB by creating a course or by doing an insert
2. the gitHub moments screen will have the dropdown for that course will fetch all the directorys and print them out as option
![image](https://user-images.githubusercontent.com/102797583/235114838-36afbc52-9d3c-4735-a70f-55db31b6aa7e.png)
3. ( This week (v4) all cid is hardcoded as =1 when  creating a course, this means that the dropdown only will show options for course 1, which is the webbprogrammering course all other courses wont show anything. 
![image](https://user-images.githubusercontent.com/102797583/235116810-2ee41e49-fd4d-473b-af3a-7a031e106b4f.png)
to test this on another course one the make an insert into the sqlite db like :
```
insert into gitFiles values (4 , "test" , "dir" , "blabla" , "bla" , "a", "g");
```
one way to se the course id is in the url
![image](https://user-images.githubusercontent.com/102797583/235118393-ce6e3ad1-83ef-44ad-a826-1721259af2af.png)

)
