### ISSUE TITLE
Code Viewer: Resizing of the boxes should be saved

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1346]
When a user resizing the boxes of code or text should be saved for just that user. Like if the user visit the page again, the page should look the way that the user changed it to be.

**Comment by b12alela** [comment]
This is already done for one computer use, where the changes the user makes to the width and height of the codeboxes are saved in localStorage. 

To expand on this you could instead store the information about this in the database for users that are logged in, then later ovveride the localstorage properties with the database ones.

This would provide a truly seamless experience going from computer to computer.

**Comment by a14didda** [comment]
After looking into this we´ve come to a conclusion that this will take too long time to do this type of change this early. a14ponse and I will get back to this later once the database is cleaner and more manageable.
