### ISSUE TITLE
Arrow should be filled

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13461]
According to the notation for state diagrams the arrow should be filled, which means it should be completely white in darkmode. Rather than "transparent" or black and outlined.

![5f1e6b68e6f21c399bd698a7c613d2d1](https://user-images.githubusercontent.com/102578165/233339488-28f7393c-b977-4ec8-8e4d-59bb911a0b29.png)

**Comment by c21adano** [comment]
I think the state diagarm reuses the the black arrow from the other diagarms changing it may affect them. so i propose another solution, in darkmode the state diagrams switch from the black triangle arrow to the white triangle arrow.
