### ISSUE TITLE
Create a visual representation for the metadata

### ISSUE THREAD

**Issue by a21rammo** [HGustavs/LenaSYS#13475]
Working on githubrepository, seperate file to able work parallel
Issue created from a discussion we had as a group

**Comment by c21sebar** [comment]
Create a visual representation for the metadata, this has already been created before but we want to separate it from the php file to another file so that the php file contains only php.

**Comment by e21krida** [comment]
I'll work on it but locally for now, to avoid merge errors, branch with the file and update at hand will come after merging of another issue

**Comment by e21krida** [comment]
I will take the time at hand to enlighten @a21lukpo on how the script works for future development and his help in breaking out the visual representation.

**Comment by e21krida** [comment]
Closed after completion.
