### ISSUE TITLE
The line still goes under the final state if you zoom

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13487]
Before zooming out:
![dc12b124486c62aafc56fe86766e40c0](https://user-images.githubusercontent.com/102578165/233587314-3d82ced4-a573-419e-a0c1-1ea61f30943a.png)
After zooming out:
![435f535b70a4f51afae74a5fc993cda9](https://user-images.githubusercontent.com/102578165/233587320-2855fa2b-16b7-4901-940c-bfd2b6b0e9f8.png)

This issue is related to #13472

**Comment by b21oscpe** [comment]
This issue seems to occur when you try to drag the line vertically, and connect it to any element
https://user-images.githubusercontent.com/102578165/233587789-ceeb5acb-989a-4c1e-bad0-738392dc7fd1.mp4

**Comment by b21eriho** [comment]
Uhm, I branched and couldn't recreate the issue, however I could on the stable-site, so I pulled to the stable folder in the server and now I can't replicate it on the stable site either. Conclusion; someone else has just fixed this issue.

**Comment by b21oscpe** [comment]
Perhaps, it was merged 1 hour ago, and i created the issue after the merge

**Comment by b21eriho** [comment]
My theory is that that merge wasn't pulled to the stable site until I did however, can you recreate the issue now?
