### ISSUE TITLE
Does changeLineProperties in diagram.js store anything to the state machine?

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13498]
In diagram.js there is a todo comment about changeLineProperties not storing anything to the state machine, confirm the validity of the comment by investigating if changeLineProperties truly doesnt store anything in the state machine.

**Comment by a21aldsa** [comment]
It definitely saves everything to the state machine, every change it does, or might do; it saves in the state machine. Correctly too, i might add. This issue can be closed and the comment in the code has been deleted. 

Although I found some slightly confusing code in there:
`// Check if this element exists
    if (!!document.getElementById('propertyCardinality')){

        // Change line - cardinality
        var cardinalityInputValue = document.getElementById('propertyCardinality').value;

        if (line.cardinality != undefined && cardinalityInputValue == ""){
            delete line.cardinality;
            stateMachine.save(StateChangeFactory.ElementAttributesChanged(contextLine[0].id, { cardinality: undefined }), StateChange.ChangeTypes.ELEMENT_ATTRIBUTE_CHANGED);
        } else if (line.cardinality != cardinalityInputValue && cardinalityInputValue != ""){
            line.cardinality = cardinalityInputValue;
            stateMachine.save(StateChangeFactory.ElementAttributesChanged(contextLine[0].id, { cardinality: cardinalityInputValue }), StateChange.ChangeTypes.ELEMENT_ATTRIBUTE_CHANGED);
        }
    }`
 
This does not need the `!!` and why does it check that line.cardinality is not null and is == to "". This makes little sense, I believe they wanted to write "is not null or is == "". Also on the else if, it does not need the check for if it is empty.

This is completely unrelated to this issue though, but it is worthy of note.
