### ISSUE TITLE
Investigate getlines ToDo comment in diagram.js

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13497]
There is a comment next to the getLines function, investigate if the comment makes any reasonable sense.

![getlines](https://user-images.githubusercontent.com/102599332/233625695-e2952b26-690f-4351-9325-c1fc44784e2e.PNG)

**Comment by a21aldsa** [comment]
After doing some digging around I have concluded that the comment has a point. The function returning a readily available variable makes it rather useless, and to strengthen that; the function is only called once. Should I rework this function to return a specific line via a parameter or should I remove this function and change the one place where its called to just use the variable straight up?

**Comment by c21adano** [comment]
I think the rework could be healthy for the system, we already had a similar rework a couple of weeks ago regarding the colour check that done every constantly.

A rework will make the code easier to understand and work with.
