### ISSUE TITLE
Replace UMLLineIcons text with actual icons for the dropdown

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13496]
When selecting icons on a line all of them appear as text, change the text to an image of the icon instead.
Forexample change the "Arrow" text to the "Arrow" icon.

I personally dont know how hard this issue will be. So start with the UMLLineIcons "Arrow" icon and report back if multple smaller issues should be made out of this issue.

**Comment by c21adano** [comment]
I assumed the svg's used in the program could be reused, is this assumption wrong?

Are new icon images needed?

**Comment by c21adano** [comment]
You are allowed to change all the text to icons if you deemed it easy.

**Comment by b21matfi** [comment]
But there are no icons for every drop down

**Comment by b21matfi** [comment]
i could only find arrow.svg

**Comment by c21adano** [comment]
I understand now, seem i had a bit of misunderstanding regarding your report. In the issue it said to start with the arrow, right now its more about laying the ground work for future improvement, even if the arrow.svg is bad, use it as a place holder. The main goal for this issue was to try and get icons into the dropdown.

Im unsure if you can have text and icons in the same dropdown or of the dropdown has to be remade to support it.

**Comment by c21adano** [comment]
This issue can also wait until the needed svg's are made.

**Comment by c21adano** [comment]
This issue will be put on hold until a custom dropdown has been made that support svg icons.

The dropdown is currently not top priority, issue#13529 which is creating the svg icons will contiue for use in the future.
