### ISSUE TITLE
Border improvements

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13519]
Some colour have hard to see borders, this is due to them being lighter colours and giving them a white border in darkmode makes it hard to see were the upper and lower parts split.
![hardtoseeborder](https://user-images.githubusercontent.com/102599332/233937448-0431231e-848d-4c39-87a2-0d82ce5a7599.PNG)

Here are the colour i think need a switch to black borders in darkmode.
![makeborderblack](https://user-images.githubusercontent.com/102599332/233937422-ced67df9-590b-4173-991c-1935c9f8e0bd.PNG)

**Comment by a21aldsa** [comment]
In that case I would like to be removed from this issue as I see no way forward.

**Comment by c21adano** [comment]
That is fine by me, tell @b21oscpe that you would like a new issue instead.
