### ISSUE TITLE
Make icons for dropdown

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13529]
Related: #13496 
We want to replace the text in the icons dropdown with svg's that show the icon instead.

Make a svg version of every UMLLineIcons icon.

**Comment by c21theti** [comment]
![image](https://user-images.githubusercontent.com/102578329/234258299-00a94706-1608-48ff-8702-b13c288676e3.png)
![image](https://user-images.githubusercontent.com/102578329/234258342-d6dab05b-8d0d-4f10-90d5-cb79181c2748.png)
Which arrow looks best?

**Comment by c21adano** [comment]
the lower one is clear and displays an arrow better.

**Comment by c21theti** [comment]
![Arrow](https://user-images.githubusercontent.com/102578329/234264748-655ac5e0-0a24-41de-ac99-420a7daea465.svg)
![Black_Diamond](https://user-images.githubusercontent.com/102578329/234264750-f26f192c-6979-4504-8c74-7dd52022529a.svg)
![Black_Triangle](https://user-images.githubusercontent.com/102578329/234264751-900b75c5-2b64-4cbb-8cc4-9be5b6c4dbfe.svg)
![Triangle](https://user-images.githubusercontent.com/102578329/234264752-ff302058-16a6-43b3-9f59-c18f6387c32d.svg)
![Triangle_Small](https://user-images.githubusercontent.com/102578329/234264753-a43dd545-80ef-456c-ab98-9f8f07f47ad3.svg)
![White_Diamond](https://user-images.githubusercontent.com/102578329/234264755-aa3b8a93-0b8d-46c6-bc83-c450cdbc29f7.svg)
![White_Diamond_Small](https://user-images.githubusercontent.com/102578329/234264757-c84e34a0-3dee-479d-9aad-67b6d05fc472.svg)
I have made two versions of the white diamond and the triangle with different border sizes, the small ones have smaller borders.

**Comment by c21adano** [comment]
Looks good to me, they will be added to the system files later and a wait a future use.
