### ISSUE TITLE
Make a new notation for how state diagrams work

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13527]
This notation lacks in some aspects. For example it doesn't mention how the "Operation" state is handled, we need support for operations. Multi-choice arrows should be surrounded by [ ]. Some arrows don't have labels. Etc.

This is our current notation:
![image](https://user-images.githubusercontent.com/102578165/233968994-d2a64d41-8bfb-4d8e-99e3-0a71172015d4.png)
As well as:
![229782546-789fd7ac-c161-441e-b465-e968961fd4d8](https://user-images.githubusercontent.com/102578165/233969116-a655b523-05e1-4505-ab1b-c633e4e19dc9.svg)

**Comment by b21eriho** [comment]
![image](https://user-images.githubusercontent.com/129077727/234006145-00f58a71-9fd7-40a2-93f2-55284e4270c7.png)
Here are a first draft on my purposed changes, based on my non-perfect understanding of state diagrams, open for comments

**Comment by b21oscpe** [comment]
This looks good but I still want it to support operative states, for example the "Operation" state needs support to be modelled further. See examples from the book (Sommersville)

**Comment by b21eriho** [comment]
![image](https://user-images.githubusercontent.com/129077727/234021282-54a414f7-5ac1-4528-83ef-211fcebe5034.png)
Slight rework

**Comment by b21eriho** [comment]
@b21oscpe I would quite like your opinions on this before I reformat my drafts into a final updated notation

**Comment by b21oscpe** [comment]
This looks good, however, the way that the "timer" lines kink don't neccessarily correlate with how we've planned lines should work. Lines should be able to go diagonally if needed/possible. This goes for the Half and Full power options as well

**Comment by b21eriho** [comment]
![image](https://user-images.githubusercontent.com/129077727/234229031-5a9e7023-bf60-46b2-ab4a-3bf8f598acc7.png)
Is this better, or should the same lines as in the old notation be kinked/straight?

**Comment by b21oscpe** [comment]
Looks good, need to hear from @c21adano as group leader that this is ok aswell before i close the issue
