### ISSUE TITLE
Find bugs/unwanted behaviour for state diagrams

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13531]
Find bugs or unwanted behaviour for state diagrams and report them as a comment to this issue

**Comment by b21matfi** [comment]
There is an issue where you can not draw two lines on the State diagram, you should be able to draw two lines in the state diagram from the same spot

**Comment by b21matfi** [comment]
![image](https://user-images.githubusercontent.com/102650424/234003062-b0a8e24d-4d14-42df-bd91-21de7a18183e.png)
If State diagram is selected and you place one and then right click and move it afterwards, it breaks it and starts placing ghosts around and an arrow is allways there

**Comment by b21matfi** [comment]
black dots are ghosts

**Comment by b21matfi** [comment]
![image](https://user-images.githubusercontent.com/102650424/234006357-2fe4dadc-b2d0-4080-9b84-a0b5659d897b.png)
![image](https://user-images.githubusercontent.com/102650424/234006669-a6611666-fbd0-462b-be1b-4568f4989523.png)
if a line connected to the bottom of the State diagram its not connected to the diagram

**Comment by b21matfi** [comment]
or created from the bottom

**Comment by b21matfi** [comment]
![image](https://user-images.githubusercontent.com/102650424/234018605-6fa0bb24-679a-4954-9a0f-5d725baea1b6.png)
if state is the color black The name does not change to white

**Comment by b21matfi** [comment]
if the state is locked the arrow is not near the diagram at alla 
![image](https://user-images.githubusercontent.com/102650424/234019142-51714c3a-7aa9-406c-835d-9645c2344b6f.png)

**Comment by b21matfi** [comment]
not working, but is it an feature in State to have double lines? 
![image](https://user-images.githubusercontent.com/102650424/234019641-179cb3c3-b295-4c19-99ef-31e3866cf88b.png)

**Comment by b21matfi** [comment]
no lock icon on the uml finalstate 
![image](https://user-images.githubusercontent.com/102650424/234020188-65d28372-9ef4-4757-ac00-df7da89cd3d0.png)
