### ISSUE TITLE
Minimal model for Sequence Diagram

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13535]
Related: #13521 & #12922
Make a minimal model with the notation that we aim to support, and also publish this here in this issue and also as part of the repository (standardized image format such as svg or png)

**Comment by a21aldsa** [comment]
[sequenceDiagram.pdf](https://github.com/HGustavs/LenaSYS/files/11319965/sequenceDiagram.pdf)

![sequenceDiagram](https://user-images.githubusercontent.com/102581306/234208114-4b3def50-2590-4c4f-ba57-0d6e8e629e2f.png)

[sequenceKey.pdf](https://github.com/HGustavs/LenaSYS/files/11319968/sequenceKey.pdf)

![sequenceDiagramKey](https://user-images.githubusercontent.com/102581306/234208163-bdf80fcd-4d1e-4518-a087-23b12419a2a1.png)
