### ISSUE TITLE
Roadmap: - Automatically create the code-examples from the downloaded files

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13547]
"Code examples should automatically be added to the courses by linking to a folder to a part of a course." From https://github.com/HGustavs/LenaSYS/issues/12926

# TODO
## adding

* - [x] Code examples should automatically be created and named after the files in the folder 
#13549
* - [x] Moments should automatically be created and named after the directories in the github folder 
#13690 
 
## previewed : 
* - [ ] Control the order of the code-examples, txt file that controls order and "tabs", order is redone when refreshed
https://github.com/HGustavs/LenaSYS/issues/13017 
* - [ ] If a .md with the same name as the code example exists this will be used as the description of that code example
https://github.com/HGustavs/LenaSYS/issues/13016
* - [x] if we have a preview html or preview png this should be shown as the preview content.
https://github.com/HGustavs/LenaSYS/issues/13698
## Changing :
* - [x] Uppdatering från repot ska inte förstöra eller ta bort manuellt gjorda exempel och filer
https://github.com/HGustavs/LenaSYS/issues/13703
* - [ ] When code is updated to the folder in the repository the examples should be added/removed/updated accordingly based on file names etc, If code-example goes to 2 from 3 or from 3 to 2 files aswell.

Other course-modules
* We want support for other non-course-module example collections such as the curated example set in "complete examples" in 
* Currently assignment texts are stored in lenasys as files we want the same kind of github integration as we have for the code examples.
https://dugga.iit.his.se/DuggaSys/sectioned.php?courseid=7&coursename=Webbprogrammering&coursevers=82518

**Comment by b21sebgr** [comment]
https://github.com/HGustavs/LenaSYS/issues/13549
