### ISSUE TITLE
New database - update/fix queries for new db

### ISSUE THREAD

**Issue by a21rammo** [HGustavs/LenaSYS#13542]
This issue is to fix queries and insertions for the new database table to ensure it's fully functional before merging it into the weekly branch. This is to help prevent disruptions for other team members and ensures a smooth integration of the new database tables. Once the queries and insertions have been updated and tested, we will merge this issue/branch back into the weekly branch.

Post from an previous Pull Request: 
https://github.com/HGustavs/LenaSYS/pull/13468#issuecomment-1520105603

**Comment by a21rammo** [comment]
new branch that you can work from: https://github.com/HGustavs/LenaSYS/tree/g3-2023-v3-fix-queries-for-new-db

**Comment by e21krida** [comment]
Closed after completion.
