### ISSUE TITLE
Investigate why showduggaservice.php crashes

### ISSUE THREAD

**Issue by a19hakja** [HGustavs/LenaSYS#13548]
Showduggaservice crashes when loading pages

Why?

**Comment by b21antbr** [comment]
This is investigated simultaneously as issue#13401

**Comment by b21antbr** [comment]
We were unable to work out why this happens and will focus on other issues for the time being.

**Comment by b21ricni** [comment]
I looked through a few as Toddler, and can access duggas, what user did you use and what  duggas could you not access?

**Comment by b21ricni** [comment]
This issue might have been fixed already cuz it does not crash for me. But might just be lucky
