### ISSUE TITLE
Confirm or change file services for Github implementation 

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#13573]
Because of how files are references through the system one has to confirm that files in the github folder can be reached where file services are located. 

Continuation of #13512
Roadmap #13429

**Comment by HGustavs** [comment]
I think file storage can be simplified.
At the very least we only need to support  something that works similarly to version local storage

**Comment by a21olljo** [comment]
@HGustavs We do at the moment treat the files from Github as course local and stores them in a github folder in the course specific folder, similarly to how the version specifik is stored in a version folder in the course specifik folder. But because we give them the same kind (3) as course local, the files from github is treated as such. 
Meaning that we can only use one instance of Github for each course, which cant be viewed by other courses. 
Is this acceptable and a good solution for the file structure?
https://cms.webug.se/root/G3/students/a21olljo/LenaSYS/courses/1/ (where to view this file structure)

Where this ties in to this issue is with the pathing of files, following that the system only looks in the course specific folder and cant traverse in to the Github folder. We need to make sure that the system can identify when to look in course specific and when to look in Github.

**Comment by a21olljo** [comment]
Concerning the file filereceive_preview.php which is a mess with conflicting documentation which dosent correspond with the actual code. I found that the last referens to it where removed along with the commit "Fnörk" in 2018. 
https://github.com/HGustavs/LenaSYS/commit/9957b2dfb5af3645ff5dfe752f7d4e0f46fc7da0?diff=unified
Can I remove this file and save future students time, and why was the form removed here?

**Comment by HGustavs** [comment]
Im thinking that we in the future can use the github markdown preview for files on github but that we still may need a preview-supporting editor for old files that are not yet on github.
