### ISSUE TITLE
Problem showing courses in teacherview.php

### ISSUE THREAD

**Issue by c13marme** [HGustavs/LenaSYS#1357]
There is a problem how the course results for a student in teacherview.php when there is many courses that has been done by the student.

**Comment by a13ottne** [comment]
possible to make the course bar field scrollable?

**Comment by f13marhe** [comment]
The CSS code needs an overall reconstruction and need to be rewritten. Not enough time to fix this issue before the last merge.

**Comment by a13ottne** [comment]
Ok, closing this issue then
