### ISSUE TITLE
Create a button for super-states

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13589]
Create a button for state diagram super-states according to the notation created by #13527

**Comment by a21aldsa** [comment]
Is this just the button or am I expected to have it actually work and allow the user to create super states?

**Comment by c21adano** [comment]
Just the button for now, the super-state will have alot of unique behaviour and will take a while to make.

**Comment by HGustavs** [comment]
For the reason of documentation, can we make some kind of screenshot or some other type of notation that can show how this interface would look.

**Comment by a21aldsa** [comment]
The menu looks like this now that the superstate button is added: 
![image](https://user-images.githubusercontent.com/102581306/234793640-69e4176b-34aa-4522-b9d2-636b26aff14b.png)

**Comment by b21oscpe** [comment]
I'm not sure that it is intuitive enough, unless there is some instruction telling us to stretch the element until it becomes a superstate, perhaps the tooltip of the state button?

Yes, there are properties that differ from the regular state, as you can see the regular state has a line that cuts through it and the text is not enclosed within a small container in the same way a superstate is
![234019587-2aa57c2b-2b3a-40be-a381-e086fc60c11d](https://user-images.githubusercontent.com/102578165/234834190-a955df7c-f5ff-4199-a443-dd6c974bf561.png)

hiding a feature like that to only those who already know about superstates and are creative enough to try to coax this tool into that functionality seems like a way to have a lot of the users never try this feature

Regardless, in my opinion, any functionality that needs a manual should be avoided even though this functionality seems to have been implemented for lucidcharts.

Decision is up to @c21adano

**Comment by c21adano** [comment]
The button will be placed in a pop out with state start and stop, the pop out will hold all extra state functions.
