### ISSUE TITLE
log.php timestamp issue in serviceLogEntries

### ISSUE THREAD

**Issue by b21kurar** [HGustavs/LenaSYS#13585]
![image](https://user-images.githubusercontent.com/129070844/234539433-fbae9e34-b77f-40c6-8130-c07f7429416b.png)
Timestamp is shown as Unix timestamp in serviceLogEntries

Change it to match the other timestamps (YYYY-MM-DD HH:MM:SS):
![image](https://user-images.githubusercontent.com/129070844/234539685-6ef06e01-fef9-47ef-8362-ba3f7b7891a0.png)

**Comment by HGustavs** [comment]
Is this a display issue or a data storage issue?

**Comment by b21kurar** [comment]
> Is this a display issue or a data storage issue?

Both, kind of. It is saved as an integer in the SQLite database, it still contains the right date, so a simple solution is to fix the presentation. 
![image](https://user-images.githubusercontent.com/129070844/235080713-a84b2871-2fc2-43d0-a46c-5aa10a23aba4.png)

I don't know if there is any other dependency with how the data is stored.

**Comment by a21jeaha** [comment]
@c21alest from what i can see this issue seems to be solved, and should probably be closed. 
![image](https://user-images.githubusercontent.com/102600391/236123203-2808ec57-6759-4391-b3f3-74f6b949d5df.png)

**Comment by d21erisu** [comment]
This issue seems to be resolved so i will close it.
