### ISSUE TITLE
Remove double line option from state diagram lines

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13588]
There is an option on state diagram line to change the line kind to be double, but this doesnt work for state diagram lines.
![doubleline](https://user-images.githubusercontent.com/102599332/234541517-22bb4fe3-4ef5-4bc8-8943-326a0a9cf280.PNG)

**Comment by b21matfi** [comment]
Should i remove all the options? or only the double? ¨

**Comment by c21adano** [comment]
Remove all option is fine, removing double would only leave the normal kind anyway so it may be better to just remove all options.
