### ISSUE TITLE
Create button for "lifeline" according to #13577

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13581]
See #13577

**Comment by b21eriho** [comment]
I am assuming that "lifeline" is the same as what is labeled "lifetime" in the notation? Further should I just add the button or should I also design the image. If the image should be added are there any opinions on how it should look?

**Comment by b21eriho** [comment]
![image](https://user-images.githubusercontent.com/129077727/234575703-86ce572f-a738-4565-b896-83017f7112ff.png)
So not the lifetime? Also by image I mean the icon that is shown in the toolbar.

**Comment by b21oscpe** [comment]
Oh I see, apologise for late answer, I would suggest it would be a "person"-like figure to resemble an "actor"
