### ISSUE TITLE
Remove type drop down from state start and end elements

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13587]
The state start and stop elements currently have a dropdown to change diagram type on them, the dropdown does nothing and should be hidden/removed.
![typedropdown](https://user-images.githubusercontent.com/102599332/234540884-3a43b193-d09f-4727-b1de-3605dce1cd3b.PNG)

**Comment by c21theti** [comment]
Looks like it's hard coded and it's not possible to remove only the dropdown without affecting anything

**Comment by c21adano** [comment]
This issue will be closed for now then. Remaking the code is not necessary right now.

**Comment by c21theti** [comment]
The state start- and stop dropdown uses the same code as the "properties" dropdown for state diagrams
