### ISSUE TITLE
Corners of state diagram entities need to be more rounded to fit the notation

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13592]
Current state diagram
![sd](https://user-images.githubusercontent.com/102578165/234578122-d99e81bb-8681-4522-aa21-006708c4673b.png)

Notation
![sd_notation](https://user-images.githubusercontent.com/102578165/234578148-7421d785-413e-4fea-a686-514c7819ce07.png)

**Comment by HGustavs** [comment]
Perhaps we can leave this as a setting in the settings pane?

Depending on the scale of the diagram and the scale of the symbols one might want larger or smaller rounding.
