### ISSUE TITLE
When deleting a course we do not delete all the connected things to the course

### ISSUE THREAD

**Issue by c21sebar** [HGustavs/LenaSYS#13597]
Add fucntionality to delete entries in the SQLite database when deleting a course. The files on the webserver and related MySQL entries may already be deleted when doing this but check to make sure that they are. Deleting a course should delete everything connected to it.

**Comment by HGustavs** [comment]
This seems ***very*** dangerous.

What about pressing delete course button on accident is all content removed then?

I am thinking that delete mostly should be possible only if the course is more or less empty (if one for example pressed create course by accident).
