### ISSUE TITLE
Make new pop out for state start, stop and super-state

### ISSUE THREAD

**Issue by c21adano** [HGustavs/LenaSYS#13607]
There exist three state element that fill upp the left side menu, make them into a pop out similar to how the entity pop out looks/works
![newpopout](https://user-images.githubusercontent.com/102599332/234795483-b8c81f9f-98bc-4661-97dd-f2d398f04c71.PNG)

![popout](https://user-images.githubusercontent.com/102599332/234796069-73d7b349-1153-4c38-aeef-4dd08345e5b4.PNG)

**Comment by HGustavs** [comment]
Looks fine

**Comment by c21adano** [comment]
Changing the final state can become its own issue.

**Comment by a21aldsa** [comment]
I had to give up on this issue. Here are my findings:

It seems that for each permutation of a dropdown menu, this needs to be reflected in diagram.php. Then this is later controlled by switching classes on and off via togglePlacementType in diagram.js and somehow this makes things hidden with css?

I strongly believe the current method for dropdowns needs to be reworked, this is pure chaos.

**Comment by b21eriho** [comment]
This issue has been moved to issue #13708
