### ISSUE TITLE
dropdown and textfield incorrect in darkmode

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13606]
Dropdown and textfield "Name" are black when they should be white. 

![4c53fb3be9061db978b14070c0a0c9d2](https://user-images.githubusercontent.com/102578165/234795482-faa46bd4-4071-4c9c-b8af-9b6bc0acf34d.png)

**Comment by HGustavs** [comment]
Is there a dark mode version of the orange background there?

To my eyes it looks too bright when the text areas are black?
