### ISSUE TITLE
Lifetime button needs functionality

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13612]
Lifetime button is the "person"

![cf720433eeb9eba172bc07b7d6828c53](https://user-images.githubusercontent.com/102578165/234825019-b073c1b8-c985-489e-9b63-f9a56fe5fa3e.png)

The button should place a lifetime according to the #13535 notation

**Comment by HGustavs** [comment]
Are we reaching a level where there are too many buttons?

Can we group symbols in some way?

Perhaps start and end points can be grouped under the same button?

**Comment by b21eriho** [comment]
This has been remade into issue #13684 but the groupings of buttons will be kept in mind
