### ISSUE TITLE
Reintroduce the output that shows the path of testcases

### ISSUE THREAD

**Issue by b21oscpe** [HGustavs/LenaSYS#13614]
a linear path from start to stop should be outputted going through each state:

Ex.
Start -> state1 -> state2 -> final

you may keep the counters

![3f89ec7e97df8b7147d7c076e59b9cb9](https://user-images.githubusercontent.com/102578165/234826350-11c3902a-5fa9-4a7e-b09f-c58a922443f7.png)

**Comment by c21adano** [comment]
This is related to issue#13437 and the last comment on issue#13555. Start with single pathed diagrams for now, then muli paths will become an issue later on.

**Comment by a21nibah** [comment]
this issue appears to be resolved. The outputs are correctly printed out. At least when i tested creating an alert to see.




Assigned #13614<https://github.com/HGustavs/LenaSYS/issues/13614> to @a21nibah<https://github.com/a21nibah>.

**Comment by b21oscpe** [comment]
The output does not appear in the output window for the options tab

**Comment by a21nibah** [comment]
Does the er output appear as it should?  The options pane is not accessible for me. Something might have gotten messed up during a merge.

**Comment by d21matbo** [comment]
A UML Initial State is required for the path to be displayed, if no such entity exists it is not possible to know where to start the path

**Comment by a21nibah** [comment]
is this issue considered to be complete?
