### ISSUE TITLE
Removal of faulty error message when creating a new course with a course code already in use

### ISSUE THREAD

**Issue by e21krida** [HGustavs/LenaSYS#13621]
![imagebug](https://user-images.githubusercontent.com/102578849/234848643-a42f89fc-8190-4c74-a805-c975345ef693.png)

Currently, when creating a new course with a course code that is already in use, you're presented with an error message stating that "xxxxxx is already in use. Choose another." This error message is fine, but the error message doesn't disappear after a new correct course code has been inputted instead. Given that the text-field gains a red background on incorrect syntax which disappears after the correct syntax has been inputted, the same principle should go with this error message.

**Comment by HGustavs** [comment]
This is an important issue

**Comment by e21krida** [comment]
@HGustavs Working on it now!

**Comment by e21krida** [comment]
Closing this issue as my solution has been merged in via https://github.com/HGustavs/LenaSYS/pull/13630
