### ISSUE TITLE
Add strings to the $info variable in codeviewerservice

### ISSUE THREAD

**Issue by a19hakja** [HGustavs/LenaSYS#13629]
This file needed a modification

**Comment by HGustavs** [comment]
Can we write a little more details, so we have documentation of what this issue is intended to do.

**Comment by a19hakja** [comment]
Ah yes, sorry about that. The developer notified me that there were strings missing for the $info variable in codeviewerService.php and that it needed to be fixed. This is just a completion of this issue: https://github.com/HGustavs/LenaSYS/issues/13491
