### ISSUE TITLE
Changing the "Inheritance"-property to "overlapping" on "IE inheritance" crashes the system

### ISSUE THREAD

**Issue by d21matbo** [HGustavs/LenaSYS#13644]
When the **SAVE** button is pressed after swapping from "disjoint" to "overlapping" the system becomes unresponsive

![image](https://user-images.githubusercontent.com/102599161/235627173-8017b103-e621-4f03-a527-7314dd27242d.png)

The console throws errors that could be provide insight in how to fix this issue

**Comment by a21nibah** [comment]
is there a diagram i can use  to test this?
