### ISSUE TITLE
Add missing content to FRD_contribution_loginbox_service

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#13651]
Related to: https://github.com/HGustavs/LenaSYS/issues/13642

Identify and add missing content to FRD file: FRD_contribution_loginbox_service

**Comment by d21erisu** [comment]
b21tilbe is busy so c21axepe will take over this issue

**Comment by c21alest** [comment]
It is unclear how contribution_loginbox_service works, so this issue is paused for now.

**Comment by b21tilbe** [comment]
So I should wait with this?

**Comment by c21axepe** [comment]
Yes
