### ISSUE TITLE
Guide on how to use Test API

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#13681]
Write PDF or something similar to document how to use the test API.

More information about test API can be found here: #13631, #13532 and #13679

----------------------------------------------------------
## Example on how to run this test from another file:

include_once "../Shared/test.php";

$testData = array(
    'value1' => 'test',
    'value2' => 'test',
    'service' => 'https://cms.webug.se/root/G2/students/c21alest/LenaSYS/DuggaSys/courseedservice.php',
    'serviceData' => serialize(array( // Data that service needs to execute function
        'opt' => 'NEW',
        'username' => 'usr',
        'password' => 'pass',
    )),
    'test1Debug' => false, // If true more information of test will be displayed
    'test2Debug' => true,
    'test3Debug' => true,
);

testHandler($testData, false); // 2nd argument true = prettyprint (HTML) false = raw JSON, no debug mode is avalible when using prettyprint

----------------------------------------------------------

**Comment by a21jeaha** [comment]
@d21erisu @c21alest do we as of this moment have a dedicated test database?
i have to have something to test against which guaranties the same results every time.

**Comment by c21alest** [comment]
> @d21erisu i presume these are suppose to be JSON data? ![image](https://user-images.githubusercontent.com/102600391/236180575-d9ec20f0-3e58-40ea-88f4-50ed5112eac0.png)
> 
> if that is the case, is this JSON string suppose to have been altered beforehand so that time related data receive another value? otherwise the comparison will always fail if any time related values are present. because these values will always be different.

I dont quite understand what you mean. value1 and value2 are used by the assert test to check if these values are equal to each other. This test might need some changes depending on how this test will be used, which is unclear so far. Maybe value2 should be generated by the test to do the assert with the origin value1 and the changed value2.

**Comment by c21alest** [comment]
> @d21erisu @c21alest do we as of this moment have a dedicated test database? i have to have something to test against which guaranties the same results every time.
> 
> edit: i see now that there exist a database with the name test. before i use something that might be for something completely different, i need to make sure that this is the database we are to use?

There is no dedicated database so far, during testing we have used our own personal databases but you are free to create a new one to be used for testing.

**Comment by d21erisu** [comment]
> @d21erisu @c21alest do we as of this moment have a dedicated test database? i have to have something to test against which guaranties the same results every time.
> 
> edit: i see now that there exist a database with the name test. before i use something that might be for something completely different, i need to make sure that this is the database we are to use?

Yes that needs to be confirmed. 

> > @d21erisu @c21alest do we as of this moment have a dedicated test database? i have to have something to test against which guaranties the same results every time.
> > edit: i see now that there exist a database with the name test. before i use something that might be for something completely different, i need to make sure that this is the database we are to use?
> 
> There is no dedicated database so far, during testing we have used our own personal databases but you are free to create a new one to be used for testing.

I know that the old management talket about having a "clone" dedicated to this, not sure if they made one or not.

**Comment by c21alest** [comment]
Tests won't work correct until #13679 is solved. The problem is that userid SESSION won't work with the API so a manual adjustment is needed in the service file to be tested. This manual change needed can be read here: #13679 might be a good ide to include this in the guide.

**Comment by c21alest** [comment]
![Test API](https://user-images.githubusercontent.com/102578850/236433176-de62d451-41de-4336-988d-68a343d71b2d.png)
