### ISSUE TITLE
Add a pop-out for final-, initial- and super-state

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#13708]
The buttons for super-state, uml-final-state and uml-initial-state should function as a pop-out like there is now for entities and relations. The button to be selected when first booting the system should be the initial state.

**Comment by c21adano** [comment]
This issue is the same as #13607

**Comment by c21adano** [comment]
I will wait a bit with starting this issue, pull request #13721 and this issue will have conflicts if i were to start right away. It would be safer to wait until #13721 is merged.

**Comment by c21adano** [comment]
![popoutplacement](https://user-images.githubusercontent.com/102599332/236455998-b658befa-fb96-47cb-9582-8ce8d8eea34d.PNG)

Where on the menu should the pop out be placed? Its currently under the other elements, should i move it to be further up?
