### ISSUE TITLE
Check if TODO is fullfilled for the function "updateSelection"

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#13711]
```
/**
 * @description Updates the current selection of elements depending on what buttons are down. Context array may have the new element added or removed from the context array, have the context array replaced with only the new element or simply have the array emptied.
 * @param {Object} ctxelement Element that has was clicked or null. A null value will DESELECT all elements, emptying the entire context array.
 */
function updateSelection(ctxelement) **// TODO : Default null value since we use it for deselection?**
{
(...)
}
```

There's a old TODO in the code. Check if the default value checks out with the todo. 

If default value is NULL, remove TODO comment.

If not, make sure to add default NULL values from those functions who uses the ```updateSelection``` function.

**Comment by b21matfi** [comment]
When selecting an element it shows the element when not selecting anything it comes out as null 
![image](https://user-images.githubusercontent.com/102650424/235935424-3c5568f1-6f9b-4079-a138-5625fe4908af.png)
