### ISSUE TITLE
Document a general overview of diagram.js

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#13733]
There is a wiki for this repo, available here: 
![image](https://user-images.githubusercontent.com/129077727/236130822-309dd217-1926-44b9-83ec-1fa4a4eca564.png)
A general overview of or beloved 12000 lines of js-code would probably be nice for the next batch of students to take this course. Add a page there with a very general overview of diagram.js. 

Containing information such as sectioning the code into 200-600-ish-line segments. You do not need to show the code simply something along the lines of "lines 420-690:" followed by descriptions of roughly what is going on in each segment if that is possible. Make it clear on that page when you are writing it so that we can later tell when last it was updated.

**Comment by b21eriho** [comment]
After Discussion with teacher this should instead be done by documenting the function names in the file and a brief description of what the function does as well as how it relates to other functions such as if it's used in another function and if it uses other functions. If there are tens of refrences only mention the most relevant and that there are others

**Comment by a21aldsa** [comment]
I had to give up on this issue but for the next person, here is what I managed to write: 

[docs_for_diagram_js.md](https://github.com/HGustavs/LenaSYS/files/11420854/docs_for_diagram_js.md)

**Comment by a22hanfa** [comment]
Now the whole Diagram.js should be documented. There should be nothing missed. This is documented on the old version as in week one, so the changes made since then will need to be updated in this document. 

Please, take a look: [Document](https://github.com/HGustavs/LenaSYS/wiki/Documentation-of-Diagram.js)
