### ISSUE TITLE
Document the function "getVariantParam()"

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#13736]
## Goal
In ```diagram.php``` there's a function called ```getVariantParam()```. Find out what the code does, what it outputs and create a block comment with description and return value.

Ex:
```
/**
* @description This code does bla bla bla
* @return [variable] What variable contains.
*/
function getVariantParam()
{...}
```

**Comment by b21matfi** [comment]
It looks like it does not have any use at all for the moment. It is used in the function fetchDiagramFileContentOnLoad(), this function is called when you reset the diagram button, but it has no fuction for now, the function getVariantParm() does not return any value for now and causes an error. the fetchDiagramFidleContentOnLoad() was used when there was hardcoded diagram in v1. 
![image](https://user-images.githubusercontent.com/102650424/236164908-9e523c9c-c99d-4855-b13d-0aa24093ac0e.png)
![image](https://user-images.githubusercontent.com/102650424/236165397-c8e8abe6-9b10-40d3-b705-3acc0ad94cf0.png)
i will comment out getVariantParam() and fetchDiagramFileContentOnLoad() to see if something on the diagram changes

**Comment by b21matfi** [comment]
I have commented out the function getVariantParam() and also the code that uses it because it only caused console errors and had no other use execpt for when the whole diagram was hardcoded in v1.
