### ISSUE TITLE
Update class diagram Model filereceive service #12970.svg to include input data in methods

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#13746]
Update with input data and add methods to service:

* [backend-models/Model filereceive service #12970.svg](https://github.com/HGustavs/LenaSYS/blob/44f973e4d27a94e1a23932e941dd1501dc3868ce/backend-models/Model%20filereceive%20service%20%2312970.svg)

Related to: #13743

**Comment by b21ricni** [comment]
Filereceive service does not exist
