### ISSUE TITLE
Change showDuggaservice-test.txt to MD and add expected output

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#13791]
Related to: #13788

[backend-models/service-tests/showDuggaservice-test.txt](https://github.com/HGustavs/LenaSYS/blob/44f973e4d27a94e1a23932e941dd1501dc3868ce/backend-models/service-tests/showDuggaservice-test.txt)

**Comment by a21ponkr** [comment]
I am using https://cms.webug.se/root/G2/students/a21ponkr/LenaSYS/DuggaSys/showDuggaservice.php for the service output part in .md which should be correct since others have done the same

**Comment by a21ponkr** [comment]
I am not looking at showDuggaservice.php file in vscode for the outputs, i am only looking at showDuggaservice-tests.txt and the website
