### ISSUE TITLE
Use duggasys file uploader to upload files

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1382]
The files used by the codeviewer e.g code examples and descriptions, should be uploaded with the file uploader used by duggasys.

**Comment by HGustavs** [comment]
This is a duplicate of issue #1177 (there is one more duplicate of this issue with the same code quote that I am unable to find at the moment....).

It is a question of using the filename stored in the dialog using the showdoc code.

This way it should work automatically.

**Comment by a13jorla** [comment]
See also #1008.

**Comment by b12simsa** [comment]
ok
