### ISSUE TITLE
Removing functionality to edit downloaded GitHub files 

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#13821]
Files downloaded through github shouldn't be able to be modified or deleted, the only way a github-file should be changed or deleted, is through github. 
So remove the buttons and hinder the functionality of the buttons marked below, similarly of how one cant edit certain files for instance json.
![remove edit option](https://user-images.githubusercontent.com/102599614/236779125-b2d61848-9cb9-45b7-af35-d93e1a5888f8.png)

**Comment by HGustavs** [comment]
Perhaps a octo-cat icon to indicate that a file is a github file.

No editing pencil and no trashcan for github files, but some other icons such as an octocat miniature icon.

I have also added this as a separate issue for the sake of documentation

**Comment by e21krida** [comment]
Closed after solving
