### ISSUE TITLE
Implement test file for accessedservice.php

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#13848]
Related to: #13847

You can found a guide on how to use this API [here](https://github.com/HGustavs/LenaSYS/blob/cdb827478334ec6099763471afd3e0c16ade1332/Shared/Documentation/Test%20API/Guide%20on%20how%20to%20use%20Test%20API.md).

**Comment by a20fanma** [comment]
I could not finish this issue. The accessedservice will not provide any outputs and it will instead display a server error.

**Comment by c22emigr** [comment]
Continued work on local repository as merge is on wednesday. First test should be completed

**Comment by a22eriwi** [comment]
Continued working on the testfile. Tried to create an sql query that saves a variable for the array input. Merge is on wednesday so we cant do any new commits now because we have to remove the branch tomorrow.

**Comment by c22emigr** [comment]
test file is close to being done. Trying to figure out how to insert data from a query into variables in array.

**Comment by c22emigr** [comment]
After researching it seems like we cant follow the test model file as you cant write SQL-queries in php arrays. Continuing research for other solution

**Comment by c22emigr** [comment]
tests that arent using cid (courseid) now works. Working on fixing SQL-queries selecting cid for the rest of the tests

**Comment by c22emigr** [comment]
Researching what parts of lenasys sends the values and attributes we are testing to find out what i should have as the expected output of the test.

**Comment by c22emigr** [comment]
Cannot get expected outputs for reset password as that feature on lenasys doesnt work. Password reset in lenasys - webbutveckling & datorgrafik - login - forgot password.

**Comment by c22emigr** [comment]
Test file is almost done. Putting it on hold as we cant seem to find all the expected outputs on Lenasys as they might not yet be implemented. So we cant test them yet
