### ISSUE TITLE
Documentation - Create a reference guide for how we want to document in the Wiki

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#13868]
The Github Integration consists of individual components working in unison, we want each part to be documented to then be easier understod and utilized in the future, but also how these components cooperates and works together to complete the Github Integration.
The idea is then to document this in the wiki under the "Github Integration" tab, and this issue should present a reference guide or structure for how this could be done.

**Comment by c21rebja** [comment]
This template can be found on the start page (under the code tab), same place as the README file.
The file is named github_integration_doc_template.md.

co-author @g21emmka

**Comment by c21rebja** [comment]
Could we get someone to look at this before closing the issue? :) 
@a21olljo 

/ @g21emmka & @c21rebja

**Comment by a21olljo** [comment]
Talked to @a21hugni who has done documentation before and he would look at it. 
I have also looked over the template and it looks good.

**Comment by a21hugni** [comment]
I have looked over the template and the body text on the wiki. I don't have anything to complain about.
