### ISSUE TITLE
Remove refresh button from code examples

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#13863]
After conversation with costumer, it was decided that the refresh button present for each code example was unnecessary. 
To be removed are the frontend and backend. But be carful with backend because it can share some functionallity with other refresh functionalities.  
https://github.com/HGustavs/LenaSYS/issues/13428#issuecomment-1536206018  
![Remove refresh 1](https://user-images.githubusercontent.com/102599614/236842263-bfa32e4e-8eda-439c-8380-381a83401529.png)
![Remove refresh 2](https://user-images.githubusercontent.com/102599614/236842261-145e7886-1209-488a-a53f-965ba9d8525c.png)

**Comment by HGustavs** [comment]
The button should appear on for example Javascript examples

Commonly one does more than one update at a time, so we want to refresh the whole example set in order to only retrieve the information once from github.

This way if we make more than one edit we only refresh once (removing repeat checks on github).

**Comment by e21krida** [comment]
> The button should appear on for example Javascript examples
> 
> Commonly one does more than one update at a time, so we want to refresh the whole example set in order to only retrieve the information once from github.
> 
> This way if we make more than one edit we only refresh once (removing repeat checks on github).

Please elaborate further! Do you want the button to remain there for manually added files, as in non-github files? Or do you want it to be removed overall? Or simply removed on all non-javascript files?

**Comment by a21olljo** [comment]
This is a communication error I'm going to bring up during the group meeting on wednesday, where it at some point been mixed-up what a section and what a moment is. In the issue above, section is used to contain the examples, "Javascript Examples", "HTML5 Examples" and "Shader Examples" are all sections. But what we done earlier in the project is assumed that only moments could hold examples, which it sometimes does https://dugga.iit.his.se/DuggaSys/sectioned.php?courseid=7&coursename=Webbprogrammering&coursevers=82518. This is something that has to be corrected and implemented for sections as well. 

But refreshing each and every code example still shouldn't be possible.
