### ISSUE TITLE
File editing view of github files

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#13873]
We want an icon to indicate clearly that a file is a github file in the file editor view.

Perhaps a octo-cat icon to indicate that a file is a github file.

No editing pencil and no trashcan for github files, but some other icons such as an octocat miniature icon.

**Comment by a21olljo** [comment]
> We want an icon to indicate clearly that a file is a github file in the file editor view.

> Perhaps a octo-cat icon to indicate that a file is a github file.

We have already implemented an extra column specifying that a file is a github file, along with the ability to filter between github and manual. Is this a good solution?
![image](https://user-images.githubusercontent.com/102599614/237034974-28492a13-22fa-4ed3-9cae-00f39c1ddba4.png)

> No editing pencil and no trashcan for github files, but some other icons such as an octocat miniature icon.

That is currently being worked on in this issue #13821
