### ISSUE TITLE
Put the JS in diagram.php in seperate file.

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#13874]
## Description
In ``diagram.php``` the head tag is a mess with scripts right now. Create a seperate file for the JS and make sure that the context is not disturbed. 
```
           /**
 * @description returns the value of a query string sent in a URL.
 * @param a key of type string.
 * @returns a string containing the value 
 */
function search(key)
{
    const parameters=new URLSearchParams(window.location.search);
    return parameters.get(key);
} 
        // Fetch variant parameters from server
        var DiagramResponse;
        
      function fetchDiagram() {
            var response;

            let cid=search("courseid");
            const folder=search("folder");
            let did=search("did");
            const id=search("id");
            if(cid=="UNK"&&folder!=null)
                cid=folder;
            else
                cid=1894;
            if(did=="UNK"&&id!=null)
                did=id;
            else
                did=21;

            response = getCourseId(cid, did);

            return response;
        }

        function getCourseId (courseId, did) {
            try {
                let response;
                $.ajax({
                    async: false,
                    method: "GET",
                    url: `diagramservice.php?courseid=${courseId}&did=${did}`,
                    //>>>>>>> g1-2023-v5
                }).done((res) => {
                    console.log(res)
                    response = res;
                })

                return response;
            } catch (error) {
                console.error(error);
            }
        }
        
        /**
         * @description get the contents of a instruction file
         * @param fileName the name of the file t.ex. test.html
         * */
        function getInstructions(fileName)
        {
            const instructions = DiagramResponse.instructions
            if(instructions.length > 0){
                for (let index = 0; index < instructions.length; index++) {
                    if(instructions[index][2]==fileName){
                        window.parent.document.getElementById("assignment_discrb").innerHTML = instructions[index][3];
                    }
                    if(instructions[index][5]==fileName){
                        window.parent.document.getElementById("diagram_instructions").innerHTML = instructions[index][6];
                    }
                }
            }			
        }
```

## Suggestion
Maybe we should make a folder called "assets/js" and put in all the script files in there.

**Comment by HGustavs** [comment]
diagram.php should only contain static html with very few exceptions.

The number of files should be as small as possible in the interest of finding the code as easily as possible.

This is probably related to other historic issues... the javascript code for examples seems to be spread over several files?

If we embed a diagram into a dugga, for an assignment, is this code called there too?

**Comment by b21phiro** [comment]
> diagram.php should only contain static html with very few exceptions.
> 
> The number of files should be as small as possible in the interest of finding the code as easily as possible.
> 
> This is probably related to other historic issues... the javascript code for examples seems to be spread over several files?
> 
> If we embed a diagram into a dugga, for an assignment, is this code called there too? And if so is the call there distinct from this call?
> 
> Could this be the reason for putting this code here?
> 
> I worry that assignments break if this code is moved without testing both with individual diagrams, and with diagrams embedded into assignments.

## My thinking
My thinking is that indeed we could embedd it elseswhere. And to me ``DuggaSys`` folder has way to many files at the moment, where PHP, CSS and JS files are together. We could also include the files whenever we want in different files.

## Suggestion?
I'd like to see more of a structure, where we have an assets folder for example: ``assets/css``, ``assets/js`` etc. However I do understand your worry, maybe before merge we could do some testing do find issues related to code going unexpected?
