### ISSUE TITLE
Clearer visual representation of toggled function in options menu

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#13881]
## Description
In options panel, we attempt to give the user a visual clue what is toggled or not (for example grid). Right now, we give the button a slightly darker purple. This is not clear enough.

Figure 1
![bild](https://user-images.githubusercontent.com/45258330/237047140-87c2641a-2f92-4ebb-bc47-199f510c51c1.png)

## Your job
Give a clearer visual representation of what is toggled.

## Suggestion
Make buttons that is not active filled color, while active are hollow. You can ofcourse come up with some other solution, just make sure the color has enough contrast.

## Tip
If you choose to change the color on different modes, make sure the contrast is large enough.
https://coolors.co/contrast-checker/112a46-acc8e5

**Comment by c21theti** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/102578329/332ab8b8-a71d-4af9-b8e0-3f1559291e5b)
Does this looks good?

**Comment by b21phiro** [comment]
Yes

**Comment by c21theti** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/102578329/4fe26e5a-0c46-4102-b6dd-fae7b4a4fff3)
 or this (with darker purple)

**Comment by b21phiro** [comment]
Looks good to me

**Comment by c21theti** [comment]
yes it is still in development, plan is to finish it today
