### ISSUE TITLE
Fix codeviewerService.svg

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#13891]
codeviewerService.svg is missing some methods and inputs

Wait with this issue until codeviewerService.md is finished

**Comment by c21alest** [comment]
codeviewerService.md is done, green!

**Comment by d21erisu** [comment]
The arrows in the class diagram on codeviewerService.svg needs to be corrected ("1..1" is missing).

**Comment by a22iliru** [comment]
Added group 1 label as the latest comment seems to be related to diagrams.

**Comment by a22jacka** [comment]
Is this really a issue? `1..1` in class diagrams are usually shortened to just `1` since the number is the same anyway

**Comment by a22iliru** [comment]
Youre right. closing this
