### ISSUE TITLE
Research and create design of test-case

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#13917]
Henrik has made it clear that the wanted output of the test-case-generation should be one statement per transition that could feasibly be used by a human in testing of the modeled system. This should take into account entry-conditions. So if a transition between two states has the condition [A] then the outputted statement for that transition should tell a human how to test that the transition is handled correctly in the system behind the model.

Despite this sounding very serious it is not needed to be entirely correct, rather it should convey the idea of model-generated test-cases

**Comment by d21matbo** [comment]
An potential solution to this issue would be to provide the person with a list of value pairs that they should test against the model.
This suggestion is based on state coverage with the goal of making sure that all values provided will lead to an end.

![image](https://github.com/HGustavs/LenaSYS/assets/102599161/622fd071-7439-41f2-8b8c-eced75679eeb)

The image above models a simple addition software that has the guards `[i < 10]` and `[i > 10]`, the system would then provide the person with the numbers `[9, 10, 11]` to test the model with. Of course the models fails when `i=10`.

This does however suffer from "state explosions" as multiple different guards would greatly increase the combinations of values that the person needs to test, and as such this might not be the best solution.

**Comment by b21eriho** [comment]
This has been discussed with Henrik and instead of this we would like a design where for each transition if there is a bracket the test-case that is printed should be such that a person could use it to test that particular transition. It may include instructions to figure out the edge-values for the condition and the like. This because at this point the system cannot know the data-type of a condition variable and therefore it isn't possible to generate the edge-values.

**Comment by d21matbo** [comment]
Ok, so an alternative solution that is more or less an addition to the current `generateStateDiagramInfo()` function, could look like the image below.

![image of the same simple addition model, but with the addition of the testcast window showing the labels/guards present on the transitions](https://github.com/HGustavs/LenaSYS/assets/102599161/3ed2e336-c18f-486a-9c84-77a238a765ab)

This images illustrates the addition of "with guard X" on the current transitions that previously just stated that it did transition. In addition to this, the solution can also show whether it is acually a guard or just a label on the transition by the use of regex.

I believe that this gives the reader a clear view of what they need to test that transition, which is what I understood was requested from the provided feedback

**Comment by b21eriho** [comment]
Looks good. I would like to add that all transitions should show their label on their first printout, so that the part below where the labels are printed separately can be removed.
