### ISSUE TITLE
If a new file is added on github in a folder that is tracked by the synchronization module we want this file to be added automatically to the course view.

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#13934]
When a folder is used to generate code examples, if the folder then gets a new file, that file should be automatically generated where the folder is in use. Should be done along with the refresh button. 
Related to issue: #13931

**Comment by c21sebar** [comment]
We divided the update into three parts:

1. Hide an example when all files are deleted to that codeexample in the github repo.
2. Remove/unlink one or more boxes if one or more file (but not all) are removed from the github repi
3. Add boxes to the codeexample if more files are added to the githubrepo and those files should be added onto an existing code-example.
