### ISSUE TITLE
Buttons in headings when in light mode has the wrong color 

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#13939]
Buttons for headings don't show in light mode
![image](https://github.com/HGustavs/LenaSYS/assets/102599614/d0a08db8-ab05-46aa-a9d3-4b403efd202e)
![image](https://github.com/HGustavs/LenaSYS/assets/102599614/0353b6bf-58c9-49e2-989d-9f12cc736730)
Also investigate if one is suppose to be able to move a headings? Because currently it misses the buttons on the side to drag and drop. 
Might be related to the missing drag and drop, but the text in the heading is not centred in relation to the page or the course header.  
![image](https://github.com/HGustavs/LenaSYS/assets/102599614/fd9474a1-0393-4883-89c7-d13a7944920c)
This is relevant following that in issue #13932 we are suppose to "tie" code examples to headings.

**Comment by b21geoyo** [comment]
Regarding the settings and delete buttons for Heading I added inline styling to make them visible form the purple background.

**See the code examples below. Note that the style inline attribute is only relevant.**

Settings icon:
```
<img style="filter: invert(1);" alt="settings icon" tabindex="0" id="dorf" title="Settings" class="settingIconTab" src="../Shared/icons/Cogwheel.svg">
``` 

Delete icon:
```
<img style="filter: invert(1);" class="traschcanDelItemTab" alt="trashcan icon" tabindex="0" id="dorf" title="Delete item" src="../Shared/icons/Trashcan.svg">
```
---

However for the tabElement button to give it the correct styling you have to use:

```
<input style="filter: invert(1); border:none; background:transparent;" type="button" value="↹" id="tabElement" title="Tab example button" tabindex="0">
```
Note that the tabElement button is not the same size as the other tablElement buttons on other rows, check image below:

![image](https://github.com/HGustavs/LenaSYS/assets/102578996/3459a75d-9888-4b84-a8f1-60de5dfac9b4)

**Comment by a21hugni** [comment]
Worked with @b21geoyo on some of the later commits.
