### ISSUE TITLE
Add favicon's with Högskolan i Skövde's logo

### ISSUE THREAD

**Issue by a13oscwe** [HGustavs/LenaSYS#1393]
If somebody could add favicon's to all the duggasys pages with högskolan i skövde's logo that would be nice.

**Comment by HGustavs** [comment]
No.

We are not allowed to use the official livery for an "external" project.

Instead it must be removed in all places.

**Comment by a13oscwe** [comment]
So no favicon at all? Not even a custom one? @HGustavs

**Comment by HGustavs** [comment]
A favicon is allowed but we are not sanctioned to use the official university livery.
