### ISSUE TITLE
Further work on sequence activation

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#13945]
Make it so that the sequence activation object can be placed on top of sequence lifeline and also make it scalable vertically.

**Comment by b21matfi** [comment]
should you be able to place the object inside on top of the lifeline or is it so that you can drag it

**Comment by b21eriho** [comment]
Ideally it should be placeable on top of the lifeline, does that seem feasible?

**Comment by b21matfi** [comment]
i will try and make it placeable on top of it, but how it was coded it can be hard, but i will try

**Comment by b21eriho** [comment]
Sounds good
