### ISSUE TITLE
Create first MS and template

### ISSUE THREAD

**Issue by d21erisu** [HGustavs/LenaSYS#13955]
Try and start to create and figure out the creation of MicroServices. A template/standard for others to follow later should be created as well. A suggestion is to start with either sectionedservice.php or accessedservice.php.

**Comment by b21ricni** [comment]
Free hands to choose whatever service we want to split in to ms?

**Comment by b21ricni** [comment]
To be able to split everything up i would need to start with making the login service, otherwise i could not test if the other functions are working properly right?

**Comment by b21ricni** [comment]
My take on File structure since the name conventions are still being reviewed:

**Comment by b21ricni** [comment]
If name suggestions go through:
We would need to make a more in-depth structure with folders and naming. (Example below)
A folder for universal code would have to be made as well, like set user rights ect
Example:
Folder: codeViewerService
Files:
- settingCodeexampleTemplate
- editCodeExample
- editContentOfCodeExample
- editBoxTitle
- deleteExample

**Comment by b21ricni** [comment]
If all files where to be set in the same folder:
Name conventions on files would have to change, currently microservice names have variation in the start and if this where to be created it would cause massive confusion for the future developers.
The names would have to have something that define them in the beginning of the name so they would lay in a row, this way the next person could look for a letter and find all the files they need
Example:
- settingCodeexampleTemplate - would be codeViewerTemplateSetting
- editCodeExample - would be codeViewerEditExample
- editContentOfCodeExample - would be codeViewerEditContent
- editBoxTitle - would be codeViewerEditBoxTitle
- deleteExample - would be codeViewerDeleteExample

**Comment by d21erisu** [comment]
The main purpose is to research and make questions appear. As you have. Keep up the work and try to make a "template" so that later when it's time for others to create the microservices they can work as smoothly as possible.

**Comment by d21erisu** [comment]
Regarding your questions I think renaming will be good to avoid. Some sort of map for each service's "unique" MS would be good I think. I’ll think about it and discuss with issue-dude and come back regarding that.

**Comment by b21ricni** [comment]
Services will be split in to several microservices, all fair and square. What will we do with Retrieve information? I am not sure what to do about it, might need to have a smart person to join me throwing ideas back and forth

**Comment by b21ricni** [comment]
Ran in to another issue, since different services askes for different userAccess. Should we make a function in CheckUser status that lets us define user access in the file that is fetching them?

**Comment by c21alest** [comment]
IMPORTANT @b21ricni @b21hamwe the MS you are creating must follow the naming standards in this documentation:
https://github.com/HGustavs/LenaSYS/blob/g2-2023-v7/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md
