### ISSUE TITLE
State without attributes displays incorrectly

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#13961]
![image](https://github.com/HGustavs/LenaSYS/assets/129077727/a2165c85-6287-4556-b6aa-faa8cc767c3d)

If one leaves the attributes tab os an SD state empty it still shows half of the word do: creeping up from below. Find out why the "do:" is there and report what you find so we can decide what to do from there.

**Comment by b21oscpe** [comment]
I found that there was a harcoded "Do:" left in the code that was added after the "empty" textarea. I simply removed the "do:" so that it displays correctly for now

**Comment by b21eriho** [comment]
Sounds good

Den fre 12 maj 2023 12:49b21oscpe ***@***.***> skrev:
