### ISSUE TITLE
Investigate issue with function elementHasLines()

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#13964]
## Description
In the file ``diagram.js`` there's a function called ``elementHasLines()``. It's function is as described ``Triggered on ENTER-key pressed when a property is being edited via the options pane (...)``. However, this function does not work for UML, SD and IE elements.

## Your job
Try to find out why, and make a quick report if we can solve it.

**Comment by b21oscpe** [comment]
Already solved https://github.com/HGustavs/LenaSYS/pull/13948
