### ISSUE TITLE
Research: If the saving of assignments is properly implemented

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#13975]
## Description
Our customer thinks that saving an assignment might be implemented allready, but we are unsure if it actually works. 

## Job
Together with a partner [optional], find out how this works and if it's actually implemented. Write a quick report about it.

**Comment by a19clasv** [comment]
The only way to save at the moment is to export a diagram with or without history by clicking on an empty space, going into options and then clicking on "With history" or "Without history". The saved diagram can then be loaded by choosing the exported file in the options menu and clicking "Load". Loading an exported diagram from a different machine tested by b21eriho to make sure you can share the saved diagram.

**Comment by b21eriho** [comment]
Where is this button, could you send a screenshot?

**Comment by b21eriho** [comment]
Do you mean the one ine diagram.php or another one?

**Comment by b21matfi** [comment]
i mean when you go thru the courseed.php to demo and then diagram dugga

**Comment by b21eriho** [comment]
Right, please send a screenshot of where the button is and the error so we can use it in another issue

**Comment by b21matfi** [comment]
To find the button you first need to go to courseed.php, then pick demo-course and after that you go in to the diagram dugga you should see that the save button is disabled with a class, if you remove the class and then try to use the button you will see that the button does not work and i it will give you the error in the second image 

![image](https://github.com/HGustavs/LenaSYS/assets/102650424/55c4bd6b-9665-4e7a-bfde-ac1f3753feb3)
![image](https://github.com/HGustavs/LenaSYS/assets/102650424/94cacbfb-eacd-4a08-9532-044a4b38732b)

**Comment by b21eriho** [comment]
Thank you, great job

**Comment by a19clasv** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/57549915/e225661c-22b2-4384-9a83-554dfb976c89)
There is also a save button in both showDugga.php and diagram.php. No errors pop up when it's clicked, but it doesn't save either. As I wrote previously, the only way to save is by exporting the diagram. There's a function for saving, but it's not connected to it. The issue Hook up save button with storeDiagramInLocalStorage function #13984 aims to fix that.
