### ISSUE TITLE
The automatic and manual synchronization options should have individual settings for each

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#14002]
From #13880 
This issue is to verify and implement that the synchronization settings for both manual and automatic can be changed by a line at the top of the files. Making it so that one doesn't have to search the code for hardcoded variables, but it should also not be set in the user interface.

**Comment by HGustavs** [comment]
I am talking about two global variables at the top of the php file (or near the top as applicable) one for the maximum time before manual refresh and one for the minimum time for automatic refresh when any user visits the page / example.
