### ISSUE TITLE
Check status on models, test, microservice files and FRDs. 

### ISSUE THREAD

**Issue by d21erisu** [HGustavs/LenaSYS#14013]
Check that the current files that have been tested and merged are up to standard. For example, the files that should be converted to MD are fine. And that the class diagrams look alike and are "correct".

The main purpose is to find the files that are not up to standard so that they can be corrected.

**Comment by a21oscgu** [comment]
Should I look from master or g2-2023-v6? @d21erisu

**Comment by a21oscgu** [comment]
There's a question mark at duggaedservice-test.md, "#Delete variant and useranswer? (line 134)" (LenaSYS/backend-models/service-tests/duggaedservice-test.md). I'm not sure if it's supposed to be like that.
