### ISSUE TITLE
Fix FRD_courseedservice.md

### ISSUE THREAD

**Issue by d21erisu** [HGustavs/LenaSYS#14033]
FRD_courseedservice.md has some header columns that needs to be corrected (for example "F1" should be renmaed to "FR1" and so on).

**Comment by a22fokol** [comment]
all headers has been correctly changed from “F1” to “FR1”, “F2” to “FR2”, and so on. This should make the system more consistent and easier to understand.

**Comment by a22iliru** [comment]
waiting for a22fokol to make a pull request so this can be tested and merged.

**Comment by a22marca** [comment]
Table headers are properly labeled. Good to go!
