### ISSUE TITLE
Should <table class="list"> be so close to the navheader?

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#1404]
![untitled](https://cloud.githubusercontent.com/assets/11715749/7564418/cc294d8e-f7e6-11e4-96ff-e4790366c391.png)

**Comment by a13oscwe** [comment]
Would benefit from some margin IMO.

**Comment by HGustavs** [comment]
Seems like a bug. If done correctly it should never be possible to have a table below the header.

**Comment by c13chrjo** [comment]
Could you explain in more detail what you mean? 
Should no tables exist at all or should it be done in another way?

**Comment by a13alfbe** [comment]
Codeviewer has a similar problem where the navheader overlaps the content by a few pixels.
