### ISSUE TITLE
Remove dropdown that is used to set next and previous code example 

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#14050]
There is a setting page located in each code example, which holds a dropdown used to go between code examples. This was thought in issue #13877 to not be synced to the order found in course list, but it was found out to be. 
The old manual way of chosing the order is now non functional and can be removed (which is this issue). 
![image](https://github.com/HGustavs/LenaSYS/assets/102599614/8af70bf9-b2db-4c2b-a7c0-aa3d66b7b824)
What to be removed
![image](https://github.com/HGustavs/LenaSYS/assets/102599614/8c7703a8-75f9-4ee5-8875-35672e32a98f)

**Comment by a21olljo** [comment]
I wasn't maybe clear enough. The buttons in this picture should remain.
![image](https://github.com/HGustavs/LenaSYS/assets/102599614/c4baed37-90b3-4165-9b6c-20424c81fe78)


What to remove are the dropdowns in this picture. 
![image](https://github.com/HGustavs/LenaSYS/assets/102599614/90eb9da3-2d7f-4a7a-9241-82733618cc50)


But because code only got commented out, it should only be to remove the comments present here. 
https://github.com/HGustavs/LenaSYS/pull/14125/files#diff-480d67f8acb0fada0d2f80ee377e45cbe3fc0cf4d0f470278a5ab7ca1d6ca6d1

**Comment by a21rammo** [comment]
ill fix it my bad missed ur "what to remove".
