### ISSUE TITLE
Name of lifeline elements

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#14059]
As of now the names of lifeline elements look like this
![image](https://github.com/HGustavs/LenaSYS/assets/129077727/abdba2a9-464f-48cc-be17-6997e0fdfbd9)
The name should have a background so that it is doesn't overlap like it does now. Further the default value should be "lifeline"

**Comment by b21eriho** [comment]
I see now how I was unclear. The name of the actor should have a background so that it doesn't overlap. And since we don't and shouldn't change the name of the entity when we swap between object and actor the default name should be lifeline

**Comment by a21aldsa** [comment]
> I see now how I was unclear. The name of the actor should have a background so that it doesn't overlap. And since we don't and shouldn't change the name of the entity when we swap between object and actor the default name should be lifeline

But the name is for the actor and object, no? Like, the name of the actor or object.

**Comment by a21aldsa** [comment]
So the only thing I should do for this issue is add a background for the text for actor?

**Comment by a21aldsa** [comment]
For documentation: Upon discovering a unexpected error related to how names that are too long to fit and consulting with the group leader about this, we came to the conclusion that there are two ways of fixing this, both of which are part of this issue.

Method one would be to use a similar linebreak that, for example, func uses in UML elements. This means that the name would extend onto a new line whenever its too long.

Method two would be to use a similar method as the name for ER entities; simply have the name cut off into nowhere if its too long.

I will first try to implement method one, but if I cannot manage this, method two was also deemed acceptable.
