### ISSUE TITLE
Change the years in studentView to represent the semester instead

### ISSUE THREAD

**Issue by a13erilj** [HGustavs/LenaSYS#1409]
In studentView the courses are represented under a given year (2013, 2014 and 2015). This should be changed to represent the semesters instead. 
For example instead of 2013 it should say HT-12/VT-13 or HT-13/VT-14

**Comment by a13erilj** [comment]
Partially fixed

**Comment by a13ottne** [comment]
Since no data about when courses take place are is present in the database, this is issue will be closed for now
