### ISSUE TITLE
Default name for save

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#14116]
## Job/Description
When saving, you can add a name. However right now there's no default-name, so the user is forced to write something. Come up a solution where there's always a unique-name as a default value for the save. 

### Tip/suggestion
It could be something like "diagram-2023-05-22". 

Figure 1.
![bild](https://github.com/HGustavs/LenaSYS/assets/45258330/6f0463b4-c0aa-408f-87a4-79d8aca7cf69)

**Comment by HGustavs** [comment]
That is easy and works well

**Comment by HGustavs** [comment]
Just make clear that it is a placeholder, and that the user can enter any name

**Comment by b21eriho** [comment]
This will be combined into #14117
