### ISSUE TITLE
Make sequence activation snap to lifeline

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#14112]
It should be possible for the sequence activation to be placed precisely on the center of the lifeline, naturally it shouldn't be stuck there forever but given a close-enough placement it should snap to the horizontal center of a lifeline

**Comment by c21adano** [comment]
It would appear that pr #14097 has messed up the moving system for elements.

This is what i get when i move elements.
![errorors](https://github.com/HGustavs/LenaSYS/assets/102599332/fce357ef-fd04-41bc-a51a-61b71a3dc598)

**Comment by b21eriho** [comment]
Indeed something is strange, does this prevent you from completing this issue?

**Comment by c21adano** [comment]
a bit but not a 100%, im unable to test the ctrl z function and the site seems to slow down a bit after some time. Ill continue looking into the issue for the next day but if i feel like i havent made enough progress then ill consider giving up.

**Comment by b21eriho** [comment]
Sounds very reasonable

**Comment by c21adano** [comment]
I think i have to give up on this issue for now, the errors seem to break the current element position and over time the overlapping function seems to break down and not function any longer. 

This is a image from our stable branch with 5 er elements placed ontop of each other.
![errors](https://github.com/HGustavs/LenaSYS/assets/102599332/32a73880-83cc-498d-84ba-597c8b66c9c9)

**Comment by a23ponek** [comment]
Tried to create a function for the snap between the sequence activation to lifeline but tools like Class for a lifeline/sequence activation was unclear and where the implementation needs to be was also not strictly obvious. 
This code is a start of but needs changes for correct variables/logic:

function snapSAToLifeline() {

    const lifeline = document.getElementById("sequenceActorAndObject");
    if (lifeline) {
        const lifelineRect = lifeline.getBoundingClientRect();
        lifelineCenterX = lifelineRect.left + lifelineRect / 2;

        for (let i = 0; i < data.length; i++ ){


            if (data.kind == "sequenceActivation") {
                const element = data[i];
                const activationCenterX = element.x + (element.width / 2);
                const distanceToCenter = Math.abs(activationCenterX - lifelineCenterX);
                const proximityThreshold = 20;

                if (distanceToCenter < proximityThreshold){
                    const newX = lifelineCenterX - (element.width / 2);
                    element.x = newX;
                }
            }
        }
    }
}

**Comment by b22davbe** [comment]
We (me and a22cazlu) have now implemented so that the sequenceActivation snaps to the lifeline while hoovering over it when the activation is a ghostelement. After a few days of trying we still haven't made it work when the activation is already created but logically you should be able to expand mouseEnterSeq() and snapSAToLifeline() for this to work. However there's probally some other code that interrupt this and we can't figure out what.
