### ISSUE TITLE
Allow use of tab in toolbar

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#14119]
## Description/Job
As of right now you can't use the TAB-key to select modes or items in the diagram. By setting the tab-index on elements (or even better, use sematic tags such as buttons) you can solve that issue. Implement a way to use the tab to navigate through the toolbox.

![bild](https://github.com/HGustavs/LenaSYS/assets/45258330/691a87df-57e9-46fa-8d55-3a34fdfd27a6)

## Tips
Tabindex: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex
Button element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

**Comment by b21phiro** [comment]
## Yes
Indeed, it's concidered bad practice according to many, you can read more about it here:
https://adrianroselli.com/2014/11/dont-use-tabindex-greater-than-0.html

However, having no way of navigating using tab is worse. In our case, we do not have any substantial that a screen-reader could read.

I do agree, that in most cases it's a bad idea. However, in this context the flaws are not as relevent. Howver this is highly subjective.

## Replace with elements
Yes, that's a possible solution as stated, however as you said it brings problems. So, it's easier for now to use tabindex.

**Comment by a21aldsa** [comment]
> ## Yes
> 
> Indeed, it's concidered bad practice according to many, you can read more about it here: https://adrianroselli.com/2014/11/dont-use-tabindex-greater-than-0.html
> 
> However, having no way of navigating using tab is worse. In our case, we do not have any substantial that a screen-reader could read.
> 
> I do agree, that in most cases it's a bad idea. However, in this context the flaws are not as relevent. Howver this is highly subjective.
> ## Replace with elements
> 
> Yes, that's a possible solution as stated, however as you said it brings problems. So, it's easier for now to use tabindex.

A screen reader can already navigate this site fairly well, the issues that arise are not because of the menu: that part works fine. The issues lie in how the options pane is always there just visually hidden. How there is no tooltips on keyboard focus. How there is no way of placing elements without clicking, etc etc etc.

**Comment by b21phiro** [comment]
> > ## Yes
> > Indeed, it's concidered bad practice according to many, you can read more about it here: https://adrianroselli.com/2014/11/dont-use-tabindex-greater-than-0.html
> > However, having no way of navigating using tab is worse. In our case, we do not have any substantial that a screen-reader could read.
> > I do agree, that in most cases it's a bad idea. However, in this context the flaws are not as relevent. Howver this is highly subjective.
> > ## Replace with elements
> > Yes, that's a possible solution as stated, however as you said it brings problems. So, it's easier for now to use tabindex.
> 
> While I agree that a screen reader cannot navigate this site well; the issues that arise are not because of the menu: that part works fine. The issues lie in, for example, how the options pane is always there but just visually hidden, so a screen reader will always read this. Or how there is no tooltips on keyboard focus. Or how there is no way of placing elements without clicking, etc etc etc.

Yes that is an issue itself. This could be solved using some simple CSS, for example ``visabilty`` argument. However that's an issue itself. Tabbing is just convenient, and more of a handy feature rather than a necessity. 

If we in fact can focus on buttons using tab, we could very well make so tooltips can show. However, to implement that we must have a way to actually focus using tab, which is right now impossible. Hence, why that's an issue.

**Comment by a21aldsa** [comment]
For context, see this old PR of mine regarding the accessibility of the menu:

https://github.com/HGustavs/LenaSYS/pull/13506
