### ISSUE TITLE
Better loadscreen

### ISSUE THREAD

**Issue by b21phiro** [HGustavs/LenaSYS#14121]
## Description/Job
When loading up the diagram, there's no indication to the user if the diagram is being loaded or if it's broken. While the diagram is being loaded, there should be a spinner or _something_ that indicates that the diagram is in fact being loaded.

Figure 1.
![bild](https://github.com/HGustavs/LenaSYS/assets/45258330/a510c5c2-017c-48b6-9c62-bfa304a65ae4)

### Tips
- You can simulate slow internet using the browsers devtools on the network tab.
- Make use of eventlisteners: https://javascript.info/onload-ondomcontentloaded

**Comment by HGustavs** [comment]
Spinning wheel like in for example yotube?

**Comment by b21phiro** [comment]
Yeah that would be good! Just something that indicates that it is in fact loading
