### ISSUE TITLE
Remove filtering in dropdown 

### ISSUE THREAD

**Issue by a21olljo** [HGustavs/LenaSYS#14129]
Right now there is a filter to only allow directories with "Example" in the name, when generating code examples.

**Comment by e21krida** [comment]
> Yes we can remove this. The code example folders can be named in any way. We select from all available folders.
> 
> There are not any cases where we have so many folders that it is too much for a normal dropdown.

We have solved this within #14133

**Comment by e21krida** [comment]
closed after completion
