### ISSUE TITLE
Update Potetial_micro_services.md

### ISSUE THREAD

**Issue by d21erisu** [HGustavs/LenaSYS#14132]
Change the name from "Potetial_micro_services.md" to "Potential_micro_services.md"

https://github.com/HGustavs/LenaSYS/blob/master/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md

Check so that the typo isn't anywhere else in the document

**Comment by a21jeaha** [comment]
@c21alest this issue is resolved and need to be closed. 
seems like i have been rather bad at linking issues to PR:s, my bad :(
