### ISSUE TITLE
Create microservice createNewCodeexample

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14154]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#createNewCodeexample)

File: createNewCodeexample_ms.php
Folder: shared_microservices

**Comment by b21kurar** [comment]
Looking through `sectioned.js` shows 12 different calls to `AJAXService` using `kind = "SECTION"`
As such, the AJAX call in `dugga.js` is in charge of many different functions. 

To be able to have a functioning system with just this microservice added, a check will be made in `dugga.js` to check if `opt === "NEW"`. This ensures that the rest of the service will still work. 

```js
else if(kind=="SECTION"){
    if(opt === "NEW"){
       // call microservice
    } else{
    $.ajax({
      url: "sectionedservice.php",
      type: "POST",
      data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
      dataType: "json",
      success: returnedSection
    });
    }
}
```

There should probably be a cleaner solution when the backend is fully in microservice architecture
