### ISSUE TITLE
Create microservice setActiveCourseversion

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14151]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#setactivecourseversion)

File: **setActiveCourseversion_ms.php** 
Folder: **shared_microservices**

**Comment by a22eddpe** [comment]
create a new file named setActiveCourseversion i the folder shared_microservices.

**Comment by a22eddpe** [comment]
<?php
    date_default_timezone_set("Europe/Stockholm");

    // Include basic application services
    include_once "../../../Shared/basic.php";
    include_once "../../../Shared/sessions.php";
    include_once "../shared_microservices/getUid_ms.php";
    include_once "../shared_microservices/updateTableCourse.php"; // Assuming updateTableCourse service is available

    // Connect to database and start session
    pdoConnect();
    session_start();

    // Global variables
    $cid = getOP('cid');
    $versid = getOP('versid');
    $makeActive = getOP('makeActive');

    getUid();

    if ($makeActive == 1) { // Assuming 1 represents the condition for setting a version as active
        // Update the active version using the updateTableCourse service
        $updateData = array(
            'activeversion' => $versid // Data to update
        );
        
        $updateCondition = array(
            'cid' => $cid // Condition to identify the course
        );

        // Call the updateTableCourse service
        $updateResult = updateTableCourse($updateData, $updateCondition);

        if (!$updateResult) {
            $debug = "Error updating entries"; // Handle update failure
        }
    }
?>

**Comment by a22eddpe** [comment]
need to locate the connected files. 
So far I have located "updateCourseVersion_courseed". 
Folders: DuggaSys/microservices/

**Comment by a22eddpe** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/129263688/4c8e4022-a749-4e6f-9821-c766580a77fa)

**Comment by a22eddpe** [comment]
These are scattered in the folder "DyggaSys>courseedservice.php

**Comment by c22emigr** [comment]
Unsure if there is a duplicate issue as a file called setAsActiveCourse_ms already exists in the shared microservices folder with the same functionality.

**Comment by a22eriwi** [comment]
Seems to be a duplicated issue, like c22emigr said the file setAsActiveCourse_ms.php already exists, which does the exact same thing as the file we were supposed to implement.
