### ISSUE TITLE
Create microservice logging

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14150]
Related to: #14143

Read more about the MS [here]( https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#logging)

File: **logging_ms.php**
Folder: **shared_microservices**

**Comment by a22marca** [comment]
The description of the microservice is quite short, "Uses a function in basic.php". There are two functions from basic.php that are used through in the service files. 

The first logs a user event.

```
function logUserEvent($uid, $username, $eventType, $description)
```

The second logs a service event.
```
function logServiceEvent($uuid, $eventType, $service, $userid, $info, $timestamp = null)
```

 For example after creating a new course in `courseedservice.php`, it is logged using this function call:
```
$description = $coursename . " " . $coursecode . " " . $courseGitURL . " " . "Hidden";
logUserEvent($userid, $username, EventTypes::AddCourse, $description);
```

It seems like a good idea to create two seperate microservices, one for logServiceEvent and one for logUserEvent.

**Comment by a22marca** [comment]
logUserEvent, does not really perform any other functionality than creating a query using the parameters of the function and a global variable.

logServiceEvent, uses two other functions `getOs()` and `getBrowser()`, these are implemented in basic.php and needs to be included in the microservice.

**Comment by a22marca** [comment]
I found a comment from the previous year specifying a part of a microservice, that should be made into it's own microservice for logging:
```
// TODO: the following will be changed to a microservice, as such this should be updated to a microservice call

// *********************** vvvv CHANGE TO MICROSERVICE CALL vvvv ***********************************
// Gets username based on uid, USED FOR LOGGING
$query = $pdo->prepare("SELECT username FROM user WHERE uid = :uid");
$query->bindParam(':uid', $userid);
$query->execute();

// This while is only performed if userid was set through getUid(), a guest will not have it's username set, USED FOR LOGGING
while ($row = $query->fetch(PDO::FETCH_ASSOC)) {
    $username = $row['username'];
}
// *********************** ^^^^ CHANGE TO MICROSERVICE CALL ^^^^ ***********************************

```
