### ISSUE TITLE
Create microservice setAsActiveCourse

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14157]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#setAsActiveCourse)

File: setAsActiveCourse_ms.php
Folder: shared_microservices

**Comment by a21oscgu** [comment]
> The JSoN data should display an “opt”, find the opt that has the same name as your function in the microservice.

There's no "opt" and I have no idea why.
![Skärmbild 2023-05-24 110445](https://github.com/HGustavs/LenaSYS/assets/102578829/848faaaf-b16e-4c77-948b-6859f3cf1443)

**Comment by c21alest** [comment]
OPT can be found in payload

<img width="735" alt="Skarmavbild_2023-05-24_kl _11 17 59" src="https://github.com/HGustavs/LenaSYS/assets/102578850/0def1d0e-8745-4c04-ba63-6dc5bdd38fde">
