### ISSUE TITLE
Create microservice createNewCourse

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14160]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#createNewCourse)

File: createNewCourse_ms.php
Folder: courseedService

**Comment by c22mohel** [comment]
Upon further research this issue appears to be almost done. Just testing needs to be done

**Comment by a22iliru** [comment]
please open a pull request for testers

**Comment by c22mohel** [comment]
This is not ready for test

**Comment by a22iliru** [comment]
seems to already be a course called createnewcourse without this issue being closed. so closing it.
