### ISSUE TITLE
Errors when moving unselected elements

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#14169]
When I move objects I get these errors:
![image](https://github.com/HGustavs/LenaSYS/assets/129077727/0e3b93f7-f3b1-404b-83f6-76bcf3e4cdd2)
I have found that they are most reproducible when having the selection tool active and then moving an element by clicking on it and dragging without releasing the button, when this is done and the element is placed moving the mouse will produce the errors that are by the hundreds in the screenshot. After that I have to unselect by clicking the blank area, and then clicking the blank area again (not double-clicking) before it can be reproduced again.

There seem to be a number of different errors going on here, for example the error about the stateMachine I've only gotten once. If you during this issue find that the errors are caused by multiple separate faults and fixing them all would be too much work for this issue, you should only fix the errors that are being spammed hundreds of times.

**Comment by b21matfi** [comment]
this came from something that was merged 
becuase it breaks everything, so just changing the element type can make so the diagram acts strange

**Comment by b21eriho** [comment]
Alright, useful information for the next developer
