### ISSUE TITLE
Cookies and "loginvar" are now redundant.

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1418]
Since we changed both the login and logout functions to reload the whole page we are no longer using the loginvar variable. The cookies are thus redundant.

**Comment by HGustavs** [comment]
I agree.
The cookie was there to remember that you were logged in previously.

It is probably more secure to use the standard browser-built-in password-remembering functionality instead.

**Comment by a15timbe** [comment]
Solved in #3754
