### ISSUE TITLE
Fix $info (row 21) in getUid_ms.php

### ISSUE THREAD

**Issue by b21ricni** [HGustavs/LenaSYS#14183]
It currently do not display any data when used in a echo

**Comment by f22linhe** [comment]
getUid_ms.php
A part of a system that manages user identification and logging of activities. The purpose of the getUid function is to fetch and return the user's unique identifier (UID) based on the session. If no user UID is present in the session, the user is assumed to be a guest and 'guest' is assigned as the UID.

Includes files:
coursesyspw.php, sessions.php, basic.php

What is the issue?
The variable $info displays no data when called by echo.

**Comment by f22linhe** [comment]
Update:
The variables for $info have now been defined, as they were not before. $log_timestamp has been added to the logServiceEvent function, as it was defined but not included earlier.

**Comment by a22iliru** [comment]
unassigned and waiting for tester

**Comment by a22fokol** [comment]
tested and it works
