### ISSUE TITLE
Create microservice updateCourse

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14199]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#updateCourse)

File: ** updateCourse_ms.php**
Folder: **courseedService**

**Comment by a22iliru** [comment]
assigned c22cargo to test

**Comment by a22iliru** [comment]
reassigned b21youab to issue, as the work done was made on an already completed issue
