### ISSUE TITLE
Create microservice newCourseVersion

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14194]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#createCourseVersion)

File: **createCourseVersion_ms.php**
Folder: **courseedService**

**Comment by b21hamwe** [comment]
My code isn't to blame, the code does what it was created to do.
However, this issue, is an issue! Beacuse the code thats written in the service (courseed) is not being used correctly in the system. 
The code is not being used in courseed file, but in sectionedService.php were the same code can be found. 
(ish).

A colleague of mine has experienced a similiar problem, see : 
https://github.com/HGustavs/LenaSYS/issues/14196

OBS!
I tested out my code in the right file instead, and its working where it should be. 
Meaning, this microservice is useless in the position that the issue says it should be in the system.
But when placed where it should be, it's working perfectly.
