### ISSUE TITLE
Create microservice copyCourseVersion

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14198]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#copyCourseVersion)

File: ** copyCourseVersion_ms.php**
Folder: **courseedService**

**Comment by c20juler** [comment]
Create folder for microservice and add it to DuggaSys/microservices. 

Find the monolithic service!!! In the monolithic service find the relevant code block to be converted into the microservice "copyCourseVersion". Convert the code block into the microservice and save the code in a separate file. 

Read and follow the guideline for converting monolithic service to microservice:   
https://github.com/HGustavs/LenaSYS/blob/master/DuggaSys/microservices/monolithic-to-microservices.md 

Other documentation related to microservice copyCourseVersion:
https://github.com/HGustavs/LenaSYS/issues/14143
https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#copyCourseVersion

Look at how other microservices are implemented.

**Comment by c20juler** [comment]
DuggaSys/courseedservice.php (monolithic file) to be split into a number of microservices located in DuggaSys/microservices/courseedService. The file copyCourseVersion_ms.php does not yet exist in DuggaSys/microservices/courseedService which has to be created.

**Comment by c20juler** [comment]
When trying to create a new course version and choosing to "copy content from" previous course version there are multiple errors related to file "navheader.php" located in Shared/navheader.php. Not sure if the problem it is related to this issue though.

**Comment by a22iliru** [comment]
Ok. set on hold until Group 3 fixes navheader.php

**Comment by a22marca** [comment]
It seems [#14580](https://github.com/HGustavs/LenaSYS/issues/14580) regarding navheader.php is not yet resolved. Furthermore, there is something wrong with the input validation of start and end date when creating a course version. The input type is 'date', but the input is validated and requires a format of "HTNN, VTNN or STNN". I'm suggesting this as a new issue to @a22iliru.

**Comment by a22marca** [comment]
The input of dates works when using these fields instead:

![image](https://github.com/HGustavs/LenaSYS/assets/128985931/ff95146b-f83b-48f0-b383-491f2c6c057b)

**Comment by a22marca** [comment]
The issue regarding the input fields still exists (image in previous comment). Furthermore, another group has noticed that the functionality of copying a course version does not seem to exist in the backend. When looking through the code of sectioned.js, there is a opt that can be sent:
```
      // Create a copy of course version
      AJAXService("CPYVRS", param, "COURSE");
```
This request is sent to courseedservice.php, which do in fact handle the "CPYVRS". I'm not sure whether the insertion into the database is implemented correctly however. When trying to copy a course I'm not able to find the request that contains this opt, so I'm also not sure if the request is being sent correctly.

**Comment by a22marca** [comment]
When creating a new course version, the `validateForm()` function receives "newCourseVersion" as a formid. If all information is filled in correctly by the user the function `createVersion()` is called. This function retrieves all the inputted parameter, and it checks if the user wants to copy a currently existing course version or make a new one. It then makes a AJAX call to courseedservice.php, containing "CPYVRS" if a course version should be copied, or "NEWVRS" if it should be a completely new version.

In both of these cases (copying or creating a new), the request is not able to be performed:
![image](https://github.com/HGustavs/LenaSYS/assets/128985931/7876885b-f677-45b7-8c79-d75b2a09c743)

The request itself is aborted with the message NS_BINDING_ABORTED. I believe this might be because the page is being redirected before courseedservice.php is able to execute.

**Comment by a22marca** [comment]
We need to wait for [PR#15066](https://github.com/HGustavs/LenaSYS/pull/15066) which might solve this issue. Putting this issue on-hold.

**Comment by f22linhe** [comment]
Make sure to implement the _retrieveCourseedService_ms.php_ into this microservice when developing it.

**Comment by a22marca** [comment]
I will give this another go now, as the issue mentioned earlier has been fixed and merged.

**Comment by a22marca** [comment]
This issue still persists as of now, the same happens when trying to integrate the microservice:
![image](https://github.com/HGustavs/LenaSYS/assets/128985931/fc95f155-cbaa-45a0-9f5d-8e13113bdc6e)

**Comment by a22marca** [comment]
Copying a version works when setting new version as the default version for the course when using the original service file (courseedservice.php). I will try to make it work with the microservice first, and then we will probably have to wait for a separate issue to resolve the problem when copying a version without setting it as default.

**Comment by a22marca** [comment]
The microservice will not work at all in the current state. The requests to the microservice does not return a response, even if it is a simple echo at the top of the file. Will investigate this further when group 3 has taken another look at the functionality.

**Comment by a22marca** [comment]
I've tried to further deduct where the problem described occurs. When using the microservice instead of courseedservice.php in tha ajax call, the call is throwing an error:
```js
        } else if (opt === "CPYVRS") {
			$.ajax({
				url: "../DuggaSys/microservices/courseedService/copyCourseVersion_ms.php",
				type: "POST",
				data: "opt="+opt+para,
				dataType: "json",
				success: returnedCourse,
				error: function(error){
					console.error("testing error:",error);
				}
			});
        } else {
```

Console logged error:
```js
testing error: 
Object { readyState: 0, getResponseHeader: getResponseHeader(a), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(a, b), overrideMimeType: overrideMimeType(a), statusCode: statusCode(a), abort: abort(a), state: state(), always: always(), then: then()
, … }
[dugga.js:1048:14](http://localhost/LenaSYS/Shared/dugga.js)
    error http://localhost/LenaSYS/Shared/dugga.js:1048
    jQuery 6
    AJAXService http://localhost/LenaSYS/Shared/dugga.js:1038
    createVersion http://localhost/LenaSYS/DuggaSys/sectioned.js:1274
    validateForm http://localhost/LenaSYS/DuggaSys/sectioned.js:3845
    onclick http://localhost/LenaSYS/DuggaSys/sectioned.php?courseid=3&coursename=Datorns grunder&coursevers=123:1
```

**Comment by a22marca** [comment]
The issue of the post request to the microservice being aborted has been solved. The issue was that there was a redirect being made before the ajax request to the microservice had time to finish. This is solved by disabling async on the ajax call:
```
        } else if (opt === "CPYVRS") {
		$.ajax({
			url: "../DuggaSys/microservices/courseedService/copyCourseVersion_ms.php",
			type: "POST",
			data: "opt="+opt+para,
			dataType: "json",
			async: false,
			success: returnedCourse
		});

```

**Comment by a22marca** [comment]
There is a microservice mentioned that should create a new insert into the table vers called createNewVersionOfCourse, which should be used. It is not implemented yet, so I will keep the code as is regarding the following query:

```
		$query = $pdo->prepare("INSERT INTO vers(cid,coursecode,vers,versname,coursename,coursenamealt,startdate,enddate,motd) values(:cid,:coursecode,:vers,:versname,:coursename,:coursenamealt,:startdate,:enddate,:motd);");

```

**Comment by a22marca** [comment]
Waiting for issue [15304](https://github.com/HGustavs/LenaSYS/issues/15304) to get merged before adding the retrieve service to this microservice.

**Comment by a22marca** [comment]
The microservice works now using the solution with ajax in one of the previous comments. Instead of creating a pull request for this now, I will wait until the weekly merge is done and create a new branch and PR.
