### ISSUE TITLE
Create microservice changeActiveCourseVersion_courseed

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14196]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#changeActiveCourseVersion_courseed)

File: **changeActiveCourseVersion_courseed_ms.php**
Folder: **courseedService**

**Comment by a21jeaha** [comment]
@d21erisu @c21alest is the parent service for this service already created and tested?
If not, then i don't see a way of creating this micro service, seeing as it used that service to perform this function. you could say that the all the child services don't exist and that the parent service is the actual service. seeing as all the child services do exactly the same thing.
![image](https://github.com/HGustavs/LenaSYS/assets/102600391/8bd93696-d48a-4b1a-9301-a57fa591cf56)

the actuall service that should be created is therefore setActiveCourseversion.

**Comment by c21alest** [comment]
Sorry missed that information, setting this on hold

**Comment by a21jeaha** [comment]
Work on this issue is now continued.

**Comment by a21jeaha** [comment]
I have come to the conclusion that this code is never used in this service, courseedservice. There exists a copy of this code in the service, sectionedservice. This version is most likely the version that is suppose to be used (though this version does not function as intended).

The reason i believe this is that no option is given to change the active version from courseed, but there is one in sectionedservice.
courseed: 
![image](https://github.com/HGustavs/LenaSYS/assets/102600391/79d73bbf-ae5b-466c-b315-55c8165c527f)

sectionedservice: 
![image](https://github.com/HGustavs/LenaSYS/assets/102600391/f915879b-a63b-4fd7-9038-a53f25452d0c)

@d21erisu @c21alest should i drop this issue?

**Comment by b21isabe** [comment]
I have started researching this issue and believe that the microservice requested by this issue is for the opt "CHGVERS" on line 178-185 in courseedservice.php which updates the course table with the current active version of that course. There also appears to be an identical opt in sectionedservice.php on lines 445-453. The previous years students did also mention this but I will see if I can find anything they didn't notice.

**Comment by b21isabe** [comment]
From what I can gather, neither the sectionedservice or courseedservice versions of the code is actually ever used. When you edit a course, and change its active version the opt that is used seems to be UPDATEVRS which also has duplicate code in both sectionedservice and courseedservice. When you create a new version of a course and set it as active the NEWVRS opt is used.
