### ISSUE TITLE
Create microservice deleteCourseMaterial

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14206]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#deleteCourseMaterial)

File: **cdeleteCourseMaterial_ms.php**
Folder: **courseedService**

**Comment by c21alest** [comment]
Depending on:
deliteFromTableCodexample
deliteFromTableListentries
deliteFromTableQuiz
deliteFromTableCourse

**Comment by a22yifwa** [comment]
Need to add a File: **deleteCourseMaterial_ms.php** in the Folder **courseedService**. In deleteCourseMaterial_ms.php we need to use different service to delete _Course Material_ from different table. 
In MS : Uses service **deliteFromTableCodexample** to delete a row from the table codeexample. Uses service **deliteFromTableListentries** to delete a row from the table listentries. Uses service **deliteFromTableQuiz** to delete a row from the table quiz. Uses service **deliteFromTableVers** to delete a row from the table vers. Uses service **deliteFromTableCourse** to delete a row from the table course.

**Comment by a22yifwa** [comment]
- Lines **543-548** from the courseedservice.php are use to delete the course example from the course database.
- Lines **550-555**  from the courseedservice.php are use to delete listentries from the course database.
- Lines **557-562** from the courseedservice.php are use to delete the quiz from the course database.
- Lines **564-569** from the courseedservice.php are use to delete the vers from the course database.
- Lines **572-577** from the courseedservice.php are use to delete courses that have been marked as deleted.

**Comment by a22yifwa** [comment]
For make a microservice we need to use the file monolithic-to-microservices with [https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/DuggaSys/microservices/monolithic-to-microservices.md](Link) . We need to follow the steps and enter the correct code from the courseedservice.php. Those lines of code I wrote earlier can be used in the new file.

**Comment by a22yifwa** [comment]
For make a microservice we need to use the file monolithic-to-microservices with [](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/DuggaSys/microservices/monolithic-to-microservices.md) We need to follow the steps and enter the correct code from the courseedservice.php. Those lines of code I wrote earlier can be used in the new file.

**Comment by a22yifwa** [comment]
For make a microservice we need to use the file monolithic-to-microservices with link [monolithic-to-microservices](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/DuggaSys/microservices/monolithic-to-microservices.md). We need to follow the steps and enter the correct code from the courseedservice.php.  Lines of code I wrote earlier can be used in the new file.

**Comment by a22yifwa** [comment]
I re-downloaded lenasys, and downloaded github desktop. I use github desktop to branch the issue.

**Comment by a22yifwa** [comment]
I use XMAPP to opened the local lenaSYS web page to test whether the code works well.

**Comment by a22yifwa** [comment]
Tested the code and no errors were displayed.
