### ISSUE TITLE
Result list definitions and input

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1420]
* Anm: is not required to be filled out by LenaSYS
* A: "Betyg" should be filled out by LenaSYS from the grading of the particular "Moment", e.g., "Hemtentamen" or "Laborationer"
* B: "Skrivningspoäng" should be filled out by LenaSYS
* C: "ECTS-betyg" should be filled out by LenaSYS
* 1-8: These fields are used for scores on individual exam questions or lab assignments. Should be used and filled out by LenaSYS
We also need to be able to input the following manually:
* Issuer of the list, e.g., Christina Söderqvist
* date of issuing list
* "List nr" (Most important)
* "Provdatum"

**Comment by a13antda** [comment]
Change to English. Don´t use any other language then English!

**Comment by a97marbr** [comment]
Well the text that should be used in this list is in Swedish.

**Comment by a97marbr** [comment]
![skarmklipp](https://cloud.githubusercontent.com/assets/4948661/7583395/2136ed28-f895-11e4-8daa-aad21255ee1a.png)

**Comment by a13chrju** [comment]
can only three "moments" exist under a course or do you want the alphabet to continue e.g A,B,C,D,E... if more "moments" exist?

**Comment by a13chrju** [comment]
where does the ECTS-grade and the "skrivsningspoäng" come from?

**Comment by a13denli** [comment]
Completed issue?
