### ISSUE TITLE
Create microservice getGroupValues

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14207]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#getGroupValues)

File: **getGroupValues_ms.php**
Folder: **sectionedservice**

**Comment by a22melst** [comment]
This issue shall be split into sub-issues.

### **From potential_micro_services.md:**
**getGroupValues**
Uses service selectFromTableGroup to get information it requires from group.

**Comment by a22melst** [comment]
Looking into where the DB-table "groups" is used. Creating a group in a course only seems to add a record to the table "listentries".
