### ISSUE TITLE
Create microservice deleteListentries

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14209]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#deleteListentries)

File: **deleteListentries_ms.php**
Folder: **sectionedservice**

**Comment by a22fokol** [comment]
## Implementation Plan

I plan to move the "deleteListentries" function to a new file named `deleteListentries_ms.php`. This will make the function easier to manage (maintain) and test. I am also planning to update any parts of our application that call the  "deleteListentries" function to use the new location.

I'll start with the work soon as possible. Any feedback is welcome.

**Comment by a22iliru** [comment]
Continue work on this issue. No progress has been done

**Comment by a22albjo** [comment]
The microservice is now a copy of the funtionality from the monorepo, however the monorepo has a problem, this should probably be solved before moving on with the pull request:
`<br/>
<b>Fatal error</b>
:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`albin`.`useranswer`, CONSTRAINT `useranswer_ibfk_3` FOREIGN KEY (`moment`) REFERENCES `listentries` (`lid`)) in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/sectionedservice.php:198
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/sectionedservice.php(198): PDOStatement-&gt;execute()
#1 {main}
  thrown in <b>/Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/sectionedservice.php</b>
on line <b>198</b>
<br/>
`
