### ISSUE TITLE
Create microservice createListentrie

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14212]
Related to: https://github.com/HGustavs/LenaSYS/issues/14143

Read more about the MS [here](https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#createListentrie)

File: **createListentrie_ms.php**
Folder: **sectionedservice**

**Comment by c21alest** [comment]
Depending on:
selectFromTableCodeexample
createNewCodeexample

**Comment by c22emigr** [comment]
To do:
Add createListEntry_ms.php to group branch. 

Insert a new code example and update variables accordingly. Uses service selectFromTableCodeexample to get information it requires from codeexample. Uses service createNewCodeexample to makes inserts into the table codeexample. Uses service createNewListentrie to makes inserts into the table listentries.

**Comment by a22eriwi** [comment]
Done research on the issue at hand.

Explanation of the issue,
createListentrie
Insert a new code example and update variables accordingly. Uses service selectFromTableCodeexample to get information it requires from codeexample. Uses service createNewCodeexample to makes inserts into the table codeexample. Uses service createNewListentrie to makes inserts into the table listentries.

listentries are duggas, headers, tests, etc..

We are supposed to create a new php file (createListentrie_ms.php) and put in inside a new folder (sectionedservice).
