### ISSUE TITLE
Outline of black state diagram 

### ISSUE THREAD

**Issue by b21eriho** [HGustavs/LenaSYS#14239]
A black-colored state diagram looks like this:
![image](https://github.com/HGustavs/LenaSYS/assets/129077727/e0461b8c-3187-4707-aba9-aeca2d3505ed)
Make the outline white

**Comment by a19clasv** [comment]
Black-colored state diagrams aren't the only ones with that gray outline, should I change the rest as well or just that one?

**Comment by a19clasv** [comment]
It might actually be easier to change all of them.

**Comment by a19clasv** [comment]
But are you sure that it would be wise to have a white outline on a white background?

**Comment by a19clasv** [comment]
They already turn white in dark mode.

**Comment by b21eriho** [comment]
Actually, you make good points, this issue shouldn't exist
