### ISSUE TITLE
Status after group 2 2023

### ISSUE THREAD

**Issue by c21alest** [HGustavs/LenaSYS#14260]
Below is a spreadsheet of the current state after group twos progress. The initial task was to re-engineer all service files and convert them to microservices. But before this could be done much documentation was needed. Below is the different sub task (documentation types) that was needed. And many service files have had problem and some had low priority/postponed. The X marks what sub tasks are done for a specific service file. And not a complete service file has been replaced by microservices only parts.

<img width="1206" alt="Skärmavbild 2023-05-25 kl  16 57 06" src="https://github.com/HGustavs/LenaSYS/assets/102578850/625fb3a1-8b21-44e1-8119-51fafe0dd18c">

### Tests status
As you can see there are not many finished tests to be used with the test API, something that needs to be done in order to compare the old service file with the new microservices. There are only a few finished tests and one that is in an unfinished state. But the majority of all service files have a test description that is used to create the JSON for the test API. The test API also needs further development to support all services files (array problems and comparison between service and MS), current state for test API can be found [here](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/Shared/Documentation/Test%20API/Guide%20on%20how%20to%20use%20Test%20API.md).

### Finished MS
- retrieveCourseedService
- updateCourseVersion_courseed
- editBoxTitle
- setAsActiveCourse
- createNewCodeexample
- createMOTD

[Here](https://github.com/HGustavs/LenaSYS/tree/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/backend-models/microservices/duggaSys%20services) you can find documentation about the other microservices that are to be implemented and [here](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/backend-models/microservices/microservice_priority.md) is the priority lists.

**Comment by a21jeaha** [comment]
This document might be useful for you as well, it describes how communication can be conducted between the three file structure (.php .js  service.php) for the services, and can be found [here](https://github.com/HGustavs/LenaSYS/blob/master/backend-models/service%20documentation/Communication%20used%20in%20the%20old%20style%20service%20files.pdf)
