### ISSUE TITLE
Add error handling for function deleteMetadataDB()

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14280]
When running the installer (LenaSYS/install/install.php) on machines where the folder "githubMetadata" is not present in the parent folder of LenaSYS, the installer runs into the following error:

`Warning: scandir(../../githubMetadata): Failed to open directory: No such file or directory in /var/www/html/LenaSYS/install/install.php on line 740`

`Warning: scandir(): (errno 2): No such file or directory in /var/www/html/LenaSYS/install/install.php on line 740`

`Fatal error: Uncaught TypeError: preg_grep(): Argument #2 ($array) must be of type array, bool given in /var/www/html/LenaSYS/install/install.php:740 Stack trace: #0 /var/www/html/LenaSYS/install/install.php(740): preg_grep('~\\.db$~', false) #1 /var/www/html/LenaSYS/install/install.php(453): deleteMetadataDB() #2 {main} thrown in /var/www/html/LenaSYS/install/install.php on line 740`

Removing the code does not seem to affect the function of the installer. 

If it is determined that the function is needed, some error handling should be implemented to prevent the installer from crashing if it cannot find the githubMetadata folder.

**Comment by a22oscja** [comment]
Code is deemed to be necessary due to installer not updating metadata in a fresh install otherwise, could lead to corruption and the like.

Error handling added by checking if directory exists before deleting from it, returning instead if it does not exist.

**Comment by a22willi** [comment]
I have tested the code, it works, and everything looks good!
