### ISSUE TITLE
Create Class-diagram Wiki

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#14285]
## Description

The functionality of different types of diagrams needs to be documented.
A wiki page need to be created with the current functionality and some technical description of how it is achieved.
There should also be references to closed issues that have implemented said functionality.
There should be clear descriptions for each new topic with pictures if user interface is described.
File paths and code blocks should be included when describing code implementation.
An example of good structure can be found in:
https://github.com/HGustavs/LenaSYS/wiki/Diagram-dugga-overview

## Job

Create a new wiki page describing how the Class-diagrams currently work.

**Comment by a23ponek** [comment]
Färdig med issue Create Class-diagram Wiki #14285, länk till Wiki sidan:
https://github.com/HGustavs/LenaSYS/wiki/Class%E2%80%90Diagram-functionality-documentation

Återkom ifall något ska ändras/läggas till.

**Comment by a22solmi** [comment]
Don not reference issues about bugs or other small changes.
#12593 Has nothing to do with implementation of the UML entity. #11737 should be replaced with #11763. 
You should link #11248 and other posts from Henrik as they contain sub issues for UML entities. 
You can remove the part about the IO and save functionallity. This wiki is supposed to be about UML only

**Comment by a23ponek** [comment]
Wiki page is updated.
