### ISSUE TITLE
Entire toolbar not visible

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14283]
# Description
The toolbar uses a fixed size so that on certain screens the toolbar can be cut off with no way to access the lower icons. 
This is most apparent with different screen sizes/scaling

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/3059c2fb-335e-4a49-8001-f743ea17e026)
![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/1f3127ba-2695-413c-9e6d-2db87086dea5)

# Job
Implement a fix. Could be to either make the toolbar resize or add a scroll-feature. You could try both and check which works best

**Comment by a22jacka** [comment]
This has been looked at earlier in issue [12693](https://github.com/HGustavs/LenaSYS/issues/12693) and different fixes seem to introduce new problems. The whole toolbar likely needs to be reworked a bit

**Comment by d22hanol** [comment]
Adding an overflow value to the toolbar makes the popup toolbar and tooltip appears behind the diagramwindow/canvas  instead of in front of it. Did not manage to find a sufficient solution to fix this issue.
