### ISSUE TITLE
Create State-diagram Wiki

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#14286]
## Description

The functionality of different types of diagrams needs to be documented.
A wiki page need to be created with the current functionality and some technical description of how it is achieved.
There should also be references to closed issues that have implemented said functionality.
There should be clear descriptions for each new topic with pictures if user interface is described.
File paths and code blocks should be included when describing code implementation.
An example of good structure can be found in:
https://github.com/HGustavs/LenaSYS/wiki/Diagram-dugga-overview

## Job

Create a new wiki page describing how the State-diagrams currently work.

**Comment by a22ricni** [comment]
We are done with the state-diagram wiki page
https://github.com/HGustavs/LenaSYS/wiki/State%E2%80%90Diagram

**Comment by a22solmi** [comment]
The issues linked in the wiki page are just random bug repports. They have nothing to do with the implementation of features. Please find the issues regarding the implementation of said features. Look for issues made by Henrik as these are usually requests for new features.

**Comment by a22ricni** [comment]
Have hopefully fixed the wiki
https://github.com/HGustavs/LenaSYS/wiki/State%E2%80%90Diagram
