### ISSUE TITLE
output buffer discarded before installation script is done

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14282]
**Problem:** In the installer, the output buffer is discarded too early using `ob_end_clean()` on line 280, before all output has been sent. This results in errors whenever `ob_flush()` is called during the progress bar operation.

**Solution:** Simply changing `ob_end_clean()` to `ob_clean()` should fix the issue. This modification clears the current output (the pre-installation messages) without ending the entire output buffering.

**Comment by b22marah** [comment]
Task fulfilled
