### ISSUE TITLE
Find out how data is gathered from github

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14290]
Investigate the current method used to retrieve code examples from GitHub. Determine whether they are obtained via the Git command line interface (CLI) or through the GitHub website. Please also identify where these examples are stored. Document your findings in the comments of this issue.

[sqlite diagram](https://github.com/HGustavs/LenaSYS/wiki/Github-Integration#sqlite-1)

**Comment by a22maxra** [comment]
Files for code examples is in one of the folders within /LenaSYS/courses
New files that can be used in code examples are created within and stored in the folder.

After selecting a course, you can then click on 'files' to add the newly created file. Once the file is added, it will be included in the database in the "fileLink" table and can be used as a code example in courses.
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/3f8743b7-92d8-413b-a4e7-41f06017c50e)

That is for the files that make up a code example. The code examples themselves are stored in the "codeexample" table.

You should be able to link GitHub repositories to create code examples, however we were not able to do this but the relevant files are:

`gitfetchService.php`
Takes a user-provided github repository and converts it in to a API endpoint for fetching content. Files get stored in Lenasys/course/_courseid_ and file information in fileLink table. 

`gitcommitService.php`
Retrieves latest commits if repositories have been updated. Repositories are linked with a specific course ID which can then be used to update the right code examples.
