### ISSUE TITLE
[Research] Find reason for site breaking

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14298]
## Description
A bug that crashes the whole site. 
Steps to reproduce:
1. make a sequence diagram lifeline
2. select "Sequence Activation"
3. left click once on the lifeline to select it
4. right click while hovering over the lifeline
See video for clarification

EDIT: this also happens with the super-state

https://github.com/HGustavs/LenaSYS/assets/129258593/0cf9f65a-df54-437b-8539-bcac2ecd81ab

## Job
Research how this happens and write a report about how this works. Could also be good to write down if this happens with other elements and which ones in that case

**Comment by a21liltr** [comment]
When the break happens, it seems the program enters the method **mouseMode_onMouseUp(event)** where an **if()** condition is fulfilled, when a user presses the **right button click**. Inside the **if block**, a **switch case** decides what is supposed to happen, but as the user has _sequence activation_ active, the user's mode is recognized as **mousemode.PLACING_ELEMENT**.

In this particular mode, the program reaches method **showdata()**, whether from inside **makeGhost()** or after completing **makeGhost()**, it is unclear. The method attempts to redraw all elements and lines, but as the _sequence activation_ element is seemigly not "registered" or added correctly, it cannot redraw the elements, resulting in an error.  This is also backed up by a line or edge that connects from the _sequence lifeline_ object to nothingness when usually a line cannot be created unless there are atleast 2 objects that the line is connected between.

Then the code gets "stuck" on **updatepos** for the mouse position through either **mouseMode_onMouseUp** or **mouseMode_onMouseMove**, it seems like, where nothing the mouse does after this actually has an impact or registers. This is hard to test as breakpoints doesn't seem to work (for me).

**Comment by a22jacka** [comment]
This might also have been fixed by #14565. Some testing is required to confirm this

**Comment by a21liltr** [comment]
> This might also have been fixed by #14565. Some testing is required to confirm this

After doing a small test, it seems this issue has indeed been fixed. Please move to actual test stage to properly confirm (or something else appropriate) so that this issue can be closed.

**Comment by a21liltr** [comment]
Testing has been completed on Chrome, Edge and Firefox by placing down multiple elements and observing how they react when trying to place the elements both next to eachother or on top of one another. The test also included placing the elements with a slight overlap and overlapping completely.

This was also tested with different elements such as ER Entity, UML Class, IE Entity etc, as well as the relation elements, UML States and Sequence elements (meaning, most grouped elements with subitems). All elements except Sequence Lifeline had the same behaviour, they could not be overlapped. Around 20 elements where placed without error occuring.

**Sequence Lifeline could overlap over all elements** and the other elements could also overlap over Sequence Lifeline. Still no error occured by doing this.

The elements **could still become overlapped** if an element A is placed close to another element B and then have one of the elements **expanded over the other.**

**Pressing right mouse button did nothing, only when pressing left mouse button could an element be placed.**

No "major" error occured or was observed. Only some error messages on console informing that an implementation at switch-case in ddown() is missing, and "Failed to create an element as it overlaps other element(s)".

Issue seems to have been solved.
