### ISSUE TITLE
Explore how the current codeviewer works.

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14296]
Explore how the current code viewer works, which is mainly located in the files:
- DuggaSys/codeviewer.js
- DuggaSys/codeviewer.php
- DuggaSys/codeviewerService.php

Also read the documentation located in the [wiki](https://github.com/HGustavs/LenaSYS/wiki/CodeViewer). This is alot of work, so we suggest that you work as a group and explore the features and code.

Maybe this link could also be useful: [wiki](https://github.com/HGustavs/LenaSYS/wiki/CodeViewer:-Add-Update-Templates
).

Try to create a small and concise report of your findings in the comments below, what works, what doesn't etc.

**Comment by SleepyBearIV** [comment]
Utifrån roadmapen kan man se att det enda som implementerats är att när du skriver in en url som sparas i en databas till en specifik kurs både när du skapar ny eller redigerar en kurs. De problem som finns med nuvarande implementationen.

issue 1:  funktion elementIsValid(element)   "courseed.js" är fel, när man ändrar i edit cours kan man inte spara för githubb-url går inte att validera. Är samma sak för create new men funka om man lämnar den tom.
issue 2: när både Course code och GitHub URL ändras ligger informationsrutorna fel  "courseed.php"

issue 3, url sparas i databas (om man bypassar valideringen från issue 1) men hämtas inte när man kollar i edit course "courseed.js" 

Mer än detta är inte implementerat, hur vi går vidare är beroende på vad kunden vill ha det.
