### ISSUE TITLE
Fault handling if not logged in and has no example needed

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#1429]
![username bug](https://cloud.githubusercontent.com/assets/11715479/7585870/11d565d2-f8a7-11e4-853b-aac6e15ba382.jpg)
This appears when you're standing in http://webblabb.iki.his.se:8080/codesys/c12jenek/CodeViewer/EditorV50.php and you are not logged in

**Comment by HGustavs** [comment]
I would really like if the buttons would disappear if there is no backward/forward/play link to go to. Also the undefined:undefined should not appear.

**Comment by c12jenek** [comment]
HGustavs comment is made into smaller issues #1483 and #1482
