### ISSUE TITLE
Create example state diagram

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14303]
## Description
There is no example diagram for state diagrams

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/01ab03cc-5c05-4769-8b29-f80fe92d41ba)

## Job
Create a state diagram that can be used as an example

**Comment by d22abdha** [comment]
![statediagram](https://github.com/HGustavs/LenaSYS/assets/58794335/084d1a65-75d8-4cac-bf9f-716c22e9e58c)

I detta diagram är vattenkokare example diagram, den har vi tre tillstånd: "Avstängd", "Uppvärmer" och "Automatisk avstängd". Vattenkokaren startar i "Avstängd". När strömbrytaren aktiveras, flyttas systemet till "Uppvärmer", och om temperaturen når 100°C, går den över till "Automatisk avstängd". Och strömbrytaren stängs av när som helst, återgår vattenkokaren till "Avstängd".

**Comment by a22solmi** [comment]
This is not proper syntax for a state diagram. Please choose an example diagram from the Software Engineering course book instead. It should also be written in English to be consistent with other examples.

**Comment by d22abdha** [comment]
[State diagram.drawio (1).pdf](https://github.com/HGustavs/LenaSYS/files/14878879/State.diagram.drawio.1.pdf)

"1. Waiting State: The microwave starts in this state, where it displays the time. This is the default state when the microwave is not in use.

2. Full Power and Half Power States: If the user selects either full power or half power, the microwave transitions to those states. In "Full Power," the microwave sets its power to 600, and in "Half Power," it sets the power to 300.

3. Set Time State: After choosing the power level, the user sets the time by entering a number (duration for cooking). Once the number is entered and the time is set, the microwave transitions to the "Enabled" state if the door is closed. If the door is open while in this state, it will move to "Disabled" state where it displays 'Waiting'.

3. Enabled State: In this state, the microwave displays 'Ready', indicating that it is ready to start operation. The microwave will remain in this state as long as the door remains closed.

4. Operation State: When the user starts the microwave (presumably by pressing the start button), it transitions to the "Operation" state, where the actual cooking or heating operation takes place.

5. Transitions Back to Waiting: If at any point the door is opened during the operation, or if the operation is canceled, the microwave returns to the "Waiting" state."

**Comment by a22solmi** [comment]
Why are you linking a drawing from drawio? You are supposed to make the diagram in LenaSYS. Look at the implementation of the other examples and make a pull request with the files.

**Comment by a22solmi** [comment]
Solved with #14432
