### ISSUE TITLE
Can't access states inside superstates

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14304]
## Description
When creating a superstate over some already existing states, it's somtimes impossible to access the states inside it without moving the superstate. 

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/70148d15-181b-4572-8b13-9267916884f2)

## Job
Create a way to either click past the "filled" area or to move the superstate below the states

**Comment by d22hanol** [comment]
If you create the super state before you create the object inside then you can access it, but if you create the super state after the inside object then it doesnt work. 
the same is true for the loop/alt for sequence diagram
