### ISSUE TITLE
Refactor broken code

### ISSUE THREAD

**Issue by d22hanol** [HGustavs/LenaSYS#14301]
In /DuggaSys/diagram.php on line 926 and 927, the onclick values are incorrectly formatted. it should be ' onclick="func(); func2(); func3();" ' and not ' onclick="func(), func2(), func3()" '
Also, remove the extra spaces in the button on line 927.

**Comment by b22chrmo** [comment]
After changes, code still works as intended. Code looks cleaner and easier to read after changes. Nothing different with the functionality before or after changes.
