### ISSUE TITLE
[Research] find out if re-adding setup brings back old issue

### ISSUE THREAD

**Issue by b22jonan** [HGustavs/LenaSYS#14312]
## Description
In issue [14003](https://github.com/HGustavs/LenaSYS/issues/14003) I found that fixing the save button requires that you bring back the `setup()` function in `diagram_dugga.js`. But it was mentioned in that issue that readding the setup function would bring back an old issue: [13080](https://github.com/HGustavs/LenaSYS/issues/13080). 
## Job
Research is needed to see if it still brings back the preloading problem and if its possible to fix that issue without commenting out the setup function

**Comment by a22cazlu** [comment]
We have looked this up and uncommenting the setup() function doesn't bring the issue from #13080 back.
