### ISSUE TITLE
Implement retrieveSectionedService_ms

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14319]
Related to:

https://github.com/HGustavs/LenaSYS/issues/14208

Check comments

**Comment by f22linbe** [comment]
**TASK**
---
Create `retrieveSectionedService_ms` with the **objective** of returning a JSON with the same structure for all sectioned services(microservices). 

An example of the JSON returned by the microservice(getCourseGroupsAndMembers), as mentioned in #14208, is structured as follows: 
`{"debug":"NONE!","grplst":[["coursegroup","firstname","lastname","email@his.se"]]}`

This example represents a suitable structure to follow.

See [Creation of retriveInformation_ms](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/DuggaSys/microservices/monolithic-to-microservices.md#creation-of-retriveinformation_ms)

**Comment by f22linbe** [comment]
How to test: 
1.
Include the retrieveSectionedService into the microservice
`include_once "retrieveSectionedService_ms.php";`

2.
Call the function inside the _ms_ with these parameters _$pdo_, _$userid_ and an array variabel) the array should contain the data you want to retrieve. If the variable you need is known, include its name as the key in your request.
Example: 
`retrieveSectionedService($pdo, $userid, array('debug'=> "NONE!", 'grplst' => $grplst));`
or
`retrieveSectionedService($pdo, $userid, $grplst)` if $grplst already is an array.

3.
To see the returned values from the microservices in a browser, navigate to a page to where the related microservice is used. Open inspect->network->search for the microservice name and click on the service name.

NOTE: Don't forget to change the url in `dugga.js`
