### ISSUE TITLE
[Research] Find out how 

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14311]
## Description
When trying to select an ER entity with the box select, you need to select quite a bit above the entity in order to select it. 
I suspect it might have something to do with the `margin-top: 19px;` on the parent div but it requires further investigation and testing.

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/109acb60-dd05-4b67-b825-57360ba90355)
This does not highlight the entity

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/cf5e071c-dd7d-4d54-b86e-fccbf9760987)
This highlights the entity

## Job
Write a comment about how the ER entities get their sizes and positions

**Comment by b22jonan** [comment]
the ER entities seem to get thier dimensions in diagrams.js on lines 10107-10114. 
```
        if (element.kind == "EREntity") {
            str += `<div id='${element.id}'	class='element' onmousedown='ddown(event);' onmouseenter='mouseEnter();' onmouseleave='mouseLeave()';' style='
                            left:0px;
                            top:0px;
                            margin-top:${((boxh / 2))}px;;
                            width:${boxw}px;
                            height:${boxh}px;
                            font-size:${texth}px;`; 
        }

```

removing the `margin-top` from there removes that property from the entity aswell.
