### ISSUE TITLE
Find out why the margin exists

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14313]
## Description
Following [#14311](https://github.com/HGustavs/LenaSYS/issues/14311), the margin causes the problem

## Job 
Find out why the margin exists and check if anything breaks if it's removed. If nothing breaks then remove it

**Comment by b22jonan** [comment]
they were added in issue [13940](https://github.com/HGustavs/LenaSYS/pull/13940) to make the entities centered as ghosts, should be possible to have the margin removed after they are placed. but thats a different issue.
