### ISSUE TITLE
A button to remove text in input fields?

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#1431]
We used to use placeholders to show text in input fields. So you didn't need to remove text before typing. This was a challange because if you didn't input anything new, the current data would get overwriten with null values in the database when saving.

However, in internet explorer there is by default a button that removes text in input fields. We where thinking if we should simulate the same thing in the other browsers with code.

What is your opinion?

**Comment by a13alfbe** [comment]
HTML5 has the option to use <input type="search"> instead of <input type="text"> to get the "clear-button" that you are looking for. This might be a quick solution?

**Comment by HGustavs** [comment]
Better to use something standardized rather than patching with code.

The less javascript we have for such things, fewer things break in the future.

**Comment by c13chrjo** [comment]
@HGustavs Is this an extension of what a13alfbe wrote or are you talking about something else?

**Comment by HGustavs** [comment]
In most places I prefer standardized stuff over javascript shims. So I up-vote the search type trick.

**Comment by c13chrjo** [comment]
creating an issue from this
