### ISSUE TITLE
White object on white background

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#14328]
## Description
White objects blend into background. This is not an issue in dark mode as the color black is not allowed.
![issue-v1-6](https://github.com/HGustavs/LenaSYS/assets/129150661/cb79b0bf-a80f-42af-a5e3-4edb0bbd09b8)

## Job
Create a thin black outline around affected objects or remove option for white objects on white background.

**Comment by a21liltr** [comment]
Issue has been solved with weekly branch merge.
