### ISSUE TITLE
Course github repo is not being saved. 

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14322]
After adding a github repo to a course. It does not show up the next time you try to modify it.

Adding github repo.
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/910220c6-dee3-4357-b95b-d8f09e312ee6)
The next time you edit, it is no longer there. 
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/ec6098ac-7265-44dc-913f-ccdf1e5f90c7)

[sqlite diagram](https://github.com/HGustavs/LenaSYS/wiki/Github-Integration#sqlite-1)

**Comment by a22moamy** [comment]
The bug has now been fixed. Additionally github URL should be logged as well. As a side effect, courses with no GitHub URL will display the default null value in the "GitHub URL" field from the edit course window. This null value has to be removed when updating a course. Adding a correct github URL will still make the field red, but it has the right functionality and does not affect saving the URL.

**Comment by HGustavs** [comment]
Unclear about the details so I will give a short overview of my requirements regarding this functionality.

A repository is not necessary (if there is no github project for a course).
It should be possible to change or enter a github repository using the same dialog.
