### ISSUE TITLE
[Research] Box-select not working properly with super-states

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14325]
## Description
Similarly to [](https://github.com/HGustavs/LenaSYS/issues/14317), when using box select to highlight a super-state the highlight needs to be super big in order to highlight it. This time it doesn't appear to be because of margin, might be but unsure. 

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/d08c3859-95bf-4e50-b626-e4507892d43c)
The black box is the highlight

## Job
Find out why it doesn't work properly and write a comment with your findings

**Comment by a22solmi** [comment]
Solved by #14377
