### ISSUE TITLE
Investigate how a save button could be implemented for github code example.

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14329]
When trying to select a github path for a code example via clicking the github button here:
![bild](https://github.com/HGustavs/LenaSYS/assets/129264968/38b3ce85-c5ac-4075-b2ab-f2a2bcadfd08)
The following popup appears. There is however no way to save the entered data. 
![bild](https://github.com/HGustavs/LenaSYS/assets/129264968/b1ae8932-9bc8-4de7-bc8b-ed03ee316d50)

In this issue your task is to:
- Establish if there is code to save the data, if there is, document where it is located. 
- If not, find out where this data should be stored. And suggest the best way to proceed in adding a save button.

**Comment by d22mikwe** [comment]
En Save knapp var utkommenterad i php-filen sectioned.php på rad 654.
![image](https://github.com/HGustavs/LenaSYS/assets/129263393/1d51403a-f0e8-4e98-996a-2734ca56c95a)
Denna knapp kallar funktionen updateTemplate() som inte är kompatibel med denna githhub funktion. updateTemplate() används när användaren klickar på ett skapat kodexempel och uppmanas att välja ett template.
![image](https://github.com/HGustavs/LenaSYS/assets/129263393/10cdf5ea-213a-43df-b996-533a702d0b3b)
Denna funktion hämtar redan lagrade kodexempel och lägger in dem i respektive template.

Vi kunde inte hitta några specifika funktionaliteter för just denna github-funktion.

För att implementera detta tror vi att en variation av den redan existerade funktionen (Bild 2) där användaren väljer ett template och vilka kodexemplar som ska läsas in kan implementeras. 
Skillnaden i den nya Save knappen + vyn blir att användaren istället får fylla i X antal GitHubURL:s och filepaths beroende på typ av template som valts. I dagsläget ändras inte Vyn beroende på vad användaren valt. 

Lagringen borde ske i samma mapp och db som vanligt implementerade kodexempel. Dvs LenaSYS\Courses\ 
![image](https://github.com/HGustavs/LenaSYS/assets/129263393/0889af3d-d724-4af3-a6d5-7d6c7b61978c)
