### ISSUE TITLE
[Research] Find reason for infinite recursion

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14332]
## Description
Somehow loading this save causes a recursion error. Afterwards nothing can be placed and moving the canvas causes a lot more errors to appear. Loading another save or reloading the site fixes it.

https://github.com/HGustavs/LenaSYS/assets/129258593/5a6c98b9-3ea1-4467-8d81-f5d6faec626e

The broken save files:
With edit history: 
[bugged_diagram_history.json](https://github.com/HGustavs/LenaSYS/files/14863315/bugged_diagram_history.json)

Without edit history:
[bugged_diagram_no_history.json](https://github.com/HGustavs/LenaSYS/files/14863318/bugged_diagram_no_history.json)

## Job
Try to recreate the bug and find out what causes it

**Comment by a22solmi** [comment]
zero character max length causes infinite loop where the text is split without decreasing in size.
