### ISSUE TITLE
Find bugs with creation of items in course

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14353]
When trying to create course moments/code examples/links etc. The functionality was found to be working suboptimally. Suggest concrete issues and bugs that can be solved in the future.

An example: When clicking button X, I expect Y to happen, instead Z happens. 

When you find a bug, create a new issue according to the following instructions:
- Go to the issues tab and click `new issue`.
- Write a good description and title. 
- Add the labels: `Bug` & `g3-2024`.
- Click `Submit new issue`.
- In the Projects tab, select awaiting triage, and add it to the `to-do` column.

This is the page you should test:
![bild](https://github.com/HGustavs/LenaSYS/assets/129264968/6f8b3bd2-f330-44e6-b082-be526ca4e5a9)

**Comment by a22karja** [comment]
I created:
https://github.com/HGustavs/LenaSYS/issues/14358
https://github.com/HGustavs/LenaSYS/issues/14368
https://github.com/HGustavs/LenaSYS/issues/14371
