### ISSUE TITLE
Modify "download github repo" tooltip

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14352]
![bild](https://github.com/HGustavs/LenaSYS/assets/129264968/8c4ae6af-9ec2-4e9f-996f-a7d6d87528c9)
When hovering over the button circled above, it should show a html/css styled popup instead of the default html title property. See [example](https://www.w3schools.com/css/css_tooltip.asp).

Requirements:
- The tooltip needs to be styled the same way as the rest of the page.
- It needs to work in dark mode. 
- It should show when the last fetch was made. 
- It should show how long is left on the cooldown (does not need to update dynamically).

**Comment by b22chran** [comment]
Added tooltip-class to the github-button and a span-element with tooltiptext-class. This uses the created session-variables "lastFetchTime" and "fetchCooldown" from the gitcommitService.php to navheader.php to show the latest fetch and cooldown next possible fetch. This is visable when hover. Fixed the classes in style.css for the tooltip to work as wanted.

**Comment by b22chran** [comment]
Pull-request:
https://github.com/HGustavs/LenaSYS/pull/14402
