### ISSUE TITLE
Error message when clicking `Show tests`

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14360]
![bild](https://github.com/HGustavs/LenaSYS/assets/129264968/177917a3-c2e9-446d-82ab-36846fefc2d2)

After clicking the `Show tests` button in a course, the following error message appears. 

The `Show tests` button is located here:
![bild](https://github.com/HGustavs/LenaSYS/assets/129264968/199ff240-24a3-484a-abff-58e584dba84a)

**Comment by a22moamy** [comment]
This bug only appears for some users, not including me. @a22willi found the solution was to start the session before including any files. The solution does not cause any faults that we are currently aware of. 

When pressing the `show tests` button, no alerts appear and the user is directed to the following page: 
![Skarmavbild_2024-04-08_kl _09 59 29](https://github.com/HGustavs/LenaSYS/assets/129263915/43bc1d07-5cb7-4e8f-89cb-d97eaa1cddbb)

(Screenshot is from the demo-course).
