### ISSUE TITLE
ctrl + z removes lifelines

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14364]
## Description
When using <kbd>ctrl</kbd> + <kbd>z</kbd> removes every lifelife along with the latest element

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/27af210a-7c3c-41d3-aca6-6623276f4395)
The most recently changed is the activtion furthest right

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/88048677-3d9f-494c-8580-652b1186071b)
After <kbd>ctrl</kbd> + <kbd>z</kbd> the latest element and every lifeline are removed

## Job
Make it so that <kbd>ctrl</kbd> + <kbd>z</kbd> don't remove lifelines

**Comment by a22ricni** [comment]
What I find is that the variable "felem" is undefined on the line 7430. Also find that the actors but also the diagrams get a negative value on the width when you ctrl+z after you change the size. 
It seems like it gets the same result when you move the actor/ diagrams around first then ctrl+z.

**Comment by a21liltr** [comment]
Observations:

After placing an element on the diagram then reselecting it with the pointer to adjust its size, the selection is somehow still on the element or somehow the resized elements was placed in an array or clumped together with the last placed element, which after pressing CTRL+Z, removes the it along with all the other elements which have had their sizes changed using the pointer.

**Comment by a21liltr** [comment]
Additionally, it seems that after resizing an element then pressing CTRL+Z (which will cause the resized element(s) to disappear), it also breaks the diagram in the way that if you still have a placable element, you can still place it, however you cannot change tool to use, whether by clicking the tool in the toolbar with the mouse cursor or by using the keybindings. it will cause the cursor to lose the active placable element and nothing will react to the cursor at all. E.g. placed elements that were not resized will not react when clicked upon, and pressing other tools in the toolbar will not work either.

I still cannot find the solution to this issue but I believe it lies somewhere in StateMachine.save().
So,I will leave this and hope for the best for the next person that is assigned this monstrosity.
Good luck!

**Comment by a21liltr** [comment]
Will continue working on this issue after weekly merge. A new issue will be created and linked to this.
