### ISSUE TITLE
Add functionality to save a github code example

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14370]
At the moment it is currently not possible to fetch an example from github for a specific code example. In [Issue-#14329](https://github.com/HGustavs/LenaSYS/issues/14329) potential ways on how to do this were explored. Implement this functionality.

Requirements:
- For a code example a github repo the following should be stored.
  - The github repo URL.
  - The file path to enter in the github repo.
  - The template to use.
  - Numer of items. (explore what this does, and if it is necessary first).
- Add a save button, that when clicked saves this informaion. 
  - Save button styling must work in both light and dark theme.
- After clicking save, the requested files should be fetched. 
  - Issue [#14290](https://github.com/HGustavs/LenaSYS/issues/14290) should detail how data can be fetched. 
- This issue does not necessarily have to make the code examples appear correctly. But all the data necessary to load a code example should be stored. 

Useful information:
- [Wiki page](https://github.com/HGustavs/LenaSYS/wiki/Github-Integration)
- [Example repo](https://github.com/LenaSYS/Webbprogrammering-Examples)
- [gitfetchservice](https://github.com/HGustavs/LenaSYS/blob/master/DuggaSys/gitfetchService.php)
- [gitfetchserviceVisual](https://github.com/HGustavs/LenaSYS/blob/master/DuggaSys/gitfetchServiceVisual.php)

**Comment by d22mikwe** [comment]
Efter diskussion med a22willi ska kraven för issuet ändras till att enbart säkerställa funktionalitet så att det är möjligt att hämta samtliga filer med samma namn i en folder. Dvs att alla filer med samma namn fast olika filtyper (HTML, txt, js mm) ska hämtas.
Kraven att lagra datan i databaser och koppla till en filmapp i repositoryn har tagits bort då issuet ansetts för stort och ska delas
upp i mindre delar.

Nuvarande funktionalitet som implementerats tillåter hämtning av 1 fil från ett github repository, dock inte flera med samma namn. Detta ska implementerats och därefter anses detta issue färdigt.
