### ISSUE TITLE
Make a working test for updateListentrie in sectionedservice_Test.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14393]
- make sure a correct expected output and filters are used
- currently this does not pass the assert test
- Be aware that some tests needs a fresh database to pass

File: sectionedservice_Test.php

**Comment by a22melst** [comment]
It seems like the tests in the file does not depend on each other.

**Comment by a22melst** [comment]
The array "entries" is empty when returned. I believe it should contain the data which have been updated.

**Comment by a22melst** [comment]
None of the tests are currently able to send data to sectionedservice.php.

**Comment by a22melst** [comment]
For the test updateListentrie the query is performed when using brom, but no output is generated.

**Comment by a22melst** [comment]
You need to have installed "Testing-Course" for the tests to work.
