### ISSUE TITLE
Final part of #14228

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14399]
## Description 
#14228 was fixed for the minutes, but all the other numbers are still wrong

## Job
Implement the same thing for months, days, hours, and seconds

**Comment by d22hanol** [comment]
this issue is on branch [g1-2024-v1-#14385#14228 ](https://github.com/HGustavs/LenaSYS/tree/g1-2024-v1-%2314385%231422)
with pull request [g1-2024-v1-#14385#14228](https://github.com/HGustavs/LenaSYS/compare/g1-2024-v1...g1-2024-v1-%2314385%2314228)
