### ISSUE TITLE
Make the test for "create an assignment" in duggaedservice-tests.php work

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14408]
The valueoutput seem to repeat the last field making the test fail.

Example:
value expected: {"debug":"NONE!","writeaccess":true,"coursecode":"IT118G","coursename":"Webbutveckling - datorgrafik","entries":[{"qname":"Bitdugga1"},{"qname":"Bitdugga2"},{"qname":"colordugga1"},{"qname":"colordugga2"},{"qname":"linjedugga1"},{"qname":"linjedugga2"},{"qname":"dugga1"},{"qname":"dugga2"},{"qname":"Quiz"},{"qname":"Rapport"},{"qname":"HTML CSS Testdugga"},{"qname":"Clipping masking testdugga"},{"qname":"test"}]}
value output: {"debug":"NONE!","writeaccess":true,"coursecode":"IT118G","coursename":"Webbutveckling - datorgrafik","entries":[{"qname":"Bitdugga1"},{"qname":"Bitdugga2"},{"qname":"colordugga1"},{"qname":"colordugga2"},{"qname":"linjedugga1"},{"qname":"linjedugga2"},{"qname":"dugga1"},{"qname":"dugga2"},{"qname":"Quiz"},{"qname":"Rapport"},{"qname":"HTML CSS Testdugga"},{"qname":"Clipping masking testdugga"},{"qname":"TestDugga1337"},{"qname":"TestDugga1337"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"}]}

file: duggaedservice-tests.php

**Comment by c22cargo** [comment]
This issue might require issue #14396 to be merged first, since it relies on the test file, which seems broken.

**Comment by c22cargo** [comment]
Every time the test is re-ran there appears more instances of {"qname":"test"}. They seem to duplicate. I suspect this issue has something to do with information being saved and then not deleted. Since the amount of {"qname":"test"} do not get reset when the server is restarted, the information is likely stored in the database.

**Comment by a22iliru** [comment]
This issue was fixed by linked pull request
