### ISSUE TITLE
Fix microservice getUid_ms not using a REST interface

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14407]
currently you would have to include the file and call the function in the file. The userid should be able to be retrieved via e.g. a GET-request.

filee: getUid_ms.php

**Comment by a22albjo** [comment]
Related resources:
Micro service implementations info:
- https://github.com/HGustavs/LenaSYS/blob/1f6fc81f85fd7cadc4652cf44f52bfab88e2e496/backend-models/microservices/duggaSys%20services/Potetial_micro_services.md#createNewListentrie
- https://github.com/HGustavs/LenaSYS/issues/14143

Original implementation of this file:
- https://github.com/HGustavs/LenaSYS/pull/14152

**Comment by a22albjo** [comment]
The file is discussed extensively here and is a good read for testing and implementation:
https://github.com/HGustavs/LenaSYS/issues/13679

**Comment by a22albjo** [comment]
The getUid is never called by itself from the frontend, it is only included in other backend services. It is probably the reason that it do not function as a isolated REST micro service for the moment.
The REST interface architecture is used for the most part to make the frontend talk to the backend services with the use of AJAXServices in dugga.js. 
More on this here: https://github.com/HGustavs/LenaSYS/blob/master/backend-models/service%20documentation/Communication%20used%20in%20the%20old%20style%20service%20files.pdf

With what i have written above in mind, is there a reason to make getUid in to an isolated micro service that is accessed with the help of a http request or is it more elegant to include it where needed as it is now?

**Comment by a22albjo** [comment]
The getUid does the following things:
- Gets the userID(uid) of the logged in user.
- Loggs that the getUid service has been used and from where.
- Assignes a variable $appuser with the uid, however the value is never used.

**Comment by a22albjo** [comment]
The variable $appuser is not used anywhere, it is assigned in another file as well but never used, i have removed all references to $appuser to avoid confusion. 

This results in that the getUid does the following things:

- Gets the userID(uid) of the logged in user.
- Loggs that the getUid service has been used and from where.
