### ISSUE TITLE
Make the test for "delete an assignment" in duggaedservice-tests.php  work. 

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14409]
The valueoutput seem to repeat the last field making the test fail.

Example:
value expected: {"debug":"NONE!","writeaccess":true,"coursecode":"IT118G","coursename":"Webbutveckling - datorgrafik","entries":[{"qname":"Bitdugga1"},{"qname":"Bitdugga2"},{"qname":"colordugga1"},{"qname":"colordugga2"},{"qname":"linjedugga1"},{"qname":"linjedugga2"},{"qname":"dugga1"},{"qname":"dugga2"},{"qname":"Quiz"},{"qname":"Rapport"},{"qname":"HTML CSS Testdugga"},{"qname":"Clipping masking testdugga"},{"qname":"test"}]}
value output: {"debug":"NONE!","writeaccess":true,"coursecode":"IT118G","coursename":"Webbutveckling - datorgrafik","entries":[{"qname":"Bitdugga1"},{"qname":"Bitdugga2"},{"qname":"colordugga1"},{"qname":"colordugga2"},{"qname":"linjedugga1"},{"qname":"linjedugga2"},{"qname":"dugga1"},{"qname":"dugga2"},{"qname":"Quiz"},{"qname":"Rapport"},{"qname":"HTML CSS Testdugga"},{"qname":"Clipping masking testdugga"},{"qname":"TestDugga1337"},{"qname":"TestDugga1337"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"}]}

file:  duggaedservice-tests.php

**Comment by a22melst** [comment]
The qid (quiz id) is not retrieved correctly, which hinders the deletion from taking place. When I manually insert a row to quiz, comment out the 'query-before-test-1' option and simply hard-code 'qid' to the correct id, it seems to work (The deletion takes place and the value output doesn't repeat {"qname":"test"} ).

**Comment by a22melst** [comment]
Using the following syntax the deletion takes place, but the value output still repeats {"qname":"test"}, causing the test to fail.

'qid' => '<!query-before-test-1!><*[0]["id"]*>',

**Comment by a22melst** [comment]
After reinstalling the database the issue now is that the JSON-element {"qname":"test"} or {"qname":"TestDugga1337"} doesn't appear in the output at all.
