### ISSUE TITLE
Research and create microservice reorderListentries

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14419]
file: sectionedservice.php

Se: https://github.com/search?q=repo%3AHGustavs%2FLenaSYS%20reorderListentries&type=code

**Comment by a22eddpe** [comment]
DuggaSys>sectionedservice.php

**Comment by a22eddpe** [comment]
### reorderListentries
Uses the services __updateTableListentries__ to change the content of these columns:

**Comment by a22eddpe** [comment]
need to create a new ms file in DuggaSys>microservices>sectionedService>

**Comment by a22eddpe** [comment]
connected file createListentrie_ms.php

**Comment by a22eddpe** [comment]
a suggestion on how to implement the service "updateTableListentries" 
$query = $pdo->prepare("CALL updateTableListentries(:courseid, :coursevers, :pos, :moment)");
$query->bindParam(':courseid', $courseid);
$query->bindParam(':coursevers', $coursevers);
$query->bindParam(':pos', $pos);
$query->bindParam(':moment', $moment);

**Comment by a22eddpe** [comment]
include 					foreach ($orderarr as $key => $value) {
						$armin=explode("XX",$value);
						$query = $pdo->prepare("UPDATE listentries set pos=:pos,moment=:moment WHERE lid=:lid;");
						$query->bindParam(':lid', $armin[1]);
						$query->bindParam(':pos', $armin[0]);
						$query->bindParam(':moment', $armin[2]);
                     

						if(!$query->execute()) {
							$error=$query->errorInfo();
							$debug="Error updating entries".$error[2];
						}
					}

**Comment by a22eddpe** [comment]
This code from sectionedservice.php compairs $opt to REORDER. If it equals 0, I need to use if for my reorder-file. 		    	
} else if(strcmp($opt,"REORDER")===0) {
					$orderarr=explode(",",$order);

**Comment by a22eddpe** [comment]
updateListentrie
Uses service __selectFromTableListentries__ to _get_ information it requires from __listentries__.
Uses service __createNewCodeexample__ to makes _inserts_ into the table __codeexample__.
Uses the services __updateTableListentries__ to change the content of these columns:
- highscoremode
- gradesystem
- moment
- entryname
- kind
- link
- visible
- comments
- groupKind
- feedbackenabled
- feedbackquestion

Uses service __insertIntoTableList__ to makes _inserts_ into the table __list__.
