### ISSUE TITLE
Make the test for "update an assignment" in duggaedservice-tests.php work. 

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14410]
The valueoutput seem to repeat the last field making the test fail.

Example:
value expected: {"debug":"NONE!","writeaccess":true,"coursecode":"IT118G","coursename":"Webbutveckling - datorgrafik","entries":[{"qname":"Bitdugga1"},{"qname":"Bitdugga2"},{"qname":"colordugga1"},{"qname":"colordugga2"},{"qname":"linjedugga1"},{"qname":"linjedugga2"},{"qname":"dugga1"},{"qname":"dugga2"},{"qname":"Quiz"},{"qname":"Rapport"},{"qname":"HTML CSS Testdugga"},{"qname":"Clipping masking testdugga"},{"qname":"test"}]}
value output: {"debug":"NONE!","writeaccess":true,"coursecode":"IT118G","coursename":"Webbutveckling - datorgrafik","entries":[{"qname":"Bitdugga1"},{"qname":"Bitdugga2"},{"qname":"colordugga1"},{"qname":"colordugga2"},{"qname":"linjedugga1"},{"qname":"linjedugga2"},{"qname":"dugga1"},{"qname":"dugga2"},{"qname":"Quiz"},{"qname":"Rapport"},{"qname":"HTML CSS Testdugga"},{"qname":"Clipping masking testdugga"},{"qname":"TestDugga1337"},{"qname":"TestDugga1337"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"},{"qname":"test"}]}

file: duggaedservice_Tests.php

**Comment by a22fokol** [comment]
I could not found the file "duggaedservice-tests.php" after all my search  in the Network Panel. It means it is impossible for me to solve the issue

**Comment by a22iliru** [comment]
@a22fokol is referencing to the network panel in inspect element. The file does exist in the repo
