### ISSUE TITLE
Boxtitles not showing when not logged in

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#1441]
![ett](https://cloud.githubusercontent.com/assets/11722176/7587131/428db5dc-f8b4-11e4-8469-743216cc8270.png)
Only displays numbers when not logged in.

**Comment by HGustavs** [comment]
I wondered about that........ how can that happen? I would say that it is a bug.... and an important one to fix?

**Comment by b12alela** [comment]
This was due to a mixup in the boxmenucreation function, there is an array with all the values for the boxes. There the wrong value was called from the array, which made it display a number instead of the boxtitle. Pullrequest is in for this. solved etc.

**Comment by f12danjo** [comment]
Fixed by: [#1489](https://github.com/HGustavs/LenaSYS/pull/1489).
