### ISSUE TITLE
Research and create microservice updateCourseVersion_sectioned

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14423]
file: sectionedservice.php

Se: https://github.com/search?q=repo%3AHGustavs%2FLenaSYS+updateCourseVersion_sectioned&type=code

**Comment by c22cargo** [comment]
The MS is supposed to use another MS, ```setActiveCourseversion``` which hasn't been created. However it seems that ```setActiveCourseversion``` and ```setAsActiveCourse``` has the same functionality. I don't know what the difference is. The latter has been implemented, so maybe this MS should use that one instead.
