### ISSUE TITLE
CodeViewer deletes first php tag

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#1442]
![1](https://cloud.githubusercontent.com/assets/11722176/7587543/699b05e6-f8b7-11e4-9569-3718caafc95a.png)
The ending tag is displayed as normal though.

**Comment by HGustavs** [comment]
Question is whether it is there and just not shown or if it is really lost.

I suspect that it is there?
If so, have we translated the ? to a &#35;63; entity?

**Comment by a13alfbe** [comment]
FIxed this bug, waiting on the weekly branch to be created. 
Missing && tokens[i+1].val != "?" in the statement on line 1295 in codeviewer.js

**Comment by f12danjo** [comment]
Fixed by [#1485](https://github.com/HGustavs/LenaSYS/pull/1485).
