### ISSUE TITLE
Research and create microservice updateListentrie

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14420]
file: sectionedservice.php

See: https://github.com/search?q=repo%3AHGustavs%2FLenaSYS%20updateListentrie&type=code

**Comment by a22marca** [comment]
I've identified the code to be located at line 302.
The code matches the description of the database services used: selectFromTableListentries, createNewCodeexample and updateTableListentries.

Will proceed with creating the file and implementing the code as a microservice

**Comment by a22marca** [comment]
A call with the opt "UPDATE" using ajax is made from within the function `updateItem()` in sectioned.js
```
function updateItem() {
  console.log("Running updateItem");
  AJAXService("UPDATE", prepareItem(), "SECTION");
```

It is called using the function `AJAXService()` with the kind "SECTION".

The request to sectionedservice.php is made within the function AJAXService" for the case where  kind contains "SECTION":
```
	}else if(kind=="SECTION"){		
		$.ajax({
		url: "sectionedservice.php",
		type: "POST",
		data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
		dataType: "json",
		success: returnedSection
	});
```

A issue here is that this ajax call is not only made for the "UPDATE" opt, but for others also. We probably need split this part into several different calls depending on the opt. For example the "DEL" opt also uses the ajax call when `kind=="SECTION"`.

**Comment by a22marca** [comment]
To properly integrate and test this microservice, the retrieiveSectionedService.php should be implemented. This is because the ajax call expects a response from the service containing data.

**Comment by a22marca** [comment]
A way to implement a selection for the different opts as mentioned in one of the previous comments, can be found in a comment i made for another [issue](https://github.com/HGustavs/LenaSYS/pull/14515#issuecomment-2051631661).

**Comment by a22marca** [comment]
Using this code, it is possible to test the microservice via e.g. changing the name of a dugga.

```
	}else if(kind=="SECTION"){		
		if(opt=="UPDATE"){
			$.ajax({
				url: "../DuggaSys/microservices/sectionedService/updateListentrie_ms.php",
				type: "POST",
				data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
				dataType: "json",
				success: function(){console.log("UPDATELISTENTRIE TEST")}
			});
		}else{
			$.ajax({
				url: "sectionedservice.php",
				type: "POST",
				data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
				dataType: "json",
				success: returnedSection
			});
		}
```
This is not a fully functional integration, you need to refresh the page after e.g. updating the name of a dugga. The reason for this is that normally sectionedservice.php returns its data array, which can update the page. To be able to do this with the microservice we need to implement the retrieiveSectionedService_ms first, as mentioned previously.
