### ISSUE TITLE
Research and create microservice changeActiveCourseVersion_sectioned

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14424]
file: sectionedservice.php

Se: https://github.com/search?q=repo%3AHGustavs%2FLenaSYS+changeActiveCourseVersion_sectioned&type=code

**Comment by a22melst** [comment]
There exists two opts for changing the active version of a course inside of sectionedservice.php, "CHGVERS" and "UPDATEVRS". I will continue my research to find if there is a difference between the two, or if one can be deleted.

**Comment by a22melst** [comment]
A difference between this ms and the others I have mentioned seems to be that the variable "makeactive" does not need a value of 3 for this ms to work.

**Comment by a22melst** [comment]
[linktest](https://github.com/HGustavs/LenaSYS/blob/d663ef4fd4f5d138017e7ce456bed6dce1350e15/backend-models/microservices/duggaSys%20services/Potential_micro_services.md#changeactivecourseversion_sectionedl)
