### ISSUE TITLE
Research and create microservice getUserDuggaFeedback

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14434]
file: sectionedservice.php

See: https://github.com/search?q=repo%3AHGustavs%2FLenaSYS%20getUserDuggaFeedback&type=code

**Comment by f22linbe** [comment]
Retrives all information
Uses service __selectFromTableUserduggafeedback__ to _get_ information it requires from __userduggafeedback__.

Retrives the average score
Uses service __selectFromTableUserduggafeedback__ to _get_ information it requires from __userduggafeedback__.
