### ISSUE TITLE
Fix bug in dugga.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14448]
File: showDugga.php 
Recreate problem: Go to http://localhost/LenaSYS/DuggaSys/showDugga.php?did=9&courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732&moment=2014&segment=2013&highscoremode=1&comment=null&deadline=2015-02-19%2015:30:00&cid=2
Press a radio input and press save, nothing happens and you will get an error sayng that function uploadFile() is not defined. 
To fix this add this to the other scripts in the html <head> tagg (line 24 - 28):
    <script src="../DuggaSys/templates/svg-dugga.js"></script>
This will make showDugga.php have access to the necessary javascript file.
Expected behavior: A popup should be shown with ex a hash, hash password and possibility to copy receipt(as shown in the image).
![image](https://github.com/HGustavs/LenaSYS/assets/164884946/7bb1620c-a4d7-4017-b491-b6af7e04ee2f)

**Comment by a22yifwa** [comment]
I logged in to this webpage with brom username. As long as the LenaSYS webpage is logged in with the account, dugga will not be displayed.
![dugganotshow](https://github.com/HGustavs/LenaSYS/assets/129604134/1548c2c7-f20c-40a7-af71-400fcf650114)


Dugga only displays on pages without login.
![Screenshot 2024-04-11 202616](https://github.com/HGustavs/LenaSYS/assets/129604134/5bf595ed-45ef-4dac-b866-72db69cbdf3d)

**Comment by a22yifwa** [comment]
The problem now is that the dugga won't show up at all, so there's no chance of saving the dugga.

**Comment by a22yifwa** [comment]
I'm now researching why no dugga shows up.

**Comment by c22cargo** [comment]
A small note. When logged in as brom the dugga won't show up. I logged out and could see the dugga. This is probably not specific to brom.

**Comment by c22cargo** [comment]
Issue seems to already have been fixed. It works now.
