### ISSUE TITLE
Changing properties of one test, changes all tests with same link

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14447]
When changing a deadline for a user created test in “Webbutveckling - Datorgrafik”, all deadlines for all tests recently created by the user are changed, IF they have the same link value. This is due to a query in sectionedservice.php (line 384 to 387), where the id is set to link, therefore, all tests with the same link value will be updated to the edited deadline. This code can be seen below:
```
$deadlinequery = $pdo->prepare("UPDATE quiz SET deadline=:deadline, 
relativedeadline=:relativedeadline WHERE id=:link;");
$deadlinequery->bindParam(':deadline',$deadline);
$deadlinequery->bindParam(':relativedeadline',$relativedeadline);
$deadlinequery->bindParam(':link',$link);
```

Make sure that you change the query to only select the correct item. If its not possible to uniquely select a single test. Create a comment detailing why, and what steps can be taken to add a unique identifier to the entries. (Maybe naming them `new test 1`, `new test 2`... `new test n`. And then selecting on the name. 

But first, try to fix the issue if it is possible.  

Derived from #14371

**Comment by a22karja** [comment]
Jag har kommit fram till att just nu som databasen är uppbyggt kan man inte få loss deadlinen från att vara kopplad till databas.quiz.
Problemet är att deadlinen är kopplad till databas.quiz och inte databas.listentries. Detta gör att varje element med deadline i 

LenaSYS/DuggaSys/sectioned.php?courseid=2&coursename=Webbutveckling - datorgrafik&coursevers=97732  
(Hemsidan)
![issue 14447 pic 1](https://github.com/HGustavs/LenaSYS/assets/129260794/49fd7810-85f2-4146-a63c-768f262758e6)
Figur 1
Kommer alltid hämta deadline från databas.quiz. 

Detta i säg kommer göra att utmärkta elementen kommer vara kopplade till samma deadline om dom är kopplade till en link på hemsidan

![issue 14447 figur 2](https://github.com/HGustavs/LenaSYS/assets/129260794/b7657763-f0e3-4e55-a81d-92eaeb5f0821)
Figur 2
(Links på hemsidan är sparade i databas.quiz). 
Så för att ha en unik deadline för utmärkta elementen i figur 1 på hemsidan så måste deadline vara sparad i databas.listentries. Detta kan dock ses som redundancy och bör då undvikas

**Comment by b22marah** [comment]
@HGustavs What do you think we should do regarding this issue?

**Comment by andras-marki** [comment]
I would say the two dugga should be able to have different deadlines. So you probably need to adjust the information design, as we really don't want to have interconnected deadlines where they shouldn't be.

It seems like, for example, for the re-examination of a dugga, we would still be able to use the same link (if that's what Bitdugga1 is about); hence, having non-interconnected deadlines is preferred.

**Comment by HGustavs** [comment]
I think that from a refactoring standpoint we have little recourse to make changes.
We cannot change the meaning of items or remove items from the database only add. So I think that the current way of doing things is the only way to handle this type of problem.

Currently it is done in the same way as in canvas. We use double entries for re-examinations.

I am unsure if it is actual redundancy or only looks like redundancy.

In older version both interfaces used the same data for the same deadline but it appeared in two places in the interface. So in that older version it only looked like redundancy but it instead was same information accessed in two dialogs.
