### ISSUE TITLE
Fix bug in courseedservice.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14452]
To reproduce the bug:
Login as 
user: brom
password: password
Edit the first course "Datorns grunder" by pressing the settings icon and change visibility to deleted, save and refresh the page. All courses are now gone and it seems that we have to reinstall lenasys to get the courses back.

Error that is recived from the sevice call to courseedservice.php:
Fatal error
Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (albin.filelink, CONSTRAINT filelink_ibfk_1 FOREIGN KEY (cid) REFERENCES course (cid)) in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/courseedservice.php:574
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/courseedservice.php(574): PDOStatement-&gt;execute()
#1 {main}
  thrown in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/courseedservice.php
on line 574

File: courseedservice.php

**Comment by c22mohel** [comment]
This bug appears to happen when you try to delete any course not just the "Datorns grunder" one

**Comment by c22mohel** [comment]
When deleting newly created courses this does not happen for some reason

**Comment by c22mohel** [comment]
It does not remove the courses from the database. It appears that coursedsrvice.php fails to retrieve the courses.

**Comment by c22mohel** [comment]
Most likely this is a foreign key constraint fails. There is a foreign key that  uses the rows on course. this makes deleting a course impossible. 
But this should not be a problem since when deleting a course, the course should not actually be deleted but the visibility should change. 
At the moment it is unclear why newly created course get deleted from the database.

**Comment by c22mohel** [comment]
All tables that use "cid" and their subtables:
all these need to be deleted for this to work 

Subparts
partresult - from subparts

codeexample
impwordlist - from codeexample
box - from codeexample
improw - from box

listentries
user_participant - from listentries

useranswer

timesheet

quiz
variant - from quiz

vers

filelink

programcourse

user_course
course_req
