### ISSUE TITLE
Update guide for naming potential microservices according to new standard (CRUD)

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14467]
CRUD stands for the four basic operations for managing data in applications and databases: Create, Read, Update, Delete.

Create:

- Purpose: To create or add new records in a database.
- Methods:
  - In a web application or API: Use the POST request to send data to be created.
  - In SQL databases: Use the 'INSERT' command to add new rows to a table.

Read:

- Purpose: To fetch or read data from a database. This can include retrieving a specific record or a list of records based on certain criteria.
- Methods:
  - In web applications or APIs: Use the GET request to request data.
  - In SQL databases: Use the 'SELECT' command to retrieve data from one or more tables.

Update:

- Purpose: To update existing records in a database with new or modified data.
- Methods:
  - In web applications or APIs: Use PUT or PATCH requests to send updates.
  - In SQL databases: Use the 'UPDATE' command to change data in existing rows.

Delete:

- Purpose: To delete records from a database.
- Methods:
  - In web applications or APIs: Use the DELETE request to remove data.
  - In SQL databases: Use the 'DELETE' command to remove rows from a table.

Therefore, updates must be made to the documentation below:
https://github.com/HGustavs/LenaSYS/blob/master/backend-models/microservices/duggaSys%20services/Potential_micro_services.md

For example:

GET → READ
SET → UPDATE
REMOVE → DELETE

**Comment by f22linhe** [comment]
Referar till issue #13044

**Comment by f22linhe** [comment]
This issue has unofficially been merged with issue #14599 (Merge Potential_micro_services.md and Database_related_micro_services into 1 file). Documentation regarding what all the microservices should be named, as well as the merging of query information—i.e., updating and transferring all information about queries from Database_related_micro_services.md to Potential_micro_services.md—is ongoing.

New link for the microservice documentation (updated the filename of the documentation) :
https://github.com/HGustavs/LenaSYS/blob/master/backend-models/microservices/duggaSys%20services/Microservices.md.

**Comment by f22linhe** [comment]
The majority of the microservices have now been implemented although, no renaming of the microservices will take place until all ms are implemented.

**Comment by f22linhe** [comment]
This issue can be considered resolved since the documentation of all microservices is ongoing, and all microservices now have names that align with the new naming convention. Any new microservices that arise will be named in accordance with the new convention right away. As this issue also evolved over time into one concerning comprehensive documentation for the microservices, it is therefore merged with the issue Document information about all microservices #15515. This issue should therefore be closed.
