### ISSUE TITLE
[research] Global variables with single use

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#14474]
## Description 
There are many global variables in diagram.js that are only used in one or two places in the code. 
Using global variables makes the code more difficult to read and follow.

## Job
Find and list global variables that could be changed into local variables / functions that set global variables that could return them.
Describe why each item is listed.

**Comment by a22vioja** [comment]
These are the global variables that are never used or used only in one function, I added a comment to each of them. The number in the parentheses is an amount of uses :

var defs = "";   (1) never used
var startTop, startLeft; (1) never used
var hasRecursion = false;  (1) never used
var dblClickInterval = 350;  (5) used only in “ddown”, could be local variable 
var mousePressed; (5)  used in two functions, but maybe the state and behavior can be encapsulated related to the mouse press within an object or a class.
var camera = new Point(0, 0);  (1) never used
var lastMousePosCoords = new Point(0, 0);  - used two times same name in declaration, used in two functions, 6)
var zoomAllowed = true;  (3) used only in “mweel”, could be local variable 
lastZoomPos - used two times with same name in declaration, used in two functions
lastMousePosCoords  (8) - used two times same name in declaration, used in two functions
const elementwidth = 200;  (1) never used
const elementheight = 50;    (1) never used
selectedColor (3) never used

used only in “screenToDiagramCoordinates” function, could be local variables or refactor the if statements for setting zoomX to use a switch statement or an object mapping for better readability and maintainability.
const zoom1_25 = 0.36;
const zoom1_5 = 0.555;
const zoom2 = 0.75;
const zoom4 = 0.9375;
const zoom0_75 = -0.775;
const zoom0_5 = -3;
const zoom0_25 = -15.01;

var errorActive = false; (6) used only in “toggleErrorCheck()” function, can be local
const maxDeltaBeforeExceeded = 2; (5) used only in “calculateDeltaExceeded()” function, can be local
var propFieldState = false; (4) used only in ”propFieldSelected” function, can be local
var previousMouseMode; (1) never used

These const global variables are used one time each, but I do not have an idea if this could be organized in other way 
const subMenuEntity (1) 
const subMenuRelation (1)
const subMenuUMLstate (1)
const subMenuSequence (2)

var diagramToLoad = ""; (1) never used
var cvers = ""; (1) never used
var diagramToLoadContent = ""; (1) never used
