### ISSUE TITLE
[research] Hard coded zoom

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#14480]
## Description
The zoom functionality is hard coded and extremely verbose. 
Increasing readability will help solve the many bugs related to the zoom functionality.

## Job
Find out how it works and what parts could be broken down into smaller functions.
Make a list of functions / parts of code and describe common patterns that could be broken out.

**Comment by a22wilas** [comment]
### Zoom function documentation
In the documentation, the different zoom functions and their purposes will be explained.
Both explanations and code examples will be given for how to improve the handling of the zoom functions,
and suggestions for how to improve code visibility for a programmer will be suggested.  

The zoom functions are triggered by onclicks on the zoom buttons or by event handling on scrolling the mouse wheel. There are three different zoom functions that handle different types of zooms, zoomin(), zoomout() and zoomreset().

`div class="diagramZoomIcons" onclick='zoomin();'`
`div class="diagramZoomIcons" onclick='zoomout();`
`div class="diagramZoomIcons" onclick="zoomreset();`


The zoom functions names should be modified to follow name standards. Like for example zoomIn(), zoomOut() and zoomReset() would be better and would create more clarity for a programmer. 

Keybinds can also be used to trigger zoom functions.
`ZOOM_IN: {key: "+", ctrl: true, meta: true},`
`ZOOM_OUT: {key: "-", ctrl: true, meta: true},`
`ZOOM_RESET: {key: "0", ctrl: true, meta: true},`


Variables that either hold numeric values or points for x and y positions are used for the zoom functions. Most of them are used to check mouse pointer position and change the camera so it aligns with the pointer.

Variables:
`var desiredZoomfact = 1.0;`
`var zoomfact = 1.0;`
`var scrollx = 100;`
`var scrolly = 100;`
`var zoomOrigo = new Point(0, 0);`
`var camera = new Point(0, 0);`
`var lastZoomPos = new Point(0, 0);`
`var lastMousePosCoords = new Point(0, 0);`
`var zoomAllowed = true;`
`var lastZoomPos = new Point(0, 0);`
`var lastMousePosCoords = new Point(0, 0);`

As shown above, there are two variables that get declared twice. Both lastZoomPos and lastMousePosCoords would only need to be declared ones. Some variable names should be modified to follow programming standards: zoomfact and desiredZoomfact to zoomFact and desiredZoomFact.

Both zoomin and zoomout checks if the function was triggered by a mouse event (scrolling on the mouse scroll wheel) or if one of the zoom buttons on the application was pressed. Both functions could be optimized in multiple ways to improve both visibility and future implementations.

```
zoomin(){
    if (!scrollEvent) {
        if (zoomfact < 4) {
    }else if(zoomfact < 4.0){
    }
}
```
```
zoomout(){
    if (!scrollEvent) {
        if (zoomfact > 0.25) {
    }else if(zoomfact > 0.25){
    }
}
```
This is the code for the selection that checks if a mouse listener was active or not. For the selection the variable zoomfact is checked against values, this is unnecessary. Both “if (zoomfact < 4)” and “if (zoomfact > 0.25)” could be removed and both else if could be remade to just else as there are no more selection statements. 


```
var mouseCoordinates = screenToDiagramCoordinates(scrollEvent.clientX, scrollEvent.clientY);
if (scrollEvent.clientX != lastZoomPos.x || scrollEvent.clientY != lastZoomPos.y) {             
var delta = {
                x: mouseCoordinates.x - zoomOrigo.x,
                y: mouseCoordinates.y - zoomOrigo.y
            }
scrollx = scrollx / zoomfact;
…
} else if (scrollEvent.clientX == lastZoomPos.x && scrollEvent.clientY == lastZoomPos.y) {
        zoomOrigo.x = lastMousePosCoords.x;
        zoomOrigo.y = lastMousePosCoords.y;
}

```
This code runs if a mouse event was triggering the zoomin or zoomout functions. The code makes sure the position of the camera will zoom in on the pointer of the mouse. This code in both functions are identical and does the same thing. Would be advised to create a new function with this code.

```
function updateZoom(scrollEvent, zoomTowardsMouse) {
    var mouseCoordinates = zoomTowardsMouse ? screenToDiagramCoordinates(scrollEvent.clientX, scrollEvent.clientY) : zoomOrigo;
    var delta = {
        x: mouseCoordinates.x - zoomOrigo.x,
        y: mouseCoordinates.y - zoomOrigo.y
    };
    scrollx = scrollx / zoomfact;
    …
    lastZoomPos.x = scrollEvent.clientX;
    lastZoomPos.y = scrollEvent.clientY;
}
```
Example code to illustrate how a function could be made that does the calculations for the camera and mouse pointer. The else if condition has been replaced with a ternary operator to make it more versatile, as it now works as a boolean with true or false. This will be true for both zoomin and zoomout and “mouseCoordinates” will never get the value zoomOrigo in this implementation of the application but could be used in future implementations. 
This function could be called from the else in the zoomin/zoomout functions. 

```
function zoomin(scrollEvent = undefined) {
    if (!scrollEvent) {
    } else {
        updateZoom(scrollEvent, true);
    }
}
```

In both functions, a switch is used to check the value of the variable zoomfact and give it a new value. In zoomin() the switch changes zoomfact to a higher value like a staircase while zoomout() lowers the value. Both use the same values but in reverse orders. This could instead be accomplished with an array and an algorithm. This makes it possible to get the switch out of the main zoom functions and create a new function where this calculation happens. 

```
switch (zoomfact) {
    case 0.25:
        zoomfact = 0.5;
        break;
    case 0.5:
        zoomfact = 0.75;
        break;
    case 0.75:
        zoomfact = 1.0;
        break;
    case 1.0:
        zoomfact = 1.25;
        break;
    case 1.25:
        zoomfact = 1.5;
        break;
    case 1.5:
        zoomfact = 2.0;
        break;
    case 2.0:
        zoomfact = 4.0;
}
```
This depicts the switch that is used in zoomin()

At the end of both functions, some more calculations are made, and four more functions are called. This happens in both functions with the same code. This could instead be added to the new function that holds the calculation for the zoomfact, making both zoomin() and zoomout() a lot smaller and easier to understand. 

```
function updateZoomFactors(zoomIn) {
    const zoomFactors = [0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0, 4.0];
    const currentIndex = zoomFactors.indexOf(zoomfact);
    if (zoomIn) {
        zoomfact = currentIndex < zoomFactors.length - 1 ? zoomFactors[currentIndex + 1] : zoomfact;
    } else {
        zoomfact = currentIndex > 0 ? zoomFactors[currentIndex - 1] : zoomfact;
    }
    document.getElementById("zoom-message").innerHTML = zoomfact + "x";
    scrollx = scrollx * zoomfact;
    scrolly = scrolly * zoomfact;
    updateGridSize();
    updateA4Size();
    showdata();
    drawRulerBars(scrollx, scrolly);
}

updateZoomFactors(true);
updateZoomFactors(false);

```
Example how this function could be coded. The parameter zoomIn is a boolean, where zoomin() sends true and zoomin() false at the end of their functions. By remaking the switch into an array, it will be easier to add more values, as code only needs to be added at one place. 

Zoom variables for handling camera position:
`const zoom1_25 = 0.36;`
`const zoom1_5 = 0.555;`
`const zoom2 = 0.75;`
`const zoom4 = 0.9375;`
`const zoom0_75 = -0.775;`
`const zoom0_5 = -3;`
`const zoom0_25 = -15.01;`

```
function screenToDiagramCoordinates(mouseX, mouseY) {
    var zoomX = 0;

    // ZOOM IN
    if (zoomfact == 1.25) zoomX = zoom1_25;
    if (zoomfact == 1.5) zoomX = zoom1_5;
    …
	return new Point(Math.round((mouseX / zoomfact - scrollx) + zoomX * scrollx + 2 + zoomOrigo.x), // the 2 makes mouse hover over container
        Math.round((mouseY / zoomfact - scrolly) + zoomX * scrolly + zoomOrigo.y)
    );
}
```
An algorithm is used to make sure the zoom goes onto the mouse pointer or into the middle of the screen. This happens in the screenToDiagramCoordinates function. One of the variables that are used to do this calculation are zoomX. The value of zoomX depends on the value of the zoomfact variable. As can be seen from the code above, there are multiple const variables that hold different values that are used to give zoomX different values. These const variables are not used for anything else and can be hard to both find and understand. As they are not used for anything else, it would be better suited to remove the variables and give zoomX the values directly. For every different zoomfact value an if selection is used to give zoomX a value, while this works using multiple if selection in a row should normally be avoided. A better way to do this would be to use a switch with zoomfact value as the different cases.

```
function screenToDiagramCoordinates(mouseX, mouseY) {
    var zoomX = 0;
    // Calculate zoomX based on zoom factor
    switch (zoomfact) {
        case 1.25:
            zoomX = 0.36;
            break;
        case 1.5:
            zoomX = 0.555;
            break;
        …
    }
}
```
This code is an example of how this function could be altered to both make the multiple if selection into a switch and also remove the const variables and give zoomX directly the values.

These are the changes that are easy to implement and do not impair other parts of the code. More changes could be done to make the zoom function better but would need parts of the code to be changed that involve other parts of the application.
