### ISSUE TITLE
 Create microservice logUserEvent_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14492]
file: basic.php, function logUserEvent()

Related to: [issue#14150](https://github.com/HGustavs/LenaSYS/issues/14150)

**Comment by a22melst** [comment]
Branch for this issue:
https://github.com/HGustavs/LenaSYS/tree/g2-2024-v2-issue%2314492

**Comment by a22melst** [comment]
As was done for issue #14493, this issue will be put on hold until the group has decided whether the microservice should be used through a function call or by making a POST request to it.

**Comment by c20juler** [comment]
created microservice, implemented to be used through a function call.
