### ISSUE TITLE
503 Service error from ajax calls

### ISSUE THREAD

**Issue by a22oscja** [HGustavs/LenaSYS#14495]
While testing for another issue, the 503 service error would repeatedly appear. The most likely culprit would be too many calls being executed in some form, this is further reinforced by that fact that code that worked before would cease functioning (such as our weekly branch).

As we were working with the github API at the time and the alert that is given is sent by gitfetchservice.php line 229, this could also be related to too many requests being sent to the github API as a result, where the limit, through some googling, appears to be 60 requests per hour.

**Comment by a22karja** [comment]
Anledningen till att det blir ett error är att utan github token har hemsidan ett max antal fetch requests den får göra. detta är 60 i timmen. Det är därför man får ett error. Att det är ett 503 error är dock inkorrekt det är bara att om koden inte får tag på data så antar den att det är ett 503 error
