### ISSUE TITLE
Create test: Create active users in showDuggaservice_test.php

### ISSUE THREAD

**Issue by a22albjo** [HGustavs/LenaSYS#14501]
Create test: Create active users in showDuggaservice_test.php

There is a commented out version of this test more or less finished in showDuggaservice_test.php, to resolve this issue gather expected output from the service and make this test work as intended.

**Comment by a22eddpe** [comment]
The test can have something thing to do with:
http://localhost/LenaSYS/DuggaSys/accessed.php?courseid=1&coursevers=45656

**Comment by a22eddpe** [comment]
first and second test passed but the third failed.

**Comment by a22eddpe** [comment]
expected value:  {"debug":"[Guest] Missing hash\/password\/variant!","param":"
what I got: {"debug":"[Superuser] Could not load dugga! no userAnswer entries with moment: UNK \nline 338 showDuggaservice.php","param":"

**Comment by a22eddpe** [comment]
Värdet för "debug" nyckeln är olika i value expected och value output. Value expected indikerar att det saknas hash, lösenord eller variant, medandå value output tyder på att det uppstod ett problem vid laddningen av "dugga"

**Comment by a22eddpe** [comment]
Can not solve this as intended. Either I solve it as it says in showDuggaservise-test.md and change the hash and opt too tj7dh2nb and UPDATEAU and delete password and username. But then the first test will fail and the secound and third will succeed. Or I change expected output.

**Comment by a22eddpe** [comment]
The test is to add a user and match the expected value with the value output. There are two ways to kind of solve this issue. Either you kind of follow the instructions in showduggaservise_test.md or you don't. If you don't follow the instructions in that file, you need too change the expected value to make it match with the value output you get by making research on how to do it (it can be quite complicated. You will need too look in showduggaedservice on why the dugga is not uploading and if it's missing any value or what the issue maight be. You will also need too add this:
username' => 'brom',
'password' => 'password',
If you choose too do this alternative, you will have three tests that works at the same time which is what we want. 
The other alternative is too kind of follow the instructions in the showduggaservise_test.md file. Then you need too change the hash and opt to tj7dhnb and also UPDATEAU. You will also need too delete password and username. The downside of this alternativ is that test1 will never work. (Test 1 is a test on the username and password which you had too delete).

**Comment by f22linhe** [comment]
Updated issue: Fix test 'Create active users' in showDuggaservice_test.php #15104
