### ISSUE TITLE
Fix microservices linking to wrong files

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14516]
From a22eddape: 
![image](https://github.com/HGustavs/LenaSYS/assets/164884946/67b6af70-9f45-4930-b518-37567b61a831)

File: any files linking incorrectly

**Comment by c22cargo** [comment]
It seems that at least "createListentrie_ms.php", "changeActiveCourseVersion_sectioned_ms.php", and "createCourseVersion_ms.php" have incorrect include paths.
Many also use different formats, some use parentheses around the include while others do not. Many use both formats in the same file. Preferably a single standard should be used.
There also seems to be many instances where "include" is used when "include_once" should be used instead.
Many files also have "?>" at the end of the file. That should not be there when the file only consists of php.

A branch will be created to fix this after the weekly merge.
