### ISSUE TITLE
Store relevant github database entries for codeexample

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14525]
It was determined that the scope of [#14370](https://github.com/HGustavs/LenaSYS/issues/14370) was too large, therefor the filefetching and creation of db entries has been split up into 2 separate issues. Assuming that the issue has been solved, and files can be fetched from github when clicking save.

The following should be saved to the sqlite db.
![236859351-088624a4-bd36-4e12-8b5d-4635d922543e](https://github.com/HGustavs/LenaSYS/assets/129264968/89397251-8d34-4389-bad3-e21c15cbf15d)

**Comment by d22mikwe** [comment]
Talked with william and a different issue is to be made to improve readability, error handling, input handling, commenting and general effectiveness. Also make sure it doesnt overwrite data etc
