### ISSUE TITLE
Import downloaded github code example into website

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14532]
After a code example has been downloaded ([#14370](https://github.com/HGustavs/LenaSYS/issues/14370)), and the proper records have been created in the sqlite db ([#14525](https://github.com/HGustavs/LenaSYS/issues/14525)). Ensure that the code example can be viewed properly in the website.

**Comment by d22mikwe** [comment]
TODO: Research if theres anything missing before being able to import into website

**Comment by d22mikwe** [comment]
Name kan sparas för att lägga en titel på kodexemplet?

codeviewer.js
updateExample() - uppdaterar kodexempel titel/section titel. 
validateForm("editSection"). Uppdaterar namnet på containern.
updateTemplate(). - pushar kodexmplet till webbsidan

**Comment by d22mikwe** [comment]
We have encountered alot of problems with this. Will update after some more research with concrete examples.

**Comment by d22mikwe** [comment]
Successfully added files into fileLink.
Successfully fetched codeexamples info when clicking github icon to be processed in sectioned.js and sectioned.php

**Comment by d22mikwe** [comment]
Successfully updated codeexample.

New issue:
need to insert boxes in box table in mysql db.

**Comment by d22mikwe** [comment]
Successfully inserted into box table.
Files can now be viewed in codeviewers codeexample.
