### ISSUE TITLE
Dont show tooltip if there is no github repo

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14533]
If there is no github repo saved for the current course, the tooltip should not be shown.
![bild](https://github.com/HGustavs/LenaSYS/assets/129264968/953f9297-6992-4cd7-96fa-12b0de9c8534)

This tooltip was added in #14352

There are also several bugs with this feature. If you find one that is an easy fix, simply make a comment here of your findings and fix it.

**Comment by a22maxra** [comment]
Every course that does not have a github repo shows 9:28:31 as the last fetch time, atleast for me at this point in time.

The last fetched time is passed with .$_SESSION['lastFetchTime']

**Comment by a22maxra** [comment]
Added check if 'courseGitURL' (column in course table) is set for the course.
```
// Check if there is a 'courseGitURL' set for the course
$checkIfGithubURL = $row['courseGitURL'];
if ($checkIfGithubURL) {
$updateTime = $row['updated'];
} else { $updateTime = "No Github URL set"; }
```

**Comment by a22maxra** [comment]
Also fixed space between Cooldown: and the time
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/32ebd873-2c26-4848-a260-78f3f82a6d95)

**Comment by a22maxra** [comment]
https://github.com/HGustavs/LenaSYS/pull/14546

**Comment by a22maxra** [comment]
Added some error handling
