### ISSUE TITLE
Create microservice loadDugga.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14555]

**Comment by a22marca** [comment]
From file: showDuggaservice.php
Database service loadDugga
Retrieves answers using hash
```
SELECT vid,variant.variantanswer AS variantanswer,useranswer,param,cid,vers,quiz FROM userAnswer LEFT JOIN variant ON userAnswer.variant=variant.vid WHERE hash=:hash
```
Otherwise retrieves answers using a specific moment
```
SELECT vid,variant.variantanswer AS variantanswer,useranswer,param,cid,vers,quiz FROM userAnswer LEFT JOIN variant ON userAnswer.variant=variant.vid WHERE moment=:moment
```

The related code seems to exist at lines 339-363 in showDuggaservice.php

**Comment by a22marca** [comment]
This functionality is related to loading a dugga using a hash. I will have to get a userAnswer hash from the database, with its password and related course and try to load it to see test the request and response that is needed.

**Comment by a22marca** [comment]
There seems to be several issues with the file validateHash.php.
For example it is trying to `echo` before changing the header link, which is not allowed, and stops the redirect from working. When i fix this issue, there seems the link that is redirected to is not valid (can't find the file on the server).

**Comment by a22marca** [comment]
using the hash AcIj-Ld6, the redirect link tries to navigate to:
http://localhost/sh/?s=AcIj-Ld6

**Comment by a22marca** [comment]
I'm having trouble identifying where and how this functionality is used on the website. It's not bound to a specific `opt` sent to showDuggaservice.php. Instead it is only executed if the user navigating the page is a superuser and the hash is not "UNK". To find where this functionality is integrated seems a bit involved, and should probably be its own issue. I will try to create microservice so that it works with proper parameters in a request, and that the response from the microservice is the values that are retrieved from the queries.

Below is the values that are assigned from the rows after the queries:
```
				foreach($rows as $row){
					$variant=$row['vid'];
					$answer=$row['useranswer'];
					$variantanswer=html_entity_decode($row['variantanswer']);
					$param=html_entity_decode($row['param']);
					$newcourseid=$row['cid'];
					$newcoursevers=$row['vers'];
					$newduggaid=$row['quiz'];
				}

```

The response from the microservice will look like this:
```
echo json_decode(
    array(
        'variant'=>$variant, 
        'answer'=> $answer, 
        'variantanswer'=>$variantanswer,
        'param'=>$param,
        'newcourseid'=>$row,
        'newcoursevers'=>$newcoursevers,
        'newduggaid'=>$newduggaid,
    ));

```

**Comment by a22marca** [comment]
Needed data to test is a hash and a moment. I tested using
moment: 2008
hash: AcIj-Ld6

Using the following command to make the POST request:
```
curl -X POST -d "hash=AcIj-Ld6&moment=2008" http://localhost/LenaSYS/DuggaSys/microservices/showDuggaService/loadDugga_ms.php
```

This response contains values in each field of the json that is returned, I can see the same values when checking these in the database. So this seems to be working.

**Comment by a22marca** [comment]
The curl works to test the microservice. The response to the previous command:
```
{"variant":"13","answer":null,"variantanswer":"{Variant}","param":"{\"linje\":\"10,30,19 20 40 20 50 30 50,81 65 50\"}","newcourseid":{"vid":"13","0":"13","variantanswer":"{Variant}","1":"{Variant}","useranswer":null,"2":null,"param":"{\"linje\":\"10,30,19 20 40 20 50 30 50,81 65 50\"}","3":"{\"linje\":\"10,30,19 20 40 20 50 30 50,81 65 50\"}","cid":"2","4":"2","vers":"97732","5":"97732","quiz":"5","6":"5"},"newcoursevers":"97732","newduggaid":"5"}
```

Database entry:
```
|   13 | {Variant}     | NULL       | {"linje":"10,30,19 20 40 20 50 30 50,81 65 50"} |   2 | 97732 |    5 |
```
