### ISSUE TITLE
Create microservice submitDugga.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14554]

**Comment by a22marca** [comment]
The microservice will be created from code in showDuggaService.php. The microservice will get useranswers based on the hash:
```
SELECT password,timesSubmitted,timesAccessed,grade from userAnswer WHERE hash=:hash;
```
Then _update_ or _insert_ into userAnswer.

Code related to this microservice is located at line 274, where the select for OPT="SAVDU" exists.

**Comment by a22marca** [comment]
This functionality is executed when answering a dugga and pressing the "save" button:

```
courseid=2
did=2
coursevers=97732
moment=2003
segment=2001
hash=UNK
password=UNK
opt=SAVDU
answer=2%2097732%202003%2000000001%200%200%201408%20880%20777%20748
log_uuid=mn11hhYj2brFXjG
variant=undefined
```

Seems the current implementation is not working properly right now. This error is received as the response from showDuggaService.php:
```
Fatal error: Uncaught Error: Class "ZipArchive" not found in /var/www/html/LenaSYS/DuggaSys/showDuggaservice.php:170 Stack trace: #0 /var/www/html/LenaSYS/DuggaSys/showDuggaservice.php(378): processDuggaFiles() #1 {main} thrown in /var/www/html/LenaSYS/DuggaSys/showDuggaservice.php on line 170
```

**Comment by a22marca** [comment]
Putting this issue on hold until the current implementation is fixed in a separate issue.

**Comment by a22marca** [comment]
waiting for issue: [https://github.com/HGustavs/LenaSYS/issues/14587](https://github.com/HGustavs/LenaSYS/issues/14587)

**Comment by a22marca** [comment]
The mentioned issue is resolved, so I will continue work here.
Creating a new branch.

**Comment by a22marca** [comment]
It seems this functionality have been implemented in a new microservice call `saveDugga` since last time.

**Comment by a22iliru** [comment]
saveDugga exists. does same
