### ISSUE TITLE
Copying a course version doesn't work

### ISSUE THREAD

**Issue by a22chrfa** [HGustavs/LenaSYS#14580]
When creating a new course version and trying to copy an existing version, it doesn't make a copy.
![image](https://github.com/HGustavs/LenaSYS/assets/128893264/70fa5706-2d88-4bef-810a-be4e614bb20a)

![image](https://github.com/HGustavs/LenaSYS/assets/128893264/bc4df49a-7c9a-4a9d-b1ae-34588440686b)

I suspect the actual function to copy a course might be missing entirely, so this issue might need the function to be built from scratch. Start by verifying if it's actually missing or just not being triggered.

Leads might be found in these comments:
https://github.com/HGustavs/LenaSYS/issues/14497

**Comment by a22willi** [comment]
After discussing with @a22ahmom and @a22diako it seems there is currently no functionality implemented to solve this. I therefor propose this plan.

- First issue: Read the existing course versions and make them show up in "new course version" copy from dropdown.
- Second issue: Create PHP function that creates a new course with copied content. 
- Third issue: Ensure that a course is copied properly using the now created functions.
