### ISSUE TITLE
Create microservice retrieveSectionedService_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14590]
It should retrieve sectionedService.php

**Comment by a22marca** [comment]
The related code to this microservice exists in sectionedservice.php below line 914. I will move all this code into a function as a microservice, like described by the previous group [link](https://github.com/HGustavs/LenaSYS/blob/6874b5277f63c2ca2e0a60429d0c22dc1878c3fb/DuggaSys/microservices/monolithic-to-microservices.md).

**Comment by a22marca** [comment]
The microservice has been implemented and test by adding the following code at the end of another microservice (I tested using getCourseGroupsAndMembers_ms)
```
include_once("./retrieveSectionedService_ms.php");
$log_uuid=getOP('log__uuid');
$array=retrieveSectionedService($debug, $opt, $pdo, $userid, $courseid, $coursevers, $log_uuid);
$array['grplst']=$grplst;
echo json_encode($array);
```

If I look at the response from the microservice it now also contains additional information and is structured like how the response from sectionedService is currently.

**Comment by a22marca** [comment]
Created a new branch because of the weekly merge.
