### ISSUE TITLE
Fix: Its not possible to update the "gradesystem", "visibility" or "moment" of a listed entry in a course.

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14626]
Find the related files, and fix it

**Comment by a22albjo** [comment]
It seems i am able to change visibility and moment on a listentrie. However the gradesystem wont stick after reloading the page.

**Comment by a22albjo** [comment]
I have tried to recreate the problem with visibility and moment but it still works fine. However i have started looking at the gradesystem to see why those changes wont stick, i will try to locate the code that handles updates to listentries.

**Comment by a22albjo** [comment]
row 347 - 353 seem to handle updates to the grade system, i notice that the db update is before the gradesys varieble is set. This seems odd, ill try to switch places and se if it works.

**Comment by a22albjo** [comment]
When saving two opts are requested from sectionedservice.php:
UPDATE 
UPDATEDEADLINE
I will take a closer look at them to find out what is going on.

**Comment by a22albjo** [comment]
seems like something is off with this query:
$query = $pdo->prepare("UPDATE listentries set highscoremode=:highscoremode, gradesystem=:gradesys, moment=:moment, entryname=:entryname, kind=:kind, link=:link, visible=:visible, comments=:comments, groupKind=:groupkind, feedbackenabled=:feedbackenabled, feedbackquestion=:feedbackquestion WHERE lid=:lid;");

**Comment by a22albjo** [comment]
Seems like only listentries with the type moment should be able to have a grade. The grade on other entries is instead for some reason changing nr of tabs the item is set to. It seems that the plan was to have the gradesys do different things depending on the type of item. 

I think that the right thing to do is to remove the option to change gradesys on all items except moment. 

I have gone thru att types and the only ones containing grade is test end moment. Moment will keep it and test will have it removed.
