### ISSUE TITLE
Create microservice deleteFileLink

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14635]
Count rows where these conditions hold. This will indicate if the file is in used.

- __FROM__ fileLink, box __WHERE__ box.filename = fileLink.filename __AND__ (fileLink.kind = 2 __OR__ fileLink.kind = 3) __AND__ fileLink.fileid=:fid ;

If not in use, then service __deliteFromTableFileLink__ is used to delete a row from the table __fileLink__.

This service contains two seperat instances of the above mentiond code, placed in an if and else statement. 

`Note that the description may be wrong or missing steps, do as u think is right.`

**Comment by c22cargo** [comment]
This seems to be related to "fileedservice.php".
