### ISSUE TITLE
Create microservice editCodeExample

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14638]
This service uses __updateTableCodeexample__ to update values in table __codeexample__:
- runlink
- examplename
- sectionname
- beforeid
- afterid

Aswell as __insertIntoTableImpwordlist__ or __deliteFromTableImpwordlist__ to add or remove a row in table __impwordlist__.

`Note that the description may be wrong or missing steps, do as u think is right.`

**Comment by a22marca** [comment]
I've identified the related code at lines 158-231 in codeviewerService.php. This will moved to a microservice.

**Comment by a22marca** [comment]
When entering a code example a POST request with the opt "EDITEXAMPLE" is sent to codeviewerService.php.
The code regarding added or removed words is used when entering a code example as a teacher, pressing the "Example Settings" button at the top -> adding(or removing) words -> saving.

**Comment by a22marca** [comment]
To test a integration of this microservice, I believe the microservice retrieveCodeViewerService_ms.php needs to be implemented first. I need to create a custom curl request to test this microservice individually for now.
