### ISSUE TITLE
Create microservice editContentOfCodeExample

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14639]
Uses the services __updateTableBox__ to change the content of these columns:
- boxtitle
- boxcontent
- filename
- fontsize
- wordlistid

Aswell as __insertIntoTableImprow__ or __deleteFromTableImpwordlist__ to add or remove a row in table __improw__.

**Comment by a22marca** [comment]
This functionality can be accessed via this cog wheel:
![image](https://github.com/HGustavs/LenaSYS/assets/128985931/5caff0f3-7f0c-49aa-85ea-ada40d27d680)
