### ISSUE TITLE
Create microservice updateFileLink

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14636]
Uses the services __updateTableFileLink__ to change the content of these columns:
- filesize
There exist three different versions of this update, with different _WHERE_ cases.
__WHERE__ kind __AND__ filename;
__WHERE__ cid __AND__ kind __AND__ filename;
__WHERE__ vers __AND__ cid __AND__ kind __AND__ filename;

`Note that the description may be wrong or missing steps, do as u think is right.`

**Comment by a21sahfa** [comment]
issuet kan inte lösas eftersom orden den nämner inte finns.

**Comment by a22melst** [comment]
The microservice is misspelled as "updataFileLink" in [potential microservices](https://github.com/HGustavs/LenaSYS/blob/d663ef4fd4f5d138017e7ce456bed6dce1350e15/backend-models/microservices/duggaSys%20services/Potential_micro_services.mdl).

**Comment by a22melst** [comment]
Trying to fix the logging so this can be tested before the weekly merge.

**Comment by a22melst** [comment]
Will create a new branch for this issue after the weekly merge.

**Comment by a22melst** [comment]
When using getOP('fid') from the MS, the returned value is "UNK". The file ID is needed when fetching the path of a file, which in turn is used for setting the $currcwd variable for course local files.

**Comment by a22melst** [comment]
Everthing works now except for logging.

**Comment by a22melst** [comment]
Will make a new branch to be able to use the retrieveUsername microservice.
