### ISSUE TITLE
Create microservice deleteCodeExample

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14640]
Uses service __deleteFromTableBox__ to delete a row from the table __Box__.
Uses service __deleteFromTableImprow__ to delete a row from the tabe __improw__.
Uses service __deleteFromTableImpwordlist__ to delete a row from the tabe __impwordlist__.
Uses service __deleteFromTableCodeexample__ to delete a row from the tabe __Codeexample__.
Uses service __deleteFromTableListentries__ to delete a row from the tabe __listentries__.

`Note that the description may be wrong or missing steps, do as u think is right.`

**Comment by a22albjo** [comment]
Locating the code from the monorepo that delete the codeExamples as this:
				```
$query1 = $pdo->prepare("DELETE FROM box WHERE exampleid=:exampleid;");
$query1->bindValue(':exampleid', $exampleId);				

$query2 = $pdo->prepare("DELETE FROM improw WHERE exampleid=:exampleid;");
$query2->bindValue(':exampleid', $exampleId);				

$query3 = $pdo->prepare("DELETE FROM impwordlist WHERE exampleid=:exampleid;");
$query3->bindValue(':exampleid', $exampleId);				

$query4 = $pdo->prepare("DELETE FROM codeexample WHERE exampleid=:exampleid;");
$query4->bindValue(':exampleid', $exampleId);
			
$query5 = $pdo->prepare("DELETE FROM listentries WHERE lid=:lid;");
$lid = getOP('lid');
$query5->bindValue(':lid', $lid);

if(!$query1->execute()) {
	$error = $query1->errorInfo();
	echo (json_encode(array('writeaccess' => 'w', 'debug' => $error[2])));
	return;
}
if(!$query2->execute()) {
	$error = $query2->errorInfo();
	echo (json_encode(array('writeaccess' => 'w', 'debug' => $error[2])));
	return;
}
if(!$query3->execute()) {
	$error = $query3->errorInfo();
	echo (json_encode(array('writeaccess' => 'w', 'debug' => $error[2])));
	return;
}
if(!$query4->execute()) {
	$error = $query4->errorInfo();
	echo (json_encode(array('writeaccess' => 'w', 'debug' => $error[2])));
	return;
}
if(!$query5->execute()) {
	$error = $query5->errorInfo();
	echo (json_encode(array('writeaccess' => 'w', 'debug' => $error[2])));
	return;
}
echo (json_encode(array('deleted' => true, 'debug' => $debug)));
return;
```

**Comment by a22albjo** [comment]
Getting this error from both mono and micro service when testing the service:
and show them this message:


Fatal error
: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`albin`.`improw`, CONSTRAINT `improw_ibfk_2` FOREIGN KEY (`boxid`, `exampleid`) REFERENCES `box` (`boxid`, `exampleid`)) in /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/codeviewerService.php:310 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/codeviewerService.php(310): PDOStatement->execute() #1 {main} thrown in
/Applications/XAMPP/xamppfiles/htdocs/LenaSYS/DuggaSys/codeviewerService.php
on line
310

**Comment by a22albjo** [comment]
Query2 runns first and then query 1 it works.

**Comment by a22albjo** [comment]
To run the service go to course webbprogrammering click on a dugga, then the settings wheel and then remove. The service will run and the example will be removed.
