### ISSUE TITLE
Create microservice updateDuggaVariant

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14645]
Uses the services __updateTableVariant__ to change the content of these columns:
- disabled
- param
- variantanswer

`Note that the description may be wrong or missing steps, do as u think is right.`

**Comment by a22marca** [comment]
This service can be called in the function `AJAXService()` in Shared/dugga.js, in the if-statement where `kind=="DUGGA"`.
This part is called for several different functionalities regarding duggor, so to test this microservice you need to add another if-condition inside to check if the opt is SAVVARI.

```
	}else if(kind=="DUGGA"){
		let serviceURL = "duggaedservice.php";
		if (opt=="SAVVARI"){
			serviceURL="../DuggaSys/microservices/duggaedService/updateDuggaVariant_ms.php";
		}		
		$.ajax({
			url: serviceURL,
			type: "POST",
			data: "opt="+opt+para,
			dataType: "json",
			success: returnedDugga
		});
```

To test the service add the code, head over to 'show tests' in a course (logged in as a teacher) -> 'Edit variants' -> Edit a specific variant. You may need to refresh the page to see if a variant is updated.
