### ISSUE TITLE
Create microservice updateDugga

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14642]
Seems like there is a function in duggaed.js that does this, so it should be replaced with this.
Uses the services __updateTableQuiz__ to change the content of these columns:
- coursename
- visibility
- coursecode
- courseGitURL
- qname
- autograde
- gradesystem
- quizFile (template)
- qstart (start date)
- deadline
- qrelease (release date)
- jsondeadline
- group

`Note that the description may be wrong or missing steps, do as u think is right.`

**Comment by a22iliru** [comment]
created new issue

**Comment by a22marca** [comment]
the microservice is now implemented and worked. I tested it by adding this code to dugga.js (line 1061):

```
	}else if(kind=="DUGGA"){
		let service_url = "duggaedservice.php";
		if (opt==="SAVDUGGA"){
			service_url = "../DuggaSys/microservices/duggaedService/updateDugga_ms.php";
		}
		$.ajax({
			url: service_url,
			type: "POST",
			data: "opt="+opt+para,
			dataType: "json",
			success: returnedDugga
		});
```

This functionality can be tested by logging in as a teacher, going into a course and then "show tests". Editing a dugga can be done by clicking the cog icon.
