### ISSUE TITLE
Create microservice createDuggaVariant

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14644]
Uses service __insertIntoTablVariant__ to makes _inserts_ into the table __Variant__.

`Note that the description may be wrong or missing steps, do as u think is right.`

**Comment by a22eddpe** [comment]
### createDuggaVariant
Uses service __insertIntoTablVariant__ to makes _inserts_ into the table __Variant__.

**Comment by a22eddpe** [comment]
cant find the relevant function in the dugga.js file.

**Comment by a22eddpe** [comment]
this issue is not done yet because the servise insertIntoTableSettings is missing. View the pull request for the code that was created before insertIntoTableSettings and see what can be used.
