### ISSUE TITLE
Improve functinality of code example downloader

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14656]
After #14630 it was determined that more error handling and input handling should be implemented.

**Comment by d22mikwe** [comment]
Apparently the lenasys installer may move the courses folder to root directory if testing-course was installed.
Need to check if this is the case and add functionality to be able to write to both folderpaths.

**Comment by d22mikwe** [comment]
When checking the box to include testdata in the installer the courses folder is moved to root dir.
Unsure why some users did not have a course folder in root. Need to look into it further. 
In the meantime ill implement handling to resolve this.

**Comment by d22mikwe** [comment]
Instead just created a courses folder in root if it doesnt exist already

**Comment by d22mikwe** [comment]
Look into making this or parts of it into a function
![image](https://github.com/HGustavs/LenaSYS/assets/129263393/74a3291b-3c39-4b1c-9137-4166b129de65)

**Comment by d22mikwe** [comment]
checkForUpdatedFiles have been depreciated and moved to a future issue.

**Comment by d22mikwe** [comment]
Input fields are cleared when clicking exit button, save button or outside of the templatepopup.
