### ISSUE TITLE
GitFetch cooldown causes errors

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14669]
The following error appears once per second after clicking the github fetch button for a course and then navigating to another site. 
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/759aa9fb-0062-41c6-9381-a6e7b5dc9b45)

**Comment by a22samka** [comment]
Located error in the navheader.php file with the function setInterval:
![image](https://github.com/HGustavs/LenaSYS/assets/129301680/ea09af99-a263-48a8-8517-f1792e63e03e)

I will try to fix the error..
