### ISSUE TITLE
Remove unnecessary console log

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14668]
When focusing the website, console logs are made. (unfocus = clicking outside the website) Remove this.

Steps to recreate:
- navigate to a course. 
- open the console. 
- click anywhere in the console window.
- click on the website. (a log should appear.)

**Comment by d22isaka** [comment]
Removed two lines of console logs which stated if the page is focused/unfocused, found in sectioned.js.

![Skärmbild 2024-04-25 141700](https://github.com/HGustavs/LenaSYS/assets/129263107/eb66962c-e8de-407c-9646-7c055b28e107)

Should solve the issue.
