### ISSUE TITLE
Fix updateCours_ms.php spelling , remove updateCourse.php, move first one to courseedService folder

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14665]
Delete: updateCourse.php
Fix: updateCours_ms.php to updateCourse_ms.php
Then move updateCourse_ms.php to courseedService folder.

**Comment by a22marca** [comment]
I've deleted the unused file and move the misspelled one to the correct path and name.  I also took a look at the code in the file, and it seems it's not correctly done. Some parameters are not retrieived for example. I test the microservice to make see if it works before creating a pull request.

**Comment by a22marca** [comment]
I've integrated the microservice, and no requests are properly handled in the microservice
Error:
```
 Fatal error: Uncaught Error: Call to undefined function getOP() in /var/www/html/LenaSYS/DuggaSys/microservices/courseedService/updateCourse_ms.php:6 Stack trace: #0 {main} thrown in /var/www/html/LenaSYS/DuggaSys/microservices/courseedService/updateCourse_ms.php on line 6
``` 
This error is likely thrown because some files are not included.

**Comment by a22marca** [comment]
Will create a new separate issue to fix the implementation of the updateCourse_ms.php microservice.
