### ISSUE TITLE
Input validation for new course version bugs 

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14675]
The input validation for creating a new course version does not work properly at the moment. 
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/14ba6300-be12-4bd5-a718-a7a1a57cabe3)
For example, as the image above shows, the error shows up for the wrong text input. If you find any other bugs regarding the input validation, create a new issue according to these instructions:
- Go to the issues tab and click `new issue`.
- Write a good description and title. 
- Add the labels: `Bug` & `g3-2024`. (or other appropriate tags)
- Click `Submit new issue`.
- In the Projects tab, select awaiting triage, and add it to the `to-do` column.

**Comment by a20jonda** [comment]
`Edit Section` also have enough common code and shares method  `quickValidateForm()` with both `New course` and `Edit course` so it will be included
