### ISSUE TITLE
Create microservice saveDugga

### ISSUE THREAD

**Issue by c22emigr** [HGustavs/LenaSYS#14693]
Create microservice for $opt SAVDU

**Comment by c22emigr** [comment]
Reusing code from previous closed issue related to this. https://github.com/HGustavs/LenaSYS/issues/14633#event-12508277693

**Comment by a22eriwi** [comment]
Me and c22emigr were working on this branch before https://github.com/HGustavs/LenaSYS/tree/g2-2024-v3-issue%2314693 but the issue wasnt linked to that branch. that's why we created a new one and pasted the code in it.
