### ISSUE TITLE
Filter output for getCourseGroupsAndMembers in sectionedservice_Test.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14714]
make sure a correct expected output and filters are used
    currently this does not pass the assert test
    Be aware that some tests needs a fresh database to pass

File: sectionedservice_Test.php

**Comment by c22mohel** [comment]
The current code does pass the all the test, its just that when installing the lenasys database you need to Include Testing-Course.

**Comment by a22marca** [comment]
The getCourseGroupsAndMembers retrieves a list of groups, so the `grplst` variables should probably be the only variable to be compared

**Comment by a22marca** [comment]
Seems the queries made before the test and after the test inserts into tables of the database that are not used by the getCourseGroupsAndMembers functionality. I will test writing two new queries that can be used as well.

**Comment by a22marca** [comment]
It seems the current code in sectionedservice.php that is supposed to handle the `opt` "GRP" is not working. The microservice for getCourseGroupsAndMembers, is working so the `grplist` is returned when using that instead.

**Comment by a22marca** [comment]
I will look at issue#14826 before proceeding with this issue.

**Comment by a22marca** [comment]
The mentioned issue above is now resolved. I will continue with this issue after the weekly merge is complete today.

**Comment by a22marca** [comment]
Creating a new branch with these weekly group branch as base, since the old one didn't really contain any changes.

**Comment by a22marca** [comment]
Fixed returned values of grplst in #14873, waiting for merge.

**Comment by a22marca** [comment]
I've added a new expected output and the showgrp parameter that specifices the type of group to retrieve members from. The group being inserted by the query is the same type as the one specified in showgrp in the test.

**Comment by a22albjo** [comment]
I think the output needs to be filtered a lot more.

**Comment by a22albjo** [comment]
I used an old branch, @a22marca has filtered this to perfection. My bad
