### ISSUE TITLE
Filter output for tests in sectionedservice_Test.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14720]
#14719 #14718 #14717 #14716 #14715 #14714 

Parent issue

**Comment by a22iliru** [comment]
https://github.com/HGustavs/LenaSYS/issues/14719 https://github.com/HGustavs/LenaSYS/issues/14718 https://github.com/HGustavs/LenaSYS/issues/14717 https://github.com/HGustavs/LenaSYS/issues/14716 https://github.com/HGustavs/LenaSYS/issues/14715 https://github.com/HGustavs/LenaSYS/issues/14714

**Comment by a22albjo** [comment]
The tests works and we decided to close this issue with comment.

**Comment by a22albjo** [comment]
All children issues are completed, this issue is therefore done.
