### ISSUE TITLE
IE primary keys

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14734]
## Description
There is currently no way to underline attributes in IE to properly mark them as primary keys.

## Job
Implement a button (and preferably a <kbd>ctrl</kbd> + <kbd>U</kbd> keyboard-shortcut) to make text underline

**Comment by a22robko** [comment]
We were assigned the task of creating primary keys, and we managed to do so by adding "PK," which stands for primary key. We thought this was the simplest way, but we understand that it can be difficult to know when to write "PK" in diagram.php without that information, as it's not the most natural way to do it.
image1:
<img width="896" alt="Screenshot 2024-04-23 at 16 24 35" src="https://github.com/HGustavs/LenaSYS/assets/129367092/35c6826f-190b-49d2-9d40-43a21bf5a540">
The code checks if the text from each item is longer than two letters and ends with "PK" which usually means "Primary Key". If this is true, it makes the text underlined to show that it is a primary key property. If not, it just uses a regular 'text' style.
image2:
<img width="782" alt="Screenshot 2024-04-23 at 16 30 44" src="https://github.com/HGustavs/LenaSYS/assets/129367092/dac79ff8-dc3c-4fbc-b1e4-083e765535bd">
