### ISSUE TITLE
accessedserivce: Create microservice updateUserCourse

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14755]
Uses service updateTableUser to update one of these columns in the table user_course at a time:

    examiner

Uses service updateTableUser to update one of these columns in the table user_course, at a time:

    vers

Uses service updateTableUser to update one of these columns in the table user_course, at a time:

    access

Uses service updateTableUser to update one of these columns in the table user_course, at a time:

    group

folder: accessedservice

**Comment by c22mohel** [comment]
The code for the monolithic file does not work. i will focus on fixing that first

**Comment by c22mohel** [comment]
To test this add the courseID and userID for the row you wish to change and the value you want to change.
example:
$userid = 4; 
$cid = 2;

//prop for what value you wish to change
$prop= "examiner";
$groups= "Le_A";
$vers = "00000";
$access = "ST";
$examinerValue = 1;

then load the updateUserCourse_ms.php and the values should change in the database. 
Right now the whole of accessedservice.php is broken, so i have not found another way to test this.
