### ISSUE TITLE
profileservice: Create microservice updateUserPassword_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14757]
Uses service updateUserPassword to update the column "password" in the table user.

folder: accessedservice

**Comment by a22marca** [comment]
Found related code at line 143 in accessedservice.php.

**Comment by a22marca** [comment]
I've implemented the microservice and i'm now trying to find where to change the users password on the page.
I'm guessing this setting can be accessed by clicking the username at the top-right of the page. This part of the site requires a https connection. So currently i'm not able to access this part of the site.

**Comment by a22marca** [comment]
Some other people in the group seems to have access to the page so I will let someone else continue

**Comment by c22emigr** [comment]
Dont know why but only a22eriwi seems to have a https connection so continuing testing on his computer. Testing to see if the ms is working

**Comment by c22emigr** [comment]
after researching this i am still unsure when the code for CHPWD from accessedservice.php is used. If you try to change the password by clicking on the user in LenaSys it uses the profileservice.php file. If you try to change the password by clicking "forgot password" when logging in it used the code in resetpw.php. Putting this issue on hold until i get some clear instructions on what i should convert to a microservice.

**Comment by a22eriwi** [comment]
It seems like the op CHPWD is not used in the accessed.js file. Like c22emigr said above if you change the password via the user page (profile.php) the profile.js file is used to send an ajax call to the file (profileservice.php) which recieves password, newpassword and action. In order to make an ms for change password the name of the ms has to be changed and defined differently

**Comment by a22eriwi** [comment]
This microservice comes from the file profileservice.php which can be split into 2 different ms. One to change and update the password and another for the security question.

**Comment by c22emigr** [comment]
We have now made updateUserPassword as one microservice that now works. We have tested it by changing the url for the ajax call in profile.js on line 164 to the url for our microservice.

**Comment by a22eriwi** [comment]
The ms (updateUserPassword_ms.php) we have created seems to be working. 
![image](https://github.com/HGustavs/LenaSYS/assets/129263553/e825b7fb-8462-4b33-8ce3-b3328e8ca275)
