### ISSUE TITLE
resultedservice: Create microservice getUserAnswer

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14752]
Uses service selectFromTableUserAnswar to get information it requires from userAnswer. Uses service selectFromTableListentries to get information it requires from Listentries.

folder: resultedservice

**Comment by a22marca** [comment]
Seems like this microservice will make up the whole old microservice, since it is so small. So will simply copy the old service into the microservice and try to identify parts that are not used/not needed in the code.

**Comment by a22marca** [comment]
The functionality can be tested by logging in as a users, going into a course and pressing edit student results. To test the microservice itself change the url in dugga.js at line 1178.
