### ISSUE TITLE
Create shared class for accessing coursesyspw.php

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14761]
Create a new php file in the shared directory with a class called configurationManager or maybe something else. That contains functions for reading and writing configuration settings to the file `coursesyspw.php`. 

The file looks like this:
```
<?php
          define("DB_USER","lenasys");
          define("DB_PASSWORD","password");
          define("DB_HOST","db");
          define("DB_NAME","lenasysdb");
          define("DB_USING_DOCKER","on");
?>
```
The class should allow future developers to quickly read and set configuration variables like this:
```
$cm = new configurationManager();
$cm.set("DB_USER", "username");
// or 
$dbname = $cm.get("DB_NAME");
```

Note: since the variables are set using define(), you need to make it change the itself, by reading and writing to the php file. (You can see the previous implementation of this in the `install/install.php` file line 652)

**Comment by a22moamy** [comment]
This issue will be unnecessary due to the work by @b22marah on issue #15149.
