### ISSUE TITLE
DragnDrop has a few bugs and issues

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#1478]
There's a lack of comments and the behaviour is very strange, moving a box within the pop-up moves the entire pop-up. The "create new sequence"/"Delete sequence"/"Save sequence" should be aligned and have some margin from the surronding edges aswell as follow the standard with purple boxes

**Comment by c12jenek** [comment]
It's also implemented in it's own files which we're not supposed to do, it could and should be implemented in codeviewer.js/editorService.php

**Comment by a13jansa** [comment]
i can start with the "create new sequence"/"Delete sequence"/"Save sequence"

**Comment by b13danso** [comment]
Fixed.

**Comment by f12danjo** [comment]
Fixed by [#1642](https://github.com/HGustavs/LenaSYS/pull/1642).
