### ISSUE TITLE
[Research] Find a way to import

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14790]
## Description
When trying to import a variable or function into another file it just gives an error lite "importing needs to be done in top of module"

## Job
Try to successfully import anything and write about what you did to fix it

**Comment by a22solmi** [comment]
Javascript files should not use import / export syntax. Adding a file with `<script src="./XXXX"></script>` to diagram.php will make all functions and global variables available to all js files below it in the php file.
