### ISSUE TITLE
Identify why It's not possible to remove a listed entry in a course

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14803]
By a22marca: It's not possible to remove a listed entry in a course, when trying to remove it no requests are sent, so i'm not sure whats wrong in this case. I belive a listed entry should be set to visibility 3 and then removed after wards, i'm not sure?

**Comment by c22cargo** [comment]
Issue can be reproduced by going into "show tests" for a course and trying to delete a test.

**Comment by c22cargo** [comment]
It seems that the "useranswer" table has references to these quizes, which is why they cannot be deleted.
