### ISSUE TITLE
fix sectionedservice.php no grplist is ever returned.

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14826]
when the opt "GRP" is sent to sectionedservice.php, no grplist is ever returned. Related to #14825

**Comment by a22marca** [comment]
Some code has been commented out that places the information retrieved from the database, in the list that should be returned. Furthermore, there are some issue with the frontend javascript code that prints members to the page in sectioned.js.

**Comment by a22marca** [comment]
The group members are now being added to `grplst` and the frontend shows the group members correctly.

**Comment by a22marca** [comment]
To test this functionality, you need to go into a course that has groups (Webbutveckling - datorgrafik), create a new group activity->assign the group a activity ("No") -> click it. The request to sectionedservice.php is containing the opt "GRP", the request shows the members in grplst. The webpage should also show the group members.
