### ISSUE TITLE
Undefined : undefined showing

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#1483]
When not logged in and not at an example Undefined : undefined is the title f the examples, this should  be changed

**Comment by a13jorla** [comment]
As for now, when you are going through duggasys you wont get this line in the navheader. So @c12jenek  should we close this issue?

**Comment by c12jenek** [comment]
Is up to the groupleader, since when going with a direct url it's still shown

**Comment by f12danjo** [comment]
Fixed by [#1680](https://github.com/HGustavs/LenaSYS/pull/1680).
