### ISSUE TITLE
Fix microservice createListentrie

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14844]
Is supposed to use createNewCodeExample and createNewListentrie, but currently implements their functionality itself.

**Comment by a22marca** [comment]
There are a couple ways to make createListentrie use the two microservices createNewCodeExample and createNewListentrie:
- Making createNewCodeExample and createNewListentrie into functions so they can be included and called
- Making curl requests from createListenrie to the two microservices
- including the microservices so all code in them are executed.

**Comment by a22marca** [comment]
We decided to move createNewListentrie and createNewCodeExample into functions. I've implemented these two as functions instead. What is left is to integrate these so they are used in createListentrie, and make sure that everything works.

**Comment by a22marca** [comment]
I've manage to integrate the function calls in createListentrie instead. I tested that it still works by creating new list entries in a course (Group activity, test, etc.). Add the following code to dugga.js (line 1077) to test it:
```
	}else if(kind=="SECTION"){
		let service_url = "sectionedservice.php";
		if (opt=="NEW"){
			service_url="../DuggaSys/microservices/sectionedService/createListentrie_ms.php";
		}
		$.ajax({
			url: service_url,
			type: "POST",
			data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
			dataType: "json",
			success: returnedSection
		});

```
