### ISSUE TITLE
Investigate why courseed.php does not work with old database

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14849]
In issue #14736 It was determined that the courseed.php page wont load when using the old database, figure out why and ensure that it works. 

Before fixing it, ensure that your fix does not break any rules regarding continuous integration. IE, don't change the tables, the best way would probably be to ensure that the LenaSYS page can read both the old and new database.

**Comment by a22oscja** [comment]
Course page appears to load in data correctly, the issue with delete is seen as redundant to fix as the same feature has been worked on in another issue. Also I could not get the delete feature to work in our current database on either branch, hence it will likely be a future issue instead.
