### ISSUE TITLE
Scale sequence actor on the height aswell

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#14857]
## Description
If a sequence actor is scaled on the X-axis then the character expands on height aswell and then get's hidden because of the overflow. 

![bild](https://github.com/HGustavs/LenaSYS/assets/129258593/effb2d51-40ce-4d28-8761-dfc866de411d)

## Job
Make it so that sequence lifelines also scale vertically when scaled horizontally. 
**NOTE**: The lifeline is **_NOT_** supposed to scale horizontally when scaled vertically

**Comment by a21liltr** [comment]
Solved by PR #15999.
