### ISSUE TITLE
Fix github fetch tooltip

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14869]
When there is no github repo set, there should not be any cooldown. Remove this. And test it thoroughly. 
![image](https://github.com/HGustavs/LenaSYS/assets/129264968/47bd3280-9a35-4149-9654-46f22fb36394)

**Comment by a22danwe** [comment]
iv'e noticed that the countdown does not start when trying to save something that isnt a github repo. The save button doesnt work when the inputfield is empty which makes it so you have to press escape or click outside of the popup, this does activate the cooldown.

**Comment by a22danwe** [comment]
im trying to make a new cooldown function in sectioned.js that checks if a repo is set before starting.

**Comment by a22danwe** [comment]
made it so that the timer doesnt start as soon as the button is clicket. i moved the function from the php file to the js file.
the cooldown still runs when no GitHub repository is present.

**Comment by a22danwe** [comment]
thinking of putting some validation on the inputfield on the github popup window that appears when repo is empty.
