### ISSUE TITLE
Replace js alerts with toasts

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14876]
in #14682 toast functionality was implemented. Use this to replace some of the existing alerts with toasts. Replace all that you can find, where it makes sense to have a toast instead of an alert.

**Comment by a20jonda** [comment]
https://github.com/HGustavs/LenaSYS/wiki/Toast

**Comment by a20jonda** [comment]
Starting with courseed.php/js

**Comment by a20jonda** [comment]
a fix for toast container blocking buttons will be included
