### ISSUE TITLE
Visual adjustments and code improvements for ´Edit Server Settings´ ´Edit Course´ and ´New Course´ in courseed.php and courseed.js

### ISSUE THREAD

**Issue by a20jonda** [HGustavs/LenaSYS#14875]
´Edit Server Settings´ 
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/60c597fc-6642-436a-891b-a3514a272a39)
Error should be visible

´Edit Course´ 
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/4773459f-32a5-4b76-aac3-7048e2aadd06)
Bad alignment to errors and missing error checking for github tokens

´New Course´
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/fdc180c5-5a6a-4feb-9c08-e7e95a7c4f07)
bad alignment of errors

## Note
sectioned.js uses a similar ´quickValidateForm()´ which could be mimicked for ease

**Comment by a22maxra** [comment]
Looking in to how the validation works.

**Comment by a20jonda** [comment]
The new [loading button](https://github.com/HGustavs/LenaSYS/wiki/loadingButton.js) implementation forgot to add an ID to the loading button so it currently no longer gets disabled by the validation. The original id was `saveCourse``.

Also I got an implementation for the forms in [sectioned.php/sectioned.js](https://github.com/HGustavs/LenaSYS/pull/14870) which is currently being tested to be merged. I would recommend checking it out as sectioned and courseed are quite similar.

**Comment by a22maxra** [comment]
The quickValidateForm function, triggered on the oninput event of each validated input field, is used to validate the input after each input to the field. I'll try adding this to the MOTD and see why the messages do not align.

**Comment by a22maxra** [comment]
Fixed alignment of MOTD symbol limit message

![image](https://github.com/HGustavs/LenaSYS/assets/98206230/270bb954-5285-4007-ab48-695cbd84f425)


![image](https://github.com/HGustavs/LenaSYS/assets/98206230/7d7b5442-0a37-4e9f-a3fe-24d8277e1d05)

**Comment by a22maxra** [comment]
The other error messages do not work the same way the re-alignment is not working

**Comment by a22maxra** [comment]
There was a duplice ID 'dialog5' so i changed it to 'dialog51' which now means the error gets shown,

![image](https://github.com/HGustavs/LenaSYS/assets/98206230/a15feeaa-9fed-4df9-bf5d-e0f6f87cd33f)

I went ahead and fixed the placements after this
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/aad166d9-2e2f-4414-8e3a-076718630ee2)

**Comment by a22maxra** [comment]
Edit course messaged aligned

![Uploading image.png…]()

**Comment by a22maxra** [comment]
There is now a error message for the Github key/token and error messages are alligned
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/334279b5-8c55-4474-9ba6-74a25bfb5fb7)
