### ISSUE TITLE
Add expand button to toast

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14885]
A toast implementation was made in #14682. Change it to incorporate the following:
- Allow the toast to show longer error messages when expanded.
- The toast should expand when clicked anywhere but the close button. (But only if there is hidden content)
- Ensure that, by default, only 2 rows of text are visible in the toast.
- Apply an ellipsis effect to display three dots when there is hidden content in the toast.

**Comment by a22willi** [comment]
This issue [#14813](https://github.com/HGustavs/LenaSYS/issues/14813) is currently in progress, which also modifies the functionality of toast.php. Try to collaborate with @a22karja on this if you can.

**Comment by a22samka** [comment]
I have fixed everything except ellipsis, this is because it breaks the toast and I dont know how to fix it. When I add them it looks like this: 
![image](https://github.com/HGustavs/LenaSYS/assets/129301680/e3b01761-64b8-4c0b-991c-cfe2d9d1a245)
And the expand class is no longer toggle-able
