### ISSUE TITLE
Research if it is possible to allow  variable-query-after-test

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14887]
, currently test.php only supports 
variable-query-before-test

**Comment by c22cargo** [comment]
While technically possible, it would be a lot of work to implement this. I have tried some implementations but I believe ```test.php``` would have to be rewritten quite extensively. Also, having ```variable-query-after-test``` is a nice to have, but isn't strictly necessary. There are workarounds. I think this issue should be closed until a scenario appears where ```variable-query-after-test``` is absolutely necessary to have.
