### ISSUE TITLE
Create microservice updateOrder_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14898]
![image](https://github.com/HGustavs/LenaSYS/assets/164884946/c22c02a0-782f-448c-ab40-45484c229865)

https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/backend-models/microservices/duggaSys%20services/Microservices.md#updateorder_msphp

**Comment by a22eddpe** [comment]
this issue has been closed
