### ISSUE TITLE
Guest ID fix

### ISSUE THREAD

**Issue by a13alfbe** [HGustavs/LenaSYS#1490]
At the moment you get new guestID everytime your refresh the page. It would be nice if the ID was stored in local storage.

**Comment by HGustavs** [comment]
This sounds like a very worthwhile effort.

**Comment by a14ponse** [comment]
Since all the people that are going to use the page are students or teachers and therefore has an account and can log in we cant see any use in storing a guest ID for any one. And its no point to save an guest ID since you cant modify anything ether.

**Comment by HGustavs** [comment]
It would be nice to be able to track users even when not logged in.

So I would like this feature together with the logging.

A local storage id that is used for users that do not have them. This way we can track usage patterns for users that do not log in.

**Comment by HGustavs** [comment]
I think this is an issue for the logging group (group 3?)

**Comment by a16joare** [comment]
Is this issue still an issue?

**Comment by a17poner** [comment]
Bump @HGustavs

**Comment by d17marle** [comment]
Minor issue needs to be changed, doesnt give out a new guest id once logged in and then logged out again.

**Comment by b17carbr** [comment]
@HGustavs I have implemented guest users ids that persist for one hour by storing the id in cookies. At login the guest user cookie gets deleted. This was inline the original request of this issue, but further down in the comments there is talk about having the original issue together  with logging. Should logging be part of this issue, or moved to another issue? I can only find one place where guest are logged at this movement which is in codeviewer.
