### ISSUE TITLE
Fix createNewListentrie_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14914]
Add pdo as parameter, dont create a new one with pdoconnect
Remove as many includes as possible
Remove session_start()
The reason for this: This things are already done by the calling microservice

IF IT DOESNT NEED PDO ( DOES NOT EXECUTE QUERIES) , JUST MARK ISSUE AS COMPLETE)

**Comment by a22marca** [comment]
PDO is already a parameter in function of this microservice. Closing this issue.
