### ISSUE TITLE
Create microservice updateListentriesGradesystem_ms.php 

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14929]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/backend-models/microservices/duggaSys%20services/Microservices.md

**Comment by a22marca** [comment]
I believe this functionality is already implemented in updateListEntriesTabs_ms.php.
```
    $query = $pdo->prepare("UPDATE listentries SET gradesystem=:tabs WHERE lid=:lid;");
```

**Comment by a22marca** [comment]
im guessing this microservice should update the gradesystem column of the table with a similar query like the one above, but using the opt gradesystem instead.

**Comment by a22marca** [comment]
The microservice is implemented, but this functionality doesn't seem to exist in sectionedservice.php so it's kind of hard to integrate it at this point.

You can try to update a gradesystem of a listentry by performing this curl command:
```
curl -X POST -d "lid=5009&gradesys=0" http://localh
ost/LenaSYS/DuggaSys/microservices/sectionedService/updateListEntriesGradesystem_ms.php
```
Check the database before and after the curl request with this query:
```
select lid,entryname, gradesystem,tabs from listentries where lid=5009;
```
