### ISSUE TITLE
Create microservice getGitReference_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14927]

**Comment by a22melst** [comment]
From [potential microservices](https://github.com/HGustavs/LenaSYS/blob/d663ef4fd4f5d138017e7ce456bed6dce1350e15/backend-models/microservices/duggaSys%20services/Potential_micro_services.md#getgitreference-this-is-a-temp-name-dont-really-know-what-the-point-of-this-service-is-yet-): 

**getGitReference (this is a TEMP name, dont really know what the point of this "service" is yet )**
This service creates an array containing values from the column downloadeURL in the database found here "../../githubMetadata/metadata2.db" Uses service selectFromTableBox to get information it requires from box. Uses service selectFromTableCodeexample to get information it requires from codeexample. Uses service selectFromTableGitFiles to get information it requires from gitFiles.

**Comment by a22melst** [comment]
gitFiles is a table in metadata2.db.
box and codeexample are tables in the main database.

**Comment by a22melst** [comment]
```
//------------------------------------------------------------------------------
// This method is to be used to check if a code example should re-fetch the
// contents of a code example based on eventual changes in external github-repo
//------------------------------------------------------------------------------
async function refreshCodeExample(exampleid) {
  console.log("Should try to refresh a code example (check if re-fetching from external github repo is necessary)");
  AJAXService("REFGIT", { exampleid: exampleid });
}
```

**Comment by a22melst** [comment]
There is currently no records in the gitFiles table, so it is difficult to say what its use is.

**Comment by f22linhe** [comment]
Ensure to implement _retrieveSectionedService_ms.php_ in this microservice when the development of the microservice is feasible.
