### ISSUE TITLE
Create microservice createGithubCodeexample_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14928]
[https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/backend-models/microservices/duggaSys%20services/Microservices.md](url)

**Comment by a22marca** [comment]
After investigating this a bit, the only related  code i can find for this is under the `opt` "NEW". This code however is already implemented in the microservice, so this microservice seems to be redundant.

**Comment by a22marca** [comment]
Taking another look at this microservice, and I found some code for the opt "CREGITEX" that seems related to this the description of this microservice. It does perform a few other queries as well however. But the opt sounds like it has something to do with creating a git code example.

**Comment by a22marca** [comment]
I have implemented the code from the opt CREGITEX into a microservice. I will proceed with replacing the code making inserts into codeexample and listentries to use the microservices createNewCodeExample and createNewListentries instead.

**Comment by a22marca** [comment]
I've added the use of createNewCodeExample and createNewListentries to the microservice, and I am trying to find where in LenaSYS the opt CREGITEX is performed from to see where this microservice should be used.

Currently, there is a limit on the Github API so I can't add any new examples currently to find where it is tested. I will wait for a while and try some more.

**Comment by a22marca** [comment]
CREGITEX is used when for example adding a repo link to demo-course, going into the course pressing the refresh symbol above the listed entries.

**Comment by a22marca** [comment]
There seems to be some issues with adding a github repo to the course, I got recommended to add a generate Personal access tokens (classic) from github and add that to the course as well. The refresh symbol mentioned in the previous comment does not seem to be the action that is required for the list entries to be added from the code files in the added repo. The files currently gets added when selecting a github moment.

**Comment by a22marca** [comment]
When integrating the microservice it seems to handle request and send a response correctly. However, I'm not sure that the actual functionality is working, which i mentioned in the previous comment. I will have to investigate further whether this microservice is able to be tested on the website itself.

**Comment by a22marca** [comment]
There is a query at line 759 in sectionedservice.php that is not properly written.
```
SELECT boxid AS bid FROM box WHERE exampleid = :eid AND filename=:boxName;
```
The `FROM box` was missing. So the entries seems to be created properly now when using the original service file.

**Comment by a22marca** [comment]
The microservice seems to be working, but we will have to test this thoroughly when do the final integration to see if the works when more fixes have been added by group 3 regarding the fetching of github repos itself.

Currently you have to add a github repo to a course, as well as a github [Personal access tokens (classic)](https://github.com/settings/tokens). I used a personal repo from a previous course for testing. Then go into the course and wait for the git fetch cooldown, then press it (You can only test this every 5 minutes). After this you should be able to add a github moment on a moment header in the listentries. After choosing one, press submit. During this part i'm not really sure what happens, the CREGITEX opt might be sent here already. The "refresh symbol" can be pressed to send the request to this microservice manually.

To integrate the microservice change the url on line 3329 in sectioned.js.
