### ISSUE TITLE
Create microservice hasAccess_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14932]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/backend-models/microservices/duggaSys%20services/Microservices.md

**Comment by a22marca** [comment]
The documentation says this:
This function is currently housed in session.php and might therefore not be something that should be transitioned to a micro service.."

And when looking at the code of the hasAccess function, the code executed by it also makes a call to another function in session.php (`getAccessType`). So if this where to be implemented as a microservice, it would still not be isolated from session.php. My opinion is that we need to decide if would should move all used parts of session.php into microservices, or if it should remain in session.php

**Comment by a22melst** [comment]
### Functions in sessions grouped by functionality

•	Login (login, checklogin, failedLoginCount, addlogintry) 
•	Userstatus (isSuperUser, isTeacher, isStudentUser)
•	Security Question (getQuestion, checkAnswer)
•	Password (requestChange, standardPasswordHash, standardPassWordNeedsRehash)
•	Access (hasAccess, getAccessType)
•	Other (git_checklogin, showLoginPopup)

I am not sure yet whether sessions.php should be split into microservices, but if so this grouping could be an alternative or at least a stepping stone.

**Comment by a22melst** [comment]
The code at the top of file which sets the cookie parameters could perhaps be its own microservice as well.

**Comment by a22melst** [comment]
Something to consider when grouping these functions into microservices is not only which functions are related to the same functionality, but also which functions are frequently used together.

**Comment by a22melst** [comment]
The group decided to leave sessions.php as it is.
