### ISSUE TITLE
Update microservices.md for setUserID_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14938]
This is already finished as there is another ms with same function (getUid)

**Comment by f22linhe** [comment]
Documentation Microservices.md is now updated. The microservice setUserID_ms.php was deleted from the documentation based on these facts: 

- "The microservice retrieves the userid from `$_SESSION`. This functionality is already covered by `getUid` (later renamed to `readUid_ms.php`), which also returns the value. Therefore, the microservice was considered unnecessary."
