### ISSUE TITLE
Create microservice updateSecurityQuestion_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14930]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/backend-models/microservices/duggaSys%20services/Microservices.md

**Comment by a22marca** [comment]
Found in the documentation:
```
Statements below are methods for changeProfileValues and not services.
updateSecurityQuestion
```
I will implement this microservice lika  a function

**Comment by a22eriwi** [comment]
Implemented the file updateSecurityQuestion_ms.php in the folder sharedMicroservices

**Comment by a22eriwi** [comment]
The code is taken from the file profileservice.php. Certain things have been removed and changed
