### ISSUE TITLE
Create microservice setUserID_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14933]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/backend-models/microservices/duggaSys%20services/Microservices.md

**Comment by a22marca** [comment]
Description of the microservice: "Checks currents sessions user ID and sets it to a variable."

I persume this is the code they are referring to:
```
    if (isset($_SESSION['uid'])) {
        $userid = $_SESSION['uid'];
    } else {
        $userid = "guest";
    }
```

**Comment by a22marca** [comment]
I don't think this microservice is necessary since this functionality is already done by getUid, which sets the user id based on the session and returns value.
