### ISSUE TITLE
Update wiki to include "loading buttons"

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14943]
In issue [#14648](https://github.com/HGustavs/LenaSYS/issues/14648) a generic loading button was implemented that should be able to replace any button. Write about it on the wiki. 

The post should include:
- Where are the files located. 
- How can I use it. 
- How does it work.

**Comment by a22maxra** [comment]
Wiki explaining `loadingButton.js`
https://github.com/HGustavs/LenaSYS/wiki/loadingButton.js
