### ISSUE TITLE
Add "undo" toast type 

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14945]
Add functionality to create an "undo" toast. A toast that shows up for x seconds, and while its visible, the user should have the option to click undo, to reverse whatever action they just did.

Requirements:
- Add the undo type
- Add the undo button for the "undo" toasts
- After the deadline/timeout for a toast has passed the toast function should return true if the user clicked undo. False if the timer passed.

**Comment by a20jonda** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/102598258/fcf9ad86-28c1-4383-bc72-7dd3d3c4c70f)
An already built in undo button appears in sectioned.php when you delete a section. Will add a undo toast alongside it
