### ISSUE TITLE
Create microservice insertIntoSQLite_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14962]

**Comment by a22marca** [comment]
This issue is related to gitcommitservice.php. I will be copying the function `insertIntoSQLite()` into a separate folder under microservices/gitCommitService/insertIntoSQLite_ms.php.

**Comment by a22marca** [comment]
I've implemented the function in a separate file. To see if it works adding this include at line 36 in gitcommitService.php, and comment out the function (line 80). Then try to add a link to a course on the courseed.php page. To check that the link got added properly, you have to check the sqlite database in the githubMetadata/metadata2.db.

run
```
SELECT * FROM gitRepos;
```
And the link should show up along the the courseid.
