### ISSUE TITLE
Create microservicec refreshGithubRepo_ms.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#14965]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/DuggaSys/gitcommitService.php

folder: microservices/gitcommitService

**Comment by a22albjo** [comment]
The microservice is implemented, however there are two functions in the ms right now who later probably will be having there own MS.

**Comment by a22albjo** [comment]
change url in LenaSYS/DuggaSys/sectioned.js row 466 to the microservice.

To run the service go in to a course and press the git icon in the navheader:
![image](https://github.com/HGustavs/LenaSYS/assets/53318057/439b4b6e-ba9f-42c4-a825-6ae67814b5cb)

Im not entirely sure what this service does or how the github works with the coursepage.

**Comment by a22albjo** [comment]
To test this you have to prevent default to see the response or make a curl request. 

You also importantly need to be logged in as a superuser.

There are currently no githubrepo to test this functionality but you can se that output is given, this will need to be revisited when the functionality is fixed.
