### ISSUE TITLE
Investigate why testDugga.php does not work with old database

### ISSUE THREAD

**Issue by a22willi** [HGustavs/LenaSYS#14990]
In issue #14736 It was determined that the testDugga.php page wont load when using the old database, figure out why and ensure that it works. 

Before fixing it, ensure that your fix does not break any rules regarding continuous integration. IE, don't change the tables, the best way would probably be to ensure that the LenaSYS page can read both the old and new database.

**Comment by a22oscja** [comment]
having looked at both the code and the website itself the testdugga page appears to not be used or referenced anywhere.

Because of this, this issue is deemed unecessary.
