### ISSUE TITLE
Fix getCourseID in gitcommitService.php

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#15011]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/DuggaSys/gitcommitService.php

folder: microservices/gitcommitService

Warning: The current implementation does not work in gitcommitService.php.
Info:
When creating a new course,  getCourseID is executed in gitcommitService.php. Inside this function a call to insertIntoSQLite() is made. However, this function call only contains two parameters, but it needs three.. so there is a fatal error
```
         if($cid != null) {
            insertIntoSQLite($githubURL, $cid);
        } else {
            print_r("No matches in database!");
        }

```
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function insertIntoSQLite(), 2 passed in /var/www/html/LenaSYS/DuggaSys/gitcommitService.php on line 70 and exactly 3 expected in /var/www/html/LenaSYS/DuggaSys/gitcommitService.php:80 Stack trace: #0 /var/www/html/LenaSYS/DuggaSys/gitcommitService.php(70): insertIntoSQLite('https://github....', '1896') #1 /var/www/html/LenaSYS/DuggaSys/gitcommitService.php(25): getCourseID('https://github....') #2 {main} thrown in /var/www/html/LenaSYS/DuggaSys/gitcommitService.php on line 80`

It looks like  the token variable is not passed in properly. I'm not sure what the token should contain, we need to check this, maybe it should be empty since it is a new course?

**Comment by a22marca** [comment]
Looking at the code of `insertIntoSQLite()` we can see that it checks if the token is empty or not, and if it isn't it will retrieve the old token. 

```
	function insertIntoSQLite($url, $cid, $token) { 
		if(strlen($token)<1)
		{
			$token=fetchOldToken($cid);
		}
```

I believe that the token used in the call from getCourseID, should be empty in this case since insertIntoSQLite will check if there is a old token if the string is empty.
```
		// Check if not null, else add it to Sqlite db
		if($cid != null) {
			insertIntoSQLite($githubURL, $cid, "");
		} else {
			print_r("No matches in database!");
		}

```
