### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by c13andka** [HGustavs/LenaSYS#1501]
If somebody want, they can make the email that is sent with some headers and stuff so it looks clean and professional out. This can be done with html and inline style css. You can try to send the email to yourself to see how it will look.

**Comment by a12majca** [comment]
Ok, I'll do that today. 
I also noticed that we're not actually sending a receipt to the user right now. 
This is what it looks like:

![skarmavbild 2015-05-26 kl 21 48 54](https://cloud.githubusercontent.com/assets/11715536/7829927/91505df2-0447-11e5-8084-afa33954f6f4.png)

**Comment by a12majca** [comment]
i misunderstood this issue, thought you wanted to get rid of the prompt... unassigning now.

**Comment by a12majca** [comment]
but we are sending a receipt now.. 
![skarmavbild 2015-05-27 kl 11 13 50](https://cloud.githubusercontent.com/assets/11715536/7833138/b7ff215a-0464-11e5-8bc9-14b10bd5c763.png)
