### ISSUE TITLE
Document the stages of the installer

### ISSUE THREAD

**Issue by b22marah** [HGustavs/LenaSYS#15024]
Document all the steps that the current installer goes through in a simple to follow list. 

Ex:
- Requests db credentials.
- creates table x, y and z.
- creates user. 
- etc.

Note: this is meant to document the steps in the PHP file install.php, not what the user sees when installing.

**Comment by a22willi** [comment]
The stages of the installer are as follows: 
- init.
    - Check if credentials file already exist. And import settings if it does
    - Get working directory of LenaSYS
    - Show UI.
    - Check post variable for selected settings. 
    - Verify that all credentials have been set.

- Establish pdo connection
    - Try to connect with pdo using root mysql account.
    - check if overwrite user / db.
    - delete sqlite db for github integration.
    - Check file permissions for root directory of LenaSYS. ( wrong order; should be called before deleting sqlitedb)
    - create new database. 
    - Create new user. 
    - Grant new user permissions for created db.

**Comment by b22marah** [comment]
### Steps following @a22willi comment...
- Transaction?
    - Remove all comments from .sql file.
    - create transaction?

- Test data (all if checked).
    - Add testdata.
    - Create democourse.
    - create testingcourse.
    - Add codeexamples.
        - Add courses directory.
        - add course 1.
        - add course 2.
    

- Save credentials.
    - Save the current credentials to coursesyspw.php (write to file)
    - check upload size parameter.

**Comment by a22moamy** [comment]
@HGustavs Is it okay to remove the "Yes I want to perform the database-initializing as an transaction" option in the installer as it does not seem to have any real function and only causes errors? @a22willi and @b22marah have analyzed the code and deemed it redundant. 

By "Yes I want to perform the database-initializing as an transaction" I mean this option in the installer:
![Skärmavbild 2024-04-29 kl  11 33 52](https://github.com/HGustavs/LenaSYS/assets/129263915/413d7172-562b-46a6-ae07-0abbe817d0aa)

**Comment by a22moamy** [comment]
Regarding the issue, the documentation is great and concise. 
Well done!
