### ISSUE TITLE
Arrow keys scroll page on dugga

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#15035]
## Description
When moving elements using the arrow keys while in a dugga it also scrolls the page at the same time.

https://github.com/HGustavs/LenaSYS/assets/129258593/fbc9e5fd-eaac-42cf-a6d8-ae6739da884a

## Job
Make so that the page doesn't scroll if you're focused on the diagram in the dugga.

**Comment by a21liltr** [comment]
Solved with PR #15295 .
