### ISSUE TITLE
Possibly move php code for fetching codeexamples into relevant php file

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15039]
Current integration of fetching code examples from github has its PHP code inside sectioned.php.
Look into if other more relevant php files like gitfetchService.php, sectionedService.php is more suitable.
If it is move the implementation to that php file and secure continued functionality

**Comment by SleepyBearIV** [comment]
after discussion, there are more faults that need to be fixed and it was decided that the smartest way to fix the issue whit the original code in place and try this again later
