### ISSUE TITLE
Enable arrow keys on snapToGrid

### ISSUE THREAD

**Issue by a22jacka** [HGustavs/LenaSYS#15037]
## Description
Currently there's a check that disables the arrow keys if the option "snap to grid" is enabled.

## Job
Implement so that the arrows use the grid size if the setting is enabled otherwise just keep moving 1px.

**Comment by b22samer** [comment]
b22samer and a22robko enhanced functionality to enable the movement of elements using arrow keys while snap to grid is enabled. Previously, this feature was not working as intended. One of the issues was with the selection mechanism responsible for arrow key movements, which did not account for snap to grid. Regardless of the zoom level, elements will now consistently align precisely with the grid lines, ensuring a seamless experience.
