### ISSUE TITLE
Research possibility for asynchronous fetching of github repo

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15041]
The current iteration of fetching a github repo to a course seems to be synchronous, thus making the webpage freeze until it has been completed. Seems to be the bfs() function that is synchronous. Correct me if im wrong.

Look into what parts of the whole fetch process is synchronous.
Research if it is possible to refactor the current fetching to be asynchronous in its current php file.
If not, is it possible to integrate the function partly or all of it into a js file where asynchronous requests are natively supported?

Relevant issue:
- #14391

**Comment by a22ahmom** [comment]
this one got reverted
