### ISSUE TITLE
Rename changeActiveCourseVersion_ms.php (in the sectionedService folder) -> changeActiveCourseVersion_sectioned_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15056]
The microservice _changeActiveCourseVersion_ms.php_ in the sectionedService folder should be renamed: "_changeActiveCourseVersion_sectioned_ms.php_" since there is a microservice in the courseedService folder also named _changeActiveCourseVersion_ms.php_.

_ _sectioned_ should be added to more easily keep them apart.

**Comment by a22fokol** [comment]
I have check it and it looks good as it should  "changeActiveCourseVersion_sectioned_ms.php"

**Comment by c22emigr** [comment]
this file is already correctly named in the group branch so this issue should be closed.
