### ISSUE TITLE
Add a HTML title-attribute to create tooltips for certain buttons in sectioned.php

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15054]
Adding a title-attribute to an element makes them display a tooltip when hovering above them. It gives the user a clue as to what a button does. Like so:
![Skärmavbild 2024-04-28 kl  19 59 13](https://github.com/HGustavs/LenaSYS/assets/129263915/a7be2fa3-f589-4dd5-9907-397955455ccf)

The following buttons are missing a title-attribute: the theme-toggler, the "fetch github repo button" and the draggable parts of list entries. These buttons are marked in red:
![Skärmavbild 2024-04-28 kl  19 53 35](https://github.com/HGustavs/LenaSYS/assets/129263915/361a3b2d-7359-4a1e-8276-3d5584246f6d)
![Skärmavbild 2024-04-28 kl  19 57 47](https://github.com/HGustavs/LenaSYS/assets/129263915/48f89601-c584-4b09-a364-26bddaf7de54)

**Comment by a22diako** [comment]
Cant fix this issue because of revert, therefor this one is set on pause.
