### ISSUE TITLE
Investigate why an error message is created when re-arranging list entries in sectioned.php

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15055]
When re-arranging list entries, an error message will be generated. You can re-arrange list entries in a course by dragging them with these buttons:
![Skärmavbild 2024-04-28 kl  19 57 47](https://github.com/HGustavs/LenaSYS/assets/129263915/d85a3e98-414b-46ac-b651-73e428f82a9d)

The generated error-message on Firefox:
![Skärmavbild 2024-04-28 kl  20 05 07](https://github.com/HGustavs/LenaSYS/assets/129263915/fbe12c8a-57aa-4090-98a7-c49c5166b017)

**Investigate why this error message is created and fix it.**

**Comment by d22mikwe** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/129263393/4bc9754e-578f-4033-862d-349aa515475e)
