### ISSUE TITLE
 Remove as much inline css as possible from sectioned.php

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15063]
Currently, there is a lot of unnecessary inline css in `sectioned.php`. Having inline css and external css for the same website makes development harder, and thus it should be separated as much as possible into the external css files. Inline css is especially unneccessary for elements with ids and often unnecessary for those without them as well. **Please move as much inline css as possible from `sectioned.php` to the external css files.**

**Comment by SleepyBearIV** [comment]
Remove undo button dose not work remove the code if no longer in use

**Comment by SleepyBearIV** [comment]
can no longer delete stuff

**Comment by SleepyBearIV** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/96497530/35dc3dbf-07c0-498d-ba49-5d8265a99698)
dose not line up, Probably needs to be dynamic

**Comment by SleepyBearIV** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/96497530/4eceb217-e3ae-4d26-8c8e-35dffb2d83b8)
![image](https://github.com/HGustavs/LenaSYS/assets/96497530/46c145cb-4c42-451f-a322-8c93b08615f0)
sometimes the cancel button jumps around, should be changed to dynamic
