### ISSUE TITLE
Eliminate error message in console and fix the code to implement toasts. 

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15070]
## The issue
When pressing the "Get Canvas Link" button, an error message is generated in the console. 

"Get Canvas Link"-button (can be found in list entries): 
![Skärmavbild 2024-04-29 kl  10 59 59](https://github.com/HGustavs/LenaSYS/assets/129263915/2ae93b09-16bb-4922-8eb3-8c47e3d80e25)

The error message on Firefox:
![Skärmavbild 2024-04-29 kl  11 00 49](https://github.com/HGustavs/LenaSYS/assets/129263915/5a17c959-77de-45e8-ae41-d296ddb6f5c6)

## The requested fix
Add code that checks whether there is a Canvas link or not before trying to get the Canvas link. If there is none, **an error toast should pop up stating so.** If there is a link, then it can be fetched. Also check if the right link is being fetched, or if the current method uses faulty logic. No error messages should be generated in the console.

**Comment by d22mikwe** [comment]
The showCanvasLinkBox() function seems to be searching for a node element that contains the href link to the codeexample viewed in codeviewer. I'e the <td class="example-item".
Try adding an extra .parentNode in the querySelector.
