### ISSUE TITLE
Line appears over the cursor

### ISSUE THREAD

**Issue by a22vioja** [HGustavs/LenaSYS#15086]
## Description

When connecting two objects, the line currently appears over the cursor. 
Instead, it should run alongside the cursor.

<img width="887" alt="Screenshot 2024-04-29 at 14 06 20" src="https://github.com/HGustavs/LenaSYS/assets/129263559/1e505e7f-f6a4-4afc-a5c6-0b5b032e0915">

## Job

Make that cursor would be beside the line.

**Comment by a22hanfa** [comment]
This problem is actually a problem for all entities, so all entities are not under the mouse pointer.

**Comment by a22vioja** [comment]
> This problem is actually a problem for all entities, so all entities are not under the mouse pointer.

Yes, it applies to all entities. There's an ER example of an issue in the image, but the problem described in the issue is that it occurs when connecting objects.

**Comment by a22hanfa** [comment]
> Yes, it applies to all entities. There's an ER example of an issue in the image, but the problem described in the issue is that it occurs when connecting objects.
 
 Yes! Sorry, was just talking to myself haha! Making some notes on the page
