### ISSUE TITLE
ESC to go back for sectioned

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15088]
In previous issue it was determined that adding an eventlistener to ESC button to go back to previous page created conflicts with the already existing eventlistener on ESC button for closing popups and modules.
- #14663 

Eventlisteners can be found in sectioned.js line 593 - 672.

Possible solution could be to add statements to check if the popups/modules are open inside eventlisteners? If they are not open, go back instead?

Possible solution could be to look into if there is a way to set a global key for an open popup or module, could be integrated by a common function call in all popups/modules.

If this is not possible research if there's other work arounds.

**Comment by a18chrkr** [comment]
I have looked into the code and found all the montioned eventListeners for closing windows/modals. However I could not find the code that actually takes the user back in browser history. Therefore I could not properly investigate and simulate the bug where pressing the 'ESC' button both closes a modal _and_ takes the user back in history at the same keypress.

Other than that, I could suggest changing the way the event handlers starting on line 592 is written. At the moment they all pretty much do the same thing, except they only close one specific window each. I believe there is a more effective way to implement this kind of functionality.

**Comment by d22mikwe** [comment]
maybe history.back() function could be implemented in some way with the eventlisteners and popupmodules to go back to previous browser page

**Comment by d22mikwe** [comment]
Added functionality that's replicable in other pages than sectioned.php
