### ISSUE TITLE
Fix test 'Create active users' in showDuggaservice_test.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15104]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v4/DuggaSys/tests/showDuggaservice_test.php

See issue "_Research which showDuggaservice_test.php tests work and which do not #14956_" for more information.

**Comment by a22iliru** [comment]
The reason this test does not work is that it is missing "activeusers": null in the output.

**Comment by a22iliru** [comment]
The tests pass now after changing the expected output to include active users and fixing some others. Easy testing by just opening this file.
