### ISSUE TITLE
When creating a new version of a course there are no options to copy content from.

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#1511]
This course should have two versions already existing. To choose from.

![untitled](https://cloud.githubusercontent.com/assets/11715749/7699559/0c1b936a-fe19-11e4-8f82-dfd33804c023.png)
![untitled2](https://cloud.githubusercontent.com/assets/11715749/7699580/2f330248-fe19-11e4-9e7a-d648dfe2003b.png)

**Comment by b13alebr** [comment]
Henrik wrote something about this in issue #885
When creating a version and you want to copy content from another version that already exists the content you copy to the new version must be duplicated. There are currently no functions to do this thats why there are no options to choose from.

**Comment by c13chrjo** [comment]
Then I will close this issue

Duplicate of #885
