### ISSUE TITLE
Investigate why there's a text stating "Login is only possible from course page!"

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15151]
When trying to log in to LenaSYS, there is a text stating "Login is only possible from course page". This text can be seen below:
![Skärmavbild 2024-04-30 kl  10 55 33](https://github.com/HGustavs/LenaSYS/assets/129263915/72f5349f-02b6-40ab-8dd3-f9289cbed66c)

But from our brief research, no issues arise when logging into **any page in LenaSYS.** So your issue is to find out if the system crashes from logging in at any subpage (for example, sectioned.php, codeviewer.php etc) to see if this text is really even needed. If no errors arise, you should get rid of the text from the form and submit a pull request. Otherwise, a comment explaining your findings will suffice.

**Comment by d22mikwe** [comment]
After discussions the intended function is not needed as it should be possible to login from any site.
Make sure the text box is removed and does not break any other feature.
