### ISSUE TITLE
Improve highlight function when creating new list item.

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15159]
Improve the highlight to make it more intuitive and noticable

**Comment by SleepyBearIV** [comment]
after reconsideration it is better perhaps to make the whole row highlighted, continuation after weekly merge

**Comment by SleepyBearIV** [comment]
when you ad a new course element (code) the whole row should be highlighted  
![image](https://github.com/HGustavs/LenaSYS/assets/96497530/7daa3e35-cdd4-40a0-8a29-e352c6fdc5fc)


current animation function can be found here 
![image](https://github.com/HGustavs/LenaSYS/assets/96497530/2f0dff87-1b3e-404e-af1a-562898c27169)
