### ISSUE TITLE
Fix test setVisibleListentrieHIDDEN in sectionedService_test.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15155]
The test _setVisibleListentrieHIDDEN_ is failing because it is missing the "groups" entry. When adding the "groups" to the filter list, there is a difference in the values for this entry. I believe we should try to create a new expected-output and filters for this test as well.

**Comment by a22iliru** [comment]
The output in the test file is broken. I will update this output

**Comment by a22iliru** [comment]
Before continuing, we should find an easy way to locate where the output leads to, so we can update the test file
