### ISSUE TITLE
Create new test for the microservice processDuggaFile_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15165]
See parent issue: _Create new tests for the microservices created from showDuggaservice.php. https://github.com/HGustavs/LenaSYS/issues/15162"_

**Comment by a22eddpe** [comment]
add the test in showDuggaservice_test.php. The ord. function is found in showDuggaservice.php

**Comment by a22eddpe** [comment]
'process Dugga File' => array(
    'expected-output' => '{"debug": "[Guest] Missing hash/password/variant!","param": "{}","answer": "UNK","danswer": "UNK","score": 0,"highscoremode": "","grade": "UNK","submitted": "","marked": "","deadline": "UNK","release": "UNK","files": {},"userfeedback": "UNK","feedbackquestion": "UNK","variant": "UNK","ishashindb": false,"variantsize": "UNK","variantvalue": "UNK","password": "UNK","hashvariant": "UNK","isFileSubmitted": "UNK","isTeacher": 0,"variants": [],"duggaTitle": "UNK","hash": "UNK","hashpwd": "UNK","opt": "UNK","link": "UNK"}',
    'query-before-test-1' => "SELECT MAX(subid) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-2' => "SELECT MAX(vers) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-3' => "SELECT MAX(did) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-4' => "SELECT MAX(fieldnme) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-5' => "SELECT MAX(filename) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-6' => "SELECT MAX(extension) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-7' => "SELECT MAX(mime) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-8' => "SELECT MAX(updtime) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-9' => "SELECT MAX(kind) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-10' => "SELECT MAX(filepath) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-11' => "SELECT MAX(seq) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-12' => "SELECT MAX(segment) AS listentries FROM submission WHERE hash = ?;",
    'query-before-test-13' => "SELECT MAX(hash) AS listentries FROM submission WHERE hash = ?;",
    'query-after-test-1' => "DELETE FROM submission WHERE hash = ?;",
        'service' => 'http://localhost/LenaSYS/DuggaSys/showDuggaservice.php',
        'service-data' => serialize(array( // Data that service needs to execute function
            'opt' => 'UPDATEAU',
            'username' => 'brom',
            'password' => 'password',
            'hash' => 'hnf3j58s',
            'courseid' => '9999',
            'coursevers' => '1337',
            'duggaid' => '1',
            'duggainfo' => '9',
            'moment' => '<!query-before-test-3!> <*[0]["moment"]*>'
        )),
        'filter-output' => serialize(array( // Filter what output to use in assert test, use none to use all output from service
            'none'
        )),
    ),``

**Comment by a22eddpe** [comment]
the code above is what i have come up with. I am not sure of how to create the test but now you have something to start from.
