### ISSUE TITLE
Create new test for the microservice loadDugga_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15164]
See parent issue: _Create new tests for the microservices created from _showDuggaservice.php._ #15162"_

**Comment by b21isabe** [comment]
There doesn't appear to exist a working test for the monolith service, so I will have to make one from scratch. From a first look at the microservice it looks like I will need to use moment and hash as service data. I will need to insert something into userAnswer and variant, and then delete it afterwards. It looks like the ms is outputting the right data so it should possible to create a new test-file for it.

**Comment by b21isabe** [comment]
I have tested the ms and it seems to work with already existing duggas. I have been having some problems with inserting new variants/userAnswer/listentries etc to create the test. I need to use variables-query-before-test to insert into several tables that are linked with foreign keys before running the test. I will try to find a solution first and if I can't I will just do a workaround.

**Comment by b21isabe** [comment]
Since we merged today I have created a new branch to continue my work on.
