### ISSUE TITLE
Adding file

### ISSUE THREAD

**Issue by c13andka** [HGustavs/LenaSYS#1516]
When you add a file in global files it will not get added. fix please

**Comment by a13oscwe** [comment]
Might have to change file permissions for owner/group like issue #1327

**Comment by c13andka** [comment]
Make the map /templates have the same permission so that we can add global files, global files is saved in a different map then course local and local files. Should all be saved in the same map with different underlying maps ? or have the hierarchy we have now?

**Comment by a13oscwe** [comment]
I changed permissions and it seems to work for both duggasys and master now.
chgrp and chown -R www-data /templates

**Comment by c13andka** [comment]
works ! :) great.
