### ISSUE TITLE
Create new test for the microservice addClass_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15178]
See parent issue: _Create new tests for the microservices created from _accessedService.php_ #15177_

**Comment by c22cargo** [comment]
To test the implementation, issue #15012 needs to be merged first.

A branch with the implementation will be created after the weekly merge.

**Comment by c22cargo** [comment]
Errors occur because it's hardcoded in ```test.php``` for test-files to be located in a specific place.

**Comment by c22cargo** [comment]
There was an issue with the user id not being set correctly when performing the test, thus making it fail. This was fixed by adding ```checklogin()``` to the ```getUid_ms```.
