### ISSUE TITLE
Fix write problem when fetching codeexamples from github on Mac

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15173]
Mac users have experienced problems when fetching a codeexample from github. 

All relevant files are not written in  .../LenaSYS/courses/$cid when fetching codeexamples.
The relevant course folder is also not created in LenaSYS/courses/
$cid is the courseid.

Make sure the files are written inside the correct course folder and that it contains all files that has been fetched.

Relevant Issues:
- #14532 
- #14525

**Comment by a22danwe** [comment]
when testing this issue it worked for me, it created a $cid folder in lenasys/courses where the file was written

**Comment by d22mikwe** [comment]
Issue is deemed completed and problem solved
