### ISSUE TITLE
Create new test for the microservice addUser_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15179]
See parent issue: _Create new tests for the microservices created from accessedService.php https://github.com/HGustavs/LenaSYS/issues/15177_

Note, this issue cannot fully be completed unless _Create a retrieveAccessedService microservice https://github.com/HGustavs/LenaSYS/issues/15250_ and _Create new test for the retrieveAcessedService_ms.php https://github.com/HGustavs/LenaSYS/issues/15306_ has been resolved.

__Since the frontend for accessedservice.php, is not finished it's not possible to test that the retrieveAcessedService_ms.php or any related microservice to accessedservice.php actually works. Once the frontend is implemented, testing of the microservices will be possible.__

**Comment by c22mohel** [comment]
frontend for accessedservice.php does not work. this needs to be resolved before i can solve this issue.
