### ISSUE TITLE
Create new test for the microservice editContentOfExample_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15186]
See parent issue: _Create new tests for the microservices created from codeviewerService.php https://github.com/HGustavs/LenaSYS/issues/15182_

Note, this issue cannot be resolved until the issue Implement retrieveCodeViewerService_ms.php into all microservices in the codeviewerService folder https://github.com/HGustavs/LenaSYS/issues/15387 has been resolved.

**Comment by a22melst** [comment]
There seems to be issues with the microservice.

**Comment by a22melst** [comment]
When trying to insert records to impid without specifying a value for impid (which is an auto-incrementing primary key), an error occurs saying it is out of range.

Error mesage:
Error Code: 167. Out of range value for column 'impid' at row 1
