### ISSUE TITLE
Create new test for the microservice createNewCourse_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15191]
See parent issue: _Create new tests for the microservices created from courseedService.php https://github.com/HGustavs/LenaSYS/issues/15187_

Note, for this issue to be resloved the issue _Implement retrieveCourseedService_ms.php in all microservices in the courseedService folder #15304_ need to be resolved.

**Comment by a22marca** [comment]
I'm continuing work in this issue. Creating a new branch to get all the recent updates.

**Comment by a22marca** [comment]
The test is almost done at this point. I'm having some issues with the filters, for some reason "versions" is not filtered out from the values that i compared against the expected value when i'm using the following filters:
```
        'filter-output' => serialize(
            array(
                'entries' => array(
                    'cid',
                    'coursename',
                    'coursecode'
                ),
                'debug'
            )
        ),

```

I believe this is a issue with the actual filter. the versions array does also contain the entries cid, coursename and coursecode. So versions is still collected and compared against it seems.
