### ISSUE TITLE
Create new test for the microservice updateCourse_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15195]
See parent issue: _Create new tests for the microservices created from courseedService.php https://github.com/HGustavs/LenaSYS/issues/15187_

**Comment by a22marca** [comment]
There are some issues with updating a course in the frondend at this point. Group 3 are working on this issue, waiting until I know that the issue is fixed before proceeding here

**Comment by a22marca** [comment]
There is a commented out function in sectioned.js that may use this microservice.

In anycase, this microservice purpose is to return listentries with the visible attribut set to 3.
retrieveSectionedService already returns all listentries, so this microservice is redundant.

**Comment by a22marca** [comment]
It is now possible to update a course. I will continue in this issue.

**Comment by a22marca** [comment]
I believe this is not fixed, group 3 are still working on it.
