### ISSUE TITLE
Create new test for the microservice retrieveCourseedService_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15193]
See parent issue: _Create new tests for the microservices created from courseedService.php https://github.com/HGustavs/LenaSYS/issues/15187_

**Comment by a22iliru** [comment]
This is a big microservice that will require a lot of testing in the test file, will take time

**Comment by a22iliru** [comment]
The querys return foreign key constraint error, not sure how to fix it yet

**Comment by a22iliru** [comment]
The constraints are fixed, remaining is fixing expected output.
