### ISSUE TITLE
Update Database Wikis diagrams to represent the current state of the database

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15205]
The wiki with information about the database was last updated three years ago. 
Update **the diagrams in** [this wiki](https://github.com/HGustavs/LenaSYS/wiki/Database#schema-of-the-database-with-relationships) to be accurate with the current state of the database. Update **only the diagrams** .

**Comment by a22chrfa** [comment]
Changed the model **with** relationships so far

**Comment by a22chrfa** [comment]
The other model (after discussing with @a22moamy ) was replaced with a model of the same notation, but only includes the actual keys.
