### ISSUE TITLE
Create new test for the microservice updateFileLink_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15207]
See parent issue: _Create new tests for the microservices created from fileedService.php https://github.com/HGustavs/LenaSYS/issues/15204_

**Comment by a22melst** [comment]
It would be good to make tests for global files, course local files and version local files respectively.

**Comment by a22melst** [comment]
Since there are no course local or version local files by default, the files to test the updates on will be created using curl requests to filereceive.php.
