### ISSUE TITLE
Research if a retrieveshowDuggaservice microservice would be beneficial

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15234]
Some of the microservices originating from _showDuggaservice.php_ have no output, while some, such as _updateActiveUsers_ms.php_, have very short output. Research whether it would be beneficial to create a _retrieveshowDuggaservice_ms.php_, similar to the ones made for _sectionedservice.php_ _(retrieveSectionedService_ms.php)_ and _courseedservice.php_ (_retrieveCourseedService_ms.php)_. This microservice could then be called at the end of the microservices.

**Comment by a22iliru** [comment]
My suggestion is that we have a retrieve for every service file we have implemented
