### ISSUE TITLE
Error on line 34 i basic.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15233]
When attempting to load a dugga (using the button) with a hash and password, a redirect is stopped due to an echo statement used for error printing in _basic.php_ line 34. The exact cause of the error remains unclear, temporarily resolving the issue involves commenting out the echo statement, enabling successful loading of the dugga. Research and try to find a solution for the problem.

**Comment by a22iliru** [comment]
When loading a dugga, the page does redirect but an errror "undefined" pops up, not related to line 34. Checking how to replicate this specific error.

**Comment by a22iliru** [comment]
I could not replicate the specific error, however I have added output buffering and instead of echoing an error in default switch case, it will now store the error in a variable and log it.
