### ISSUE TITLE
Remove lines between SE

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#15253]
## Description 
You can drag lines between lifelines and sequence objects. It should only be possible to have lines between sequence activations.
![Screenshot from 2024-05-02 10-38-27](https://github.com/HGustavs/LenaSYS/assets/129150661/eee6ff55-7ea3-4cd5-a6a4-03178bec8669)

## Job
Remove the ability to have lines between these entities.

**Comment by a22vioja** [comment]
Solved by another issue
