### ISSUE TITLE
Background objects overlap

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#15258]
## Description
Background objects such as UMLSuperState, sequenceLoopOrAlt, sequenceActor and sequenceObject have a lower z-index than other objects. They should be able to overlap with elements on a different z-level but not with each other.
![Screenshot from 2024-05-02 10-49-44](https://github.com/HGustavs/LenaSYS/assets/129150661/085481b8-a30b-44ab-906d-90f79de3f684)

## Job
Find a way to check for overlap of background objects.

## Tip
Look in file called **helper.js** in diagram folder and function **entityIsOverlapping()**.

**Comment by a21liltr** [comment]
Was solved with PR #15556.
