### ISSUE TITLE
Lock color darmode

### ISSUE THREAD

**Issue by a22solmi** [HGustavs/LenaSYS#15268]
## Description
The color of the lock icon does not change on darkmode 
![Screenshot from 2024-05-02 11-09-55](https://github.com/HGustavs/LenaSYS/assets/129150661/bdc04d05-1c98-4686-95f8-415c3729ac06)

## Job
Make the icon white when darkmode is on

**Comment by d22abdha** [comment]
the lock icon remains now visible against black background, added a condition to check if the background is black and then applied a filter to change the lock icon to white.

**Comment by a22solmi** [comment]
Solved by #15577
