### ISSUE TITLE
Research if microservices cover the entire functionality of the servicefile resultedservice.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15292]
Review the microservices in the resultedService folder. Do these/this microservices/microservice cover the entire functionality of the original service file, resultedservice.php? If you find any functionalities that are not covered, do we need to create a new microservice for this functionality?

https://github.com/HGustavs/LenaSYS/tree/g2-2024-v5/DuggaSys/microservices/resultedService

**Comment by a22iliru** [comment]
The original service file is quite short, only containing enough for 1 microservice to be implemented, which has been done. Also a retrieve service file has been implemented for it too which is good.
