### ISSUE TITLE
Implement retrieveCourseedService_ms.php in all microservices in the courseedService folder

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15304]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/microservices/courseedService/retrieveCourseedService_ms.php

https://github.com/HGustavs/LenaSYS/tree/g2-2024-v5/DuggaSys/microservices/courseedService

Note that the microservice _copyCourseVersion_ms.php_ has not yet been created. The issue that was blocking the creation of this microservice has now been resolved, and therefore the microservice should be able to be created. A comment about remembering to include _retrieveCourseedService_ms.php_ in the microservice when it´s being developt has been added to this issue: _https://github.com/HGustavs/LenaSYS/issues/14198_

**Comment by a22marca** [comment]
Looking at the parameters of the function and the code inside it:
```
function retrieveCourseedService($pdo, $ha, $debug, $LastCourseCreated, $isSuperUserVar)
```
The `$ha` and `$isSuperUser` is the same value and are originally set like this at the start of courseedservice.php:
```
$isSuperUserVar = false;

if (checklogin()) {
	if (isset($_SESSION['uid'])) {
		$userid = $_SESSION['uid'];
	} else {
		$userid = "UNK";
	}
	$isSuperUserVar = isSuperUser($userid);

	$ha = $isSuperUserVar;

	if ($ha) {

```

The last if condition in the code snippet above includes all the conditions of the different opt's that is handled. So each microservice should probably set a $ha variable and pass this as a parameter to `retrieveCourseedService()`.
In retrieveCourseedService, the isSuperUser variable can simply be set from $ha.
```
function retrieveCourseedService($pdo, $ha, $debug, $LastCourseCreated){
isSuperUserVar=$ha;
}
```

**Comment by a22marca** [comment]
I've added the retrieve service call to the microservice changeActiveCourseVersion_courseed_ms.php, which is originally called in courseedservice using the opt `CHGVERS`. However,  the javascript (dugga.js) side, that makes the POST-request does not send this opt in any part of the code base. I'm not sure this functionality is actually integrated to the frontend of the website.

**Comment by a22marca** [comment]
When making the microservice deleteCourseMaterial use the retrieve service I noticed that this performs deletions on courses that are marked for deletion. This is already done in the retrieve function itself. This is because this was originally done by the "retrieve information" part of courseedservice.php, before returning any values.

**Comment by a22marca** [comment]
The microservice createCourseVersion_ms.php has some issue (all microservices regarding, updating/creating course versions). Looking at the requests when creating or changing a course version the request to the microservice is aborted. But in fact the insert is made using this microservice. So it's not possible to view the actual response from the microservice. 

I believe this is because this is made from sectioned.php, which makes the call to courseedservice.php (originally) and then redirects back to sectioned.php afterwards. The returned json from courseedservice.php, is not used since sectioned.php pages uses the json from sectionedservice.php after that has been run.

**Comment by a22marca** [comment]
I've added the use of the retrieve service to all microservices in microservices/courseedService, except updateCourseVersion_ms.php. The reason for this is that some code are written that is incorrect and there are some declared functions that should not be there, so we should refactor this microservice before adding finalizing it with the retrieve service call.

**Comment by a22marca** [comment]
There is also the microservice copyCourseVersion which is not implemented yet, because there are some problems with the implementation [14198](https://github.com/HGustavs/LenaSYS/issues/14198)

**Comment by a22marca** [comment]
I will proceed to test the integration and verify that the correct responses with the use of the retrieve service is working.

**Comment by a22marca** [comment]
I've added the function call to all the available microservices in microservices/courseedService now. I will now proceed to test each and check that they still work as they should, and that they return a correct response.

**Comment by a22marca** [comment]
It seems like updateCourse_ms.php and updateCourseVersion_ms.php is currently performing the same query.
I will create a new issue to resolve this and add the call to the retrieve service when that is done.

**Comment by a22marca** [comment]
I think I have found a solution to integration of microservices that change/create course versions. There was a issue where the request to the microservice was aborted. This is because when changing a course version within the course (sectioned.php) the request is made to the microservice, and then there is a redirect to a new url in section.php. The ajax call did not have time to finish before the redirect. So to fix this I set these specific ajax calls to not run in async:

```
		} else if (opt === "NEWVRS") {
			$.ajax({
				url: "../DuggaSys/microservices/courseedService/createCourseVersion_ms.php",
				type: "POST",
				data: "opt="+opt+para,
				dataType: "json",
				async: false,
				success: returnedCourse
			});


```

**Comment by a22marca** [comment]
All microservices in courseedService is now using the retrieve service. I have also tested the integration.

changeActiveCourseVersion - done/untested - original opt "CHGVRS" not used, no place to change active version specifically on the website
deleteCourseMaterial - done/untested - retrieveCourseedService already performs this functionality, might be a unnecessary microservice.
createCourseVersion - done/TESTED
updateCourseVersion - untested - currently does the same thing as updateCourse, needs to be changed
createNewCourse - done/TESTED
updateCourse - done/TESTED
createMOTD - done/TESTED

I used this code for integration:
```
	if(kind=="COURSE"){
		//for testing of the microservice, delete the if/else and uncomment the original ajax call below before merge
		if(opt === "NEW"){
			$.ajax({
			        url: "../DuggaSys/microservices/courseedService/createNewCourse_ms.php",
				type: "POST",
				data: "opt="+opt+para,
				dataType: "json",
				success: returnedCourse
			});
		} else if (opt === "NEWVRS") {
			$.ajax({
				url: "../DuggaSys/microservices/courseedService/createCourseVersion_ms.php",
				type: "POST",
				data: "opt="+opt+para,
				dataType: "json",
				async: false, // Doesn't have time to finish with async before redirect
				success: returnedCourse
			});
		} else if (opt === "CPYVRS") {
			$.ajax({
				url: "courseedservice.php",
				type: "POST",
				data: "opt="+opt+para,
				dataType: "json",
				async: false, // Doesn't have time to finish with async before redirect
				success: returnedCourse
			});
		} else if (opt == "UPDATE"){
			$.ajax({
				url: "../DuggaSys/microservices/courseedService/updateCourse_ms.php",
				type: "POST",
				data: "opt="+opt+para,
				dataType: "json",
				success: returnedCourse
			});
			
		} else if (opt == "SETTINGS") {
			$.ajax({
				url: "../DuggaSys/microservices/courseedService/createMOTD_ms.php",
				type: "POST",
				data: "opt="+opt+para,
				dataType: "json",
				success: returnedCourse
			});
		} else {
			$.ajax({
				url : "courseedservice.php",
				type: "POST",
				data: "opt="+opt+para,
				dataType: "json",
				success: returnedCourse
			});
		}

```
