### ISSUE TITLE
Implement retrieveSectionedService_ms.php in all microservices in the sectionedService folder

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15305]
https://github.com/HGustavs/LenaSYS/tree/g2-2024-v5/DuggaSys/microservices/sectionedService

https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/microservices/sectionedService/retrieveSectionedService_ms.php

Note, _updateCourseVersion_sectioned_ms.php_ and _getGitReference_ms.php_ are not fully developed yet. _updateCourseVersion_sectioned_ms.php_ is under development, and we will need to delay _getGitReference_ms.php_ as functionality in the service file is missing. Comments have been added to both of these issues that _retrieveSectionedService_ms.php_ should be implemented when these microservices are developed.

Create microservice getGitReference_ms.php #14927
Created microservice updateCourseversion_sectioned.php #14961

**Comment by a22albjo** [comment]
I have included the retrieve function into the section Microservices, however there is a prolem where not all output is given, for example when deleting a listentry the entries array is not returned. When creating a new entry the array is included meaning there is some inconsistency.

**Comment by a22albjo** [comment]
There seem to be a problem where deleteListentrie_ms.php don't have info about the current course, therefor no listentries is shown.

**Comment by a22albjo** [comment]
After a listEntrie is created all listentries with visibility 3(hidden) is not visible on the screen even if you are a superuser. You need to refresh the page to get the entries to show. Unclear if this is a problem with the monorepo as well.

**Comment by a22albjo** [comment]
**deleteListentrie_ms.php** - After a entry is deleted the toolbuttons are removed:
Before:
<img width="1392" alt="Skärmavbild 2024-05-06 kl  07 58 33" src="https://github.com/HGustavs/LenaSYS/assets/53318057/d278156b-8a17-433b-91fd-11984fc6ca4e">
After:
<img width="1391" alt="Skärmavbild 2024-05-06 kl  07 57 49" src="https://github.com/HGustavs/LenaSYS/assets/53318057/a3cc1e3c-060d-4e5d-9383-1152c03808ba">

**Comment by a22albjo** [comment]
**removeLestEntrie_ms.php**

- After a listEntrie is hidden all listentries with visibility 3(hidden) is not visible on the screen even if you are a superuser. You need to refresh the page to get the entries to show. Unclear if this is a problem with the monorepo as well.

- After a entry is hidden the toolbuttons disappears:
Before: Skärmavbild 2024-05-06 kl  07 58 33
After: Skärmavbild 2024-05-06 kl  07 57 49 After a refresh is made the buttons reappears.

- When visibility is changed with this service it is not crossed out as it is when visibility is changed by the settings.

**Comment by a22albjo** [comment]
**updateListEntriesTabs_ms.php**
- Not outputting any entries, works fine after refreshing the page.

**Comment by a22albjo** [comment]
**reorderListentries_ms.php**

- After a listEntrie is hidden all listentries with visibility 3(hidden) is not visible on the screen even if you are a superuser. You need to refresh the page to get the entries to show. Unclear if this is a problem with the monorepo as well.

- After a entry is hidden the toolbuttons disappears:
Before: ![image](https://github.com/HGustavs/LenaSYS/assets/53318057/92b32f00-c9d4-4bf1-a127-86164be0131e)
After: ![image](https://github.com/HGustavs/LenaSYS/assets/53318057/d6f6dadf-8a6c-4962-9a4c-6180e2befa5b) After a refresh is made the buttons reappears.

- Get a alert that is saying null for no reason, the alert is probably not in the scoope of this issue.

**Comment by a22albjo** [comment]
**getListEntries_ms.php**
- Get a alert that is saying null and then its ok after pressing ok.
