### ISSUE TITLE
Create a retrieveDuggaedService microservice

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15308]
Some of the microservices originating from the servicefiles has no output, while some, such as _updateActiveUsers_ms.php_ from the _showDuggaService.php_, has a very short output. Create the microservice _retrieveDuggaedService_ms.php_, similar to the ones made for _sectionedservice.php (retrieveSectionedService_ms.php)_ and _courseedservice.php (retrieveCourseedService_ms.php)_. __This microservice should then be implemented and called at the end of each microservice in the duggaedService folder__.

**Comment by f22linhe** [comment]
This issue seem to be a duplicate. Create a retrieveDuggaedService microservice #15254 has already been completed and closed. This issue should be closed as not planned.

**Comment by c22mohel** [comment]
Since this has already been completed i will close this issue.
