### ISSUE TITLE
Research current functionality of accessed.php

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15315]
accessed.php is a work in progress site that seems to have some backend development already made, while the front end is very lacking.
The purpose of the site seems to be for admins to controll users access to courses and set different privileges (User is examiner etc).
Currently it is possible to create a user, which is then inserted into "user" table in the database.

There are however many functions that we're unsure of their purpose and we don't exactly know what has been already developed.

We think that the intended functionality is that all users should show up in a list where they would be able to be edited, i'e classes and courses can be added to users and password changes can be made. Searches and filtering should be able to be made.
![image](https://github.com/HGustavs/LenaSYS/assets/129263393/ba7f78fd-dab2-4ef6-99bc-b05aafc846b8)

**Your job is to research what has already been implemented in files accessedservice.php and accessed.js and what is missing for the intended functionality i described above**
Provide a detailed description of what steps are needed to be made in order to start developing this site.
what is missing in order for this to work? what has already been developed etc?

Relevant files: 
LenaSYS\backend-models\functional-requirements\FRD_draft\accessedservice.php_functionalrequirements.txt
accessed.php (frontend)
accessedservice.php
accessed.js

**Comment by a22maxra** [comment]
You are able to filter through people in the search field
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/0d0d6960-551f-40b3-a23d-50dd11e74e12)

However there does not seem to be a way to edit access to the course for users

**Comment by a22maxra** [comment]
When resetting a password a random string is created and mailed to the users email which is the new password
```js
function resetPw(uid, username) {
	rnd = randomstring();

	window.location = `mailto:${username}@student.his.se?Subject=LENASys%20Password%20Reset&body=Your%20new%20password%20for%20LENASys%20is:%20${rnd}%0A%0A/LENASys Administrators`;

	AJAXService("CHPWD", {
		courseid: querystring['courseid'],
		uid: uid,
		pw: rnd,
		coursevers: querystring['coursevers']
	}, "ACCESS");
}
```

**Comment by d22mikwe** [comment]
Gj!
