### ISSUE TITLE
Investigate why the user gets "404 Not Found" error in DuggaSYS

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15325]
When entering DuggaSYS, for example `courseed.php` or `sectioned.php`, you always seem to get a 404 Not Found error. This is because it is failing to get favicon.ico, even though this file still exists. Investigate why this happens and fix the issue, without damaging the appearance of DuggaSYS. 

The most reasonable solution is to fix the requested path, but that's just a theory....  A game theory...........

**Comment by a22edvbu** [comment]
Ok, so what I've found out is that the reason why LenaSYS fails to find favicon.ico is that it tries to look for it in the root folder. The path that its using is _localhost/favicon.ico_ instead of the given path in the php-file.

**Comment by a22moamy** [comment]
Interestingly enough, it still tries to fetch favicon.ico even if you change it to a different file format and change all references to the file according to the new format. The issue is considered low priority and seems to be because of the general server implementation. Issue will be closed.
