### ISSUE TITLE
When checking multiple list entries and dragging one, all of the checked entries should follow along

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15321]
When checking multiple list entries and dragging one, all of the checked entries should follow along. For example, if you check "Färgdugga 1" and "Färgdugga 2" from Datorgrafik, and then drag one of them to a different moment, then both of them should be moved to the new moment, not just the one that was dragged. 

You can check a list entry by pressing its checkbox:
![Skärmavbild 2024-05-03 kl  10 29 13](https://github.com/HGustavs/LenaSYS/assets/129263915/cf61777b-2717-4190-b316-1ad148a62414)

You can drag a list entry by holding its drag-button and moving it. The drag-button:
![Skärmavbild 2024-05-03 kl  10 28 15](https://github.com/HGustavs/LenaSYS/assets/129263915/21e97d9a-8a45-4cac-9cd6-d1be9e250f15)

Checked list entries are currently added to an array, and are used by these two buttons:
![Skärmavbild 2024-05-02 kl  13 56 40](https://github.com/HGustavs/LenaSYS/assets/129263915/061c5e87-dc53-4180-b603-c2965f977da9)

**But they are never used for quick moving of multiple list entries.**

The array structure: 
![Skärmavbild 2024-05-02 kl  13 28 47](https://github.com/HGustavs/LenaSYS/assets/129263915/b82ea66f-511d-4b73-8e39-b970e9dfc690)

There is a [similar issue](https://github.com/HGustavs/LenaSYS/issues/15278) for deleting multiple checked list entries at once, consider checking it out.

**Comment by a22maxra** [comment]
A reorder request is sent from `section.js` with AJAX
```
AJAXService("REORDER", {
        order: str
      }, "SECTION");
```
Which is received in `dugga.js`
```
else if(kind=="SECTION"){
	$.ajax({
		url: "sectionedservice.php",
		type: "POST",
		data: "courseid="+querystring['courseid']+"&coursename="+querystring['courseid']+"&coursevers="+querystring['coursevers']+"&comment="+querystring['comments']+"&opt="+opt+para+"&hash="+hash,
		dataType: "json",
		success: returnedSection
	});
```

Which is relieved by `sectionedservice.php`

**Comment by a22maxra** [comment]
After ´sectionedservice.php´ handles the request the `returnedSection` function gets called with the JSON  responds.

In the `returnedSection` function all elements is added to the _str_ variable and then outputs all of the examples and such in the div with the ID _Sectionlisti_ so when dragging and dropping something it needs to be located where it should be put and refreshed

**Comment by a22maxra** [comment]
Now a microservice is used `/LenaSYS/DuggaSys/microservices/sectionedService/reorderListEntries_ms.php`

**Comment by a22maxra** [comment]
Theres a table **listentries** with a column _pos_ which determines what position each example has in the list

**Comment by a22moamy** [comment]
Dev gave up, putting this on hold
