### ISSUE TITLE
Research if it is possible to create a retrieveGitCommitService_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15335]
See line 924 in:
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/sectionedservice.php

Services like sectionedservice.php has a _Retrieve Information_ part. gitcommitService does not have this part. Research if it is possible and/or necessary to create a retrieveGitCommitService_ms.php. 

https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/gitcommitService.php

**Comment by a22iliru** [comment]
I think its possible to greate a retrieveGitCommitService, and the functionality would be to retrieve data from which the original service file has updated in any way, like  updateGitHubRepo.
