### ISSUE TITLE
Fix functionality to delete a whole course

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15338]
Currently, you cannot delete a whole course. You can press the cogwheel for a course (`in courseed.php`) and press the red delete button, but nothing will happen. Investigate why the button does not work and fix it.

**Comment by b22chran** [comment]
Researched old issues to see where the previous delete-function was removed. Found that the edit course section is not functional because it needs a gitkey to save changes and test the delete function.
