### ISSUE TITLE
Research if microservices cover the entire functionality codeviewerservice.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15344]
Review the microservices in the _codeviewerService_ folder. Do these microservices cover the entire functionality of the original service file, _codeviewerService.php_? If you find any functionalities that are not covered, do we need to create a new microservice for this functionality?

https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/codeviewerService.php

Note, this issue can only be resolved once the issue _Create microservice settingCodeexampleTemplate #14637_ and _Implement retrieveCodeViewerService_ms.php into all microservices in the codeviewerService folder #15387_ has been resolved.

**Comment by a22eddpe** [comment]
Because the two issues #14637 and #15387 has been resolved, this issue should be doable

**Comment by a22eddpe** [comment]
the includes is wrong implemented. This should be a new issue

**Comment by a22eddpe** [comment]
It seems that the microservices cover most of the functionalities present in codeviewerService.php, but some aspects such as user authentication, authorization, and logging are not completely covered. It might be beneficial to separate these functionalities into dedicated microservices. For example, create a microservice for user authentication and authorization can be used to check user authentication and authorization before allowing access to other functionalities within the system.

**Comment by a22eddpe** [comment]
the functions can look something like this :`function checkAuth($courseId, $userId) {
    // Implement your authentication and authorization logic here
    // For example:
    if (checklogin() && (hasAccess($userId, $courseId, 'w') || hasAccess($userId, $courseId, 'st'))) {
        return true;
    } else {
        return false;
    }
}

// Handle request
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Retrieve course ID and user ID from request
    $courseId = $_POST['courseId'];
    $userId = $_POST['userId'];

    // Check authentication and authorization
    $authResult = checkAuth($courseId, $userId);

    // Return authentication result
  `

**Comment by a22eddpe** [comment]
dont forget to include the correct files and database
