### ISSUE TITLE
Pressing the "Show files"-button from the navbar of a course generates error message

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15341]
When pressing the "Show files"-button from the navbar of a course, this error message is generated in the console:
![Skärmavbild 2024-05-03 kl  14 56 43](https://github.com/HGustavs/LenaSYS/assets/129263915/7118df86-263d-45d6-bd62-919ca114478d)

**Please fix this.**

The "Show files"-button (from `sectioned.php`):
![Skärmavbild 2024-05-03 kl  14 57 05](https://github.com/HGustavs/LenaSYS/assets/129263915/9cd1fef1-b282-4cfc-9c5a-2b7a15ab161a)

**Comment by a22samka** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/129301680/97bcd89b-71b6-43ed-8f82-763318dfabb3)
Fixed another error aswell
