### ISSUE TITLE
Research if microservices cover the entire functionality of the servicefile accessedservice.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15340]
Review the microservices in the accessedService folder. Do these microservices cover the entire functionality of the original service file, accessedservice.php? If you find any functionalities that are not covered, do we need to create a new microservice for this functionality?

https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/accessedservice.php

**Comment by a22iliru** [comment]
The current microservices implement the entire functionality of the original service.  The other file "retrieveAccessedService.php" implements the second half of this file which is retrieving information.
