### ISSUE TITLE
Create microservice highscoreservice_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15352]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/backend-models/microservices/duggaSys%20services/Microservices.md

Research the service highscoreservice.php and see if you can create a highscoreservice_ms.php

**Comment by c20juler** [comment]
The microservice seems a bit redundant as the original mono file is already reasonably small. Im not sure if the file should be simmered down further so will just create the file and add it to microservices/highScoreService/highscoreservice_ms.php.
