### ISSUE TITLE
Research if microservices cover the entire functionality of profileservice.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15359]
Review the microservices in the profileService folder. Do these microservices cover the entire functionality of the original service file, profileservice.php? If you find any functionalities that are not covered, do we need to create a new microservice for this functionality?

https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/profileservice.php

**Comment by a22eriwi** [comment]
Me and c22emigr created 2 different ms: "updateSecurityQuestion_ms.php" and "updateUserPassword_ms.php" which are both located in the profileService folder. There doesn't seem to be anything that is missing from the profileservice.php file that needs to be implemented somewhere else. In my opinion this issue can be closed now.
