### ISSUE TITLE
Research if microservices cover the entire functionality profileservice.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15351]
Review the microservices in the profileService folder. Do these microservices cover the entire functionality of the original service file, profileservice.php? If you find any functionalities that are not covered, do we need to create a new microservice for this functionality?

https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/profileservice.php

**Comment by a22iliru** [comment]
Since this monolith file is really small, the current microservices does cover the entire functionality of it.
