### ISSUE TITLE
Research if microservices cover the entire functionality of courseedService.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15379]
Review the microservices in the courseedService folder. Do these microservices cover the entire functionality of the original service file, courseedservice.php? If you find any functionalities that are not covered, do we need to create a new microservice for this functionality?

https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/courseedservice.php

Note, this issue cannot be resolved until this issue has been resolved:

Create microservice copyCourseVersion #14198

**Comment by a22iliru** [comment]
It seems like not all services are implemented. After looking at the microservices in the courseed folder it is missing functions related to useranswer, quiz etc however I remember that these issues have been implemented

**Comment by c22mohel** [comment]
the funcctionalitys for courseedservice.php are the following:
Create new course
Create course version 
Update course 
Update course version 
Delete course 
Copy course version 
Create/change message of the day 
Change Active course Version
Retrieve courses
Special update 

all the functionality is covered by microservices except Special update. 
Some microservices lack logging. I will create new issues for these problems.

**Comment by c22mohel** [comment]
Specialupdate have now been added as a microservice. With this all functionalities are covered this issue can now be closed.
