### ISSUE TITLE
Go over test for the microservice addClass_ms.php again

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15377]
See parent issue: _Create new tests for the microservices created from accessedService.php #15177_

The test for this microservice was created before the retrieveAccessedService_ms.php was created. Therefore, go over the test again and make sure it works once the retrieveAccessedService_ms.php has been implemented. If it does not work as aspected, make sure it does.

Note, this issue cannot be resolved until these issues has been resolved:

Create a retrieveAccessedService microservice #15250

Create new test for the retrieveAcessedService_ms.php #15306

**Comment by c22cargo** [comment]
The retrieve MS always returns NULL from addClass_ms. This needs to be fixed before the test can be fixed.
