### ISSUE TITLE
Research if microservices cover the entire functionality of the servicefile fileedservice.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15374]
Review the microservices in the fileedService folder. Do these microservices cover the entire functionality of the original service file, fileedservice.php? If you find any functionalities that are not covered, do we need to create a new microservice for this functionality?

https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/fileedservice.php

**Comment by c22emigr** [comment]
After researching it seems like all the code from the monolith file is used in the three microservices in the folder fileedService so there is no need to create any more microservices out of the monolith file.
