### ISSUE TITLE
Create new test for the microservice copyCourseVersion_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15378]
See parent issue: _Create new tests for the microservices created from courseedService.php #15187_

**Comment by a22iliru** [comment]
There is a foreign key constraint problem with this issue,

**Comment by a22iliru** [comment]
I will work on another test as the foreign key constraint does not seem to resolve

**Comment by a22marca** [comment]
I have implemented the test. The test only works for the microservice copyCourseVersion, not on courseedservice
