### ISSUE TITLE
Research and possibly update setVisibleListentries_ms.php

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15380]
line 31 in _setVisibleListentries_ms.php_ is not doing anything at the moment, maybe this can be removed or the query needs to be changed:

    // prepare SQL query
    $query = $pdo->prepare("UPDATE listentries Set visibility = :listentryId");

    // Bind Parameters
    $query->bindParam(':cisiblity', $visibility);
    $query->bindParam(':listentryId', $listentryId);
    
Research and update if needed!

**Comment by a22iliru** [comment]
The ms is trying to update visibility column wiht the value of :listentryId  , which is incorrect. I will make it update visibility that is identified by its listentryId.
