### ISSUE TITLE
Implement retrieveCodeViewerService_ms.php into all microservices in the codeviewerService folder

### ISSUE THREAD

**Issue by f22linhe** [HGustavs/LenaSYS#15387]
https://github.com/HGustavs/LenaSYS/blob/g2-2024-v5/DuggaSys/microservices/codeviewerService/retrieveCodeviewerService_ms.php

https://github.com/HGustavs/LenaSYS/tree/g2-2024-v5/DuggaSys/microservices/codeviewerService

The retrieveCodeViewerSerice_ms.php should be implemented and called in the end of all microservices in the codeViewerService folder.

**Comment by b21isabe** [comment]
I believe I am finished with the implementation of the retrieve with all microservices, but I can't test right now because I am having some very strange problems with my database right now. I will try to fix this and then test again before making a PR.
