### ISSUE TITLE
Cannot set default version when creating new course version

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15392]
Users are experiencing problems when creating a new course version.
When checking the box to use the new copied course version as default the course version is not created.

Look into whats causing this and solve it.

**Comment by a22maxra** [comment]
I'll start doing commits tomorrow after the weekly merge

**Comment by a22maxra** [comment]
![image](https://github.com/HGustavs/LenaSYS/assets/98206230/a523988c-31ef-4dd0-9c0b-5cd40e5b09e1)

![image](https://github.com/HGustavs/LenaSYS/assets/98206230/fbf0c178-d850-42c0-94eb-49e324d10ca6)

Despite a success message when checking the "Change this to default version" the is no new course version

**Comment by a22maxra** [comment]
Even the regular new version of a course does not seem to work even without checking the box

**Comment by a22maxra** [comment]
I'm trying to see why new versions no longer get created in either case, when using a switch with cases the case is not triggered for some reason, but when switching back to a if a new version is still not created even though the request is sent

**Comment by a22maxra** [comment]
The problem is in when the "CPYVRS" argument is passed to `courseedservice.php`, when "NEWVRS" is passed a new version is created, so looking at logic in in `courseedservice.php` when "CPYVRS" is passed.

**Comment by a22maxra** [comment]
There was a missing $ sign in front of the _allOperationsSucceeded_ variable in `courseedservice.php`

**Comment by a22maxra** [comment]
There is some problem when copying certain groups where the progressBar class styling doesn't show

**Comment by a22maxra** [comment]
There is an error message when copying a course and entering a dugga

![image](https://github.com/HGustavs/LenaSYS/assets/98206230/7a23cac8-99af-482b-a303-960749d6755b)
