### ISSUE TITLE
Research if microservices cover the entire functionality of sectionedService.php

### ISSUE THREAD

**Issue by a22albjo** [HGustavs/LenaSYS#15406]
SectionedService seem to be missing ms for the opts: REFGIT and CREAGITEX. 
And no service seem to do what is done on row 912 - 919:
```
else if (strcmp($coursevers, "null")!==0) {
	// Get every coursevers of courses so we seed groups to every courseversion
	$stmt = $pdo->prepare("SELECT vers FROM vers WHERE cid=:cid");
	$stmt->bindParam(":cid", $courseid);
	$stmt->execute();
	$courseversions = $stmt->fetchAll(PDO::FETCH_COLUMN);
	$totalGroups = 24 * count($courseversions);
} 
```

Check to se if anything else is missing from the file and create issues for them.

**Comment by c22emigr** [comment]
After researching this i have found that the opt CREAGITEX does have a microservice that is called createGithubCodeExample_ms.php that has the required functionality.

I couldnt find a microservice that uses the opt REFGIT that is a part of retrieving files from Github.

![image](https://github.com/HGustavs/LenaSYS/assets/129170158/78996228-e80f-403a-8af6-babc378ae19c)

As for row 912 -> 919 it seems like this piece of code is never used in any of the microservices that i could find. As that code seems to retrieve all the versions of a course. I suggest putting it in one of the microservices managing course versions like getCourseVersion_ms or updateCourseVersion_ms

![image](https://github.com/HGustavs/LenaSYS/assets/129170158/c8259d73-848c-4686-95c2-977599df9c46)

**Comment by a22eriwi** [comment]
I have researched the file sectionedService.php and have come to the conclusion that everything is used except the code that is on row 482 - 486 and row 912 - 919. The code on row 912 - 919 retrieves versions of a course for a certain course id and then calculates the total number of groups by multiplying the number of elements in the "$courseversions" array by 24.

**Comment by c22emigr** [comment]
Found the issue for the opt REFGIT on row 482. https://github.com/HGustavs/LenaSYS/issues/14927 
Not really sure what is going on with that issue
