### ISSUE TITLE
Sequence Lifeline object is black instead of white

### ISSUE THREAD

**Issue by a22vioja** [HGustavs/LenaSYS#15468]
## Description
Sequence Lifeline object in the toolbar is black instead of white as others.

<img width="469" alt="Screenshot 2024-05-07 at 14 22 25" src="https://github.com/HGustavs/LenaSYS/assets/129263559/56bc1be1-473c-40ee-bb69-a73700435743">

## Job

Icon should be changed to white.

**Comment by a21liltr** [comment]
Solved by PR #15639 for issue #15589
