### ISSUE TITLE
There is nothing hindering the user from saving illegal characters in student feedback input

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15487]
There is nothing hindering the user from saving illegal characters in student feedback input in the dugga-form. 
This can be seen below where no user feedback (ironically) is given when you write illegal characters in the last input of a dugga.
![Skärmavbild 2024-05-07 kl  16 55 37](https://github.com/HGustavs/LenaSYS/assets/129263915/cf090367-3a5a-4e15-8922-036cb75c2be4)

Saving the dugga with these illegal characters will disable the user to ever open it again.
Implement a similar feedback system to the "Name"-input since they have the same illegal characters. A tooltip should appear, warning the user about the illegal characters. The input should also turn red, like other inputs when entering bad data.

**Comment by a23simry** [comment]
Opening this issue as it it still relevant, though it might be fixed if/when the feedback functions are removed.
