### ISSUE TITLE
Change the icon for Sequence Object

### ISSUE THREAD

**Issue by a22vioja** [HGustavs/LenaSYS#15589]
## Description 

There is an "eye" icon for the Sequence Object in the toolbar. It should be changed to Sequence Object element.
They are in a folder 2 ../Shared/icons/diagram_sequence_object.svg

## Job

Change the icon in the toolbar.

**Comment by c22abdha** [comment]
The icon has been replaced in the diagram.php file.
By replacing
shared/icons/eye_icon.svg
to
diagram_sequence_object.svg

![image](https://github.com/HGustavs/LenaSYS/assets/129261791/fa27e85b-7629-4a16-9d6b-7daccb7a3536)
