### ISSUE TITLE
Course status should be yellow aswell

### ISSUE THREAD

**Issue by a13denli** [HGustavs/LenaSYS#1562]
![image](https://cloud.githubusercontent.com/assets/11715616/7725309/b8248f00-fef9-11e4-9efd-7996d35e3d75.png)
Even if you have something handed in, course status still remains unchanged(it's white), but it should be yellow.

**Comment by a13denli** [comment]
Not sure if it can be done

**Comment by a13oscwe** [comment]
Should definitely be doable and makes sense, i would consider this a bug atleast.

**Comment by a13denli** [comment]
Completed
