### ISSUE TITLE
Can't have some characters in important words

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#1564]
Having certain characters in important words causes them to not be highlighted. Thus far I have tested to have "." and "=".
![1](https://cloud.githubusercontent.com/assets/11722176/7725329/e6303cdc-fef9-11e4-959b-855868a9245a.png)

**Comment by a13erisc** [comment]
This seems to be related again with the tokenizer. Console and log are both "name" kinds, while the punctuation becomes an "operator". Would it be possible to create some sort of compound important word type, which consists of various token kinds? This would be useful for console.log() and the like.
