### ISSUE TITLE
Duggas not working when copying new course and setting as default version

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15653]
See #15566 

When creating a new course version and copying from a course and setting it as default version the duggas do not work. When trying to load a dugga an error occurs.

![image](https://github.com/HGustavs/LenaSYS/assets/129263393/bc255cd1-cf5e-4b64-a2fa-049fed4183cf)

![image](https://github.com/HGustavs/LenaSYS/assets/129263393/f5f2431f-3f87-44dc-a422-085315862c5d)

Look into it and resolve the problem so duggas can be loaded.

**Comment by a22moamy** [comment]
Cannot be done due to other bugs.
