### ISSUE TITLE
Create or implement retrieval of courseversions into a new ms or an existing.

### ISSUE THREAD

**Issue by c22emigr** [HGustavs/LenaSYS#15652]
![image](https://github.com/HGustavs/LenaSYS/assets/129170158/97cbd48a-fab2-4b6e-a055-6a481f22f0a4)

Row 912 -- 920 in sectionedservice.php

**Comment by a22eriwi** [comment]
This ms retrieves all the course versions from the database table "vers" for a particular course id and then calculates the number of groups by multiplying the course versions with 24. 
This code was taken from the sectionedservice.php file from row 912.
