### ISSUE TITLE
Scale Sequence OBJECT on the height 

### ISSUE THREAD

**Issue by a22vioja** [HGustavs/LenaSYS#15679]
## Description
If a sequence object is scaled on the X-axis then the character expands on height as well and then get's hidden because of the overflow.

https://github.com/HGustavs/LenaSYS/assets/129263559/7e5284fc-974f-4338-b8f8-cfaf23f22b95

## Job
Make it so that sequence object lifeline also scale vertically when scaled horizontally.

**Comment by a21liltr** [comment]
will be solved by PR #15602

**Comment by a21liltr** [comment]
Solved by #15999.
