### ISSUE TITLE
Buttons for adding/removing imp words placed weirdly in Firefox

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#1568]
Also some other oddities in the Edit Example window. Like the text field for "Title:" going outside the window. Bug only encountered in Firefox.
![1](https://cloud.githubusercontent.com/assets/11722176/7743451/3e59c22e-ff9b-11e4-9ae4-c2d2cd9ca5d4.png)

**Comment by a13jansa** [comment]
iam on it.

**Comment by c13caral** [comment]
this is now solved :+1:
