### ISSUE TITLE
Create new test for the microservice getDeletedListEntries_ms.php

### ISSUE THREAD

**Issue by a22marca** [HGustavs/LenaSYS#15688]
See parent issue: [Create new tests for the microservices created from sectionedService.php](https://github.com/HGustavs/LenaSYS/issues/15681)

**Comment by f22linbe** [comment]
This service retrieves all hidden (removed) list entries but the service is not storing the data it retrieves from the database anywhere on (see code lines 27-38 below).

```
$results = array();

$query = $pdo->prepare("SELECT * FROM listentries WHERE visible = '3'");
if($query->execute()) {
    while ($row = $query->fetch(PDO::FETCH_ASSOC)){
        array_push($results, $row);
    }
}else{
    $debug="Failed to get listentries with visibility DELETED!";
}

echo json_encode(retrieveSectionedService($debug, $opt, $pdo, $uid, $courseid, $coursevers, $log_uuid));
```

**Comment by a22marca** [comment]
This microservice was removed. Closing this issue
