### ISSUE TITLE
Able to edit the description box via important words

### ISSUE THREAD

**Issue by a13erisc** [HGustavs/LenaSYS#1569]
For example, adding h*e as an important word, causes this to be the output in the description box.

![wwww](https://cloud.githubusercontent.com/assets/11733626/7743834/92faab10-ff9e-11e4-869a-3548fba1482f.jpg)

**Comment by f12danjo** [comment]
Fixed by [#1623](https://github.com/HGustavs/LenaSYS/pull/1623)
