### ISSUE TITLE
Create new test for the microservice updateListEntriesTabs_ms.php

### ISSUE THREAD

**Issue by a22marca** [HGustavs/LenaSYS#15700]
See parent issue: [Create new tests for the microservices created from sectionedService.php](https://github.com/HGustavs/LenaSYS/issues/15681)

**Comment by c22cargo** [comment]
It seems that "tabs" is always retrieved as NULL, even when the value is not set to NULL. This likely has to do with the retrieve MS, and it will have to be fixed before the expected-output can be updated.

**Comment by c22cargo** [comment]
The problem above was fixed in #15748.
