### ISSUE TITLE
Add Enter-listener for creating new course

### ISSUE THREAD

**Issue by a22moamy** [HGustavs/LenaSYS#15719]
# The issue
When creating a new course, you should be able to press Enter to submit the form. This should only be allowed if all fields have correct values though, just like how the "Create" button gets disabled when fields are not correct.

![Skärmavbild 2024-05-14 kl  13 11 32](https://github.com/HGustavs/LenaSYS/assets/129263915/55028a73-af63-47ff-ae41-ba5130ace331)

**Comment by a22chrfa** [comment]
When clicking the the submit button with the mouse it calls "validateForm('newCourse')". This will validate the form and then call a function to create the course should the validation go through. 

We can use this by simply adding an event listener to the surrounding div of the form. Will try this.
