### ISSUE TITLE
login button

### ISSUE THREAD

**Issue by a12jiyba** [HGustavs/LenaSYS#1577]
When a example name is too long then the login button disappear it do not matter if i have the web browser in fullscreen(its different in different resolutions). 
The solution will be that we could make so that the login button is always showing on the right side no matter if the example name is too long.

**Comment by b13danso** [comment]
Didnt merge.

**Comment by b13danso** [comment]
We merged a temporary fix for this, we changed the font in navHeading from 2.5em to 26px, fixing the problem with lower resolutions having to large text and pushing the loginButton away. This cant be fixed now because the whole navHeader-file is structured after a table.
