### ISSUE TITLE
[Documentation] camera.js

### ISSUE THREAD

**Issue by a21liltr** [HGustavs/LenaSYS#15791]
## Description
We have documentation of the old diagram.js file, however, the code has been changed quite substantially.
Therefore, the documentation that was made during the early part of the period needs to be updated with the new changes and we need more documentation to include the moved classes and functionality.

## Job
Write new documentation for camera.js

**Comment by b22jonan** [comment]
@a21liltr i dont think anythis needs to be done in camera.js, i read through it and its properly commented everywhere and the only function in there has a nice description, nothing needs to be done here.

**Comment by b22jonan** [comment]
having read into the document more i just go ahead and say that the documentation i sup to date as of today.

**Comment by a21liltr** [comment]
Nothing to add.
