### ISSUE TITLE
Test microservices from sectioned service

### ISSUE THREAD

**Issue by a22albjo** [HGustavs/LenaSYS#15817]
To test:
opt "DELETE": URL= "../DuggaSys/microservices/sectionedService/removeListEntries_ms.php";
opt "DEL": URL= "../DuggaSys/microservices/sectionedService/deleteListEntries_ms.php";
opt "NEW": URL= "../DuggaSys/microservices/sectionedService/createListEntry_ms.php";
opt "REORDER": URL= "../DuggaSys/microservices/sectionedService/reorderListEntries_ms.php";
opt "UPDATE": URL= "../DuggaSys/microservices/sectionedService/updateListEntries_ms.php";
opt "UPDATETABS": URL= "../DuggaSys/microservices/sectionedService/updateListEntriesTabs_ms.php";
opt "UPDATEDEADLINE": URL= "../DuggaSys/microservices/sectionedService/updateQuizDeadline_ms.php";
opt "SETVISIBILITY": URL= "../DuggaSys/microservices/sectionedService/setVisibleListentries_ms.php";
opt "GRP": URL= "../DuggaSys/microservices/sectionedService/getCourseGroupsAndMembers_ms.php";
opt "CHGVERS": URL= "../DuggaSys/microservices/sectionedService/changeActiveCourseVersion_sectioned_ms.php";
opt "get": URL= "../DuggaSys/microservices/sectionedService/getListEntries_ms.php";

**Comment by c22cargo** [comment]
Working:
* createListEntry (Works fine unless there is a "group activity" in the course. If there is one the MS still works, but you need to refresh the page to see new listentries. This may not be the fault of this MS.)
* removeListEntries (Only seems to work a few times, after that it stops working. Changing back to the monolith doesn't fix this though so the MS will stay implemented.)
* deleteListEntries
* reorderListEntries
* updateListEntries
* updateListEntriesTabs (Works but there is no frontend)

Not working:
* getListEntries (works until there is a "group activity" in a course.)
* updateQuizDeadline

Can't test:
* setVisibleListentries
* changeActiveCourseVersion_sectioned
* getCourseGroupsAndMembers

--------------------------------------------------------------------------------------------------------------------------------------------

The microservices that seem to be working and those that I was unable to test will be implemented. Those that weren't working will have to be fixed before implementation.
