### ISSUE TITLE
Unable to move a sequence box if you have to scroll

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#1585]
You are unable to drag a sequence box from "Unused Examples" into "Sequence Examples" if you have to scroll to get it there.

**Comment by b13danso** [comment]
Got a fix for it, will be able to make a pull request next week.

**Comment by b13danso** [comment]
Fixed.

**Comment by f12danjo** [comment]
Fixed by [#1642](https://github.com/HGustavs/LenaSYS/pull/1642).
