### ISSUE TITLE
Weird behaviour on A4 template

### ISSUE THREAD

**Issue by a21liltr** [HGustavs/LenaSYS#15872]
https://github.com/HGustavs/LenaSYS/assets/129370135/93c83c81-463b-4ee1-b440-466f99292c2c

## Description
The A4 template behaves weirdly when the button for horizontal is clicked first. The vertical layout for the A4 template is displayed by default and does not disappear after clicking horizontal. the first time. The user has to actually press the vertical button for it to disappear first, after which only the button for the flipped template may be pressed. After this happens, the horizontal A4 also starts scaling with the zoom, which it is not supposed to. It is supposed to be a constant size.

## Job
1. Fix the issue with the double overlapping of A4 templates.
2. Find out why A4 horizontal scales with zoom. If it's easy to fix, do it, otherwise report back the findings of the problem.

**Comment by a22alfna** [comment]
I was working on this issue but it seems like this issue just like my last was solved by someone elses issue getting merged.
