### ISSUE TITLE
Update Wiki for planned async fetching of git repos

### ISSUE THREAD

**Issue by d22mikwe** [HGustavs/LenaSYS#15903]
Update with the current plans of making the fetching of github repos asynchronous.

Include:
- Progress so far regarding this functionality (Including code)
- What needs to be done in additionally to be able to implement the solution
- Small description of the purpose of the change

**Comment by a22ahmom** [comment]
A wiki page has been created with a description of how to make the fetching of github repos asynchronous. 
https://github.com/HGustavs/LenaSYS/wiki/asynchronous-fetching-of-git-repos

**Comment by d22mikwe** [comment]
Great Work!
