### ISSUE TITLE
Add documentation for microservices in highscoreService

### ISSUE THREAD

**Issue by a22iliru** [HGustavs/LenaSYS#15974]
LenaSYS\DuggaSys\microservices\highscoreService

**Comment by c20juler** [comment]
There are 2 microservices in highscoreService that needs to be documented. A single md file will be created in the highscoreService folder to document both microservices.

**Comment by c20juler** [comment]
Documentation for these microservices already exists in "Microservices.md", this issue will therefore be closed. I will also close my pull request when working on #16209.
