### ISSUE TITLE
Highlight bug in description box

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1599]
There seems to be a bug with mouseover highlight for certain inputs.

![errordumphighlightdesc](https://cloud.githubusercontent.com/assets/11715509/7745614/e9ec6450-ffac-11e4-9fff-da942c290be4.png)

**Comment by b12simsa** [comment]
Cannot find this example anymore so I think we could close this one.

**Comment by b12simsa** [comment]
Bug reoccured.

**Comment by b12simsa** [comment]
The word appendChild existed twice in the sql-file used to initialize the database.

**Comment by f12danjo** [comment]
Fixed by [#1663](https://github.com/HGustavs/LenaSYS/pull/1663).
