### ISSUE TITLE
Code Viewer:  Beforebutton and aftbutton doesn't work properly

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1612]
You can't switch to another code example. There is a bug somewhere in the code

**Comment by a13jorla** [comment]
This is due to changes in the before and after tuples in the database. if there is an incorrect sequence the function for the button will disable the buttons.

**Comment by a13alfbe** [comment]
There was incorrect data in the database. It works properly now after a new initialization and testdata being inserted.

**Comment by c13caral** [comment]
This is no longer relevant. We have made a new issue for this problem that explains the problem.
