### ISSUE TITLE
Code Viewer:  It doesn't work to move around the others pop-up boxes 

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#1613]
It doesn't work to move the pop-up boxes like Login and Edit Content.

This problem I think is something that was made by us in code viewer.

**Comment by c13caral** [comment]
Maybe just add a class to Edit Content. Now it is hard to example add important row when the code is hidden by the pop-up window. You maybe don't remember which row you want to highlight

**Comment by f12danjo** [comment]
Fixed by [#1641](https://github.com/HGustavs/LenaSYS/pull/1641).
