### ISSUE TITLE
Update 'popup form convention' wiki

### ISSUE THREAD

**Issue by a20jonda** [HGustavs/LenaSYS#16148]
A lot of changes to the forms have been made and new conventions have been created. The wiki will be updated to include these.

Also all forms in listed in this [table](https://github.com/HGustavs/LenaSYS/wiki/Popup-form-conventions#currently-known-popup-forms-on-lenasys) will need to be assessed.

**Comment by a22moamy** [comment]
Looks great! The aspects that previously got critiqued have been fixed nicely, well done :D !!!
