### ISSUE TITLE
Code Viewer: Tag not highlighted correctly (mouseover)

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1653]
When the last html tag is moused over the correct tag is not highlighted. The body tag at line 12 is highlighted instead of the html tag on line 2.

![errordumphighlightmouseover](https://cloud.githubusercontent.com/assets/11715509/7796522/57e7f4b6-02e0-11e5-9a51-df0342800f0c.png)

**Comment by f12danjo** [comment]
Fixed by [#1660](https://github.com/HGustavs/LenaSYS/pull/1660).
