### ISSUE TITLE
About lay-out standard

### ISSUE THREAD

**Issue by a13denli** [HGustavs/LenaSYS#1661]
I want to change the table in Access editor to look like something like this:
![image](https://cloud.githubusercontent.com/assets/11715616/7797135/59c28834-02e8-11e5-9acc-18b44cb8524a.png)

Instead  of this: 
![image](https://cloud.githubusercontent.com/assets/11715616/7797139/697e3908-02e8-11e5-9bb0-431878b8aed7.png)

But I'm not sure if I'm allowed to change so the cogwheel is on the left side and not the right side?

**Comment by HGustavs** [comment]
No problems, as long as the functionality remains.
