### ISSUE TITLE
Possible to enter negative row numbers in important rows.

### ISSUE THREAD

**Issue by e12johka** [HGustavs/LenaSYS#169]

**Comment by a13jorla** [comment]
At the present time you can still enter numbers that do not exist. If they follow eachother like 40-41. 40-38 is not able to enter. Same goes for negative numbers like -40--41 and -40--38.

**Comment by c13caral** [comment]
Now you can't enter negative numbers like -2 - 3 but you can still enter numbers that don't exist

**Comment by f12danjo** [comment]
Fixed by [#1630](https://github.com/HGustavs/LenaSYS/pull/1630).
