### ISSUE TITLE
Sequence name

### ISSUE THREAD

**Issue by a13alfbe** [HGustavs/LenaSYS#1699]
Would be nice if the user was prompted to name the sequence before creating it. As of now the sequence gets named the next incremental number. This makes it hard to find the right sequence in the dropdown list.

![untitled](https://cloud.githubusercontent.com/assets/11715493/7830429/81ff09b0-044d-11e5-9dab-ac983d5d164e.png)

Don't know what would be best, either a pop-up that appears once you click "New sequence" where the user type the name or a new text input in the edit example box.

**Comment by h14marma** [comment]
Is this an old feature? @a97marbr

**Comment by b14rebst** [comment]
@HGustavs

**Comment by a17poner** [comment]
Pretty sure there is nothing named sequence anymore in codeViewer, assuming this was before a big change in codeviewer (possibly before the removal of fileEditorV50.php? ) closing.
