### ISSUE TITLE
Possible to drag and drop a template

### ISSUE THREAD

**Issue by e12johka** [HGustavs/LenaSYS#170]
It is possible to drag and drop a template outside the box. if you do this twice, there is no more templates left in the box and you have to go back to the examples for  the templates to reappear as usual. 
it is also possible to copy rows of code and put there.
this only regards the template tab.

**Comment by c13caral** [comment]
Is this still relevant?.
I have tested to drag and drop a template outside the box. And it doesn't work but that's is a good thing?
I don't think that I really understand the issue.

**Comment by c13caral** [comment]
This is not longer relevant. Will now close this issue.
