### ISSUE TITLE
Template button

### ISSUE THREAD

**Issue by a13alfbe** [HGustavs/LenaSYS#1705]
- Should the template button be removed from the navheader?
- Should the template button be located in the "Edit example" box instead? 

The template button works pretty well right now. Additional boxes are created if the example is missing any boxes for that template. So if you have an example with 2 boxes, and change to a template that requires 4 boxes, 2 additional empty boxes are created automatically.
If you do the opposite and change to a template with less boxes, the first boxes in order gets used.

**Comment by a17alevu** [comment]
@HGustavs Is this something that should be prioritized?

**Comment by a17alevu** [comment]
Closing this issue.
