### ISSUE TITLE
Redundant code for datepicker.

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#1729]
Some redundant code when changing the minimum deadline date to be the release date. Also needs to fix the deadline date not being properly set when the page is loaded.

**Comment by a13arnhe** [comment]
There doesn't seem to be any redundancy of the deadline date setter at this moment. Deadline is changed if release date is changed and min date is fetched from the database as the release date if there is no change of the release data and to init it. Probably already fixed before.
