### ISSUE TITLE
Codeviewer Markdown Lists formatted in Code Blocks 

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1733]
If a list is written inside a code block like:
  \~\~\~
  \- 1
  \- 2
  \- 3
  \~\~\~
The code block loses it font style.

**Comment by b14rebst** [comment]
Codeblocks are using "Hack" as font. I don't see any problems here since it's working properly. @HGustavs what exactly is losing its font style?

**Comment by HGustavs** [comment]
I think this has been resolved.
