### ISSUE TITLE
Codeviewer Parenthesis Written Twice

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1734]
In example 8, parenthesis after functions are some times written twice (might occur in several examples). Example function() becomes function()().

**Comment by b14davbo** [comment]
@HGustavs what is example 8?

**Comment by a17vikab** [comment]
To be able to work on this issue, the #5988 needs to be solved.

**Comment by a17andby** [comment]
Have tried to recreate this issue by checking different types of files on the CodeViewer. I can't reproduce that parenthesis are written twice.

My suggestion is that we close this issue and if we stumble on this issue again we could just reopen this issue.

**Comment by a17alevu** [comment]
Closing this issue.
