### ISSUE TITLE
Edit example box not displayed correctly in firefox

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1735]
The field for writting the title of an example, does not fit the box. Buttons for adding and removing words are on the wrong side of the dropdown list for important words. There should also be some padding between the section title field and the title field.
![errordumpfirefox](https://cloud.githubusercontent.com/assets/11715509/7878521/adc9f53c-05e7-11e5-8190-b99d0f3c4c4a.png)

**Comment by a14jimso** [comment]
This had been fixed.
