### ISSUE TITLE
Important words break markdown code in description

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1738]
If word used for writting html tags is used as an important word, and the tag is used in the description box it will be printed out in the description box.
![errordumpimportantwordmarkdown](https://cloud.githubusercontent.com/assets/11715509/7879524/4e9b5bc8-05f1-11e5-93c2-c9317a9f4bc1.png)

**Comment by A15cecal** [comment]
This has been solvedby other issues.
