### ISSUE TITLE
Html tags disappear from the description box

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#1739]
Html tag are removed from the description box, alternative solution is to convert '<' and '>' to \&lt; and \&gt;, instead.

**Comment by b14rebst** [comment]
Is this issue still relevant? We don't really understand the problem. There is code in markdown.js and showdoc.php that replaces '<' and '>' to &lt; and &gt;. Also in codeviewer.js there is code that fix this. It would be nice to have a picture that illustrates the problem. @HGustavs

**Comment by HGustavs** [comment]
I think this has been fixed. I would retire the issue.
