### ISSUE TITLE
Underscore '_' is stripped in plain text

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1751]
Underscore '_' is stripped in plain text code box.

**Comment by a97marbr** [comment]
I think this is markdown-related. Underscore is used for making text italic, however, this should not happen inside a code section, right?

**Comment by a15herny** [comment]
Where is this located? Is it in the dagbok/diary view?

**Comment by A15cecal** [comment]
@a97marbr @HGustavs This seems to be solved now, or maybe I don't understand the problem?

**Comment by A15cecal** [comment]
Solved already. Closing.
