### ISSUE TITLE
Swedish characters not allowed in course "moment"

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1758]

**Comment by a14maxry** [comment]
it seems to work right now as far as i can see

**Comment by a97marbr** [comment]
![capture](https://cloud.githubusercontent.com/assets/4948661/14325210/93606a54-fc28-11e5-8ad3-b30d993059d7.PNG)
The bug appears if we first add a title with Swedish characters and then later want to edit the tile. See enclosed image.

**Comment by a15freed** [comment]
This is solved
