### ISSUE TITLE
Markdown http link support is partially finished

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1766]
The problem is that we allow any kind of link in the markdown link.
!!!ftp://!!!%%%foo%%%
do we allow ftp or only htpp/https/lenasys links?

Perhaps for performance reasons we let it this be?

**Comment by h14marma** [comment]
This is a pretty old issue. How do you feel about this now? @HGustavs

**Comment by b14rebst** [comment]
@HGustavs

**Comment by HGustavs** [comment]
I think we can retire this issue.
