### ISSUE TITLE
important rows is not working properly

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1767]

**Comment by HGustavs** [comment]
I have removed a number of checks with bugs in them for the important rows code.

We need to check that isNumber works for empty strings or white space strings also. If not this functionality needs to be added to compensate.

**Comment by HGustavs** [comment]
Previously the code checked the row numbers against the tokenizer row number global... but this does not work when there is more than one code box.

**Comment by a14jonal** [comment]
isNumber is no longer used in the important rows code.
