### ISSUE TITLE
A quick upload feature in CodeViewer

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1773]
It would be very convenient to be able to upload a new version of a code example or example description directly from the code viewer.

**Comment by b17annni** [comment]
Is this still relevant? More notes? @a97marbr @HGustavs

**Comment by a17andby** [comment]
Isn't this already fixed? We have a File Upload button in Codeviewer now.

![Screenshot from 2019-05-17 14-47-34](https://user-images.githubusercontent.com/49235724/57929221-fd424000-78b2-11e9-959d-d9b95ea70358.png)

**Comment by a17alevu** [comment]
Im closing this.
