### ISSUE TITLE
Our md should be documented in github - not in PDF

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1776]
We should have a lenasys-markdown.md file.

**Comment by a97marbr** [comment]
I have started this. A first example exists: https://github.com/HGustavs/LenaSYS/blob/master/lenasys-markdown.txt

**Comment by b14davbo** [comment]
It's now documented in both GitHub Wiki & in /Examples/

https://github.com/HGustavs/LenaSYS/blob/master/Examples/markdown-examples.md
