### ISSUE TITLE
Code viewer templates missing

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1779]
There are a few tempates missing from the code viewer
- One single pane
- More top-to bottom variants e.g. two or three stacked

more?

**Comment by a17robes** [comment]
Added a single pane template. The SVG-icon looks like this:
![image](https://user-images.githubusercontent.com/38004435/57626390-1175fc80-7596-11e9-8a06-b0d1fe44e5a7.png)
and the template looks like this:
![image](https://user-images.githubusercontent.com/38004435/57626422-23f03600-7596-11e9-9b23-fa3c1e77e1ab.png)


 As you can see the new template has the wrong SVG icon, and now we need to create a new one for the new template. We decided to give the creation of the SVG-icon it's own issue, now issue #6978 . We also need some styling for this new template, this is dealt with in issue #6982 .
