### ISSUE TITLE
Markdown should support multi-levelled lists

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1780]
Matching for 1,2 or 3 spaces before asterisk or minus should result in multilevelled lists
Space Asterisk Space Text should generate ul li text /li /ul
Space Space Asterisk Space Text should ul li ul li text /li /ul /li /ul

The hairy issue has to do with how to handle the unwanted multiple ul-tags that are generated, and if there is a way to remove those that does not result in convoluted code.

**Comment by h14marma** [comment]
Is this issue related to these issues? #1845 #1868
In that case, this issue has already been solved. @HGustavs

**Comment by h14marma** [comment]
Closing issue
