### ISSUE TITLE
Markdown tables would be super nice

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1781]
Using pipe characters. 

Colons can be used to align columns.

| Tables | Are | Cool |
| --- | :-: | --: |
| col 3 is | right-aligned | $1600 |
| col 2 is | centered | $12 |
| zebra stripes | are neat | $1 |

The outer pipes (|) are optional, and you don't need to make the raw Markdown line up prettily. You can also use inline Markdown.

| Markdown | Less | Pretty |
| --- | --- | --- |
| _Still_ | `renders` | **nicely** |
| 1 | 2 | 3 |

**Comment by a15ramha** [comment]
This issue has been solved.
