### ISSUE TITLE
showdoc without parameters gives an error

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1782]
If I browse /Lenasys/DuggaSys/Showdoc.php and provide no parameter I get an error message:

Notice: Undefined variable: file_extension in /Library/WebServer/Documents/LenaSYS_Codeview_v15/DuggaSys/Showdoc.php on line 234

**Comment by a14maxry** [comment]
think it works. Now if you enter showdoc.php without parameters the site echo " You have reached a non-navigable link!"
