### ISSUE TITLE
Navigating to showdoc produces unk in return link

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1783]
so...
I make a link to a document without supplying a course version.... i.e. showdoc?courseid=3&filename=?foo.md

when I click the return button I am returned to the right course but the version is "unk" which is true as no verison was given to showdoc.... however....  adding a version locks the file link to a certain version, which is not the intended behavior either.

A better way is to use the newest version "live" version if no version is provided. This way we can get version-unlocked links to showdoc and still supporting the back button in a user-transparent manner.

The only time when this back-fires is if a teacher is editing a future version and clicks the back button, he or she would then return to a version that is not the same as the originating page.

**Comment by a17andby** [comment]
Fixed and merged. Closing.
