### ISSUE TITLE
Moving from hidden to public on link with underscore _ will break the link

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1784]
Moving from hidden to public on link with underscore _ will break the link. It throws an "illegal characters removed" and will break the link.

**Comment by a97marbr** [comment]
Correction. When editing a link it will not have the current link preselected in the dialogue box. Fixing this will probably fix this bug.

**Comment by a18kaswi** [comment]
The negative effects on the project of having an untouched issue from 2015 in the backlog outweights the positive effects at this point.
