### ISSUE TITLE
There should be a "test dugga" button associated with each dugga version in the test editor

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1786]

**Comment by a15magkn** [comment]
@a97marbr @HGustavs 
This needs some clarification. Does "test dugga"-button mean a preview button where the teacher can view  a dugga from the students view? 
Is this relevant since the implementation of the SortabaleTables in Dugga Editor?

**Comment by a18kaswi** [comment]
"a97marbr commented on 11 Aug 2015
No description provided."

CLOSING
