### ISSUE TITLE
Consider changing the layout for file management

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1792]
As is now a course with a lot of links or course files will "push" down the buttons for submitting course local files. Should we consider a "pane view", i.e., a horizontal line with [LINK][GLOBAL][COURSE][LOCAL]?

**Comment by c16jonha** [comment]
@HGustavs Is this still an issue?

**Comment by c16linst** [comment]
We are closing this issue since the described problems are no longer actual.
