### ISSUE TITLE
Perhaps use different sizes for "stop sign"-identifiers

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1793]
I think a Moment-stop sign should be bigger than a mere dugga's.

**Comment by a15freed** [comment]
is this size ok for the stop sign so we can close this issue? @a97marbr 

![image](https://cloud.githubusercontent.com/assets/26706932/25171487/4586277a-24ee-11e7-8cc5-0ca3df3f1595.png)
