### ISSUE TITLE
Default to a dummy-link instead of the first link in list 

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1796]

**Comment by a15eriho** [comment]
Elaborate. Which list in which view/dialog.

**Comment by a15eriho** [comment]
@a97marbr 
Is this still an issue? Screenshot/Mockup/Description to identify the problem.

**Comment by a18kaswi** [comment]
The negative effects on the project of having an untouched issue from 2015 in the backlog outweights the positive effects at this point.

**Comment by a97marbr** [comment]
The issue writing skills need improvement from my end it seems :)

When setting a sectionEd line to type Link we should have a default page that is a global page to which the sectionEd line would point to.

The template page should have something like
```
Placeholder. Content will be added soon!
```
Current behaviour is that the first item in our list of possible links/files will be chosen. I don't like this.
