### ISSUE TITLE
Remarking a dugga with fail once more is not possible

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1798]

**Comment by a13arnhe** [comment]
If a dugga is resubmitted the colour code of it in the result page will fail. The dugga can be graded again and again with a fail (U) until it is finally given a pass (>= G). Today a person can fail 3 times and the dugga is locked ( Issue #1910 ), then a teacher of the course can unlock the dugga again for the user, allowing the user to take it 3 times again until a pass is reached.
