### ISSUE TITLE
HTML-code slips through in markdown

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1799]
For example the <input> tag is not caught it seems.

**Comment by a14jimso** [comment]
@a97marbr The details are a bit unclear. Which tags are not caught, all of them, or a specific tag?

**Comment by b14rebst** [comment]
@HGustavs

**Comment by HGustavs** [comment]
I think this may have been solved already by someone.

I tested it just now and I cannot repeat the bug currently.

Confirm by trying to put html code in the markdown file, written verbatim in the .md file or as quoted code. Neither one of those options seem to generate html.

e.g. <input type="text"> should make that text, not a text input.

**Comment by b14rebst** [comment]
I tested this and as you say neither of these options generate html. Closing issue.
