### ISSUE TITLE
Hover highlighting of Important Line Ranges.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1802]
If the mouse hovers e.g. (27-41) line 27-41 should be highlighted in the code viewer e.g. by changing color.

**Comment by HGustavs** [comment]
The suggested solution is to insert the row number and file name as the ID of the div element.

the div has either class "normaltext" or "impo"

if we also add an ID we can highlight the important rows group using javascript.

**Comment by HGustavs** [comment]
I think this has been implemented a97marbr uses this in the android course or the web design course... either way I think it has been solved already.

**Comment by a97marbr** [comment]
Yes this is implemented. It would be nice if someone could do a test of the functionality though. Build a test case for this in the over all test data set.

It should work by using a markdown file that uses the **===filename,start row,end row, text to show===** to point out a range of important rows in the referenced source file when hovered over the text in the markdown file. For example:

===javascript_source.js,4,10,A cool source code part!===

**Comment by a15elibr** [comment]
Since the issue has been resolved, I am closing this issue.
