### ISSUE TITLE
Codeviewer preview should select correct file server side

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1803]
Right now a messy javascript solution is used. Rewrite and use PHP to select correct file for preview.

**Comment by HGustavs** [comment]
No I do not understand this bug description.

**Comment by A15cecal** [comment]
I don't understand this issue. Need some further explaining on this

**Comment by HGustavs** [comment]
Dont really understand this either, I will ask Marcus.

**Comment by A15cecal** [comment]
@HGustavs Did you get an answer to this?

**Comment by a15freku** [comment]
This issue is not a problem any more
