### ISSUE TITLE
We need a set number of lifes (submits) of duggas

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1804]
- We want to limit the number of re-submits
- For example, 2 / day, 2, 2 until new lives have been granted
#Gamification

**Comment by a97marbr** [comment]
A teacher should be able to change from unlimited re-submits to a fixed number of re-submits as stated

**Comment by a14maxry** [comment]
Wonder if this feature is necessary when #1910 has been implemented already
