### ISSUE TITLE
We want student submissions as part of the 'coreses' structure

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1809]
A student's submission should be stored in a folder with the following format:
lastname_firstname_login

**Comment by a15magkn** [comment]
@a97marbr  @HGustavs 
This is very unclear. Does this relate to and old version of LenaSYS? Does this relate to the Course Editor? If so this should not be tagged to grupp 3 (2018).

**Comment by a18kaswi** [comment]
Issue from 2015 that's been discussed in 2018, not very high prio, I close.
