### ISSUE TITLE
coloring of html in code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1817]
Right now HTML or XML is colored black in the code viewer. A much better way would to give it a separate color e.g. green.... so it is easier to identify html code mixed with javascript or php.

**Comment by a15freed** [comment]
![image](https://cloud.githubusercontent.com/assets/26706932/24707816/4adb1df4-1a15-11e7-9ed1-dc0defef0fba.png)

Is it something like on the picture you are thinking about?
and maybe other color for <?php

**Comment by b15linek** [comment]
<img width="327" alt="screen shot 2017-04-06 at 11 09 18" src="https://cloud.githubusercontent.com/assets/26706647/24746478/8d24abf4-1ab9-11e7-9714-30fd97cdb996.png">

Is this something like it for HTML or should ALL text be green? Now only the tags are changed. @HGustavs
