### ISSUE TITLE
Setting Up New Code Example

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1819]
Right now, too many clicks (and other interactions) are required for setting up a new code example.
- Presumably, one example is similar to the next, when we click new example, a copy of the layout of the previous exmple should be created. Right now it is empty. This requires lots of clicks to set up a code example, and most code examples require the same sequence of actions.
- Section name and Example title need to be copied from the section editor so that we enter those names in one single place. However if we want to change that default we can if we want to.
- The kinds of content can also be copied if the previous example uses 1, 2 3 split then the next one will probably use that also. If it uses code for 1, preview for 2 and description for 3 the next exmple will probably also use this layout.

**Comment by HGustavs** [comment]
By doing this we can reduce the work needed for creating a new code example by 90%, and it can be achieved without changing the underlying interface.

**Comment by a17joaap** [comment]
Doesn't this clash with https://github.com/HGustavs/LenaSYS/pull/7055?
