### ISSUE TITLE
List filters in code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1822]
The lists could be filtered more agressively.

I feel that removing .md from the list of code files would be acceptable. If one wants to show markdown in the code viewer one could easily change the extension to .md in those cases.

**Comment by d15johro** [comment]
Is this issue related to #1896 and if so, did this #4055 pull-request solve it?

**Comment by a17poner** [comment]
I think this might have gotten solved in a commit by @b16johso will see once it gets merged .
