### ISSUE TITLE
More icons in section editor

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1823]
The section editor would benefit from having icons for the functions such as files, tests access and so on moved into the top menu, like in the code viewer.

The reason for this is that when we have many files in a course the menu moves out of sight.

I suggest making icons like in the code viewer.

**Comment by a15freed** [comment]
Is this also related to #717

**Comment by d15eriso** [comment]
Is this still relevant? 
Is the icon suposed to be beside the text ON the button, or should the button replace the textbutton?
@HGustavs

**Comment by a15eriho** [comment]
The buttons is supposed to be moved to the top of the page, on the same row as the small house, and the login/logout-button.

**Comment by a15tobli** [comment]
Hello! Group 2 has added an extra button in this navigation, which leads to a page for creating student groups for duggor, issue #2934. The button is labeled "Groups". This is something that has to be taken in consideration when redesigning the menu, as this link will be added in the weekly merge.
![groups](https://cloud.githubusercontent.com/assets/26705097/24908600/df7477da-1ec0-11e7-99fe-507a854df034.PNG)

**Comment by d15eriso** [comment]
Created a new Icon in the top "navheader" next to the Home and Swimlane icon. The icons are visable all the time and are not course specific. The "sectioned.js" file handles the buttons for the course and "navheader.php" handles the icons on the top of the page. 
I dont know how to make the course buttons appear in the header on top of the page.

**Comment by a15andau** [comment]
Doing a pull request on changes made but would like feedback from @HGustavs if the changes are alright so let's leave the issue open for now.

Got rid of the tab-looking buttons and made them to look more like actual buttons. Changed the position of the version dropdown menu and re-named the "New Item" button to just a +-sign. This is how it looks now:
<img width="1263" alt="skarmavbild 2017-04-25 kl 15 20 18" src="https://cloud.githubusercontent.com/assets/26709847/25387375/df6efb06-29ca-11e7-8314-d1386a93b67d.png">

**Comment by a15andau** [comment]
After discussions with Henrik this issue is finished in it's current form. Some changes has been made, related to issue #1837 but this issue can be closed.
