### ISSUE TITLE
Code viewer css support

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1824]
It would be interesting to see if we could push the envelope a bit when it comes to css support in the code viewer. Much like we did for html support.

Imagine hovering over a css declaration ".someclass" if the corresponding divs e.g. <div class="someclass"> would highlight that would increase the readability of css declaration for novice html/css-ists.

**Comment by a14ponse** [comment]
So what you want is pretty color (important words) and the purple highlight when hovering css code in a course with an exampel? like we have now with JS, PHP, HTML, Plain Text, Java, SQL, SR ?

**Comment by a14ponse** [comment]
@HGustavs bump

**Comment by HGustavs** [comment]
Im thinking adding strings as important words.

If I add .someclass as an important word both someclass with quotes class="someclass"  as well as .someclass in css should be highlighted.

**Comment by HGustavs** [comment]
Mockup time! The class .tstclass is highlighted in all views when hovered.

![mockupcssclass](https://cloud.githubusercontent.com/assets/6978801/14668875/8c7f8ac6-06e6-11e6-83dd-5e47e0a84fb3.png)
