### ISSUE TITLE
Faux-Deletion of Dugga Variant

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1826]
Deletion of dugga/variant may not happen if one has been used in an answer.

The best way to handle this is to _NEVER_ delete anything. But what if a dugga-variant is erroneous and it _HAS_ to be deleted.

I suggest (is there a better approach?) a "disabled" button to keep a variant (and therefore keep any links to previous answers) but disallow it from being used in future dugga-s.

**Comment by a97marbr** [comment]
I like this approach

**Comment by a14maxry** [comment]
https://github.com/HGustavs/LenaSYS/pull/2166
