### ISSUE TITLE
Informative title, e.g., filename, instead of showdoc.php

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1827]
I would like the page title to reflect which file that has been opened instead of saying "showdoc.php".

**Comment by a15andau** [comment]
When opening a file now the page title says Document viewer. I added the name of the file that is being viewed (see picture). Is this what you were looking for @a97marbr ?

<img width="701" alt="skarmavbild 2017-04-11 kl 12 46 18" src="https://cloud.githubusercontent.com/assets/26709847/24905716/240f2d06-1eb5-11e7-9dbf-9bac32d0a274.png">
