### ISSUE TITLE
Button to retrieve section name and example name

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1829]
I think that one simple way to solve the bugs that do with section and example name for the code examples would be a button to automatically copying current section and current example name from the section table.

The other previous way that was suggested in another issue is to make this process completely automatic. 

Perhaps a one-button solution could work as well?

**Comment by d15eriso** [comment]
Är det här fortfarande relevant 2017? Vad menar du med "code examples", är det här i code viewer eller vart är det du menar? @HGustavs

**Comment by a16konka** [comment]
No longer relevant in 2018, therefore it should be closed.
