### ISSUE TITLE
File updated log

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1832]
We have made issues for creating logs for page views and file downloads etc

I would also like to have a log of all file uploads to be able to graph the update rate of a file.

**Comment by a15matab** [comment]
File uploads are already logged?

https://github.com/HGustavs/LenaSYS/blob/master/DuggaSys/filereceive.php#L221
https://github.com/HGustavs/LenaSYS/blob/master/Shared/basic.php#L188

**Comment by a15elibr** [comment]
As this has already been implemented, I am closing this issue.
