### ISSUE TITLE
Tabs need to be converted to spaces in code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1834]
One major problem with the code viewer is the size of the tabs. They are HUGE.

I am thinking along the lines of replacing all tabs with 2 or 4 spaces.

I think we implemented this feature a long time ago but it does not seem to work... perhaps that code was removed for some reason?

**Comment by b14davbo** [comment]
I think that one tab should represent 4 spaces.

**Comment by a97marbr** [comment]
What about users on space-limited platforms? Mobile and tablets ... could we use 2 spaces for those at least?

**Comment by HGustavs** [comment]
I vote for two unbreakable spaces and a fixed width font.

The preview windows are small for big tabs.

I think there is an issue for choosing fonts/sizes in the code viewer / code previews.

A solution like in github is probably the most flexible, a setting for selecting 1-6 spaces for each tab. A code display settings dialog for font - coloring and tab sizes.

**Comment by a97marbr** [comment]
We use Hack (https://github.com/chrissimpkins/Hack), which is monospaced, i.e., fixed width, for code. So that one should already be covered.

**Comment by HGustavs** [comment]
#1936 is a near-duplicate of this.

**Comment by HGustavs** [comment]
There are other free and open code fonts that can be used, if we allow users to change size, we might just as well have a choice of fonts and tab sizes also. But only if someone makes such a dialog.

First priority is to make the tabs two spaces and we may have a second separate issue for code viewer configuration.

**Comment by b14antfr** [comment]
Changed down to 2 spaces now.

**Comment by a17johpe** [comment]
@HGustavs is this still an issue or should it be closed?

**Comment by a17johpe** [comment]
Cannot test if this is still an issue until https://github.com/HGustavs/LenaSYS/issues/5988 is fixed

**Comment by HGustavs** [comment]
I think it is fixed?
