### ISSUE TITLE
File upload functionality

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1835]
The file uploading view needs some additional features:
- Size of file and upload date
- Link to Preview of file by clicking on the name of the file

**Comment by g13johbj** [comment]
Is the preview function supposed to be on the popout window when you're uploading the file or on the list of already uploaded files?

**Comment by a15herny** [comment]
When receving the files, when does the file uploaded get written to the server? And does this concerne the files: fileed.js, fileed.php and filereceive.php?

**Comment by a15freku** [comment]
The problem is solved.
