### ISSUE TITLE
Mailto email when lenasys course has been changed.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1840]
semi-automatically e-mailing the students through an mailto email link using the normal email client but with automatically generated message would be an awesome addition.

**Comment by a97marbr** [comment]
Preferably with a direct link to the changed material and course.

The course "link to course" has updated the following material:
* "Link to material 1"
* "Link to material 2"

**Comment by HGustavs** [comment]
It would be nice to support mailto for organizations that do not allow sending email and standard email service for organizations that do. Same message for both only contents change.

**Comment by e14johho** [comment]
@a15timbe, I talked with Henrik about this issue and this can be closed.
