### ISSUE TITLE
I would like to be able to store number of students present at a lecture  

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1842]
There would be nice to have a the ability to store the number of students that went to a lecture. This would be a way to see the actual number of students taking a course.

**Comment by a13arnhe** [comment]
Is this something that you are still interested in? if so, would you mind to clarify a bit more how you want this. Should you be able to add a lecture associated to moments, tests, code example, and so on? or would you prefer a whole new type 'lecture' to be able to be inserted into the course and moments where you could click on them and get number of students present, when and where it was, notes? and other useful items. (image)

![screen shot 2016-04-12 at 14 02 20](https://cloud.githubusercontent.com/assets/18159848/14459271/338d0180-00b7-11e6-9f6e-f9ca66aa0677.png)

**Comment by a14phili** [comment]
Is this something that you are still interested in? @HGustavs

**Comment by b16karhe** [comment]
Closing the problem since it has to do with the "old" duggaed table which have been replaced with the "sortableTable".
