### ISSUE TITLE
Document viewer / Code viewer title.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1843]
Currently when one is viewing documents / code in tabs, the name of the document is not visible.
Adding the name of code example / document to title would be a worthwhile effort.

**Comment by a13henlo** [comment]
This issue seems to be related to which browser you use, if you're using Firefox you'll get the result you want but it does not appear to be supported in Chrome/Explorer (not sure about other browsers)

**Comment by HGustavs** [comment]
Im thinking this comes from the title element - is the title element static in some views?

The section editor seems to not do this correctly, but the code viewer seems to work at least in firefox.

**Comment by a13henlo** [comment]
I believe we're thinking about two different matters here, could you take a screencap of the page you're on where the title isn't working?

**Comment by a13henlo** [comment]
@HGustavs Unable to move forward with this issue without a sceencap

**Comment by b14davbo** [comment]
If you press the back button from a file (or box) in a LenaSYS course, the URL doesn't show you the attribute "coursename" which leads to an empty title in the head tag.

**Comment by a13henlo** [comment]
I will look into it

**Comment by b14davbo** [comment]
Merged. Good job.
