### ISSUE TITLE
Some generated passwords are not working

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1849]
There seems to be a discrepancy between password generated and passwords that the system allows.

**Comment by a14maxry** [comment]
do you mean that the generated hash sometimes is not accepted in the database?

**Comment by c14caran** [comment]
Is this issue still relevant?
The code in dugga.js is currently:
```javascript
function randomstring()
{
//		str="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890![]#/()=+-_:;.,*";
		str="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890";

		var valu="";
		for(i=0;i<9;i++){
				valu+=str.substr(Math.round(Math.random()*78),1);
		}

		return valu;
}
```
While this is not a very good implementation ( the 78 should be replaced with the new str length, currently it produces shorter than 9 length passwords ) it should never give a password that is invalid.

**Comment by c14caran** [comment]
@HGustavs Is this issue still relevant?

**Comment by a16seplu** [comment]
Is this issue still relevant or should i close it?

**Comment by a16chrsa** [comment]
This issue has been solved. Based this on #3469 and #3470 where it has been corrected and tested to work. As intended, generated passwords are not less than 9 characters long.
