### ISSUE TITLE
When adding a new code example the "before" and "after" buttons should lead to examples above and below

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1851]
When adding a new code example the "before" and "after" buttons should by default lead to examples above and below. Or to itself if the former cannot be done.

**Comment by a14didda** [comment]
This seems to be working already. I did a check with it and it does work without any problems provided that you edit the example after creating it to determine the order of which examples should be and where they should link to. If this is configured correctly (just choosing which example it should link to) it will work regardless, even if a bit tedious to edit many examples for an entire course. Is this what you had in mind?

**Comment by a18jakme** [comment]
@a18lukto 
This issue might be more into section.php rather than codeviewer.php? we have discussed this and we think the issue is that the new added code example doesn't get added correctly into the database, therefore we cant use the "before" and "after" buttons in codeviewer for the new code example. whats your thought on this?

**Comment by a18jakme** [comment]
@a18eliek

**Comment by a18lukto** [comment]
@a18jakme @a18eliek 
We have discussed this in our group and agree with you. We can take this issue if you want us to

**Comment by a18jakme** [comment]
@a18lukto You can if u have time, I sign your group.

**Comment by a97marbr** [comment]
So the behaviour is a bit more complex than I originally anticipated.

1. Code example 1 (not hidden/req login)
2. Code example 2 (not hidden/req login)
3. Code example 3 (not hidden/req login)

In the above scenario 
Code example 1 points to Code example 2, 
Code example 2 points to Code example 1 and Code example 3,
Code example 3 points to Code example 2

1. Code example 1 (not hidden/req login)
2. Code example 2 (hidden)
3. Code example 3 (not hidden/req login)

In the above scenario 
Code example 1 points to Code example 3, 
Code example 2 points to no code example
Code example 3 points to Code example 1

1. Code example 1 (not hidden/req login)
2. Code example 2 (req login)
3. Code example 3 (not hidden/req login)

In the above scenario 
IF logged in and with permission to view code example 2
Code example 1 points to Code example 2, 
Code example 2 points to Code example 1 and Code example 3,
Code example 3 points to Code example 2
ELSE
Code example 1 points to Code example 3, 
Code example 2 points to no code example
Code example 3 points to Code example 1

**Comment by a97marbr** [comment]
If I add a new Code example (or move an existing Code example ... this should be reflected in the next/previous buttons

```
1.   Code example 1 (not hidden/not req login)
1.b Code example 1b (not hidden/not req login)
2.   Code example 2 (not hidden/not req login)
3.   Code example 3 (not hidden/not req login)
```
Code example 1 points to Code example 1b,
Code example 1b points to Code example 1 and Code example 2,
Code example 1b points to Code example 1 and Code example 2,
Code example 3 points to Code example 2

**Comment by a18jenro** [comment]
@HGustavs or @a97marbr 
When investigating this issue I found peculiar behaviour which prevented me from even starting on the issue. Here is what I found.

When adding a new code example the database is updated with this (the codeexample table):
![untitled](https://user-images.githubusercontent.com/62876507/80582771-952b3200-8a0f-11ea-9161-093a35348e0c.PNG)

But afterwards, when editing the name in lenasys, the data in the database is not updated. Similarly, when removing the data in the database, the new code is not removed from lenasys.
This seems to be to be a huge problem and I can't really figure out what is happening.

How can something that is not in the database be shown in lenasys?

**Comment by a18jenro** [comment]
So apparently the new code example is saved also in a table called listentries.
But why does seem completely decoupled from the corresponding entry in the codeexample table?

**Comment by a97marbr** [comment]
You could have the same code example occur multiple times in your course (the listentries).

I'm guessing that a start for this issue would be to see if you can get the order of the listentries when in a code example. If the code example knows its own position in the listentries you could check for closest visible code example above and below?

**Comment by a18jenro** [comment]
Perhaps it would be smart to wait with this issue until this issue: https://github.com/HGustavs/LenaSYS/issues/8973 is solved.

**Comment by a20patpe** [comment]
This issue is caused by a missmatch between the name of the example when you pick the example: 
![image](https://user-images.githubusercontent.com/102600690/161913251-75793074-d414-4e8e-902d-f48d4c8ba37e.png)
And the name of the example once inside of it: 
![image](https://user-images.githubusercontent.com/102600690/161913428-132d3fd1-46aa-45e4-8017-e7e3c8ad7854.png)
Changing one of the names to match the other fixes the issue entirely:
![image](https://user-images.githubusercontent.com/102600690/161913728-c4e761d3-16bb-47d8-b542-213a52325976.png)
