### ISSUE TITLE
There is no CSS for linked HTML pages

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1854]
When linking to HTML files there is no styling at all for HTML pages displayed by showDoc.php.

**Comment by b14kriwe** [comment]
Could this be explained further? This seems to be used when a dugga is opened. But the Dugga seems to be styled so is this issue still valid, or am I looking in the wrong place?

**Comment by a97marbr** [comment]
I think that this issue has been solved, but not reported as such.
