### ISSUE TITLE
The stoplight icons showing marked/passed/waiting/failed duggas could be done in CSS

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1855]
The stoplight icons showing marked/passed/waiting/failed duggas could be done in CSS and be made a little bit bigger.

**Comment by a97marbr** [comment]
A first test is in the code now. I'm not completely happy about the end result.

**Comment by a97marbr** [comment]
Actually, this might lead to poor performance. It might be better to use png-files for this reason.

**Comment by d11karjo** [comment]
Would the following PNG-files be acceptable?
![nolight](https://cloud.githubusercontent.com/assets/18137886/14605301/4d91a16a-0578-11e6-8b6f-ccc6451693c7.png)
![redlight](https://cloud.githubusercontent.com/assets/18137886/14605309/571c960e-0578-11e6-98fd-e47e939ff960.png)
![yellowlight](https://cloud.githubusercontent.com/assets/18137886/14605316/5bbf5d18-0578-11e6-8f63-6c57cbd8244a.png)
![greenlight](https://cloud.githubusercontent.com/assets/18137886/14605322/60b4ab52-0578-11e6-94f9-ab55924737d6.png)
