### ISSUE TITLE
Warning on dugga content missing.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1857]
One common problem is when for some reason a dugga receives an empty string "" as its parameter.
In this case we get a javascript crash since json-parsing of an empty string results in an invalid state.

I suggest showing an alert for when the dugga parameter is missing.

**Comment by a14maxry** [comment]
Have recently added default parameters for duggas with empty parameters, so then it should not be possible to get an empty string anymore.
