### ISSUE TITLE
When editing a section that is a link - the current link is not selected

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1859]
When editing a section that is a link - the current link is not selected, instead the first link in the drop-down list is selected. This is most annoying and should be fixed.

**Comment by a97marbr** [comment]
Test to confirm fix. https://github.com/HGustavs/LenaSYS/commit/ee75f4b1c22f97e8131d75f028d38bd82b344215

**Comment by b16linra** [comment]
The fix has been tested and appears to work. Without the fix it does not work. We have edited a link-section with different users, and it worked for the ones we tested.

People who worked on this issue: b16linra, a14oliri.
