### ISSUE TITLE
Pasting text into html/css-dugga will not trigger preview window update

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1861]
Pasting text into html/css-dugga will not trigger preview window update. Should be the same as when typing in text.

**Comment by HGustavs** [comment]
Are we saying ctrl+v or right mouse menu paste?

**Comment by a97marbr** [comment]
right mouse menu past is the culprit ...

**Comment by a14maxry** [comment]
solution in https://github.com/HGustavs/LenaSYS/pull/2143
