### ISSUE TITLE
Removing Version Drop-Down from students view

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1863]
It should not be easy for students to accidentally go to an older version of a course.

The drop down (top left corner) should be removed for students. Students can still go to an older version if they are given an older link or use an older bookmark. The front-page link should always go to the linked version (which most of the time is the most recent).

**Comment by a97marbr** [comment]
I think this is a high priority bug

**Comment by b14kriwe** [comment]
This is now solved. Non-teachers will not see any option to change course version.

The solution was to comment the whole area where the drop down list is created. If was a boolean if statement. If 'writeaccess' as true, you would be able to also create new courses and edit old ones. Other users would only be able to display the course and browse it's different versions through a drop down list. The code is NOT removed, it's only commented. In someone wants to use it at a later time. The comment is currently in "sectioned.js" in rows 461-480.

**Comment by a97marbr** [comment]
If the solution is deemed to work, the out commented code should be removed.

**Comment by b14kriwe** [comment]
The commented code is now removed. So the drop down menu is only view-able by "teachers".

**Comment by HGustavs** [comment]
Teachers should not be able to see it either.

**Comment by b14kriwe** [comment]
So nobody should be able to change the versions? (unless you have a "hard link" to it?)

**Comment by HGustavs** [comment]
Correct. 

This is so that you do not accidentally make edits to old version of a cours thinking that it is current or vice versa.

If you want to navigate to old course it is done through a hard link on courseed page. This is much less error prone.

**Comment by HGustavs** [comment]
The only time that button has been used is in error.

**Comment by b14kriwe** [comment]
The drop down list is now removed for everyone.
