### ISSUE TITLE
Cookies Pull-Down

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1864]
We need a "do you want to use cookies" roll-down before allowing anyone to log in.

It needs to come down only for logins (and only for the first one). Login should not work before cookies have been accepted.

**Comment by a14maxry** [comment]
is the cookie roll-down supposed to show for every new user on the machine, or just once for every user on the machine?

**Comment by HGustavs** [comment]
Over-showing it will not be a problem. It is better from a legal standpoint to show it once too often than not enough.

**Comment by a14nikau** [comment]
It seems to work except when i press cancel i can enter the page anyway.
I'm using Firefox.

**Comment by a14maxry** [comment]
https://github.com/HGustavs/LenaSYS/pull/2355/commits/a6bf849e62db6d95dea2b3a065f926d3dc119897 seems to have fixed the problem

**Comment by a14nikau** [comment]
If i press cancle i will still log in.

**Comment by a14maxry** [comment]
There's some additional problem i guess, will look into it

**Comment by a14maxry** [comment]
Seems to work on the computers/smartphones i have tried. would need to debug on a machine which it does not work to be able to grasp the issue
