### ISSUE TITLE
Collapsable sections

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1867]
Im thinking that the sections in the section editor should be collapsable using some kind of an accordion effect. (An arrow to the left of the section name much like the play link but pointing upwards)

It would be super if this information could be stored in local storage (preferred) or a cookie so that this view state is remembered when we return to the same view again.

**Comment by a97marbr** [comment]
This is also true for the file upload area. We want "collapasability" there as well.

**Comment by d11karjo** [comment]
The collapsability exists, but it is not saved when you reload the page.

**Comment by c14emian** [comment]
Unassigning as my planned solution requires changes in Ajax, a15mikla will implement a different solution.

**Comment by a15mikla** [comment]
I'm separating this issue into smaller issues.

**Comment by a15freed** [comment]
@a15jorpa will check on the file upload area

**Comment by a15mikla** [comment]
Functionality for collapsable sections in "sectioned" is added. 
File-upload was collapsable from the beginning.

**Comment by a15mikla** [comment]
Attempting to style the collapsability in file-upload to match the collapsability that exists with sections.
