### ISSUE TITLE
Logging of execution times and other things

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1874]
One key feature for the next iteration of lenasys is logging, to figure out performance bottlenecks and the reason for crashes. 
A generalized logging feature, for logging performance information and usage statistics.

* Each time any service is run it would be nice to have a log of the execution time. (e.g editorservice.php) 
* There are different ways to keep the logs.
http://stackoverflow.com/questions/183783/log-to-file-via-php-or-log-to-mysql-database-which-is-quicker
* Currently only logins/attempts are logged in the database, it would be nice to keep a log of every page read or every user click in some manner, to be able to analyze user behavior, or usability problems.
* One of the only advantages of Scio is that it is easy to see statistics, on for example how many people have downloaded a file or how many that have viewed a certain page. This is key for good analytics.

Perhaps sqlite is a good way to keep the logs, better than mysql or postgres?

**Comment by b14vikgu** [comment]
Closing this because the execution times are now implemented in https://github.com/HGustavs/LenaSYS/issues/1957.
The rest is covered in https://github.com/HGustavs/LenaSYS/issues/495.

**Comment by HGustavs** [comment]
Making a new issue for user-logging.
