### ISSUE TITLE
Better consistency check for duggas

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1875]
It should not be possible to change dugga on a course where there are submitted answers.
I.e., course "My course" has a dugga called "color test" which links to "dugga2". It should not be possible to change this linking if we have received student answers to this dugga.

I would argue that it should not be possible to change a dugga at all after it has been made visible.

**Comment by d11karjo** [comment]
If there is an answer on a dugga and the dugga is then hidden, should it be possible to change the dugga then or not?

**Comment by d11karjo** [comment]
Right now there is a minor fix implemented, where moments that are public cannot be edited. If they're hidden, though, they can be edited.
