### ISSUE TITLE
Font size setting

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1876]
It would be nice to be able to set the font size for the code view pane (decided for each pane by superuser)

Depending on course, verboseness of the languages differs greatly.

One could argue on a larger font size for PHP and a smaller one for Android in Java.

**Comment by HGustavs** [comment]
But not a "setting per language" since some other course using php/javscript/etc may have another preference.

**Comment by a97marbr** [comment]
I like this
