### ISSUE TITLE
Start and end tag for php

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1877]
Currently we have start and end tag matching for all html tags e.g. <html> and </html> but not for <?php and ?>

**Comment by a16tobfr** [comment]
I am not quite sure of what you are refering to. Can you please elaborate on the issue so that I am able to understand it better.

**Comment by HGustavs** [comment]
This has to do with the code viewer and matching of start and end tags.

Seems like I did not quite finish my thinking in 2016 ... but I think we can close this issue.

**Comment by a16tobfr** [comment]
Issue closed
