### ISSUE TITLE
Syntax highlighting of HTML

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1879]
It would be nice to have syntax highlighting of HTML Tags such as <body> , <div>, </body> ... etc

Right now the html (at least for PHP) renders as ordinary black text.

Is there a better way to highlight recognized html? (specifically within php)

**Comment by A15cecal** [comment]
@HGustavs Could you explain this issue further?

**Comment by HGustavs** [comment]
I think this issue has been solved for the main code viewer.

However, syntax highlighting is not enabled for code snippets e.g.  Three tilde (~) characters followed by code block flowed by another three tilde characters.

~~~
Code block <html>
~~~

as can be seen in the code in this block above, no syntax highlighting happens even in github.

...

I would mark this issue as solved and if we are out of work later in the project we can make a new issue for syntax highlighting of code blocks.

**Comment by A15cecal** [comment]
No need for this issue right now. Closing it.
