### ISSUE TITLE
Heading size in code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1880]
Currently the font sizing in the code veiwer documentation panes is odd.

The headings are a bit too large.

Perhaps there are other inconsistencies.

**Comment by b14antfr** [comment]
There's different sizes depending on which h(1,2,3..) you use, would you like them all slightly reduced or a specific one?

**Comment by b14antfr** [comment]
@HGustavs bump

**Comment by HGustavs** [comment]
Well currently the one hash size is quite big compared to the body text. A reduction so that the markdown version looks more like github... or considerably smaller than current size. 

# A
## B
### C

**Comment by a97marbr** [comment]
When working with font size there is a tradition to work with **the golden ration, phi**. Perhaps this would work nicely here as well?
https://en.wikipedia.org/wiki/Golden_ratio
There is a lot of talk on this on the web. See this article for instance
http://www.lauradhamilton.com/the-golden-ratio-and-typography

**Comment by HGustavs** [comment]
Im thinking small differences between the sizes, like in a report for a course or some other document, where the difference is Text 12pt  Headings same font but bold and 12pt 14pt and 16pt. 

On the web the A type header above is more than double the C type header.

**Comment by b14antfr** [comment]
![titletest](https://cloud.githubusercontent.com/assets/18139516/14522765/6312a124-0230-11e6-95cc-7b8515fb86db.png)
How does this feel? The golden ratio seem to have provided quite big sizes so we ended up going with @HGustavs suggestion
