### ISSUE TITLE
Marking duggas

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1882]
I would like a marking page that focus on marking duggas. The results page we have at the moment gives a good overview of how the students perform, but it is hard to mark duggas in a satisfactory order.

As a complement I would like a separate page that allows to sort unmarked duggas.
The following query would result in all moment 421-duggas in course 14 sorted by the earliest submitted first: 

```
select * from userAnswer where cid=14 and moment=421 and (grade < 2 or (grade is null and userAnswer is not null)) order by submitted;
```

To get all non-marked duggas for a course:

```
select * from userAnswer where cid = 14 and userAnswer is not null and (submitted > marked or (submitted is not null and marked is null)) order by submitted;
```

Double check that the queries work.

As a starting point I implement a page that is populated with the second query, i.e., all duggas for selected course.

**Comment by HGustavs** [comment]
I suggest we make this part of the normal marking page either organically within the current layout or in a separate tab in the same window.

I do not want marking to be placed in two separate views with potentially divergent code.

**Comment by HGustavs** [comment]
New windows only when it is a new non-conflicting function. 

Otherwise we break the one functionality, one window one code file philosophy

**Comment by a97marbr** [comment]
* see overview of dugga-results
* mark duggas

Isn't this two different functions? I could live with losing the marking ability from the result overview if this conflicts with the philosophy.

**Comment by a97marbr** [comment]
Clicking on a dugga in the overview page would open the mark dugga's page and the newly clicked dugga. Or would this violate the philosophy?

**Comment by HGustavs** [comment]
Same table same service same file.

If it worked by writing to another table, then perhaps. But I do not want two files that do marking, potentially in different ways. 

Especially if we talk about something as important as marking.

Within the same view (in some manner) using the same service.

**Comment by a97marbr** [comment]
I agree with the part "not having two files that do marking".

What I'm saying is that one service is viewing the date (read-only)
The other is marking (read-write)

Viewing the result is centered around a student
Marking the duggas could keep the identity of the one submitting the dugga hidden, which probably is a good thing.

So your saying: have two tabs instead of two php-files. Would it be OK to only respond with data for the selected tab?

**Comment by a15herny** [comment]
Can someone create a new issue for this with proper explanations to what should be done? This thread end in a question. @HGustavs

**Comment by a15elibr** [comment]
Closing this issue since I think it's actually solved, and if not, a better issue with clearer description should be made.
