### ISSUE TITLE
Feature whish: Analysis page

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1885]
I would like a line graph over dugga activity.
- Show number of duggas submitted during the day
- Show number of duggas marked during the day

We should have the default start/stop to be the start and stop of the current course's beginning and end date.

I can think of more graphs, but this is a good start I think.

**Comment by a97marbr** [comment]
Come to think of it ... I would like an Analysis page

**Comment by c14emian** [comment]
Would the Analysis page only include the line graph or are there additional requests for the page?

**Comment by a15andau** [comment]
It would be great with some feedback regarding what the analysis page should contain. When the Analysis button in section editor is clicked it doesn't really do anything, it only sends the user to an empty page  @a97marbr  @HGustavs

**Comment by a18filkr** [comment]
Split this into 2 issues, one for logging duggas submitted and marked, and one for showing these in analytic.

**Comment by a18filkr** [comment]
The references will solve the issues in this thread and the analysis page is already online, closing this issue now.
