### ISSUE TITLE
Loading animation for long loading times

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1887]
It would be nice to get some kind of feedback when a page is waiting for data.

**Comment by HGustavs** [comment]
We used to have a throbber. 

Perhaps re-introducing a throbber gif for the code viewer and showdoc / showdugga?

**Comment by b14marki** [comment]
The picture is available but it needs to be an animation.

**Comment by a17fellu** [comment]
Added the animation to codeviewer.php in branch: https://github.com/HGustavs/LenaSYS/tree/GruppC2019_1887fix

Will update the other pages as well and then make a pull request

**Comment by a17fellu** [comment]
This could be introduced on all of our pages. Seems a little inconsistent to only have it on a few. I feel like ether we only add it to the codeviewer only or the entire site?

**Comment by a17fellu** [comment]
Pull request: https://github.com/HGustavs/LenaSYS/pull/5829

**Comment by a17andby** [comment]
#5867
