### ISSUE TITLE
Code viewer shows select template button even if user is not an administrator

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1890]
![screenshot 2016-02-26 09 59 11](https://cloud.githubusercontent.com/assets/6978801/13347717/d3ee2012-dc6f-11e5-87a2-dd21ff054edf.png)

The select template button (third from the left) should not be shown if the user is not a super-user of some kind. The button is confusing for regular users as it has no effect unless you are an administrator. 

Furthermore the play button should not be shown if there is no data in the play button field (this as also been discussed in another issue)...

The only buttons that should be available in this screenshot is home, down, left, right buttons.

**Comment by d11karjo** [comment]
After closer examination, this issue is not part of DuggaSys. I would like to remove the label, but it won't let me.

**Comment by a14jimso** [comment]
This has been fixed now.
