### ISSUE TITLE
Filtering in code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1896]
There are some strange features of the code viewer dropdown dialogs.....
- It is possible to select external links for code examples (not possible, only local files permitted)
- Even files of unrecognized types can be selected. Pre-filtering to only code files would help.
- It is possible to select strange illogical things for the preview, limiting to some file types would in addition to this also reduce the size of the dropdown list, .html .htm .pdf .png .jpg .txt would probably be enough ?

**Comment by HGustavs** [comment]
Also if one selects a pdf it should automatically embed the pdf into the document using the embed tag.

**Comment by d15johro** [comment]
adding following fileextension to the valids arrays: ['js', 'md', 'php', 'html', 'css', 'htm', 'html', 'pdf', 'png', 'jpg', 'txt'].

**Comment by a15freku** [comment]
Solved
