### ISSUE TITLE
Should we allow submissions from students not in the access list?!

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1900]
Currently we only check if logged in. Not if part of the course.

**Comment by HGustavs** [comment]
Probably a good idea.

Is there a case for general submissions e.g. a feedback page or something like that?

**Comment by d11karjo** [comment]
I'm guessing this might be good if there is ever a submission-page that is not directly bound to a course. But as is, aren't all submission-pages bound to courses? As far as I can tell, the courses already check if you happen to have access to them before they let you see anything.

**Comment by a97marbr** [comment]
What happens if I use the submit link without looking at the actual submit page?

**Comment by d11karjo** [comment]
At the moment, if you enter the dugga without having access to the course (possible if you have a link) you are not allowed to actually partake in the dugga, and instead see an error message, no Save-button or anything. However, if you somehow can activate the function while logged in but without being part of the course and without accessing the actual button, it is possible to leave an answer.

**Comment by HGustavs** [comment]
Im thinking that feedback/help could use the forum functionality.

**Comment by d11karjo** [comment]
And you want this feedback to be available to non-users?

**Comment by HGustavs** [comment]
Assignment submissionso only to registered students, but we want un-registered students to be able to *view* assignments... but not to submit.

**Comment by d11karjo** [comment]
Okay, but at the moment un-registered students can't even access courses they are not part of. That'll have to be changed if we want to add these functions.

**Comment by HGustavs** [comment]
Yes they can, most courses are "open". In that anyone can access content, just submissions are "closed".

There is a setting to make a whole course closed, requiring login to view the course. But currently this feature is rarely used.

Generally we want to avoid logins, the fewer times you need to login the better. Viewing assignments unless explicitly closed can reduce the times that people need to be logged in.

**Comment by d11karjo** [comment]
Actually, we changed the code slightly in Issue #1898. I fixed it now so that if a course is set to public anyone can see it, but if it is set to login only those logged in can see it. But I've still yet to change the underlying problems with that issue, so I'll have to check back with you later on that.

**Comment by HGustavs** [comment]
Are we saying "see" or "view"?

We want people to see the course but not access (view) it.

If the course is not hidden it should be visible in the list, but when you click the course you get an error message.

**Comment by d11karjo** [comment]
Yes, and the problem (again, Issue #1898) is that if you are not logged in you can view any course you want. Meanwhile, if you're logged in you can see any course that is set to public or login, but you can't view any you do not have access to. In short, if you're logged in you follow the rules, if you're not you don't.
