### ISSUE TITLE
File upload into dugga template folder

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1901]
I have changed my standing on uploads into the template folder.

Uploads should be possible under the following conditions:
* Super-user
* Only files that do not previously exist
* Only .html .js .png

**Comment by a97marbr** [comment]
So uploading new duggas should be allowed ... nice :)

**Comment by a14maxry** [comment]
opened again to add the functionality to remove dugga templates too

**Comment by a14maxry** [comment]
https://github.com/HGustavs/LenaSYS/pull/2232
