### ISSUE TITLE
Broken style sheets in showdoc html

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1903]
showdoc breaks styles for html content.

I think this may be due to not closing the tags properly.

It seems like any html file breaks the menus, so it is probably not a local style issue.

![screenshot 2016-03-04 13 24 14](https://cloud.githubusercontent.com/assets/6978801/13527042/85e41eb0-e20c-11e5-8dbd-dc6ca09bf9e9.png)

**Comment by d15eriso** [comment]
Is this still relevant in 2017? @HGustavs

**Comment by A15cecal** [comment]
This is not relevant anymore, closing.
