### ISSUE TITLE
Tokenizer bugs?

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1906]
After some testing I have concluded that there may be some problems in the tokenizer.
- The tokenizer does not recognize Object.Method properly. If I add Method as an important word, it is not recognized. Probably this is due to the tokenizer not breaking on the . character for variables.
- Similar thing appears to happen for Type:Namespace and Type::Namespace if we add Nnamespace as an important word, it is not recognized.

**Comment by HGustavs** [comment]
Test and confirm.

**Comment by HGustavs** [comment]
Also modulo and mod if the important word is mod the first half of modulo should NOT be hightligrted.
Works correctly in code viewer but not in description text.

**Comment by a14emeax** [comment]
It does no longer highlight part of words, but the main issue needs to be fixed. Assigning to Group 2.

**Comment by a17fellu** [comment]
I am currently taking a look at this. But need to get a better understanding of how this could be fixed.

**Comment by HGustavs** [comment]
Im not sure how far this issue has progressed, I would imagine that it has been partially fixed by for example the recognision of html entities?
