### ISSUE TITLE
Styling Issues

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1907]
The code viewer description styles are not very pretty.

The # heading is too large in my opinion.

Cleaner styling of the # heading
- Perhaps a colored background could make the headings stand out more, a bit like the headings in the section editor
- Or perhaps a bottom border that makes a line or a dotted line at the bottom of the # headings
- Or a rounded border around the heading a bit like a button
- Or some other kind of distinctive styling 

The text for the descriptions would look _much_ better if justified.

...

Probably there are more styling problems.

**Comment by a15andau** [comment]
Is it the header "Description" you want to look different @HGustavs ? Or is it "Description", "JavaScript_Ex1.html" and "JavaScript_Ex1.js" that needs to be changed? Or is it anything else?

<img width="1188" alt="skarmavbild 2017-04-11 kl 14 32 32" src="https://cloud.githubusercontent.com/assets/26709847/24909398/04f3989e-1ec4-11e7-888b-d6efaa0ceb26.png">

**Comment by a15andau** [comment]
Issue is considered finished and done as it is.
