### ISSUE TITLE
Bug in Dugga Variant Editor

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1908]
In the dugga variant editor the option list (on the cog wheel window, not in the main window) reads on and hidden for autograde, not on and off as it does in the main window.

**Comment by d11karjo** [comment]
Where is the dugga variant editor located? We cannot seem to access it.

**Comment by d11karjo** [comment]
Issue solved, though it needs a sanity check to see if it doesn't interfere with anything else.

The following rows (119-123) in duggaed.js were edited.

Before:
	var str="";
	if(autograde==0) str+="<option selected='selected' value='0'>Off</option>"
	else str+="<option value='0'>Hidden</option>";
	if(autograde==1) str+="<option selected='selected' value='1'>On</option>"
	else str+="<option value='1'>Public</option>";
	$("#autograde").html(str);

After:
	var str="";
	if(autograde==0) str+="<option selected='selected' value='0'>Off</option>"
	else str+="<option value='0'>**Off**</option>";
	if(autograde==1) str+="<option selected='selected' value='1'>On</option>"
	else str+="<option value='1'>**On**</option>";
	$("#autograde").html(str);

**Comment by a97marbr** [comment]
When you quote code you could use the markdown feature and enclose the code with "three mustaches", i.e., ~~~, you can even add which language the code-snippet uses; ~~~ javascript
~~~ javascript
var obj = 5;
~~~

**Comment by a97marbr** [comment]
Nice! :+1:
