### ISSUE TITLE
Hightlights of words on touchscreen-devices

### ISSUE THREAD

**Issue by b11davgu** [HGustavs/LenaSYS#191]
The mouseover-event when hoovering important words that results in a highlight should on touchscreen devices be replaced with a press-and-hold function.

Javascript-library "hammer.js" has been mentioned by customer.

The same should apply for the tooltips.

**Comment by a13jorla** [comment]
Mobile funktions not priority att this moment.

**Comment by a17pongo** [comment]
@HGustavs I believe this issue can be closed until this is relevant?

**Comment by HGustavs** [comment]
Not important, close.

Mobile view is not important for this, since it is very dependent on screen space.
