### ISSUE TITLE
Feature request: A "view in separate tab" from preview in code viewer

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1914]
I would like to be able to get a preview to be displayed in a separate tab/window, i.e., add a link with target="_blank" somewhere in the preview window.

**Comment by HGustavs** [comment]
Is that not what the play button should do?

**Comment by HGustavs** [comment]
But slightly more powerful as it could link to something different entirely, but most of the time it will be a link to either the code or to the preview.

**Comment by HGustavs** [comment]
Or are you talking about something else?

**Comment by a97marbr** [comment]
I think the intention of the play button is what I'm after. Full screen in separate tab. 

I do however think that the play symbol is misleading. The code preview runs the code already ... there is no need to play it.

I would argue that we change the symbol to something along "full screen".

**Comment by HGustavs** [comment]
I say this works, a full screen button that shows only the play link (if one exists)

**Comment by a15herny** [comment]
What constitute the "preview in code viewer"? Because either it is broken or I don't seem to understand were this button is located.

**Comment by a15herny** [comment]
Talked to Alice regarding the _JSON_ file. This was done because I cannot debugg otherwise. The issue is not that hard in it self hopefully.

**Comment by a15freku** [comment]
Solved #4054
