### ISSUE TITLE
Dugga variant default

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1915]
I would like a set of default templates for dugga variants.

A set of buttons each producing a varying set of pre-made templates such as this:
~~~ Javascript
{"type":"md",
 "filelink":"Assignment8.md", 
  "submissions":[{"fieldname":"Inl1Document","type":"pdf"},{"fieldname":"Inl2Document","type":"zip"}]
}
~~~

**Comment by a97marbr** [comment]
Could we do this by adding a mandatory dugga-local function that sets default parameters? This way we guarantee that we get a complete set of parameters for any given dugga. It should only run if params are null, i.e., we have not set any parameters. Something like this:
~~~ javascript
function setDefaultParams (p) {
   if (p=== null){
      return '{"type":"md", "filelink":"Assignment8.md",   "submissions":[{"fieldname":"Inl1Document","type":"pdf"},{"fieldname":"Inl2Document","type":"zip"}]}';
   }

}
~~~

**Comment by a97marbr** [comment]
It would still help a lot to have an editor like form for more complex duggas, but with the above idea we get working duggas without adding any parameters.

**Comment by a14maxry** [comment]
could not find the original pull request, but https://github.com/HGustavs/LenaSYS/pull/2149 is a part of it (the function was made for this issue)
