### ISSUE TITLE
JQuery errors ... can we investigate?

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1916]
Are these only related to jQuery ... can we mitigate by updating jQurey-files?

Do we dare update?

![capture](https://cloud.githubusercontent.com/assets/4948661/13878146/a762b23c-ed0f-11e5-9c2a-445fedd786c4.PNG)

**Comment by a14emeax** [comment]
Is this an issue for Group 1 or Group 2? Neither of us is really sure.

**Comment by a15eriho** [comment]
Is this still an issue? Can you elaborate on how to produce the error?

**Comment by c14caran** [comment]
Any usage of Alpha( is limited to existing jquery libraries. If any errors still exists jquery-ui is probably the cause of these arrors.
![image](https://cloud.githubusercontent.com/assets/26733338/25654439/47ec1f20-2ff1-11e7-805f-e4df3a0ca3b6.png)

**Comment by a18kaswi** [comment]
No answer from customer since 2016, closing.
