### ISSUE TITLE
CSS errors - prefix missing?

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1917]
This from firefox 38.0.5

Are we missing any prefix-code?

![capture](https://cloud.githubusercontent.com/assets/4948661/13878215/22dcb8ae-ed10-11e5-88bd-505794507912.PNG)

**Comment by b14antfr** [comment]
Seems like there's more to this issue than just these two, will try to clean it up a tad.

**Comment by a14jonal** [comment]
fixed in merge  #2302
