### ISSUE TITLE
Adding users needs to update how to parse course participant list

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1918]
The format from the generated course participant lists has changed. We need to update the parser when adding new students.

New format:
[SSN],[Lastname],[Firstname][WHITESPACE][Anmkod][WHITESPACE][Type of registration][WHITESPACE][Study program],[Year of admittance][WHITESPACE][email address]

**Comment by a14nikau** [comment]
This issue is merged with #1969 
https://github.com/HGustavs/LenaSYS/issues/1969
