### ISSUE TITLE
sectionedservice has poor SQL for retreiving dates on dugga submissions

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1919]
Currently we need to correct the string into a format that Javascript Date can handle - this is not preferred.
~~~ javascript
   // mt holds the time received from the database
   var mts = mt.split(" ");
   marked = new Date(mts[0]+"T"+mts[1]);	
~~~
Do the string manipulation using SQL and Date format. Javascript accepts the following time string:
~~~ javascript
   var timeStr = "Wed Mar 25 2015 09:56:24 GMT+0100 (W. Europe Standard Time)";
   var d = new Date(timeStr); 
~~~
So the string timeStr Should be what we get from the database.

**Comment by a97marbr** [comment]
It turns out that time zone is not part of the stored values. This means that the following string should suffice:
~~~ javascript
var timeStr = "2015-03-25T12:00:00";
var d = new Date(timeStr); 
~~~

**Comment by a97marbr** [comment]
Submitted a suggestion for this https://github.com/HGustavs/LenaSYS/commit/8e96cf5b64ed1834a0b2d970aeb1f5a3355be16e

**Comment by a97marbr** [comment]
Handed in time is not working

**Comment by a13arnhe** [comment]
As far as I can see this solution holds up, the stoplights are working as they should. About the handed in time, in the userAnswer table in the database, that seems to be working as it should.
