### ISSUE TITLE
For dugga submissions we should do a brief sanity check

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1920]
Upload buttons should be disabled until we have inserted a proper item.

* for url we could look enable upload if http:// is present
* for pdf - we check that a pdf is selected
* etc

**Comment by a14maxry** [comment]
is there even duggas where you upload a document like a pdf?

**Comment by a97marbr** [comment]
Yes. https://github.com/HGustavs/LenaSYS/blob/master/DuggaSys/templates/generic_dugga_file_receive.html

**Comment by a14maxry** [comment]
added some sanity checking, like when you have the pdf- or zipsubmit you can only upload one file of that kind. if multiple files are to be added the multisubmit can be used instead. Also "for url we could look enable upload if http:// is present", "https://" was added too in addition to "http://"
