### ISSUE TITLE
Hide score keeper if dugga has disabled highscore

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1922]
![capture](https://cloud.githubusercontent.com/assets/4948661/13882303/369f6c32-ed25-11e5-8b40-036763ebd695.PNG)

The score board is still present even if no time or moves are counted. Should be hidden, i.e., display none

**Comment by a13arnhe** [comment]
Issue has been fixed in pull request #1944

**Comment by a97marbr** [comment]
There should be different persons committing code and reviewing code.

**Comment by a13arnhe** [comment]
I solved the problem, committed it, and submitted a pull request that I am waiting for review on. If that review fails this issue should be opened again by the person that reviewed the pull request #1944

**Comment by a97marbr** [comment]
The issue should be closed by the reviewer that allows the code into the shared code. In this way we know that an issue that is closed have been deemed resolved by an independent reviewer.

**Comment by a13arnhe** [comment]
Merged #1944

**Comment by a13arnhe** [comment]
@d11karjo please close this resolved issue
