### ISSUE TITLE
Collapsing along duggas and their border

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1923]
![capture](https://cloud.githubusercontent.com/assets/4948661/13882440/b092a6da-ed25-11e5-971a-1ba61a42573f.PNG)
Wouldn't it be nice to be able to collapse "Media Query - Dugga #1" in the above example? For example by clicking the stoplight?

**Comment by a13arnhe** [comment]
Moments can be collapsed, looked like the most practical thing, rather than header or sections (which can't told test btw.)
