### ISSUE TITLE
The stoplight and spacers should not be displayed for hidden elements unless we are logged in as teacher or superuser

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1924]
![capture](https://cloud.githubusercontent.com/assets/4948661/13882571/505c2e5c-ed26-11e5-92a8-0cee091b5172.PNG)
This needs to be fixed quickly!

**Comment by b14kriwe** [comment]
Everything appears to be working fine. I cannot see the hidden "tests" (that uses stoplights) when signed in as a normal user.
