### ISSUE TITLE
The folder that holds duggas have a lot of testing files which should not be there

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1925]
I suggest removing
* old unused / none-functional duggas
* files that should not be there (pdf, png, more?)

The way duggas now work we should only need to have two files per dugga
* dugga_name.html
* dugga_name.js

If we want particular files belonging to a dugga, e.g., different color files or xml examples they should be part of the course that uses the dugga, i.e., uploaded using the regular file upload feature, and referenced using the markdown linking =={id}==

For the record I also suggest moving to descriptive names, i.e., generic_file_submit.html is **a lot better** than dugga1.html

**Comment by a14gabon** [comment]
There are only 50% files left

**Comment by a97marbr** [comment]
I don't see a reference to the actual commit that deals with this?
