### ISSUE TITLE
SQL clean up / formatting / ordering

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1926]
During the migration towards an SQL code that works both for MySQL and other SQL engines such as Postgres I want the following to be considered:
* **One file** that holds all the major parts used in LenaSYS + a default super-user with default password
* **One file** that holds a complete test data set, i.e, a _test course_ with content and one user with write access and a few users with read access. 

**We also need to sync this with _test course_ uploaded content and submissions.**

This way we can choose to install LenaSYS with or without test data.

**Comment by a97marbr** [comment]
One could argue that supported code syntax could still be in separate SQL files. If so they should be formatted in a way that makes it easy and intuitive to add more languages.

**Comment by a14ponse** [comment]
@a97marbr The first point, i dont really understand if you just wants us to infiltrate together (nästla ihop) and relink everything. Or is it somthing that stops us from doing that that i miss?
on the second point you have, what is it that you want have more than whats in the file "testdata.sql" in the folder "shared/SQL" ?

**Comment by a14ponse** [comment]
@a97marbr  bump

**Comment by a97marbr** [comment]
I discussed this with @HGustavs and it may be the case that the division cannot be done due to historical reasons and too much entanglement between actual database structure and actual data (users, courses, duggas, dugga versions, etc). I would have preferred a way to have a completely empty database with only 1 users - "Toddler" as superuser, and the option to add a complete set of test data (1 course, 1 teacher, n students, a few select parts in the course, some submitted answers, etc. etc.) 

Being that this is not possible the argument should be to put all the SQL into one file: **init.db** and to make explicit documentation on how to add things such as a support for a new programming language syntax.

**Comment by a97marbr** [comment]
If you can show that we **can** divide the database as I have described I vote for this. But we must be sure that it holds.

**Comment by HGustavs** [comment]
To clarify my position:

I want the following:
* A tested and working script for clearing the database in case one breaks it
* A script for inserting test data that is taken from real courses with real information needs. If we want to test a dugga variant for a test student we can do this using that insert after clearing the database if we want to test if it works on a "fresh install".

I am not very invested in if this is done in 1-2 or 3 files. but that functionality is what we want.

and... that SQL code should be human-readable and properly commented.

At some point someone recreated the sql by exporting from a the database using a sql tool such as mysql workbench.... which made the code much less standardized and less readable than before.

**Comment by a97marbr** [comment]
> At some point someone recreated the sql by exporting from a the database using a sql tool such as mysql workbench.... which made the code much less standardized and less readable than before.

Yes, this is unfortunate ... getting back to standardized and readable code is good
