### ISSUE TITLE
Adding teachers to courses

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1927]
In the access area (and/or the result area) we should be able to add teachers from the set of users that have write access elsewhere.

**Comment by a14nikau** [comment]
contains a solution. the question is should the system for adding users be refurbished.

**Comment by a14nikau** [comment]
This issue is affected by https://github.com/HGustavs/LenaSYS/issues/1918
so it will be included in issue as a sub-issue https://github.com/HGustavs/LenaSYS/issues/1969
