### ISSUE TITLE
Feature: Moment should have options to show: credits, grade scale, and estimated start-stop time

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1928]
![capture](https://cloud.githubusercontent.com/assets/4948661/13904047/6f7401ca-ee93-11e5-9763-fc9e07dad69b.PNG)
- The credits and grade scale should be possible to have stored in the database
- estimated start and stop time is a help for the students - I could see that this could be an optional text field in the database.

By having these as separate items we can choose how to display them when the screen size is limited.

**Comment by a13arnhe** [comment]
You mean that a teacher could decide what the moment show? or that the user should be able to choose somewhere from a dropdown list possibly, of what he would like to see?

**Comment by a97marbr** [comment]
No, it should be based on available display space. A small view (cell phone) shouldn't be verbose but on a large screen we should display as much as possible.

As an alternative we could make the extra info (credits, grade system, and opt text) a lot smaller and on a new line below the name of the moment name.

The optional field should only be displayed if not empty (and we have screen real estate)

**Comment by a13arnhe** [comment]
Can you present to me how you visualize this for the moments? 

About the estimated start and stop time. I could fetch from the database the earliest start time of a dugga in the moment and set that as the start date and likewise get the last deadline of the moment objects and present that as the estimated stop time of the moment. Is that something in the direction you had in mind?

My idea for displaying a moment grade (amount of hp) is that every quiz could have its own grade and the sum of these would be displayed as the total hp in the moment

**Comment by a15magkn** [comment]
The grade scale part of this issue has been solved, and the remaining request have been broken down into two new issues #4809 and #4810 
This issue will therefore be closed.
