### ISSUE TITLE
Dugga variant editor bug - resize of individual fields possible but not the entire dialog

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1929]
Resize of individual fields possible but not the entire dialog. I want the reverse:

Resize of dialog should be possible but not individual text input fields.
![capture](https://cloud.githubusercontent.com/assets/4948661/13904501/5279af88-eea3-11e5-9f8e-1cd89efb89e0.PNG)

**Comment by a97marbr** [comment]
Or at least resize of individual fields the should not break the dialog.

**Comment by d11karjo** [comment]
Well, the text doesn't resize anymore... but right now, this is the result if you resize the Login-window to smaller than the default:

![problem](https://cloud.githubusercontent.com/assets/18137886/14809910/78c34e38-0b90-11e6-8c09-8ab311d83d89.png)
