### ISSUE TITLE
When previewing dugga3 and dugga4 they will interfere with one anothery

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1933]
If we use both dugga3 (line and curve dugga) and dugga4 (geometry dugga) the will display the previous previewed dugga as a flashing image.

I believe this due to poorly clearing of the canvas on facit exit.

**Comment by a14gabon** [comment]
In which course site does this happen?

**Comment by a97marbr** [comment]
If you add a dugga3 and a dugga4 to a test course and submit you will see the effect if you have things to mark on both these duggas.

Start by building a test case to replicate the problem.

**Comment by A15cecal** [comment]
I can't recreate this problem. Might need some more information on this.

**Comment by a15elibr** [comment]
Closing issue, cant recreate problem, if it still remains as an issue in the future, just create a new issue then.
