### ISSUE TITLE
Tabs are not handled properly.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1936]
I am not sure if this has been reported previously but...

tabs both in code boxes and in code viewer need to be converted to _two_ nbsp entities each.

The current tabs are far too large and it makes the code unsightly.

**Comment by HGustavs** [comment]
I would like to add that the code box issue has to do with markdown and that the code viewer issue is a tokenizer issue. 

Either way I want it to work mostly the same in either case.

**Comment by a15freku** [comment]
What tab and where is it? Any examples?

**Comment by a15freku** [comment]
There is no tabs
