### ISSUE TITLE
Markdown bugs

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1938]
If I make this markdown (n is number)
N. Text
N. Text
N. Text

the markdown works but if I do
N. Text
N. Text
Image
N. Text

The numbering will start over for the third N e.g. the first one reads 1 2  3 but the second 1 2 1

Is there a better way to do this?

Perhaps by using the number from N. in the markdown text that is generated rather than using ul and li or an alternative way to detect the ul and li styling for the numbered sections?

**Comment by b14antfr** [comment]
Is there a particular reason as to why you'd want to keep the OL tag at all, seeing as you're probably not writing massively long lists, this could be done by just removing the replace line of code in the markdown.js file that adds the OL part and then have you write 1. | 2. | 3. and so on manually instead.
Would this work?

**Comment by HGustavs** [comment]
I would say, not very highly prioritized, other markdown things may be more important, such as
* lists inside lists
   * like this
   * or this
* tables.

List within lists is really useful on almost any page, so I would prioritize that first.
As a second priority I would select some kind of table support.... can be very rudimentary if needed ; some is better than nothing. As a distant third, numbered lists.

| We        | Need           | Tables  |
| ------------- |:-------------:| -----:|
| What?      | Yes | 1 |
| Do      |  We      |   2 |
| We Really? | Do      |  44 |
