### ISSUE TITLE
Markdown horizontal line

### ISSUE THREAD

**Issue by b14davbo** [HGustavs/LenaSYS#1945]
Typing two stars (**) should generate a horizontal line ( < hr > )

**Comment by b14davbo** [comment]
I'm unsure what shortcut we should use for creating horizontal lines.

Two, and three stars ```(**) and (***)``` is currently generating bold text with the ```<strong>``` tag. Therefore I suggest using three hyphens ```(---)``` to generate a horizontal line.

Does this sound like a good idea?

**Comment by a97marbr** [comment]
From this commit I cannot deduce if the documentation has been updated to include three hyphens. 

There is also two ways of parsing markdown in LenaSYS - one through javascript (fixed here) and one through PHP (https://github.com/HGustavs/LenaSYS/blob/master/DuggaSys/showdoc.php), they should be kept in sync. So, something for the reviewers to consider.

**Comment by b14davbo** [comment]
@a97marbr It is documented in the [wiki](https://github.com/HGustavs/LenaSYS/wiki/LenaSYS-Markdown).

What is the reason to have two different functions, written in two different syntaxes that does the exact same thing?

**Comment by a97marbr** [comment]
JS is for CodeViewer and PHP is for everything else. Sometimes we don't want to show the actual MD.

**Comment by a14jimso** [comment]
Now added to php as well.
