### ISSUE TITLE
Move moments as whole not individual divs

### ISSUE THREAD

**Issue by a13arnhe** [HGustavs/LenaSYS#1948]
When moving divs with jQuery UI draggable, individual divs will only move. This is frustrating for the process of moving whole moments/sections. Creates extra problem when a collapsed moment is moved.

![screen shot 2016-04-01 at 16 55 40](https://cloud.githubusercontent.com/assets/18159848/14210735/97ba7196-f82a-11e5-83e6-9b327ce51020.png)

**Comment by HGustavs** [comment]
This may be complicated to solve. Nice to have but not necessary to solve.

There are several conflicting goals at once.

* The need to collapse moments that have been finished (from student standpoint they dont necessarily want to see all parts of moment 1 if it has been finished
* The need to have a way to move sections around for teachers (a very un-common operation in my experience)
* The more common operation to move an example or document from one moment or section to another.

As the second point (moving sections around) is rare, I would prioritize this issue towards the lower end. 

Student view things (such as collapsability) with more users goes before teacher view things such as moving collapsed sections around (which is rarer and may be more complicated to implement).

I say this is two separate issues. With different priorities.

**Comment by a13arnhe** [comment]
I agree, although it would be a nice feature. It could be tricky to implement, so at this moment lets treat this with low priority
