### ISSUE TITLE
I want a text only submission module to "generic-file-receive-dugga" 

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1950]
I want to add a text only submission to "generic-file-receive-dugga" https://github.com/HGustavs/LenaSYS/blob/master/DuggaSys/templates/generic_dugga_file_receive.html. This could be used when we want small code-snippets or very short assignment reports.
As a first step we could use a stripped down version of the html-and-css-dugga https://github.com/HGustavs/LenaSYS/blob/master/DuggaSys/templates/html_css_dugga.html where we take a way the need for a link.

**Comment by a97marbr** [comment]
The first step should be in a single issue. #liveasyoulearn

**Comment by a18kaswi** [comment]
Issue been passed around for four years. My call is that we need to clean up, if it hasnt been done in four years. Then it probably wont be done in the next two and only the negative externaliteies stemming from this will hold.
