### ISSUE TITLE
Stability logging

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1957]
As we are having (rare - at most weekly) crashes due to unknown reasons logging for stability reasons is needed quite fast.

This is along the lines of what we need

* Generate a random ID in client application before calling service and pass this with the call to the service along with client timestamp
* Pass random ID and timestamp to service service logs when form data is received
* Save ID, client time and server local timestamp to log
* Execute Service
* At end of service, just before or after json encode, get current server timestamp and save it to log
* When data is received in client send local client timestamp to server.

If we now read the log we have the following information

Client start timestamp
Server start timestamp
Server end timestamp
Client end timestamp

With this we can trace any request and see how much time it takes and if the last two steps are missing or very long, we know that a crash has ocurred or that performance is bad. We can even trace the exact data to the anomaly.

First three steps do not add additional requests to the network (only the id and timestamp, which are minute in comparison to rest of data)

A configuration switch to disable the fourth round-trip step would be needed as it adds a network request that was not present previously, in a constrained network, having the ability to disable this "un-necessary" network request would be a good thing.

**Comment by a97marbr** [comment]
Yes this would be great to have quickly :+1:

**Comment by b14vikgu** [comment]
Would this result in 3 logged events?
When:
* Server receives request from client
* Server is done processing request and responds
* Server receives confirmation that the client processed the response

**Comment by b14vikgu** [comment]
Implemented in branch https://github.com/HGustavs/LenaSYS/tree/grp3w14-logging
