### ISSUE TITLE
Logging database

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1958]
The logging needs to work with an external database. 

Currently the logging uses the same database as the rest of the information. This is sub-optimal, since it clogs up the main database with logs. And also, logging can use a lighter interface since we are only appending information, never deleting, and rarely selecting information from the log.

I suggest moving all of the logging operations to an sqlite database or even using a specialized logging layer with options for log storage such as mysql, postgres, sqlite or a text file depending on performance needs.

**Comment by b14vikgu** [comment]
The code for logging is located in in Shared/Basic.php right now.
A new file should be created in the Shared folder (logging.php) to contain the code for logging.
All places that use the old logging functionality should be changed to use the new log function, make a search for "makeLogEntry" to find them.

We have decided to use SQLite for the log database for now.

**Comment by a97marbr** [comment]
Make sure that you do not use any SQLite specific stuff, that would hinder any future flexibility.

**Comment by HGustavs** [comment]
If possible I prefer all shared functionality in basic.php no additional files. I can see why we would want a separate file but, finding the code is easier if all general project-wide code is in basic.php.

**Comment by b14vikgu** [comment]
This has now been implemented in https://github.com/HGustavs/LenaSYS/tree/grp3w14-logging
