### ISSUE TITLE
Log preview window

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1959]
Also, some kind of network issue window for the admnistrator with graphs that show this data would be nice....

Examples of thing we would like to see in this view:

* which service is the slowest?
* which service is used the most?
* are there any crashes or slowdowns and if so, in what service?
* are we being attacked by for instance password guessing applications?

Graphs using html5 canvas.

**Comment by b14vikgu** [comment]
Maybe this one could be combined with https://github.com/HGustavs/LenaSYS/issues/496?

**Comment by HGustavs** [comment]
Kind of. 
One is per user and one is without user info and just for performance.

**Comment by b14vikgu** [comment]
Can we use [this](http://www.chartjs.org/)?

**Comment by HGustavs** [comment]
No.

No external libraries except for jquery.

Also, a simple diagram is very little code.

**Comment by b14vikgu** [comment]
Issues have been created to make new service calls for the wanted information above:
#2126 
#2127 
#2128 

Now we also need to decide how to present this information in the view.

**Comment by b14vikgu** [comment]
This has now been implemented, except for  " or slowdowns" which is covered in another issue.
