### ISSUE TITLE
Markdown image zoom rollover

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1960]
I would like to have some kind of support for something like the images in this page in the markdown

http://wwwlab.iit.his.se/gush/ShaderprogrammeringOld/Assignment3.html

When we rollover the image it is shown in its original size but normally it is only a thumbnail.

This way it is easier to follow the layout of the page, without it being cluttered with large images.

**Comment by a14jimso** [comment]
The issue is now fixed. Support for a really fancy rollover function in both showdoc.php and markdown.js. You'll love it. ;)
