### ISSUE TITLE
Get rid of external css file for hack and place in main css

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1961]
One thing that makes things hard to find is using different css files for different things.

We want things in one place, one css file, one declaration for each kind of thing to make things as easy as possible to find.

We are using an external css (hack-extended.min.css) file in the code viewer for the hack font... this needs to be moved to the main file

**Comment by HGustavs** [comment]
Am I mistaken or did another code font just get added using yet another separate css file?

The goal is to have one small readable css file and not a lot of external css files. I think we are making it worse by adding more and more fonts using external css-files.....

**Comment by a16joare** [comment]
When inspecting the page it uses 5 diffrent .css files. Which files should be removed and where should we put the code? styles.css? 
How should this be done exactly? Should we go through all the code in example: codeviewer.css and move it to styles? Should we just check for name conflicts or is it something more?

**Comment by a16joare** [comment]
This issue is still active from 2019. 
We are not sure if we should add all css into style.css. Wouldn't it be better to add all code viewer related css to codeviewer.css?  As it is now, the css for code viewer is kind of all over the place..

**Comment by a16vikva** [comment]
We assume that this is already fixed since the "hack-extended.min.css" doesn't exist?
