### ISSUE TITLE
Section editor deadlines should not show time if 00:00

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1966]
Right now it is confusing in the section editor, when we are showing deadlines.

If we write 2015-06-03 the deadline printing code shows 2015-06-03 00:00:00

If the last part of the string reads 00:00:00 it is unclear as it could mean 23:59 or 00:01 i.e. you either have the day to complete the task or not...

My suggestion is to remove the last 8 characters if they are 00:00:00 if one wants 00:01 then one needs to write that or one day earlier and 23:59.

Also, no point in writing seconds, hours and minutes is fine enough.

**Comment by a14maxry** [comment]
solution in https://github.com/HGustavs/LenaSYS/pull/2252
