### ISSUE TITLE
Fix installation

### ISSUE THREAD

**Issue by b14vikgu** [HGustavs/LenaSYS#1967]
The installation script is broken right now. (entering a database other than imperious does not work since the SQL scripts have imperious hardcoded)

Implement a new installation method, perhaps using a web interface like other systems (ex Wordpress)

**Comment by HGustavs** [comment]
This is related to other issues such as #479 that refer to the installer. It may be a good idea to link these issues.

**Comment by HGustavs** [comment]
Web-based installer seems like a good idea.

Keep it simple though, and use the SQL file.

Installers that build the full sql using for example a php script, will make hand-building of the system without the installation script difficult.

So, an installer that builds the database using the sql file is fine. But that SQL file needs to be used.

**Comment by b14vikgu** [comment]
> This is related to other issues such as #479 that refer to the installer. It may be a good idea to link these issues.

How do I link issues?

**Comment by b14davbo** [comment]
@b14vikgu You type a hashtag (#) followed by the issue ID, e.g. for this issue you would type ```#1967```

**Comment by b14davbo** [comment]
Install script has been fixed, see the branch "install-issue" https://github.com/HGustavs/LenaSYS/compare/install-issue

You can now chose another database name than "imperious" and also get to chose if you want to include testdata.sql when you initiate the database. I can make a pull-request of this into group 2 since we're handling the database.

**Comment by b15linek** [comment]
A bit problematic with a new install when a database already exists. Must add an option to write over existing database.
Must make it easier to execute the bash commands at the end of the installer. 
Should write out the last SQL line when error occurs.

**Comment by a15eriho** [comment]
Current issues that need fixes:
* Permissions for all of LenaSYS needs to be, at least, "www-data" for the group. Manually do the "chgrp -R www-data <LenaSYS-dir>" will do. This should preferable be done immediately after the initial copy of the Lena-dir. 
* Create directories for uploads. "LenaSYS/courses/global"
* Create test files specified in the test-data. These files are specified in "testdata.sql".
- Maybe these should be shipped with the installation, in a "testdata"-directory, and copied with the installer-script if the installer want them installed.
- The SQL-file "testdata.sql" maybe should be in this directory also.

Please comment things need be created by the installer.

**Comment by b15linek** [comment]
A suggestion is to move the installer to an install directory inside LenaSYS and put all files needed inside it (SQL files, example files etc.) All installation will be make from inside this folder and the user is free to delete it once installation is finished. Is this a good idea? @HGustavs

**Comment by HGustavs** [comment]
Seems like a good idea.

The sql stuff is *shared* so that kind of fits with the shared folder, but an installer folder in the main folder also makes the installation stuff easier to find... right now this type of stuff is kind of hidden in the shared folder.

**Comment by b15linek** [comment]
We will do it like that then. Copying SQL files from Shared to a new directory. Will remove those from Shared later when it works correctly.
