### ISSUE TITLE
Revamp the add user system for courses.

### ISSUE THREAD

**Issue by a14nikau** [HGustavs/LenaSYS#1969]
The current system for adding users is complicated. it can be greatly simplified especially for users that already exist in the database.

- **Make it easier to add students and teachers that already exist.**

**ISSUES to think about**

- **Adding users needs to update how to parse course participant list.**

The format from the generated course participant lists has changed. We need to update the parser when adding new students.

New format:
[SSN],[Lastname],[Firstname][WHITESPACE][Anmkod][WHITESPACE][Type of registration][WHITESPACE][Study program],[Year of admittance][WHITESPACE][email address]

**Comment by HGustavs** [comment]
How about an add individual user button, with a looking glass icon... 

If I wanted to add myself I would write Gustavs in the text field and all people that have Gustavs in their names would appear in the list, and if I press a person or ok it is added to the list.

Much like how things work in for example dropbox/github/facebook etc. for sharing content.

**Comment by HGustavs** [comment]
The current paste-userlist from webladok is great as it is a good and complete list.

What I would like to see is a tag e.g. red color for any people that have been created from scratch...

These newly created people the user that added that user needs to send an email to that user with the password.

**Comment by HGustavs** [comment]
Sorry. Did not intend to close the issue....

**Comment by a14nikau** [comment]
Small question, do we store anmkode somewhare in the databases?

**Comment by a97marbr** [comment]
anmkode I believe could be the same as course version id. I for one use this in such a way. However, it is not enforcing and we could use any unique code for course version id.

**Comment by a14nikau** [comment]
There will be a partial solution to this, in the upcomming merge.

This will not be using the new format the next one will.
