### ISSUE TITLE
Unclear CodeStandard regarding variable names

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#1971]
I think it is unclear from the code standard documentation https://github.com/HGustavs/LenaSYS/wiki/Code-standard that we use camelCase for variables. Could the example be improved?

**Comment by HGustavs** [comment]
No underscores in table names variable names or columns.

This rule has been broken, variable names can be fixed but column names and table names must remain as is.

**Comment by HGustavs** [comment]
Im thinking this is a very simple issue to fix and to close.

**Comment by b14vikgu** [comment]
Should be fixed now.
