### ISSUE TITLE
Modularize CodeViewer.js

### ISSUE THREAD

**Issue by Snuffsis** [HGustavs/LenaSYS#1990]
I believe that it would be beneficial to modularize the codeviewer.js file. As it is now it is massive with 2000 lines of code doing different things. I feel it would make it easier if it was modularized into smaller components. 
For example: The function that deals with highlighting important words could be its own file, highlight.js

**Comment by HGustavs** [comment]
No. That is too small.

The ambition is that as much as possible should be in a file to make it easy to find things.
The rationale is that it is easier to find something inside one file than inside 10 files.

So, perhaps splitting it into two parts, one for the tokenizer and one for everything else could be ok.... but splitting it more adds complexity we do not want.

Another possible division is to split the file into user-interface things and one for everything else. Having a view and a controller file would make things easier to find, everything that has to do with showing and hiding things in the user interface and reacting to clicks in one file, and one file that processes the data.

That is a division we have talked about before and I do prefer that to any other division.

**Comment by HGustavs** [comment]
Related to issue #466

**Comment by a17poner** [comment]
in issue #1210 you say that to do the mvc split we'd need to do so for every file/service which isn't feasible, so this issue should probably be closed. If its about splitting up functions to make the giant beast which is codeviewer.js more readable that is already mentioned in #1210.
