### ISSUE TITLE
Login timeout and button color change

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#1992]
logins timeout too fast. after half an hour?  

Longer timeouts would be better.

Also when login times out the login button does not turn red.. it is still green but nothing works, at which point one has to press the logout/login button twice, one for logout of current and another for logging in again.

Functionality for checking if logged in every 5? minutes or so, and if logged out, refresh to red button?

**Comment by a15tobli** [comment]
Session has been changed to 5 hours. Issue #3199 covers updating the user icon from green to red.
