### ISSUE TITLE
Forum mockup/wireframe

### ISSUE THREAD

**Issue by b14vikgu** [HGustavs/LenaSYS#1996]
Come up with a basic design of how the forum should look.

The forum should be clean and simple, a lot like GitHub issues.
The idea is to have a page with the full forums, but also a smaller view on sectioned.php where the most relevant posts are shown (maybe most shown, or latest?)

The first design could be made using some wireframing software or just paper and pen. Or just create an actual page in a branch.

From this design we can later create database tables (easer when we know what information they should contain)

**Comment by HGustavs** [comment]
Im thinking a photoshoped screenshot of lenasys so we get the same layout.

**Comment by HGustavs** [comment]
Something like this - an accordion-able box with most important forum tags inside?

![forummockup](https://cloud.githubusercontent.com/assets/6978801/14276988/715244e4-fb21-11e5-9935-9a1126d4fdf3.png)

**Comment by a14jaksi** [comment]
Working on the thread-interface. What would be preferable? A traditional timeline-based comment order, like GitHub Issues, or a reddit-like interface, with comments being ordered in a hierarchical fashion, with replies on replies on replies?

**Comment by a14haman** [comment]
@HGustavs we were thinking we should display the (5?) latest active threads in the forum-box (private and public) and have quick-links to each thread next to each dugga/example or whatever.
Does that sound good to you? Also, would you like to have the ability to view all threads connected to a course in an overview-kinda way?
