### ISSUE TITLE
Can't close little window in duggapreview with click

### ISSUE THREAD

**Issue by g13johbj** [HGustavs/LenaSYS#1998]
Går ej att stänga rutan som pilen pekar på genom att klicka på krysset
![littlewindow](https://cloud.githubusercontent.com/assets/9322288/14276214/bb8ae65a-fb1d-11e5-8a54-38c66c16f812.png)

**Comment by HGustavs** [comment]
....Im thinking it would be a good idea to do away with that box and place it within the main box....

**Comment by a97marbr** [comment]
Yes, this could be an option. We should, however, make sure that we still have a clear distinction between the stats and the dugga.

**Comment by d11karjo** [comment]
One minor thing that might have to be altered; if you hover over a fist to show the window while at the same time hovering over the upper border of the stats window, the mouse pointer changes to look like the box can be moved, which is not the case. Not a big flaw, but something that might be worth looking at.

**Comment by a14vicni** [comment]
#1891 issue fixed that problem guys
