### ISSUE TITLE
Markdown wish

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2009]
I would like markdown for iframes similarly to how images work

markdown symbol lets say (-- for iframe and --) for end of iframe, two arguments are given as pixel sizes and one web address.

(--400,400,www.foo.nu--)

This would result in an iframe of 400px by 400px linked to www.foo.nu

**Comment by a97marbr** [comment]
Yes, this would be most useful.

**Comment by b14davbo** [comment]
Seems to be working. No pull request was made because we reconstructed our branch due to some issues.

This is also documented in our [wiki](https://github.com/HGustavs/LenaSYS/wiki/LenaSYS-Markdown).

**Comment by a97marbr** [comment]
Again, you need to make sure that the PHP version gets updated as well.

**Comment by a14jimso** [comment]
Now added to php as well.
