### ISSUE TITLE
Need and icon for hidden rows, should look like an eye with a slash over

### ISSUE THREAD

**Issue by g13johbj** [HGustavs/LenaSYS#2010]

**Comment by HGustavs** [comment]
Hidden rows where?

In section editor?

I kind of like the transparent grayed current look, but also having an icon could be nice.

Or are we talking about something else?

**Comment by g13johbj** [comment]
Yes in the section editor, just opened an issue so another person who is more experienced in photoshop could make a nice icon.

The icon will be placed on the hidden rows to make it easier too see wich rows are hidden since it can be hard to spot the difference with just a glance.

**Comment by a14ponse** [comment]
![johannes oga](https://cloud.githubusercontent.com/assets/18189123/14310900/bb07cab4-fbe4-11e5-95e5-f6e1b51accd5.png)

Eye, you can scale it as you like to make it fit. If you have any infliktions @HGustavs just let us know.
