### ISSUE TITLE
Add a configuration switch to disable the fourth round-trip for service logging

### ISSUE THREAD

**Issue by b14vikgu** [HGustavs/LenaSYS#2011]
As seen in #1957

> A configuration switch to disable the fourth round-trip step would be needed as it adds a network request that was not present previously, in a constrained network, having the ability to disable this "un-necessary" network request would be a good thing.

**Comment by HGustavs** [comment]
Perhaps in a separate file, to make it easy to find? 

settings.js or settings.php ?

~~~
noRoundTrip=false;
~~~

**Comment by b14vikgu** [comment]
This configuration switch now exists and can be changed on the settings page, however the code that shows crashes on the analytic page still does not take this setting into account. Maybe the setting value should be logged for each service call entry so that the analytic code can decide if a call missing step 4 is a crash or not.

**Comment by a18filkr** [comment]
Closing issue, this cannot be found in new analytic nor seen as a problem anymore.
