### ISSUE TITLE
Button press logging

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2014]
I want logging for almost every button press in the user interface.

Like in the old logging functionality that logs screen sizes and operating system also.

I would like to ask queries such as on resolutions over x does different things happen when compared to resolution y.

Does people press different buttons in Edge compared to Chrome.

How often do users press new section button.

Which users press cancel on dialog x.

**Comment by HGustavs** [comment]
It would even be nice to know the mouse coordinate of the click on a button and also the scroll position.

Groundwork for monitoring the scroll and mouse or touch position would allow us to do this.

e.g. adding a global mousemove/touch handler in dugga.js would allow us to collect the mouse coordinate on any dialog more or less automatically.

If we wanted to be REALLY thorough when it comes to logging we could log the mouse position every 5-ish seconds or at button click and periodically (once every five minutes?) we can send a package of mouse coordinates and scroll positions to the server.

If we have that information we can do very deep analysis of user behavior.

**Comment by b14vikgu** [comment]
Wouldn't this be very simple to do if we just log on all clicks by binding to the click event on document?

For example:

```javascript
$(document).bind('click', function(e) {
    // Here we have the event object e which contains all the info about the click
    $.ajax({
        url: <some-ajax-log-click-service-url>,
        dataType: 'json',
        data: {
            target: e.target
        }
    });
});
```

The data sent to the server can contain almost anything, from id of clicked element, to screen coordinates, screen resolution and so on. This way we would not have to include something at all places where we handle clicks, which will make the code a lot cleaner, and we will avoid many merge conflicts.

**Comment by HGustavs** [comment]
Seems like a good idea. Except for new file. We want this as part ofvdugga.js
