### ISSUE TITLE
If you add important word documentviewer does not work on school computers

### ISSUE THREAD

**Issue by a14jimso** [HGustavs/LenaSYS#2026]
We do have a solution ready to implement and fix this, so this issue will merely be for follow-up and documentation for what have been done, and who fixed the issue.

For some reason, which we suspect is due to the schools computers not being up-to-date, the document viewer does not work when adding important words. 
It has been tested on students laptops, both mac and windows, and they work fine there. 
The error that is thrown is
"TypeError: can't supply flags when constructing one RegExp from another" in CodeViewer.js. Row 959.
According to Mozilla* documentation regarding RegExp, this is fixed in ECMAScript 6 and later, so this shouldn't have occured had the schools computers been up-to-date with support for this. Seeing as it worked on all the students personal computers that were tested.

**Comment by a14jimso** [comment]
Related to #2008

**Comment by HGustavs** [comment]
exactly what regexp is it that is broken? (quote code please so anyone can offer opinions if we have any)

**Comment by a14jimso** [comment]
The code in question is this function in CodeViewer.js
`function replaceAll(find, replace, str)
{
    return str.replace(new RegExp(find, 'g'), replace);
}`

**Comment by a14jimso** [comment]
An issue has now been merged.
