### ISSUE TITLE
Icons should be svg.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2032]
As in topic. Some icons are svg but others are png.

I vote for svg on all icons, so that it looks sharp even on retina and in super-zoomed screens.

**Comment by a97marbr** [comment]
Icons yes. Not all graphics though ... I think to recall a performance discussion for example regarding stoplights in the marking page.

**Comment by HGustavs** [comment]
To clarify, any icon that is single color - svg

a single color icon with for insance a soft shadow would not be suitable as svg...

**Comment by d11karjo** [comment]
Okay, just to clarify, at the moment of writing the following png-files are in the process of being converted/remade in svg.

DuggaSys/templates:
color_black
color_blue
color_cyan
color_darkgreen
color_green
color_magenta
color_maroon
color_navy
color_olive
color_purple
color_red
color_teal
color_white
color_yellow

Shared/icons:
duggaLock
G
Gc
Gh
U
Uc
Uh
VG
VGc
VGh

The ones that have shadows (the G, U, and VG ones, mostly) no longer have said shadows, unfortunately. But I had already started to remake them when I read your last post, so I thought I might as well continue.

Are there any of these that should NOT be converted to svg, and are there any other icons you think ought to be converted?

**Comment by HGustavs** [comment]
The new icons, the forum icon (speech bubbles) and the crossed-out eye that was added for the section editor by someone.

And any other new icons I do not know about.
