### ISSUE TITLE
Forum does not fit with system architecture

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2065]
So....

Reviewing the code of the forum module, there are some changes that need to be made.

The layout for all code in the project is as follows:

blabla.php (any static content)
blablaService.php (receives the database updates, and sends data in json to application)
blabla.js (Sends data to service and renders result in json using javascript)

so by that standard the code should contain only the files listed below No html in the php files and all database access in Service file. I am fine with putting the forum in a folder, but it could also be placed in the duggasys folder.

forum.php
forumService.php
forum.js

**Comment by HGustavs** [comment]
I reviewed the first branch that started this fix and it looks very good, everything is structured like in the other sub-projects. Great work.

**Comment by a14jaksi** [comment]
Fixed in commit: https://github.com/HGustavs/LenaSYS/commit/c477dee888e368c57c2781a37d009b7a6e298f17 and https://github.com/HGustavs/LenaSYS/commit/8ec7f20058fc27f2c4289fab8da3c984a940ca4c
