### ISSUE TITLE
code viewer does not comply with general layout.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2066]
For legacy reasons the code viewer component does not fit 100% with the general architecture of the system.

The files are currently called
EditorV50.php
codeviewer.js
editorService.php

How large would the implications be of fixing this?

In the ideal case we could just change the names to:
codeviewer.php
codeviewer.js
codeviewerService.php

...and move the files to the duggaSys folder.

and nothing bad would happen.

However... I think that we need to change a few more places, for instance there is a link in the duggasys section editor that needs to be changed so that the link points to codeviewer.php instead of ../codviewer/Editorv50.php

...

A few links to shared files or folders need to be re-jigged to fit...

Is this fix so small that it can be made without completely crashing the system??

**Comment by HGustavs** [comment]
Kind-of related to #1990

**Comment by a14jimso** [comment]
Renaming the files would be fairly simple, since one could use a regexp in a text editor to find where it occurs and change the relevant lines. 
The moving of the files, however, would be a bit more troublesome, But theoretically, the same solution as above could be used?

**Comment by HGustavs** [comment]
If it is not very cumbersome I vote for making the change, since it clarifies things a lot and also makes the url-s look a bit more unified. 
For future programming in this project or future projects is also easier since all sub-projects have the same layout.

**Comment by a14jimso** [comment]
We agree with the change.
We will look into this. We will have to coordinate this change with other groups as well to avoid any major conflicts during the next weekly merge.

**Comment by a14jimso** [comment]
@HGustavs Should the renamed CodeViewer files be in \duggasys\ or in \duggasys\codeviewer\?

**Comment by HGustavs** [comment]
/duggasys

all files in same folder. Easier to find everything if it is found in one unified place.

**Comment by a14jimso** [comment]
Refactoring has been completed. We renamed the files like you wanted, and we moved them into DuggaSys.
