### ISSUE TITLE
Bit-dugga don't show the answer

### ISSUE THREAD

**Issue by d11karjo** [HGustavs/LenaSYS#2067]
When you submit a bit-dugga, the answer is recorded in the database, but the answer is not shown when you view it in the "fist-view".

**Comment by b14kriwe** [comment]
Could a screenshot be added for even clearer where it isn't showing?

**Comment by d11karjo** [comment]
![bitdugga1](https://cloud.githubusercontent.com/assets/18137886/14451865/be5b81a6-008a-11e6-830c-1b64ac86f138.png)
1. While logged in as k90kakli, a student, we enter an answer on the dugga.
![bitdugga2](https://cloud.githubusercontent.com/assets/18137886/14451876/cd9ee41e-008a-11e6-8ac2-b98d1ddde606.png)
2. Next, we save the dugga. The answer is now recorded in the database.
![bitdugga3](https://cloud.githubusercontent.com/assets/18137886/14451884/dd7c3544-008a-11e6-9e98-133911c1add2.png)
3. While logged in as s91stcar, a teacher, we enter the results page and click the fist-icon for the dugga that we just handed in as k90kakli.
![bitdugga4](https://cloud.githubusercontent.com/assets/18137886/14451911/07cbde76-008b-11e6-96d0-e03f568fbe52.png)
4. ... and the submitted answer is not shown.

**Comment by a13arnhe** [comment]
On the subject of these dugga answers. What structure are you thinking of having them in? should it show the answers simply as text in the pop-up dugga window, or should it recreate the dugga and the questions and answers just as the user marked them?

The kryss dugga has this text format of showing the answers and a big jumble of every possible answers I am guessing (image below). Is this the format that you are seeking after?
![screen shot 2016-04-12 at 13 41 42](https://cloud.githubusercontent.com/assets/18159848/14458885/c74d17c8-00b4-11e6-93dd-a2b3fe2cae98.png)

Or should the answer be more like the dugga itself like I was mentioning, something like below. The radio buttons could be disabled so they can't be changed and the teacher can see it in a more representable and understandable format.
![screen shot 2016-04-12 at 13 47 10](https://cloud.githubusercontent.com/assets/18159848/14458945/40d70824-00b5-11e6-8667-144926723830.jpg)

**Comment by d11karjo** [comment]
It seems that it doesn't work for other duggas either. This should be fixed post-haste, if possible.
