### ISSUE TITLE
Cruft

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2068]
There are a few folders that I think we can delete.

The 

```
playerEditor
```

and

```
UserManagementView
```

 folders are not actively updated and since none of the code will work when we are changing the system it is best to remove them from the current folder structure as we only want working modules in the code.

If anyone wants to run these, they can use an older release version. There is no point for us to keep that old non-working code in the source tree.

**Comment by a14emeax** [comment]
In UserManagementView is the changepw.php and changeteacher.php files that is used by the system. However, playerEditor might be possible to just delete. I recommend Group 1 to take a look at this.

**Comment by HGustavs** [comment]
What are we using changepw and changeteacher for?

If any functions in those files are still called somewhere in the system the code should be moved to basic.php ???

**Comment by a15freed** [comment]
The only thing I can find on this issue now is that in the dugga.js there are two parts that contain usermanagementviewservice.php, but the file is missing and probably got deleted in erlier merges and that these parts are no longer in use  by the system.

![image](https://cloud.githubusercontent.com/assets/26706932/25481097/ea6ed026-2b4b-11e7-8a39-a7cc00dc50ab.png)

we could probably removed these lines safely from dugga.js?  @HGustavs

**Comment by a17joaap** [comment]
Removed the lines of code in question. @HGustavs

**Comment by a17joaap** [comment]
Fixed with [this merge](https://github.com/HGustavs/LenaSYS/pull/5671)
