### ISSUE TITLE
Checking off old issues

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2069]
There are a few very old issues that I think have been solved (or made irrelevant by other changes) such as 
#513
#512
#480
#488
#499
#916
#765
#714
#562
#565
#717
#916
#1071
#1073
#1075

One suggestion would be to close those issues if they indeed are solved already but have not been previously closed..... this way we can reduce the number of open issues significantly without much new work....

**Comment by HGustavs** [comment]
It is a good idea to start from earliest issues, and as one moves along remove issues that are irrelevant or already fixed.

This also catches old and possibly forgotten requirements.

Also the issue list is reduced fast.

**Comment by a13arnhe** [comment]
Posting again to rid the list of closed issues.

Open issues:
#488 
#499 
#565 
#717 
#916 
#1071
#1073 
#1075

**Comment by a15jorpa** [comment]
It seems only issue #717 is still open (checked the ones in last post), can this issue (2069) be closed?

**Comment by HGustavs** [comment]
Yes. It is a good idea to periodically walk through the issues from back to front and close any resolved or irelevant issues.
