### ISSUE TITLE
Marking: Changing a grade negatively with confirmation

### ISSUE THREAD

**Issue by klump** [HGustavs/LenaSYS#2071]
With the new marking window in place (and already before) it is easy to misclick when marking submissions. This can result in two situations:

1. **Students who should get pass get failed**: this is not so problematic as I can change the grade
2. **Students who should get fail get pass**: Problematic as I cannot change the grade (or am I just blind?)

Proposed solution:
Allow me to dubbelclick or something on the fail grade for a passed student **and** ask for confirmation.

**Comment by b14davbo** [comment]
In LenaSYS, you cant change a grade downward. I.e., G->U and VG->G. Only upwards. I.e. G->VG.
This is related to issue #1853

**Comment by HGustavs** [comment]
We have toyed with the idea of using ctrl+click for changing grades back.

However this is partially a legal issue, we are not allowed to downgrade marks without contacting and receiving a confirmation from the student or an administrator.

...Perhaps this legal conundrum can be solved by a tv-bleep-censor-delay, any mark is changeable the first minute then  the result is posted permanently...

**Comment by klump** [comment]
Is it really a legal issue? The only "real" grade which is hard (impossible?) to downgrade is the grade reported into Ladok. The grades shown on SCIO and Lenasys are not subject by the same rules AFAIK. SCIO has no such restrictions for changing a students grade.

**Comment by d11karjo** [comment]
Would it perhaps be acceptable to have some sort of confirmation window pop up? For example, if you press the U-button, a window pops up asking "Are you sure you want to give [this person] a grade of U on [this course]?"

**Comment by klump** [comment]
Yes, that is what I meant. I would like this for each examination in the course, not only the whole course, but yes, a popup sounds good. I think downgrading should require some form of special trigger (not just a simple click, a double click or ctrl+click).

**Comment by k14marst** [comment]
solved in this pull request #2258 and already implemented.
