### ISSUE TITLE
Time on test

### ISSUE THREAD

**Issue by d11karjo** [HGustavs/LenaSYS#2084]
Every section under sectioned.php that has the type "Test" recieves the following time: 2015-12-31 00:00:00. The time section is presumably meant to show either when the section is created, or when it was started/finished by the user, but as is it only shows said time. Not only that, the time persists if a section changes type, which doesn't seem to be the intention.

**Comment by HGustavs** [comment]
It should contain the deadline of the test that it is connected to.

If it is not connected it should not show a deadline.

**Comment by a13arnhe** [comment]
Merged

**Comment by a14maxry** [comment]
https://github.com/HGustavs/LenaSYS/pull/2102/commits/43935d1cc429184d0f2b26fc1a65a1ffb5d963dd
