### ISSUE TITLE
Dugga-receipt pop-up

### ISSUE THREAD

**Issue by a14jimso** [HGustavs/LenaSYS#2125]
The receipt when submitting something for a dugga, for example when we are submitting text for the diary for the course, should be e-mailed directly to the students his-account, much like when submitting things to scio, instead of popping up and prompting the student to save it themselves

**Comment by HGustavs** [comment]
Can be added as an option, but since the machine is port-blocked from sending email this is not possible on the machine we are using.

Since it is not applicable to our own case, I vote to down-prioritize this, to if-everything-else is fixed status.

**Comment by a15elibr** [comment]
Closing this issue, since we can't send emails, and another solution is being made in issue #2504.
