### ISSUE TITLE
Add analytic service call for service usage

### ISSUE THREAD

**Issue by b14vikgu** [HGustavs/LenaSYS#2126]
Add the call to Duggasys/analytictoolservice.php (see how the other queries are done)

The query should count how many hits each service gets. This can be done by querying the serviceLogEntries table in the log database. The query could filter to only fetch rows where eventType is ServiceClientStart (so no service calls are counted twice).

Here is an example of how the data returned from the call should look:
```json
[
	{
		"service": "courseedservice.php",
		"hits": 503
	},
	{
		"service": "duggaedservice.php",
		"hits": 41
	},
	{
		"service": "sectionedservice.php",
		"hits": 302
	}
]
```

I am not sure if we should count all the rows or restrict them to a specific time period (like a year back?). What do you say @HGustavs ?

**Comment by HGustavs** [comment]
Im thinking that one enters a parameter e.g. hourly/daily/monthly/weekly etc and you get a hit-count for each period.... a bit like a group by. 
So if we go for daily we get something like below. Then we can draw a diagram based on that data. 

2016-03-01 courseedservice.php 120
2016-03-02 courseedservice.php 240
2016-03-03 courseedservice.php 170

I would like to enter start time, end time, interval

so I could enter something like
2016-01-01 2016-04-15 daily
or
2016-01-01 12:00 2016-01-01 18:00 hourly

**Comment by b14vikgu** [comment]
It is now possible to filter by start-end and interval type (see https://github.com/HGustavs/LenaSYS/commit/4ca2e8cdc2c5bd60aca0b5029176714ceaecf622)

Closing this.
