### ISSUE TITLE
Add analytic service call for finding service crashes

### ISSUE THREAD

**Issue by b14vikgu** [HGustavs/LenaSYS#2127]
Add the call to Duggasys/analytictoolservice.php (see how the other queries are done)

The call should go through the serviceLogEntries table in the log database. It should find all the service calls that are not complete. Each call has a unique id (uuid). Calls that were not completed can be found by finding calls that do not have rows for every step in the service call (ServiceClientStart, ServiceServerStart, ServiceServerEnd, ServiceClientEnd).

Here is an example of how the data returned from the call should look:

``` json
[
    {
        "uuid": "saDOpiasjdas8",
        "service": "courseedservice.php",
        "timestamp": 123456789,
        "lastStep": 7,
        "userAgent": "Mozilla 5 blablabla"
    },
    {
        "uuid": "O4ASdosaiu8j",
        "service": "sectionedservice.php",
        "timestamp": 123456789,
        "lastStep": 6,
        "userAgent": "Chrome 11 blablabla"
    }
]
```

Where 7 and 6 are the id's for EventTypes::ServiceServerEnd and  EventTypes::ServiceServerStart.

**Comment by HGustavs** [comment]
Crashes but also very big slowdowns e.g. anything over X seconds. (X being configurable)

**Comment by a14sebpe** [comment]
Solved finding crashes https://github.com/HGustavs/LenaSYS/commit/4d998704168e6f18b9f3f6117dcc2964ad847158
