### ISSUE TITLE
Add analytic service call for discovering password guessing

### ISSUE THREAD

**Issue by b14vikgu** [HGustavs/LenaSYS#2128]
Add the call to Duggasys/analytictoolservice.php (see how the other queries are done)

Query the log database to find scenarios where the same remote address and user name combination have made a big amount of login tries which has failed. I would say more than 10 fails is a good start.

Here is an example of how the data returned from the call should look:
```json
[
	{
		"userName": "kalle",
		"remoteAddress": "123.123.123.123",
		"userAgent": "Chrome 12......",
		"tries": 543
	},
	{
		"userName": "olle",
		"remoteAddress": "321.321.321.321",
		"userAgent": "Mozilla 4.......",
		"tries": 1032
	}
]
```

**Comment by a14sebpe** [comment]
Solved in https://github.com/HGustavs/LenaSYS/commit/8958706cf1fca89c1c5fad63988a528784236948
