### ISSUE TITLE
Add markdown functionality to the forum replies

### ISSUE THREAD

**Issue by d14alehe** [HGustavs/LenaSYS#2137]
Make it possible styling your reply in a forum thread with markdown.

**Comment by d14alehe** [comment]
I have a question regarding the storage of comments in the database. Should the the comments be stored with the markdown syntax in the database e.g ** text ** or should it be stored using the HTML-tags corresponding to the current markdown syntax: e.g `<strong>` text `</strong>` ?

If it's stored with the markdown syntax, the comment will be rendered obsolete if the markdown tags ever gets changed; And if it's stored with the HTML-tags, comments with the same markdown are going to look different whenever the markdown parsing output is changed and new comments are made afterwards.

At the moment I chose to store them with HTML-tags  that are encoded e.g. `&lt;strong&gt; text &lt;&#47;strong&gt;` which then gets decoded to `<strong> text </strong>` after I'm fetching all the comments for a certain thread. 

Thanks. 

Poke: @HGustavs

**Comment by HGustavs** [comment]
Markdown format to make this completely secure.

Then we use the normal markdown code to process that into html.

**Comment by d14alehe** [comment]
Fixed.
