### ISSUE TITLE
Add a live-preview feature to the forum

### ISSUE THREAD

**Issue by d14alehe** [HGustavs/LenaSYS#2139]
When creating a new thread or adding a reply to a forum thread there should be a live-preview feature that shows how the text actually will look when posted. E.g. how the usage of headings,bold text etc would look when using markdown.

**Comment by HGustavs** [comment]
Nothing too fancy.... I would like something like the one in github.

Not a super-advanced-while-youre-writing-thing, but something like clicking a button and overlaying the editor with a preview passed through the markdown.js function for markdowning.

**Comment by d14alehe** [comment]
Fixed
