### ISSUE TITLE
highlight on HTML tags

### ISSUE THREAD

**Issue by a14ponse** [HGustavs/LenaSYS#2146]
For some reason some HTML tags dosent work with the purple highlights. When you hover the first tag the last one are supose to glow, but if you use for exampel a `<link>` tag it dosent work, the same goes for the `<meta>` tags and the `<head>` tag and the `<html>` tag. Thats the one that i found so far atleast.

**Comment by HGustavs** [comment]
To test if it is the tag itself or some other property, change the test document.

if you change a div tag to a link tag does this appen or if you change a link tag to a div does it work?

It could be some attribute or other property, but I am inclined to believe that there may be something else afoot.

**Comment by HGustavs** [comment]
It would be interesting to see if there is a way to tokenize XML data, like in the XML API course examples or in the Android course examples.

Where is the matching tag of this current tag.

Currently we only use "known" tags, like p html div span etc. But what about XML where NONE of the tags are known.....

any hopes for highlighting general XML?

**Comment by a17vikab** [comment]
To be able to work on this issue, the #5988 needs to be solved.

**Comment by a17andby** [comment]
This issue can be closed. The issue continues in https://github.com/HGustavs/LenaSYS/issues/7269 with a more information about the issue.
