### ISSUE TITLE
Issue with back button

### ISSUE THREAD

**Issue by a14jonal** [HGustavs/LenaSYS#2150]
![back button](https://cloud.githubusercontent.com/assets/18139505/14527997/942ee066-024d-11e6-8931-c143c5d8567a.jpg)
This back button at the top of the page redirekts you to the wrong page. When in codeviewer and you go to upload files the back button takes you to the course page not back to the codeviewer. After that if you keep pressing you go back and forward between the course page and the upload file page. If you hover over the button the tooltip says "Home" instead of "Back" or something.

**Comment by HGustavs** [comment]
"Return to course page" is the original intended semantic of that button.

The house was intended to mean "return to home screen"

**Comment by b14kriwe** [comment]
So is this is NOT an issue, but rather a mislabeled hover text? So if we change the hover text to "Back to course page", would that be correct?

**Comment by a13molno** [comment]
The text is already changed. See issue https://github.com/HGustavs/LenaSYS/issues/2122
