### ISSUE TITLE
save collapsed state moments

### ISSUE THREAD

**Issue by a13arnhe** [HGustavs/LenaSYS#2154]
The moment-view should remember if a moment and its variants are collapsed in the view or not.
By adding an attribute collapsed to moment we can remember the collapsed state of the moment-elements for easier editing.

_(this issue is a copy of #455 except for moments)_

**Comment by HGustavs** [comment]
Well saving as in local storage?

This is per user and not per all users, or am I missing something?

(duplicate comment from issue mentioned above)
