### ISSUE TITLE
Cannot change grading under "Tests"

### ISSUE THREAD

**Issue by k14marst** [HGustavs/LenaSYS#2164]
Changing the grading system on a dugga under "Tests" (for example, from U/G to U/3/4/5) does not actually change anything. It's still possible to change the grading system under the cogwheel on the main page, but not under "Tests".

**Comment by HGustavs** [comment]
Im thinking that either the entry in quiz or the entry in tests is wrong... 

i would guess that tests is wrong?

There should be one in listentry and one other one, set in the dugga editor!?

**Comment by k14marst** [comment]
Well from what I can see, the problem is that the new duggas created on the page "Tests" mainly use and get their grading system from the table "quiz", while on the main page and the "Results" page they mainly use and get their grading system from the table "listentries". In addition to this the tables "quiz" and "listentries" are, as far as I can determine, not connected in any usable way. 

So my suggestion is to remove the option of defining a grading system on the page "Tests" for new duggas. This is because I can't find any relation from the column "gradesystem" in the table "quiz" to any other part of the website.

**Comment by k14marst** [comment]
After talking to Marcus, grading system for duggas will now be adjusted in the page "Tests" only (i.e. it's not possible to adjust grading system for duggas on the main page anymore). Grading system shown in the "Results" page gets its grading system from the table "quiz".
