### ISSUE TITLE
Text submissions can show highscore.

### ISSUE THREAD

**Issue by a14nikau** [HGustavs/LenaSYS#2172]
When i was submitting my daily report i found this interesting bug where i press reset and it shows me the high score at the top of the window, since i haven't gotten a grade for it and since high score on a written exam doesn't make much sense i question its existence. Especially since it was hidden before i pressed reset.
![highscore](https://cloud.githubusercontent.com/assets/9131566/14612904/e885e48a-0599-11e6-884b-cbaccc52ac76.png)

**Comment by d11karjo** [comment]
For now, it might be better to just set Highscore to None manually for these sort of assignments.

**Comment by A15cecal** [comment]
Don't really understand this issue. Can't create the diary and can't provoke this bug

**Comment by A15cecal** [comment]
Closing this issue, can't provoke the bug and it's not really relevant anymore.
