### ISSUE TITLE
Four boxes view

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2173]
I would like a view with one box to the left and four boxes to the right...

could this be possible or has it already been implemented?

**Comment by a14jimso** [comment]
@HGustavs It has not been implemented yet, we will look into adding this. I think it might make the screen feel a bit too cluttered however.

But if it does work, should a mirrored version of this layout also be added?

**Comment by HGustavs** [comment]
I dont think that is necessary.

But a one to four is needed. 

Take a look at this example:

http://webblabb.iit.his.se/Dugga/CodeViewer/EditorV50.php?exampleid=292&courseid=13&cvers=987765

It would be really nice if it was possible to place the result error message below the code and not as an included code snippet in the description section....
