### ISSUE TITLE
Fixing bugs for collapse system

### ISSUE THREAD

**Issue by a13arnhe** [HGustavs/LenaSYS#2174]
Fixing various bugs and improvements for the collapse of moments (section) and duggas (dugged). Issues #455, #2154.

- Collapse not working properly in IE, mentioned in pull request #2156 
- Better way to collapse duggas than just clicking on blank space. A button on the left side maybe.
- Add the course version to the cookies so if student happens to take different versions of a course (two years) each will have an individual collapsed status

_An issue for minor fixes that have been solved but not merged + minor performance & visual improvements_

**Comment by HGustavs** [comment]
Is there a mockup or screenshot to react to?

**Comment by a13arnhe** [comment]
![screen shot 2016-04-19 at 08 43 58](https://cloud.githubusercontent.com/assets/18159848/14630007/ebe6a9ea-060a-11e6-91d2-e0a15ebfd0f0.png)

What about some arrow system like this for the duggas?

**Comment by HGustavs** [comment]
Im thinking that add dugga should (also?) be a floating round button near bottom right corner as suggested by material design. That way if we get a huge list there is no need to scroll to top.

What does add template do?

**Comment by a13arnhe** [comment]
I agree with the 'Add Dugga' button, will add one to the bottom also.

The 'Add dugga template' I am not familiar with, this was already in the duggaed page. It however seems to be the file uploader for new duggas.

![screen shot 2016-04-19 at 09 27 34](https://cloud.githubusercontent.com/assets/18159848/14630940/16907a62-0611-11e6-8f67-db2dd2a2670c.png)

**Comment by a13arnhe** [comment]
I think it would be best to add both those buttons, just add a copy of that div to the bottom. Then the users can access both 'Add Dugga' and '..Template' if needed.
