### ISSUE TITLE
Save button fix.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2186]
Along with the code that gray-es out the save button in a dugga if the user is not logged in,
it would also be nice to gray the button out if nothing has changed.

Example:

A user writes something in a text-submit window 

or

A user presses browse button to select one or more files

...

If the person then presses "save" without pressing "upload" first, nothing happens.

This is clearly a problem as students have reported submitting content to a course, but the only thing visible to teachers is an empty view.

so...

Solution, save is grayed out until upload has been pressed in some part of the generic dugga view.

If there is more than one upload button, one is sufficient, it is not necessary to both upload a zip file and a document to press save, it should be possible to add new files later and press save again.

Im not sure if this is specific only for generic_file_upload or for all duga-save-button-presses.

**Comment by HGustavs** [comment]
In short.

If user is not logged in, show dugga assignment but no variant.

Show grayed out save button, as no-one is logged in.

If logged in, show dugga assignment, with variant assigned.

Only if required action has been performed e.g. upload button press, we allow the user to "save" the dugga content.

**Comment by a14jimso** [comment]
A better solution is what i suggest in my duplicate issue. #2203 
The functionality should be similar to the functionality on SCIO.
Either remove the upload button completely if no actualy uploads should be done, or ignore it when hitting save (which should be renamed to submit).

Submit should then, when pressed, submit any text entered and any files uploaded.

**Comment by HGustavs** [comment]
Well, is is a html forms issue.

There can be any number of boxes, with any number of files going to different places.

This is **very** difficult to handle with one single button.

Also the save/submit/whatever it is called button is generic and does the same action for ALL duggas, not only the generic file receive one.

So, in short,

* difficult to program, as the html form that encompasses all of that will be very difficult or perhaps impossible to make. 
* more importantly, the dugga button is generic, connected to all different duggas, e.g. bit counting, colors, html css or any other dugga, not only to generic_file_upload.

**Comment by HGustavs** [comment]
I agree that removing the save button rather than graying it out could be an option... but as we want to show the dugga even without being logged in, one may miss that one needs to log in to subit a dugga.

**Comment by a14jimso** [comment]
If they are viewing the dugga as a guest, it could be possible to make the dugga only show the description for the assignment, with the submission part being replaced with a "Sign in to submit your assignment" text, maybe with a "sign in" button under the text.

**Comment by HGustavs** [comment]
Yes that would work.

**Comment by a15elibr** [comment]
I will start to gray out the button and then see if the button can be removed in some way.

**Comment by a15elibr** [comment]
Just a question, on the "real" lenaSys (dugga.iit.his.se), the button is already grayed out if nothing has been uploaded. Should it be implemented in "our" lenaSys too? Seems unnecessary to fix something that's already fixed.

**Comment by a14chrve** [comment]
Ett krav enligt Henrik är att när ladda upp knappen trycks ska spara-funktionen ske samtidigt.

**Comment by a16linas** [comment]
I've written a function that checks for change in a textarea, and when it does, it supposedly disables the save button. This has not been tested yet. 

Another issue was to somehow bind the save() and upload() function to one button.

**Comment by a16linas** [comment]
The small code that I've written will be sloped, as the issue regards the file "showdugga.php", which isn't my group's area of focus.

**Comment by d15marwi** [comment]
This Issue was never fixed, there was some confusion about this issue. @HGustavs if this is still something you want to get done, next years students should get an update on what you want.

**Comment by HGustavs** [comment]
I think we can close this issue as it is covered by other functionality making this issue irrelevant.

**Comment by a18kaswi** [comment]
HGustavs commented on 21 May 2018
I think we can close this issue as it is covered by other functionality making this issue irrelevant.

CLOSING
