### ISSUE TITLE
Create a settings page for superusers

### ISSUE THREAD

**Issue by a14antpa** [HGustavs/LenaSYS#2187]
- Add functionality to be able to enable/disable mousemovement-logging.
- Add functionality to be able to enable/disable "client successfully recieved service request"-logging.
- Add functionality to be able to swap database, edit the connection settings for Host, DBname, Username & Password.
- Add functionality to be able to change base values, such as website name, logo etc.

**Comment by HGustavs** [comment]
Yes this is a good idea.

Mostly static view that saves to file/db as in ther issues on this topic.

How about calling it options.php ... optionsService.php etc ???

**Comment by a14antpa** [comment]
I agree with you on that point, will start looking in to it during the afternoon today.

**Comment by a13molno** [comment]
A settings page has been created and you can disable two options. Some things are not done though: 

- The ability to change database is not completely finished. @a14antpa has started working on this though, so there has been some progress and it's buildable for future work. 
- The boxes on the settings page are supposed to be the same size too, but the box for the database are somehow a bit bigger. Might want to fix that later on. 
- Buttons seems to be living there own life. The decide to work sometimes and sometimes not. Not sure why.
