### ISSUE TITLE
The Indentation Issue

### ISSUE THREAD

**Issue by d11karjo** [HGustavs/LenaSYS#2216]
It has come to my attention that some of the files do not have proper indentation. This ought to be remedied, as proper indentation is a great help when it comes to reading and navigating the code.

**Comment by HGustavs** [comment]
Since this kind of refactoring wreaks havok with git, it is a good idea to do that type of thing just after the merge.

**Comment by HGustavs** [comment]
The code standard specifies one tab of two spaces or two tabs of two spaces each as the main indentation scheme.

This is so we could get smaller and smaller indents as we have deeper nesting of blocks.

**Comment by a18kaswi** [comment]
We should discuss this topic at weekly group-meating/weekly merge. For now I think all that is told the developers is that DONT REFACTOR. Maybe some clarity would be good.

**Comment by a18kaswi** [comment]
> nce this kind of refactoring wreaks havok with git, it is a good idea to do that type of thing just after the merge.

Good idea.

**Comment by a18jenro** [comment]
Some more information can be gotten from here: https://github.com/HGustavs/LenaSYS/issues/7757
