### ISSUE TITLE
Submissions of duggas causes problems when non-ascii characters are used

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2219]
When submitting files through the dugga system, i.e., using the generic-file-receive-dugga we get a problem with malformed file paths if we have Swedish characters in the filename or file path.
- **min_fil.zip** works
- **min_låda.zip** does not work

**Comment by a97marbr** [comment]
I think that @HGustavs has an idea for how to solve this. I mark this one as low-prio

**Comment by b14davbo** [comment]
What about having a file like this: [foreign_chars.php](https://raw.githubusercontent.com/bcit-ci/CodeIgniter/develop/application/config/foreign_chars.php) and loop through all characters in the string when uploading a file?

**Comment by b14davbo** [comment]
@HGustavs could you tell us your idea for how to solve this?

**Comment by b16karhe** [comment]
A regex like "**str.replace(/[^\x00-\x7F]/g, "");**" could be used to replace non-ascii characters with "nothing".

**Comment by a14isshi** [comment]
A solution to the problem seem to already implemented. When tested, a file with name ääö.zip were submitted where the filename instead got changed to .zip. The non-ascii characters were replaced with nothing.
![30120680_10211451679674889_2069865123_n](https://user-images.githubusercontent.com/37794167/38250191-6b210284-374e-11e8-8235-c6653c79e461.png)

**Comment by b16karhe** [comment]
A better preview of the fixed problem.
![hej](https://user-images.githubusercontent.com/37793806/38250524-5313860c-374f-11e8-9ac1-45ef4a7d50ff.png)

**Comment by a14isshi** [comment]
As this issue seem to be solved, this issue will be closed and if the solution is bad, a new issue needs to be created.
