### ISSUE TITLE
General mess in sectioned

### ISSUE THREAD

**Issue by d11karjo** [HGustavs/LenaSYS#2222]
After the last merge, it seems something has gone horribly wrong. The sections can no longer be dragged and dropped, it is almost impossible to change anything on the items, and the move-to-top-button just flatout doesn't work most of the time.

We need to look into this, and fix it.

**Comment by b14davbo** [comment]
We can create new boxes, but not update them, something must be wrong with AJAXService in sectioned.js

**Comment by b14davbo** [comment]
Solved at pull request #2223
