### ISSUE TITLE
Create diagram functionality for analytics page

### ISSUE THREAD

**Issue by b14vikgu** [HGustavs/LenaSYS#2239]
Using HTML5 canvas.

**Comment by b14davbo** [comment]
http://www.chartjs.org/ is sweet for canvas charts in HTML :)

**Comment by b14vikgu** [comment]
Yeah I was planning to use that, but the teachers would not allow it unfortunately...

**Comment by b14davbo** [comment]
@HGustavs and @a97marbr 
Personally I don't find anything negative with using a free, open-source, 3rd party library for charts. In my opinion it is stupid to reinvent the wheel, when there's a huge community out there using and supporting charts.js to make beautiful charts it is a bad idea to try re-create it yourself.

Open source is the way to go if you want to make a good software with limited manpower and time...

**Comment by b14vikgu** [comment]
Bar charts, pie charts, and line charts have now been implemented.
