### ISSUE TITLE
Unviewable results when adding more courses

### ISSUE THREAD

**Issue by b14kriwe** [HGustavs/LenaSYS#2242]
As can be seen in the screenshot below, when having a few versions of a course (copied previous ones) we end up with a lot of duggas making it a pain to see and understand them. The proposed solution is adding a drop down list where default is "all", but you can also choose which version to display.

![screenshot from 2016-04-26 10-56-19](https://cloud.githubusercontent.com/assets/18162859/14812695/863fb80e-0b9e-11e6-8054-33258472714f.png)

**Comment by HGustavs** [comment]
That must be a bug.

The dugga-entries should only appear for the local course version.

**Comment by b14kriwe** [comment]
You now have the option to select which version through a drop down list. The drop down list displays the active version when it loads.

**Comment by HGustavs** [comment]
Well the marking view should only show the dugga entries for the currently active version e.g. in the case of the screenshot 97732. 

Any other dugga entries should not be shown. If any dugga from a version other than 97732 is shown that is a bug.

It may be that I misunderstood the issue?

**Comment by b14kriwe** [comment]
As of now with our implementation you will get a drop down list choosing which version to see and grade. The active version will be the version that boots up and is chosen in the drop down list. Before there was some sort of bug, where if you added more version, it repeated the printing process, printingt out "version x's" duggas for as many versions there was in the database. So if there was 5 versions, it would print out dugga 1 & 2 & 3, 5 times, instead of once as it should. I hope I clarified it more this time.
