### ISSUE TITLE
Sometimes you can't remove items from a course.

### ISSUE THREAD

**Issue by k14marst** [HGustavs/LenaSYS#2270]
Created a new test item in a course. Accessed the new test, pressed some buttons on the test and then went back to main course page. Then I tried to delete it but it wasn't possible. It's recreatable so there must be some conflict when not resetting or saving things on duggas and then trying to delete them.
![delete1](https://cloud.githubusercontent.com/assets/18142922/14881128/f3f8f802-0d32-11e6-83bd-81f79ca6bbcc.png)
![delete2](https://cloud.githubusercontent.com/assets/18142922/14881130/f5ae1574-0d32-11e6-844c-01c815563950.png)

**Comment by HGustavs** [comment]
A first step would be to find which part of the code that is culpable and change the error message in that specific spot to something a bit more useful with like the SQL error message and so on.

**Comment by k14marst** [comment]
I found out what the problem is. When someone has entered a dugga then an entry in the table userAnswer is made. So you get a foreign key constraint that prohibits you from removing the course item. This could be resolved by removing any associated userAnswer rows. Is that solution alright?

**Comment by k14marst** [comment]
So, is deleting associated userAnswer rows a viable solution? Because if it is, I've already got a working trigger I just need to add to the database. If not, I'll have to find another solution.

**Comment by a97marbr** [comment]
I am a bit uncomfortable with the idea to delete rows in userAnswer table. If we can guarantee that nothing has been submitted, i.e., useranswer part is *null* and only the creator of the dugga has seen the dugga, than this is a way forward.

A second alternative could be to just keep the dugga hidden.

**Comment by k14marst** [comment]
I'll look into how to check that nothing has been submitted. Another option I've been thinking about is saving the deleted row in another table. So for example create a table called "old_userAnswer" and saving the rows in that table before they're deleted from the userAnswer table.

**Comment by a97marbr** [comment]
@HGustavs what's your take on an old_userAnswer?

**Comment by a16konka** [comment]
This issue can not be repeated, therefore it is propably solved.
