### ISSUE TITLE
Faster Workflow in Code Viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2277]
I would like a way to assign files to all views at once.

Right now it is Select Template, Ok, Cog Wheel First View, Select File, Ok, Cog Wheel Second View, Select File, Ok, Cog Wheel Third View, Select File, Ok, Cog Wheel Fourth View, Select File, Ok

...

I would like a workflow that works like this:

Select Template, Below the template selection images, in same view there are file dropdowns for View1, View2 View3 View4 for selecting Kind, Language (if appropriate) and File for each.

This way, most of the work CAN be done in the template selection window, and it can then be changed by the current normal way of doing it with the cog wheels.

**Comment by HGustavs** [comment]
Ugly Mockup

![mock](https://cloud.githubusercontent.com/assets/6978801/14885692/141ba8e0-0d4d-11e6-9165-a1fa7063ff60.png)

**Comment by a17poner** [comment]
merged!
