### ISSUE TITLE
Markdown hoverzoom specify thumbnail size

### ISSUE THREAD

**Issue by a14jimso** [HGustavs/LenaSYS#2290]
Would be nice to be able to specify the size of the thumbnail when writing the document in markdown.

**Comment by b14davbo** [comment]
Also original size, not only thumbnail :)

**Comment by a15ramha** [comment]
Is it possible that this issue is already solved because size is already specified as an argument of the thumbnailImg function.

**Comment by a15elibr** [comment]
Issue is already solved. Closing issue.
