### ISSUE TITLE
Clean up CSS

### ISSUE THREAD

**Issue by b14kriwe** [HGustavs/LenaSYS#2291]
This is the same as issue #464 - CSS is full of unused code, however bumping this since it's an always in need of check. Adding more comments wont hurt, telling where it's used so it's easy to tracks.

**Comment by b14kriwe** [comment]
I've assigned myself on this as I will be working from home during the week and it seems like a suitable task to take on from home. But more people than me can for sure work on this.

**Comment by HGustavs** [comment]
The part that is most annoying to me is the multitude of dialog stuff, and multiple definitions of buttons.

There should be one style for floating "window" and one style for "Button" ... perhaps one for "Red Button".

Ideally I would want to be able to change the color of all buttons on one row in the css, or one row to change all the fonts and so on.

**Comment by b14kriwe** [comment]
As of now, I've been able to clean up a lot of un-used CSS. I've opened seemingly all non-image files in the notepad and run ctrl + f through all of them, also running ctrl + f in certain specific files, just to verify that it's not used in there.

**Comment by b14kriwe** [comment]
I've looked over the site roughly and tried to see what class and id are used for different buttons. This is what I came up with:
**.submit-button**
Used for:
- New (course)
- Create (when creating a new course=
- The analytic tool buttons
- Course navigation (new/edit version, list, files, tests, results, access) when in course
- Save/reset - In duggas for example
- "Stäng" on pop up windows
- Access (the access page uses it)

**Comment by a15timbe** [comment]
Partly solved in #3731

**Comment by a18kaswi** [comment]
We close these CSS-errors as we have enough to do right now.

The goal is a clear issue-board so we can once again start thinking about these kind of stuffs.
