### ISSUE TITLE
The Great Plan to replace Codeviewer with Ace

### ISSUE THREAD

**Issue by a14emeax** [HGustavs/LenaSYS#2297]
- Define what features we get
- Make sure we don't lose any existing features
- Plan time requirement (do we have enough time to do this?)

Compile to a presentable document for evaluation.

**Comment by HGustavs** [comment]
Many questions. We can try to put the discussion in this issue?

Im thinking replace is a strong word, allowing as an option would perhaps be a less divisive way to say it?

Im thinking, options for a graduated approach, on a per-course basis, and/or for editing only.

In-line editing of code in lenasys, is a long-term stretch goal of this project. Are there benefits that outweigh the risks for a view-only scenario?

What candidates are there?

Are there features in ace (is there a better code viewer/editor) than ace?

If there is an issue with the editor, we expose only teachers to it and only when live-editing code would be less risky than exposing all students all the time. 

An inline-editor only approach with a pop-over would probably be the easiest to implement?

What does a full editor give us that a more passive viewer does not?

**Comment by HGustavs** [comment]
One key point here is that we do NOT do long-term refactoring in this project.

We do short issues limited in time, and we deploy within days.

Anything that is so complex that it can not be tested or used before the next merge is immediately out.

So. An approach that lets us go step by step is paramount.

**Comment by a14jimso** [comment]
Agreed. changing the whole thing would take far too long, since it isn't just about implementing it (this is the easy part), we also have to change the look of it, and make the proper changes to it so that it works as the current codeviewer does.
As such, i think it would be a good idea to adapt small things from it, to improve upon our codeviewer. Something like using the ace tokenizer for syntax highlighting.

**Comment by HGustavs** [comment]
I think this thread can be used to collect these step-by-step issues that we agree upon to be the next steps. That way we can follow the progression and also make sure that we adress the most pressing issues first.

**Comment by a17poner** [comment]
@HGustavs  is this still relevant or has "the great plan" already been implemented?

**Comment by HGustavs** [comment]
Some kind of editor mode for editing code in the file view.

Adding some code editor for this, a bit like how it works for markdown but with ace editor or some other javascript code editor instead.

**Comment by b17carbr** [comment]
@HGustavs I have implemented what you asked for. Please take a look at the linked pull request and tell me if there is anything else you want in regard to the ace editor implementation, such as syntax highlighting.
