### ISSUE TITLE
Change lockbox styling

### ISSUE THREAD

**Issue by a13arnhe** [HGustavs/LenaSYS#2298]
Lock should not be over the dugga. A div above would be better letting the user know that the can see it, but cannot submit it. -At least remove the shadow part. Perhaps move the lock to the bottom (the lock was great!).

**Comment by a13arnhe** [comment]
How is this styling for notifying the user that they need to log in or if the test is locked for submission?
![screen shot 2016-05-02 at 12 04 04](https://cloud.githubusercontent.com/assets/18159848/14952137/1cb9cc70-105e-11e6-9d8e-1f1efb243c29.png)

**Comment by HGustavs** [comment]
This is much better.

Exactly how I imagined it, but better, as there is a concise instruction beside the lock.

Great work!

**Comment by a13arnhe** [comment]
Great! then I will push this on the weekly now.
