### ISSUE TITLE
Possible to resize popout windows too much

### ISSUE THREAD

**Issue by g13johbj** [HGustavs/LenaSYS#2299]
When re sizing popout windows, it should block so that you can't resize it and make it so small so the elements inside doesn't fit the window.
![resizebug](https://cloud.githubusercontent.com/assets/9322288/14951139/23a31c32-1057-11e6-8d82-03c02918b1bc.png)

**Comment by HGustavs** [comment]
Im thinking that resizing should not be possible at all?

My vote would be for close only. No moving around, no resizing.

**Comment by HGustavs** [comment]
Is there a specific reason for allowing movement of the popovers?

**Comment by g13johbj** [comment]
Yes, sometimes you want to resize the textboxes if you want to write lengthy code, and resizing those without resizing the entire popover isn't possible.

**Comment by g13johbj** [comment]
Or should we just remove the resize function and move around function?

**Comment by HGustavs** [comment]
That is the case for the json windows on the dugga-editor, but any other window than that?

Also, resizing windows is nearly useless on mobile.

We prefer solutions that work regardless of resolution.

The text boxes should be small in many cases to encourage brevity.

**Comment by HGustavs** [comment]
Im thinking resize and move on a select few windows that may need it, but never as a generic option on all windows.

**Comment by g13johbj** [comment]
Could you give me some examples of which selected few this function should be implemented on and I'll remove the function from all windows and implement them on only those few.

**Comment by HGustavs** [comment]
This is the only candidate that I can remember off-hand.

![screenshot 2016-05-02 12 11 37](https://cloud.githubusercontent.com/assets/6978801/14952244/14df3020-105f-11e6-8db7-14e8d40d77db.png)
