### ISSUE TITLE
Displaying a file in codeviewer crashes the site.

### ISSUE THREAD

**Issue by a14jonal** [HGustavs/LenaSYS#2346]
If you display a uploaded file in the codeviewer the side crashes. This is a new problems that came up after the recent merge.

**Comment by HGustavs** [comment]
A bit of clarification is probably needed. Are we saying any file or a specific file?

**Comment by a14jonal** [comment]
After further testing it seems to break when i upload a file containing 
~~~
* På
* Dig
~~~
and if you select to display it as code or document it crashes but displaying it as a preview works fine

**Comment by HGustavs** [comment]
What exactly is the problem, the swedish character or something else?

Are there any other test cases.

**Comment by a14jonal** [comment]
Seems to be the swedish character, I tested with a file that only contained a 'ö' and another file containing 'å' both crashes. If you choose preview mode the 'ö' or 'å' is displayed as a '�'.

**Comment by HGustavs** [comment]
Im thinking that something is amiss with the binary conversion.
The content reader should convert the å into & aring; and the ö into & ouml;
