### ISSUE TITLE
UTF8-coding on database tables.

### ISSUE THREAD

**Issue by a14sebpe** [HGustavs/LenaSYS#2353]
I have noticed some of the tables init_db.sql are missing the UTF8-coding line `CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB;`. Do you want us to check the tables and add it to the tables who are currently missing it?

**Comment by HGustavs** [comment]
All tables should be UTF8 even though no content should be UTF8 (we use htmlentities to avoid UTF8 Issues). This way if any UTF-8 makes its way through nothing breaks.
