### ISSUE TITLE
Choose template bug in codeviewer

### ISSUE THREAD

**Issue by Snuffsis** [HGustavs/LenaSYS#2358]
The popup for not having chosen a template keeps popping up, even when one is chosen, if you edit anything, such as the contents, what to show and so on.

**Comment by b16johso** [comment]
This is still an issue in 2019.

**Comment by HGustavs** [comment]
Confirm if this is still a problem.

May or may not be related to the issue that some of the templates are wrong... e.g. ar rendered with scrollbars and the like.

**Comment by a16vikva** [comment]
Can't confirm if this is still an issue. Can't seem to find the problem, or it is working.

**Comment by a18jakme** [comment]
Can't find the bug, it seems to be working.
