### ISSUE TITLE
Center content in settings page 

### ISSUE THREAD

**Issue by a14frilo** [HGustavs/LenaSYS#2365]
Center settings div in settings page.

**Comment by a13molno** [comment]
Fixed in commit #https://github.com/HGustavs/LenaSYS/commit/13bcb9942caf3376600c64b5749ef29233a63617.

**Comment by a13molno** [comment]
Fixed in commit #https://github.com/HGustavs/LenaSYS/commit/13bcb9942caf3376600c64b5749ef29233a63617.
