### ISSUE TITLE
Fixing preview of dugga bug

### ISSUE THREAD

**Issue by g13johbj** [HGustavs/LenaSYS#2367]
Fix a bug when previewing duggas where the highscore window is broken again.

**Comment by a15herny** [comment]
Assuming I would know where this is, what is the bug? I think this is a self set issue and not just no finished. Maybe we should remove/close it? @HGustavs @a15elibr

**Comment by a15herny** [comment]
https://i.imgur.com/iGiX2Au.png - This actually works. We can remove this one.  @a15elibr

**Comment by a15elibr** [comment]
Closing issue since it no longer seems to be a problem!
