### ISSUE TITLE
Improve thread access selection interface

### ISSUE THREAD

**Issue by jakobsisk** [HGustavs/LenaSYS#2373]
Currently you can only select users from one class. You should be able to select users from several different classes.

**Comment by a14jaksi** [comment]
Solved: https://github.com/HGustavs/LenaSYS/commit/374a5c83ff41811814a1cf0fa39648ec547a7054

**Comment by a14jaksi** [comment]
I think this change might have been overwritten somehow in the master branch. Is this the case? If so the commit needs to be reapplied.
