### ISSUE TITLE
duggaed does not work with later PHP-versions

### ISSUE THREAD

**Issue by d11karjo** [HGustavs/LenaSYS#2392]
After the last server update, it is not possible to open duggaed (the tab named "Tests") any longer. This is probably due to a change in the PHP-script, but exactly what is currently unknown.

To be more specific, the update was mainly to get a newer version of PHP that supports hashed passwords. However, the Tests-tab worked before the update, but not afterwards.

**Comment by c14caran** [comment]
This is a very bare issue.
The tab tests works and group 2 has made changes to it without noticing it being broken.

Please elaborate.

**Comment by a16konka** [comment]
A variable is missing inside the _quiz_ table, in the main db file

**Comment by a16konka** [comment]
This issue has been fixed through another issue, therefore this issue has been closed.
