### ISSUE TITLE
List entry with ' will void the ability to change the entry name

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2414]
If we write a list entry such as "Egon's lecture" this will render the row impossible to change.

**Comment by a15freed** [comment]
Is this in the view when creating a course?

Because when creating "Egon's lecture" the link seems broken when inspecting the code like in the picture

![image](https://cloud.githubusercontent.com/assets/26706932/24608148/8ee2aba8-1875-11e7-9a7d-7556726c139e.png)

**Comment by a15freed** [comment]
This issue is solved
