### ISSUE TITLE
Set as default option in Copy Course Version Does Nothing

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2415]
Pretty much what title says... you have to click edit version in section editor to set as default.....

**Comment by a18jenro** [comment]
When I change the default version and try to save that change I get an alert:
![untitled](https://user-images.githubusercontent.com/62876507/80700431-4348e180-8acd-11ea-8c86-d0c843ffc4a4.PNG)
I'm gonna assume that this is the issue you are refering to @HGustavs.
