### ISSUE TITLE
Logging does not happen for "you do not have permission to view this page"

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2419]
One worthwhile effort would be to give us more information on what pages people have tried to view outside the "normal" pages.

Is it possible to replace the standard apache error page with a php-variant which uses logging, and also a redirect to the correct home page?

**Comment by a15jorpa** [comment]
Sure, that is possible. I have made a rudimentary custom error page. What kind of log message should be generated, what information should be stored? Is it meant only/primarily for logged in users? Should the user be presented with a message and a link or redirected automatically? If automatically, how much delay should there be?

**Comment by a16chrsa** [comment]
There were several issues when testing this on the remote server. I will divide this into several issues with smaller changes.

#4843: Link re-directing to the front page.

**Comment by a16chrsa** [comment]
#4872: Log entry for the 404 page. The message shall contain the page which the user tried to access.

**Comment by a16chrsa** [comment]
Issue is solved.
