### ISSUE TITLE
Codeviewer is not reading course local files

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2421]
As title says.

Having a course file (global to specific course e.g. Database Systems) file1.md

And uploading a course local file (local to course  version e.g. Database Systems VT17) file1.md

The latter should be loaded. This does not happen at the moment.

**Comment by a15oscwe** [comment]
Does local file refer to a uploaded file or a file locally on the server?

**Comment by d15johro** [comment]
Is this issue referring to uploading of files in "/LenaSYS/DuggaSys/fileed.php?cid=317&coursevers=1123". If not, how can I recreate this bug?

**Comment by a17poner** [comment]
This seems to have been solved already.
`SELECT filename,kind from fileLink WHERE (cid=:cid or isGlobal='1') and UPPER(filename)=UPPER(:fname) ORDER BY kind DESC LIMIT 1;`
All course local files will have kind = 3 while global files have kind = 2 (vers and local have 4) which should ensure the correct file is used. Closing this issue for now.
