### ISSUE TITLE
Course page design through import

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2422]
I would really like the posibility of creating a course page by importing markdown

-# Course Goal 1 (7.5HP)
-* Code Example 1 ==ex1.js==
-* Code Example 2 ==ex2.js==
-* Test 1 ==test1.md==
-# Course Goal 2 (7.5HP)
-* Code Example 3 ==ex3.js==
-* Code Example 4 ==ex4.js==
-* Test 2 ==test2.md==

This way it would be possible to generate a course page skeleton very fast, rather than by clicking and writing things many times.

**Comment by a16thegu** [comment]
Not relevent anymore. Closing the issue for now.
