### ISSUE TITLE
 Keeping track of marking preview

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2426]
Currently when one clicks the preview to view/edit the results of a sutdent and click a document we are automatically moved bakc to the list of all students when we go "back" from the pdf document.

One would prefer a solution that uses histories or local storage to remember that we were displaying the results of a specific student.

**Comment by A15cecal** [comment]
Can't recreate this issue since the functions controlling this are all broken. Waiting for a fix for now.

**Comment by A15cecal** [comment]
Closing this for the same reason listed in my earlier comment. Can't provoke the bug and see what's wrong, therefore you can't "prove" something's actually wrong.
