### ISSUE TITLE
Marking list row number

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2427]
It would be nice to have an over-sized number for each visible row in the marking view as the left column. 

1 for the first visible student, and 2 for the second etc. Not the number in the dataset, but the sequence number of currently visible students.

**Comment by a97marbr** [comment]
Implemented in https://github.com/HGustavs/LenaSYS/commit/60d0f302c271db0c625d28e825a4353bd4b740dd

**Comment by a97marbr** [comment]
When clicking on the same column (to resort in revers order) the numbers are not ordered correctly. The row numbers should always be from 1 ... 2 ... 3 ... 4 ... etc

**Comment by a97marbr** [comment]
Actually, it is not correct at all. It does not consider gaps when filtering.

**Comment by a97marbr** [comment]
Now it works. https://github.com/HGustavs/LenaSYS/commit/aaec60b6b31b42894533b4c1ad8e738888a79d96
