### ISSUE TITLE
Marking view column click behavior

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2428]
When clicking on a purple heading in the marking view we change the sorting function to be the logical one for that column e.g. most recent unmarked for most column or last name for student.

When clicking on the orange hading in the marking view we change the direction of the sort, if it currently is ascending we change to descending ...

**Comment by a97marbr** [comment]
This is solved in https://github.com/HGustavs/LenaSYS/commit/a639be35cf1caf65c18b244acf30b44928eef791 and https://github.com/HGustavs/LenaSYS/commit/e48741a1719042ff2b8a2f372094b861f8b67a17
