### ISSUE TITLE
Magic hedings in resulted is not properly formated

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2430]
1. We do not have the upper heading only the subheding

2. The heding text is not vertically aligned in the magic headings

**Comment by a97marbr** [comment]
The second issue. The vertically alignment. Is solved in https://github.com/HGustavs/LenaSYS/commit/a639be35cf1caf65c18b244acf30b44928eef791

**Comment by a15freed** [comment]
This issue is solved
