### ISSUE TITLE
Re-clicking on header will not resort

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2432]
If we click once on a header it will resort on that header. Clicking again will do nothing. Clicking yet again will resort properly. This pattern will repeat it self ... every second click on the same column will trigger a resort.

**Comment by HGustavs** [comment]
Is this bug general to all sorting views?

This is related to the implementation details in #2545.... does this bug need to be fixed before we re-implement this in other views?﻿﻿﻿

One suggestion would be to test if this bug is no longer present, we can then retire this issue...

**Comment by a15herny** [comment]
@HGustavs What/Where is this "header"?

**Comment by A15cecal** [comment]
This problem seems to be solved. Closing.
