### ISSUE TITLE
I want a generic accordion widget

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2434]
We really could use a generic accordion widget similar to this:
https://jqueryui.com/accordion/

We already have some code written for this. There is one in generic file dugga and another one in file list. It should be generic and work with the color and sizes used in LenaSYS

**Comment by HGustavs** [comment]
The accordion in file list does not work properly. When one clicks "add file" the accordion collapses.

I like the gray one used in the dugga views more. (even though the gray color is non canon - we can change that to the main color or the contrast color)

**Comment by a15mikla** [comment]
The issue where the content collapses once you click "Add File" is now fixed. Are the remaining requests current? @HGustavs

**Comment by a15freed** [comment]
![image](https://cloud.githubusercontent.com/assets/26706932/24791079/08b17e0e-1b79-11e7-9f62-42c71d8a8c13.png)


The gray/white odd even row in the resulted view got messed up and need to get fixed
