### ISSUE TITLE
Filter view in result editor is cleared to no filtering if the login times out while viewing result editor

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2435]
A better way to do this is to not update the filter property if not logged in, currently it seems that it is cleared if user does not have permission.

**Comment by A15cecal** [comment]
@HGustavs Don't really think this should be implemented. The user will see an alert that the session's about to end/has ended, and if so they can log in again. Seems better and safer this way. Give me some input on this if you don't agree, but for now I'll close this.
