### ISSUE TITLE
Resort after changing mark does not update contents

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2439]
The contents of the in-memory-sorted result table is not updated fully.

* Sort the table on last submit
* Mark one student assignment
* Assignment is shown as marked in table
* Sort again

- Now we expect no change...

but... we get the table without the marked result until we refresh the page.

**Comment by HGustavs** [comment]
This is related to the implementation details in #2545.... does this bug need to be fixed before we re-implement this in other views?

**Comment by A15cecal** [comment]
This seems to be solved already, but will look in to it a bit more before closing.

**Comment by A15cecal** [comment]
Yes, This one is solved. Closing.
