### ISSUE TITLE
If blank filter list we need some output

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2440]
We need a "filter list is blank" output if filter list is blank, currently nothing happens....
which may confuse the user to thing that the code is broken.

**Comment by a15elibr** [comment]
Currently this issue cannot be resolved because there is a fix for filter in process. After the weekly merge tomorrow, this issue can be resolved.

**Comment by a15matab** [comment]
What "filter" are you referring to? On the result editor?

**Comment by a15matab** [comment]
![screenshot from 2017-04-20 09-58-31](https://cloud.githubusercontent.com/assets/26706785/25219667/75996a78-25af-11e7-98e9-a1cf4ed6ee39.png)

@HGustavs @a15elibr is this what you mean? (This is on the Result Editor page)
