### ISSUE TITLE
Students groups in various views

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2441]
Assignning groups to students in access list and supporting per-group marking/handin/assignments

If student A and B collaborate in a group we would want this to be represented somehow.

Unclear as to exact details.

**Comment by b15matol** [comment]
This seems to be related to this issue https://github.com/HGustavs/LenaSYS/issues/2463.

**Comment by b15matol** [comment]
I'm thinking this could either be presented on some kind of profile page for the user, or on a dedicated page that displays all existing groups and their users.

**Comment by a18kaswi** [comment]
This seams solved since the extensive PR-history here. Closing.
