### ISSUE TITLE
Magic headings can some times be above popover modal dialog

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2443]
It is somewhat intermittent.

![screenshot 2017-01-10 13 54 19](https://cloud.githubusercontent.com/assets/6978801/21806938/7b993ba4-d73c-11e6-8351-d55cb8602cf2.png)

Unclear if this is due to clicking outside of the popover, or one touches scroll wheel on a mouce / scrolls on touchpad or for some other reason.

**Comment by HGustavs** [comment]
Marking result view.

**Comment by c14emian** [comment]
Could use some help recreating the issue to see what's wrong.

**Comment by a15freed** [comment]
bump @HGustavs

**Comment by HGustavs** [comment]
Go to the marking view and then click the marking fist followed by the preview of a submission of for example a pdf file.... if we have enough students that the magic heading appears, it should appear above all of the other dialogs.

To repeat this enough studetns have to be added that we are required to scroll down a bit and that the magic heading appears.

**Comment by a17alevu** [comment]
I am not sure where i am supposed to go. I uploaded a PDF file then opened it up but i am not quite sure if i am doing it right? The thing is that the PDF is opened in a new popup (as seen in the picutre) but it is not interfered by any header (what i can see). 


![image](https://user-images.githubusercontent.com/49199285/56195768-de435a80-6035-11e9-9280-1617ba8279a4.png)

**Comment by a17maxsj** [comment]
Removed ?@HGustavs
