### ISSUE TITLE
Search filtering in marking result view

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2444]
What title says.

**Comment by b16filor** [comment]
Is this issue already fixed? You can filter in the result view by for example dugga/pending. @HGustavs

**Comment by HGustavs** [comment]
Sortable table has row filtering.

* If I write "svensson" in a looking-glass search box I only mark for students or teachers named svensson.
* If I write WEBUG I only mark the webug study program (for example)

We should get this more or less for free after having implemented sortabletable.
