### ISSUE TITLE
An overview regarding duggas and how they are allocated during a course

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2451]
I would like to have some kind of service that shows the outline of how the various duggas should be connected. For example, which duggas are required to be done before others, which duggas can/should be done in parallel?

For this to work we need to know when a dugga is intended to start as well as when it should finish.

* A moment ("delkurs") should be a swim lane
* We need a suggested starting time for a dugga
* We need deadlines for duggas
* The required amount of time needed to finish a task should be visible in the length of the lines. For example the blue task requires less time than the pink task 
* Perhaps we should have some indication on when students are supposed to receive feedback on duggas?

![mockuppool](https://cloud.githubusercontent.com/assets/4948661/23166795/4447624e-f842-11e6-966a-31e6e0e95eef.png)

**Comment by c14emian** [comment]
Would this be on a seperate page or somehow implemented into the Dugga view (sectioned)?

**Comment by a15freed** [comment]
Adding a new button for students in file sectioned.js to a seperate swimlane.php page during the development of this issue

**Comment by b14marki** [comment]
There should be an icon for swimlane at the top next to the other icons.

**Comment by a15freed** [comment]
Swimlane icon is added #2929

**Comment by a15freed** [comment]
an overlay (popup) is being developed

**Comment by a15freed** [comment]
overlay is added in file swimlane.php but the swimlane icon need to link to this file

**Comment by a15eriho** [comment]
For this mockup to work, there needs to be a start date and an end date for the course. Atm we cannot find any of these in the database, only the start date for individual tests, and the deadline for them. If this is what is wanted, then there should be specified dates for each course moment.

Is this something that you want added to the LenaSYS system?

An alternative could be to use real week numbers, which might be better for perceiving at what time a moment is active.

**Comment by b15linek** [comment]
A first version was created using SVG. This only works for 'Webbutveckling - datorgrafik' at the moment because duggas in database are not standardised.
<img width="1433" alt="screen shot 2017-04-19 at 13 43 38" src="https://cloud.githubusercontent.com/assets/26706647/25178489/3ef0d35c-2506-11e7-83c8-7a3e76c377e5.png">

**Comment by b15linek** [comment]
Here's the version right now. How does it look? @HGustavs 

http://webblabb.iit.his.se:8080/grupp3/LenaSYS/Shared/swimlane.php?courseid=2&coursevers=97732

**Comment by a15freed** [comment]
Popup added #3258
