### ISSUE TITLE
Teachers are present in marking view

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2452]
In the marking view, if a teacher has been added to the course, that person will be in the list of students for marking.

It is good to have "oneself" to test marking with, but there should be an option to remove teachers from the list... especially for counting students this is very useful...

with the current system it is easy to accidentally cont teachers.

**Comment by d15eriso** [comment]
Is the "marking view" the same as the "result view"?
Are you saying that you WANT the teacher to be present in the result view and you want to be able to remove/hide the teacher, OR is the teacher present and you want to be able to remove/hide the teacher?

**Comment by d15eriso** [comment]
![image](https://cloud.githubusercontent.com/assets/26739514/24705310/a043621a-1a0b-11e7-87a6-469cafa25666.png)

Something like this?
@HGustavs

**Comment by d15eriso** [comment]
I could not get the queries to work so that I could filter out the users with "write" access, and I have spent too much time on the same issue. I suggest @a15eriho take over the issue when he is available.

**Comment by a15eriho** [comment]
Still an issue with executing the filter when page is loaded. A revisit to the filter menu seems to fix it.

Stores the setting in local storage.

**Comment by a15eriho** [comment]
This issue is now completed.
