### ISSUE TITLE
Examiner is not present / visible in result / marking view

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2453]
In final year projects, the examiner is not visible in the marking list.

We need to add the following.
* In access view for a course we add an examiner dropdown which allows the course responsible to rapidly specify the examiner for each student.
* We need to show the name of the examiner in the list in the marking view. (sorting on examiner is an added benefit)

**Comment by c14emian** [comment]
I'll start looking into it, would like to know more specifically how you want it to be designed.

**Comment by HGustavs** [comment]
a dropdown in the access editor to specify the examiner for that specific student. 

the contents of that should come from the list of all teachers in lena.

currently when one clicks the cog wheel in the access editor one can edit the information for that student, adding a dropdown (and corresponding database entry)... would resolve that issue.

Also it would be nice to have the study programme as a dropdown list also.

**Comment by c14emian** [comment]
With study program do you mean course (and if so do you want course ID or course name) or do you mean class in user?

**Comment by c14emian** [comment]
Access view has been fixed, teacher and programme can be selected and updated.

Right now I'm working on the marking view and would like to know where/how you'd want to display the teacher name. Would it be on each individual student or on the entire course?

Will begin implementing a fix where the teacher will be displayed together with each student.

**Comment by a15freed** [comment]
is this issue solved now @c14emian ?  :)

**Comment by c14emian** [comment]
Yes, the issue is solved
