### ISSUE TITLE
Diagram Engine Functionality

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2454]
The diagram engine should work mostly like the engine from google docs

* Each instance of a diagram has a unique hash
* Each instance is represented as a json text document
* Not every minor change triggers an instance (moving an element or resizing it should not trigger changes)
* The engine allows one user of a diagram to query the engine if a diagram has been updated by sending diagram id and receiving the latest hash
* If the hash is not identical with the local hash, the complete document string is retrieved
* If a single user is editing and no other users are viewing the document we only do writing to the diagram.

**Comment by a14davlo** [comment]
I've created an issue for each thing Henrik pointed out. If any of the issues are too large then talk with me and I'll look into what can be done to make it easier for you.

**Comment by a18kaswi** [comment]
Since #2926 is the last remaining issue of this megaissue, i'm closing this one.
