### ISSUE TITLE
Offline diagramming

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2455]
Since the diagramming engine works through reading or writing json documents, an offline or slow-internet version of the engine should be possible e.g. by storing the diagram in local storage and ony infrequently updating the on-server document.

**Comment by a14davlo** [comment]
c14joalu will be working on this. If this issue is too big for a few days of work, come and talk with me and we'll sort it out and split up the work better.

**Comment by c14joalu** [comment]
@HGustavs , I wondered with this, is it just as simple as that it will update the on-server text document when possible ( or set a timer for it ) and simply have a button for a person to be able to view the canvas text document so they can save it manually on the computer if there is no connection while working on it?

**Comment by c16carbe** [comment]
This is already possible. Issue should be closed.
