### ISSUE TITLE
Magic Headings Marking View - Columns

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2461]
I would like to have magic headings on the columns in the resulted service.

If a course have many duggas and we need to scroll horisontally, I would like to still see the rownumber and the student name in the same way as we see the dugga names when we scroll vertically.

**Comment by c14emian** [comment]
I've implemented a solution using position:fixed, the first 2 columns (rownumber and student name) will stay on the left when scrolling horizontally. It isn't a pretty fix though and needs some work on the styling.

Would like an opinion whether the solution is accepted as well as on how you would want it to be styled.

**Comment by c14emian** [comment]
Would also like to add that in order to make a "proper"/better solution I would need to change how the table is created. It would be possible to make a better solution using overflow and make the table scrollable, this solution doesn't seem to work with this table unfortunately.

**Comment by c14emian** [comment]
Due to conflicts the isssue has not been merged, I will make a backup/copy of my solution and put it on ice for now. Would like to discuss the solution before implementing it into the new version. @HGustavs @a97marbr

**Comment by c14emian** [comment]
I have discussed with the client and the current solution will not work, will take a closer look on the vertical magic headings and attempt a new solution at a later point. Issue is still on ice for now as I'm currently in the middle of a different issue.

**Comment by a14phili** [comment]
Solved and merged #3991
