### ISSUE TITLE
Email response for duggas

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2464]
I would like to be able to contact students based on their results.

For example:
* Inform all students who have not been active at all
* Inform students that a deadline is near
* Inform all students who have failed duggas
* More

It is enough to have a feature that generates the list of recipients and a pre-generated subject and content. The actual sending of the email can be done by external email client.

**Comment by a15tobli** [comment]
Closing issue as we are not allowed to implement email functionality. We are planning to add this functionality through push-notifications instead, issue #2504.
