### ISSUE TITLE
Split diagram.js into parts

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2467]
I think that diagram.js will be too big to fit the one function one file rule.

I suggest we augment the code styleand specify that we allow additional class files if they are sizable (>1000 lines of code) and localized (used only in one module).

I suggest using adding the class name to the name of the file e.g.

diagram.js (for user interface stuff)
diagram_diagram.js
diagran_symbol.js
diagram_figure.js
etc.

Indicating that it is part of the diagram module but that each sub-class (there will only be a few of these) has its own file.

The goal is to keep as few of these files as possible.... but to separate diagram class from the symbol class.

**Comment by HGustavs** [comment]
I strongly prefer not splitting the symbol or giagram classes further e.g. a er-entity class or a er-attribute class.... I want this functionality encapsulated within a single class in order to make the code as small and generic as possible.

**Comment by a15admsa** [comment]
Are we allowed to change the name of diagram.js to diagram_userinterface.js when we split up the big diagram.js-file into smaller parts?

**Comment by HGustavs** [comment]
I would say no on the name change as the rest of the project has standardized naming of user interface stuff.

e.g.
sectioned.php <- Static user interface
sectioned.js <- User interface code
sectionedservice.php <- Data service

Im thinking we try to adhere to this rule as much as possible, and only make incremental update by adding specialized files in addition to the standard ones.

**Comment by b15matki** [comment]
A couple of questions:

- What is the difference between a figure and a symbol, if there is any?
- Is it enough to create two files, one containing the symbols and eventually also the figures and one file containing the "rest of the code".

**Comment by HGustavs** [comment]
Figures are a collections of lines and fills etc that can be used to create a software such as illustrator or to draw custom shapes in a diagram.

Symbols are glyphs in a diagram e.g. ER entity, UML Class etc that have properties like names and so on.

So if we want to draw for instance a border line around parts of the diagram to indicate which group is the owner of that part of the diagram, we do that with a figure.... but each of the diagram symbols such as entitites or classes are drawn using symbols.

**Comment by HGustavs** [comment]
![screenshot 2017-03-29 15 55 17](https://cloud.githubusercontent.com/assets/6978801/24458164/6f62195c-1498-11e7-925b-a9849ce25482.png)

The pink part is a figure and the rest of the diagram is composed of symbols.

I suggest we start out with the symbols, one diagram at a time and then move on to figures if there is time.

**Comment by a15admsa** [comment]
This issue has now been resolved and diagram.js has been splitted up into multiple files.
