### ISSUE TITLE
Diagram scaling

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2472]
I suggest an implementation that uses view position (position of top left corner on screen) and a scale factor to draw graphics.

Currently graphics are drawn without scaling a global scaling factor needs to be used in the draw method and when reading mouse and touch coordinates.

It would be advantageous to have similar scaling for svg output, allowing us to fit more or less of the diagram on a svg image page.

**Comment by HGustavs** [comment]
How about storing scale and position in local storage so that we return to the same diagram view when we return on the same device at a later time.

**Comment by a15admsa** [comment]
Issue is now fixed!
