### ISSUE TITLE
Shared SQL foreign key files not working

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2475]
These sql files does not work.
keywords_sql.sql
keywords_sr.sql
You'll find them if you go into SHARED and then into SQL.
Here's the error message:
ERROR 1452 (23000) at line 1: Cannot add or update a child row: a foreign key constraint fails (`grupp04`.`word`, CONSTRAINT `fk_word_joins_wordlist` FOREIGN KEY (`wordlistid`) REFERENCES `wordlist` (`wordlistid`))

**Comment by a15eriho** [comment]
This issue is handled in issues #1967 and #2649. Files fixed and included/executed in the installation. Closing this issue since it's reduntant and is handled by the issues above.
