### ISSUE TITLE
Add page for user profile

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2476]
When clicking the link with the username you get directed to the non existent file https://dugga.iit.his.se/Dugga/UserManagementView/redirector.php
Suggested solution is implementing a page with a form containing user settings, such as changing password and challenge question.

**Comment by a15timbe** [comment]
Hello! Added a page for user profile #2513

**Comment by a15tobli** [comment]
Hello! I have reviewed your implementation, looks good!

**Comment by a15tobli** [comment]
Merged issue #2513, closing.
