### ISSUE TITLE
Unused SQL tables and entries in sql-files.

### ISSUE THREAD

**Issue by a15eriho** [HGustavs/LenaSYS#2480]
Check which tables are in use and not when creating database.

Remove those which are not in use.

**Comment by a15eriho** [comment]
Also move out the syntax highlighting for php from init_db.sql to keywords_php.sql when clearing out unused stuff.

**Comment by a15admsa** [comment]
The file addtemplates.sql can be removed. The same inserts are in the init.db.sql-file, so there is no use of the file addtemplates.sql.

**Comment by HGustavs** [comment]
agree on removing addtemplates.sql ..

same thing with strutt.sql ...

I described strutt.sql and added it to a separate issue.

**Comment by a15elibr** [comment]
I have solved issue #2483. Created a separate issue for removing addtemplates.sql. #2530.

**Comment by a15eriho** [comment]
What is temptable.sql supposed to do? Since it's not used in the installation, is it safe to be removed?

**Comment by a15eriho** [comment]
Will close this issue. If there still are SQL-stuff that needs attention, new, more specific, issues will have to be created.
