### ISSUE TITLE
Unknown column 'fontsize' in 'field list'

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#2481]
The column fontsize is missing from the database.

**Comment by HGustavs** [comment]
In the file strutt.sql I found this content. I think that these changes also have to be added to the tables in the init_db if they have not already been added.

alter table user_course alter column result SET DEFAULT 0.0;
alter table user_course alter column period set default 1;
alter table user_course alter column term set default 1;
alter table user_course add column vershistory TEXT;
alter table user_course add column vers VARCHAR(8);
alter table codeexample MODIFY runlink VARCHAR(256);

**Comment by a15freku** [comment]
See issue: Added column fontsize to init_db #2484
