### ISSUE TITLE
Merging of changes in strutt.sql into init_db.sql

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2483]
In the file strutt.sql I found this content. I think that these changes also have to be added to the tables in the init_db if they have not already been added.

alter table user_course alter column result SET DEFAULT 0.0;
alter table user_course alter column period set default 1;
alter table user_course alter column term set default 1;
alter table user_course add column vershistory TEXT;
alter table user_course add column vers VARCHAR(8);
alter table codeexample MODIFY runlink VARCHAR(256);

**Comment by a15elibr** [comment]
Assigning d15johro due to similiarity to issue #2481.

**Comment by d15johro** [comment]
this issue should be closed

**Comment by a15elibr** [comment]
Closed due to fix, pull requests created isue #2565 and #2529.
