### ISSUE TITLE
Error updating entriesUnknown column 'studyProgram' in 'field list'

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#2499]
When klicking on "List" in the super user menu an error alert appears with the message "Error updating entriesUnknown column 'studyProgram' in 'field list'". The column should be added to the init_db.sql file.

**Comment by HGustavs** [comment]
Yes, I think that the person that added that column to the database forgot to update init_db.sql

**Comment by a15elibr** [comment]
Closing issue, since List has been removed in issue #2560, this issue is no longer relevant.
