### ISSUE TITLE
Display push-notifications

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2504]
The idea is to send push notifications to browsers from LenaSYS. This function should work even when being offline. By having push notifications at the site, the admins would have a good way to remind students of information, such as deadlines. 
This issue will be split into smaller ones;
#2623 - Ask user to allow push-notifications - SOLVED
#2626 - Save information about push notifications - SOLVED
#2767 - Make notifications work in chrome - SOLVED
#2990 - Set messages for push notifications - SOLVED
#2991 - Stop sending push notifications for inactive or broken registrations - SOLVED
#3028 - Deregister push notifications for lenaSYS - SOLVED
#3098 - Installing the push notifications system - SOLVED
#3137 - Send notifications when a dugga has been graded - SOLVED

**Comment by HGustavs** [comment]
Suggested work process 

* Start out with testing if push notifications work at all by sending to one specific client in chrome on computer.
* Check if notifications are push notifications on mobile browser or if we need to make a webview app....
* If that works
  * Expand to subscription of notifications i.e. asking for notification
  * Generalizing subscription service.

**Comment by a15tobli** [comment]
We will break up this into smaller issues. This issue will be implementing the request to allow push-notifications.

**Comment by a15timbe** [comment]
The last sub-issue #3137 was now solved. All sub issues have been solved and merged. Closing this issue.
