### ISSUE TITLE
Send push notifications as LenaSYS admin

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2505]
When push notifications, issue #2504 is implemented, the idea is to implement a way of creating messages as a LenaSYS admin, which all the subscribed browsers would check for with regular intervals. When a message is found, the current notification will be shown in the browser.

**Comment by c14caran** [comment]
After discussion with @HGustavs this issue should not be implemented. No custom ways for only admins to send messages was needed, the messages that should be sent are in issue #3137
