### ISSUE TITLE
Cannot upload file in fileed.php

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#2506]
Cannot upload file in "/DuggaSys/fileed.php?cid=1&coursevers=2013". 

Uploading file takes me to "/DuggaSys/filereceive.php" and gives the following warning: "Warning: mkdir(): No such file or directory in /home/sventheman/grupp1/d15johro/DuggaSys/filereceive.php on line 89
No file found - check upload_max_filesize and post_max_size in php.ini"

**Comment by HGustavs** [comment]
I think this is apache settings, allowing large uploads, also, check file permissions on these folders.

Something for the installation script, to make sure that these folders are created and have the right permissions.

**Comment by a15oscwe** [comment]
You'll need to create a folder called "courses" in the LenaSYS-folder. You also need to add www-data as group owner and change permissions recursively to rw for both owner and group.
Do the following:
```
mkdir -p courses
sudo chgrp -R www-data courses
sudo chmod -R 664 courses
``` 
Note that chmod 664 allows for read and write for owner and group, but others may only read the contents of the folder. This is also why the group www-data must be owner of the files and folders.

**Comment by HGustavs** [comment]
This needs to be added to install script.

**Comment by a15wilhe** [comment]
This issue is now fixed. Folder is added and permissions is set to 777 in install. @a15elibr
