### ISSUE TITLE
XMLAPI_report1.js does not exist in LenaSYS/DuggaSys/templates

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#2507]
There is a file in directory LenaSYS/DuggaSys/templates, named XMLAPI_report1_file_receive.js. Is this the file intended?

**Comment by b15matol** [comment]
It could be relevant to note here that the file XMLAPI_report1.js is referenced by the page showDugga, when the template is XMLAPI_report1 is used. Saved in the database as "$duggafile"

**Comment by b15matol** [comment]
@a15tobli I think this can be closed, the changes was reverted.

**Comment by a15tobli** [comment]
Hello, viewed this and closing issue.
