### ISSUE TITLE
cannot create new course in /LenaSYS/DuggaSys/courseed.php

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#2514]
Clicking create-button in dialog "New Course" wont show new course. Button for creating new course  triggers function createNewCourse() found in file coursed.js. Created course is found in database with created attribute as null, however.

**Comment by HGustavs** [comment]
Any errors given in the json data in the console?

Im thinking it may be that some column is missing or something ... 

It seems like someone added things to the database without updating the sql that creates the database... making some code break until columns are added.....

**Comment by a15eriho** [comment]
This now works as intended. and are most likely due to what HGustavs suggested or something alike.
