### ISSUE TITLE
Change markdown processing for javascript

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#2521]
~~Right now markdown processes line by line but it would be better to process an entire file instead.~~

Right now markdown processes an entire file instead of line by line. Would be better to have it line by line.

**Comment by a15elibr** [comment]
This issue should be split into smaller parts.

**Comment by d15johro** [comment]
it's the other way around. should process row for row.

**Comment by a15freku** [comment]
Yes you are right its the other way around

**Comment by a15elibr** [comment]
My mistake, got it wrong. Fixed now.

**Comment by a15freku** [comment]
Great!

**Comment by d15johro** [comment]
Where to test markdown processing related issues in LenaSYS? You can test markdown when adding a user in "/LenaSYS/DuggaSys/accessed.php", owever, this feature doesn't work at the moment... can you test markdown somewhere else?

**Comment by a15freku** [comment]
Yes in webbprogrammering PHP Example 2 in the descriptionbox. You have to edit the PHP_Ex2.txt file in the templates folder.

**Comment by d15johro** [comment]
issue is closed
