### ISSUE TITLE
Display the size of a file after it's been uploaded in the teachers view

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#2524]
After uploading a file, the size of the file should be displayed.

This issue is connected to #1835

**Comment by HGustavs** [comment]
We mean "after" uploading file, right, not "when" ??

**Comment by HGustavs** [comment]
Is size represented in the database? In that case a size column needs to be added, it is the best place to do this when we upload the file...

**Comment by a15herny** [comment]
Where exactally is this being implemented? Is it the diary functionality?

**Comment by a15elibr** [comment]
This is in the teachers view. Updated title and description for more clarity.
