### ISSUE TITLE
PHP example file not found

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#2527]
"File: PHP_Ex2.txt not found."
"File: PHP_Ex2.php not found."

Files exists and are located in /LenaSYS/DuggaSys/templates folder but the webpage can not find the files for some reason.

**Comment by HGustavs** [comment]
Im thinking not added to file list with uploaded files or permission problem?

More details.

Can other files be read?

**Comment by a15freku** [comment]
The filename is mentioned in the database, all files have group:www-data and g=rwx permissions. Still not working. Which "file list" do you mean?

**Comment by a15freku** [comment]
Fixed this by doing: "insert into fileLink (fileid, filename, kind, cid, isGlobal) values (2,"PHP_Ex2.txt",2 , 1, 1);"
It's the descriptionbox in php example 2, now we just need to do the same for the code box and all the other examples. I suggest to add this insert to testdata.sql until better solution is available. So we can focus on the markdown issues now that we can test the information in the boxes.

To learn more read the code on line 420 in codeviewerService.php

**Comment by a15elibr** [comment]
Closing issue since the issue has been resolved.
