### ISSUE TITLE
Error message when choosing template in examples

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#2531]
When trying to change template view in an example in a course, an error occurs:

> Error creating new bx: Duplicate entry '1-2' for key PRIMARY 
> Error creating new box: Duplicate entry '2-1' for key PRIMARY

It's some kind of error with the database.

**Comment by HGustavs** [comment]
Great work testing this functionality!

Does it work anyhow or does nothing happen?

If it gives an error but still works, it is less of an issue, but if it does not work, then we have a bigger problem.

**Comment by HGustavs** [comment]
Perhaps using __LINE__ to show which line the error happens on.

**Comment by a15elibr** [comment]
It does not work at all. The error message pops up and then it refreshes back to its original state. Going to discuss with group 3 if this is something that they can solve.

**Comment by b15linek** [comment]
The error message is fixed. It still does not update the template to show a different view. This needs to be fixed, see the new issue #2789 .
