### ISSUE TITLE
Following error occurs when going back to the course list

### ISSUE THREAD

**Issue by b15sarha** [HGustavs/LenaSYS#2534]
It would be nice to be able to go back to the course list. right now it doesn't redirect to the. When going to the 'List' in a e.g Webbprogrammering, and using 'Go back' arrow in the left corner of the page, it shows the following message:

Error updating entriesUnknown column 'studyProgram' in 'field list'

**Comment by b15sarha** [comment]
redirect to the list*

**Comment by HGustavs** [comment]
Seems to be an sql bug.... I would assume that the study program column is missing from the database in init_db.sql....

Dont remember which table this column was added to, but Im guessing student?

**Comment by b15sarha** [comment]
grupp4 fix this.
