### ISSUE TITLE
Missing arrows in calendar for editing dates

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2541]
In the section for editing duggor there is an option to set dates for deadlines. When swapping between months there are spans which are clickable to change the selected month. However, there are no arrows indication that the spans can be used for this. Refer to the picture.
![calendar](https://cloud.githubusercontent.com/assets/26705097/24503715/95c155de-1553-11e7-9928-8b502d72e69b.png)
Suggested solution is adding two icons with arrows that indicates that this functionality is supported.

**Comment by HGustavs** [comment]
Great idea, test to confirm that any solution does not break in other browsers or on mobile.

**Comment by a15tobli** [comment]
Merged in #2780
