### ISSUE TITLE
Print JSON from table in dugga

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#2544]
Print out JSON based on content in table (based on forms) instead of writing it by hand.

Related to #2545, #2546, #2547 and #2548

**Comment by HGustavs** [comment]
are we saying database table?

This is already stored in the database as a column value in json format.

We want to edit this data, in the client and store again in JSON format or have I misunderstood something?

**Comment by a15alica** [comment]
The idea was to add a kind of form, where you can choose what submission types you want for an assignment. When the form is filled out the data is presented in a table next to it (and you can add more submission ways). We use the data from the table (when you save and say you're finished with it) and create a JSON string from that. (So you don't have to do that manually.)

**Comment by a15alica** [comment]
This issue can be closed since the basic function has been added but in a different way. The main problem has therefor been solved. (See issue #2546)
