### ISSUE TITLE
Enable configured messages for dugga receipt

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2569]
Related to issue #2420 and #2558. With the current implementation from #2558, a text string in the receipt when a deadline is missed tells the student that they would have to wait until the next time that course runs. Refer to image below, line 157 in Shared/dugga.js
![2569](https://cloud.githubusercontent.com/assets/26705097/24547966/dd437544-1612-11e7-9f83-78671190af5b.JPG)

Suggested steps to this is by adding a configurable message as requested at #2420. With this configuration, the teachers would be able to set different messages to the receipt, depending on which course the dugga is a part of.

**Comment by HGustavs** [comment]
The data entry I would say is part of the dugga  json editor in among other issues #2548 ...
each dugga has a specific receipt message.

**Comment by a15tobli** [comment]
The idea was to implement an extra text field when editing a course, where a message can be set for missed deadlines in every dugga at the same time. E.g. in webbprogrammering, a message will be shown saying that no further reviewing of the duggor will be made until the next time the course runs. This allows the teachers to set a different message for every course if that is something to be desired. This would save a lot of time for the teachers by adding this message once, compared to adding it for every dugga in a course. 

The new field would set a string which will be saved to the courses table as a varchar in the database and will be shown on the receipt as a deadline is missed. However, when a dugga is submitted on time, the receipt will be displayed as per usual by using a selection which checks if the deadline is currently active.

With this suggestion we made the assumption that this implementation would not be related to the JSON dugga editor, as this will be an external issue for the course editor. The people working with JSON failed to see how this would be a relevant issue to the dugga editor. 
Do you want the message to be added to each dugga specific or would this solution be something that could work? Thoughts?

**Comment by a15tobli** [comment]
An input for a comments has been added in the dugga editor, issue #2615.
