### ISSUE TITLE
Bug in the Result-view filter menu

### ISSUE THREAD

**Issue by d15eriso** [HGustavs/LenaSYS#2571]
A bug that extends the header-border with a triangle every time you click on the border or open and close the filter menu.

This happens when you toggle all courses to show in the result-view and apply the filter and then toggle all courses off again. Then a new trangle will appear every time you open the filter-menu or when you click the triangle.

Related to this issue #2573

**Comment by d15eriso** [comment]
![image](https://cloud.githubusercontent.com/assets/26739514/25376293/e80c9b5a-29a3-11e7-8a01-fc3c30a511b2.png)
Here is a screenshot of the issue.

**Comment by a14phili** [comment]
Issue is solved. There is no bug with header-border anymore
