### ISSUE TITLE
The Result-view does not filter out duggas correctly

### ISSUE THREAD

**Issue by d15eriso** [HGustavs/LenaSYS#2573]
If all the duggas in the result-view are toggled to be shown and the filter is applied, and then all duggas are toggled off, the duggas are still shown in the list and should be filtered out.

This is somewhat related to this issue:
#2571

**Comment by a15wilhe** [comment]
I do not understand. I can not show all courses in the marking view. The marking view shows the results for one course. Can you do a print screen of the problem?

**Comment by a15wilhe** [comment]
I still cannot find the problem and no  other in my group. If you cannot show a printscreen of the problem I will start thinking of closeing the issue.

**Comment by d15eriso** [comment]
![image](https://cloud.githubusercontent.com/assets/26739514/25376045/1d5dd78e-29a3-11e7-95b5-87ec166d1079.png)
The different columns for each dugga are still visable even though no duggas are checked/selected.

**Comment by a15wilhe** [comment]
This seems to be working good now after the merge. 

![image](https://cloud.githubusercontent.com/assets/26706754/25473409/aeddf6ac-2b2f-11e7-8856-e3d8b0d8827b.png)

Was this what your were looking for? May I close this issue?

**Comment by d15eriso** [comment]
Yes this is now solved with the latest merge. It is related to this issue #3388. 

Im closing this now.
