### ISSUE TITLE
Edit Text In Objects

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#2586]
For the diagram editor we need the ability to write & manipulate text inside the objects. We want to be able to have several options on how to edit the appearance of the text inside objects.

Options
Change font
Change color
Change size

**Comment by a14pethu** [comment]
with object, do you mean diagram?

**Comment by b15matvi** [comment]
Pretty much everything, entities, attributes or classes. Currently they say only for example, attribute1, attribute 2 etc

**Comment by a14pethu** [comment]
this is done in  diagram.js right?

**Comment by b15matvi** [comment]
I think so, but not 100% sure

**Comment by b15matvi** [comment]
Issue resolved.
