### ISSUE TITLE
Fix the issue with resizing the class symbol.

### ISSUE THREAD

**Issue by b15matki** [HGustavs/LenaSYS#2588]
At this moment if you resize the class so that you move the top-left corner beneath and/or right the bottom right corner the class symbol brakes. When using the class symbol the user should be able to resize it according to the user's wish. To fix this issue some rules must be implemented to prevent errors. 

- If the top left corner is moved right of the top right corner the text disappears. 
- If the top right corner is moved beneath bottom left corner the symbol brakes.

**Comment by b15matki** [comment]
Example:

![example](https://cloud.githubusercontent.com/assets/26705132/24599580/1bae265e-1851-11e7-8b86-a8db0b4ff018.png)


1. The top right corner is to the left of the bottom left corner.
2. The top right corner is beneath and left of the bottom left corner.
3. The top right corner is beneath the bottom left corner.

**Comment by a15perbl** [comment]
@HGustavs 

A possible solution is to implement a rule making sure topLeft-bottomRight-middleDivider can't overlap.   Currently there is no way in the code to differentiate whether points belongs a class, attribute, line or an entity, therefore it's hard to enforce this rule.

Are we allowed to change the structure of the code to make this possible?

**Comment by HGustavs** [comment]
I would add code that sets the bottom right point a value that is top left plus some number e.g. 20px if it is smaller than top left + 20px .. much in the same way that we center for instance the attribute center points.

**Comment by a14davlo** [comment]
Issue resolved
