### ISSUE TITLE
Cannot delete 'Dugga'

### ISSUE THREAD

**Issue by b15sarha** [HGustavs/LenaSYS#2605]
Right now we are able to add a new 'dugga' but we cannot delete them. It should be possible to to be able to remove ones we don't need. 
This is in a course e.g Webbprogrammering > Tests

**Comment by HGustavs** [comment]
That is a good idea, if it has not yet been used (if some student has submitted an answer to it, it should not be possible to delete it)....

Some kind of a confirm dialog (are you sure you want to delete this ...) is also a good idead, we dont want this kind of stuff to be deleted by accident.

**Comment by a15elibr** [comment]
Changed this to group 1 by request.

**Comment by b15sarha** [comment]
Since we cannot choose which dugga to delete it is better to move the delete button to the "Edit dugga" option. By doing this one could simply delete the dugga the user want, by editing it. But right now I'm having problem deleting them. I'm unable to delete a dugga from the 'quiz' database even though I'm giving the right primary key. When pressing Delete button, i get the 'id' of the dugga i want to delete, but it is still there.

**Comment by HGustavs** [comment]
what is sent to server and what does it reply, look in console and check the returned json information?

Often an error is printed into the json data file....

If this is not the case one can start by writing for example (if $duggaid is the name of the variable containing the id of the dugga which is sent to the server)

$debug=$duggaid;

An alert should then appear with the correct id inside...

**Comment by a15elibr** [comment]
Partially, this issue has been resolved in pull request #2776.

**Comment by a15ramha** [comment]
Maybe you should close this issue and make a new one that describe the new problem.

**Comment by b15sarha** [comment]
Maybe i don't want to close my issue?
