### ISSUE TITLE
Add menu for changing diagram appearance

### ISSUE THREAD

**Issue by a15oskst** [HGustavs/LenaSYS#2609]
Create a menu that works like the menu for font settings in Microsoft Word.

Part of issue: #2473

**Comment by HGustavs** [comment]
Keeping with a material design-like theme I would put this in a dialog since such menus work poorly on mobile platforms.

**Comment by HGustavs** [comment]
Look at android general settings for my idea of what it could look like.

A long scrolling dialog with multiple settings, but the most important at the top.

**Comment by a15oskst** [comment]
@HGustavs 

The code and classes for the login dialog can be reused for this dialog menu, but it might look confusing since all of those classes etc. are named "loginSomething" should this code be rewritten to be more generic?

E.g: The class "loginBox" would be named "dialogBox" etc.

Or is it okay to use these classes etc. anyway?

**Comment by b15matvi** [comment]
Issue reolsved.
