### ISSUE TITLE
Add attribute for course table in database

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2616]
Add a varchar to the course table in the database. This varchar will be filled with the value from the text field in  issue #2615. This text will be shown on receipts of missed deadlines in every dugga in the course.
EDIT: The way of setting the receipt message have been changed from the course view to the dugga view, which makes it possible to assign a different message to each dugga. This makes it harder to set the same message for every dugga in a course however.

**Comment by a15tobli** [comment]
We changed the idea to add the comments from the course view to the dugga view. This makes it harder to set the same message to every dugga in a course. We are suggesting to implement a way to mark several duggas as groups, or set a message to all duggas. We are kind of stuck of which solution would be the best one, or if there is another solution we haven't been thinking on.

**Comment by a15ponja** [comment]
Closed due to issue cleanup, not necessary anymore.
