### ISSUE TITLE
Connect lines to diagram attributes, classes, entities

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#2619]
It should be possible to connect lines between attributes, entities and classes so that connections between them will show up. The lines should stay connected if you are trying to move the components that they are connected to.

**Comment by b15matvi** [comment]
Possible to look at the hardcoded example with the lines, they follow the attribute when moving around.

**Comment by a15chrau** [comment]
Having trouble to solve this issue

**Comment by a15chrau** [comment]
I still don't have any idea why points won't be added to top-, right-, bottom- or left-connector on newly created objects.

**Comment by a15chrau** [comment]
This problem was solved in another issue.

**Comment by a15perbl** [comment]
Closing issue.
