### ISSUE TITLE
Select multiple objects in the diagram

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#2620]
We would like to be able to select multiple objects at once and move them alltogether

**Comment by HGustavs** [comment]
I suggest selecting the points, and not the objects.... by having a selected attribute on each point we get object moving for "free" ....

The complicating factor is that we need to select all points in any object that is selected e.g. if we use box selection (by drawing a box to select any object inside the box) we must select both corners and the center point of an ER-entity even if only one corner is inside the selection box....

everything else will be handled automatically if we can group-move all selected points.

**Comment by b15matvi** [comment]
Issue resolved.
