### ISSUE TITLE
Functionality for a debug mode - Showing/Hiding console and X'es

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#2622]
If you try to draw a big class or entitiy for example over many other objects, the other objects X'es are still shown, despite the object isn't visible.

**Comment by HGustavs** [comment]
This is what we want.... we want to see all x-es while debugging so we know exactly where each point in the diagram is.....

However we need a "debug-mode" to show/hide debug stuff like the x-es and the custom console box.

**Comment by a14davlo** [comment]
Well done my boy!
