### ISSUE TITLE
Ask user to allow push-notifications

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2623]
Referring to issue #2504. Implement a way of requesting for permission to send push-notifications and recieve the push data.

**Comment by c14caran** [comment]
Hello.
I have made a pull request #2633 . This has implemented basic functionality of asking for push notification permissions.
It works in firefox using the ssl endpoint. Chrome support needs additional support from HiS IT.

**Comment by HGustavs** [comment]
It would be a good idea to outline exactly what additional support we are talking about...

**Comment by c14caran** [comment]
The additional support is outlined in the newly created issue #2767 

The reason for excluding it for the solution for this issue is because of the complexity involved.

**Comment by a15tobli** [comment]
Merged in #2633, closing issue.
