### ISSUE TITLE
Save data for push-notifications

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2626]
Referring to #2504. When a user has accepted the site to show push-notifications, implement a way of saving the information about the user, such as accepting notifications and the address of the web browser.

**Comment by HGustavs** [comment]
I suggest some kind of a generic "profile" or "settings" view. I think someone is already working on a settings/profile view? Dont know if in group 2 or some other group... 

I dont want 2 views with similar functionality.

**Comment by c14caran** [comment]
The button to activate push notifications exists in the profile view created by group 2. This change was made in issue #2623

**Comment by a15tobli** [comment]
Merged in #2272, closing issue.
