### ISSUE TITLE
Implement support for line-by-line parsing in php markdown-equivalent, i.e showdoc.php

### ISSUE THREAD

**Issue by a15ramha** [HGustavs/LenaSYS#2631]
Right now markdown processes an entire file instead of line by line. Would be better to have it line by line.

**Comment by a15elibr** [comment]
Just a clarification - the markdown process has one javascriptfile and one phpfile, this issue concerns the php part.

**Comment by HGustavs** [comment]
I suggest finishing the javascript one first, and then port it to php, this way we have a properly tested and working markdown system... which reduced the amount of testing needed by roughly half.

**Comment by a15elibr** [comment]
The javascript markdown has been finished.

**Comment by d15johro** [comment]
Parts of markdown in php should be line-by-line. For instance, blocks sorrounded by "@@@" or "&&&" should be as is and not be parsed line-by-line.

**Comment by a15ramha** [comment]
The javascript markdown has not been finished entirely because there are some bugs that need to be solved.

**Comment by a15wilhe** [comment]
closing this issue after fixed with pr #3379
