### ISSUE TITLE
Add warning icon to dugga receipt

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2639]
Related to #2572 and #2567. The intended warning icon to be used at dugga viewer will also be implemented at the receipt when submitting a dugga after the deadline has passed.

**Comment by HGustavs** [comment]
Mockup?

**Comment by a15filba** [comment]
![warningtriangleinduggareceipt](https://cloud.githubusercontent.com/assets/26706822/24650182/b34cdbd0-1929-11e7-8a80-09b3f17d3530.jpg)

Adds a warning icon in the receipe popup when submitting a dugga after the deadline has past.

**Comment by a15tobli** [comment]
Merged in #2785, closing issue.
