### ISSUE TITLE
Create "tolerance areas". [Sub issue of Figure]

### ISSUE THREAD

**Issue by b15matki** [HGustavs/LenaSYS#2645]
When drawing a figure it might be complicated to be precisely at the correct pixel. Therefore a tolerance area should be implemented so that a user might be able to complete a figure just by selecting the starting line's tolerance areas. Example:

![example2](https://cloud.githubusercontent.com/assets/26705132/24609695/0ab36a6e-187c-11e7-801d-e781d8484456.png)

The blue colour represents the figure, the red rings represents the tolerance areas. Root issue #2584.

**Comment by b15matvi** [comment]
issue resolved.
