### ISSUE TITLE
Add more sorting in Access view on students

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#2647]
There is no way to sort students in access view. Would be nice to be able to sort by age, added, name etc.

**Comment by HGustavs** [comment]
Do we mean sort or filter?

Is this the access view, the marking view or some other view we are talking about?

**Comment by a15elibr** [comment]
I mean sorting, my bad, will change title. This issue regards the access view.

**Comment by a15elibr** [comment]
Closing issue since it has been resolved.
