### ISSUE TITLE
implenting incremental alternatives to markdown syntax that follow markdown in markdown.js

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#2648]
At the moment markdown.js doesn't follow the universal syntax for markdown. If possible, implement (incrementally) alternatives for existing syntax that follow the universal syntax.

**Comment by a15elibr** [comment]
But, according to Markus and Henrik: it's okay to add syntax that is missing in our syntax, but there is no need to change already existing markdown, just to make it universal.

**Comment by HGustavs** [comment]
I would say to try to support both if possible, and breaking existing stuff as little as possible.

The main goal is to support "standard" markdown as much as possible.

Currently we have some kind of hybrid that supports similar markup but with non-standard markdown characters.

**Comment by HGustavs** [comment]
I would prioritize lists, first unordered, then ordered and then add tables... and then everything else....

I suggest making an issue for updating the current markdown example document that showcaqses all available lenasys markdown, that can be used for testing

**Comment by d15johro** [comment]
Issue regarding updates on current markdown examples showcasing availbable lenasys markdown now submitted.

**Comment by a15ramha** [comment]
The markdown.js and showdoc.php now supports lists and tables and the missing parts are the text type in tables that need to be changed to support this types according to markdown cheat sheet
![image](https://cloud.githubusercontent.com/assets/26706764/26191128/e5b076ae-3bac-11e7-98df-ed1a969e1511.png)

**Comment by a16silph** [comment]
I've been trying to figure out which of the supported markdown in markdown.js is still using nonstandard syntax. 

**So far i've found these issues:**

1. `Italic standard syntax should use either *text* or _text_, but in markdown.js it uses __text__ or ___text___.`

2. `Bold standard syntax should use either __text__ or **text**, but in markdown.js it uses **text** or ***text***.`

If these first two are changed fully to support the standard syntax, existing text on LenaSYS may change from being _italic_ to being **bold** or vice versa.

3. `Bold+Italic standard syntax should use either ___text___, ***text***, __*text*__ or **_text_**, but currently it uses ****text**** or ____text____.`

4. `Code Blocks standard syntax states that text that is indented either one tab or four spaces should be shown as code, but the current syntax ```code``` seems to be used in github at least.`

5. `Unordered lists can use + with a space as a list qualifier, but markdown.js does not allow that.`

6. `Nested lists do not work in markdown.js. In the standard syntax you can create nested lists by tabbing once before the list element, or with four spaces.`

7. `Ordered lists (1. ,2. etc...) turn into unordered lists in markdown.js.`

**Comment by HGustavs** [comment]
I think that nested lists work but some times slightly wrong ...

~~~
* Lägg till kod så att färgerna på bollen varierar enligt ett shack-rutigt mönster
* Lägg till parameter som styr hur mjuk/vass övergången mellan fälten blir, vid 0.0 skall övergångarna vara helt fyrkantiga, och vid 1.0 skall de vara mjuka.
|||http://wwwlab.iit.his.se/gush/Shaderprogrammering/Ass1StepVG.png|||

* hello
  * yello
* mello
  * snello
  * kello

# Krav på rapporten:

För Uppgift 1 så skall rapporten bestå av följande:

1. Ett urval av de viktigaste programkodsraderna och för respektive kodstycke en tillhörande beskrivning av hur man tänkt (ej en beskrivning av vad varje kodrad gör utan på högre abstraktionsnivå). 
2. En reflektion varför man har de parametrar som valts ut som inparametrar för shadern (vad som gör dem lämpliga som parametrar)
  1. foo
  2. pgoo
~~~

<img width="707" alt="Screenshot 2020-04-21 10 16 26" src="https://user-images.githubusercontent.com/6978801/79842534-3e8f7980-83b9-11ea-9cea-6d2499e8886a.png">

**Comment by HGustavs** [comment]
In that case it works but In other cases when I add images between the bullet points they do not close properly afaik.

I would not change how bold and italics work since that would alter old pages.

**Comment by HGustavs** [comment]
We only want fixes that add new features, or fix errors, we do not want to break existing pages.
