### ISSUE TITLE
Make install script handle language keyword SQL files

### ISSUE THREAD

**Issue by a15jorpa** [HGustavs/LenaSYS#2649]
Make the install script handle keyword files like test data or other reasonable way, currently these files seem to be unused.

**Comment by HGustavs** [comment]
One suggestion is to use some kind of input to the install script e.g. a list box for selecting languages to install.... and then only install the chosen languages....

one problem with installation of languages is that the lists are numbered sequentially....
e.g. first installed list is number 1 second installed list is number 2....

If installed by a script we can install both the language and the keywords at the same time by using the last inserted id ($dbh->lastInsertId();) to figure out which id to use for the keyword lists.
