### ISSUE TITLE
Tweak the styling of the JSON dugga submission editor form

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#2667]
The JSON dugga editor does not look good. Requires some makeup.

**Comment by HGustavs** [comment]
Screenshot(s) please. This is not something that can be resolved without asessing the extent of the problem visually.

**Comment by b15matol** [comment]
Hi! Of course! This is how it looks now. The issue primarily concerns the left part of the popup. The inputs needs to be aligned in a better way and also to blend in with the rest of the design of the page. I'm investigating the use of flex to arrange this (as you requested here: https://github.com/HGustavs/LenaSYS/issues/2665).

![skarmavbild 2017-04-04 kl 19 06 16](https://cloud.githubusercontent.com/assets/26713381/24669226/ea49d058-1969-11e7-8169-42ff3b808119.png)

**Comment by b15matol** [comment]
This was fixed in pull request #2790.
