### ISSUE TITLE
Change the default font-family to "Roboto" for a more  Material Design feel.

### ISSUE THREAD

**Issue by a15denbi** [HGustavs/LenaSYS#2674]
"Arial" is the standard font-family for Sectionlist-section. Would be better to change to Google's font "Roboto". 

Sectionlistc with Arial font:
<img width="749" alt="arial-old" src="https://cloud.githubusercontent.com/assets/26705156/24646124/1e9548be-191b-11e7-9786-bdb6b337672a.png">

Sectionlistc with Roboto font:
<img width="754" alt="roboto-new" src="https://cloud.githubusercontent.com/assets/26705156/24646130/24a86c54-191b-11e7-81ac-a2b8b7b0ae66.png">

Thoughts?

**Comment by HGustavs** [comment]
I prefer the slightly compacter arial.... especially on mobile we have problems fitting both the deadline dates and the names of the assignments on a single row....

btw.

The up-down arrows denote collapsibility?

I do not quite like that icon... it signals drag-ability to me and not collapsibility.... 

I suggest a single up arrow for collapsed state and a single up arrow for collapsible state.

**Comment by a15mikla** [comment]
I will work on the arrows. I'm guessing there should be different arrows depending on if the sections is collapsed or not? @HGustavs

**Comment by a15freed** [comment]
Closing this issue since the font should be the slightly compacter arial
