### ISSUE TITLE
Update lenasys-markdown.txt.

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#2676]
Update the current markdown example document that showcases all available lenasys markdown, that can be used for testing.

**Comment by HGustavs** [comment]
I dont remember where it is but I know that previous years had such a document.... so it is probably here somewhere in the repository...

**Comment by a15elibr** [comment]
Another issue already existed with the same content. There was some additional comments from the other issue, they should now be included in this issue. 
>Also make sure that the JS and PHP feature lists match up.
>Check both JS and PHP

**Comment by A15cecal** [comment]
The PHP file is located in /DuggaSys/showdoc.php

**Comment by a15elibr** [comment]
Closing issue since it has been resolved.
