### ISSUE TITLE
Attribute Options Henrik feedback

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2677]
[EDIT] We'll not directly work with this issue, this is here for us to read feedback from Henrik. [EDIT]

So the task is to create an editor tool that can draw all kinds of diagrams. This sub issue is about creating a function & button that lets you mark some text and make it into a primary key on your diagram.

Whenever you make an entity always has a primary key attribute that's distinguished with an underline. We need this.

#2576 root issue

**Comment by HGustavs** [comment]
I think this is a good case for making a dialog...

for example when double clicking an attribute we come to a dialog that allows us to set things such as key yes/no weak yes/no color / data type if one wants to go into that kind of detail ... or compund attribute yes/no etc etc.

**Comment by a14davlo** [comment]
The idea I had in mind is to create button. So you click on the text inside a box and then you have that piece of text selected and then up at the menu you had a button that gives the text an underline, making it like a primary key.

**Comment by HGustavs** [comment]
... a much simpler solution is to have all attributes default to "vanilla" and any other property such as weak, computed, compound etc is done by double clicking and editing dropdowns for properties in a dialog that appears...

This allows us to easily add new properties when we come up with new options...

**Comment by HGustavs** [comment]
also - much less fiddly on mobile.

**Comment by HGustavs** [comment]
![screenshot 2017-04-04 10 36 13](https://cloud.githubusercontent.com/assets/6978801/24648485/0bf1c90e-1924-11e7-8be3-7feab94bc707.png)

**Comment by HGustavs** [comment]
Ugly mockup but I think it is possible to understand from the context.

**Comment by a14davlo** [comment]
Yeah I've understood and like your suggestion. I've created a new issue for this matter.

However, it's a technically advanced issue to have a dropdown menu appear from double-clicking on text, boxes and bubbles.

**Comment by b16andka** [comment]
This seems to have been fixed. There is already an option to change attribute types. Therefore the issue will be closed.
