### ISSUE TITLE
Update metadata for UTF-encoding 

### ISSUE THREAD

**Issue by a15denbi** [HGustavs/LenaSYS#2685]
Update metadata for UTF-encoding in order to allow Swedish characters to display correct charset "å,ä,ö" etc. 

text issue:
<img width="304" alt="skarmavbild 2017-04-04 kl 11 11 23" src="https://cloud.githubusercontent.com/assets/26705156/24649473/79e23860-1927-11e7-984e-83707a83e9da.png">

Edit: Maybe a server issue? UTF-8 needs to be assign from both sides.

**Comment by HGustavs** [comment]
There are so many steps here.

I prefer storing everything in the database using htmlentities e.g. "& ouml;"

This way it does not matter if it is delivered to client in utf-8 form....

make sure that the data in the database is stored using htmlentities form.... if not, that is probably part of the problem.

**Comment by A15cecal** [comment]
@HGustavs  @a15tobli Shouldn't this be closed? Seems like someone fixed this issue already.

**Comment by HGustavs** [comment]
I think it has been solved.

**Comment by A15cecal** [comment]
This has been solved. Closing issue.
