### ISSUE TITLE
Fix spacing problems on mobile UI 

### ISSUE THREAD

**Issue by a15denbi** [HGustavs/LenaSYS#2688]
Update the design on mobile & tablet UI in order to fix the spacing issues on smaller displays.

**Comment by HGustavs** [comment]
Screenshot plz.

This seems like a big decision that can not be resolved without at least one example of what those spacing issues are.

**Comment by a18kaswi** [comment]
If denbi didnt supply screenshot 2017 I doubt we can get it in 2020, C L O S I N G
