### ISSUE TITLE
Functionality for double clicking on an attribute/entity

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#2694]
In order to solve the dropdown menu we need the functionality for double clicking on an object.

Subissue of #2684

**Comment by HGustavs** [comment]
If there are any other suggestions for how to trigger the editing dialog, I am flexible.....

it has to be a gesture that is natural both on mobile and on computers....

e.g. right click is not suitable since it does not work well on mobile....

**Comment by a14davlo** [comment]
I have designed a structure on the issues to make it cleaner, don't worry, this issue is still here, in fact I edited the issue this one relates to be this exact one.
