### ISSUE TITLE
Debug Mode variable problem

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2709]
Need to fix a variablename that's wrong.

Take a look at ghostingvrosses, it seems to be the problem.

#2622 root issue

**Comment by a15gunfu** [comment]
What is the problem caused by the variable name?

**Comment by a14davlo** [comment]
The variablename should be named ghostingcrosses, there's a v that should be replaced with a k.

ghostingcrosses is a variable named used multiple times in the code.

**Comment by b15matvi** [comment]
Issue resolved.
