### ISSUE TITLE
Faulty SQL-query in resultedservice.php

### ISSUE THREAD

**Issue by a15eriho** [HGustavs/LenaSYS#2711]
A faulty SQL-query in the resultedservice.php makes the result page throw an error when loading if the mysql server is of a later version. This is due to stricter control of SQL-queries in later versions.

This can be fixed by reconfigure the mysql-service (not a good option), or by modifying the SQL-query (a good option to secure the LenaSYS-system for a more compatible future)

**Comment by HGustavs** [comment]
In the interest of documentation write the error and describe the problem here as a comment.

**Comment by a15eriho** [comment]
The faulty query was in file 'resultedservice.php':
$query = $pdo->prepare("SELECT listentries.*,quizFile,variant.vid as qvariant FROM listentries LEFT JOIN quiz ON  listentries.link=quiz.id LEFT JOIN variant ON quiz.id=variant.quizID WHERE listentries.cid=:cid and listentries.vers=:vers and (listentries.kind=3 or listentries.kind=4) GROUP BY lid ORDER BY pos;");

The error produced were (database name was "grupp03"):

"Error retreiving moments and duggas. (row 276) 0 row(s) were found. Error code: Expression #16 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'grupp03.variant.vid' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"

Fix was to modify to **COUNT(**variant.vid**)**. Previous version of mysql seems to not be as strict with this.
