### ISSUE TITLE
Create A Dropdown Menu That Appears

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2715]
This is a sub issue that will later be combined with another sub issue about double-clicking any object in the editor tool.

Design & create the structure of the dropdown menu, it will later be filled with multiple options on how to alter a selected object.

#2576 root issue

**Comment by b15matvi** [comment]
Possible to look at how the appearance menu created by issue #2732 for a base.

**Comment by a14davlo** [comment]
We kinda did this already in #2732
