### ISSUE TITLE
Attribute Dropdown Option - Primary Key

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2719]
In the dropdown menu we'll create for the attribute options, primary key attribute is going to be one of them.

For a piece of text to be distinguished as a primary key this will create an underline underneath the word(s).

#2576 root issue

**Comment by a14pethu** [comment]
for some reason my function does not work. no matter what i try the text doen't want to print a underline underneath the text.

function setType(form){
	
	if(document.getElementById('attributeType').value == 'Primary key')
	{    
		var name_lenght = diagram[selobj].name.length;
		var underline = '-';
		for(i = 0; i < name_lenght-1; i++){
			underline = underline + "-";
		}
		 		
		diagram[selobj].name = diagram[selobj].name + "\n" + underline;
	}	
	 updategfx();
}

**Comment by a14pethu** [comment]
@HGustavs

I can't seem to get it to work.

if(this.key_type == 'Primary key'){
			var linelenght = ctx.measureText(this.name).width;
			ctx.beginPath(1);
			ctx.moveTo(x1+((x2-x1)*0.5), y1+(0.85*this.textsize);
			ctx.lineTo(x1+((x2-x1)*0.5), y1+(0.85*this.textsize)+10 ;
			ctx.lineTo(x1+((x2-x1)*0.5)+linelenght, y1+(0.85*this.textsize)+10;
			ctx.strokeStyle = "#000";
			ctx.stroke();
		}

**Comment by b15matvi** [comment]
Issue resolved.
