### ISSUE TITLE
parsing bug regarding in markdown requires markupfile to end with blank line

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#2723]
Function parseLineByLine() in "/Shared/markdown.js" currently parse every line until the current line has no return ("\n"), like this: "while(currentLineFeed != -1){}". This requires you to end the markup-file (template) with a blank new line, else it wont treat the last line in the markup-file as a current line (it will be ignored when parsing). However, the remainingLines-variable will fetch it.

**Comment by a15ramha** [comment]
This issue has been solved.
