### ISSUE TITLE
Zoom in and out in a diagram

### ISSUE THREAD

**Issue by a15admsa** [HGustavs/LenaSYS#2735]
Making it possible to zoom in and out with buttons. These buttons should zoom in and out in the Canvas-element, not the whole site. 

Root issue is #2472

**Comment by b15matvi** [comment]
We want the zoom in button as a toggle, when you click it you get a magnifiyng glass effect similar to that of paints zoom feature. You will continue to zoom when you click until you untoggle the button.

**Comment by a15admsa** [comment]
Issue is now fixed!
