### ISSUE TITLE
Create A Menu To Edit Texts In Objects

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2739]
Design a menu with the capacity to be filled with several various options on how to change the appearance of text inside the objects. We want to be able to change the size, the font and even the color of the text inside objects.

This menu should also have a text box where you write the text you want to appear in the object. Once you're done, you click a confirm button and the text appears inside the object.

First, design a menu.
#2586 root issue

**Comment by b15matvi** [comment]
Issue resolved.
