### ISSUE TITLE
Attribute Dropdown Option - Foreign Key

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2743]
Create a menuoption inside the double-click dropdown menu where you can turn an attribute into looking like a foreign key. To make an attribute to look like a foreign key in ER it needs an underline that's striped like "_ _ _ _ _ _".

To make sure there's no confusion, the difference between this one and the derived attribute issue is that the entire surface of the derived attribute is striped with "- - - - -" and this one creates an underline beneath a text with "_ _ _ _ _".

#2576 root issue

**Comment by b15matvi** [comment]
As we cannot assign attributes in the diagram, this issue is redundant. Foreign keys are represented in the relationstable.
