### ISSUE TITLE
Make notifications work in chrome

### ISSUE THREAD

**Issue by c14caran** [HGustavs/LenaSYS#2767]
Notifications are currently only supported on firefox and not chrome. This is due to two reasons.

1. https needs to have a valid server key, the current key on the testserver is not trusted.
2. VAPID authentication needs to be added.

A good resource on how to implement VAPID authentication can be found on the following website:
https://developers.google.com/web/updates/2016/07/web-push-interop-wins

The location on where to save these application keys needs to be considered. They should not be public. This is because with the private key attackers can send messages posing as LenaSYS to the users (note: only if the database is also compromised, as the attacker alsoneed the endpoint (basically an address to the phone for a specific website)).

**Comment by c14caran** [comment]
The https part is out of the scope for this issue. The installation and configuration of a web server is not something that should be addressed in this github repository. A simple notice should be added to the readme that ssl needs to be configured and working.

**Comment by a15tobli** [comment]
Solved in @2881 and @3173, closing issue.
