### ISSUE TITLE
Add sorting to file lists in teachers view

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#2775]
Implement a way of sorting the files in the teachers view, by name, date etc. Currently however, the files does not have any date or size displayed to them. Therefor, ideally, issue #2525 and #2524 should be solved first, since they will implement date & file size.

**Comment by a15elibr** [comment]
Some sorting code is already available in marking view, this code can be re-used.

**Comment by a15freku** [comment]
The problem is solved.
