### ISSUE TITLE
Saving playlink in php examples does not work

### ISSUE THREAD

**Issue by A15cecal** [HGustavs/LenaSYS#2784]
This is relevant to codeviewer.

If you check the console you'll see that the link gets posted but nothing happens...

This is a database issue in codeviewerService.php ...

![skarmklipp](https://cloud.githubusercontent.com/assets/26705134/24707582/7893d804-1a14-11e7-87ce-5b9c09998eeb.JPG)

**Comment by a15elibr** [comment]
Find out what exactly is happening, and we will decide further after that.

**Comment by a15freku** [comment]
This is now fixed @a15oscwe knows more about this
