### ISSUE TITLE
Codeviewer does not update template when new one is picked.

### ISSUE THREAD

**Issue by b15linek** [HGustavs/LenaSYS#2789]
When you pick a new template in codeviewer.php it won't change the view. 
If you have two windows and change to three for example it does not change, just refreshes the page with the same template.

**Comment by HGustavs** [comment]
Has this been fixed is there a link that I can use to test this fix out??

**Comment by b15linek** [comment]
This is not fixed. Can not find the problem that causes this... Will look at a earlier version of master, I think it worked in an earlier release.

**Comment by a17robes** [comment]
This doesn't seem to be an issue anymore, tested all templates and each one works. When changing template you use the "Choose template" icon in the header. Should we close this issue? @a17alevu

**Comment by a17alevu** [comment]
I will close this since it seems like it is not an issue anymore.
