### ISSUE TITLE
Double-Click Menu Options "Ok" And "Cancel"

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2791]
For the small menu to feel complete we'll need options where you're able to confirm the edits you've selected and the text you've written.

We'll need an OK button and a CANCEL button. They're self-explanatory.

**Comment by b15matki** [comment]
Added the buttons and fixed the buttons functionalities. Also made the window adapt to the object the user selected.

**Comment by b15matvi** [comment]
Issue resolved.
