### ISSUE TITLE
Participation list (class list) for seminars, moments and duggas.

### ISSUE THREAD

**Issue by a15eriho** [HGustavs/LenaSYS#2796]
A list of possible participants (probably course participant list), to be able to check of who has been at a seminar, or active at the seminar/moment/dugga.

The mockup below shows how we imagine it can be implemented.

* When pressing the Cogwheel, there will be an option to connect a participant list to the moment. (This is not shown in the mockup below). A simple tickbox will probably be sufficient.
* When the option is checked, there will be an extra icon next to the cogwheel where the teacher can control the participants of the group. Next to this icon i.e. is a "4/10" to indicate that 4 out of ten participants were on this particular moment. #1842 is related to number of participants.
* In the participant list view, there will be a list of students registered to the course, and the teacher can tick off those that they want. This list will be fetched from the database.
* An additional pen icon next to the participant will be used to make a comment on the participant if needed. How this comment is shown is up to debate, maybe a static text-box behind the participant (will take real estate on screen and might not be preferable for mobile view) or a simple "!" can be sufficient to mark that a comment has been made, that will show the comment on hover. This design here depends a bit on how much the comment function will be used.

![participant-list](https://cloud.githubusercontent.com/assets/26706624/24710621/fdedf3be-1a1d-11e7-97c2-72d6dfe9ff74.png)

A separate issue will be created for group participation.

**Comment by a15eriho** [comment]
Design requests from the customer:

There should be a additional button at top in the sectioned view menu which is labeled something that associates it with groups/participants. This new view should resemble the teachers result-view, where each course participant should be a row, and each moment/seminar etc. should be in columns.

An option for selecting the student as active in the seminar, and selecting which group the student should belong to.

This issue is now related to #2441, and should be in the same view as described above.

**Comment by a15ponja** [comment]
Issues 3900 and 3901 have been made to replace this one.

**Comment by a15eriho** [comment]
Just modified the comment above to actually point to the issues referred to by the comment. (added the # in front)
