### ISSUE TITLE
Add a "current course version" column in the access service

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#2799]
When listing the users who has access to a course I would like a column that lists the course version that each user has as their active version.

In the edit user dialog I would like to be able to change this. Preferably by selecting from a dropdown filled with available course versions.

**Comment by a15andau** [comment]
![screenshot 2017-04-07 kl 13 28 28](https://cloud.githubusercontent.com/assets/26709847/24798413/1ffd8fe0-1b96-11e7-8f0f-bd5a267d3db1.png)

What shall we do about null values in columns? Leave the or maybe change it to blank or N/A or something else @HGustavs ?
