### ISSUE TITLE
Width issue on list elements?

### ISSUE THREAD

**Issue by a15denbi** [HGustavs/LenaSYS#2800]
Is this behaviour okay with not displaying the full name when the name is longer than the width of the container? 

<img width="1277" alt="skarmavbild 2017-04-06 kl 09 01 21" src="https://cloud.githubusercontent.com/assets/26705156/24741806/d95d52f8-1aa7-11e7-9b65-4f66731c46a8.png">

@HGustavs , @a97marbr

**Comment by a18kaswi** [comment]
Customers didnt answer 3 years ago, why would this stil be relevant in an environment such as this we are working in. 

The debate is wether to check for new bugs or confirm old ones. (as for now.)

**Comment by a97marbr** [comment]
I have no problem with cropping the names to save space ... but if hovering over a name the title attribute should give me the full name ...
