### ISSUE TITLE
Continues bug in sub-listing in markdown.js

### ISSUE THREAD

**Issue by a15ramha** [HGustavs/LenaSYS#2808]
Sub-listing only handles one "backwards-indentation" at the time, e.g. the following will work:

* item 1
    * item 2
* item 3

But this doesn't:

* item 1
    * item 2
        * item 4
* item 4

**Comment by b15sarha** [comment]
Please do not assign yourself to the issues, this is done by our issue master. 
kind regards/sarbast

**Comment by a15ramha** [comment]
This issue is fixed!
