### ISSUE TITLE
Changes to the login box

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2810]
We are looking at implementing some fixes for the login box. Some of the interaction does not work, which will be implemented and validation of the form input will be added. The "Forgot password" button has been fixed, where 2 new forms are added. The first one finds the user Security questions for reseting password have been added, which will also be implemented further.
![login](https://cloud.githubusercontent.com/assets/26705097/24744939/0d9e6c94-1ab4-11e7-8ac1-2f749389ce93.PNG)

Suggested list of functionality to be added:
#2804 - Always open the login box at the login view - SOLVED
#2815 - Create error feedback when wrong input is inserted. - SOLVED
#2820 - Create a barrier which sets a maximum amount of failed inputs at username. (forgot password) SOLVED
#2830 - "Check user" button sometimes breaks when - SOLVED
#2822 - Create a barrier which sets a maximum amount of failed inputs at security challenge answer. SOLVED
- Create some way of denying further inputs when the barrier is reached, e.g. a timeout or captcha.
#2969 - Create code that handles problems if the user does not have a security question. SOLVED
#2967 - Create code that denies password changing for teacher accounts. SOLVED
#2937 - Reset the forms which are linked to password reset when the user closes the window - SOLVED
#920 - Fix the "remember me" button so it works. SOLVED(We removed it, the browers now adds this support)
#3023 - Change requestedpasswordchange value in database when password change is requested SOLVED
#3024 - Mark students with requested password change SOLVED

**Comment by a15alica** [comment]
Another thing that might be related to this too, is amount of failed login attempts, not just for the security question. So both controlling how many attempts and then some kind of barrier (like a timeout) when a limit has been reached.

**Comment by a15tobli** [comment]
Good catch, added a separate issue for username.

**Comment by a15alica** [comment]
If you write a username and/or security question answer when applying for a new password and then changing to a different view (login, username input for new password or answer for security question) the input in the fields are still there the next time you go back. This has to be changed so that the form is reset every time you go to a different part.

**Comment by a16seplu** [comment]
solved remaining parts
