### ISSUE TITLE
Support for groups in seminars, duggas, and moments. Possibly a generic widget.

### ISSUE THREAD

**Issue by a15eriho** [HGustavs/LenaSYS#2812]
A way to divide participants into groups, and to manage groups in moments/duggas/seminars.

The mockup shows a possibly way of this to be implemented.

* An icon on the activity bar, next to the cogwheel, shows if there is any groups involved in the moment.
* Clicking this icon will bring up the group management view/overlay.
* A list of students enrolled in the course will be shown in the list to the left.
* Groups can be formed by dragging the participants to respective group. The participants can be moved around freely between groups and the participant-list.
* Groups are formed dynamic if a new member is dragged to the new group section (the empty group with a grey name and with a + sign in it).
* Groups can be deleted with the X sign in the top right corner of the group.
* Any participants that are not in a group will be shown at the top of the list with black color, to be able to see easily which participants that does not have a group.
* Group members will be shown with at the bottom of the participant list, with a number next to them to indicate to which group they belong. They will have another color than the group-less participants.

![group-list](https://cloud.githubusercontent.com/assets/26706624/24745544/5b3e8860-1ab6-11e7-834c-f1402e5c2286.png)

* Possible additions may include naming the groups, comments on the groups, comments on members on the group (like assignments for group leader etc)...

**Comment by a15eriho** [comment]
Possible duplicate of #2441

**Comment by b15matol** [comment]
Hi a15eriho and all concerned. I think your ideas on this looks great. A suggestion from me is that the assigning of people to groups is done on a separate new page (i think that is what your mockup depicts primarily). 

But that the assigning of groups to a dugga is done on the page sectioned.php which is displayed in the mockup. That would make the assigning of groups to a dugga a bit more simpler. What do you think?
