### ISSUE TITLE
Remove The X's That Appear From Connecting Lines

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2813]
When you connect diagrams with lines, X's appear at the beginning and end of the lines, this issue is about removing them so that it looks better.

#2619 root issue

**Comment by HGustavs** [comment]
Is this not just a question of removing the debug mode?

**Comment by a15chrau** [comment]
It is not. When removing one of the attributes in the example program one of the bordering X:s, in the class it is connected to, should be removed.

**Comment by HGustavs** [comment]
When we say "removed" we mean hidden.

If something is "deleted" from ther list it is not possible to trust the index values.

**Comment by a15chrau** [comment]
Alright so:
They're only meant to be deleted from an object's connector- top, right, bottom or left, removed from the points array.

**Comment by a15perbl** [comment]
Issue resolved._
