### ISSUE TITLE
Remove checkbox options, align ok and cancel buttons

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#2835]
We don't currently need the checkboxes in attribute and entity. Remove them and make sure the OK and Cancel buttons are aligned correctly at the bottom.

**Comment by b15matki** [comment]
Removed checkboxes and the cancel button due to it being redundant.
Added CSS to better structure to the attribute, entity and class-windows.

**Comment by a14davlo** [comment]
This issue was solved days ago.
