### ISSUE TITLE
Make "Dugga Stat" popup closable and movable

### ISSUE THREAD

**Issue by a15matab** [HGustavs/LenaSYS#2855]
When you open the "fist-view" and look at the results of a dugga a popup obstructs some of the information and is not closable. It's also not movable by dragging the header of it which other popups are.

![screenshot from 2017-04-07 10-33-07](https://cloud.githubusercontent.com/assets/26706785/24792168/2edd78e0-1b7d-11e7-8c3d-0b469a9b1d59.png)

**Comment by a15elibr** [comment]
Just a friendly reminder, do not self assign yourself on any issues. All created issues should be run by me. /issuemaster1337

**Comment by a15matab** [comment]
Yep, sorry. ;p
