### ISSUE TITLE
Code cleanup in resulted.js

### ISSUE THREAD

**Issue by d15eriso** [HGustavs/LenaSYS#2859]
Fix code formatting in resulted.js to make it more consistent and easier to understand. **Attention:** This issue has been changed.

**Comment by b15matvi** [comment]
Jobba hårdare!

**Comment by d15eriso** [comment]
This changes will probably cause a conflict during the weekly merge so the issue will be changed to smaller cleanup that does not effect the whole file, as stated in the pull request.
