### ISSUE TITLE
Create a 404-page

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#2860]
Currently the 404-page is just the standard boring one. Would be nice to have a LenaSYS-specific 404page. Doesnt have to be anything too fancy

**Comment by a15elibr** [comment]
This is also a security issue, since it is easy to find a directory list where you can see all files on the server. Eg. browsing to [http://webblabb.iit.his.se:8080/grupp1](url) while give you a directory file tree. Instead, a 404-page should be shown

**Comment by HGustavs** [comment]
we should make file-name guessing as hard as possible.

**Comment by a15herny** [comment]
Cannot find .htaccess or apache2 /var/www (sudo find -name *apache2*). I'll test to add an .htaccess to my own folder.

**Comment by a15jorpa** [comment]
@a15herny  Please make the error file more useable. Currently it only shows a blank page which makes testing needlessly difficult. Please use proper language, not "Filez". The <h1> tag is visible as a tag in the tab name which makes the message harder to quickly understand.

**Comment by a15ramha** [comment]
Is this issue still present or would you like me to delete it?

**Comment by a15herny** [comment]
Yes I think that is okay, maybe ask @a15elibr as well.

**Comment by a15elibr** [comment]
Issue has been resolved, closing issue.
