### ISSUE TITLE
Bugs in section-editor, adds extra cog-wheel

### ISSUE THREAD

**Issue by a15mikla** [HGustavs/LenaSYS#2909]
In the section-editor there is a bug where every dugga gets 2 cogwheels. Also, when you click the cog-wheel the section collapses.

**Comment by a15mikla** [comment]
The 2 cog-wheels were supposed to be there... But I'm attempting a solution to fix the problem with the section collapsing.

**Comment by HGustavs** [comment]
I confirm this, when I tested the system I also got double cog wheels.

**Comment by a15mikla** [comment]
One of the cog-wheels is supposed to be another icon, for participants. But this is being fixed in issue #2796 @HGustavs
