### ISSUE TITLE
Diagram Engine Functionality - Json Text Document

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2920]
The diagram engine should work mostly like the engine from google docs.

Each instance is represented as a json text document.

#2454 root issue

**Comment by c14joalu** [comment]
@HGustavs , I tried some on this issue, but i keep getting the problem that if you use JSON.stringify, on for example diagram to retain the state, it only gets a shallow version i.e. it does not reference it functions anymore. wouldn't this issue be alot easier to solve if you use a deep clone version of the arrays, and then convert them to string and be able to make a file of that string?

**Comment by c14joalu** [comment]
I found a way to make it possible to go from a stringify JSON to the array put in before, making it possible to save and load states from JSON text files, disregard my previous comment.

**Comment by a14davlo** [comment]
Well done!
