### ISSUE TITLE
Diagram Engine Functionality - Instance Should Not Trigger From Minor Change

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2923]
The diagram engine should work mostly like the engine from google docs.

Not every minor change triggers an instance (moving an element or resizing it should not trigger changes).

#2454 root issue

**Comment by HGustavs** [comment]
But after a time lets say 10 seconds (configurable?) or more we should trigger the change or if we move many objects at the same time.

**Comment by b15matki** [comment]
Issue already resolved. Closing issue.
