### ISSUE TITLE
A line that separates 'Duggor' would be nice 

### ISSUE THREAD

**Issue by b15sarha** [HGustavs/LenaSYS#2928]
Right now when adding 'Duggor' they just end up one after another. A line between each of them would be nice, just a design matter.

**Comment by HGustavs** [comment]
Mockup.

**Comment by A15cecal** [comment]
![mockup](https://cloud.githubusercontent.com/assets/26705134/24947341/b951a6e4-1f66-11e7-8edd-e535ac626f11.jpg)
Made a mockup with a slightly different solution than suggested. Think it's better to stick with one design and not switch between them.

**Comment by A15cecal** [comment]
@HGustavs @a15freku What should we do with this issue?

**Comment by HGustavs** [comment]
Where are the individual variants added, below each item in the list?

**Comment by A15cecal** [comment]
@HGustavs Yes

**Comment by A15cecal** [comment]
@HGustavs Yes. So what should we do?

**Comment by A15cecal** [comment]
This has been fixed. Closing.
