### ISSUE TITLE
Diagram Engine Functionality - Complete Document String

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#2930]
The diagram engine should work mostly like the engine from google docs.

If the hash is not identical with the local hash, the complete document string is retrieved.

So the complete document string needs to be retrieved if the hash is not identical with the local hash. This issue will be dependent on Diagram Engine Functionality - Unique Hash #2917 since that issue creates the unique hashes.

#2454 root issue

**Comment by HGustavs** [comment]
The hash does not have to be completely unique e.g. adding code of all characters one by one is enough, since we only want to compare against previous document, as it IMHO is very unlikely that an incremental change from the same starting point adds upp to the same number ...

**Comment by a14pethu** [comment]
@HGustavs 

i can't seem to get the array of the diagram to copy to another array, in order to store it on localstorage, and retrive it later.

**Comment by b15matvi** [comment]
Issue resolved.
