### ISSUE TITLE
Add some padding between logo and courses 

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#2932]
It would look so much better with a little padding between LenaSYS-logo, the line and the courses. Picture to illustrate: 
![kekeke](https://cloud.githubusercontent.com/assets/26704655/24851147/e9e407ce-1dd2-11e7-95ec-1f07dfb6ecdf.png)

The added padding should be where the red lines are.

**Comment by HGustavs** [comment]
Yes a little more but not an ocean of space
