### ISSUE TITLE
Add responsiveness for the menu in the section editor

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2936]
This menu is not very responsive, this is very obvious at lower resolutions, such as using a mobile device. This problem is related to the creation of student groups, as we will create an additional button in this menu, issue #2934. Suggest fix is using media queries and a hamburger menu to make all links appear on the page.

**Comment by HGustavs** [comment]
Not necessarily responsiveness... by adding icons instead of buttons this is resolved.

**Comment by a15tobli** [comment]
We have put this issue on hold as another group is working on adding icons for this menu.

**Comment by a15freed** [comment]
related to #1823

**Comment by a15tobli** [comment]
Group 3 solved this issue in #3318, closing issue.
