### ISSUE TITLE
Edit grouped.js to use the dugga.js AJAXService to get some content into the grouped.php page

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#2943]
A cumbersome but interesting task. 

The grouped.js file should use the Ajax service to fill the grouped.php page with the existing groups.

**Comment by HGustavs** [comment]
It is a strict rule that nearly no php appears in the code except for services... the only eceptions as far as I know is the login/logout functionality and file upload.

**Comment by b15matol** [comment]
Hello, 

The idea is that this will look and behave similar to the current resulted.php page, with a .js and a service.php file. 

However, this issue is too large. Closing it and splitting it up in smaller ones.
