### ISSUE TITLE
[Course version] and [New Item] in sectioned need redesign.

### ISSUE THREAD

**Issue by a15eriho** [HGustavs/LenaSYS#2951]
In the section editor, the icons created in the issue #1823 to replace the current menu, will make the current buttons disappear. This will make the [course version]-selection and the [New Item]-button alone in this row, and they should be redesigned to fit the new button placement somehow. Preferably without having to keep the now almost empty row.

![menu](https://cloud.githubusercontent.com/assets/26706624/24859268/23e2f4c2-1df0-11e7-8e8b-b0687429d1d9.jpg)

**Comment by HGustavs** [comment]
I see two main variants
* Moving the version dropdown to the top menu
* Moving the version dialog to just to the left of the course name.

From my perspective it is a good idea to have it close to the name of the course, and the navigation bar will be large enough without also adding the version dropdown.

**Comment by HGustavs** [comment]
Icon suggestions and mockups:

* Tests could have the already used "fist" icon.
* I like a torso-and-key look for the permission icon, something like this icon but with the man symbol from the login logout icon we already use... https://www.iconfinder.com/icons/176151/access_authorization_authorize_lock_password_permissions_security_icon#size=128 or something like this icon https://www.uspto.gov/sites/default/files/documents/Introduction%20to%20Financial%20Manager%20User%20Permissions.pdf
* A stylized clipboard probably fits well for the tests button https://www.google.com/search?q=clipboard+icon&ie=utf-8&oe=utf-8
* Files already have a wall-socket-plug icon that we can use

I have no suggestions for
* Edit version
* New Version

**Comment by a16konka** [comment]
This issue has been handled in a different issue, therefore this issue is no longer relevant.
