### ISSUE TITLE
Student view of group assignment

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2963]
Im thinking that each seminar is a dugga, we have a setting for "group or else" for each section editor item, something like a dropdown, Normal, Group, Seminar, Group Seminar

In the section editor if group or group seminar has been set we clearly show the assigned group number in the section editor heading.

Mockup anyone?

**Comment by HGustavs** [comment]
Conflicting views and/or suggestions... are also welcome

**Comment by a15alica** [comment]
@HGustavs  What would be the difference between a normal dugga and a seminar dugga?

I am not sure of where you want the group number. Can students be places in different groups in the same course or are the same groups used for all parts in a course? Would the group number then be placed in the header of the course page (the section editor), in the header of a certain part of a course, on the line for a specific dugga or on the page you end up on when you open a dugga?

Depending on how many groups a student can be placed in for each course I would solve this differently.

**Comment by a15alica** [comment]
![mockup2](https://cloud.githubusercontent.com/assets/26705108/25534247/7fa3756a-2c33-11e7-9baa-05e6a5013dfe.png)

In the picture above there are 6 different placement or designs for showing a student which group it belongs to for each moment. Maybe one of these can be used? Or do you have any other idéas or preferations @HGustavs?

**Comment by HGustavs** [comment]
I like the far-right version... with brackets ...

**Comment by a15timbe** [comment]
Solved in #3942
