### ISSUE TITLE
Collapsability of sections on mobile

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2966]
Collapsing sections is particularly useful on mobile, does the collapsing work as expected on mobile, and is the gesture for collapsing "good enough" or do we want to modify the behavior to better fit mobile use?

**Comment by b15sarha** [comment]
Right now it is a long list of sections one after the other and they exceed the mobile screen when holding it vertically. We would definitely want to change it to fit the mobile use. A way to do this is by having a list, where the user can toggle the sections. Another way to do this is knowing the size of each section and viewing only 3 sections, the rest are hidden under '>>'.

**Comment by a15eriho** [comment]
Is this issue the same as #1867, and #2540? If it is, then it is solved.
The related issue with local storage is under construction, but uncertain if it will be done until the merge on Thursday 4/5.

**Comment by a15emibo** [comment]
Collapsability works well on me and my colleague's mobile devices. I declare it solved.
