### ISSUE TITLE
Arrow icon for opening/closing content isn't where it's supposed to be

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#2973]
Image for clarification:
![kekekkekekeke](https://cloud.githubusercontent.com/assets/26704655/24899365/57ddf352-1ea0-11e7-81c9-b9830849084f.png)

The arrows are placed beside ID on 2 of the items but not on the others. Should be symmetrical for them all.

**Comment by a15freed** [comment]
Hello :) this issue is solved in out branch

http://webblabb.iit.his.se:8080/grupp3/LenaSYS/DuggaSys/fileed.php?cid=1&coursevers=45656

**Comment by a15elibr** [comment]
Awesome! Closing this issue then.
