### ISSUE TITLE
Install script test data

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#2974]
We need more test data... for example

* A completely empty course
* More tests (duggas)
* More students assigned to courses
* More teachers assigned to courses (for testing teacher filtering)

**Comment by a15eriho** [comment]
The 'user_course' table needs a connection to a version of the course in the 'vers'.

eg. "INSERT INTO user_course (uid, cid, result, creator, access, period, term, vers) VALUES (1010, 1, '0.0', 1, 'R', 0, 'HT15', 12345);"

Where '12345' exists in the 'vers' table.

This is to connect the user to a version of a course.

**Comment by a15ponja** [comment]
At the time of writing this comment there are 2 issues that are connected to this issue:

- #3588 Add security questions and answers into the install scripts testdata.

- #3561 Need testfiles in the .md-format in installscript as testdata.

**Comment by a18kaswi** [comment]
Line 449 f.f
`    <!-- START of install section. When form is submitted mode will be changed to install and this will run
      -- Flush and ob_flush is used after every output in progress to dynamically show output when something was done.`

**Comment by a18kaswi** [comment]
> We need more test data... for example
> 
> * A completely empty course
> * More tests (duggas)
> * More students assigned to courses
> * More teachers assigned to courses (for testing teacher filtering)

More studens and teachers were added and assigned to courses in 2017.
A completely empty course exists in the form of 'datorns grunder' 

More tests (duggas) has been implemented with #8744 

If that one gets merged, this can be closed. And we'll take the installer forward from there.

**Comment by a18kaswi** [comment]
All currently available duggas are now available to look at in the demo-page course.
