### ISSUE TITLE
Make timeout visible on screen

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2979]
Part of issue #2417. When a session has been timed out, make this visible to the user so the student is aware that he/she is no longer connected to LenaSYS.

**Comment by HGustavs** [comment]
A simple way to do this is to change the torso icon to red from green... and perhaps also make a pop-up saying that you have been logged out?

**Comment by HGustavs** [comment]
Alert is better than popup since it is operating system neutral...

**Comment by a15tobli** [comment]
Merged in #3042, closing issue
