### ISSUE TITLE
Create a database relation between usergroup and listentries

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#2981]
A group (usergroup) should be connected to a listentry in the database. 

This is because a group of users should be connected to a course event, for instance a seminar.

**Comment by HGustavs** [comment]
Or to a dugga?

Dont remember how this is done for other parts of the system.

**Comment by b15matol** [comment]
Hello, 

Yea, a moment in the course, that could be a seminar, a dugga, etc. This is a part of #2463. This is referenced in the database as listentries.

**Comment by a15tobli** [comment]
Solved in #3099, closing issue.
