### ISSUE TITLE
Add responsive design for profile page

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2982]
When visiting the profile page from a mobile device, the code requires some implemented responsiveness for alignment of the elements.

**Comment by HGustavs** [comment]
Screenshot so we know what were looking at.

**Comment by a15alica** [comment]
![image](https://cloud.githubusercontent.com/assets/26705108/24902953/2b1feac6-1eac-11e7-80bd-ec5a876211d0.png)

This is the plan for the fix.

**Comment by a15tobli** [comment]
Solved in #2988, closing issue
