### ISSUE TITLE
Two buttons does not work in Section Editor

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#2995]
The "Edit Version" and "New Version" buttons in the menu in Section Editor runs JS-functions on click, but nothing happens on the site when they are clicked. 
The functions that are being called upon are showEditVersion() and showCreateVersion() in sectioned.js. When looking at the code, an element with the version should appear, but this is not the case.

**Comment by a15eriho** [comment]
These are working in the last merge version from w14.

**Comment by a15eriho** [comment]
Closing this issue since these buttons now are working.
