### ISSUE TITLE
Mobile browsing

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3001]
LenaSys is at this moment not well adjusted to smaller screens like mobile devices. There are a few pages that looks good on mobile devices but most of them do not. The list of courses look alright and the profile page has been changed to look good.

The section editor needs fixes for following things:
- The menu takes up as much space as is needed which makes it necessary to scroll horizontally.
- The dugga list is adjusted to the width of the screen but the text gets placed on top of each other.
- You are able to scroll quite far vertically even though the content ends further up.

- The access-page is zoomed out and the content is strangely positioned.
- The results-page is zoomed out a lot and the content is still so wide scrolling horizontally is necessary. The background color doesn't fill the entire page. 
- The tests-page is zoomed out.
- The files-page is a bit zoomed out but looks alright.
- The list-page is non-existing (Not found).
- The analysis-page does not contain anthing (just a white page with the header).
- The groups-page is a work in progress (right now not containing much). It is missing an arrow which allows you to go back to the previous page though.
- The new item-button opens a popup-box on the page which allows you to add a new dugga. The problem is it doesn't fit into the screen of a mobile phone.
- The FAB is not visible unless you zoom out a lot and when doing that the + in the button is not centered in the yellow circle. (Are both the new item-button in the menu and the FAB needed at the same time if you're viewing the page from a mobile device?)

If you open a dugga (for example a 3D-dugga or a Färgdugga) they too are zoomed out. Some look alright if you ignore that, some don't.

In the edit variant in the dugga editor the instruction file-div overlaps with the param-div.

Almost all popup-windows (like the login-box, the edit variant and so on) are too wide to fit into the width of a mobile phone. It is also difficult to close some of them since the closing-button isn't visible unless you zoom out. Another problem is that you can't move them on mobile devices.

**Comment by a15tobli** [comment]
Suggested method of solving this is creating a new issue for every separate problem in the given list when someone decides to fix something, as this will be a huge project to implement.

**Comment by HGustavs** [comment]
Prioritize student view stuff.

Teacher views are mostly used by us teachers and do at this moment not make use of much mobile features....

However, anything that is student-facing is more useful to make even more mobile focused.

I suggest starting out with some of the smaller issues, such as adding ellipses to table lists that break due to being too wide.

**Comment by HGustavs** [comment]
* The menu takes up as much space as is needed which makes it necessary to scroll horizontally.

...

Clarify which menu we are talking about, is it the navigation menu or some other menu?

**Comment by a15eriho** [comment]
This is a very big issue, and might benefit of breaking down to smaller issues to make it more readable and easier to keep up with what is fixed, and what still needs fixing.

**Comment by e14johho** [comment]
Adapt loginbox for mobile browsing is going to be fixed in #3880.

**Comment by d15marwi** [comment]
Nothing left regarding Group 3 2018

**Comment by c16linst** [comment]
Nothing left regarding Group 2 2018

**Comment by c16matan** [comment]
Nothing left regarding Group 1 2018
