### ISSUE TITLE
The title for the groups tab is displaying misleading text upon hovering the button. 

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3004]
Like this: 
![img_3281](https://cloud.githubusercontent.com/assets/26713381/24910642/ab6d61e2-1ec8-11e7-8c35-8f863f1c5c9a.JPG)

**Comment by a15tobli** [comment]
Setting high priority as this is something that should be fixed before the weekly merge, as icons will be implemented for this menu.

**Comment by a15tobli** [comment]
Merged in #3008
