### ISSUE TITLE
Headings on pages you reach from section editor menu

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3007]
All the pages you can reach from the section editor menu (for example access or results) could use some kind of heading showing which page you ended up on. This could either be fixed by adding a heading text saying for example "Access editor" or keeping the menu from the section editor.

If the menu from the section editor is used one idea is to make it look like different tabs and the one selected is marked in some way, showing it's different from the rest.

**Comment by a15alica** [comment]
If the menu from the section editor is to be used this is one suggestion of how it could look.

![image](https://cloud.githubusercontent.com/assets/26705108/25181144/d2dcc4e0-2510-11e7-99dd-89da4b9e57f0.png)

The screenshot is meant to show the access-tab to be selected.

**Comment by HGustavs** [comment]
Space is at a premium so no new additional things, but if there is space in some existing element such as the menu, I am for it.

It is more important is to change the title element so that you can see which page it is in the web browser tab....

**Comment by a15timbe** [comment]
This was solved in #3436
