### ISSUE TITLE
Changes must be implemented to edit variant in dugga editor

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#3029]
We discussed and reached a conclusion that every submission in dugga editor should have an unique ID for either the dugga, course or an overall unique ID. 

@HGustavs which one is preferred to use as identifier?

**Comment by a15alica** [comment]
@HGustavs How unique is the submission ID suppose to be?

**Comment by HGustavs** [comment]
What does the database code look like currently?

**Comment by a15alica** [comment]
Right now each submission someone uploads has a submission id (which is automatically assigned) and it is connected to a user, a course, a dugga and a filename (amongst a few other things). It is also saved with a timestamp of when it was submitted and connected to the fieldname of the submission (which defines if it is suppose to be e.g. a projct report or a project zip). If a dugga has multiple submission parts (e.g. both a pdf and a zip) they are saved as two submissions in the database.

From what I can tell: if two different pdf's are suppose to be uploaded at a dugga they need different fieldnames for them not to be mixed up or confused as two versions of the same thing.

Proposed changes are to either have it like it is now but to add a number after the fieldname (automatically assigned), to show a difference, or to add a dropdown list where you can choose what kind of submission (e.g. a pdf or a zip file) and have a text field where you can type the fieldname yourself (with a check to make sure the same name hasn't been used before in the same dugga). Other ideas are also appreciated.

**Comment by a15alica** [comment]
Each submission (each file is saved as a new submission) is saved in the database table shown below.

![image](https://cloud.githubusercontent.com/assets/26705108/25222010/7440a210-25b7-11e7-8f22-f2a1e889e60e.png)

To be able to tell the difference between two versions of the same submission and two different, for example, reports in the dugga, the fieldname has to be different for the two types.

This can be solved by either adding an automatically assigned number after the predefined fieldname or by allowing the teacher to write a fieldname in a textbox. Mockup for the two variants below.

![image](https://cloud.githubusercontent.com/assets/26705108/25223232/200971f0-25bb-11e7-9f05-1278e65fbfa5.png)
(The number is shown in the JSON-string)

![mockup1](https://cloud.githubusercontent.com/assets/26705108/25223802/c47c01de-25bc-11e7-88fc-2e7a9373a5de.png)

**Comment by HGustavs** [comment]
Looks good. lets try it out, email me a link to a version that I can play around with.

**Comment by e14johho** [comment]
This has now been solved, talked with @a15alica and @b15matol to confirm this.
