### ISSUE TITLE
Implement functionality to create Relations

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#3058]
We need to be able to create Relations, these will work similarly to the already existing attribute/entity. The button to create them will also need to be implemented. The relations should take the form of a diamond.

**Comment by HGustavs** [comment]
It should be a hybrid of an entity and an attribute.... since we need the connection boxes from the entity to allow us to connect anttributes to the relation.

I suggest making one issue for drawing the diamond and another issue for the connector lists.

**Comment by b15matvi** [comment]
Issue resolved.
