### ISSUE TITLE
Formatting error in sorting/filter menu in result view.

### ISSUE THREAD

**Issue by a15eriho** [HGustavs/LenaSYS#3060]
When pressing the arrow up/down button for sorting/filter options in the teachers result view, the formatting of some options are wrong.

![filter_result](https://cloud.githubusercontent.com/assets/26706624/25118227/a33fa96a-2415-11e7-9e66-f8f201c45fbb.png)

**Comment by HGustavs** [comment]
I would say this is a bug

**Comment by d15eriso** [comment]
The sorting menu in result-view works fine when no duggas/courses has been toggled in the filter menu. But when you select a dugga that you want to see in the list, the botom of the menu gets pushed to the right side and too long course names does not show properly.

**Before:**
![image](https://cloud.githubusercontent.com/assets/26739514/25387851/7325e8fe-29cc-11e7-80dd-cf2fdbe3fbbb.png)


**After:**
![image](https://cloud.githubusercontent.com/assets/26739514/25387885/8c6b6dd4-29cc-11e7-8ac6-3257e79fe505.png)

My suggestion is to keep the "FIFO", "Grade", "Submitted", "Marked" radioboxes to the left side like in the first picture and add the courses to the bottom, under these radioboxes.

**Comment by d15eriso** [comment]
This is fixed since the last merge. Im closing down this issue.
