### ISSUE TITLE
The 'List' button is still there even though i have removed it twice.

### ISSUE THREAD

**Issue by b15sarha** [HGustavs/LenaSYS#3061]
The 'List' button in the menu section remains even though it is been deleted twice. The only conclusion is that someone is merging an old version of LenaSYS or someone is trying to add the button.

**Comment by a15elibr** [comment]
Third time's the charm!

**Comment by HGustavs** [comment]
For the next merge, make a note of this issue and take it to the merge meeting and confirm that it has been removed after the merge, and if not, remove it directly from the master before branching the sub-projects.

**Comment by a15ramha** [comment]
This issue has been solved.
