### ISSUE TITLE
Arrow icons still not where they are supposed to be

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#3073]
References issue #2973. Look there for more specific information. This issue was supposed to be solved and be working after the latest merge, but it isn't, so it needs to be fixed again.

**Comment by a15elibr** [comment]
Either put icon on the right side of the text or on the left, so that they all have the same

**Comment by HGustavs** [comment]
Screenshot?

**Comment by a15elibr** [comment]
![18009621_10210752636824876_814890710_n](https://cloud.githubusercontent.com/assets/26704655/25123474/bb94f6b0-2428-11e7-8f64-969a3ee7a7c1.png)

**Comment by a15elibr** [comment]
Closing issue since it has been resolved.
