### ISSUE TITLE
Attribute and entity menu options should stay selected when you open them again

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#3088]
The selected options get "deselected" when you open them again, this needs to be fixed.

**Comment by HGustavs** [comment]
Every time that the dialog is opened it should be filled with the data from the objects... if it works on double-click it should work automatically.

**Comment by b15matvi** [comment]
As the name part was bugged out from an earlier pullrequest it needs to be fixed inside this issue aswell

**Comment by a15perbl** [comment]
Issue resolved.
