### ISSUE TITLE
Display a message that the teacher has been notified about resetting the password

### ISSUE THREAD

**Issue by e14johho** [HGustavs/LenaSYS#3093]
After the user has pressed the button answering the security question, a window should appear displaying a message that the teacher has been notified about this. 
The window should display something along this
"A message has been sent to the techer about resetting your password"
"You will be sent a new password as soon as possible"

**Comment by HGustavs** [comment]
Good idea to give feedback here.

Perhaps an alert to make it look more official?

**Comment by e14johho** [comment]
@HGustavs we have implemented this window. Is there any designsuggestions you have regarding this? 
<img width="546" alt="skarmavbild 2017-04-19 kl 11 10 58" src="https://cloud.githubusercontent.com/assets/26707533/25172389/2224504c-24f1-11e7-91ca-1ce83934c132.png">
