### ISSUE TITLE
Add styling to the alert given when the session has expired

### ISSUE THREAD

**Issue by b14larek** [HGustavs/LenaSYS#3094]

**Comment by a15tobli** [comment]
Already got an issue for this, #2627, closing this one.

**Comment by HGustavs** [comment]
Change back from green man icon to red man icon?

**Comment by a15tobli** [comment]
That is something we have planned to do, but we would also like to implement some sort of notification so it becomes more clear that the session has expired. It is likely that the student does not notice that the icon has changed color, which could lead to lost work progress when they try to submit something.

**Comment by a15tobli** [comment]
Alert solved in #3171, closing issue.
