### ISSUE TITLE
Add a grid to the diagram, objects should "snap to grid"

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#3097]
We want a grid in order to ease the usage of the diagram. The grid should also make use of the snap to grid functionality which means the grid assists you when creating objects.

**Comment by HGustavs** [comment]
"could" snap to grid not "should" ... also ...

Drawing the grid could be added to the ruler described in another issue....

**Comment by HGustavs** [comment]
#2458 Im thinking that the grid is drawn as a 15-20% gray dotted line on every 5 or 10 in the ruler e.g. 25,30,35 or 10 20  30 40 50 etc.

When the ruler is drawn and if grid is enabled we draw vertical and horizontal grid lines.

**Comment by HGustavs** [comment]
Snap to grid is literally one line of code.

if mouse coordinate is in cx,cy (I think it is ?)

To snap to grid we do the following

cx=Math.round(cx/gridsize)*gridsize;
cy=Math.round(cy/gridsize)*gridsize;

where gridsize is the variable from above e.g. 5 or 10

....

**Comment by a15chrau** [comment]
Sounds correct. However, we've been struggling to draw the grid on a canvas after the zoom and navigation functionality was commited.

**Comment by a15chrau** [comment]
However, it seems a bit redundant to have the option between a grid size of 5 or 10.

Wouldn't a more reasonable solution be to have a gridsize of 5 and give every other, or every 5th, a darker border, as seen in Ex 1 and Ex 2 respectively.
![image](https://cloud.githubusercontent.com/assets/26707347/25247707/edc4bb54-260b-11e7-8942-f9211aa0c779.png)

**Comment by a15chrau** [comment]
When you find time, could you pass by and help me out?

**Comment by b15matki** [comment]
Closing issue due to the main objectives being complete.
