### ISSUE TITLE
Add search function to access view

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#3120]
Would be nice to be able to search between users in the access view for teachers.

**Comment by a15elibr** [comment]
Is partially fixed with pull request #3122

**Comment by a15wilhe** [comment]
pr 3122 was for fileed view(issue 3012) and this issue is for access view. 
So far I know nothing has been added for this specific issue.

**Comment by a15wilhe** [comment]
I believe this issue was fixed with pr#3255. I added a fast key up search functionality for the table.
You can check the result at the testsite in my folder. Can I close this issue now?

**Comment by a15elibr** [comment]
Yes, this as indeed been fixed and therefor I am closing this issue.
