### ISSUE TITLE
All users should be listed in result view!

### ISSUE THREAD

**Issue by c14emian** [HGustavs/LenaSYS#3124]
Currently only the users who have submitted a dugga are listed in the result view, this is a bug since all users registered to the course should be listed. Maybe error in the filter or course version?

**Comment by d15eriso** [comment]
This conflicts with my issue (#2452). I am trying to show teachers in the result view and a way to filter them out, but this will conflict with what Im working with at the moment.

**Comment by a15eriho** [comment]
This is most likely due to incomplete test data. "vers" field in the 'user_course' must match a corresponding entry in the 'vers' table.

When this is properly fixed, all the students will show up regardless if they have a submit or not.

**Comment by d15eriso** [comment]
Added and modified some testdata for my issue #2452, so now there are some students and teachers visable in "Datorgrafik" and "Webbprogrammering". But I will fix this for all courses after the merge.
