### ISSUE TITLE
Styling on profile page

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3128]
The styling of the profile page needs to look more like the rest of LenaSys. The buttons should be purple like the rest of the buttons on the site for example.

**Comment by a15alica** [comment]
![image](https://cloud.githubusercontent.com/assets/26705108/25224652/51a50d74-25bf-11e7-9792-53cabf99d777.png)

The styling of the profile page needs more changes than we first thought. We're thinking about adding this kind of menu. @HGustavs, is this design okey?

**Comment by HGustavs** [comment]
Im thinking in lena-sys stile, material design-like as much as possible.
We have not been using this type of layout previously as is too desktop-focused to be useful on other platforms or on smaller screen devices.

**Comment by a15timbe** [comment]
Solved in #3857
