### ISSUE TITLE
De-selecting results filter not working properly

### ISSUE THREAD

**Issue by a15matab** [HGustavs/LenaSYS#3136]
When selecting then de-selecting filters in the result editor the table is not updated properly.

![bug1](https://cloud.githubusercontent.com/assets/26706785/25181647/7e350d1a-2512-11e7-8cec-7524772e1d84.png)

As seen in the image above, the results for Biträkningsdugga 1 still shows up when it shouldn't. This is after first selecting all Biträkningsdugga, filter, and then de-select and filter them again.

**Comment by a15matab** [comment]
Seems #3202 may have fixed this issue too.

**Comment by A15cecal** [comment]
@a15elibr Should we close this issue then?

**Comment by a15freku** [comment]
Closing this issue see #2573 (duplicate issue)
