### ISSUE TITLE
Most of the attribute/enitity options are broken

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#3140]
- Name is not entered when you open an enitity/attribute

- Primary key does not give the underline as it should

- Multivalue does not give the border around

- Changing text scale does not work

- Weak option does not give the border around the entity

**Comment by b15matki** [comment]
Fixed the following bugs as of right now:

- Primary key does not give the underline as it should.

- Multivalue does not give the border around.

- Changing text scale does not work.

-Weak option does not give the border around the entity.

**Comment by b15matvi** [comment]
Issue is reoslved
