### ISSUE TITLE
Fill the group editor with groups in a table, for each moment

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3148]
Hello @HGustavs! The group editor needs to be filled with the existing groups for the moments in the course. The question is how to output the data in the table, that should resemble the result editor. Out proposal is this: 

![skarmavbild 2017-04-20 kl 09 56 35](https://cloud.githubusercontent.com/assets/26713381/25219757/bc51e7f6-25af-11e7-9f3a-1198ee335232.png)

The idea here is that it should be easy to assign a moment to a group. Instead of the "true (false)" etc under each moment, there should be buttons, if true, there should be a green button or light that displays that the group is assigned to the moment. If false, it should be a red light that displays that the group is not assigned to the moment. 

By listing all users (the username is what should be displayed, not real name) in a cell next to the group, the assigning of a group to a moment is done easily technically. More information about each user could be displayed when hovering each name. 

This is related to the larger issue #2441.

**Comment by a15tobli** [comment]
Solved in #3211, closing issue.
