### ISSUE TITLE
Overlay fixes for boxes

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#3152]
Lenasys requires some design tweaks to be more consistent through the site. The login box has a gray overlay added to it, the other boxes with the same layout needs to have an overlay added as well.

**Comment by HGustavs** [comment]
I say that we are talking about the under-lay?

Or the background of the dialogs themdselves...

**Comment by a15tobli** [comment]
We made a pull, #3293, which added a gray underlay at all the windows. When a window is active, all other content gets colored which adds a bit of clarification that the content is not reachable until you close the window and the gray color disappears.
