### ISSUE TITLE
Going back button not working properly 

### ISSUE THREAD

**Issue by b15sarha** [HGustavs/LenaSYS#3180]
When pressing "Go back" button it only takes you to the previously visited page, this is however not desired. Upon pressing the button multiple times we would want to go to the home page of LenaSYS. 
Right now it is hardcoded with links of previous pages.

**Comment by b15sarha** [comment]
Pair programming with @a15oscwe

**Comment by HGustavs** [comment]
Reverted.

We dont want "back" .. that button is already present in browser.

We want the button to go down to a previous page.

If we want to add more pages, new code must be added if we want this button on other pages.
