### ISSUE TITLE
Display the right dugga type at the dropdown list in dugga edit

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#3192]
The dugga edit have a new menu added where you can choose type of dugga, e.g. groupdugga or seminar in a dropdown list. When the dugga edit have been closed and reopened, the list always displays the default value, no matter what has been chosen. The value of the selected item is saved to the database properly, so this is just a visual fix.

**Comment by a15mikla** [comment]
I'm guessing this is related to issue #3238
