### ISSUE TITLE
implenting incremental alternatives to markdown syntax that follow markdown in showdoc.php

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#3193]
This is issue is exactly like issue #2648 but for showdoc.php instead of markdown.js

**Comment by HGustavs** [comment]
Where are we on this has it been resolved?

**Comment by a16silph** [comment]
How are you supposed to try out showdoc.php on the group website? 
For me it gives the 
> Bummer! You have reached a non-navigable link!

 error message when opening the website at the showdoc.php file. 

Where is it used in the actual webpage at runtime?

![image](https://user-images.githubusercontent.com/49142660/79758989-641b7500-831e-11ea-9675-6a873413b3e8.png)

**Comment by HGustavs** [comment]
I think that this has mostly been solved?

**Comment by HGustavs** [comment]
It is an issue from 2017 so my hunch is that the markdown in showdoc.php and markdown.js do mostly the same thing.

I would test with a file link to a .md file with some complicated markdown (code examples, images and bullet lists) and a .md file in the code viewer.

If they look the same this issue has been mostly solved.

**Comment by a16silph** [comment]
My primary problem right now is not knowing where showdoc.php is used in LenaSYS. I know that markdown.js is used in codeviewer, but I want to be able to test the code running in showdoc.php to see that it works as expected, but I can't seem to find where showdoc is used.

**Comment by HGustavs** [comment]
It is used when we add a link or in a test

**Comment by HGustavs** [comment]
So if we upload a .md file and in the section editor makes a link item and then assigns this .md as the link it is shown using showdoc.

**Comment by HGustavs** [comment]
Also if we do the same thing with a test e.g. we make a test that links to assignment1.md that also uses showdoc.php.

**Comment by HGustavs** [comment]
Showdoc can also be used independeny as you did above but you must pass a link to an existing file e.g. 

https://server.com/DuggaSys/showdoc.php?cid=13&coursevers=12345&fname=Assignment1_2020.md

**Comment by a16silph** [comment]
I've added the same + notation support that I added to markdown.js, #8300 but I'm still having trouble testing that it works properly due to errors displaying my testing .md files on LenaSYS.
Error message shown below.
![SetLinkError](https://user-images.githubusercontent.com/49142660/80284518-518aac80-871f-11ea-8624-23aa7384c2d3.png)
**_Fig.1 - Error message display_**

Should I still make a pull request, or should i keep trying to find one of the ways to display showdoc.php markdown that doesn't stop me with an army of error messages?

**Comment by a18filkr** [comment]
If this still hasn't been answered next week, close issue.

**Comment by a97marbr** [comment]
I tried to upload a file to the master and it seems that the fileed functionality has changed somewhat (showdoc.php will not render files when clicking on them in fileed.php) but linking a file in the course view will make showdoc.php render the file

http://masterfiles.webug.his.se:20001/LenaSYS/DuggaSys/showdoc.php?exampleid=snus.md&courseid=2&coursevers=97732&fname=snus.md

**Comment by a16silph** [comment]
I got the preview of my list test file to work with both of your path examples finally. The strange thing is that I was not on the issue branch for this issue, but showdoc had no problem displaying **+ sign** list elements. Does showdoc.php even need a separate fix for displaying markdown, or is markdown.js always used for that? (markdown.js is referenced in showdoc.php) 
![showdoc](https://user-images.githubusercontent.com/49142660/81293902-5bd96e80-906e-11ea-875b-3a4f90a19429.jpg)

**Comment by a18filkr** [comment]
This has been solved for now, we decided not to merge more fixes for this issue.
Closing
