### ISSUE TITLE
Increase size of error window for install.php

### ISSUE THREAD

**Issue by e14johho** [HGustavs/LenaSYS#3195]
Would be really helpful to increase the size of the window so you can more easily read the code that is wrong.  

<img width="657" alt="skarmavbild 2017-04-20 kl 12 56 41" src="https://cloud.githubusercontent.com/assets/26707533/25268940/f0e6dd5c-267a-11e7-8ea7-a22be5e139e8.png">

**Comment by a15freed** [comment]
This is solved and merged
