### ISSUE TITLE
bug in showdoc.php - javascript function loadedmd() referenceError

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#3198]
in showdoc.php line 280 - "body onload='loadedmd();'"; give referenceError. Function loadedmd() either doesn't exist or not included correctly.

**Comment by b15sarha** [comment]
The method loadedmd() is now deleted since it doesn't seem to exist anywhere in the code.

**Comment by a15freku** [comment]
Method is now removed se pull request #3239
