### ISSUE TITLE
Update user icon when session has timed out

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#3199]
Alerts have been added for the session functionality. Implement a fix so that the user icon and name updates automatically when the session has ended. At the moment, you will get logged out, but have to manually refresh the page before you can see the change of the icon. This change will make it even more obvious that the session has ended and the user have to log back in.

**Comment by a15ponja** [comment]
This issue has for been put on hold due to similarity to issue #2946 after that issue has been solved we will decide how work on this issue will proceed.

**Comment by a15matab** [comment]
@a15ponja issue #2946 is solved now.

**Comment by a15ponja** [comment]
Since issue #2946 was solved there is no need for this issue.
