### ISSUE TITLE
Creating entity/attribute/relations should have a predefined size - but also possible to increase

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#3206]
When we create new entities:
* Attributes or relations there should have a predefined size if you just click to create a new object. 
* Also if you try to drag to define your own size, if it is too small it will be the predefined size. 
* However you should also be able to drag to create your own defined size aswell.

**Comment by HGustavs** [comment]
The last bullet point (edited for clarity) is difficult to understand...

**Comment by a15perbl** [comment]
Issue resolved.
