### ISSUE TITLE
Create an undo & and redo button

### ISSUE THREAD

**Issue by a14davlo** [HGustavs/LenaSYS#3208]
In almost all editors you have buttons where you can take a step back and if you've stepped back, you can also take steps forward.

We currently have hash code that can be further developed for this.

**Comment by b15matvi** [comment]
It would be preferred if it's possible to use ctrl + z for undo and ctrl + y to move forward aswell.

**Comment by HGustavs** [comment]
Seems like a great way to do this by havig both a button and a key combination...

This can quite easily be implemented by keeping a history of the json data, or retrieving an old version of json data from server.

**Comment by b15matvi** [comment]
Placing this issue on ice until @a14pethu is finished with the hashing function.

**Comment by a15admsa** [comment]
I've made it possible to save the state you are at and to return to the previous state. The problem is that it won't redraw the diagram and the points. That is the only thing left in this issue.
