### ISSUE TITLE
You can only change size correctly on relation in the right hand corner. Need to be able to change in the top left aswell

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#3210]
The size changes correctly when changing in the bottom right corner. However if you try to change in the top left the relation doesn't scale as it should.

**Comment by d15eriso** [comment]
Too long title, and the description is the same as the title, shame..

**Comment by b15matvi** [comment]
Reported.

**Comment by b15matvi** [comment]
Issue resolved.
