### ISSUE TITLE
Missing image when using jquery's datepicker functionality.

### ISSUE THREAD

**Issue by a15eriho** [HGustavs/LenaSYS#3225]
When picking dates for a course, or a dugga, the following errors occur. Seems it is due to missing images.

![datepicker](https://cloud.githubusercontent.com/assets/26706624/25301608/051526c4-272c-11e7-924a-71a07c8e9884.png)

This does not seem to cripple functionality in any way, but errors..

Suggested moves: Either remove these image references, create images to match them, or ignore the errors.

**Comment by a15freed** [comment]
a solution for this might be on this page http://stackoverflow.com/questions/19515943/icons-missing-in-jquery-ui
