### ISSUE TITLE
The forward and backward buttons for switching between examples is not working

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#3233]
For example in the webprogramming course when you click on javascript example 1 and then click on the next button the javascript example 2 should show up.

**Comment by b15sarha** [comment]
<img width="1271" alt="skarmavbild 2017-04-24 kl 15 08 29" src="https://cloud.githubusercontent.com/assets/25817750/25338588/0c83b422-2900-11e7-968c-e400135b4cd3.png">

**Comment by a15freku** [comment]
Have this not been solved recently? @b15sarha

**Comment by b15sarha** [comment]
This doesn't work for current version of the course. Working on it.

**Comment by a15emibo** [comment]
Fixed with pull request #3700
