### ISSUE TITLE
Hovering over an object should give you four alternatives to change the object scale

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#3269]
As in the boxmodell code, in issue #2458 we want the four alternative scale options to show up when you hover over an object. This is because we have to be able to change size from all angles.

**Comment by HGustavs** [comment]
Or when more than one element is selected by group select... a bigger box around all selected elements.

* Only points selected (no box?)
* Single object selection - box around that object
* Multiple object selection - box around all objects (not individual boxes around all elements)

...

How to make that box?

If we iterate over all selected symbols, the lowest top is the top of the box, the lowest left of the symbols is the left of the box 

pseudo code:

~~~
boxleft=5000;
boxright=-5000;
boxtop=5000;
boxbottom=-5000;
for(each symbol){
    boxleft=Math.min(boxleft,symbol.topleft.x)
    boxtop=Math.min(boxtop,symbol.topleft.y)
    ...
}
~~~

**Comment by c16linst** [comment]
The hover functionality isn't longer needed - this can be done by clicking an object. We are not sure about the box around multiple elements. Is it really a good idea to change the size of multiple objects at once? This tends to destroy the structure of things (at least in other applications where this is possible).

**Comment by c16linst** [comment]
@HGustavs should we close this issue? It doesn't seem relevant anymore.
