### ISSUE TITLE
General cleanup of forgot password code

### ISSUE THREAD

**Issue by a15ponja** [HGustavs/LenaSYS#3275]
There are various things with the forgot password code that needs cleanup, such as:

- Some comments needs to be reworked/added/removed #3278 - SOLVED

- The login button and forgot password button should not be in the same table row #3276 - SOLVED

- A user should not be able to request a password change while they already have a pending password change request #3279 - SOLVED

**Comment by a15timbe** [comment]
Last sub-issue was solved in #3478. Closing this issue.
