### ISSUE TITLE
Sorting / filtering files by date, size, name etc in file view

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#3277]
There was an issue on this but it was closed and partially fixed, so for clarity I make this new issue instead.

As title said, there should be a way to sort or filter files by name, size, date, file type etc. Since it might be tricky to make it work via clicking on table head (sinze it will minimize table), it could be done as filtering is done.

**Comment by HGustavs** [comment]
We can expand/contract on double-click and re-sort on single click...

If click and no other click within lets say one second, it counts as a "sorting" click, but if there is a second click within a second, we expand or contract the accordion....

Could this compromise be acceptable?
