### ISSUE TITLE
In the group editor page, only group duggas should be displayed as headings

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3285]
This is because it is irrelevant to display non-group-duggas. 

This is how it looks as of now, the results does not match the number of group-duggas: 

![skarmavbild 2017-04-25 kl 10 49 46](https://cloud.githubusercontent.com/assets/26713381/25376565/f7066612-29a4-11e7-8c77-c1c9194ac1f1.png)

A small adjustment in a query in groupedservice.php file is needed to fix this problem.

**Comment by a15tobli** [comment]
Solved in #3290, closing issue.
