### ISSUE TITLE
Remove the "New Item" button in sectioned.php

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#3299]
A yellow Floating Action Button has been added to the section editor, which have the same functionality as this button, which makes them redundant. Due to the fact that the FAB follows material design, this should be kept instead of the "New Item" button. 
The "New Item" button also adds another tab to the navigation row, which makes mobile browsing of this page even worse as this row is not properly displayed in the mobile view. This further adds a reason to remove this button.

**Comment by a15andau** [comment]
Apparently Henke want's both the "New item"-button, as well as the yellow floating action button so I'm closing this issue. Fixes has been made related to this issue in issue #1823
