### ISSUE TITLE
Select and move a figure

### ISSUE THREAD

**Issue by b15matvi** [HGustavs/LenaSYS#3321]
This is a rebranding of an earlier issue, the issue at hand is the ability to select and move a figure

**Comment by HGustavs** [comment]
Not super easy this issue....

I like functionality like Illustrator if possible.

* If I click near a point I select that point
* If I click inside the figure, I select the whole figure e.g. all the points inside that figure.
* If I press control while doing any of the above, I group select
* I box-selection tool that allows us to select any figure that has a point inside the box.

Any other functionality that seems useful to add here?

**Comment by b15matgu** [comment]
I think this issue is related to #3409, https://github.com/HGustavs/LenaSYS/issues/3409.

**Comment by a15perbl** [comment]
Issue resolved.
