### ISSUE TITLE
The duggas don't need time for deadline, just date

### ISSUE THREAD

**Issue by a15freed** [HGustavs/LenaSYS#3323]
The duggas don't need time for deadline, just date

![image](https://cloud.githubusercontent.com/assets/26706932/25422440/314f5452-2a61-11e7-8f69-cc0bf5df5f13.png)

**Comment by a15freed** [comment]
If a deadline is not set in time there should not be zeros visable

**Comment by a15elibr** [comment]
Agreed that if there is no time set, the zeroes should be hidden, but it would be a mistake to remove the time all together. Deadlines are often set in date AND time!
