### ISSUE TITLE
Ellipsis on Section Editor View entries

### ISSUE THREAD

**Issue by a15eriho** [HGustavs/LenaSYS#3347]
Related to huge issue #3001 Mobile Browsing

**Comment by HGustavs** [comment]
This goes a far way to make the experience more bareable on mobile platforms.

* Ellipsis on titles of elements and 
* A shorter date column for deadlines on mobile - 2012-01-07 17-00 could be changed to 01-07 on mobile using css that hides that part of the date text on mobile.

**Comment by a15eriho** [comment]
Course version disappears when screen gets narrow enough.
Deadline year disappears when screen gets narrow enough.
If there is a time that is not 00:00:00 as a deadline, it will remove the trailing seconds when the screen gets narrow enough.
Various texts get ellipsis (tex...) when screen gets narrow enough, and will no break on white space.
