### ISSUE TITLE
 Centerpoint of a relation symbol should not change the shape

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3348]
Currently when the centerpoint of a relation is selected and moved it alters the shape altogether. This is not meant to happen as a relationship always should be shaped like a diamond.

![bild](https://cloud.githubusercontent.com/assets/26705103/25471229/658df190-2b26-11e7-8b52-47492cf2d94e.png)
![bild](https://cloud.githubusercontent.com/assets/26705103/25471237/6ee13ebe-2b26-11e7-9d60-28c9b3d8831c.png)

**Comment by HGustavs** [comment]
In addition to this there should be only a fixed size. 

We dont want relationship symbold of varying sizes, one single fixed size is the way to go.

**Comment by a15perbl** [comment]
Issue resolved.

**Comment by b15matgu** [comment]
Tried a new solution, but reverted code to original. Issue can be closed again.
