### ISSUE TITLE
Move exit button into swim lane.

### ISSUE THREAD

**Issue by b15linek** [HGustavs/LenaSYS#3349]
It's hard to see the exit button for the swim lane. Move it to a better position.

**Comment by HGustavs** [comment]
Screenshot

**Comment by b15linek** [comment]
Was like this:
<img width="1351" alt="screen shot 2017-04-27 at 10 34 23" src="https://cloud.githubusercontent.com/assets/26706647/25474901/28c1c23c-2b35-11e7-8bd2-81e955199f59.png">

Will be like this:
<img width="1327" alt="screen shot 2017-04-27 at 10 34 34" src="https://cloud.githubusercontent.com/assets/26706647/25474907/30c39d16-2b35-11e7-956b-38f734e72f37.png">
