### ISSUE TITLE
Split up diagram.js further

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3350]
The file diagram.js as it is right now has over 2000 lines of code. There shouldn't be more than 1000 lines of code and therefore diagram.js needs to be split up again.

**Comment by HGustavs** [comment]
Well, not easy to do if there is only one single class in that file....

I say 1000 lines is more of a guide line, if we split the same class in more than one file we are losing cohesion, not gaining.

**Comment by a15admsa** [comment]
This issue is now fixed!
