### ISSUE TITLE
When editing an Example, the edit window looks kind of weird 

### ISSUE THREAD

**Issue by b15sarha** [HGustavs/LenaSYS#3359]
<img width="707" alt="skarmavbild 2017-04-27 kl 09 52 14" src="https://cloud.githubusercontent.com/assets/25817750/25473309/4c06a6be-2b2f-11e7-888d-43eb7a3f46f6.png">

**Comment by HGustavs** [comment]
Im thinking that making the window bigger would solve this, or removing the frame ...

**Comment by b15sarha** [comment]
resolved.
