### ISSUE TITLE
CSS is ugly in code examples when creating new items

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#3364]
![ugly](https://cloud.githubusercontent.com/assets/26705670/25474429/80413b16-2b33-11e7-9782-a4baacb78270.png)

Maybe fix the border-radius so it is more konsistent

**Comment by A15cecal** [comment]
This works in Firefox but not in chrome, so it's a browser-related issue.

**Comment by a15freku** [comment]
The problem is solved
