### ISSUE TITLE
Add buttons in filter in result

### ISSUE THREAD

**Issue by a14phili** [HGustavs/LenaSYS#3366]
Add two buttons in filter in result. "Select all" and "Select none". 
The buttons shouldn't have any affect on "Show teachers" and "Only pending".

**Comment by a15mikla** [comment]
@HGustavs Is it optimal to have the "Select all/Unselect all" as a checkbox or should it be a button, like the filter-button?

Image to clarify:
<img width="269" alt="selectall" src="https://cloud.githubusercontent.com/assets/26705198/25483784/94b61ff2-2b57-11e7-9bba-6052739babc3.png">

**Comment by a15eriho** [comment]
After discussion with 'customer', the functionality of this button should be:
* If any of the check-boxes below are selected: Clear all - Note that the checkbox should be filled if there is anything selected, so it clears everything on first click.
* If nothing is selected, check all boxes.
