### ISSUE TITLE
Match file extension with MIME type

### ISSUE THREAD

**Issue by a15jorpa** [HGustavs/LenaSYS#3384]
Currently the upload filter in DuggaSys/filereceive.php only checks if a file's mime type and extension are allowed, not that they match. It is possible to upload a file with a .html extension that is really a binary file. I would also like to have the filter use php's finfo to make a more reliable examination of a file's type.

**Comment by HGustavs** [comment]
Mime types are very unreliable for binary files... we have ecountered at least 20 distinct mime types for pdf files only.

Different browsers assign different mime types to the same file, depending on how a file is printed we get other distinct mime types ...

...

**Comment by a15jorpa** [comment]
As I understand it using `file['type']` relies on the browser uploading the file setting the correct type. Using the php function `mime_content_type` examines the contents of the file on the server in order to determine its type. This should result in more consistent types for files as the process relies only on one system instead of every possible browser.

With this more reliable system in place, matching file type to file extension should be possible and help increase the probability that a file with a given extension is actually that kind of file.

**Comment by a15freed** [comment]
Uploading files are ok but the error message contains array info.

![image](https://cloud.githubusercontent.com/assets/26706932/25695390/30d7b9bc-30b3-11e7-9d23-27002dfee9f6.png)

**Comment by a15jorpa** [comment]
Allowing files of RAR format doesn't seem to be worth the effort required. Rar is as far as I know easily replaced by zip. If we need a compressed format with a higher degree of compression than zip I would suggest 7zip (.7z) as it is an open format unlike rar. Is there a need for anything other than zip? @HGustavs

**Comment by a18kaswi** [comment]
No answer 2017 - no point having in backlog 2020.
