### ISSUE TITLE
Make rows in swim lane more clear.

### ISSUE THREAD

**Issue by b15linek** [HGustavs/LenaSYS#3403]
It's hard to see what week a dot is on. It should be more clear what week a dugga ends and starts on.

**Comment by HGustavs** [comment]
Screenshot plz

**Comment by b15linek** [comment]
Before:
<img width="1318" alt="screen shot 2017-05-02 at 08 47 13" src="https://cloud.githubusercontent.com/assets/26706647/25606731/50f9ae72-2f13-11e7-9e1d-c61a21a70d9e.png">

After:
<img width="1296" alt="screen shot 2017-05-02 at 08 47 59" src="https://cloud.githubusercontent.com/assets/26706647/25606734/5680c4ca-2f13-11e7-8101-eb04ab99203f.png">
