### ISSUE TITLE
Remove the column group in the group editor

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3423]
The groups should be displayed in drop down list instead of the current solution, where the group is in a column next to the student name. 

_Edit:_ As the data then is displayed per user instead of per group, also make the group visible that the student row belongs to. That will display the group id as an integer instead of the current stoplights that were used as a preparation to assign moments to a group.

**Comment by HGustavs** [comment]
Yes I think that a dropdown is better as it is clearer which group that has been assigned.

**Comment by a15timbe** [comment]
Solved in #3503
