### ISSUE TITLE
CSS styling for the cookies-window

### ISSUE THREAD

**Issue by A15cecal** [HGustavs/LenaSYS#3431]
If you're on a mobile device the window looks weird. Fix it so that it adapts to the screen size for mobile devices.
![p](https://cloud.githubusercontent.com/assets/26705134/25529382/0ea0c702-2c22-11e7-87f1-5d27423a307b.JPG)

**Comment by a15freku** [comment]
Check with @a15eriho it could be that he is working on something similar.

**Comment by A15cecal** [comment]
This issue is almost the same as issue #3399, which is solved. Closing this.

**Comment by A15cecal** [comment]
We were wrong about this issue, this still needs fixing and the other issue was not related to this problem.

**Comment by a15freku** [comment]
Fixed with pullrequest #3559
