### ISSUE TITLE
Install script requires PHP >=7

### ISSUE THREAD

**Issue by a15jorpa** [HGustavs/LenaSYS#3435]
The version of the dirname function used in install/install.php is only available in php 7 or higher. If possible LenaSYS should be able to run on PHP 5.6 or so (asked @a97marbr ). Is the system more widely incompatible with older versions of PHP or should we try to fix the install script?

**Comment by HGustavs** [comment]
How large is the problem, what type of functions are we talking about?

**Comment by HGustavs** [comment]
Is it relatively easy to back-port to a slightly older php?

**Comment by a15eriho** [comment]
The piece of the installer which i think this is referring to is that the dirname() PHP function is used with additional arguments, which is PHP7 only.

From http://php.net/manual/en/function.dirname.php
Version	Description
7.0.0 	Added the optional levels parameter.
5.0.0 	dirname() is now binary safe

Levels just filters the directories in a path, and it is possible to filter out part of a path.

**Comment by a15eriho** [comment]
I made a version of the dirname(path, level) that is compatible with the PHP5 version. This is not tested with PHP5 though, since it's the PHP7 version install on the developement system.
