### ISSUE TITLE
The blue outline should be removed

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#3445]
![ugly](https://cloud.githubusercontent.com/assets/26705670/25608286/97f9b7b6-2f1a-11e7-8867-27f401a0d1ae.png)

**Comment by A15cecal** [comment]
@a15freku Shouldn't this have some sort of shadow?

**Comment by a15freku** [comment]
It has a shadow but that is not the problem. The problem is that; when it is selected, the blue border appears. Maybe this can be helpful https://www.w3schools.com/tags/tag_a.asp
