### ISSUE TITLE
Is it necessary to have two buttons that do the exact same thing

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#3449]
![ux](https://cloud.githubusercontent.com/assets/26705670/25608562/9c2c3da8-2f1b-11e7-9ef5-9d4cc36b2d1d.png)

Maybe remove one of them so that the user does not get confused, or make it more descriptive from an UX point of view.

**Comment by a15elibr** [comment]
This issue has been resolved since once of the buttons already has been removed.
