### ISSUE TITLE
Change cursor to pointer on 'X' for remaining popup-boxes

### ISSUE THREAD

**Issue by a15matab** [HGustavs/LenaSYS#3452]
There was a previous issue on this: #3144 which was closed, but there are still popups that don't have use pointer when hovering over the close button.

**Comment by a15elibr** [comment]
I think an update on our group repo so it matches the one here on github (G1)  just to make sure that the changes I've made really are visible, because I'm actually pretty sure I covered them all. But maybe not!!

**Comment by a15matab** [comment]
The main ones I found were: https://github.com/HGustavs/LenaSYS/blob/G1/DuggaSys/codeviewer.php#L182 and https://github.com/HGustavs/LenaSYS/blob/G1/DuggaSys/showDugga.php#L164

It doesn't look like they have the pointer cursor from what I can tell?

**Comment by a15ramha** [comment]
This issue is solved.
