### ISSUE TITLE
Misleading button name for creating "duggor"

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#3453]
![tests](https://cloud.githubusercontent.com/assets/26705670/25609308/efa00e12-2f1e-11e7-9b57-b2ca09196683.png)

There must be some better name then "tests" for this button. For example "Templates".

**Comment by a15elibr** [comment]
Perhaps even more straight forward than Templates, something to connect with the fact that it's a link to creating duggor. I know just writing "Duggor" / "Dugga" isn't suitable, but it should be... :--)

**Comment by a15freku** [comment]
Yes the problem is that "Dugga" is not an English word and therefore we can not use it.

**Comment by a15matab** [comment]
So is "Templates" a suitable name, or does anyone have another idea?

**Comment by HGustavs** [comment]
Test works or do we have any better suggestions for an english name?

I am open for suggestions.

**Comment by a15freku** [comment]
Templates?
