### ISSUE TITLE
Incorrect offset when moving canvas and zooming

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3463]
Currently when a user moves the canvas and then zooms in that order the offset is disrupted. However, when the canvas is zoomed in on first and then moved the offset is not affected. The order in which the actions are done should not matter and should be fixed.

**Comment by a15gunfu** [comment]
Objects can be moved after zooming, though some problems with the canvas after zooming out. So the part about moving objects looks good!

**Comment by c16jonha** [comment]
Is this still an active issue?

**Comment by a17jacsv** [comment]
Issue #5145 is the same as this issue and therefore I close it to make it easier for the developers.
