### ISSUE TITLE
Add more documentation for installing LenaSYS

### ISSUE THREAD

**Issue by c14caran** [HGustavs/LenaSYS#3466]
Information on how to install is sorely lacking, add a more detailed guide on which packages are needed and any custom configuration.
A guide for setting up ssl would be great too, thanks.

**Comment by c14caran** [comment]
Wrote https://github.com/HGustavs/LenaSYS/wiki/Configuring-web-server-for-LenaSYS-installation

**Comment by c14caran** [comment]
Wrote https://github.com/HGustavs/LenaSYS/wiki/Getting-a-free-ssl-certificate-and-installing-it-when-not-having-access-to-port-80

**Comment by a15ponja** [comment]
Solved in #3473
