### ISSUE TITLE
Back arrow after login - bug

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3479]
When you log in, go to any page and then use the back arrow on the page (not the browser itself) you don't get redirected to the previous page. Instead you get an error message asking you if you want to resend the form. The page should not try to resend the data when the back arrow is used, just send you back the the previous page.

@a15freku Could this be something for you to solve?

**Comment by a15freku** [comment]
@b15sarha Was this something you worked with earlier? if so do you want to solve this issue?

**Comment by b15sarha** [comment]
This issue is already solved, the navigation through the pages should work fine. Upon pressing the 'back arrow' you should be redirected to the previous page.
