### ISSUE TITLE
Show/hide button in Section editor needs to show/hide all moments, even when some are collapsed

### ISSUE THREAD

**Issue by a15andau** [HGustavs/LenaSYS#3492]
Right now the show/hide button collapses and shows all moments but if a moment is collapsed and the button is pressed, it will collapse all moments, except the already collapsed section, which will un-collapse again.

**Comment by a15mikla** [comment]
There is still an issue with the toggling for the arrows. They dont toggle correctly if you for example have one section hidden and then choose to hide all sections. I will create a new issue for this.
