### ISSUE TITLE
Selected objects not deleted when clicking "Delete object"

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3498]
When a user selects more than one object and clicks the "delete object"-button they're not all removed at once, objects are removed pne-by-one. This means the button has to be clicked several times before everything selected is gone.

**Comment by a15perbl** [comment]
Issue resolved.

**Comment by a15chrau** [comment]
Issue stopped working after merge

**Comment by b15matki** [comment]
Reopened issue due to the function not working as intended anymore,

**Comment by a15perbl** [comment]
Issue is now resolved again.
