### ISSUE TITLE
Clean up unneeded JS files.

### ISSUE THREAD

**Issue by c14caran** [HGustavs/LenaSYS#3510]
In the /shared/js/ folder there are many js files that are not used anywhere in the system.

Files in /shared/js/:
* jquery-1.11.0.min.js - IN USE
* jquery-ui-1.10.4.min.js - IN USE
* three.min.js - IN USE
* jquery-1.5.1.min.js - No usage found, everything uses jquery-1.11.0.min.js
* jQuery-Core-1.10.2.js - No usage found, everything uses jquery-1.11.0.min.js
* jquery-ui-1.10.4.custom.min.js - No usage found, everything uses jquery-ui-1.10.4.min.js
* jquery.datetimepicker.js - No usage found, the date picker in use is from jquery ui
* jquery.js - No usage found, everything uses jquery-1.11.0.min.js
* Preload.js - No usage found, broken file
* tooltips.js - No usage found, if any tooltips are needed in the future, maybe use the one in jquery ui instead

This usage analysis is only for files available in this repository, there might be other usages in custom dugga templates, make sure to ask teachers for confirmation about usage in those.

**Comment by a15timbe** [comment]
Solved in #3536
