### ISSUE TITLE
Create dropdown menus for each student and group in the group editor

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3515]
The group in the dropdown associated with a student and moment should be `selected`. 

The dropdowns will replace the current method of display, where there is the value false when no group is associated, and a integer for the group id when a group is: 

![capture](https://cloud.githubusercontent.com/assets/26713381/25660423/6bcd7504-300c-11e7-9afc-98d038d4dc73.PNG)

**Comment by a15timbe** [comment]
Solved in #3522
