### ISSUE TITLE
Style the group editor page

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3524]
Some suggestions: 
* Smaller font for the dropdown menus
* Every other row in gray
* Borders for the cells
* Minor/light highlight of the `<select>` that belongs to a group (i.e does have the selected attribute)

For reference, this is how the page looks before styling: 
![capture](https://cloud.githubusercontent.com/assets/26713381/25663788/e26d4764-3018-11e7-9e33-543305578d5f.PNG)

**Comment by HGustavs** [comment]
Standardize styling across dialogs.

Find some dialog that has a similar layout and reuse the styling from there.

**Comment by a15alica** [comment]
The groups should be unique with a groupname (e.g. Group 1, Group 2 or Group A, Group B) and a moment in a course (e.g. Biträkningsduggor 1HP). In the dropdowns you should be able to pick which group a student should belong to and my suggestion is that the students not placed in a group should be highlighted somehow. For example the "Pick a group" option could have a different background color.

**Comment by a15timbe** [comment]
Solved in #3638
