### ISSUE TITLE
When adding many duggas the design breaks

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#3529]
![break](https://cloud.githubusercontent.com/assets/26705670/25694696/0f179e62-30b0-11e7-8ac5-313fe84cd24e.png)

Remove duplicated headers the th-tags is sufficient enough.

**Comment by HGustavs** [comment]
Are we progressing on this issue or is it no longer relevand?

**Comment by HGustavs** [comment]
furthermore, adding many variants is also important to investigate if it causes any problems.

**Comment by a15freku** [comment]
The problem has been solved.
