### ISSUE TITLE
Different behavior on buttons on android and iOS

### ISSUE THREAD

**Issue by a14phili** [HGustavs/LenaSYS#3533]
As you can see in the screenshots below different OS has different behavior.

On android it looks the same as on the computer
Nothing needs to change with that
![android](https://cloud.githubusercontent.com/assets/26705978/25695038/ceb66edc-30b1-11e7-9470-97e585f9d0cc.jpg)

But on iOS the buttons change form, color and position.
This should be change. It shouldn't change behavior in iOS
![iphone](https://cloud.githubusercontent.com/assets/26705978/25695042/d40bbaf4-30b1-11e7-98d5-fb01afb2bc09.jpg)

**Comment by HGustavs** [comment]
Not super important but I do prefer that the interface is as standardized as possible across platforms.

**Comment by b18gussv** [comment]
On iOS it looks like on computer browser.
![bild](https://user-images.githubusercontent.com/49142342/79458819-a9743580-7ff2-11ea-90d8-dd871d4e2d61.png)

**Comment by a18filkr** [comment]
On android it looks just like iOS that b18gussv posted, the warning that makes the navbar looks bad has nothing to do with this issue but should be fixed.
