### ISSUE TITLE
The changegroup() function in grouped.js should make a AJAXRequest

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3534]
The new AJAXRequest should put the current user in a group in the database.

**Comment by b15matol** [comment]
The AJAXRequest should do the following updates, as stated in the grouped.js file:

Make a query (two really) to the AJAXRequest function to insert (or update) those mappings: 
* uid to ugid assignment in user_usergroup
* ugid to lid assignment in usergroup_listentries

Should be something like: 

`AJAXRequest("UPDATE", data, "GROUP"); `, where data contains the new assignments. 

And of course corresponding code in the groupedservice.php file to handle the request.

**Comment by a15timbe** [comment]
Solved in #3853
