### ISSUE TITLE
Styling of onmouseover event in marking view

### ISSUE THREAD

**Issue by a15freed** [HGustavs/LenaSYS#3537]
The yellow border should be removed since the first row looks messed up.
Either remove the function "cellin()" from the TD element or change the color to transparent but only in this view when no filter is checked.

What do you think @HGustavs ?

![image](https://cloud.githubusercontent.com/assets/26706932/25695989/b68cd75c-30b5-11e7-91f9-64d611b73d2b.png)

**Comment by a15freed** [comment]
Update after merge

![image](https://cloud.githubusercontent.com/assets/26706932/25736261/1181f2e4-3171-11e7-95d1-454cd8bb9070.png)

**Comment by HGustavs** [comment]
Looks like the position of the highlighting div is not read/computed correctly from the table?

**Comment by d15eriso** [comment]
Also on a side note, should the text "Results" and the white border around it be that big? It seems uneccecary to have it take up that much space. @HGustavs

**Comment by a15ponja** [comment]
This one seems to have been solved by group 3.
