### ISSUE TITLE
Need testfiles in the .md-format in installscript as testdata

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#3561]
This issue depends on #3582 to be solved.
Testing markdown for php requires testfiles with the .md-extension. 4 Files should be included in the installscript in the "DuggaSys/templates" folder; block.md, unordered-list.md, ordered-list.md and table.md.

**Comment by d15johro** [comment]
content comming soon...

**Comment by a15eriho** [comment]
It would be good if you could create the files, since you know how they should look like. Then put them in "LenaSYS/install/md", then comment on where you want the files to be placed.

**Comment by a15ramha** [comment]
issue #3582 is now solved. this issue can now be implemented. @a15eriho

**Comment by b15linek** [comment]
I will copy all files in install/md to DuggaSys/templates in installation. Is that correct?

**Comment by b15linek** [comment]
There is a file called unordered-list.md already in duggasys/templates. Can this be removed to make room for the one in install/md?

They have different content. Which one is correct?
The one in install/md:
<img width="173" alt="screen shot 2017-05-12 at 12 27 46" src="https://cloud.githubusercontent.com/assets/26706647/25993897/ef5ba804-370b-11e7-9ec2-26a27dd5a102.png">

The one in duggasys/templates:
<img width="738" alt="screen shot 2017-05-12 at 12 28 18" src="https://cloud.githubusercontent.com/assets/26706647/25993912/01fe4002-370c-11e7-9681-51142fc826c8.png">

**Comment by b15linek** [comment]
Removed old one to make place for the new one in install/md.
