### ISSUE TITLE
Dialog window needs to display set values

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3564]
When the relation symbol is doubleclicked and the dialog window appears the latest saved settings aren't displayed. It would be better if these did displayed the current values to not confuse the user.

**Comment by a15gunfu** [comment]
Was fixed together with issue #3355 and already merged in. So the set values are all saved when user doubleclick the relation symbol.

**Comment by a15perbl** [comment]
Issue is now resolved after discovering the fix didn't merge in along with another issue after all.
