### ISSUE TITLE
Extend Show/hide function to entire section

### ISSUE THREAD

**Issue by a15andau** [HGustavs/LenaSYS#3565]
Make entire section (where course name and course code is displayed) clickable, just like when a single moment is hidden or is showing.

**Comment by a15andau** [comment]
Is this even wanted or needed @HGustavs ?

**Comment by HGustavs** [comment]
Course name and course code should always be visible.

A Screenshot cold help to remove some confusion as to what we are about to do.

Does not sound very necessary IMHO but feel free to sway my opinion using a screenshot.

**Comment by a15andau** [comment]
What I meant was; if it is desirable to be able to show/hide all moments (which is the function of the Hide/show all arrow (see screenshot) by clicking any part of the section that contains the course name and course code (they will stay visible) @HGustavs ?

<img width="1271" alt="skarmavbild 2017-05-05 kl 10 20 10" src="https://cloud.githubusercontent.com/assets/26709847/25738331/c34daeea-317c-11e7-8e28-0460822dd76d.png">

**Comment by HGustavs** [comment]
I think it is fine as it is.

**Comment by a15andau** [comment]
Ok, i'll close this issue then.
