### ISSUE TITLE
The font of the 'show/ hide collapse' looks weird.

### ISSUE THREAD

**Issue by b15sarha** [HGustavs/LenaSYS#3574]
<img width="1228" alt="skarmavbild 2017-05-05 kl 10 05 20" src="https://cloud.githubusercontent.com/assets/25817750/25737985/ef36757a-317a-11e7-8d29-59714a4b771a.png">

**Comment by a15wilhe** [comment]
the text "Show/hide all" is showed by a text tag what now that is in html... The font-size 14px is now applied and maybe the tag should be swittch to a span to solve this.

**Comment by a15wilhe** [comment]
Solved with pr #3587
