### ISSUE TITLE
Modal pixel is wrong which making it go above the screen and can't be seen

### ISSUE THREAD

**Issue by a15ramha** [HGustavs/LenaSYS#3580]
Cant reach the other options in the box. The pixels should be changed to 300 px from 100 px.
<img width="1109" alt="skarmavbild 2017-05-05 kl 10 29 41" src="https://cloud.githubusercontent.com/assets/26706764/25738489/c9d2114c-317d-11e7-8d3d-8d2e8b802311.png">

**Comment by b15sarha** [comment]
Already solved.
