### ISSUE TITLE
put .md-files in the install folder so that it can be used in installscript

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#3582]
the files should looks something like this:

**block.md** (the text is just an example text and can be whatever. it's the markdown-symbols that are important) 
![block](https://cloud.githubusercontent.com/assets/26705142/25715789/0b7738f6-30fd-11e7-8394-6dbd2ee004e7.png)

**unordered-list.md**
![unordered-list](https://cloud.githubusercontent.com/assets/26705142/25715839/3753a2a2-30fd-11e7-8590-1ae81be5c452.png)

**ordered-list.md**
![ordered-list](https://cloud.githubusercontent.com/assets/26705142/25715814/2b80b096-30fd-11e7-9481-dbf61d07313a.png)

**table.md**
![table](https://cloud.githubusercontent.com/assets/26705142/25715828/32483fac-30fd-11e7-8478-e37420178d41.png)

Notice the extra empty new line in every picture, this is required.

**Comment by a15ramha** [comment]
This issue is solved
