### ISSUE TITLE
Comments in group duggas

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3598]
A suggestion for improvement in the group duggas: Maybe a comment field could be implemented where the students can write messages to the rest of the group members. This could be just being able to add a comment when an assignment is handed in or more like a forum where everyone in the group could write messages or questions to the other students.

**Comment by a18kaswi** [comment]
yes yes alica many mighty fine ideas. My group have also fine ideas, PRIORITIZE
