### ISSUE TITLE
Dialog box for editing duggas needs fixing

### ISSUE THREAD

**Issue by A15cecal** [HGustavs/LenaSYS#3611]
When clicking on the cogwheel to edit a dugga the box appears too far up and you can't see the whole thing, and you can't scroll up to it either.
![h](https://cloud.githubusercontent.com/assets/26705134/25794416/119d3506-33d1-11e7-9395-d45b7ebf0d25.JPG)

**Comment by b15sarha** [comment]
synca upp din mapp, problemet är löst, pull-request @#3573.
