### ISSUE TITLE
Cookies everywhere on the menu section, bug!

### ISSUE THREAD

**Issue by b15sarha** [HGustavs/LenaSYS#3614]
<img width="1241" alt="skarmavbild 2017-05-08 kl 09 29 19" src="https://cloud.githubusercontent.com/assets/25817750/25794580/d26cf230-33d1-11e7-8284-8844f4b45e13.png">

**Comment by c14caran** [comment]
Have you tried doing a hard refresh (with ctrl+F5)? It looks like your css file is outdated.

**Comment by a15freku** [comment]
See #3869
