### ISSUE TITLE
Style the "show/hide all" option, it needs more space

### ISSUE THREAD

**Issue by A15cecal** [HGustavs/LenaSYS#3628]
The text needs some more space.

![h](https://cloud.githubusercontent.com/assets/26705134/25798915/48f3c6de-33e3-11e7-8183-6cbc5ddd4a24.JPG)

**Comment by a15andau** [comment]
This has been solved in issue #3553 and #3608 (after latest merge) so you can close it.

**Comment by A15cecal** [comment]
@a15andau This still looks the same?

**Comment by a15andau** [comment]
I meant that this got fixed after latest merge so the fix won't show up until after next merge.

<img width="282" alt="skarmavbild 2017-05-09 kl 09 21 39" src="https://cloud.githubusercontent.com/assets/26709847/25839677/f3f36b42-3498-11e7-9be3-b5efe09a6e28.png">

**Comment by A15cecal** [comment]
Now I'm with you. Closing.
