### ISSUE TITLE
Class object moves to the right when scaling.

### ISSUE THREAD

**Issue by b15matki** [HGustavs/LenaSYS#3657]
At this moment when moving the top-left corner(TL) to the right of the bottom-right corner(BR) the class object "jumps" a certain distance to the right to compensate.

This function should be revised so that when a user moves to TL to the left it stops when the object is a certain width. Similar to what happens if you move BR to the left of TL.

The middle divider should also be fixed so that it scales accordingly so that the user can read all the field in the class object.

**Comment by b15matgu** [comment]
The middle divider on the static class exemple code is movable but when creating a new class it's not possible. It seems like it's only moving the object and sort of "overriding" moving the point.

**Comment by c16jonha** [comment]
This issue will be solved through the solution of Issue #4868.
