### ISSUE TITLE
Create a similar button for sorting on grouped.php as it is in resulted.php

### ISSUE THREAD

**Issue by a15nikho** [HGustavs/LenaSYS#3681]
A button should be added in grouped.php in the navbar. The button should be the same as it is in resulted.php(like the picture below). When the button is clicked a dropdown-menu should open where it is possible to sort after firstname, lastname, username and ssn, but that is a later issue.
![sortering_knapp](https://cloud.githubusercontent.com/assets/26705128/25847889/403c3e88-34b8-11e7-85d5-7b1a2dfdf819.PNG)

**Comment by a15ponja** [comment]
Closed due to issue cleanup, not necessary anymore.
