### ISSUE TITLE
Display a dropdown-menu when the sorting button is clicked in grouped.php

### ISSUE THREAD

**Issue by a15nikho** [HGustavs/LenaSYS#3682]
A dropdown-menu should be displayed when the sorting button in grouped.php is clicked(sorting button will be created in issue #3681 ). The dropdown-menu should make it possible to sort on firstname, lastname, username and ssn(like the picture below).
![dropdown_sortering](https://cloud.githubusercontent.com/assets/26705128/25848177/73a71378-34b9-11e7-95f1-4921e348cfc8.png)

**Comment by a15timbe** [comment]
Partly solved in #3709

**Comment by a15timbe** [comment]
Solved in #3749
