### ISSUE TITLE
Make listentry-specific groups only appear below the correct listentry

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3688]
Right now groups that are assigned to a listentry is specified as a group for all listentries, which is not correct. It should only appear under the specified one. 

For example, "Festargruppen" is tied to listentry Biträkningsduggor 1HP, and should not be available under other listentries: 

![skarmavbild 2017-05-09 kl 14 56 42](https://cloud.githubusercontent.com/assets/26713381/25851869/ceb61684-34c7-11e7-8f05-8413a13c078f.png)

**Comment by a15timbe** [comment]
Solved in #3760
