### ISSUE TITLE
Button is overlapping 

### ISSUE THREAD

**Issue by a15freku** [HGustavs/LenaSYS#3691]
![overlapp](https://cloud.githubusercontent.com/assets/26705670/25853911/9044b03e-34ce-11e7-8488-da2aa3c71f57.png)

**Comment by a15freku** [comment]
Think it is related to the cookies

**Comment by A15cecal** [comment]
Seems to be browser related too, it works in chrome but not in firefox.

**Comment by a15freku** [comment]
the picture is from chrome

**Comment by A15cecal** [comment]
@a15eriho Maybe your group should look at this issue, seems to be related?

**Comment by A15cecal** [comment]
We will put this issue on hold until the merge is done. It might be that group 3 solved this already.

**Comment by a15eriho** [comment]
Still an issue after merge 11/5-2017. It did work after the merge the week before.
How it looks now: (left: before logged in; right: after logged in)
![dada](https://cloud.githubusercontent.com/assets/26706624/25966147/71eac8cc-368a-11e7-957f-27e70cc3fd5e.png)![dada2](https://cloud.githubusercontent.com/assets/26706624/25966149/7505c96c-368a-11e7-8b96-63d42cf482eb.png)
And this is how it looked before merge:
![dada3](https://cloud.githubusercontent.com/assets/26706624/25966214/ac6c7856-368a-11e7-88f2-87f8da0e506e.png)

**Comment by A15cecal** [comment]
@a15eriho Seems to be the media queries for cookiemsg that causes these problems, but without them the styling for mobile devices looks ugly. I think the rules collides with the queries on row 2166.
Work on this together maybe?
