### ISSUE TITLE
Change unclear variable names in code

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3693]
Many of the variables are named in such a way that it's not clear what they're used for. A lot of time is spent on figuring out where and when variables are used, if names were to be changed it would prevent a lot of confusion for both current and future developers.

**Comment by c16jonha** [comment]
Should this issue be closed? We've reverted some of the variable names in #4325

**Comment by c16jonha** [comment]
This issue is outdated and will now be closed.
