### ISSUE TITLE
Customization in dialog menu for lines

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3719]
A line can be doubleclicked and selected in the diagram but no customization can be done.

![bild](https://cloud.githubusercontent.com/assets/26705103/25891374/2377086e-3571-11e7-8800-c18eb4f7c864.png)

Having lines made customizable is better than altering the lines via entities or relations, especially when you only want a specific line to be doubled. As it is right now, all the lines connected to the entity and relations are doubled when the option 'weak' is picked.

The dialog menu for lines should be changed so that a user can pick if a line type should be weak or strong.

**Comment by a15perbl** [comment]
Issue resolved.

**Comment by b15matki** [comment]
Solution merged into the G4 branch!
