### ISSUE TITLE
Adding a new section/header works sometimes and sometimes it doesn't 

### ISSUE THREAD

**Issue by b15sarha** [HGustavs/LenaSYS#3720]
When trying to add a new header/section/code it works sometimes and when refreshing or changing the site it doesn't work.

**Comment by HGustavs** [comment]
What does the console say? Any unfamililar errors?

**Comment by b15sarha** [comment]
@HGustavs Thats the hard part of solving this issue, there is no error message.

**Comment by A15cecal** [comment]
@b15sarha Can't recreate this problem? I have no problem with creating a new section/header/code. Do you have some more information on this?

**Comment by b15sarha** [comment]
Well i tried on multiple students, all seem to have the problem, not been able to create anything/ and sometimes it works perfectly fine, i don't really get what the problem is, since there is no error. I tried to debug it, the values were all correct, as expected but the problem remains.

**Comment by A15cecal** [comment]
@b15sarha That's very odd. Does other groups have the same problem?

**Comment by HGustavs** [comment]
Could it be the test data installed with the system that differs between users?

**Comment by b15sarha** [comment]
@A15cecal Yes i checked with other grupps too, they seem to have the same problem. @HGustavs , could be, since this worked fine before.

**Comment by A15cecal** [comment]
@b15sarha @HGustavs This is really weird. Seems like everyone has this problem? But I don't. I have no problem creating things and they don't disappear for me, the things I created hours ago's still there, in all courses. Really can't recreate the problem listed here.
What browser do you use?

**Comment by A15cecal** [comment]
This is not a problem on the actual site. The problem described have to be some sort of local problem. Closing.
