### ISSUE TITLE
Diagram editor additional symbols

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3735]
Some symbols seem to be missing from a complete ER diagram.

* Dashed attribute lines (do we have that?) ..0, 
* Compund attributes e.g. attributes connected to other attributes
* Fill color and shadows (to indicate depth) for symbols (not in official notation)
* Arity symbols e.g. N and 1 printed near the connector

I would like to see an example diagram drawn from scratch e.g. the ER diagrams from page 206 and 225 in fundamentals of database systems (2014 edition).

https://image.slidesharecdn.com/03-ch3-notes-revised-1195929135473217-4/95/03-ch3-notes-revised-17-728.jpg?cb=1195900336

**Comment by a14pethu** [comment]
@a15perbl 

This issue should be split up.

**Comment by c16jonha** [comment]
All of the sub-issues of this issue has been closed and this issue is now solved.
