### ISSUE TITLE
Diagram editor test/demo diagram

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3737]
We need a test / evaluation diagram that we can work with for testing purposes.

The current "demo" diagram is not very complete.

I suggest using the diagram from

**Comment by HGustavs** [comment]
issue #3735 as a base for a testing diagram.

We can then distribute this to allow for more testing of problems in a more realistic diagram.

**Comment by c16jonha** [comment]
This issue seems outdated and not so relevant anymore.
