### ISSUE TITLE
Basic UML diagram support

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3739]
We need to create support for more UML diagram constructs

* Quantified relationships
* Arity symbols and stereotypes on classes ()
* Recursive relationships
* Text boxes or dropdowns for arity symbols e.g. 1..4 using text boxes or dropdowns for upper and lower bounds independently.

https://image.slidesharecdn.com/chapter-7-160719190219/95/fundamentals-of-database-system-data-modeling-using-the-entityrelationship-er-model-40-638.jpg?cb=1468954970

**Comment by HGustavs** [comment]
Relationship classes and aggregates do not seem to be supported?

**Comment by c16jonha** [comment]
To make sure that this issue is still relevant, it will be split up into smaller, newer issues.
