### ISSUE TITLE
Recursive relationships in ER Daigrams

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3740]
Recursive relationships in ER Daigrams ...

**Comment by c16jonha** [comment]
Care to elaborate on this issue @HGustavs ?

**Comment by c16jonha** [comment]
This is not an issue since it is possible to create recursive relationships in the Diagram.

![yes](https://user-images.githubusercontent.com/37794047/39130522-91704106-470d-11e8-80cc-548169863c56.PNG)
