### ISSUE TITLE
Align support in diagram

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3745]
If we select more than one symbol we sould be able to do aligment like in illsutrator.
![screenshot 2017-05-10 14 43 34](https://cloud.githubusercontent.com/assets/6978801/25899166/1dcdee00-358f-11e7-9192-f9e671408059.png)

**Comment by a15perbl** [comment]
Issue resolved!

**Comment by a15chrau** [comment]
Found a minor code error that should produce a bug. It'll be hotfixed in the implementation of #4024 

Instead of iterating through selected objects for the align, it iterates through diagram objects, only aligning the first objects within the diagram array, no matter what objects you select.
