### ISSUE TITLE
Diagram locking of objects

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3747]
It should be possible to lock objects much like in adobe illustrator.... by clicking the lock icon the object is still visible but cannot be clicked or changed by mouse/keyboard/button actions

![screenshot 2017-05-10 14 45 45](https://cloud.githubusercontent.com/assets/6978801/25899264/75558f66-358f-11e7-9a1b-034c992bf91d.png)

Perhaps some kind of a view like in illustrator that shows all objects in a list would be useful for "locking" diagram objects

**Comment by c16jonha** [comment]
We will create a checkbox in the appearance menu that allows the user to lock the object.
