### ISSUE TITLE
Multiple selection sets

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3751]
If I do a box-select in the diagram e.g. select multiple object, can I move these objects as a grou or e.g. delete the whole group?

Any "locked object" see previous issue should not be affected by group selection.

**Comment by a15perbl** [comment]
It is possible to move and delete multiple objects as a group if they're all selected. Functionality for locking objects however does not exist yet.

**Comment by HGustavs** [comment]
It would be great if you could post a lnkt ot the "bleeding edge" version so that I can run some tests and see what the newest version is missing when it comes to selections.

**Comment by b15matki** [comment]
Here's a link to an up-to-date version of our site : http://webblabb.iit.his.se:8080/grupp4/b15matki/LenaSYS/DuggaSys/diagram.php (2017-05-10 15:28)

**Comment by c16jonha** [comment]
This does not seem to be relevant anymore and will be closed.
