### ISSUE TITLE
Set a max/min value for zooming

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3753]
Zooming in/out can be done an infinite amount of times right now. Zooming should be limited, e.g set the maximum zoom in to 200% and zoom out value to 50%.

**Comment by HGustavs** [comment]
i say minimum 5% and maximum 1600% seems about enough.

**Comment by HGustavs** [comment]
Not necessarily 10% increments, perhaps from a list of values e.g. 5% 10% 20% 30% 50% 75% 100% 125% 150% 200% 400% 600% 800% 1000% 1200% 1400% 1600% ??

**Comment by a15perbl** [comment]
Original issue resolved. A new issue has been opened about adding the list of values (#3764)
