### ISSUE TITLE
Default size of relationship not even multiple of default size of entity

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3756]
If we have enabled snap to grid.... and create an entity and a relationship symbol....

They are not aligned, since the middle of the relationship does not coincide with the middle of the entity and the line is thus not straight, but at an angle.

...

![screenshot 2017-05-10 16 59 46](https://cloud.githubusercontent.com/assets/6978801/25905445/5b2422a2-35a2-11e7-895f-b2befc5b23e5.png)

**Comment by b15matki** [comment]
Solution merged into G4.
