### ISSUE TITLE
Mode specific drawing tools

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#3757]
When drawing an entity we see a rectangle.... fair enough, but when we draw an attribute we dont see an oval but a rectangle when drawing.... same thing for the lines, we want to see a line, not a rectangle while drawing.

I like the stippling, but I would rather see an oval or a stippled line instead of the stippled rectangle regardless of the shape that one is drawing...

![screenshot 2017-05-10 17 08 16](https://cloud.githubusercontent.com/assets/6978801/25905898/7087f870-35a3-11e7-8e23-c834d0332100.png)

**Comment by a15perbl** [comment]
Issue resolved.
