### ISSUE TITLE
Add a funnel button on grouped.php

### ISSUE THREAD

**Issue by a15nikho** [HGustavs/LenaSYS#3780]
A funnel button should be created in grouped.php. The button should be placed to the left of the sort button in the navheader. The funnel button will make it possible to only display a specifik moment in the table on grouped.php. When hovering on the funnel button a dropdownlist should be displayed with every moment that are saved as a "Gruppdugga" or "Gruppseminarie".

**Comment by a15timbe** [comment]
Solved in #3823
