### ISSUE TITLE
When 'New Group' is clicked the correct moments should be displayed in the first select-field

### ISSUE THREAD

**Issue by a15nikho** [HGustavs/LenaSYS#3786]
A query to the database needs to be created to make it possible to show proper information in the select-field. The database is not used at the moment to show the correct moments which makes it show the wrong information.
![ny_grupp](https://cloud.githubusercontent.com/assets/26705128/25939528/7b376fd6-3633-11e7-9d32-b1fcb5b982ac.PNG)

**Comment by a15timbe** [comment]
Solved in #3816
