### ISSUE TITLE
Styling of onmouseover event in Groups

### ISSUE THREAD

**Issue by a14phili** [HGustavs/LenaSYS#3787]
There should be a yellow border around the column in table when you hover it in Groups.

Following examples are from Results but it should look the same way in Groups when you hover a column and row.

Yellow border when you hover a column that is selected/pressed
<img width="370" alt="skarmavbild 2017-05-11 kl 10 14 19" src="https://cloud.githubusercontent.com/assets/26705978/25939306/a8103cb4-3632-11e7-94dd-7f8ae243f4e8.png">

Purple border when you hover a column that is not selected/pressed
<img width="364" alt="skarmavbild 2017-05-11 kl 10 18 23" src="https://cloud.githubusercontent.com/assets/26705978/25939459/3ea1f5f0-3633-11e7-8d25-3126057e8e4c.png">

There should also be a horizontal border as you can see in both photos. It shows what row you are hover. That border should be black.

**Comment by a14phili** [comment]
The border is not working as it should. Border should end as the table ends. 
Issue for this is #3537

**Comment by a14isshi** [comment]
As most parts of the earlier implementation of groups were deleted, this issue is no longer relevant and therefore closed.
