### ISSUE TITLE
Groups tied to a listentry can show up under the wrong listentry in the group editor

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3789]
For instance "Coola gurppen" (ugid 2) is showing up under listentry "Geometri 2HP" (lid 2007), while it should show up under "Frågeduggor 1HP" (lid 2013). Very strange.

**Comment by a15timbe** [comment]
Solved in #3760

**Comment by HGustavs** [comment]
Screenshot plz.

**Comment by b15matol** [comment]
Hello @HGustavs, this is now resolved. Here is some screenshots anyway, we can see that groups are now correctly tied to their listentry. 

(Those are columns for the same student, had to take separate screenshots to display the available options for each listentry.) 

![skarmavbild 2017-05-12 kl 19 10 40](https://cloud.githubusercontent.com/assets/26713381/26008911/f6f2e2ea-3746-11e7-99c8-3d72f16ff020.png)
![skarmavbild 2017-05-12 kl 19 11 02](https://cloud.githubusercontent.com/assets/26713381/26008912/f71a6fb8-3746-11e7-92c1-59f45fa963bc.png)
![skarmavbild 2017-05-12 kl 19 11 15](https://cloud.githubusercontent.com/assets/26713381/26008913/f71c2bb4-3746-11e7-941b-6dcfd619b991.png)

Before, all of those groups would have appeared as possible options for all of the listentries. That would have been rather chaotic after a while.

**Comment by b15matol** [comment]
It is possible that this problem had to do with a sorting in the SQL query on grouptype. The issue can remain open until next week (when the testdata is applied to the database), if the problem would occur again.

**Comment by a15magkn** [comment]
Since this seems to be a bug related to the Group Editor this issue will be closed, seeing as how the Group Editor has been deleted.
