### ISSUE TITLE
Cardinality - ER-notation

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3793]
As described in the root issue, symbols should appear when ER-entities are connected. These symbols should also be customizable - perhaps a list could appear when you doubleclick the cardinality symbol? The list should contain the values "1", "N" and "M".

![bild](https://cloud.githubusercontent.com/assets/26705103/25940481/8e80247c-3636-11e7-99c1-bcee59c651a3.png)

If there's a better way to implement this feel free to suggest it.

root issue  #3782

**Comment by HGustavs** [comment]
Perhaps in a dialog, when double clicking the arity symbol a dialog should appear, you should als obe able to assign a role name to each arity. For example if the entities were management and employee - the N side could read N above the line and "Subordinate" and on the 1 side it could read 1 on top of the line and "Boss" below it.

Also, while I am at it, adding attributes to the relationship symbol, does that work?

**Comment by a15perbl** [comment]
Now cardinality when connecting entities to relations exist, however it's not completely solved. Leaving issue open.
