### ISSUE TITLE
Arrows for showing collapsed or hidden content toggles wrong in sectioned

### ISSUE THREAD

**Issue by a15mikla** [HGustavs/LenaSYS#3836]
If you have one section hidden and then choose to hide all sections the arrow toggles wrong. The arrow toggles to show that the section is showing instead of keeping it's state of hidden.

Image to clarify:
<img width="356" alt="111" src="https://cloud.githubusercontent.com/assets/26705198/25990192/23a8fbfa-36ff-11e7-93ff-16dd41a34992.png">

**Comment by a15andau** [comment]
Solved and merged. Closing
