### ISSUE TITLE
Overlaps in Section Editor in mobile view

### ISSUE THREAD

**Issue by a15andau** [HGustavs/LenaSYS#3837]
In mobile view the name of course and the show/hide all text overlaps each other.

See image:
<img width="302" alt="skarmavbild 2017-05-12 kl 11 02 20" src="https://cloud.githubusercontent.com/assets/26709847/25991315/09b39d46-3703-11e7-81df-1f8de365adf1.png">

**Comment by a14phili** [comment]
solved #3879
