### ISSUE TITLE
Graphical bug in the grid/list in result-view

### ISSUE THREAD

**Issue by d15eriso** [HGustavs/LenaSYS#3839]
The cells in the list in result-view does not align with the borders of the list and "pops up" like in the picture below:
![image](https://cloud.githubusercontent.com/assets/26739514/25991820/f8709280-3704-11e7-8c15-f53f43f8ccf0.png)

This does not look nice.

**Comment by HGustavs** [comment]
As this is the most important view of all, it is a priority to fix this.

One suggestion is to test it in more than one browser e.g. forefox,chrome, edge and see how it looks. The only browser that it is allowed to break in is Internet Explorer (for obvious reasons).

**Comment by a14phili** [comment]
#3537 Same issue

**Comment by a14phili** [comment]
At the end of the list
<img width="411" alt="skarmavbild 2017-05-15 kl 11 30 27" src="https://cloud.githubusercontent.com/assets/26705978/26051287/036b7af6-3962-11e7-9a94-5cde547a7e9d.png">

**Comment by a14phili** [comment]
solved and merged #3979

**Comment by a15freed** [comment]
this is solved
