### ISSUE TITLE
Make the restults page and the groups page more similar

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3845]
I would like to add coloring to the lines in the results page to make it easier to see which line belongs to which student. The picture below shows what the groups page looks like at the moment and I would like to use the same kind of coloring scheme in the results page.

![image](https://cloud.githubusercontent.com/assets/26705108/25992469/e4c7c666-3706-11e7-8dbd-d66abab0802b.png)

In issue #3787 we want to add the borders from the result page into the groups page too.

By combining these two issues I believe both pages will look good, be easy to get an overview of and be pleasant to use.

**Comment by a15timbe** [comment]
Solved in #3947
