### ISSUE TITLE
Make progress bar dynamic for window re-sizing.

### ISSUE THREAD

**Issue by b15linek** [HGustavs/LenaSYS#3847]
Right now the progress bar is incorrect if window gets re-sized during installation. This could be fixed.

**Comment by HGustavs** [comment]
Screenshot plz.

**Comment by b15linek** [comment]
This happens is window gets resized (shold be full):
![namnlos](https://cloud.githubusercontent.com/assets/26706647/25997795/1a72b390-371e-11e7-9600-e311e4f8b70a.png)

**Comment by a14phili** [comment]
solved and merged #3883
