### ISSUE TITLE
Be able to change set grade from G -> U

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3848]
If a dugga has been, accidentally, graded G and the teacher needs to change it to U this is not possible at the moment. This should be implemented but it should only be possible for a short duration of time after set grade.

**Comment by HGustavs** [comment]
Control+Click or some other similar action ... perhaps also combined with a time limit but not a too-short-one e.g. 15 minutes is too short - for example one day, may be acceptable or 4 hours or something like that.

**Comment by a15ponja** [comment]
Fixed with #4092.
