### ISSUE TITLE
Lock student names in results and groups pages

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3849]
The student names in the tables on the results and groups page should be visible at all times. If you scroll horizontally (to view all moments) the names should stay at the same place. If you on the other hand scroll vertically (to view all students) the list should scroll like it does now.

**Comment by HGustavs** [comment]
Currently the headings work correctly in your version ?

![screenshot 2017-05-12 13 15 43](https://cloud.githubusercontent.com/assets/6978801/25995997/35e0faf0-3715-11e7-9a2b-2349d25a6da9.png)

On the live-site it works for the headings that attach below the menu when scrolling out of view....

We want the same for the number column and the student name column when scrolling left-right.

Im thinking that the javascript can be adapted/copied/rewritten to also handle the number and name columns ...

**Comment by a16linas** [comment]
This feature is already implemented, therefore closing the issue.
