### ISSUE TITLE
The text inside an object should always be inside the object.

### ISSUE THREAD

**Issue by b15matki** [HGustavs/LenaSYS#3864]
At this moment it is possible for the text within an object to exist outside the object itself. An example could be seen below:

![textoutside](https://cloud.githubusercontent.com/assets/26705132/25997410/27ddd4d0-371c-11e7-9c5c-1062a46bace8.png)

The text should be within the object similar to this:

![text inside](https://cloud.githubusercontent.com/assets/26705132/25997464/64c2a650-371c-11e7-9d68-cbd6e5c69a5f.png)

This could be solved either by resizing the object or decreasing the size of the text.

**Comment by HGustavs** [comment]
Clipping is the solution.

The text should be drawn with clipping enabled.

**Comment by HGustavs** [comment]
Basically Like This
~~~
		// Draw Box Outline

		ctx.beginPath();		
		// Draw Box Outline (Again, same outline as alredy drawn but this time only the outline and it will be used for clipping only)
		ctx.closePath();	
		ctx.save();
		ctx.clip();
  		// Draw Text
   		ctx.restore();
~~~

Same code basically, for entity, relation, attribute, class etc. etc.

**Comment by c16jonha** [comment]
This doesn't seem to be an issue anymore. I will therefore close this issue
