### ISSUE TITLE
Move the "cookie-bar" so it won't cover the buttons.

### ISSUE THREAD

**Issue by b15matki** [HGustavs/LenaSYS#3872]
The cookie-bar in diagram.php currently lies on top of the buttons which makes it hard for users to select the buttons. 

The cookie-bar needs to be either moved or revised so it won't interfere with the selection of buttons.

**Comment by a15chrau** [comment]
This is likely caused from when Group 2 added a cookie bar #2758

**Comment by a15perbl** [comment]
There's already an issue related to this I believe. ( #3840 )

**Comment by b15matki** [comment]
Correct, due to this issue being duplicate the issue will be closed. The original issue #3840 .
