### ISSUE TITLE
Change position of "zoom" and "start moving" button

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3914]
Currently the "zoom"-window and "start moving"-button are placed on a fixed position in the browser. Since the coordinates are placed on the bottom left corner of the canvas, these should too be placed inside the canvas. 

![bild](https://cloud.githubusercontent.com/assets/26705103/26096000/0498843c-3a20-11e7-80d7-db0758f66148.png)

"Start moving" should be placed on the top right corner and the zoom should be placed in the bottom right corner.

![bild](https://cloud.githubusercontent.com/assets/26705103/26096215/b4816b02-3a20-11e7-99fd-b7a30c855d78.png)

**Comment by b15matgu** [comment]
This is fixed in issue #3940.
