### ISSUE TITLE
weird margin-top on headings in css presented in markdown

### ISSUE THREAD

**Issue by d15johro** [HGustavs/LenaSYS#3916]
parsed markdown have weird margin-top on headings. For example the h4 tag have a margin of "1px 0px 8px 0px" which makes the break-line tag above it useless. Also, the heading merges with the text above which makes it look semantically incorrect.

**Comment by d15johro** [comment]
how it looks:
![bug-css](https://cloud.githubusercontent.com/assets/26705142/26096674/3f4c7654-3a22-11e7-8436-40f5ce784956.png)

increased top margin by 10px: 
![bug-css-fixed](https://cloud.githubusercontent.com/assets/26705142/26096706/60001e6e-3a22-11e7-89b2-6e196059602a.png)

**Comment by d15johro** [comment]
what do you think? @HGustavs

**Comment by HGustavs** [comment]
What is the difference?

Or is it that there is no difference?

**Comment by HGustavs** [comment]
Now I get it...

Yes the bottom one seems more semantically correct?

**Comment by HGustavs** [comment]
It should work mostly as "pre" e.g. a single normal line feed makes a line feed.

**Comment by d15johro** [comment]
I don't understand. What's the preferred way of solving this issue? Changing the css of headings might effect code elsewhere and the "br" doesn't seem to have any effect?

**"br" above and under headings:**
![asd](https://cloud.githubusercontent.com/assets/26705142/26100593/a317a1ac-3a2e-11e7-8709-bc3bb229f24b.PNG)

@HGustavs

**Comment by a15freku** [comment]
Solved
