### ISSUE TITLE
File size shown as 0 bytes for example files in fileed

### ISSUE THREAD

**Issue by a15jorpa** [HGustavs/LenaSYS#3929]
When viewing uploaded files in a course the file size for all the example files is listed as 0 bytes. The files I upload get a size that is close to what my own computer gives.

**Comment by HGustavs** [comment]
I would say that this is a prioritized issue.

Does this happen for the demo data or only when uploading new files, it may have to do with the test data, any new uploaded files or a combination....?

**Comment by a15jorpa** [comment]
It only affects the demo data. I looked into it, it appears that the filesize defaults to 0 in the filelink table and is not set in the demo data SQL.

**Comment by c16linst** [comment]
We are closing this issue since this is a problem with the inserted test data and not with the actual webpage.
