### ISSUE TITLE
When a group iss assigned in the group editor, where is no way to change it again without refreshing the page

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3930]
This is because a _oldUgid_ in the id attribute of the `<select>` is thrown into the service file. When a `onchange()` occurs, this oldUgid is not changed in the id, so the old group data is still in the id of the select. This obviously wont do any updates in the database. 

When a onchange() occurs, the id must be updated to reflect the new group assignment of the student.

**Comment by a15timbe** [comment]
Solved in #4002
