### ISSUE TITLE
Add depth to figures

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3937]
To indicate depth, the ability to give figures shadows needs to be implemented. An option should be added to the already existing dialog menu where a user can adjust the shadow.

#3735 root issue

**Comment by HGustavs** [comment]
~~~
ctx.save();
ctx.shadowBlur = 8;
ctx.shadowOffsetX = 4;
ctx.shadowOffsetY = 4;
ctx.shadowColor = "#000";
ctx.fill();
ctx.restore();
~~~

**Comment by HGustavs** [comment]
One set of shadow parameters for all of the document, not individual shadow parameters for each object.

**Comment by c16jonha** [comment]
this issue is now fixed and will now be closed. See #4287 for more information.
