### ISSUE TITLE
When there are more than one group assigned to a lid, still only one group is available in the dropdown list

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#3951]
In Lena it looks like this: 
![skarmavbild 2017-05-16 kl 16 21 03](https://cloud.githubusercontent.com/assets/26713381/26110845/c454109c-3a53-11e7-90ad-7fa15097a4d5.png)

In the database it looks like this: 
![skarmavbild 2017-05-16 kl 16 20 42](https://cloud.githubusercontent.com/assets/26713381/26110844/c4512abc-3a53-11e7-970c-62e38f67a3fd.png)

Färgduggor is lid 2004, hence the dropdown should contain the groups: 
* test
* 1
* 2

But it does not as of now.

**Comment by a15timbe** [comment]
Solved in #3952
