### ISSUE TITLE
Fix so that the course name of the course does not come across show/hide all

### ISSUE THREAD

**Issue by b14marki** [HGustavs/LenaSYS#3953]
Fix so that the course name of the course does not come across show / hide all.

**Comment by a15andau** [comment]
This might have been solved in issue #3938

**Comment by a15andau** [comment]
<img width="300" alt="skarmavbild 2017-05-17 kl 09 10 26" src="https://cloud.githubusercontent.com/assets/26709847/26142421/b5600f18-3ae0-11e7-8142-6f59ea87c096.png">
