### ISSUE TITLE
Only activate language support checkboxes when testdata is checked.

### ISSUE THREAD

**Issue by b15linek** [HGustavs/LenaSYS#3957]
You should only be able to check the checkboxes for language support and markdown if the checkbox to include testdata is checked. And you should only be able to check the testdata checkbox if the 'create new database' checkbox is checked.

It should not be possible to do like this:

<img width="524" alt="screen shot 2017-05-17 at 09 49 32" src="https://cloud.githubusercontent.com/assets/26706647/26143147/f1a8b60c-3ae3-11e7-88b3-9c8b574fdb08.png">

**Comment by a15andau** [comment]
Merged. Closing
