### ISSUE TITLE
Inconsistency with moving multiple selected objects

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3960]
Selecting multiple objects and moving them around sometimes causes issues with the offset. Objects move the opposite direction of where it is supposed to move and "flies" away out of canvas. This problem has particularly been present when selecting an attribute connected to an entity with a line.

**Comment by HGustavs** [comment]
This is a priority issue, since moving groups inside a diagram is a "standard" operation that is very commonly used.

**Comment by c16jonha** [comment]
This issue seems to be irrelevant and will now be closed
