### ISSUE TITLE
Duggas as headers doesn't fill the whole row

### ISSUE THREAD

**Issue by a15mikla** [HGustavs/LenaSYS#3961]
If a dugga is selected to look like a header the background-color doesn't fill the whole row.
Image to clarify:
<img width="810" alt="errorfailwhaat" src="https://cloud.githubusercontent.com/assets/26705198/26143469/63ead096-3ae5-11e7-813a-d6383d820221.png">

**Comment by HGustavs** [comment]
Is this a problem to the deadline box that shoudl be there to the right?

Perhaps this only happens if there is no deadline?

**Comment by a15freed** [comment]
I can't recreate this issue. If I create a new dugga without a deadline it won't save it, I get an UNK. Otherwize it looks ok when changing it to a header. Maybe we can close this for now? @HGustavs

**Comment by a15mikla** [comment]
The issue is still there. Even with a deadline the color on the row doesn't fill. But yes, this should be a problem with the for example the witdth of the deadline-box.

**Comment by a14isshi** [comment]
We are having a hard time to recreate the issue to help us identify when the problem occur. Neither from a student or a teacher perspective can this be found. Can we get an explanation or demonstration  on how to recreate the problem? @HGustavs

**Comment by a14isshi** [comment]
As the problem could not be recreated, it is probably solved! Therefore this issue will be closed.
