### ISSUE TITLE
Implement titles for buttons

### ISSUE THREAD

**Issue by a14phili** [HGustavs/LenaSYS#3967]
When hover buttons it should give a popup/feedback on its title.
It's already implemented on most buttons

**Comment by HGustavs** [comment]
Is this true for all icons and buttons in dialogs also or only on buttons in part of the interface?

**Comment by a15eriho** [comment]
Titles are missing here and there. No consistency in where there are and where there aren't a title set.

For example, the Submit button on the Login dialog doesn't have title, but most of the Teacher buttons had titles in the Section View.

Also added titles to fields that gets truncated on small screens (example the course names in course editor), so the full name, active course code, and if someone is registered or not on the course when hoovering over the field. Not sure how well this shows on touch devices, but at least there are some way to see the full course name.
