### ISSUE TITLE
Styling on Filter and Sorting dropdowns

### ISSUE THREAD

**Issue by a14phili** [HGustavs/LenaSYS#3969]
How filter looks right now. The align is wrong as you can see in the photo below
<img width="317" alt="skarmavbild 2017-05-17 kl 10 06 01" src="https://cloud.githubusercontent.com/assets/26705978/26144481/460e67d2-3ae9-11e7-813f-5cc0286c0d65.png">

It should look like this. 
<img width="463" alt="skarmavbild 2017-05-17 kl 10 10 07" src="https://cloud.githubusercontent.com/assets/26705978/26144567/9feb293e-3ae9-11e7-8716-4097ba3c2c84.png">

Same thing needs to be fixed on Sort dropdown

**Comment by HGustavs** [comment]
Yes that looks better.

Dont make the text too large though.

**Comment by a15freed** [comment]
This issue is solved through #3986 so closing this one
