### ISSUE TITLE
"Show/Hide all" doesn't expand when all moments are collapsed

### ISSUE THREAD

**Issue by a14phili** [HGustavs/LenaSYS#3973]
If all moments are collapsed it should expand and show all moments.
Now if all moments are collapsed when pressing "Show/Hide all" nothing happens until you press it twice, then the list expands.

**Comment by a14phili** [comment]
Same thing happens if you expand all moments and press "Show/Hide all" it should collapse but now nothing happens until you press it the second time.

**Comment by c14emian** [comment]
What browser are you using? When i press "Show/Hide all" it toggles all moments, hidden moments are shown and shown moments are hidden (using Chrome).

**Comment by a15eriho** [comment]
If you use the "toggle all" to set all moments to visible, then close all one by one separately, and then press the "toggle all", it will try to close all fields again. Same if you do the reverse.
Default action should always be Close all, except when they are all closed, then it should be Show all.

**Comment by a14phili** [comment]
solved and merged #4077
