### ISSUE TITLE
Improve mobile view for drawing menu

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3982]
Mobile view for the entire canvas page is rather crowded. Some major adjustments should be made to improve the user experience.

![bild](https://cloud.githubusercontent.com/assets/26705103/26147622/673f9cd6-3af4-11e7-80f5-70937b24ffa8.png)

#3743 root issue

**Comment by c16jonha** [comment]
is this issue still active?

**Comment by c16jonha** [comment]
This issue is no longer relevant and will now be closed.
