### ISSUE TITLE
More styling of dropdown filter menu in Result-view

### ISSUE THREAD

**Issue by d15eriso** [HGustavs/LenaSYS#3986]
![image](https://cloud.githubusercontent.com/assets/26739514/26148913/90338aea-3af8-11e7-8a4a-685affe605cf.png)

These arrows are next to some dugas and not others and does not do anything when used other than moving slightly up and down.

**Comment by d15eriso** [comment]
Im refering to the up- and down arrows next to "Transformationer 3,5HP".

**Comment by a15eriho** [comment]
I think I accidentally solved #3969 in the same issue.
