### ISSUE TITLE
Create submenu for export alternatives

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#3988]
Exporting alternatives are currently two separate options. The alternatives should be put in submenu instead.

Current:
![bild](https://cloud.githubusercontent.com/assets/26705103/26152897/49efe626-3b09-11e7-9880-d918fc170c44.png)

What it should look like:
![bild](https://cloud.githubusercontent.com/assets/26705103/26152910/59a2117a-3b09-11e7-91e8-4c8dbaaae2e7.png)

**Comment by HGustavs** [comment]
I like the general look of this suggestion.

Also, svg, should svg not be part of this dialog?

**Comment by HGustavs** [comment]
Furthermore, I think this menu is best together with the static html in the diagram.php file.

**Comment by c16jonha** [comment]
This issue is solved and will now be closed. See #4301 for information about the solution.
