### ISSUE TITLE
Zoom dropdown menu icon indicates falsely.

### ISSUE THREAD

**Issue by b15matki** [HGustavs/LenaSYS#3990]
When opening the dropdown menu so that the user can choose the desired zoom the arrow indicates that the options will be listed below when in reality the options are displayed on-top of the menu. The same goes when closing the dropdown menu. 

It would be more consistent if the arrow points correctly at which direct the dropdown menu would move if it is pressed.

**Comment by a16juleh** [comment]
Have worked with this issue and apparently it's only a problem on mac. Click to change the direction for the arrow only works every other time and I didn't discovered it from start because I have mac. No solution has been found yet.

**Comment by a14oscna** [comment]
This issue will be closed as the zoom bar has been reworked and no longer contains a list of options.
