### ISSUE TITLE
Teachers should be able to set amount of opponents and students/group

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3995]
For seminars the teachers should be able to decide how many opponents each student should have and also be able to set a maximum amount of students per group. This should preferably be implemented on the tests page.

**Comment by HGustavs** [comment]
In the database I imagine that this maximum students per group stuff can be stored together with the deadline dates of the test?

**Comment by a15alica** [comment]
I would suggest that it is to be saved with the groups? So where the groupname is saved and linked to a listentry.

**Comment by a18kaswi** [comment]
No effort were made by the customer neither the idea-spawner to realize this idea, closing to leave room for new ideas. And more essential: the ideas put forward by the customers.
