### ISSUE TITLE
Max amount in seminar group - error message

### ISSUE THREAD

**Issue by a15alica** [HGustavs/LenaSYS#3997]
If the maximum amount of students has been reached in a group for a seminar the rest of the students that haven't registered yet should get an error message if they try to pick a full group.

Maybe even make the full group hidden for students that have not yet chosen a group.

**Comment by HGustavs** [comment]
I dont quite understand the gramatics of the last sentence... IMHO "full group" can be interpreted in various manners...

Do we mean "Any groups that have exceeded the maximum number of members should be removed (or grayed?) from the list of available groups for unallocated students"

**Comment by a15alica** [comment]
Yes, that is what we meant, as a way of preventing all students to end up in the same group.

**Comment by d15marwi** [comment]
the group functionality has no function for this.

**Comment by a18kaswi** [comment]
> the group functionality has no function for this.

closing.
