### ISSUE TITLE
A student can be active in more than one group per listentry

### ISSUE THREAD

**Issue by b15matol** [HGustavs/LenaSYS#4001]
This is not intended, and causes some strange behavior in the group editor. 

First the page displays:
![skarmavbild 2017-05-17 kl 21 48 12](https://cloud.githubusercontent.com/assets/26713381/26173152/20a1510a-3b4b-11e7-8dbc-695206af97b1.png)

Another group is assigned, the page is refreshed and now it displays a entirely different group (not the one chosen when assigning a new): 
![skarmavbild 2017-05-17 kl 21 52 03](https://cloud.githubusercontent.com/assets/26713381/26173197/43c0ec22-3b4b-11e7-853a-9899a824cb9a.png)

Update again and mr Anders is back in the "test" group. 

This definitely needs some investigation. 

Possibly have something to do with the `REPLACE INTO` query in the group editor, that does `INSERT`'s if no data is found. Else it makes an `UPDATE`.

**Comment by a15timbe** [comment]
Solved in #4005
