### ISSUE TITLE
Kind value in filelink table

### ISSUE THREAD

**Issue by a15jorpa** [HGustavs/LenaSYS#4016]
I haven't found any details about the "kind" field in the filelink database table. The value seems to be set in such a way that codeviewer thinks an svg file is code (it appears when choosing code from the dropdown menu for choosing an example). It would be good to look over the way this value is set and used and make sure it is consistent.

**Comment by HGustavs** [comment]
What kinds of values are in that column, is it a number e.g. "2" or is it for example ".pdf".

* As far as I can recall there are two columns that relate to files, one stores the type of file, if it is a course local, global or version local file which is stored as an integer.
* I think that there also is a column that stores the extension / file type?

**Comment by c16linst** [comment]
Is there even an issue here or should we close this?

**Comment by c16linst** [comment]
We are closing this issue since this doesn't seem to actually be an issue.
