### ISSUE TITLE
Distribution support

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#4024]
Related to issue #3745, functionality for distribution support should be implemented. When selecting multiple objects, an even spacing should be created between them.

**Comment by HGustavs** [comment]
Not super important to implement distribution, I would prioritize alignment, and when alignment works, focus on distribution.

**Comment by a15perbl** [comment]
Functionality for alignment has already been implemented

**Comment by a15chrau** [comment]
Would have been a good idea to inform me that this was the case.

**Comment by a15perbl** [comment]
Issue resolved
