### ISSUE TITLE
The sorting breaks when the first moment is not shown

### ISSUE THREAD

**Issue by a15nikho** [HGustavs/LenaSYS#4028]
If all moments are shown the sorting is working but if some moments are hidden by the filter the sorting brakes. When the moments are in a different order after filtering the sorting is done on the wrong moment. For example, if Biträkningsdugga and Färgdugga is shown as default and you decide to only show Färgdugga. If you decide to sort on Färgdugga will it not work. Instead it will order on Biträkningsdugga before it was placed there from the beginning.

**Comment by HGustavs** [comment]
Is this a generic bug on all sorting views or only on  this specific view?

**Comment by a15nikho** [comment]
This bug is only in grouped.php. But the sorting is working if you choose to only show Biträkningsdugga because it is the first moment and therefore does not depends on any other moment like Färgdugga. Färgdugga is shown as the second moment and therefore depends on Biträkningsdugga. I think the problem is because it is not updated on which moment is shown and which moments are not shown.

**Comment by HGustavs** [comment]
ok.

Also I would change the title to "breaks", and not "brakes"?

I was under the impression that we are talking about a slowdown, but I am starting to think we are talking about the layout breaking?

**Comment by a15nikho** [comment]
The sorting breaks if the table is not shown in the same order as it was default. For example, if only Färgdugga is shown it will be placed as number one where Biträkningsdugga was as default. Because of that the sorting will be done on Biträkningsdugga instead of Färgdugga and therefore is sorting made on the wrong moment. The sorting will be done on Biträkningsdugga but only Färgdugga will be shown.

**Comment by a15timbe** [comment]
Solved in #4034
