### ISSUE TITLE
The arrow from moments drop to the next row when you minimize

### ISSUE THREAD

**Issue by a14phili** [HGustavs/LenaSYS#4032]
The photo below shows the problem. When you minimize the page the arrow from moments drop to the next row. It should stay at the same row as the text at all time.

<img width="153" alt="skarmavbild 2017-05-19 kl 10 40 06" src="https://cloud.githubusercontent.com/assets/26705978/26240044/e3c9e928-3c7f-11e7-8374-1e4af0f8ed17.png">

**Comment by HGustavs** [comment]
Yes this is a bug. I would guess that the arrow needs its own column in the table / flex layout so that it does not use a new line....

**Comment by a15magkn** [comment]
This issue was also posted in issue #3465 and solved with pullrequest 4235.
