### ISSUE TITLE
Hide preview table if there are no file submissions

### ISSUE THREAD

**Issue by a15elibr** [HGustavs/LenaSYS#4047]
Right now, in any file upload dugga, the table for showing previous uploads will be shown regardless if there are any uploads to show or not. Would be fancier to hide the table if there are no uploads to show.

**Comment by a15wilhe** [comment]
Could you do a printscreen and describe your view of the issue a bit more?

**Comment by a15elibr** [comment]
![keke2](https://cloud.githubusercontent.com/assets/26704655/26358989/8541e16e-3fd4-11e7-8555-45d3d8aaa0ef.png)

What I mean is that if there are no files uploaded yet, should we hide the preview table all together? The preview table is the one I circled in red.

**Comment by a15elibr** [comment]
It's just something I thought about, perhaps it should actually be there to show that no files have been uploaded yet. Or maybe insert a comment in the table which specifically says that there are no files yet. I dont know!

**Comment by A15cecal** [comment]
I think we should leave it of now. You could add some sort of placeholder saying something like "No uploaded files", but that seems quite self-explanatory as an empty list too. Closing.
