### ISSUE TITLE
Make it possible to delete groups in grouped.php

### ISSUE THREAD

**Issue by a15nikho** [HGustavs/LenaSYS#4051]
It should be possible to delete groups in grouped.php. That should be done through adding one more pop-up window when 'Manage Groups' button is clicked(watch mockup). The new pop-up should be designed as the current pop-up, but remove groups instead of creating new groups.

![new_group_mockup_v2](https://cloud.githubusercontent.com/assets/26705128/26294092/90484d3c-3ec1-11e7-95ad-daaccf3ae659.png)

**Comment by a15timbe** [comment]
Solved in #4093
