### ISSUE TITLE
Adding colorblind mode

### ISSUE THREAD

**Issue by a14pethu** [HGustavs/LenaSYS#4056]
It would be a good idea to add colorblind mode for the diagram. In order to make seeing the diagram easier for those who are colorblind.

**Comment by a17robhe** [comment]
@HGustavs Är inte diagrammet svart och vitt?

**Comment by a18antsv** [comment]
The colors do not seem that advanced in the diagram at the moment. What would adding color blind mode mean exactly? The figures and lines are black and white as standard. It is possible to change colors on everything though and if someone that is colorblind loads someone's diagram he might want to restore all colors to black and white? Would this be a function meeting this criteria?

**Comment by a18antsv** [comment]
There seems to already be a function, "Global Appearance", that changes a property of all the figures in the diagram at once. Which is what I was thinking to do.

**Comment by a18kaswi** [comment]
Since we have one work-week left after tomorrows merge. I'm putting this back into the idea-stack.
