### ISSUE TITLE
If no moments are 'Group dugga' or 'Group seminar' a message should be displayed in grouped.php

### ISSUE THREAD

**Issue by a15nikho** [HGustavs/LenaSYS#4057]
A message should be displayed in grouped.php when there are no moments that are 'Group dugga' or 'Group seminar'. The message should be instead of showing a table with only students(watch mockup).  Design should also be added to the message to fit in with the theme.
![no_group_type](https://cloud.githubusercontent.com/assets/26705128/26296824/b0c0c0a8-3ed0-11e7-9e57-3a5538d59dec.png)

**Comment by a15timbe** [comment]
Solved in #4069
