### ISSUE TITLE
There is a bug when dropdownlist of the funnel icon is visible incorrectly in grouped.php

### ISSUE THREAD

**Issue by a15nikho** [HGustavs/LenaSYS#4063]
When you hover over the funnel icon in grouped.php and the dropdownlist is showing, if you drag your mouse to the back-button or the home button the dropdownlist will still be visible. The dropdownlist should only be visible if the mouse hover over the funnel icon or the dropdownlist.

**Comment by a15ponja** [comment]
Fixed with #4094.
