### ISSUE TITLE
Groupname disappears when you have placed a student and then sort on a moment

### ISSUE THREAD

**Issue by a15nikho** [HGustavs/LenaSYS#4072]
If you place a student in a group and then decide to sort on a moment, the groupname will disappear from the student. For example if you place a99petha in a group in Färgdugga 1HP and then decide to sort on Färgdugga 1HP the group will not be shown for a99petha. It should work with a page reload to solve this issue.

**Comment by a15magkn** [comment]
This seems to relate to an old version/design of how groups are handled. Because of this, this issue will be closed.
