### ISSUE TITLE
When button is unselected, it should return to normal state

### ISSUE THREAD

**Issue by a15admsa** [HGustavs/LenaSYS#4104]
If you press a button twice, the color will change on the button. This is to indicate if a button is pressed or not. When you unpress a button, the mode is not returning to normal. The user has to draw the figure for it to return to normal. This should be fixed.

**Comment by a16rasja** [comment]
You can unselect the button by pressing it again before you have drawn something. You can't unselect it by pressing it again if you have drawn something

**Comment by c16jonha** [comment]
This issue is now solved since issue #4249 was solved
