### ISSUE TITLE
Symbols and figures changing colors at creation

### ISSUE THREAD

**Issue by a15oskst** [HGustavs/LenaSYS#4105]
If you create a symbol and press OK without changing anything, the symbol changes color to black, and if you continue to create symbols, altering pressing OK and just pressing outside the dialog box the colurs on previous symbols change colors to both blue and dark green etc.

The same thing happens with figures, but only the line around the figure change color.

**Comment by a15oskst** [comment]
![bild](https://cloud.githubusercontent.com/assets/26707190/26375839/b5d6cd18-400a-11e7-98c5-dd60e1c7dfba.png)

**Comment by c16jonha** [comment]
This issue will be solved through issue  #4202
