### ISSUE TITLE
"Draw square" creation functioning incorrectly

### ISSUE THREAD

**Issue by a15perbl** [HGustavs/LenaSYS#4113]
When the "draw square"-button is selected nothing happens at the first. Two clicks are required before the canvas actually creates the square, which needs to be fixed.

**Comment by a16adala** [comment]
The way it currently works is as following. The first click on the square-button checks if a first point is set. When the first point is set the user will then need to click the button again to set the second point. After both points are set, the square will be created

**Comment by c16jonha** [comment]
This issue is solved and will now be closed
