### ISSUE TITLE
Update the list of students in the opponent dropdown (grouped.php)

### ISSUE THREAD

**Issue by a15tobli** [HGustavs/LenaSYS#4127]
Related to the new dropdown lists added for  #3994. After a group has been set for a student, the list of possible opponents in that group is not updated correctly. The members of the old group still displays after a new group has been set. This updates correctly after the page has been reloaded, but a function needs to be added which updates the students as a new group is chosen.

**Comment by b16karhe** [comment]
Since grouped should be deleted from #4188 this issue will be closed because grouped won't exist.
