### ISSUE TITLE
free assigned Countdown Timer on specific elements

### ISSUE THREAD

**Issue by a15denbi** [HGustavs/LenaSYS#4140]
Creating a countdown timer so the students can more clearly see when a specific task should be completed, creating the timer in a separate file so that I can easily be linked to any project on the site. 
Edit: This can also make it more clear when a student will get logged out automatically.

**Comment by a18kaswi** [comment]
Customer didn't react to this idea. Closing it to leave room for new ideas to customer, that maybe, just maybe, can actually be implemented this year.
