### ISSUE TITLE
Course members inconsistently displayed on "Results" / "Access"

### ISSUE THREAD

**Issue by andras-marki** [HGustavs/LenaSYS#4146]
The ordering is inconsistent between the two lists. The data is also inconsistently displayed.

I have no idea what Access is sorted on, but has separate first / last name fields.

Result can be sorted but is right now sorted on First name.

**Comment by d15eriso** [comment]
Can you clarify? Both seem to be sorted in the right order för me, and the list in Result are sorted by Last name and not First.

@andras-marki

**Comment by proci** [comment]
Check Access.

If it has sorting, this feature has already added to the project V17 variant (you are working on), but didn't make its way into the stable build yet.

Result is possibly fine, I get sorting on the Fname on one of my computers and Lname on my other, so it can happen that there is some usability quirk with it.

**Comment by d15eriso** [comment]
Then I think everything is working, exept for maybe a default setting so that Result sorts by Last name by default. This way the lists will feel more consistent. 
I will get to work on that.

**Comment by c17johha** [comment]
Resulted displays member by first name
