### ISSUE TITLE
Formating in result-view dropdown-menu

### ISSUE THREAD

**Issue by d15eriso** [HGustavs/LenaSYS#4147]
Separating lines are inconsistent. Should be using same format for all parts of the dropdown menus.

**Comment by d15eriso** [comment]
![image](https://user-images.githubusercontent.com/26739514/26929938-e1be91ec-4c5b-11e7-9815-9adb03c56326.png)

**Comment by a16seplu** [comment]
Solved

**Comment by a16seplu** [comment]
Solved
