### ISSUE TITLE
Teacher feedback on preview is "UNK" by default

### ISSUE THREAD

**Issue by proci** [HGustavs/LenaSYS#4153]
Small thing, but people not familiar with the system can wonder why UNK is displayed by default.

**Comment by a15magkn** [comment]
Since this is part of the ResultEd, this is not the responsability of Group 3 (2018). And therefore this issue will be untagged.

**Comment by b16linra** [comment]
This is probably related to the feedback found in the images below.

When on a course, clicking on the "Results" button makes it possible to leave feedback as a teacher by clicking on the fist icon.
![image](https://user-images.githubusercontent.com/37793838/38867212-a6bf4a3a-4243-11e8-88e3-eca26eed242e.png)

Then, click on the feedback button to leave feedback.
![image](https://user-images.githubusercontent.com/37793838/38867240-b4040596-4243-11e8-9f59-39de4d67036b.png)

As can be seen here, the default feedback value is "UNK".
![image](https://user-images.githubusercontent.com/37793838/38867262-c3344ec2-4243-11e8-8138-9dc672c2a97b.png)

**Comment by a18kaswi** [comment]
There should maybe have been a faq from the start?
