### ISSUE TITLE
File handling problem - How should we copy files between course versions?

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#4159]
The files used in a course uses a global -> course -> course version idea. This 
means that files uploaded as a global file is available to all courses. A file 
uploaded as a course file is available to all course versions of that course. A 
file uploaded to course local is only available to that specific course version.

When retrieving a file we only specify a file name, and the system will serve 
the appropriate file using the preference rule local over course over global.

When creating a new course version based on on an old course version we are 
faced with a problem. How should we chose files that have a local version?

The overall goal is to have old course versions to be as they were and new 
course versions to have the most updated versions of files.

**Scenario 1:**
A file, file1.txt is created in HT15. The following year an updated version is 
created and put in course local files receiving a new id (id2). The following 
year, HT17, we want this updated file to be used as the new "regular" course 
file and the field course local file should be empty.

If we in HT17 change a typo in File1.txt this will be shown in HT17 and HT16 
but not in HT15.

== HT15 ==
-- Course Files --
id1, File1.txt
-- Course Local Files --

== HT16 ==
-- Course Files --
id1, File1.txt
-- Course Local Files --
id2, File1.txt

== HT17 ==
-- Course Files --
id2, File1.txt
-- Course Local Files --

For this to work I think we need a path column in the fileLink table to be able 
to located the most current file.

**Scenario 2:**
A file, file1.txt is created in HT15. The following year we create a unique 
version of file1.txt and put in course local files receiving a new id (id2). 
The following year, HT17, we don't want the unique file created previous year 
but rather the course file created HT15. Course local files should be empty.

If we in HT17 change a typo in File1.txt this will be shown in HT17 and HT15 
but not in HT16.

== HT15 ==
-- Course Files --
id1, File1.txt
-- Course Local Files --

== HT16 ==
-- Course Files --
id1, File1.txt
-- Course Local Files --
id2, File1.txt

== HT17 ==
-- Course Files --
id1, File1.txt
-- Course Local Files --

This does not require a new column in fileLink, but we need to change the code 
that creates a new course version from an old course version, so that it 
disregards course local files.

**_### Comments_**
One could argue that both the above scenarios are valid. Depending on how one 
use LenaSYS. Perhaps we should implement both and give the user a choice when
creating the new course version?

Either way, giving a brief description of what is done during the copy process
should be given so that a new user knows what has been done I think is a good 
thing.

A third scenario based on timestamps could perhaps be used. This will also 
require a path column. I am unsure if this is usable solution though. I have a 
feeling that this would break our global -> course -> course version idea 
though.

**Comment by HGustavs** [comment]
Scenario 1 is wrong.

Local file is not for fixed typos, but for content that is not relevant in another year.

**Comment by HGustavs** [comment]
Course local files are local to a specific course,
Version local files are local to a specific version of a course

Any version local file should not be copied as it is only valid to the local version.

For instance a document that details deadlines for 2017, it should only be showing that document to 2017, not to 2016 nor 2016.

**Comment by a97marbr** [comment]
So scenario 2 is what we want.

And if we, for example, change the description of a dugga from one year to another we should give this a new file name to preserve old course versions and as a result we would need to change the pointer to the new file in the JSON for that dugga.

**Comment by HGustavs** [comment]
I vote for giving any significant changes a new name, then we can view both old and new files in the file library.... e.g. Assignment1_2017.md

**Comment by HGustavs** [comment]
it would be nice to have an error message if we attempt to download a file that has a local version but not a "new" local version. 

This way if we "forget" a local version of a file we are guaranteed that we are not serving old files...

**Comment by a97marbr** [comment]
Not following...

**Comment by a97marbr** [comment]
Implementing scenario 2 is still going to require some effort it seams. We only have a type parameter:
1. link
2. global
3. course
4. local

We than serve the file depending on its type. 
`SELECT filename,kind from fileLink WHERE (cid=:cid or isGlobal='1') and UPPER(filename)=UPPER(:fname) ORDER BY kind DESC LIMIT 1;`

We have no idea in which course version a specific file was local, only that there exists a local version.

**Comment by a97marbr** [comment]
add a course version column to the fileLink table?

**Comment by a18kaswi** [comment]
This seems like some old discussion between customers, closing.
