### ISSUE TITLE
SortableTables in Accessed

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4162]
We need to do the following (includes suggested suitable sub-goals)

1. Put sortableTables in Accessed (allows us to get uniform design, and 'free' sorting and filtering
     * Use sortable table for rendering rows - SOLVED
     * Use sortable table for filtering - SOLVED
     * Use sortable table for column sorting - SOLVED

2. Remove edit single user dialog and replace with cell editing from sortabletables - SOLVED

**Comment by a16jonis** [comment]
Since all subgoals are solved in this issue I'm closing it.
