### ISSUE TITLE
Responsive design - Breakpoints for different devices?

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#4165]
Is there a clear target size for LenaSYS?

- What do we consider a mobile (small) device setting? 320px width? This would mean devices such as iPhone5 in portrait position. Should this be the minimum screen width setting? I would vote for this.
- What do we consider a tablet (medium) device?  1024px width? This would mean devices such as iPad (in landscape position)
- What do we consider a desktop (large) device? 1280px width? This would give laptops such as MacBook pro 13 inch the desktop size.
- Should we have a large desktop device setting? I don't think we need this at the moment.

**Comment by andras-marki** [comment]
I would be a bit careful with resolutions. My own phone has an 1440p display which is higher than my desktop screens home.

You can on the other hand use the browser id to decide which type of device we are looking at.

**Comment by HGustavs** [comment]
How about as little breakpoints as possible and an as completely fluid layout as possible.

Breakpoints add cruft to css.

Fluid designs are like one size fits all trousers from "ullared". We only need to keep one size in store but it will be baggy on some people and smallish on others.

**Comment by a18kaswi** [comment]
Right now the task of developing a responsive design for LenaSYS is out of the question. If all teams can work together to erase this horrible backlog, then surely we can optimize databases and implement it on docker.
