### ISSUE TITLE
Add group attribute/column to accessed

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4170]
The datatype should be a long varchar or text.
The data should be json data in text format
For example

{"Presentation2":"A","Seminar3":"IV","Seminar2":"IX"}

Denotes the value for group id "Presentation2" is "A" and correspondingly, the value for group id "Seminar2" is "IX"

The group identifiers are predefined in the access editor see issue #4169

**Comment by a16seplu** [comment]
Solved

**Comment by d15marwi** [comment]
The new design doesnt work like this. We will refer to new issue soon.
