### ISSUE TITLE
Very confusing use of pen AND cog wheel in Course Editor

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4172]
<img width="971" alt="screenshot 2018-03-21 21 19 54" src="https://user-images.githubusercontent.com/6978801/37735631-ef8607fe-2d4e-11e8-9b65-89a41197b910.png">

Remove new course version "pen" icon as this is covered more or less completely by functionality available in the version dropdown in sectioned.

**Comment by HGustavs** [comment]
Make sure (confirm here for documentation-s sake) that no useful feature is lost when we only have the corresponding dialog and retire this issue at your leisure.

**Comment by d16linja** [comment]
Solved
