### ISSUE TITLE
Fileed has database search for files

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4173]
Remove Database Search in Fileed and change it to a sortable table version.

* A normal looking-glass dialog
* Perhaps integrating the looking glass icon with the text box, like how the version dropdown to the top left corner of the section editor.
* Instead of searching in the database we can search interactively using the functionality from sortabletable.

![screenshot-2018-03-21-21 35 56](https://user-images.githubusercontent.com/6978801/37736477-521da992-2d51-11e8-82b6-84eb60265ae2.png)

**Comment by c16jonha** [comment]
I will split this issue into two parts: the first part will contain the first and second points in the list and the second part will contain the third point in the list.

**Comment by c16jonha** [comment]
This issue has been split. see issue #4250 and #4251

**Comment by c16linst** [comment]
This issue is solved, see #4276 and #4583
