### ISSUE TITLE
Live markdown preview in file editor

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4174]
For example by a pen icon or a button for .md files could allow direct editing of markdown files.

A view much like the marking preview window.

Data file to the left and markdown preview to the right.

A save button that saves the edited mardown text to the corresponding file.

This editing should only work for .md files.

**Comment by HGustavs** [comment]
If possible ... less ugly?

**Comment by c16jonha** [comment]
Is there an existing module for the markdown page or should we make our own from scratch?

**Comment by HGustavs** [comment]
There is a markdown module included in lenasys called markdown.js ... if you call parsemarkdown or whatever that function is called in markdown.js https://github.com/HGustavs/LenaSYS/blob/master/Shared/markdown.js the corresponding html for that markdown is returned.

however.

We need to apply the styling so that the markdown looks exactly right (as it would in a dugga instruction or code example description for example) ... we need also to call this function continously when the text is updated...

also the on-disc file containing the markdown also needs to be saved.

**Comment by b16nicbr** [comment]
Progress so far is that we have done the function for canecling the event of markdown.
The next step is converting markdown code to normal text.

**Comment by a15setno** [comment]
We changed the appearance of the generated markdown-code to simulate the look of the file when viewed in codeviewer.php.

Look from the codeviewer
------
![codeviewer_markdown](https://user-images.githubusercontent.com/37832730/38854725-b8123ae4-4221-11e8-8a72-da04881b859d.PNG)

Look from the preview 
------
![markdown](https://user-images.githubusercontent.com/37832730/38854738-c03f9a40-4221-11e8-9897-61fc2d7eb874.PNG)

Does this look sufficient @HGustavs ?

**Comment by b16nicbr** [comment]
can this be closed?
Because this iissue is already fixed and improved
