### ISSUE TITLE
Mini mode (blue mushroom mode)

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4175]
For the marking a mini-mode has been requested.

A second rendering mode accessible by a button or check box somewhere... (in filter dialog?)

By checking this box we render the whole marking view with a reduced size to allow us to get a reduced size preview of the whole course (e.g. if we have 30 tests and 80 students in a course).

* Using sortable table we just change the rendering callback to render this specific mode if a box is ticked
* Render all marking buttons inoperative, this is a viewing mode only.
* Render students names in a reduced single line mode with only the name of the student and no ssn etc
* Only show color of cells, green for G or VG, yellow for un-marked and red for failed tests. It should not be possible to click anything or select/mark anything.
* Sorting of columns should happen normally.

**Comment by HGustavs** [comment]
Usage scenario: I want to see how many failed tests there are compared to how many that have not been handed in for the whole course. If i sort on first column in first part of the course I can see exactly how many remins to be marked or how many that have been marked.

This overview is very useful in large courses.

**Comment by b16nilpe** [comment]
A version of mini-mode was implemented according to the bullet-list. This was done through the issues: #4227, #4228, #4229, #4230, #4231.
Closing this issue for now.
