### ISSUE TITLE
Filter in marking view for teachers responsible for marking this specific test

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4178]
Similarly to #4177 we need a filter for marking teacher.

Each test (dugga) should have a "marking teacher" for it.

A teacher is selected from a drop-down containing all teachers in the course.

Each test has one or more teachers as a comma-separated list

The looking glass should allow us to search for only assignments shortlisted for any specific teacher written in looking-glass text box.

**Comment by HGustavs** [comment]
Usage scenario: A teacher wants to limit which tests that are shown, only the tests relevant for that teacher should be shown.

This filter should be remembered if one returns to this dialog later.

**Comment by a16hamsa** [comment]
this list of teachers, from where do i get the teachers in a specific course? and when i create the list, should i create it as an array in a separate file or is it best to store them in a textfile for the purpose?

**Comment by a17adasy** [comment]
For this to be efficient, the filter has to work on both rows and columns for it to be sort of useful and even then it can be unnecessary. For example, if these two tests have been graded by teacher1 and the other test marked by teacher2, if one sorts by teacher1, both rows and both columns has to show either way so the use of this is very circumstantial.
![image](https://user-images.githubusercontent.com/37799016/57609556-6b170080-756f-11e9-9c10-4bbc68a383cf.png)

**Comment by a17ludca** [comment]
On further inspection we noticed that a student has a specific examiner, is one teacher responsible for grading all assignments from a certain student?
