### ISSUE TITLE
Control+Click to change incorrect mark

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4179]
In the marking view we want the ability to fix erroneous clicks e.g. if one accidentally fails the wrong student by clicking the wrong line.
* Control+click on other mark changes the mark to this mark
* Only allowed within a short time-span - after let us say 10 minutes the control+click method is not possible for reverting mark
* It should be possible to revert from any mark to any other mark or not-yet-marked

**Comment by HGustavs** [comment]
...Extreme vetting so that only good faith edits are possible...

**Comment by d16linja** [comment]
Solved
@HGustavs read about the workaround in #4444
