### ISSUE TITLE
Retaining collapsed-state of sections in local storage

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4181]
For each course viewed in the browser the collapse-states of each element should be remembered.
 * If all parts of the course execpt for the first is collapsed and we return to the course this should still be the case - currently we are returned to the full-all-elements-expanded view.
 * Standardized way to remember these settings. Preferably a library that we can make part of the code base which helps with this task. This code can then be shared between groups as this is needed in more than one part of the code.

**Comment by a15magkn** [comment]
This is divided into two new issues and this will be closed. 
The new issues are #4322 and #4323
