### ISSUE TITLE
Swim lanes are too wide and require scrolling

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4182]
<img width="1309" alt="screenshot 2018-03-21 22 56 41" src="https://user-images.githubusercontent.com/6978801/37739658-27561b68-2d5b-11e8-8935-1bca90da91b7.png">

* Full view is neither shown horizontally nor vertically.
* Rows and symbols are too high
* Columns are too wide.

**Comment by HGustavs** [comment]
Can someone provide a screenshot with adjusted distances etc so we have something to look at?

**Comment by a16konka** [comment]
This issue has moved to #5163, therefore this issue shall be closed
