### ISSUE TITLE
Dockable always on top swim-lanes

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4184]
On wider computer screens we can show swim-lanes in a dockable right hand view.
  * Like gene frenkle we should really explore the space, perhaps a vertical layout (see mock-up) is more efficient than a horizontal layout.
 * The goal is to get the whole swim-lanes view (full course) on the right part of the screen
 * Note the small triangle, when we push this, the swimlanes are collapsed away to the right or collapsed forward to the middle of the screen.
* On mobiles etc swimlanes should not be shown (or shown in full screen when swimlanes button is pressed).

<img width="500" alt="screenshot 2018-03-21 23 00 17 copy" src="https://user-images.githubusercontent.com/6978801/37739982-57a21e06-2d5c-11e8-9b65-13e190bd6616.png">

**Comment by HGustavs** [comment]
A better mock-up would be appreciated... I am not very happy about the one above.... but it conveys the principle (albeit poorly)

**Comment by a16konka** [comment]
This issue has moved to #5163 and therefore shall be closed
