### ISSUE TITLE
Group editor

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4188]
The group editor functionality and section editor button should both be removed.

Group editor was to complicated to work well issue #3900 - #3901 ... 

New improved simplified suggestion in #4170 among others.

**Comment by b16karhe** [comment]
What do u mean? Weren't we supposed to create functionality for group editor and handle problems with the section editor? And here it says to delete it.

**Comment by b16karhe** [comment]
Question has been answered.
