### ISSUE TITLE
Sectioned group indicators

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4189]
There should be a field in sectioneditor for connecting to group-ids.
* Should work for section type, only Group Activity
* Groupid is just a text field
* Text  field contains reference to a group e.g. "Presentation2"
* If the json data for current student in the current course is {"Presentation1":"A","Presentation2":"C"} for the section that has "Presentation2" in its group field, we write "C" next to the text written for the current section ...

and so on for each section...

**Comment by a16linas** [comment]
I'm not sure I fully understand the issue. Can you explain the "group-id"?

**Comment by a16thegu** [comment]
@HGustavs, can you take a look and explain more.

**Comment by a16thegu** [comment]
After talk with client, issue will be on hold.

**Comment by d15marwi** [comment]
design for this icon was made in #5051

**Comment by a14isshi** [comment]
Merged and closed.
