### ISSUE TITLE
Contribution is currently a button in section editor and add a dugga/test instead using an iframe

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4193]
Remove contribution button in section editor and add a dugga test   type which loads it as an iframe

**Comment by a16filol** [comment]
Should the iframe be shown if "Dugga/test" is pushed, in the content field?

**Comment by a16thegu** [comment]
@HGustavs, can you take a look and explain.

**Comment by a16thegu** [comment]
After talk with client, not Group 3 responsibility. Will talk with Group 1.

**Comment by a17joaap** [comment]
This can certainly be done, however the database needed to test contribution.php does not seem to be included in the repository.

contributionservice.php:
`$log_db = new PDO('sqlite:../../GHData/GHdata_2018_7.db');`

Without this the file will cause a 500 error. Is this part of another issue @HGustavs ?

**Comment by a17joaap** [comment]
The above solution will link any dugga with 'Link' set to Contribution to an iframe containing contribution.php

**Comment by a17joaap** [comment]
Can be closed @a17andby

**Comment by a17andby** [comment]
Closing
