### ISSUE TITLE
Marking view date colors / Icon

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4194]
The printed date in the marking view should be colored red if deadline has passed.
This is an easy way to see that this hand-in was made after the deadline.

Instead of seconds in time we can also add a miniature of the deadline icon to further show that this hand-in was made after the deadline.

**Comment by HGustavs** [comment]
<img width="274" alt="screenshot 2018-03-21 22 48 03" src="https://user-images.githubusercontent.com/6978801/37743189-305caff2-2d69-11e8-894c-cd114e7201cd.png">

This is the icon  I was talking about.

**Comment by a16hamsa** [comment]
<img width="274" alt="markingviewdeadlinemockup" src="https://user-images.githubusercontent.com/37805128/38310533-15059ac0-381d-11e8-87f9-434ba384b61c.png">

**Comment by a16seplu** [comment]
bump

**Comment by d16linja** [comment]
@HGustavs Please review the mockup

**Comment by HGustavs** [comment]
Looks ok.

**Comment by d16linja** [comment]
@a15magkn

**Comment by d16linja** [comment]
The textpart is already solved in issue #4216

**Comment by b16linra** [comment]
The icon was moved in pull request 5032. This issue will be closed.
