### ISSUE TITLE
Test deadline either normal date like currently or a json string

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4195]
Add json option for deadlines format:   {["2010-11-01","You have past first   deadline","2010-11-02","You have past the second   examination deadline","2010-12-01","Your submission was   handed in after last deadline, let the teacher know that you have handed in   by sending an email"]} 

We need to also change the datatype of the deadline field in the database from datetime to string to allow us to either store a single deadline date or a json string containing multiple deadlines and error messages for passing each deadline.

**Comment by a17pongo** [comment]
@HGustavs a sub issue of this #4164 ?

**Comment by b18jonli** [comment]
Seems to be already implemented, closing issue.
