### ISSUE TITLE
Diagram editing settings dialogs

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4198]
Currently the way that settings dialogs work is a bit of a problem from a code standard and programming standpoint As can be seen in the screnshot of the folder structure below... the settings-dialogs are individual static dialogs that are populated when a diagram object is created.

* In order to follow the code standard we need to have a single service file that does all back-end stuff i.e. diagram_service.php
* We need one file that has all the static html dialogs / content i.e. diagram.php
* We need one file that handles all these dialogs, also no need to have distinct dialogs for distinct content, one dialog that is changed to fit each kind of diagram entity. (as can be seen below, entity and relation are exactly identical) 

I suggest splitting this into a few smaller sub-issues.

![screenshot 2018-03-22 10 34 24](https://user-images.githubusercontent.com/6978801/37762718-7151bd82-2dbd-11e8-9ca3-9ecdfebc0591.png)
![screenshot 2018-03-22 10 26 54](https://user-images.githubusercontent.com/6978801/37762719-71822918-2dbd-11e8-8e9c-1f9fff7f6cd8.png)
![screenshot 2018-03-22 10 09 01](https://user-images.githubusercontent.com/6978801/37762720-71af5a3c-2dbd-11e8-8b22-b5eba9c78a9a.png)

**Comment by c16carbe** [comment]
@HGustavs Is global appearance something you still want? Because it seems like a pretty niche functionality to us.
