### ISSUE TITLE
When making diagram object settings is automatically shown

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4200]
When we draw a diagram object, the settings dialog is shown always.

This is not helpful for a fast working process, if I draw an entity, and then want to draw five attributes:

1. I want to be able to click entity, draw the entity,
2. Click attribute and click five times to get the five attributes.
3. Move attributes or entities them so they are placed evenly on screen.
4. Then I write the names of each attribute.

Currently the work process is

1. Click entity
2. Click ok in settings dialog
3. Click attribute
4. Click ok in settings dialog
5. Click attribute (sigh!)
6. Click ok in settings dialog (again! sigh!)

Imagine drawing five entities with five attributes each.

**Comment by c16jonha** [comment]
This issue has been split into two sub-issues: #4248 and #4249

**Comment by HGustavs** [comment]
You are free to retire this issue if covered completely by sub-issues or keep it and retire it after sub-ssues have been resolved.

Keep the clearest issue among the redundant ones and retire the others, is a good work process, otherwise we clog up the issue queue.
