### ISSUE TITLE
Questionable defaults

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4202]
When one draws a new entity it has black text on black background?
Or is it random color?

I suggest using the pervasive white fill and relatively thick black line as the no-action-default.

**Comment by HGustavs** [comment]
![screenshot 2018-03-22 11 37 47](https://user-images.githubusercontent.com/6978801/37765783-7833d5ba-2dc5-11e8-9132-324dfc459361.png)

**Comment by HGustavs** [comment]
State of diagram after drawing a few entities attributes and relationship symbols.

**Comment by c16jonha** [comment]
This issue is solved

**Comment by HGustavs** [comment]
Do we have a link to the pull request that resolves this.

I am curious about what/when/how this was done in the code.

**Comment by c16linst** [comment]
https://github.com/HGustavs/LenaSYS/pull/4261
