### ISSUE TITLE
Dotted lines when drawing lines

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4207]
Crrently when drawing lines we dont see where we are drawing (while drawing preview)

Something like the mock-up below would make it much easier to see where the next line segment will be placed.

![screenshot 2018-03-22 16 55 54 copy](https://user-images.githubusercontent.com/6978801/37782188-9b2c705e-2df2-11e8-9539-1f883915f54e.png)

**Comment by c16jonha** [comment]
This issue is now solved and will now be closed. See #4310 for more information about the solution to this issue.
