### ISSUE TITLE
Writing headings, sections, etc. that includes quotes (") in sectioned will make editing of that line impossible

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#4208]
Writing headings, sections, etc. that includes quotes (") in sectioned will make editing of that line impossible
For example, writing a heading:  This is an important "thing" will make the cogwheel menu unreachable for that heading.

**Comment by HGustavs** [comment]
This seems like a very important bug... since it will necessitate finicky hands-on alterations.

**Comment by a16konka** [comment]
Should we handle this bug by allowing quote tags or should we make sure that quotes and other characters are not allowed?
