### ISSUE TITLE
Marking view date colors / Icon - part one

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4216]
The printed date in the marking view should be colored red if deadline has passed.
This is an easy way to see that this hand-in was made after the deadline.

**Comment by c16matan** [comment]
Developed using pair programming. Added deadline into the select query in the ajax service file. Also did a condition check to see if the deadline had already passed or not to change the text color.

**Comment by a16seplu** [comment]
Solved
