### ISSUE TITLE
Marking view date colors / Icon - part two, symbol

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4217]
Instead of seconds in time we can also add a miniature of the deadline icon to further show that this hand-in was made after the deadline.

**Comment by HGustavs** [comment]
Can I see a mock-up of this suggested interface?

**Comment by d16linja** [comment]
Issue #4194

**Comment by d16linja** [comment]
Closed since another group is working the the main issue with their own system
