### ISSUE TITLE
Control+Click to change incorrect mark - part two, time allowance

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4219]
In the marking view we want the ability to fix erroneous clicks e.g. if one accidentally fails the wrong student by clicking the wrong line.

Only allowed within a short time-span - after let us say 10 minutes the control+click method is not possible for reverting mark

...Extreme vetting so that only good faith edits are possible...

**Comment by d16linja** [comment]
@HGustavs There seems to be an time-limit of 24h already, should this be changed to 10min? This who issue seems partly solved except the "remove grade" part (issue #4220 )

**Comment by a16seplu** [comment]
Solved
