### ISSUE TITLE
Filter in marking view for teachers responsible for marking this specific test - part four, looking glass shortlist

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4224]
Similarly to #4177 we need a filter for marking teacher.

The looking glass should allow us to search for only assignments shortlisted for any specific teacher written in looking-glass text box.

Usage scenario: A teacher wants to limit which tests that are shown, only the tests relevant for that teacher should be shown.

This filter should be remembered if one returns to this dialog later.

**Comment by HGustavs** [comment]
Im thinking that the row-filter in sortable table is sufficient.

The only thing we need additionally is the teacher list and to get this working with sortable table row filters.

https://github.com/HGustavs/SortableTableLibrary/blob/master/sortableTableDemo_rowfilter.html
