### ISSUE TITLE
Filter in marking view for teachers responsible for marking this specific test - part one, create list of teachers

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4225]
#4178 
A teacher is selected from a drop-down containing all teachers in the course. 
We should create this list separately, making it easier for the future

**Comment by a16hamsa** [comment]
this list of teachers, from where do i get the teachers in a specific course? and when i create the list, should i create it as an array in a separate file or is it best to store them in a textfile for the purpose?
