### ISSUE TITLE
Mini mode (blue mushroom mode) - part four

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4230]
Only show color of cells, green for G or VG, yellow for un-marked and red for failed tests. It should not be possible to click anything or select/mark anything.

**Comment by HGustavs** [comment]
I am thinking this is handled semi-automatically by a mode switch in sortable table rendering callback.

Is it possible to change backgroun color in sortabletable?

~~~
If(minimode){
  // Render one way
}else{
  // Render other way
}
~~~
