### ISSUE TITLE
Test deadline either normal date like currently or a json string - part one

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4240]
**Add json option for deadlines format: {["2010-11-01","You have past first deadline","2010-11-02","You have past the second examination deadline","2010-12-01","Your submission was handed in after last deadline, let the teacher know that you have handed in by sending an email"]}**

We need to also change the datatype of the deadline field in the database from datetime to string to allow us to either store a single deadline date or a json string containing multiple deadlines and error messages for passing each deadline.

**Comment by HGustavs** [comment]
Perhaps a clearer description than part one and part two?
