### ISSUE TITLE
Diagram Toolbar should be able change from vertical to horizontal

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4244]
![toolbar](https://user-images.githubusercontent.com/37794047/38081547-985d9810-3344-11e8-8a33-3aa245292f86.PNG)
You should be able to change direction by clicking on a button in the toolbars top right corner.

**Comment by HGustavs** [comment]
The toolbar is far from ideal especially in mobile.

Perhaps some kind of docking / pinning mode or as a hotdog menu?
