### ISSUE TITLE
Remove the object settings from showing automatically

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4248]
When you draw an object the settings should not be shown automatically when you're finished drawing the object. This is a sub-issue of issue #4200

**Comment by HGustavs** [comment]
Prioritized issue also. VERY annoying. Often one wants to for example add five attributes near a certain entity in rapid in rapid succession, or create five entities within a short timespan. This should be possible without many movements of mouse/finger or additional clicks etc.

**Comment by c16jonha** [comment]
This issue is solved and will now be closed.
