### ISSUE TITLE
The buttons for objects has to be pressed for drawing every object

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4249]
When one object is selected, the user should be able to draw that object several times without having to press the objects button again. When the objects button is pressed again, then the object is de-selected. 

You should also be able to name the objects after you've drawn them with the object settings dialouge window.

This issue is a sub-issue of issue #4200

**Comment by HGustavs** [comment]
This is a prioritized issue from my standpoint. If this is not fixed the diagrams are nearly useless as the process of making a diagram is VERY slow without it.

**Comment by c16jonha** [comment]
This issue was solved and will now be closed
