### ISSUE TITLE
Fileed database search

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4250]
- A normal looking-glass dialog
- Perhaps integrating the looking glass icon with the text box, like how the version dropdown to the top left corner of the section editor.

This is a sub-issue of issue #4173

**Comment by HGustavs** [comment]
Standardization of the look and feel of this is important so that search/sorting etc works identically in all modules.

**Comment by HGustavs** [comment]
A clearer description than part1 and part2 in the issue title is not a bad idea.

For example "Fileed search database" and "fileeed search interface" are much clearer than "p1" and "p2" for example.

**Comment by c16jonha** [comment]
This issue is solved and is now closed
