### ISSUE TITLE
Move button does not unselect when object button is pressed

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4254]
When you select the move button and then select an object, the move button is not deselected. it is only deselected by a second click on the move button.
![capture](https://user-images.githubusercontent.com/37794047/38238206-77d3b532-3729-11e8-8f3e-118577fdad42.PNG)

**Comment by HGustavs** [comment]
I would be glad if we could do away with that button completely....

* If we are in drawing mode and we click and draw we draw an object (e.g. an entity symbol)
* If we are not in drawing mode and we click and drag on edge of object or in object we move/resize that object.
* If we are not in drawing mode and we do NOT start our click/drad in an object or on the edge of an object we scroll.

This way the button is only needed in a few edge cases. 

It could even work like in photoshop/illustrator, pressing spacebar (or other key?) we are in scrolling mode... this way we dont need the button at all either, other than perhaps as some kind of feedback mechanism.

**Comment by b16andka** [comment]
The original issue is solved, should we complete the pull request and close this issue and create a new issue with the new functionality?

**Comment by HGustavs** [comment]
Always complete the code... but you can choose how to handle the issue within the project group. Standardize for some approach.

**Comment by c16jonha** [comment]
This issue is solved and will now be closed
