### ISSUE TITLE
Add move button functionality to hot key 

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#4265]
Able to use spacebar or other key to scroll instead of move button. The move button should only indicate that the screen is currently movable. 

Check comment in issue #4254 for more details.

**Comment by HGustavs** [comment]
It would be nice to have it as a fixed FAB-like icon that comes into view when needed instead of a full button that takes up screen real-estate.

**Comment by c16jonha** [comment]
Wouldn't it be better to just let the mousepointer be the indicator for moving the canvas since it changes automatically and remove the icon instead?

**Comment by c16jonha** [comment]
This issue is solved. View #4285 for more information.
