### ISSUE TITLE
Relations in the diagram has a fixed size

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4273]
When drawing a relation in the diagram, it always sets to a fixed size instead of the size the user chooses when drawing them. They are also impossible to scale after they have been drawn.

**Comment by HGustavs** [comment]
I think this is mostly what we want I think. Most of the time the diagrams will look strange if there are varying sizes of relationship symbols. So I would keep it to a single default size per diagram. Perhaps with a global setting for size.

**Comment by c16jonha** [comment]
Since not a real issue, this will be closed.
