### ISSUE TITLE
Minimize the toolbar on mobile

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4281]
One should be able to minimize the toolbar by pressing a button next to it's body. The toolbar should then slide away to the left of the screen. Once the toolbar has been minimized the usser should be able to maximize it again by pressing a button at the left side of the screen and make the toolbar slide out again.

![minimizemobile](https://user-images.githubusercontent.com/37794047/38294857-983e7528-37ec-11e8-926e-296bdfcc4318.png)

**Comment by HGustavs** [comment]
Not very high priority but there is a huge amount of screen real-estate that is not used for the diagram...

**Comment by a16juleh** [comment]
A similar functionality already exists. Solved through issue #4280.
