### ISSUE TITLE
Description for hotkeys needed

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4283]
A description for the hotkeys should be added to the diagram. There is a lot of empty space above the canvas where these descriptions could be implemented.

For exampe: Spacebar: Moves canvas

**Comment by HGustavs** [comment]
Im thinking as a small help icon + modal dialog or something along those lines....

The dead space is better removed completely... I want the canvas to occupy as much of the screen as humanly possible. Currently we have bezels on all sides...

**Comment by c16jonha** [comment]
This issue has been solved, see #4321 for more information about the solution.
