### ISSUE TITLE
Section Editor, Adding clock time to the date

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4284]
When solving #4180 a new issue was discovered. 

The clock time is currently not showing alongside the turn in-date of a dugga. 
The clock-time should be visible alongside with the date, if there is room. 
If there is not enough room to show the name of the dugga, the date and the clocktime (for example if you view the page on a mobile-screen) then the date should be prio. meaning that it should always be fully visible, the name of the dugga is visible to a certain amount of character (if the name is to long the remainder of the name is shown as elipsis ...) and the clock time can be removed if there is not enough room.

**Comment by d15marwi** [comment]
1) enable a time(hh:mm) deadline when creating a dugga
2) Store that variable in the datebase
3) print the time variable in the Section Editor togheter with the date

![image](https://user-images.githubusercontent.com/37793970/38406767-f66cd3c0-3976-11e8-89cd-85d67ae126f3.png)

**Comment by a16thegu** [comment]
@HGustavs, can you look at this mock-up suggestion?

**Comment by a16thegu** [comment]
After talk with client, all web browser now supports time with datepicker directly. Change current datepicker so it also has time and make it standard with HTML5 input.

**Comment by a16filol** [comment]
some browser does not suport datepicker in html5 (Firefox, safari) In firefox you could use date and time field but i dont think that is the most optimal way.
