### ISSUE TITLE
On branch #4181, arrow on collapsed menus are displayed incorrectly

### ISSUE THREAD

**Issue by b16linra** [HGustavs/LenaSYS#4307]
When a menu is collapsed based on data in local storage, the arrow icon is pointing down instead of right. In the image below, the top menu is collapsed based on local storage and the second one is collapsed by pressing on it.

![image](https://user-images.githubusercontent.com/37793838/38352306-0af73e4e-38b3-11e8-9c93-446f6e874627.png)

This issue is related to issues #4181 and #2854.

**Comment by HGustavs** [comment]
Also we want the state of this to be remembered using local storage.

In sortabletable we have a pretty robust way of storing / retrieving view state information from local storage. One good idea is  to look at that code and copy/re-implement something similar for these accordions.

It is really annoying that one has to re-collapse all the accordions on each page visit.

**Comment by b16linra** [comment]
A solution for remembering the state by using local storage has already been worked on, before we knew about sortabletable. It might be necessary to create a new issue to change the current implementation to the standardized sortabletable.
