### ISSUE TITLE
Exception when making new point at same position as last point when freedrawing.

### ISSUE THREAD

**Issue by b16petma** [HGustavs/LenaSYS#4311]
When making a freedraw figure and making the next point and the same position as the last one, we get exception and the code breaks.

**Comment by HGustavs** [comment]
Definitely a bug. 

This is the intended behavior for highlighting a section of the diagram, so it should not break.

**Comment by g18marma** [comment]
The issue seems to be resolved from previous merges. The bug does not exist as of right now.
