### ISSUE TITLE
Pressing enter changes the selected/most recent entity

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4314]
When you click on an entity and then press enter, the name of the entity disappears and the borders of the entity changes color. This also happens to the most recent entity if none are selected.

**Comment by HGustavs** [comment]
Weird behavior to say the least, bug or partially implemented feature?

**Comment by c16jonha** [comment]
Well. it's partially implemented since the enter button wasn't always functional, but this particular behaviour is not intended.

**Comment by c16jonha** [comment]
This issue seems to have been solved through the solution in #4464. This issue will now be closed.
