### ISSUE TITLE
Fix UI when resetting password

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#4317]
The UI when trying to change password (from login box -> forgot password) currently doesn't work. Add UI that flexes to the right of the login box. Each new step should replace the previous step (forgot password -> Enter username -> enter security question -> reset complete).

**Comment by HGustavs** [comment]
Screenshot for documentation of this visual bug is a good idea.

**Comment by HGustavs** [comment]
Are both visible simultaneously?

I suggest that login box disappears when we click reset password, but since it requires manual steps from system administrator it may be better to not get back to the login box after the reset, since the user forgot the login in the first place?

**Comment by a16jonis** [comment]
Yes they were visible simultaneously.

It is fixed now. Reset password box now replaces the login box.
