### ISSUE TITLE
New Icon for SwimLanes

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4320]
Swimlanes is a pretty good feature when it has been fixed,but nearly no students find it and make use of it.

Question: how to find the swim lanes and manke it more prominent on page.

Better Icon is one step.

**Comment by HGustavs** [comment]
A screenshot would be appreciated for documentation and for me to comment on.

**Comment by a16katba** [comment]
![swimlane-icon](https://user-images.githubusercontent.com/37793711/38408213-d6a9b458-397c-11e8-829f-6d0e04a31873.jpg)

**Comment by a16katba** [comment]
@HGustavs

**Comment by HGustavs** [comment]
New icon is much better.

**Comment by a16seplu** [comment]
This does not need to be an issue anymore right? we can close it?
