### ISSUE TITLE
In the result view there should be a clear indication of if students have submitted before deadline or not - Part three

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4334]
In order to better be able to prioritize grading, especially if we have reoccurring grading during a course, the system should indicate if a dugga has been submitted before deadline or not.

I would like the following (or similar):

when sorting on a particular dugga all ungraded duggas should be at the top in order of submitted date and time. The duggas submitted before deadline should be separated from the duggas submitted after the deadline and grace period by a line or by using a clearly different background color. If there exists a better way to visualize this I'm open to suggestions.
the ability to completely filter out submissions submitted after deadline
**the ability to set a grace period (swe: respittid) on the dugga deadline. This should default to the closest following workingday. A dugga submitted during this time should not be indicated as handed in too late**

**Comment by a16jonis** [comment]
Issues with better explanation has been made. Closing.
