### ISSUE TITLE
Markdown page design

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4335]
We need to create a design for the markdown preview page. the should contain a button that creates a pop-up window or something similar. This window must contain two textfields: one textfield for entering markdown code and one textfield for showing the translated html-code. This window must also contain a two buttons, one save button and one cancel button.

This issue is just focussed on visual design and not functionality, that comes later.
It should look like this:
<img width="851" alt="markdown mockup" src="https://user-images.githubusercontent.com/37794047/38418344-4c763d2c-399c-11e8-828c-559abf96cbce.png">

Furthermore some formatting buttons would be useful for more obscure markdown commands. Take the buttons in the github comment window as an example.
![formattingbutton](https://user-images.githubusercontent.com/37794047/38418504-e8a61b5e-399c-11e8-9ae0-544821ae6e03.PNG)

**Comment by HGustavs** [comment]
Dont we already have a mock-up of this?

**Comment by c16jonha** [comment]
This issue is solved.
