### ISSUE TITLE
Complications in SortableTable

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4337]
At the moment, group 2 and group 1 can't progress with several issues due to complications with the sortabletable folder. This needs to be fixed as soon as humanly possible. Since this issue affects several groups, members from all groups will work together to fix it.

- Fix the css
- intergrate the database
- implement with the server

**Comment by a16juleh** [comment]
We have fixed the basic CSS.

**Comment by HGustavs** [comment]
The implement with the server issue seems to be somewhat of a mis-understanding.

SortableTable works with a table structure that is exactly like the on-screen table. The data returned from the services should have mostly the corresponding structure.

Each service needs to adapt the table sent using json to fit how sortable table expects the table.

For example:

Sortable table wants 
~~~
var tabledata={
	tblhead:[
		"First/Last","Pnr","Num","Foo","Holk","Trumma"
	],
	tblbody:[
	],
	tblfoot:[]
}
~~~

For example the accessed service returns the folowing:

~~~
$array = array(
	'entries' => $entries,
	"debug" => $debug,
	'teachers' => $teachers,
	'classes' => $classes
);
~~~

In this case entries (which is the data that is to be displayed as a table) needs to be changed slightly.

~~~
$tblentries=array(
    'tblhead' => array('');
    'tblbody' => $entries;
    'tblfooter' => array();
);
~~~

**Comment by c16jonha** [comment]
Issue #4377 is a sub Issue to this Issue

**Comment by a16juleh** [comment]
We are trying to make the delete button dynamic. The problem seems to be that the tables primary keys are named differently.

**Comment by c16linst** [comment]
Sortabletable is already implemented for all our tables. Closing this issue.
