### ISSUE TITLE
Migration: Create the parser

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4341]
We need to write a parser that parses the Json-tables created in issue #4340.

The parser should accept the Json and turn it into an SQL-string.
For example the following Json should be parsed into the SQL-format shown bellow.
## Json Example
```
{
    ‘create’, 
    ‘users’, 
    ‘columns’: {
	 {‘uid’, ‘int’, ‘UNSIGNED NOT NULL AUTO_INCREMENT’}
         {‘name’, ‘varchar(30)’, ‘NULL’}
         {‘email’, ‘varchar(30)’, ‘NOT NULL’}
    },
    ‘Version’ => ‘v0.10’
}
```
## Desired SQL-format
```
CREATE TABLE users(  
    uid INT UNSIGNED NOT NULL AUTO_INCREMENT,  
    name varchar(30) NULL,  
    email varchar(30) NOTNULL,  
);
 ```

**Comment by HGustavs** [comment]
Or an even simpler more general way.

One that just creates the table

And the columns are added one by one separately.

This way, adding columns or adding tables use the same code for each column.

So there would instead be
[
{ ‘Version’:‘v0.10’,[
{‘create’, ‘users’},
{'column','users',‘uid’, ‘int’, ‘UNSIGNED NOT NULL AUTO_INCREMENT’},
{'column','users',‘name’, ‘varchar(30)’, ‘NULL’},
{'column','users',‘email’, ‘varchar(30)’, ‘NOT NULL’}
]
},
{ ‘Version’:‘v0.11’,[
{‘create’, ‘student’},
{'column',,'student'‘uid’, ‘int’, ‘UNSIGNED NOT NULL AUTO_INCREMENT’},
]
},
,
{ ‘Version’:‘v0.12’,[
{'column','greger'‘uid’, ‘int’, ‘UNSIGNED NOT NULL AUTO_INCREMENT’},
]
}
]

**Comment by HGustavs** [comment]
~~~
{"insert","users","ssn","20070401-5566","name",'greger'}
~~~

~~~
INSERT INTO USERS(SSN,NAME) VALUES('20070401-5566','greger');
~~~

**Comment by HGustavs** [comment]
Also, the create/alter example above works even if the table has already been created whereas the "complete create" example works only if users table does not already exist.

**Comment by a16filol** [comment]
You are not able to create an empty table. Im thinking of a workaround or do you have any suggestions on how to solve that problem.

**Comment by HGustavs** [comment]
How about adding key definition for that table into the create table definition.

A table with a key column(s) should work well.

Im thinking of something like

{‘create’, ‘users’, ‘uid’, ‘int’, ‘UNSIGNED NOT NULL AUTO_INCREMENT’},

**Comment by a16filol** [comment]
Yes that was the soulution i was thinking of. What do you have in mind for foreign keys ?

**Comment by a16filol** [comment]
Also should the column be modified if it allready exists?

**Comment by a16filol** [comment]
The user could do something like ``` ['column', 'gunnar', 'rid', 'int', 'UNSIGNED NOT NULL; FOREIGN KEY (rid) REFERENCES roger(rid)'], ``` That would work. But i don't think this a good solution.

**Comment by HGustavs** [comment]
I would separate the key into a separate string...  

['column', 'gunnar', 'rid', 'int', 'UNSIGNED NOT NULL;','FOREIGN KEY (rid) REFERENCES roger(rid)']

PHP array and json is the same thing so it does not matter, the same structure in php and javascriot will translate to the same JSON.
