### ISSUE TITLE
SectionEd: Cannnot remove dugga

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4343]
When you attempt to remove a dugga that has answers from a student, the dugga can't be removed. 

The issue is that a foreign key restraint fails. This causes a failure when trying to delete the listentries.
What actions should be made? Should we display a well formated message to the user that he/she can not remove the specified listentries because of the connected answer. Or should we be able to remove it either way?

**Comment by HGustavs** [comment]
This seems to be the intended behavior.

We may (functionally) NEVER lose the data submitted by a student, so if someone has submitted something to an exam this exam can not be deleted.

A better error message will take care of this issue?

~~~
"You are not allowed to delete tests after students have submitted assignments in it"
~~~

**Comment by a15magkn** [comment]
Since this seems to be working as it should, this issue will be closed.
