### ISSUE TITLE
Courseed - Change buttons for Edit Course and New Course Version

### ISSUE THREAD

**Issue by b16linra** [HGustavs/LenaSYS#4354]
As requested by @HGustavs, change the functionality of the buttons for "New Course Version" and "Edit Course" on the courseed page.

![image](https://user-images.githubusercontent.com/37793838/38483467-47027a8e-3bd3-11e8-97d0-890ed94c85af.png)

Possible solution is to combine these buttons into one, or simply remove the "New Course Version" button, as it already exists when opening up a specific course page.

This is related to issue #3483 .

**Comment by b16linra** [comment]
Some clarification on point 3 @HGustavs , do you want these buttons to remain the same as they are right now, or should they be changed?

**Comment by HGustavs** [comment]
Im thinking that the new version should remain unchanged
New course should be a FAB (it is not currently?)
The pen icon / cog wheel should not be able to add new versions (remove new version functionality from here) only to edit properties of existing course... and merged into one button.

**Comment by b16linra** [comment]
While in the courseed (Course Organization System), clicking the FAB opens this dialog:

![image](https://user-images.githubusercontent.com/37793838/38491511-5e167db0-3bec-11e8-8fcf-69d8998a9ff8.png)

If a course has been selected/clicked on, the FAB opens this dialog:

![image](https://user-images.githubusercontent.com/37793838/38491566-846b6520-3bec-11e8-9cd9-0d8f364ddbea.png)

**Comment by f16linli** [comment]
I dont quite understand what you mean with this:
"Remove the clunky selection highlight (from javascript, css and php, wherever it is present) which does not appear in any other dialog."

do you mean the yellow box around the course in the screenshot above?

**Comment by f16linli** [comment]
I found the yellow box that appeared if the cogwheel was clicked and I will remove it.

**Comment by c16matan** [comment]
Solved.
