### ISSUE TITLE
SectionEd: No "Are you sure"-prompt unless you're about to delete something.

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4358]
When you create, edit or delete something a pop-up window shows up that asks you "Are you sure you want...." and this pop-up should only be present if you are trying to delete something.

Has to do with #4097 #4330

![screenshot from 2018-04-09 09-54-31](https://user-images.githubusercontent.com/37794262/38486211-9d0b8ef8-3bdc-11e8-9942-fad5c3132d06.png)

**Comment by a14oliri** [comment]
We need to talk with a16filol about issue #4330 since we are editing in the same place.

**Comment by a16konka** [comment]
This issue has been resolved, therefore it should be closed!
