### ISSUE TITLE
Remove nearly all gray courses from test data

### ISSUE THREAD

**Issue by a14oliri** [HGustavs/LenaSYS#4362]
#4282 

Remove nearly all gray courses from the test data(visibility = 0) from database. 

![screenshot from 2018-04-09 11-15-05](https://user-images.githubusercontent.com/37795562/38489680-69d74580-3be7-11e8-9b38-3faff0b96446.png)

**Comment by HGustavs** [comment]
Nearly all would perhaps be a more moderated number.
We need at least one gray course for testing that it still works.
