### ISSUE TITLE
SectionEd/DuggaEd: Explain why a title is invalid

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4366]
Certain characters are invalid and cannot be used in a title. The submit-button is greyed out but it might be nice with a pop-up window when hovering over the button that explains that certain characters are not allowed and that is why the button is greyed out. 

<img width="552" alt="skarmavbild 2018-04-09 kl 10 09 00 fm" src="https://user-images.githubusercontent.com/37794262/38491024-04f6f7ba-3beb-11e8-9e1b-d5ef0d62a537.png">

**Comment by HGustavs** [comment]
Great work!

No need to explain further. Since this is a teacher only interface, we can rely on prior knowledge.
