### ISSUE TITLE
closing boxes by clicking outside the box does not work in mobile (touch) version

### ISSUE THREAD

**Issue by e12johka** [HGustavs/LenaSYS#437]

**Comment by a13jorla** [comment]
Mobile funktions not priority att this moment.

**Comment by HGustavs** [comment]
I bump this issue. 

Is this still a problem?

**Comment by c14caran** [comment]
Which boxes are this issue about?
![image](https://cloud.githubusercontent.com/assets/26733338/25900528/09888716-3594-11e7-8dbe-d429dd0a7ad9.png)
All boxes like the ones above can't be closed by clicking outside on either a computer or a phone. I have not found one box that closes when pressing outside on a computer.

**Comment by a17poner** [comment]
FIxed, loginboxes can be closed both with a normal mouseclick and touch click in codeviewer.
