### ISSUE TITLE
DuggaEd: Illegal characters when renaming dugga(test)

### ISSUE THREAD

**Issue by a14oliri** [HGustavs/LenaSYS#4373]
#4208 

After creating a new dugga the name can be changed and can contain illegal characters.

![screenshot from 2018-04-09 13-48-35](https://user-images.githubusercontent.com/37795562/38496159-c27cb548-3bfc-11e8-92ed-b74d47d34ba5.png)

**Comment by a16konka** [comment]
This issue is design-related and after speaking to the customer it was decided that this design should change, and the ability to edit through the tables columns should not be allowed anymore. Therefore this issue is no longer relevant. Continuation of this issue: #4382
