### ISSUE TITLE
SectionEd: Dialogue-box title

### ISSUE THREAD

**Issue by a14oliri** [HGustavs/LenaSYS#4376]
Dialogue-box title is "Edit Item" both when editing and creating new items. 

![screenshot from 2018-04-09 14-15-18](https://user-images.githubusercontent.com/37795562/38497184-860fcc9a-3c00-11e8-8ce1-f63d85790850.png)

**Comment by HGustavs** [comment]
Good idea to fix this.

Come up with a suitable title.
