### ISSUE TITLE
AccessEd: "Back-icon" button needs redirection

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4378]
At the moment the back-button redirects the user to "courseed" while it should direct to "sectioned". 

## This button

<img width="1438" alt="skarmavbild 2018-04-09 kl 3 26 44 em" src="https://user-images.githubusercontent.com/37794262/38500427-aa4f4c20-3c0a-11e8-8f38-692c46ff6ea4.png">

**Comment by HGustavs** [comment]
This button is not "back" but "down".

Example 
* If we navigate to file editor from code example and then press down we should end up in section editor, not in code example.
* If we navigate to access editor from section editor and then press down twich - we should end up in course editor - access to section to course....

**Comment by f16linli** [comment]
@HGustavs I dont quite understand what you mean?
is the current functionallity of the botton right or wrong?
If it is wrong, what is wrong and what should it do instead?

**Comment by f16linli** [comment]
@HGustavs poke
