### ISSUE TITLE
SectionEd: Duplicating items when going from hidden to public

### ISSUE THREAD

**Issue by a14oliri** [HGustavs/LenaSYS#4381]
After creating a new item as Visibility = hidden and then editing it to Visibility = public it will create a new item and not remove the hidden one.

In the picture, the top item has been created as hidden, and the bottom item is the public one. Both items has the type of Header, but this bug will affect every type. 

To recreate this bug: Go to sectioned, press "+" to create a new item, create the item as a hidden one, press the cog-wheel after it has been created and change the visibility to public.

![screenshot from 2018-04-09 15-38-25](https://user-images.githubusercontent.com/37795562/38501008-394751b0-3c0c-11e8-9b62-297658caaea6.png)

**Comment by a14oliri** [comment]
This will also happen when changing visibility to Login.

**Comment by a16konka** [comment]
Issue has been solved
