### ISSUE TITLE
SectionEd: "Type" in editing reverts

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4392]
Sometimes when editing an entry by using the "cog-button" the "Type" is not saved and can be changed accidently if the user is not carefull. For example if the entry is a "Test" when the edit-menu pops up the type is changed to "Header" by default. It would be better if the previously selected "Type" was saved as the default. 
For example a "Test" is always saved as a "Test".

**Comment by HGustavs** [comment]
I think this is a bug? 

The previous value should always be the default. 

If one presses ok without changing something no change should be made to the data.

**Comment by a14oliri** [comment]
This problem seems to only happen if the item that we are editing has the type of "Test". When creating a new item, the test-option is grayed out. This may be why it wont save the type when editing.

**Comment by a14oliri** [comment]
Seems to have been fixed when adding more test-data. The test-type-option is no longer grayed out and it does not change any settings when pressing edit -> save.
