### ISSUE TITLE
DuggaEd: No "Are you sure"-prompt unless you're about to delete something.

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4396]
When you create, edit or delete something a pop-up window shows up that asks you "Are you sure you want...." and this pop-up should only be present if you are trying to delete something.

Has to do with #4097 #4330

screenshot from 2018-04-09 09-54-31
![image](https://user-images.githubusercontent.com/37794262/38556402-da9e7274-3cc9-11e8-94de-8197af666e58.png)

**Comment by a14oliri** [comment]
This issue seems to have been resolved after DuggaEd has been rebuilt with SortableTables.
