### ISSUE TITLE
Markdown shortcut buttons lack functionality

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4425]
The shortcut buttons need to have proper functionality, meaning they write out their assigned markdown code when pressed. The dropdown menu could also use a better visual design so that the alternatives don't look like links.
![shortcuts](https://user-images.githubusercontent.com/37794047/38660557-f363d5c8-3e2d-11e8-93ee-a6c162af117f.PNG)

**Comment by a16adala** [comment]
Some markdown functionality doesn't seem to work, commands for cursive text for example. Problem should be in markdown.js
