### ISSUE TITLE
SectionEd: Submit button in the wrong place when creating new item

### ISSUE THREAD

**Issue by a14oliri** [HGustavs/LenaSYS#4427]
Cancel button seems to have moved. It should be in the lower left corner. 

![screenshot from 2018-04-12 09-34-08](https://user-images.githubusercontent.com/37795562/38662479-b577995a-3e34-11e8-9c66-485137343d2f.png)

**Comment by b16linra** [comment]
This issue was solved by pull request 4424 which solved issue #4423.
