### ISSUE TITLE
SectionEd: "Test" not available as a type in Edit Item/ New Item

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4443]
When trying to create or edit an item i the sectioned, for some reason you are unable to choose "Test" as the type, (it defaults to "Header"). 

It would be nice if the previously chosen type is remembered, or at the very least you can choose "Test" as the type.
  
![sectioned edit item](https://user-images.githubusercontent.com/37794262/38667942-28caa6b4-3e43-11e8-9b4b-d3997735b84a.JPG)

![sectioned new item](https://user-images.githubusercontent.com/37794262/38667948-2caf9a28-3e43-11e8-9841-55f75020d084.JPG)

**Comment by a16linas** [comment]
The issue is a 'user error', as the test type isn't available while there is no available dugga in the "Test" section. A new issue will be created about making the warning easier to notice.
