### ISSUE TITLE
SectionEd: Change the FAB "+"-buttons position

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4445]
At the moment there are time when the FAB-button almost covers the Edit and Delete buttons, and it could stand to be moved slightly to the left. When it comes to exactly how much, some judgement from the technician will be required. 

![sectioned move fab button](https://user-images.githubusercontent.com/37794262/38668829-1135c72a-3e45-11e8-88e1-d6d2803c7192.JPG)

**Comment by b16linra** [comment]
This issue was solved by pull request 4654 by making it possible to scroll further down the page; this puts the add button below the "edit" and "delete" buttons. This issue will be closed.
