### ISSUE TITLE
SectionED: Fix the placement for the hamburger-button in the navigation-menu.

### ISSUE THREAD

**Issue by b16karhe** [HGustavs/LenaSYS#4449]
The issue is a continuation of issue #4435 and refers to the **button** shown below:
![5](https://user-images.githubusercontent.com/37793806/38671341-6e4b1284-3e4b-11e8-962b-e2480d0dc07f.png)

**Comment by a16konka** [comment]
@HGustavs I've made a mock-up for what I think is the best position for the menu button (mobile). Should we proceed with it or do you have any other ideas regarding the positioning?

## Older
<img width="363" alt="skarmavbild 2018-04-16 kl 9 39 43 fm" src="https://user-images.githubusercontent.com/37795608/38799151-eaf64aea-4163-11e8-9b0e-2e7f3dc003d8.png">


## Mock-up
<img width="376" alt="skarmavbild 2018-04-16 kl 9 39 18 fm" src="https://user-images.githubusercontent.com/37795608/38799237-3482fde8-4164-11e8-972f-6a51f1d434ec.png">
<img width="375" alt="skarmavbild 2018-04-16 kl 9 39 04 fm" src="https://user-images.githubusercontent.com/37795608/38799240-370fe9f4-4164-11e8-8f3b-8548ca78ae45.png">
