### ISSUE TITLE
SectionEd: Change the functionality of "+"-FAB button

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4450]
There are two "+"-buttons in the sectioned at the moment and these do the exactly same thing. There is a request from the customer that the behavior of the FAB-button should change. 

## Requested change from the customer

When the FAB-button is pressed , rather than a pop-up window showing up where you select type, name etc. there should be no pop-up window with options.

Instead when pressing the button several options appear in a "bubble-form", one bubble for each option of type. 

## The functionality of this button should be changed... 
![sectioned fab button](https://user-images.githubusercontent.com/37794262/38673421-8dace9e4-3e51-11e8-9228-e1ee4b455578.JPG)
# 

## ...to something like this
<img width="123" alt="skarmavbild 2018-04-12 kl 4 53 59 em" src="https://user-images.githubusercontent.com/37794262/38685641-ab9ecaf0-3e72-11e8-8adb-574df93ae0b2.png">

**Comment by a16konka** [comment]
Here are some mock-ups for the new FAB button funtionality, based on the principals of material design. 

@HGustavs I tried different color schemes, could you give us some feedback on which color scheme do you like the most, and if you would like a different combination.

## Mockup 1
<img width="1440" alt="skarmavbild 2018-04-13 kl 8 55 47 fm copy" src="https://user-images.githubusercontent.com/37795608/38725443-a17a671a-3f07-11e8-9905-6e77cff16270.png">


## Mockup 2 
<img width="1440" alt="skarmavbild 2018-04-13 kl 8 55 47 fm copy2" src="https://user-images.githubusercontent.com/37795608/38725460-b1737e5e-3f07-11e8-978c-4b19cbf4a9d9.png">

**Comment by b16karhe** [comment]
**Complete so far.**
