### ISSUE TITLE
SectionEd: Clarify why "Test" cannot be chosen as a type

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4457]
When there is no dugga to be chosen as a "Test" you are unable to select "Test" as a type. This is explained already however it's easy to overlook and could lead to user-error. Therefore a pop-up explanation is suggested. 

## The current situation
![sectioned plain edit item](https://user-images.githubusercontent.com/37794262/38677460-a14e74ce-3e5e-11e8-9cf9-f23073a8b585.JPG)

## The suggested solution: something similar to this 
![sectioned edit item pop-up](https://user-images.githubusercontent.com/37794262/38677475-aa2a9258-3e5e-11e8-922a-dfa0b81645c1.JPG)

**Comment by b16linra** [comment]
The pull request caused a new issue that was missed during testing. A new issue, #4500, has been created to deal with this problem.
