### ISSUE TITLE
SectionEd: The arrows show a strange behavior 

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4467]
When an item is moved between two sections, the original content of the section are visible when the section is open, while the new items are visible when the section is closed.
This must be resolved.

In the Screenshot One, the section should be collapsed.  
## Screenshot One
![screenshot from 2018-04-12 15-37-04](https://user-images.githubusercontent.com/37795562/38680800-7a9eafca-3e67-11e8-9d0b-2c24abd994d8.png)

## Screenshot Two
![screenshot from 2018-04-12 15-37-14](https://user-images.githubusercontent.com/37795562/38680809-7f3be282-3e67-11e8-9db0-ef18df1c71b4.png)

**Comment by a16filol** [comment]
Closed this isssue in pullrequest 4473
