### ISSUE TITLE
SectionEd: Page title always showing Section Editor

### ISSUE THREAD

**Issue by a14oliri** [HGustavs/LenaSYS#4480]
Page title always says Section Editor, this may not make sense to the user, maybe the course name would make more sense as the page title.

## As it is now

![screenshot from 2018-04-13 09-22-49](https://user-images.githubusercontent.com/37795562/38722335-ee5fca20-3efd-11e8-8dc2-3facc946d65e.png)

## How it could be

![screenshot from 2018-04-13 09-55-47](https://user-images.githubusercontent.com/37795562/38723297-e78e5678-3f00-11e8-94b7-3898a5fef3a0.png)

**Comment by a16filol** [comment]
This issue is solved in pullrequest 4492.
