### ISSUE TITLE
DuggaED: Working with implementing the sortable-table. Buttons for adding a dugga

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4482]
Since the implementation of the sortableTable there is no buttons to add a new dugga/test.
As per request of the customer there should be two buttons to add new items/duggas.
One button that is a yellow "+", that opens a window with options. The way it currently works in sectioned could be used as a prototype. 

## This button should exist in duggaed as it does in sectioned
![skarmavbild 2018-04-13 kl 8 52 10 fm](https://user-images.githubusercontent.com/37794262/38722497-5e1b0e10-3efe-11e8-92cc-0329a4dc5166.png)

There should also be a FAB-button in sectionEd that is currently being reworked in issue #4450 
Once this issue is closed this can be used as a prototype for the FAB-button in duggaEd (with slightly different functionality, dugga-templates etc.).

**Comment by b16linra** [comment]
This has been fixed in pull request 4482.
