### ISSUE TITLE
DuggaED: Working with implementing the sortable-table. Adding "Delete"-buttons

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4497]
Since the implementation of the sortableTable in duggaed we need to insert buttons to delete
 items. These will need one column each. As a working prototype we will use the look and layout from the sectioned.

## These numbers should be the delete buttons
![duggaed ska bli delete](https://user-images.githubusercontent.com/37794262/38725935-173ed87c-3f09-11e8-9850-d1845e4005e1.jpg)

## Use this as a working prototype
![skarmavbild 2018-04-13 kl 8 52 10 fm](https://user-images.githubusercontent.com/37794262/38725717-8469c8cc-3f08-11e8-925a-df98793c72f2.png)

**Comment by b16karhe** [comment]
@a14oliri

**Comment by a14oliri** [comment]
Found problems with the solution, it will always delete the last element in the list instead of the one that you click on.
