### ISSUE TITLE
SortableTables in Accessed - part two

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4502]
#4162
We need to do the following (includes suggested suitable sub-goals)

Put sortableTables in Accessed (allows us to get uniform design, and 'free' sorting and filtering

* Use sortable table for rendering rows
* **Use sortable table for filtering**
* Use sortable table for column sorting

Remove edit single user dialog and replace with cell editing from sortabletables

**Comment by a16jonis** [comment]
Solved
