### ISSUE TITLE
DuggaED: Working with implementing the sortable-table. Adding "Arrow-functionality"

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4507]
In the duggaEditor there is a section that should be clickable "arrows" that, when clicked, opens up a sub-section that shows the content f this section.
This "arrow-functionalty" needs to be implemented.

## These numbers should be arrows

![duggaed ska bli arrows](https://user-images.githubusercontent.com/37794262/38726906-d084c164-3f0b-11e8-9152-a6790516c9d0.jpg)

**Comment by b16karhe** [comment]
@HGustavs, You said something about wanting a new design because it was a common misstake to add variants to the wrong dugga. 

_How the old version looked:_
![oldarrow](https://user-images.githubusercontent.com/37793806/38857673-2133e20e-422a-11e8-9433-bdff56942228.png)

_A possible new version:_
![mockupnewarrow](https://user-images.githubusercontent.com/37793806/38859596-a86395cc-422e-11e8-872c-a9f5240eb73c.png)

**Comment by HGustavs** [comment]
That is one way of doing it....

How about integrating it with the variant editor.. 

One common work task is copying from one variant to another. By placing this list at the top of the variant editor we can do that with very few clicks, and it also makes the whole process glanceable.

**Comment by HGustavs** [comment]
![screenshot 2018-04-17 11 52 07](https://user-images.githubusercontent.com/6978801/38862733-fc373922-4235-11e8-80a9-a15b759e53c5.png)

**Comment by b16karhe** [comment]
**The new view for variants is a work in progress!**

_This will be the default view when opening variants in duggaED:_
![add](https://user-images.githubusercontent.com/37793806/39034206-dd3ec444-4475-11e8-9855-118fde2d775b.png)

_This is how the editingview will look for a disabled variant:_
![savewindow](https://user-images.githubusercontent.com/37793806/39034301-335f3f48-4476-11e8-8b49-65540009138b.png)

**Comment by b16karhe** [comment]
_**Will close but new issues on will be created on these things.**_
![bestpic](https://user-images.githubusercontent.com/37793806/39039339-a1c2e64c-4485-11e8-8a73-9e436378ffee.png)
