### ISSUE TITLE
Implement sortable table on the result page

### ISSUE THREAD

**Issue by f16linli** [HGustavs/LenaSYS#4513]
Implement a sortabla table on the result page below the current table.

after implementing the structure for sortable table, implement additional features in the sortable table after this issue is complete.

**Comment by HGustavs** [comment]
My suggested workflow is to remove the "old" type completely and then start slowly with sortable one feature at a time.

1. Display Table at all
2. Display working buttons
3. Add sorting
4. Add filtering
etc

I would have a temporary for-comparison-only version of the old table e.g. resulted_old.js / resulted_old.php that can then be removed when finished. The _old files do not even need to be uploaded to the github repository but used by developers locally.

**Comment by f16linli** [comment]
@HGustavs we could use some feedback on how you would want the design for the result page should look since we cannot have double headers like in the previos table.

This is our current progress:
![image](https://user-images.githubusercontent.com/37804205/38876763-74bffc7c-425d-11e8-9b23-baad8825ffe4.png)
