### ISSUE TITLE
SectionEd: Yellow border not removed when pressing escape

### ISSUE THREAD

**Issue by a14oliri** [HGustavs/LenaSYS#4515]
Yellow border that comes up when clicking the cogwheel does not get removed when pressing escape instead of pressing "cancel" or the X.

![screenshot from 2018-04-13 13-25-24](https://user-images.githubusercontent.com/37795562/38732359-2cac5dbe-3f1e-11e8-9959-ce92a2b7cdd4.png)

**Comment by a16filol** [comment]
This issue is solved in Pullrequest 4516.
