### ISSUE TITLE
More example duggor

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4525]
Create more duggor that can be used for testing purposes

**Comment by c16matan** [comment]
Implemented last week. Closing.

**Comment by c16matan** [comment]
I don't know if i missed click or something, but this is implemented. Closing

**Comment by d16linja** [comment]
#4282 
With this issue we fixed the old duggas so that they fit the new format and show up under the "test" page in LenaSYS. We also added deadlines so that the issues with the time could be worked with more easily, and added the new duggor as listentries so that the show up in a course

**Comment by c16matan** [comment]
Implemented. Closing.
