### ISSUE TITLE
Markdown shortcuts fix

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4532]
The shortcuts are currently working, but not without faults. For example they stop working after a line,break. There also seems to be no implementation of italics via the shortcut. When using the bold shortcut, the positon of the typer should be automatically placed in the middle of the bold asterisks.

![astersiks](https://user-images.githubusercontent.com/37794047/38793285-ebfbee3a-4150-11e8-8e81-61294f6c70bd.PNG)

**Comment by HGustavs** [comment]
Screenshot?
