### ISSUE TITLE
Group-Functionality: Forensics, what is left in DuggaEd?

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4539]
After deleting the grouped.php and grouped.js (as per request fro the customer) a lot of functionality was "lost". However a lot of group-realted functionality is still requested in other parts of the system. 
It would be good to have an overview of the code and see if there are any traces of group-related features left in the code, and if this code is usable?
-Check the files duggaed.php & duggaed.js
-Are there variables?
-Are there functions?

**Comment by a14oliri** [comment]
There does not seem to be any group-related variables or functions in duggaed.php or duggaed.js. The files were not modified in #4188 and don't seem to have had any group variables or functions going back and looking in our first weeks group branch (branch G3V01-2018). There however seems to be group-stuff left in /Shared/dugga.js.
