### ISSUE TITLE
DuggaEd: Check Mobile browsing

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4549]
This issue is a part of #3001 

* **"The tests-page is zoomed out."**

Check the tests-page in the Dugga Editor and check if  the layout and formatting is acceptable on reasonably big mobile screens, (eg. not a iPhone4 etc.)

**Comment by b16linra** [comment]
It seems that this might be a problem only in Chrome.

**Comment by b16linra** [comment]
The zoom level can be fixed, but making the tables work on smaller screens can be difficult. This is probably not even necessary as @HGustavs has mentioned that it is the pages which students use that should be better adjusted for mobile devices.

**Comment by b16linra** [comment]
The zoom level can be fixed, but making the tables work on smaller screens can be difficult. This is probably not even necessary as @HGustavs has mentioned that it is the pages which students use that should be better adjusted for mobile devices.

**Comment by a16linas** [comment]
The mobile view works fine now
