### ISSUE TITLE
Collapsable dugga-view.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#455]
The dugga-view should remember if a dugga and its variants are collapsed in the view or not.
By adding an attribute collapsed to dugga we can remember the collapsed state of the dugga-elements for easier editing.

**Comment by a13arnhe** [comment]
Solution will add saving of collapsed or not both in the dugga view and in the moment view.

**Comment by HGustavs** [comment]
Well saving as in local storage?

This is per user and not per all users, or am I missing something?

**Comment by a13arnhe** [comment]
Getting fixated on testing with the user logged on into the system and that is usually used, I know realize that of course the changes of one user changes it for all users, which will not do. Now I am just thinking if it would be best to store in local cache for faster and less querying the database and server, or would actually making a connecting table between user,course,moment, and collapse state better. I do fear that adding yet another table and yet another query call puts more strain then is wanted on the database.

**Comment by HGustavs** [comment]
Local storage. No database. Much better that way as it remembers the size for the device and not for the user.

There is local storage stuff in the code viewer for this kind of stuff. It may be a good idea to take a peek at how they did that in the code viewer. I think it has to do with the resizing of the boxes, which is remembered across the page views.

**Comment by a13arnhe** [comment]
Great, I will look into this in the coming week and implement this.

**Comment by a13arnhe** [comment]
I made a solution for this that stores the collapse states for every moment and dugga as a cookie on the local system. The cookies are persistent cookies and have a lifetime of 15 days, with fetches and changes to the cookies, this time is refreshed again to 15 days. This way no querying the db is needed and the cookies can simply be fetched from the local system to both initiate the collapse lists or to update them. See pull request #2156 for changed code

**Comment by a13arnhe** [comment]
There would however be no problem to turn it into a solution that stores it in localStorage. That could however bring some compatibility issues it is much newer than cookies. Note also that even though the cookies need to be sent and received by the client and server, the traffic is not that much since its only sent to init the list and when the list is changed. What do you think? should we store as cookies for now or jump into localStorage?
