### ISSUE TITLE
SectionEd: FAB-button. Position & functionality when Mobile browsing

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4555]
The following issue is part of #3001  

* **The FAB is not visible unless you zoom out a lot and when doing that the + in the button is not centered in the yellow circle. (Are both the new item-button in the menu and the FAB needed at the same time if you're viewing the page from a mobile device?)**

Since the FAB-button in the Section Editor is made per request from the customer, this can be used as a working prototype for the FAB in the Dugga Editor.

**Comment by a15magkn** [comment]
The FAB-button in the DuggaEd as been moved to it's own issue #4572
