### ISSUE TITLE
Datum efter rättad dugga är inte korrekt

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#456]
Istället för datumet när duggan blivit rättad så visas "null". Jag tror att vi inte skickar med 'marked' i vår respons.
/M

**Comment by HGustavs** [comment]
I may be mistaken but it seems that this issue is written in some unknown middle-earth type mystical language.

**Comment by a13chrju** [comment]
the date for when a test is marked is now stored in the db.
