### ISSUE TITLE
Re-adding dropdowns in access view

### ISSUE THREAD

**Issue by a16seplu** [HGustavs/LenaSYS#4562]
Re-adding the dropdown menus that were removed from access view previously

**Comment by HGustavs** [comment]
screenshot of this would be nice.

**Comment by b16filor** [comment]
@HGustavs 
After changes (in red circle):

![readd](https://user-images.githubusercontent.com/36665559/38858891-29c91850-422d-11e8-8fa6-723827fae6fc.JPG)

**Comment by HGustavs** [comment]
This seems to work well.

Try to make something generic (e.g. makedropdown function) that can be used for all three dropdowns.
