### ISSUE TITLE
SectionEd: Grade overview with Pie Chart, Part 1 (ref #4185)

### ISSUE THREAD

**Issue by d15marwi** [HGustavs/LenaSYS#4565]
First part of original issue #4185, needed to split the original issue into 2 or 3 parts

The first step we will take is to add a pie chart in the first coloum of the swimlane/deadline table(se picture) without any function. 

![image](https://user-images.githubusercontent.com/37793970/38800273-2971a9e2-4167-11e8-899a-591d99fcc48a.png)

**Comment by d15marwi** [comment]
Updated version


![image](https://user-images.githubusercontent.com/37793970/38813094-5d44be04-418e-11e8-9497-b56489c17047.png)

**Comment by b16karhe** [comment]
Done
