### ISSUE TITLE
SectionEd: Grade overview with Pie Chart, Part 2 (ref #4185)

### ISSUE THREAD

**Issue by b16linra** [HGustavs/LenaSYS#4566]
This is part 2 of the original issue #4185 that has been seperated into smaller issues. See Part 1 here: #4565.

In this part, functions necessary to connect data to the pie chart will be created.

**Comment by d15marwi** [comment]
Works, the solution is not very good and hard to understand. Its building on the same concept as the swinlane colors are build on. Could be better but it works.

**Comment by b16linra** [comment]
The solution depends on data that is being returned for the swim lane diagrams. A better solution might be to separate the two so that the pie chart can be moved elsewhere if desired.
