### ISSUE TITLE
Inconsistent functionality for connection lines

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4567]
It is possible to select and move a line that connects an entity with a relation, but not a line that connects an attribute and an entity. The lines should not be draggable at all.

![eh](https://user-images.githubusercontent.com/37794047/38857613-001856b8-422a-11e8-819d-fb65232c2380.PNG)

Note that the lines should still move together with the objects they're connected to when the objects are moved.

**Comment by HGustavs** [comment]
Screenshot.

No lines should be draggable imho.

This is especially hard on mobile.

I think it should not be possible to make "dangling" lines that have an endpoint in one end but not the other.

**Comment by c16jonha** [comment]
Updated the issue description. A new issue will be created for the "dangling" lines.
