### ISSUE TITLE
DuggaEd: Change the "Deletion-confirmation"-message

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4568]
At the moment when you delete something in the DuggaEd, you get a message from the web-browser. This message should be the same as it is seen in the SetionEd.

## At the moment this shows up when the delete-button is pressed...
![confirmdeletefel](https://user-images.githubusercontent.com/37794262/38801183-78e3768e-4169-11e8-9ed5-51ca53e7e210.PNG)

## ...And this is the desired end-result
![confirmdeleteratt](https://user-images.githubusercontent.com/37794262/38801239-9c6f2d82-4169-11e8-901a-68bf6fbbf4c8.PNG)

**Comment by a14oliri** [comment]
Found issues with the solution by #4497, will put this issue on hold until they have solved it. The problem with their solution was that the item with the greatest ID would always get deleted.
