### ISSUE TITLE
DuggaEd: Change the delete-button to a cancel-button from the Edit-window

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4569]
At the moment when you press the cog-button, the edit window pops up. In this window there is a button that is used to delete items, but since a separate delete-button (a trashcan) will be added, the delete-button in the edit-window can be removed.

This button could be changed to a "Cancel"-button as seen in #4599 

## This button should be removed
![deleteknapp](https://user-images.githubusercontent.com/37794262/38801497-458314ec-416a-11e8-90fd-3be80847242b.PNG)

**Comment by d15marwi** [comment]
To long rows, check code std
