### ISSUE TITLE
DuggaEd: Which columns from the "Edit Dugga"-window should exist?

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4571]
At the moment there are more options in the window that shows up when you press "Edit Dugga" than there are columns for. 
For example: there is a column for Gradesystem and Template, but there is no column for Start Date.

Should more columns be added to match the options given in "Edit Dugga"

## The columns in question
![vilkacolummer](https://user-images.githubusercontent.com/37794262/38807257-52f33b9a-417c-11e8-9c3e-8f3d269c72df.PNG)

## "Edit Dugga"-window
![30711879_10211536498715312_3841271311905062912_n](https://user-images.githubusercontent.com/37794262/38807274-59336d5e-417c-11e8-95ce-07d3ebd7d302.png)

**Comment by HGustavs** [comment]
That seems about right.

**Comment by a16konka** [comment]
This issue is no longer relevant therefore it should be closed.
