### ISSUE TITLE
SectionEd: Ensure that the background color fills the entire page on mobile screen

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4579]
This issue is based on #4548 

## "The background color doesn't fill the entire page."

This is slightly vague since there are no screenshots of the issue, but try to replicate the problem in the Section Editor to see if it stills exists. If that is the case then it should be solved, but if the problem can't be replicated the issue can be closed. 

Be sure to test different sizes of screens.

**Comment by a16linas** [comment]
Could not replicate the issue, therefore closing the issue.
