### ISSUE TITLE
Better styling in fileed

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#4581]
The fileed page needs some minor fixes regarding the styling:
- ~~Remove the extensions from file names~~
- ~~Make links clickable~~
- ~~Fix editor column and icon for all files~~
- ~~Change the headlines in the ”Add File/Link” pop-ups~~
- ~~Remove the move cursor from the headlines (in the ”Add File/Link” pop-ups)~~
- ~~Create a margin between buttons and table~~

**Comment by a16juleh** [comment]
Fixed "Make links clickable"

**Comment by HGustavs** [comment]
Extensions should be in a separate column... not removed... since there is no current screenshot I dont know if that is the case or not.

**Comment by a16juleh** [comment]
Fixed "Change the headlines..", "remove the move cursor.." and "create a margin between button and table"

**Comment by HGustavs** [comment]
How about using the pen icon for editing .md files?

**Comment by HGustavs** [comment]
Perhaps creating some kind of general styling for sortabletables in the style file?

So if we add margins or colors to one table all sortable tables change in the same way?

This could be a separate issue.

**Comment by a16juleh** [comment]
Extensions are in a separate column, I have added screenshots of the solutions for better understanding.

**Comment by a16juleh** [comment]
The pen icon already exists, look at pull request #4488 for the solution. General styling for the table also already exists and all tables that uses sortabletable has the same css, the styling in these solutions only affect other changes regarding fileed.

**Comment by a16juleh** [comment]
Extensions are in a separate column, I have added screenshots of the solutions for better understanding.

The pen icon already exists, look at pull request #4488 for the solution. General styling for the table also already exists and all tables that uses sortabletable has the same css, the styling in these solutions only affect other changes regarding fileed.

**Comment by a16juleh** [comment]
Fixed "Fix editor column and icon for all files". Earlier the editor icon only existed for the MD files, but in the future we want to be able to edit all types of files - this is why we use the pen on all files.

<img width="230" alt="skarmavbild 2018-04-17 kl 14 14 08" src="https://user-images.githubusercontent.com/37794632/38869131-ed153296-4249-11e8-92b1-76d79f6a6407.png">
