### ISSUE TITLE
SectionEd: Undeclared variables in sectioned.js

### ISSUE THREAD

**Issue by a16thegu** [HGustavs/LenaSYS#4584]
There are some undeclared variables that need to be declared using the keyword _var_;

- at the top of the file, if the variable is used in multipule functions
- at the top of the function, if the variable is just used in that function.

Optional:
You can add the line "use strict"; at the top of the file and save.
Then run the page in the web browser to see in the console (right click on the page -> Inspect element -> console) where validation errors occurs.

Remember to delete the "use strict"; line when doing the last commit before the pull reqest.

**Comment by b16linra** [comment]
It might not be necessary to delete "use strict" if no more errors occurs after the file has been fixed. Leaving "use strict" will prevent new issues in the future.

**Comment by a16thegu** [comment]
Approved.
