### ISSUE TITLE
DuggaEd: Pressing Escape-button does not clear the error

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4597]
A similar issue related to this one in #4406 

![image](https://user-images.githubusercontent.com/37794262/38853879-ef88bfaa-421e-11e8-851c-777b84746509.png)

When using invalid characters the field turns red, and you cannot press submit. When this window is closed by pressing "cancel" or the "X" buttons the "red-issue" is cleared.
If this window is closed by pressing Escape on the keyboard this is not cleared, so if you open a different item to edit the Name-field is still red.
The Escape-button should function the same way as the cancel and X-buttons.

**Comment by HGustavs** [comment]
Yes, same as cancel.

All dialogs should work like this... not only this dialog?

Perhaps this is something that can be added generically in some way without breaking old functionality?

**Comment by HGustavs** [comment]
For instance escae key calling another function that may or may not be implemented in each view. If it is implemented the dialog is cancelled, if not, nothging happens... this way old and new code should work well together..
