### ISSUE TITLE
SectionEd: Cancel-button changes to a delete-button

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4599]
When you open and close the "Edit Item"-window there is a button that changes between "Cancel" and "Delete". 
Seeing as how there is a dedicated "Trashcan"-button for deleting items, the button in "Edit Item" should always say "Cancel".

![skarmavbild 2018-04-17 kl 9 06 36 fm](https://user-images.githubusercontent.com/37794262/38854333-6b459f7c-4220-11e8-834f-937d9d7c917c.png)

![skarmavbild 2018-04-17 kl 9 12 46 fm](https://user-images.githubusercontent.com/37794262/38854339-6ee5e812-4220-11e8-9924-d4e1fbb8f92e.png)

**Comment by HGustavs** [comment]
Pretty bad interface decision. There should always be a cancel button, delete could/should be a third button if necessary imho.
