### ISSUE TITLE
Attributes can connect to other attributes

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4601]
Right now the attributes can connect to other attributes. Composite attributes should be the only attributes with the ability to have other attributes connected to it. This must be fixed for the diagram to work correctly.

**Comment by HGustavs** [comment]
Attributes should be able to connect to other attributes.

But not entity to entity or relationship to relationship.

Examples:

![screenshot 2018-04-17 09 42 26](https://user-images.githubusercontent.com/6978801/38855440-c37f9744-4223-11e8-9a7e-ca8e3e3e3a59.png)
![screenshot 2018-04-17 09 42 16](https://user-images.githubusercontent.com/6978801/38855441-c3ac383a-4223-11e8-9b1b-b27e357cd4f0.png)

From course lecture notes.

**Comment by c16jonha** [comment]
Since the composite attributes are to be used as normal attributes, then this issue is no longer relevant and will now be closed.
