### ISSUE TITLE
Thought behind the second and third deadline.

### ISSUE THREAD

**Issue by 96kehman** [HGustavs/LenaSYS#4605]
@HGustavs 

When creating or editing duggar, there are field for a second and third deadline. These fields are not a part of the database, so how should they be implemented?
![dead1](https://user-images.githubusercontent.com/37793806/38857161-d5a9be90-4228-11e8-8dd3-33199c2f459e.png)

**Comment by HGustavs** [comment]
i think I responded in some other issue that we can write a json for this.

**Comment by HGustavs** [comment]
Alternative would be one text box that we write json directly into... three boxes one per deadline with the format from previous comment seems to be a good compromise imho.

**Comment by b16karhe** [comment]
A issue for group 1. @d16linja
