### ISSUE TITLE
Lines have to be connected to other objects.

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4608]
Right now the lines in the diagram can be drawn freely. It should not be possible to draw a line thats not connecting two objects with each other.

**Comment by HGustavs** [comment]
Well. 

* If we are talking about lines, this was supported previously for making boxes or scribbling on the diagram.
* Or are we talking about relation/attribute connectors?

![screenshot 2018-03-22 11 45 57](https://user-images.githubusercontent.com/6978801/38926023-9495005c-4301-11e8-9f08-32bb6755a93a.png)

I suppose the second? We are talking about the diagonal connectors and not the lines that make up the parts of the A symbol?
