### ISSUE TITLE
DuggaEd: Combining Dates and comments for Dugga Deadlines

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4622]
If you check #4605 you can see that a suggestion from @HGustavs is to combine some of the fields in order to create a less crowded interface. The working suggestion is to combine the date for the Deadlines (First deadline, Second deadline etc.), and the comments for these deadlines to 1 single filed per deadline. 

By doing this we will reduce the interface by 3 fields.

## These fields should be combined with it's respective filed above
![image](https://user-images.githubusercontent.com/37794262/38875352-757180b2-425a-11e8-97e7-ad6f9dc7e339.png)

**Comment by b16karhe** [comment]
Not our issue. Group 2 knows about this.
