### ISSUE TITLE
DuggaEd: New Dugga, all fields must be filled in order to create new dugga

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4623]
In order to create a new dugga you need to enter something into every field, otherwise you can't create the new dugga. This can be a bit annoying so this restriction could be lifted. 

## Maybe some of these fields could be left blank 
![hejdu](https://user-images.githubusercontent.com/37794262/38876110-218a94c8-425c-11e8-94a6-5f25842a6213.png)

**Comment by HGustavs** [comment]
Only mandatory is Name as far as I can see.
Empty deadlines and release dates correspond to immediate publication or no deadline message
If no start date is given we assume continous

I suppose that we need some kind of a default template... and default grade system and autograding off as the default.

**Comment by a14isshi** [comment]
Pull-request #4976 is accepted and therefore will this issue now be closed.
