### ISSUE TITLE
Make clipping dugga more dynamic

### ISSUE THREAD

**Issue by c16matan** [HGustavs/LenaSYS#4632]
Make the usage of cid dynamic so that the template could be used in more courses. Currently it is hardcoded to be 2, and  that could cause problems.

**Comment by HGustavs** [comment]
Make this issue description more clear, it seems like a bug to me but we need to specify more cleary which files are affected and detail more succinctly what the effects of this issue are to the application at large.

**Comment by c16matan** [comment]
Sorry, i just made a very short comment because it was a quick fix and was something that i would myself fix immediately. The returned data from the ajaxservice is currently used to create a image with a src of showdoc.php, and the parameter "cid" was hardcoded to be 2. So that resulted in that the template would only work for a course with the cid 2 (otherwise the image could not be found). And since that template has been implemented to the "Webbutvecklare - Datorgrafik" course as test data, which doesn't have cid2, i wanted to make it more dynamic so that it can be used on any course. This has been implemented into the branch G1-issue-4632 and is currently waiting to be reviewed.

**Comment by c16matan** [comment]
Fixed. Closing.
