### ISSUE TITLE
SectionEd: FAB-button bug

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4636]
At the moment the new FAB-button causes some issues. The list that pops up when the FAB-button is pressed is covering some things even when it is "down". This results in some of the edit and delete-buttons being non accessible. 
## This list should not be covering any buttons when it's collapsed 
<img width="212" alt="skarmavbild 2018-04-19 kl 8 18 25 fm" src="https://user-images.githubusercontent.com/37794262/38975163-204279e4-43ad-11e8-9d3b-d31e28e1a269.png">

**Comment by b16linra** [comment]
This issue was solved in pull request 4642. This issue will be solved.
