### ISSUE TITLE
SectionEd: FAB-button functionality

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4640]
In the current build the action-bubbles that show up when the FAB-button is pressed are simply visual, they do not have any actual functionality.
These are all called "Test", "Header", "Code" etc. and preferably the "Test"-bubble should create a new test, and so forth. 

## These bubbles should have their appropriate functionality 
![fab-bubbles](https://user-images.githubusercontent.com/37794262/38976030-4233359a-43b0-11e8-8995-6f8e5f0dbfb9.JPG)

**Comment by b16linra** [comment]
This issue was solved in pull request 4675. This issue will be closed.
