### ISSUE TITLE
SectionEd: Clarification of the Hamburger-menu

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4655]
As the screen size shrinks the buttons on the top of the Section Editor are compressed into a hamburger menu. However two of these buttons are icons in their uncompressed state, but compressed they change to text only.  An idea for change could be to have a combination of both icon and text in the collapsed state. 

## Pre-Collapsed state 
![duggaed buttons pre hamburg](https://user-images.githubusercontent.com/37794262/38979528-b7e3a2f2-43ba-11e8-9427-7c7e9d328eaa.JPG)

## Maybe the icons should be retained + the text for absolute clarification
![duggaed buttons post hamburg](https://user-images.githubusercontent.com/37794262/38979595-e5227478-43ba-11e8-89fe-ea2e9d751066.JPG)

**Comment by HGustavs** [comment]
Buttons work fine.

It would look strange if we have both buttons and icons at the same time.

**Comment by a14oliri** [comment]
Would this solution work @HGustavs ? Or should I just keep it as it is?

![screenshot from 2018-04-23 14-52-01](https://user-images.githubusercontent.com/37795562/39127689-0a5c7a7e-4706-11e8-95e8-33aec8883290.png)

**Comment by a14oliri** [comment]
@HGustavs

**Comment by a14oliri** [comment]
@HGustavs Bump please :cry:

**Comment by a14oliri** [comment]
After a discussion with the client we have come up with the solution that we should just keep New Version and Edit Version buttons where they are instead of shoving them into the Hamburger Menu.

**Comment by b16linra** [comment]
Solved in pull request 5213. This issue will be closed.
