### ISSUE TITLE
SectionEd: Unable to delete certain Headings

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4658]
At the moment you are unable to delete certain headings in the Section Editor (for example Geometri 2 Hp). 
When you attempt to delete this you get a error-message. 
This needs some looking into.

![errorupdatingentries](https://user-images.githubusercontent.com/37794262/38981075-c27176c8-43be-11e8-9f48-ca68ebfe11c9.JPG)

**Comment by a16filol** [comment]
This is not an isssue. The issue should be to improve the error message. This message is getting reported because the heading has foreginkeys stopping the delete. those entries should not be deleted.

**Comment by b16linra** [comment]
I and @d15marwi are currently working on a solution to improve the error message when it is not possible to delete items.

**Comment by d15marwi** [comment]
We know about this and are currently working on a message for this. The picture shows an error from the database (we will use this information for our solution)
![image](https://user-images.githubusercontent.com/37793970/39118471-c65ed04a-46e9-11e8-89a3-3ea60bd7bed5.png)

**Comment by d15marwi** [comment]
@HGustavs , what more would we need in the alert? This solution should work?
![image](https://user-images.githubusercontent.com/37793970/39124938-8d6ac97e-46fd-11e8-854b-8c475f9ea902.png)
