### ISSUE TITLE
Javascript code can be split into separate files

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#466]
Perhaps we can split the js files into separate files for user interface rendering and user interface code and make code even easier to find.

example.php (static code e.g. html code)
exampleservice.php (service code with no html)
example.js (all javascript code relating to example window)

I suggest something similar to this, splitting the code into two parts:
example.js (all interface rendering code)
example_ui.js (user interface code e.g. code for handling dialogs and mouse events and so on).

**Comment by c14caran** [comment]
These changes have already been done, should this issue be left open for future reference?

**Comment by a17pongo** [comment]
@HGustavs I suggest closing this issue

**Comment by HGustavs** [comment]
Yes close it. I consider this cruft, we have since started using sortableTable which alleviated these problems significantly.
