### ISSUE TITLE
SectionEd: FAB-button opacity issue

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4667]
When creating a new item and setting the visibility to hidden these recieve a higher index than the FAB-button. This results in the button ending up behind the new items, resulting in an un-clickable FAB-button. 

<img width="125" alt="skarmavbild 2018-04-19 kl 11 35 44 fm" src="https://user-images.githubusercontent.com/37794262/38987782-41ecf442-43d1-11e8-8ef7-9a06ce91971a.png">

**Comment by b16linra** [comment]
This issue was solved in pull request 4678. This issue will be closed.
