### ISSUE TITLE
DuggaEd: Less ambiguous confirmation-message 

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4673]
At the moment when you delete an item you get a confirmation message asking you if you really want to perform this action.
Since this window only pops up when attempting to delete something, it might be appropriate to change the text to something along the lines of:
"Are you sure you want to delete this item?"

## This message could be more specific 
![screenshot from 2018-04-19 13-42-51](https://user-images.githubusercontent.com/37794262/38990238-b7417918-43d9-11e8-8f7e-cdc832d86f16.png)

**Comment by b16linra** [comment]
This was solved in pull request 4727. This issue will be closed.
