### ISSUE TITLE
Webgl preview window

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#468]
It would be really nice to support iframes as views in the code viewer. This would allow easy previewing of webgl content.

**Comment by HGustavs** [comment]
I think that adding support for more content types and getting that to work well should be an important focus for the short term.

**Comment by HGustavs** [comment]
This is related to issue #1073 ...

**Comment by f12danjo** [comment]
Implemented [#1590](https://github.com/HGustavs/LenaSYS/pull/1590)
