### ISSUE TITLE
Magic header scrolling  in access

### ISSUE THREAD

**Issue by a16katba** [HGustavs/LenaSYS#4682]
Fix for the scrolling in access with magic header. When scrolling in access the table will fall out when  you resize screen.

**Comment by HGustavs** [comment]
Screenshot of the issue for documentation so we can more easily diagnose the reason of the problem.

**Comment by a16katba** [comment]
I have fixed the isssue for chrome and  firefox but trying to solve it for edge. 
![exempel](https://user-images.githubusercontent.com/37793711/39125618-ddc3abe6-46ff-11e8-9759-7238d32bb10e.jpg)

**Comment by a16katba** [comment]
@HGustavs

**Comment by a16katba** [comment]
Solved

**Comment by a16katba** [comment]
Solved
