### ISSUE TITLE
Add kind to fileed

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#4691]
When we upload a file, we can choose whether it should be stored as a global, local or course local file. However, there is no way to see which kind a file has in the table in fileed. We should add this to the table so that it is possible to sort the files based on their kind. The kind is stored as an integer, but this should somehow translate to readable words.

**Comment by c16linst** [comment]
@HGustavs as of now, there is only one upload button for files (and a separate button for links). But it is possible to select between "global", "local" and "course local" when the popup for files appear. Is this ok?

![skarmavbild 2018-04-23 kl 08 28 02](https://user-images.githubusercontent.com/37794714/39110158-5433fb58-46d0-11e8-8b54-68f4a4a330b8.png)
