### ISSUE TITLE
SectionEd: "New Item"-default state

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4692]
When you press the "+"-button in the upper right corner, a menu pops up where "Type" is defaulted to Header. However the attributes that are available are far more than whats actually available for the type Header. 
If the default type should be Header, maybe the attributes that doesn't apply to this type should not be visible. 

## Actual attributes of Header
![actuallheaderattributes](https://user-images.githubusercontent.com/37794262/39035601-eb5e2092-447a-11e8-8a24-91efe8469766.JPG)

## The current default state 
![new item](https://user-images.githubusercontent.com/37794262/39035612-f9041aa8-447a-11e8-81ae-6e4bdf1ea451.JPG)

**Comment by a16thegu** [comment]
@HGustavs, to leave all the options visible without filtering on which type that are selected is not a good choice. The user might think that a header-type need a grading-system or a highscore, but the type will not use these options at all.

It is better to hide options depending on which type that is selected. There will be no questions on why some options need to be filled out or the user need to remember which options needs to be filled out to create a header or test.

Do you have a list of the bugs?
I think it's better to solve them then showing all the options avaliable for creating a section.

**Comment by a14oliri** [comment]
@HGustavs

**Comment by a16thegu** [comment]
After discussion with the client; all the section options should be visiable in both new/edit item dialogs and opacity should be used on the labal of the option attribute to dim out options that are not relevat for that section type.

**Comment by d15marwi** [comment]
This issue is closed because this solution is not needed anymore
