### ISSUE TITLE
Support for trees in the code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#470]
One stretch goal feature that would be really appreciated is support for trees in the code e.g. allowing one to click a small plus icon near a function or block which would expand or contract that block to a single line.
e.g. 
`+ if(condition){ 

...   

random code  

...

}

...if we click the plus...

it would be turned into

`- if(condition){ ...`

and if we click the - we would return to the above.

**Comment by a13erisc** [comment]
I've decided to split this issue into several parts, because of its complexity. Right now I've set up a pull request that will cover the first part, which adds a border with clickable buttons next to the code, see #1266. The second part would definitely require group effort.

**Comment by a13jorla** [comment]
We are putting this issue on ice for now. And we are letting other course work on this issue.

**Comment by a17poner** [comment]
@HGustavs is this still relevant and something you want us to work on?

**Comment by a17poner** [comment]
Finally fixed 4 years later, all praise lord joaap!
