### ISSUE TITLE
SectionEd: Enter-key = Yes/Finalize

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4703]
When you get a pop-up window such as deletion or creating a new item you can press the escape-key to exit, and it would be nice if the Enter-key worked as a OK/Yes/Submit shortcut.

![actuallheaderattributes](https://user-images.githubusercontent.com/37794262/39039748-5d215edc-4486-11e8-80d6-e60bcd5573db.JPG)

![areyousurewindow](https://user-images.githubusercontent.com/37794262/39039661-35393156-4486-11e8-8a27-90618e1f3b6b.JPG)

**Comment by a14isshi** [comment]
Finished!
