### ISSUE TITLE
DuggaEd: Edit Variant, Disable- and Submit-buttons needs functionality 

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4706]
In the currrent version of the Edit Variant menu the disable- and submit-buttons does nothing and this needs to be rectified. 

![image](https://user-images.githubusercontent.com/37794262/39041039-72d22638-4488-11e8-9ab7-e239410f56d6.png)

**Comment by b16karhe** [comment]
_How disabled should look._
![Uploading disabled.png…]()

**Comment by b16karhe** [comment]
The sub-issues are solved
