### ISSUE TITLE
Code viewer markdown support

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#471]
Currently a system with parsing of html is used for the comment section.
As a stretch goal I suggest implementing (not downloading existing code) limited markdown support, so that when the code comments are shown instead of storing html (which is unsafe) we store markdown which is dynamically turned into html.

Basic support for headings, ordered lists and pre-formatted blocks would be enough.

**Comment by HGustavs** [comment]
No full html support, for security reasons only some basic markdown commands, for instance headings, ordered and unordered lists and emphasis, quotes and boxes for code examples.

https://help.github.com/articles/github-flavored-markdown/
https://help.github.com/articles/markdown-basics/

If we have write permission we can switch between a textarea tag and a normal html tag for the documentation section.

**Comment by b12simsa** [comment]
Markdown suggestions. 
It would be nice if Marcus Brohede or Henrik Gustavsson could comment on what is most important to implement and if some are missing.

#### Lines
"***", "___" , or "---"horizontal line 
Example:
***

#### Headings
\#  Heading 1 
Example: 
# 1
\#\# Heading 2
Example:
## 2
\#\#\# Heading 3
Example:
### 3
\#\#\#\#  Heading 4
Example:
#### 4
\#\#\#\#\#  Heading 5
Example:
##### 5
\#\#\#\#\#\#  Heading 6
Example:
###### 6

#### Text section
\~~~ 
text section
\~~~
~~~~
text section
~~~~

#### Lists
\* text or \- text bulletin list
Example:
* 1
* 2

#### Link
"[name]: /url "title" [name]" creates a link

#### Italics
\*text\*, \*text text\*, \_text\_, or \_text text\_
<br/>Example:
*text text*

#### Bold
\**text*\*, \*\*text text\*\*, \_\_text\_\_, or \_\_text text\_\_
<br/>Example:
**text text**

#### Bold and Italics
\*\*\*text\*\*\*, \*\*\*text text\*\*\*, \_\_\_text\_\_\_, or \_\_\_text text\_\_\_
<br/>Example:
***text text***

\!\[name]\(/url "title"\) inserts image

**Comment by HGustavs** [comment]
Basics first. (in order of priority)

Headings
Italics / Bold *text*, *text text*, _text_, or _text text_
Ordered / Unordered List i.e. * or 1
Code or Text (fixed width font in box) i.e. ``` or ~~~
Images

Also it would be nice if people with editing privileges could switch between markdown and a textarea-tag for editing the markdown.

**Comment by f12danjo** [comment]
Will split this issue up into several issues and link them here. Don't know EXACTLY what you mean with images so I left it out for now.

[Bold & Italics #871](http://github.com/HGustavs/LenaSYS/issues/871)
[Headings #872](http://github.com/HGustavs/LenaSYS/issues/872)
[Lists #873](http://github.com/HGustavs/LenaSYS/issues/873)
[Code/Text field #874](http://github.com/HGustavs/LenaSYS/issues/874)
[Text area for editing #875](http://github.com/HGustavs/LenaSYS/issues/875)

**Comment by HGustavs** [comment]
Can we retire this issue?
