### ISSUE TITLE
DuggaED: Update confirmation-box

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4729]
At the moment the header on the confirmation box in DuggaEd says "Confirm your update". This should be changed to "Confirm your deletion" which is the same as in SectionED.

## Current state
<img width="497" alt="skarmavbild 2018-04-23 kl 9 35 18 fm" src="https://user-images.githubusercontent.com/37795608/39112850-193ef9a8-46da-11e8-89b6-becd062a8a8f.png">

**Comment by HGustavs** [comment]
Is this very complicated code or could we even resort to using the built in dialog?

~~~
if (confirm('Are you sure you want to save this thing into the database?')) {
    // Save it!
} else {
    // Do nothing!
}
~~~

The built in dialog gives us an operating-system specific dialog, which may be better for this kind of warning?

Also should be much less code.
