### ISSUE TITLE
DuggaED: Update variant table after changes have been made

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4732]
This relates to #4706.

#4716 (Sub-issue)  At the moment when changing a variant entry in a dugga (such as editing or deleting), the table doesn't update until the variant window is closed and reopened. That should be handled so that the table updates at the same time as the change has happened.

**Comment by HGustavs** [comment]
The preferred way to do this kind of stuff is to refresh the table completely e.g. retrieve the information again from the database.

If this operation is very slow e.g. the marking view we change the on-screen data and then refresh, in all other cases we can safely just referesh e.g. the same operation that we do when the page is first loaded.

**Comment by a16thegu** [comment]
Approved, the solution works.
