### ISSUE TITLE
File ID sort doesn't work correctly

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4738]
When you click on the header to sort the table by file ID it doesn't sort them correctly. Fix it so that they appear in number order.

![sortfilenmbr](https://user-images.githubusercontent.com/37794047/39115365-bf22ab60-46e1-11e8-9384-d6f5684ce1c0.PNG)

**Comment by HGustavs** [comment]
Do we need to show the file id at all?

**Comment by c16linst** [comment]
We can remove the file ID, but we have already made a solution to sort properly on numbers. Should we also remove this?

**Comment by HGustavs** [comment]
The field in itself is not very useful but the numbers-sorting could be kept in some way to help with other places in the code that needs an example for how to do sorting on numbers? Perhaps adding this code to the examples folder in sortabletable for future reference?
