### ISSUE TITLE
Make the preview window resizable.

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4743]
One should be able to shrink and enlarge the preview window in file editor.

**Comment by HGustavs** [comment]
Well, I prefer a fluid design. As large as possible and adapting to screen borders. No need to make it movable, that tends to be annoying in the long run.

**Comment by a16juleh** [comment]
Instead of manually shrinking and enlarging the preview window, this should be done automatically when the window is resized. A new issue for mobile mode will be made.
