### ISSUE TITLE
Markdown preview buttons

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#4744]
We have a few editing buttons in the markdown preview.

I would like an interface that allows me to link to files e.g. an image in the file repository for the course with a dropdown and a button. This way an image can be added very rapidly.

**Comment by HGustavs** [comment]
A mock-up would be nice.

**Comment by c16linst** [comment]
We are not quite sure what you are looking for. Could you elaborate?

**Comment by HGustavs** [comment]
Like a dropdown of some sort that would contain images from the file list so I dont have to jump back and forth to the file editor to remember the file names.
