### ISSUE TITLE
SectionEd: Reduce and refine the code used for the FAB-button

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4769]
The code managing the FAB-bubbles could stand to be simplified since a lot of it is re-used. In order to increase maintainability, the code that is shared could be located in a single location to enable universal changes to all buttons, rather than having multiple instances of identical code. 

## The marked code is identical in all FAB-bubbles
![fab-code](https://user-images.githubusercontent.com/37794262/39131913-e39fe1f4-4710-11e8-9cd3-4ac8879109d6.JPG)

**Comment by b16linra** [comment]
This was solved in pull request 4808. This issue will be closed.
