### ISSUE TITLE
SectionEd: Pressing enter shows a dropdown list when creating a new item (Chrome)

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4771]
As of right now when pressing the enter key in google chrome, it activates the selected input box. For example when pressing enter while the marker is on a dropdown list, it activates the dropdown list instead of saving the item. This issue isn't relevant on Firefox.

<img width="562" alt="skarmavbild 2018-04-23 kl 4 11 19 em" src="https://user-images.githubusercontent.com/37795608/39131949-fa418c82-4710-11e8-9c58-f1e58e92f75c.png">

**Comment by d15marwi** [comment]
This issue was closed because this is a problem in chrome.
