### ISSUE TITLE
Size sort in fileed

### ISSUE THREAD

**Issue by c16jonha** [HGustavs/LenaSYS#4775]
The sorting by size is incorrect, it does not show the files sizes from smallest to biggest or vice versa.

![size](https://user-images.githubusercontent.com/37794047/39170261-2c8fbd00-479b-11e8-9fa3-e0ce5fa58d3d.PNG)

**Comment by HGustavs** [comment]
I thought I commented on this already...

but, the sorting needs to sort on the value and the rendering needs to render it as something else.

**Comment by HGustavs** [comment]
The data is in bytes if we sort 38 vs 1200 this is fine

In rendercell we render 38 as "38 Bytes" and 1200 as "1.2 KB" ... using a renderkilobytes help function e.g. if kb>1000 do this if kb<1000 else if kb>1000000 do this etc

then the sorting should be fine.
