### ISSUE TITLE
SectionEd: Clicking outside the hamburger menu should close it

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4784]
For convenience it would be preferable to have the ability to close the hamburger menu by clicking outside of it, as is the standard for many other menus and windows in the Section Editor. 

![hamburgermenu](https://user-images.githubusercontent.com/37794262/39175107-bf1fc4f4-47a9-11e8-81e9-e1d0b14d549a.JPG)

**Comment by b16linra** [comment]
This was solved in pull request 4793. This issue will be closed.
