### ISSUE TITLE
No installer exists.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#479]
When the application is first downloaded there is no installation script.
* There is a sql file but no way to run it.
* There is a configuration file but litte instructions as for where to put it

A nice readme/installation instruction is a great feature.

**Comment by HGustavs** [comment]
Scratch geat and insert fabulous

**Comment by HGustavs** [comment]
scratch fabulous and insert stupendous

**Comment by HGustavs** [comment]
I think there is a python installer.

Does it work?

Is there documentation for it?

**Comment by a14antpa** [comment]
It's not working properly. Needs to be updated or replaced.

**Comment by b14vikgu** [comment]
Since the installation script already exists I am closing this. Followed up here: https://github.com/HGustavs/LenaSYS/issues/1967
