### ISSUE TITLE
SortableTable in Accessed - part three 2.0

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#4794]
Bugs with sorting mentioned in #4724:

* The first click on a column will sometimes not sort correctly, after the second click it will work, however. - SOLVED
* Å, Ä and Ö are treated like A and O respectively - unwanted behaviour? - SOLVED
* The column is sorted based on the contents of the cells. This results in columns with drop down and editable not working. - SOLVED

**Comment by HGustavs** [comment]
Locale spelling is handled in the callback, not a bug in sortabletable.

str1.localeCompare(str2);

So, if the appropriate compare function is used sorting should work ok.

**Comment by a16jonis** [comment]
Yes, the bugs mentioned above is in regard to the way the sorting was implemented rather than sortableTable itself.
