### ISSUE TITLE
SectionEd: The type "Group Activity" includes fields that are not hidden

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4795]
The type Group Activity includes a attribute called Group Type. This attribute is not hidden if you go from the type Group Activity to another typ, such as Link. 

## Note the lowest attribute...
![new groupactivity](https://user-images.githubusercontent.com/37794262/39178475-17ea2cac-47b2-11e8-8c88-7f0ac4ba535d.JPG)
## ...still remains even after the Type is changed
![moment with grouptype](https://user-images.githubusercontent.com/37794262/39178478-1a025000-47b2-11e8-9cf9-6962e6d55b03.JPG)

**Comment by b16linra** [comment]
This was solved by pull request 4797. This issue will be closed.
