### ISSUE TITLE
SectionEd: Adding startdate to Moment

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4809]
This is an off-shot from #1928 

There were several requests in the original issue, therefore the decision was made to close the original on and break it into several smaller ones. 
This was part of the original request:
* estimated start and stop time is a help for the students - I could see that this could be an optional text field in the database.

Deadlines are already featured in the Section Editor, but there are no visible start-dates on moments.

![image](https://user-images.githubusercontent.com/37794262/39185748-7fdd8c9e-47c8-11e8-86cd-9d070327179a.png)

**Comment by a14oliri** [comment]
Since Moments does not have a start date, I could fetch the earliest start date from the Tests inside of the moment. And use the latest deadline for the stop date on the Moment.

Is that what you are looking for on this issue?
