### ISSUE TITLE
database name

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#481]
Some times database names that mix upper case and lower case letters. This creates problems on some operating systems.
It is a good idea to change this to use only lower case letters.

**Comment by HGustavs** [comment]
e.g. change name of the database from TestDatabase to testdatabase

**Comment by a12jiyba** [comment]
The database name do not have a mix of upper case and lowercase letters.

**Comment by HGustavs** [comment]
In the db_init.sql the database is called Imperiouz which I do believe contains one upper case letter. Any name can be used but the one in that sql file does have a mix of upper and lower case....

**Comment by HGustavs** [comment]
Scratch that. It was my local branch.
