### ISSUE TITLE
SectionEd: Adding credit (HP) to Moment

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#4810]
This is an off-shot from #1928 

There were several requests in the original issue, therefore the decision was made to close the original on and break it into several smaller ones. 
This was part of the original request: 

* The credits and grade scale should be possible to have stored in the database

Gradescale was already solved as part of the original issue, so the remaining request would be the credits. At this point in time there seems to be a standard among the teachers to write the credit as a part of the "Name" field. 

Is the request to add the credit to the database still relevant in 2018? 

![image](https://user-images.githubusercontent.com/37794262/39185748-7fdd8c9e-47c8-11e8-86cd-9d070327179a.png)

**Comment by HGustavs** [comment]
I would say this is not relevant it is better that each teacher decides how to do this in each course.

**Comment by d15marwi** [comment]
We closed this issue because of the lack of demand.
