### ISSUE TITLE
Contribution - bar diagram of user activity

### ISSUE THREAD

**Issue by c16matan** [HGustavs/LenaSYS#4823]
Main issue #4822

Create a bar diagram similar to the one shown on the image below and insert it between the first and second table. The bars should look like the first bar in the diagram, hence, using three colors, one for LOC, commits and events. There should be one bar for each day in the diagram.

![untitled-1](https://user-images.githubusercontent.com/37793866/39245303-a4de2adc-4893-11e8-8e57-7ab830e45dcc.png)

**Comment by HGustavs** [comment]
10 weeks with 7 days each e.g. 70 days in total.
There should be some kind of divider for each week e.g. week 1 ... week 10 ... I dont think we need to see the individual dates.

**Comment by a16chrsa** [comment]
Getting this console error-message:

Uncaught TypeError: Cannot read property 'commits' of undefined
    at renderBarDiagram (contribution.js:97)
    at Object.returnedSection [as success] (contribution.js:241)
    at j (jquery-1.11.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.0.min.js:2)
    at x (jquery-1.11.0.min.js:4)
    at XMLHttpRequest.b (jquery-1.11.0.min.js:4)
