### ISSUE TITLE
Contribution - Bug fixes

### ISSUE THREAD

**Issue by c16matan** [HGustavs/LenaSYS#4825]
Look through the table that shows the weekly activity for the user and check that all of the columns display the correct information.

**Comment by HGustavs** [comment]
The event count is definitely wrong, it shows the number of distinct events rather than the total number of events, this may be an SQL error rarther than a javascript issue.

**Comment by c16matan** [comment]
No more issues has been found since the last one. Closing. Please open a new issue if another bug is found on the contribution page.
