### ISSUE TITLE
Creating a group column in Access (Part 1 of  #4169)

### ISSUE THREAD

**Issue by d15marwi** [HGustavs/LenaSYS#4827]
#4169 
We need a column in Access that gives the ability for a teacher to select which group a student belongs to. 

Before:
![image](https://user-images.githubusercontent.com/37793970/39289504-b9fc6eee-492c-11e8-87bc-958eda93703b.png)

Goal:
![image](https://user-images.githubusercontent.com/37793970/39289626-2f288f54-492d-11e8-9397-3b3b894e208c.png)

**Comment by b16linra** [comment]
The column was created in pull request 4857. This issue will be closed.
