### ISSUE TITLE
SectionEd: The "Type" dropdown is red when there are no links available

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4832]
When creating a new item and selecting Test theres a function that checks if theres any links available to choose from. If there aren't any links available to choose from the input changes to red and a black tooltip appears. When selecting the dropdown list there are red lines on top and bottom of the list. This needs to be fixed so just the Test option in the dropdown is changed to red.

## The issue
<img width="504" alt="skarmavbild 2018-04-26 kl 8 44 38 fm" src="https://user-images.githubusercontent.com/37795608/39290102-c4d809f2-492e-11e8-9f2c-41ac48de0fda.png">
<img width="496" alt="skarmavbild 2018-04-26 kl 8 44 43 fm" src="https://user-images.githubusercontent.com/37795608/39290104-c75d3c1a-492e-11e8-9305-5b7bc8e392ee.png">

**Comment by a14oliri** [comment]
I can only recreate this on MacOS + Firefox. I do not think this is a "Issue" that we can solve, but only how MacOS+Firefox looks.

**Comment by a16thegu** [comment]
Closing issue due to previous comment.
