### ISSUE TITLE
SectionEd: When closing the pop-up window while test selected, state doesn't reset

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4838]
At the moment when closing the "new item" pop-up window while there are no links and test is selected, the state isn't reset when creating a new item afterwards.

## While selecting test
<img width="495" alt="skarmavbild 2018-04-26 kl 9 18 15 fm" src="https://user-images.githubusercontent.com/37795608/39291299-dae196e2-4932-11e8-9c2e-1158b389519d.png">

## When reopening 
<img width="498" alt="skarmavbild 2018-04-26 kl 9 18 24 fm" src="https://user-images.githubusercontent.com/37795608/39291288-d283fd96-4932-11e8-99d6-41afbc6729b6.png">

**Comment by a14oliri** [comment]
I cannot recreate this error, maybe it has been fixed by someone else? Could you retry this and if the fault still exists, provide me with the steps you take? :+1:
