### ISSUE TITLE
SectionEd: Arrow icon need to be separated from the Ellipsis effect

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4839]
When on mobile mode a lot of Moments have the ellipsis effect due to the length of the text. The problem here is that the ellipsis applied both on the title and on the show/hide arrow. This needs to be fixed somehow so that just the title is being affected by the ellipsis effect.

<img width="363" alt="skarmavbild 2018-04-26 kl 9 21 21 fm" src="https://user-images.githubusercontent.com/37795608/39291511-8aa23500-4933-11e8-9d15-fb31e5b33933.png">

**Comment by a16thegu** [comment]
Approved, look very good now!
