### ISSUE TITLE
Redirect to the frontpage from the custom 404 page.

### ISSUE THREAD

**Issue by a16chrsa** [HGustavs/LenaSYS#4843]
In the custom 404 page located at errorpages/404.php, add a link to the frontpage(DuggaSys/courseed.php).

**Comment by a17fellu** [comment]
https://github.com/HGustavs/LenaSYS/pull/5724

Has been fixed in this pull request

**Comment by a17andby** [comment]
It seems that this problem only occurs when we run the application on a local machine. And since we should not refactor old code I will close this issue since it don't solve anything on the live server.
