### ISSUE TITLE
SectionEd: Creating a new item through the FAB list the entry stays underneath the FAB button

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4846]
At the moment when creating a new item through the FAB list the item stays underneath the FAB button. This need to be fixed so that when creating a new item through the FAB list the page is scrolled to the bottom so that the focus is on the newly created entry.

## How it looks now
<img width="1439" alt="skarmavbild 2018-04-26 kl 9 49 18 fm" src="https://user-images.githubusercontent.com/37795608/39292647-19258996-4937-11e8-81cc-5bd6dd2c7cfe.png">

## How it should look
<img width="1440" alt="skarmavbild 2018-04-26 kl 9 49 50 fm" src="https://user-images.githubusercontent.com/37795608/39292673-29fe5702-4937-11e8-902d-e32a40920628.png">

**Comment by b16linra** [comment]
This was solved in pull request 4888. This issue will be closed.
