### ISSUE TITLE
SectionEd: Message entry styling

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4848]
At the moment the Message entry doesn't have much focus and it should be changed up a bit in order to put more focus into it. 

<img width="1429" alt="skarmavbild 2018-04-26 kl 9 55 26 fm" src="https://user-images.githubusercontent.com/37795608/39293020-20c7f7dc-4938-11e8-9349-799099585610.png">

**Comment by b16linra** [comment]
This seems to be related to issue #4898.

**Comment by a14isshi** [comment]
@a16konka This issue can be deleted as #4898 is related to this one.
