### ISSUE TITLE
The study program overview

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#486]
The study program overview should list all students in the a "kull"
* options to hide students who have aborted
* sort options on all fields, e.g., name, pnr, etc.
* all courses in the study program should be present and show correct status (not registered, passed, partially passed, not started, etc.
*statistics should be present. %passed, %partial passed, %failed for each course
* statistics should be updated if aborted is hidden

**Comment by HGustavs** [comment]
Retired
