### ISSUE TITLE
SectionEd: Default title values on created items through the FAB list

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4861]
At the moment no matter what item you create through the FAB list the title is "New item", this needs to change so that each type of item has its own default title, for example a new test should have a default title "New Test".

<img width="1428" alt="skarmavbild 2018-04-26 kl 11 00 54 fm" src="https://user-images.githubusercontent.com/37795608/39296418-26c0ab3a-4941-11e8-8345-34d3088b0503.png">

**Comment by a16filol** [comment]
This issue was solved in pullrequest 4980.
