### ISSUE TITLE
DuggaEd: Mark the selected variant when editing

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4862]
Currently when editing a variant in the variant list there is no clear indication on which variant is currently being edited. This should be fixed so that the user can clearly see which variant is currently being edited.

## Mock-up idea (Color variation could be different)
<img width="1181" alt="skarmavbild 2018-04-26 kl 11 02 44 fm" src="https://user-images.githubusercontent.com/37795608/39296687-dc192cb4-4941-11e8-9276-1eed560258b8.png">

**Comment by b16karhe** [comment]
Done.
