### ISSUE TITLE
Show which courses that are prereq

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#487]
In the study program student view hovering over a course with prereq should highlight in some way which courses that are prereq.

**Comment by a13erilj** [comment]
This issue is assigned also to @a13freas, he will work together with @a13antda on the issue

**Comment by a13antda** [comment]
This issue isnt completly done dont close. The function is there just needs to fiqure out what to do except for the hover effect!

**Comment by a13ottne** [comment]
would like a separate smaller icon for each course on which to put the hover effect. So that you are still able to move the mouse somewhat freely without courses constantly fading.

**Comment by a13ottne** [comment]
if "easily done" the icon should be as follows:
if student has points in all pre-reqs, but not completed all = warning triangle
if student has zero points in any of the pre-reqs = stop sign
if student has completed all pre-reqs = green checkmark

**Comment by a13erilj** [comment]
This issue is handled by @a13freas and @a13antda

**Comment by c13marme** [comment]
This issue is solved
