### ISSUE TITLE
SQL is indented horribly and does not conform to any kind of consistent standard

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#488]
SQL code does not look good.
First part of code looks fine, but further down code looks worse, and is harder to read.
- Proper indentation, with datatypes stacked vertically using tabs.
- Inserts should follow immediately after corresponding table
- Consistent use of capital letters, any SQL code should be capialized e.g. INSERT INTO Person ... etc

**Comment by HGustavs** [comment]
Still not much better.
Overly verbose foreign key and primary key statements that seem auto-generated.
SQL create table and data split into two files.

**Comment by a15jorpa** [comment]
@HGustavs LenaSYS/Shared/SQL/init_db.sql was giving error messages when run, some options for fixing:
grade in partresult part of PK, should it not be DEFAULT NULL or be removed from PK? (line 400)

class in programcourse is DEFAULT NULL but table does not seem to make sense then, should it be  NOT NULL? (line 414).

**Comment by a15jorpa** [comment]
Indentation, overly verbose foreign key statements and capital letters for SQL should be ok now.

**Comment by a15jorpa** [comment]
Pull request #2662 should resolve the last part this issue. Splitting SQL into multiple files was decided to be a good thing when done reasonably because it allows more options in setting up a new instance.
