### ISSUE TITLE
SectionEd: All options when creating an item should be reverted

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4880]
After a discussion with the client, all input options need to be visible when creating a new item.

## Current view
<img width="492" alt="skarmavbild 2018-04-26 kl 3 12 27 em" src="https://user-images.githubusercontent.com/37795608/39307870-4cd6d8f8-4964-11e8-89e8-1fc1fd745d10.png">

**Comment by a16thegu** [comment]
Approved, looks good on both new and edit item!
