### ISSUE TITLE
SectionEd: Long press on the FAB button

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4884]
After a brief discussion with the client, it was decided that a quick press on the FAB button should create a default entry, while when long pressing the FAB button the fab list should appear.

**Comment by b16linra** [comment]
As mentioned during the seminar, we might still have to give this some thought to find a good solution. @HGustavs mentioned double clicking as a possible solution to create default items in the SectionEd.

**Comment by a14oliri** [comment]
I'll try adding some different styles of opening the FAB-menu.

**Comment by a14oliri** [comment]
After a discussion with the client we have agreed on opening the FAB-List on hover and creating new "quick-item" when just clicking on the button.

**Comment by b16linra** [comment]
This was solved in pull request 5175. However, it might be preferable to change the solution in the future and remove the timer. It should simply check whether or not the mouse is hovering over the content and close if it is not. This issue will be closed.
