### ISSUE TITLE
SortableTable in Resulted - part two

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#4899]
Part of #4896

Use sortable table in order to filter the table in Resulted.

**Comment by b16nilpe** [comment]
Filtering is almost on par with the the filters that was available before the implementation of sortable table.
Still missing checkboxes to select/deselect all columns and columns that belong to a specific moment.

**Comment by a16jonis** [comment]
Issue based on the comment above has been created. Closing this issue since it's completed.
