### ISSUE TITLE
Error message when no template has been chosen

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#491]
Currently, no appropriate error message is given when no template has been selected ant the user is
not an administrator (i.e. does not have write access).

If logged in we do get a message telling us to choose a template.

A good error message would be something like "The administrator of this code example has not yet chosen a template"

**Comment by HGustavs** [comment]
Something like when we choose a course that does not exist.

**Comment by a13jorla** [comment]
Is this implemented @c12jenek ?

**Comment by c12jenek** [comment]
There are no examples where the template has not been chosen so am unsure, try adding an example for it and check

**Comment by f12danjo** [comment]
Fixed by [#1675](https://github.com/HGustavs/LenaSYS/pull/1675)
