### ISSUE TITLE
SectionEd: Saving an item by pressing "Enter" even if its not allowed

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4914]
At the moment when creating/editing an item and using illigal characters in the title, you can still press enter and create the item even through you can't press the save bottom inside the pop-up box. This needs to be fixed.

<img width="508" alt="skarmavbild 2018-04-27 kl 2 09 25 em" src="https://user-images.githubusercontent.com/37795608/39362354-703b8a9c-4a26-11e8-9730-0f079cece5ac.png">

**Comment by b16linra** [comment]
It might be necessary to wait with this issue until issue #4704 is solved.
