### ISSUE TITLE
SectionEd: Pie chart placement (Swimlane)

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#4926]
After a discussion with the client the current pie chart needs to change position and placed inside the swimlane table at the top left corner. The pie legend is not needed.

## Current
<img width="841" alt="skarmavbild 2018-05-02 kl 8 43 37 fm" src="https://user-images.githubusercontent.com/37795608/39509099-448e61ea-4de5-11e8-83dc-2e2e75e7f99f.png">

##Mock-up
<img width="844" alt="skarmavbild 2018-05-02 kl 8 42 28 fm" src="https://user-images.githubusercontent.com/37795608/39509103-4d1fad3c-4de5-11e8-8045-975ff2788aca.png">

**Comment by b16linra** [comment]
We will also remove the empty whitespace that is visible at the top in the mockup, and perhaps make the pie chart hoverable so that a bigger version becomes visible with more details.

**Comment by d15marwi** [comment]
After discussion in the last meeting suggestions were made that swimlane should be re-designed so that more users/students use this feature.  We gonna create a mockup that shows how swimlane looks with the lanes going from right to left instead of from top to buttom.  The main goal is to make swimlanes more useable for students. So we will decide the position of the pie chart after we decide which design to use in swimlanes.

**Comment by a16thegu** [comment]
Mock-up for turning the swimlanes horizontally. Rows and it's lanes symbols etc. can be made smaller, but this is just to show how it can look horizontally.

<img width="883" alt="skarmavbild 2018-05-07 kl 11 19 05" src="https://user-images.githubusercontent.com/37794246/39694756-ac0d0086-51e8-11e8-9a9c-b9b9f928a94e.png">

More options are comming.

**Comment by a16thegu** [comment]
Here are some more options for the swimlane design:

Alt. 2:
<img width="513" alt="skarmavbild 2018-05-08 kl 10 01 26" src="https://user-images.githubusercontent.com/37794246/39745238-ff7b48b8-52a6-11e8-9d43-bd9a2578c693.png">

Alt. 3:
<img width="994" alt="skarmavbild 2018-05-08 kl 10 01 48" src="https://user-images.githubusercontent.com/37794246/39745259-09219c3c-52a7-11e8-9fdf-b59de497f2dc.png">

**Comment by b16linra** [comment]
The pie chart is currently being moved to a new statistics section in SectionEd, see issue #5243.

**Comment by b16linra** [comment]
This issue will be closed because swimlanes and the pie chart are being reworked and moved to a new location.
