### ISSUE TITLE
SectionEd: Items with invalid names can be created

### ISSUE THREAD

**Issue by a14oliri** [HGustavs/LenaSYS#4929]
Items with invalid names can be created. 

## Steps to recreate this:
1. Click create new
2. Enter an invalid name(e.g. @¡@£$)
3. Select another Type
4. Submit button becomes clickable and a new item with an invalid name can be created

![screenshot from 2018-05-02 09-29-32](https://user-images.githubusercontent.com/37795562/39510821-6430705a-4deb-11e8-8296-d1534beab162.png)

**Comment by a16linas** [comment]
Both types now need to be valid in order to submit.
