### ISSUE TITLE
DuggaED: Preview functionallity for variants.

### ISSUE THREAD

**Issue by b16karhe** [HGustavs/LenaSYS#4933]
_**A preveiw of the variant should be displayed when clicking the "playbutton".**_
![variantpreview](https://user-images.githubusercontent.com/37793806/39511695-a80db7f8-4dee-11e8-8ec5-0692a0610ba0.png)

**Comment by a16filol** [comment]
@HGustavs How is this supposed to work. We dont have a working version of the preview to look back at. Should the preview display that specific part of a dugga?
