### ISSUE TITLE
DuggaED: Error when loading the page.

### ISSUE THREAD

**Issue by b16karhe** [HGustavs/LenaSYS#4935]
There is an error when loading the page that comes from the function updateVariantTitle() becuase it tries to load a name from a dugga that has not yet been selected. The error does not cause any further problems but it should still be fixed. 

![wow](https://user-images.githubusercontent.com/37793806/39512192-4c57561a-4df0-11e8-86b5-092eef14fb93.png)

**Comment by a14isshi** [comment]
No errors occurred when different events took place in duggaed in order to test the solution to this issue. I therefore close this issue.
