### ISSUE TITLE
In code viewer hovering is used...

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#494]
Hover is used in code viewer to for instance showing parentheses. No corresponding mobile gesture exists.

**Comment by a13alfbe** [comment]
This could be fixed by adding **:focus** to the css.

**Comment by a13alfbe** [comment]
I now see that the hover effect is done with javascript (onmouseover & onmouseout). My bad

**Comment by a17poner** [comment]
Assuming this is the same as #191
https://github.com/HGustavs/LenaSYS/issues/191#issuecomment-493387980

> Not important, close.
> 
> Mobile view is not important for this, since it is very dependent on screen space.
