### ISSUE TITLE
IP address logging in ServiceLogEntries

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#4942]
Whenever the user performs an action on the website that action is logged in the table ServerLogEntries in the database.

On a locally hosted workspace the IP address of the device is correct. But in the webserver database the IP that is logged is always 10.0.0.2 no matter from which device you access the website. It could be that the webserver is behind a proxy or something which causes the unwanted behaviour. It could also be the way the remote IP address is fetched in the code. 

Examine the cause of the problem and document it in a comment here. Fix the issue if it is a code-based problem.

**Comment by a16seplu** [comment]
Feels like a bug outside of our code. Tried making changes in the code and it still didn't work.

**Comment by f16linli** [comment]
After doing some research into why the webserver logs the wrong ip number of the client, the entire php attribute $_SERVER was checked and the client ip number is not stored anywhere in this attribute when it is run on the webserver. But when the attribute is inspected on a local server the ip of the client is present in $_SERVER["REMOTE_ADDR"]. This leads me to believe that this issue has to do with the webserver settings and not to do with the code in LenaSYS.
