### ISSUE TITLE
Logging not applied everwhere

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#495]
Logging had been implented for submmission of dugga and possibly also logon and logoff. This needs to be added in more places. If someone changes a marl but also for code examples and followups.

This is portant throughout for accountability purposes.

Reusing as much code as possiblw from ds.

**Comment by b14vikgu** [comment]
From #1874 

> Currently only logins/attempts are logged in the database, it would be nice to keep a log of every page read or every user click in some manner, to be able to analyze user behavior, or usability problems.

**Comment by HGustavs** [comment]
Is this not solved now?

**Comment by b14vikgu** [comment]
There are still things to log in the system. For example I don't think changes to examples and followups are logged.

**Comment by b17carbr** [comment]
@HGustavs I can only find one place where  page reads by guests and users are logged at this movement which is in codeviewer. Should this be expanded?

**Comment by b17carbr** [comment]
Unsure of the status of this issue, should I investigate further @HGustavs ? or do you have some insight to what degree this issue is solved now?

**Comment by a18filkr** [comment]
We are now logging much more and this is being developed in the new analytic page.
