### ISSUE TITLE
AccessED Change the coloumn "Group(s)" from a textbox to a multichoice scroll.

### ISSUE THREAD

**Issue by a14isshi** [HGustavs/LenaSYS#4954]
![image](https://user-images.githubusercontent.com/37794167/39521449-d5f08f36-4e0e-11e8-8534-ccdfad305e21.png)

Instead of saying "PLACEHOLDER" we want a multichoice scroll to enable a person to be appointed to multiple groups.

**Comment by HGustavs** [comment]
As standardized as possible.

size=1 does not work so it has to be a select list in some way.

**Comment by d15marwi** [comment]
This is already solved in #4169
