### ISSUE TITLE
Resulted view deadline indicator - part one

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#4958]
Part of #4164 

when sorting on a particular dugga all ungraded duggas should be at the top in order of submitted date and time. The duggas submitted before deadline should be separated from the duggas submitted after the deadline and grace period by a line or by using a clearly different background color. If there exists a better way to visualize this I'm open to suggestions.

**Comment by f16linli** [comment]
This issue have already been implemented in issue #4332.
There have been some mistake that ended up in two identical issues.
