### ISSUE TITLE
Log analysis tools

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#496]
When/if we have comprehensive logging implented some kind of logging view would be great. Answering questions like
- who from the course have visited this page
- how many peaple have downloaded this file
- how many failed login attempts have each user made
- which operating systems are most common

**Comment by a13chrju** [comment]
why not just use google analytics :)?

**Comment by c13andka** [comment]
Should we do this ourself ?

**Comment by b14vikgu** [comment]
Some of these have now been implemented on the analytic page, for example operating systems..

**Comment by b17carbr** [comment]
@HGustavs do you know the status on this issue? I can't find any analytic page like the comments above mentions.

**Comment by a97marbr** [comment]
I think that this feature has been forgotten ... BUT it is a great feature ... I would love to be able to get a feel for things like

* How many of the students registered actually visit the course page
* Is the traffic to the course only during scheduled supervisions
* Can we detect potential cut offs where students drop from courses 
* etc.

Give us a sketch on a prospect UI and we'll take it from there ... this could be really good!

**Comment by a18filkr** [comment]
These are being worked on in sub-issues instead and som are already solved. Closing this since new issues are created.
