### ISSUE TITLE
SectionEd: Creating option to press Enter when reveiving a error/delete message to close. 

### ISSUE THREAD

**Issue by d15marwi** [HGustavs/LenaSYS#4963]
![image](https://user-images.githubusercontent.com/37793970/39524363-048aeff8-4e19-11e8-995c-2b836a254a02.png)

When getting this message (trying to create a test in section Ed. ) it should be possible to close the window with pressing the enter button.  The same goes for the delete window.

![image](https://user-images.githubusercontent.com/37793970/39524522-88274bfe-4e19-11e8-93a0-e57f2a2ffebb.png)

**Comment by a16thegu** [comment]
Approved.
