### ISSUE TITLE
MOTD Bug fix

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#4968]
When there is a MOTD(Message of the Day) the footer will cover the course at the bottom of the page. It is impossible to scroll down to see the course. Add a little bit of padding to the last course so that MOTD can fit under it. This should only happen when there is a MOTD so unnecessary padding is avoided.

![motdbug](https://user-images.githubusercontent.com/37793947/39524860-9ccbfe46-4e1a-11e8-89bb-91c03fb08031.PNG)

**Comment by c16matan** [comment]
Fixed. Closing.
