### ISSUE TITLE
SectionEd: Change default value when creating a new item with add button

### ISSUE THREAD

**Issue by d15marwi** [HGustavs/LenaSYS#4981]
When creating a new item with the add button the new item should be called "new item"(for example "new header" or "new code" etc). 

![image](https://user-images.githubusercontent.com/37793970/39562916-55df4d46-4eae-11e8-893a-b7c7eaff3155.png)

**Comment by HGustavs** [comment]
I like this idea.

The "default" short click could create "new item" header but the long-click drop-up buttons could create typed elements.
