### ISSUE TITLE
Tool tip

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#499]
Tool tips are used in many places but can be added to many more.

Add tool tips to each place that lacks them

**Comment by a13arnhe** [comment]
What do you mean by tool tips? Is this something that the system is still using and is the issue still relevant?

**Comment by HGustavs** [comment]
Retire this issue after make sure that the icons have the alt tag set so we can see some kind of tool-tip. Eg. the house icon tooltip should read something like "home"
