### ISSUE TITLE
Fileed mobile browsing - correct table size

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#4993]
The table is too big right now for mobile devices. Adjust it for better utility. 

![31919368_10209616087598265_1541665235155288064_n](https://user-images.githubusercontent.com/37794632/39567042-f09fdbac-4ebd-11e8-95e5-92a21dc32d30.jpg)

**Comment by c16linst** [comment]
A good example can be found on https://css-tricks.com/responsive-data-tables/ (on the cellphone under the headline "So here's what we are gonna do...")
