### ISSUE TITLE
DuggaED: Layout changes to the variant editor.

### ISSUE THREAD

**Issue by b16karhe** [HGustavs/LenaSYS#4996]
![real](https://user-images.githubusercontent.com/37793806/39569978-209ee0d8-4ec7-11e8-9182-98f892ee1e19.png)

**Some changes that might be of intrest to the costumer:**
- _Removing the answer column in the table to leave more room for the parameter column._
- _Changing the name from "Disabled/Enabled to Status in the table to make the column smaller._

**Comment by b16karhe** [comment]
@HGustavs what are your thoughts on this?

**Comment by a16konka** [comment]
@HGustavs What are your thoughts on this? Should we go ahead a continue the process?

**Comment by b16karhe** [comment]
Will talk about in person, closed.
