### ISSUE TITLE
"Jumping" navbar items

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#4999]
When menu alternatives are clicked, items in the navbar are "jumping". The styling for them should not be affected by other elements. 

<img width="1165" alt="skarmavbild 2018-05-03 kl 09 38 03" src="https://user-images.githubusercontent.com/37794632/39568053-42b2a462-4ec1-11e8-9ba7-50d58ec49e62.png">

**Comment by HGustavs** [comment]
Can this be improved without making the css / html more complicated?
