### ISSUE TITLE
Search in specific columns

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5003]
For now, the search happen in all columns and that can make it hard to find what you´re looking for. 
If you know in which column you want to search, something like this should be good:
<img width="602" alt="skarmavbild 2018-05-03 kl 11 43 14" src="https://user-images.githubusercontent.com/37794632/39570018-3dee50ce-4ec7-11e8-8318-80bc097a2d80.png">

First column name, two colon and then the string you want to search for.

**Comment by HGustavs** [comment]
Not a bad idea.
