### ISSUE TITLE
DuggaED: An icon that more clearly links to variants.

### ISSUE THREAD

**Issue by b16karhe** [HGustavs/LenaSYS#5005]
**It is not quite clear that the current icon is going to show variants.**
![unclear](https://user-images.githubusercontent.com/37793806/39571082-9fa01c6e-4eca-11e8-8d8d-8ed3214cc236.png)
_Use a better icon or create a new one and maybe declare something in the table header if needed._

**Comment by HGustavs** [comment]
This icon seems more like a "play" or "preview" button... we need something that means "expand" or "edit" or something similar

**Comment by b16linra** [comment]
This was solved in pull request 5016. This issue will be closed.
