### ISSUE TITLE
DuggaED: Fixes around the icons in the variant table.

### ISSUE THREAD

**Issue by b16karhe** [HGustavs/LenaSYS#5019]
**The styling around the icons need some work.**
![clickoutside](https://user-images.githubusercontent.com/37793806/39577627-2605dc6e-4ee2-11e8-8033-cf56277aecda.png)
**Things to do:**
- _Make the "play button" look like the other icons._ 
- _Remove/fix margins around icons so that they take up less space._

**Comment by b16linra** [comment]
This was solved in pull request 5019. This issue will be closed.
