### ISSUE TITLE
Access & Result - Standardised cell highlighting

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5021]
In order for the system to look and act the same across the entire platform we need to change the access cell highlighting to be like the one in resulted.

Fix in both Resulted and Accessed: As of right now the entire table moves and shifts a bit when you move the mouse cursor around. Example on a fix could be to create an invisible border so that the line only fills that invisible space.

**Comment by HGustavs** [comment]
Tried this but could not make it work, could not fix the over-draw in the borders, each row would cover the row below it so only first row would get a top border.... if you also come upon this problem we could resort to only fill the background for highlighting.

**Comment by HGustavs** [comment]
Screenshot of different variants so we can make an informed selection.

**Comment by a16jonis** [comment]
These are the different cell highlightings we currently have. @HGustavs What do you think?

Resulted: 
![result](https://user-images.githubusercontent.com/37793947/39616508-17856cc8-4f7c-11e8-91be-06a7a8ddef03.PNG)

Accessed:
![access](https://user-images.githubusercontent.com/37793947/39618236-18c4f962-4f83-11e8-9831-7720776a6657.PNG)

**Comment by HGustavs** [comment]
Im thinking that we can stop using borders alltogether if it causes problems and only use the semi-transparent gradient. Perhaps with slight coloring?

**Comment by c16matan** [comment]
It sounds like you would like to keep the current system, so we will try to fix the issue so that the borders doesn't shift, and if we get that working we will also implement that system into both accessed and resulted. If we don't get it to work we will instead use the other method suggested by you.
