### ISSUE TITLE
Reading deadline like date or json string

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5025]
Examine #4241 

The solution in the issue above only deals with how the data is added to the database. Implement a way for the system to read the newly implemented json string in all places where dugga deadlines are read and displayed on the website. 
Note that the system needs to be able to read both the newly implemented json string and the old date format.

**Comment by f16linli** [comment]
There are multiple files in LenaSYS that use deadline in the quiz table for logical comparison on dates.
If we where to make changes to this format, where it could contain Json objects, multiple files will fail, which will be very hard to fix without refactoring and changing the logic in every file where this is true. That would entail to much work and the risk for breaking things is very likely.

I don´t quite understand how this is suppose to work and how you would like to store it in the database.

**Comment by a17pongo** [comment]
@HGustavs 
Is this issue a duplicate and can be closed?

**Comment by HGustavs** [comment]
From what I can gather yes.
