### ISSUE TITLE
SectionED: With Add button, creating link and code items should not be possible when nothing is stored in files

### ISSUE THREAD

**Issue by d15marwi** [HGustavs/LenaSYS#5029]
At the moment its possible to create an item of type link and code with ADD button, when nothing is stored in 'Files'. This should not happen so we need a solution for this like we have with test items. 
![image](https://user-images.githubusercontent.com/37793970/39580774-37d003ea-4eea-11e8-9e4b-a71b49c60679.png)
in this picture we take care of the test item, the same should be applied for link and code

**Comment by HGustavs** [comment]
Not needed imho, work-flow may be the reverse, first creaing the links and then upload the files and subsequently connect them together.
