### ISSUE TITLE
Adding headings on selected text doesn't work

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5030]
One can add headings if the text is written after the markdown shortcut is added but not on selected text. If something in the middle of the text is selected and headings shortcuts are added the shortcut is places at the end of the page.

**Comment by HGustavs** [comment]
I suggest something like an insert at cursor function, which can in turn be used for all of the different markdown editor buttons.

https://stackoverflow.com/questions/11076975/insert-text-into-textarea-at-cursor-position-javascript
~~~
if (myField.selectionStart || myField.selectionStart == '0') {
        var startPos = myField.selectionStart;
        var endPos = myField.selectionEnd;
        myField.value = myField.value.substring(0, startPos)
            + myValue
            + myField.value.substring(endPos, myField.value.length);
    } else {
        myField.value += myValue;
    }
~~~

**Comment by HGustavs** [comment]
No need to support IE, firefox/chrome/edge only
