### ISSUE TITLE
DuggaED: Saving dugga changes opens the variant editor.

### ISSUE THREAD

**Issue by b16karhe** [HGustavs/LenaSYS#5038]
**The title is self explanatory, but here is a picture to highlight the button in question.**
![clickoutside](https://user-images.githubusercontent.com/37793806/39616538-393bbf70-4f7c-11e8-9b71-f8b821b16ed3.png)

**Comment by b16linra** [comment]
The error only occurs if the variant editor has been opened once before editing a variant. It also does not seem to be just the save button that causes this error, it also occurs when deleting an item.
