### ISSUE TITLE
Marking in duggasys

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#505]
Marking is done by viewing dugga and putting result in combo. 

If we have a kind of mark that requires a comment in additipn to marl, how can this be entered into box?

**Comment by c13chrjo** [comment]
Issue is not present

**Comment by d15marwi** [comment]
Unclear discribtion, need clarification!?

**Comment by a18kaswi** [comment]
Requested clarification in 2018, stil havent recieved any, probably not wanted by customer anymore, CLOSING.
