### ISSUE TITLE
Group: Design for new Group icons(Mockup)

### ISSUE THREAD

**Issue by d15marwi** [HGustavs/LenaSYS#5051]
We need new icons shown in the section Editor. These should mark what group is associated with each moment.  We need 3 types of group made of 8 groups (so 3*8). The design chosen  later by our Customer will be added into the system.

**Comment by a14chrve** [comment]
C:\Users\Vesterlund\Downloads\ikon-lenasys.svg
Above is a link to some groupicon-pictures. Are the icon something thar will function at LenaSys? What color is suitable?

**Comment by a14chrve** [comment]
Here is the icon for LenaSys selected by the group.

![groupicon3](https://user-images.githubusercontent.com/37794805/40107322-389fda62-58f8-11e8-9f12-a08a71fcabb2.PNG)

**Comment by d15marwi** [comment]
The Icon will be used in the referenced issue
