### ISSUE TITLE
Font weight is different in Firefox on macOS

### ISSUE THREAD

**Issue by b16linra** [HGustavs/LenaSYS#5055]
Font weight in Firefox on Windows and Chrome on macOS:
![bild](https://user-images.githubusercontent.com/37793838/39616359-49c47dc4-4f7b-11e8-95b2-0227425171a6.png)

Font weight in Firefox on macOS
![bild](https://user-images.githubusercontent.com/37793838/39616453-bbd716c4-4f7b-11e8-80e0-0660742563e9.png)

This might be related to anti-aliasing in macOS.

**Comment by a16thegu** [comment]
Approved.
