### ISSUE TITLE
Accessed - Fab for adding and importing users

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5061]
The functionality of adding and importing users on the access view should be made into a FAB (floating action button) in the style of the one on the course editor page. The previous two buttons should be removed.

**Comment by HGustavs** [comment]
Yes, a good idea.

**Comment by HGustavs** [comment]
We can do this with the long-click multiple button fab.

Default action should be "import" as this is 90% or more of all use.
