### ISSUE TITLE
DuggaED: Placement for the "+" button.

### ISSUE THREAD

**Issue by b16karhe** [HGustavs/LenaSYS#5063]
**At this moment in time the "+" button to add new duggas is placed to the far right.**
![clickoutside](https://user-images.githubusercontent.com/37793806/39621240-50a561a4-4f8e-11e8-8ac3-d237c9041d4d.png)

_A better fit would be to place it in over the middle column or at least move it a bit to the left to give a better look._

**Comment by a14isshi** [comment]
![image](https://user-images.githubusercontent.com/37794167/39625824-929447ea-4f9f-11e8-8be4-c2142a0a8d65.png)

The button has been moved to the left and is more inline with the trash-can. This issue is therefore closed.
