### ISSUE TITLE
Filter on examiner in marking view

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5067]
Primary issue for #4338 and #4339

Work on this issue can begin once the search functionality is added to the markdown view.

The ability to filter after a specific examiner is needed. For example the examiner "Bo Lindgren" needs to be able to find all students that he is supposed to grade.

**Comment by f16linli** [comment]
@HGustavs 
I don´t quite understand what the requirement is.

In issue #4338 (Part 1) 
> A teacher needs to be able to filter after examiner in the markdown view to find out which students are his/hers to grade.
>If we write the name of an examiner in a searchbox only students examined by this teacher are shown in the table.

In issue #4339 (part 2) 
> If the examiner exits the page and later on returns to it the filter is remembered.

In (part 2) do you want to add a filter in the filter menu and only show duggas that should be graded by the logged in teacher, or do you only want save the search box content for that teacher, so it is filled in when he/she logs back in? Or is there another solution that you want?

I just feel like saving the search box content seems like a strange approach, so I would need your feedback.

**Comment by a18kaswi** [comment]
Customer didnt respond two years ago. I doubt customer will respond now. We need to prioritze. Closing.
