### ISSUE TITLE
DuggaED: Add padding around the table.

### ISSUE THREAD

**Issue by b16karhe** [HGustavs/LenaSYS#5068]
**Change the styling around the table in duggaED to more closely resemble the one in sectionED.**

![clickoutside](https://user-images.githubusercontent.com/37793806/39626050-ad12c9b0-4fa0-11e8-9199-6e2b0582b454.png)
_The table in duggaED fills the whole page._

![clickinside](https://user-images.githubusercontent.com/37793806/39626070-c8098466-4fa0-11e8-84c2-02f6c431ab40.png)
_There is some padding around the table in sectionED._

**Comment by b16linra** [comment]
This was solved in pull request 5077. This issue will be closed.
