### ISSUE TITLE
Sectioned - Edit course version bugs

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5074]
Open a random course -> Click the cogwheel OR the plus next to the course version dropdown in the top left corner. Bug is related to the end- and start date in these views. Check sub-issues for further information.

* Change month bug #5075 
* End date before start date #5076

**Comment by a16jonis** [comment]
Seems to be an issue for group 3.

**Comment by a16linas** [comment]
Closing because the current datepicker will be replaced by a new one
