### ISSUE TITLE
Sectioned - Edit course version bug one 

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5075]
Part of #5074.

Click the cogwheel OR plus next to the Course version in the top left of a course page -> Click either Start or End date -> Click either the left or right arrow to change month. 

Doing this causes the change date popup window disappear. It seems like it is impossible to change the month of a course version this way?

**Comment by a16jonis** [comment]
Seems to be an issue for group 3.

**Comment by a16linas** [comment]
Closing because the current datepicker will be replaced by a new one
