### ISSUE TITLE
Sectioned - Edit course version bug two

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5076]
Part of #5074 

Click the cogwheel OR plus next to the Course version in the top left of a course page and click either start or end date. This will open up a popup window. 

It is possible to have the end date before the start date. Rather than letting the user do this, the if either start or end date is picked. The one left to choose should have the "impossible dates" greyed out and let them be unclickable.

Examples:

Start date is set to 4th of May -> When opening end date the dates before 4th should be greyed out.
End date is set to 4th of May -> When opening start date the dates after 4th should be greyed out.

**Comment by a16jonis** [comment]
Seems to be an issue for group 3.

**Comment by HGustavs** [comment]
I think this needs to be prioritized, as it is one of the most important things in the system.

**Comment by a16linas** [comment]
Closing because the current datepicker will be replaced by a new one
