### ISSUE TITLE
Styling of the markdown and file editor

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5081]
The markdown editor (and the regular text editor) could use some additional styling. It would be nice if the text area always matched the size of the box that’s holding it, regardless of if the window changes size and choice of browser (the most regular ones; firefox, chrome, safari). We would also like if there were some additional space between the text and the border of the text area, to increase readability.

There are three buttons to close the markdown editor (cancel, close, and “x”). If some of them aren’t absolutely necessary, they could be removed. If there are any other styling properties that could increase the user experience of the editor, feel free to apply them.

<img width="927" alt="skarmavbild 2018-05-05 kl 16 29 30" src="https://user-images.githubusercontent.com/37794632/39664304-8304120a-5081-11e8-9213-5d918c1d71d1.png">
<img width="1035" alt="skarmavbild 2018-05-05 kl 16 29 17" src="https://user-images.githubusercontent.com/37794632/39664305-832af834-5081-11e8-919f-92630c1b405b.png">

**Comment by HGustavs** [comment]
In my minds eye, this is what I see:
* Slightly wider view that adapts to the extents of the window
* Minimum borders around dialog. (<16 pixels from end of dialog to end of screen)
* Minimum border (is 2 pixels achievable??) between editor and preview
