### ISSUE TITLE
Movement of borders

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#509]
In code viewer it would be nice if it was possible to move the borders of the areas.
for example, if it is split 50% 50% vertically, this may not be ideal if we want documentation on the left and code on the right.
We may want a 20% 80% split instead.
If we could drag the borders each user could adapt his view to his preferences.

**Comment by HGustavs** [comment]
Local storage to store the setting would be sweet!

**Comment by HGustavs** [comment]
Click and drag of border.

**Comment by b12alela** [comment]
im on it
