### ISSUE TITLE
SectionED & DuggaED: Scroll-position

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5092]
The client suggested that we add a local storage function to be able to save the scroll position of the page, so that when reloading the page the position stays as it was before reloading.

**Comment by HGustavs** [comment]
a very good idea but some parts fo scrolling functionality has been deprecated due to responsivity issues on mobile browsers. Make sure that any solution is mostly compatible with this.

**Comment by b16linra** [comment]
This was solved in pull request 5137. This issue will be closed.
