### ISSUE TITLE
Accessed - Reposition searchbar & title text

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5095]
It is preferable to keep the styling of the website the same all over. The searchbar above the table should be moved to be just above the table rather than in the middle of the white space. (Look at FileEd)

The title text "Access" should also be move to the right. That is, center it to the middle of the page. 

Since the two buttons _Add user_ and _Import user(s)_ are about to be removed in #5061 these can be ignored. (If they are not already removed when doing this issue)

**Comment by HGustavs** [comment]
Screenshots of each would be a good idea for documentation so we can compare and thus know when it has been fixed.

**Comment by c16matan** [comment]
Before fix:
![image](https://user-images.githubusercontent.com/37793866/40363699-9d565f94-5dd0-11e8-86eb-74c68ea951d2.png)

**Comment by a16katba** [comment]
After fix:
![test1](https://user-images.githubusercontent.com/37793711/40364722-4dd18a22-5dd3-11e8-9008-f01de2ebedce.jpg)
