### ISSUE TITLE
SectionED: Group activity should have a group selector

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5096]
The client suggested that when creating a new group activity there should be a dropdown list that assigns a group to that activity ( G1-9, GA-F or GI-VIII(Latin) ).

**Comment by HGustavs** [comment]
Screenshot!

**Comment by c17alepe** [comment]
![image](https://user-images.githubusercontent.com/38323901/55946859-b75be180-5c4d-11e9-997f-c8e1ec93b4fa.png)
Mockup ^

Is this the kind of dropdown that is wanted? And what is meant by G1-9, GA-F, GI-VIII ?

**Comment by HGustavs** [comment]
In access view we assign groups by assigning symbols to each person.

For example we choose that Sven Persson is part of Group A and Group 4 and goup VII

And we can then show for instance

Supervision Group A

in the list if we choose Letter type for Supervison section.
