### ISSUE TITLE
Mobile theme code viewer does not work 100% well.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#510]
Menu heading and tab menu do look great but I am unsure about the functionality of the hotdog menu.

**Comment by a15alica** [comment]
@HGustavs Is this still relevant or does issue #3001 cover this?

**Comment by d17marle** [comment]
I cant seem to find the hotdog menu, where can you access it?

**Comment by HGustavs** [comment]
Since this is a 2015 issue perhaps the interface is distinct now ...
how does the code viewer look on mobile?

**Comment by HGustavs** [comment]
Screenshot

**Comment by d17marle** [comment]
i managed to find it, thank you either way!
