### ISSUE TITLE
CourseEd - Course and cogwheel fix

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5100]
When there are a lot of courses on the course editor page it is rather hard to see which cogwheel belong to which course in the list. This is due to the cogwheels being all the way to the right, and courses are centered in the middle of the page. 

Possible solutions:
* Move the cogwheels closer to the the course in the middle
* Underline the row all the way over to the cogwheel (could perhaps be made like a discrete dotted line?)

**Comment by a16jonis** [comment]
@HGustavs Could you chime in on this, is it a good idea? Which of the proposed solutions is preferable, if any.

**Comment by HGustavs** [comment]
Perhaps a row highlight only for superusers/teachers when logged in. 

As it is only for this group that it makes sense for?

Im thinking some kind of semitransparent gradient background (which I think is the default for sortabletable in other parts of the UI)

Screenshots for documentation of what it looks like would be helpful.

**Comment by a16lovka** [comment]
@HGustavs  Would this solution to put the cogwheels closer to the text work? 
![image](https://user-images.githubusercontent.com/36051552/40306736-15d1e82a-5d00-11e8-8702-83287cd29108.png)

To have a different background on every other row may look strange on the courseed page.

**Comment by a16lovka** [comment]
Merged. Closing
