### ISSUE TITLE
DuggaED: Variants - left to right scroll

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5103]
When reducing to a certain width the variants table should change to a left to right scroll instead of the current situation where the table width depends on the window width.

<img width="528" alt="skarmavbild 2018-05-07 kl 11 33 09 fm" src="https://user-images.githubusercontent.com/37795608/39695356-88c6c948-51ea-11e8-8547-a3b70185a49f.png">

**Comment by HGustavs** [comment]
Screenshots before we make any decision...

**Comment by b16karhe** [comment]
@HGustavs a screenshot has been added. A way to fix the issue would be for the "overflow" to go from hidden to auto when the screen gets to small.

**Comment by b16karhe** [comment]
No need to fix because it only affects very small screens.
