### ISSUE TITLE
Contribution - overall stats bug

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5107]
Part of #4825 

It seems that "Events Performed" under project statistics for a user takes "Comment Creation" into account. 

Using the provided testdata we can see that created comments amounts to 138. Looking at the total amount of performed evens in the contribution list below we can see that 7 events have been performed. If we now look back to the table at the top we can see that "Events Performed" is at 145.

**Comment by a16jonis** [comment]
@HGustavs Could you verify this?

**Comment by HGustavs** [comment]
This is most likely a bug, I think that since comments are listed elsewhere it makes sense to not include comments in the events category.

I think this could be filtered on the SQL level.
