### ISSUE TITLE
Parts of code does not use PDO

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#511]
We need to phase out the insecure mysql in favour of PDO.

**Comment by a13jorla** [comment]
Are this two issues relevant any longer? @HGustavs , @b13frero , @b12simsa , @a13erilj , @c12jenek .

**Comment by HGustavs** [comment]
I think that this has been resolved?
All three sub-projects use pdo now? if this can be confirmed then I think we can retire this issue.

**Comment by a13ottne** [comment]
UMV uses PDO

**Comment by HGustavs** [comment]
I am retiring this issue now.
