### ISSUE TITLE
Add the freedraw tool again

### ISSUE THREAD

**Issue by c16linst** [HGustavs/LenaSYS#5110]
In a previous version of the diagram, there existed a freedraw tool where you could press multiple times in the diagram to make a symbol of your choice. This could be useful in some situations, and could therefore be added again.

**Comment by HGustavs** [comment]
Useful for drawing a partition of a diagram. 

* It would be useful to be able to set background fill color, line color and opacity value.
* It should be possible to have "no fill" (not same as 0% opacity).
* If not very difficult dashed lines would be a nice embelishment.

**Comment by a16juleh** [comment]
We have created subissues for your input: 

- It would be useful to be able to set background fill color, line color and opacity value. It should be possible to have "no fill" (not same as 0% opacity (#5373). 
- If not very difficult the ability to draw using dashed lines would be a nice embelishment (#5371).
