### ISSUE TITLE
DuggaED: Variants table should be sortable

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5117]
At the moment the variants table is not sortable. This need to change and the sorting function needs to be adopted to each column of the table in order to sort things by column.

**Comment by HGustavs** [comment]
This is a good idea.
Also searchable with the standard looking-glass icon that we have adopted elsewhere.

Perhaps a mock-up could be possible?

The record for variants so far is 35 variants for a single test, so the dialog should be reasonably workable with at least 35 variants.
