### ISSUE TITLE
SectionED: Change the old datepicker to the browsers default

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5119]
At the moment LenaSYS uses a datepicker.js file to be able to choose a date. After a discussion with the client he suggested that if this doesn't create any functionality issues then it should be a good idea to use the browsers own datepicker.

<img width="605" alt="skarmavbild 2018-05-07 kl 11 16 40 fm" src="https://user-images.githubusercontent.com/37795608/39694606-31104302-51e8-11e8-9f2a-7074f8656ba8.png">

**Comment by HGustavs** [comment]
Primarily we cannot write a time in this dialog.

So the workflow is, use dropdown to select a date and then write e.g. 17:00 at the end of it.

We want the time and date at the same time with some kind of calendar functionality, ideally in one step.

**Comment by a16thegu** [comment]
According to #4284 , HTML5's date/time picker is not supported by all web browsers. So we cannot implement this functionality yet. But we have found a jQuery date/time picker that can be a option (Datepair Plugin):

http://jonthornton.github.io/jquery-timepicker/

Can this be an option, @HGustavs ?

**Comment by b16linra** [comment]
Solved in pull request 5206. That solution seems better than what was currently implemented and if the customer is happy with this, it might be a good idea to implement the same solution everywhere where a date and time is selected, like in DuggaEd.
