### ISSUE TITLE
Names are not consistent

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#512]
Naming is inconsistent in some cases.
In javascript we have a name for a value/variable
in AJAX/html we have names for parameters
In php we have a name for a value/variable
in SQL columns have names

The code needs to be reviewed so that the names of variables in javascript, html, php and SQL correspond.

For example, if the column in the database is called courseid, html, php and javascript also need to use the name courseid and not cid or some variation of it.

**Comment by HGustavs** [comment]
Is this not an ALL issue?

**Comment by a13arnhe** [comment]
I deem that this issue, like #513 is not of great concern to the project at this moment as there are more pressing issues that need to be fixed and finished. I say that when the right time comes either this issue can be reopened or recreated.
