### ISSUE TITLE
DuggaED: Change the old datepicker to the browsers default

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5120]
At the moment LenaSYS uses a datepicker.jr file to be able to choose a date. After a discussion with the client he suggested that if this doesn't create any functionality issues then it should be a good idea to use the browsers own datepicker.

<img width="605" alt="skarmavbild 2018-05-07 kl 11 16 40 fm" src="https://user-images.githubusercontent.com/37795608/39694606-31104302-51e8-11e8-9f2a-7074f8656ba8.png">

**Comment by a16thegu** [comment]
According to #4284 , HTML5's date/time picker is not supported by all web browsers. So we cannot implement this functionality yet. But we have found a jQuery date/time picker that can be a option (Datepair Plugin):

http://jonthornton.github.io/jquery-timepicker/

Can this be an option, @HGustavs ?

**Comment by HGustavs** [comment]
If it works in reasonably new firefox and chrome the standardized way is much better than the scripted version.

If we can get a calendar-like date dropdown but it does not have time
then we can add a second time dropdown for writing the time, and these two are then combined to form the date+time that we then store in the database.

**Comment by b16johso** [comment]
Issues solved?
