### ISSUE TITLE
document.getelementbyid

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#513]
There are places that use document.getelementbyid(id); rather than $("#"+id) which is shorter and most of the time easier to understand using Jquery (one of the few allowed instances of libraries)

**Comment by a13jorla** [comment]
a13alfbe is checking the codeviewer files.

**Comment by f12danjo** [comment]
This merge has now fixed part of this issue. [#1539](https://github.com/HGustavs/LenaSYS/pull/1539)

**Comment by a13arnhe** [comment]
Is this still relevant? a year has passed and apparently this standard of not having "document.getElementById()" was not followed and is not being followed. Currently for example I can find  53 instances of usage of it in 5 files, and that is not all as it seems to be used in every javascript file in the system. Does this affect the performance at all?

**Comment by HGustavs** [comment]
No, not really a performance issue but a code readability issue.

Im thinking we either retire this issue or try to fix it. 

Currently I think there are more pressing issues, so I vote for closing this issue and moving on to more pressing issues, that result in crashes or, in issues that have to do with missing features.

An issue that only improves readability is not that important in comparison so I say close+wontfix

**Comment by a13arnhe** [comment]
Focusing on other problems is more important at this moment. !wontfix
