### ISSUE TITLE
DuggaED: Fix magic heading in the dugga table and the variant table.

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5136]
At the moment when scrolling inside the variants table and dugga table there is a bug that makes just one column header visible while all the others disappear for no reason. This needs to be fixed by making sure the whole table header is visible during scrolling.

**Comment by b16linra** [comment]
There seems to be some different errors occuring with the headings.

Error 1:
![bild](https://user-images.githubusercontent.com/37793838/39702331-b8c8ce74-5204-11e8-95cd-09d629f47ff8.png)

Error 2:
![bild](https://user-images.githubusercontent.com/37793838/39702267-7da585bc-5204-11e8-8cc4-1fb0e997192f.png)

Error 3:
![bild](https://user-images.githubusercontent.com/37793838/39702280-89fa379a-5204-11e8-9bdb-5c8a14840dd6.png)

**Comment by HGustavs** [comment]
Magic headings only works for full screen dialogs. Since this is a table inside a dialog the only solution for now is to disable magic headings.

**Comment by b16linra** [comment]
This was solved in pull requet 5151. This issue will be closed.
