### ISSUE TITLE
Global appearance doesn't work properly 

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5140]
The diagram has a global appearance menu that doesn't work properly, the changes aren't updated as the values in the selectboxes, you have to click "OK" to se the changes for the diagram. The selectbox options aren't correct from the beginning and should have a default statement to minimize   trouble. 

<img width="1027" alt="skarmavbild 2018-05-07 kl 17 09 15" src="https://user-images.githubusercontent.com/37794632/39709162-673d13e8-5219-11e8-9a4c-475248532a11.png">

**Comment by HGustavs** [comment]
Low priority
