### ISSUE TITLE
SectionED: Entry table bottom-margin

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5142]
At the moment the FAB button is on top of the last entries edit and delete button, this needs to be fixed somehow with a bottom margin on the content table so that the page can be scrolled a bit further and allow the possibility to press the last entries edit and delete button.

<img width="1440" alt="skarmavbild 2018-05-08 kl 8 37 22 fm" src="https://user-images.githubusercontent.com/37795608/39741681-23d66cc6-529b-11e8-8e27-4ea3e813018f.png">

**Comment by a16thegu** [comment]
Approved.
