### ISSUE TITLE
Zoom functionality doesn't work correctly

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5145]
The zoom alternatives in the diagram are to many, 30% to 200% is enough. Sometimes when the zoom is changed from high to low percent and vice versa, the image is freezing and hacking. 

![31960773_10209643363360142_4759662231778492416_n](https://user-images.githubusercontent.com/37794632/39742724-da097af8-529e-11e8-97d1-a3fafd87e1b4.png)

**Comment by b16petma** [comment]
The problem seems to be when we move around the canvas when in zoom in or zoom out the coordinates (sx, sy) get the wrong values. This result in mouse coordinates doesn't match the canvas, we clear a incorrect rectangle when updating graphics and the grid is not drawn correctly.

**Comment by c16linst** [comment]
Found another issue on this #3463

**Comment by a17drama** [comment]
This issue should be solved when #5826 is implemented

**Comment by a17alfcl** [comment]
Already solved in issue #5826
