### ISSUE TITLE
DuggaED: Start date is not registered

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5148]
At the moment the start dates are not getting registered in the test table and the value in always "null". The only way to add a start date is by editing the entry afterwards.

## New entry
<img width="1430" alt="skarmavbild 2018-05-08 kl 9 31 06 fm" src="https://user-images.githubusercontent.com/37795608/39743898-c12c9e58-52a2-11e8-8be5-bb4122f06cfb.png">

## After edit
<img width="1430" alt="skarmavbild 2018-05-08 kl 9 35 56 fm" src="https://user-images.githubusercontent.com/37795608/39744059-43bec198-52a3-11e8-88b3-1edabba798e7.png">

**Comment by b16linra** [comment]
This was solved in pull request 5158. This issue will be closed.
