### ISSUE TITLE
Result-handling is not working in duggasys

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#515]
There should be a nice overview on the results from duggas.
- One view should display results in the old paper-format used by administration
- One view should be glanceable for online use

**Comment by c13chrjo** [comment]
Issue is not present

**Comment by a16konka** [comment]
Issue has been opened and closed multiple times without any end result. This issue should stay open until it is fixed.

**Comment by a17pongo** [comment]
@HGustavs is this still high priority? 
If so, could we get some reference to what this issue is suggesting or more information?

**Comment by HGustavs** [comment]
I think this has been solved by the csv export functionality in sortabletable... mostly so I say we can close and open new issues for any minor remaining kerfuffles.
