### ISSUE TITLE
AccessEd - Requested password reset indicator

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5152]
Before using sortableTable for the access editor table, the row of users who had requested a new password would have a red background to make it easy for a teacher or superuser to see.

We need to implement something similar to this. Colouring the entire row in red is a bit excessive, perhaps colouring the "reset pw" cell in yellow could work?

**Comment by a16jonis** [comment]
@HGustavs Any specific colour or styling that you'd prefer?

**Comment by a16jonis** [comment]
Update (from HG):

If it is possible to make the whole row red - do that!
If not, making the "reset pw" cell red/yellow is okay too.

**Comment by b16filor** [comment]
@HGustavs

**Comment by b16johso** [comment]
Has this been implemented?

**Comment by a17maxsj** [comment]
seems to have been implemented in #5673
