### ISSUE TITLE
DuggaED: Sorting resets when creating a new test

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5157]
At the moment when creating a new test while the table is sorted, the new entry resets the sorting back to how it was before sorting it. 

## Before new test
<img width="1434" alt="skarmavbild 2018-05-08 kl 1 08 53 em" src="https://user-images.githubusercontent.com/37795608/39754003-04e57200-52c1-11e8-8fcd-79028e026590.png">

## After new test
<img width="1431" alt="skarmavbild 2018-05-08 kl 1 09 02 em" src="https://user-images.githubusercontent.com/37795608/39754011-0a48f244-52c1-11e8-899c-69a798ea16cc.png">

**Comment by a16joare** [comment]
Is this issue fixed? When we are looking at this in the test environment it seems to work? Another issue could be that it is not possible to sort from top - down, just down - top?

**Comment by a17maxsj** [comment]
bump

**Comment by a16joare** [comment]
This issue is solved in this pull request #5944
