### ISSUE TITLE
Add cellediting to specific columns

### ISSUE THREAD

**Issue by d16linja** [HGustavs/LenaSYS#5164]
For example in the access table we only want to be able to add cell editing for the first 4 columns, and not the rest

If you add a function for cell editing in the current version it gets applied to every cell.

**Comment by HGustavs** [comment]
Some kind of return false option would be the best option for cancelling the editing of certain columns.

e.g. 

if the edit popup callback returns false we skip over showing the popup and nothing happens.

**Comment by a17pongo** [comment]
@HGustavs has this issue been solved, because some columns seems to be uneditable while others are.

**Comment by b18jonli** [comment]
This is already fixed with a "return false"-solution
