### ISSUE TITLE
SectionED: Toggle and hide new swimlande view

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5165]
This issue refers to #5163.

In order to implement the new swimlane view, we need to have a function that slides in the side navigation, and pushes the swimlane content to the right.

An example of how we want to implement this function. 
https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sidenav_push

**Comment by b16linra** [comment]
This was solved in pull request 5235. This issue will be closed.
