### ISSUE TITLE
ResultEd - table display bug

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5220]
In the result editor view: 

When a course has no tests the contents of the Fname/Lname/SSN column is not rendered, only the column headers. Even if a course is empty as such, the contents of the column should probably still be rendered.

In the current state: 
![jon](https://user-images.githubusercontent.com/37793947/39994785-97f63f8a-577a-11e8-9e19-2d3dc7146fdd.jpg)

**Comment by HGustavs** [comment]
We need to also render the counter column so we can easily count the students.
