### ISSUE TITLE
SectionED: Icon bug in the statistics tab

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5233]
Currently there is a bug that needs to fixed. The arrow icon that is displayed on the "statistics" tab needs to be displayed the other way around, which means that the "down" arrow need to be shown whenever the statistics tab is closed and the "right" arrow whenever the statistics tab is open.

**Comment by b16linra** [comment]
This issue was reopened because the wrong issue was closed by mistake.

**Comment by a16thegu** [comment]
Approved.
