### ISSUE TITLE
DuggaED: Add a title

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5248]
At the moment the DuggaED dosn't have a title on the pages header like all other pages do. We thought it would be a good idea to add one in order to make all pages consistent. 

## Example
<img width="1287" alt="skarmavbild 2018-05-15 kl 10 11 24 fm" src="https://user-images.githubusercontent.com/37795608/40044702-7cd4a6d4-5828-11e8-9245-7725ba72b3a8.png">

**Comment by HGustavs** [comment]
Good suggestion.
