### ISSUE TITLE
AccessEd & ResultEd - Remove the sorting icon in the navheader

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5253]
Since sorting has been implemented by clicking on the column header in the table itself we probably don't need this alternative way of sorting, it seems redundant. Should we remove these? @HGustavs 

The icon at the right:
![navheader](https://user-images.githubusercontent.com/37793947/40045579-fe4d9890-582a-11e8-8e26-e40d4bc1c707.PNG)

**Comment by HGustavs** [comment]
I kind of like to have both.
Not all sort values are headings, for instance if name is the heading we may have ssn, first name and last name inside that table. We would most likely want to be able to sort on either. The easiest way to display this is to have a sorting button for those edge cases.

**Comment by a16jonis** [comment]
Ok, I've created new issues for implementing this feature in both Access and Result. Closing this issue since it is no long relevant.
