### ISSUE TITLE
ResultEd - Sorting icon in navheader

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5257]
In result editor view:

Sorting is already possible by clicking on the column headers in the table itself. We need to implement the feature of sorting the table from the sorting icon in the navheader. (The icon to the right)
![navheader](https://user-images.githubusercontent.com/37793947/40046974-802b5a7a-582e-11e8-82ed-eaa6ee584d18.PNG)

Note that the radio- and checkboxes in the popup might be outdated since they were lasts used before sortableTable was implemented. 
![result](https://user-images.githubusercontent.com/37793947/40046980-859a2e96-582e-11e8-84c9-26b06c3df9a6.PNG)

**Comment by b17nicsv** [comment]
This is already implemented. Sorting through the sort tool in the navbar works.
