### ISSUE TITLE
DuggaED: Check access on the buttons

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5266]
At the moment we have a method that checks if a user has access to the duggaED content and we show/hide the content depending on the users access. The problem with this is that anyone with programming skills can enable the hidden content (the empty sortable table, fab button and "add" button) which can cause some problems. What we want to do is have the same method check if the user has access to perform the action whenever the FAB button or the "add" button is pressed. By doing this we could potentially create an extra "security wall".

**Comment by a15magkn** [comment]
This has already been resolved in another issue, #5398, and therefore this issue will be closed.
