### ISSUE TITLE
Unable to remove courses

### ISSUE THREAD

**Issue by b13gusbe** [HGustavs/LenaSYS#527]
Unable to remove new courses.

**Comment by b13alebr** [comment]
If you edit a couse and change visibility to "deleted" the course will not show in the list but is not deleted from database. If "deleted" is choosen the values 3 will be stored in the database and only courses with visibility less than 3 will show in the list. courseedservice.php line 101 to 105.

**Comment by b13alebr** [comment]
courseedservice.php has an empty if statement "if(strcmp($opt,"DEL")===0){}" that could be used to delete courses from database.

**Comment by HGustavs** [comment]
For accountability reasons we do not delete almost anything. We hide things, since if things disappear, information may be lost.

**Comment by c13chrjo** [comment]
Since you should not be able to delete the course, I will close this issue
