### ISSUE TITLE
DuggaED: Hide more content

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5286]
Related to issue #5214 

At the moment if a user dosn't have access to content in DuggaED the content in not visible at all for them. But since we added a title to the page and a search function it would be a good idea to hide them too for users that don't have access.

## From a guest perspective
<img width="1440" alt="skarmavbild 2018-05-16 kl 7 56 58 fm" src="https://user-images.githubusercontent.com/37795608/40099233-79196d9c-58df-11e8-97f6-f9adad7e8892.png">

**Comment by a14isshi** [comment]
#5304 pull-request, merged and closed. Therefore This is closed as well.
