### ISSUE TITLE
SectionEd: New Statistic/Course-overview function, create a "upcoming deadline" with 3 or 5 deadlines

### ISSUE THREAD

**Issue by d15marwi** [HGustavs/LenaSYS#5298]
One of the original ideas with swimlanes was to give the students a fast method to check which deadline comes up next. This feature was never been used as intended by the student so we will add a quick and downsized overview for users to see the next upcoming deadlines for tests (if any exist)

![image](https://user-images.githubusercontent.com/37793970/40103038-70d4afb8-58ec-11e8-874c-4a1517575536.png)

**Comment by a16thegu** [comment]
Approved.
