### ISSUE TITLE
ResultEd - Fixed positions for search bar and title 

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5299]
In result editor view:

If you horizontally you'll notice that the search bar and "Result" title stays static in their position. They should probably have a fixed position on the screen so they "follow" when you scroll to the right.

Consider also that you probably want to have the search bar available even if you have scrolled far down into the table. Perhaps somehow attaching it under the magic magic header could work? @HGustavs Any input regarding this?

**Comment by c16matan** [comment]
We have merged a version of this issue now, and currently it is always fixed, so it will follow the screen both vertically and horizontally. However, it's not attached to the magic header and it also got a low z-index value, thus, it will always end up behind the table and magic header. But it is visible if the table is not wide enough to cover the entire screen (low amount of columns). @HGustavs What do you think about this?
