### ISSUE TITLE
The Back/Return button 

### ISSUE THREAD

**Issue by a13henhu** [HGustavs/LenaSYS#531]
The Return/Back button in codeviewer isn't linked to a page, when clicked on. 

<-a href="sectioned.php?courseid=UNK&amp;coursevers=UNK"><-img src="../Shared/icons/Up.svg"-><-/a> The linked page is missing in the server(?)

**Comment by a13jorla** [comment]
It's linked to a page but it's not linked right cause it tries to go to sectioned.php.
