### ISSUE TITLE
SectionED: Hide the statistics tab on mobile

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5324]
Currently when on mobile mode the statistics tab dosn't behave well, so the idea was to hide it untill we figure out a method to display it.

## The issue
<img width="406" alt="skarmavbild 2018-05-17 kl 9 02 29 fm" src="https://user-images.githubusercontent.com/37795608/40161438-0cb7e85e-59b1-11e8-8c0e-2ee82dd10ac0.png">

**Comment by b16linra** [comment]
This was solved in pull request 5327. This issue will be closed.
