### ISSUE TITLE
SectionED: Small improvement to code when creating new items

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5330]
When creating a new item in SectionEd, the page is automatically scrolled to the bottom to show the new item. Because the AJAX request is asynchronous, the current implementation uses a timer to wait for the AJAX request to finish before scrolling to the bottom. This is not optimal and should be changed.

**Comment by b16linra** [comment]
The change of scroll position should probably happen at the end of the method that is called if the AJAX request is successful.

**Comment by a16thegu** [comment]
Approved. Solution works as a substitute for the previous solution.
