### ISSUE TITLE
Fileed FAB works incorrectly for iOS 11.3 (and further versions)

### ISSUE THREAD

**Issue by c16linst** [HGustavs/LenaSYS#5343]
The fab in the fileed's mobile view doesn't work correctly for phones with iOS 11.3 (and further versions). In some cases the click functionality works as it should, but for others the different fab effects interferences with each other which makes it work incorrectly.

**Comment by a16jenja** [comment]
I tried this on my phone and on two other phones, two of them were androids and one of them were IOS. The FAB button worked as it should on all three phones, not sure if this is still an issue in that case. Need some clarification about this.

**Comment by b17nicsv** [comment]
Closing this issue. Way to low priority and also no clarification since last comment so I guess it's fixed.
