### ISSUE TITLE
Fileed mobile browsing - FAB can't be closed when pressing outside of it

### ISSUE THREAD

**Issue by c16linst** [HGustavs/LenaSYS#5347]
As for now, the FAB cannot be closed when you press outside of it. The idea is that one should be able to press wherever on the page when the FAB-list is visible (except for on "the little FAB-buttons") to close the FAB-list. This works in desktop mode, but not in mobile mode.

![skarmavbild 2018-05-17 kl 11 30 42](https://user-images.githubusercontent.com/37794714/40169216-c8a35814-59c5-11e8-9d37-1eaac39c5870.png)

**Comment by a17pongo** [comment]
@b17nicsv since we have hover functionality on all FAB;s now this issue is solved?

**Comment by b17nicsv** [comment]
Closing this because it isn't an issue anymore.
