### ISSUE TITLE
Database// update problem

### ISSUE THREAD

**Issue by a13jansa** [HGustavs/LenaSYS#535]
Some files are not connected to the database and the databas is not defined!

**Comment by a13erisc** [comment]
"mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/html/master/Shared/database.php on line 32" in EditorV50.php
Should be mysqli_connect()!

**Comment by c13caral** [comment]
This issue is not longer relevant. I will now close this issue.
