### ISSUE TITLE
AccessED: Add groupd to the filter

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5354]
At the moment when hovering on the filter icon all column options are available besides the "groups" column. This should be fixed so that you can show/hide all columns from the table.

<img width="1349" alt="skarmavbild 2018-05-17 kl 1 42 48 em" src="https://user-images.githubusercontent.com/37795608/40175451-70d45c10-59d8-11e8-8942-04d20b1c6b03.png">

**Comment by a16jonis** [comment]
This has already been fixed.
