### ISSUE TITLE
AccessED: Change the language on the groups dropdown

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5355]
At the moment the groups column has a dropdown for each user that is writen in swedish. This needs to change to english in order to keep content consistent.

<img width="1305" alt="skarmavbild 2018-05-17 kl 1 47 19 em" src="https://user-images.githubusercontent.com/37795608/40175818-b0247b38-59d9-11e8-972e-76482abeb4c9.png">

**Comment by c16matan** [comment]
Merged. Closing.
