### ISSUE TITLE
AccessED: Align the search bar

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5356]
Currently the search bar is a bit out of place and needs to be aligned.

<img width="475" alt="skarmavbild 2018-05-17 kl 1 55 05 em" src="https://user-images.githubusercontent.com/37795608/40175900-f093264c-59d9-11e8-984a-6df276a6b528.png">

**Comment by HGustavs** [comment]
Not a bad idea.
Dont forget to make this styling global so that all search boxes are affected equally and that no other one is worse from this change... if the search box is too big in some other dialog... this fix can cause problems elsewhere.

**Comment by a16jonis** [comment]
This issue already exists #5095.
