### ISSUE TITLE
DuggaED: Update template files

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5360]

**Comment by HGustavs** [comment]
We need more of a description here. Too little information for future use as documentation.

**Comment by b16karhe** [comment]
**DESCRIPTION of the PROBLEM.**

Some of the templates does not work correctly with the preview as they are constructed at the moment which in some cases led to various errors as seen below.
![error](https://user-images.githubusercontent.com/37793806/40362965-5b9e1b0c-5dce-11e8-9007-2164ccd3b3ec.png)


_Changes will probably be needed in both the preview function and in the template files to make it work as intended._

**Comment by d15marwi** [comment]
We are not sure why and from were we get these errors. Maybe it was just something with the virtual server. Needs to be analyzed in further sessions
