### ISSUE TITLE
JSON deadline object - Creating new dugga

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5377]
Check #5345 for information

The JSON deadline object added in the mentioned merge request seems to work only when editing an already existing dugga, not when creating a new one. This functionality needs to be implemented as well.

**Comment by HGustavs** [comment]
Yes this is quite important as this functionality is not useful without it.

**Comment by d16linja** [comment]
Solved, the first deadline gets added as a deadline as both json and the old way to that everything still works as usual at the webpage
