### ISSUE TITLE
Accessed - Missing table error

### ISSUE THREAD

**Issue by c16matan** [HGustavs/LenaSYS#5385]
Accessed.php is currently giving the error that can be seen on the image below. A member of group 3 said that a table for groups should not even exist, so could @a16konka or @d15marwi please clarify how this should be solved? However, Issue #5085 says that the database should be updated, and if that is actually correct please update install/SQL/init_db.sql with the table. 

![image](https://user-images.githubusercontent.com/37793866/40232458-255ae7c8-5a9f-11e8-8546-459005bc2847.png)

**Comment by a16filol** [comment]
This issue was solved in the last merge. Update migration v0.05 and v0.06 and the correct group tables should be set.
