### ISSUE TITLE
Resulted - Sorting bug

### ISSUE THREAD

**Issue by f16linli** [HGustavs/LenaSYS#5386]
It seems like the sorting on last name does not work as intended. Because when searching on last name parameters those results are not shown.
![image](https://user-images.githubusercontent.com/37804205/40232591-b41a410c-5a9f-11e8-861c-945e2d1fa294.png)

The search result for "andersson" can be seen below
![image](https://user-images.githubusercontent.com/37804205/40232617-d173bb84-5a9f-11e8-9d90-29ea25d64cf7.png)

**Comment by c16matan** [comment]
Merged
