### ISSUE TITLE
DuggaED: Only people with access should be able to see content

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5398]
At the moment users without access are being redirected to the main page of the course. The problem is that the content in duggaED is still visible and the html code is there for other people with experience to see. The idea was to create the content at the same time that access is given through the database and delete the content when the access is denied, so that hackers or other people with bad intentions don't get access to sensitive content.

**Comment by a15magkn** [comment]
Reviewed and closed
