### ISSUE TITLE
DuggaED: Clean up the duggaservice.php file

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5403]
Clean up the duggaservice.php file so that the code has code that is useful.

**Comment by HGustavs** [comment]
It would be nice to outline what will be removed so we know which functions that are removed... if someone encounters a bug in the future it is then easier to trace the origin of that bug.

**Comment by b16karhe** [comment]
**@HGustavs**  _The functionality that has been removed has to do with updating fields inside the old table and since we are now using the new "sortable Table" there should not be any problems regarding this._

**Comment by HGustavs** [comment]
ok.

**Comment by b16linra** [comment]
This was solved in pull request 5406. This issue will be closed.
