### ISSUE TITLE
Table header is smaller than the table

### ISSUE THREAD

**Issue by c16linst** [HGustavs/LenaSYS#5405]
The table header has currently got a smaller width than the rest of table, which leaves a gap of some pixels.

**The left side has got some kind of border**
![skarmavbild 2018-05-21 kl 09 49 26](https://user-images.githubusercontent.com/37794714/40296299-8ecae444-5cdc-11e8-8718-e33c07254664.png)

**The right side is somewhat smaller than the table**
![skarmavbild 2018-05-21 kl 09 50 13](https://user-images.githubusercontent.com/37794714/40296301-8efeb832-5cdc-11e8-8ab9-cf9f3295f093.png)

**Comment by HGustavs** [comment]
This styling should be in the css. Also confirm that this is not a local style for that specific table but something that is as global as we can make it styling-wise.
