### ISSUE TITLE
Pen and trashcan icons are not correctly aligned

### ISSUE THREAD

**Issue by c16linst** [HGustavs/LenaSYS#5413]
The pen and trashcan icons in the fileLink table should be in the center of the column, not aligned to the left.

![skarmavbild 2018-05-21 kl 10 11 44](https://user-images.githubusercontent.com/37794714/40297273-8853dc76-5cdf-11e8-8322-a92b40597936.png)

**Comment by a16juleh** [comment]
A new issue for white space around icons and unnecessary extra spaces for all the other columns in sortabletable is created.
