### ISSUE TITLE
Accessed - New fab icons

### ISSUE THREAD

**Issue by c16matan** [HGustavs/LenaSYS#5414]
The FAB on the accessed page should get two new icons which represent their respective action (create user and import user). The current look of it can be seen on the image below.

![image](https://user-images.githubusercontent.com/37793866/40297157-19e255ec-5cdf-11e8-8ac2-b1a4b0843ecf.png)

**Comment by a16seplu** [comment]
i was thinking something like this?

import:
![image](https://user-images.githubusercontent.com/37794583/40305942-0163028c-5cfd-11e8-9f2e-eff4d2a76b39.png)

Create:
![image](https://user-images.githubusercontent.com/37794583/40305987-3235a946-5cfd-11e8-981f-4f9294fe2840.png)

maybe slightly low-quality

**Comment by c16matan** [comment]
@HGustavs

**Comment by a16chrsa** [comment]
The new icons are now in use in #5586.

**Comment by a17maxsj** [comment]
Buttons are implemented so will close this issue.

**Comment by a17fellu** [comment]
The Buttons are not implemented. The buttons does not even exist. I will create the icons for:
* Create user
* Import User

**Comment by a17fellu** [comment]
The new Create User Icon:
![createUser icon](https://user-images.githubusercontent.com/49202955/56297191-3068a680-6130-11e9-8d1f-3549c197c76d.PNG)

**Comment by a17fellu** [comment]
The new Create User Icon:
![createUser icon](https://user-images.githubusercontent.com/49202955/56297415-91907a00-6130-11e9-96bf-7d9c86cea121.PNG)

**Comment by a17andby** [comment]
Fixed and merged. Closing.
