### ISSUE TITLE
Clearly see which courses are mandatory - UserManegementView

### ISSUE THREAD

**Issue by c13emmjo** [HGustavs/LenaSYS#542]
Ex. different colors and hovers

**Comment by a97marbr** [comment]
I would not say mandatory, but rather which are in core subject, i.e, datalogi for webug and on what level. Perhaps the overall progressbar could be divided similar to iTunes bar showing music, apps, etc....

**Comment by a13ottne** [comment]
feature discarded, will show pre-requirements
