### ISSUE TITLE
DuggaED: Some test don't delete

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5425]
At the moment some test aren't being removed. There is no explanation to why at the moment, but its something that needs to be fixed.

**Comment by HGustavs** [comment]
Well if that test has been used by someone it is very important that we cannot delete it.

But if it has not been referenced I would consider this a bug.

**Comment by b16linra** [comment]
@HGustavs - It is probably a foreign key constraint causing this, so we will add an error message that displays a message to the user.
