### ISSUE TITLE
SectionED: Make the piechart bigger

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5435]
At the moment the piechart is kinda small and the idea was to make it a bit bigger so that it is more visible.

<img width="426" alt="skarmavbild 2018-05-21 kl 2 18 14 em" src="https://user-images.githubusercontent.com/37795608/40307209-d625043a-5d01-11e8-92ab-c3cc5adc7bb7.png">

**Comment by b16linra** [comment]
These changes were made in pull request 5514. This issue will be closed.
