### ISSUE TITLE
Many keys are wrong/improper in SQL code

### ISSUE THREAD

**Issue by a13karsi** [HGustavs/LenaSYS#545]
Many tables are declared with auto incrementing primary keys. For example the table 'user' is declared with an auto incrementing primary key 'uid' while the 'username' field is declared to be 'UNIQUE'. 

It would be better to make 'username' the primary key so that it is possible to reference the primary key of that table with a foreign key properly.

This problem is prevalent throughout the database code and warrants a total re-design of tables and relations.

**Comment by HGustavs** [comment]
Nope.

**Comment by a97marbr** [comment]
Explain. Why?

**Comment by HGustavs** [comment]
We are given a system that is considered complete. No old things are allowed to change unless non-working. New features/columns/documentation can be added, but any working existing code should largely remain unchanged.

Apart from the philosophical issues, this is particularly important since any such changes may result in consequences for the other subprojects.

**Comment by a13karsi** [comment]
Let's look at an example, we have the following table 'user',
```sql
/* user contains the users of the system and related  information */
CREATE TABLE user (
    uid INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(80) NOT NULL UNIQUE,
    firstname VARCHAR(50) NULL,
    lastname VARCHAR(50) NULL,
    ssn VARCHAR(20) NULL,
    password VARCHAR(225) NOT NULL,
    lastupdated TIMESTAMP,
    addedtime TIMESTAMP,
    lastvisit TIMESTAMP,
    newpassword TINYINT(1) NULL,
    creator INT UNSIGNED NULL,
    superuser TINYINT(1) NULL,
    PRIMARY KEY (uid)
)  CHARACTER SET utf8 COLLATE utf8_unicode_ci;
```
There is no reason that we should use the attribute 'uid' as a primary key in this case and simply make the attribute 'username' unique. 'username', in this case, should be the primary key so that foreign key references to the 'user' table can directly reference the user's username and not an arbitrary number associated with the user tuple. I'd consider this improper and even wrong in most cases.

The phrase "If it's not broken why fix it" is a dangerous reasoning here, the SQL code was even in a broken condition when we first looked at it this morning. This is especially augmented by the fact that there doesn't seem to exist documentation or even design specs for the database, and the SQL code itself is sparsely commented. 

So the possibility of doing a possible re-design and re-implementation of the database that would strive to maintain most of the connections to the system is off the table?

**Comment by HGustavs** [comment]
Off the table.

The database is as is.

Many of the identifiers are numbers so that data does not leak. If data escapes the system, neither the login name nor password is compromised even if data with the user id leaks. Knowing user id does not help an attacker to guess passwords or login informaiton.

**Comment by HGustavs** [comment]
We can add tables or add columns but change of existing things is off the table unless the change is local i.e. only affects a limited amount of code... especially if that code is broken. This case is at odds with this rule as it is a very basic function, deep in the system.

**Comment by HGustavs** [comment]
I however do agree that unique identifiers that are random militates even better against guessing, so a better solution would be a completely random identifier... now an attacker can start with 1 and begin to guess.... which is worse than guessing a completely random sequence of numbers.

But... as I said, we only change things with minimal side effects and only if broken, so we leave this particular general issue as is.

**Comment by a13karsi** [comment]
Alright, got it.

I don't however agree that doing the trade-off design quality vs. security is viable at the lowest design level on a database.
