### ISSUE TITLE
Bugs with unordered list in markdown

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5460]
The unordered lists last item behaves strangely if the list is the last part of the document. 

**When there are two items in the list:**
<img width="632" alt="skarmavbild 2018-05-22 kl 09 00 11" src="https://user-images.githubusercontent.com/37794632/40347264-f23e47fa-5d9f-11e8-812a-435aa177d020.png">

**When there are three or more items in the list:**
<img width="648" alt="skarmavbild 2018-05-22 kl 09 00 01" src="https://user-images.githubusercontent.com/37794632/40347265-f25c81d4-5d9f-11e8-98b6-9ef0518a2d24.png">

**Comment by HGustavs** [comment]
Seems to be related to the newish issue #7775

**Comment by a16vikva** [comment]
Closing this and #7775 since they are already working, look the screen shot in #7775. The issue with number 3 should also be resolved already, #7828
