### ISSUE TITLE
Ordered lists don't exist in markdown

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5462]
For now, it's only possible to use unordered lists in markdown. If you start to write with numbers, the list will still appear as an unordered list in the preview. 

![33107366_10209717392090814_5761090370020573184_n](https://user-images.githubusercontent.com/37794632/40347516-e5e8edf6-5da0-11e8-9aec-4193e3e03247.png)

**Comment by HGustavs** [comment]
Try to make a numbered list and see if it works.

Dont forget to test both php and js markdown to see if there is a problem

also, look at code an see if it is there.
