### ISSUE TITLE
DuggaED: Fix the styling on the variant view

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5464]
At the moment the variant view dosn't have a good styling and the idea was to fix it.

<img width="1424" alt="skarmavbild 2018-05-22 kl 9 37 56 fm" src="https://user-images.githubusercontent.com/37795608/40348444-07ab4076-5da4-11e8-869e-352f1796d3b9.png">

**Comment by b16linra** [comment]
This was solved in pull request 5484. This issue will be closed.
