### ISSUE TITLE
Accessed and resulted - Styling bug

### ISSUE THREAD

**Issue by c16matan** [HGustavs/LenaSYS#5466]
When moving your mouse horizontally along the first user row there are usually parts of the top border that disappear, just like on the image below. This needs to be fixed.
![image](https://user-images.githubusercontent.com/37793866/40349771-e5430bb4-5da7-11e8-8719-849979e94a8c.png)

**Comment by b16johso** [comment]
Where do I find this table?

**Comment by b16johso** [comment]
This seems to no longer be an issue?

**Comment by a17andby** [comment]
Removing our label (gruppC2019) after a conversation with GruppB2019.

**Comment by a17pongo** [comment]
Closing this issue because the bug seems to be fixed.
