### ISSUE TITLE
ResultEd & AccessEd - cell highlighting bug

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5467]
There seems to be a slight bug with the cell highlighting. Sometimes when you hover your mouse around the table a portion the highlight border all the way to the left or right will be visible. When this occurs it seems like this border will permanently stay there.

![capture](https://user-images.githubusercontent.com/37793947/40349982-96dcce8c-5da8-11e8-8208-66f0adcc6394.PNG)

Notice how one of the "student" cells is being hovered, but the cell border to the right of "reset pw" is visible.

#5466 seems to be related to this this issue.

**Comment by b17carma** [comment]
Having problems recreating this issue, appears to be fixed?

**Comment by a17maxsj** [comment]
bump

**Comment by a17andby** [comment]
Can't recreate this issue on current week branch. I assume that this issue is fixed. Closing.
