### ISSUE TITLE
LoginBox - Security question bug

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5473]
Follow these steps to replicate:

Open the loginbox -> Click "forgot password" -> Enter a username (at the time of writing this issue a99kerbe works) -> Close the window by either hitting "esc" on your keyboard or clicking the cross -> Open up the loginbox again

Doing this should open up the loginbox, instead it opens up the "security question window" again.

**Comment by c16matan** [comment]
Merged. Closing.
