### ISSUE TITLE
Loginbox - functionality bug

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5478]
Follow these steps to replicate: 

Open the loginbox -> Click "forgot password" -> Enter a username (at the time of writing this issue a99kerbe works) -> Click "Back to login" -> Click "forgot password.

Doing this will return you to the security question window (step 3). It should instead take you to "reset password" (step 2).

**Comment by c16matan** [comment]
Could not be reproduced (even by the author). Closing.
