### ISSUE TITLE
ResultEd & AccessEd - Invisible border between cells

### ISSUE THREAD

**Issue by a16jonis** [HGustavs/LenaSYS#5481]
The space in between the cells (Where the invisible border is) is split right in the middle of the cells. This looks quite strange when the space in between cells are of different colour. 

![capture](https://user-images.githubusercontent.com/37793947/40354338-e2adb2bc-5db3-11e8-8688-77e70ed4688d.PNG)

This looks especially strange in mini-mode in ResultEd.

**Comment by f16linli** [comment]
I will also fix so that the header does not take up double its space if sorted and the date should not wrap, it should be on a single line.
![image](https://user-images.githubusercontent.com/37804205/40411690-666f27c6-5e71-11e8-8742-4bc98c6e485e.png)

**Comment by d16linja** [comment]
Solved!
