### ISSUE TITLE
DuggaED: Consistent code in variants view

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5493]
Enable the same type of closing mechanism for the preview window as there are for all the other windows. Meaning that the "closeWindows()" function should be used and it should be possible to close the window by clicking outside of it.

**Comment by b16karhe** [comment]
**_The same type of closing mekanisms should be implemented for the preview window as there are for all the other windows. Meaning that the "closeWindows()" function should be used and it should be possible to close the window by clicking outside of it._**

**Comment by b16linra** [comment]
Solved in pull request 5520. This issue will be closed.
