### ISSUE TITLE
loginButton change question

### ISSUE THREAD

**Issue by b13danso** [HGustavs/LenaSYS#551]
Should we change the login box to something thats more clear to the user instead of having an icon representing a user with red/green background. It would be easier for the user to understand that the login button/logout button is placed on the top-right corner if the icon represented something like a door with an arrow pointing in(login) and a door with arrow pointing out(logout)?

**Comment by HGustavs** [comment]
Im thinking that the icon is kind of nice, and a bit different style-wise (a good thing?).
Im also thinking that we want very clean and simple iconography. Make me a door icon, and we can compare it to the current one and have a "vote". 

What I am thinking is that perhaps, we can remove the yellow link which is kind of pointless, and replace it with something like an on-hover tooltip.

**Comment by b13danso** [comment]
Icon idea approved by HGustavs, currently working on converting the created icon to SVG.

**Comment by b13danso** [comment]
issue #618 is conntected to this issue.

**Comment by b13danso** [comment]
Completed, pull request #620 created,

**Comment by b13danso** [comment]
Fixed.
