### ISSUE TITLE
Wrong heading in "no item selected" popup when deleting

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5511]
When you are trying to delete objects without selecting anything, the same popup as "no item selected" for appearance changes is shown. The content should be the same, but not the heading. 

<img width="258" alt="skarmavbild 2018-05-22 kl 16 41 26" src="https://user-images.githubusercontent.com/37794632/40369745-009ec18c-5ddf-11e8-988f-825bcc42f4dc.png">

**Comment by a16hamsa** [comment]
#5590

**Comment by a17alfcl** [comment]
Unclear instructions about what the new heading should be, and in what other situation the heading should remain the same. Cannot compare the cases as we have only found one case, which is when no object is marked when deleting. What is "appearance changes"?

**Comment by a17okaoz** [comment]
Issue #5667. The issue is fixed. The heading in the pop-up box is fixed like the description wants is to be
