### ISSUE TITLE
SectionED: Change the search placeholder in variant view

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5532]
At the moment the search placeholder in the variant view says "Searchterm...", we want to change that to just "Search..." in order to keep content consistent across the website.

<img width="645" alt="skarmavbild 2018-05-23 kl 10 26 35 fm" src="https://user-images.githubusercontent.com/37795608/40412537-dc1823f4-5e73-11e8-81b9-e99a4e537f15.png">

**Comment by a16linas** [comment]
The placeholder now says search instead of searchterm
