### ISSUE TITLE
SectionED: Hamburger menu shows before a nav button is hidden

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5538]
At the moment the hamburger menu shows before a nav button is hidden. This problem happened when we deleted the contribution button from the nav list.

<img width="772" alt="skarmavbild 2018-05-23 kl 10 44 08 fm" src="https://user-images.githubusercontent.com/37795608/40413510-451f3d54-5e76-11e8-889a-b9a3a7a57558.png">

**Comment by b16linra** [comment]
This was solved in pull request 5540. This issue will be closed.
