### ISSUE TITLE
Add hover on the swimlane canvas

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5541]
The idea was to add a hover functionality on each dugga that is displayed inside the swimlane canvas, so that it could highlight the dugga that the entry represents in the section editor.

**Comment by a16thegu** [comment]
How to create a hover in canvas: [Hover funtionality](http://techfunda.com/howto/1084/canvas-hover)

Mock-up:

**Comment by a17pongo** [comment]
@HGustavs 
Is this still a requested feature?

**Comment by b17nicsv** [comment]
@HGustavs Bump

**Comment by HGustavs** [comment]
I dont think it works this way any longer... so .. unclear.

**Comment by HGustavs** [comment]
I dont think it is even a canvas.

**Comment by b17nicsv** [comment]
This is an old issue and it doesn't look like this anymore. Closing this.
