### ISSUE TITLE
File names and extensions get destroyed when the name is too long

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5543]
If the file name is too long, the file name doesn't get an extension. If the file name is more than 128 characters, the name disappears and the extension gets the file name instead. There should be a limit for how long the file name can be. 

![longfilename](https://user-images.githubusercontent.com/37794632/40414223-f7183cf8-5e77-11e8-9178-60451c041888.png)

**Comment by c17johha** [comment]
Imo filename should not be limited cause of UI. What file needs a name of >128 chars? I don't think it's motivated to implement this safety.
