### ISSUE TITLE
SectionED: Remove the swimlane icon

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5545]
Since we have added a new swimlane in the section editor the old swimlane link and icon need to be removed from the sectionED files.

<img width="1440" alt="skarmavbild 2018-05-23 kl 11 25 17 fm" src="https://user-images.githubusercontent.com/37795608/40415810-0cc4baa0-5e7c-11e8-8e0d-40fea5ad2d33.png">

**Comment by b16linra** [comment]
This change was made in pull request 5562. This issue will be closed.
