### ISSUE TITLE
SectionED: Make statistics text unselectable

### ISSUE THREAD

**Issue by a16konka** [HGustavs/LenaSYS#5574]
At the moment you can select the statistics text on the statistics tab. This should not be possible since the tab is meant to be a button and not a text.

<img width="543" alt="skarmavbild 2018-05-24 kl 1 24 11 em" src="https://user-images.githubusercontent.com/37795608/40482708-f2b12286-5f55-11e8-9de8-b7e58810e4d8.png">

**Comment by b16linra** [comment]
This change was made in pull request 5575. This issue will be closed.
