### ISSUE TITLE
Can't sort a table in moblie view 

### ISSUE THREAD

**Issue by a16juleh** [HGustavs/LenaSYS#5583]
For now, it's not possible to sort in the table when the mobile view is used except with the radio buttons for file kind. In the desktop view the sorting is done by pressing the table header, but there is no typical table header in the mobile view. It would be good if there were some kind of menu where one can choose how to sort the table.

<img width="392" alt="skarmavbild 2018-05-25 kl 09 17 51" src="https://user-images.githubusercontent.com/37794632/40531381-884f95e2-5ffc-11e8-9bcb-b810a5055411.png">

**Comment by c17johha** [comment]
Able to sort by pressing table header on my phone with chrome.
