### ISSUE TITLE
Consistency between FABs

### ISSUE THREAD

**Issue by a16hamsa** [HGustavs/LenaSYS#5595]
The FAB in DuggaEd have another style than the other FABs and the FAB in CourseEd doesn't have the same hover-effect as the other FABs in the project. This should be fixed so all the FABs are consistent in style across the project.

**Comment by a16hamsa** [comment]
#5596 All FABs now look and behave the same on all pages.

**Comment by a17fellu** [comment]
Made the FAB on courseed consistent with the others

**Comment by a17fellu** [comment]
Branch with the change: https://github.com/HGustavs/LenaSYS/tree/GruppC2019%235595

Changes to FAB (Button with + sign) on courseed.php

- Removed the zoom effect on hover and the excessive drop shadow is changed to fit the others

- Made the FAB get brighter on hover just like the one on the other pages
