### ISSUE TITLE
styling fix for sorting and filtering in navbar; resultEd and AccessEd

### ISSUE THREAD

**Issue by a16hamsa** [HGustavs/LenaSYS#5597]
The dropdown-menus which appear when you hover over the icons at the top of the pages almost covers the icon when active.

**Comment by a16hamsa** [comment]
#5598 Moved the menu so that it doesn't cover the button that activates it. works in both ResultEd and AccessEd.

**Comment by a17adajo** [comment]
@HGustavs Me and @a16lisri  have started working on this issue.

We have been unable to locate a dropdown on the current version wich behaves like the description. Can you provide us with a screenshot or something that shows the unwanted behavior?

**Comment by a17maxsj** [comment]
@HGustavs  bump, is this still an issue?

**Comment by a17maxsj** [comment]
Seems to be fixed. Closing
