### ISSUE TITLE
SectionEd: Change where GradeSys is an option

### ISSUE THREAD

**Issue by a15magkn** [HGustavs/LenaSYS#5606]
Currently you can choose a grading system on things where it does not make sense, such as headers or quotes. This seems strange and should be changed.

**Comment by a17anter** [comment]
Now Grade system will only show for the types "Test" and "Moment"

![Screenshot 1](https://user-images.githubusercontent.com/49204317/55726943-37493800-5a11-11e9-86ef-7645dbf79c0b.PNG)
![Screenshot 2](https://user-images.githubusercontent.com/49204317/55726944-37e1ce80-5a11-11e9-9d36-edaebfebb3e6.PNG)
