### ISSUE TITLE
Creation of the first dugga in a course

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#5608]
Error inserting variant (row 235) 0 row(s) were inserted. Error code: Cannot add or update a child row: a foreign key constraint fails (`imperiouz2`.`useranswer`, CONSTRAINT `fk_useranswer_joins_listentries` FOREIGN KEY (`moment`) REFERENCES `listentries` (`lid`))

**Comment by b17timjo** [comment]
There are no references to "imperiouz2" in the project.
It seems related to the hard-coded database "imperious" - part of the duplicate SQL bug from #5657 and others - and is likely no longer relevant, and will almost certainly be resolved by fixing those.

**Comment by a18kaswi** [comment]
Issue that Tim referred to got closed, in his opinion this will be fixed. Moving on to more urgent stuff.
