### ISSUE TITLE
Column based filters in marking view

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5612]
Some kind of simple column based filter e.g. "Participated Seminar 1" "Submitted Course Part 1" "New Result Course Part 2"

**Comment by a17ludca** [comment]
How does one get to this "marking"-view from the courseed-page? A more elaborated description of the issue is also welcome.

**Comment by a17pongo** [comment]
@HGustavs
Is this an old issue that is already fixed?

**Comment by c17johha** [comment]
#5635
