### ISSUE TITLE
e-mail all students taking course

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5614]
We need a function for e-mailing all students in a course by generating a compose email in the same way as we do reset password but with many recipients

**Comment by HGustavs** [comment]
variants:

* Mail all students on a specific course version (e.g. all registered to latest version)
* Mail all students in all course versions
* Mail all students who have not passed the course

**Comment by HGustavs** [comment]
This is very important and considered very high priority.

**Comment by HGustavs** [comment]
email students that have not had a result in specific part of the course e.g. home exam.

...

There is a dialog for exporting to csv at top of screen, this should also work as source for email. (there is other issue on this?)

**Comment by a17anter** [comment]
There is now a "mail" button which opens the default mail application and fills in all e-mail adresses for the participating students with a subject.

Participating students are filtered by current URL keys "courseid" and "coursevers".

**Comment by HGustavs** [comment]
All visible in result view
