### ISSUE TITLE
Reset password template

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5615]
It would be nice to have the posibility of  having some kind of a template for sending emails to the list of freshly created accounts.

For instance we would write 

"For course xyz nameofcomuter.org your password is $newpassword"

**Comment by b17nicsv** [comment]
So the steps would be;

- [Create button in AccessEd]

- [Filter newly created accounts]

- [Write template and ensure randomness in password generation]

- [At the onclick of the button to send E-Mails, the template and password is sent to the group of newly created accounts]  

Correct me if I'm wrong.

**Comment by a17robes** [comment]
Atm you can go into accessed and click the "Reset password" button, and an email with the new password gets generated and sent to the email address of the user.

![image](https://user-images.githubusercontent.com/38004435/58333095-fc725680-7e3c-11e9-88d1-b14563182b8e.png)

Just to clearify, do you want to be able to send this kind of email to each and/or multiple "freshly created" account in a template? 

In that case, where would you want the button for this Reset password template? in accessed?

@HGustavs

**Comment by c20adael** [comment]
I'm closing this issue since we are not allowed to work with emails.
