### ISSUE TITLE
Sorting and filtering access list

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5616]
We want to be able to sort the access list on course-registration term

Also we want a filter for filtering on term

**Comment by HGustavs** [comment]
Related to #5635

**Comment by a17pongo** [comment]
@a17adasy @a17ludca 
is the boolean search solution able to be more generic and implemented into SorttableTable?

**Comment by a17adasy** [comment]
If i remeber correctly some tables have coded columnnames (lid:2003 etc) while other have proper names, so dont really know how to make it more generic and have it in sortabletTable, maybe @a17oscno has an idea.

@HGustavs

**Comment by b17nicsv** [comment]
Closing this issue. It is already solved.
