### ISSUE TITLE
Section editor styling

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5619]
* We want a subtle difference between examples and other links so students can see the kind of link without navigating to that link. 
* We also want a subtle difference between internal and external (to other non-university pages) links

Preferrably very subtle, not using icons or other exceedingly overt notations.

**Comment by c17julka** [comment]
![image](https://user-images.githubusercontent.com/37792321/56132177-9f57cb00-5f89-11e9-81d5-e58a05ad8e98.png) ![image](https://user-images.githubusercontent.com/37792321/56132216-b5fe2200-5f89-11e9-8fbc-c005c29ed2d6.png)
Fixed and merged. Above pics shows change in text color when hovering over certain links (example links, external links and internal links. Pics show example link + internal link).
