### ISSUE TITLE
Marking view of assignment does not show name of student

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5622]
Title of on-screen view showing pdf only shows placeholder title not name and id of student.

**Comment by HGustavs** [comment]
![screenshot 2019-01-25 10 39 11](https://user-images.githubusercontent.com/6978801/51737724-94c61d80-208d-11e9-9d4e-a39f83581d18.png)

In place of document preview we want more relevant information such as student data and even assignment data such as name of assignment?

**Comment by HGustavs** [comment]
This is in the resulted, view, after one has clicked the hand for marking a specific result.

**Comment by c17johha** [comment]
sub issue: #5907
