### ISSUE TITLE
Create user in accessed.php gives us 500 error

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5624]
Nothing happens as the running system does not produce output on 500.

It is probably not a database issue since database issues should give us $debug error message in alert statement.

Syntax error in php?

![screenshot 2019-02-05 10 06 35](https://user-images.githubusercontent.com/6978801/52262791-c2348600-292d-11e9-96fa-353103b7b988.png)

**Comment by a17alevu** [comment]
I dont quite understand the issue ? Am I supposed to watch over the code to see if there is any possible errors? Am i supposed to create a error handler?

**Comment by b17carma** [comment]
I'm not entirely sure what the problem is since I am able to add users with that button on my local system

**Comment by a17maxsj** [comment]
bump @HGustavs

**Comment by a17maxsj** [comment]
This seems to no longer be a feature, closing...
