### ISSUE TITLE
Uneconomical use of space in result view

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5625]
Currently the data in the result view is slightly higher than necessary.

A mockup of the problem:

![screenshot 2019-02-08 11 32 51](https://user-images.githubusercontent.com/6978801/52473472-2d809100-2b96-11e9-8359-37aaaab5d133.png)

The "null" in each student which contains something, and the times graded in the result...

this makes the whole result row one row of text too high.

I would like to add the numer of marked times as just a number enclosed in parenthesis next to the result in some place e.g. (1) or (2) or (3)

**Comment by HGustavs** [comment]
What do the null-s contain?

one is study program?

**Comment by a17amama** [comment]
Null next to studentID contains Class and the null at the bottom contains SetTeacher, should any of them be removed?

**Comment by a17pongo** [comment]
Resolved and merged with groupB branch
