### ISSUE TITLE
Self assessment tool group ranking and sorting

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5627]
Currently the self assessment tool has course-wide rankings, it would be interesting to also add group-rankings.... If a developer performs well within the group but not necessarily globally this should be visible.

So in short adding group to the sorting in the table....

**Comment by HGustavs** [comment]
Also are we using sortabletable? 

if not....

**Comment by a17poner** [comment]
@HGustavs Im currently unable to access contribution in the development environment, heard there is something about a database missing cause currently the contribution.php page is nothing but blank when I access it on my local or the dev webserver.

**Comment by a17adajo** [comment]
A test database will be provided soon by henrik

**Comment by a17poner** [comment]
merged
