### ISSUE TITLE
We need a better dugga specifically for entering time sheets.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5628]
I suggest something like the code for making surveys in surveySYS.

Page 3 in the following research paper:

http://crpit.scem.westernsydney.edu.au/confpapers/CRPITV42Clark2.pdf

**Comment by HGustavs** [comment]
Im thinking it can be used for self-reporting attendence in some way.

**Comment by a17robda** [comment]
![dagbokmock](https://user-images.githubusercontent.com/37792328/55612328-48334880-5788-11e9-987d-8ef30cbba7d2.png)

Started working on a time sheet mockup for the general idea. We would like some feedback on this simple mockup if there is anything we have forgotten. We thought about adding a preview after adding each row.

**Comment by a17poner** [comment]
Is this something we want for all text file submissions? As we understand currently, to add this we need to change in generic_dugga_file_receive.js under the "else if(type =='text')" which would change any possible text file submission in lenasys to use this type of timecheet form, if we're correct in our assessment is this how we want it to be or should we make/add a new type for it?

**Comment by a17poner** [comment]
@HGustavs in order to test this and start working with integrating our form, how do we create a diary(dagbok) in lenasys? Been trying for 30 minutes to get through the superuser ui to create something similar to whats on the live version for this course but with very poor results

**Comment by a17joaap** [comment]
@HGustavs How do you want the data to be saved? Currently there is no infrastructure that supports this tabular data, at least that I can find. Should we create a way for the system to parse this? 
![timesheet](https://user-images.githubusercontent.com/37792198/55990480-0fbfcd00-5ca8-11e9-9198-48d809a980a5.PNG)

**Comment by a17joaap** [comment]
I went ahead and created a way to save user input in a json file, this way it could be parsed and reentered to the table when the user revisits the page, if this is something we want.

**Comment by HGustavs** [comment]
I would say that we create a time sheet table in the main database somehow.

And that we connect this data to the section in the course, this way we can have more than one time sheet in a course.

**Comment by HGustavs** [comment]
Generic names... I suggest Kind or Type and Reference instead of pull request and number

**Comment by HGustavs** [comment]
Week numbers also as a sortable / searchable column

**Comment by a17joaap** [comment]
I created a new table for timesheets, with references to the course, quiz, user, and moment.
![timesheetdb](https://user-images.githubusercontent.com/37792198/56033691-615a6d00-5d25-11e9-938d-3a54ec807e5c.PNG)

Could you clarify what you mean by 'Week numbers as a sortable column'? Do you want the data from the database to populate the timesheet table when the user accesses the dugga?

**Comment by a17joaap** [comment]
Current version:
![timesheetdugga](https://user-images.githubusercontent.com/37792198/56146567-b822a980-5fa6-11e9-9a4d-404a10b7e6a2.PNG)

Instructions are editable through fileed, the type select box can be populated with whatever depending on the course id and moment. Made it as generic as I can. 

By sortable week numbers you mean in the database? @HGustavs

**Comment by a17joaap** [comment]
Fixed with #5880 and #6255

**Comment by a17maxsj** [comment]
Has been implemented! closing...
