### ISSUE TITLE
Integration of time-sheet data with progress self-assessment tool.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5629]
After having made the time sheet tool ...

I would like to integrate that data with the progress/self assessment module

**Comment by HGustavs** [comment]
Currently the time sheet is handled by feedback_dugga in the templates folder.

**Comment by HGustavs** [comment]
Passive view in sortable table for each time sheet in course.

It is better that teachers view progress here than in each time sheet dugga.

**Comment by a17poner** [comment]
Merged now, closing
