### ISSUE TITLE
Login button shows incorrectly in chrome

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#563]
The fault does not lie in CSS

**Comment by a13chrju** [comment]
https://github.com/HGustavs/LenaSYS/pull/617

**Comment by b13danso** [comment]
#549

**Comment by a13antda** [comment]
Remove " width: 60px; " from .navName in the shared css and the problem will go away!

**Comment by c13chrjo** [comment]
Issue is already present and fixed, closing.
