### ISSUE TITLE
Hiding ssn

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5630]
As a general rule we want to hide ssn numbers except for export of data.

This is due to privacy EU rules.

**Comment by a17pongo** [comment]
@HGustavs 
this seems like something that should be implemented now. 
Could you give more information on eg. where it should be hidden?

**Comment by a17alian** [comment]
I've found visible ssn in 'Results' and 'Access' and masked them out. This solution still makes it possible to sort by SSN in heading. 
<img width="374" alt="Skärmavbild 2019-04-20 kl  15 38 55" src="https://user-images.githubusercontent.com/37792256/56458193-cb0cf380-6383-11e9-8ee3-266090f1e06c.png">

<img width="212" alt="Skärmavbild 2019-04-20 kl  15 47 08" src="https://user-images.githubusercontent.com/37792256/56458194-cb0cf380-6383-11e9-8072-89fe6353cf77.png">

@HGustavs please let us know we missed pages where ssn needs to be masked
