### ISSUE TITLE
Cookies information popup

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5631]
Are we sure that the cookies pull-down works as advertised?

**Comment by HGustavs** [comment]
It should appear for all "new" users and users that have not clicked it away previously.

Status (clicked / not) should be in local storage so it is kept over time even if not logged in.

Until clicked should always appear.

If incognito mode it should also appear?

**Comment by HGustavs** [comment]
Course editor would be the best place to put this?

**Comment by b17carma** [comment]
Appears the status is already set in local storage, could already be fixed?

**Comment by a17maxsj** [comment]
Seems to be working, closing this issue for now.
