### ISSUE TITLE
Search boolean operators for results and student list

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5635]
* In the student list (for example) we want to have the boolean operators (as implemented in the file interface). e.g. Student named name:sven and term:vt19 (i do believe this is the syntax?)

* For results: Allowing us to specify things such as not completed home exam and name:sven

Other views?

**Comment by HGustavs** [comment]
Important to make this reasonably generic so this is not rewritten 3 times slightly differently.

**Comment by a17ludca** [comment]
Result-part of this issue does not seem worth doing, provide further motivation for this please.

**Comment by c17johha** [comment]
problem: its hard to find outline students. esepcially courses thas has many students. Now we can only search for key words. We want to be able to have multiple words in searching. smart searching. 
There is a similar method in fileed.php.

**Comment by c17johha** [comment]
example code can be found under fileed,js.
Henrik recommends trying to copy-pase and reuse this code and adapt it.

**Comment by a17ludca** [comment]
Im not sure how this is going to be useful, are you asking for column-removal if not matching the search (example below). If so, isn't this redudant function since the filter for columns already exists.  
![image](https://user-images.githubusercontent.com/37799006/56122264-50eb0200-5f72-11e9-9775-780610f28bed.png)

**Comment by HGustavs** [comment]
Row filter based on values in columns

**Comment by HGustavs** [comment]
An example workflow: something like

markU:Biträkningsdugga1 && markG:Biträkningsdugga 2  

and then pressing email button to email those students

**Comment by HGustavs** [comment]
or even as a stretch goal

markG:Bitr*2 && markU:Bitr*1

**Comment by HGustavs** [comment]
Work flow, reporting on any marks entered into the system after some date.

Date operator would be awesome

date:2019-01-01

would filter any marks or handins made after that date.
