### ISSUE TITLE
Property dialog in Diagram

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5638]
![Screenshot 2019-04-03 09 25 09](https://user-images.githubusercontent.com/6978801/55460504-6f581180-55f2-11e9-9f35-fc9e73d1cf2a.png)

Properties dialog is built by code?

It should be a static dialog in php file.

**Comment by HGustavs** [comment]
~~~
function globalAppearanceMenu(){
    globalAppearanceValue = 1;
    //open a menu to change appearance on all entities.
    $(".loginBox").draggable();
    var form = showMenu();
    //AJAX
    loadFormIntoElement(form,'diagram_forms.php?form=globalType');
}
~~~

**Comment by HGustavs** [comment]
diagram_forms.php

**Comment by HGustavs** [comment]
The ajax runs the following get http://localhost/LenaSYS_HT2017/DuggaSys/diagram_forms.php?form=entityType

which returns markup of a mostly static page.

The way we want this to happen is, the returned markup

~~~
Entity name: </br>
      <input onkeyup="changeObjectAppearance('entityType');" id='nametext' type='text'></br>
      Entity type: </br>
      <select onchange="changeObjectAppearance('entityType');" id='object_type'>
      <option value='Weak'>Weak</option>
      <option value='Strong' selected="true">Strong</option>
      </select></br>
      Background color:<br>
        <select onchange="changeObjectAppearance();" id='symbolColor'>
        <option value='#64B5F6'>Blue</option>
          <option value='#81C784'>Green</option>
          <option value='#e6e6e6'>Grey</option>
          <option value='#E57373'>Red</option>
          <option value='#FFF176'>Yellow</option>
          <option value='#FFB74D'>Orange</option>
          <option value='#BA68C8'>Purple</option>
          <option value='#ffffff'>White</option>
          <option value='#000000'>Black</option>
        </select><br>Font family:<br>
        <select onchange="changeObjectApp

...
~~~

should be in static form in diagram.php 

... and only be shown by javascript, after having updated the select boxes etc.

**Comment by HGustavs** [comment]
This dialog can be updated in javascript with a call to 
~~~
makeoptions(option,optionlist,valuelist)
~~~

in dugga.js for each property.

**Comment by a17jonro** [comment]
We don't really understand exactly what you're aiming for, could you please elaborate? What do you mean by static form? As the options are diffrent for each symbol.

**Comment by a18antsv** [comment]
I am thinking to create all inputs static in the diagram.php file and show and hide the inputs depending on if they are relevant to the type whose appearance should be changed.
