### ISSUE TITLE
Feature: Tutorial for setting up and running LenaSYS in Docker

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#5643]
This is a runnable draft on how the run the system in a docker container:

[LenaDocker.zip](https://github.com/HGustavs/LenaSYS/files/3043222/LenaDocker.zip)

### 1 Install Docker on your system

Windows users (need Enterprise or education edition): https://hub.docker.com/editions/community/docker-ce-desktop-windows

### 3 Open a command window in the folder containing the "Dockerfile"

Windows users can hold down shift and right click:
![image](https://user-images.githubusercontent.com/49197690/55552858-e5d23d80-56de-11e9-9bcb-5f1725ee9dde.png)

### 4 Build the image

Run: docker build -t lenasys .

### 5 Start a new container

Run: docker run -i -t --rm -p "80:80" -v ${PWD}/app:/app -v ${PWD}/mysql:/var/lib/mysql lenasys

Press "Share it"
![image](https://user-images.githubusercontent.com/49197690/55553880-af49f200-56e1-11e9-8be3-bf31ef9d8ada.png)

### 6 Install lenasys

Go to: http://127.0.0.1/LenaSYS/install/install.php
Enter "123" as password for "Enter password for MySQL user. "
![image](https://user-images.githubusercontent.com/49197690/55553144-b2dc7980-56df-11e9-835a-3b1b41b3eec6.png)

Go to next page.

Enter "admin" as MySQL root user and the password from the docker output as password.
![chrome_2019-04-04_13-44-27](https://user-images.githubusercontent.com/49197690/55553215-e3241800-56df-11e9-8ef9-005fccac1b79.png)

Go to next page
![image](https://user-images.githubusercontent.com/49197690/55553271-0c44a880-56e0-11e9-8561-31a4ae1adc86.png)

Go to next page
![image](https://user-images.githubusercontent.com/49197690/55553284-149ce380-56e0-11e9-8121-c4ecf943253f.png)

Press install!
![image](https://user-images.githubusercontent.com/49197690/55553303-1bc3f180-56e0-11e9-9fb6-b1de5d33621a.png)

Just press the green button at the bottom.
![image](https://user-images.githubusercontent.com/49197690/55553346-34340c00-56e0-11e9-82e9-ef5fd62c6601.png)

### 7 Make Changes

You can now edit the files used by the system here:  app\LenaSYS
The LenaSYS folder is a clone of the current master branch from Github.

The course page is located here: http://127.0.0.1/LenaSYS/DuggaSys/courseed.php
You can login to the system with user and password: c92cober / password

### 8 Shutdown

Press ctrl+c in the command window to shut down the system

### Other stuff

Acces phpmyadmin here: http://127.0.0.1/phpmyadmin/

Remove all Docker images: docker rmi $(docker images -q)
Remove all Docker containers: docker rm $(docker ps -a -q)

**Comment by a17andby** [comment]
Toddler/Kong

(Admin login)

**Comment by a17andby** [comment]
För er som inte har Windows 10 PRO kan använda sig av "Docker Toolbox".

**Comment by a17pongo** [comment]
https://docs.docker.com/v17.12/toolbox/toolbox_install_windows/ - installationsfil för docker toolbox

använd ip: 
http://192.168.99.100

För att komma åt eran lokala server.

**Comment by a17adajo** [comment]
If this is appreciated I suggest adding it as a wiki page

**Comment by a14oscna** [comment]
För att stänga av en aktiv process i Docker / DockerToolbox gör du såhär:
1. I terminalen skriver du: docker ps
Du får då upp en lista på alla aktiva processer. Är listan tom har du inga aktiva processer.

2. Kopiera ID:t för den process du vill stänga av (står under CONTAINER ID).

3. I terminalen skriver du: docker stop (skriv ID här)
Ex: `docker stop c90edae9005f`

**Comment by a16joare** [comment]
If you get problem with missing config.json file in DockerToolBox, one fix is to take the "default" directory from someone with a working DockerToolBox. Looks like sometimes when you install DockerToolBox some off the files needed will be missing.  My default directory was located at C:\Users\MyPC\.docker\machine\machines.
