### ISSUE TITLE
Mobile view: Deadline date cuts off

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#5644]
In mobile view, the deadline dates get cut off due to incorrectly styled media queries.
![Capture](https://user-images.githubusercontent.com/37793460/55555403-80357f80-56e5-11e9-8c84-497bb6b7261b.PNG)

**Comment by b16johso** [comment]
Removing the media query in question seems to fix it @HGustavs 

```
@media only screen and (max-width: 1085px),
only screen and (max-device-width: 1085px) {
     . . .
  .dateSize {
    width: 50px;
  }
}
```

![Capture](https://user-images.githubusercontent.com/37793460/55556309-89bfe700-56e7-11e9-8946-13582bfbec50.PNG)

**Comment by HGustavs** [comment]
This looks better?

Whats the verdict?

**Comment by b16johso** [comment]
Merged https://github.com/HGustavs/LenaSYS/pull/5684
