### ISSUE TITLE
Install script does not work on Windows

### ISSUE THREAD

**Issue by c17matjo** [HGustavs/LenaSYS#5647]
Install script assumes unix file paths and fails to check permissions on windows.

**Comment by c17matjo** [comment]
We added a windows check that handles the "C:\" part and converts backslashes to forward slashes in cdirname(). 


```
// Create a version of dirname for <PHP7 compability
    function cdirname($path, $level) {
      $prefix = '';
      if (preg_match("/^.:\\\\/", $path)) {
        $prefix = substr($path, 0, 2);
        $path = substr($path, 2);
        $path = str_replace("\\", "/", $path);
      }
      $paths = explode("/", $path);
      $r = '';
      if(count($paths) <= $level) {
        $r = '/';
      } else {
        $r = '/';
        for($i = 0; $i < count($paths) - $level; $i++) {
          if($i > 1) {
            $r .= '/';
          }
          $r .= $paths[$i];
        }
      }
      return $prefix . $r;
    };
```

[install.php](https://github.com/HGustavs/LenaSYS/files/3043932/install.zip)

**Comment by a17drama** [comment]
Could this be made dynamic so the script checks what OS it's running on?

**Comment by c17matjo** [comment]
The function should already work on both windows and unix systems. The first if statement is a kind of OS check, only it goes by the path string format (`C:\bla`, vs `/bla`). What do you mean by making it dynamic?

**Comment by a17drama** [comment]
You shouldn't have to edit the install.php manually to get it working if you switch OS. No matter what OS you use install.php should work "out of the box".
