### ISSUE TITLE
New instance should create loglena4.db if missing

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5649]
When setting up a new instance of lenasys, if the sqlite log (../log/loglena4.db) does not exist: create it, instead of silently failing to operate.

**Comment by b17timjo** [comment]
"new PDO('sqlite:../../log/loglena4.db');"
in:
lenasys/Shared/basic.php:90
lenasys/Shared/resetpw.php:16 and 63
lenasys/Shared/loginlogout.php:31

**Comment by b17timjo** [comment]
Suggestion: either the installer creates the database (possibly: `new SQLite3('<path-to>/loglena4.db')`) or each location of use takes some action.
Such actions could be checking for an existing database and silently skip attempting to use it (possibly add to some other error log), or perhaps create it (would creating it in this manner lead to data races? probably)

**Comment by a17pongo** [comment]
has this issue been resolved with a17joaap fix?

**Comment by a17joaap** [comment]
Yes!
