### ISSUE TITLE
Replace Deprecated MYSQL commands

### ISSUE THREAD

**Issue by b12alela** [HGustavs/LenaSYS#565]
Deprecated mysql commands should be updated to their newer equivalents, ex: "mysql_connect()" needs to be "mysqli_connect()". However this may require further investigation because this could involve more than just renaming some functions to the new versions.

**Comment by HGustavs** [comment]
This is a sortof-duplicate to an other issue that calls for PDO.
Much of the code uses PDO already, it is a question of identifying which parts that still use mysql...

So technically it is not a question of changing to mysqli but to PDO, which is a duplicate of issue

**Comment by HGustavs** [comment]
Solved
