### ISSUE TITLE
loglena4.db: don't set chmod 777

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5651]
Current installation instructions suggest setting full access to the log database.
Find out which users/groups actually need what access, and restrict access to a sane minimum.

**Comment by HGustavs** [comment]
This is a security issue, clearly, even though it can not be reached from the web server it can be reached from other users on the same machine or if we have a security breach on the web server.

**Comment by b17timjo** [comment]
060 is sufficient for the site (regular webservice group)
Are there other services, or can this change be applied?

**Comment by a18kaswi** [comment]
Have been communicated with other groupleaders. Will make an documentation-issue to resolve this problem permanently.
