### ISSUE TITLE
Write a wiki page about how to set up a local dev environment

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#5653]
Should contain topics on suggested IDE and how to debug PHP/javascript

**Comment by HGustavs** [comment]
Excellent idea.

**Comment by a18jenro** [comment]
@HGustavs Would a word document suffice? If so, should that guide be added to the repository? I'm thinking it should be easy for people to update in the future, so a PDF wouldn't be optimal.

**Comment by a18jenro** [comment]
Started one here: https://github.com/HGustavs/LenaSYS/wiki/Setting-up-a-local-development-environment

**Comment by a18jenro** [comment]
@HGustavs or @a97marbr Given that we have:
https://github.com/HGustavs/LenaSYS/blob/master/README.md
and
https://github.com/HGustavs/LenaSYS/wiki/Configuring-web-server-for-LenaSYS-installation
What more is needed? Besifes maybe suggesting an IDE?

**Comment by a97marbr** [comment]
Looks good ... but didn't you need enabling of sqlite and mysql modules (more?) in php.ini

Have you tried letting an uninitiated user install the system using the much improved guide?

**Comment by a18jenro** [comment]
@a97marbr I added a 10th step to the installation guide in readme, what do you think?
![untitled](https://user-images.githubusercontent.com/62876507/80095997-2cecd400-8569-11ea-968c-d247abca8018.PNG)

**Comment by a97marbr** [comment]
I like the text, but perhaps also add to prerequisites? To avoid errors in the first place?

**Comment by a18jenro** [comment]
@a97marbr I added a "Configuring PHP" part in the wiki: https://github.com/HGustavs/LenaSYS/wiki/Configuring-web-server-for-LenaSYS-installation

![untitled](https://user-images.githubusercontent.com/62876507/80181747-be118880-8605-11ea-87c0-9bd0a7492255.PNG)

Is there anything more you want for this issue?

**Comment by a97marbr** [comment]
Perhaps give example locations to where php.ini resides on different installations 
```
Ubuntu 18.04
/etc/php/php.ini

Mac OSX 10.5
...
```
Otherwise I think there has been much improvement in the installation and get started department :)
