### ISSUE TITLE
Problem with drawing lines between two squares

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#5654]
You can't draw lines between two squares. Why? Fix this.

**Works without any problem.**
* If you try to draw lines between two circles.

* If you try to draw lines between one square and one circle.

**Comment by HGustavs** [comment]
I can confirm that this is "partially" a bug ...

In an ER diagram we cannot draw between entities directly we must draw either 
* entity to attribute
* attribute to relation
* relation to entity.

We still have no clear way to draw UML relationships with the same process..
as there is no relationship symbol to draw to / from.

however we dont want to draw between uml classes directly.... we want to have some kind of an entity symbol for uml diagrams also so we can draw diagonal lines.... between specific points

**Comment by HGustavs** [comment]
![Screenshot 2019-04-05 13 26 29](https://user-images.githubusercontent.com/6978801/55624507-76c01c00-57a6-11e9-803c-41f300f79d3e.png)

This is how I mean...

When the line drawing tool the relationship anchors are shown and when not active they are not drawn at all.

**Comment by HGustavs** [comment]
This way, If we move the leftmost class down, the anchor will change to the top but the "turning point" will still be anchored to the relationship anchor.

Also, in UML we want "kinks" rather than diagonal lines.

So if we are drawing an UML diagram, diagonals use move straigth up and then straight left, rather than a diagonal line between two points.

**Comment by a17johpe** [comment]
That the original issue was a non-issue was realised during code analysis and the new comments will be forwarded to a new issue

**Comment by a17jacsv** [comment]
**Issue: https://github.com/HGustavs/LenaSYS/issues/5690** 
A issue who solved "kinks" rather than diagonal lines".
