### ISSUE TITLE
Logout button is unclear

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#5655]
Button is unclear that it is an logout button until hover. Accidental logout is a problem.

**Comment by HGustavs** [comment]
Mockup for how this can be improved?

**Comment by a17maxsj** [comment]
![New Project](https://user-images.githubusercontent.com/49199993/55624378-f1d50280-57a5-11e9-93a4-a47b788e0180.png)

Something like this? Or some other way to show the user being logged in as well as indicating it being a logout button.

**Comment by HGustavs** [comment]
That red/green mess looks horrible perhaps we can change the "man" icon to a login / logoff icon instead?

**Comment by a16joare** [comment]
Removed the hover function, added a fixed color to the button and changed the logout button color. 
When you login: ![image](https://user-images.githubusercontent.com/49194898/55805164-2adee100-5ade-11e9-9356-02a8ea435fa2.png)

When you logout: ![image](https://user-images.githubusercontent.com/49194898/55806508-a6419200-5ae0-11e9-870c-bea9f46b3853.png)

what do you think?

**Comment by a16joare** [comment]
I will close this one but look at #5812

**Comment by a17maxsj** [comment]
Needs some further work

**Comment by a17maxsj** [comment]
done.
