### ISSUE TITLE
Back button is hidden on frontpage. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#5656]
The back button on the front page on lenasys is just hidden. If you place the mouse over the back buttons place a text with "back" will appear and it is possible to click on it.

**Comment by HGustavs** [comment]
I can confirm this...

![Screenshot 2019-04-05 09 58 16](https://user-images.githubusercontent.com/6978801/55612806-60579780-5789-11e9-9111-03b0eb6e9297.png)

This is clearly a bug

**Comment by HGustavs** [comment]
This has to do with the courseed service.

**Comment by a17robes** [comment]
I removed the title of the back button altogether, but im not sure this is what you are looking for. Do you mean that I should just block/delete the button title on the frontpage or should I delete the title of the button on all pages?

**Comment by b16johso** [comment]
Solved the issue by putting an if-statement around the line of code generating the back button in navheader.php checking that the page implementing it is not the front page. This results in the back button not being generated at all on the frontpage.
https://github.com/HGustavs/LenaSYS/tree/GruppC2019W16_5656
