### ISSUE TITLE
Two locations for sql files

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5657]
There is a **_LOT_** of confusion about the sql initiation files.... there are currently two copies, one in the installation folder and one in the shared/sql folder.

I suggest that the installation script uses the latter rather than the former??.

**Comment by a17adajo** [comment]
Using init_db.sql from the shared/sql folder results in the following during install:

![image](https://user-images.githubusercontent.com/49197690/55627815-61032480-57af-11e9-8e92-85dac4aeface.png)

**Comment by b17timjo** [comment]
Subset of diff between install/sql/init_db.sql and shared/sql/init_db.sql.
![kdiff](https://user-images.githubusercontent.com/38911528/55713637-59cb5900-59f1-11e9-830b-c5a4681a35a9.png)

Shared/* appears to use a hard-coded table, and lacks at least some fields (and has different types for others). Is the file in install/* the most relevant?

**Comment by a17adajo** [comment]
Another option could be to remove all current SQL files in the repo and dump the schema from the live database.

**Comment by a17andby** [comment]
Fixed and merged.
