### ISSUE TITLE
Problem with changing stroke color

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#5658]
When you set the stroke color to a color it should be changed globally and to every new line added should have that color. But after you changed the color (of all elements already added) and add a new line it has the originally color (black). Why? Fix this.

<img width="442" alt="Skärmavbild 2019-04-05 kl  10 21 18" src="https://user-images.githubusercontent.com/37792795/55614113-98140e80-578c-11e9-8fcb-1547943e9433.png">

**Comment by HGustavs** [comment]
I think this is related to #5675 ...

If we add a properties[] array...  

This would mean that only explicitly changed colors would use anything other than the global standard.

...

Algorithm (in pseudocode)

~~~
color = global diagram color
if(properties[strokecolor] is set){
   color=properties[strokecolor]
}
draw using color
~~~

... so I think that the bug really is using the local object color even if no such color has explicitly been set.

**Comment by a17alfcl** [comment]
Already solved this.
