### ISSUE TITLE
Null value appears in result view

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#5661]
broken-down issue from:
Uneconomical use of space in result view #5625

value "null" appears in view. Taking up space.

![52473472-2d809100-2b96-11e9-8359-37aaaab5d133](https://user-images.githubusercontent.com/49199825/55617674-f218d200-5794-11e9-834d-a3e767a8ecfa.png)

**Comment by c17johha** [comment]
![pasted image 0](https://user-images.githubusercontent.com/49199825/55617827-42902f80-5795-11e9-9ca7-e0e0274f0531.png)
![pasted image 0 (1)](https://user-images.githubusercontent.com/49199825/55618206-3a84bf80-5796-11e9-852f-44e592ba83b4.png)

"null is gone"

**Comment by HGustavs** [comment]
This looks much better!

**Comment by a17pongo** [comment]
@c17johha this issue is merged and fixed.
Please close this issue.
