### ISSUE TITLE
"Times Graded: x" taking up space in result view

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#5662]
![52473472-2d809100-2b96-11e9-8359-37aaaab5d133](https://user-images.githubusercontent.com/49199825/55618435-ceef2200-5796-11e9-8b36-c40bf23eca96.png)

I would like to add the numer of marked times as just a number enclosed in parenthesis next to the result in some place e.g. (1) or (2) or (3)

**Comment by HGustavs** [comment]
Do we have a screenshot of a proposed solution? 

Question is whether the (N) number is better placed aftetr the VG or after 12:40:17

**Comment by a17alian** [comment]
<img width="977" alt="Skärmavbild 2019-04-08 kl  10 23 30" src="https://user-images.githubusercontent.com/37792256/55709420-8c248880-59e8-11e9-8887-79d2b46a4469.png">

Proposed solutions for "Times Graded". Solution 1 is the preferred approach with only a single number  and the removal of "Times Graded", but if you would rather have the "Times Graded" specified, the solution 2 is what we propose.
