### ISSUE TITLE
Remove the "templates" directory and its contents

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#5664]
It seems that a13chrju added the folder for no apperent reason in commit 9b50ec5 four years ago. Now it only serves to increase the kognativ load on new developers trying to get a grip on what every files does in the project.

**Comment by HGustavs** [comment]
I think that it should be removed.

Templates are now in another folder.

**Comment by a16joare** [comment]
Fixed?

**Comment by a17adajo** [comment]
yep, a pull is open

**Comment by a17adajo** [comment]
Pull is now merged to Group branch C. Closing issue
