### ISSUE TITLE
Problem with cardinality

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#5666]
You cant add cardinality to drawn lines. Nothing happens when you have clicked on the button "OK".

<img width="644" alt="Skärmavbild 2019-04-05 kl  12 47 06" src="https://user-images.githubusercontent.com/37792795/55622709-40cc6900-57a1-11e9-926e-be6c789c3213.png">

**Comment by HGustavs** [comment]
There is no cardinality for attributes, so far ok, but does the same happen for the line from relationship to entity?

**Comment by HGustavs** [comment]
AFAIK it does not...

![Screenshot 2019-04-05 13 31 47](https://user-images.githubusercontent.com/6978801/55624781-31e8b500-57a7-11e9-8b1c-d4f004258ea2.png)

**Comment by HGustavs** [comment]
Multiple valued attributes are denoted with a double line on the attribute symbol.

**Comment by a17jacsv** [comment]
Oh thats true. My bad. It working as it should. I consider this issue as closed.

<img width="737" alt="Skärmavbild 2019-04-05 kl  14 12 51" src="https://user-images.githubusercontent.com/37792795/55626908-1bddf300-57ad-11e9-9a2d-157b75b63251.png">
