### ISSUE TITLE
makeLogEntry() in Shared/basic.php is a stub

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5677]
Function used in:
DuggaSys/showDugga.php line 125
DuggaSys/showDuggaservice.php lines 262 and 376

**Comment by a18kaswi** [comment]
I dont know exactly what a stub is, but my ten-second googling told me that it sounds like redudant code. I will suggest we do a 1-2 day read-through of potentially redudant code/css with starting point https://github.com/HGustavs/LenaSYS/issues/1778 https://github.com/HGustavs/LenaSYS/issues/465
