### ISSUE TITLE
basic.php creates all loglena4 tables if they do not exists

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5678]
basic.php is included from all over the site, and each time it is included/loaded it will attempt to re-create all tables in the log database (loglena4.db)

**Comment by HGustavs** [comment]
Is this not included with include once?

That would solve this issue and not break anything else?

**Comment by b17timjo** [comment]
My understanding is that sqlite3 is ACID-compliant, so it is indeed not an error per se.

However, consider that the cognitive load increases: a developer reading this code may wonder if the log tables can/should be dropped occasionally. They are probably not dropped occasionally, and probably should not, but should instead be created exactly once, during setup.
In short, creating tables in this file is a case of low cohesion.
Also, a runtime file re-creating tables on nearly every page-load is wasteful, and may reset any changes introduced at setup, causing confusion.

**Comment by a18kaswi** [comment]
Tim have good experience, I think it is hard to understand for current students what he talks about. Closing since last word is on him and we dont want to disturb him.
