### ISSUE TITLE
Selection of entities while line tool is chosen

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#5679]
While the tool for drawing lines is chosen (marked with red circle in figure below) it’s not possible to select any entities (squares, circles etc.). This forces the user to chose the tool for one of the entities (marked with green circle in figure below) if the user wants to delete an entity. If a tool for an entity is chosen lines can be selected and deleted as supposed.
![Edited](https://user-images.githubusercontent.com/46029340/55627251-fb626880-57ad-11e9-96c4-a535599ded94.PNG)

**Comment by HGustavs** [comment]
Yes I also noticed that, but do we have a better suggestion for how it should work?

**Comment by a17drama** [comment]
There are different ways to solve this: 

Suggestion one: Click should select the item you click. Click and drag should set attachment point and start drawing a line.

Suggestion two: Click should select the item you click and set the first attachment point. Second click should draw the line to the other entity and attach it. This solution skips the drag part but is more confusing because it is different compared to other software like paint etc.

**Comment by a17drama** [comment]
This should also solve the problem with selection of lines. While the line tool is chosen and a line is selected it does not show it visually. If user hits delete the line is removed which means that it was selected but the selection was never shown to the user (exception is hovering over the line).
If this doesn't fix this problem make a new issue for it.

**Comment by a16jenja** [comment]
> There are different ways to solve this:
> 
> Suggestion one: Click should select the item you click. Click and drag should set attachment point and start drawing a line.
> 
> Suggestion two: Click should select the item you click and set the first attachment point. Second click should draw the line to the other entity and attach it. This solution skips the drag part but is more confusing because it is different compared to other software like paint etc.

This seems to still be a problem, and I agree with implementing suggestion one. Since it makes it easier for the user and removes the unnecessary move to disable the line selection before selecting an object. This seems to work right now when in other create modes, so it would be good if it was applied to the line selection mode as well.

**Comment by a18kaswi** [comment]
https://github.com/HGustavs/LenaSYS/pull/7891 <- comments on try to solution
