### ISSUE TITLE
Crash Bug in Code Viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#568]
There is a PHP crash bug when the project is started from scratch.
This bug was traced to reading directories that do not exist, in that case the code would iterate indefinitely.

Rather than fixing it by creating the directories in the repository, a better idea is to add fileexists to check that the directory exists beforehand.

**Comment by HGustavs** [comment]
If this issue has been confirmed as fixed, we close the issue.

**Comment by a13erisc** [comment]
This has been implemented for a while, so I'm closing this issue.
