### ISSUE TITLE
Final button on install page will redirect to "https://duggasys/courseed.php"

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5680]
The button is part of a form:
`<form action="//DuggaSys/courseed.php">`
redirects to "https://duggasys/courseed.php"

Fix:
`<form action="/DuggaSys/courseed.php">`
which will redirect to 
`https://<site-goes-here>/duggasys/courseed.php`
 and work properly

**Comment by HGustavs** [comment]
This seems like it would work much bettter.

**Comment by a17robda** [comment]
![Annotation 2019-04-08 131012](https://user-images.githubusercontent.com/37792328/55719913-b3d31b00-59ff-11e9-8592-f0bc31a65785.png)

This seems fixed around row 803 in install.php

**Comment by b17timjo** [comment]
I disagree:
![5680_detail](https://user-images.githubusercontent.com/38911528/55721156-e6cade00-5a02-11e9-8dfe-b5549fc75c38.png)

On firefox, this will cause a redirect to an offsite-page.

**Comment by a17robda** [comment]
I will take a closer look at this.

**Comment by a17maxsj** [comment]
Any news on this issue?

**Comment by a17robda** [comment]
Removing the first slash in the instance of putting the LenaSYS files directly into the folder without a subfolder (Which causes the issue) seems to crash LenaSYS upon pressing the last button for some reason.
