### ISSUE TITLE
Many error messages could use a space for clarity

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5683]
Typical error strings lack a space before the content message.

Fictional example:
`$debug="Error reading thing".$error[2];`
if `$error[2]` is "Table does not exist" the error string would read:
`"Error reading thingTable does not exist"`
which might lead one to look for "thingTable".

**Comment by HGustavs** [comment]
I would add a backslash n ... \n rather than a space

**Comment by HGustavs** [comment]
Related to #5691 ... we could also present the error message in a much friendlier way if we work around the alert statement... so in reality a better solution could be a hybrid of both issues.

**Comment by b16johso** [comment]
I added line breaks to all error messages I could find that lack spaces like in the above example. Should be more readable now https://github.com/HGustavs/LenaSYS/tree/GruppC2019%235683

**Comment by a17maxsj** [comment]
This has been merged.
