### ISSUE TITLE
Assign key numbers to variables for increased readability

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5685]
diagram.js
<img width="323" alt="keyNumbers" src="https://user-images.githubusercontent.com/49199690/55629848-834b7100-57b4-11e9-8ea0-564e09d8c339.PNG">
Not clear what key each number represents, should assign the key numbers to variables to increase the readability of the code.

**Comment by HGustavs** [comment]
it is crucial that this is declared in the same file, otherwise we are breaking the "no refactoring" clause...

I also recommend using const

**Comment by a17okaoz** [comment]
I have found out what the key values are. Now I´m going to change them to variables

**Comment by a17okaoz** [comment]
Issue #5685 Fixed. I have written a comment about each key variable about which key it is and its keyCode

**Comment by a17okaoz** [comment]
Is it ok for me to change the variables for each key? I know that I will be break the no refactoring rule but if I do that it will increase the readability
