### ISSUE TITLE
Objects gets stacked on top of each other when aligning

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#5686]
File: diagram.js

![Capture](https://user-images.githubusercontent.com/37792271/55631531-8d6f6e80-57b8-11e9-84b6-1ba7b2ff1d92.PNG)

Objects gets stacked on top of each other when aligning top/bottom/right/left/vertical/horizontal.

**Comment by HGustavs** [comment]
Are we talking about align or distribute?

In the case of horizontal alignment, as it seems to be above, I would imagine that the symbols should move horizontally, to the average of all of the selected objects. If they are placed at those same vertical coordinates as before the horizontal centering, it seems to be working correctly.

Vertical distribution is the sorting of symbols vertically and the re-distribution depending on the share of each symbols vertical height compared to the total height.

**Comment by a17celal** [comment]
> Are we talking about align or distribute?
> 
> In the case of horizontal alignment, as it seems to be above, I would imagine that the symbols should move horizontally, to the average of all of the selected objects. If they are placed at those same vertical coordinates as before the horizontal centering, it seems to be working correctly.
> 
> Vertical distribution is the sorting of symbols vertically and the re-distribution depending on the share of each symbols vertical height compared to the total height.

Align. I just assumed that the objects should not be stacked on top of each other. Instead I thought they should appear next to each other. See the picture below for what I mean.
It was hard to understand the purpose of the alignment functionality, there were no comments in the code.


![Capture2](https://user-images.githubusercontent.com/37792271/55706239-fcc7a700-59e0-11e9-90ac-bb8384030c80.PNG)

**Comment by HGustavs** [comment]
To me it seems like correct behavior if we assume that he resulting diagram is from a set of attributes with differing x-coordinates and that each object retains its y-coordinate from before we re-alined the elements.

**Comment by a17alfcl** [comment]
> To me it seems like correct behavior if we assume that he resulting diagram is from a set of attributes with differing x-coordinates and that each object retains its y-coordinate from before we re-alined the elements.

So should we proceed with this issue or is it good as it is? I cannot tell wether you would like the objects to overlap or not.
