### ISSUE TITLE
The mysql tables use "utf8" not "utf8mb4"

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5688]
Many tables use "character set utf8": this is a broken encoding in mysql, and utf8mb4 should be used instead.
Specifically, mysql "utf8" only supports 3-byte sequences, as opposed to the up to 4 bytes defined by the standard.

**Comment by HGustavs** [comment]
Any running systems can probably not be retroactively patched, but since this is not a "breaking" refactoring, I feel that it is safe to fix this in the SQL files, as any running system is unaffected since the running system wont re-run the create tables and the rest if the code is unaffected.

**Comment by HGustavs** [comment]
short version: go ahead and patch the sql, but make sure that the RIGHT sql is patched, since there used to be two conflicting ones...

**Comment by b17timjo** [comment]
The duplicate sql inits have not been resolved at the time of writing, this issue should be held back until #5641 and #5650 (and any other related issues) have been resolved.

**Comment by a17adajo** [comment]
It should be possible to correct a running system according to:
https://dev.mysql.com/doc/refman/8.0/en/charset-table.html

**Comment by a17andby** [comment]
Fixed and merged. Closing.
