### ISSUE TITLE
Error pages, and use of .htaccess

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5689]
Error pages (/errorpages/403.php and 404.php) are referenced only by /.htaccess and there is no documentation for this; they are easily missed if the site is not configured to allow such overrides.
And as the apache project states:
> You should avoid using .htaccess files completely if you have access to httpd main server config file.
 (https://httpd.apache.org/docs/current/howto/htaccess.html, 2019-04-08)

(.htaccess is also apache-specific)

**Comment by HGustavs** [comment]
The advantage is that it will work either way, also, the config-version is not stored together with the code.

We are fine with assuming that it only works with apache. And if the person running the system has access to the config they can add the override and disable the local .htaccess

**Comment by b17timjo** [comment]
Certainly, from a functionality perspective it doesn't matter which error pages are shown, but if they are intended for use they should be mentioned in some documentation/wiki and otherwise they should probably be removed to reduce the number of unused files cluttering the repo.

**Comment by a18kaswi** [comment]
Tim flexing his skill or smthng, customer says they are fine with what they have, CLOSING.
