### ISSUE TITLE
Redirecting alert

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5691]
Currently the $debug error messages use "alert()" to display error messages.

This may be considered a problem for security reasons on non-development systems.

We would like for the alert function to be over-ridden and also adding checking if the current user is a teacher and if so, displaying this message using normal alert, but if not, suppressing the alert.

~~~
(function(proxied) {
  window.alert = function() {
    // do something here
    return proxied.apply(this, arguments);
  };
})(window.alert);
~~~

**Comment by a17maxsj** [comment]
Merged and done, closing...

**Comment by a17robhe** [comment]
@HGustavs It seems like this issue isn't solved? The code in the initial comment just seems to have been pasted in?
