### ISSUE TITLE
Potentially unused files

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5692]
The following js/css/php/html files are not referenced by any other file (of those same types) on the site, check if they are still relevant (this list excludes /errorpages/*.php, which are referenced only by /.htaccess):
* /DuggaSys/filereceive_preview.php
* /DuggaSys/templates/3d-dugga.html
* /DuggaSys/templates/3d-dugga.js
* /DuggaSys/templates/bit-dugga.html
* /DuggaSys/templates/bit-dugga.js
* /DuggaSys/templates/boxmodell.html
* /DuggaSys/templates/boxmodell.js
* /DuggaSys/templates/clipping_masking_dugga.html
* /DuggaSys/templates/clipping_masking_dugga.js
* /DuggaSys/templates/color-dugga.html
* /DuggaSys/templates/color-dugga.js
* /DuggaSys/templates/curve-dugga.html
* /DuggaSys/templates/curve-dugga.js
* /DuggaSys/templates/default.js
* /DuggaSys/templates/dugga1.html
* /DuggaSys/templates/dugga1.js
* /DuggaSys/templates/dugga2.html
* /DuggaSys/templates/dugga2.js
* /DuggaSys/templates/dugga3.html
* /DuggaSys/templates/dugga3.js
* /DuggaSys/templates/dugga4.html
* /DuggaSys/templates/dugga4.js
* /DuggaSys/templates/dugga5.html
* /DuggaSys/templates/dugga5.js
* /DuggaSys/templates/dugga6.html
* /DuggaSys/templates/exampledugga.js
* /DuggaSys/templates/exampledugga1.js
* /DuggaSys/templates/exampledugga2.js
* /DuggaSys/templates/exampledugga3.js
* /DuggaSys/templates/exampledugga4.js
* /DuggaSys/templates/exampledugga5.js
* /DuggaSys/templates/exampledugga6.js
* /DuggaSys/templates/exampledugga7.js
* /DuggaSys/templates/feedback_dugga.html
* /DuggaSys/templates/feedback_dugga.js
* /DuggaSys/templates/generic_dugga_file_receive.html
* /DuggaSys/templates/generic_dugga_file_receive.js
* /DuggaSys/templates/html_css_dugga.html
* /DuggaSys/templates/html_css_dugga.js
* /DuggaSys/templates/html_css_dugga_light.html
* /DuggaSys/templates/html_css_dugga_light.js
* /DuggaSys/templates/kryss.html
* /DuggaSys/templates/kryss.js
* /DuggaSys/templates/placeholder_dugga.html
* /DuggaSys/templates/placeholder_dugga.js
* /DuggaSys/templates/shapes-dugga.html
* /DuggaSys/templates/shapes-dugga.js
* /DuggaSys/templates/transforms-dugga.html
* /DuggaSys/templates/transforms-dugga.js
* /DuggaSys/templates/XMLAPI_report1.html
* /DuggaSys/templates/XMLAPI_report1_file_receive.js
* /DuggaSys/testDugga.php
* /Shared/BenchmarkLogging/index.html
* /Shared/BenchmarkLogging/parseagents.php
* /Shared/coursesyspw_place_two_levels_below.php
* /Shared/css/blackTheme.css
* /Shared/css/blank.css
* /Shared/css/colorblind.css
* /Shared/css/jquery.datetimepicker.css
* /Shared/icons/animation.html
* /Shared/SortableTableLibrary/fixedtest.html
* /Shared/SortableTableLibrary/sortableTableDemo.html
* /Shared/SortableTableLibrary/sortableTableDemo_columnfilter.html
* /Shared/SortableTableLibrary/sortableTableDemo_edit.html
* /Shared/SortableTableLibrary/sortableTableDemo_highlight.html
* /Shared/SortableTableLibrary/sortableTableDemo_rowfilter.html
* /Shared/SortableTableLibrary/sortableTableDemo_simplest.html
* /Shared/SortableTableLibrary/sortableTableDemo_simplest_w_magich.html
* /Shared/SortableTableLibrary/sortableTableDemo_sortadvanced.html
* /Shared/SortableTableLibrary/sortableTableDemo_sortsimple.html
* /Shared/SortableTableLibrary/sortableTableDemoDB.html

**Comment by HGustavs** [comment]
All the dugga-s are referenced using a test.
So in this case there seems to be no test in the test data that makes use of that template.

![Screenshot 2019-04-08 10 13 33](https://user-images.githubusercontent.com/6978801/55708820-2be11700-59e7-11e9-98af-eddc33b96345.png)

In the case from the screenshot, we made use of the feedback_dugga and generic_file_dugga templates ...

so for all of the dugga-s except possibly from exampledugga1-7 I would assume that those files are OK, and the bug is that we have not supplied any data in the sample data that refers to each.

I assume that the css-files can be removed if none is referenced by the code, as the css cannot be controlled by the database.

The sortabletable demos should not be present in this repo.

**Comment by c17johha** [comment]
If there is a group that handles dugga, it might be better for them to look into the rest of the files

**Comment by a18kaswi** [comment]
Closing, we have https://github.com/HGustavs/LenaSYS/issues/465 and https://github.com/HGustavs/LenaSYS/issues/1778 touching issues revolving redudant code and CSS-stuff. Closing this to try to pinpoint what should prioritized in this clustermadness of a backlog.
