### ISSUE TITLE
The install script should create the database in its final form without the use of ALTER statements.

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#5693]
At the moment the database are created with CREATE statements and then at the bottom some tables are then altered.
Those tables should be created as they should be directly wich would simplify the script.

Example of lines that could be removed:

635: alter table user_course alter column result SET DEFAULT 0.0;

**Comment by HGustavs** [comment]
The alters should be there as documentation ... ... but in deltachange.sql

The process is, if the running system presents an SQL error, this means that the tables have been augmented compared to the running system. The error message and the alter table should then be found in deltachange.sql

The init_db sql should be the "current" create-at-once-database, any alters necessary for patching any older system running an older database should be available in deltachange.sql together with the corresponding error message.

If the alter table in the init_db is NOT of that kind, but just a result of the work process or the export of some tool... then it should be incorporated back into init_db.sql

**Comment by HGustavs** [comment]
Running the init_db is the edge case and the running system with the "old" database is the main case. ...In many other development paradigms this is the other way around...

**Comment by a17poner** [comment]
merged.
