### ISSUE TITLE
Developer mode toggle clarified

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#5694]
View menu has a "Developer mode" that is a toggle function. It's not so clear if this is active or not. Solution for this would be to make a marking (suggestion in the green circle in screenshot) in the menu that shows if it's selected.  Another solution is to write out the mode that is currently used in a "status bar" that is attached to the bottom of the page.
![Edited](https://user-images.githubusercontent.com/46029340/55711224-92b4ff00-59ec-11e9-88c5-2657fe9d2378.PNG)

**Comment by a17drama** [comment]
I missed that the snap to grid feature should have the same solution. Do both while doing this issue.

**Comment by a17drama** [comment]
There will be more functions with toggle implemented from other issues and it would be preferable to be able to just attach this toggle indication to these as well. In other words it would be preferable no to hard code this for each choice if possible.

**Comment by c17matjo** [comment]
![image](https://user-images.githubusercontent.com/49195031/55873968-4e169880-5b91-11e9-9c28-186d791d7de8.png)
Screenshot of my implementation. The checkboxes are not specified in the html document but are instead added to the page from javascript in a setCheckbox method. This can be called on any element that needs a checkbox element.

**Comment by a17jacsv** [comment]
Content from this pull-request was not included after the merge and needs to do over again.

**Comment by c17matjo** [comment]
Turns out that the merge was correct but that some other commit (https://github.com/HGustavs/LenaSYS/commit/3d30fb1f3d377346c91e40f4b8a74f9605c35ab6) in gruppA2019W16 had changed the menu-item implementation enough to break checkboxes.

**Comment by c17matjo** [comment]
https://github.com/HGustavs/LenaSYS/pull/5904 should fix the issue

**Comment by a17jacsv** [comment]
Okay, I understand. We have some guys working with trying to decrease the number of files regarding the diagram. Unfortunately, you'll have to do this solution again when they are done as we can't editing at the moment. I'll be in touch.

**Comment by c17matjo** [comment]
Okay 👌

**Comment by a17jacsv** [comment]
Now you can fix this issue with a refreshed branch from our branch (gruppA2019W16) and create a new pull request.
