### ISSUE TITLE
Improve user importing in accessed.php

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#5698]
![user import](https://user-images.githubusercontent.com/37834592/55714777-8c765100-59f3-11e9-941e-c3a3c03e1459.PNG)

Importing users is a hassle right now, why not add the option to show all eligible users in a dropdown list so you can add them without typing information manually?

**Comment by HGustavs** [comment]
Well, there would be over 600 users in that dropdown... and the list is exported from an automated system as a csv ... so it is quite usable as is. Export csv from ladok and pasting into that box, pressing import.

also, we create new users using that dialog, not only connecting existing users to course.

The dialog serves dual purposes.

**Comment by HGustavs** [comment]
Aslo, the format listed above is wrong we currently use a csv.

**Comment by a17pongo** [comment]
What is the correct way of entering a new user in this way?
copy-pasting the example users will present an error saying that does users do not exist.

**Comment by a17joaap** [comment]
> What is the correct way of entering a new user in this way?
> copy-pasting the example users will present an error saying that does users do not exist.

Long-pressing the FAB and choosing the create user option
