### ISSUE TITLE
courseHomepage - a page with al the courseInfo

### ISSUE THREAD

**Issue by c13emmjo** [HGustavs/LenaSYS#570]
From the studentView the student should be able to click her/himself on a specific course that she/him have taken or are going to take. 
Then another page will show and its the page with all the courceInfo were courceGoal and things will show.

**Comment by HGustavs** [comment]
Is this glanceable?

Too many clicks.

Can this be done on the same page with a hover popup?

**Comment by a13ottne** [comment]
feature discarded due to time constraints
