### ISSUE TITLE
Variables checked against numbers

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5709]
<img width="151" alt="toolbarState" src="https://user-images.githubusercontent.com/49199690/55723725-09142a00-5a0a-11e9-8703-ea7ab0da151e.PNG">
There are variables that are checked against numbers in if statements in various places within the diagram files. It is hard to get a grasp of what the numbers represents.
It would be better if the the numbers were mapped to variables that could be used instead.

**Comment by HGustavs** [comment]
This is already an issue #5685 I think it was.

**Comment by HGustavs** [comment]
Please use moustaches (~ <-- three of those) when quoting code.

Screenshots are for user interface stuff not for code.

~~~
This is how a moustache-encapsulated block looks!
~~~

**Comment by a17okaoz** [comment]
Is it ok for me to change the variables here to? I have just written a comment on what the numbers stands for.
