### ISSUE TITLE
Highlighting in code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#571]
There are a few issues with highlighting
* Highlighting of parentheses on hover is so subtle that it is nearly invisible
* If we hover an important word in code viewer code box it seems like it is not highlighted in description box but the converse case is true; if we hover in description box it is highlighted in code box. Unclear if it is a jquery or a css issue

**Comment by HGustavs** [comment]
I have left it up to Andras and Marcus to figure out what to do with my patches, if you want to merge them with master or to your wekly merge on thursday or some other way.

My two bugfix branches nevertheless need to be reviewed by some one.

**Comment by c13caral** [comment]
this is now solved
