### ISSUE TITLE
Large code segments are in comments

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5711]
<img width="259" alt="outCommentedCode2" src="https://user-images.githubusercontent.com/49199690/55724107-fd753300-5a0a-11e9-9f9f-10e7dce4f6aa.PNG">
There are a lot of out commented code in the diagram files. If not used, the segments should be deleted.

**Comment by a17adajo** [comment]
I agree, if needed, the code can be retrived in the git history.

**Comment by HGustavs** [comment]
These screenshots are barely readable ... when citing code it is more convenient to paste code encapsulated with thee moustaches ( ~ <- three of those ) and then a code block and then three more moustaches.

And then we get a nice block
~~~
code
~~~

**Comment by a17drama** [comment]
I agree to disagree. Screenshot is readable if you click the picture. But for convenience sake it's better to implement the code into the comment. Can be done so in the future.

**Comment by HGustavs** [comment]
It is relatively common for people to have problems seeing colors which makes low-contrast text very difficult to read if it is in the darker side of the spectrum... it is less of a problem if it is black on white or white on black... so it is an accessibility issue.
