### ISSUE TITLE
Unused/empty functions

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#5712]
There are some functions in diagram_IOHandler.js that are unused or without content. If they are not used they should be deleted.

![Capture5](https://user-images.githubusercontent.com/37792271/55724210-33b2b280-5a0b-11e9-8283-922521e67806.PNG)

**Comment by HGustavs** [comment]
No idead what this code does... 

There used to be a button that generated a demo diagram... perhaps leftovers from this?
