### ISSUE TITLE
Function names does not follow naming standards

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5714]
<img width="206" alt="functionNaming" src="https://user-images.githubusercontent.com/49199690/55724376-973ce000-5a0b-11e9-9b92-9c5ec8161448.PNG">
Functions in diagram_mouse.js does not follow the naming standard.

**Comment by HGustavs** [comment]
This type of thing may cause refactoring-problems so it is best to leave this as is.

We can only change function names if only used in one place or if the function is used only in the same file as it is defined.

**Comment by a17drama** [comment]
Doing as suggested. Leaving it be and closing this issue.
