### ISSUE TITLE
Add guidance on how to set mySQL root password in the LenaSYS install guide

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#5720]
The lenaSYS install.php guide requires users to fill in all text fields in every part o the installation to proceed. If you run a local database for example by using xampp, the default root has no password set, hence you can not proceed the installation as you have to fill in a password when you have none. The guide should therefore instruct the user on how a password can be set for mySQL.
![guide1](https://user-images.githubusercontent.com/37793141/55727227-d5d59900-5a11-11e9-9340-3e4a2b7d0e42.PNG)

**Comment by a17adajo** [comment]
I yhink lenasys should allow an empty root password instead

**Comment by a14oscna** [comment]
I changed the fix to allow the user to proceed without a password rather than enforcing the user to set a password if they do not already have one. However, it is still very bad practice to not have a root password.
