### ISSUE TITLE
 Scroll to reach elements that are further down the page after zooming in is not reached

### ISSUE THREAD

**Issue by a17okaoz** [HGustavs/LenaSYS#5721]
When zooming out to 30% or 50% and placing the element at the bottom of the paper and then zooming in, you cannot reach these elements because it cannot scroll down on the paper.
<img width="597" alt="b1" src="https://user-images.githubusercontent.com/37792681/55727703-d6226400-5a12-11e9-9080-5be05a04aec6.PNG">

<img width="469" alt="b2" src="https://user-images.githubusercontent.com/37792681/55727709-d91d5480-5a12-11e9-9aab-140621eba26d.PNG">

 Make it possible to scroll down on the paper so the elements can be reached.

**Comment by a17drama** [comment]
This issue should be solved when #5826 is implemented

**Comment by a17drama** [comment]
Is this still an issue considering we got a working zoom function and camera that can move? It is solved by the issues that fixed zoom and camera.
