### ISSUE TITLE
Mouse coordinates to match canvas coordinates in all zoom modes

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#5722]
When zooming and moving the canvas, new drawings do not always get created at the cursor.

#5145 root issue

**Comment by HGustavs** [comment]
Yes, this is the best solution, converting the on-screen mouse coordinates to pixel coordinates regardless of the zoom level.

**Comment by a17alfcl** [comment]
Already solved in issue #5826
