### ISSUE TITLE
Change that the canvas-origo can't move

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#5723]
The canvas should not be able to be moved so both X & Y becomes negative. It should only be moved when X & Y are positive. There is no reason for it to show a negative window of the canvas when it can scale endlessly.

#5145 root issue

**Comment by HGustavs** [comment]
This seems like a good fix. Hopefully this will resolve the zoom and pan issues.

There has been several attempts at this functionality.

**Comment by a17drama** [comment]
Expand this issue to locking the canvas totally. No moving of canvas should be possible. Making a comment in the existing pull request for this issue as well.

**Comment by a17drama** [comment]
This is one part of the solution for #5826 . Canvas should be static and not move.

**Comment by a17jacsv** [comment]
I close this issue because there is a better solution on the go. #5826
