### ISSUE TITLE
Hidden item on a course page has visibility issues

### ISSUE THREAD

**Issue by a17fellu** [HGustavs/LenaSYS#5729]
An item on a course page with visibility set to hidden is too hard to read. The opacity on the text should be a little bit higher 

OR

Add parentheses with the text (HIDDEN) beside the list item

**Comment by HGustavs** [comment]
I think this is already an issue... #5623 if I am not mistaken.

I think this can be solved by a combination of a little less opacity and ... would primarily add text-decoration: line-through; ...

If we add more text, wrapping of the items may be an issue.

**Comment by a17fellu** [comment]
Already an open issue of this
