### ISSUE TITLE
Code viewer syntax highlighting does not work

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#573]
Syntax highlighting does not work even if correct data is supplied.

**Comment by HGustavs** [comment]
If this patch is merged into code viewer the syntax highlighting works as indicated by the screen shot below..... (data is from test dataset from recent issue)
* Important rows are highlighted
* Important words for code example highlighted in both document and code
* Syntax highlighting using wordlist

![screenshot 2015-04-01 00 02 31](https://cloud.githubusercontent.com/assets/6978801/6930338/9d51cd00-d802-11e4-98cb-c27e6891fd88.png)

**Comment by a13jorla** [comment]
Seems to highlight brackets and gullwings only, at howerover.

**Comment by a13jorla** [comment]
It works on text to if the right exempleid is set in database.
