### ISSUE TITLE
style.css is 4635 lines

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5731]
/shared/css/style.css is 4635 lines. Surely, all these rules are not actually required across the entire site, and can be split into modules.

**Comment by HGustavs** [comment]
This is a refactoring nightmare. Remember, we are in a continuous deployment scenario, and that all code will not be deployed at the same time... and that code from old and new versions is combined into the running systems.

If we split/change this in a breaking way, old versions of the site will perhaps not work the same, and we will have to keep the code in two places, one in old file for old code and one in new file(s) that may or may not be run at the same time.

What __can__ be done, however, is checking over which declarations that are not in use, and can be removed completely.

Splitting files or any kind of breaking changes are not possible.

**Comment by HGustavs** [comment]
It is an arduous process, checking over where each declaration is used, and if apparently not used, removing it.... line by line... with testing of any applicable part of the interface.

We want the css to be generic and template-able.

If we change color of the base font, much of the text on the site changes color, no special cases based on id-s and so on.

**Comment by b17timjo** [comment]
The CSS [`@import`](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) rule has been around since the original [CSS1 standard from 1996](https://www.w3.org/TR/REC-CSS1/) and as such it is even [supported by IE 5.5](https://developer.mozilla.org/en-US/docs/Web/CSS/@import#Browser_compatibility)
Successively separating independent portions of style.css into separate files and replacing with an import should be feasible? This would still allow use of a single monolith css-file, but simplify development and maintainance.

**Comment by a18kaswi** [comment]
#1778 - Original issue about CSS-mess. Closing this so the team of this year can go through the CSS when TIME is there.
