### ISSUE TITLE
SectionED: Edit Item tab Moment row not working 

### ISSUE THREAD

**Issue by b17nicsv** [HGustavs/LenaSYS#5733]
In the Edit Item tab there's a row called Moment which doesn't work. Logically it should only show if the Type row has Moment selected and then choose which moment it refers too.
![Moment Github](https://user-images.githubusercontent.com/49198878/55783005-c3a93880-5aad-11e9-88e6-0cf835950a8d.PNG)

**Comment by HGustavs** [comment]
It only has a function for dugga items, connecting each test to the corresponding part of the course.

We used to hide this part automatically but it was a bit of a kerfuffle.

The moment item is only valid for tests, but... if we are in a "section" and changes it into a "test", it should re-appear, and conversely, it should disappear, if we change from "test" to for example "code".
