### ISSUE TITLE
create a script that creates a new instance/folder/branch on the web-server

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#5737]
It should be enough to pass arguments to a script to create a new issue-branch.
The arguments might be:
GroupId: which group folder the instance should be place in, also which branch it should clone
Name: name of the new branch, folder and URL

**Comment by HGustavs** [comment]
This is outside of the system, and as such, you are free to add this to the documentation wiki but it should not be part of the code base per se.

**Comment by a17maxsj** [comment]
A member of group C is on it, see issue https://github.com/HGustavs/LenaSYS/issues/5739 (did not see this thread)

**Comment by a17pongo** [comment]
@c17johha 
Recommends closing this issue because of duplication.
