### ISSUE TITLE
(non LenaSYS) streamline setup of personal/issue folders on the webserver

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#5739]
Produce a script to make it easier to set up folders for issues. Takes quite a while to set up using the current putty method.

**Comment by HGustavs** [comment]
Well, should that script not just be a variation of 

 git pull origin <branch>

since there are never any local changes on the server we should just be able to just get the branch?

**Comment by HGustavs** [comment]
this is how I do it

~~~
git clone https://github.com/HGustavs/LenaSYS.git
~~~

~~~
cd LenaSYS
git pull origin GruppB2019#5633
~~~

verified and working on my machine.

**Comment by HGustavs** [comment]
and then I change the code on githun and do arrow up and do the git pull again... takes about 1 sec to update to latest version of branch...

**Comment by a17adajo** [comment]
At the moment there are also some steps where a new Linux user is created and some configuration in apache is done. And this is repeated for every issue.

**Comment by HGustavs** [comment]
The creation of users should not be necessary in the generic case (useful outside of the course) ... 
we only need users for users (if that, only one single user for the whole app also works) ...

No special apache configuration should be necessary either in the general case... in the deployed system we only change the timeouts and maximum file sizes for uploads, so for the generic case... 
no specific per folder changes should be necessary.

**Comment by b16johso** [comment]
I created the script createbranch.sh in the groupC directory on the test server. It automates all the steps in the guide provided by group B, creates directory, git clone and conf file.
Run the script with
`sudo bash createbranch.sh Group Issue`

Example
`sudo bash createbranch.sh C 5656`

Branch name must follow name standard, otherwise the script won't work.

**Comment by a17pongo** [comment]
Recommend creating a sort of wiki/guide for git with the necessary commands for this course.
Describing the commands and when you need them.

**Comment by a17maxsj** [comment]
This has been created and distributed throughout the teams! Closing...
