### ISSUE TITLE
Coordinates showing non useful info

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#5746]
![Capture](https://user-images.githubusercontent.com/46029340/55796420-4809b480-5aca-11e9-9799-51fba7bd893e.PNG)
Coordinates should show mouse position. As it is now it's showing something that has no relevance to the user.

**Comment by HGustavs** [comment]
For debug purposes useful.... perhaps relegate to developer view ?

**Comment by a17vikab** [comment]
> For debug purposes useful.... perhaps relegate to developer view ?

On the second thought, it might be useful for both the user and the developer and therefore it might be a good idea to add a second bar or extend the existing bar so it can contain both mouse-coordinates and origo-coordinates?

**Comment by a17drama** [comment]
This is useful for the developer because we move the canvas around and these coordinates show the offset. In any case if it is for the developer it shouldn't be shown until the developer mode is active. Regular users have no use of this info and it's just confusing. This will also be obsolete if #5748 is implemented because the canvas would be static in that case.
