### ISSUE TITLE
Right click drag scrolling

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#5748]
Implement a new function where you can right click the canvas and drag to explore the canvas. In other words instead of scrolling you should be able to click and drag.

**Comment by a17drama** [comment]
There is a similar function that activates when spacebar is pressed but this moves the canvas around. My suggestion involves a camera object that is moved instead and canvas is static. This is related to issue #5721. This would also solve the problem with #5723. Moving canvas causes a lot of problems and takes unnecessary computing power to recalculate the new positions on the canvas with the offset that is caused because of the move.

**Comment by HGustavs** [comment]
The canvas should be static and the graphics move inside the canvas IMHO.

**Comment by a17drama** [comment]
This issue is related to #5826 and is a part of the functionality for that issue.
