### ISSUE TITLE
Prioritization of object placement (front/back)

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5750]
<img width="205" alt="toFront" src="https://user-images.githubusercontent.com/49199690/55797584-1a723a80-5acd-11e9-81bb-45f5e422d1d3.PNG">
It is not possible to decide which object is in the front of the canvas space and which object that gets stacked in the back of the canvas space. This functionality might be useful in the future.
<img width="205" alt="toFront" src="https://user-images.githubusercontent.com/49199690/55798087-5954c000-5ace-11e9-9bb5-054b4f3a9e74.jpg")>
To further clarify the problem, the Z-axis in the image above is the vector in which objects should be able to be moved.

**Comment by HGustavs** [comment]
It should draw back to front depending on the list of objects, it is a drawing order thing.

If we implement "move to front" this should mean put last in object list.

If we implement "move to back" this should mean put first in object list.

**Comment by HGustavs** [comment]
Objects are commonly drawn from first to last, and then lines after the objects.
