### ISSUE TITLE
Remove empty rows when sorting in the Result Editor.

### ISSUE THREAD

**Issue by a17oscno** [HGustavs/LenaSYS#5755]
When currently sorting grades in the Result Editor rows that dosn't have anything in common with the sorting (example the person do not have any passed assignments in that course) still shows. Would be nice if these rows would get temporarly removed when sorting. 

Something that might be useful is to have a look at the "Search" functionality due to it actually temporarly removes rows when searching for users in a course.

It is located in the same page as the sorting is.

**Comment by HGustavs** [comment]
This may related to the boolean operators for search ... somehow entering empty on certain column?

Most of the time you want the global perspective, out of 31 people this term 18 handed in first assgnment ... and sightly less for second assignment ... and so on...

But for special case ... find me the "Greger" that has not handed in "Assignment B" or even "Assignment*" when looking for specific people ...

So... not for sorting but for searching ...

**Comment by a17oscno** [comment]
My bad i ment to write "when Filtering" which can be described as a type of searching but in this case only for grades.

**Comment by c17johha** [comment]
#5635
