### ISSUE TITLE
Resulted: Export text doesnt seem to match the chosen options

### ISSUE THREAD

**Issue by a17adasy** [HGustavs/LenaSYS#5757]
If for example Rapport 1HP is chosen shouldnt only the rapport duggor and related grades be shown?
The way it is now everything is shown, even though the title of the "popup box" is "Results for: Rapport 1HP. 

![](https://i.gyazo.com/16ef7abadfd620e32967b48b1ff576ce.png)

**Comment by HGustavs** [comment]
The dropdown specifies which delkurs we are reporting and the filter tells us which sections in the dugga system that we want to export.

These are often related but not exclusively so.

Most commonly the delkurs selected from the dropdown appears in the set but we could filter any combination of columns depending on for example if we only want to import exam scores for example.
