### ISSUE TITLE
Fab icon style is broken

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#5761]
Currently the styling for the extendable FAB icons are broken.
![fabnoIcon](https://user-images.githubusercontent.com/37792198/55832250-6779ff00-5b15-11e9-8a20-31eb40f483c2.PNG)

The styling for these buttons have no background set?

**Comment by HGustavs** [comment]
They should be rainbow colored backgrounds... 

with each button some other color...

What it used to look like in  #5414 among other issues.

im thinking some error in css so that those subsequent colors are not assigned.

I think there was some change in the css to fix that those colors were erroneously into links in some other places...

**Comment by HGustavs** [comment]
I think it is this part that is not applied properly ??

~~~
/*===============================*/

/* FAB action buttons background */

/*===============================*/

/* First item */

.btn-floating li:nth-last-child(1) a {
  background-color: #6ead2a;
  color: white;
}

.btn-floating li:nth-last-child(1) a:hover {
  background-color: #83ae55;
  color: white;
}

/* Second item */

.btn-floating li:nth-last-child(2) a {
  background-color: #adc726;
  color: white;
}

.btn-floating li:nth-last-child(2) a:hover {
  background-color: #b8cd4e;
  color: white;
}

/* Third item */

.btn-floating li:nth-last-child(3) a {
  background-color: #e9a901;
  color: white;
}

.btn-floating li:nth-last-child(3) a:hover {
  background-color: #ddae37;
  color: white;
}

/* Fourth item */

.btn-floating li:nth-last-child(4) a {
  background-color: #dc7e34;
  color: white;
}

.btn-floating li:nth-last-child(4) a:hover {
  background-color: #d78b50;
  color: white;
}
~~~

**Comment by HGustavs** [comment]
Or perhaps the markup needs to be changed to match the css if we see no obvious error in css?
