### ISSUE TITLE
SectionEd: when editing item you can't change the moment

### ISSUE THREAD

**Issue by a17adasy** [HGustavs/LenaSYS#5768]
It is shown as a dropdown but nothing happens when it is clicked. The moment cannot be changed for a item. If the site is inspected the dropdown has options in it.

**Comment by HGustavs** [comment]
It should update only for tests ... when one chanes to test does the box refresh?

**Comment by a17adasy** [comment]
The "moment" dropdown is never clickable, even if the type is Test.
