### ISSUE TITLE
SectionEd: The FAB button is in the way of some items if you want to edit item.

### ISSUE THREAD

**Issue by a17adasy** [HGustavs/LenaSYS#5769]
The FAB button is over the edit buttons.

![image](https://user-images.githubusercontent.com/37799016/55867284-7fd43300-5b82-11e9-8247-ef1569d9a061.png)

**Comment by b17carma** [comment]
I believe this is a duplicate issue, see https://github.com/HGustavs/LenaSYS/pull/5743
