### ISSUE TITLE
Line thickness slider gets hidden in the Firefox browser when draged

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5780]
![lineThicknessSlider](https://user-images.githubusercontent.com/49199690/55876346-b9fbff80-5b97-11e9-9cce-443d9589c4d5.JPG)
When using the Firefox browser, the slider gets hidden while being clicked and dragged. It would be nice if this could be fixed.

**Comment by HGustavs** [comment]
Do we know why?

This must be css styling?

Normal range input does not behave like this......

**Comment by a16tobfr** [comment]
Code located in diagram_forms.php
~~~
<input id="line-thickness" oninput=\'globalLineThickness(); hashFunction(); updateGraphics();\' style="width:100%; margin: -2px; padding: 0px;" type="range" min="1" max="3" value="1">
~~~
A tip is to check out how the zoom slider is made which can be found in the shared style.css document.
.zoomSlider uses the following for adjusting to different browsers
For Chrome, Opera, Safari, Edge:
.zoomSlider::-webkit-slider-thumb {
...
}
and for FireFox:
.zoomSlider::-moz-range-thumb {
...
}

This might help in order to solve this issue in the future.

**Comment by a18kaswi** [comment]
PR #7963 not good because rework of system. Check with @a18antsv

**Comment by a18petha** [comment]
This Issue implementation needs to be redone to be compatible with solution from #5638
