### ISSUE TITLE
Pressing escape in sectioned.js removes the FAB used to add items

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#5782]
When the escape key is pressed in sectioned.js with no dialog open, the fab used to add new items is removed which does not appear to be intended behaviour

**Comment by HGustavs** [comment]
This must be a bug

**Comment by b17carma** [comment]
This issue seems to have reappeared?

**Comment by a17robes** [comment]
Just tested it again and there are no problems for me, works like the fix said it would! Can anyone else confirm? @a17alevu ?

**Comment by a17robes** [comment]
Might be that the edited code have been changed after my fix of this issue. Going to check this out!

**Comment by b17carma** [comment]
Fixed in https://github.com/HGustavs/LenaSYS/pull/6170
