### ISSUE TITLE
No feedback/error message when creating new duggas with incomplete data

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#5783]
When adding a new dugga on "Edit Dugga" (Picture below), you have to fill in start date etc. However, nothing says that you have to do that and if you try to save the dugga without meeting the requirements (that you have no idea about) nothing will happen. There should be a type of error message for feedback for what went wrong and what needs to be filled in. 

<img width="357" alt="editdugga" src="https://user-images.githubusercontent.com/37792690/55877729-1ca2ca80-5b9b-11e9-962d-1d4e43f8bc75.png">

**Comment by HGustavs** [comment]
Yes, for the mandatory fields in this dialog, I would prefer an alert if we press the button without having entered the mandatory fields.

**Comment by b17annni** [comment]
#6026

**Comment by b17annni** [comment]
appears to be sorted
