### ISSUE TITLE
Buttons on "variants for:  Test" page doesn't do anything. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#5784]
When you hit the pen button on a test a new window will appear.  
This is the pen button: 
![image](https://user-images.githubusercontent.com/49194898/55877664-ed8c5900-5b9a-11e9-9001-2c8c7a20f04b.png)

This buttons shown in the image bellow doesn't do anything.. Should the be removed or get some kind of purpose? 
![image](https://user-images.githubusercontent.com/49194898/55877553-94242a00-5b9a-11e9-81d5-65742cfc4134.png)

**Comment by a17maxsj** [comment]
clicking the pen is now broken, new issue? 
![image](https://user-images.githubusercontent.com/49199993/55943160-58469e80-5c46-11e9-9c67-36aee18bdbc6.png)

**Comment by a17poner** [comment]
Merged!
