### ISSUE TITLE
Trigger in SQL code

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#580]
There is a trigger in the SQL code that refers to a table that does not exist.
I say; remove that trigger as it does not work, and it is unclear to me if it is possible to make it work as the database looks currently.

**Comment by a13karsi** [comment]
The trigger seems to be designed to avoid a foreign key constraint failure when you delete something from the table 'wordlist'. I changed the table reference 'codeBox' to 'box' in the trigger and it seems to function correctly, that is, you can delete entries from 'wordlist' without getting a foreign key constraint error with the trigger working.
