### ISSUE TITLE
Menu bar moving when resizing inspection window

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#5804]
![Edited](https://user-images.githubusercontent.com/46029340/55885148-af4a6600-5ba9-11e9-8699-3d6eaaf46632.PNG)
Menu bar is moving (Marked with red arrows) when inspection window is resized (Line marked with green is draged). This has been tested in both Edge and Chrome and it's the same phenomena. Menu line should be static.

**Comment by HGustavs** [comment]
I would remove the white space above completely.

**Comment by a17drama** [comment]
Normally there is no white space. It only shows up when the inspection window is dragged out like in the screenshot.
