### ISSUE TITLE
contributionservice.php references a database that doesn't exist

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#5806]
In contributionservice.php this line of code:
`$log_db = new PDO('sqlite:../../GHData/GHdata_2018_7.db');`
should initialize a database with data from github.

This does not exist yet. We need to create this and create the necessary tables.

**Comment by HGustavs** [comment]
It is a privacy issue, we cannot distribute this database on github.

Last year we distributed a database (off-line, not on github) containing the data for HGustavs and a95marbr but nothing else ... this way we are limiting the  privacy risk ... 

We will update the current database for the week, shortly, and then distribute a sanitized copy.
