### ISSUE TITLE
More accurate statistics in pie chart for each course

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#5808]
For courses where duggas are separated by university program (such as WEBUG, SVBIG, etc.), the pie chart also takes those duggas not relevant to the student into account when displaying the information.

Image is from the Databaskonstruktion course and all assignments pertaining to WEBUG have been handed in and have a passing grade. 
![piechart](https://user-images.githubusercontent.com/37792313/55911702-70380700-5be1-11e9-8173-400ab56f4c85.png)

To give the student a more accurate picture of the progress of the course, the data the pie chart uses should somehow be filtered by what duggas are actually relevant to the student who's logged in.

**Comment by HGustavs** [comment]
I think we can resolve this without filtering on study programmes.

How about counting at most one of each dugga with the same name or something similar to that.

What if it is not split depending on study programme but for example something like the course group?

If we only filter by the name of the test, each teacher can decide how to handle this individually?

**Comment by HGustavs** [comment]
Priority order:
* Correct for all
* Nothing for all
* Consistently wrong for all

Not:

* Correct for some, wrong for some.

**Comment by c17johha** [comment]
Support to create an example would be very helpfull.

**Comment by b17nicsv** [comment]
@HGustavs Is this a high priority ora problem at all? I don't see a case where, in the same course, students from different programmes would need to have different duggas. The course have the same goals for everyone.

**Comment by a17johpe** [comment]
The reason for the different duggas with same names and goals is because there are different deadlines depending on course group (as can be seen in the screenshot).

**Comment by HGustavs** [comment]
This may be unsolvable.

* Two courses run at the same time but with different speeds
* People are not reading the course variant that is congruent with study programme data as given

**Comment by a18kaswi** [comment]
Due to eventually unsolved I close.
