### ISSUE TITLE
The diagram canvas seems too large for the screen?

### ISSUE THREAD

**Issue by a17jonro** [HGustavs/LenaSYS#5820]
There are scroll bars that appear both vertically and horizontally when using the diagram. However the scrolling is minimal and doesn't achieve anything, the canvas should be scaled to the screen better so that these does not appear.

**Comment by HGustavs** [comment]
The canvas should be ___exactly___ as large as the screen.

Since the diagram can be larger than the screen and it depends on the scrolling position we do not need any scroll bars.

We scroll by right mouse or pressing space bar or whichever way that was chosen for this.

**Comment by a17drama** [comment]
This issue will be addressed as soon as the #5826 is implemented.

**Comment by a17vikab** [comment]
This issue was solved in #6020
