### ISSUE TITLE
Menu items position is changed when changing direction of the toolbar

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#5821]
Menu items position is changed when changing direction of the toolbar. It should not affect this menu **only** the toolbar.

_See picture below:_
<img width="268" alt="Skärmavbild 2019-04-11 kl  10 11 37" src="https://user-images.githubusercontent.com/37792795/55941391-68f51580-5c42-11e9-99cd-6d9ec4960e37.png">

_See picture below:_
<img width="408" alt="Skärmavbild 2019-04-11 kl  10 15 59" src="https://user-images.githubusercontent.com/37792795/55941634-de60e600-5c42-11e9-9e48-2833bfa405ec.png">

**Comment by a17drama** [comment]
This issue is redundant.

**Comment by a17drama** [comment]
This could have to do with #5804 .
