### ISSUE TITLE
Canvas grid layout collapses

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#5832]
When you are dragging the canvas either up or down, the grid layout collapses. It no longer draws whole squares.

![Capture7](https://user-images.githubusercontent.com/37792271/55945660-87134380-5c4b-11e9-93d1-21b23c6e5b16.PNG)

**Comment by a17drama** [comment]
This issue is there because we are able to move the canvas around and the solution for this issue is addressed in #5826 .

**Comment by a17celal** [comment]
This issue should be closed since the problem is fixed now
