### ISSUE TITLE
After merge an error is thrown from sortable table on result and access and the "pens" on test no longer works

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#5833]
![image](https://user-images.githubusercontent.com/49194938/55945811-ccd00c00-5c4b-11e9-8451-811ada3316a4.png)

When going onto a page that has a sortable table the first error in the console is thrown. When pressing a pen the second error is thrown. Access however is fine despite having a sortable table but it doesn't have an edit pen the same way the other two tables do.

**Comment by HGustavs** [comment]
Is it any sortable table or just this specific sortable table?

**Comment by a17poner** [comment]
It's accessed and test, both of them when viewed throw the first error shown in the screenshot and then when the pen is clicked they both throw the second error, not yet sure what causes this since it happens in two different places I assume it will be something in sharedtable.js. Git blaming that file non of the rows listed in the stacktrace have been altered in the last 8 months so guessing it would be something above in the chain that causes it.

**Comment by HGustavs** [comment]
It this related to #5853 ?? seems very similar?

**Comment by a17poner** [comment]
Yes this is the exact same issue as #5853. There is a pull requset pending for this issue but if @a17joaap need to be able to click the pen to test your own issue currently being worked on all you have to do is remove the line at 562 that tries to add styling to tableid+delimiter+"tableheadmhv" (pay attention to the v at the end) and the error should go away.

**Comment by a17andby** [comment]
Fixed and merged. Closing.
