### ISSUE TITLE
Free drawn objects have some absent apperance attributes

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5841]
As of now, the only way to add text to free drawn objects are by making a separate lable. It should exist as an option in the apperance menu for the object, as it does for the ER objects.

The additional attributes which makes sense to be in the apperance menu for free drawn objects are:
- entity name
- font family
- font color
- text size

Optionally, add a grouping functionality which makes text objects able to be attached to the free drawn objects, or any object.

**Comment by a16tobfr** [comment]
Can most likely be closed since this is no longer relevant, or requested by the customer.

**Comment by a17vikab** [comment]
Solved.
