### ISSUE TITLE
"Du tillhör grupp" has extra hidden functionality.

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#5845]
We should make this visible by using the "clickable" pointer. This also has the wrong cursor when hovering over on the header since it cant be moved.

![image](https://user-images.githubusercontent.com/49199993/55957582-0104f600-5c67-11e9-86e3-24b991b566d5.png)

See gif...
https://gyazo.com/69551b4c92e05950206f8a0451321629

**Comment by b16johso** [comment]
Changed the cursor to the pointer cursor to make it more obvious that it's a clickable link. I also changed the icon to a group icon to make it more obvious that it's a group list link.
https://i.imgur.com/0BMrjF0.png

**Comment by HGustavs** [comment]
Makes sense!
