### ISSUE TITLE
Headers in settings has the wrong cursor.

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#5846]
I have noticed this in all settings menus so far.
Ex. 
![image](https://user-images.githubusercontent.com/49199993/55957754-622cc980-5c67-11e9-8bec-7081412c590b.png)
![image](https://user-images.githubusercontent.com/49199993/55957762-65c05080-5c67-11e9-9928-f02b2f04320c.png)

Since these are not movable the cursor should be changed for now. Probably a global variable?

**Comment by HGustavs** [comment]
Seems reasonable... make sure this is a global setting for all of the dialogs.

**Comment by a17maxsj** [comment]
Fixed, closing.
