### ISSUE TITLE
sectioned.php Icon, fetched from showdoc.php, not showing.

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#5849]
Tested on local test server. The icon that would be fetched from `showdoc.php?courseid=4&coursevers=2883&fname=skalman-257x300.jpg ` is not showing as the picture below demonstrates.

![Screenshot from 2019-04-11 15-26-36](https://user-images.githubusercontent.com/49235724/55960990-395c0280-5c6e-11e9-9ea0-9c872e2bff40.png)

**Comment by b17annni** [comment]
![image](https://user-images.githubusercontent.com/37792766/56131415-a1208f00-5f87-11e9-8a2b-c9e896a30b89.png)

**Comment by a17andby** [comment]
This issue seems to be fixed. Closing.
