### ISSUE TITLE
Automatic mail function to students should also show coursecode in "subject"

### ISSUE THREAD

**Issue by a17anter** [HGustavs/LenaSYS#5850]
When the mail opens the subject should also contains the coursecode.
![Screenshot issue_5850](https://user-images.githubusercontent.com/49204317/55961501-4b8a7080-5c6f-11e9-9e85-7683f74b6c5e.PNG)

**Comment by HGustavs** [comment]
Well, kind of... but all students in a course may not study the same code....

if we mail all students that have taken the course, some of them study different course codes... unclear which code we show in the email?

**Comment by a17anter** [comment]
Currently no coursecode is shown in the mail subject. The highlighted coursecode is the one displayed on Lenasys webpage.

But if there are several coursecodes for the same course won't it be stored in the same variable??

**Comment by HGustavs** [comment]
Only course name, which changes less frequently than the course code or registration code.
