### ISSUE TITLE
Feature: Add dark theme

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#5851]

**Comment by c17julka** [comment]
Make sure to take account other issues relating to styling, such as #5619 so it will look good even after these styling changes

**Comment by HGustavs** [comment]
We have had this previously.... and... it resulted in divergence of styling.

If there is some way to resolve this without having two style files, that invariable diverge over time?

...We also want this type of thing to be theme-able....

Ideally we want to change very few things....

Such as a font color that changes all of the colors in all of the text
Primary color that changes all of the primary colors.

so the whole change, if we can whittle lighttheme.css down to a variant of/similar to the folowing

~~~
body {color:black}
.background {background-color:white}
.primary {background-color:orange}
.secondary {background-color:purple}
~~~

Then the whole darktheme.css would only be:

~~~
body {color:white}
.background {background-color:black}
.primary {color:purple}
.secondary {color:orange}
~~~

If this can be done... at the same time as #5731 I am all for it.

**Comment by a17maxsj** [comment]
Documentation for a dark theme idea...
https://uxdesign.cc/the-light-and-the-dark-side-creating-a-ui-colour-system-in-3-steps-41818c5bdb60

https://material.io/design/color/#tools-for-picking-colors

**Comment by b16johso** [comment]
This needs to be fixed before we can go ahead with this: https://github.com/HGustavs/LenaSYS/issues/5931
