### ISSUE TITLE
Clicking the pencil icon in duggaed.php does nothing

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#5853]
It's supposed to call the showVariantEditor function in duggaed.js, but the console shows this error instead:

`sortableTable.js:562 Uncaught TypeError: Cannot read property 'style' of null
    at SortableTable.magicHeader (sortableTable.js:562)
    at SortableTable.reRender (sortableTable.js:490)
    at SortableTable.renderTable (sortableTable.js:267)
    at renderVariant (duggaed.js:492)
    at HTMLImageElement.onclick (duggaed.php?cid=2&coursevers=97732:1)
SortableTable.magicHeader @ sortableTable.js:562
SortableTable.reRender @ sortableTable.js:490
SortableTable.renderTable @ sortableTable.js:267
renderVariant @ duggaed.js:492
onclick @ duggaed.php?cid=2&coursevers=97732:1`

**Comment by HGustavs** [comment]
Seems like some element is missing?

**Comment by a17poner** [comment]
Fixed it as #5833 and a pull request has been submitted #5854.
Should be reviewed and merged fairly soon, closing this one and leaving the other issue up to close it once the pull request has been merged
