### ISSUE TITLE
Resultview-scrolling should be contained in the table

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#5856]
When scrolling sideways in the result editor, the scrolling should happen in the table and not on the actual page. In the current state you can not make searches while at the far right of the table.

**Comment by HGustavs** [comment]
No. 

We want this as is.

Since table based scrolling causes other problems.

We prefer a solution where the position of the search box is fixed and/or put it in the navigation bar.

**Comment by a17ludca** [comment]
Since the entire table is located in a div, maybe scrolling in the actual div might be more appropriate. Im not sure what problems you are referring to that this could cause.

**Comment by a17amama** [comment]
This has been solved
