### ISSUE TITLE
SectionEd: FAB-button and NewItem-button has the same functionality

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#5857]
The small button in the top-right corner and the fab-button does the same thing at this time. This seems unintended.

**Comment by a17ludca** [comment]
Is the functionality supposed to be different or should the top-right button be removed?

**Comment by HGustavs** [comment]
Both should be therem and do the same thing.

Some users prefer the (original position of the) button when there are few items in a course.

**Comment by a17pongo** [comment]
im clossing this issue because this functionality seems to be as it should be.
