### ISSUE TITLE
“Edit item” hovering has a marking that it can be moved by mouse. The window cannot be moved at all.

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#5858]
![image](https://user-images.githubusercontent.com/49199825/56018147-95bc3200-5d01-11e9-9677-45cb594886c3.png)

The mouse marker could not be visualized in screen shot. To understand the issue, go to this view and try move the window

**Comment by b17nicsv** [comment]
Would you like to be able to move the window or just to have the cursor look different?

**Comment by b17timjo** [comment]
@HGustavs is it an intended unimplemented feature to move these windows, or is the bug that they show a cursor suggesting they can be moved?

**Comment by c17johha** [comment]
The window should not be able to be moved.
