### ISSUE TITLE
Contirbution.js shows data for a student

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#5864]
userid in contribution.js has been set to a student id, this is not ok and should be set to @HGustavs

**Comment by a17fellu** [comment]
It is not exactly correct to choose a specific user at all. This should not be hardcoded. It should be pointing to the user id of the user that is logged in

**Comment by a17joaap** [comment]
Henrik explains in this comment: https://github.com/HGustavs/LenaSYS/issues/5806#issuecomment-481846720

Last year they got a database with HGustavs as one of the users, we will be given a similar database next week

**Comment by a17adajo** [comment]
We will get the database this week

**Comment by a17maxsj** [comment]
This has been fixed now. Closing
