### ISSUE TITLE
Swimlane svg spills outside box

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5866]
As seen in:
![swim_spill](https://user-images.githubusercontent.com/38911528/56026637-da04fd80-5d14-11e9-887c-15078f794a34.png)

**Comment by HGustavs** [comment]
The div should expand to cover the whole svg.

Is this even possible since we dont know how large the view is physically, beforehand?

**Comment by b17timjo** [comment]
Appears to have been fixed at some point; unless someone can reproduce it, this issue can be closed.

**Comment by b17timjo** [comment]
Reproduced in firefox on windows:
![5866_firefox_windows](https://user-images.githubusercontent.com/38911528/56208755-2a9c9380-6052-11e9-918f-acc92372d394.png)

But after toggling the dev tools in firefox on/off it expanded:
![5866_ffxwin_readjusted](https://user-images.githubusercontent.com/38911528/56208978-bca49c00-6052-11e9-9200-0ffaca420804.png)

Not sure what to make of this...

**Comment by a17ludca** [comment]
@HGustavs This issue only occurs for Firefox-users and as Tim says, the box adjusts when opening dev-tools.  I'm not sure what is causing this, do you know?

**Comment by HGustavs** [comment]
Str***aaaa***nge for sure.

Could it be how the cotent is assigned, perhaps the dom in the browser does not trigger a complete refresh when we input the content?

It is as if the browser doesnt understand that the content was updated but when we go to devtools it re-renders whole page and bobs-your-uncle ??

**Comment by a17ludca** [comment]
@HGustavs Can't seem to fix this but adjusted the width so that the yellow boxes doesn't spill out. Does this look good? 
![image](https://user-images.githubusercontent.com/37799006/56662222-cc039500-66a3-11e9-9c0e-d43e668e72cb.png)
