### ISSUE TITLE
Navbar: User profile link has green text shadow

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#5870]
The user profile link in the navbar has a green text shadow. In my opinion, this clashes badly with the purple background and should be removed.
![bild](https://user-images.githubusercontent.com/37793460/56029396-8eede900-5d1a-11e9-8191-fc7643a91dc8.png)

**Comment by a17maxsj** [comment]
horrendous

**Comment by a17fellu** [comment]
Fixed in pull Request: https://github.com/HGustavs/LenaSYS/pull/5961

* Changed Shadow from Green to Black. Also made the shadow a little bit bigger

**Comment by a17andby** [comment]
Fixed and merged. Closing.
