### ISSUE TITLE
Crosses for draw free entities are still present when object gets deleted.

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5877]
When drawing in free draw mode and not finishing the figure (press the esc key), the crosses for the unfinished object can still be seen in the developer mode. This should not be the case.

The crosses for objects that has been drawn in free draw are also still present after the object has been deleted.

![crossError](https://user-images.githubusercontent.com/49199690/56034090-91564000-5d26-11e9-8f93-a35ad8eb5528.JPG)

**Comment by a17jacsv** [comment]
This issue seems to be fixed in merger #7522. @a17vikab

**Comment by a17vikab** [comment]
Seems to be fixed.
