### ISSUE TITLE
The direction which the lines are drawn in can in some cases be a bad direction

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5878]
When having relations and ER entities close to each other, there are situations in where the lines are not drawn in a good manner. In the example image, the line is drawn vertically while it would be better if the line were drawn horisontally.
![relationEntity](https://user-images.githubusercontent.com/49199690/56034394-7d5f0e00-5d27-11e9-9e0a-edb2f33b3f25.JPG)

**Comment by a17jacsv** [comment]
I can't see the problem with this issue as the lines are behaving like the should do in my opinion. The symbols are rarely that close to each other when drawing diagrams so this is pretty much redundant? @a17vikab & @a14oscna

**Comment by a17vikab** [comment]
> I can't see the problem with this issue as the lines are behaving like the should do in my opinion. The symbols are rarely that close to each other when drawing diagrams so this is pretty much redundant? @a17vikab & @a14oscna

It should still be exceptions on how the line works if someone wants to draw a diagram with objects close to each other.

**Comment by a16tobfr** [comment]
Just making a comment to clarify that this is still an issue
Could probably make a check if the relation is overlapping in any way on the left or right side of the entity, then the line should instead be drawn to the top or bottom of the relation (whichever is closest). If the relation overlaps the entities top or bottom position, the line should be drawn to the left or right side of the relation (whichever is closest).

The same logic can probably be made to other cases where this may happen.

**Comment by a18jonpe** [comment]
I don't really understand what the issue is. When trying the diagram tool I feel like the lines behave as expected. Is it possible to clarify what exactly is the issue here?

**Comment by HGustavs** [comment]
I am thinking it has to do with when the objects are very close together. 

In the case above we move the diamond very close to the entity.

In that case the line should not go to the right corner of the diamond but from the top corner of the diamond.

I assume it is quite finicky with repeating this issue.

Seems like the two elements are nearly exactly corner to corner.

It does not seem like a major issue.

How does it look if we put the two elements close, but not as close, and leave a few pixels between the two?

I say we can retire this issue if it is only a problem when the elements are nearly overlapping.

I would consider this a problem of the diagram not the engine used to draw the diagram.

**Comment by a18jonpe** [comment]
I believe this issue is solved since the problem is very hard to recreate and it is not an issue that should bother the user making diagrams.
