### ISSUE TITLE
accessed.php - Boolean operator, search

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#5882]
Expanded search function with several keyword. 

ref:
#5635

**Comment by a17andby** [comment]
Talked to gruppB2019 and they are working on a solution that will work with our `accessed.php`. They will contact me when the solution is done and we will implement their solution to `accessed.php`.

**Comment by a17poner** [comment]
Im guessing we're not getting anything from groupB and can undo the on-hold and start working on this ourselves soon? :)

**Comment by a17andby** [comment]
> Im guessing we're not getting anything from groupB and can undo the on-hold and start working on this ourselves soon? :)

Hehe, well they haven't contacted me yet. But maybe you should contact their new leader and see if they are still working on some solution?

**Comment by a17robes** [comment]
Is a boolean search needed for accessed.php aswell? I can't see the benefits of it in accessed.php, atm it's possible to search for characters.. @HGustavs 

This is how accessed.php looks atm:

![image](https://user-images.githubusercontent.com/38004435/58022276-6ae9a880-7b0d-11e9-86a6-39cd38ea4cfa.png)


This is the boolean search in resulted.php:

![image](https://user-images.githubusercontent.com/38004435/58022072-e139db00-7b0c-11e9-98f3-165e086a1bd9.png)

**Comment by a17robes** [comment]
Never mind. Reading #5635 helped me figure it out.

**Comment by a17robes** [comment]
Looking at how the the search function in resulted.php is built, it's not applicable for accessed.php. The syntax for accessed.php should be something like "name:sven and term:vt19 " instead of "markG:DuggaName".  Will finish my other issue before i try to re-write the code for accessed.

**Comment by a17robes** [comment]
After a lot of back and forth, this issue seems unnecessary in the end. Instead of searching for a name like: name:sven date:2019-04-25,  you can as it is now just enter "sven 2019-04-25".  To fix this issue, we would as mentioned before need to re-write the smartsearch function, which seems like a lot of work considering the search function works just fine as it is atm.  @a17alevu

**Comment by a17alevu** [comment]
Closing this.
