### ISSUE TITLE
Editing variants in DuggaED doesn't autofill values properly

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#5883]
When editing a variant in duggaed view the left column doesn't properly get filled with the values that the variant that is being edited has/had. 
![image](https://user-images.githubusercontent.com/49194938/56035042-54d81380-5d29-11e9-8967-f11e9683a9b5.png)
Expecting there to be values (and the amount of submission rows to be correct) in the left column(instruction file, extra parameters and submission types) which currently becomes emtpy/whatever was in there when "edit" was pressed.

**Comment by a17poner** [comment]
merged! 😺 closing!

**Comment by a17andby** [comment]
Since this issue is not closed I'm not creating a new issue. 

These changes creates new issues. For example see picture below.  

![Screenshot from 2019-05-06 21-34-54](https://user-images.githubusercontent.com/49235724/57250255-48548b80-7047-11e9-94ec-9ae54748d5a5.png)
