### ISSUE TITLE
Draging the top corner points of relations to resize it, moves the relation on the screen

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5884]
1. Draw a new relation
2. Resize it by draging the top corners
3. See how the relation gets moved while also being resized
It should only be resized, not moved.

**Comment by a14oscna** [comment]
To add on this issue; the problem is that vertical movement does not scale the object, it only moves it, while horizontal movement only scales and does not move the object. I have created issue #6180 which covers the same problem but for all affected objects and with a little more detail.

**Comment by a16jenja** [comment]
This seems to be fixed, I can't recreate this problem anymore. @a17vikab

**Comment by a14oscna** [comment]
Correct, this issues has been solved.
