### ISSUE TITLE
Move the menu bar up to the top of the page

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#5885]
Issue #5695 already adressed this issue but the menu bar has been moved down again, likely when trying to fix another issue with the menu bar.

![chrome_M43hr5kFRc](https://user-images.githubusercontent.com/49199287/56035428-74237080-5d2a-11e9-8a4c-2c139723868c.png)

**Comment by a17jacsv** [comment]
Okay, that would be great!

**Comment by a16jenja** [comment]
Issue #6020 have solved this by reducing the white space above the canvas. Therefore the menu bar is in a good place and it looks much cleaner now, so this issue is not relevant anymore.

**Comment by a17jacsv** [comment]
Agreed.
