### ISSUE TITLE
Resulted, Mail button to all visible students in the list

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#5887]
#5614 Mail button was implemented in sectioned, but it should be in resulted
It should be possible to create a mail that will be sent to all students that's currenlty visible in the list.

**Comment by HGustavs** [comment]
Im thinking we use something that works like the csv export functionality in sortabletable but only for the email column (we need a setting to tell which column is the email and a callback for generating the email headers etc)
