### ISSUE TITLE
Clicking the horizontal/vertical button on the toolbar while it is minimized

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5888]
Clicking on the horizontal/vertical button while having the toolbar minimized does not change the direction in which the toolbar is located. Instead it reopens the toolbar and the arrow which should indicate if the toolbar is minimized or not is not changed.

Note that the toolbar is always reopend vertically when this is done.
![tb0](https://user-images.githubusercontent.com/49199690/56037029-a931c200-5d2e-11e9-8989-8a4a6da19877.JPG)
![tb1](https://user-images.githubusercontent.com/49199690/56036728-ddf14980-5d2d-11e9-9a17-e2a592d92ead.JPG)
![tb2](https://user-images.githubusercontent.com/49199690/56036784-05e0ad00-5d2e-11e9-9545-a501731372e7.JPG)
![tb3](https://user-images.githubusercontent.com/49199690/56036563-720ee100-5d2d-11e9-9a5d-5c04efda8604.JPG)
![tb4](https://user-images.githubusercontent.com/49199690/56036565-720ee100-5d2d-11e9-8ae5-8d0601232580.JPG)

**Comment by a17vikab** [comment]
This issue is now solved thanks to a refactoring of the toolbar.
