### ISSUE TITLE
Diagram menubar spacing changes with different toolbar views

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#5889]
When switching between the toolbar's horisontal and vertical view, the spacing between the menubar's items changes as well. 
![menubar1](https://user-images.githubusercontent.com/37792313/56037018-9c14d300-5d2e-11e9-8c81-6d2a1b231909.png)
Above is the toolbar in vertical mode where the menu buttons at the top have a certain spacing.

![menubar2](https://user-images.githubusercontent.com/37792313/56037020-9dde9680-5d2e-11e9-85d3-d358ff88ee9c.png)
This is the toolbar in horisontal mode and the menu buttons at the top have noticeable larger margin between each other.

It doesn't break anything but is unnecessary. Can the relation between these two objects changing be in the styling?

**Comment by a17johpe** [comment]
Note: because of different image sizes, the spacing issue is not as visible as when you actually view diagram.php and test it.

**Comment by a16jenja** [comment]
This should already be solved, issue #5821 handled this. It works fine for me right now.

**Comment by a14oscna** [comment]
This issue is obsolete as the toolbar has been reworked.
