### ISSUE TITLE
Snap to grid exist in two places

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5890]
The snap to grid option appears in both the 'view' tab in the menu bar, and in the 'align' tab in the menu bar.
<img width="279" alt="snapToGrid" src="https://user-images.githubusercontent.com/49199690/56037618-0aa66080-5d30-11e9-8cfb-23dcb94fe256.png">

**Comment by a17drama** [comment]
This is due to a fix to #5763 . Should have been detected in testing.
