### ISSUE TITLE
Testing environment for each student

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#5891]
Put up your own developing/testing environment on the server so you can do future tests on the platform it is going to run on. To do this you can follow the instructions that you got through discord in the Documents channel. Instructions says to make an instance per issue but don't do that. Just make one instance used by you and use your ID when you create it. ie a17xxxxxx for both the directory and the configuration file that gives you your URL that starts with your ID. "a17xxxxx.webug.his.se:20001". If you have questions ask your closes neighbor or your supreme leader for help. Report to @17drama when you have your own instance up and running.

**Comment by a17drama** [comment]
The small guide that is written doesn't cover the SSL config but it's very similar. There are three rows at the start of the SSL config file that should be edited with your ID and path to your folder and few rows with the same procedure at the end of the file.

**Comment by a14oscna** [comment]
If anyone still needs help to set up their environment you can talk to me about it and I will help you /Oscar in group A

**Comment by a17drama** [comment]
Everyone has completed this task. Closing the issue.
