### ISSUE TITLE
Stuck in "select" mode, after right clicking diagram

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#5894]
After you right click the diagram and left click back, you get stuck in the "select" mode. Instead of having to hold the mouse button to select, you are stuck in selection without holding the button, until you decide to deselect.

Here are some screenshots showing this problem:
![Screenshot 2019-04-12 at 14 36 11](https://user-images.githubusercontent.com/38030926/56037837-9c15d280-5d30-11e9-84b9-27d21476475b.png)
![Screenshot 2019-04-12 at 14 37 27](https://user-images.githubusercontent.com/38030926/56037846-a041f000-5d30-11e9-8a88-463aba58f27f.png)

**Comment by a17vikab** [comment]
The problem seems to be exclusive to MacBook AIR. For windows and MacBook PRO does not have the same problem.

**Comment by a16jenja** [comment]
This issue is now fixed after this merge: #7422 
So this issue should probably be closed @a17vikab

**Comment by a17vikab** [comment]
> This issue is now fixed after this merge: #7422
> So this issue should probably be closed @a17vikab

I'm closing this issue in that case.
