### ISSUE TITLE
Problem with file uploading on test-server. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#5895]
When i tried to upload a pdf file on the test page i get this error message.
![image](https://user-images.githubusercontent.com/49194898/56037958-f0b94d80-5d30-11e9-97c8-ce3666c14169.png)

I think that it is some kind of server right problems, so the server will not approve the creation of directorys and files that the code wants to create.

**Comment by a17andby** [comment]
Taking over this issue after a conversation with gruppA2019

**Comment by a17andby** [comment]
This issue should be fixed. https://github.com/HGustavs/LenaSYS/issues/5902
