### ISSUE TITLE
Remove sort function for "Password" cell in access table. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#5898]
For now it is possible to sort the "password" cell in the accsess table. Why? seems pointless. 
![image](https://user-images.githubusercontent.com/49194898/56041029-0da54f00-5d38-11e9-950f-1ac51a796246.png)

**Comment by a17joaap** [comment]
I'm not certain, but maybe it sorts users who requested password reset to the top?

**Comment by a16joare** [comment]
Yeah sure that one solution, but it sounds inefficient that the user should make a request to reset their password and the admin must approve every request.  Would not an automatic password restet be a better solution?

**Comment by a17joaap** [comment]
It's up to @HGustavs. But I added sorting to the password column in #5905 in the mean time

**Comment by HGustavs** [comment]
Good idea to have the yellow ones at top/bottom when sorting.

**Comment by a17joaap** [comment]
Fixed in #5905. Suggest we close this @a17andby
