### ISSUE TITLE
Not possible to upload files inside the files tab on the test-server. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#5902]
When you try to upload a file at the "files tab" on a coures frontpage i get this error: 
![image](https://user-images.githubusercontent.com/49194898/56113922-98b45e00-5f5f-11e9-8006-191ac8e3b191.png)

I think that this issue has the same problem as issue#5895 but it is a different error message.

**Comment by a17andby** [comment]
Taking over this issue after a conversation with gruppA2019

**Comment by a17andby** [comment]
I could not recreate this issue on my test environment on the testserver. However, when I used @a16joare test environment, I got the error. I reinstalled a16joare's test environment and thereafter it worked to upload files even for a16joare.
