### ISSUE TITLE
Misleading heading in accessed.php table?

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#5912]
The `Added` heading is quite misleading as it is updated when there is a change in the record. 

Example:
When you change `Group(s)` the `Added` updates to current time. 

Maybe change the heading to something more appropriate? Or maybe even add a new column that shows when the last updated was?

**Comment by HGustavs** [comment]
Screenshot?

Unclear what heading we are talking about, the lena specific one or the browser heading?

**Comment by a17andby** [comment]
Before:
![Screenshot from 2019-04-15 11-26-57](https://user-images.githubusercontent.com/49235724/56121891-6dd30580-5f71-11e9-8793-80ff8209c17c.png)


When I update the group the `Added` column updates.
![Screenshot from 2019-04-15 11-28-23](https://user-images.githubusercontent.com/49235724/56121969-9b1fb380-5f71-11e9-9576-832e187f76bd.png)

**Comment by a17andby** [comment]
(Updated the group on the red row)

**Comment by HGustavs** [comment]
Perhaps this is the mysql updating timestamp bug

https://stackoverflow.com/questions/18962757/when-is-a-timestamp-auto-updated

Perhaps calling the column changed instead of added?

**Comment by a17maxsj** [comment]
How is this coming along? @a17robda

**Comment by a17joaap** [comment]
Seems like this already is fixed.

![alreadydone](https://user-images.githubusercontent.com/37792198/57293625-88f2ea00-70c5-11e9-8864-5b4ba91dc47b.PNG)

**Comment by a17poner** [comment]
yea, I'll close this then, fixed on c branch at least.
