### ISSUE TITLE
Buttons for adding files and links in the FileEditor are identical in apperance

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5913]
fileed.php
In the file editor, The buttons that appear for adding new files are all looking the same. It would be better if there were some kind of image in the circle which indicates what you are looking at.
![bild](https://user-images.githubusercontent.com/49199690/56116820-0ca63480-5f67-11e9-8c1a-238e823c0cd6.png)

**Comment by HGustavs** [comment]
Transparent behind white icon...

there is a style for this that I quoted in another issue, unclear why that style is not applied.

It was over-applied previously ... so that any ul/li got rainbow styling including markdown lists in the code viewer.

**Comment by HGustavs** [comment]
Aledgedly fixed in  #5761
