### ISSUE TITLE
Load functionality not yet implemented

### ISSUE THREAD

**Issue by b17robev** [HGustavs/LenaSYS#5915]
Load functionality is not yet implemented in diagram, however the UI allows us to to click on the menu-item. Fix a form of load functionality?

Note that this might not be possible to implement before #5914

<img width="197" alt="load" src="https://user-images.githubusercontent.com/37845511/56117823-36605b00-5f69-11e9-8d4d-c89400e37743.png">

**Comment by HGustavs** [comment]
Is this a stub currently?

From what I can gather from the console log, change detection seems to happen?

Is saving automatic or does it happen to local storage?

**Comment by HGustavs** [comment]
We really want automatic saving rather than manual saving?

**Comment by a17drama** [comment]
Saving is automatic but it's saved on the local machine and current browser (cache). What we want is saving to a file instead and of course with save every few minutes so when the time comes and we want to load it should be possible to do so from a file and it should work on any browser.

**Comment by a17drama** [comment]
After a meeting with @HGustavs about this issue and #5914 the conclusion is that load function is obsolete due to the fact that we have an import function. See more elaborated explanation in #5914 .

**Comment by a17robhe** [comment]
This issue seems obsolete, especially due to https://github.com/HGustavs/LenaSYS/issues/2926
