### ISSUE TITLE
Sorting of results perform strangely

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#5916]
If one sorts on the result of a specific part of a course, the result seems to be randomly sorted within the marks. If I sort on the "green" mark I would assume that greener marks i.e. VG would sort above the plain G. This does not happen.

![Screenshot 2019-04-15 10 33 59](https://user-images.githubusercontent.com/6978801/56118286-390f8000-5f6a-11e9-96f6-002c824f2dd9.png)

**Comment by b17timjo** [comment]
When a column is clicked, the call-chain makes it to newCompare via array.sort.
newCompare does not appear to function correctly, for example the following resulted in two empty strings being compared:
https://github.com/HGustavs/LenaSYS/blob/0b3972bc464df6240a4088ec74e41fcd70bad63f/Shared/SortableTableLibrary/sortableTable.js#L752-L759

**Comment by b17timjo** [comment]
In resulted the cells contain complex objects, and there is no particular functionality to sort them.

An example run:
When sorting by Fname
![5916_clicksortbyname](https://user-images.githubusercontent.com/38911528/56719644-74b40200-6741-11e9-84b3-b90f67e063e9.png)
this example slice of the data is passed to newCompare:
![5916_sortelems](https://user-images.githubusercontent.com/38911528/56719671-85fd0e80-6741-11e9-885a-681fcd33cf71.png)
and the slice is never transformed to json (bug? JSON.stringify does not mutate, should the result have been assigned?)
![5916_nonjson](https://user-images.githubusercontent.com/38911528/56719676-87c6d200-6741-11e9-9bcd-28472074d739.png)

Subsequently, the object seen in the final image above is converted into an empty string in
`firstCellTemp=$('<div/>').html(firstCellTemp).text();`

Furthermore, even if it was transformed into json, in order for it to correctly sort by the "firstname"-field in the json object, that field would have to happen to be the first element in the object when parsed as a string, which to my knowledge is neither guaranteed by the standard, nor forced via existing code.
i.e. an object such as: `"{\"grade\":\"<div class='dugga-result-div'>Maria Johansson</div><div class='dugga-result-div'>a99marjo / DVSUG13h</div><div...`

**Comment by b17timjo** [comment]
In essence: using sortabletable as a shared implementation presently assumes cells contain simple data, such as a single date or string. This assumption does not hold, and this makes the abstraction problematic.

**Comment by b17timjo** [comment]
I'm not sure how to work around this. Higher-order functions could be used, allowing the appropriate comparision function to be passed - but this requires knowledge of the actual data passed to the function, which is kept in sortabletable, and thus require white-box knowledge (or a well-documented and stable interface).

Sortabletable should probably be resdesigned to a much smaller scope - perhaps just producing an HTML table-element with "magic headers" given a datastructure describing the desired table? Sorting would then be on the callers side: transforming the local datastructure to a re-sorted representation and replacing the old `<table>` with a new one.
