### ISSUE TITLE
Feedback on repeated failed login

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5917]
The colours of the fields in the regular login change to red on the first failed login attempt, but on further failed attempts there is no feedback, either by message or colour.

Suggestion: pulse the colours, or briefly display a message to indicate the input was processed.

**Comment by HGustavs** [comment]
I would use an alert as this is visible on all operating systems and also terminates execution.

**Comment by HGustavs** [comment]
...Clicked wrong button... issue is still open.
