### ISSUE TITLE
Adding File buttons should appear when hovering

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5918]
fileed.php
Some users seem to have an issue with not being able to view the different buttons that should appear when clicking the add file/link button. Instead they are directed to the view that only should appear when the button is clicked twice.
If the sub buttons appeared when the mouse are hovering the add file/link button this would not be a problem.
![plus](https://user-images.githubusercontent.com/49199690/56119093-b25ba280-5f6b-11e9-8a22-2cb072129196.JPG)
Directed here directly instead of being able to see the different buttons:
![fileadd](https://user-images.githubusercontent.com/49199690/56119178-dcad6000-5f6b-11e9-8169-88d993bf6d66.JPG)

**Comment by a17adasy** [comment]
Have tested and seems like this issue is fixed. E.g the buttons appear when hovering.

@b17nicsv I guess this issue can be closed?

**Comment by b17nicsv** [comment]
Closing this because it is already solved.
