### ISSUE TITLE
searching for files does not seem to work

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5922]
fileed.php
It does not seem possible to find any files at all in the file editor, even after trying to upload a new file.
![searchingForFiles](https://user-images.githubusercontent.com/49199690/56119658-d66bb380-5f6c-11e9-84ce-5cd7a70ba6db.JPG)

**Comment by a16hiwah** [comment]
on my server everything works as it should!
![bild](https://user-images.githubusercontent.com/37792852/57608680-b203f680-756d-11e9-9d2f-ef6932ef3393.png)

**Comment by c17julka** [comment]
Searching works for me too. It seems like this was an issue that has been fixed but was never closed.

**Comment by a17adasy** [comment]
Works fine here too, I guess this issue can be closed @b17nicsv ?

**Comment by b17nicsv** [comment]
Closing this because it isn't an issue anymore.
