### ISSUE TITLE
Wrong URL to LenaSYS git repository on courseed.php

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#5923]
On `courseed.php` there is a old URL (https://github.com/HGustavs/LenaSYS_2014) to this git repo. Even though git redirects the user to the correct url this should be updated to prevent future issues.

**Comment by a17adajo** [comment]
https://github.com/HGustavs/LenaSYS/blob/5803cb172f692681c9a15014cd190bf9c60a64f3/DuggaSys/courseed.js#L336

**Comment by a17andby** [comment]
Fixed and merged

https://github.com/HGustavs/LenaSYS/pull/5927
