### ISSUE TITLE
Uploading file to the file editor takes you to filereceive.php

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5924]
This is the view that you are presented after you have done a file upload to the file editor.
Instead of this you should probably simply get a notification that the file was uploaded or not
![uploadFile](https://user-images.githubusercontent.com/49199690/56120522-8c83cd00-5f6e-11e9-9742-8ebfef1a63fa.JPG)

**Comment by HGustavs** [comment]
Firstly, this view is not the problem, allowing PNG is the bug in this specific case.

This should be shown if there is an upload error, but perhaps in a slightly more usable manner?

**Comment by HGustavs** [comment]
Related to issue #5899

**Comment by a18felen** [comment]
This is not an issue, it is working as intended. fileed.php redirects to this website in case there is an error and if the file gets uploaded it redirects back to fileed.php. The related issue#5899 is already so this issues should just be closed.
