### ISSUE TITLE
Toolbar should have fixed buttons for switching diagram modes

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#5934]
When in the toolbar's horisontal mode, switching between different diagram modes (e.g. ER, UML) results the left and right arrow buttons moving around since it's centered relative to the size of the toolbar.
![toolbarhoris1](https://user-images.githubusercontent.com/37792313/56127944-9dd4d580-5f7e-11e9-930e-ccb77ec2b490.png)
![toolbarhoris2](https://user-images.githubusercontent.com/37792313/56127947-a0372f80-5f7e-11e9-856d-4bb8c6be4a51.png)
The problem is that when you're trying to get to a specific toolbox mode, you have to move the cursor every time to find the buttons again. This is a minor user experience issue.

**Comment by HGustavs** [comment]
I think this option should be moved to the menu instead since very rarely we change type in a diagram

Separate issue

We should not allow ER entities in a uml diagram and vice versa

Free draw should be available in both / either

**Comment by a17jacsv** [comment]
Remove all-option in the toolbar: #6105 
Remove the free-option in the toolbar: #6106

**Comment by a17drama** [comment]
@a17vikab Considering this is a parent issue for those that you are assigned this goes to you so we can tag all of them in the pull request and close all of them.

**Comment by a17jacsv** [comment]
I approve this...
