### ISSUE TITLE
Unable to press FAB in sectioned.php when there are items below it

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#5935]
When you try to press the FAB in sectioned.php nothing happens and the cursor doesn't change when there are rows behind it (example in picture below)

![fab](https://user-images.githubusercontent.com/37834592/56128636-872f7e00-5f80-11e9-865b-1112e770af1f.PNG)

**Comment by a17andby** [comment]
Fixed and merged. Closing.
