### ISSUE TITLE
Sub-fabs in sectioned.php appear behind headers/sections

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#5937]
At the moment, sub-fabs appear behind headers/sections as seen in the image below which I believe is unintended

![Capture](https://user-images.githubusercontent.com/37834592/56128968-64ea3000-5f81-11e9-87f2-b7d7a1bd76c4.PNG)

**Comment by a17joaap** [comment]
Samme issue as #5935 ? Z-index maybe?

**Comment by b17carma** [comment]
I tried using a higher Z-index on the button than the section but it didn't solve the issue so I'm unsure

**Comment by HGustavs** [comment]
No idea.

Could it have something to do with the ul/li that the ul is lower???

Definitely a bug imho

**Comment by a17andby** [comment]
Fixed and merged. Closing.
