### ISSUE TITLE
Login - All functionalitys (Login, Logout, Attempts, Press "Enter", "Remember me" and so on

### ISSUE THREAD

**Issue by a13henhu** [HGustavs/LenaSYS#594]
An issue has been identified, the Login button is not "working". When clicked "Login" it wont close and refresh the browser. And while manually refresh your browser, you'll be logged.

**Comment by a13jansa** [comment]
iam on it!

**Comment by a13henhu** [comment]
NEW CODE: onclick="processLogin('CODV'); window.location.reload();return false;"

**Comment by a13henhu** [comment]
#678

**Comment by a13erilj** [comment]
The problem has not been fixed properly, this is just a workaround.

**Comment by a13chrju** [comment]
can I provide a solution :P?

**Comment by a13henhu** [comment]
![alert](https://cloud.githubusercontent.com/assets/11715477/7061983/e03f6ec8-de98-11e4-8794-cc01e36450c1.png)

The alert works now, but still working on how many attempts you're able to login

**Comment by a13henhu** [comment]
#731

**Comment by a13henhu** [comment]
#920 Remember me, need a fix for this issue

**Comment by a13henhu** [comment]
UPDATE: Attempts try to login is now working

**Comment by c13caral** [comment]
I will close this issue. And open issue #1236 for the forgot password doesn't work. And it already exists a issue for remember user #920 
But this issue is kinda messy. I think it is better to make a lot of small issue for the loggin instead of one big.
