### ISSUE TITLE
Improve user importing instructions in accessed.php

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#5940]
![image](https://user-images.githubusercontent.com/49194938/56129809-73394b80-5f83-11e9-9418-46a9b7b18592.png)

As mentioned in #5698 the importing interface is fine as it is but the instructions/example for how to import is wrong. Now its a type of csv (not sure what it looks like) and not what it currently says on the page it is. It should probably be updated to help people new to lenaSys in the future.

**Comment by HGustavs** [comment]
~~~
18972221-8475;Piraten-Nilsson; Sven;92337 ; 2019-01-21 - 2019-03-31 ; 50% ; Normal;Ej påbörjad;WEBUG
18531603-5473;Grishufvud; Egon;92337 ; 2019-01-21 - 2019-03-31 ; 50% ; Normal;Registrerad; ej avklarad (1);DVSUG
~~~

**Comment by a17poner** [comment]
Im still not entirely sure what that would look like in the "type format" 

> SSN<tab>Lastname,<space>Firstname<tab>CID<tab>Ny<tab>PID,<space>Term<tab>Email<linebreak>

Even though it sort of means you do most of the work on this issue could you show me the format with that sort of typing? I find it quite hard to understand what the last few entries in csv are/mean.

**Comment by a17joaap** [comment]
Very confused with that csv format, does not seem to work with the code at all. For example, in accessedservice.php:

                  $firstname = $user[1];
                  $lastname = $user[2];
                  $className = $user[count($user)-2];
                  $saveemail = $user[3];
                  $regstatus = $user[count($user)-1];

This would mean that firstname=Piraten-Nilsson, lastname=Sven, className=Normal, saveemail=92337

I'll go ahead and edit the instructions, but this should perhaps be looked at also
