### ISSUE TITLE
Show coordinates without decimals when zooming

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#5941]
I would like the coordinates should show like the picture 1 below and zooming should not affect the writings of the coordinates. Remove the decimals for a smoother view and use. It should view as the second picture below.

<img width="550" alt="Skärmavbild 2019-04-15 kl  13 35 49" src="https://user-images.githubusercontent.com/37792795/56129801-6fa5c480-5f83-11e9-8149-2da9aac547a7.png">

<img width="318" alt="Skärmavbild 2019-04-15 kl  13 35 25" src="https://user-images.githubusercontent.com/37792795/56129897-c14e4f00-5f83-11e9-8a76-c4592dd976d1.png">

**Comment by HGustavs** [comment]
One decimal.

**Comment by a17jacsv** [comment]
Yes, limit the decimals to one would be perfect.
