### ISSUE TITLE
Show origo in developer mode

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#5942]
Origo should be shown i developer mode and no it should be static. That means it's pinned to the canvas and no matter what it's stuck on the same point as it was from the start. Please use the proper "icon" for origo.

**Comment by HGustavs** [comment]
Im thinking that we show the "page" or "the first grid line with a thicker colored line" so that it moves
with scrolling.

Below is a mock-up of my two options....

![Screenshot 2019-04-16 08 24 17](https://user-images.githubusercontent.com/6978801/56186824-08d6e880-6021-11e9-89ff-96105a1add65.png)

**Comment by a17drama** [comment]
Sounds like a good idea with the lines. Implement those please.
