### ISSUE TITLE
Ruler for X and Y axis

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#5943]
Add rulers that toggle via the view menu (can be show or hidden). Rulers should mark the current mouse position and also mark the positions of the selected entities. Don't forget that rulers have to scale with the zoom function.

**Comment by HGustavs** [comment]
Good suggestion.

Rulers should be at top of screen rather than top of diagram when scrolling.... and look like photoshop rulers

![Screenshot 2019-04-16 08 14 40](https://user-images.githubusercontent.com/6978801/56186468-be08a100-601f-11e9-98bc-5ec68cb6a8ce.png)

**Comment by a14oscna** [comment]
Just going to reference the issue where ruler was mentioned in the past, which contains further image examples. #2458

**Comment by a18antsv** [comment]
The layout of diagram.php needs to be changed to make it possible to position rulers in a good way. Right now, the layout is very poorly designed making it hard to do the right positioning.

**Comment by a18antsv** [comment]
Issues were created to divide this into small steps so this bigger one can be closed:
#9060 
#9061 
#9062 
#9063
