### ISSUE TITLE
Test dugga table size

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#5948]
When window shrinks in test dugga.
![image](https://user-images.githubusercontent.com/37792766/56131294-54d54f00-5f87-11e9-83f3-ba14666cdcf8.png)

**Comment by HGustavs** [comment]
Feel free to make an effort to make it more readable, but dont put too much effort into this as it is not in the mobile-centric parts i.e. student facing parts.

In some older issue we outlined that only student facing parts of the pages should be fluid, and the teacher facing stuff should assume desktop computers or laptops.

**Comment by a17alian** [comment]
This table has been removed when "hasMagicHeadings" was set to false, in Grupp C issue #5979 - Fix for "ghost table" and missing heading on tests, see committ a739bdb. 

Closing this issue
