### ISSUE TITLE
Remove the "ghost table copy" that appears when you sort tables. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#5953]
When you try to sort a column inside the files tab a ghost table will appear. Here is an example when it happens. https://media.giphy.com/media/39sYXeXFsMHXPHxR48/giphy.gif

When the sort function is called it creates a copy of the table and then hides it. I think the problem is that the copy does not get invisible fast enough, which makes it flicker on the screen

**Comment by HGustavs** [comment]
I think that this has to do with the magic headings?

Perhaps hiding that element by default before adding content remedies this?

Or where does it come from?

**Comment by a17andby** [comment]
Fixed and merged. Closing.
