### ISSUE TITLE
Add Easier Zoom Functionallity

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#5955]
It should be short commands that make it easier and faster to zoom in or out in the canvas. Maybe something like: (**Ctrl +**) / (**Ctrl -**) or something similar. However, this issue needs to be "On Hold" just because of #5826 might refactor the zoom-method and it would be best to wait for it to be finished.

@HGustavs should have the final say about what the short command should be.

**Comment by HGustavs** [comment]
Doesnt the browser capture ctrl+ ?

We dont want anything that conflicts with browser built-in stuff.

I like ctrl+ since it is like illustrator/photoshop/browsers so it is a well known key combo.

**Comment by a17vikab** [comment]
The browser is using ctrl+, therefore I want something with the same function as the browser-zoom but only for the zoom-function in the canvas. I only ask for suggestions, e.g mouse-scroll while the mouse is inside the canvas?
