### ISSUE TITLE
Make the searchfield bigger

### ISSUE THREAD

**Issue by a17okaoz** [HGustavs/LenaSYS#5956]
The serach-area is to small. Make so the grey border around will get bigger and make more space for the letters
<img width="259" alt="b1" src="https://user-images.githubusercontent.com/37792681/56136113-653ef700-5f92-11e9-8070-f3453837779c.PNG">

The letters get exactly the place in the box I will be better if there was little space between the letters and the border

**Comment by HGustavs** [comment]
I agree.

We should also examine the possibility of putting an optional search box (usable in many places) in the navigation menu...

or at least making a test version to see if it looks like crap.

Currently when the search field scroll out of view they are nearly useless.
