### ISSUE TITLE
Possible to remain and access the access page as guest.  

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#5964]
If you go to the access page as admin and logout is it still possible to remain on the page. You can't see the content on the page, but a relocation to the front page would maybe be better?

It's also possible to copy the url and access the page. 

Here is a image when logged in:
![image](https://user-images.githubusercontent.com/49194898/56191212-3ecd9a00-602c-11e9-8af0-922358d4125c.png)
Here is a image when you logout:
![image](https://user-images.githubusercontent.com/49194898/56191243-4d1bb600-602c-11e9-9a0c-99def787529f.png)

**Comment by b17annni** [comment]
#6134

**Comment by a17alevu** [comment]
I feel like when you logout you sahould directly be moved to the homepage as a guest.
