### ISSUE TITLE
Problem when moving two marked entites

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#5966]
**As the title above: problem when moving two marked entites. Must be BUG?**

_Watch gif below:_
![exempel](https://user-images.githubusercontent.com/37792795/56193185-53ac2c80-6030-11e9-8d99-3c7455e2d233.gif)

**Comment by a17vikab** [comment]
It looks like it is a local bug, but I can recreate the scenario by holding "ctrl" and trying to move the selected objects after clicking on the second object. However, that is expected in my opinion. If someone clicks an object with ctrl it should act as it does right now. 

Suggest closing this issue.

**Comment by a17jacsv** [comment]
Yes, it must have been a local bug. It works as expected when I tried it again. I consider this issue closed.
