### ISSUE TITLE
freeDraw performs oddly when double clicking

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5967]
Some odd behaviour occur when double clicking while drawing a 'free draw' object. Should probably not be able to make a text box while in the process of free drawing.
![freeDraw doubleClick0](https://user-images.githubusercontent.com/49199690/56193639-6b37e500-6031-11e9-9b29-d3ddbe821c3f.JPG)
![freeDraw doubleClick1](https://user-images.githubusercontent.com/49199690/56193638-6b37e500-6031-11e9-94b2-4cb4ebee2415.JPG)

**Comment by HGustavs** [comment]
Unclear, this can do almost anything....

I would say that it should make two dots, no text box that seems like a bug.

**Comment by a17johpe** [comment]
Since Create Text now exists as a button, should double click still create text on the canvas? In that case this still needs to be fixed.

**Comment by a17vikab** [comment]
> Unclear, this can do almost anything....
> 
> I would say that it should make two dots, no text box that seems like a bug.

At the moment, if you double click, you get two points in the same place. Therefore, I am closing this issue.
