### ISSUE TITLE
Drawing a text box after having drawn another text box makes the indicator box start from the last text box.

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#5968]
As the headline states, after you have made a text box and then attempts to draw another one. The lines which should indicate the size of the text box starts from the previous text box. It does not seem to matter where you are clicking on the canvas.
![textBoxIssue](https://user-images.githubusercontent.com/49199690/56193968-2e202280-6032-11e9-95dd-b876a99d4758.JPG)

**Comment by c17matjo** [comment]
@a16tobfr I can't seem to replicate this issue on a recent gruppA2019 branch. Could you verify that this issue is still present? It seems the text box functionality has been changed recently so this issue might already have been fixed.

**Comment by a16tobfr** [comment]
Yes, it seems like this has been solved in some other issue. I think this issue can be closed
