### ISSUE TITLE
Implement markdown in the editor text field

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#597]
Choose convention and implement a possibility to use a markdown to style comments and other parts of code

**Comment by b12simsa** [comment]
Suggestion to convention upploaded to the groups google drive (Markdown manual.docx).

**Comment by b12simsa** [comment]
Markdown suggestions

#### Lines
"***", "___" , or "---"horizontal line 
Example:
***

#### Headings
\#  Heading 1 
Example: 
# 1
\#\# Heading 2
Example:
## 2
\#\#\# Heading 3
Example:
### 3
\#\#\#\#  Heading 4
Example:
#### 4
\#\#\#\#\#  Heading 5
Example:
##### 5
\#\#\#\#\#\#  Heading 6
Example:
###### 6

#### Text section
\~~~ 
text section
\~~~
~~~~
text section
~~~~

#### Lists
\* text or \- text bulletin list
Example:
* 1
* 2

#### Link
"[name]: /url "title" [name]" creates a link

#### Italics
\*text\*, \*text text\*, \_text\_, or \_text text\_
<br/>Example:
*text text*

#### Bold
\**text*\*, \*\*text text\*\*, \_\_text\_\_, or \_\_text text\_\_
<br/>Example:
**text text**

#### Bold and Italics
\*\*\*text\*\*\*, \*\*\*text text\*\*\*, \_\_\_text\_\_\_, or \_\_\_text text\_\_\_
<br/>Example:
***text text***

\!\[name]\(/url "title"\) inserts image
