### ISSUE TITLE
Change color of Tablerow in Showdugga.php

### ISSUE THREAD

**Issue by a17robes** [HGustavs/LenaSYS#5973]
As you can see the table body has a grey background color while the table row far down has a white one.

![image](https://user-images.githubusercontent.com/38004435/56196439-1eefa380-6037-11e9-8ac0-7c3abca795d4.png)
![image](https://user-images.githubusercontent.com/38004435/56196481-3333a080-6037-11e9-8bb0-f94e348c306c.png)

**Comment by b16johso** [comment]
Related: https://github.com/HGustavs/LenaSYS/issues/5931

**Comment by a17maxsj** [comment]
Has been fixed. Closing... 🍰
