### ISSUE TITLE
Hovering over the navButtons on the header, in accessed.php, will generate a white empty dropdown field.

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#5975]
Before hovering over the "tratt" and the arrows.
![image](https://user-images.githubusercontent.com/49199285/56196894-08961780-6038-11e9-9ab0-e7c2d4f24e03.png)

The white empty field generated after hovering over the "tratt" and arrows. 
![image](https://user-images.githubusercontent.com/49199285/56196982-311e1180-6038-11e9-8a14-b2514fd9dea1.png)

![image](https://user-images.githubusercontent.com/49199285/56197042-4a26c280-6038-11e9-93f8-2a4e22d309f0.png)

**Comment by a17alevu** [comment]
You have to be in a course site and then enter the access editor.

**Comment by a17robes** [comment]
Couldnt see that it affected other pages, please test this!

**Comment by a17andby** [comment]
Fixed and merged. Closing.
