### ISSUE TITLE
Remove old commented code in duggaedservice

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#5981]
Line 55

**Comment by a17alian** [comment]
Sub issue: #6174

**Comment by b17timjo** [comment]
The code was commented out 7 months ago in 
https://github.com/HGustavs/LenaSYS/commit/c82087b8fe124fef13c2a627889a73c300e5a75f
and as such presently has no effect, see:
https://github.com/HGustavs/LenaSYS/blob/e23ec0048d21debc45e356e70cc53a4c9f0381b3/DuggaSys/duggaedservice.php#L55-L80
