### ISSUE TITLE
Problem while rightclicking object

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#5982]
If the user right-clicks an object and later move out of the object and right-clicks or left-clicks, the object will move to the mouse. 

Problem video: https://gyazo.com/d8e8551f935602359ca87732d5ff67f2

**Comment by a14oscna** [comment]
This issue seems to be browser specific for Chrome. In Firefox and Edge there are no problems.

**Comment by a17jonro** [comment]
I cannot replicate this issue and since it seems to have to do with the right click menu, this should be resolved and shouldn't be a problem anymore. Can we close this issue?

**Comment by a17jonro** [comment]
@a17vikab

**Comment by a17vikab** [comment]
> I cannot replicate this issue and since it seems to have to do with the right click menu, this should be resolved and shouldn't be a problem anymore. Can we close this issue?

You are correct, this is no longer a problem.
