### ISSUE TITLE
There are no example files or ID in codeviewer

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#5988]
To be able to work with code viewer we need to have example files in place on the web servers. The following image maybe points in the right direction for a solution. There need to be example files for many different languages, e.g: XML, HTML, CSS, JS, PHP and so on. There might be example files in place but the usage of their IDs might be wrong.

There are many issues for CodeViewer that need this to work.

![](https://i.gyazo.com/c69428a1a590d44e68c54bd882305e14.png)

**Comment by a17joaap** [comment]
Unable to recreate this issue, codeexamples are added with testdata.sql. From reading the code I think this error message occurs when no such data is present.

**Comment by a17alevu** [comment]
All the files are on available in the testfiles folder, closing this issue.
