### ISSUE TITLE
UML classes should resize to longest existing string

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#5994]
For a greater experience it would be nice to have the UML classes resize back down when a long string of text is removed. Currently it only expands to fit a long string of text as shown in the images, but when you delete the longest string it keeps the same size.
![longclass1](https://user-images.githubusercontent.com/37792313/56210567-60dc1200-6056-11e9-80d4-7367dc49275b.png)

![longclass2](https://user-images.githubusercontent.com/37792313/56210571-62a5d580-6056-11e9-89fa-802b1a153cbe.png)

**Comment by HGustavs** [comment]
Im thinking that it should be the set width drawn by user and that longer text should be clipped.

**Comment by a17drama** [comment]
I totally agree with the clipping considering methods can have long names and this would make the UML look like the Frankenstein's monster with all the different sizes of classes.

**Comment by HGustavs** [comment]
Clipping refers to making the class symbol a maximum size and hiding the overflow.

I would clip in a rectangle a few pixels inside the border of the symbol

https://www.w3schools.com/tags/canvas_clip.asp

**Comment by b18mikfr** [comment]
@HGustavs Thank you! I was also thinking regarding the functionallity of resizing, Should the different symbol uml objects be resized per automatic to the longest string always? or should the user be able to resize out side of the longest string? 

I was thinking of automatically resizing to the longest string _**_when_**_ changes are done to the symbol class then the user can resize the symbol as they will? Would this suffice as a change?

**Comment by HGustavs** [comment]
Never resize imho

Always setting the size of the symbol using the normal box-sizing functionality.

**Comment by a18kaswi** [comment]
PR #7942 failed acceptance-test @b18mikfr @a18andtu

**Comment by b18mikfr** [comment]
The UML Symbols now get clipped if the user decides to resize the symbol size with the box sizing functionality
