### ISSUE TITLE
AccessED: Automatically import user when created

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#5999]
When importing a user that doesn't exist yet to a course, we have to first create them and then import them. 

Would be a good idea to skip that extra step no? @HGustavs

**Comment by a17maxsj** [comment]
Status on this?

**Comment by a17joaap** [comment]
Can put this on hold, not sure if this is something they want

**Comment by a17maxsj** [comment]
bump @HGustavs  continue or close?

**Comment by a17joaap** [comment]
Closing this, existing code already does this
