### ISSUE TITLE
Lenasys is synced to the wrong timezone

### ISSUE THREAD

**Issue by a17anter** [HGustavs/LenaSYS#6001]
When I worked on another issue and tested it with submitting "duggor" I noticed that the timezone were GMT+2 hours. At the moment we are GMT+1 so the submission has a 1 hour offset. See attached screenshot.

![Lenasys timezone error](https://user-images.githubusercontent.com/49204317/56218647-a3f1b180-6065-11e9-8300-01eacd5881e7.PNG)

**Comment by a17pongo** [comment]
@HGustavs when retrieving the time, is the servers time settings used?

**Comment by c17julka** [comment]
But we are indeed using GMT+2, CEST is 2h ahead of GMT, which makes it GMT+2.
