### ISSUE TITLE
Time sheet: add week number when uploading data

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6002]
As per Henriks [request](https://github.com/HGustavs/LenaSYS/issues/5628#issuecomment-482473714).

When posts get uploaded to the database, the week number of the post should be added.

This means adding week to the insert statement on row 146 in filereceive_dugga.php, and calculating the week number from the 'day' value and adding it with bindParam.

**Comment by a17joaap** [comment]
Fixed in #6255

**Comment by a17andby** [comment]
![fixed](https://user-images.githubusercontent.com/49235724/56724652-b77ad780-674b-11e9-8a90-853eeb9d1140.jpg)
