### ISSUE TITLE
showDugga.php - Blank page - 500 internal error

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#6008]
`/LenaSYS/DuggaSys/contributionservice.php:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

URL: /LenaSYS/DuggaSys/showDugga.php?did=9999&cid=4&coursevers=1338&moment=2041&segment=0&highscoremode=1&comment=UNK&deadline=null

![Screenshot from 2019-04-17 09-42-16](https://user-images.githubusercontent.com/49235724/56270098-a7347e00-60f5-11e9-89d7-949fc5d495e0.png)

Getting to the blank page by clicking on:  

![Screenshot from 2019-04-17 09-52-39](https://user-images.githubusercontent.com/49235724/56270504-989a9680-60f6-11e9-9415-c048c1f14c43.png)

**Comment by a17poner** [comment]
This might be related to #5624 I'll investigate!

**Comment by a17poner** [comment]
What sort of dugga/quiz is "New Code" that you clicked to get to the page with the error?

**Comment by a17joaap** [comment]
This is because of contributionservice.php looking for a database that doesnt exist. See #5806
