### ISSUE TITLE
"Toggle A4 Holes" should not be displayed if "Display Virtual A4" isn't active

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#6012]
In View, it should not be possible to see the option to Toggle A4 Holes while Display Virtual A4 isn't active. It creates confusion for the user at the moment and should be hidden until the display virtual A4 is active.

![issue1](https://user-images.githubusercontent.com/37792464/56270989-b5839980-60f7-11e9-9bb3-59bddfa4791e.png)

**Comment by a17jacsv** [comment]
I agree...
