### ISSUE TITLE
Apperance of the menu bar while scrolling down

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6013]
1
Initial apperance of menu
![menu0](https://user-images.githubusercontent.com/49199690/56270848-689fc300-60f7-11e9-8991-efb3f2f98559.JPG)
2
After scroll down
Now it looks like the menu gets detached while scrolling.
![menu1](https://user-images.githubusercontent.com/49199690/56270849-689fc300-60f7-11e9-865c-6b680e997308.JPG)
3
The entire whitespace should follow the menu down while scrolling to make it look better.
![menu2](https://user-images.githubusercontent.com/49199690/56270851-689fc300-60f7-11e9-8782-5aba912368ef.JPG)

**Comment by a17jacsv** [comment]
I agree. This should be fixed.

**Comment by a17jonro** [comment]
The fix for issue #6020 in #6057 has fixed this issue since we can no longer scroll in the diagram.
