### ISSUE TITLE
Hover effect on buttons in toolbox

### ISSUE THREAD

**Issue by a17okaoz** [HGustavs/LenaSYS#6015]
When the pointer is above a button in the toolbox make so the button have a hover effect that will show witch button you are on.

**Comment by a17drama** [comment]
You mean like a tool tip?

**Comment by a17okaoz** [comment]
Tool tip already exists. I think like the background color will change to when the pointer is over a button. The hover color could be the same as when a button is clicked

**Comment by a14oscna** [comment]
If hover is the same as button clicked, you would not be able to differentiate between a click and a hover, which could be annoying for people using a touchpad who generally have less physical feedback already. I suggest just changing the cursor icon or similar.

**Comment by a17okaoz** [comment]
The color could be a lighter tone of the existing color that is now. Just a simpel visiuell effect that will help the user a little if they miss the tool tip below
