### ISSUE TITLE
Coordinates are not relative to origo / Y-value always negative

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6016]
Currently the coordinates on the diagram are relative to the diagram frame and not the origo. However, if top-left is supposedly the 0,0 cooridnate, moving the cursor further down should result in a positive Y-value, but that is not the case. In the image below origo was moved down close to the coordinates frame and the cursor was at the position of the red circle. See that neither the X or Y values are related to the position of origo and also that the Y-value is negative. 
![needscursor](https://user-images.githubusercontent.com/37793141/56272581-5758b580-60fb-11e9-84bb-28add6bbde04.PNG)

**Comment by a17jacsv** [comment]
Interesting...
