### ISSUE TITLE
Add another click functionality for "choose zoom"

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#6018]
Right now you can click the text "choose zoom" to get the options for zooming. However you should also be able to click the arrow to get the options.

![Capture9](https://user-images.githubusercontent.com/37792271/56273416-fa5dff00-60fc-11e9-83ad-ca770b8e0aa6.PNG)

**Comment by a17jacsv** [comment]
Seems like a small matter, but I agree that the arrow should be able to be clicked.

**Comment by a17drama** [comment]
This arrow should be kept after solving: #6143 . It's nice to be able to chose fixed points from the line.

**Comment by a17johpe** [comment]
Is this still something we want or can it be closed?

**Comment by a14oscna** [comment]
This issue is obsolete and will be closed now.
