### ISSUE TITLE
You should be able to access the menu bar above the diagram using only the Tab key

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6021]
As with any site, you should be able to move through the main content of a page only using the tab key as it allows users with no mouse / steadiness-related disabilities to navigate the page. As of right now if you navigate using tab key, the menu bar above the diagram is completely skipped in the sequence of content, this should be changed. Image below illustrates the menu and the options that should be available, but aren't.
![user interraction](https://user-images.githubusercontent.com/37793141/56275161-68f08c00-6100-11e9-9d1a-a21ef425e304.PNG)
Furthermore this issue could be expanded to cover more options, like the log-in button in the top right corner of the page.

**Comment by a17jacsv** [comment]
I agree with you. This should be fixed.

**Comment by a14oscna** [comment]
This should be solved using the tabindex attribute, which essentially adds an element to the list of elements that the user will list through when "tabbing" through the page.

**Comment by o18marka** [comment]
Solved using the tabindex attribute as mentioned in comment above
