### ISSUE TITLE
All sortable tables broken in w17 merge

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#6027]
All the sorrtable tables have broken in the w17 test merge.
![image](https://user-images.githubusercontent.com/49194938/56276563-02b93880-6103-11e9-8f89-6a811764fa69.png)

**Comment by a17poner** [comment]
each page with a table have a common error at sortableTable.js:440 and an individual error in their own js files.

- resulted at resuilted.js:705
-  duggaed (tests) at duggaed.js:426
- fileed (files) at fileed.js:69
- Accessed (access) at accessed.js:389

**Comment by a17pongo** [comment]
this issue was fixed by issue #6039
