### ISSUE TITLE
Sort by grade not working, styling also needs to be fixed

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#6030]
Sorting by grade in resulted is not working. The styling is also overlapping the heading and needs to be corrected
<img width="224" alt="Skärmavbild 2019-04-17 kl  11 31 00" src="https://user-images.githubusercontent.com/37792256/56277345-76a81080-6104-11e9-999d-80e66593891a.png">

**Comment by a17pongo** [comment]
Style has been fixed and merged in #6114.
Issue  #6128 has been created for the sort by grade.
