### ISSUE TITLE
Menu-item who brings back the toolbar

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6031]
The toolbar in the diagram is shown when opening the file. Sometimes it disappears for unknown reasons and you can get it back by refreshing the page, that shouldn't be necessary. It can be scary for the user to refresh and all their content might be gone.

Please implement a menu-item in the section "view", who will "bring" back the toolbar. 

<img width="375" alt="Skärmavbild 2019-04-17 kl  11 39 34" src="https://user-images.githubusercontent.com/37792795/56277942-968c0400-6105-11e9-8571-d64f9bc35da3.png">

**Comment by a17drama** [comment]
This issue could be solved together with #6073 .
