### ISSUE TITLE
Dropdown menu buttons gets error on accessed.php

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#6037]
![image](https://user-images.githubusercontent.com/37792321/56281419-d9050f00-610c-11e9-8c0c-35c69d3f6f19.png)
 ![image](https://user-images.githubusercontent.com/37792321/56281413-d2769780-610c-11e9-9c5c-561bd596e3d5.png)

Hovering over these dropdown menu buttons in accessed.php results in these errors.

**Comment by a17andby** [comment]
Fixed and merged. Closing.
