### ISSUE TITLE
Key-binds are not mapped correctly for arrow keys

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6038]
Currently in the diagram when you want to move any drawn object using the arrow keys, their bindings are wrong. They also interact with the scrollbar on the page if present, which should not happen if an object is selected. 
**Up**-arrow moves object **down**.
**Down**-arrow moves object **right**.
**Left**-arrow moves object **up**.
**Right**-arrow moves object **left**.

EDIT: I did not attach the W17_test label as the bug was confirmed present pre-merge.

**Comment by a17jacsv** [comment]
Oh yes, that needs to be fixed...
