### ISSUE TITLE
first row in access and file table is missing. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6040]
The first row in access and file table is missing. 

![image](https://user-images.githubusercontent.com/49194898/56283310-a6114a00-6111-11e9-9039-b628eb5d17f8.png)

**Comment by a17andby** [comment]
If this error comes from SortableTable.js, gruppB2019 owns it.

**Comment by a17pongo** [comment]
@a17andby has this issue been resolved after merging the fix?

**Comment by a17andby** [comment]
@a17pongo Yes you are correct. Closing this issue.
