### ISSUE TITLE
Size column in files table sorts wrong. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6042]
Size column sortis wrong. It only sorts on the first digit. 

![image](https://user-images.githubusercontent.com/49194898/56283440-0dc79500-6112-11e9-8f04-172481c6ebab.png)

**Comment by c17julka** [comment]
This is very likely to be due to #6039, which is currently being worked on.

**Comment by c17julka** [comment]
Solved on #6039
