### ISSUE TITLE
Unable to see top text in dugga submission (showDugga.php)

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6044]
As seen in the image, you can't see the top text in a txt submission. This was tested with the contribution dugga so I'm not sure if it affects other duggas too.

![Capture](https://user-images.githubusercontent.com/37834592/56283890-3c923b00-6113-11e9-973a-93120401ff65.PNG)

**Comment by a17joaap** [comment]
Is this issue related to #6040 ? Maybe a styling issue with tables?

**Comment by a17andby** [comment]
If this error comes from SortableTable.js, gruppB2019 owns it.

**Comment by a17joaap** [comment]
Took a look, it's not a sortabletable in the submissions. Must be something else.

**Comment by a17joaap** [comment]
Fixed in #6066

**Comment by a17andby** [comment]
Since this should already be fixed I'm closing this issue.
