### ISSUE TITLE
FABs should show sub-fabs on hover instead of on mousedown

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6045]
At the moment, there's nothing indicating that you can hold down on a FAB to get other sub-fabs to show. Using hover instead of mousedown might be more suitable?

**Comment by b16johso** [comment]
https://material.io/design/components/buttons-floating-action-button.html#extended-fab

**Comment by a17andby** [comment]
Fixed and merged. Closing.
