### ISSUE TITLE
Sorting in access table not considering ÅÄÖ

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6046]
For example: Åsa shouldn't be first here.
![sortingissue](https://user-images.githubusercontent.com/37792198/56284249-3badd900-6114-11e9-9cd4-285636e657e8.PNG)

**Comment by a17alevu** [comment]
Is this issue solved?

**Comment by a17joaap** [comment]
Still having the same issue

**Comment by a17andby** [comment]
Fixed and merged. Closing.
