### ISSUE TITLE
Remove console.log prints from sortableTable 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6048]
Missed to remove test prints from newCompare function in sortableTable. 

![image](https://user-images.githubusercontent.com/49194898/56284270-4bc5b880-6114-11e9-9fec-7435f1193318.png)

**Comment by a17poner** [comment]
Adding GruppC as well since the change that added and forgot to undo the log was made in gruppC so its related to our group too 😺

**Comment by a17joaap** [comment]
Removed some in #6089, not sure if those were all of them.

**Comment by a17maxsj** [comment]
Any news on if all were removed? @a17jooap

**Comment by a17joaap** [comment]
I think all are gone, I'm not getting any logs in console anyway

**Comment by a16joare** [comment]
Yes, you removed all of them.

**Comment by a17maxsj** [comment]
Great! Closing...
