### ISSUE TITLE
Accessed FAB Button Long press has wrong icons

### ISSUE THREAD

**Issue by a17fellu** [HGustavs/LenaSYS#6051]
Create user has a GPS locate icon and import user has a globe. Should be changed to the more apropriate ones

**Comment by a17andby** [comment]
https://github.com/HGustavs/LenaSYS/issues/5414 

Reopened this issue, can you continue from that issue @a17fellu ?

**Comment by a17fellu** [comment]
Yes switching over to that one and closing this one
