### ISSUE TITLE
Error is thrown when hovering funnel(tratt) and up down pyramid (arrows) on access

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#6052]
In accessed.php hovering the funnel or the pyramid arrows, hovering one of them throws an error in console. Clicking them does nothing(as it did pre merge).

**Comment by a17pongo** [comment]
this issue seems to have been resoled with this fix: #6069

**Comment by a17pongo** [comment]
I was wrong, this issue still exists

**Comment by a17poner** [comment]
same as #6037

**Comment by a17andby** [comment]
Fixed and merged. Closing...
