### ISSUE TITLE
Touch: Adding a new item in sectioned.php on a touch screen creates two items.

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6054]
When using any touch screen to add a new item in sectioned.php, two items are created instead of just a single item. Please fix.

**Comment by a17maxsj** [comment]
touchend touchstart something something

**Comment by a17maxsj** [comment]
This can be tested using the Toggle device toolbar in dev mode

**Comment by a17alevu** [comment]
Yes this sounds good, the only problem it causes a new issue.

**Comment by a17maxsj** [comment]
Any news on this?

**Comment by b17carma** [comment]
Can't reproduce this problem with the latest version, might have been fixed with https://github.com/HGustavs/LenaSYS/issues/6340

**Comment by a17maxsj** [comment]
This is working. Closing...
