### ISSUE TITLE
Suggestion: Multifactor authentication

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6056]
Having the option of adding another layer of security to your account through multifactor authentication (e.g time based one time password) could be useful to increase the security of your account. I'm not sure how feasible this is but I thought I would at least suggest it.

**Comment by b17albbe** [comment]
I think there would be possible issues concerned with this suggestion, like losing your authenticator, and not being able to access your assignments as a result. I also don't think there is a immediate security concern, in regards to dugga.

**Comment by a17adajo** [comment]
I think it is a good idea.

Dugga does contain personal information and having as good security as possible should be a priority

**Comment by b17albbe** [comment]
While I agree that having good security should be a priority, I think the risk of losing your authenticator and account pose a greater concern than somebody getting personal information. Then again, I think it also depends on what kind of multifactor system we are talking about. Being able to secure your dugga account with your school email account i think would be more desirable than a mobile solution.  

I'm not even sure if dugga allows you to change your password yet. If not, perhaps that would be suitable to add beforehand.

**Comment by b17carma** [comment]
Bump @HGustavs
