### ISSUE TITLE
Sorting doesn't work in resulted.php

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#6058]
In resulted.php sorting doesn't seem to work. Nothing happens when you press the sort button.

<img width="263" alt="resultsorting" src="https://user-images.githubusercontent.com/37792690/56285793-571ae300-6118-11e9-8c88-ab74122d62cb.png">

**Comment by a17pongo** [comment]
I think the problem is with the compare function but not sure. Could also be that a render function is not working properly in SortableTable.

**Comment by a17oscno** [comment]
Is this feature even necessary to have? i mean the sorting by pressing the different headings does the same thing as this dropdown menu and it is much easier to use togheter with the current workflow.

**Comment by a17oscno** [comment]
@b17nicsv What was the different types of sorting HGustav wanted, or rather which issue did he comment it on, can't seem to find it.

**Comment by b17nicsv** [comment]
@a17oscno #6515
