### ISSUE TITLE
Forward/Back buttons

### ISSUE THREAD

**Issue by a13henhu** [HGustavs/LenaSYS#606]
Make a functional forward and backward buttons..... WORK IN PROGRESS

Just a notification, if someone wants to jump in, go on, I won't deny any help

**Comment by HGustavs** [comment]
I added a commit for this and a few unrelated bugs. Unfortunately I added it to master.... so it needs to be re-merged into the cv15 branch.

**Comment by HGustavs** [comment]
Issue #667 is a superset of this issue. If that commit is proved to solve the issues, this issue can also be retired.
