### ISSUE TITLE
No cursor for hovering over top cogwheel on courseed.php

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#6060]
The cursor still doesn't change when hovering over the top cogwheel on courseed.php. This was fixed in [#5726](https://github.com/HGustavs/LenaSYS/issues/5726) but it wasn't included in the merge.

**Comment by a17andby** [comment]
https://github.com/HGustavs/LenaSYS/pull/5795 Can you fix this @a16lisri ?

**Comment by a16lisri** [comment]
Yes I will fix [#5795](https://github.com/HGustavs/LenaSYS/pull/5795). Closing this issue.
