### ISSUE TITLE
Remove dead and commented code from accessed.js

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6065]
Accessed.js contains a compare function that is not used anymore after the merge (2019-04-17). This function and a commented copy of it should be removed from the file. 
![image](https://user-images.githubusercontent.com/49194898/56287053-ab739200-611b-11e9-8126-59d9e5da855e.png)

**Comment by a16joare** [comment]
Pull request is up #6070.

**Comment by a17maxsj** [comment]
Merged... closing!
