### ISSUE TITLE
Add menu option to reset origo

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6073]
Right now the only way to reset origo to its original position in the top left corner is to refresh the page. Moving it back by dragging it manually lacks precision, hence there should be an option reset it. The menu option could be added somewhere under the Edit category.

**Comment by a17drama** [comment]
There is another issue with similar problems #6031 . Maybe these can be solved with the same "Reset" of the page trough the menu?

**Comment by a17jonro** [comment]
I don't think this issue has anything to do with #6031 since the toolbox is not part of the canvas, which is what this issue concerns. These functions could possibly be used together by maybe using the same button if that's desirable, since their functions are indeed quite similar.

**Comment by a17drama** [comment]
This is my thought exactly to use the same button for resetting both origo and the tool box. Person working on #6031 can piggy back on this solution.

**Comment by HGustavs** [comment]
I would suggest both in tool box and menu. 

Something like zoom extents in autodesk software.

https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/3DSMax/files/GUID-B27D7DCC-EFDF-4D27-B6BA-F6E6BA1B7E3C-htm.html
