### ISSUE TITLE
Make some room between the text when a file is uploaded. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6082]
The filename and upload date is to close to each other. I suggest that we make some space between them to make it more readable.

![image](https://user-images.githubusercontent.com/49194898/56291084-da423600-6124-11e9-9229-4c13d8d9671a.png)

**Comment by HGustavs** [comment]
Adding some padding is not a bad idea.

Also, long (several lines/pages?) feedback tends to look weird.

**Comment by a17maxsj** [comment]
This has been merged, closing...
