### ISSUE TITLE
Space between menu and dropdown

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#6083]
There is a space between the menu and the dropdown and if e.g the toolbox is below the menu it can break the dropdown. Look at the image for more explanation. it looks like it is a few pixels that are between the dropdown and the menu and it should not be any space at all.

![issue2](https://user-images.githubusercontent.com/37792464/56291463-9ac81980-6125-11e9-9fe2-c235e5b124e4.png)

**Comment by a17drama** [comment]
This issue could be related to #5997 or even the solution for it. Removing the space could help a lot.
