### ISSUE TITLE
Column header in test table ambiguous

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6084]
The column header for the 'release' column is 'Result date'.

This is confusing, is 'release' when the dugga is released or when the result is released? @HGustavs

**Comment by a17poner** [comment]
Think you mean header in test table

**Comment by a17poner** [comment]
Assuming its supposed to be when the result is released since startdate should be when the test is started. I'll change it to result  date in the form, if im wrong and its supposed to be the other way it should be pretty easy to revert and change the tablename instead.

**Comment by a17joaap** [comment]
I think so too, from looking at the code. The only place I can see the qrelease value being used is when feedback is showed, so should probably be result.

**Comment by a17poner** [comment]
Yeah, looked at the json response and noticed it was called qRelease there as well but the way its used seems to only be related to realising results. Guess its to late to change the database name and something we have to live with unfortuantly :/ but at least the form can be made more clear this way

**Comment by a17andby** [comment]
Merged. Closing
