### ISSUE TITLE
Update the mail access menuButton title to a more descriptive one.

### ISSUE THREAD

**Issue by a17robes** [HGustavs/LenaSYS#6086]
The title of the test-button:
![image](https://user-images.githubusercontent.com/38004435/56293742-fd231900-6129-11e9-9a74-7146c2599b97.png)

The title of the result-button:
![image](https://user-images.githubusercontent.com/38004435/56293837-2d6ab780-612a-11e9-9f0e-48b49ba47d9a.png)

The title of the mail-button:
![image](https://user-images.githubusercontent.com/38004435/56293924-50956700-612a-11e9-8474-53b3b3f59f5f.png)

**Comment by HGustavs** [comment]
Good idea, this is a little too verbose imho.

**Comment by a17maxsj** [comment]
Was this fixed?

**Comment by a17robes** [comment]
Forgot to make a pull request for this, my bad. Going to fix it now, just waiting for the merge to be completed.

**Comment by a17robes** [comment]
Just saw that the mailbutton got moved to another page and the decription also got updated, therefore this issue is not important anymore. Please close this one @a17maxsj
