### ISSUE TITLE
Bug inside "Resulted" preventing name-display

### ISSUE THREAD

**Issue by a17amama** [HGustavs/LenaSYS#6090]
There should be information about student to the very left next to the number list .
![bug](https://user-images.githubusercontent.com/37793130/56307479-3a48d480-6145-11e9-8772-6380e1047d6f.PNG)

**Comment by c17johha** [comment]
How does this bug appear? I can't produce the problem.

**Comment by a17pongo** [comment]
I have seen this issue too but somehow it later disappeared, the group should monitor if this issue appears again.

**Comment by HGustavs** [comment]
The local storage that remembers shown columns used to behave very weirdly.

If we are on one course showing a set of columns and then navigate to other course....

corresponding columns are shown in that course.

It seems like the filter is not course-local but view local.... so any shown column on that (or any other?) page is reflected on other views.

Unclear if this can be fixed without fiddling with the generic functionality of sortabletable?

**Comment by HGustavs** [comment]
And if this is generic to sortabletable it is very hard to fix without breaking older versions.

**Comment by HGustavs** [comment]
...A data-dump of localstorage for this filter would be interesting to view in this issue... so we can triage the problem.

**Comment by a17pongo** [comment]
I think this issue has been fixed after applying fixes for bugs in sorttabletable that appeared after the first two merges and removing duplicate code in the library.
This issue has not appeared again so I will close this issue for now until we see this again.
