### ISSUE TITLE
Release date is not inserted in the edit dugga dialog

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6092]
If you try to edit a dugga with a set release date, it doesn't show in the dialog.
![norelease](https://user-images.githubusercontent.com/37792198/56313410-d9c09400-6152-11e9-81ff-b3ffbd5139f9.PNG)

Something to do with the selectDugga function in duggaed.js

**Comment by a17joaap** [comment]
Fixed in #6093

**Comment by a17andby** [comment]
Fixed and merged. Closing.
