### ISSUE TITLE
Possible to change grade from G to U after 24h

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#6102]
![image](https://user-images.githubusercontent.com/49199825/56346162-c8fb3700-61c1-11e9-989d-a762509195a5.png)

It is possible to change the grade from G to U after 24h has passed by pressing the "G" logo (which unmarking "G"), and then it is possible to set the grade "U".

Should this be possible?

**Comment by HGustavs** [comment]
it should be ctrl-click for un-setting.... unclear if this has been implemented twice or if the fencing has holes?

**Comment by c17johha** [comment]
works as intended
