### ISSUE TITLE
Remove all-option in the toolbar

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6105]
Remove the all-option in the toolbar as it isn’t needed. It just makes it difficult for new users who trying to learn to model.

<img width="238" alt="Skärmavbild 2019-04-18 kl  10 23 26" src="https://user-images.githubusercontent.com/37792795/56347353-65263d80-61c4-11e9-9b7e-dd8b2776715f.png">

**Comment by a17drama** [comment]
Would be appreciated if we could keep the ALL alternative while we are in developer mode. This makes developing/testing easier when an experienced developer doesn't have to switch between different modes.
