### ISSUE TITLE
Remove the free-option in the toolbar

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6106]
The free draw-option-items should be visible in the ER/UML section of the toolbar as it should be available in both. Remove the free-option in the toolbar as well.

<img width="174" alt="Skärmavbild 2019-04-18 kl  10 27 50" src="https://user-images.githubusercontent.com/37792795/56347491-a9194280-61c4-11e9-868a-bccaef4cf681.png">

**Comment by HGustavs** [comment]
Yeah. free is not a diagram type for sure.

It would be a really strage work-process to highlight something without drawing some diagram to highlight....
