### ISSUE TITLE
Move the changing of model-type in the menu instead of toolbar

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6108]
**This option should be moved to the menu instead of the toolbar since very rarely we change type in a diagram as Henrik said.**

Instead of changing the types here, move it to the menu instead.
<img width="187" alt="Skärmavbild 2019-04-18 kl  10 33 15" src="https://user-images.githubusercontent.com/37792795/56347934-aec35800-61c5-11e9-806a-6d81eaa760a2.png">

 I suggests under the view section.
<img width="372" alt="Skärmavbild 2019-04-18 kl  10 36 17" src="https://user-images.githubusercontent.com/37792795/56348015-da464280-61c5-11e9-8b78-5f14b3c12185.png">

**Comment by HGustavs** [comment]
Much better in menu
