### ISSUE TITLE
Filter button on resulted.php does nothing

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#6112]
In the dropdown menu on resulted.php, the "Filter"-button does nothing, as the filtering already occurs after clicking on the checkboxes. Maybe this button should be removed?

Perhaps the "Sort"-button also does not do anything, but cannot see this as the sorting currently does not work.

**Comment by a17pongo** [comment]
Probably issues that occured after merge, a similar issue #6058 has been assigned to another member to see what caused this issue or if this even worked in the beginning.

**Comment by c17julka** [comment]
![image](https://user-images.githubusercontent.com/37792321/56361382-7cc2ed80-61e7-11e9-9786-e5eef61ba604.png) ![image](https://user-images.githubusercontent.com/37792321/56361390-864c5580-61e7-11e9-8038-71856e773801.png)

If you look at the function for clicking the button, all it does is close the menu, and does no filtering. Might have been like this all along.

**Comment by HGustavs** [comment]
I think there was a separate issue (now closed?) that implemented auto-fuiltering, making this button useless. 

I think we can vaporize this button without consequences.
