### ISSUE TITLE
Sorting by Fname in(Result)  is not working

### ISSUE THREAD

**Issue by a16hiwah** [HGustavs/LenaSYS#6119]
![Sorting](https://user-images.githubusercontent.com/37792852/56359566-30c17a00-61e2-11e9-98aa-90938de7b591.PNG)

**Comment by HGustavs** [comment]
Im thinking this is a local issue and not a general sorting issue?

**Comment by c17johha** [comment]
#6376 Headers should be generally solved within this pull request
