### ISSUE TITLE
Maximize utilization of work space

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6121]
![Edited](https://user-images.githubusercontent.com/46029340/56360642-919e8180-61e5-11e9-9403-60c49f0adce3.PNG)
The margins around the canvas are not equal and is way to big on the down side. Margins are a waste of work space and should be minimized to use the screen as efficiently as possible. Screenshot is placed on the black background so it's easier to see where the margins end.

**Comment by HGustavs** [comment]
Efficient use of spce is a priority since we want this to be used on for example tablets for drawing content.
