### ISSUE TITLE
Access table column added is missguiding

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#6127]
The column added is actually a "last modified" or "last touched" or "last updated/updated".

**Comment by b16johso** [comment]
Like this?
![bild](https://user-images.githubusercontent.com/37793460/56365258-b0eedc00-61f0-11e9-891d-e411ccb43372.png)

**Comment by HGustavs** [comment]
Better!

**Comment by a17maxsj** [comment]
Was this fixed? if so closing

**Comment by b16johso** [comment]
Yes, but I forgot to create a pull request. Created one just now: https://github.com/HGustavs/LenaSYS/pull/6266

**Comment by a17maxsj** [comment]
Noice, closing....
