### ISSUE TITLE
Sort by grade not working

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#6128]
Sorting by grade in resulted is not working. 
Ref: #6030

**Comment by HGustavs** [comment]
Is this a general sorting issue (there used to be problems with sorting that seemed general?) or a grade specific sorting issue?

**Comment by a17pongo** [comment]
@HGustavs 
This is an issue for specificly the sorting part, the styling was fixed as a separate issue.

**Comment by a17pongo** [comment]
ok, seems like an issue was not created specifically for the styling fix.

**Comment by c17johha** [comment]
#5916
