### ISSUE TITLE
Be able to download the diagram in A4 size

### ISSUE THREAD

**Issue by a17jonro** [HGustavs/LenaSYS#6129]
A virtual A4 has been implemented #3752 and now it would be nice to be able to to download the content that is shown inside of the virtual A4 boundaries as a document with the correct proportions.

**Comment by HGustavs** [comment]
Svg export with limit to certain page/coordinate combo only?

**Comment by HGustavs** [comment]
If svg export and canvas drawing use nearly exactly the same code, proportions should be identical?

I think svg export together with normal canvas rendering needs to be solved firstly.
