### ISSUE TITLE
Delete item dialog hotkeys

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6131]
Add keyboard shortcuts for the delete confirmation dialog window that pops up when you want to delete an item in sectioned.php. Use tab to cycle between yes and no and enter to select. Default selection yes?

![bild](https://user-images.githubusercontent.com/37793460/56367833-71c38980-61f6-11e9-93f5-4f5d641b2332.png)

**Comment by HGustavs** [comment]
Default No imho.

**Comment by a17adasy** [comment]
@HGustavs right now enter will be like pressing yes and escape will close the popup box. Isnt this sufficient?

**Comment by b17timjo** [comment]
I say, for accessibility reasons, "enter" should press the currently highlighted button

**Comment by b17nicsv** [comment]
I agree with Tim.

**Comment by a17adasy** [comment]
Okay I will get started on this now.
