### ISSUE TITLE
Old issues not closed

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#6136]
Many old issues seems to have been solved but not closed. It would be good to go through all issues and 'clean up'.

**Comment by a17adajo** [comment]
I agree!

One thing we can do is using keywords in the pull requests to automatically close the corresponding issue when the pull is accepted:
https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by a18kaswi** [comment]
Kasper "The Closer of Issues" Witt
