### ISSUE TITLE
Reference to logdb is created but never used

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#6138]
https://github.com/HGustavs/LenaSYS/blob/e23ec0048d21debc45e356e70cc53a4c9f0381b3/Shared/loginlogout.php#L31

Later a handle using $GLOBALS is used instead.
Remove the unused variable.

**Comment by HGustavs** [comment]
this may be a refactoring?

Can we still use $log_db in other files as we do currently?

**Comment by a17adajo** [comment]
I dont know about refactoring or not but $log_db in the global scope should still be usable from the its creation here:
https://github.com/HGustavs/LenaSYS/blob/e23ec0048d21debc45e356e70cc53a4c9f0381b3/Shared/basic.php#L96

**Comment by a17andby** [comment]
Since I merge this solution I will close this issue.
