### ISSUE TITLE
FAB hover area is a little small which makes it easy to accidentally close the expanded item list

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6142]
An easy way to fix this is to make FABs follow the principle outlined at https://material.io/design/components/buttons-floating-action-button.html#extended-fab under the "Behaviour" heading.

This change would make the acceptable hover area larger which makes it harder to close the list by accident, especially when there are many expanded actions in the list.

**Comment by HGustavs** [comment]
The problem with this is that the FAB-s tend to cover other more useful interface elements.

We need to make something that works in all of the FAB views.

Can we make a mock-up of this so we can see if it causes other (worse?) problems?

**Comment by b17carma** [comment]
I was thinking something along the lines of how e.g lastpass does it where the tooltips are always visible and can be hovered over as part of the item.

![image](https://user-images.githubusercontent.com/37834592/56565881-a8f8b880-65b1-11e9-9145-04a5533f6dea.png)

**Comment by b17carma** [comment]
In dugga it would look something like this on desktop

![image](https://user-images.githubusercontent.com/37834592/56566650-79e34680-65b3-11e9-90d6-cf824d5a5ff4.png)

![image](https://user-images.githubusercontent.com/37834592/56566679-85cf0880-65b3-11e9-8692-618aeab251fd.png)

And on mobile:

![image](https://user-images.githubusercontent.com/37834592/56566706-9bdcc900-65b3-11e9-952a-1612b14cb7a8.png)

**Comment by a17maxsj** [comment]
I think this is a great idea!

**Comment by a17maxsj** [comment]
Adding some / a lot of  opacity while not hovering over the tooltips and then making them 100% visible while hovering?

**Comment by a17maxsj** [comment]
Was this implemented? any news on this :)

**Comment by a17maxsj** [comment]
bump, @b17carma any news?

**Comment by b17carma** [comment]
Leaving this for now, if anyone else would like to work on this they can

**Comment by a17robes** [comment]
Not sure how to solve this, been trying but have not made any progress. Maybe let someone else try to get this fixed? @a17alevu

**Comment by a17alevu** [comment]
Okey, someone else will be assigned to this issue.

**Comment by a16lisri** [comment]
I've made a solution to this. Shown here: https://i.gyazo.com/6da240ae46796312ab5ac21b6555f48e.mp4
Is this good?
