### ISSUE TITLE
Create a smoother "zoom-changer"

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6143]
Change zoom-button to picture below to change the zoom of the diagram instead of clicking a button. This solution decreases the number of clicks and makes it more user-friendly and a smoother view.

(The picture below is from Word)
<img width="200" alt="Skärmavbild 2019-04-23 kl  10 05 40" src="https://user-images.githubusercontent.com/37792795/56565185-173c7b80-65b0-11e9-8168-7fa39bee0e60.png">

**Comment by HGustavs** [comment]
Yes!

But stepped if possible... or with automatic re-centering of diagram.

Soft zoom without auto-centering is motion-sickness-inducing as content moves latteraly when zooming without dynamic centering of view.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

**Comment by a17drama** [comment]
Check out #6018 and make sure these don't destroy each other.

**Comment by a17jacsv** [comment]
Please delete the zoompart in the "coord-bar" as it gets redundant...
<img width="304" alt="Skärmavbild 2019-04-25 kl  10 32 37" src="https://user-images.githubusercontent.com/37792795/56721604-88616780-6745-11e9-8434-494d4618d85a.png">
