### ISSUE TITLE
De-select all entities when re-opening diagram

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6144]
Currrently if you put entities in your diagram and close the session all the entities remain when you enter the diagram page again. The entity which was selected in the previous session will still be selected visually but NOT functionally. For example if you press delete to remove the selected entity you get the following message: 
![saved entity looks marked](https://user-images.githubusercontent.com/37793141/56565380-831ee400-65b0-11e9-97fa-c8e700fe84ab.PNG)
To fix this the visual representation of a selected entity should be removed as a new session is opened on all entities that remain from a previous session.

**Comment by HGustavs** [comment]
Seems reasonable.
