### ISSUE TITLE
Indication when resizing an entity

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6146]
When hovering a corner (point) of an entity there should be a clear indication that it's possible to resize the entity. This should be indicated by changing the mouse icon to:
![Capture](https://user-images.githubusercontent.com/46029340/56566371-bcf0ea00-65b2-11e9-9c3c-72607f26f4d2.png)

**Comment by HGustavs** [comment]
Yes.

Older version had this... and it was very useful.
