### ISSUE TITLE
Upper "add new item" button in sectioned.php has wrong appearance on Safari for IOS/macOS

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6147]
The button is expected to look like this:
![image](https://user-images.githubusercontent.com/37834592/56568254-e7dd3d00-65b6-11e9-807c-68a26fd99111.png)

But it actually looks like this:
![image](https://user-images.githubusercontent.com/37834592/56568277-f0ce0e80-65b6-11e9-9149-36a0dd52bbf8.png)

I'm thinking the issue is that  "-webkit-appearance: none;" is missing from the button style

**Comment by a17andby** [comment]
FIxed and merged. Closing
