### ISSUE TITLE
The cardinality dissapears in some positions

### ISSUE THREAD

**Issue by a17okaoz** [HGustavs/LenaSYS#6148]
If you move the entity with a cardinality attached on it the cardinality can disappear. It´s little hard to make this to happen but if you clear the diagram and built new entity with cardinality and move it slowly around it should happen. This could be a bug and I don´r know what the cause of this is. 

The picture below shows this situation

<img width="211" alt="b1" src="https://user-images.githubusercontent.com/37792681/56568631-b31db580-65b7-11e9-8925-3f27c4e7017a.PNG">

**Comment by HGustavs** [comment]
Confirm this bug by drawing some entity to the right on same level as entity 0....

There is different code for left-right, up-down connections, currently?

**Comment by HGustavs** [comment]
Is it only top/bottom or left/right or some kind of combo, draw another entity below entity 0, does this behave better? same with one above entity 0....

**Comment by a17drama** [comment]
We have tried to force this bug without success. In other words it's not a big issue but it can occur if the user is unlucky.

**Comment by a17alfcl** [comment]
This should be solved by storing the ID and retrieving it, for the object that the cardinality should adapt to. The cardinality should store the object that is relevant, i.e. the Entity or the Class object, and not the Relation object.

**Comment by g18marma** [comment]
Our group has tried to force this bug on different occasions. The bug seems to occur on very rare occasions or not at all. We will close the issue for now.
