### ISSUE TITLE
Part two of issue #571

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#615]
#571 :
If we hover an important word in code viewer code box it seems like it is not highlighted in description box but the converse case is true; if we hover in description box it is highlighted in code box. Unclear if it is a jquery or a css issue

**Comment by a13jorla** [comment]
There is no function who highlights important words. Have to create one.

**Comment by a13jorla** [comment]
In example3 we can see how it works, but boxes lies over eachother so it's hard to tell. New issue.
