### ISSUE TITLE
Minor styling issue, Resulted.php - column headers do not fill whole table when scrolling horizontally

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#6152]
![Screenshot from 2019-04-23 11-19-15](https://user-images.githubusercontent.com/37792222/56569725-d6496480-65b9-11e9-84f0-4dd08148fe16.png)
When scrolling horizontally, the last table column is a little to small and does not fill the whole space.
This only applies for the bottom row.

**Comment by a17pongo** [comment]
is this issue related to magic heading being "shackey"?

**Comment by HGustavs** [comment]
Could it be that the iterator goes over one row too little?

**Comment by a17pongo** [comment]
seems like I am the only one that notices this issue so I will close this for now.
