### ISSUE TITLE
Export doesn't work in Edge

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6159]
None of the export options work in Edge. All of them work just fine in Chrome and Firefox.

**Comment by a17jacsv** [comment]
> Definitely not a priority as edge will be running webkit soon. #7433 

As @HGustavs said, this is not a priority...

**Comment by a18kaswi** [comment]
This could possible be solved after Edge went chromium, test before trying to solve.

**Comment by HGustavs** [comment]
We have a policy that  only student-facing code needs to support edge reasonably well. (preferrably not silent fail). Teacher facing code should work with Chrome/Firefox, accidental support for Edge is allowed but any fails on Edge (silent or otherwise) are considered low prio.

**Comment by a18antsv** [comment]
It works well in the new version of Microsoft Edge. This could be closed.
