### ISSUE TITLE
Cardinalitys position are wrong when it are created when the entity-object are in a diagonal position

### ISSUE THREAD

**Issue by a17okaoz** [HGustavs/LenaSYS#6163]
The cardinalys position gets closer to the line when it are created when the entity object are in a diagonal position. To get the cardinality to the right position you will have to move the enitity down to get the cardinality to it´s right position. 

The picture below shows when the cardinality are created in horizontally to the relation-object that is right
<img width="382" alt="b1" src="https://user-images.githubusercontent.com/37792681/56580644-53350800-65d3-11e9-9922-50ae69afc810.PNG">

 and created in a diagonally position that for now is wrong position
<img width="380" alt="b2" src="https://user-images.githubusercontent.com/37792681/56580655-56c88f00-65d3-11e9-89ad-d557e14607a8.PNG">

Make so the cardinality gets to its right position from the start when it are created in a diagonally position

**Comment by a17alfcl** [comment]
Same as issue #7391
