### ISSUE TITLE
Add points for relation symbols' actual corners

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#6168]
As is now, the points that are created when creating a Relation symbol is the top left point, the bottom right point, and the center point. Some code may be simplified if the points of the actual diamond (as seen in the image) were created at the same time as the other points.
![relationpoints](https://user-images.githubusercontent.com/37792313/56582803-6696a200-65d8-11e9-9867-668f56811c65.png)
These points only exist if there are lines drawn to the symbol, but they should already exist and the lines should be drawn to and from these points instead of creating them on their own.

**Comment by a17alfcl** [comment]
Is not relevant anymore. The current approach is more general and more intuitive, which should be preferred.
