### ISSUE TITLE
Possible to remain and access the result pages as guest.

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6175]
If you go to the access page as admin and logout is it still possible to remain on the page. You can't see the content on the page, but a relocation to the front page would maybe be better?

It's also possible to copy the url and access the page. 

Here is a image when logged in:
![image](https://user-images.githubusercontent.com/49194898/56585015-461d1680-65dd-11e9-920a-5a5f9b9e14e8.png)
Here is a image when you logout:
![image](https://user-images.githubusercontent.com/49194898/56585098-72389780-65dd-11e9-8173-868f659c0cdb.png)

**Comment by a17adajo** [comment]
The most important question: can any data be accesed by a non-admin?
I agree that the page should re-direct without showing anything if for example a malicious actor scrapes the site

**Comment by a16joare** [comment]
I made some simple tests and i cant find a way for a non-admin user to access the data.. Maybe a more experienced person can make some more advanced tests?

**Comment by a18felen** [comment]
I know fileed.php has the same problem and most likely big parts of the system has this problem and would need a fix to make sure they are not accessable when you dont have access.
