### ISSUE TITLE
Possible to remain and access the files pages as guest.

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6176]
If you go to the access page as admin and logout is it still possible to remain on the page. You can't see the content on the page, but a relocation to the front page would maybe be better?

It's also possible to copy the url and access the page.

Here is a image when logged in:
![image](https://user-images.githubusercontent.com/49194898/56586001-31418280-65df-11e9-8a4f-ed72de504ee2.png)
Here is a image when you logout:
![image](https://user-images.githubusercontent.com/49194898/56586061-49190680-65df-11e9-8299-ebcb56b4a9e8.png)

**Comment by a17amama** [comment]
2 identical issues, closing this one.
