### ISSUE TITLE
Creating a course with swedish letters (Å, Ä, Ö) is broke (courseed)

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6190]
When you enter the courseed site and create a new course and give it a name with the swedish letters, Å, Ä & Ö, it will cause problems. 

Below we create a new course named "Övergångsställe"
![image](https://user-images.githubusercontent.com/49199285/56641994-d65b6a00-6676-11e9-8cfd-c738ce7a5be7.png)
The course is created, but as soon as you click on the cogwheel next to the course you will see the problems.
![image](https://user-images.githubusercontent.com/49199285/56642102-06a30880-6677-11e9-9016-2c1c8402cb8b.png)

The name has changed because the site cannot handle Å, Ä & Ö. 
![image](https://user-images.githubusercontent.com/49199285/56642276-57b2fc80-6677-11e9-9c96-531ee1f29175.png)
Same in the courseed site.
![image](https://user-images.githubusercontent.com/49199285/56642367-93e65d00-6677-11e9-8cda-1b47c1e6556d.png)

**Comment by a17andby** [comment]
Just merged so closing this issue.
