### ISSUE TITLE
"Draw Square" objects can be so small that they are invisible

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6192]
When drawing squares using "Draw Square" you can just click once on the screen and a square with all corners stacked on top of each other is drawn. This square has no size and as soon as it is de-selected it will disappear visually. There should be a minimum size that ensures that the square can be found and interacted with without having to guess its location. The dots on the image below are examples of these squares which I have selected using the select all feature.
![invisible squares](https://user-images.githubusercontent.com/37793141/56643396-de68d900-6679-11e9-9617-d4266a0e871e.PNG)

**Comment by a16tobfr** [comment]
#6395 is related to this issue and might be the way to go in order to solve this issue aswell?

**Comment by a16tobfr** [comment]
As with issue #6395 , this issue is no longer relevant since the 'draw square' functionality will be removed.
