### ISSUE TITLE
Remove sorting options

### ISSUE THREAD

**Issue by a17amama** [HGustavs/LenaSYS#6193]
Inside results, when choosing how to sort the table, there are strange options such as ":)". Remove the options that are not used.
![Screenshot (52)](https://user-images.githubusercontent.com/37793130/56643637-491a1480-667a-11e9-8259-e5e5bdf1e3cf.png)

These sorting options automatically appears from the result-table headings, look into them and remove the pointless ones, all the tests etc.

**Comment by a17pongo** [comment]
This is not an issue, this list is populated from another page and is there for not an issue. 
By removing things from a dugga course, elements in that list will be removed too.

**Comment by a16hiwah** [comment]
issue  has been fixed. 
![Anteckning 2019-04-25 134919](https://user-images.githubusercontent.com/37792852/56733652-1b5bcb00-6761-11e9-841f-e972105b33f6.png)

**Comment by a16hiwah** [comment]
![Screenshot_2019-04-25 Result Editor](https://user-images.githubusercontent.com/37792852/56733682-24e53300-6761-11e9-9489-78f498211c66.png)
