### ISSUE TITLE
Confusing choice of fontcolor and backgroundcolor.

### ISSUE THREAD

**Issue by a17robes** [HGustavs/LenaSYS#6197]
Look at the bottom of the deadline section in sectioned.php.

Some text in the Deadline section where the user can see how many weeks the different tasks/deadlines for these tasks extends, has a red font and a grey background, while some of the text has a black font with a yellow background.  You can see this in the picture below: 
![image](https://user-images.githubusercontent.com/38004435/56643905-e5dcb200-667a-11e9-962b-dd4be8fe5971.png)

Not sure if the choices of font for this depends on the grade of the deadline(pass/fail/pending/ n/A)? Maybe we could add an explanation for this or just go with the same font & backgroundcolor for each of the deadlines?

**Comment by a17maxsj** [comment]
@HGustavs please explain

**Comment by a17maxsj** [comment]
Will put someone on getting a nicer color scheme.

**Comment by HGustavs** [comment]
I really dont know what the plan is with this color scheme, is not submitted red for some reason?

Because failed is completely red?

I think we need to look at the code and see what it does and then decide on colors that match te stop-lights.... with a font that is sufficiently contrasty comparing to the background color.....

**Comment by HGustavs** [comment]
A grey first week hand-in should be possible to differentiate compared to an empty first week.

**Comment by a17maxsj** [comment]
Any updates? @a17robes

**Comment by a17robes** [comment]
Checking it out now! @a17maxsj

**Comment by a17robes** [comment]
The following code are as far as I know the rules for the filling of the divs. As i can see it first sets the background color to grey, then sets it to yellow(#FFEB3B) if it doesnt have a grade. The two "else if-statements" should set the background color to green(#00E676) if the grade is bigger than 1 , and red(#E53935) if the grade is equal to one.  

        var fillcol = "#BDBDBD";
        if ((entry.submitted != null) && (entry.grade == undefined)) fillcol = "#FFEB3B"
        else if ((entry.submitted != null) && (entry.grade > 1)) fillcol = "#00E676"
        else if ((entry.submitted != null) && (entry.grade == 1)) fillcol = "#E53935";


Furthermore, it either sets the font-color(textcol) to black or red. It sets it to black font-color if the background color of the element is yellow, and to red if the background color is grey. 
        var textcol = "#000000";
        if (fillcol == "#BDBDBD" && entry.deadline - current < 0) {
          textcol = "#FF0000";
        }
        str += "<rect opacity='0.7' x='" + (startday * daywidth) + "' y='" + (weeky) + "' width='" + (duggalength * daywidth) + "' height='" + weekheight + "' fill='" + fillcol + "' />";
        str += "<text x='" + (12) + "' y='" + (weeky + 18) + "' font-family='Arial' font-size='12px' fill='" + textcol + "' text-anchor='left'>" + entry.text + "</text>";
      }
    }

**Comment by a17robes** [comment]
To clearify: when a dugga is submitted and approved, the background color of it should turn green, a pending one should turn yellow and a failed one should turn red. If no submissions of the dugga have been done, the background color of the div should be grey with a red font.

**Comment by a17robes** [comment]
The section that shows the time period for each dugga deadline is made with SVG.  I planned to make a hover-effect on each field that could help the user to clearify what the chosen color of the field means. I could not figure out how to fix this because of the fields being created with SVG, so instead I added comments to the code explaining the rules of each color.

**Comment by a17alevu** [comment]
Closing this.
