### ISSUE TITLE
Commented code in resulted.js 

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#6199]
In resulted.js, in the function makeSelect(), there are several commented, unused LOC. It seemed it was initially for creating grading buttons for the grades U-3-4-5.

Perhaps this can be safely vaporized.

**Comment by b17timjo** [comment]
The comment was introduced in 2016, here:
https://github.com/HGustavs/LenaSYS/commit/abd440f69b00850a424e776fbf9b76678f22538e#diff-964513d878ea2fb8003afa9032858d8aR619

I doubt the code is relevant today, and it can always be retrieved via version control.
For the sake of improved readability, I say it should be removed.

**Comment by HGustavs** [comment]
It can be removed, we no longer have 3-4-5 mark courses....
