### ISSUE TITLE
In sorting-options, swedish characters are not available

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#6202]
When opening the sorting-options, some characters are not showing as intended. Also the way of shortening the words is mildly confusing. 
![image](https://user-images.githubusercontent.com/37799006/56648698-107f3880-6684-11e9-94a3-4870a0997703.png)

**Comment by HGustavs** [comment]
Unclear what happens....

could it be that it cuts up the text inside &ouml; ?

We want to see the end and beginning of the items if possible with a reasonable amount of code.

If the duggas are called

Test Duggasvar Fråga 1
Test Duggasvar Fråga 2
Test Duggasvar Fråga 3
Real Duggasvar Fråga 1
Real Duggasvar Fråga 2
Real Duggasvar Fråga 3

If we shorten first part we only see

Test
Test
Test
Real
Real 
Real

If we show only end we see

Fråga 1
Fråga 2
Fråga 3
Fråga 1
Fråga 2
Fråga 3

...

By shortening the middle but neither beginning nor end we get best of both worlds...

**Comment by b17timjo** [comment]
It is almost certainly the case that an "&auml;" is string-replaced with "..."
