### ISSUE TITLE
Sortabletable in contribution view

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#6204]
The current contribution view uses some kind of home-grown sorting table code for the sortable tables. I assume this could be better handled with the ordinary default sortable table implementation.

**Comment by a17adajo** [comment]
Can @HGustavs provide a test SQLite database for testing purposes?

**Comment by HGustavs** [comment]
I can prepare one before the meeting on friday.

**Comment by a17maxsj** [comment]
How is the database coming along.

**Comment by a16joare** [comment]
The contribution.js file and tables inside it is a mess.. All HTML code is entered in to a string which makes it hard to read and perform changes..  Here is a example of a table from contribution.js:
![image](https://user-images.githubusercontent.com/49194898/56894070-fe870680-6a84-11e9-8860-506698255dfe.png)

contribution.php file is close to empty and I wonder why the solution is implemented inside the .js file and not the .php? I can't see any reason why it should not..
I suggest that a refactoring should be done and all the html code should be moved from the .js file to the .php file. This will make it easier to structure and read the code and it is possible to solve all tables at the same time. What do you think @HGustavs ?
