### ISSUE TITLE
Add message or alert when object connection is invalid

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#6207]
When making a line connection between symbols that aren't possible, the user should get a message or alert saying the connection is invalid. For example, when trying to connect two entities, it could look like this:
![sdf1507cb57](https://user-images.githubusercontent.com/38030926/56656011-a7ec8780-6694-11e9-9233-30fc287d74e3.png)

**Comment by a17johpe** [comment]
If this is to be a thing, it shouldn't lessen the experience and should be unobtrusive. If the user has to click away an error message every time they draw a line between two invalid objects, it might slow down the use too much

**Comment by a17vikab** [comment]
At the moment, you can only successfully draw lines between objects that is correct according to ER and UML. If you draw a wrong line between two objects, the line does not connect and disappears.

Therefore, I am closing this issue.
