### ISSUE TITLE
Cardinality collision with lines when there dual relation

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6209]
When there is more than one line for the relation lines and cardinality can collide. See the picture.
![Capture](https://user-images.githubusercontent.com/46029340/56656200-29441a00-6695-11e9-8c5c-b9a42122a7b7.PNG)
Lines could stay as they are but it would look even better if the lines where parallel instead of attaching to one point in the relation.

**Comment by a17alfcl** [comment]
Should not be solved before issue #7391
No obvious fix for this issue
