### ISSUE TITLE
Cookie/MOTD Message in courseed.php overlaps the new course FAB

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6210]
![Capture](https://user-images.githubusercontent.com/37834592/56656390-aec7ca00-6695-11e9-9257-a54624ea62af.PNG)

**Comment by a17maxsj** [comment]
maby put the motd bar under the navbar? could work

**Comment by b16johso** [comment]
+1

**Comment by a17maxsj** [comment]
Rough mockup, maybe with a nice fold out effect
![eb761795c0be0904bef9f1fcefc68555-png](https://user-images.githubusercontent.com/49199993/56659582-cd31c380-669d-11e9-9d4a-c8da33870c75.png)

**Comment by a17maxsj** [comment]
Maybe add error messages also in this bar at a later stage

**Comment by b16johso** [comment]
After discussing this with some other group members, we decided we want the MOTD message to appear at the top of the page, under the navbar, but leave the cookie message at the bottom. However, this means the cookie message still overlaps the FAB, so my suggestion is to change the styling of it. Here's what I came up with:

![bild](https://user-images.githubusercontent.com/37793460/56725942-1e00f500-674e-11e9-8b63-5b556cd0be2a.png)

**Comment by b16johso** [comment]
Also animations for showing and hiding the messages would look nice.

**Comment by a17maxsj** [comment]
Looks good, further input from the group would be nice!

**Comment by a17joaap** [comment]
Looks good, the MOTD was really annoying before but this makes it less so

**Comment by a16joare** [comment]
I think it looks much better, GJ!

**Comment by b17annni** [comment]
I approve

**Comment by a16lisri** [comment]
I think it looks better too. Nice!

**Comment by b17carma** [comment]
I agree, this looks a lot better 😃

**Comment by a17maxsj** [comment]
Was this implemented? @b16johso  i think it should be added before merge!

**Comment by a17andby** [comment]
I approve as well. Merge this solution to our group branch before the merge.
