### ISSUE TITLE
Errors when pressing Enter in sectioned.php

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#6211]
![image](https://user-images.githubusercontent.com/37792321/56656250-4b3d9c80-6695-11e9-8d4d-13bb0274f4a4.png)
![image](https://user-images.githubusercontent.com/37792321/56656267-5c86a900-6695-11e9-955a-52cf1ee59cd9.png)
This error appears if you press Enter while editing an item in sectioned.

![image](https://user-images.githubusercontent.com/37792321/56656314-7aeca480-6695-11e9-9708-69bf38aafa50.png)
If you press Enter in just sectioned, this error appears.

Relevant code is in the $(window).keyup function. The functions "isNameValid()" and "isTypeValid()" aren't defined anywhere.
`if (saveButtonDisplay == 'block' && editSectionDisplay == 'flex' && isNameValid()) {
      updateItem();
    }`

`else if (isTypeValid() && testsAvailable == true) {
      confirmBox("closeConfirmBox");
      testsAvailable = false;
    }`

**Comment by c17julka** [comment]
Same error with isTypeValid() appears when you press enter while editing/adding course.

**Comment by HGustavs** [comment]
The validation code should be removed completely in that view as it is not possible to validate in a succint way, and I may have not done that removal correctly ...

**Comment by c17julka** [comment]
The errors when pressing enter still appears, as they are still used in the key event function.

**Comment by a17adasy** [comment]
https://a17adasy.gruppb.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732

The errors do no appear for me on my test site which has the issue 6211 branch right now.

**Comment by c17julka** [comment]
Seems my branch had messed up and not updated correctly, my bad.

**Comment by a17pongo** [comment]
@c17julka so did I just merge something that did not fix the issue?

**Comment by a17pongo** [comment]
@c17julka so did I just merge something that did not fix the issue?
