### ISSUE TITLE
Suggestion: Add graphical response on icon hover

### ISSUE THREAD

**Issue by a17robda** [HGustavs/LenaSYS#6213]
![issueeeeeee](https://user-images.githubusercontent.com/37792328/56656449-d9b21e00-6695-11e9-843b-9c923eb672d5.png)
I think we should add some visual feedback on these icons for clarity?

**Comment by a17maxsj** [comment]
would be nice!

**Comment by a17robes** [comment]
#6240 Fix for this issue!

**Comment by a17andby** [comment]
Marge this issue to the new weekly branch
