### ISSUE TITLE
Very hard to use accessed.php, duggaed.php & fileed.php on smaller devices

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6216]
These pages have tables which overflow outside the viewport on mobile devices which make them annoying to use. 

Additionally, accessed.php seems to be missing the viewport meta tag.

**Comment by b17albbe** [comment]
I disagree.

**Comment by a17alevu** [comment]
I logged into LenaSYS on my mobile (Android) and looked at the tables in accessed and duggaed, I dont really see a problem? Can you perhaps screenshot and put it in the comments ? @b17carma

**Comment by a17alevu** [comment]
Now i looked at the small device simulator on Google Chrome and i can see the problem. Don't mind the last comment.

**Comment by a17alevu** [comment]
When we tried this on a iPhone it we were not able to see the whole table, but as soon as we rotated the phone we saw the whole table.

**Comment by a17maxsj** [comment]
Worthwhile putting someone on this?

**Comment by b16johso** [comment]
Related issue: https://github.com/HGustavs/LenaSYS/issues/6677

**Comment by b16johso** [comment]
Removing the horizontal scroll from mobile view is not possible and not even really a problem. However, here are some things I've found that can make it more mobile friendly:

Change cell padding to Material Design standard. Add missing viewport meta tags (Access starts zoomed out at the moment).

I also tried to make the table headers sticky, but couldn't find a good solution.
