### ISSUE TITLE
Make error messages more user friendly

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6217]
Make error messages more user friendly and easier to understand. For example, this error message appears when editing a course version without setting the start and end dates:
![bild](https://user-images.githubusercontent.com/37793460/56656970-2518fc00-6697-11e9-9b19-6e9abe3b28f9.png)
The text here could be changed to "Please enter a start/end date", or something like that. Additionally, the error message should display on top of the dialog window instead of first closing the dialog and then displaying the error message.

**Comment by HGustavs** [comment]
The error message handling is generic and comes from the service side. 

so... fixing this can thus be boiled down to ramping up the specificity of some of the error messages on sql errors in the service code, and then the generic error handling will take care of the rest.

**Comment by a17joaap** [comment]
I think form validation is a better way to solve this, instead of targeting specific SQL error codes (there are a lot) with switch cases.

**Comment by a17joaap** [comment]
Form validation is implemented for access in #7251
