### ISSUE TITLE
Unable to change Course Version ID 

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#6218]
reverts back to the former value after save, see image...

![image](https://user-images.githubusercontent.com/49199993/56657198-b8eac800-6697-11e9-880c-610fbd3859d6.png)

**Comment by a17joaap** [comment]
Version ID is a primary key for the 'vers' table, what this dialog does is change the version name, start date, end date, and defaultness of the version with the version ID you put in. So this is working as intended, you can't change the version ID.

**Comment by HGustavs** [comment]
We could even remove the version as it is immutable imho.
