### ISSUE TITLE
Suggestion: Add smoother animation for piechart in sectioned

### ISSUE THREAD

**Issue by a17robda** [HGustavs/LenaSYS#6219]
![sectioned](https://user-images.githubusercontent.com/37792328/56657200-b9835e80-6697-11e9-81b4-9c644a3ae1f1.png)
Clicking the deadline arrow to expand piechart menu should have a shorter smooth animation to show and hide it?

**Comment by a17robda** [comment]
Right now it only "snaps" from visible/hidden state.
.

**Comment by a17maxsj** [comment]
could be nice if minimal

**Comment by HGustavs** [comment]
Is there a presedence somewhere?

Im starting to thing that there are too many conflicting visual cues, and that it is probably time to start to letting the css complexity militate against adding additional ones.

**Comment by a17pongo** [comment]
I agree, I will close this issue because there is already too many known issues with CSS.
If this is requested in the future we can open it but first maybe we should focus on resolving some issues with the css.
