### ISSUE TITLE
Variables uses different conventions, and some are poorly namned in file codeviewer.js

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#622]
Variables uses different conventions some follow the new word start with capital letter, while others use lowercase letters for all word in the name.  
Some variables are named with only one letter in cases where it according to my opinion, would increase the clarity by naming them with what they do.
Variables with the word "id" in them are written differently sometimes "nameId" others "nameid".

Issue for file codeviewer.js.

**Comment by a14emeax** [comment]
Some of these problems have been corrected while working on other issues in the code. It might be troublesome however to fix all of the code at once since that would cause conflicts with the other pull requests.

**Comment by a17andby** [comment]
Since we can't refactor old code, is this still a issue?

**Comment by a17poner** [comment]
We can refactor a bit in files as long as its within the same microservice and isn't used by anything else I believe, altough this seems to have been sort of fixed in different issues in history according to some of the issues referenced above.
