### ISSUE TITLE
Cant exit preview window in showdugga.php

### ISSUE THREAD

**Issue by c17alepe** [HGustavs/LenaSYS#6220]
![image](https://user-images.githubusercontent.com/38323901/56657124-89d45680-6697-11e9-83c6-35b41df00c85.png)

Whenever you open a text or pdf file that you have submitted in showdugga.php, you cant close it any other way than clicking the back button, which takes you to the previous site.

The image is an example of opening a textfile and being trapped.

**Comment by HGustavs** [comment]
This must be some kind of styling issue?

There used to be buttons here?
