### ISSUE TITLE
Difficult to close filter windows on resulted using smartphone

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#6221]
The filter windows use mouse movement to detect if the window loses user focus, which does not work well using touchscreens.

**Comment by HGustavs** [comment]
Any better suggestions?

We dont want to lose this functionality for non-touch, and furthermore this is not a touch centric view.

Only student facing views should be mobile first as discussed in older probably closed issues.

It is too easy to press the wrong button marking assignments on mobile.

**Comment by c17johha** [comment]
closing this issue until there is any better suggesstion.

**Comment by b17timjo** [comment]
A common approach is to close a window if the user clicks outside it, which should work here.

And although I used a smartphone as an example, this of course applies to tablets and desktop touchscreens as well, where the screen real-estate should be more than enough to reliably click any buttons on the site.

**Comment by c17johha** [comment]
will take this to H

**Comment by HGustavs** [comment]
The idea is to save on one click....

I wouldnt mind to have both.

If clicking outside dialog or hovering out of the dialog, would both trigger the exact same code.

**Comment by c17alepe** [comment]
![image](https://user-images.githubusercontent.com/38323901/57134500-a7e03c00-6da6-11e9-983c-6677467fc594.png)

I could need some JQuery help with figuring out how to select the popup div and all of its descendants. 

Right now there is code for closing the window whenever the mouse is not hovering anymore. My test code is a failed attempt to make the window close whenever anything except the popupbox and its children is clicked. It still closes whenever i click in the box.

**Comment by b17nicsv** [comment]
Status on this?

**Comment by c17alepe** [comment]
This is not that high priority since its a mobile problem on the teachers site. I cant figure out what i mentioned above in this moment.

**Comment by b17nicsv** [comment]
Yepp, will close this one.
