### ISSUE TITLE
Content div in sectioned.php has excessive margin

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6222]
In my opinion, the left, right and bottom margin on the content div in sectioned.php should be completely removed, but I would like to know what other people think.

![Capture](https://user-images.githubusercontent.com/37834592/56657631-d79d8e80-6698-11e9-9e2d-181ada1d7b82.PNG)

**Comment by a17maxsj** [comment]
I think this might have something to do with material design papers, not sure if it would make the page better or worse. Mockup maybe 😄

**Comment by a17andby** [comment]
Just merged a fix for this issue. Closing.
