### ISSUE TITLE
SectionEd: Message item icon broken

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6223]
The icon for the message item in sectioned.php is broken. Looking at its html code, it appears to be using another php file as image source, which doesn't seem right.

![bild](https://user-images.githubusercontent.com/37793460/56657670-f13ed600-6698-11e9-8737-d827f76ab439.png)

Code:
`<img src="showdoc.php?courseid=333&amp;coursevers=1&amp;fname=UNK" style="display:block;margin:auto;max-width:32px;max-height:32px;overflow:hidden;">`

**Comment by a17adasy** [comment]
The issue doesnt seem to be on the group B branch. On the B branch there isnt even an image.

**Comment by b16johso** [comment]
> 
> 
> The issue doesnt seem to be on the group B branch. On the B branch there isnt even an image.

The image only appears on local servers. On the web server it doesn't appear at all, regardless of group.

**Comment by c17johha** [comment]
It's not worth spending resources on this issue, since it works on the web server

**Comment by b16johso** [comment]
Reopened this as it now seems to be an issue on the web server too.

**Comment by a17oscno** [comment]
Do we know which icon was there before? or is it just to pick something appropriate like a warnings triangle?

**Comment by a17oscno** [comment]
@b16johso
