### ISSUE TITLE
AccessEd: Search function should accept lower case and ÅÄÖ

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6225]
The search function in the access editor requires an exact match including upper case letters. It should be possible to search for 'conny' and still get results for Conny. 

It's also not possible to search for names including ÅÄÖ, such as 'Åsa'.

**Comment by a16lisri** [comment]
Couldn't solve this one, assign someone else maybe?

**Comment by HGustavs** [comment]
Searching should mostly support national characters but other than that I have few opinions.
