### ISSUE TITLE
Variables uses different conventions in editorService.php

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#623]
Three different way of naming variables have been spotted, lowercase for all words, Capital letter for new words, and underscore between words.
Also variables that end with "id" are some times written "nameid", and other times written "nameID".

Issue for file editorService.php.

**Comment by a13alfbe** [comment]
Wait with this issue until we all have agreed on what type of variable naming convention to use.

**Comment by a13jorla** [comment]
Closing this since we have merged #668 and it's about the same topic.
