### ISSUE TITLE
Suggestion: Move TopMenuStatic buttons to main header

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6230]
![Capture](https://user-images.githubusercontent.com/37834592/56658920-239e0280-669c-11e9-9c90-b4b602ed8d83.PNG)

**Comment by b17annni** [comment]
![image](https://user-images.githubusercontent.com/37792766/56805233-ac49a980-6828-11e9-97af-bda09f45ff4f.png)

**Comment by b17annni** [comment]
#6350

**Comment by a17maxsj** [comment]
Looking good!

**Comment by a17andby** [comment]
@b17annni implemented this suggestion. Closing this suggestion/issue.
