### ISSUE TITLE
Refactor each symbols draw method to a more generic drawPolygon method

### ISSUE THREAD

**Issue by b17robev** [HGustavs/LenaSYS#6233]
Currently each symbol has its own separate draw method, after a talk with @HGustavs it would be good if we could abstract that logic into a more generic drawing method. Since every shape is inherently a polygon besides the circles and text. 

Perhaps something in line with...
```
function drawPolygon( ArrayOfPoints, fill, stroke ...)
```

**Comment by a17alfcl** [comment]
Tried and failed. Basic functionality remade in branch https://github.com/HGustavs/LenaSYS/tree/gruppA2019W19%236611
but too much time were required to implement every old functionality in the new logic.
The required duplications of functions (or making exceptions for Path objects) is the main problem with the current functionality, but as all other logic is based on it, it might not be worth solving this issue.

**Comment by a18kaswi** [comment]
REFACTOR - CAREFUL
