### ISSUE TITLE
Map A4 to new canvas logic

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#6234]
Related to issue #5826

**Comment by HGustavs** [comment]
More details for documentations sake, this description is too generic.

**Comment by a17alfcl** [comment]
![a4](https://user-images.githubusercontent.com/49202727/56740582-844b3f00-6771-11e9-9639-3ccee630e4f4.png)

A4 is always located at topleft of canvas and does not scale with zoom
