### ISSUE TITLE
UML lines breaks on negative values

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#6237]

**Comment by HGustavs** [comment]
Screenshot

**Comment by a17drama** [comment]
There is a broken UML line in #6206. It's the one that looks totally fubar. Check that out for a screenshot.

**Comment by a14oscna** [comment]
I wont work on this issue right now since we are completely reworking UML lines in general. Adding on-hold label.

**Comment by a17vikab** [comment]
Solved in the current branch.
