### ISSUE TITLE
Filtering and sorting buttons don't do anything in accessed.php

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#6238]
In accessed.php the buttons for filtering and sorting don't do anything and they also have no text when you hover over them like the home and back button do. (Can test this by going into "Datorgrafik" then "Access").

![086607047d31f405d811ac4ba0c8809d](https://user-images.githubusercontent.com/37792690/56659463-7926df00-669d-11e9-9f12-f598b9aa0fcd.png)

**Comment by a17poner** [comment]
It used to give you a empty white box, can't remember or find the issue that dealt with it but then that fix caused some error logs in chat which where brought up in #6037 and #6052. Which I then made a really bad fix for in #6145. Im not sure what they do in accessed but im assuming they should do the same thing here and do some filtering related stuff. The same functions hovers and hoverc exists in accessed.js except they actually have some code in them so to whoever end up with this issue to make them do whatever they do in accessed (never used them or tested so no clue what they do) that is probably a good place to start 😄

**Comment by a17poner** [comment]
@HGustavs is the sorting arrows still necessary? Feels redundant to have them when you can sort the table by clicking the columns in the same way the arrows are supposed to do.

**Comment by a17maxsj** [comment]
bump @HGustavs

**Comment by a17poner** [comment]
This one is now a week branch behind and there seems to be some problems with the placements of the filtering and sorting buttons, I'll wait for a comment by @HGustavs on to keep the sorting or not and for the placements issue to be worked on before I attempt to rebase the fix for this and perform further actions on it.

**Comment by a17poner** [comment]
Splitting this issue, putting the arrow part in a seperate issue so we can move on and merge the funnel once reviewed without having to wait for a response about the arrows in #6602
