### ISSUE TITLE
Ability to lock proportions when resizing entities

### ISSUE THREAD

**Issue by b17robev** [HGustavs/LenaSYS#6239]
One should be able to lock the proportions when resizing entities, could possibly be done while pressing shift and resizing an entity.

**Comment by HGustavs** [comment]
Or locking height.

Entities should have a specific and equal height, attributes should perhaps be slightly more resizeable since the text may not fit all shapes of elipses but, really a maximum/minimum height but largely unrestricted width would be one way to achieve both.

**Comment by a17vikab** [comment]
This issue is being solved when #6309 is done.

**Comment by a17vikab** [comment]
The pull request, #6368, did not merge correctly and therefore this issue is now the main issue regarding this problem. 

Old issue: #6309
