### ISSUE TITLE
Variables uses different conventions, and some are poorly namned in file EditorV50.php

### ISSUE THREAD

**Issue by b12simsa** [HGustavs/LenaSYS#624]
Variables with the word "id" in them are written differently sometimes "nameid" others "nameID".
Variables are written with lowercase letters, depening on how the naming is done in the other files this might have to be changed so that the names follow the general convention used.

File: EditorV50.php

**Comment by a13henlo** [comment]
this is already resolved ....

**Comment by a17andby** [comment]
Since we can't refactor old code, is this still a issue?

**Comment by a17poner** [comment]
The file EditorV50.php doesn't exist, closing this!
