### ISSUE TITLE
Resulted: Add support for multiple search values

### ISSUE THREAD

**Issue by a17adasy** [HGustavs/LenaSYS#6244]
The groundwork is probably set from the pull-request #6243

**Comment by HGustavs** [comment]
Are we talking about boolean operators discussed in a few other issues or something else?

**Comment by a17adasy** [comment]
@HGustavs Yes, thats the issue. It was divided into a seperate issue (this one) because the original was getting pretty big. 

I saw that i had linked the wrong pull request before, it is now fixed.

**Comment by a18matna** [comment]
Hard to test without any working search values, currently re-working previous work assuming it somewhat works

**Comment by b18veran** [comment]
Hard to test without testdata. So I will wait until we got some data to test it on.

**Comment by b18alegu** [comment]
This issue was merged into the W16 master. I'm closing this one now.
