### ISSUE TITLE
E-Mail button in Resulted do not work with the new Boolean Search

### ISSUE THREAD

**Issue by a17oscno** [HGustavs/LenaSYS#6245]
With the new boolean search functionality in the Result view the only way to send emails to the visible students is when searching for their names and not (for example) when searching for everyone who got a G on Biträkningsduggor 1HP.

**Comment by HGustavs** [comment]
E-mailing should be generic functionality... as was discussed in another earlier issue.
We compose email with exactly the visible items.... the only thing we need to specify is which column contains the emails.

In the ideal case there could/should be a function email("colname") in the sortable table object, which composes the email from visible rows, and the email addresses are gathered from the column "colname" ...

This way emailing works in any dialog, access editor, result editor or any other view as long as we know which column contains the email address.

**Comment by HGustavs** [comment]
Kind of how csv export works but for making emails instead (I think it was described as such in a previous issue)

**Comment by a17anter** [comment]
Mail functionality has now ben moved to "sortabletable.js" to be more generic and will now e-mail all users that are not "null" in the array "currentRowFilter". An issue still remains though with setting the correct users in this array, a new issue will be created for handling this array with all different types of filtering/searches. "currentRowFilter" will be used in a similar way to "columnOrder" and "columnfilter" in sortabletable.js.
