### ISSUE TITLE
Add tooltip to searchbar so the user know the keywords.

### ISSUE THREAD

**Issue by a17adasy** [HGustavs/LenaSYS#6248]
related to the search from pull request #6243.

A kind of tooltip somewhre near the input field so you can see what the keywords are for searching.
Right now you will have to look in the code to see the keywords (markG, markU, date).

**Comment by HGustavs** [comment]
Give me a mock-up please.
I have a very hard time imagnining what we are talking about.

**Comment by a17adasy** [comment]
@HGustavs this is what i mean:
![image](https://user-images.githubusercontent.com/37799016/56718703-8bf1f000-673f-11e9-8e15-b1d4b0f3b4e0.png)

so when you hover over the questionmark the box appears.
