### ISSUE TITLE
Locked objects are able to be resized

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6250]
Locked objects should not be able to be resized.

A solution might be to make locked objects to be unselectable. This will however most likely result in the the removal of the ability to change the objects individual appearance, but the global appearance would most likely still change the appearance.

Suggestion is to either make the appearance of locked items unable to change at all, or to find a way to make it so that the individual appearance still can be changed (e.g. by double clicking on the object).
![lockedResizable](https://user-images.githubusercontent.com/49199690/56662334-040ad800-66a4-11e9-9402-4722394568f1.jpg)

**Comment by a17alfcl** [comment]
Solved in #6309
