### ISSUE TITLE
Function lacks comment in diagram_object.js

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6251]
Minor fix
The function below needs a comment to clarify where and when it is used
~~~
function removeForcedAttributeFromLinesIfEntityIsNotWeak(x1, y1, x2, y2) 
~~~
I will asign this to myself since I know where and when it is used.

**Comment by HGustavs** [comment]
wow.

I think we can crown this function name most verbose (by definition most useless?) name in the application. I can not imagine there is a longer name anywhere?
