### ISSUE TITLE
Search bar in resulted.php should be sticky

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#6253]
Scrolling horizontally back and forwards can be annoying. Would be easier if the search bar was sticky so you don't have to scroll this much.

**Comment by HGustavs** [comment]
Or up in the already static navigation menu.

I think that there is some other issue (other service than this?) that has already discussed this, and if I am not mistaken I asked for a mock-up of how this may look.

**Comment by c17julka** [comment]
![image](https://user-images.githubusercontent.com/37792321/56720429-1b4cd280-6743-11e9-978a-53de14ab86ef.png)

@HGustavs Here's a mock-up picture of a suggested move. Would this be a viable move?
