### ISSUE TITLE
typo in script in filereice_dugga.php

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#6262]
`echo "<script>window.gocation.replace('showDugga.php?cid=".$cid."&coursevers=".$vers."&did=".$duggaid."&moment=".$moment."&segment=".$segment."&highscoremode=0');</script>"; //update page, redirect to "fileed.php" with the variables sent for course id and version id`

3 years ago according to git blame marcus misspelt window.location to windows.gocation. This throws an error when uploading a file right before you get redirected (turn on preserve logs to see error)

this line should be changed to:
`echo "<script>window.location.replace('showDugga.php?cid=".$cid."&coursevers=".$vers."&did=".$duggaid."&moment=".$moment."&segment=".$segment."&highscoremode=0');</script>"; //update page, redirect to "fileed.php" with the variables sent for course id and version id`

**Comment by a17andby** [comment]
Closing.
