### ISSUE TITLE
Snap to grid does not adjust properly to different zoom

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6270]
The Snap to grid function is supposed to snap the objects to the visual grid, but the objects are rarely aligned to the lines in the grid which is frustrating in itself. However the position it snaps to in relation to the lines change when the zoom is changed as well. This code logic has to be rebuilt. See the differences in the different images below they are ordered from 75% zoom to 200%.
![75%](https://user-images.githubusercontent.com/37793141/56722962-58679380-6748-11e9-918f-9c6a8eefdd73.PNG)
![100%](https://user-images.githubusercontent.com/37793141/56722970-5c93b100-6748-11e9-826e-c7290d7d6b21.PNG)
![150%](https://user-images.githubusercontent.com/37793141/56722979-60273800-6748-11e9-8559-c4eaf39ca866.PNG)
![200%](https://user-images.githubusercontent.com/37793141/56722988-63222880-6748-11e9-9f11-7a36286aed4c.PNG)

**Comment by HGustavs** [comment]
The easiest thing is to make the grid in "real pixels" ... then the pixel to canvas should handle this automatically.

If we do the positioning of all movements also in real pixels it will also work automatically.

**Comment by a14oscna** [comment]
This issue has been fixed but not referenced after the snap to grid logic was improved.
