### ISSUE TITLE
Improve rules for UML Lines

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#6274]
The UML Line tool creates an unnecessary amount of kinks and breakpoints in certain situations, and should adapt depending on certain positions to make the best line path possible. Here's an example on how that could look like:
![11db3d4ba6b44c4db0f713ec66379b0b](https://user-images.githubusercontent.com/38030926/56729734-442a9300-6756-11e9-904b-2119a82fa7f6.png)
![11db3d4ba6b4hj4c4db0f713ec66379b0b](https://user-images.githubusercontent.com/38030926/56729749-50165500-6756-11e9-86db-21485ea4789d.png)

**Comment by a17jacsv** [comment]
I agree...
