### ISSUE TITLE
Free draw brakes in some cases

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6277]
In some cases, when in free draw, the lines can disapear when in the process of drawing a figure.
<img width="112" alt="freeDrawLinesRemoved" src="https://user-images.githubusercontent.com/49199690/56723687-bf397c80-6749-11e9-905e-20b9b212d474.png">

**Comment by a16tobfr** [comment]
I have not encountered this problem in a long while and I think that the issue can, therefore, be closed.

**Comment by a17vikab** [comment]
Solved.
