### ISSUE TITLE
possible to sort on pen, cogwheel and trashcan at duggaed.php

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6278]
The pen, cogwheel and trashcan does not have any table headings but it is still possible to sort them. 

![image](https://user-images.githubusercontent.com/49194898/56733492-9b356580-6760-11e9-93c6-9b39eed9aaf2.png)  ![image](https://user-images.githubusercontent.com/49194898/56733512-a6889100-6760-11e9-8944-1922d98442e3.png)

I cant find any reasons to why we should sort them so how about removing the possibility completely?

**Comment by a17maxsj** [comment]
seems like a good idea!

**Comment by a17robes** [comment]
It seems like the headers of the table are automaticly sortable when they get created in the .js-file. I don't know how to remove this functionality for these three particular headers. Any ideas? @HGustavs

**Comment by b16johso** [comment]
@a17robes did you find out anything useful?

**Comment by b16johso** [comment]
Fixed
