### ISSUE TITLE
Separating lines in some tables but not all. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6279]
If we look at the tables inside fileed.php and duggaed.php the tables got lines that separating the columns in the table. But the tables inside accessed.php and resulted.php do not have this separating lines. 

Table inside fileed.php:
![image](https://user-images.githubusercontent.com/49194898/56734417-0d0eae80-6763-11e9-9dff-6e3863674cfb.png)
Table insde resulted.php:
![image](https://user-images.githubusercontent.com/49194898/56734462-2e6f9a80-6763-11e9-93b7-b6a49b1b3aa7.png)

I suggest that we either add the separating lines to the tables that do not have them or remove them from the tables that do.

**Comment by HGustavs** [comment]
I kind of like the lines.

This should be a generic thing in the css. 

Sortable styling should happen once in the style.css file ... if we change for example the sortable table header color in the css all sortable table headers should change accordingly...

**Comment by a16joare** [comment]
Do you mean the "yellow lines" when you hover a column?  In that case we misunderstood each other. I meant this lines: 
![image](https://user-images.githubusercontent.com/49194898/56791334-1cdfce80-6807-11e9-9024-6a490c998bf7.png)

**Comment by a17alevu** [comment]
Looks like all the lines are black now, meaning that every table (Files, Access etc.) have black lines. Not sure if this is a good solution ?

**Comment by a17andby** [comment]
Closing this issue since I merged a solution for this issue.
