### ISSUE TITLE
Canvas is totally broken in Edge after implementing solution for #5609

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6280]
Coordinates for the mouse don't work and if the view (camera) is moved everything turns white and doesn't update at all.

**Comment by HGustavs** [comment]
I think this may be related to the old polyfill used for reading the mouse coordinate.

The best way to read the muse in 2019 is 

https://stackoverflow.com/questions/442404/retrieve-the-position-x-y-of-an-html-element

Perhaps edge does not support this well?

**Comment by a17drama** [comment]
I noiced it isn't even possible to select objects. All I see in console is:
![Capture](https://user-images.githubusercontent.com/46029340/56791341-210bec00-6807-11e9-9978-73c2506c6d63.PNG)

**Comment by a17alfcl** [comment]
https://windowsreport.com/uninstall-edge-windows-10/
