### ISSUE TITLE
Changing line colour on free draw objects doesn't work

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#6282]
Nothing happens when you try to change line colours on both kinds of free drawn objects, it remains black.
![freedrawline](https://user-images.githubusercontent.com/37792313/56735147-ee111c00-6764-11e9-9622-e11703cc1df5.PNG)
![freedrawline2](https://user-images.githubusercontent.com/37792313/56735148-f0737600-6764-11e9-8d59-1285067dfb2f.PNG)

**Comment by a17vikab** [comment]
This issue got solved.
