### ISSUE TITLE
Explanatory name under the help tab is wrong

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6283]
It should no longer be 'Move grid' since this is not what we are doing. We are moving the camera, not the grid.
I suggest changing the name to 'Move camera'.
<img width="159" alt="moveGrid" src="https://user-images.githubusercontent.com/49199690/56735182-16007f80-6765-11e9-8ccf-0a1a0e48b728.png">

**Comment by a17jacsv** [comment]
I agree...
