### ISSUE TITLE
Possible to have the same name on assignments

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6288]
On the course site it is possible to add assignments with the same name.  Feels like a bad feature and maybe some kind of name check would be an good idea? 
![image](https://user-images.githubusercontent.com/49194898/56736002-49dca480-6767-11e9-8f6e-ae58b0a59558.png)

**Comment by a17adajo** [comment]
I think the database should enforce the validation and the client should display an appropriate error message when it happens.

**Comment by a17maxsj** [comment]
Could be useful

**Comment by HGustavs** [comment]
There may perhaps be cases where we have the same name, so this seems to fall under the refactoring umbrella.

**Comment by a18kaswi** [comment]
Closing due to @HGustavs decission that it might could make the system worse.
