### ISSUE TITLE
Not able to open Results, Tests etc. on a new tab.

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6290]
![image](https://user-images.githubusercontent.com/49199285/56736935-ac36a480-6769-11e9-97cb-9e847b100e60.png)

Unable to open these links/buttons on a new tab (ctrl or right-click open on new tab)

**Comment by b16johso** [comment]
This is a group B issue

**Comment by HGustavs** [comment]
Can it be achieved without making anything else worse?

**Comment by a17alian** [comment]
It could!! 🥇 💯 👍

**Comment by HGustavs** [comment]
It works on all browsers, with right click menu also, for opening in new tab?
