### ISSUE TITLE
cogwheel hover on courseed.php display a strange title. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6291]
If you hover the cogwheel for a course on courseed.php a kind of strange title will be shown.
Image of the title: 
![image](https://user-images.githubusercontent.com/49194898/56736864-84dfd780-6769-11e9-9be2-5954211563b5.png)

The value after the course name in the title is linked to the Version ID of the course and not the course code as i first thought.. 
If you click to edit the course this window will appear:
![image](https://user-images.githubusercontent.com/49194898/56737338-82ca4880-676a-11e9-931d-e736bd59c64c.png)

@HGustavs is this on purpose or is it some kind of misslinking?  Feels strange that the version ID will be shown in the title when you cant change it when you press the cogwheel. 
I suggest that the title will be changed to include the "course name" + "course ID" or all of it is removed and the title is changed to "Edit Course". To be honest i prefer the last suggestion..
What do you think?

**Comment by HGustavs** [comment]
I think we can remove the version ID from the title... it does not help the user much.
