### ISSUE TITLE
The submission table colors in showDugga.php do not fill the entire table block.

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6296]
The table in showDugga.php do not fill the entire table block. Here is a image of the table:
![image](https://user-images.githubusercontent.com/49194898/56739296-a1324300-676e-11e9-8156-adb8d610a608.png)

How about to make the table "stripes" fill all the way to the right or stretch the headings and content all the way to the right?

**Comment by HGustavs** [comment]
Yes, this can be better... make sure it looks ok with some sample feedback.... especially some longer feedback. Some teachers write something like two pages of feedback, unclear what a multitude of feedback looks like.

**Comment by a17poner** [comment]
merged, closing this(altough a bit slow on closing 😞 )
