### ISSUE TITLE
Map hotkeys to dropdown functions

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#6297]
Create hotkeys for as many of these as possible.
Wanted to create a discussion for which are the most intuitive.
"Reset view to origin" could perhaps be mapped to "Shift+0" etc.

![hotkeys](https://user-images.githubusercontent.com/49202727/56793354-27509700-680c-11e9-9646-dd0f6bb4d35e.png)

**Comment by HGustavs** [comment]
More details plz

**Comment by a17drama** [comment]
I do agree with @a17alfcl here. It's very nice to have hotkeys for as much as possible. Over time people tend to use these and it boosts efficiency compared to clinking menus all the time. Only thing to consider is the collision with existing hotkeys.

**Comment by HGustavs** [comment]
Two rules.

Anything that doesnt clash with browser functionality is in general fine...

and we dont have stuff that has hotkeys but not menu items (apart from enter and escape etc)

**Comment by a17alfcl** [comment]
Align might be "Shift + arrowKey"
