### ISSUE TITLE
Buttons change border radius on hover

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6300]
Minor nitpick - The border radius on buttons, for instance the OK button in the cookie message, changes on hover. Seems unintentional? It's not really that noticeable though.

**Comment by HGustavs** [comment]
This is surely cruft from an older version before material design and flat-ness.

Feel free to remove or to make it more material design-y but question is how hover looks in the latest material design? no action?

It is a good idea to make this a precedent and put this hover action on all button?
