### ISSUE TITLE
Contribution hourly chart

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#6304]
I would like an hourly chart in addition to the weekly chart currently available

Something like this

<img width="409" alt="Screenshot 2019-04-25 22 12 49" src="https://user-images.githubusercontent.com/6978801/56765495-79130600-67a7-11e9-8ca3-845e09baa026.png">

On hours above some treshold e.g. 5%, we paint a hoverable rectangle with detailed info.

It would be nice to show commit activity, issue activity etc in different colors ...

Displaying what hours a person has been committing/issue-writing and so on.

A decidedly nebulous view, depictinig only the hours of each type and computing the percentage compared to total... but nevertheless and estimate at which hours a person is most active.

Eg. 

If commits are green... and the user has made one commit on 21th of march at 13:12 and one commit at 15:35. The 13 point would show 50% and the 15 point would show 50% and we would see 
~~~
13:00-14:00 
50% activity
1 commit total of 2.
~~~

in the hover view.

At the same time we could see a polygon for events, showing the corresponding information for events, but in another color for example yellow might look like above.

**Comment by HGustavs** [comment]
Looking at the mock-up I would rather not have 24:00 at the top, but 12 noon at the top, makes more sense that the light hours are at the top and the dark less busy hours at bottom.

**Comment by a17joaap** [comment]
Progress so far:
![circleprogress](https://user-images.githubusercontent.com/37792198/56816146-3868ca80-6843-11e9-9409-2341f51c2a69.PNG)

Working on branch gruppC2019W18_6304

**Comment by a17joaap** [comment]
What kinds of activity do you want represented here? Looking at the database, there are no entries for pull requests which I find strange. However there are multiple different types of event including 'renamed', 'unlabeled', 'deleted' and so on.

I think the most relevant are comment, commit, issue and will start with these.

**Comment by a17poner** [comment]
Closing this, looks to me like all requested features got merged.
