### ISSUE TITLE
Redesign of the contribution page

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#6312]
Either add tabs or buttons for all the views, making it less cluttered. 

Some of these buttons and/or dropdown could probably be useful?
![image](https://user-images.githubusercontent.com/49199993/56791638-d0e15980-6807-11e9-95b2-298e173cb2df.png)

**Comment by a17maxsj** [comment]
@HGustavs how can we show the contribution page on local/webserver? contribution.php shows a blank page

**Comment by a17maxsj** [comment]
![image](https://user-images.githubusercontent.com/49199993/56795317-87e1d300-6810-11e9-98f2-5c8915b2335f.png)
 guessing we have to create the page in a course? cant seem to find it

**Comment by a17alevu** [comment]
Looks like all the lines are black now, meaning that every table (Files, Access etc.) have black lines. Not sure if this is a good solution ?

**Comment by a17adajo** [comment]
I think we also need a SQLite database to pull the data from as can be seen on this line:

https://github.com/HGustavs/LenaSYS/blob/0b3972bc464df6240a4088ec74e41fcd70bad63f/DuggaSys/contributionservice.php#L17

**Comment by a17maxsj** [comment]
Critical issues in starting work on contribution...

**Comment by HGustavs** [comment]
I supplied goup leader with the database.

Look in console log in browser if no error messages appear

...and also enable error messages on the development server...
often, error messages are disabled and only written to log file, making any debugging on a development server difficult.

**Comment by a17joaap** [comment]
Since we now have the database, we can create a contribution dugga by setting 'Link' to Contribution.
![contrib](https://user-images.githubusercontent.com/37792198/56905572-bfff4500-6aa0-11e9-8b0d-38e313fe5ea3.PNG)

**Comment by a17poner** [comment]
merged!
