### ISSUE TITLE
Strange title on hover 

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#6313]
When hovering over a course name in courseed.php, a lot of seemingly irrelevant information appears in the the title. Should course coordinator and versionID be displayed or can it be removed? @HGustavs 
<img width="389" alt="Skärmavbild 2019-04-26 kl  09 39 42" src="https://user-images.githubusercontent.com/37792256/56791465-692b0e80-6807-11e9-872a-f9e88db35ec5.png">

**Comment by HGustavs** [comment]
I have no idea even what this is ?

What does course coorindator even mean?
