### ISSUE TITLE
When scrolling horizontal in resulted. search tools, filters etc. doesn't follow

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#6314]
![image](https://user-images.githubusercontent.com/49199825/56791688-f53d3600-6807-11e9-9b9f-ca17ecad02ed.png)

is it efficient to have the components "Delkurs" "Betygsskala" Betygsdatum" etc. to follow when scrolling the view horizontal?

**Comment by c17julka** [comment]
#6253 talks about how the search bar should become sticky (currently in progress)

**Comment by c17johha** [comment]
![image](https://user-images.githubusercontent.com/49199825/56883035-c3c1a600-6a65-11e9-861b-58dac2e7cbb2.png)
@c17julka Does #6253 cover more than this search bar?
