### ISSUE TITLE
Drawing assistant

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6323]
Implement a drawing assistant that helps the user with indications of spacing, size, alignment etc. This is "on the fly" alignment and distribution.

It should draw out a line to show the user when the entities are aligned and this should cover both center alignment and top, bottom, left and right. 
Spacing should be indicated with double arrows.
![Edited](https://user-images.githubusercontent.com/46029340/56794298-26b90000-680e-11e9-84d8-e56db3ed5b0a.PNG)
When "Entity 3" is moved in the direction of the green arrow and achieves the same distance to "Entity 2" as the distance between "Entity 1" and "Entity 2" it should have the indication as it is shown with the blue arrows and have a small snap but the user should be able to continue moving.. (FYI This is done in paint and is not the final design of arrows. You are free to chose the style).
Similar indications should show when the size of entities is manipulated. Difference is that the double arrows are shown on the entities instead of between.

**Comment by b18simla** [comment]
Should this always be on, or should there be an option to toggle?

Also, if anyone got ideas on how to begin tackle this problem, please do share.

**Comment by b18simla** [comment]
@a17robhe did you get any progress before you were unassigned?
