### ISSUE TITLE
Sortabletable.js cleanup

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#6324]
The file is generally speaking an ill-documented mess, which makes working with it for any purpose difficult. I propose creating sub-issues for cleaning up various aspects of it, including e.g. reading and commenting existing code.
Any changes should preferably be localised such that no existing interfaces are broken.

**Comment by a17adajo** [comment]
I agree that any measure than can be taken to simplify the codebase (any codebase really) is a good thing but how can we simultaneously do this and still avoid trespassing in refactoring land?

**Comment by b17timjo** [comment]
Comments are of course safe, and changes should be safe so long as they are internal to a module - be it the particular file or a function in the file.

**Comment by HGustavs** [comment]
Commenting code works very well, but most other changes tend to affect behavior of the code which probably isnt permitted.

**Comment by b17timjo** [comment]
Consider changes such as re-ordering conditional statements in a function, or renaming a local variable, or using a different algorithm. Such changes do not affect anything outside the function, and are safe in terms of keeping the interface stable. I see no reason to disallow them.
On the other hand, e.g. renaming a variable or function visible to external scopes should be done with care.

**Comment by c17johha** [comment]
#6329 Part of job done

**Comment by b17nicsv** [comment]
@a17jakos Status on this?

**Comment by a18kaswi** [comment]
something-something refactoring madness. I will propose a sprint dedicated to clean up what we are possible able to clean up when we have more urgent matters under control.
