### ISSUE TITLE
Reset view to origin doesn't work 

### ISSUE THREAD

**Issue by a17jonro** [HGustavs/LenaSYS#6327]
Some functionality seems to have been removed when implementing the camera. Zoom also seems to break functionality.

**Comment by HGustavs** [comment]
If implemented correctly the reset should only set the xoffset to 0 yffset to 0 and set the zoom to 1.0

...

and then refresh the view, and it should be mostly automatic from there?

Or are we talking about some other reset?

**Comment by a17jonro** [comment]
No, that is correct. The reset view to origin function only needs to be adapted to the new canvas implementation, since it was different before the change.
