### ISSUE TITLE
The database do not handle swedish characters.

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6330]
Lena database do not handle swedish characters like ÅÄÖ.  Here is a image of the row values of the course table. 
![image](https://user-images.githubusercontent.com/49194898/56796898-d0e75680-6813-11e9-8f4c-1b71b87225e6.png)

Here is the course names on courseed.php
![image](https://user-images.githubusercontent.com/49194898/56796937-e6f51700-6813-11e9-9813-682510b27e62.png).

It is the same for the user table in the database meaning that names with ÅÄÖ can be missed in a querys.  
Is there a easy way to fix this?

**Comment by HGustavs** [comment]
In the database the data stored should use ~~~ ampersand o u m l semicolon ~~~ but it seems the displaying converts this to something else? Perhaps the code converts the ampersand character to ~~~ ampersand a m p semicolon ~~~

**Comment by a18andtu** [comment]
There doesn't seem to be a problem with using ÅÄÖ but might need more testing.

**Comment by a17robhe** [comment]
![before bug](https://user-images.githubusercontent.com/62876844/78361592-f00c6d80-75b8-11ea-8466-f6ff9b19a291.png)

While this works, if the course is then opened the characters aren't represented correctly in the name field:

![after bug(maybe)](https://user-images.githubusercontent.com/62876844/78361661-0c100f00-75b9-11ea-800c-6ec30f825cee.png)

@a18andtu

**Comment by a17robhe** [comment]
This issue is missleading. Continued in https://github.com/HGustavs/LenaSYS/issues/7839
