### ISSUE TITLE
Result funnel and sorting arrows using redudant code

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#6331]
Instead of using the icons created by navheader and simply setting their display to table-cell. A new pair are generated in js and used instead causing the same code to be in two places (resulted.js and navheader.php). Resulted.js should be changed to set the display of the two "icons" instead of creating two new ones.

**Comment by HGustavs** [comment]
Any static interface should be static in the php file and this does not seem to be the case?

**Comment by a17poner** [comment]
In navheader the sorting and filter buttons are echoed out but with a hidden display/display:none and then when they are used e.g. on accessed in the accessed.js setup function their style.display is changed to "table-cell" but in resulted.js they are created as a html string and then put into the div with jquery instead of simply changing the display style. additionally they do add two divs and don't add one of them but that can be done instead in the setup, e.g. removing the div that isn't used in resulted.js and adding the two that are and simply changing the display on the entire icon/div. Should make it easier in the future if the icon for the funnel were to get a new name instead of having to update two files.

**Comment by a17andby** [comment]
Merged, so closing this issue

**Comment by a17poner** [comment]
Seems that this issue is back on the gruppC2019W19_test_merge branch so reopening and labelling it up

**Comment by a17poner** [comment]
Closing this, migrating to a new issue. #6649
