### ISSUE TITLE
Undo and redo buttons doesn't work for align and lock function

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#6335]
Undo/Redo buttons don't take any align or lock functions (possibly other functions as well) into account and they are skipped. 
For example:
1. Create an entity, an attribute, and a line between them.
2. Select them all and align them in some way.
3. Press "Undo".
The result is not that the align is both undone _and_ the line is deleted.
Difficult to document with images.

**Comment by a17drama** [comment]
Close #6360 when this one is to be closed because they cover the same issue.
