### ISSUE TITLE
Holding down FAB on touch device causes error

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6340]
![image](https://user-images.githubusercontent.com/37834592/56800743-10b23c00-681c-11e9-8049-d8390f6bd558.png)

Holding down on a FAB makes the error shown in the picture appear. I believe this is because "touch-action:none" is missing from the FAB in style.css

**Comment by HGustavs** [comment]
Is this an issue that happens in other places also?
I guess that this is the only "press" button in the interface...

**Comment by b17carma** [comment]
> Is this an issue that happens in other places also?
> I guess that this is the only "press" button in the interface...

I believe this issue only occurs with FABs because of a change which was recently made to them where e.preventDefault is called

**Comment by a17andby** [comment]
Closing this issue since I merged a solution for this issue.
