### ISSUE TITLE
Lines will sometimes move when trying to move an locked object

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#6352]
It's kind of a random issue that only happens sometimes i've noticed, I'll try to explain it. Everything works even if this issue exists, it is just kind of weird when it actually happens.

![image](https://user-images.githubusercontent.com/49199287/56805443-5aedea00-6829-11e9-9b09-9afd8285916c.png)
I found one way to make it consistent though, In the picture above I have the mouse just at the second t in the default attribute name. Notice where the lines are placed.

![image](https://user-images.githubusercontent.com/49199287/56805513-95f01d80-6829-11e9-9ca7-e0ebb84604a2.png)
In this picture I clicked and held the mouse at the second t like in the other picture. Then I tried dragging the object to the right. And now the lines have suddenly moved. You can also see that one of the lines is selected, even though I did not even try to select it. I just tried dragging the locked object.

![image](https://user-images.githubusercontent.com/49199287/56805621-f2533d00-6829-11e9-9ee8-cbf7de8d3a6d.png)
This seems to happen when trying to drag the object up, left or down aswell.

![image](https://user-images.githubusercontent.com/49199287/56805754-4827e500-682a-11e9-89e6-9fbec72eae80.png)
When I let go of the mouse the lines seem to adjust themselves and it goes back to the way it was before. It is barely an issue, but still quite interesting.

**Comment by a17jacsv** [comment]
This issue seems to be solved and can be closed as the problems do not exist anymore. @a17vikab

**Comment by a17vikab** [comment]
> This issue seems to be solved and can be closed as the problems do not exist anymore. @a17vikab

Perfect!
