### ISSUE TITLE
Undo doesn't work correct

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6360]
When the user locks an entity and draws a new one and then does an undo it removes the newly drawn entity and the lock from the action before. Removal of the new entity is fine but the lock should remain.

**Comment by HGustavs** [comment]
I think undo should basically just re-read the last version whatever that is.

If it is implemented correctly, all older versions should be saved?

So, undo should basically entail taking one step back.

**Comment by a17drama** [comment]
Exactly. And it does do so but not in all cases.

**Comment by a17drama** [comment]
This issue is redundant due to #6335 .
