### ISSUE TITLE
Investigate/remove stats 

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#6361]
This might be unused:
![image](https://user-images.githubusercontent.com/49199993/56806770-2c720e00-682d-11e9-959f-96fcd0304e65.png)
Please investigate functionality and remove if possible

**Comment by HGustavs** [comment]
In which dialog is this happening?

**Comment by b17annni** [comment]
@HGustavs clarification?

**Comment by b17annni** [comment]
Seems to be unused and abandoned.

**Comment by a17adajo** [comment]
@HGustavs It is from the document you provided at the start of the course

**Comment by a17andby** [comment]
https://github.com/HGustavs/LenaSYS/pull/6410

**Comment by a17andby** [comment]
Closing this issue since I merged the solution
