### ISSUE TITLE
Group links can be pressed far away from the text

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6367]
Trying to hover a group:
![image](https://user-images.githubusercontent.com/37834592/56808236-46adeb00-6831-11e9-8c78-24d9aefe636e.png)

Trying to hover a code link:
![image](https://user-images.githubusercontent.com/37834592/56808264-5a595180-6831-11e9-9566-36b90b788974.png)

I think it's weird that groups can be pressed like that when no other link can & I think having unified standard behavior for all different links in sectioned.php would be better.

**Comment by a17andby** [comment]
Closing (since merged this solution)
