### ISSUE TITLE
Content in acces page is hidden

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#637]
Click the acces button in edit course to get to the page

**Comment by c13andka** [comment]
I think we will need a comment from the our customer how they would like this site to look before we unblock all information inside the site

**Comment by c13chrjo** [comment]
Yes I agree!

**Comment by b13alebr** [comment]
Related to issue #581 - Access button redirects to a new page

**Comment by a13chrju** [comment]
#774 already solved
