### ISSUE TITLE
Add some styling to the Zoom range. 

### ISSUE THREAD

**Issue by a17okaoz** [HGustavs/LenaSYS#6379]
Add some styling to the Zoom range. Now it´s looks kind of basic. 

<img width="184" alt="b1" src="https://user-images.githubusercontent.com/37792681/56883690-b7d6e380-6a67-11e9-8697-2f852c10e3a6.PNG">

**Comment by a16tobfr** [comment]
What kind of styling do you have in mind? To be honest, I think it already looks good, and it agrees with the overall look of the page.
If you could give me some examples of what to add, I might get a better picture of how to solve this issue

**Comment by a17okaoz** [comment]
The thing you drag to increase and decrease the Zooming can be round instead of the existing shape

<img width="204" alt="b1" src="https://user-images.githubusercontent.com/37792681/56898554-a276af00-6a91-11e9-9059-2da2d3a26d77.PNG">
