### ISSUE TITLE
Improve the design of the zoombar

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6385]
Please improve the design of the zoom-bar... Fix all the content to be centered. Please add "border-radius" to the "+" & "-" buttons for a cleaner view.

<img width="304" alt="Skärmavbild 2019-04-29 kl  10 34 19" src="https://user-images.githubusercontent.com/37792795/56884527-5f551580-6a6a-11e9-81f4-7f0abf88f445.png">

**Comment by a17celal** [comment]
I believe that this issue is fixed now?

![Capture10](https://user-images.githubusercontent.com/37792271/56955704-736c4600-6b42-11e9-96f5-976b1eff6bd7.PNG)

**Comment by a17jacsv** [comment]
It's better, but I want it to be exactly centered (Just as much space up as down).
