### ISSUE TITLE
ER line can be drawn between UML objects

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6388]
ER lines can be drawn between UML objects, should not be possible
![erLineBetweenUML](https://user-images.githubusercontent.com/49199690/56885903-fbcce700-6a6d-11e9-814d-23a1ec6c643c.JPG)

**Comment by a17drama** [comment]
The UML line and the ER line will be merged into one line in the future. This is being worked on.

**Comment by a17johpe** [comment]
Yes, when https://github.com/HGustavs/LenaSYS/issues/6415 is solved this issue is likely to be solved at the sae time

**Comment by a16tobfr** [comment]
This is solved (probably #6315), and the issue can now be closed.

**Comment by a17vikab** [comment]
Solved.
