### ISSUE TITLE
Removing UML lines may result in odd behaviour

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6389]
Having two UML lines between UML objects and removing one of them will result in odd behaviour
![removingUMLLineOdd](https://user-images.githubusercontent.com/49199690/56886201-b8bf4380-6a6e-11e9-94b9-9fa9ff7921a6.JPG)

**Comment by a17drama** [comment]
What is the orange line covering the blue line above the "New1" class?

**Comment by a16tobfr** [comment]
This does not seem to be a problem any more, issue can be closed

**Comment by a17vikab** [comment]
Solved.
