### ISSUE TITLE
UML lines change appearance on zoom

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6392]
The appearance should be concurrent and not change when zooming in or out
On zoom 100%
![umlLineOriginalAppearance](https://user-images.githubusercontent.com/49199690/56886453-5ca8ef00-6a6f-11e9-9e64-c74130eac693.JPG)
On Zoom +- 10%
![umlZoomAppearance](https://user-images.githubusercontent.com/49199690/56886499-6e8a9200-6a6f-11e9-92b5-aa08b44898c1.JPG)

**Comment by a17jonro** [comment]
This also seems to happen when just moving in the canvas.

**Comment by a17johpe** [comment]
Duplicate of https://github.com/HGustavs/LenaSYS/issues/6452: "UML Line stops working when zooming in/out, or moving camera"

**Comment by a16tobfr** [comment]
Issue can be closed, not a problem anymore.

**Comment by a17vikab** [comment]
Solved.
