### ISSUE TITLE
Wrong kind of cursor when hovering over symbols while in line mode

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#6397]
When one of the lines tools is selected, the cursor still changes to "move around" style when hovering over an object. 

![cursor](https://user-images.githubusercontent.com/37792313/56888541-857fb300-6a74-11e9-8809-28015b1d1d55.png)

This is only an issue with line drawing tools.

**Comment by a16jenja** [comment]
#6377 is related to this issue.

**Comment by a17vikab** [comment]
Solved.
