### ISSUE TITLE
Email vulnerability allows an attacker to retrieve all emails associated with a given course

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#6398]
The following code runs without checking if the user has a valid login:
https://github.com/HGustavs/LenaSYS/blob/0b3972bc464df6240a4088ec74e41fcd70bad63f/DuggaSys/resultedservice.php#L72-L104

This allows a malicious actor to retrieve all emails for a course (students and teachers alike) using only publicly known information, by simply sending a POST request with the correct parameters.
This may be a breach of GDPR, as email addresses may be used to identify individuals.

This is mitigated by the ability to block direct access to this page via webserver configuration, but that should not be relied upon.

**Comment by a17adajo** [comment]
I have not looked at detail at the code and vulnerability you are describing but I guess that it would be easy to craft the correct POST parameters just by looking at the publicly available code in this GIT repo to figure it out?

**Comment by a17adajo** [comment]
Just to clarify: I am not suggesting that having the code behind closed doors would be a solution (that would simply be "Security through obscurity" )

**Comment by b17timjo** [comment]
> I guess that it would be easy to craft the correct POST parameters just by looking at the publicly available code
More or less correct: you need the "cid" and "coursevers", which depend on database contents. However, these parameters are both visible in the URL when visiting a course page with the public guest account. And as the database fields are known via the repo (if the deployed site has not made changes) they can also be targeted by brute-force.
