### ISSUE TITLE
Possible misrepresentation of ssn may be a breach of GDPR

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#6401]
The following code uses a hard-coded constant which assumes an ssn refers to the 1900:s
https://github.com/HGustavs/LenaSYS/blob/0b3972bc464df6240a4088ec74e41fcd70bad63f/DuggaSys/resulted.js#L1078-L1082

This should be investigated: depending on how this data is used it may be a breach of GDPR by misrepresenting personal information, if the ssn refers to an actual birth-date and the individual is not born in the 1900:s.

**Comment by a17adajo** [comment]
Nice find. do you know under what chapter in the GDPR this is described?

**Comment by b17timjo** [comment]
Chapter 2, article 5 mentions that data shall be accurate and up-to-date

**Comment by a17oscno** [comment]
Would it be more accurate to not assume at all and if a ssn do not contain the first 2 digits (e.g 010101-XXX X instead of 11010101-XXXX) to just write it out as it is? or can the assumption that noone that is a student or teacher on the school is over 100 years old and with that use the current date to compare to see if a person is born in the 1900:s or 2000s @b17timjo

**Comment by a17oscno** [comment]
or later by making it generic with the dates by using the current date (year)

**Comment by b17timjo** [comment]
Contrary to popular belief, swedish pnr:s are not guaranteed to include the birth-date of the given individual (e.g. the correct date may not have been available) and their only true purpose is to uniquely identify an individual for government purposes.

**Comment by b17timjo** [comment]
So, I would think the "19" prefix should be removed entirely

**Comment by a17pongo** [comment]
@a17oscno what is the status on this? 
since I made a PR that takes back ssn but does not fix this issue, I am open to take over it and make the appropriate changes.

**Comment by a17oscno** [comment]
@a17pongo Well the status is that we just removed the option for the system to "assume" that you are born in the 1900 if you don't specify. And that won't break any GDPR rules (as far as I know). But i guess it depends what you have in mind with "appropriate changes".

**Comment by a17pongo** [comment]
@a17oscno with changes I meant removing it as timm sugested or if there is a better solution, but it seems like it is solved?

**Comment by a17oscno** [comment]
@a17pongo I think if you look at the pull request for issue #6004 then those changes should already be implemented but they are probably outdated due to it being weeks ago since i made them.

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
