### ISSUE TITLE
Error message in sectioned.js

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6405]
![Capture](https://user-images.githubusercontent.com/37834592/56895165-7dca0980-6a88-11e9-8b05-0b1316866096.PNG)

**Comment by a17andby** [comment]
@b17carma How do I reproduce this error message?

**Comment by b17carma** [comment]
Try visiting a few different course pages from courseed.php and the error should pop up in the console for some of them

**Comment by a17andby** [comment]
@b17carma Can you give an example of a page that shows this error? 

I have gone through all the course pages and I don't seems to reproduce this error on my test environment (gruppC2019W18 branch)

**Comment by b17carma** [comment]
> @b17carma Can you give an example of a page that shows this error?
> 
> I have gone through all the course pages and I don't seems to reproduce this error on my test environment (gruppC2019W18 branch)

I tried setting up a fresh database and am unable to reproduce the issue now as well which means that something may have been wrong with my previous database. I'll do some more testing to make absolutely sure that I can't reproduce it.

 If I can't reproduce it, I think we can assume it was a problem on my end and not with the system.

**Comment by a17andby** [comment]
@b17carma Yes please do some more testing on your side and tag me here when you are done

**Comment by b17carma** [comment]
@a17andby I can't recreate it, so I think you can close the issue & cancel the pull request

**Comment by a17andby** [comment]
@b17carma Okey :)
