### ISSUE TITLE
Tests edit -> disable does not work 

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#6408]
Pressing the disable version button does nothing on the page, please fix.
![image](https://user-images.githubusercontent.com/49199993/56895514-97b81c00-6a89-11e9-9397-3d1f5866a4b2.png)

error in console pressent 
duggaed.php

**Comment by a17joaap** [comment]
Seems to work now? Can you give steps to recreate issue?

**Comment by a17poner** [comment]
Semi related to this, the disable button does not work and is greyed out/disabled if there is anything in answer since that causes a json parse error on line 252 to get information to the left, shown in #7175

**Comment by c14jonfr** [comment]
I believe this is not an issue anymore. I can both disable and enable tests/variants as I want. I will look into it a bit more but this will likely be closed.
