### ISSUE TITLE
Error when clicking FAB in access

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6424]
![accesserror](https://user-images.githubusercontent.com/37792198/56904616-f76cf200-6a9e-11e9-913e-350dc3133611.PNG)

**Comment by a17maxsj** [comment]
This is probably since the long click was changed to a hover, can probably be removed.

**Comment by a17andby** [comment]
This issue still exists after the weekly merge. 
![image](https://user-images.githubusercontent.com/49235724/57161509-172c4f00-6dec-11e9-8487-c0f964e2c414.png)
