### ISSUE TITLE
Discrepancy between user import csv and accessedservice

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6425]
According to [HGustavs](https://github.com/HGustavs/LenaSYS/issues/5940#issuecomment-483536323), this is the csv they use for importing/creating users:

```
18972221-8475;Piraten-Nilsson; Sven;92337 ; 2019-01-21 - 2019-03-31 ; 50% ; Normal;Ej påbörjad;WEBUG
18531603-5473;Grishufvud; Egon;92337 ; 2019-01-21 - 2019-03-31 ; 50% ; Normal;Registrerad; ej avklarad (1);DVSUG
```
This format is incompatible with accessedservice.php:
Line 173:
```
                  $firstname = $user[1];
                  $lastname = $user[2];
                  $className = $user[count($user)-2];
                  $saveemail = $user[3];
                  $regstatus = $user[count($user)-1];

```

As you can see, firstname and lastname are switched, className, saveemail, and regstatus all have the wrong index.

But, according to @HGustavs they use this, so it apparently works for them. Is the live version running a different version of accessedservice.php?

**Comment by a17adajo** [comment]
I have been thinking about this… when issues are created, should we clarify where the issue at hand are present? I seems that the current master on GIT and the live version can differ severely. And that can lead to lots of wasted time provoking a bug that may or may not be present in the test environment.

**Comment by a17andby** [comment]
Waiting for @HGustavs response if live version runs a different version of accessedservice.php before I merge https://github.com/HGustavs/LenaSYS/pull/6423

**Comment by a17poner** [comment]
@HGustavs, bump. This issue has been with a fix since week 18 and wasn't meeged before getting a comment from you. Don't want it to have to miss out on a second merge if we are going to keep tje changes/fixes :smiley:

**Comment by HGustavs** [comment]
Does it work with the supplied test data?

In that case it works.

It may be that one system has
Firstname Lastname
whereas the other has
Lastname Firstname

**Comment by a17joaap** [comment]
> Does it work with the supplied test data?

It does not.

`$saveemail = $user[3];`
With the data provided, this gets set to whatever course id we put in, '92337' in this case.
Saveemail is then used to create the username:
`$username = explode('@', $saveemail)[0];  `


These are also wrong:
```
$className = $user[count($user)-2];
$regstatus = $user[count($user)-1];
```

With this input:
`18972221-8475;Piraten-Nilsson; Sven;92337 ; 2019-01-21 - 2019-03-31 ; 50% ; Normal;Ej påbörjad;WEBUG`

className = "Ej påbörjad" & regstatus = WEBUG

**Comment by HGustavs** [comment]
Make it work with this given data, if it works it works with the data format exported by the uni at the start of the course.

This will be considered best effort.

**Comment by a17joaap** [comment]
I don't see how it could work with the given data. There is no email from which to parse a username from. We could get the 'joaap' bit, but not the 'a17' part, which prevents duplicates. There is also the issue of the two given examples being different lengths. The first example has 9 items while the second has 10.

**Comment by HGustavs** [comment]
~~~"18481724-5557";"Fritfjof";"Nilsson Piraten";"a48fripi@student.his.se";"booboo@mail.nu";"WEBUG";"Avklarad" ~~~

Re-re-checked again the data above is the current (ever changing) export data for each student there is a new line in the file.

ssn firstname lastname email additional email study programme code

...We should ignore additional email and code....

**Comment by a17joaap** [comment]
Accessedservice is now correct, closing this
