### ISSUE TITLE
Free draw mutation

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6429]
When drawing a free draw object and switching to another symbol without finishing the free draw some funny things start to happen. Free draw should be auto completed as soon as the user switches to another symbol.

**Comment by a17drama** [comment]
Just noticed that it's not possible to click the mutated object to select it. Instead the user has to make a click and drag selection.

**Comment by g18marma** [comment]
An easy fix to remove the mutation would be to trigger the cancelFreeDraw function when changing modes.
