### ISSUE TITLE
Error occur when refreshing page and moving mouse where canvas is

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6433]
When refreshing the page and moving the mouse, this error seem to occur every time. Should investigate what it is, why it is happening, and if we can fix it.
![errorOnMoveAround](https://user-images.githubusercontent.com/49199690/56947599-f505a900-6b2d-11e9-9291-f0f1ee8ea062.JPG)

**Comment by a17alfcl** [comment]
Change browser

**Comment by a17jonro** [comment]
I'm not entirely certain but this issue seems fixed. I also had this problem before but i cannot recreate it anymore in the current branch.

**Comment by a16tobfr** [comment]
Same here. The error seems to no longer be possible to reproduce.

**Comment by a17vikab** [comment]
closing this issue because people have trouble to reproduce the problem.
