### ISSUE TITLE
Points & locks doesn't scale with zoom

### ISSUE THREAD

**Issue by a17jonro** [HGustavs/LenaSYS#6434]
The solution for issue #6357 fixed so that lines scales with zoom level. But when objects are selected the points that appear doesn't scale with zoom.
They look either very small or very big when zoomed in or out respectively.

Zoomed out, points look too big:
![image](https://user-images.githubusercontent.com/49195133/56947724-4e6dd800-6b2e-11e9-8bb6-5f198c0b87d1.png)
Zoomed in, points are small:
![image](https://user-images.githubusercontent.com/49195133/56947734-53cb2280-6b2e-11e9-8dcb-bdc93eea14ae.png)
Normal size:
![image](https://user-images.githubusercontent.com/49195133/56947764-6c3b3d00-6b2e-11e9-8d05-d86d506fcf8f.png)

**Comment by a16tobfr** [comment]
I want to add that the same problem seems to occur when it comes to locked objects. The locks are not scaling correctly aswell.
