### ISSUE TITLE
Unintentional move of entities

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6440]
If the users intention is to right click and drag to move the camera and the user accidentally clicks on an entity two things happen. Camera is moved but so is the object. Right clicking and raging should not move entities.

**Comment by a17adajo** [comment]
I dont know, maybe "Right clicking and **raging**" should move the entities ;)

**Comment by a17drama** [comment]
Maybe we could do this without rage and change the word to dragging. :D "Right clicking and dragging".
