### ISSUE TITLE
background cell color in contribution ranking has a hard coded student amount

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#6446]
![image](https://user-images.githubusercontent.com/49194938/56949475-52502900-6b33-11e9-9c7d-af0191ace83b.png)
the nunmber 41 is hard coded instead of received from the ajax that returns ranking score. Picture is taken on a branch with groupRanks and it would be nice to get those correct as well and returned by the ajax (sizeOf(groupMembers). Probably worth doing both at the same time and not working this issue until the groupRankings have been merged to gruppC and to see if henrik is okey with that or if adding a way to see the exact numbers in the course and group breaks any integrity things.

**Comment by a17adajo** [comment]
Maybe the number should be the amount of registered students on the course?

**Comment by a17poner** [comment]
uhm yes? this is what was suggested in the issue originally...

**Comment by a17adajo** [comment]
I was thinking, what if some students has not made any contribution, should they still be added to the total amount of students or not?

**Comment by a17poner** [comment]
merged and closing 😈
