### ISSUE TITLE
Resulted: Removal of sorting-dropdown in navbar

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#6447]
There is no longer any use for this atleast in the resulted-page. With sortable headers this function becomes redundant.

**Comment by b17nicsv** [comment]
I would say it is more intuitive to use the sorting in navbar since filter also is there. It isn't intuitive to be able to sort multiple times. There should only be one way to sort rows and one way to sort columns.

@HGustavs What are your opinions on this? Would you like to use sort in the navbar or the headers on the columns?

**Comment by a17amama** [comment]
@HGustavs If i remember this correctly, you would like to keep it the way it is to be able to filter multiple things at a time, right? Should i close this issue or keep it open?

**Comment by HGustavs** [comment]
We dont sort colums?

We filter rows, and we filter columns...

And we sort rows depending on a specific column.

Some users consider clicking column headings intuitive for sorting on columns, some users consider the same operation in the menu to be intuitive. For users that have poor eyesight, it is crucial to have the bigger item in the arrow drop-down to click on... which is much larger than the column heading.

**Comment by HGustavs** [comment]
I am assuming we are talking about which column we set the sort order after?

**Comment by HGustavs** [comment]
It is a crucial feature to be able to filter on both rows (looking glass) and columns (funnel) so we do not want any changes on that general behavior. 

Apart from perhaps being able to click/unclick sub-elements if we filter on a moment, all sub-element should also click/unclick to reflect.

**Comment by b17nicsv** [comment]
Closing this. We'll keep both the sort in the navbar and the column header sorting.
