### ISSUE TITLE
UML Line stops working when zooming in/out, or moving camera

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#6452]
When you're zooming in or out, or moving around with the camera, the UML line stops working properly. The line loses it's kinks, which can be shown in this screenshot:

![9266469884464b05b9b4d26527441aaa](https://user-images.githubusercontent.com/38030926/56950964-e7085600-6b36-11e9-8d5d-fb3e4aaded11.png)

**Comment by a17johpe** [comment]
I think @b17robev said it had to do with function(?) "pixelsToCanvas"?
