### ISSUE TITLE
VOTING!!! -  Where should the toolbar be? Vote in comments!

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#6457]
Leave a print screen of the window with the toolbar at the position that it could be initiated to or statically set to. Thumbs up at the option that you vote for if it already exists

**Comment by a17alfcl** [comment]
My suggestion is to make the buttons static at the top.
![toolbar](https://user-images.githubusercontent.com/49202727/56956803-7ae11e80-6b45-11e9-9677-34eeccc7a84e.png)

**Comment by a17jacsv** [comment]
I do support this addition. This would be a more user-friendly and a smoother view in my opinion. What do you think @HGustavs?

**Comment by a17drama** [comment]
Due to our democratic society this voting is over. Winning suggestion is the one by @a17alfcl with 10 votes out of 14 total. This suggestion is accepted by the council. Thank you for your votes.

**Comment by a17jacsv** [comment]
You're free to go ahead with this solution @a16tobfr.

**Comment by a16tobfr** [comment]
After having had a democratic discussion, the toolbar will instead be moved to the left and be displayed in a vertical manner. This means that the canvas will also have to be moved a bit to make room for the toolbar.
![toolbar](https://user-images.githubusercontent.com/49199690/57129708-8af03c80-6d97-11e9-9dd6-fc076e2800c4.JPG)

**Comment by a14oscna** [comment]
Agreed with the comment above, further inspiration can be taken from the following:
https://www.photoshopessentials.com/basics/photoshop-tools-toolbar-overview/

**Comment by a17vikab** [comment]
Issue solved, closing issue.
