### ISSUE TITLE
Some duggas can't be viewed properly on mobile

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6458]
Transformation dugga:
![image](https://user-images.githubusercontent.com/37834592/56956588-ee366080-6b44-11e9-929c-92c4363dfb7e.png)

This applies to many of the duggas using more complex templates (check sample data for course "Webbutveckling - datorgrafik" for more examples)

**Comment by a17joaap** [comment]
Working on this right now. So far, the templates I've found that does not do well on mobile are:

- html-css-dugga
- transforms-dugga
- clipping_masking_dugga
- boxmodell
- curve-dugga
