### ISSUE TITLE
No padding for empty course message in sectioned.php

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6467]
I think adding a 5px padding on this message would make it look better.
Before:
![image](https://user-images.githubusercontent.com/37834592/56959564-1bd3d780-6b4e-11e9-8122-b6b713f556e2.png)
After:
![image](https://user-images.githubusercontent.com/37834592/56959612-46be2b80-6b4e-11e9-8d2c-6f0d0845b545.png)

**Comment by b17albbe** [comment]
I agree that this would look better

**Comment by a17robda** [comment]
I agree.

**Comment by a17andby** [comment]
Looks much better! I merge the solution and will close this issue.
