### ISSUE TITLE
Is var pressTimer important or should it be removed? 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6473]
I had an issue about the FAB button is accessed.php, Whenever it was clicked an error would pop-up in the console. This was solved when i removed the parameter pressTimer in accessed.js 

![image](https://user-images.githubusercontent.com/49199285/56960165-38710f00-6b50-11e9-8dab-579bf075d241.png)

When clearTimeout(pressTimer) was removed no errors would show up. So should we just delete all pressTimer?

**Comment by a17andby** [comment]
The issue @a17alevu is talking about is https://github.com/HGustavs/LenaSYS/pull/6435

**Comment by b17carma** [comment]
If I remember correctly, pressTimer is used to open the extended FAB list on touch devices

**Comment by a17andby** [comment]
I closed the first solution (https://github.com/HGustavs/LenaSYS/pull/6435) since I just created other issues. We need to rethink a solution for this issue.

**Comment by a17andby** [comment]
Since we found that pressTimer is important we maybe should close this issue? We already have a new issue (https://github.com/HGustavs/LenaSYS/issues/6424) up and we have closed the original issue https://github.com/HGustavs/LenaSYS/pull/6435 

What do you say @a17alevu ?
