### ISSUE TITLE
Inconsistent styling/visuals for the redo and undo buttons

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#6485]
Between all of the tool buttons, there seems to be an inconsistency for the redo and undo buttons when it comes to the visuals. Either they are slightly off center, or they're not matching size wise. Here are some screenshots showcasing this:

![8a85fc607fb5c326c0d4cd30480b8bac](https://user-images.githubusercontent.com/38030926/57061971-2661ae80-6cbf-11e9-8c97-0227915e0cca.png)

![9e46b255c941f192056bcc59feb58bb0](https://user-images.githubusercontent.com/38030926/57061995-38dbe800-6cbf-11e9-8d37-278de5fb6949.png)

**Comment by a17vikab** [comment]
Solved.
