### ISSUE TITLE
Option to show/hide text

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#6487]
I think it would be great if you could have the option to hide or show text. That way you can have both a commented version, but also a clean version if you choose. This would also allow the user to have notes that wouldn't otherwise be included with the diagram.

**Comment by a17drama** [comment]
This is a great idea but not all text is "comments". You can add text to clarify things (don't know if ER or IE) and this should be visible at all times. But we could implement a comment entity that can be toggled or showed on hover.

**Comment by b17albbe** [comment]
That makes sense. How about having the option to make certain texts "comments"? For example, having a tick box in the appearance menu that toggles wether or not it's a comment.

**Comment by a17celal** [comment]
Maybe it could be like sticky notes? You can make a note and drag it wherever you want and have the option to show/hide it.

**Comment by a16jenja** [comment]
This issue is still relevant and should still be implemented in my opinion, right now there is not enough time to implement this new function in my opinion. But for the people next year, this is a good addition to implement.
