### ISSUE TITLE
Lines connect to wrong sides when resizing boxes to less than min. dimensions

### ISSUE THREAD

**Issue by c17matjo** [HGustavs/LenaSYS#6491]
This issue appeared while solving #6180. If a box is resized to less than it's minimum dimensions, sometimes connecting lines flicker over to the wrong sides of the box. 
![bild](https://user-images.githubusercontent.com/49195031/57063490-bd306a00-6cc3-11e9-8fc8-3ad9d8909f90.png)

**Comment by a18kaswi** [comment]
Possible connected:
#5057
#6491
#7491
#7673
