### ISSUE TITLE
Increase responsivness burger 

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#6499]
![image](https://user-images.githubusercontent.com/37792766/57064752-91af7e80-6cc7-11e9-908a-b0dbe5158c79.png)

Could be more graceful.

**Comment by a17adajo** [comment]
What do you mean by **"burger"**?

**Comment by a17maxsj** [comment]
@a17adajo the burger menu, probably in sectioned.php

**Comment by b17annni** [comment]
In fullscreen mode.
![image](https://user-images.githubusercontent.com/37792766/57220697-a445f280-6ffc-11e9-9078-b24236d10965.png)
In smaller mode.
![image](https://user-images.githubusercontent.com/37792766/57220759-c9d2fc00-6ffc-11e9-9f6f-2aaf89ba99d9.png)

**Comment by a17poner** [comment]
merged, closing.
