### ISSUE TITLE
Courses stays when you loggout and loggin box shows when you push for loggout 

### ISSUE THREAD

**Issue by c13andka** [HGustavs/LenaSYS#650]
When you login to the page, it work perfekt. But when you loggout, sometimes the courses will stay on the page even when you are outlogged. If you update, the courses will dissaper. So it should be easy to fix this issue, with page update (get courses again after you have logged out )

One more issu is that when you loggout the inlogg box will show, this i think is wrong. Please fix

**Comment by c13chrjo** [comment]
Is this related to all groups or just duggaSYS?

**Comment by c13chrjo** [comment]
This problem is not present on any of my browsers (Firefox, IE, Chrome). But I will leave this open for now.
