### ISSUE TITLE
UML lines should not be moveable

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#6500]
![image](https://user-images.githubusercontent.com/49199287/57064650-37162280-6cc7-11e9-9602-b91981388817.png)
Before.
![image](https://user-images.githubusercontent.com/49199287/57064667-42694e00-6cc7-11e9-8fdc-eeef8008e9d9.png)
After.

Since the ER lines are not moveable, the UML lines should not be moveable either i feel like. The lines should be static between the two objects.

**Comment by a17johpe** [comment]
We're currently not able to recreate this issue. Might be because of some other issue that has been solved.

**Comment by a17celal** [comment]
I think this issue is colliding with issue #6577 ?

**Comment by a17johpe** [comment]
No, this issue was specifically about being able to move the line's start and end points manually (which you shouldn't be able to when we can move the lines manually either).

**Comment by a17jacsv** [comment]
> We're currently not able to recreate this issue. Might be because of some other issue that has been solved.

I can't either. Is this issue already been solved? @a17johpe

**Comment by a17johpe** [comment]
This issue can probably be closed and then reopened if/when the issue appears again. It seems to have been magically been solved/caused by some underlying issue that isn't there currently.

**Comment by a17jacsv** [comment]
> This issue can probably be closed and then reopened if/when the issue appears again. It seems to have been magically been solved/caused by some underlying issue that isn't there currently.

@a14oscna & @a17vikab

**Comment by a17vikab** [comment]
Closed.
