### ISSUE TITLE
Toggle row in resulted.js and sortabletable.js

### ISSUE THREAD

**Issue by a17anter** [HGustavs/LenaSYS#6501]
Subissue to #6245

When filtering/searching in resulted.php the array "currentRowFilter" in sortabletable.js should be modified to only contain visible users in the table.

Make togglefunctions similar to how "column" is handled.

**Comment by c17johha** [comment]
What is the purpose of currentRowFilter? I can only find one reference and that's when it's created. 
Maybe the array filteredRows actually do what currentRowFilter is supposed to do?

**Comment by a17pongo** [comment]
@c17johha was this fixed in pull request #6771 ?

**Comment by c17johha** [comment]
@a17pongo I believe that the array filteredRows does the job, which was fixed in #6771 . But Im not sure because I dont really know what filteredRows is supposed to do. If currentRowFilter should contain all current/visible rows, then I think filteredRows is a better describing name

**Comment by b17nicsv** [comment]
Status on this?

**Comment by HGustavs** [comment]
No idea really what the purpose is.

It may be cruft that is only there so the functionality does not break in old implementations.

**Comment by a17anter** [comment]
The functionality to only mail the visible students has been implemented by @c17johha but in another way than explained in the issue.

Issue could be closed.
