### ISSUE TITLE
Course page: Stoplight circles are not vertically aligned

### ISSUE THREAD

**Issue by a17fellu** [HGustavs/LenaSYS#6503]
**The circles are missing some margin for the bottom:**
![coursePageCircles](https://user-images.githubusercontent.com/49202955/57065395-8eb58d80-6cc9-11e9-97b4-c51899d2f00e.PNG)

They should get the same bottom margin as top margin

**Comment by a17fellu** [comment]
Fixed in Pull Request: #6536

**Comment by a17andby** [comment]
This is not our area of responsibility. This is gruppB2019 area of responsibility.

**Comment by a17poner** [comment]
this isn't ours but for this occassion we could take it and merge it but avoid any sectioned issue in the future.
