### ISSUE TITLE
Move cursor is showing when trying to draw UML lines

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#6507]
![image](https://user-images.githubusercontent.com/49199287/57066459-8448c300-6ccc-11e9-8758-36690f236e56.png)

The issue #6377 was supposed to adress this problem. I was assigned to that issue, but I only fixed the problem when drawing ER lines. I forgot about the UML lines. My bad.

**Comment by a17drama** [comment]
This issue is covered by #6377 . Marking as redundant and tagging this issue in the older one.

**Comment by a17drama** [comment]
This issue is covered in #6377 . Tagging this one in the old one and marking it redundant.
