### ISSUE TITLE
DuggaEd: Can't delete tests

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6512]
Getting an error when trying to delete tests:
![premergedelerr](https://user-images.githubusercontent.com/37792198/57066725-48622d80-6ccd-11e9-8990-48c6198735d6.PNG)

**Comment by a17joaap** [comment]
Problem fixed after refresh

**Comment by a17maxsj** [comment]
![image](https://user-images.githubusercontent.com/49199993/57066790-7fd0da00-6ccd-11e9-8ca0-a3665bd97f26.png)

if trying to delete from the variants menu
