### ISSUE TITLE
Issues with the sorting system inside resulted

### ISSUE THREAD

**Issue by a17amama** [HGustavs/LenaSYS#6515]
The sorting system has quite a few issues, when sorting after grade U, it displays the ungraded first which i am not sure should be classified as U and therefore not be the first to be displayed. Also, when sorting after the grade G, it does not work, instead it will sort after VG. I assume the sorting option P is just to show which one you have marked, however there is also a sorting option "-" and I am not quite sure baout what it does or the reason for it.
![hmmm](https://user-images.githubusercontent.com/37793130/57067042-3765ec00-6cce-11e9-9594-398cba6bb951.PNG)

**Comment by b17nicsv** [comment]
I agree the sorting is unclear, however when sorting by G it returns all tests which passed including VG. Sorting by U gives unmarked and tests which failed. Sorting by P should return pending tests, which is yet to be graded.

I'd like to see that when you sort by VG it returns all tests that is marked as VG and so on. This would be much more intuitive. 

@HGustavs Do you want it as it is now (sorting by G gives all passed tests) or do you want it as I mentioned?

**Comment by HGustavs** [comment]
Use centric sorting.... off the top of my head I want the most relevant items first.... hopefully my view of relevant is same as everyone elses....

For all views
* We always want un-viewed tests at bottom in all sort orders.
* After that visited but not handed in.

For grade specific views sort in order of grades given the sort order... if U start with U and then falling
if VG start with VG and then falling.

No G mode.

Howabout Ascending grade mode, Descending Grade mode and Pending.

**Comment by b17nicsv** [comment]
Pending
```
Pending
U
G
VG
Icke Inlämnad
```

Ascending
```
U
G
VG
Pending
Not filed
```

Descending
```
VG
G
U
Pending
Not filed
```

These should be the states then. We should remove current states "-" and "G".

**Comment by c17johha** [comment]
ASC/DESC/PEN is solved
