### ISSUE TITLE
Filter and sortingdropdowns in navbar bad placement

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#6516]
The dropdowns have bad placement since some information/options are hidden.

**Comment by a17maxsj** [comment]
#6520 has an corresponding image for the same issue, closing this one

**Comment by a17maxsj** [comment]
nvm

**Comment by b17nicsv** [comment]
Closing this one as it is a duplicate of [Issue 6539](https://github.com/HGustavs/LenaSYS/issues/6593).
