### ISSUE TITLE
Filter and sorting-icons still visible in accessed but no functionality

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#6517]
Nothing happens when hovering or pressing these icons.

**Comment by a17poner** [comment]
There is a fix for this it just didn't get merged to gruppC before the big branch merge, so this is sort of resolved and should be visible to all in a week :)

**Comment by a17oscno** [comment]
Should we then close this issue? when it is already fixed but not merged.

**Comment by c17julka** [comment]
Fix works in current version, so closing this.
