### ISSUE TITLE
purpose of label in courseed "jag föredrar kexchoklad"

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#6519]
<img width="704" alt="kexchoklad" src="https://user-images.githubusercontent.com/49199825/57069518-2371b880-6cd5-11e9-9bef-798f266f1739.png">

"jag föredrar kexhchoklad" and button that disappears the label. Will this ever be useful?

**Comment by a17pongo** [comment]
that is a message of the day, not an issue :) anybody with an admin account can change this message. 
But it is supposed to contain things like, accept cookie storing, copyright info or stuff like that.

**Comment by a17maxsj** [comment]
Not an issue, closing.
