### ISSUE TITLE
Increase spacing between error-texts.

### ISSUE THREAD

**Issue by a17robda** [HGustavs/LenaSYS#6524]
![Screenshot_2019-05-02_13-26-43](https://user-images.githubusercontent.com/37792328/57072511-45bc0400-6cde-11e9-89d2-bb663994def6.png)
Right now the bold "Bummer!"-text seems too close to the rest of the error-message. Maybe add a few pixels between these?

**Comment by a17poner** [comment]
Has this been fixed? And if so in what pr?

**Comment by a16lisri** [comment]
Forgot to close this. This was fixed in https://github.com/HGustavs/LenaSYS/pull/6540
