### ISSUE TITLE
UML line is coming up as a straight line

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6529]
UML line is coming up as a straight diagonal line instead of line with kinks. UML lines should never go diagonal. They should always be horizontal/vertical or the combination of the two with "kinks".

**Comment by a17drama** [comment]
Line is showing up correct after a refresh of the page. Should not be a requirement to refresh the page to get the correct line.

**Comment by a17johpe** [comment]
Unless there is an issue somwhere else as well, this is a duplicate of https://github.com/HGustavs/LenaSYS/issues/6452 about UML lines breaking when zooming in/out.

**Comment by a17drama** [comment]
This did not happen when zooming. I cleared the diagram and drew from scratch without zooming or moving and it didn't get correct line in.

**Comment by a17drama** [comment]
Could not recreate this now. Something fishy was going on after the merge but it seems to be solved now. Closing this issue because it serves no purpose anymore.
