### ISSUE TITLE
Standard position of despription/code

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#653]
Code example and explanation should switch places; the code should be in the right box, explanation in the left one

**Comment by HGustavs** [comment]
For every box you choose content. So. It could be either way.
It is kind of confusing, the test data perhaps should reflect this and use the most common variation.

**Comment by a13jorla** [comment]
By using the Edit Content cogwheel  you can choose what will show in the separate boxes.

**Comment by c12jenek** [comment]
Is no longer relevant
