### ISSUE TITLE
Sectioned.php buttons disappearing

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#6530]
(issue for breaking points and the hamburger menu exists #6523)
If i click outside of the dropdown, all page functionality (buttons etc) disappears
![image](https://user-images.githubusercontent.com/49199993/57073580-caf4e800-6ce1-11e9-8763-a3ff70c8f554.png)

![image](https://user-images.githubusercontent.com/49199993/57073592-cf210580-6ce1-11e9-8207-dacae3d85a0b.png)

**Comment by a17alian** [comment]
Created sub issue for buttons disappearing when clicking esc button: #6735

**Comment by a17alian** [comment]
Reopening this since this issue till remains in Firefox
