### ISSUE TITLE
Fill the null's

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#654]
![null-issue](https://cloud.githubusercontent.com/assets/11715479/6961418/21bd3650-d92b-11e4-9be6-fcaab857d038.jpg)

The null in the header and the null in the bottommenu should be replaced with a relevant value

**Comment by HGustavs** [comment]
I think this is due to the test-data supplied in issue #572 I think if the bug-fixes were merged, they should display the data from #572 i.e. Xample Code
