### ISSUE TITLE
Sorting table is cut in the middle and does not show the full window

### ISSUE THREAD

**Issue by a17amama** [HGustavs/LenaSYS#6548]
The sorting table does not show the full window when dropping down, and you can't scroll past it either..

**Comment by a17pongo** [comment]
@a17amama can you add an image to make it more clear on what this issue is about?

**Comment by a17adasy** [comment]
is this the same issue as #6516 ?

**Comment by a17amama** [comment]
This is the same issue, specifically for the sorting window, but it can be removed

**Comment by a17adasy** [comment]
I think this issue can be closed since the filter and sort buttons are supposed to be moved back to the left, resulting in the windows to be fully shown again.

@b17timjo
