### ISSUE TITLE
Tooltip should not be clickable.

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#6553]
GIF: https://gyazo.com/2871bc3fc958a9ac5f677f7eddc843df

It should not be possible for a user to click the tooltip, there is a very small chance that this could happen but nonetheless, it shouldn't be possible.

**Comment by a17jacsv** [comment]
It seems like the tooltips are created using the attribute on button-tag with "data". This means that this "tooltip" will behave like a button and therefore we'll need to implement new tooltip functions to solve this matter. There is little chance to find this issue so I suggest putting this on hold.

**Comment by a17drama** [comment]
Considering it's far fetched and the work to solve it not worth the time at the moment this should be put on hold or low priority.
