### ISSUE TITLE
sortableTable: Sorting does not work correctly on numbers

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6557]
Example:
![weeksort](https://user-images.githubusercontent.com/37792198/57078878-6e98c500-6cef-11e9-8d83-4f67c66a549b.PNG)

I think this is because the sort function treats the numbers as a string. I suggest checking if the cells are numbers with isNaN() as a generic solution.

**Comment by a17joaap** [comment]
@b17nicsv any reason why you put this on grupp C? I thought sortable table was in your scope

**Comment by a17poner** [comment]
I'll give this back to group B

**Comment by a17adasy** [comment]
Cant seem to find a table that has numbers, where on the page was the image taken?

**Comment by a17joaap** [comment]
contribution.php, but unsure if that table is merged to master yet

**Comment by a17ludca** [comment]
@a17joaap This setup does not seem to work, when opening the test created nothing shows.

**Comment by a17joaap** [comment]
Most likely a database error then, it needs to be the database filled with github data from HGustavs/a97marbr.

**Comment by a17ludca** [comment]
And where does one acquire this database? :)

**Comment by a17joaap** [comment]
You can copy the 'GHData' directory from the groupC directory on the webserver

**Comment by a17ludca** [comment]
The table in the bottom is empty, any idea how to add data into this? @a17joaap

**Comment by a17joaap** [comment]
Easiest way is to log in with toddler on the web server, go to Webbplatsdesign -> Contribution.

Otherwise you have to create a time sheet dugga in the same course / moment, and upload some data
