### ISSUE TITLE
ResultEd: grading one submission in a group assignment should grade the whole group

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6563]
See https://github.com/HGustavs/LenaSYS/issues/2463 for the original issue.

I've done some work in our (group C) scope here https://github.com/HGustavs/LenaSYS/pull/6562

Basically what needs to be done is checking if the quiz is a group quiz: https://github.com/HGustavs/LenaSYS/pull/6562/commits/18b67cb61f47da558c5ab847c2d8c27554faef02
1 = true, 0 = false

If it is, all users in the group should receive the same grade.

**Comment by a17joaap** [comment]
Did not make it in to the final merge, leaving this for next year

**Comment by a18marax** [comment]
I've come to the same conclusion as a17joaap, the quiz table ha a tiny int that is used as a Boolean if it't set to 1 its a group quiz. One could then make a if statement to check that value each time if its 1 or 0, if 1 then check the table user_group for everyone that belongs to that group and set their grade to the same.

**Comment by a18marax** [comment]
Should it be possible to be part of several groups in one course?

**Comment by c14jonfr** [comment]
Some progress has been made..
It is now possible for us to grade whole groups at once (by grading a student in a group). This only works on group assignments (= works as expected). This updates both the database and the user interface properly.

However, the "moment"-duggas, such as Biträkningsduggor 1 etc. are now somewhat "broken". They still work in the sense that they update the database, but the user interface is not updated. Refreshing the page is needed for it to display properly. This is hopefully a minor issue and we will be able to solve it during the day.

Grading moments does not grade the whole group and I believe this is intented behaviour (simply speaking from previous experience with how our courses with group assignments have worked). Can there be cases where a moment only consists of one/several group assignment, where you would want to grade whole groups for moments as well?

**Comment by c14jonfr** [comment]
It seems when grading moments nothing is returned (logging data in returnedResults in resulted.js does nothing, or rather it does not get executed at all). Note this is on our issuebranch (G2-2020-W18-#6563, not on master or any other branch).

**Comment by b18jonli** [comment]
Merged to master.
