### ISSUE TITLE
File submission table needs alternating row colors

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6564]
Submission table needs alternating row colors to better separate the items from eachother
![image](https://user-images.githubusercontent.com/37793460/57126659-03ea9680-6d8e-11e9-8dd1-4ec0268dc2a3.png)
Should look more like this imo (not exactly like this, just a rough mockup):
![image](https://user-images.githubusercontent.com/37793460/57126742-4b712280-6d8e-11e9-9994-e591bff2a482.png)

**Comment by a17poner** [comment]
merged, closing issue.
