### ISSUE TITLE
AccessEd: Edit name box needs to be redesigned

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6567]
![image](https://user-images.githubusercontent.com/37793460/57127125-afe0b180-6d8f-11e9-8846-e2dd926ee4c8.png)

First off, the red X icon looks like a delete button, but it's actually a cancel button. Change the icon to something more suitable please.

Second, the green background color is kind of ugly and doesn't really fit.

Third, the cursor should change to the pointer cursor when hovering the icons.

**Comment by b16johso** [comment]
Also maybe add some keyboard shortcuts, like enter to submit and escape to cancel.

**Comment by a17andby** [comment]
Maybe we can split this issues up to many issues? So it easier to revert if something goes wrong etc. 

What do you think @a17poner and @a17alevu ?

**Comment by a17alevu** [comment]
We can split it up into 2 issues. One can for example be to fix the image of the red X, and the other issue can be about adding keyboard shortcuts. Or do you have a better idea ? @a17andby

**Comment by a17andby** [comment]
> We can split it up into 2 issues. One can for example be to fix the image of the red X, and the other issue can be about adding keyboard shortcuts. Or do you have a better idea ? @a17andby

I agree with you @a17alevu and @b16johso on that we could change the styling of "edit box" and split these up. So one issue could be just for the styling of the "edit box". Example on what that issue could contain:

- Change the "X" icon to more suitable icon for cancel functionality 
- Change the background color (or do we even have to change background color?)
- Add a cursor when hovering the icons. 
- A tooltip for the icons/button would be useful as well.

The other issue could be just keyboard shortcut functionality.

**Comment by b17annni** [comment]
Working on the style in branch gruppC2019W19_6567_style

**Comment by a17andby** [comment]
(Just for future reference, the keyboard functionality: https://github.com/HGustavs/LenaSYS/pull/6656 https://github.com/HGustavs/LenaSYS/issues/6644)

**Comment by b17annni** [comment]
![image](https://user-images.githubusercontent.com/37792766/57304165-1db61180-70df-11e9-8843-ff5c45cd67ad.png)

**Comment by b17annni** [comment]
![image](https://user-images.githubusercontent.com/37792766/57406606-6e159800-71e1-11e9-9467-798f0dbfd25f.png)

**Comment by a17poner** [comment]
merged, closing
