### ISSUE TITLE
Strange checkbox placement in courseed

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6568]
![Capture](https://user-images.githubusercontent.com/37834592/57127128-b2430b80-6d8f-11e9-9f45-5fb8c795e019.PNG)

**Comment by a17oscno** [comment]
@b17carma  Does it even fulfill any function? because it can't be clicked but there is code that uses it in both Dugga.js and .php

@HGustavs is this something that was used before but stopped being used like the "burget menu"?

**Comment by a17oscno** [comment]
@b17carma It seems it do not fulfill any particular purpose because it can't be clicked and when you remove the restriction it still don't do anything when being checked. Might be "best" to either just remove it (comment the code out incase it actually does something) or let it be.

**Comment by a17pongo** [comment]
has this issue been fixed? 
can not find this issue.

**Comment by b17nicsv** [comment]
@a17pongo What do you mean? A pull request has been made by a17oscno. However until Henrik has answered (either before or during the kundmöte) I will either merge it or close it.

**Comment by HGustavs** [comment]
Write something more clever than MOTD... I forget what it means every time.

Is it easy to find?

Where do we get to it?

If we do want to add a message such as "Servers down for the moment no ETA" is it easy enough to know where to enter that message?

**Comment by HGustavs** [comment]
No idea what read only does?

If it is truly message of the day, does the check button mean that message remains for more than one day or is that already the default?

If it does nothing vaporize.

**Comment by a17oscno** [comment]
Due to the fact that the Read only checkbox inserts values into the database (that might be used in other queries and it has its own Table) It might be bad to remove the feature to use it.

And the Message of the day button is very easy to find, when logged in as a Teacher (or whoever has Admin rights) then by pressing the Cogwheel  next to the title of the page (LenaSYS title on the courseed.php page).
