### ISSUE TITLE
Switching modes between ER and UML in the toolbox should put you in select mode

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#6570]
![chrome_GZawgSY1D5](https://user-images.githubusercontent.com/49199287/57127484-dd7a2a80-6d90-11e9-80fb-eaaea1fa70e8.png)
Here we select to draw UML lines.

![chrome_gUnu4MZQAx](https://user-images.githubusercontent.com/49199287/57127591-2e8a1e80-6d91-11e9-9267-f85d26b197bd.png)
Then we switch to ER mode in the toolbox.

![chrome_SEfnoHij3J](https://user-images.githubusercontent.com/49199287/57127612-4b265680-6d91-11e9-921b-e2957287c304.png)
And we can still draw UML lines but its hard to disable if we changed our mind since we are on the ER tab of the toolbox. Therefore we would have to switch back to UML mode and disable the draw UML line and then go back to ER again.

In my opinion it would be nice that when we switch modes between ER and UML in the toolbox it should reset the selected modes. In other words you should be able to select and move entities and other stuff again. I hope that makes sense.

**Comment by HGustavs** [comment]
The more generic issue is that we are having two different line functions, one for UML and one from ER.

I would assert that they are identical except for how we draw the lines and what we draw the lines between.

Drawing lines as kinked lines in a UML diagram and drawing lines as diagonals in ER solves most of this, and using one single line function will make this a non-issue ???

**Comment by HGustavs** [comment]
Select mode reset is not a bad idea though, separately from the line drawing is selected button...

**Comment by a16jenja** [comment]
The line functions have been merged into the same button for both UML and ER lines, so this part is solved. But the select mode reset should still be implemented, so each time you switch mode it should reset to select mode so you can choose objects and do other functionalities with ease.

**Comment by b17albbe** [comment]
I think there is a select mode reset implemented in the current build. So perhaps the whole issue is fixed now?

**Comment by a16jenja** [comment]
> I think there is a select mode reset implemented in the current build. So perhaps the whole issue is fixed now?

You are correct, I checked this myself now as well and it seems to be implemented now. Maybe we should close this issue then? @a14oscna

**Comment by a14oscna** [comment]
Yeah, this looks fixed. WIll close.
