### ISSUE TITLE
Button highlight too slow

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6575]
The button highlight hover effect feels too slow and unresponsive. Making it faster would make it feel more responsive.
![hover1](https://user-images.githubusercontent.com/37793460/57128777-cd644a00-6d94-11e9-83b6-3325d404c855.gif)

Faster transition:
![hover2](https://user-images.githubusercontent.com/37793460/57128783-d0f7d100-6d94-11e9-8752-2fce478a8c18.gif)

**Comment by a17poner** [comment]
Merged and closing.
