### ISSUE TITLE
Add anchors to manually move UML lines

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#6577]
In LucidChart you can manually move UML lines and add new anchors for splitting up the lines. 
![umlanchors](https://user-images.githubusercontent.com/37792313/57128784-d0f7d100-6d94-11e9-9b30-3959488ff838.png)

With this the user can move lines that may be overlapping as seen in the image below
![umlanchorsdugga](https://user-images.githubusercontent.com/37792313/57128881-14523f80-6d95-11e9-81ec-60ccd26389a2.PNG)

**Comment by a17johpe** [comment]
To clarify for if the line is broken or not: the start and end points of the line should not be movable but the line itself should

**Comment by a17johpe** [comment]
Code with partial solution can be found in stale branch _GruppA2019W22#6577_. During review of pull request https://github.com/HGustavs/LenaSYS/pull/7652 we found too many major issues to be able to merge immediately. See https://github.com/HGustavs/LenaSYS/pull/7652/files for a clear view of what was added/edited/deleted.

Summary of solution:
Added arrays "anchors" and "draggablePoints" to Symbol (in diagram_objects.js) which will contain the extra points on the UML line. Anchors are points for every corner/kink on the line. Draggable points are the points which the user can click on to manipulate the line.
![anchorsumk](https://user-images.githubusercontent.com/37792313/58640021-72bd0000-82f8-11e9-9266-0fe36879ffe7.png)
Above we see the points visible for the regular user when you click on a line. The orange points are starting and end points (not anchors) while the grey point is a draggable point.

![anchorsdev](https://user-images.githubusercontent.com/37792313/58640138-b57ed800-82f8-11e9-8927-0c20753c007a.png)
Here (in dev mode where _all_ points are drawn out as crosses) we see the anchor points as well.

Almost all of the code for this is found in diagram_objects.js. Functions addAnchor and addDraggablePoint are used for creating the points. Function createDraggablePoints is used to automatically create one draggablePoint between every existing anchor.
Function drawUMLLine is what actually calculates everything and draws the line. The anchors and draggable points are created in here once and then their positions are recalculated based on the positions of the line's start and end point + if the user has/is moving on any draggable points.

![anchors](https://user-images.githubusercontent.com/37792313/58641316-435bc280-82fb-11e9-81d0-2614a65a1b69.gif)
Gif of solution

The code contains rules for moving these points either up/down or left/right (though at this point there is only draggable point created which can only be moved up and down). While you can delete the line and connected objects, there are some interesting errors trying to delete an object when there are recursive lines in place.

The code that was added in diagram.js is for being able to hover and click-and-drag on the draggable point.

What is needed is for there to be clearly defined rules for how the lines and points should behave before the proper code is written. If there is some way to streamline the calculation of the points' positions, this would also be preferable.

**Comment by a18jonpe** [comment]
The solution that was mentioned here needs to be reworked a lot because of a rework of diagram.js that was made.
