### ISSUE TITLE
Daily Minutes: Change styling to be consistent with rest of LenaSYS

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6579]
At the moment, the styling of the new Daily Minutes submission form is inconsistent with the styling of the rest of LenaSYS. For example, the "Add row" button should be purple and have the same styling as all other buttons.
![image](https://user-images.githubusercontent.com/37793460/57129037-9478a500-6d95-11e9-8feb-58c7084ba9b5.png)

**Comment by HGustavs** [comment]
If someone feels adventurous, in addition to this, we could add a fab?

**Comment by a17robes** [comment]
Can't get access to the daily-minutes-page atm, therefore it's hard to fix anything but stylings in there. Will fix the fab asap!

**Comment by a17fellu** [comment]
Remember that there is a second form for when the window is smaller. Make sure to update that one aswell so it matches

**Comment by a17robes** [comment]
> Remember that there is a second form for when the window is smaller. Make sure to update that one aswell so it matches

Will do!

**Comment by a17robes** [comment]
Do you have any ideas of what the FAB could do on this page? Added it now but can't think of any practical functionality for it on this page.  @HGustavs

**Comment by a17robes** [comment]
bump @HGustavs

**Comment by a17robes** [comment]
Divided this issue into two issues. The FAB request issue is #6703

**Comment by a17poner** [comment]
merged

**Comment by b16johso** [comment]
Reopening this because it's still not fixed
