### ISSUE TITLE
access.php - Still possible to see ssn-numbers

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#6580]
Even though ssn numbers are masked in the table (first picture) it's possible to see ssn numbers if you want.  
![Screenshot from 2019-05-03 11-30-59](https://user-images.githubusercontent.com/49235724/57129561-14ebd580-6d97-11e9-8350-999acc223cfe.png)

The HTTP JSON response still have them. So if you have the knowledge to check the HTTP JSON response you can still get the ssn number of a person.
![Screenshot from 2019-05-03 11-29-52](https://user-images.githubusercontent.com/49235724/57129685-7613a900-6d97-11e9-8eaf-50856b393d72.png)

**Comment by a17adajo** [comment]
Good catch, it is probably another GDPR violation wich needs to be resolved asap

**Comment by a17poner** [comment]
merged, closing!
