### ISSUE TITLE
resulted.php - Still possible to see ssn-numbers

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#6581]
Even though ssn numbers are masked in the table (first picture) it's possible to see ssn numbers if you want. The HTTP JSON response still have them. So if you have the knowledge to check the HTTP JSON response you can still get the ssn number of a person.
![Screenshot from 2019-05-03 11-41-23](https://user-images.githubusercontent.com/49235724/57130010-7eb8af00-6d98-11e9-9b5a-a4573e06233f.png)

**Comment by HGustavs** [comment]
We only need the ssn for exporting, so perhaps a separate function in service to include ssn or not, that is triggered exclusively for exporting?

**Comment by c17julka** [comment]
Is your main way of exporting students through the LadExport? If that's the case, displaying the SSN there would mean it will still be visible to anyone. Then a lot of functionality for the LadExport would need to be remade.

If your main way of exporting student is through some other functionality then you would only need to import an array without the SSN from service.
