### ISSUE TITLE
Spelling error in contribution.php

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#6583]
![image](https://user-images.githubusercontent.com/37792321/57130794-f8ea3300-6d9a-11e9-913b-d5bb283e7636.png)

**Comment by b16johso** [comment]
Fixed

**Comment by a17andby** [comment]
Maybe fix these typos as well before we close this issue? 

![image](https://user-images.githubusercontent.com/49235724/57164129-717cde00-6df3-11e9-9223-38d25b7fbb1a.png)

**Comment by a17joaap** [comment]
Those are values from the database, so we can't change the spelling. But I don't think they are misspelled?

**Comment by a17andby** [comment]
> Those are values from the database, so we can't change the spelling. But I don't think they are misspelled?

Ah okay, didn't know there were values from the database

**Comment by a17poner** [comment]
Merged, closing this. Guess there is nothing to do about the database values/anything that needs to be done but if so make it a new issue :)

**Comment by HGustavs** [comment]
These are the names that github gives us. Question is whether we want this to be shown in a slightly more informative way?

A mock-up of some kind of more informative display of those items could be made into a new issue?
