### ISSUE TITLE
Contribution: Make a view for hourly graph that shows all hours from time period

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6586]
Henriks request from the seminar

**Comment by HGustavs** [comment]
I am interested in whether or not people (including myself) are working continously over time and which hours each person keeps.

If all events happen between 10:00-11:00 we know that the working hours for that person requires furter investigation. This is the puropse of such a view.

**Comment by a17poner** [comment]
merged, closin this gestapo addition.
