### ISSUE TITLE
Handin document preview not resized in mobile view

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#6588]
When opening the handin document preview in resulted on a mobile device, the width is too large to fit the screen
Left side of document preview:
![image](https://user-images.githubusercontent.com/37792256/57133442-11f6e200-6da3-11e9-9d59-c4096b697421.png)
Right side of document preview:
![image](https://user-images.githubusercontent.com/37792256/57133489-33f06480-6da3-11e9-9d17-c7ecf353e521.png)

**Comment by HGustavs** [comment]
As this is a teacher facing view, mobile functionality is not prioritized.

Back burner.

**Comment by c17julka** [comment]
![image](https://user-images.githubusercontent.com/37792321/57522444-fbacd100-7322-11e9-8f84-13e593e6502d.png)
This should be fixed in PR #6867

**Comment by c17julka** [comment]
Fixed in latest merge
