### ISSUE TITLE
Handin grade/feeback in resized window

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#6589]
When handin document preview window is resized the grade/feedback section is taking up a big part of the screen. 
![image](https://user-images.githubusercontent.com/37792256/57133866-7e261580-6da4-11e9-8638-9b02f27b231e.png)
A redesign to make grade/feedback section a sidebar which can be toggled might be a solution

**Comment by HGustavs** [comment]
As it is teacher facing, no mobile adaptiation is prioritized.
