### ISSUE TITLE
[Suggestion] fileed.php - Show what file types you can upload (Course Local File)?

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#6591]
Right now there is no information on what types of files you can upload. For a better user experience it might be good to display what types of files you are allowed to upload. For example, you are not allowed to upload .cer files but you can upload pdf files.

![Screenshot from 2019-05-03 13-17-51](https://user-images.githubusercontent.com/49235724/57134370-47e99580-6da6-11e9-8874-465280e510c9.png)

**Comment by HGustavs** [comment]
Yes for this dialog it is certainly possible to list the files in some manner...

Can someone make a mock-up?

**Comment by a17adasy** [comment]
Are there many files that are allowed? Thinking of a way to list them in nice way. If there are alot maybe having a button that shows the allowed file types when clicked? or having a box that shows allowed file types when you hover on the choose files button perhaps?
Kinda like this:
![image](https://user-images.githubusercontent.com/37799016/57620146-319ebf00-7588-11e9-9b5d-06b8428a7c0d.png)

@HGustavs

**Comment by b17nicsv** [comment]
How many files are accepted as valid?

**Comment by HGustavs** [comment]
Seems ok.

Unsure if there is a global list of applicable file types that we can use or if this is depending on what we are uploading at the moment.
