### ISSUE TITLE
Sort and filter buttons in Resulted should be moved back

### ISSUE THREAD

**Issue by b17nicsv** [HGustavs/LenaSYS#6593]
![Example how it can be](https://user-images.githubusercontent.com/49198878/57135392-816fd000-6da9-11e9-93b9-9797a0a0c018.PNG)

The above picture is how it should be. It will also solve the problem with the box being outside of the window.

**Comment by c17alepe** [comment]
#6565 duplicate?

**Comment by b17nicsv** [comment]
We will go with this issue and close the other one.

**Comment by b17nicsv** [comment]
This issue can also fix the issue which is mentioned in [Issue 6520](https://github.com/HGustavs/LenaSYS/issues/6520).

**Comment by c17julka** [comment]
This issue will be fixed along with pr #6596

**Comment by b17nicsv** [comment]
Issue is solved with another pull request.
