### ISSUE TITLE
The submission page has to be changed (zip files only)

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6600]
When uploading a zip file you have the option to download it on the button next to it. But you can also click on the zip file and then a new window will pop up where you can click again on the file name where you can download it. Does not feel necessary. 

![image](https://user-images.githubusercontent.com/49199285/57137723-03afc280-6db1-11e9-9de6-450fe71a0f3f.png)

![image](https://user-images.githubusercontent.com/49199285/57137791-2fcb4380-6db1-11e9-9904-7dd565134d8d.png)
This window will popup when you click on the file name, and when you click on the file inside the window you will download the zip file. I feel like the window should be removed for zip files, i understand that this functionallity is good for pdf files.

**Comment by HGustavs** [comment]
Yes this is a good idea.

I like it.

**Comment by a17alevu** [comment]
Any news on this @a17robda ?

**Comment by a17robda** [comment]
Getting this fixed as soon as possible.

**Comment by a17robda** [comment]
I am currently having some issues with creating new duggas for turn ins which I am trying to resolve.
