### ISSUE TITLE
Scaling of weak entities, multivalued attributes, and relations are wrong

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6608]
When zooming out, the weak entities, and the outer bodies of multivalued attributes does not scale properly.
100%:
![scale100](https://user-images.githubusercontent.com/49199690/57145652-fb14b780-6dc3-11e9-9a5c-e8e86795e7c6.JPG)
20%:
![scaling](https://user-images.githubusercontent.com/49199690/57145322-47abc300-6dc3-11e9-8596-308d70b2adf1.JPG)
200%:
![scale200](https://user-images.githubusercontent.com/49199690/57145788-3d3df900-6dc4-11e9-9137-2c41a91c0a4b.JPG)

**Comment by a16tobfr** [comment]
Note that relations suffer from the same issue

**Comment by HGustavs** [comment]
The offsets should be in pixels in 100%

pix2canvas(xk+offset,yk+offset) ...

I am guessing that the offsets are added separately?

**Comment by a17vikab** [comment]
This issue got solved in #6624.
