### ISSUE TITLE
showDugga.php - Styling touch-up? 

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#6609]
showDugga.php maybe need a styling touch-up? See pic below (1920x1080)

- The error in the small ring just looks weird. Do we need two columns? Why not just have one column? 
- Maybe set the `Quiz` box to 100% width instead of 70%?

![image](https://user-images.githubusercontent.com/49235724/57168137-c83ce480-6e00-11e9-8e91-e43d3bca12fc.png)

**How it looks with 100% width**
![image](https://user-images.githubusercontent.com/49235724/57168507-464dbb00-6e02-11e9-9835-cb91d90c5494.png)

**Comment by a17joaap** [comment]
I believe this is a problem with this particular dugga template 'kryss'.

Another dugga where the two column styling makes sense:
![example](https://user-images.githubusercontent.com/37792198/57212900-6be6ea00-6fe5-11e9-8cf5-3ed328817610.PNG)

I will try to find a natural break point in the instructions of the kryss template so we can keep the two columns.

**Comment by HGustavs** [comment]
The two column layout as you clearly show is useful in some tests and not very useful in others.... as for making the view 100% it seems ok if it does not break anything else?

**Comment by a17poner** [comment]
merged, closing. I don't think it broke anything else that we've managed to spot in the review process at least. Hopefully we managed to find :)
