### ISSUE TITLE
Refactor Free draw object into the symbol class

### ISSUE THREAD

**Issue by b17robev** [HGustavs/LenaSYS#6611]
Currently Free draw object are its own entity, they should be inseparable from the symbols.

**Comment by HGustavs** [comment]
Im thinking we have most of the functionality in the symbols already.

Interconnecting points with lines, and moving the points independently, that is about it.

**Comment by a17alfcl** [comment]
Abandoning the mega issue and trying to pick small pieces from the code base instead.
Got a better understanding of how things are interconnected but too high coupling to connect the parts in another way in a reasonable time frame.
