### ISSUE TITLE
Starting from the oldest issues, close them if no longer applicable (B 2019)

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#6614]
Sift through all issues created prior to this years run, and check if they are still valid - otherwise close them.

Somewhat overlaps with #6136

**Comment by a17adajo** [comment]
I have been looking very far back at older issues and I think some  can be closed just becuse the micro service does not exist anymore

**Comment by b17timjo** [comment]
This issue is specific to group b, but I suggest each group create their own versions of this issue and remove old issues that are no longer relevant in their domain.

E.g. for group b: if an old issue is referencing something in resulted which has already been fixed, or no longer exists, that issue should be closed by group b.

**Comment by a17amama** [comment]
Closed some of the issues that has already been solved, replaced by something else or irrelevant for LenaSYS today.

**Comment by a18kaswi** [comment]
WORKING ON IT

**Comment by a18kaswi** [comment]
I made my overview, no other seems interested, CLOSING.
