### ISSUE TITLE
Contribution.php needs to be more informative. 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6615]
@HGustavs wrote a comment in issue #6583 that we should consider to re-design the table that holds the GitHub Contribution so that it is more informative. 

*These are the names that github gives us. Question is whether we want this to be shown in a slightly more informative way?*

*A mock-up of some kind of more informative display of those items could be made into a new issue?*

_Originally posted by @HGustavs in #6583

**Comment by HGustavs** [comment]
To clarify for future documentation: 

Not a redesign of the table (from the view of the database) the data in the table is exactly what github gives us...  which is considered outside the scope of this issue.... but the view in the screenshot in  #6583

What does for example 17 merges signify, and can we add something in this view to make the view more easy to read/use?

An icon that links to each event?

Also, prioritizing the events, we want more important events on top, and less significant ones at the bottom of the list, question is which events that are more significant.

**Comment by a16joare** [comment]
Here is a example of how the github contribution can look like. 
![image](https://user-images.githubusercontent.com/49194898/57302298-273d7a80-70db-11e9-8394-3b92b1cb4bdf.png)

If you hover any of the icon this window will appear: 
![image](https://user-images.githubusercontent.com/49194898/57302387-5a800980-70db-11e9-9822-fe8f8127740c.png)

And if you click the icon all the information from github is shown: 
![image](https://user-images.githubusercontent.com/49194898/57302471-869b8a80-70db-11e9-9ba9-b289a56daec1.png)

Any ideas or comments on this one? 
@HGustavs

**Comment by a17alevu** [comment]
This looks really good Joakim. Good job =)

**Comment by b17annni** [comment]
Looks good

**Comment by a17robes** [comment]
Looks promising

**Comment by a17joaap** [comment]
Icons for commit, issue, and events could be more informative. Could use githubs issue icon for example. The red color in the bubble could be milder. Otherwise great job!

**Comment by a17adajo** [comment]
I like the icons! Should be much quicker to glance over.

**Comment by HGustavs** [comment]
I would say that 

* Commits should be visible directly.
* Comments should be visible directly.

Everything else should be icons.

Hiding of commits/comments could be possible using local storage (separate issue )

**Comment by HGustavs** [comment]
Are all of the around 15-ish events in github represented or only the most basic?

**Comment by HGustavs** [comment]
Check copyright of icons (creative commons).
