### ISSUE TITLE
Should not be possible to resize objects while they are locked.

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#6622]
The old issue did not merge correctly, #6250, and the only thing left is that it should not be possible to resize the objects when they are locked.

Old PR: #6368

**Comment by c17matjo** [comment]
It seems like 19802dd8 was the commit that broke this. In diagram.js:2539 an if statement was removed that checked if the selected object was unlocked before resizing. Re-adding that if-statement seems to fix it.

**Comment by c17matjo** [comment]
Solved by #6697
