### ISSUE TITLE
Swimlanes in sectionEd isn't scaling properly

### ISSUE THREAD

**Issue by b17nicsv** [HGustavs/LenaSYS#6623]
![Swimlanes example in Webbutveckling - Datorgrafik](https://user-images.githubusercontent.com/49198878/57215606-b10f1a00-6fed-11e9-9b1f-c5bcf465edbf.PNG)

The swimlane container isn't scaled properly when you enter the URL. This is a bug, when pressing the Deadlines column to the left twice then it rescales to the proper size. Going into a dugga and back also resizes the container. It should be and always be properly sized to it's content.

**Comment by a17ludca** [comment]
This has been adressed in #5866 and as far as I know the issue only occurs in the newest version of firefox. I think it has something to do with the html loading before the Javascript, making the container not sizing according to it's content.

**Comment by b17nicsv** [comment]
Missed that issue! Closing this one.

**Comment by b17timjo** [comment]
@a17ludca interesting idea, might be worth investigating. It could be that some javascript runs before the appropriate events pertaining to page load are fired -- perhaps that could be made into a separate issue?

**Comment by c17johha** [comment]
#6836
