### ISSUE TITLE
Submission types when editing variants in DuggaED doesn't autofill. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6631]
Instruction file and Extra parameters is solved in pullrequest #6627. I was not able to solve the Submission types.. The hard part about the left divdialog is that we need to fetch the information from the Generated Param JSON that is stored in the database. The solution for Instruction file and Extra parameters is reading the values from the JSON string at Generated Param JSON field. The Submission types is harder to solve in a good way due to the possibility to have multiple rows. 

One variant selected: 
![image](https://user-images.githubusercontent.com/49194898/57218322-4cf05400-6ff5-11e9-89b7-d0802220714b.png)
Another variant selected: 
![image](https://user-images.githubusercontent.com/49194898/57218363-66919b80-6ff5-11e9-8e82-150034edc9af.png)

**Comment by a17poner** [comment]
merged, closing
