### ISSUE TITLE
Remove "Create JSON" button inside editing variant at Duggaed.

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6632]
The Create JSON button is unnecessary because the JSON string is updated when a value is entered in any of the fileds. 
My suggestion is that we remove the button. 
![image](https://user-images.githubusercontent.com/49194898/57218999-16b3d400-6ff7-11e9-90ae-12528cb7eef7.png)

**Comment by a17poner** [comment]
merged, closing :)
