### ISSUE TITLE
Overlapping nav when shrunk

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#6638]
![image](https://user-images.githubusercontent.com/37792766/57221964-3f40cb80-7001-11e9-91d7-093df1ee7c9b.png)

**Comment by a17joaap** [comment]
If I'm understanding the issue right, this only occurs when the user is resizing the browser window, and not an issue concerning smaller devices?

If so, we could set the min-width of the whole page (for large devices) to where this overlap doesn't occur.

**Comment by b17annni** [comment]
Found same.

**Comment by a17joaap** [comment]
After looking more into it, this is because we put the menu items in the navbar. Breakpoints for hiding the menu items are in place, but they are incorrect because they are further to the right when in the navbar.

**Comment by a17poner** [comment]
merged, closing.
