### ISSUE TITLE
Problems with master after week-14 merge

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#664]
There seems to be incorrect code checked in. When I run master it complains when trying to load the following file: /var/www/html/master/Shared/coursesyspw.php on line 3

Also, the /Shared/coursesyspw.php contains information you NOT want on github.

**Comment by HGustavs** [comment]
I vote for adding this file to gitignore and calling the file in Shared "example_login_info.php" or something like that.

**Comment by HGustavs** [comment]
It is a serious security issue if the password is checked in on github.

**Comment by a13ottne** [comment]
coursesyspw.php reverted to it's original template
password to the db has been changed as well
