### ISSUE TITLE
Menu is rather broken on mobile view

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#6654]
Menu also disappears if clicking outside of the hamburger dropdown. 

Is the login button supposed to be this large?
![image](https://user-images.githubusercontent.com/49199993/57228212-8cc63400-7013-11e9-993f-cb41b4497e72.png)

**Comment by a17maxsj** [comment]
Tried on iPhone 8 using safari

**Comment by b17annni** [comment]
Menu view should be fixed #6499

**Comment by a17maxsj** [comment]
@b17annni  looks much better now :D
