### ISSUE TITLE
Accessed  hover and leave functions for funnel and arrows were unecessarily removed, put them back

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#6657]
in #6400 the hover and leave functions were deemed unecessary and removed. They were unused in that branch but they were needed for the branches that were being worked on and got commited+ merged the following merge and now the removal of these functions is causing undefined errors and the funnel and sorting arrow can no longer work as a result of this. Bring back the functions! (minus the commented code).
This is what it looked like previously.
```
function hoverc()
{
	/*
	$('#dropdowns').css('display','none');
	$('#dropdownc').css('display','block');
	*/
}

function hovers()
{
  /*
  $('#dropdowns').css('display','block');
  $('#dropdownc').css('display','none');
  */
}

function leavec()
{
		$('#dropdownc').css('display', 'none');
}

function leaves()
{
		$('#dropdowns').css('display', 'none');
}
```

**Comment by c17julka** [comment]
The sorting buttons (funnel + arrows) were directly copied from resulted, and did nothing in accessed. Instead a better idea would be to remove the buttons, since they never did anything.

**Comment by a17poner** [comment]
Yeah, they had been seperated into different issues so they were supposed to do things altough it didn't show on the main branch as that change took 1 more week before it got merged, it missed the wednesday merge by a day so it never ended up showing to other groups.

**Comment by a17maxsj** [comment]
Hover works again!

**Comment by a17poner** [comment]
merged, closing
