### ISSUE TITLE
Merged line button doesn't work with current branch

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#6664]
The code of the merged line button uses the old version of symbolstartKind, which uses numbers instead of variables. This should be fixed and updated to accommodate the new changes currently merged into branch. Related to this issue: https://github.com/HGustavs/LenaSYS/issues/6415

**Comment by a14oscna** [comment]
Im closing this issue but I am not sure if this has any connection to the pull request #6665
