### ISSUE TITLE
Button on Cookie information popup should get some bottom margin

### ISSUE THREAD

**Issue by a17fellu** [HGustavs/LenaSYS#6666]
There is no bottom margin for the button. Looks currently like this:

![cookiesNoMargin](https://user-images.githubusercontent.com/49202955/57273875-aad67780-7099-11e9-8aa1-b7b4b80922c9.PNG)

**Comment by a17fellu** [comment]
With some bottom margin:

![cookieMsgFixed](https://user-images.githubusercontent.com/49202955/57274922-09512500-709d-11e9-922b-de796d955e2a.PNG)

**Comment by a17fellu** [comment]
Pull request:

#6667

**Comment by b16johso** [comment]
I think a better fix would be to just center the button. I don't know why it's not centered in the first place.

**Comment by a17fellu** [comment]
Updated the fix. I just removed the position: absolute and it aligned it self centered

**Comment by a17poner** [comment]
this just got merged in #6667 closing this.
