### ISSUE TITLE
Contribution: The github contribution table is a monster

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6668]
Look at this beast:
![monster](https://user-images.githubusercontent.com/37792198/57279095-6d2d1b00-70a8-11e9-8a3d-101bbe3c82b5.PNG)

It uses a lot of space and just looks bad, all because of the Github contribution column.

I suggest that we, instead of showing all events from the start, only show clickable headings in the column. Like so:
![bettermonster](https://user-images.githubusercontent.com/37792198/57279250-d01eb200-70a8-11e9-8cac-18c4b2ed0b0c.PNG)

If the user clicks 'Made 3 commit(s)' for example, we show the links. Thoughts?

**Comment by a17adajo** [comment]
I think it is a great idea!

**Comment by a17andby** [comment]
I think @a16joare working on this?

**Comment by a16joare** [comment]
Yes iam working on a solution for this one. Will show a preview in this issue  #6615 soon.

**Comment by a16joare** [comment]
Look here for an example: #6615.
