### ISSUE TITLE
navigation buttons in code viewer do not work

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#667]
Navigation buttons have problems
* Long press / click does not show a navigation list
* Short press / click does not navigate to next / previous example
* Navigation buttons do not disappear for first/last example in series

**Comment by HGustavs** [comment]
I accidentally merged this fix into master and not into cv15...
can someone please reapply that merge to cv15 branch so that cv15 is current with master.

**Comment by HGustavs** [comment]
I apparently tell people how to do things and then I go out and do it wrong myself. Sorry for ruining the branch tree.

**Comment by a13henhu** [comment]
572
