### ISSUE TITLE
Add functionality: Tabs?

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#6672]
The diagram should have tabs available for the user to use. An example would be how google docs use the tabs or something similar.

**Comment by HGustavs** [comment]
For different documents?

I am thinking we do this through lenasys.

When a user clicks a link in lena we end up at that document... 

for example we create a link for "diagram 1" and that takes the user to a new or existing version of that doucment for that assignment....

**Comment by HGustavs** [comment]
... but a complicating factor is if we want this to be group-based we want multiple users to click the link and see the same diagram at the same time.

There are no such "group assignments" currently in lena AFAIK, so this has to be handled separately in some manner.

**Comment by HGustavs** [comment]
We want something that is lena-specific for specific assignments, rather than a generic diagram editor, perfectly integrated into the current functionality.
