### ISSUE TITLE
Ghosting crosses does not scale with zoom value

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#6675]
![ghostingCrosses](https://user-images.githubusercontent.com/49202727/57285397-6ce64d00-70b3-11e9-8258-101aa2ce18a1.png)

**Comment by HGustavs** [comment]
Is this the same problem as with the other similar issues? 

the call sequence for drawing with pix2canvas is not correct, we are not calling with the real, un-zoomed pixel values?

**Comment by a17alfcl** [comment]
> Is this the same problem as with the other similar issues?
> 
> the call sequence for drawing with pix2canvas is not correct, we are not calling with the real, un-zoomed pixel values?

pixelsToCanvas is executed on the points before this is done, so it only requires multiplying with zoomValue when drawing.
