### ISSUE TITLE
Navbar: Fix for mobile view

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6677]
When viewing pages like AccessEd in mobile view, there isn't enough room in the navbar for all the icons and the search bar, so the login button gets pushed off screen.
![image](https://user-images.githubusercontent.com/37793460/57286073-d581f980-70b4-11e9-9ef9-40ebb3de8a2d.png)
Possible solutions:
1. Create a hamburger menu for mobile which contains all the navbar items (home, filter, search, etc).
![image](https://user-images.githubusercontent.com/37793460/57286535-b6379c00-70b5-11e9-8154-629ada850c9e.png)

2. Change the search bar in mobile view, so that it's only a search icon and clicking it opens up a search field.
![image](https://user-images.githubusercontent.com/37793460/57286454-88525780-70b5-11e9-974f-be9df117fe16.png)

**Comment by b17carma** [comment]
I think a hamburger menu would look good :)

**Comment by b17annni** [comment]
Waiting on #6739.

**Comment by b17annni** [comment]
![image](https://user-images.githubusercontent.com/37792766/58020527-ac2b8980-7b08-11e9-97d7-55c5a87e9211.png)

**Comment by b16johso** [comment]
This was fixed, but somehow reverted in todays test merge on branch gruppB2019W22#testmerge
