### ISSUE TITLE
resulted.js - number of times graded is increased everytime you press one of the grade buttons

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#6679]
Even if you did not change the grade, the number is still increasing.
Which means you can continue pressing for example "G" and timesgraded will continue to increase.

**Comment by a17pongo** [comment]
@b17timjo @b17nicsv 
This issue can be closed, there was a color render error on my branch when testing. This means that when pressing the set grade one more time it removes the grade but still counts as being graded. 
I don't know if this is the correct behaviour or not but the retrieved Json might have to be changed if this is not the correct behaviour.

**Comment by HGustavs** [comment]
Dont really have a concise view on how I want this stuff to work... 

Counting "failed" marking attempts or not... I would say I agree with how it works, if one presses G then G again to cancel.... I would say it is ok to count up.

**Comment by a17pongo** [comment]
@HGustavs ok, then I will close this issue as it now works as expected at the moment.
