### ISSUE TITLE
editorservice contains code standard errors

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#668]
editorservice.php should not have passed the review for the merge as it breaks the code standard repeatedly.
* It contains numerous commmented-out sections. We do not use /* for commenting out things in the code, only for headers and box-commenting code for internal testing. Commenting out things is something that we do only for internal testing. The merged branches should not have this.
* Also, the indentation seems off in places but I am unsure about this.

**Comment by a13jorla** [comment]
Since there is many issues about codestandards and this one was specific about editorservice.php i'm closing this issue. Cause it has been merged.
