### ISSUE TITLE
Object names are wrong

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6688]
![wrongObjectNames](https://user-images.githubusercontent.com/49199690/57288899-b0908500-70ba-11e9-85ed-1e4e905221d7.JPG)
The object names are wrong.
Should be: Entity0, Attr0, and Relation0
in this case...

**Comment by a17vikab** [comment]
Connected to #6699.

**Comment by a17drama** [comment]
@a16tobfr How do you want this to work. Chronological that just adds over time for each kind or do you want to reuse numbers. eg You create entity 0,1,2,3 and then delete entity 2 and 3. Next created one should be called 2 or 4? 2 if reused and 4 if we are keeping track of how many entities where drawn total trough out the life span of the diagram.
