### ISSUE TITLE
codeviewer edit example dialog does not work

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#669]
Edit of code example data does not update database.
Data from database does not update all of edit example dialog.

**Comment by HGustavs** [comment]
Edit content should be updated in the same way.

**Comment by HGustavs** [comment]
Perhaps it is better to add a separate issue for the edit content dialog.
In that dialog we need a hidden field to keep track of which cogwheel that was pressed.

**Comment by HGustavs** [comment]
At this point I have no code to contribute for the edit content issue, you are free to begin resolving that issue and making similar code for that issue.

**Comment by f12danjo** [comment]
I will make a branch with the code HGustavs have commited, test it and make a pull request.
