### ISSUE TITLE
Consistency suggestion with undo/redo button

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#6690]
I think the undo/redo buttons would look better if they followed the same size and shape as all the other buttons. Here's a comparison showcasing what i mean: 
![056628233b72804ff98b1fce5168b34a](https://user-images.githubusercontent.com/38030926/57290712-3f52d100-70be-11e9-8591-5a887419e72e.png) ![01e4a320a8106f8a4a42b75765235ed7](https://user-images.githubusercontent.com/38030926/57290739-5396ce00-70be-11e9-96d3-da08028bfb59.png)

**Comment by a17jacsv** [comment]
related to issue: #6485

**Comment by a17vikab** [comment]
Related to issue: #6707

**Comment by a17vikab** [comment]
solved in #6707
