### ISSUE TITLE
Remove the whitespace next to dropdown-menu

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6691]
Make the design look like the mock-up below for a smoother design:

![bils](https://user-images.githubusercontent.com/37792795/57291631-16334000-70c0-11e9-8a5e-679981ca71b6.png)

**Comment by a17vikab** [comment]
Mode should not be on the same line as the menu. If you remove the whitespace it can be misunderstood to be with the menu. Because of the reason, I will close this issue.

**Comment by a17jacsv** [comment]
I don't agree with you as you can make a line to decide them and would be easy to see that they are not paired with each other. 

Another solution will be to put the menu to all the way to the left to erase the whitespace that doesn't look good.

**Comment by a17johpe** [comment]
This was already discussed in pull request https://github.com/HGustavs/LenaSYS/pull/6598 as your mockup was the original design and it was agreed upon that separating them as is now was a better and more clear design

**Comment by a14oscna** [comment]
As previously stated by fellow members, the decision was made in the classroom to keep the menu as it is right now so that we can focus on other more important issues. We are aware that the current solution is not perfect, but aligning the toolbar title with the top menu will add confusion, which we currently avoid.

**Comment by a17jacsv** [comment]
> As previously stated by fellow members, the decision was made in the classroom to keep the menu as it is right now so that we can focus on other more important issues. We are aware that the current solution is not perfect, but aligning the toolbar title with the top menu will add confusion, which we currently avoid.

Okay, I see. Let's put this on-hold as you said and let it be a future issue, as this current design should be changed.👍

**Comment by a17vikab** [comment]
This is the new issue that will address all the changes that need to be done regarding the Toolbar / Menu

#6699

**Comment by a14oscna** [comment]
Good call
