### ISSUE TITLE
showDugga file upload/teacher feedback table goes outside the box on small devices

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6698]
![image](https://user-images.githubusercontent.com/37834592/57296116-716b2f80-70cc-11e9-9c93-334d0583001c.png)

**Comment by a17joaap** [comment]
Progress; 
![iphone5](https://user-images.githubusercontent.com/37792198/57302496-961ad380-70db-11e9-8ca5-ffe7f1568299.PNG)

**Comment by a17poner** [comment]
merged, closing (#6716)
