### ISSUE TITLE
Megathread: Toolbar / Menu Styling

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#6699]
This is the issue that should fix all the design fixes related to the Toolbar / Menu.

**Comment by HGustavs** [comment]
Before-after screenshots would be appreciated....

**Comment by a17vikab** [comment]
Before:
![image](https://user-images.githubusercontent.com/37792464/57358613-1d1c8a00-7176-11e9-8d8e-c6ed6238f06b.png)

**Comment by a14oscna** [comment]
As the toolbar label issue is yet to be fixed I will reopen this issue.

**Comment by a17vikab** [comment]
After:

![image](https://user-images.githubusercontent.com/37792464/58407638-8a805400-806c-11e9-9f50-f66a1a20d6e1.png)

**Comment by a16tobfr** [comment]
The toolbar labeling 
<img width="188" alt="toolbarLabelIssue" src="https://user-images.githubusercontent.com/49199690/58409318-15af1900-8070-11e9-9744-d3b59af254ee.png">
The labels should be next to each button instead of being in the corner as it is now

**Comment by a18kaswi** [comment]
Unclear whats wanted, closing.
