### ISSUE TITLE
Give the "daily minutes" FAB some functionality. Located in daily-minutes.html

### ISSUE THREAD

**Issue by a17robes** [HGustavs/LenaSYS#6703]
A FAB for "Daily Minutes" has been requested and now exists in daily-minutes.html, as it is now it doesn't have any functionality. We should probably try to add some functionality for it. Some examples could be "add row" and "submit"? Any ideas are welcome.
![image](https://user-images.githubusercontent.com/38004435/57297889-1982f780-70d1-11e9-9f32-fced2dceaa8f.png)

**Comment by HGustavs** [comment]
Add row would be the most logical fab functionality IMHO.

**Comment by a17poner** [comment]
merged!
