### ISSUE TITLE
Reduce whitespace padding left/right for toolbar

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6708]
related to #6699
<img width="58" alt="reduceWhitespace" src="https://user-images.githubusercontent.com/49199690/57358621-20b01100-7176-11e9-8a59-c4f2d89b6145.png">
Make it so that only the whitespace inside the black lines are present. Will need to move the canvas and resize the toolbar in order to make it look good across the entire page

**Comment by HGustavs** [comment]
Screenshot of suggested fix?

**Comment by HGustavs** [comment]
Looks all right. Question is (I have no answer...) if this look is standardized in the interface... is there some other dialog that we can borrow the styling cues from?

**Comment by a16tobfr** [comment]
I am unsure about what you mean with dialog in this context

**Comment by a16tobfr** [comment]
Issue #6749 fixes this issue. When the review for that issue is approved, this issue can be closed.
