### ISSUE TITLE
Rename diagram symbols upon creation

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#6710]
When you create a new symbol on the canvas, you should be able to rename the symbol instantly, for example as shown in the image below.
![namesymbol](https://user-images.githubusercontent.com/37792313/57301519-8b5f3f00-70d9-11e9-9b0a-954d3de1ff2a.png)
Here the symbol name becomes focused when the symbol is created and you can either change the given name by starting to type, or you can ignore it and let the name be as is.

It's a smoother experience and more like how someone will actually work with the diagram, rather than placing a bunch of symbols first and _then_ renaming them.

**Comment by HGustavs** [comment]
I would say that one very common workflow first considers the general layout and then specify things further.

e.g.
Draw e.g. 4 entities, rename each
Draw 3 attributes for each entity and see if they fit, and depending on specifics move things around.
Decide which attribute name that goes where.

If we know beforehand which attributes we want an entity to have, we dont need to make the ER model... the whole point of the model is that we dont know which attributes to make?

**Comment by a17johpe** [comment]
I don't necessarily agree with your argument, but this solution doesn't _force_ the user to rename a symbol immediately. It just gives them the _possibility_ to do it. 

I'd argue that if you're drawing an ER model, you are usually aware of the domain for which you're modelling (unless you're playing around) and thus have an idea of the names of entities and attributes. This was at least how we worked during the entire Databassystem course...

**Comment by a17drama** [comment]
I like this idea but doing it this way on canvas where text isn't really managed as regular text is a lot of coding just to "select" text. There is an example here: https://codepen.io/rochastuff/pen/yJdOrJ What we could do is to use our dialog box for changing this text. I don't mind doing this coding but it will take some time. I would like an opinion on this before I give it a go. @a14oscna @a17vikab @a17johpe I personally like the original idea but it will take some time to implement.

**Comment by a14oscna** [comment]
I'm not very familiar with how the implementation would work outside the information given in this thread but I would definitely argue that this issue is very minor and should not be prioritized. If what @a17drama says is true than we probably will not have time to implement a change with the limited time we have left of this course. So let this issue be and perhaps future students may decide to implement it for another year.

**Comment by a17drama** [comment]
#7025 is a part of this issue and should be marked as redundant. This one covers all objects and 7025 covers only the text object. @a17vikab

**Comment by a18kaswi** [comment]
> I would say that one very common workflow first considers the general layout and then specify things further.
> 
> e.g.
> Draw e.g. 4 entities, rename each
> Draw 3 attributes for each entity and see if they fit, and depending on specifics move things around.
> Decide which attribute name that goes where.
> 
> If we know beforehand which attributes we want an entity to have, we dont need to make the ER model... the whole point of the model is that we dont know which attributes to make?

CLOSING
