### ISSUE TITLE
Log out button has no shadow and overlaps scroll bar

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#6714]
![image](https://user-images.githubusercontent.com/49199993/57303483-b21f7480-70dd-11e9-8c10-e333b97bff51.png)

**Comment by HGustavs** [comment]
Is there any view that does not have a scroll bar that may interfere with any fix to this?

**Comment by a17poner** [comment]
This was also brought up in #6857 and a fix was merged in #6898 to fix this problem in contribution which I believe was the only place where the issue existed. Closing this, until another place where it exists is discovered.
