### ISSUE TITLE
Background color for weak entities/relations fills the wrong frame

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6715]
When an entity or relation is set to weak, the background color extends to the border of the "weak" frame which is incorrect. This is especially problematic when the background color is changed to match the border color as you can no longer determine if the entity/relation is weak or strong. 

The background color should be changed to always only extend to the default frame.

**Comment by HGustavs** [comment]
Well, this is a definition issue.

Which of the two borders is considered the original and which is considered the "inner"

I would say that we draw a background-using normally sized border just like any other entity symbol....and then we add a slightly smaller background-free border inside it to denote the weakness.

Would this not get us nicely standardized backgrounds just like normal entities?

Inner box is used for clipping.
