### ISSUE TITLE
After refreshing page, deleted symbols comes back

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#6719]
If you draw some symbols, deletes them (with delete button, not clear diagram), and then refresh the page, the symbols come back. If you delete something it should stay deleted, whether you refresh the page or not.

**Comment by HGustavs** [comment]
Could it be that the data update is not triggered by deletes?

**Comment by a17johpe** [comment]
Have tried several solutions but can't find a reliable fix. It seems to work for some objects sometimes and sometimes not?
