### ISSUE TITLE
Toolbar labels are in the wrong position

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6720]
As of now, the toolbar labels are positioned wrong. The lables should pop up next to the button, not beneath the entire toolbar.
related to #6699

**Comment by HGustavs** [comment]
Screenshot. Unclear where we are and in what view.

**Comment by a16tobfr** [comment]
<img width="76" alt="label" src="https://user-images.githubusercontent.com/49199690/57358286-5f919700-7175-11e9-8bf5-7c5573c96f98.png">

**Comment by a14oscna** [comment]
An attempt has been made and merged but we are still looking for a solution which places the tooltip next to the hovered button. I will therefore not close this issue yet.

**Comment by a17vikab** [comment]
Closing this issue, if the next generation of developers want to change the location they might need to create a new issue.
