### ISSUE TITLE
Order numbering of diagram objects

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6724]
Continue where #6688 ended Fix the issue when copying objects and make sure it pleases @a16tobfr with numbers that are reused. eg If the user only makes 6 entities their default names will be Entity 0, Entity 1, Entity 2, Entity 3, Entity 4, Entity 5. Then the user deletes Entity 0. Next Entity drawn should then reuse the number 0. As it is now the next entity would be called Entity 5 and the user would end up with two of those.

**Comment by a14oscna** [comment]
Im happy with how the solution looks now after the #6890 merge and will therefore close this issue.
