### ISSUE TITLE
Right click moving the diagram opens context menu

### ISSUE THREAD

**Issue by c17matjo** [HGustavs/LenaSYS#6726]
When rightclick-dragging to move the canvas around the browsers rightclick context menu opens, blocking the canvas. This seems to only happen on some OS's/browsers. 
![image](https://user-images.githubusercontent.com/49195031/57357804-1f7de480-7174-11e9-896c-2bb99510ef91.png)
After rightclick-dragging a context menu is opened. Verified on my linux laptop on both firefox and chrome. 

Related to issue #6634, original rightclick-drag issue #5748

**Comment by a17johpe** [comment]
It works on my laptop with Windows 10 on both Chrome and Firefox so I can't test this.

**Comment by c17matjo** [comment]
It still happens in the GruppA2019W20 branch on my laptop. I've tested it on a macbook I had home and it happens there too. The issue might only show up for linux and mac.

**Comment by a17johpe** [comment]
If the issue only exists on Linux and Mac, someone with either/both OS needs to be assigned to this issue.

**Comment by a16jenja** [comment]
#7422 Fixed this issue.
