### ISSUE TITLE
Diagram: Not be able to enable menu-items that are disabled

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6727]
Right now you can enable menu-items that are disabled. This should not work.

<img width="288" alt="Skärmavbild 2019-05-08 kl  09 55 52" src="https://user-images.githubusercontent.com/37792795/57359235-7cc76500-7177-11e9-8ba2-9c928fac35ba.png">

**Comment by a17celal** [comment]
Maybe a solution could be that you check if "display virtual A4" is active, otherwise you should not be able to select the other A4-options.
I could not get this to work propely, but hopefully someone else can!
