### ISSUE TITLE
Resulted Teacher is not an option anymore

### ISSUE THREAD

**Issue by a17amama** [HGustavs/LenaSYS#6728]
Sorting by teacher, etc, does no longer exist cause the data about teacher has been removed. 
Either it should be removed, or if Henrik prefers, it should be inserted again so that it can be used.

**Comment by a17pongo** [comment]
@HGustavs is this an important feature? 
@a17amama could you provide more info where data about teacher has been removed?

**Comment by a17amama** [comment]
Teacher has been removed from the list of student, it used to be right below the name of the student.
![teacher](https://user-images.githubusercontent.com/37793130/57701887-384b3600-765d-11e9-8c53-89b87055ac1c.PNG)

**Comment by a17amama** [comment]
@HGustavs  Should we remove the option to sort it by teacher, or should we add information about teacher inside table and keep the sorting list option?

**Comment by HGustavs** [comment]
Useful information for final year projects, for which there is an examiner / teacher for each person.

However.

Unclear if this was implemented completely, and to what extent this actually works.....

There may be issues both for the marking view and the access view for specifying who is the teacher for each person in the final year project courses.

**Comment by HGustavs** [comment]
Spelunking needed!

**Comment by b17nicsv** [comment]
@HGustavs In AccessEd we can set examiner for each individual student. How about, when a specific teacher is set to that student, it shows in ResultEd also? 

Like this:
![Like this](https://user-images.githubusercontent.com/49198878/58024200-f06f5780-7b11-11e9-926f-9163f7c92df3.PNG)

**Comment by a17alian** [comment]
@HGustavs  created the issue  #7265 that requires teacher data to exist in resulted. I think the data should be accessible again

**Comment by HGustavs** [comment]
Since it is only used in final year projects, it is a rarely used feature.

* We definitely do ***not*** want null to be written out for all other courses that are not final year projects
* Either adding it as text if not null on firstname etc
* Or adding a specific column examiner that can be ommitted.

Should say examiner and not teacher to clarify functionality.

**Comment by c17johha** [comment]
@a17amama you said "sorting" but do you mean "filtering"?
#7265 uses filtering of teacher.

**Comment by b17nicsv** [comment]
This issue already has a solution. Currently there's a dropdown menu which filters students after a specific examiner, which is a solution to this issue. It also doesn't clutter up the table.
