### ISSUE TITLE
Change the cursor when the line button is selected

### ISSUE THREAD

**Issue by a17okaoz** [HGustavs/LenaSYS#6729]
When the button line is selected and when you are going to draw a line between two objects change the cursor so the user knows that it can draw. Remove the cursor pointer or choose another pointer for increase the usability

**Comment by a14oscna** [comment]
Further clarification of requirements are described in my comment on the references pull request #6828

**Comment by a17jacsv** [comment]
> Further clarification of requirements are described in my comment on the references pull request #6828

Created a new issue of this updated issue: #6853
