### ISSUE TITLE
Unnessecary max-width?

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#6732]
![Screenshot 2019-05-08 10 56 05](https://user-images.githubusercontent.com/4948661/57362845-f5caba80-717f-11e9-8c8f-562bdabd38c6.png)

It seems that we have a max-width on our table columns when grading, but if there is room why not use the space?

**Comment by c17julka** [comment]
At least on the version we are using, there seems to be no max-width set on the columns in resulted. Where exactly is the issue referring to? @a97marbr

**Comment by HGustavs** [comment]
Does this appear in the repo version? If not we can confirm and retire this issue.

Test with different browsers.... (not Internet Explorer)

**Comment by c17julka** [comment]
This issue cannot be replicated with the repo version. It has been tried on Chrome, Firefox and Edge. The only max-width that exists is the one for the grading icons container, which doesn't do much more else than to center the icons.

Will close since it seems to have been solved in the past.
