### ISSUE TITLE
Recursive relationships for ER and UML

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6733]
It should be possible to draw a line from an entity / class back to itself to represent recursive relationships as seen in the image below.
![recursive](https://user-images.githubusercontent.com/37793141/57363473-75a55480-7181-11e9-9cb1-8992b6bb53c8.PNG)
When drawing such lines in for example lucidcharts, the line automatically gets a fixed length outwards from the object before it turns back and connects to itself. We should strive for a similar result.

**Comment by a14oscna** [comment]
Reference to #3739 where this is mentioned.

**Comment by c17matjo** [comment]
Are recursive lines for ER relations actually needed? I don't remember how ER works very well but from a google search it looks like recursive relations still use the relation symbol which means they should already work without needing a special recursive line.
![bild](https://user-images.githubusercontent.com/49195031/58077119-28c37400-7bac-11e9-81c7-cea48497940e.png)
