### ISSUE TITLE
Double-clicking while draw free is selected breaks the drawing 

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6734]
If you select the Draw Free mode and double-click on the canvas you will create a new text frame and also start drawing a new line from the point you clicked at. If you continue doing so the next line will not connect to the first and this totally breaks the drawing. In image below a double-click was made at every point where a "New Text X" is shown.
![drawfreedouble](https://user-images.githubusercontent.com/37793141/57364484-98d10380-7183-11e9-8733-bb8dadc73cc9.PNG)

**Comment by a17drama** [comment]
This issue got solved by #7040 and can be closed. This phenomena doesn't show anymore. @a17vikab  please close it.

**Comment by a17vikab** [comment]
Solved.
