### ISSUE TITLE
ResultEd: Missing viewport meta tags

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6739]
ResultEd doesn't have a viewport meta tag for mobile devices, so it starts way zoomed out in mobile view.

I guess use the viewport meta tag from DuggaEd:
`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />`

**Comment by c17julka** [comment]
I will also add a better functionality to the filter buttons and search bar along with this issue.
