### ISSUE TITLE
Progressbar off grid

### ISSUE THREAD

**Issue by c17alepe** [HGustavs/LenaSYS#6741]
![image](https://user-images.githubusercontent.com/38323901/57370571-b9ec2100-7190-11e9-9ab4-56dc91db6fc2.png)

The progress bar is off grid. It is not like this on the live dugga site where it looks like this: 

![image](https://user-images.githubusercontent.com/38323901/57370618-dd16d080-7190-11e9-85ae-e3a3305b41ff.png)

**Comment by a17ludca** [comment]
I can't replicate this issue, it works for me.
![image](https://user-images.githubusercontent.com/37799006/57435493-d5f9cc00-723d-11e9-81ae-9ace51ebb27e.png)

**Comment by c17julka** [comment]
I cannot replicate this either.

**Comment by c17johha** [comment]
![Namnlös](https://user-images.githubusercontent.com/49199825/57446584-4fe97f80-7255-11e9-90e3-7c783134116d.png)
The problem does appear on Edge

**Comment by c17alepe** [comment]
I use a browser called Vivaldi, which is based on chrome, but chrome works. So it seems like edge and vivaldi is the only faulty ones here.
