### ISSUE TITLE
Update styling of "daily minutes" page.

### ISSUE THREAD

**Issue by a17robes** [HGustavs/LenaSYS#6743]
I noticed we need to add some padding to the "Add row" button and maybe change the hover-effect on the "submit" button to be consistent with other buttons on dugga.  For example it looks like the "submit" button gets a border radius on hover atm, and the "Add row" button is missing an hover effect. 
![image](https://user-images.githubusercontent.com/38004435/57372545-477e3f80-7196-11e9-9807-2154d6792f23.png)

**Comment by a17poner** [comment]
merged!
