### ISSUE TITLE
Submitting incorrect file type has no styling

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6744]
I would suggest showing a dialog on the same page where you hand in the assignment, or the page showing the error could be changed to look better.

Example:
![Capture](https://user-images.githubusercontent.com/37834592/57373760-6df1aa00-7199-11e9-9c9b-f7c2c950f939.PNG)

**Comment by b16johso** [comment]
@b17carma where can I find an example dugga to test this?

**Comment by b16johso** [comment]
Related issue https://github.com/HGustavs/LenaSYS/issues/6780

**Comment by b16johso** [comment]
The plan is to display the error on the showDugga page instead, like this:
![bild](https://user-images.githubusercontent.com/37793460/57528299-497d0580-7332-11e9-8c1c-f3e4bf51dbac.png)

**Comment by a17poner** [comment]
merged, closing
