### ISSUE TITLE
MOTD-message not centered

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#6752]
the message isn't fully centered.

![image](https://user-images.githubusercontent.com/37799006/57376272-e5c2d300-719f-11e9-97dc-e348595f2a44.png)

**Comment by b16johso** [comment]
This was caused by someone removing the close-button's position property. It previously had absolute positioning and now it has no positioning at all.

**Comment by b16johso** [comment]
Related issue https://github.com/HGustavs/LenaSYS/issues/6832
