### ISSUE TITLE
Accessed.js - unnecessary console logs

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#6754]
Someone forgot to remove their `console.log("test");` in the accessed.php file. 
![Screenshot from 2019-05-08 14-45-09](https://user-images.githubusercontent.com/49235724/57376281-e9eef080-719f-11e9-905d-c2860bef1771.png)

**Comment by a17andby** [comment]
> I guess you just wrote the wrong file name and really mean accessed.js xD

Oh yeah, sorry! My bad! :P

**Comment by a17poner** [comment]
merged with #6775 closing
