### ISSUE TITLE
Canvas workspace is smaller

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#6760]
This is before the merge (how it should be):
![Capture13](https://user-images.githubusercontent.com/37792271/57376711-017aa900-71a1-11e9-892d-54ffca5ac523.PNG)

This is after the merge:
![Capture14](https://user-images.githubusercontent.com/37792271/57376729-0a6b7a80-71a1-11e9-92a4-061f9e7c9242.PNG)

It's not really clear in the pictures, but the canvas workspace should cover a larger surface.

**Comment by a14oscna** [comment]
Reason for closing this issue is written in pull request #6807
