### ISSUE TITLE
Problems with login!

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#678]
To be able to login you have to type in your information and click login. Close the window and refresh the page.

**Comment by HGustavs** [comment]
Run it with firebug or chrome developer console.
Perhaps there are error messages that are hindering proper execution.

**Comment by HGustavs** [comment]
Perhaps the  "User interface fix code viewer #670" branch that was merged by
a12jiyba merged 2 commits into cv15 from User-interface-fix-code-viewer 4 hours ago fixes this?

**Comment by b13danso** [comment]
Fixed with issue #594.
