### ISSUE TITLE
Pressing escape key in sectioned.php removes top menu

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6781]
Before esc:
![image](https://user-images.githubusercontent.com/37834592/57387504-c4211600-71b6-11e9-82f2-b5355246530f.png)

After esc:
![image](https://user-images.githubusercontent.com/37834592/57387522-c8e5ca00-71b6-11e9-94e3-d4c3309eb532.png)

**Comment by c17johha** [comment]
problem doesn't appear in GruppB2019W21

**Comment by a17joaap** [comment]
Fixed in https://github.com/HGustavs/LenaSYS/pull/7171
