### ISSUE TITLE
Duggaed: Stop editing variant when clicking the cog again

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6786]
Clicking the cogwheel of an active variant should make it inactive again.
![variantcog](https://user-images.githubusercontent.com/37792198/57390552-e87ff100-71bc-11e9-9b9b-82dafb89db7d.PNG)

One idea would be to have a global variable (horrible I know) that keeps track if a variant is being edited.

**Comment by a17fellu** [comment]
Instead of a global variable isn't it better to have a function that you can both set a value to through the parameter and also returns the value?

**Comment by a17robda** [comment]
I have fixed this without globals. About to push right now.

**Comment by a17poner** [comment]
merged, closing!
