### ISSUE TITLE
Disabled menu items is visable after recent merge

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6788]
See picture.... 

_"Display all tools", "Toggle A4 Orientation", "A4 Holes Right"_

![Skärmavbild 2019-05-09 kl  09 33 20](https://user-images.githubusercontent.com/37792795/57435371-81565100-723d-11e9-946a-46a8b9b33ca9.png)

Related to issue: #6727

**Comment by c17matjo** [comment]
How should the ER/UML selector work when entering developer mode? Right now, entering developer mode deselects the ER or UML option but doesn't disable them meaning you can still enter ER/UML mode without leaving developer mode. Should the ER/UML options be greyed out when in developer mode?

**Comment by a17jacsv** [comment]
> How should the ER/UML selector work when entering developer mode? Right now, entering developer mode deselects the ER or UML option but doesn't disable them meaning you can still enter ER/UML mode without leaving developer mode. Should the ER/UML options be greyed out when in developer mode?

Yes, that would be the best solution as in developer mode all objects are available.
