### ISSUE TITLE
Example of a diagram for education

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6790]
There is a lot of unused code that could be used for educational purposes. The function generateExampleCode() generates a diagram that at this point is made for debugging but with some modification this could be made into a good example of a small diagram that can show the student all correct drawing of ER and UML. This can even be completed with some text that explains what different symbols mean in case a reminder is needed. This would be a nice clickable addition for the Help menu.

**Comment by a18kaswi** [comment]
The idea in Issue #6612 will be solved when this is finished.

**Comment by a18jonpe** [comment]
I have so far created an example of an ER-diagram. I'm going to add two buttons under help, one for ER and for UML so that the users screen doesn't get too crowded.

**Comment by a18jonpe** [comment]
An example UML-diagram has also been created. These examples can be improved further, and more can be added in the future.
