### ISSUE TITLE
Error in test page when creating new test. 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6794]
Creating a new test will give a error, this has not been a problem until now. 
![image](https://user-images.githubusercontent.com/49199285/57439660-c763e280-7246-11e9-99c1-1312d9b5526d.png)

**Comment by a17joaap** [comment]
https://github.com/HGustavs/LenaSYS/pull/6562/commits/18b67cb61f47da558c5ab847c2d8c27554faef02
