### ISSUE TITLE
duggaed.php doesn't have a title

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#6808]
![image](https://user-images.githubusercontent.com/37792321/57445774-5f67c900-7253-11e9-837b-73384dc27037.png) ![image](https://user-images.githubusercontent.com/37792321/57445812-73abc600-7253-11e9-8c27-9af889fe050c.png)

Unlike the other table sections, like resulted (right picture), duggaed doesn't have a certain title. This should be changed into the appropriate title.

**Comment by a17andby** [comment]
Duggaed has a title, but it seems that it is overwritten by some javascript maybe?
![Screenshot from 2019-05-09 13-14-20](https://user-images.githubusercontent.com/49235724/57449527-70690800-725c-11e9-8fd8-57b35ed67856.png)

**Comment by c17julka** [comment]
Closing this since it has been fixed from issue #7019, PRs #7229 / #7246
