### ISSUE TITLE
[SectionEd] Set Date in Edit Item view style needs fixing

### ISSUE THREAD

**Issue by b17nicsv** [HGustavs/LenaSYS#6812]
![xerctvbyhjmk](https://user-images.githubusercontent.com/49198878/57447137-9a1f3080-7256-11e9-9bdc-dc45cc095836.PNG)

Styling on set date should be similar to the rest of the options.

**Comment by a16hiwah** [comment]
@b17nicsv 
issue has been fix!

![image](https://user-images.githubusercontent.com/37792852/57614911-b551af00-757a-11e9-9b6d-9b7be8115bf3.png)
 test link; https://a16hiwah.webug.his.se:20002/DuggaSys/sectioned.php?courseid=2&coursename=Webbutveckling%20-%20datorgrafik&coursevers=97732
