### ISSUE TITLE
Missing border lines in access table. 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6818]
![image](https://user-images.githubusercontent.com/49199285/57448722-5c240b80-725a-11e9-8afe-99538ce79a1d.png)
No border lines in access, even though it had border lines a few weeks ago. Maybe we should consider putting in border-lines so it has the same styling as test & files table. 

![image](https://user-images.githubusercontent.com/49199285/57448851-b624d100-725a-11e9-9186-094fa2eb5bc2.png)
I am thinking about these border lines. (from file page)

**Comment by a17fellu** [comment]
That's a good idea will make it more readable

**Comment by a17fellu** [comment]
Added the borders in Pull Request: #6852

**Comment by a17poner** [comment]
merged, closing!
