### ISSUE TITLE
Box shadow on only some elements

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#6820]
There is a box shadow around the square and the draw free. But all other elements are missing a box shadow. Either all elements should have it, or none.

![Capture15](https://user-images.githubusercontent.com/37792271/57449830-32201880-725d-11e9-8cdb-252558064b6a.PNG)

**Comment by a14oscna** [comment]
Remove box shadow for all objects.

**Comment by a17drama** [comment]
@a14oscna There is loads of code for making shadows on different objects. Do we remove all of that or just the shadows on the objects?

**Comment by a14oscna** [comment]
We do not want shadows set by CSS nor by script functions, so I want you to remove any unnecessary functions related to box shadows.
