### ISSUE TITLE
Consistency suggestion with zoom buttons

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#6829]
I suggest making the zoom buttons equally big, for consistency in styling. Preferably making the left zoom button as big as the right one.

![8881a2b5f0883a53d522286e4c7ccca8](https://user-images.githubusercontent.com/38030926/57452071-36e7cb00-7263-11e9-9269-6c3e181c31e7.png)

**Comment by a17vikab** [comment]
This Issue could handle the position of the "+" and "-" inside the buttons as well. They are not correctly centered.

![image](https://user-images.githubusercontent.com/37792464/57452738-dbb6d800-7264-11e9-9380-1ab489e1f8ca.png)
