### ISSUE TITLE
Refreshing session results in blank alert

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6830]
A dialog, telling you your session will expire in 30 minutes and asking if you wish to refresh your session, pops up after being inactive for a while. Clicking the the "Refresh" button in this dialog results in a blank alert window.
![bild](https://user-images.githubusercontent.com/37793460/57452279-ab226e80-7263-11e9-83df-7c82afeb7200.png)

**Comment by b17carma** [comment]
Does this happen in firefox? I can't reproduce it in chrome:

![image](https://user-images.githubusercontent.com/37834592/57455463-70243900-726b-11e9-867f-1bda6b487575.png)

After pressing:

![image](https://user-images.githubusercontent.com/37834592/57455484-7e725500-726b-11e9-8ecb-c107bdd57286.png)

**Comment by b16johso** [comment]
Might be a Firefox issue then. Either way the alert should be removed imo. It feels like it was probably used for debugging and left in by mistake.

**Comment by b17carma** [comment]
I agree, the alert looks out of place and isn't really necessary

**Comment by b17carma** [comment]
I created https://github.com/HGustavs/LenaSYS/issues/6841 as a separate issue for this.
