### ISSUE TITLE
Sectioned Progress bars. Box doesn't expand by rows

### ISSUE THREAD

**Issue by ghost** [HGustavs/LenaSYS#6836]
![image](https://user-images.githubusercontent.com/49199825/57454304-cba0f780-7268-11e9-9bfb-0fbbd896dba2.png)

This appears in Firefox.

**Comment by c17johha** [comment]
![image](https://user-images.githubusercontent.com/49199825/58501650-31581380-8185-11e9-91a9-944319bb3e73.png)

Progress bar in Firefox. Doesn't expand by rows

**Comment by a18oscba** [comment]
This issue is not active, it works perfectly fine on chrome and according to the issue on firfox the box wont expand. However, it acts just like chrome now and expands just fine. Therefore closed.
