### ISSUE TITLE
Hover function on the login/logout button is broken. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6842]
The hover function on the login/logout button is borken since the latest merged. It should be slightly brighter when hovered.

**Comment by a17andby** [comment]
Probably got broken with the big merge issue we had with the css. https://github.com/HGustavs/LenaSYS/commit/bd5983a3e773dff747c779d48188e97bed32d3d9

**Comment by a17pongo** [comment]
I am working on reverting the CSS, should be done tomorrow before lunch but can not guarante that it will be 100% reverted.
If anything is missing after I am done reverting it might be easier for people to clone my branch and commit fixes before performing a pull request? but that can be discussed between our leaders

**Comment by a16joare** [comment]
Hows the CSS reverting going?

**Comment by a17pongo** [comment]
still working on it, hopefully finished by the end of the day.. I was charged with changing all the colors in the file and not just the changes that were lost.

**Comment by a17alevu** [comment]
Solved and closed.
