### ISSUE TITLE
Give the option to add Contribution dugga to a course during the install

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#6849]
Nice for dev/testing/demo purposes as discussed in #6612

**Comment by a18kaswi** [comment]
R.n it boils down to how to beautifuly structure an interactive function that mods the install-db during install.

**Comment by a18kaswi** [comment]
See customers answer in #6612 

In contrast to the Diagram-Dugga, the Contribution-dugga exist. 

This means we can start with adding this to the 'Demo-Course' when that one is implemented.

1. Implement ability to add 'Demo-Course'

2. Add 'Contribution-Dugga' (LenaSYS\DuggaSys\templates\contribution) to 'Demo-Course'.

**Comment by a18kaswi** [comment]
The ContributionDugga is now available in the Demo-Course.
