### ISSUE TITLE
accessed.js: There are alot of unused functions

### ISSUE THREAD

**Issue by a17fellu** [HGustavs/LenaSYS#6856]
To be more specific there are functions that start on row: 50 - 102 in accessed.js that doesn't seem to be of any use. Have tried removing them and there is no change on accessed.

**Maybe we should remove them to make the file smaller?**

**Comment by a17robda** [comment]
What functions are you referring to?

**Comment by a17fellu** [comment]
As stated above, all functions starting at line: 50 - 102

**Comment by a17robda** [comment]
![accessedicons](https://user-images.githubusercontent.com/37792328/57516321-ca2d0900-7314-11e9-925d-af6fcf9f82d6.png)
Commenting these lines out will break hovering on these icons and add/edit user buttons on FAB. Faulty comment in code?

**Comment by a17fellu** [comment]
Most likely will closing
