### ISSUE TITLE
Login/out button covers the scrollbar. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6857]
The login/out button is to much to the right and covers the scrollbar. 
![image](https://user-images.githubusercontent.com/49194898/57513582-df069e00-730e-11e9-96f8-12af01e7bb2c.png)

The image also shows that the shadow from the navheader is appearing under the button. Dont know if that is a issue but it looks kind of strange.

**Comment by a17robda** [comment]
Seems strange, Might be a browser related issue.

**Comment by a17robda** [comment]
![loginbar](https://user-images.githubusercontent.com/37792328/57515637-69510100-7313-11e9-9317-b6258cb6538e.png) 
![loginbar2](https://user-images.githubusercontent.com/37792328/57515788-bb922200-7313-11e9-9371-666fa90f669a.png)

I will close this since I could not replicate the issue on multiple browsers. It does not seem to be a css related issue?
This could be reopened if needed.

**Comment by a16joare** [comment]
Test to access the contribution page and look there. Did some tests now and it works for all the other pages but not on contribution apparently
..

**Comment by a17robda** [comment]
![contribar](https://user-images.githubusercontent.com/37792328/57516943-090f8e80-7316-11e9-9a41-641be75fb113.png)

It works for me on the contribution page aswell.

**Comment by a16joare** [comment]
Hmm, seems strange. Will ask some more groupmembers to check this out.

**Comment by b16johso** [comment]
I can't replicate this. Works fine for me in both Firefox and Chrome.

**Comment by a16joare** [comment]
@a17alevu has the same problem..

**Comment by a17robda** [comment]
Using GruppC2019W20 and still cannot replicate the issue.

**Comment by a16joare** [comment]
Are you using the webserver or a local test server ?

**Comment by a17robda** [comment]
Local

**Comment by a16joare** [comment]
hmm very strange. We are some guys here in school and we all got it..

**Comment by a17robda** [comment]
https://stackoverflow.com/questions/13028584/browsers-scrollbar-is-under-my-fixed-div
Skulle kunna vara något liknande. Öppnar så länge.

**Comment by a17andby** [comment]
Tested this on my local test environment and on the test server, both on our weekly group branch. Can't reproduce this.

![image](https://user-images.githubusercontent.com/49235724/57526799-ab3b7080-732e-11e9-9e13-458da5aca1c4.png)

**Comment by a16joare** [comment]
Did you check this on the contribution page?

**Comment by b17carma** [comment]
The problem appears to be that there's a scrollbar for the iframe which appears under the original navbar.
 
There's also a second navbar hiding under the original one, but I think I can come up with a solution for the problem.
