### ISSUE TITLE
Shortcut on toolbar items

### ISSUE THREAD

**Issue by a17okaoz** [HGustavs/LenaSYS#6859]
Make so the items in the toolbar have a shortcut command for selecting them.  #6738 Look into this issue as well when doing this issue.  

The commands could be:
Line: shift + L
Entity: shift + E
Attribute: Shift + T
Relation: shift + R
Draw Free: shift + D
Uml create class: shift + C
Help: shift + H
Mode switch: shift + M

**Comment by a17drama** [comment]
shift + D should trigger the developer mode and shift + F could be used for free draw. What is help used for?

**Comment by a17okaoz** [comment]
> shift + D should trigger the developer mode and shift + F could be used for free draw. What is help used for?

**Comment by a17okaoz** [comment]
Yes, that solution is good!. Forget about the help command it is unnecessary
