### ISSUE TITLE
View menu got broken

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#6863]
![Edited](https://user-images.githubusercontent.com/46029340/57515352-b7193980-7312-11e9-99bb-422812552c9e.png)
While A4 isn't toggled the "child" menus should be grayed out. This worked in the past but got broken. Same thing goes for Developer mode and its "child".

**Comment by HGustavs** [comment]
Not super important but....

**Comment by a17vikab** [comment]
I think this is related to #6788. Might even be the same issue?

**Comment by a17vikab** [comment]
> I think this is related to #6788. Might even be the same issue?

this issue does already exist, therefore I am closing this one.
