### ISSUE TITLE
Alter sorting by grade in resulted to asc/desc/pending

### ISSUE THREAD

**Issue by b17timjo** [HGustavs/LenaSYS#6876]
See discussion in #6515

Instead of sorting by -/P/U/G/VG where some of the options have no clear purpose, sort by three new alternatives: pending grades, and grades ascending/descending.

Quoting HGustavs full post from #6515 for context:
> Use centric sorting.... off the top of my head I want the most relevant items first.... hopefully my view of relevant is same as everyone elses....
> 
> For all views
> 
>     * We always want un-viewed tests at bottom in all sort orders.
> 
>     * After that visited but not handed in.
> 
> 
> For grade specific views sort in order of grades given the sort order... if U start with U and then falling
> if VG start with VG and then falling.
> 
> No G mode.
> 
> Howabout Ascending grade mode, Descending Grade mode and Pending.

**Comment by c17johha** [comment]
What does it mean when an element is purple like this:
![image](https://user-images.githubusercontent.com/49199825/57684637-77b25c00-7636-11e9-98ae-5d1e8fe42654.png)

Compare to a grey element:
![image](https://user-images.githubusercontent.com/49199825/57684704-9d3f6580-7636-11e9-90fd-ca7a92f7ece6.png)

Is one of these "pending"?
@b17timjo @HGustavs

**Comment by b17nicsv** [comment]
I think the light grey and dark grey both are pending, but the background makes them light/dark.

**Comment by c17johha** [comment]
Firefox and Chrome doesn't call the function "newCompare" the same amount of times for the exactly same conditions. I believe that this is the reason for the inconsistency between Chrome and Firefox
