### ISSUE TITLE
The table in tests has an extra row. Need to be changed. 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6877]
![image](https://user-images.githubusercontent.com/49199285/57524590-90fe9400-7328-11e9-9b95-4936b82232e0.png)
I am talking about the row that is empty row 15, this should be removed in my opinion.

**Comment by a17alevu** [comment]
This is also somewhat relevant for the access table. But there is only a gray line at the end of the page.  
![image](https://user-images.githubusercontent.com/49199285/57524827-4df0f080-7329-11e9-83d7-0e1eabe79c76.png)

**Comment by a16joare** [comment]
@HGustavs is this even an issue?

**Comment by HGustavs** [comment]
Unclear.

Im hoping there is a way to disable the footer if not needed.

It should not be there automatically, there should be something like footer=true / footer=false in te constructor ...

If not we should report that as a separate issue.

**Comment by a17alevu** [comment]
Isn't this a group B issue?

**Comment by a17robes** [comment]
![image](https://user-images.githubusercontent.com/38004435/58327111-08571c00-7e2f-11e9-9dbb-69eb5f5ecc9f.png)
There are no options for hiding the footer, therefore it's a problem that needs to be fixed in sortabletable.js.

**Comment by a17poner** [comment]
merged @a17joaap 's request that added a footer boolean to sortableTable. closing!
