### ISSUE TITLE
Toolbar options in the wrong order

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#6882]
The customer wants to remove all the text other than tools and create and move the options around. It should be:

![image](https://user-images.githubusercontent.com/37792464/57524922-a1fbd500-7329-11e9-8602-ae761b8c9813.png)
![image](https://user-images.githubusercontent.com/37792464/57524888-7c6ecb80-7329-11e9-9d66-44a82e06ab38.png)
![image](https://user-images.githubusercontent.com/37792464/57524963-bcce4980-7329-11e9-8457-b3fab7a371ca.png)
![image](https://user-images.githubusercontent.com/37792464/57525007-db344500-7329-11e9-9d38-93f4c45bcc86.png)

**Comment by a16tobfr** [comment]
Do we still want the draw square button to be there? Was it not supposed to be removed, or is that being done in another issue?

**Comment by a16tobfr** [comment]
After talking to a17vikab, the decision is that the draw square button will be removed in this issue
