### ISSUE TITLE
Sectioned inconsistency of headings arrow

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#6883]
![inconsistensy](https://user-images.githubusercontent.com/49199825/57525047-ed15e800-7329-11e9-8488-542d22ac206b.png)

When expanding a section, the arrow should point down. And for minimized section, it should point to the right, not vice versa.

**Comment by a16hiwah** [comment]
@b17timjo 
i don't think this is a issue, i tested on Firefox och Google Chrome and on both working fine

results;
![image](https://user-images.githubusercontent.com/37792852/57690750-a46c7080-7642-11e9-823b-c30828125344.png)

**Comment by c17johha** [comment]
Agree with @a16hiwah , I can no longer reproduce this issue

**Comment by b17timjo** [comment]
Please direct your questions to either johha who opened the issue, or nicsv for decisions

**Comment by b17nicsv** [comment]
Closing this if it can't be replicated anymore. Will reopen if it resurface.
