### ISSUE TITLE
[SectionEd] Disappearing items when changing category from moment to section

### ISSUE THREAD

**Issue by b17nicsv** [HGustavs/LenaSYS#6887]
In SectionEd, "outer" items which has the category Moment disappears when changed to Section. 

How to replicate:

Navigate to Webbutveckling - Datorgrafik.
![ascd](https://user-images.githubusercontent.com/49198878/57526111-c7d6a900-732c-11e9-9f39-6497910d02cc.PNG)

Select "edit item" on any "outer" item which has the category Moment(except the first one!)
![sfv](https://user-images.githubusercontent.com/49198878/57526140-d7ee8880-732c-11e9-9526-ab504bd4a6fb.PNG)

Set the category from Moment to Section.
![casdc](https://user-images.githubusercontent.com/49198878/57526181-f6ed1a80-732c-11e9-8ea0-4d55ecf64492.PNG)

Watch the item disappear.
![jjj](https://user-images.githubusercontent.com/49198878/57526189-fa80a180-732c-11e9-8f7b-c7e900f5b6ea.PNG)

**Comment by c17johha** [comment]
When changing type moment to section, the element can be found inside another moment. Maybe this is a preferred behaviour? Should it be possible for an element with type "section" to be outside a moment? @HGustavs

**Comment by b17nicsv** [comment]
This isn't an issue anymore. As discussed on the kundmöte, it is working as intended yet slightly confusing for someone not used to the system.
