### ISSUE TITLE
Remove local appearance from double-clicking

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#6888]
Remove local appearance from double-clicking to a menu item to not encourage random colors and styling on the diagram.

It should be behind an "advanced settings" of some sort according to the customer.

The dubble-clicking need to still be there for entity-type and name and so on.

![image](https://user-images.githubusercontent.com/37792464/57526725-6fa0a680-732e-11e9-9391-f1615445df9f.png)

**Comment by a18kaswi** [comment]
appearanceDiagram
#7677
#7928
#7645
#8067
#6888

**Comment by a18antsv** [comment]
I think this would too many steps actually set the advanced settings. No one wants to click an object, hover over the menu-item and then click on the advanced settings option. Most of the time double click is used to style a single element. The only time the menu is used for appearance is for global appearance and for styling multiple selected objects at once.

**Comment by a18antsv** [comment]
Instead I think all the "advanced settings" should be hidden by default when opening the appearance menu but the option to show them exists. This still prevents the user from being encouraged to change to random colors on everything as an extra click is needed. If change of styling is needed it is still not so far away.

**Comment by a18antsv** [comment]
I imagine it being a "+" button with the label "Advanced properties" to show all the advanced properties in the appearance menu.
