### ISSUE TITLE
Burger feels wonky when half shrunk: SectionEd

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#6889]
![image](https://user-images.githubusercontent.com/37792766/57526732-729b9700-732e-11e9-82cb-1ec143f2f0b5.png)

**Comment by b17annni** [comment]
![image](https://user-images.githubusercontent.com/37792766/57528752-6b2abc80-7333-11e9-9f5c-d72b420d95a6.png)

**Comment by a17poner** [comment]
merge, closing !
