### ISSUE TITLE
Create and remove points on an existing free draw object

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6891]
When you have created a free draw object, such as the following: 
![draw free](https://user-images.githubusercontent.com/37793141/57526755-834c0d00-732e-11e9-9e98-48c52c7af8a8.PNG)
You should be able to create a new point by double-clicking on the line between two points and remove a point by clicking on the specific point and pressing the delete button.

**Comment by b17robev** [comment]
Should calculate between which points the new one should be added. The new point needs to be inserted at the correct point in the object's points array, as lines are drawn between points located adjacently in the array, rather than coordinates.

**Comment by b18phibe** [comment]
My eddits are in branch G4-2020-W18-ISSUE#8189 (don't know why its named that way...)

in Diagram_object row 2766 are a removeSegment function to remove segment... 
in diagram.js row 3988 it's a contextmenu function. My thought was that i was to make a costume contextmenu(right click menu) ( this menu could be used for all sort of figures on the canvas). To figure out are: 
* what symbolkind a freedraw object are so you can have a specific menu to popup if that symbolkined were to be right clicked.

* how to rewrite the removeSegment function to be better at removing only one node and how to detect what node to remove. (whit a hard coded node to remove the entire free drawing disappears til the side are reloaded.)

*and add someway of adding segments to already existing arrays. 
I belive we might wanna change the segment array to a segment linked list but when i looked at if it seemed like it was a lot of work to do in JS  but it would help whit adding and removing objects in the list.

**Comment by b18phibe** [comment]
Good work closing
