### ISSUE TITLE
showDugga/File_receive: Can't upload rar files

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6895]
showDugga says you can upload rar files:
![bild](https://user-images.githubusercontent.com/37793460/57527901-1c7c2300-7331-11e9-98af-83be13dae909.png)

But the code in file_receive.php only allows zip files:
![bild](https://user-images.githubusercontent.com/37793460/57527962-459cb380-7331-11e9-9811-023032858258.png)

**Comment by a17poner** [comment]
merged !
