### ISSUE TITLE
Zooming should originate from the center of the view rather than origo

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#6899]
When you zoom using the zoom bar in the bottom right corner, it originates from origo which is redundant since origo rarely is where objects are drawn around. Therefore zooming should originate from the center of the view when the zoom bar is used. It should still zoom from the position of the mouse when the scroll wheel or similar is used.

**Comment by a17drama** [comment]
#6854 is a small change and will be solved here. Reason why is that it's needed for the calculations for the zooming. Make sure to close that issue as well when this is being closed.
