### ISSUE TITLE
The icon on the codeviewer.php page is different from the others on dugga. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6903]
The icon that is showed on web tab in the browser is different from the others on dugga.. It is not even transparent so it is possible to see the white box around it. 
![image](https://user-images.githubusercontent.com/49194898/57529737-ee4d1200-7335-11e9-91fc-9e3e3a037c04.png)

**Comment by a17maxsj** [comment]
solved https://github.com/HGustavs/LenaSYS/pull/6950
