### ISSUE TITLE
diagram_IOHandler.js several functions lack explanatory comments

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6913]
diagram_IOHandler.js
Several functions lack explanatory comments which make it hard to figure out where they may be used. Even if a function may seem self-explanatory, it may be beneficial to add some kind of comment about how or where the function is used.
Improves the readability of this document.

Example of functions without comments:
~~~
function redirectas(doc,folder) {
...
}
function redirect(doc) {
...
}
function Load() {
...
}

~~~

**Comment by a14oscna** [comment]
Agreed, most if not all functions should in some way be described so that any student regardless of skill cant comprehend its purpose, keep that in mind while writing the comments. Note, always follow the code standard even for writing proper comments so that the we uphold proper structure.
