### ISSUE TITLE
Marking with incorrect feedback

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#6917]
This is the scenario

1. One views a document (using the marking preview window) and writes some feedback, and sets a mark in that view.
2. One sets a mark by clicking directly in the marking view ... without previewing anything first.

The logical thing would be for the first mark be given with the feedback... which predictably is what happens.

However, the second mark, which is thought to be given without feedback, has the same feedback as the previous item.

Not good, especially if we are marking different students.

I am thinking this is a relatively simple issue of not clearing the feedback dialog after setting a mark for a student?

Unclear if this happes for ordinary exams and for feedback exams only.

**Comment by a17alian** [comment]
@HGustavs Have I understood this correctly that feedback for one assignment eg 
Biträkningsdugga 1 is 'saved' and remains the same for each student if not changed or updated in the feedback preview?
