### ISSUE TITLE
Use a transaction when running init_db during install

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#6922]
That way the database will not be "half created" when a error happens during creation of the tables

**Comment by HGustavs** [comment]
One other way to see it is that a half created database will help one to diagnose errors.

Perhaps as an option?

**Comment by a18kaswi** [comment]
> Perhaps as an option?

Customer asks this feature as an option. 

It will probably be most effective to do this in conjunction with adding option for additional testdata.

**Comment by a18kaswi** [comment]
For future reference: https://www.mysqltutorial.org/php-mysql-transaction/

**Comment by a18kaswi** [comment]
public PDO::beginTransaction ( void ) : bool
Turns off autocommit mode. While autocommit mode is turned off, changes made to the database via the PDO object instance are not committed until you end the transaction by calling PDO::commit(). Calling PDO::rollBack() will roll back all changes to the database and return the connection to autocommit mode.
