### ISSUE TITLE
Changing font size will in not make any difference (codeviewer). 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6925]
When trying to change the font size (cogwheel) in codeviewer nothing will really happen. The text size will still remain the same no matter what. 

![image](https://user-images.githubusercontent.com/49199285/57604597-d7d8cd80-7564-11e9-8151-1c72f379eb3e.png)

**Comment by a17alevu** [comment]
Also the text does not have a bold text (only the stars).

**Comment by a17maxsj** [comment]
Fixed! https://github.com/HGustavs/LenaSYS/pull/6932
