### ISSUE TITLE
Fileed: Sorting after size does not work properly

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#6930]
When sorting after size in the fileed view, the largest number ends up on top which is not always desired. 
Example: 
![image](https://user-images.githubusercontent.com/37799006/57607754-0f974380-756c-11e9-866d-31f458d55ee8.png)

**Comment by HGustavs** [comment]
Up or down.

Unclear if this is a sortabletable error or a local view error.

I was hoping this would be handled automatically by the default sorting in sortabletable.

We should not need to implement this as a special case... if sortable does not do this by default there is an error in the default sorting function(s)....

**Comment by a17ludca** [comment]
I think this issue relates to #6557 since in both cases the sorting only takes the first number into account. Solving one of these might solve both. Do you agree that they might be related? @HGustavs

**Comment by b17timjo** [comment]
The issue with the default sorting is that it treats the cell contents as a string, hence e.g. "12 kb" would be less than "123 bytes", which is of course not correct in terms of file size.

**Comment by HGustavs** [comment]
I would do it the other way around....

I would have a generic sorting function that sorts

12754 and  123 numerically

and I would then have a column specific rendering function that renders 12754 as "12kb" and 123 as "123"

Now I assume we have the oposite, a generic sorting and generic rendering function that renders and sorts both?

**Comment by HGustavs** [comment]
...If the problem lies in the database, and the database stores the number 12754 as 12kb ... then we have a bug in the database... which cannot be fixed due to refactoring.

In that case we need a specific function that turns 12kb to 12 000 and then does normal sorting ...

**Comment by a17ludca** [comment]
I think I managed to fix this, I don't think the problem came from the database but rather that when sorting, two strings containing the information was compared and when sorting letters, only the first character matters. This does obviously not apply for numbers and I managed to work around that and fix this.

**Comment by b17timjo** [comment]
The current default sort `newCompare`
https://github.com/HGustavs/LenaSYS/blob/906c329774cd88fec12dfc927955e12f4e2cdf33/Shared/SortableTableLibrary/sortableTable.js#L722
has a large number of special cases for particular columns in particular tables from particular pages. If none of these match, it will then default to "compare the entire cell contents as strings containing Swedish text"

Example excerpts:
https://github.com/HGustavs/LenaSYS/blob/906c329774cd88fec12dfc927955e12f4e2cdf33/Shared/SortableTableLibrary/sortableTable.js#L729

https://github.com/HGustavs/LenaSYS/blob/906c329774cd88fec12dfc927955e12f4e2cdf33/Shared/SortableTableLibrary/sortableTable.js#L768

https://github.com/HGustavs/LenaSYS/blob/906c329774cd88fec12dfc927955e12f4e2cdf33/Shared/SortableTableLibrary/sortableTable.js#L811

https://github.com/HGustavs/LenaSYS/blob/906c329774cd88fec12dfc927955e12f4e2cdf33/Shared/SortableTableLibrary/sortableTable.js#L824-L828
