### ISSUE TITLE
Random string in contribution

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#6931]
![image](https://user-images.githubusercontent.com/49199285/57608092-a6640000-756c-11e9-8fc5-ef1e9cb129de.png)

Random string under the table.

**Comment by HGustavs** [comment]
Does not happen in the running or old system.

**Comment by a17poner** [comment]
This came when the sortableTable was added at the bottom of contribution (the one that shows timesheet) i believe. At least the function that adds the sortableTable was what causes it.
