### ISSUE TITLE
Remove SSN option in filtering

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#6934]
The option to select SSN when hovering over desc/asc filter is still there. It does not seem to work, but since SSN has been removed from resulted  this option should be removed as well. 

![image](https://user-images.githubusercontent.com/37792256/57608994-4d956700-756e-11e9-9ed0-4ba15b4c82e3.png)

**Comment by HGustavs** [comment]
Searching for ssn could be a good idea.... at least in the result editor as it is more exact than searching for names (that may change over the life of a person, but ssn not...)

In the access editor it is not necessary.

**Comment by a17ludca** [comment]
Why would you want to search for ssn though? Wouldn't searching for the id(a17xxxxx) be more appropriate to search for since that ensures unique results without using personal information?

**Comment by HGustavs** [comment]
In some cases we only have the ssn and we dont know which name the person has.

I filter/sorting option for that would be useful.

**Comment by a17alian** [comment]
The ssn info has been added back to resulted in pull request #7212, not sure this is a relevant issue anymore

**Comment by b17nicsv** [comment]
Yepp. Closing this issue.
