### ISSUE TITLE
LadExport in resulted doesn't include SSN - needs redesign

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#6937]
![image](https://user-images.githubusercontent.com/37792321/57610612-71a67780-7571-11e9-9a39-59732584a2dc.png)

The export function in resulted is currently incomplete, with no ssn included. This is because including it with the export's current functionality would be a breach of GDPR.

However, in order to make it fully functional again, and not be against GDPR, it would need to be redesigned.

**Comment by HGustavs** [comment]
We only need to hide it visually, not completely from the view.

Did we not previously have a version that did not show the ssn but it was present in the data? This is how we want it.

We want to hide SSN from anyone getting an accidental glance at the screen, anyone using the system as a teacher has rights to veiw/use the personal data, but anyone that is not a teacher should not be able view that information by accident.

So, exporting from the table is quite ok, just put that column back as it was previously but hide it from the view.
