### ISSUE TITLE
FileEd: Clicking on filename causes error

### ISSUE THREAD

**Issue by a17adasy** [HGustavs/LenaSYS#6938]
When clicking on a filename in the fileed view the console shows a href null error. I assume the filenames are supposed to be clickable to show them in either a dialog or on another page.

**Comment by HGustavs** [comment]
I am thinking downloads or previews depending on file type.

**Comment by a17adasy** [comment]
Issue was nearly fixed, except some webserver issues. Pull-request link for next years students: https://github.com/HGustavs/LenaSYS/pull/7217

**Comment by a17towan** [comment]
The webbserver issues should have been fixed this year by allowing the user the rights to upload files. This was done with the commands:

sudo chown -R www-data *name-of-branch*
sudo chgrp -R www-data *name-of-branch*

And by running the installer in install.php one more time in the branch folder on the webbserver.
