### ISSUE TITLE
Consistently in clicked buttons in diagram

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#6945]
We have to have consistent behavior when clicking buttons in the toolbar. For example, at the moment we can create multiple Er-entities without clicking the button again. But if we draw lines we have to click the button "draw-line" again to draw a second line.

We can either make it click the button each time we create an object or we toggle it off when done creating.

What's your view @HGustavs & @a14oscna on this?

**Comment by a17vikab** [comment]
This issue already exists, #6879.
