### ISSUE TITLE
Codeviewer: possilbe to choose files that don't match the chosen kind.

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6951]
When editing content in codeviewer it possible to choose files that don't match the chosen kind.  
Here is a image where the kind is "code" and the file is a pdf.. 
![image](https://user-images.githubusercontent.com/49194898/57617035-0c0db780-7580-11e9-95de-9fe09b2adb8f.png)

If you save this error will show up:
![image](https://user-images.githubusercontent.com/49194898/57617101-38293880-7580-11e9-8e4e-9e9d49ad44c7.png)

I think the problem is that it tries to read the uploaded file as it was a php/html/js file. We should add some kind of limitation that only makes it possible to select appropriate files for a the selected kind.

**Comment by HGustavs** [comment]
Not obvious what should happen here... in detail....

If we chose type document, it should either be a pdf, md or html?
Code should support js html c cpp sl rib glsl etc.

Are there any other kinds of files that can be either document or code?

* If we select html file it could either be code or document but if we choose glsl it could only be code.
* If we choose glsl and code but change either the file to pdf or the type to description the interface should show an alert.

**Comment by b16johso** [comment]
I created arrays for storing the allowed file extensions for each view (code, document, preview), which makes it very easy to add and remove file extensions.

**Comment by a18filkr** [comment]
Already fixed, it is not possible to choose files that are not the allowed type.
Closing
