### ISSUE TITLE
Codeviewer. Edit example is bugged. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6952]
When you try to edit example inside codeviewer it is not possible to have spaces in the in the "Imported words" field. If you add a string with a space it is not possible to press the "+" button, but if you remove it works fine. 
String with space:
![image](https://user-images.githubusercontent.com/49194898/57617461-285e2400-7581-11e9-9ed7-ebd4c53c058c.png)
String without spaces:
![image](https://user-images.githubusercontent.com/49194898/57617557-5cd1e000-7581-11e9-98e3-80be719e0f32.png)

**Comment by HGustavs** [comment]
I think this is as intended as the tokenizer processes everything word-by-word...  a word with spaces could never be detected IMHO.

**Comment by a16joare** [comment]
Ok, then we should add somekind of notification that tells the user that it is not possible to have spaces?

**Comment by a17alevu** [comment]
Yes, that sounds good @a16joare
