### ISSUE TITLE
Codeviewer: Still left in "edit example" mode when save is pressed. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#6954]
When you edit example and press save the screen stays darkened and not goes back to the orignal color. 
Here is before you press the save button:
![image](https://user-images.githubusercontent.com/49194898/57617914-3b252880-7582-11e9-8af5-9319e8444dac.png)

Here is after you press the save button:
![image](https://user-images.githubusercontent.com/49194898/57617879-1cbf2d00-7582-11e9-96ef-89726a75821d.png)

The screen stays darkened and if you press escape it will disappear but if you try to access the "edit example" again the screen will just be darker and the edit example window will not appear until you refresh the page.

**Comment by b17annni** [comment]
I don't get this when try to save. However I get..
![image](https://user-images.githubusercontent.com/37792766/57620090-07e59800-7588-11e9-80d3-06f375e5fd84.png)
Witch seems to be purely cosmetic.

**Comment by a16joare** [comment]
Yeah that is also an issue.. You get this message when you press the "Edit content" cogwheel.. The problem in this issue occurs when you press the "Edit Example" (the cogwheel at the top). 
![image](https://user-images.githubusercontent.com/49194898/57679247-1f299180-762b-11e9-8ca7-46dd6966ac3e.png)

**Comment by a17alevu** [comment]
This is solved in another issue, #6998. @a17andby solved this issue. Closing this.
