### ISSUE TITLE
Change cursor on ER and UML options

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#6964]
When you hover over ER and UML in the drop down menu, the cursor should change from the arrow to the finger pointer, so the user knows it is clickable.

**Comment by a17jonro** [comment]
It looks like this has already been solved in another issue?
![56](https://user-images.githubusercontent.com/49195133/58006613-c190bb80-7ae8-11e9-99a1-ecac7d18aee1.png)

**Comment by a17vikab** [comment]
This is fixed in another issue.
