### ISSUE TITLE
Pressing escape in fileed shows error in console

### ISSUE THREAD

**Issue by a17adasy** [HGustavs/LenaSYS#6965]
this error is shown:
![image](https://user-images.githubusercontent.com/37799016/57620747-fe5d2f80-7589-11e9-8cec-40ee8df6108f.png)

**Comment by a17ludca** [comment]
This also occurs in resulted, duggaed and accessed

**Comment by b17nicsv** [comment]
I can't replicate this. It seems to be working on the weekly grupp B branch.

**Comment by b17nicsv** [comment]
Nevermind I was mistaken!
