### ISSUE TITLE
Codeviewer - File Download/Upload button doesn't do anything

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#6966]
Nothing happen when you click the File Download/Upload button. 
![Screenshot from 2019-05-13 14-19-21](https://user-images.githubusercontent.com/49235724/57620794-1f258500-758a-11e9-90fc-9e60b97f9622.png)

![Screenshot from 2019-05-13 14-18-06](https://user-images.githubusercontent.com/49235724/57620740-f8ffe500-7589-11e9-8c9c-4e7308f3ad6e.png)

**Comment by a17alevu** [comment]
#6958 Is related to this issue.

**Comment by a17alevu** [comment]
This is already solved. Closing.
