### ISSUE TITLE
You have to press esc twice to completely close the file editor window in fileedit.php 

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#6969]
At the moment you have to press esc once to close the window, and then again to close the black overlay:
![gif2](https://user-images.githubusercontent.com/37834592/57621041-bdb1e600-758a-11e9-9a86-ed508ea42cb8.gif)

**Comment by HGustavs** [comment]
This seems like a small bug.

**Comment by a17ludca** [comment]
This was fixed in this PR #7088

**Comment by a17pongo** [comment]
@b17nicsv this issue can be closed
