### ISSUE TITLE
Codeviewer: Add documentation

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6971]
Codeviewer could use some better documentation to make it easier to work with

**Comment by a17andby** [comment]
Documentation for who? We developers or for those who use Codeviewer?

**Comment by b16johso** [comment]
Developers

**Comment by a17joaap** [comment]
What further documentation do you have in mind? It seems pretty well commented already.

**Comment by b16johso** [comment]
codeviewerService.php could use some more comments imo
