### ISSUE TITLE
Problem with draw text

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#6972]
When you select draw text and try to make a large text box, it does not keep that size. It always go back to the same size no matter how you draw.

![Untitled3](https://user-images.githubusercontent.com/37792271/57621311-619b9180-758b-11e9-9b2a-f8a2978629e0.png)
![Capture18](https://user-images.githubusercontent.com/37792271/57621315-63fdeb80-758b-11e9-9295-a559e26c16bd.PNG)

**Comment by a17vikab** [comment]
There is another issue regarding the same problem. The work will be done in #7027 and therefore this issue will be closed.
