### ISSUE TITLE
Lines are not connected to copied objects

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6977]
diagram.js
Related to #5040 
copy issue megathread: #7121
When objects are copied, the lines which connect them seem to lose their connections and become individual objects which are movable by clicking and draging the endpoints.

Note that in the code in the function keyDownHandler() there is an if statement with the following argument: 'cloneTempArray[i].symbolkind != symbolKind.line && cloneTempArray[i].symbolkind != symbolKind.umlLine'. 

Simply remove '!= symbolKind.line && cloneTempArray[i].symbolkind != symbolKind.umlLine' to enable the lines to be copied

**Comment by a16tobfr** [comment]
@a17okaoz @HGustavs 
We have been working on this issue for a while now and are not able to come up with a working solution. 
A new symbol is made when the copy and the symbolkind are passed as a parameter.
The attributes are copied from the original to the copy by using jQuery.extend(true, {}, source).

Everything works right now except for the lines, which are not maintaining the connection information from the original.

The arrays in diagram_objects.js does not seem to be copied properly:
    this.connectorTop = [];
    this.connectorBottom = [];
    this.connectorLeft = [];
    this.connectorRight = [];
We get a complaint that connector.sort is not a function (which is **not** something we directly try to copy).

We have looked in the mouseup/downevt functions in diagram.js to try and figure out how lines are drawn and connected from the beginning.

Any advice on how to proceed with this issue would be appreciated.

**Comment by a17okaoz** [comment]
That the copy functionality can do now is that it can copy attributes, entities, relations, text boxes, and lines.  The copy function can´t either copy relations between entities, relations, and attributes. The line that connects them is copied but not attached to none of the objects. You can see that in the GIF above. It can´t copy UML boxes and free draw.

**Comment by a18jonpe** [comment]
Adding 
```
clone.connectorLeft = jQuery.extend(true, {}, symbol.connectorLeft);
clone.connectorRight = jQuery.extend(true, {}, symbol.connectorRight);
clone.connectorTop = jQuery.extend(true, {}, symbol.connectorTop);
```
to the copySymbol function in diagram.js gives the error connector.sort is not a function in diagram_objects.js, which I have a hard time understanding since the error is not even in the same file in which the change is made.

**Comment by a18jonpe** [comment]
Like previously mentioned, the connectorLeft etc. variables do not copy but are empty in copySymbol. I'm not sure how this happens, and I'm having quite a hard time understanding how the connectors and lines are created and stored in general.
