### ISSUE TITLE
Create a SVG-icon for the "One pane" Code viewer template. 

### ISSUE THREAD

**Issue by a17robes** [HGustavs/LenaSYS#6978]
A new template was added to the template list in issue #1779 . As you can see in the picture below it now has the wrong SVG-icon. We need to create a new one for this single pane template. 

![image](https://user-images.githubusercontent.com/38004435/57625627-8811fa80-7594-11e9-94e8-aba902971b31.png)

**Comment by b16johso** [comment]
![image](https://user-images.githubusercontent.com/37793460/57678541-b68de500-7629-11e9-9cd3-29819a7411cb.png)
