### ISSUE TITLE
CodeViewer: Alert shows when saving a new file to an example

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6980]
It still works, but we shouldn't get this alert.

![giphy](https://user-images.githubusercontent.com/37792198/57625753-c90a0f00-7594-11e9-84e2-87f16ac37296.gif)

**Comment by a16lisri** [comment]
This seems to be a global issue. There is a separate issue for this: https://github.com/HGustavs/LenaSYS/issues/2358. Closing this.

**Comment by a17alevu** [comment]
Is this not already an issue? I might be wrong.
