### ISSUE TITLE
ER and UML mode under the view tab are not highlighted when hovered

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6983]
<img width="244" alt="ERUMLNOTHIGHLIGHTED" src="https://user-images.githubusercontent.com/49199690/57626452-39fdf680-7596-11e9-9979-48f0e0b58bf0.png">
The ER and UML buttons are no longer highlighted. Should be highlighted to indicate that it is possible to click them.

**Comment by a16tobfr** [comment]
#6964 also touches this problem but that issue covers the fact that the cursor does not change when hovering.

**Comment by a17vikab** [comment]
The work will continue on #6964.
