### ISSUE TITLE
Codeviewer: Foreign key constraint fail when selecting new example template

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#6989]
Getting this error when trying to switch to the new template added in https://github.com/HGustavs/LenaSYS/pull/6984
![foreignkey](https://user-images.githubusercontent.com/37792198/57628907-20ab7900-759b-11e9-825e-ccfb22054afd.PNG)

**Comment by a17maxsj** [comment]
This is fixed by adding the lines to the DB, guessing the rest are added by the install script? Now working on the test server.

**Comment by a17maxsj** [comment]
Solved
