### ISSUE TITLE
Display Virtual A4 - toolbar issues

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6990]
<img width="234" alt="displayvirtual14" src="https://user-images.githubusercontent.com/49199690/57634730-32464e00-75a6-11e9-98d6-cc44404a2d98.png">

1st. It is possible to select the different options even if 'Display virtual A4' has not been pressed.

2nd. Pressing Toggle A4 holes changes the appearance of 'A4 Holes Right' as if the 'Display virtual A4' button had been pressed.

3rd. The toggles are only highlighted when disabled. Should be highlighted even when the 'Display virtual A4' button has been pressed (or when enabled) to indicate that they are selectable in a more distinct manner (related to #6983 ).

[ 4th. If we are supposed to be able to toggle the buttons even when 'Display virtual A4' has not been pressed. Toggle A4 Orientation can only select one mode (as shown in the picture). ]

**Comment by a17vikab** [comment]
Related to #6879?

**Comment by a17vikab** [comment]
this looks like a duplicate issue of #6727 but adds a lot of useful insights of the problem.

**Comment by a17vikab** [comment]
This is now solved.
