### ISSUE TITLE
Pressing display all tools under the view tab (while it is disabled) forces you out of the menu

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6991]
<img width="226" alt="displayAllTools" src="https://user-images.githubusercontent.com/49199690/57636009-9ec24c80-75a8-11e9-8cd5-809dd872f66f.png">
Pressing this while its grayed out (disabled) should not give any response. Right now, when you press it, the button closes the menu. This should not happen since it is not a 'close menue' button.

Fix so that the button is not responsive while it is being disabled.

**Comment by a17drama** [comment]
Reopening because of a hick up while doing a merge.

**Comment by a14oscna** [comment]
Yes, good idea.
