### ISSUE TITLE
Change create line shortcut [suggestion]

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6992]
This is a suggestion and should probably be discussed with the group leader / issue manager before implementing this.

Change shortcut keys for creating lines from [shift + L] to [shift + S]
Why?
Having all the shortcuts on one side of the keyboard makes the application more satisfying to use. This makes you able to never move your right hand from the mouse since all of the most common shortcuts are placed on the left side of the keyboard.
Why S?
It is close and easy to access. However, if you find a better suggestion for a shortcut that is on the left side of the keyboard and easy to access with your left hand, that is fine since [shift + S] could instead be used for the 'save' functionality in the future.

**Comment by a17vikab** [comment]
Closing this issue because the existing shortcut is fine.
