### ISSUE TITLE
In the Help tab in the toolbar, add a button that displays all the shortcuts for the user

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6994]
<img width="256" alt="shortcuts" src="https://user-images.githubusercontent.com/49199690/57637850-b1d71b80-75ac-11e9-8635-423f5c63de31.png">
Adding this button would be good.

By pressing it you should see a window/dialog that displays all the shortcuts so the user can see them all in one place.

**Comment by a14oscna** [comment]
After a short discussion we decided not to implement this feature as there is already good coverage of the hotkeys.

**Comment by a14oscna** [comment]
This feature could however be useful in future development if there are a lot more "hidden" shortcuts that the user should be aware of. Just check the diagram.php file for the other menu options and mimic that code to create a new option.

**Comment by a17robhe** [comment]
This issue will be closed for now, if https://github.com/HGustavs/LenaSYS/issues/7003 get implemented then the help dialog for the shortcuts should be located there.
