### ISSUE TITLE
Add a toggle for enabling/disabling shortcuts 

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#6995]
<img width="214" alt="enableOrDisable" src="https://user-images.githubusercontent.com/49199690/57638516-36766980-75ae-11e9-9eaf-d4e81932d45e.png">

Shortcuts may interfere with shortcuts from external software and may, in that case, become an annoyance. To fix this, add a toggle for enabling or disabling all the shortcuts under the edit tab in the top toolbar.

**Comment by b18simla** [comment]
Changing the text to "Disable keyboard shortcuts" since a checkbox appears after clicking it. Rather than having the user guess if the checkbox means enabled/disabled, I think this makes more sense and should be less confusing.
