### ISSUE TITLE
Daily Minutes: Mobile view broken

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#6997]
Daily Minutes is completely broken in mobile view
![image](https://user-images.githubusercontent.com/37793460/57679127-deca1380-762a-11e9-9aa0-6db14ca334ff.png)

**Comment by a17joaap** [comment]
It loads when you refresh the page

**Comment by b16johso** [comment]
Related issue https://github.com/HGustavs/LenaSYS/issues/7008
