### ISSUE TITLE
Feature: easily copy code in codeviewer

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#7000]
A feature for codeviwer woudl be to make it easier to copy the contents of a code file. Say a user wants to copy the code to use in a project or to play around with outside of LenaSys. Either making ctrl + a only target the selected document or adding a copy to clipboard button to the title.

**Comment by a17alevu** [comment]
This issue is the same as #7013 ?

**Comment by a17andby** [comment]
> This issue is the same as #7013 ?

Yes, you can close this one.
