### ISSUE TITLE
Daily Minutes: Mobile friendly form

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#7008]
Make the Daily Minutes form mobile friendly. My suggestion: align the input fields vertically inside collapsible containers for each row/activity.

Mockup:
![mobileform](https://user-images.githubusercontent.com/37793460/57687578-f958b880-763b-11e9-972b-78598c53c444.gif)

**Comment by a17alevu** [comment]
This look good! I like this.

**Comment by HGustavs** [comment]
I think we only need to be able to add new entries, not edit old ones, to remove the risk of mis-clicking old entries.

**Comment by HGustavs** [comment]
to clarify: We see old issues as a non-editable tabel but the latest entry can be changed, and when an entry has been saved it cannot be deleted.

This way we can rectify minor errors but anything that has been written previously will remain, without risk of breaking old daily minutes entries.

How can I test the current interface?

**Comment by a17fellu** [comment]
We allready have a mobile form added to daily-minutes. Isnt it more logical to just update that one. It works pretty much the same as the one in the mockup. And we have spent a lot of time to both create it and style it. If there was any thoughts that the newe mobile friendly form wasn't good enough that should have been brought up before it got added

**Comment by adajoh** [comment]
I like the mockup, very clear what your vision is

**Comment by a17fellu** [comment]
**This should get closed since this pull request below fixes this without rebuilding the form:**
#7030
