### ISSUE TITLE
Codeviewer: Add copy code button and/or Ctrl-A

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#7013]
Make it possible to select all the code in a code view with Ctrl-A and/or add a copy to clipboard button.

**Comment by b16johso** [comment]
Created an icon for copying to clipboard
![image](https://user-images.githubusercontent.com/37793460/57695577-eac7cc80-764e-11e9-85ae-7bb396f48813.png)

**Comment by a17alevu** [comment]
This looks nice =)

**Comment by a17fellu** [comment]
This is a good addition and the icon looks like what the functionality represents

**Comment by a17maxsj** [comment]
good
