### ISSUE TITLE
Scale zoom-bar when minimizing window

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#7015]
Make the **zoom-bar** when minimizing the window to make it available to work at smaller windows, screens or devices. It should always be visible regardless of the size of the window/screen.

<img width="503" alt="Skärmavbild 2019-05-14 kl  11 02 00" src="https://user-images.githubusercontent.com/37792795/57688396-9a943e80-763d-11e9-8b93-3bdfe5a49a6c.png">

Related to: #7017

**Comment by HGustavs** [comment]
I view this as two separate issues, the coordinate bar and the zoom bar.

I think it is safe to only show coordinate bar in debug mode?

Do normal users really need the coordinates bar?

**Comment by a14oscna** [comment]
You are right, I do not think the standard user benefits from the coordinate bar. We will write an issue to move it into debug mode.
