### ISSUE TITLE
Make cordinates-bar scale in developer mode

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#7017]
Make the **coordinates-bar** scale when minimizing the window to make it available to work at smaller windows, screens or devices in developer mode. It should always be visible regardless of the size of the window/screen.

<img width="503" alt="Skärmavbild 2019-05-14 kl  11 02 00" src="https://user-images.githubusercontent.com/37792795/57688396-9a943e80-763d-11e9-8b93-3bdfe5a49a6c.png">

Related to: #7015

**Comment by HGustavs** [comment]
I would write "hide" in title of issue to clarify
