### ISSUE TITLE
Web page title elements

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7019]
The title element on all pages should reflect which service it is from, so we can see what service we are looking at in the tab heading.

~~~
<title>Service name</title>
~~~

currently for example the diagramming component says "Section editor"... do any other service pages have the same issue?

It is a minor inconvenience but an inconvenience still.

**Comment by a17andby** [comment]
Here is one https://github.com/HGustavs/LenaSYS/issues/6808

**Comment by a17poner** [comment]
Labelling this for all groups so each group can make seperate issues for their respective areas/microservices that have the wrong title.

**Comment by a17andby** [comment]
| Page |Title | Comment |
| :---         |     :---:      |          ---: |
| sectioned.php   | :heavy_check_mark:     |   |
|resulted.php | :heavy_check_mark: | |
|duggaed.php | :x:  | https://github.com/HGustavs/LenaSYS/issues/6808 |
|fileed.php|:heavy_check_mark:  ||
|accessed.php | :heavy_check_mark: | ||
|showDugga.php | :heavy_check_mark: | The title is just "Dugga Viewer". Maybe we could improve it? |

**Comment by b17carma** [comment]
How would you feel about calling the showDugga title something like "Dugga viewer - DuggaName", or even "Dugga viewer - DuggaName - CourseName - CourseID" though it might be a bit long :p?

**Comment by a17andby** [comment]
I think that ""Dugga viewer - DuggaName - CourseName - CourseID" would be bit long ^^ 

But "DuggaName - Dugga viewer" or "Dugga viewer - DuggaName" should be fine I think

**Comment by a17poner** [comment]
I'm pretty sure every page that relates to groupC2019 has been merged with a title fix now. Deallocating this but leaving it open to have the other groups take a look at it.

**Comment by a17vikab** [comment]
Group A does not have this problem. This issue can be closed if the other groups have solved everything regarding this.

**Comment by b17nicsv** [comment]
Grupp B doesn't have this problem either. Closing this then. 👍

**Comment by HGustavs** [comment]
Good work looking into this.
