### ISSUE TITLE
After refreshing page, undo/redo does no longer work for objects drawn before the refresh

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7022]
When you have some objects drawn on the canvas and then refreshes the page, the undo, and redo functionality is no longer working.

**Comment by a17alfcl** [comment]
This should be resolved in issue #6719 which is already merged

**Comment by c17matjo** [comment]
Undo/redo after refresh does seem to work on the newest branch, like a17alfcl said. This issue can probably be closed

**Comment by a17vikab** [comment]
closing this issue because it is solved.
