### ISSUE TITLE
Enter edit text as soon as you have drawn a text box

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7025]
After having drawn a Textbox, you should get to a state where you directly can edit the text. Now the text box is drawn and then you have to double click it in order to edit the text.
![editText](https://user-images.githubusercontent.com/49199690/57692720-c9171700-7647-11e9-9d76-ff3d1082dc00.JPG)

**Comment by a17jonro** [comment]
If an issue is redundant it should be removed? @a17vikab

**Comment by a17vikab** [comment]
> If an issue is redundant it should be removed? @a17vikab

You are right, this feature should not exist according to the workflow that the customer wants.
