### ISSUE TITLE
'Draw Text' box size is always default size

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7027]
The draw text box should most likely be sized to the square drawn by the user. As of now, it is always set to a default size.
<img width="170" alt="drawingTextBoxSize" src="https://user-images.githubusercontent.com/49199690/57693020-81dd5600-7648-11e9-92bc-bc4754848121.png">
Always set to this size:
<img width="89" alt="textbox" src="https://user-images.githubusercontent.com/49199690/57693159-d41e7700-7648-11e9-98d8-6d7aa793c57f.png">

**Comment by a17drama** [comment]
@a16tobfr What is the point of resizing the text box? We have no automatic wrap text so we can draw any use from custom sized text boxes. Text boxes are resized automatically to surround the text. Shouldn't this be enough?

**Comment by a16tobfr** [comment]
1) If we want the indicator square to fill any functionality at all, the size that the user has decided should be the limit for when text wraps. This gives the user some additional ability to decide how the text should be represented.

2) The other alternative is to remove the indicator square entirely and simply make the text boxes appear by clicking on the canvas when that button has been selected.

Right now we have a mix of the two, kind of. The indicator square brings nothing to the functionality of the text boxes, and if we want to keep it this way, we will have to change how text boxes work. 

Otherwise, as stated previously in this comment, remove the indicator square and simple make text boxes appear with their default size when the user clicks on the canvas.

If we go for the first alternative, I suppose we will have to leave this issue for the students of the next year to implement this functionality.

@a14oscna, @a17vikab will have to decide what road to take on this one.

**Comment by a14oscna** [comment]
After mutual agreement the decision is to remove the indicator box. You simply click to create a new textbox, which only adjusts as the user inputs text.
