### ISSUE TITLE
Error messages at SectionED: <rect> negative value

### ISSUE THREAD

**Issue by c17alepe** [HGustavs/LenaSYS#7028]
![image](https://user-images.githubusercontent.com/38323901/57693515-b867a080-7649-11e9-8fc3-e3bd29f10321.png)

This error message is in the current branch. Might only be at the course Webbutveckling - datorgrafik IT120G HT15. There has to be something there triggering it.

**Comment by HGustavs** [comment]
Is in the swimlanes?

Which part of swimlanes is broken in this course?

Interesting to document why this happens, and see if it is a general problem.

I would classify this as a bug, a minor one, but a bug.

**Comment by c17julka** [comment]
I fiddled with swimlaneSVG while fixing #6836. However, I checked an earlier branch and the issue seemed to have appeared before my fiddling. So that issue does not seem to be the course of this. It seems to have been around for at least a little while.

**Comment by HGustavs** [comment]
Is it in all courses or just that course?

Im thinking perhaps some special case, where for example tests are after the course ends or before the course begins?

The tests, moments, results and course start/end weeks all interrelate in the creation of swimlanes.

**Comment by HGustavs** [comment]
Perhaps we draw a box from week 0 to week -10 if the test is before the course starts.

**Comment by c17alepe** [comment]
Its only on one course right now, but its the course where we do the most testing. So it is likely that it is under certain conditions, that this will turn up

**Comment by c17julka** [comment]
It seems to happen to tests which have a deadline during 2017 / 2018, which means the tests in the past. However, the ones further in the past, during 2015, instead have an extremely big width.

**Comment by c17julka** [comment]
Another issue which might be related to this, is that some test which have been handed in do not have the yellow background.

An example if you look at Datorgrafik: 
Transformationsdugga 2 has a yellow background, which has a deadline in 2015.
Transformationsdugga 1 does not have a yellow background, with a deadline in 2017.
Both were handed in on May 2019.

This must be due to the translation of the object in its x-axis.
