### ISSUE TITLE
Line tool cursor icon changes when hovering over points

### ISSUE THREAD

**Issue by b17albbe** [HGustavs/LenaSYS#7029]
Related to issue https://github.com/HGustavs/LenaSYS/issues/6853.
The line tool is supposed to stay with the pointer icon at all times, even on hover. However, if you hover over any point, you can get the move icon instead. Here's a gif showcasing what i mean:
![df4c1cbd13abd92be46034e268041113](https://user-images.githubusercontent.com/38030926/57693666-0f6d7580-764a-11e9-8f4c-220e4763bcb5.gif)

**Comment by HGustavs** [comment]
A minor issue imho... but it can be annoying... so worthwhile fixing if there is manpower available.
