### ISSUE TITLE
UML objects can be seen through ER objects when stacked upon each other

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7037]
UML objects can be seen through ER objects when stacked upon each other.
One of them should hide the other one.

![umlObjectstransparent](https://user-images.githubusercontent.com/49199690/57696229-8e65ac80-7650-11e9-988b-53f879002bfa.JPG)

Can it be fixed by simply manipulating the z-index?

**Comment by HGustavs** [comment]
The relationship symbol needs a background even if no background color has been selected.

**Comment by a17vikab** [comment]
This issue is redundant, the problem is already worked on in #6960.
