### ISSUE TITLE
Resulted - ladexport textarea is not locked to box

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#7038]
![Screenshot from 2019-05-14 14-04-33](https://user-images.githubusercontent.com/37792222/57696566-4c893600-7651-11e9-84f8-a6e8686c22c3.png)

It is possible to drag the text area horizontally how little or how much you want, this should be locked to a fixed sized and lock the option to resize the field.

**Comment by HGustavs** [comment]
Yes this is very useful.

**Comment by b17nicsv** [comment]
The white box inside shouldn't be resizable but the whole window should be.

**Comment by a17pongo** [comment]
@b17nicsv I disagree, I think our customer does not want a resize able textfield. the textarea is scrollable and if the text in the area is too long they will jump to the next line

**Comment by b17nicsv** [comment]
Would there be a difference except from looks? If the textarea is fixed to the textfield and resizing the textfield it would be indirectly resizing the textarea, instead of resizing only the textarea. It would also not look as silly as the picture above. Correct me if I'm wrong.

**Comment by a17pongo** [comment]
the textarea(or field, gonna start using one word now) should have the property "noresize". This will prevent being able to doing querky things like the picture above. And no other resizing should take place by the fix a17alian has submitted. Resizing this popup in any other way should not be necessary

**Comment by b17nicsv** [comment]
I might have misunderstood HGustavs then. What I interpret was that it were useful having it resizeable.

**Comment by b17nicsv** [comment]
What is the intended behaviour? @HGustavs

**Comment by a17pongo** [comment]
this issue can be closed, pr #7058 fixed this
