### ISSUE TITLE
Can not enter MoveAround mode when pressing space

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7039]
When pressing space while having an object selected in the toolbar, you can not enter move around till you have drawn an object, even when you deselect the object. Solution as of now (for the user) is to make some kind of action with the mouse and then you will be able to enter the moveAround mode again.

Pressing space should get you into moveAround mode even if an object is selected.
![moveAround](https://user-images.githubusercontent.com/49199690/57697666-11d4cd00-7654-11e9-91dd-468ab99ddf2c.JPG)
![toolbar](https://user-images.githubusercontent.com/49199690/57697652-0da8af80-7654-11e9-99b6-aebbe956b31e.JPG)

**Comment by a17vikab** [comment]
This seems to be fixed in another issue.
