### ISSUE TITLE
Having selected 'draw line' outputs an error message in the console log while hovering the canvas

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7043]
While hovering the canvas and having selected 'draw line' an error message is being outputted to the console.
<img width="352" alt="hoverWhileDrawLine" src="https://user-images.githubusercontent.com/49199690/57700232-d1784d80-7659-11e9-8981-72949a33563f.png">
Should probably fix so we can avoid outputting this error message to the console.

**Comment by HGustavs** [comment]
We should check of hoverObject exists before using it... should be trivial?

**Comment by a16tobfr** [comment]
This seems to have been fixed in some other issue. The problem does not seem to be present anymore.

**Comment by a17okaoz** [comment]
Have tested this issue for when the error message will appear in the console and the error message doesn't appear at all anymore. This issue seems to be fixed by some other issues

**Comment by a17vikab** [comment]
Seems to be fixed.
