### ISSUE TITLE
Preview-window title in Codeviewer needs change. 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#7046]
![image](https://user-images.githubusercontent.com/49199285/57700715-d093eb80-765a-11e9-91a9-07f521e77d93.png)
You can do as many new lines as you want, and it is ugly. 

![image](https://user-images.githubusercontent.com/49199285/57700825-020cb700-765b-11e9-9833-a7fa5a6c3b1a.png)
The text is under everything.

**Comment by a17alevu** [comment]
Note we had an issue about this that was solved, but it only fixed it for code-windows. The window in the picture is a review-window.

**Comment by HGustavs** [comment]
Changed title of issue.

**Comment by a17alevu** [comment]
#7001 related to this, which is closed.

**Comment by b16johso** [comment]
@HGustavs my suggestion is to remove the function all together and just use the Edit Content window to set the title instead.
![image](https://user-images.githubusercontent.com/37793460/57777276-cbe63a80-7721-11e9-8d56-352306ff0b5b.png)

**Comment by HGustavs** [comment]
Unclear where that title comes from, it is not the title given in the dialog above?

If one writes greger in the title above where does greger appear? Next to "Preview window" ?

**Comment by b16johso** [comment]
It replaces "Preview window"
