### ISSUE TITLE
Naming of text objects is wrong

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#7053]
When creating a text object it should start from 0 just as the other objects like attribute or relation etc do. Only time it does this now is when it's created first. In other cases it just gets the length of diagram array.

**Comment by HGustavs** [comment]
Are we talking about draw order or position or something else?

**Comment by a17drama** [comment]
![Capture](https://user-images.githubusercontent.com/46029340/57753443-7479a780-76ec-11e9-84c9-60f74026dfd9.PNG)
Sorry for being unclear. We had a few runs around this issue already and it's clear for us. If you check the picture the name of the first created text object doesn't end with 0 like it should. All other objects start from 0 and count up for each kind but the text was missed because we didn't have a button until now. It was created by a double click. This is an very easy fix.
