### ISSUE TITLE
Document codeviewer boxes

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#7063]
Currently to change and update the way boxes(in the templates) are added and the number of boxes you are required to change at least 3 different files (codeviewerService.php, templateX.css and codeviewer.js). This could use some sort of documentation since it is not immediatly obvious and could save someone time in the future if there needs to be another template added or a current template requires changing.

**Comment by HGustavs** [comment]
Back burner, but a very worthwhile task.

I really dont know exactly what needs to be changed... especially if one makes a new template that is not clearly a copy of an old template, with minor changes.

I suggest we add this in the same place as the code standard md file.

**Comment by a17fellu** [comment]
Created a documentation for this:
#7330

**Comment by a17poner** [comment]
Its been added as a new file, should this file be linked to from codestandard.md or the wiki or just have it be a file thats never referenced?

**Comment by a17fellu** [comment]
We could add it as a new page on the wiki

**Comment by a17poner** [comment]
Yeah, sounds good, can you create a seperate issue for it and self assign and add it? :)

**Comment by a17fellu** [comment]
Closing since it is now added to the Wiki
