### ISSUE TITLE
[FileEd] Adding a link to FileEd flashes code for a second

### ISSUE THREAD

**Issue by b17nicsv** [HGustavs/LenaSYS#7065]
While adding a link to a course, it flashes code for a very short time then goes back to the files. Make it so it doesn't flash the code and just stay where it is supposed to be.

To replicate:

Go to Webbutveckling - datorgrafik.
Go to Files
Add link
Add any link
Screen flash

**Comment by c17alepe** [comment]
I didnt manage to solve this issue, but from what ive gathered, this is what flashes: 
![image](https://user-images.githubusercontent.com/38323901/58098593-3394fd80-7bda-11e9-8252-2542cc6f6d85.png)

I believe its in the filerecieve.php that this happens
