### ISSUE TITLE
Clicking FAB button in sectioned results in error

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#7068]
![image](https://user-images.githubusercontent.com/37792321/57766803-54f07800-7708-11e9-9b32-e3725db720cd.png)
The fab btn is currently non-functional, only this error appears.

**Comment by a17andby** [comment]
As I mentioned in my issue (closed) the error also triggers when you are clicking on this button: 

![Screenshot from 2019-05-15 13-49-51](https://user-images.githubusercontent.com/49235724/57773455-588bfb00-7718-11e9-8fc0-6003a982d998.png)

**Comment by a17poner** [comment]
This issue seems to have been caused by this pr #6799 if its of any help to find a working solution :)
