### ISSUE TITLE
Cant click on item in hamburger nav

### ISSUE THREAD

**Issue by a17adasy** [HGustavs/LenaSYS#7082]
Clicking on a item in the hamburger doesnt do anything. The console shows a "cannot set property href to null" error.

![image](https://user-images.githubusercontent.com/37799016/57772528-e7e3df00-7715-11e9-916f-32709c2be36b.png)

Is in sectioned.

**Comment by a17alian** [comment]
This is a similar issue remaining form W19 merge, that was never fixed, see #6755. When fixing this issue, please refer to the old one so that closes too.
