### ISSUE TITLE
If developer mode is enabled and the page is refreshed the user should still be in developer mode

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#7089]
Issue #6933 solved a part of this issue so that when in developer mode the toolbar state is still in developer mode when refreshing the page. It would also be nice if the user stayed in developer mode for all the tools. For example seeing the center coordinates of an object and seeing the x's on the screen.

![image](https://user-images.githubusercontent.com/49199287/57772719-7a847e00-7716-11e9-8a56-3ec9fe463af7.png)
If developer mode is enabled and the page is refreshed by the user it should still show the things in the above picture.

**Comment by a17vikab** [comment]
We are going to get confirmation from @HGustavs on the next customer meeting about how this should work.

**Comment by a17vikab** [comment]
Solved.
