### ISSUE TITLE
Hamburger position when half shrunk broken again post merge

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#7090]
As with this issue: #6889
the hamburger when semi shrunk goes out of position. This time however it moves up and not down.

**Comment by a16hiwah** [comment]
can you show  the problem with a screenshot?

**Comment by a16hiwah** [comment]
this issue is same as  "Cant click on item in hamburger nav #7082", and has  been fixed by @a17alian

Hamburger menu navigation fixed #7124

**Comment by a17poner** [comment]
This was about it being positioned wrongly not about the broken links but looking at his pr it seems he fixed that as well as the broken links, guess we'll close this then 😄
