### ISSUE TITLE
Resulted filtering drop-down out of position

### ISSUE THREAD

**Issue by a17anter** [HGustavs/LenaSYS#7091]
After this weeks merge the filter drop-down is still out of position. When hovering from icon to drop-down a gap between them will close the drop-down.

**Comment by a17ludca** [comment]
Are you sure? Tried emptying cache in the browser? Reason for asking is that it works for me.

**Comment by a17anter** [comment]
Clearing cookies helped! Drop-down is still out of position though. Problem now is that it's overlapping the filter icon and should be moved down.

**Comment by a16hiwah** [comment]
@a17anter 
You show view the problem with a screenshot?

**Comment by a16hiwah** [comment]
@b17timjo this issue has been fixed by me!
 Resulted filtering drop-down out of position been fixed #7091 #7172
