### ISSUE TITLE
Pressing esc to close login box causes error

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7092]
![image](https://user-images.githubusercontent.com/37834592/57773020-4f4e5e80-7717-11e9-9f81-974a10f012af.png)

**Comment by b17carma** [comment]
Appears to show the error in courseed but not on other pages? (but it still doesn't work on other pages)

**Comment by a17andby** [comment]
Same error when you trying to close "Forgot password" window

![Screenshot from 2019-05-15 13-44-17](https://user-images.githubusercontent.com/49235724/57773148-9c323500-7717-11e9-9c64-acb03f927432.png)

**Comment by a17poner** [comment]
Same error when you try to close anything with escape in codeViewer

**Comment by a17joaap** [comment]
This error occurs everywhere but in sectioned, since there are no functions called closeSelect anywhere else.
