### ISSUE TITLE
Adding a hotkey to enter select mode

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#7096]
There might already be a hotkey for entering select mode that I don't know about, in that case I will remove the issue.

This would be good because if you are creating objects and then you want to select something, you don't have to go and click on the one already selected (or use the hotkey for the one selected) just to enter select mode. Instead we have a single hotkey that changes it to select mode, instead of making the user remember every hotkey to every object to disable them and that way go into select mode.

**Comment by a14oscna** [comment]
I will just close this issue as it has been decided to not implement this by the following reasoning:
Adding a hotkey would not be sufficient without adding a button as well. However we do not want to add another button for the default tool and therefore we shall not add any hotkey either. The default tool can always be accessed by de-selecting the currently selected tool.
