### ISSUE TITLE
login/logout are both green

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#7099]
![image](https://user-images.githubusercontent.com/37792766/57773257-e3202a80-7717-11e9-9aba-f74ada50b4dd.png)
![image](https://user-images.githubusercontent.com/37792766/57773291-f9c68180-7717-11e9-8344-d23f5bd19d20.png)

**Comment by b17annni** [comment]
Merged.

**Comment by a16lisri** [comment]
Pull request is merged. Closing this.
