### ISSUE TITLE
Possibly global: Transparancy on fab hover

### ISSUE THREAD

**Issue by a17robda** [HGustavs/LenaSYS#7103]
![fabhoverissue](https://user-images.githubusercontent.com/37792328/57773497-6f325200-7718-11e9-9fa1-4f4229e7cd11.png)
Text-boxes are transparant while hovering over FAB.

**Comment by a17andby** [comment]
I think that is a global problem on all FAB buttons. Could it be that the css changed for the labels?

**Comment by c17julka** [comment]
It could be an intentional styling change for the fab buttons?

**Comment by b17carma** [comment]
This was an intentional change made in https://github.com/HGustavs/LenaSYS/pull/7049

**Comment by a17robda** [comment]
Alright, closing this then.
