### ISSUE TITLE
Cookie OK-button is not aligned

### ISSUE THREAD

**Issue by a17oscno** [HGustavs/LenaSYS#7106]
The button is not aligned after the merge. Probably a style.css error due to a conflict.

![image](https://user-images.githubusercontent.com/49207814/57773729-fb447980-7718-11e9-9adf-a3a03b99a18b.png)

**Comment by a17anter** [comment]
Button has now been aligned and is in the center! Can be closed once the PR has been approved and merged.
![image](https://user-images.githubusercontent.com/49204317/57864921-fe189a80-77fc-11e9-9796-fcc59e766b4b.png)
