### ISSUE TITLE
Suggestion: Change header button colors to stand out a little more from the background

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7109]
Right now it looks like this:
![image](https://user-images.githubusercontent.com/37834592/57773961-8d4c8200-7719-11e9-8073-3021a2cb94f3.png)

I think using a different background color (don't have to be super different) for the buttons could be preferable to make them stand out a bit more?

**Comment by a17andby** [comment]
Or maybe a nice border on the buttons?
