### ISSUE TITLE
Display All Tools not greyed out when in normal mode

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7111]
Display all tools should be greyed out when not in developer mode.
<img width="230" alt="displayToolsNotGreyed" src="https://user-images.githubusercontent.com/49199690/57774290-6cd0f780-771a-11e9-8679-7757a19e4c46.png">

**Comment by a17jonro** [comment]
It looks like this has already been solved.
![42](https://user-images.githubusercontent.com/49195133/58007759-3cf36c80-7aeb-11e9-82e4-6f4ed4143280.png)

**Comment by a17vikab** [comment]
This seems to be fixed in another issue.
