### ISSUE TITLE
Using the top add button in sectioned.php doesn't work

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7114]
Button:
![image](https://user-images.githubusercontent.com/37834592/57774630-51b2b780-771b-11e9-9ad6-87e6709255ec.png)

After pressing:
![image](https://user-images.githubusercontent.com/37834592/57774643-5a0af280-771b-11e9-8667-9fab3b37c28c.png)

**Comment by c17julka** [comment]
Referred in #7068
