### ISSUE TITLE
Styling for "sort"-button

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#7116]
Small issue: Would be nice to have some styling on the "sort"-button (shown in the picture below). Maybe so that it looks similar to the "Toggle all"-button in the filter option?

![sortbutton](https://user-images.githubusercontent.com/37792690/57774845-e6b5b080-771b-11e9-86ee-2465d23b1726.png)

**Comment by a17andby** [comment]
Good idea since we have a "button styling" on the other drop down
![Screenshot from 2019-05-15 14-23-52](https://user-images.githubusercontent.com/49235724/57775376-2c26ad80-771d-11e9-9494-395e0999beff.png)
 the button here:

**Comment by a17alevu** [comment]
Solved and closed.
