### ISSUE TITLE
Entity / attribute names are wrong on copy, does not get the correct numbering

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7119]
<img width="526" alt="copyNameNumbers" src="https://user-images.githubusercontent.com/49199690/57775396-35b01580-771d-11e9-9fe5-b32d30d3b64b.png">
Speak with a17drama when working on this since he has worked with parts of this problem before

related to #7121

**Comment by a17drama** [comment]
This and #7141 are very related and will be dealt with simultaneously.

**Comment by a17vikab** [comment]
This will be solved in #7141 so I will close this issue.
