### ISSUE TITLE
MEGATHREAD: Copy issues

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7121]
All issues related to problems with the copy functionality will be referred to in this thread.
#7119  - fixed
#7115 - fixed
#7105 - fixed
#6977 
#7149 - fixed
#7157 - fixed
#7169 - fixed
#7186 - fixed
#7187 - fixed

**Comment by a16tobfr** [comment]
Read #6977 for more information about what the current problem is when it comes to copying objects.

**Comment by a18kaswi** [comment]
Only #6977 left, closing this one.
