### ISSUE TITLE
AccessED: Make text in table cells centered?

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#7123]
Suggestion: Maybe it would look better if the text within the table cells were placed in the center? To me it looks like the first and last names are placed too far to the left. It looked better before to have it like this when we still had SSN in the table.

![stylingtable](https://user-images.githubusercontent.com/37792690/57775447-5c6e4c00-771d-11e9-8e34-89333d33cfe7.png)

**Comment by a17alevu** [comment]
I like it the way i looks now, but that is my opinion. We will ask Henke tomorrow during the "kundmöte" and see what he thinks about it 💯

**Comment by a17robda** [comment]
I agree that some elements might look better centered. Such as buttons.

**Comment by a17andby** [comment]
Maybe someone could create a table with centered cells so the group could vote on what looks best?

**Comment by b16johso** [comment]
I agree the buttons should be centered, but text in data tables is rarely centered

**Comment by a17alevu** [comment]
Yes, buttons should be centered =)

**Comment by a17poner** [comment]
Buttons got centered and merged, closing this and if you'd want the rest to be centered reopen or make a new one :D
