### ISSUE TITLE
Hotkey labels on toolbar's undo and redo buttons

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#7126]
I found this issue #7020 which should have already fixed this issue I am creating, but maybe something happened when it got merged because it's still not implemented.

**Comment by a14oscna** [comment]
This is a merge issue for sure. I can confirm that I merged that solution and it worked properly prior to the merge today.

**Comment by a16tobfr** [comment]
It was implemented by me before but has been removed in the merge.

Solution:
~~~
<!-- Undo -->
<button class="diagramAction" id="undoButton" onclick='undoDiagram(event)' data="Undo (Ctrl + Z)">
  <img src="../Shared/icons/undo.svg">
</button>
<!-- Redo -->
<button class="diagramAction" id="redoButton" onclick='redoDiagram(event)' data="Redo (Ctrl + Y)">
  <img src="../Shared/icons/redo.svg">
</button>
~~~
