### ISSUE TITLE
DuggaEd: Drag-selecting text and releasing mouse button outside the edit window closes the window

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#7136]
![dragselect](https://user-images.githubusercontent.com/37793460/57778501-7bbca780-7724-11e9-939c-9365e6a78eef.gif)

**Comment by b17annni** [comment]
Does not appear when I try.

**Comment by a17fellu** [comment]
Same here. I cannot reproduce this

**Comment by b16johso** [comment]
Could it be a browser specific thing?

**Comment by b17annni** [comment]
Might be. Its fine using firefox etc but not chrome. Is this worthwhile to pursue @HGustavs ?

**Comment by a17andby** [comment]
I could recreate this with Brave (Chromium). But when I use Firefox I don't have that issue

**Comment by b17annni** [comment]
Does not seem relevant anymore
