### ISSUE TITLE
Adding 'duggor

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#714]
There is no way of adding a new dugga. Users should be able to use the example-duggas from the DuggaSYS/template folder, but this folder should not be used in the actual production system.

**Comment by a97marbr** [comment]
For example:
```
../../duggor/
```
Could be used as a folder outside the LenaSYS code to hold all duggas.
There should exist a dialog that allows for uploading all files relating to a new dugga.
* new_dugga.html [required]
* new_dugga.js [required]
* potential other files, e.g., the png-files for the different colors in dugga2 in the template folder

To get a better structure on the web server I would suggest creating a sub-folder for each new dugga:
```
../../duggor/new_dugga/new_dugga.html
../../duggor/new_dugga/new_dugga.js
```

**Comment by a97marbr** [comment]
After some discussions with Henke the following has been descided:
* We should use the existing file upload tool.
* Duggas should therefore reside with all the other files that can be uploaded

**Comment by a13arnhe** [comment]
Currently there exists a way of adding a new dugga and a new dugga template into the template folder, I think that pretty much covers the issue in question.
