### ISSUE TITLE
Rework the object labeling function

### ISSUE THREAD

**Issue by a14oscna** [HGustavs/LenaSYS#7141]
The logic for generating labels (e.g. Entity0, Relation2) is different when creating new objects versus copying existing ones. This allows for duplicate names due to a loophole in the counter. The problem can be replicated if you create 3 of the same object, delete the first one and copy the last one. 

We want to have a single piece of code that works for both creating new and copying existing objects when generating their labels. Moreover there should be spacing between the word and the number in the label.

**Comment by HGustavs** [comment]
How about giving it the counter from the point array? 

This array does not allow deletions and as long as each entity has at least one point this should work?

Only disadvantage is that a new entity may be called entity421

**Comment by a17drama** [comment]
This one is related to #7119 and will be fixed there. We will do some pair programming on this.
