### ISSUE TITLE
Inconsistent dropdown style accessED, resultED

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#7143]
ResultED
![image](https://user-images.githubusercontent.com/37792766/57780685-099a9180-7729-11e9-979b-3df84d5e11a7.png)

AccessED
![image](https://user-images.githubusercontent.com/37792766/57780729-25059c80-7729-11e9-895a-96a53a1d5c8c.png)

**Comment by a17poner** [comment]
merged, closing :)
