### ISSUE TITLE
Codeviewer: Change file upload icon

### ISSUE THREAD

**Issue by b16johso** [HGustavs/LenaSYS#7144]
The current file upload icon is pretty unclear and there is a better icon that is currently unused. Also maybe change the tooltip to say "File Upload" instead of "File Download/Upload"

**Comment by a17fellu** [comment]
This would be much clearer

**Comment by a17maxsj** [comment]
Agree

**Comment by a17adajo** [comment]
I like it, the old one looks like a electrical plug.
