### ISSUE TITLE
Editing the same file (Course local vs Global)

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#7145]
When you upload a file "Global" and the same file but as a "Course Local" (only text files) and edit the Course Local file it will also do the changes in the Global file. 

![image](https://user-images.githubusercontent.com/49199285/57781463-84b07780-772a-11e9-94c0-d44eff048998.png)

Editing the first file the first "Hej.txt" will automaticlly edit the file under.

**Comment by a18mahkh** [comment]
The described issue is already solved but don't know which issue solved it, certainly not this one because there is no commit or links to it.
Anyway if you have the same file with different kind and if you edit one of them, the rest of the files updates themselves.
