### ISSUE TITLE
Saving what mode you're in doesn't quite work

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#7152]
If you reload the page while in UML mode there are several problems.
- Short cut for Class button (shift + C) doesn't work (though the line button short cut _does_)
- If you try to change mode, either by short cut or via menu buttons, this happens:
![modesave](https://user-images.githubusercontent.com/37792313/57837306-d6a4dc00-77c2-11e9-86a0-3362f2617f75.PNG)

**Comment by a17johpe** [comment]
Also found:
- While in this mid stage, ie have just reloaded page while in UML mode, you can use shortcuts to create ER symbols
this seems to suggest that reloading the page puts the diagram in some kind of pseudo ER mode while displaying UML tools

**Comment by a16jenja** [comment]
> Also found:
> 
> * While in this mid stage, ie have just reloaded page while in UML mode, you can use shortcuts to create ER symbols
>   this seems to suggest that reloading the page puts the diagram in some kind of pseudo ER mode while displaying UML tools

That was my first thought aswell, I will look into this.

**Comment by HGustavs** [comment]
Should be a single location fix.

A variable that contains the "mode" and every update/functionality of the interface depends on that mode variable.

The more times a variable the variable is used the more useful it is to have it in a variable and not having to do a full document.getelementbyid ...

**Comment by a16jenja** [comment]
This issue should be closed since the pull request was merged @a14oscna

**Comment by a17vikab** [comment]
Closing this issue.
