### ISSUE TITLE
Menu should not close on clicked item.

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#7161]
This is the same problem as the old issue: #6349, and for some reason, the problem has reappeared.

See the old issue for description.

**Comment by HGustavs** [comment]
What is the default behavior, that the menu does not close until we hover out of the menu?

I would prefer standard operating system way of working with menus, that the menu disappears if the choice directly affects the view, and if not, we add a tick mark or whatnot and update when hover out?
