### ISSUE TITLE
Hotdog menu does not work any longer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#717]
For some reason over the last few revisions, the hotdog menu that was previously shown when the window was narrow (when mobile platform was assumed) does no longer show.

**Comment by f12danjo** [comment]
What do you mean by hotdog menu?

**Comment by a97marbr** [comment]
The three stacked horizontal bars that shows when screen is to small to show all menu items.

**Comment by a13arnhe** [comment]
Is a hotdog/hamburger menu still wanted, if so, then for what parts of the menu? the menubar itself can be made into a hamburger menu or/also the teachers various buttons could be added to a menu too.
![screen shot 2016-04-13 at 10 11 43](https://cloud.githubusercontent.com/assets/18159848/14487029/8a6ea298-0160-11e6-92c9-1b25a10d88f8.jpg)

**Comment by a15andau** [comment]
This has been solved in other issues, eg #3555 and #3605. Closing
