### ISSUE TITLE
Consider a change on the title editor in Codeviewer. 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#7178]
![image](https://user-images.githubusercontent.com/49199285/57849196-fc3ddf80-77da-11e9-8538-f0ef27c31b90.png)
Should we just delete this function and only edit using the cogwheel @HGustavs ?

**Comment by a17joaap** [comment]
We could just make it update when the enter key is pressed. https://github.com/HGustavs/LenaSYS/pull/7012 already handles the enter key so it would be simple to just shove an ajax call in there also
