### ISSUE TITLE
Incorrect "fill" for rects in swimlaneSVG

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#7180]
In swimlaneSVG in sectioned, the tests do not get the correct fill colour for their rect element.

``` 
// Yellow backgroundcolor if the dugga have been submitted but grade is pending.
// Green backgroundcolor if the dugga have been submitted and the grade is passed.
// Red backgroundcolor if the dugga have been submitted and the grade is failed.
var fillcol = "#BDBDBD";
if ((entry.submitted != null) && (entry.grade == undefined)) fillcol = "#FFEB3B"
else if ((entry.submitted != null) && (entry.grade > 1)) fillcol = "#00E676"
else if ((entry.submitted != null) && (entry.grade == 1)) fillcol = "#E53935";
```

Inside the drawSwimlanes() function, it defines the rect colour depending on the code above. Currently, all of the rects are #FFEB3B, which means they are pending, when not all of the tests have been submitted (are pending). This also leads to tests which are supposed to have red font colour, have a grey colour instead.

In order to determine if this issue is active, #7068 would need to be fixed, so we can add more example tests to replicate this problem without fiddling with the database.

**Comment by HGustavs** [comment]
Anything that would make the display clearer is a worthwhile task in my mind.
