### ISSUE TITLE
Using middle mouse button to press top menu items in sectioned.php opens wrong link

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7182]
When you press using the left mouse button the correct page opens, but when you use the middle mouse button, it opens the wrong page in a new tab. Illustration:

![g1q5R9s0T18](https://user-images.githubusercontent.com/37834592/57852336-327f5d00-77e3-11e9-8d6f-fa162322b466.gif)

**Comment by c17julka** [comment]
Hmmm... It seems to only be an issue with the middle mouse button, while CTRL + Left MB and Right click > Open in new tab seems to work.

**Comment by HGustavs** [comment]
Low priority IMHO, as there are other ways of achieving the same functionality.

I would prefer if any solution does not add complication to the code.

**Comment by a17oscno** [comment]
One interesting thing is that if you first use CTRL+LMB to open it in a new window and then try to use the middle mouse button it actually works. Can this be some sort of effect from the "oncontextmenu" attribute?
