### ISSUE TITLE
Snap to grid does not snap properly

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7183]
Should snap to the corners of the small squares, Now it snaps to the middle of the squares
<a href="https://gyazo.com/ca267c3e1db74d19ef8e7486311afcf9"><img src="https://i.gyazo.com/ca267c3e1db74d19ef8e7486311afcf9.gif" alt="Image from Gyazo" width="965.9999999999995"/></a>

**Comment by a17vikab** [comment]
Might be connected to #6270. It might be possible to solve both issues at the same time, maybe not.

**Comment by HGustavs** [comment]
The easiest thing is to make the grid in "real pixels" ... then the pixel to canvas should handle this automatically.

If we do the positioning of all movements also in real pixels it will also work automatically.

For example if we snap to every 10 real pixels it will just work.

Coordinate=Math.floor(coordinate/10)*10;

when updating the coordinates in the coordinate array.
