### ISSUE TITLE
Weak (copied) entities becomes strong while shaken

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7187]
Related to: #7121
Probably related to the attributes which are copied from the original to the copy
<a href="https://gyazo.com/891acf23bdfcfb73bbdcb4af857a08c5"><img src="https://i.gyazo.com/891acf23bdfcfb73bbdcb4af857a08c5.gif" alt="Image from Gyazo" width="752.9999999999997"/></a>

**Comment by HGustavs** [comment]
Jazz-hands ... does anyone know what happens?

Could it be that we are hovering something with the object selected and accidentally copy the style from that hovered object?
