### ISSUE TITLE
Warning in duggaED when pressing FAB

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7189]
![image](https://user-images.githubusercontent.com/37834592/57853524-45dff780-77e6-11e9-8e84-1a94b488f15e.png)

**Comment by a17andby** [comment]
I have hard time to recreate this problem. I get not error when I press the FAB button in duggaed.php.

Tried to recreate this issue on our test server on our new weekly branch.

**Comment by HGustavs** [comment]
This is due to the re-synchronization of the new object or before we create the new object?
