### ISSUE TITLE
Codeviewer: Reset button does not reset box size after pressing maximize

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7198]
Nothing happens when I click the Reset button
![thisbutton](https://user-images.githubusercontent.com/37792198/57889661-af3b2700-7835-11e9-8f48-950549d187c8.PNG)

When I click on it, nothing happens. No error message in log, nothing. Expected behaviour would be for the box to return to normal size.

**Comment by HGustavs** [comment]
Screenshot of what happens? 

Which reset button?

**Comment by a17fellu** [comment]
Was this observed on our live server? It seems to be something wrong on the live server. Cannot replicate this on a local server. If on local server it could also be that you before pressing the reset button have manually changed the size by dragging a window. Reset can only reset the maximizes that have been made not reset the resize made by dragging the boxes.

**Comment by a17joaap** [comment]
This is on the web server.

**Comment by a17fellu** [comment]
See if you can replicate it on a local server. Because i cant.

**Comment by a17fellu** [comment]
On the web-server maximize and reset works for template 1

**Comment by a17andby** [comment]
Tried this on my local test environment with our weekly branch.

I can maximize but the reset button doesn't work. Don't get any error either when I press the reset button.

**Comment by a17fellu** [comment]
Something have gotten broken after the weekly merge. When i run the branch where i added these functionalities there are no issues. Here is that branch:

https://github.com/HGustavs/LenaSYS/tree/GruppC2019W20_mergeconflictfix

**Comment by a17robda** [comment]
Is this something that needs to be fixed or not?

**Comment by a17fellu** [comment]
It has to be fixed. Possibly compare the new branch with the branch i linked to find inconsistencies with these 2 functionalities between those branches

**Comment by a17andby** [comment]
Just tried GruppC2019W20_mergeconflictfix branch. Doesn't work. Same result as I wrote in https://github.com/HGustavs/LenaSYS/issues/7198#issuecomment-493423307

**Comment by a17joaap** [comment]
@a17fellu I tried running that branch, getting the same issues.

**Comment by a17fellu** [comment]
This is super weird because i am running that branch with 0 errors works like a charm xD. This is really strange.

**Comment by a17andby** [comment]
@a17joaap What url did you do your testning? I want to see if I get the same error on your specific url. You could pm me on discord if you don't wanna post it here

**Comment by a17joaap** [comment]
@a17fellu Even with template 3 or 8? Those are the templates calling the function that doesn't exist.
@a17andby https://a17joaap.gruppc.webug.his.se:20002/DuggaSys/codeviewer.php?exampleid=1254&courseid=2&cvers=97732

**Comment by a17fellu** [comment]
Yes they all work for me xD

**Comment by a17joaap** [comment]
could you link to where 'alignBoxesWidth2Boxes' is defined?

**Comment by a17andby** [comment]
@a17joaap I only get the error when I press these maximize buttons: 

![error](https://user-images.githubusercontent.com/49235724/57927009-265fd200-78ad-11e9-8ce9-eab109ebebaf.png)

Same for you?

**Comment by a17fellu** [comment]
alignBoxesWidth2Boxes should be replaced with alignBoxesWidth

**Comment by a17fellu** [comment]
I don't know why it works for me with the faulty code though xd

**Comment by a17joaap** [comment]
Yeah, its because box1 does not call the function:
```
                if(boxid == 1){
			$(boxValArray['box' + 2]['id']).width("0%");
			$(boxValArray['box' + 3]['id']).width("0%");

			$(boxValArray['box' + boxid]['id']).width("100%");
			alignBoxesWidth3Boxes(boxValArray, 1, 2, 3);
		}

		if(boxid == 2){
			$(boxValArray['box' + 1]['id']).width("0%");
			$(boxValArray['box' + 1]['id']).height("100%");
			$(boxValArray['box' + 3]['id']).width("100%");
			$(boxValArray['box' + 3]['id']).height("0%");

			$(boxValArray['box' + boxid]['id']).width("100%");
			$(boxValArray['box' + boxid]['id']).height("100%");
			alignBoxesWidth2Boxes(boxValArray, 2, 1);
			alignBoxesHeight3boxes(boxValArray, 2, 1, 3);
		}

		if(boxid == 3){
			$(boxValArray['box' + 1]['id']).width("0%");
			$(boxValArray['box' + 1]['id']).height("100%");
			$(boxValArray['box' + 2]['id']).width("100%");
			$(boxValArray['box' + 2]['id']).height("0%");

			$(boxValArray['box' + boxid]['id']).width("100%");
			$(boxValArray['box' + boxid]['id']).height("100%");
			alignBoxesWidth2Boxes(boxValArray, 3, 1);
			alignBoxesHeight3boxes(boxValArray, 2, 1, 3);
		}
```

**Comment by a17fellu** [comment]
I got the problem now. And by replacing alignBoxesWidth2Boxes with alignBoxesWidth it fixes the problem

**Comment by a17joaap** [comment]
I tried alignBoxesWidth, it eliminates the error message, but 'Reset' still does not work 😄

**Comment by a17fellu** [comment]
Yeah i have no idea what has happened. It worked a few days ago xD

**Comment by a17fellu** [comment]
REset starts working after you resize one of the boxes only hmmm...

**Comment by a17fellu** [comment]
One solution could be to hide the reset button until a box has been resized

**Comment by a17robda** [comment]
I do not have this problem since it works without errors for me. I can't seem to replicate the problem either.

**Comment by a17robda** [comment]
Seems to be a browser based issue since I only get this issue on Chrome-based browsers.

**Comment by a17joaap** [comment]
Does not work for me on any template, tested with firefox and chrome.

**Comment by a17poner** [comment]
Hmm, would making the reset button reset it fully solve the issue? Since you can change the size of boxes with dragging but reset does nothing to reset those changes. So if the reset changed the boxes to be like they were when the template was chosen that might be add some new functionality and may be a way to fix this?

**Comment by a17robda** [comment]
This might be a better solution since it seems like there is something that the resize events from JQuery has to trigger before being able to use the reset button. A problem I noticed is that the reset button after resizing just resets it to where you stopped resizing the template window. Since the intended behavior probably is to revert the window back to template "default" it would be better to do so. I am currently working on this.

**Comment by a17robda** [comment]
Got the original behavior to work, the issue was not saving the box size on maximize. Pushing now.

**Comment by a17joaap** [comment]
This is fixed for me now.
