### ISSUE TITLE
Global appearance should not be responsive when no object has been drawn on canvas

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7203]
When no object exist on the canvas, the Global Appearance button which is located in the edit tab should behave as the change appearance button does when no object is selected.

It should be unresponsive.
<img width="265" alt="ga" src="https://user-images.githubusercontent.com/49199690/57859553-75e1c780-77f3-11e9-8fb4-2b16a18f34a5.png">

**Comment by HGustavs** [comment]
Good idea.

**Comment by a17alfcl** [comment]
Changed to work at all times instead
