### ISSUE TITLE
Change appearance button outputs an error message to the console when no object is selected

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7204]
This error message should probably not be seen. The button should simply be unresponsive when lastSelectedObject is undefined and not give an error message to the console.
![changeAppearance](https://user-images.githubusercontent.com/49199690/57859853-07513980-77f4-11e9-951a-d546e1609ce5.JPG)

Edit: Also happens when multiple objects are selected.
Maybe change the change appearance so it works for all of the selected objects instead of just one?

**Comment by c17matjo** [comment]
I've solved the main issue but I'm not entirely sure on how to solve the second. When multiple objects are selected, should the appearance menu still work and have the changes apply to all selected objects? What if there are different types of objects selected with different possible parameters (A line and an entity e.g)? I've looked at the code for the appearance menus and I can't see an easy way of implementing something like that. 

I'm going to make a PR for the main issue for now.
