### ISSUE TITLE
Sectioned icons instead of buttons

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7210]
In the interest of standardization between views.

We have text buttons for file editor in sectioneditor view  but icons in oher views for same functionality.

How about 
* Using the hand icon for results
* Using the extension plug we use for file list in other views
* More unclear what icon to use for tests and for access (a torso icon for access?)

![Screenshot 2019-05-17 08 50 44](https://user-images.githubusercontent.com/6978801/57908786-35308f80-7881-11e9-9050-8653da756dee.png)

![Screenshot 2019-05-17 08 55 46](https://user-images.githubusercontent.com/6978801/57908923-9e180780-7881-11e9-81d5-cb7394ae9252.png)

**Comment by HGustavs** [comment]
While we are at it, perhaps a bigger plus and cog wheel icon  in sectioned also?

**Comment by a17pongo** [comment]
related to issue #7109

**Comment by a17pongo** [comment]
![Screenshot from 2019-05-20 14-13-37](https://user-images.githubusercontent.com/37792222/58020783-7cc94c80-7b09-11e9-8b0e-deedd0efbd8e.png)

@HGustavs 
Would something like a lock-icon work for accessed? 
Also thinking of using a pen over a document icon for tests

**Comment by a17pongo** [comment]
mockup suggestion for tests:

![Screenshot from 2019-05-20 14-44-03](https://user-images.githubusercontent.com/37792222/58022502-dc295b80-7b0d-11e9-9daf-4dc72db9eadc.png)

**Comment by b17nicsv** [comment]
I think this is fine. Go with it! 👍

**Comment by a17poner** [comment]
Not my groups issue just want to chime in and say that we removed the plug icon in codeviewer and instead replaced it with a more standard upload file icon since the plug made no sense for the roughly 7-8 people in the group we talked with it about.

**Comment by a17anter** [comment]
I reviewed the PR and to be honest this looks like crap.. the icons doesn't make much sense and they are all different colours. I would much rather keep the old buttons.
see picture below of how the solution looks.

![image](https://user-images.githubusercontent.com/49204317/58082584-9628d200-7bb7-11e9-9829-b6476401454e.png)

**Comment by a17andby** [comment]
https://github.com/HGustavs/LenaSYS/issues/7296

**Comment by b17nicsv** [comment]
I'd take suggestions.

**Comment by a17pongo** [comment]
I also approve the icons are bad, I created an issue for it #7296 so that someone better with this kind of work can improve. 
But I agree with @HGustavs that for consistency we should use icons, or replace all icons with buttons
