### ISSUE TITLE
Problem with moving camera with keyboard and then clicking on canvas

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#7216]
If you use the arrow keys to move the camera around and then try to use _left_ mouse button on canvas it turns into moving the canvas as well. This becomes a problem if you're trying to select an object or an area on the canvas.
![2170f144d3a8e4dc53ef9de21b3b9ff1](https://user-images.githubusercontent.com/37792313/57913676-6c0ca280-788d-11e9-89d4-c2e1a331b016.gif)

Using the arrow keys seem to turn mode into Movearound for a longer time than just the one key press. Seeing as you can both press the buttons one at a time or hold down on an arrow to move the camera further, maybe the mode should be set to default again on keyup?

**Comment by a17vikab** [comment]
#6874 seems to solve this problem.
