### ISSUE TITLE
Implement touch support on canvas for mobile view

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7218]
As of now, you cannot draw lines, move the canvas, etc, while in mobile view. Making the canvas responsive to touch events while in mobile view would solve this.

Maybe the information on this page could help with this implementation:
http://bencentra.com/code/2014/12/05/html5-canvas-touch-events.html

**Comment by a18andtu** [comment]
Added functionality for mobile devices through couple of other issues.
