### ISSUE TITLE
Add shortcut for "Reset view to origin"

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#7220]
The functionality "reset view to origin" doesn't have a shortcut. This is something that is used relatively often and would benefit from having a shortcut.

**Comment by a14oscna** [comment]
After discussing this matter I have decided that we set Shift + O as the shortcut command for this function.

**Comment by a17okaoz** [comment]
Added the short command Shift + O next to ResetToOrigin in Edit
