### ISSUE TITLE
Virtual A4 coverage

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#7221]
The A4 coverage is now covering 1 of 4 quadrants. It should cover all 4 (the whole canvas).

**Comment by a17johpe** [comment]
For future reference: here is the pull request for creating the A4 covering of the 1 quadrant.
https://github.com/HGustavs/LenaSYS/pull/6731

**Comment by b18phibe** [comment]
solved whit #7908.
Closing
