### ISSUE TITLE
Menu collapse when selecting A4-menuitems

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#7226]
Menu collapse when selecting "Toggle A4-orientation", "Toggle A4-holes" and "A4 Holes right" which it should not do.

![Skärmavbild 2019-05-17 kl  12 04 44](https://user-images.githubusercontent.com/37792795/57920775-24d9de00-789c-11e9-88c5-c2bd9f88d984.png)

**Comment by a17vikab** [comment]
This seems to be fixed somehow, might be a hardware problem? @a17jacsv

**Comment by a17jacsv** [comment]
It works now for me aswell. Maybe this was solved in a merged PR.

**Comment by a17vikab** [comment]
Issue fixed in a PR, no clue where. Closing issue.
