### ISSUE TITLE
Resulted: search bar, blankspace is not tollerated after search method

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#7231]
Empty search result:
![image](https://user-images.githubusercontent.com/49199825/57926431-83f31f00-78ab-11e9-9b03-66ca5d1443b4.png)

![image](https://user-images.githubusercontent.com/49199825/57926446-92d9d180-78ab-11e9-9978-29dc13ba07cd.png)

**Comment by a17oscno** [comment]
@c17johha remove the "blankspace" between markG: and Assingment

Because that is not in the syntax for searching.

**Comment by a17oscno** [comment]
So this issue can be closed or changed so that it may handle blankspaces but that should be a low priority one.

**Comment by a17oscno** [comment]
Blankspaces are only used when searching for lastnames 

e.g Sven E
or
e.g Leif W

So if there are multiple people named sven you can then specify if you want to find only the "Sven" that has a last name that starts with "E" like "Eriksson"

**Comment by a17oscno** [comment]
Some help to this issue might be that as of right now "blankspaces" are used when searching for specific people and multiple search terms (but that dosnt seem to work).

e.g if you have two people named Sven then you can specify their lastname like "Sven E" and only get the results of people named sven and has a lastname that starts with E. 

And "blankspaces" are used when searching by splitting the search string into an array. So it should be no problem fixing this issue.
