### ISSUE TITLE
Inconsistent heights on table cells in resulted

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#7235]
![image](https://user-images.githubusercontent.com/37792321/57926135-c36d3b80-78aa-11e9-9e74-8bb360881d96.png)
The height on the table cells in resulted are different depending on if they are graded or not. 

A suggestion would be to change the .resultTableCell to a height of 90% (not 100% since it should be consistent with the width, and the width does not look great with 100%).

Minor issue

**Comment by a17anter** [comment]
Height has been adjusted now.
![image](https://user-images.githubusercontent.com/49204317/58025720-5e694e00-7b15-11e9-89c0-1b1becca953a.png)
