### ISSUE TITLE
Login box looks different in codeviewer compared to other pages

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7236]
Codeviewer:
![image](https://user-images.githubusercontent.com/37834592/57926656-214e5300-78ac-11e9-9365-019aa685313b.png)

Courseed:
![image](https://user-images.githubusercontent.com/37834592/57926682-34612300-78ac-11e9-8c95-3058b482edae.png)

**Comment by a17joaap** [comment]
This is because codeviewer uses codeviewer.css that has a rule for the .alert class, which is used in the loginbox.
