### ISSUE TITLE
Resulted - Sorting radion buttons. A more responsive method

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#7240]
![image](https://user-images.githubusercontent.com/49199825/57927319-ed742d00-78ad-11e9-89e8-3ed75e617c0e.png)

When sorting with the radio buttons, one must click the button "sort" to apply the sorting.

Would it be satisfying that the sorting applies when a valid combination of sorting is checked?

e.g:

![image](https://user-images.githubusercontent.com/49199825/57927142-92dad100-78ad-11e9-8bc3-387676bf3ca8.png)

**Comment by c17julka** [comment]
Or a standard setting of either asc/desc sorting could be selected. Then sort it automatically on click.

**Comment by c17johha** [comment]
@c17julka I'm not sure what you mean? Is it not a standard setting of asc desc that you choose?

**Comment by c17julka** [comment]
@c17johha I mean having one of the asc/desc radio buttons "checked" as a standard. So when you go into resulted, you immediately have 1 of them checked already.

**Comment by a17oscno** [comment]
@b17timjo @c17johha 

This issue can be closed because when you move your mouse outside the sort window it will automaticly "press" the sort button so that the changes are made. No need to press it if you don't want to.

**Comment by c17johha** [comment]
@HGustavs What technique is prefered? Sorting that updates as soon as a radio button is clicked, or update when all desired options been choosed and user clicks outside the sorting table?

**Comment by c17julka** [comment]
Sorting when mouse leaves seems to be pretty inconvenient. I'm no Henke, but I'd say on click would be much more preferred

**Comment by HGustavs** [comment]
Since it is a radio button with only one item active at once leaving on click seems the most applicable solution in this case...

Column filters have the opposite way of functioning.... we can click multiple columns to show, and we do not want it to submit until finished with clicking all the desired fields.

In this case it seems like we are over-standardizing between these two views?

**Comment by b17nicsv** [comment]
The column filter are checkboxes and not radio buttons though. I'd say the best course of action is, as you suggested, when leaving it will automatically press sort.

**Comment by c17johha** [comment]
@b17nicsv I believe there are some miss understanding here.

Question is if the radio buttons should sort when a valid combination is marked
![image](https://user-images.githubusercontent.com/49199825/58024907-8c4d9300-7b13-11e9-8283-3e8dd3549052.png)

This conversation seems to confuse the sorting with the filtering. To clarify, there must be multiple choices to make a valid sorting. one must choose which course and grades ASC/DESC/PEN.

What I understand @HGustavs is to let the sorting begin as soon as there are a valid combination of radio buttons marked.

**Comment by b17nicsv** [comment]
Yepp, misunderstood. Sounds reasonable a valid combination is needed.
