### ISSUE TITLE
Add form validation to Sectioned

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7249]
These forms:
![validationvers](https://user-images.githubusercontent.com/37792198/57934188-616b0100-78bf-11e9-9f3c-358b31565582.PNG)
![validationnewvers](https://user-images.githubusercontent.com/37792198/57934191-63cd5b00-78bf-11e9-8ea0-1bc74e53c08d.PNG)
![validationitem](https://user-images.githubusercontent.com/37792198/57934192-662fb500-78bf-11e9-9ce8-62ba3fa7ce2d.PNG)

All need validation for start/end date and deadline respectively. Part of https://github.com/HGustavs/LenaSYS/issues/6217

**Comment by a17adajo** [comment]
#7252 can be used as a reference for how it can be implemented

**Comment by b17nicsv** [comment]
Related to #7250
