### ISSUE TITLE
Add form validation for Courseed

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7250]
These forms:
![validationeditcourse](https://user-images.githubusercontent.com/37792198/57934493-25846b80-78c0-11e9-9a24-f271ce0eba3c.PNG)
![validationnewcourse](https://user-images.githubusercontent.com/37792198/57934520-2fa66a00-78c0-11e9-8997-7bae2738b432.PNG)

Need validation. Part of https://github.com/HGustavs/LenaSYS/issues/6217

**Comment by a17adajo** [comment]
#7252 can be used as a reference for how it can be implemented

**Comment by a17amama** [comment]
@a17joaap What exactly do you mean by validation? Where should the validation be inserted?

**Comment by a17joaap** [comment]
Catch erroneous input before it is sent to courseedservice. See #7252
