### ISSUE TITLE
Add form validation for Accessed

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7251]
These forms:
![validationaccess](https://user-images.githubusercontent.com/37792198/57934977-0d611c00-78c1-11e9-9159-b87faa87e2db.PNG)
![validationaccessimport](https://user-images.githubusercontent.com/37792198/57934987-10f4a300-78c1-11e9-9e11-2dc8c660e556.PNG)

Need validation. Currently they fail silently, we need feedback if the input is missing/of incorrect format. Part of #6217

**Comment by HGustavs** [comment]
If errors happen when importing error messages using the standard alerts would be nice.

Contents of $debug variable should automatically present as alert in view.

**Comment by a17poner** [comment]
merged with #7252
