### ISSUE TITLE
Sectioned: Can not logout, only in

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#7253]
The button does not appear to be clickable when logged in?

![image](https://user-images.githubusercontent.com/49197690/57997563-9c428400-7acd-11e9-8f63-ee9be9522ff8.png)

**Comment by a17joaap** [comment]
Should be fixed in https://github.com/HGustavs/LenaSYS/pull/7146
Are you sure your branch is up to date?
If it is, can you check if the TopMenuStatic covers the logout button?

**Comment by a18kaswi** [comment]
Probably fixed in #7146
