### ISSUE TITLE
Error in console when maximize & reset a window 

### ISSUE THREAD

**Issue by a17alevu** [HGustavs/LenaSYS#7258]
When maximizing window in Codeviewer and then reseting it a error will pop-up in the console.

**Comment by a17alevu** [comment]
NOTE: only appears error when you press the "maximize" button.

**Comment by a17maxsj** [comment]
I did not get this error, what browser are you running?

**Comment by a17robda** [comment]
Is this the same as #7198 ? I just submitted a fix for it.

**Comment by a17alevu** [comment]
Google chrome.

**Comment by HGustavs** [comment]
Can anyone confirm and show a screenshot of the error?

**Comment by a17alevu** [comment]
https://gyazo.com/65a17366efec49ec9251174611c72a49 Error appears everytime i press "Maximize"

**Comment by a17alevu** [comment]
Yes, this is on Chrome and on my local server @a17maxsj

**Comment by a17poner** [comment]
I also get it on my local environment on row 1962, fick det inte på niclas i gruppB's server som vi testade mergen på men där funkar inte heller reset knappen för mig. Nvm orkar inte skriva om det men det verkar bara vara på en template man får felet. Tror det är template 3, (en stor ruta till vänster och 2 små ovanför varandra i högerkolumnen)

**Comment by a17maxsj** [comment]
Template 3 creates this issue in console

![image](https://user-images.githubusercontent.com/49199993/58173497-d1043600-7c9b-11e9-81b0-7f11f42782ea.png)

**Comment by a17maxsj** [comment]
This issue is no longer pressent.
