### ISSUE TITLE
Access editor student teacher

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7262]
We need functionality for having student teachers (student supervisors etc), that are allowed to change code examples, correct minor erros in files, and rework other such minor elements of courses but, should not be able to do marking of assignments and see results of other students.

**Comment by a17joaap** [comment]
Currently working on this, and wondering what you mean by minor elements of courses. 

Are student teachers allowed to 

- Accessed: See the page? Edit rows? Import users?
- Sectioned: add/edit/delete course items?

**Comment by HGustavs** [comment]
Im thinking no view in access.

In sections, we can allow pretty much complete access, as most of this is reversible.
