### ISSUE TITLE
Access editor hide teachers feature

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7264]
We want a hide teachers feature in the access editor.

Sort of like a default search option, if enabled the sortabletable automatically filters for only students, no teachers in list, and conversely, only teachers.

Three states, only teachers, only students, and both.

**Comment by HGustavs** [comment]
Local storage of data, so if we return to the access editor for this specific course with only teachers shown, same thing happens.

If we go to some other course and we have only students shown it should remember this for this course.

So... not a general setting, but a course spepcific setting.

**Comment by b16johso** [comment]
Do we want to toggle on/off with checkboxes, or do we want a dropdown menu for filtering? Where should the filtering options be located? Above the table headers, like in ResultEd, or in the funnel menu?

**Comment by b16johso** [comment]
Also, should there be an option to hide student teachers https://github.com/HGustavs/LenaSYS/issues/7262? @HGustavs

**Comment by a17poner** [comment]
merged in #7458
