### ISSUE TITLE
Highlight on HTML tags

### ISSUE THREAD

**Issue by a17andby** [HGustavs/LenaSYS#7269]
Since they were some question marks (https://github.com/HGustavs/LenaSYS/issues/2146) on which HTML tags that work or not when it comes to highlight I have made a summary on what HTML tags that works or not works. 

All HTML tags in the list are from: [w3schools.com](https://www.w3schools.com/tags/). I did choose the HTML tags that followed these criteria:
-  Have an opening and closing tag
- Supported in HTML5

**How it is suppose to work**
When you hover HTML tags in CodeViewer the tag should highlight with purple. See example below:
![Screenshot from 2019-05-20 12-23-35](https://user-images.githubusercontent.com/49235724/58014936-4cc67d00-7afa-11e9-8f0d-802f7d10357b.png)

| Opening tag  | Closing tag   | Highlight works?   |
| ------------ | ------------- | ------------------ |
| `<!--         | -->`           | :x:                |
| `<a>`          | `</a>`          | :heavy_check_mark: |
| `<abbr>`       | `</abbr>`       | :heavy_check_mark: |
| `<address>`    | `</address>`    | :heavy_check_mark: |
| `<article>`    | `</article>`    | :x:                |
| `<aside>`      | `</aside>`      | :x:                |
| `<audio>`      | `</audio>`      | :x:                |
| `<b>`          | `</b>`          | :heavy_check_mark: |
| `<bdi>`        | `</bdi>`        | :x:                |
| `<bdo>`        | `</bdo>`        | :heavy_check_mark: |
| `<blockquote>` | `</blockquote>` | :heavy_check_mark: |
| `<body>`       | `</body>`       | :heavy_check_mark: |
| `<button>`     | `</button>`     | :heavy_check_mark: |
| `<canvas>`     | `</canvas>`     | :heavy_check_mark: |
| `<caption>`    | `</caption>`    | :heavy_check_mark: |
| `<cite>`       | `</cite>`       | :heavy_check_mark: |
| `<code>`       | `</code>`       | :heavy_check_mark: |
| `<colgroup>`   | `</colgroup>`   | :heavy_check_mark: |
| `<data>`       | `</data>`       | :x:                |
| `<datalist>`   | `</datalist>`   | :x:                |
| `<dd>`         | `</dd>`         | :heavy_check_mark: |
| `<del>`        | `</del>`        | :heavy_check_mark: |
| `<details>`    | `</details>`    | :x:                |
| `<dfn>`        | `</dfn>`        | :heavy_check_mark: |
| `<dialog>`     | `</dialog>`     | :x:                |
| `<div>`        | `</div>`        | :heavy_check_mark: |
| `<dl>`         | `</dl>`         | :heavy_check_mark: |
| `<dt>`         | `</dt>`         | :heavy_check_mark: |
| `<em>`         | `</em>`         | :heavy_check_mark: |
| `<fieldset>`   | `</fieldset>`   | :heavy_check_mark: |
| `<figcaption>` | `</figcaption>` | :x:                |
| `<figure>`     | `</figure>`     | :x:                |
| `<footer>`     | `</footer>`     | :x:                |
| `<form>`       | `</form>`       | :heavy_check_mark: |
| `<h1>`         | `</h1>`         | :heavy_check_mark: |
| `<h2>`         | `</h2>`         | :heavy_check_mark: |
| `<h3>`         | `</h3>`         | :heavy_check_mark: |
| `<h4>`         | `</h4>`         | :heavy_check_mark: |
| `<h5>`         | `</h5>`         | :heavy_check_mark: |
| `<h6>`         | `</h6>`         | :heavy_check_mark: |
| `<head>`       | `</head>`       | :heavy_check_mark: |
| `<html>`       | `</html>`       | :heavy_check_mark: |
| `<i>`          | `</i>`          | :heavy_check_mark: |
| `<iframe>`     | `</iframe>`     | :x:                |
| `<img>`        | `</img>`        | :x:                |
| `<ins>`        | `</ins>`        | :heavy_check_mark: |
| `<kbd>`        | `</kbd>`        | :heavy_check_mark: |
| `<label>`      | `</label>`      | :heavy_check_mark: |
| `<legend>`     | `</legend>`     | :heavy_check_mark: |
| `<li>`         | `</li>`         | :heavy_check_mark: |
| `<main>`       | `</main>`       | :x:                |
| `<map>`        | `</map>`        | :heavy_check_mark: |
| `<mark>`       | `</mark>`       | :x:                |
| `<meter>`      | `</meter>`      | :x:                |
| `<nav>`        | `</nav>`        | :x:                |
| `<noscript>`   | `</noscript>`   | :heavy_check_mark: |
| `<object>`     | `</object>`     | :heavy_check_mark: |
| `<ol>`         | `</ol>`         | :heavy_check_mark: |
| `<optgroup>`   | `</optgroup>`   | :heavy_check_mark: |
| `<option>`     | `</option>`     | :heavy_check_mark: |
| `<output>`     | `</output>`     | :x:                |
| `<p>`          | `</p>`          | :heavy_check_mark: |
| `<picture>`    | `</picture>`    | :x:                |
| `<pre>`        | `</pre>`        | :heavy_check_mark: |
| `<progress>`   | `</progress>`   | :x:                |
| `<q>`          | `</q>`          | :heavy_check_mark: |
| `<rp>`         | `</rp>`         | :x:                |
| `<rt>`         | `</rt>`         | :x:                |
| `<ruby>`       | `</ruby>`       | :x:                |
| `<s>`          | `</s>`          | :x:                |
| `<samp>`       | `</samp>`       | :heavy_check_mark: |
| `<script>`     | `</script>`     | :heavy_check_mark: |
| `<section>`    | `</section>`    | :x:                |
| `<select>`     | `</select>`     | :heavy_check_mark: |
| `<small>`      | `</small>`      | :heavy_check_mark: |
| `<span>`       | `</span>`       | :heavy_check_mark: |
| `<strong>`     | `</strong>`     | :heavy_check_mark: |
| `<style>`      | `</style>`      | :heavy_check_mark: |
| `<sub>`        | `</sub>`        | :heavy_check_mark: |
| `<summary>`    | `</summary>`    | :x:                |
| `<sup>`        | `</sup>`        | :heavy_check_mark: |
| `<svg>`        | `</svg>`        | :x:                |
| `<table>`      | `</table>`      | :heavy_check_mark: |
| `<tbody>`      | `</tbody>`      | :heavy_check_mark: |
| `<td>`         | `</td>`         | :heavy_check_mark: |
| `<template>`   | `</template>`   | :x:                |
| `<textarea>`   | `</textarea>`   | :heavy_check_mark: |
| `<tfoot>`      | `</tfoot>`      | :heavy_check_mark: |
| `<th>`         | `</th>`         | :heavy_check_mark: |
| `<thead>`      | `</thead>`      | :heavy_check_mark: |
| `<time>`       | `</time>`       | :x:                |
| `<title>`      | `</title>`      | :heavy_check_mark: |
| `<tr>`         | `</tr>`         | :heavy_check_mark: |
| `<u>`          | `</u>`          | :x:                |
| `<ul>`         | `</ul>`         | :heavy_check_mark: |
| `<var>`        | `</var>`        | :heavy_check_mark: |
| `<video>`      | `</video>`      | :x:                |
| `<wbr>`        | `</wbr>`        | :x:                |

**Comment by HGustavs** [comment]
This seems great, and very helpful to anyone using this system for html code.

**Comment by a17poner** [comment]
This has just been merged, assuming all of the non checkmarked tags were included in it and that it is safe to close.
