### ISSUE TITLE
Errors inside of profile.php

### ISSUE THREAD

**Issue by a17amama** [HGustavs/LenaSYS#7270]
These errors appear inside the profile.php 
![profile](https://user-images.githubusercontent.com/37793130/58016058-0aeb0600-7afd-11e9-906d-2ee63981ae7b.PNG)

**Comment by HGustavs** [comment]
Anyone know what happens?

**Comment by a18jenro** [comment]
Could not access profile, error message: Profile settings can only be changed on a secure HTTPS connection.

**Comment by a18jenro** [comment]
Someone should investigate.

**Comment by a18eliek** [comment]
I was not able to replicate this issue, if it reappears we could reopen this issue in the future.

**Comment by a18jenro** [comment]
@a18eliek did you make the profile accessible?
I'm still getting "Profile settings can only be changed on a secure HTTPS connection.", when trying to access a profile.

**Comment by a18eliek** [comment]
@a18jenro You can either comment out the HTTPS check on your local copy of LenaSys, or have your development version use SSL to serve the website.

**Comment by a18eliek** [comment]
You can find the check in profile.js, row 212-214.
