### ISSUE TITLE
CSS Dugga content goes outside small screen

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7276]
![gif3](https://user-images.githubusercontent.com/37834592/58019342-9799c200-7b05-11e9-9785-c78992a9bdbc.gif)

**Comment by HGustavs** [comment]
Perhaps this is due to the size of the dialog which is fixed for all of the system?

**Comment by a17fellu** [comment]
I only get this in the chrome mobile view. I do not get this in firefox mobile view. It might only be an issue with chromes mobile view. I am gonna do some more testing

**Comment by a17fellu** [comment]
After some testing i have concluded that this is not an issue with the dialog but an issue with the styling of the text in the nav bar. On this page it has a lot of margin on the right and left sides. This is not the case for other pages. Will create a branch and start working on a fix

**Comment by b18veran** [comment]
It looks like there are problems with max-width. If you reduce max-width to 350px from 400px, it fits most platforms. What do you think about it @HGustavs?

**Comment by HGustavs** [comment]
if nothing else is worse by that change i am fine with it.

Seems like it is only a problem for certain dugga views?

The most important one is file submission dugga as that is the one that is used in 90% of all pages.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
