### ISSUE TITLE
Hamburger menu items don't work in sectioned

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7277]
![Capture](https://user-images.githubusercontent.com/37834592/58020046-53a7bc80-7b07-11e9-87e2-db21686a796c.PNG)

Pressing item:
![Capture3](https://user-images.githubusercontent.com/37834592/58020050-55718000-7b07-11e9-8eaa-005748fd2089.PNG)

**Comment by b17annni** [comment]
Already fixed in #7082
