### ISSUE TITLE
Changing deadline of an item works strange

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#7294]
When changing the deadline of an item in sectioned, the outcome is not what you would expect. Instead of changing the deadline of that specific item, you change the deadline of that type of test which is chosen in the Link-dropdown when editing. 
For example, if I were to change this deadline, I would change the deadline of all tests with the link "Fan också". 
![image](https://user-images.githubusercontent.com/37799006/58024111-bf8f2280-7b11-11e9-819d-fef00c80ff36.png)
This does not seem intended.

**Comment by HGustavs** [comment]
Seems like a bug.... and a quite serious one at that.

Local changes are more acceptable, but a change that affects other seemingly unrelated items is a more serious issue.

**Comment by a17pongo** [comment]
can not seem to replicate this.. what is a link in this context? 
Because I can change deadline on a course as expected and from what I can find so far nothing else changes.

**Comment by a17pongo** [comment]
now I saw it, so if several course moments share a link, the deadline for all those moments seem to change. Is this expected?

**Comment by a17pongo** [comment]
after some more testing and spelunking I finally realized what these links are related too, ofcourse tests in the test service. so my only question at this point, should a link to a test be unique? as in you can only link a test once to prevent linking the same test and thus it should fix this issue?

**Comment by a17pongo** [comment]
So after doing some spelunking into this issue the result is this: 

The database is not designed to be able to modify deadline the way that it is currently designed. There seems no way to distinguish between listentries when it currently does not exist (or the database do not prevent the existens) of more than one entry with the same lid. Each entry have a uniqe id but as far as I can see this ID can not be used.

**Comment by a17pongo** [comment]
You can only change the deadline of a test but currently the system is designed to be used this way and no other way. I guess that it should not exist more than one entry that has the "Bitdugga 1" test anyway, but if you want to be able to change deadline in any other way it seems like a big redesign might be needed. But there might exist a smarter solution too that I have not found.

**Comment by a17ludca** [comment]
"I guess that it should not exist more than one entry that has the "Bitdugga 1" test anyway", this is true and it seems the tests are separate for each courseversion so this shouldn't be a problem as long as you update the courseversion. With that said, there really should be a way to copy the tests from one version to another since more often than not, the courselayout is similiar to the one before.

**Comment by a18jenro** [comment]
This is related to https://github.com/HGustavs/LenaSYS/issues/7912. I actually removed the option to set deadlines on items that are not tests. But this can easily be reversed if necessary.

**Comment by a17towan** [comment]
My question is, should it even be possible to go in and edit the link of a dugga? If there should not exist more than one entry that has the link "bitdugga1", why should we be able to change it on pre-existing duggas?

**Comment by a18jenro** [comment]
@HGustavs bump

**Comment by a18jenro** [comment]
Right now, one cannot change deadlines of things other than tests, so then this is not an issue anymore.
