### ISSUE TITLE
Sectioned - create better looking icons for access and test

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#7296]
![Screenshot from 2019-05-20 15-16-09](https://user-images.githubusercontent.com/37792222/58024354-4512d280-7b12-11e9-95cb-e9ccab50ab39.png)

Icons for acess and tests should be better looking and more unified to the other icons.

**Comment by c17julka** [comment]
It could be enough to recolor the current icons so that they are white instead of black / grey.

**Comment by HGustavs** [comment]
Very un-uniform look.

Same line-thicknesses and coloring for all ?

**Comment by a17pongo** [comment]
probably not, these first icons was created quickly with a mix of using points and fixed forms like rectangles. I rather leave this to someone that is better suited for creating good looking icons.

**Comment by a17poner** [comment]
https://gruppc.webug.his.se:20002/DuggaSys/codeviewer.php?exampleid=1625&courseid=2&cvers=97732
we swapped out our plug for this upload icon in codeviewer at least which would be my suggestion for files since a plug to represent files feels very unituiative.
