### ISSUE TITLE
Resulted: "Show teacher" does not work in filter

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#7301]
Teachers show from the start and checking the box does nothing.

**Comment by a17alian** [comment]
Related issue #7265?

**Comment by c17johha** [comment]
@a17ludca "Show teacher" do work for me

**Comment by a17amama** [comment]
@c17johha Does it work inside the "tratt" filter-list?

**Comment by c17johha** [comment]
@a17amama Yes. In my local server. I'm not sure if there is a teacher in the list on the webserver - datorgrafik, I believe that why nothing happens on the webserver

**Comment by a17ludca** [comment]
@c17johha You're right, don't know what happened but it seems to be working now.

**Comment by a17amama** [comment]
@b17timjo Do we close this issue?

**Comment by b17timjo** [comment]
@a17amama please direct such questions to @b17nicsv

**Comment by b17nicsv** [comment]
Closing this because it seems it works as stated above.
