### ISSUE TITLE
Remove counter columns for some tables

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7306]
Counter columns are superfluous in these tables:
![contribcounter](https://user-images.githubusercontent.com/37792198/58074055-8489ff00-7ba4-11e9-87ed-80f64b0217c1.PNG)

Maybe for the middle one it could be useful, but the top table will always have 5 rows, and the week table already has a week column with the same numbers.

**Comment by HGustavs** [comment]
Yes, I would hide the counter table in those cases.

**Comment by a16lisri** [comment]
Merged, closing.
