### ISSUE TITLE
Change 'week' in time sheet table

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7308]
Currently the week column represents the week of the year, derived from the date input in the time sheet data. I think I misinterpreted @HGustavs when I made this, a more relevant week number would be the week in the project, so week 1 is 2019-04-01 - 2019-04-08 and so on.

**Comment by HGustavs** [comment]
Course week is better.

We have the start date of the course, so it should be relatively easy to compute.
