### ISSUE TITLE
Add a total amount row in the contribution rank table. 

### ISSUE THREAD

**Issue by a16joare** [HGustavs/LenaSYS#7310]
The table foot on all table is not used for anything.. How about adding a total amount of the colums? This feature may not fit all tables but the all rank table on the contribution page should work fine. 

I thinking something like this:
![image](https://user-images.githubusercontent.com/49194898/58078587-62e24500-7baf-11e9-83cf-b09359019427.png)

The column names should also be changed if this is fixed..

**Comment by HGustavs** [comment]
Columns sums is built into sortabletable so its a good idea to utilize this feature in this place.

**Comment by a17poner** [comment]
@HGustavs I think we've managed to locate the inbuilt functionality but it requires a callback function to be provided sumFunc, but we have yet to find any documentation on what is expected to be returned by sumFunc. Is there any documentation available or coulnd you provide us with something about it?

**Comment by a17poner** [comment]
nvm I think we managed to do this and created a pr for the personalRanking table as the allranks one got lost in the merge and hasn't been merged back yet. see #7415
