### ISSUE TITLE
CodeViewer html(maybe others) can't handle escape \

### ISSUE THREAD

**Issue by a17poner** [HGustavs/LenaSYS#7315]
in Codeviewer when uploading a file (tried with html) that include a \n a alert error is thrown saying that the row could not be tokenized. 
`previewResult += dateValue+": Issue:"+issueValue+" - "+commentValue + "\n";`
this line when I tested with a random html file on my computer is displayed in the codeviewer as 
`previewResult += dateValue+": Issue:"+issueValue+" - "+commentValue +  ;`
and the line with a bracket ending below throws a tokenizer error.

**Comment by a17joaap** [comment]
Looking further into this it seems like it handles \n just fine, but throws an error when it encounters "\n".
