### ISSUE TITLE
Make sidebar sticky when scrolling

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7325]
If I have template 2 chosen, and scroll the right box to the side, this happens:
![codeviewersidescroll](https://user-images.githubusercontent.com/37792198/58084441-2d435900-7bbb-11e9-9954-471ab4ca59e3.gif)

Would be good to have the sidebar with the line numbers sticky to serve as a divider.

**Comment by HGustavs** [comment]
There must be a bug in the styling of template 2 then...

All the other views work as expected?

All views should work the same, and this does not seem right.

It is either a bug in this specific template or in all of the templates.

If it is specific to this template we can re-use code from some other better working template?

**Comment by a17joaap** [comment]
Getting this issue on all templates

**Comment by a17robes** [comment]
Couldn't find a solution for this.  Maybe assign someone else to try? @a17alevu

**Comment by a16joare** [comment]
I coundn't find a good way to solves this issue.  When you have multiple windows/boxes the code border just acting strange when scrolling horizontal . Not sure way it behaves this strange but it maybe have something to do with how the position of the window is readed when scrolling..  One idée is to move the scroll from the "box/window" to the text inside the box.. But then you need to add something that is pushing the scroll bar down to the bottom of the boxwindow.  I tried to implement this but coundn't get it to work.  Maybe someone with more experience can solve this one?

**Comment by a17joaap** [comment]
whiteTheme.css:

```
.codeborder{
  position: -webkit-sticky;
  position: sticky;
  height: 100%;

```

**Comment by a17joaap** [comment]
whiteTheme.css:

```
.codeborder{
  position: -webkit-sticky;
  position: sticky;
  min-height: 100%;
```

codeviewer.js (bottom of rendercode function):
```
	var borders = [...document.querySelectorAll('.codeborder')] 
	borders.forEach(border => {
		var parentHeight = border.parentNode.scrollHeight;
		border.style.height = parentHeight;
	});
```
