### ISSUE TITLE
Clear diagram empties localstorage

### ISSUE THREAD

**Issue by a17alfcl** [HGustavs/LenaSYS#7327]
Localstorage should not be able to grow too large. Undo should only work for a limited amount of steps as localstorage gets too large otherwise. As of now, clear diagram and "Ctrl + A --> Del" clears localstorage. This should not be the case as you might want to undo after clearing the diagram.

![localstorage](https://user-images.githubusercontent.com/49202727/58084384-0be26d00-7bbb-11e9-8bf9-05754d03a3e5.png)

After perhaps 150 or so, diagrams, the first should be removed each time a new is added. The localstorage should not be possible to clear manually as this is not necessary for most users.

**Comment by a17vikab** [comment]
Closing this issue because it isn't needed.
