### ISSUE TITLE
Contribution.php teacher user rankings view table bug

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#7328]
When scrolling horizontally the table breaks...
![image](https://user-images.githubusercontent.com/49199993/58084598-7d222000-7bbb-11e9-930d-835e1f80dbcf.png)
see gif...
https://gyazo.com/6acd15a875c22d83e8bc99d2078cd43a

related https://github.com/HGustavs/LenaSYS/issues/7324

**Comment by a16joare** [comment]
Hmm.. Is this even an issue? The table should not be so big that you need to scroll horizontally? 
Any thoughts @HGustavs ?
