### ISSUE TITLE
Can't hover over sort / filter dropdown in resulted

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#7345]
![image](https://user-images.githubusercontent.com/37792321/58094423-ee200280-7bd0-11e9-81cf-ec0724a5b9c7.png)
Dropdown menu disappears too quickly when hovering over the sort / filter icons, making it impossible to reach.

Perhaps this could be solved by moving the onmouse-events to the td element, instead of the span element.

**Comment by a17amama** [comment]
Both accessed and resulted use the same code for the navbar, however they seem to behave differently, even though both are affected by changes. Fixing one, ruins the other. Reason is unknown.
