### ISSUE TITLE
Contribution can be viewed outside of created dugga

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7352]
By just accessing contribution.php you can view it outside a real dugga. Not sure if this is intended

**Comment by a17maxsj** [comment]
I dont think this should be possible

**Comment by a16lisri** [comment]
What do you mean with this? Could you provide me with an image maybe?

**Comment by a16lisri** [comment]
@b17carma @a17maxsj

**Comment by b17carma** [comment]
Usually when you want to view the contribution page, you would do it through a dugga set up to use thed contribution template. When you access the dugga, it would look something like:
![image](https://user-images.githubusercontent.com/37834592/58182740-73c5b000-7cae-11e9-8356-2a11a1798665.png)

However, by just going directly to contribution.php, you can view the contribution page outside of a dugga:
![image](https://user-images.githubusercontent.com/37834592/58182826-98ba2300-7cae-11e9-880e-d25fb8d9c7f3.png)

I think it shows a blank page if you haven't accessed the contribution page through the dugga first however. This gif should sort of explain it:
![Y3o8l807429](https://user-images.githubusercontent.com/37834592/58183194-31e93980-7caf-11e9-9f71-7c3697f99215.gif)

Instead of showing the contribution content when you access it outside of a dugga, I think it should show a blank page instead.

**Comment by a16lisri** [comment]
Okay I understand now! Thanks for that :)
