### ISSUE TITLE
sorting and filter dropdown, bad position

### ISSUE THREAD

**Issue by c17johha** [HGustavs/LenaSYS#7353]
Dropdowns are placed far from the hoverlogo. When moving mouse to the dropdown, the dropdown disappear.
![image](https://user-images.githubusercontent.com/49199825/58097353-773a3800-7bd7-11e9-93f7-d2f6ed29ea28.png)

**Comment by c17johha** [comment]
Earlier the position was changed in this pull:
#7172

**Comment by b17nicsv** [comment]
Duplicate of #7345
