### ISSUE TITLE
Contribution.php github contribution color scheme changes

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#7358]
Currently this section looks like this:
![image](https://user-images.githubusercontent.com/49199993/58120746-2988f400-7c06-11e9-962c-035f7137bc6b.png)

I would argue something like this would look nicer.. thoughts? darker or brighter color could be argued and/or changing the text color. 
![image](https://user-images.githubusercontent.com/49199993/58120921-81bff600-7c06-11e9-8264-3a185ad0f216.png)

**Comment by a16lisri** [comment]
Maybe a white or lighter gray colour would look good?

**Comment by b16johso** [comment]
I agree with @a16lisri. The dark gray doesn't look right, there isn't enough contrast. Needs to be a lighter color.

**Comment by a17maxsj** [comment]
Brighter? darker?
![image](https://user-images.githubusercontent.com/49199993/58172046-c6e03880-7c97-11e9-8147-a933d7122278.png)

**Comment by a16lisri** [comment]
Maybe we could actually have some colour here? I was thinking a lighter green. It will make it stand out.

**Comment by a17maxsj** [comment]
That could work, just something other than that yellow 😃

**Comment by a17maxsj** [comment]
Now a tint of the header
![image](https://user-images.githubusercontent.com/49199993/58173975-107f5200-7c9d-11e9-8496-18b97ad545e7.png)

**Comment by a16lisri** [comment]
I still think it looks too dark in contrast to the gray background. It almost blends in.

**Comment by a17maxsj** [comment]
This was never implemented, feel free trying to find a good color and implementing it.
