### ISSUE TITLE
Unable to change title of a code example

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#737]
Cannot change the title of a code example using the big cogwheel. This attribute is named "examplename" in the database.

**Comment by HGustavs** [comment]
Are we having an issue about the naming of the column or that the database code does not use the correct name?

**Comment by f12danjo** [comment]
The issue of not being able to change the value of examplename in the database by using the webapp.

**Comment by a13alfbe** [comment]
Im working on this in issue #733

**Comment by a13jorla** [comment]
Closing cince a13alfbe has merged a solotion.
