### ISSUE TITLE
Searching in resulted no longer works

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#7376]
Leaves no error in console.

**Comment by a17adasy** [comment]
is related to the examinator dropdown. If you choose a examinator you can search. If the dropdown is on "none" you can not search anymore.

**Comment by a17amama** [comment]
The information provided by hovering over the questionmark does not seem to be something you can actually search for.

**Comment by c17julka** [comment]
Reopening this issue, since it seems to have reappeared. You can yet again no longer search if you have no examinator selected.
![image](https://user-images.githubusercontent.com/37792321/58420209-02f70d00-808d-11e9-8cda-a1d2c9b715c1.png)

**Comment by a17ludca** [comment]
Is this issue in progress? Im fairly certain that I know how to fix this.

**Comment by b17nicsv** [comment]
This works now on my test branch. Now testing another PR, will hold this open for now but this is most likely already sovled.

**Comment by c17julka** [comment]
@b17nicsv ^

**Comment by b17nicsv** [comment]
Should now work as intended with examiner/student filter.
