### ISSUE TITLE
MOTD button seems broken.

### ISSUE THREAD

**Issue by a17robda** [HGustavs/LenaSYS#7379]
![motdbroken](https://user-images.githubusercontent.com/37792328/58169236-8f21c280-7c90-11e9-9be0-c2e2266b77a3.png)

**Comment by a17pongo** [comment]
related to this issue #7329

**Comment by b17nicsv** [comment]
MOTD and Cookies are overlapping.

**Comment by b17nicsv** [comment]
Closing this, this will be fixed in #7329.
