### ISSUE TITLE
Searchbar doesn't work / does nothing

### ISSUE THREAD

**Issue by a17amama** [HGustavs/LenaSYS#7380]
The information provided when hovering over the questionmark are things you can't seem to search for, also, searching for things inside the searchbar doesn't seem to do anything.
![whyt](https://user-images.githubusercontent.com/37793130/58169593-69e18400-7c91-11e9-87c6-577a5fa717b5.PNG)

**Comment by a17pongo** [comment]
related to issue #7376

**Comment by b17timjo** [comment]
Since there is overlap with #7376, which has a PR, I'll close this.
Perhaps a new issue should be created for the hover-related stuff.
