### ISSUE TITLE
Hamburger menu icon styling have yet again big spaces on the sides of it.

### ISSUE THREAD

**Issue by a17oscno** [HGustavs/LenaSYS#7383]
![image](https://user-images.githubusercontent.com/49207814/58170397-9b5b4f00-7c93-11e9-9e12-b938c3359f2f.png)

The margin is possible to big again.

**Comment by a17oscno** [comment]
To make the Dropdown menu (called hamburgermenu) visible at all you need to either be on mobile (or simulate mobile in the browser) or make the window small enough for it to appear.

**Comment by a18jenro** [comment]
Hamburger menu does not exist any more. This is not an issue anymore.
