### ISSUE TITLE
No styling for "no access/no items" message in sectioned.php

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7384]
![Capture](https://user-images.githubusercontent.com/37834592/58170471-cba2ed80-7c93-11e9-8415-d862e27289a4.PNG)

I think this message could use some styling, maybe similar to how the bummer messages look.

**Comment by HGustavs** [comment]
Good idea.

**Comment by a17robda** [comment]
![noaccess](https://user-images.githubusercontent.com/37792328/59744724-7a2a5600-9273-11e9-9942-906dfddada54.png)
Modified the message to use styling similar to the bummer messages.
