### ISSUE TITLE
Esc button doesn't work when trying to close the Edit course version/Delete dugga dialogs in sectioned.php

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7385]
When trying to close the edit coruse dialog in sectioned.php by pressing the escape key, nothing happens.

**Comment by c17johha** [comment]
is it this dialog?
![image](https://user-images.githubusercontent.com/49199825/58174618-964fcd00-7c9e-11e9-921f-62b1d7444685.png)

Works here on chrome and Firefox.

**Comment by b17carma** [comment]
No, I mean the one in sectioned.php opened from the cog on the right of this picture:
![image](https://user-images.githubusercontent.com/37834592/58247765-b644c680-7d5a-11e9-9670-278cd0b17ceb.png)
