### ISSUE TITLE
The sorting and filtering dropdown menus are hard to use.

### ISSUE THREAD

**Issue by a17oscno** [HGustavs/LenaSYS#7386]
![image](https://user-images.githubusercontent.com/49207814/58170855-e75ac380-7c94-11e9-94a1-839c5985582a.png)

Both menues are again hard to use due to them being hard to get to before they close.

**Comment by a17anter** [comment]
This is a recurring issue. The gap between the icon and the drop-down is too big so it closes if you are not fast enough.

**Comment by c17julka** [comment]
#7345 discusses this

**Comment by b17nicsv** [comment]
Closing this because it overlaps with #7345
