### ISSUE TITLE
fileed - Stored file link in database is not removed when trying to delete a file

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#7389]
sub-issue of: #6935
Currently when pressing the delete file "trashcan" icon it does not delete the file link in the database. Code exist for this but do not work properly

**Comment by a18jonkl** [comment]
After looking into problem, my conclusion is that it is not a bug or something wrong with the code. This is a user privilege problem, where the user is not allowed to remove the linked file.
When looking at the code it uses a query `SELECT access FROM user_course WHERE uid=uid AND cid=cid LIMIT 1`, I manually checked this query with the user “brom” and he didn’t have the rights to remove the file link. I then inserted the `uid` and `cid` for brom in `user_course` with `'w'` access and as expected everything worked perfectly.
