### ISSUE TITLE
Contribution: Remove counter on "contribTsTable"?

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#7390]
Do we want the counter column for this table? (1,2,3 etc)

![counter](https://user-images.githubusercontent.com/37792690/58171292-f2faba00-7c95-11e9-86ee-89d42ac8688a.png)

**Comment by a17maxsj** [comment]
I dont think so

**Comment by a17poner** [comment]
hmm, not sure. There will be multiple entries per week so in that way it might matter a little bit but I'm not sure what its actually useful for here.

**Comment by a17alevu** [comment]
I feel like it is unnecessary.

**Comment by a17andby** [comment]
Not really a purpose for that right? So, I vote for removing it

**Comment by a17robes** [comment]
Let's remove it then

**Comment by a16lisri** [comment]
I'm on it!

**Comment by a17poner** [comment]
and its gone, maybe we could do the same thing for contribution table as well? since it has 10 rows every time and 10 weeks counting from 1-10 so there's two columns where the data in the cell is 1-10

**Comment by a16lisri** [comment]
Merged, closing.

**Comment by a16lisri** [comment]
Make a new issue for that and see what the others think? @a17poner
