### ISSUE TITLE
Transformation dugga starts too far to the right

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7400]
![Capture](https://user-images.githubusercontent.com/37834592/58173316-589d7500-7c9b-11e9-8371-a0a232e07955.PNG)

I think the submission buttons should be moved down slightly & the dugga content should start more to the left.

**Comment by a17joaap** [comment]
This is because there are two templates for this dugga: 'dugga4' and 'transforms-dugga'.
The one you are looking at is using the 'dugga4' template, and the one I fixed in https://github.com/HGustavs/LenaSYS/pull/6834 is the 'transforms-dugga' which doesn't have this problem.

**Comment by a17andby** [comment]
@a17joaap If I understand this correctly, the person who created this Transformation has used the wrong template (dugga4) and the correct template (transforms-dugga) has already been fixed?

**Comment by a17joaap** [comment]
Yes, well I don't know for sure why there are two, or which one of them is correct. I just assumed the one with the name 'transforms' was the standard one. Maybe we should copy paste from transforms-dugga so dugga4 is the same.

**Comment by b17carma** [comment]
I believe this dugga was created through the test data

**Comment by HGustavs** [comment]
Unclear what the difference between the two is... are they identical apart from alignment issues?

**Comment by a17joaap** [comment]
They are identical, the alignment issues were identical until #6834 where I fixed it for 'transforms-dugga'

**Comment by b18jonli** [comment]
Changed style justify-content to "center" and removed extra </div>.

**Comment by b18alegu** [comment]
This issue was merged into the W16 master. I'm closing this one now.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
