### ISSUE TITLE
Codeviewer maximize gets a a bit to big

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#7402]
Making it hard to press the buttons in the far left section. Perhaps make minimum size a bit bigger.
![image](https://user-images.githubusercontent.com/49199993/58173755-728b8780-7c9c-11e9-8c18-37f35ca3f754.png)

**Comment by a17alevu** [comment]
Yes, i agree. If not, then we should atleast to something about the "copy-buttons" that clip the title in the templates to the left.

**Comment by a17joaap** [comment]
This is dependent on browser window size and I think the reset button is a good enough way to fix this issue. I will however hide the copy button on "minimized" boxes.

**Comment by a17alevu** [comment]
That sounds good imo. @a17joaap
