### ISSUE TITLE
The popup about ownership for LenaSYS folder should only be shown if relavant

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#7419]

**Comment by HGustavs** [comment]
Screenshot?

**Comment by a17adajo** [comment]
![image](https://user-images.githubusercontent.com/49197690/58247290-9234b580-7d59-11e9-9b31-794a98e71233.png)

**Comment by a18kaswi** [comment]
So 

1: Check if permissions are sat (is it possible for javascript to detect O/S-level permissions for folder? - if not this can probably be closed).

Optional-additional feature:
2: Check O/S
3: If not show O/S-related setting.

Actually a little unclear if you need to change permissions on Windows. If Windows-installation even are within the scope.

@HGustavs @a97marbr hello! What are the scope of the LenaSYS-installation. What platforms are the installation supported on?

**Comment by a18kaswi** [comment]
Line 600 currently checks folder permissions, so its possible (on linux)

**Comment by a18kaswi** [comment]
https://github.com/HGustavs/LenaSYS/issues/8000

Related issue. Will need designs for supported O/S's

**Comment by a18kaswi** [comment]
` <?php
      echo PHP_OS_FAMILY;
?>`

Prints the family of O/S. i.e Windows, Linux or OSX. 

Will formulate different modals for each family in next step. Need to collect info on what to change in Windows first. Afaik I didn't have to change any permissions setting up the WAMP-stack.

**Comment by a18kaswi** [comment]
The last part that I can find that corresponds to the topic "The popup about ownership for LenaSYS folder should only be shown if relavant" is that the installer should test if permissions are already set.

There are code in current version at line 400

`# Test permissions on directory before starting installation.
    if(!mkdir("{$putFileHere}/testPermissionsForInstallationToStartDir", 0060)) {
      $errors++;
      exit ("<span id='failText' />Permissions on {$putFileHere} not set correctly, please restart the installation.</span><br>
        <a title='Try again' href='install.php' class='returnButton'>Try again.</a>");
    } else {
      if (!rmdir("{$putFileHere}/testPermissionsForInstallationToStartDir")) {
        $errors++;
        exit ("<span id='failText' />Permissions on {$putFileHere} not set correctly, please restart the installation.</span><br>
          <a title='Try again' href='install.php' class='returnButton'>Try again.</a>");
      } else {
        echo "<span id='successText' />Permissions on {$putFileHere} set correctly.</span><br>";
      }
    }`

That hopefully can be reused to make a quick fix for this issue. Top prio in comming week.

**Comment by a18kaswi** [comment]
Currently enabling modal in javascript and check is php.

**Comment by a18kaswi** [comment]
Reusing the function isPermissionsSat() specified in PR #9073 in the same way as we currently set owner and operatingSystem in the permissions-modal script. 

Then using the bool value to show the modal or not.

**Comment by a18kaswi** [comment]
Some trouble with first pr so #9093 holds the solution.
