### ISSUE TITLE
Button for choosing template

### ISSUE THREAD

**Issue by b13gusbe** [HGustavs/LenaSYS#742]
I will add a button for choosing which template you want to use.

**Comment by HGustavs** [comment]
What should the icon look like?

Also, the template selection code breaks if we choose a template if one has already been selected (it was assumed that you had to start over from scratch if you choose the wrong template). The main problem is that the template must be matched with a corresponding number of box items. If we have a template with 3 boxes we and we choose a template with only two, one row needs to be removed from the box table, and conversely, if we choose a template with four, an additional box must be added.

This seems like a good idea but both things must be changed at once, both the service file (to allow change of a template if one exists) and the user interface.
