### ISSUE TITLE
Zoom and Coordinates bar should be fixed positioned.

### ISSUE THREAD

**Issue by b17robev** [HGustavs/LenaSYS#7421]
Currently the Zoom and coordinates bar are absolute positioned, this leads to an error when rapidly resizing the browser window. The solution to this should be to change the position attribute to fixed.

![ugly](https://user-images.githubusercontent.com/37845511/58236462-3ceda980-7d43-11e9-9000-78cc3d171c5c.png)

**Comment by a17alfcl** [comment]
Should be fixed in accordance with issue #7423, as the coordinates bar perhaps shouldn't even be present on a small screen.

**Comment by b18simla** [comment]
I am unable to recreate the error with the method described. Is there another way?

Also, this could be solved by moving the zoombar up to the menu row. Maybe on the right side, just below the logout/login button? Same goes with coordinates, they dont have to be inside the diagram.

**Comment by a18antsv** [comment]
I think all of the elements that should be positioned on top of the canvas should be positioned relative to the canvas. Place the markup under the container of the canvas and give the container position relative while the elements are position absolute. This will make right:0; top:0; be the top of the canvas. This makes it much easier to position things.
