### ISSUE TITLE
Coordinates bar should be hidden in mobile-view

### ISSUE THREAD

**Issue by b17robev** [HGustavs/LenaSYS#7423]
Currently the coordinates bar are shown in mobile-view it should be hidden, since it is impossible to track a users fingers when its not on the screen. In the picture below it shows the last pressed point. The zoombar should instead cover a wider area on the mobile-view.

![ugly](https://user-images.githubusercontent.com/37845511/58236813-ff3d5080-7d43-11e9-80d1-964e711541fa.png)

**Comment by HGustavs** [comment]
Can someone clarify the "since it is impossible to track a users fingers when its not on the screen"  part. 

Isn the point of that box to show the current or last available coordinate?

**Comment by a17alfcl** [comment]
> Can someone clarify the "since it is impossible to track a users fingers when its not on the screen" part.
> 
> Isn the point of that box to show the current or last available coordinate?

It doesn't bring enough useful information to justify occupying such large part of the screen IMO
