### ISSUE TITLE
Can't move multiple objects at the same time anymore

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#7424]
![image](https://user-images.githubusercontent.com/49199287/58237532-92c35100-7d45-11e9-9108-5c0ac51cb8e8.png)
Here I have multiple objects selected.

![image](https://user-images.githubusercontent.com/49199287/58237594-c2725900-7d45-11e9-8c51-c2beff8d206e.png)
Then when I try to move any of the objects selected, it will move Attr 0 only. If I remember correctly, the moving of multiple object was working correctly in the past.

It seems to only move the first one created of all of the objects selected. Even when you try and drag one of the objects that were not created first.

**Comment by HGustavs** [comment]
This used to work for sure.

**Comment by a14oscna** [comment]
This is bug must have appeared recently, but we are not sure when. The issue also applies when Snap to grid is used, where you get the following error message:
![movegrouperror](https://user-images.githubusercontent.com/37793141/58240163-b937bb00-7d4a-11e9-8e81-9124d3ffb29c.PNG)
