### ISSUE TITLE
Important word overlaps highlight of other important word in the row above

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7429]
If I have two important words on top of eachother, the bottom one will overlap the highlight of the top one:
![impwordoverlap](https://user-images.githubusercontent.com/37792198/58239317-221e3380-7d49-11e9-93ac-566c10f8eecb.gif)

**Comment by HGustavs** [comment]
Unsure what the intended functionality would be?

How do we mean on top of eachother? Directly above or actually on top?

**Comment by a17joaap** [comment]
Maybe I was unclear. Method and namespace are important words in this example. The highlight is a purple line underneath the word. This purple line is hidden for the second 'method' as you can see in the illustration above.
