### ISSUE TITLE
The zoombar looks bad in Edge

### ISSUE THREAD

**Issue by a17jonro** [HGustavs/LenaSYS#7433]
In edge there is a bit of whitespace on the right side of the zoombar text and the slider seems completly broken.

![image](https://user-images.githubusercontent.com/49195133/58240995-5f37f500-7d4c-11e9-9453-ce0cdc783158.png)

**Comment by HGustavs** [comment]
Definitely not a priority as edge will be running webkit soon.

**Comment by a18antsv** [comment]
This works in the new version of Edge. Can be closed.
