### ISSUE TITLE
Code Viewer: The copy button doesnt dissapear when box is too small

### ISSUE THREAD

**Issue by a17fellu** [HGustavs/LenaSYS#7434]
Now when you press maximize the copy button gets hidden. But not if you resize the box by dragging. The copy button should get hidden when the box reaches a specific width

**Comment by a17fellu** [comment]
Working on this over at branch:

https://github.com/HGustavs/LenaSYS/tree/GruppC2019W22_7434

**Comment by a17fellu** [comment]
> 
> 
> Working on this over at branch:
> 
> https://github.com/HGustavs/LenaSYS/tree/GruppC2019W22_7434

The functionality works on this branch with new code pages but there is a bug which breaks old code pages

**Comment by a18jakme** [comment]
@d17marle test kommentar
