### ISSUE TITLE
Search bar in fileed has transparent/no background

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7443]
![image](https://user-images.githubusercontent.com/37834592/58248240-ea6cb700-7d5b-11e9-8fdc-1ece153da1df.png)

You also can't see the text you're typing in it:
![image](https://user-images.githubusercontent.com/37834592/58248334-20aa3680-7d5c-11e9-8f61-39a9ff2d600f.png)

**Comment by c17julka** [comment]
I can't replicate this in the Grupp B branch.

It seems to only appear in the Grupp C branch. I think this should be left in their hands.
