### ISSUE TITLE
Wrong cursor icon when hovering X button when viewing a submitted assignment in resulted

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7445]
![image](https://user-images.githubusercontent.com/37834592/58248682-0de43180-7d5d-11e9-961d-f2cce27701e0.png)

The cursor should have a pointer icon instead.

**Comment by b17nicsv** [comment]
Issue already fixed.

**Comment by b18veran** [comment]
We checked it and it is still solved. Shall we close the issue?
