### ISSUE TITLE
Unnecessary scrollbar when viewing assignment in resulted

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7448]
![image](https://user-images.githubusercontent.com/37834592/58248902-b2667380-7d5d-11e9-9c2f-f83e8412b62e.png)

I believe changing this would be as simple as removing "overflow: scroll" from the div "MarkCont"

**Comment by a17robda** [comment]
Changed overflow from scroll to auto instread of removing it completely in the event of overflowing content.

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
