### ISSUE TITLE
Suggestion: Remove handle part of filter icon in accessed

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7451]
At the moment it looks like this:
![image](https://user-images.githubusercontent.com/37834592/58249296-c494e180-7d5e-11e9-8231-6ffe27c9e928.png)

I think it would look better if you remove the handle part of the filter icon since I personally think it looks out of place. Quick mockup:
![Untitled-1](https://user-images.githubusercontent.com/37834592/58249872-4a655c80-7d60-11e9-86ce-a1b39b43dc7b.png)

I would like to know what other people think about this though.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
