### ISSUE TITLE
Making the "forgot password" window work

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#746]
Add the possibility to add a mail to a user in the database
Send password or a link to reset password to said mail

**Comment by c13chrjo** [comment]
This issue will be present after 10-04-2015 week merge

**Comment by c13chrjo** [comment]
There is already a column for mail addresses in the databases

**Comment by HGustavs** [comment]
Sending email is not supported by the system. Meaning that the current solution (mailto links) must be available as an option, perhaps sending email can be added as an optional solution somehow.

**Comment by HGustavs** [comment]
Not high priority as it is useless for us (we are the only konown user of the system at this point).

**Comment by a15tobli** [comment]
Closing issue as #1236 brings up the same issue and mail is not supported by the system.
