### ISSUE TITLE
Error message at resultED when opening submission

### ISSUE THREAD

**Issue by c17alepe** [HGustavs/LenaSYS#7462]
![image](https://user-images.githubusercontent.com/38323901/58254596-5e628b80-7d6b-11e9-9ba8-377b56c2e8c1.png)

When you click the fist next to the grading on a student, this error pops up

**Comment by a18ismca** [comment]
And what is the purpose of this issue? Do you want us to erase the error messages, or do you want to change the layout of something and so on? The purpose of this issue must be stated, even though it seems obvious.

**Comment by c14jonfr** [comment]
I'm not sure if this issue is relevant anymore. I can't seem to replicate it using the instructions described here.

**Comment by b18veran** [comment]
I close this issue as it is no longer relevant.
