### ISSUE TITLE
ResultED: Grading window is positioned poorly

### ISSUE THREAD

**Issue by c17alepe** [HGustavs/LenaSYS#7463]
![image](https://user-images.githubusercontent.com/38323901/58254723-a8e40800-7d6b-11e9-9597-57a143126d18.png)

When you click the fist at the grading in resulted, you get the students submission. When you then click the yellow fist button, a grade window appears. This window is positioned poorly. Maybe it should be more centered and smaller?

Screenshot of the problem
![image](https://user-images.githubusercontent.com/38323901/58254799-d7fa7980-7d6b-11e9-9ca1-607f9650e1db.png)

(Sidenote, a console error appears when you open the submission window. I dont think the error is causing this issues problem, so i have created an issue for that)

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
