### ISSUE TITLE
Creating a course with special characters can cause problems

### ISSUE THREAD

**Issue by b13johfr** [HGustavs/LenaSYS#747]
If the name of the course contains an " ' " for example, it does not work to edit the course.

**Comment by HGustavs** [comment]
Does the function use the sanitized ajax service?
If not, that may be the bug.
Otherwise this should be fixed in that function (e.g. AJAXService) so that all dialogs are fixed at once in all places.

**Comment by a13oscwe** [comment]
The regex fix seems like a good idea, it works and it allows only certain characters now which might be a problem depending on what we want. The problem that arises now is that you can add or edit a new course and if you use non-whitelisted characters(according to the regex) the course will still be created but with a blank name. If we could factor out this regex into it's own function and bind it to the save/create buttons and give some kind of "invalid course name" feedback that would be great!
