### ISSUE TITLE
Some tables are missing engine declaration

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#7476]
Add **ENGINE=InnoDB** to the three tables below

https://github.com/HGustavs/LenaSYS/blob/6c44353adf0f1ee490478c57b394054d24f9f980/Shared/SQL/init_db.sql#L21

https://github.com/HGustavs/LenaSYS/blob/6c44353adf0f1ee490478c57b394054d24f9f980/Shared/SQL/init_db.sql#L58

https://github.com/HGustavs/LenaSYS/blob/6c44353adf0f1ee490478c57b394054d24f9f980/Shared/SQL/init_db.sql#L81

**Comment by a18kaswi** [comment]
"You do not need to specify the ENGINE=InnoDB clause if InnoDB is defined as the default storage engine, which it is by default. To check the default storage engine, issue the following statement:"

mysql> SELECT @@default_storage_engine;
+--------------------------+
| @@default_storage_engine |
+--------------------------+
| InnoDB                   |
+--------------------------+
1 row in set (0.00 sec)
