### ISSUE TITLE
fileed, suggestion - prevent deletion on files that are in use

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#7478]
sub-issue of: #6935
It should not be possible to remove files to that links are broken and pages in LenaSys become 404. Not sure if this is possible, probably hard to implement but could be a good implementation to have in the current form of fileed.

**Comment by a97marbr** [comment]
Yes, determining if a file is in use is hard. Connection to a file can exist in a lot of places. I one want to pursue this issue, perhaps start with a "list all refs" for a file?
