### ISSUE TITLE
style.css - move inline styling to external css for proper project structure

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#7479]
sub isse of: #1778 #5731
Alot of css are inline css in the services which a lot of the times are unnecessary or overwritten by other css rules.
By doing this carefully it should slim down some of the code and maybe even remove duplicate code, if similar already exist in the global shared style.css

**Comment by a18kaswi** [comment]
#1778 - Original issue about CSS-mess. Closing this so the team of this year can go through the CSS when TIME is there.
