### ISSUE TITLE
The red cross for closing the window in the choosing template window does nothing

### ISSUE THREAD

**Issue by b13gusbe** [HGustavs/LenaSYS#749]
The red cross for closing the window in the choosing template window does nothing.

**Comment by HGustavs** [comment]
It could be a good idea to write a generic close window function to close any visible window. Thus reducing the need for remembering to add this code on every screen.

Im thinking some jquery magic, searching for some generic part of a window and closing any window that has one using css.

**Comment by HGustavs** [comment]
I dont think there are two windows open at once by closing anything that has 
```<div id='editContent' class='loginBox' style='width:464px;display:none;'>```
class loginBox we should close any dialog that is open.

We then need to change every close window x event to point to that function... e.g. if we call it closeWindows and put that in dugga.js in Shared it should automatically close any window if we add that function to the x button and while were at it also to the 'escape' key.
That way it would also close when we hit escape.

**Comment by HGustavs** [comment]
Sorr for making this issue MORE difficult, but it could reduce the code by at least 4 lines of code per dialog (assuming each function has only one dialog), probably a bit more. It is a question of adding 4 lines to save hundreds all over he code.

**Comment by c13caral** [comment]
I'm shutting down this issue because of the reason why this issue was created is already dissolved ie the red button with a cross now closes windows. I have instead created a new issue which then affects problmet with all the pop-up windows should use the same function to close the window

#794
