### ISSUE TITLE
After creating freedraw object, fillcolor should be white

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#7493]
The fillcolor is not white when the object is created, but if we refresh the site it will go back to white.

![image](https://user-images.githubusercontent.com/37792464/58315579-13e81a00-7e12-11e9-9dd1-9c3d626f4c99.png)

**Comment by a16jenja** [comment]
See the referenced issue for my comment on regarding this.

**Comment by a17drama** [comment]
If you create a text after you create your first free draw object it will get the orange color but after a refresh text gets white. Kind of hard to read and even find.

**Comment by a16jenja** [comment]
> If you create a text after you create your first free draw object it will get the orange color but after a refresh text gets white. Kind of hard to read and even find.

Try selecting the items after refreshing, I noticed that it turns orange again. Very weird.

**Comment by a17drama** [comment]
Done that already. I agree. Very weird. Waiting for an merge touching this before I dive into the issue.

**Comment by a17drama** [comment]
#7224 Seems to be the right cure for this. I can't replicate this anymore after it got merged. @a17vikab suggest we close this.

**Comment by a17vikab** [comment]
solved.
