### ISSUE TITLE
Problem when drawing free draw object

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#7494]
If you clear the diagram so it is completely empty and then draw a free draw object first, it will become filled in orange. Every object that is created after this free draw object has been created will also have this orange fill for some reason. What I have noticed is that the only way to replicate this issue correctly is to follow the instructions above.

![image](https://user-images.githubusercontent.com/49199287/58315522-ff0b8680-7e11-11e9-9d9b-b75a2a1d43ba.png)
Here the diagram is empty.

![image](https://user-images.githubusercontent.com/49199287/58315581-13e81a00-7e12-11e9-847e-2661a2e17cef.png)
Here is a visual after you do the instructions I mentioned above.

**Comment by a16jenja** [comment]
After I created this issue, I noticed this issue is similiar #7493 , but it does not mention the things I said above I feel like.

**Comment by a17vikab** [comment]
Everything will be solved in #7493.

**Comment by a17vikab** [comment]
This should be solved now.
