### ISSUE TITLE
Make better testdata for next year

### ISSUE THREAD

**Issue by b17nicsv** [HGustavs/LenaSYS#7496]
Improve the testdata for next year. Currently I know in Webbutveckling - Datorgrafik it is total anarchy in the testdata.

**Comment by b18alegu** [comment]
Maybe this issue should be split into multiple issues? Since according to the old labels it concerns at least Group 2 (ResultEd) and Group 3 (FileEd & SectionEd).

**Comment by b18alegu** [comment]
#7879 Handles the ResultEd-part of this issue.

**Comment by a18jenro** [comment]
As of now, Group 3 does not agree that Webbutveckling - Datorgrafik is total anarchy. However, we would like to add another course version in for example Webbprogrammering because Webbutveckling - Datorgrafik is the only course with two verisons.
