### ISSUE TITLE
Objects change color on mouse up

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7502]
Changes to orange color on mouse up
<a href="https://gyazo.com/86c33c9ab56b8bedc1d93ce98d7875a2"><img src="https://i.gyazo.com/86c33c9ab56b8bedc1d93ce98d7875a2.gif" alt="Image from Gyazo" width="1106.9999999999995"/></a>

**Comment by a17alfcl** [comment]
Should be fixed in Pull request #7514, issue #7498 is related to this one.
