### ISSUE TITLE
CSS Dugga: X button on Dugga Stats panel does not do anything

### ISSUE THREAD

**Issue by a17fellu** [HGustavs/LenaSYS#7508]
The button that should close the panel does not do anything. This is the panel i am reffering to and it is at the bottom of the page:

![Screenshot from 2019-05-24 12-27-15](https://user-images.githubusercontent.com/49202955/58321907-c8d50380-7e1f-11e9-93c0-75d05f02d029.png)

**Comment by a17robda** [comment]
How do you reproduce this? Is this for the highscores tab?

**Comment by a17fellu** [comment]
It is located in the bottom of the html css dugga page. Try pressing the X button. It does not do anything when i press it atleast

**Comment by a18sebka** [comment]
The X button seems to be working fine.
