### ISSUE TITLE
Accessed Sort dropdown, make responsive

### ISSUE THREAD

**Issue by ghost** [HGustavs/LenaSYS#7512]
The dropdown for sorting should be responsive in the same way the sorting dropdown is in resulted.
When there are a valid combination of radio buttons checked, the sorting should sort. No "sort" button is needed

Resulted:
![image](https://user-images.githubusercontent.com/49199825/58323795-52d39b00-7e25-11e9-9df6-74b7ec3c0078.png)

Accessed:
![image](https://user-images.githubusercontent.com/49199825/58323821-65e66b00-7e25-11e9-90af-7e7621355f9e.png)

**Comment by c17johha** [comment]
Solved in Resulted. Accessed still use old method

Accessed:
![image](https://user-images.githubusercontent.com/49199825/58408468-2a8aad00-806e-11e9-81dd-28563702043c.png)

Resulted:
![image](https://user-images.githubusercontent.com/49199825/58408565-5a39b500-806e-11e9-9c7a-3c8f72a75292.png)

**Comment by a17oscno** [comment]
This can easily be solved by just adding an OnMouseLeave on the dropdown that when called calls the sorting function that the sort button normally calls on.

**Comment by c17johha** [comment]
@a17oscno 
IMO sorting should rather be called when a button has been clicked.

**Comment by a17oscno** [comment]
@c17johha Both can be in use at the same time just like in the Resulted page.

**Comment by c17johha** [comment]
@a17oscno That will call sort twice. First when button was clicked, and later when dropdown leaves. 
Another scenario why I dont think sort onMouseLeave should be called is that if one has sorted for a column:
![image](https://user-images.githubusercontent.com/49199825/58556468-69f6fc00-821c-11e9-8a5c-c2778b684d79.png)
and then there are other sorting options in the sorting dropdown. If he accidentaly enter the sorting dropdown, he will lose that collumn sorting, and the dropdown sorting will be set.

**Comment by a17oscno** [comment]
@c17johha not necessary if both the button and onMouseleave have the functionality of closing the window it Will never so it twice and that Will Also solve the example you have because by just entering the menu and leaving you wont resort

**Comment by JohanHaggmark** [comment]
@a17oscno 
I'm not sure if we confusing each other. 
"not necessary if both the button and onMouseleave have the functionality of closing the window it"
The solution I suggest will not have a button that closes the dropdown.

"This can easily be solved by just adding an OnMouseLeave on the dropdown that when called calls the sorting function that the sort button normally calls on." This sounds like sorting is called when window is closing?

-----------------------------------------------------------------------------
Sorting should be called only when a radio button is clicked. 
OnmouseLeave only closes the dropdown menu and do not call the sorting function.

**Comment by c17johha** [comment]
@a17oscno 
I'm not sure if we confusing each other. 
"not necessary if both the button and onMouseleave have the functionality of closing the window it"
The solution I suggest will not have a button that closes the dropdown.

"This can easily be solved by just adding an OnMouseLeave on the dropdown that when called calls the sorting function that the sort button normally calls on." This sounds like sorting is called when window is closing?

-----------------------------------------------------------------------------
Sorting should be called only when a radio button is clicked. 
OnmouseLeave only closes the dropdown menu and do not call the sorting function.

**Comment by a18matna** [comment]
Issue seems to already be solved. Currently theres no "sort"-button, but a "toggle-all" button. It sorts on clicking radiobuttons. I would recommend closing this issue
