### ISSUE TITLE
Error on LenaSYS when switching between browser tabs.

### ISSUE THREAD

**Issue by a17oscno** [HGustavs/LenaSYS#7513]
When switching between browser tabs an error occur on lenasys.

![image](https://user-images.githubusercontent.com/49207814/58324125-3d12a580-7e26-11e9-9c92-e1145a0e9af7.png)

This error happens everytime you switch either back or from the LenaSYS tab.

**Comment by a17oscno** [comment]
This issue has to do with different extensions that browsers can have (like Adblock or enhanced debug tool for chrome). Don't know if this issue is necessary due to it not being a problem for everyone.

**Comment by a18jenro** [comment]
Could not reproduce the problem.
