### ISSUE TITLE
Add options for hiding tfoot in sortabletable. 

### ISSUE THREAD

**Issue by a17robes** [HGustavs/LenaSYS#7523]
As mentioned in #6877 it would be nice to be able to hide tfoot in certain tables, for example the empty one in duggaed.php. To do this, sortable table needs to add an option for it, like the ones that exists in the picture below: 
![image](https://user-images.githubusercontent.com/38004435/58327387-c5497880-7e2f-11e9-942c-46caec1843a8.png)

So it could for example be "hasFooter" that you could set to true or false when needed.

**Comment by a17alevu** [comment]
@a17joaap has solved this in the issue #6877. Just so you guys know.

**Comment by b17nicsv** [comment]
If it is solved then it will be closed! 👍
