### ISSUE TITLE
Inconsistent languages

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#7524]
In most views on LenaSYS, the words are written in English. 

Then there are some views which use Swedish instead. An example can be found looking at the resulted view, where the filtering labels are in Swedish. There might be more instances of this on other views, which should be located.

IMO, it should be consistent to use either Swedish or English, not both.

**Comment by b17annni** [comment]
I agree to this and make English the main language.

**Comment by b20eripe** [comment]
@a20behta , @c20adael I got this

**Comment by b20eripe** [comment]
Issue solved, three files updated

**Comment by a20behta** [comment]
Changes merged correctly and added into into weekly merge. 
Updated and closing issue
