### ISSUE TITLE
eventLIstener in diagram.php

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#7531]
There is an event listener that triggers clickEnterOnDialogMenu(ev) in diagram.php. This should be moved to the keyDownHandler that already exists instead of having several listeners.

**Comment by a18antsv** [comment]
This can also include cleaning up and fixing clickOutsideDialogMenu. This function does currently have no effect and it is a weird way of creating an event listener. The function is never called and the eventListener is removed around line 3950 for no reason. Have this functionality in the mouseupevt function instead. Check if the appearance menu is open and then close it if the mouse is released outside of the appearance menu (on the #appearance div).

**Comment by a18antsv** [comment]
Enter has to be clicked twice the first time with the current eventlistener as well. This should also be fixed with the new implementation.
