### ISSUE TITLE
Standard box sizes have been messed up in most templates

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7534]
For example:
![templatemess](https://user-images.githubusercontent.com/37792198/58346149-7238eb00-7e5a-11e9-9b82-ac090b56135d.PNG)

is this template:
![templatemessoriginal](https://user-images.githubusercontent.com/37792198/58346157-7a912600-7e5a-11e9-8e5a-7a88ee690591.PNG)

**Edit**: Just tried this with incognito mode with different results, incognito mode shows the correct box sizes. I believe this to be because of the use of local storage.

The code uses local storage to set and get boxes height and width values, along with the template ID. This should be fixed so that it requires the example ID too, otherwise every example that uses a specific template will have the same box dimensions.

**Comment by a17robes** [comment]
Tried to re-create this issue by creating a new codeviever and uploading a file to each box, but I dont get this error.. Should I do it in another way? @a17alevu tried the same but he didnt get the issue you describe either

@a17joaap

**Comment by a17robes** [comment]
Looks like this for me:

![image](https://user-images.githubusercontent.com/38004435/58418500-34210e80-8088-11e9-9820-68ab72cfdc29.png)

**Comment by a17joaap** [comment]
I can't reproduce this anymore, closing.
