### ISSUE TITLE
Code viewer crashes if link to image file is selected as preview

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7538]
Code viewer returns error and displays no items to edit if one selects a preview type

and selects a link to a locally uploaded png as the link

**Comment by a16joare** [comment]
Can you tell us more precisely how you did to get this error? I tried to upload a local png file and then load it inside codeviewer like this: 
![image](https://user-images.githubusercontent.com/49194898/58384244-db963680-7fdf-11e9-8f6c-7f9649e36919.png)

Here is a image of my screen after pressing

**Comment by HGustavs** [comment]
This error may have been fixed some time down the line, as I found the bug in the running system which is more like the code that you started with rather than the current code.

**Comment by a16joare** [comment]
Ok, i will close this issue since i can't recreate it.
