### ISSUE TITLE
Resulted. Tooltip when hover seachbar

### ISSUE THREAD

**Issue by ghost** [HGustavs/LenaSYS#7540]
Often Icons have tooltip when hovering over them. Would it be appropriate to have tooltip by hovering the searchbar instead of hovering the question mark.
+More clean
-Inexperienced user might miss it
 
less more clean:
![image](https://user-images.githubusercontent.com/49199825/58386352-ed3b0680-7ffe-11e9-9b4a-039e2ee61c9e.png)

Beautiful but unnecessary plotting:
![image](https://user-images.githubusercontent.com/49199825/58386368-0d6ac580-7fff-11e9-8895-24eac367b759.png)

**Comment by a17adasy** [comment]
I feel like the tooltip can get in the way if it is shown when hovering on the searchbar. Since you will probably leave your mouse on the searchbar after you have clicked and started typing. May just be me though.

**Comment by c17johha** [comment]
@a17adasy this typ of tooltip dissapears when typing

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
