### ISSUE TITLE
Problems with server settings dialog

### ISSUE THREAD

**Issue by a17adajo** [HGustavs/LenaSYS#7541]
Two problems depending on browser:

**Chrome: Dialog can be saved but read-only settings does not retain after page refresh**

![2019-05-27_09-18-31](https://user-images.githubusercontent.com/49197690/58402377-733b6980-8060-11e9-8fa4-0fc3cd1aa85d.gif)

**Edge: Dialog can not be saved**

![2019-05-27_09-16-32](https://user-images.githubusercontent.com/49197690/58402277-366f7280-8060-11e9-8aa1-d0be11a68dbe.gif)

**Comment by a18antsv** [comment]
This now works in new version of Microsoft Edge. This can be closed.
