### ISSUE TITLE
Emails are sent in plain text when pressing the "Mail Students" button.

### ISSUE THREAD

**Issue by a17oscno** [HGustavs/LenaSYS#7547]
![image](https://user-images.githubusercontent.com/49207814/58404319-2312d600-8065-11e9-8242-6d93cd522351.png)

When pressing the mail button the mails can clearly be seen. This should not be because someone with the right knowledge can probably get those.  The JSON message is also send in plain text.

This issue can mostly be solved in the "ResultedService.php" file in the "mail" request type.
The message sent is an array of all the emails. Encrypt this before sending it and make sure that it is decrypted before opening it in the e-mail application and that should solve it.

**Comment by a17adajo** [comment]
I think you are misstaken. 
The call to resultedservice is a POST request (wich hides the parameters, but are not secure network wise) and the production server uses HTTPS that encrypts the traffic between the client and the server. 
I do not think any further encryption is needed at the application level.

**Comment by a18eripi** [comment]
Investigating if what a17adajo claims is true

**Comment by a18eripi** [comment]
I have examined the packets with WireShark and can confirm the packets are transmitted with HTTPS and are encrypted. It feels silly to write an encrypter module for in-application communication, given that if this access exists security is already compromised.
