### ISSUE TITLE
accessed suggestion - close editing cell when clicking outside or clicking on a dropdown

### ISSUE THREAD

**Issue by a17pongo** [HGustavs/LenaSYS#7548]
At the moment, if you want to edit a persons name for example, the box for editng willl be open until you click the red cross. Even if clicking outside on another cell, you will just keep switching between editing different cells.
This may be a little counter intuitive, a suggestions could be that only one editing box can be opened at a time and immediately closed if clicking on any another(and clicking again on a new or same cell if you want to edit) element or by closing it with the red cross.

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
