### ISSUE TITLE
Appearance menu is empty when customizing UML-Class

### ISSUE THREAD

**Issue by a17jacsv** [HGustavs/LenaSYS#7550]
Appearance menu is empty when customizing UML-Class. And if you change and want to change again it's empty again. This has worked before and probably stopped working after todays recent merger: #7514.
![Skärmavbild 2019-05-27 kl  10 13 13](https://user-images.githubusercontent.com/37792795/58405596-1cd22900-8068-11e9-9adc-32b3f0418abe.png)

**Comment by a17vikab** [comment]
#7554 might be the solution to this. Let's wait and see if it fixes this problem or not.

**Comment by a17vikab** [comment]
solved
