### ISSUE TITLE
Title for warning triangle icons

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#7551]
Adding a title on hover for the warning triangles in sectioned would be a good idea, since the icon represents different things depending on where it's placed. 
This warning triangle means that the type is 'message', and is important
![image](https://user-images.githubusercontent.com/37792256/58405663-3f644200-8068-11e9-9b2e-a5d38ee1306a.png)

These triangles next to the deadline means that the dugga has been submitted after deadline
![image](https://user-images.githubusercontent.com/37792256/58405733-6c185980-8068-11e9-9c87-a4dc82de5b12.png)

A title with some clarification would be nice

**Comment by c17julka** [comment]
I agree that this is a problem. Another suggestion could be to create a new icon to replace one of them. It could be as simple as changing the red background to yellow.

**Comment by b17annni** [comment]
That sounds like a good idea

**Comment by a18jenro** [comment]
@HGustavs 
The warning triangles to the left of messages are shown when the message has a link.
Should the hover message really be "Important message"?

Here is the code that adds that warning triangle to a message:
![untitled](https://user-images.githubusercontent.com/62876507/78556092-a1f0a780-780e-11ea-9769-204f6934ca8a.PNG)

Are you sure that those triangles should even be there?

**Comment by a18jenro** [comment]
@HGustavs or @mbrohede 24 hour bump

**Comment by a18jenro** [comment]
Due to not receiving a repsonse, this issue was closed, the warning text was added. But a new issue was opened regarding the relevance of these warning triangles: https://github.com/HGustavs/LenaSYS/issues/8157
