### ISSUE TITLE
Change Appearance on free draw objects not working

### ISSUE THREAD

**Issue by a17vikab** [HGustavs/LenaSYS#7552]
when you dubble-click a free draw object and change the fill-color, you get error messages in the console and it won't work.
![image](https://user-images.githubusercontent.com/37792464/58406376-bf3edc00-8069-11e9-906f-43f01ce5a238.png)

There is also a console.log in the code which someone has forgotten to remove.
![image](https://user-images.githubusercontent.com/37792464/58406328-a46c6780-8069-11e9-8af7-0d1f0175b2bd.png)

**Comment by a17vikab** [comment]
Related to #7554.

**Comment by a17drama** [comment]
This one got solved by @a17alfcl while solving #7562 and we should close this one.

**Comment by a17vikab** [comment]
> This one got solved by @a17alfcl while solving #7562 and we should close this one.

Problem solved.
