### ISSUE TITLE
Toolbar label positions

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7559]
The toolbar labeling 
<img width="188" alt="toolbarLabelIssue1" src="https://user-images.githubusercontent.com/49199690/58411276-3aa58b00-8074-11e9-842c-dbf17e1bb750.png">
The labels should be next to each button instead of being in the corner as it is now
Related to #6699

**Comment by g18marma** [comment]
The label elements all have a fixed top position. When removing this the labels should be dynamically placed next to the buttons.

![Screenshot_20](https://user-images.githubusercontent.com/49142301/79441558-b0da1580-7fd7-11ea-9bf4-757b44b0bf58.png)
