### ISSUE TITLE
Create test data in the database for UMV. 

### ISSUE THREAD

**Issue by a13antda** [HGustavs/LenaSYS#756]
Make sure that we have data to test triggers.
all the tables need data.

**Comment by a13erilj** [comment]
Try to add data that represents a real scenario as much as possible.

**Comment by c13marme** [comment]
Added test data to a separate file. Only umv will have access right now to that data.

**Comment by c13marme** [comment]
Added Students
Added courses
Added Classes
Added Teacher
Added Course requirements
Added subparts
Added student results
