### ISSUE TITLE
Problem with global appearance after clearing local storage and refreshing the page

### ISSUE THREAD

**Issue by a16jenja** [HGustavs/LenaSYS#7562]
![image](https://user-images.githubusercontent.com/49199287/58413329-c9b4a200-8078-11e9-8131-3aa6021aada9.png)
After clearing the local storage and refreshing the page and then clicking the global appearance option, an empty message pops up. I am guessing it should give the same message you get when clicking the change appearance option. See picture below for how it should look like.

![image](https://user-images.githubusercontent.com/49199287/58413404-f7015000-8078-11e9-8039-ad33076b2a31.png)

I have a question regarding this as well, should it not be possible to change the global appearance even if no objects have been created? Since it would be nice to able to change how all the future objects should be drawn before you start drawing. This is just an opinion though.

**Comment by a17alfcl** [comment]
Should be allowed at any time as global settings are stored in the settings array in localStorage.
All objects currently on the canvas should change settings and all future objects should get those settings as well, initially. If one object's appearance is changed it should override the appearance for that object until global appearance is updated again.
