### ISSUE TITLE
Invisible "add" and "edit" buttons in sectioned

### ISSUE THREAD

**Issue by c17julka** [HGustavs/LenaSYS#7565]
![image](https://user-images.githubusercontent.com/37792321/58415851-0932bc80-8080-11e9-912e-0101732621ae.png)
Unless you hover over these buttons and get this shadow effect, the icons for adding a course / editing a course are invisible in sectioned. This happens on smaller screens.

Solution suggestions:
- Make the icons purple
- Make the buttons have a (permanent) shadow effect
- Make it consistant to the hamburger meny: Add a purple background icon to them

**Comment by a17adasy** [comment]
For consistency the buttons should look the same on all screen sizes. Maybe having a small shadow effect all the time and not just on hover?

**Comment by b17annni** [comment]
#7701

**Comment by a18lukto** [comment]
This issue have been solved
