### ISSUE TITLE
Access editor, some "reset pw" buttons are purple

### ISSUE THREAD

**Issue by a17maxsj** [HGustavs/LenaSYS#7569]
![image](https://user-images.githubusercontent.com/49199993/58417091-08038e80-8084-11e9-82a9-962c0c43cafe.png)

**Comment by b18alegu** [comment]
Should this issue be closed? It is overlapping with issue #7722, but that issue is better specified. There is also a pull request in waiting from the previous year.

**Comment by a18eripi** [comment]
Closing due to overlapping and duplicating issue #7722
