### ISSUE TITLE
Refresh session X button has wrong cursor icon on hover

### ISSUE THREAD

**Issue by b17carma** [HGustavs/LenaSYS#7571]
The dialog:
![Capture](https://user-images.githubusercontent.com/37834592/58417097-0c2fac00-8084-11e9-95f4-ea21e5c90b9f.PNG)

At the moment it shows the normal mouse cursor, but it should have a pointer icon like the other dialogs

You can show the dialog by typing $(".expiremessagebox").css("display","block"); in the console

**Comment by b16johso** [comment]
Fixed
