### ISSUE TITLE
[SectionEd] Setting grade to U-3-4-5 in type Moment in Edit Item gives undefined

### ISSUE THREAD

**Issue by b17nicsv** [HGustavs/LenaSYS#7576]
Setting the grade to U-3-4-5 in type Moment in Edit Item view gives undefined (see Geometry 2HP).

![Like this](https://user-images.githubusercontent.com/49198878/58417843-5fa2f980-8086-11e9-9ee3-68d92a5bf7e7.PNG)

**Comment by a17adasy** [comment]
The problem here is that the text for U-3-4-5 isnt written on line 833.

**Old:**
`var strz = makeTextArray(item['gradesys'], ["", "(U-G-VG)", "(U-G)"]);`
**Fixed:**
`var strz = makeTextArray(item['gradesys'], ["", "(U-G-VG)", "(U-G)", "(U-3-4-5)"]);`

**Comment by c17julka** [comment]
Since the grades U-3-4-5 no longer exists, there shoulnd't be an option to set the grade to this in moment in the first place. So my suggestion would be to remove this option.

**Comment by a17adasy** [comment]
Alright, then this line needs to be changed (line 143)

`$("#gradesys").html(makeoptions(gradesys, ["-", "U-G-VG", "U-G", "U-3-4-5"], [0, 1, 2, 3]));`
