### ISSUE TITLE
UML TEXT size changes in a bad way with global appearance

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7583]
Either keep the text to the same size (as it was previously, uml text was always set to a standard size and not affected by global appearance changes), or change it so that the text is not as weird as in the image below.
![umlTEXTSIZE](https://user-images.githubusercontent.com/49199690/58422674-769c1880-8093-11e9-8db9-f31e07a84cc9.JPG)

**Comment by a18antsv** [comment]
This issue should be solved when solving #7645 probably. I don't see a point in making a fix for only this solution as it would need to be reworked by #7645 later anyway.
