### ISSUE TITLE
Global appearance form should show current settings

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#7586]
Currently the global appearance menu show "Choose [styling]". If you've made previous changes to the global appearance, these should be shown so you know which styling choices are active.
![Capture](https://user-images.githubusercontent.com/37792313/58422827-e0b4bd80-8093-11e9-8e7d-6a9c3c5b0eca.PNG)

**Comment by a18antsv** [comment]
This was fixed with the big rework of appearance menus for issue #5638.

**Comment by a18antsv** [comment]
There are other issues with global apperance menu though. 
-We need to know what will be affected by changes. Related issue #7645
-Global apperance is only affected if there are symbols in the diagram. It should always save even if there are no symbols drawn at the moment. Related issue #8067
-
