### ISSUE TITLE
Resulted, Filter "Show Student" & "Show Teacher" default mode

### ISSUE THREAD

**Issue by ghost** [HGustavs/LenaSYS#7598]
![image](https://user-images.githubusercontent.com/49199825/58457444-017a2300-8127-11e9-9963-3fbbdb4f1656.png)

Always when opening Resulted, filter checkboxes: "Show Student" & "Show Tacher" should be checked as default.

Now the boxes can be unchecked which leaves an empty table and that might be confused with that something is wrong.

**Comment by b16johso** [comment]
@HGustavs requested that the selected options in AccessEd should be saved in local storage. https://github.com/HGustavs/LenaSYS/issues/7264 Should probably be the same in ResultEd for consistency?

**Comment by a17adasy** [comment]
The filters should probably be saved in local storage on every page.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
