### ISSUE TITLE
More padding on new menu icons

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#7619]
The new menu icons would look better with a tiny bit more padding. The home icon and back arrow to the left is more spaced out and the menus icons should have a similar look. For example adding 2px to the menuButton class
Before:
![image](https://user-images.githubusercontent.com/37792256/58466013-29728200-8139-11e9-9fba-c22b986366e3.png)

After: 
![image](https://user-images.githubusercontent.com/37792256/58466160-69396980-8139-11e9-825f-b6bfa2a8b155.png)
The change is minimal but it looks better on the page in my opinion

**Comment by b17annni** [comment]
Agreed

**Comment by a18jenro** [comment]
Make sure that this change does not affect mobile view too much, for example by hiding dome icon.

**Comment by a18jenro** [comment]
Padding has already changed a whole lot. If this is still an issue for someone then they may reopen the issue.
