### ISSUE TITLE
Move icon is not in the correct position in FireFox

### ISSUE THREAD

**Issue by a16tobfr** [HGustavs/LenaSYS#7621]
<img width="89" alt="moveIcon" src="https://user-images.githubusercontent.com/49199690/58465818-bec14680-8138-11e9-9630-e70971fc0eda.png">

Perhaps make a class in the style.css to make sure that the icon is correctly placed in both FireFox and Chrome.

You can draw inspiration from the zoomSlider class which uses _'-webkit-'_ and _'-moz'_ in order to make the slider appear correctly for different browsers. This approach can most likely be used here as well.

~~~
/* The slider handle (use -webkit- (Chrome, Opera, Safari, Edge) and -moz- (Firefox) to override default look) */
.zoomSlider::-webkit-slider-thumb {
  -webkit-appearance: none;
  /* Override default look */
  appearance: none;
  width: 15px;
  /* Set a specific slider handle width */
  height: 15px;
  /* Slider handle height */
  border-radius: 50%;
  background: var(--color-primary);
  /*Purple background */
  cursor: pointer;
  /* Cursor on hover */
}

.zoomSlider::-moz-range-thumb {
  opacity: 1;
  width: 15px;
  /* Set a specific slider handle width */
  height: 15px;
  /* Slider handle height */
  border-radius: 50%;
  background: var(--color-primary);
  /* Purple background */
  cursor: pointer;
  /* Cursor on hover */
}
~~~

**Comment by a18antsv** [comment]
I think all of the elements that should be positioned on top of the canvas should be positioned relative to the canvas. Place the markup under the container of the canvas and give the container position relative while the elements are position absolute. This will make right:0; top:0; be the top of the canvas. This makes it much easier to position things.

**Comment by a18antsv** [comment]
Wait for #8196 to get merged to weekly branch and then create a new branch based on the weekly branch and make a solution for this out of that.

**Comment by a18antsv** [comment]
@a18andtu #8196 is merged so create a new branch from weekly and implement this. There is also javascript functionality setting position of moveButton. Remove this functionality (function setMoveButtonPosition and all places it is used) and use CSS to position it relative to the canvas for easy positioning of it.

**Comment by a18antsv** [comment]
#8091 fixed this completely. This can be closed
