### ISSUE TITLE
Always have "Show students" checked when entering Resulted

### ISSUE THREAD

**Issue by a17oscno** [HGustavs/LenaSYS#7622]
When you enter the result page nothing is shown (picture 1) because the option "show students" is not checked automatically. This can be quite confusing when you first open the page. Would probably be better if the option is "Checked" by default (picture 2). So that when you enter the page something is actually shown.

![image](https://user-images.githubusercontent.com/49207814/58466011-28415500-8139-11e9-9276-02f99940db3d.png)

![image](https://user-images.githubusercontent.com/49207814/58465901-ea443100-8138-11e9-961d-8c848a197202.png)

Files to change in:
resulted.js

**Comment by c17johha** [comment]
#7598 duplicate
