### ISSUE TITLE
Sectioned broken when logged in as student

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#7625]
Sectioned-view is not what it's supposed to be when logged in as a student, the icons for resulted, etc and the dropdown for courseversion is also showing which shouldn't be the case.

Testlogin: s94sveri, password

**Comment by a17joaap** [comment]
s94sveri has access type 'student teacher' for the Datorgrafik course, and is supposed to have access to certain things. See PR https://github.com/HGustavs/LenaSYS/pull/7293

This is my view when logged in with s94sveri:
![sveri](https://user-images.githubusercontent.com/37792198/58471925-55940000-8145-11e9-86d6-00fee36bf65d.PNG)

**Comment by a17ludca** [comment]
Hmm this is what i see 
![image](https://user-images.githubusercontent.com/37799006/58472935-b58ba600-8147-11e9-85c5-cb789459ac92.png)
Seems to be different on our groupbranches i suppose

**Comment by a17joaap** [comment]
Looked at it, it's because your branch removed the 'menuButton' class from the results, tests, and files table cells. This causes this:
```
document.querySelector("td.results.menuButton").style.display = "none";
document.querySelector("td.tests.menuButton").style.display = "none";
document.querySelector("td.access.menuButton").style.display = "none";
```

to fail.

**Comment by a18mahkh** [comment]
The issue description is a little bit ambiguous because we couldn't locate the issue "Sectioned-view is not what it's supposed to be when logged in as a student, the icons for resulted, etc and the dropdown for courseversion is also showing which shouldn't be the case."


@HGustavs @mbrohede

**Comment by a18felen** [comment]
This is not even an issue. What the person thought was an issue is not because a94sveri is not a student but a studentteacher. Because a94sveri has studentteacher its able to see navheader links for fileed and changeing the course version. @a18lukto

**Comment by a18lukto** [comment]
@a18felen Okay this does not sound like an issue then, do you believe we should close this or have you seen any other issue similar to this?

**Comment by a18felen** [comment]
I have not been looking for any similar issues but the issue that they are describing here is not an issue and i think it should probably just be closed @a18lukto

**Comment by a18lukto** [comment]
I'm closing this issue because the issue seems to not be an issue
