### ISSUE TITLE
Changing "Delkurs" (moment) in Resulted do not work

### ISSUE THREAD

**Issue by a17oscno** [HGustavs/LenaSYS#7627]
![image](https://user-images.githubusercontent.com/49207814/58466946-0052f100-813b-11e9-917b-55631447cf9f.png)

This dropdown menu does nothing. With the possibility to filter out entire moments (and subparts of those moments) with the filter tool this menu might not be needed. Either remove it or make it work so that only the moment (delkurs) that is selected actually shows.

**Comment by a17pongo** [comment]
might be realted to my comment on issue #7629

**Comment by a17oscno** [comment]
Closing this issue due to it being wrong and not relevant. The issue #7629 is the new correct issue
