### ISSUE TITLE
Make it easier to see what alternatives are ment for "Ladexport" only

### ISSUE THREAD

**Issue by a17oscno** [HGustavs/LenaSYS#7629]
![image](https://user-images.githubusercontent.com/49207814/58467624-5aa08180-813c-11e9-9b71-d0c442e6fbcf.png)

The  dropdown menues for "Delkurs" (sub course), "Betygskala" (grade scale) and "Betygsdatum" are only used to decide which information to be used with the Ladexport button but that is not so obvious. It would be better if the order and styling of the options (and lad export button) were changed to make it more apparent that they are associated to eachother only.  This needs to be fixed mostly because it can be confused with sorting of filtering for the result table.

**Comment by a17adasy** [comment]
The three dropdowns to the left of ladexport (delkurs, betygskala,betygsdatum) all belong to the ladexport and are not related to the table. I suggest redesigning this instead so it is more clear.

**Comment by c17julka** [comment]
A suggestion would be to create some sort of border around the dropdowns / button which are related to the Ladexport function. So that it is boxed in, and looks like it belongs together (see Gestalt law: common region).

**Comment by a17pongo** [comment]
I think that dropdown is only used in ladexport. the same is for delkurs and betygsdatum? 
What they should do now is giving the user a way to choose what data you want to export.

**Comment by a17oscno** [comment]
@a17pongo That seems to be the case so I will remake the issue into making it easier to understand that these tre alternatives are for the Ladexport only.

**Comment by a17oscno** [comment]
Changed the issue due to the old one being wrong.

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
