### ISSUE TITLE
'fab Button' does not work properly on mobile!  i SectionED.php

### ISSUE THREAD

**Issue by a16hiwah** [HGustavs/LenaSYS#7636]
on desktop is working fine by hover on it but not on mobile!
![Screenshot_20190528-113759_Chrome_LI](https://user-images.githubusercontent.com/37792852/58470882-ef0de280-8142-11e9-85e4-2e6c96eefd0d.jpg)

**Comment by a18oscba** [comment]
Testad, funkar och ser bra ut!
