### ISSUE TITLE
Wrong options loaded in the appearance menu

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#7638]
![image](https://user-images.githubusercontent.com/46029340/58467828-a94e1b80-813c-11e9-8d38-99142b919d1d.png)
When opening the appearance menu for a free drawn object it's not loading current settings. Picture has an object with white fill but the menu says black.

**Comment by b17robev** [comment]
The fix is probably to retrieve values from the selected object in "loadFormIntoElement()" in diagram.js

**Comment by a18antsv** [comment]
This was fixed with the big rework of appearance menus for issue #5638
