### ISSUE TITLE
Alignment possible with one object selected

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#7646]
Alignment menu should be grayed out as long as there is less than two objects selected and the same goes for the shortcuts. Requirements for the alignment is to have at least two objects selected. Bad thing with it at the moment is that it triggers SaveState() for no good reason and that is not good.

**Comment by a16tobfr** [comment]
The same is true for Distribute, this should also be grayed out when only one object is present.
However, distribute does not trigger SaveState().

**Comment by a17okaoz** [comment]
![b1](https://user-images.githubusercontent.com/37792681/58544848-63f42180-8202-11e9-805d-5a7f9ec18d25.PNG)

Implement another IF-state below   if (selected_objects.length > 0) and write 
if (selected_objects.lenght > 1 ) { 
 align function
}

You can find this at diagram.js row 1531

**Comment by g18marma** [comment]
To fix this I've added an if statement with the condition (selected_objects.length > 1) with the functions that enable align and distribute. This will cancel out the align and distribute options in the menu as long as the selected objects in the diagram is less than 2.
