### ISSUE TITLE
Code Standard unclear

### ISSUE THREAD

**Issue by a13erisc** [HGustavs/LenaSYS#765]
code_standard.js doesn't refer or explain how to name our variables. In all of our three files (codeviewer.js, editorService.php and EditorV50.php) we have variations of variable names, as follows:
```javascript
var nameID; 
var nameId;
var nameid;
var nid;
```
We have to decide what convention to follow, to avoid further confusion.
Related to #622, #623, #624, #668

**Comment by c12jenek** [comment]
This is realated to all groups, the suggested variablestandard is small lowercase first word, uppercase first letter of new word; e.g. varableNameStandard

**Comment by a13arnhe** [comment]
Old issue, we can create a new issue for code standard at some point when other more pressing issues are not in priority.
