### ISSUE TITLE
New name for "Passed deadline" filter on resulted page

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#7659]
Maybe changing the name of the filter from "Passed deadline" to "Late submissions" or something similar is more appropriate 
![image](https://user-images.githubusercontent.com/37792256/58488573-e250b500-8169-11e9-8efd-0cf604d52b47.png)

**Comment by b18alegu** [comment]
This issue is solved and merged into the G2-2020-W14 branch
Issue will be closed

**Comment by b18alegu** [comment]
Pull request #8047 should be used by reviewers.

**Comment by b18alegu** [comment]
This issue was merged into the W16 master. I'm closing this one now.
