### ISSUE TITLE
Pop-up window when entering the codeviewer page

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#766]
The pop-up window that greets you when entering the codeviewer (EditorV50.php) should be removed. The same error is already displayed on the page "Bummer! Course or Code Example does not seem to exist!". So there is no need for a pop-up aswell.

**Comment by c12jenek** [comment]
Some of this code was lost with the command line commits, am creating pull requests with the found faults

**Comment by c12jenek** [comment]
The code for the pop-up window was not found, this issue should be resolved

**Comment by a13erisc** [comment]
Solved, as of #784
