### ISSUE TITLE
Sectioned Add tooltip to "change course version"

### ISSUE THREAD

**Issue by ghost** [HGustavs/LenaSYS#7661]
![image](https://user-images.githubusercontent.com/49199825/58540013-d06a2300-81f8-11e9-8feb-0078eaff466b.png)

A tooltip could be useful since every other icon has one.

**Comment by b17annni** [comment]
![image](https://user-images.githubusercontent.com/37792766/59662385-19d0e100-91ad-11e9-8726-f54600128fa3.png)
