### ISSUE TITLE
Problem with draw line in UML

### ISSUE THREAD

**Issue by a17celal** [HGustavs/LenaSYS#7664]
When you try to draw a line to an UML class and release the mouse outside the UML, no line is drawn (which is correct). However when you try to draw a line after this, something happens because you can't draw a single line.

**Comment by a17johpe** [comment]
Gif of problem:
![umldrawline](https://user-images.githubusercontent.com/37792313/58542292-99e2d700-81fd-11e9-84ad-e4c86361e675.gif)

Current workaround for the user is to deselect line button and then select it again, so it doesn't completely break the page.

**Comment by a17johpe** [comment]
Possible place in the code is in diagram.js -> function mouseupevt(ev) and might be related to _uimode_?

**Comment by a18antsv** [comment]
This also happens when the new line is released on top of another line or another symbol that is not UML class. This is also an issue that should be fixed. The reason for this is that uimode gets into the wrong state.

**Comment by a18antsv** [comment]
This issue is referenced in #7910.
