### ISSUE TITLE
One row too much is printed by sortabletable

### ISSUE THREAD

**Issue by a17ludca** [HGustavs/LenaSYS#7665]
In the pages resulted, fileed, duggaed and accessed one extra row is printed with no information in it.
Ex. 
![image](https://user-images.githubusercontent.com/37799006/58542919-b3385300-81fe-11e9-9cf7-b961f0976cf5.png)

**Comment by a16silph** [comment]
I'm struggling to find the real issue through **fileed, duggaed** and **accessed**. 
When using _"Add Dummy Empty File"_  button in all php files, nothing seems to happen. 
This could be a potential new issue that needs to be fixed before issue #7665 can be resolved.

![image](https://user-images.githubusercontent.com/49142660/79235637-2923c800-7e6c-11ea-80bc-c77ec0f9b303.png)
**Fig. 1** - Icon for _"Add Dummy Empty file"_ **is** missing and not functioning.

**Comment by a16silph** [comment]
While the buttons now work, "Add Dummy Empty File" doesn't seem to do anything after you have chosen a name for the dummy file.

**Comment by a18filkr** [comment]
Closing this since only dummy file isn't working and there is a new issue to solve this problem. Good job finding this! New issue reference : https://github.com/HGustavs/LenaSYS/issues/8103
