### ISSUE TITLE
Redesign the feedback log

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#7667]
When a student gets feedback on a assignment it looks like the screenshot below. I feel like this needs a redesign. 
![image](https://user-images.githubusercontent.com/37792256/58544016-cea45d80-8200-11e9-9612-974f9ddcf5c6.png)
Maybe making the popup window smaller and changing the look of "Date" and "Feedback" is needed. They do not need to take up that much space and the purple background makes them blend in too much with the popup window header

**Comment by a18oscte** [comment]
Better to wait until issue #8204 gets merged into the group branch to avoid merge conflicts

**Comment by a18oscte** [comment]
![jsjs](https://user-images.githubusercontent.com/49142069/79759344-dbe99f80-831e-11ea-83a9-631cd334ed29.png)
This is the new version.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
