### ISSUE TITLE
Accessed.php is a blank page, cant add any users.

### ISSUE THREAD

**Issue by a13chrju** [HGustavs/LenaSYS#767]
the only thing showing up when you go to this page is the name of user that is logged in

**Comment by c13chrjo** [comment]
This is false since the text "Toddler" is hardcoded into the webpage.
But otherwise yes. There should be content here. Just remember that oscwe have already merged the navheader into this php file.

**Comment by HGustavs** [comment]
Its important to use a testing link as the following. Also /Shared/ is missing. I get mine to work if I change the links in the header and use a test link like the following:
/DuggaSys/accessed.php?cid=1&coursevers=2013
...

```
	<link type="text/css" href="../Shared/css/style.css" rel="stylesheet">
  <link type="text/css" href="../Shared/css/jquery-ui-1.10.4.min.css" rel="stylesheet">  

	<script src="../Shared/js/jquery-1.11.0.min.js"></script>
	<script src="../Shared/js/jquery-ui-1.10.4.min.js"></script>

	<script src="../Shared/dugga.js"></script>
	<script src="accessed.js"></script>
```

**Comment by HGustavs** [comment]
The access ed should only work when supplied with a valid course link.

**Comment by c13chrjo** [comment]
You should now be able to add users to the access page.
