### ISSUE TITLE
Swimlanes bleeding out of container

### ISSUE THREAD

**Issue by a17alian** [HGustavs/LenaSYS#7671]
On Firefox the swimlanes bleeds out of the container and needs to be fixed. This is not an issue in Chrome
Firfox:
![image](https://user-images.githubusercontent.com/37792256/58544904-7ff7c300-8202-11e9-9411-c255d19fd4bd.png)
Chrome:
![image](https://user-images.githubusercontent.com/37792256/58544953-9e5dbe80-8202-11e9-813c-3ff584429c93.png)

**Comment by a17adasy** [comment]
I remember @a17ludca was working on this. He may have suggestions for a fix.

**Comment by a17ludca** [comment]
I did not come up with any solution for this but my theory is that the html loads before the script somehow which results in the container not scaling according to the contents.

**Comment by a18mahkh** [comment]
Is this problem already solved?? Because it seems working fine.

**Comment by a18jonkl** [comment]
When running Firefox browser( v75.0) everything is working as in the picture of the Chrome browser.
<a href="https://gyazo.com/03b307028b29959ca3725b24462a5afb"><img src="https://i.gyazo.com/03b307028b29959ca3725b24462a5afb.png" alt="Image from Gyazo" width="327"/></a>
