### ISSUE TITLE
Problems with changing appearance for text and other object simultaneously

### ISSUE THREAD

**Issue by b17robev** [HGustavs/LenaSYS#7677]
They don't have the same attributes so there are some null values, which causes problems. 
Works for global appearance but not for "change appearance".

**Comment by a18kaswi** [comment]
appearanceDiagram
#7677
#7928
#7645
#8067
#6888

**Comment by a18antsv** [comment]
Objects of the same type are fine to change appearance on simultaneously. Entities, relations and attributes are fine to change simultaneously as they have the same properties exposed for change. There are problems with attempting to change appearance for any other type of objects while also trying to change for another type of object at the same time as the properties are different. The form for the previously chosen object will be shown making it impossible to do changes for the other selected types if they have properties that the previously chosen do not have.

**Comment by a18antsv** [comment]
It would be good to fix the name field to accept multiple names separated by a character so all could be changed to something different at once. At the moment, all will get the same name.

**Comment by a18antsv** [comment]
It is unclear how this should be handled. Maybe it would be interesting to have a label in the appearance menu for all properties that will affect each type and show the properties for all object types selected.

**Comment by a18antsv** [comment]
I am thinking something like this to prevent any problems:
![image](https://user-images.githubusercontent.com/49121839/80153192-651e0200-85bd-11ea-8a09-fb0edb329f3e.png)

There should be collapsible elements each containing all the inputs that are common for the types the collapsible element represents.

**Comment by a18antsv** [comment]
This solution would be something similar to what I was thinking to do to solve #6888. In #6888 all advanced properties that are not important for the data model (styling) would be under another collapsible.
