### ISSUE TITLE
"Move" cursor type should be on movearound, not mouseup

### ISSUE THREAD

**Issue by a17johpe** [HGustavs/LenaSYS#7678]
When moving canvas with right mouse button, the cursor doesn't change while moving around, rather it changes to the correct cursor type on mouseup.
![cursor](https://user-images.githubusercontent.com/37792313/58546394-89365f00-8205-11e9-8da4-0f350e0a33dc.gif)

**Comment by a18andtu** [comment]
This already seems to be fixed, works as it should on my end, closing issue.
