### ISSUE TITLE
Student teacher won't be able to view sectioned

### ISSUE THREAD

**Issue by a17joaap** [HGustavs/LenaSYS#7686]
PR to fix this issue: https://github.com/HGustavs/LenaSYS/pull/7683 

In essence, just change these rows in sectioned.js
```
      document.querySelector("td.results.menuButton").style.display = "none";
      document.querySelector("td.tests.menuButton").style.display = "none";
      document.querySelector("td.access.menuButton").style.display = "none";
```
to
```
      document.querySelector("td.results").style.display = "none";
      document.querySelector("td.tests").style.display = "none";
      document.querySelector("td.access").style.display = "none";
```

**Comment by a18mahkh** [comment]
@HGustavs This issue is a little bit ambiguous, anyway I modified the code as it suggested but I see no difference on the interface.  

I could not find any HTML tags <td> and classes .results .tests .access in sectioned.php
