### ISSUE TITLE
Shortcut doesn't work

### ISSUE THREAD

**Issue by a17drama** [HGustavs/LenaSYS#7688]
Shortcut (Shift + C) for selecting class doesn't work when in developer mode and all tools are displayed.
~~~
    } else if (shiftIsClicked && key == cKey && targetMode == "UML") {
      document.getElementById("classbutton").click();
~~~
Some modification to this if statement is required to get this working correct.

**Comment by a18petha** [comment]
Cannot reproduce this bug. Have these options selected
![image](https://user-images.githubusercontent.com/49141878/78771224-2159b480-7990-11ea-8841-b6908d9a0297.png)

have tried with UML selected and deselected, in both scenarios the keybind works just fine
