### ISSUE TITLE
Progressbar nested in progressbar (G1N,G1F,G2F)

### ISSUE THREAD

**Issue by f13marhe** [HGustavs/LenaSYS#769]
Progressbar that shows both the overall progress of the program and in it shows the different course levels. How do we fix this?

**Comment by a13ottne** [comment]
Brohede really liked this mockup, is it doable whithin a reasonable amount of time?

**Comment by a13erilj** [comment]
Because of the fact that "feature freeze" is growing nearer i think that we will not be able to add this.
