### ISSUE TITLE
Mobile View: SectionEd. Hidden buttons

### ISSUE THREAD

**Issue by b17annni** [HGustavs/LenaSYS#7701]
When in mobile view buttons are "hidden"

![image](https://user-images.githubusercontent.com/37792766/59655378-5d6e1f80-919a-11e9-8fe2-6570070bc3d5.png)
![image](https://user-images.githubusercontent.com/37792766/59655544-fbfa8080-919a-11e9-826a-7b5582bbe987.png)

**Comment by b17annni** [comment]
Added background colour to keep style choices 

![image](https://user-images.githubusercontent.com/37792766/59656646-8a243600-919e-11e9-94f1-0c6b9005c955.png)

**Comment by a18lukto** [comment]
This issue has been solved
