### ISSUE TITLE
Contribution: padding differs from div to div

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#7710]
The header of "Weekly bar chart" is more towards the middle, if we compare that to the header of "Weekly line chart". They don't align with each other.

![differentpadding](https://user-images.githubusercontent.com/37792690/59676904-ea2fd200-91c8-11e9-83b5-ba4ab539cb7f.png)

**Comment by a20sacka** [comment]
Put a label "on hold". Cant finish issue today as contribution.php doesnt display anything due to database not having any test values.

**Comment by a20vicad** [comment]
Now with the contribution server up it was easily solved.

**Comment by a20behta** [comment]
merge in to master during weekly merge
