### ISSUE TITLE
Daily minutes: Border missing around delete cell

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#7719]
The delete cell ts doesn't have a border around it. It looks a bit strange in my opinion. The existing border is only around the outer part of the button.

![border missing](https://user-images.githubusercontent.com/37792690/59776603-669edf80-92b3-11e9-9369-4e9988e50f1e.png)

**Comment by a18kaswi** [comment]
Since students this year are very active finding new fun stuff to implement, i'm closing down some of the kompletteringar. These requests are not customer-specific.
