### ISSUE TITLE
Courseed: Alert messsage not centralized

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#7733]
The alert message that appears on the top of the courseed does not appear in the middle, as shown below in the picture.

![ba256e890463170487e8ac9e18a9943a](https://user-images.githubusercontent.com/37792690/60095419-caf7ee00-974e-11e9-8b63-4ee6a2a17af4.png)

**Comment by a18antsv** [comment]
The message appears in the middle of the available space though. Maybe it is desired to have it in the middle of the available space when taking the button in the right corner into consideration.

**Comment by a17robhe** [comment]
@HGustavs This issue seems to be solved with https://github.com/HGustavs/LenaSYS/pull/7734 should we still solve it? And if so see the above comment.

**Comment by a18kaswi** [comment]
> @HGustavs This issue seems to be solved with #7734 should we still solve it? And if so see the above comment.

Yes, this is fixed in current versions. Closing
