### ISSUE TITLE
showDugga: Timesheetprev is too small

### ISSUE THREAD

**Issue by a16lisri** [HGustavs/LenaSYS#7735]
The box, where you can see your submissions, is very small. You can only see two of the timesheets and then the third one gets cut. You have to scroll a lot to see them all.

![3047a36d4fffd44da515fe8c4e2059fa](https://user-images.githubusercontent.com/37792690/60110134-d9a0ce00-976b-11e9-923a-8dcbd62089ea.png)

**Comment by a18oscte** [comment]
#7735 The issue was already solved, nothing done.

**Comment by b18alegu** [comment]
I'll let the assignees from this issue in Group-2-2020 be responsible for the review instead since the issue was already solved.

**Comment by a18oscte** [comment]
The issue has been solved and only the necessery lines are edited.

**Comment by b18alegu** [comment]
I'll move this back to ready for review. Please provide the requested reviews.

**Comment by b18alegu** [comment]
This issue is solved and merged into the G2-2020-W14 branch
Issue will be closed
