### ISSUE TITLE
CourseED: MOTD close button

### ISSUE THREAD

**Issue by c17alepe** [HGustavs/LenaSYS#7745]
![image](https://user-images.githubusercontent.com/38323901/61692560-31603400-ad2e-11e9-88f9-9fccae507eb9.png)

The button looks cramped where it is right now. I think a simple x would look better

**Comment by a17robhe** [comment]
@HGustavs This issue seems to be solved by https://github.com/HGustavs/LenaSYS/pull/7746 should we still solve it?

**Comment by a18kaswi** [comment]
The "close"-button is stil there on current version. But i'm pretty sure these kind of design-changes should come from product-owners.
