### ISSUE TITLE
Need to press fail twice after recorrection

### ISSUE THREAD

**Issue by Twilice** [HGustavs/LenaSYS#7755]
Steps:
*Fail student
*Student submit again
*Fail student

Now grade is "reset", neither U or G is checked. Even if U was clicked the U grade is not set.

*Workaround is Fail student twice. Which gives the student an incorrect extra "times graded".

**Comment by b18jonli** [comment]
@HGustavs Could a solution to this be to reset the grade when resubmitting or would that create new problems?

**Comment by a97marbr** [comment]
I would not reset the grade on resubmitting.

I like the idea that the reset-click does not increase the times graded. 👍

**Comment by b18jonli** [comment]
Closing since this has been merged.
