### ISSUE TITLE
Minimize css (again)

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7764]
Before adding dark mode and other things to css we must first reduce the css as much as possible
* Redundant css - declarations that contains the same code as some other declaration
* Unused css - css that is not used in any place in a system populated with data
* Overwritten css - css that is always overwritten by other css
* Optimizable css - joining similar styles, removing 

Are there other css optimizations

...

Removing a few different declarations and re-testing if the system works in the same way as before ... commit ... wash rinse repeat

**Comment by a18filkr** [comment]
Should whiteTheme.css be used with the regular css? To make switching between this and the future darktTheme easier. Or do you want the theme to not have anything to do with the css for now?

**Comment by HGustavs** [comment]
That was a "before dark mode was a thing"-thing. I would say that we want the standard mediaquery instead.

I would excise those files entirely and solely rely on mediaqueries as discussed in another issue.
