### ISSUE TITLE
Inline file creation in file tool

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7766]
An option for creating dummy empty files (for later editing) by pasting or writing information into file editor view.

For example if one selects create file (+) in fab?

A dialog then appears that allows the user to write a file name + a file type

**Comment by a18mahkh** [comment]
Is this a good solution? We might need a icon for the button.

@HGustavs @mbrohede 

![Anteckning 2020-04-06 141350](https://user-images.githubusercontent.com/49142349/78557278-c64d8380-7810-11ea-8309-a292917f7705.png)

**Comment by a18mahkh** [comment]
![Anteckning 2020-04-06 142752](https://user-images.githubusercontent.com/49142349/78558388-bc2c8480-7812-11ea-9e63-ae694a281095.png)

**Comment by HGustavs** [comment]
I would remove type and allow one to write greger.txt or greger.php in the file name box.

Also make sure that we are calling the service for creating files in fileed, so that we are not writing new code for the same task.

Figure out the interface in fileed.php if there is a need to synchronize with another group for adding more functionality (if some functionality is missing) please create issues accordingly and link to this issue.

Im thinking that we can also split the fab buttons and the dialog and the calling of file-ed in separate issues.
