### ISSUE TITLE
Clean up pull requests

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7767]
Which pull requests are:

* Useful and can be merged without fuss (merge)
* Not very useful or can no longer be merged automatically (remove)
* Very stale (remove)

? 

What can be merged without issue and what do we need to remove

Triage.

**Comment by b18alegu** [comment]
I think this is an issue for all the issue managers. Maybe we should try to go through all the old pull requests together after our weekly merge on W15?

Unite

**Comment by b18alegu** [comment]
"Jag skulle säga att om det är så att en PR är **väldigt stale**, oklart vad den påverkar... så skulle jag sopa den no questions asked. Går ju ändå inte att merga in den utan att saker brejkar." @HGustavs 

All that are stale will be removed shortly.

**Comment by b18alegu** [comment]
Nice clean sweep @a17robhe. I'll close this issue.
