### ISSUE TITLE
Drag and drop file upload in code viewer

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7768]
I  want a feasibility study for drag+drop for file uploads in code viewer

If I drag and drop a php file to top right view in code viewer I want this file to be uploaded and automatically connected to this view.

Is this feasible without breaking current file upliad functionality?

**Comment by b17carbr** [comment]
@HGustavs as requested by the issue I've been investigating the feasibility of this functionality. I have looked over possible implementations of drag and drop functionality, investigated how to add the files to the database, and looked closer how to refresh the view of the code viewer. But I still lack knowledge in what is most important with this issue, i.e. how files actual get uploaded onto to server. I'm guessing there is some good example of this maybe using Ajax somewhere, but I have yet to locate it. If you know of any good example then please sent I my way, so I can quickly determine whether it is feasible.

**Comment by a97marbr** [comment]
Uploading a file is done by submitting a file using `form`

From fileed.php
```
            <form enctype="multipart/form-data" action="filereceive.php" onsubmit="return validateForm()" method="POST">
                <div>
                    <input type='hidden' id='cid' name='cid' value='Toddler'/>
                    <input type='hidden' id='coursevers' name='coursevers' value='Toddler'/>
                    <input type='hidden' id='kind' name='kind' value='Toddler'/>
                    <div class='inputwrapper filePopUp'>
                        <span>Upload File:</span>
                        <input name="uploadedfile[]" id="uploadedfile" type="file" multiple="multiple"/>
                        <div class="fileUploadInfo">
                            <h1>Allowed Files</h1>
                            <p>PDF, HTML, PHP, MD, TXT, JS, JPG, PNG</p>
                        </div>
                    </div>
                    <div class='inputwrapper linkPopUp'>
                        <span>URL:</span>
                        <input style="width:380px" id="uploadedlink" class="textinput" name="link"
                               placeholder="https://facebook.com" type="text"/>
                    </div>
                </div>
                <div id='uploadbuttonname'>
                    <input class='submit-button fileed-submit-button' type="submit" onclick="uploadFile(fileKind);"/>
                </div>
                <div style='display:none;' id='errormessage'></div>
            </form>
```

**Comment by a18filkr** [comment]
Can this issue be solved together with group3 who works with fileed? And get that implementation along with the fix to codeviewer to load that file on drag and drop.

Our biggest problem is the fileupload from codeviewer.

**Comment by a20willa** [comment]
We should make more research into this issue and find a way to allow such a feature. What is needed for this functionality? We may not use any framework (since we would lose control of code) except JQUERY since it is already in use in lenasys.

**Comment by a20willa** [comment]
We now have more info on how this might be viable. A similar function has been made in #11475 pull request, where the basic function is implemented. The steps of putting the contents of a file into the codeviewer needs to be added through other means, but this provides a solution to actually get the file into the browser.  

The code can be found in duggaed.js and duggaed.php

**Comment by a20willa** [comment]
These are the supported file types which will should be accepted when dropping into codeviewer. 
![image](https://user-images.githubusercontent.com/81626616/164400377-1a18c653-4269-4a2e-9a6b-81995f190397.png)

**Comment by a19xinhu** [comment]
I tried dragging and dropping an html file, and now lenasys opens that html file directly. I searched for the keywords "drag" and "drop", but couldn't find the corresponding function at js file.

**Comment by a20willa** [comment]
# Current status

- [x] Drag and Drop a file into code viewer
- [ ] Upload the file into the database
- [x] Set the file as the one to use in said code example

# Notes
I am currently using an IFRAME to show the fileed.php page, and trough it try to upload into the database. This is convenient since the edit button already has implemented partial functionality needed to correctly show an IFRAME with the correct metadata, and also eliminate importing all fileed files. From there, the file upload dialog may be shown and modified to use any file. 

The problem, however, seems to be the last step of uploading, which is the submit button. I have tried trough many means to activate it, and in all cases the file will NOT upload correctly. If the button is pressed manually, it WILL upload. 

I will look into this bug and if possible, resolve it. If nothing works, perhaps directly importing the fileed files is needed, although at the cost of more files to load.

**Comment by a20willa** [comment]
Apparently, when a form inside a IFRAME is submitted from any outside source, the `filez` array is empty, causing everything to break.
![image](https://user-images.githubusercontent.com/81626616/166222181-66a27284-e095-4fdb-a7f1-1e4df946c07f.png)

Here is a command which attempt to press the submit button inside the iframe:
`framecontent.document.getElementById("uploadbuttonname").childNodes[0].click();`

I will look further into why filez is broken here.

**Comment by a20willa** [comment]
# Updated status
- [x] System is working
- [ ] Can currently only drag and drop in one window, not all
- [ ] CSS for drag and drop

**Comment by a20willa** [comment]
With the help of @a20patpe, drag and drop is complete. It remains to see if it will work on the server however.

**Comment by a20willa** [comment]
For testing: 
1. Go into the webbprogrammering course
2. Go into PHP Example 1
3. Drag and drop any of the following file types into any window: `txt, html, js, php, java, sr, sql, md`
4. The file content should now appear on the code window
