### ISSUE TITLE
Lists generated by SortableTable sometimes has poor performance when rows increase > 100

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#7769]
For courses with many participants, more than 100 students, the access editor's lists generated by SortableTable that include operating system widgets such as buttons and dropdowns will have sluggish performance.

Perhaps change to a DIV with styling to mimic button appearance for `<button></button>`?

Perhaps implement a dropdown using HTML/JS instead of relying on the operating system?

**Comment by HGustavs** [comment]
We want a mock-up first as screenshot then as html before building into system.

**Comment by g18marma** [comment]
![buttonsToDivs](https://user-images.githubusercontent.com/49142301/78131983-3bd5e000-741c-11ea-961a-c2d956f9696c.png)

En mockup på hur Reset PW knapparna kommer att se ut efter de har ändrats till div-element

**Comment by HGustavs** [comment]
if select tag is used for dropdown this will result in poor performance since it has to go via the os to display the dropdown. 
I suggest using some kind of div/span based css dropdown list instead as this does no use operating system widgets.

important that it does use a self contained solution e.e. as much css as possible to avoid complicated javascript solution...

**Comment by HGustavs** [comment]
this may be split into more than one issue if needed...

**Comment by a18petha** [comment]
![image](https://user-images.githubusercontent.com/49141878/78253979-824b3d80-74f5-11ea-940d-54218017d45c.png)
current design for dropdown menu.

there still some functional requirement that needs to be implemented
*Last modified needs to interact with new dropdown menu
*Style the new dropdown element
*Implement the solution for other dropdown elements within the table
*Implement cap for how many dropdown menus that can be open at a given time

is this the intended solution we are looking for?

**Comment by a97marbr** [comment]
There seems to be a bit of overlap for the dropped down part, but otherwise I think it looks as it should

Also, should't the down-arrow be visible also after we have expanded the dropdown?

**Comment by a18petha** [comment]
Continued working on styling and implemented so the dropdown arrow is still visible during the expanded layout

![image](https://user-images.githubusercontent.com/49141878/78539420-d48ca700-77f2-11ea-9ee4-3ca663293f27.png)

is this something we are looking for as the final product?

**Comment by a18kaswi** [comment]
@a97marbr @HGustavs !

**Comment by a17robhe** [comment]
Left for group 2 to investigate and merge if they find it appropriate

**Comment by b18alegu** [comment]
I think it is best to create a new branch with fixes to make sure there are no conflicts. But probably most or some of the code written by @a18petha and @g18marma can be used.

**Comment by b18jonli** [comment]
This has been merged, closing issue.
