### ISSUE TITLE
Marking icon in top navheader is inconsistent with other icons

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7772]
We want suggestions for a better icon

**Comment by a17towan** [comment]
Here are some suggestions for a better "Marking" icon for the top navheader. Please let me know which one you like the most and want implemented or if you want changes to be made, or more suggestions.

![image](https://user-images.githubusercontent.com/49142028/78244717-7b68fe80-74e6-11ea-897d-20aee1e72a08.png)

**Comment by a17towan** [comment]
@HGustavs

**Comment by HGustavs** [comment]
Seems that the outlines are thin compared to the other icons.

To make them similar the lines must be **THICK**

Like the second/third ones the most.

It would be nice to see a screenshot with the second/third ions in place to gauge the similarities style wise.

**Comment by HGustavs** [comment]
<img width="836" alt="Screenshot 2020-04-03 09 40 32" src="https://user-images.githubusercontent.com/6978801/78336169-38169a80-758f-11ea-8032-23143ab446ad.png">

That catastrophy is what I gleen upon in my current dev branch of lena.

**Comment by HGustavs** [comment]
btw the contours of the test icon are also thin. Feel free to make a second issue for that ...
and while youre at it, make an issue for the vertical alignment of the dropdown... does this not look the same on your machine?.

**Comment by a17towan** [comment]
Yes, alright. Good feedback, I will make the icons thicker and focus on the second and the third one. 

Will make issue for the test icon. 

Will make issue for the dropdown as well. You mean that it is positioned too closely to the icons and to close to the roof, yes?

**Comment by a17towan** [comment]
Okay, here are three new suggestions for a thicker icon as well as screenshots of how it would look like next to the others.

### 1.  ![image](https://user-images.githubusercontent.com/49142028/78342455-9a749880-7599-11ea-947b-9972eee173e8.png)

### 2.  ![image](https://user-images.githubusercontent.com/49142028/78342504-aeb89580-7599-11ea-9164-9095bc110caf.png)

### 3. ![image](https://user-images.githubusercontent.com/49142028/78342563-c4c65600-7599-11ea-955d-fa917e5c8c03.png)

**Comment by HGustavs** [comment]
A little spacing around the pen would be appreciated so that we can more clearly see that it is a pen. Probably the second looks better with more spacing?

squint mode engaged.

**Comment by HGustavs** [comment]
btw now we definitely need a new issue for the man with pad icon (for tests), as it now does not conform to "the look"

**Comment by a17towan** [comment]
Yes, I've created an issue for the test icon. I agree it doesn't fit in with the rest of the icons.

This is the newest icon that has the changes made to the pencil to make it stand out more and look more like a pencil. I hope this is what you meant.

![image](https://user-images.githubusercontent.com/49142028/78357152-38c02880-75b1-11ea-839c-2a1d1360f642.png)

**Comment by a17towan** [comment]
I made another suggestion. Suggestion #10 @HGustavs 

![image](https://user-images.githubusercontent.com/49142028/78529784-abfcb100-77e2-11ea-89c4-906d771c2f45.png)

**Comment by HGustavs** [comment]
The thicker pad is gread but the pen is too small imho.

Perhaps the first icon with a bigger pen is better?

Right now we cant clearly identify the pen as a pen.

**Comment by a17towan** [comment]
First icon with bigger pen, icon #11

![image](https://user-images.githubusercontent.com/49142028/78544002-c8581800-77f9-11ea-9fa3-caaf659ba881.png) 

Alternatively, icon #12 with spacing
![image](https://user-images.githubusercontent.com/49142028/78544949-38b36900-77fb-11ea-810c-c01e6312e28f.png)

@HGustavs

**Comment by HGustavs** [comment]
Second one. Lets go with that one
