### ISSUE TITLE
Cloning a course version should be done as 1 transaction

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#7776]
When creating a new course version we have the option to clone from a previous course.

Currently if we specify a course version name that already exists we get a duplicate key error for the course name but the cloning of course is still done giving us duplicate entries in the course version that generated the duplicate key error.

Current code i believe does the following:
```
Create the new course version // Could generate a duplicate key error
Make a copy of all the sectioned-items, duggas, etc // This is done regardless of 
                                                    // the success of the previous 
                                                    // create operation.
```
Perhaps create a stored procedure for the clone operation and guard the whole internals of the procedure with a `begin transaction` and a `commit`? Other ideas?

**Comment by a18conch** [comment]
> When creating a new course version we have the option to clone from a previous course.
> 
> Currently if we specify a course version name that already exists we get a duplicate key error for the course name but the cloning of course is still done giving us duplicate entries in the course version that generated the duplicate key error.
> 
> Current code i believe does the following:
> 
> ```
> Create the new course version // Could generate a duplicate key error
> Make a copy of all the sectioned-items, duggas, etc // This is done regardless of 
>                                                     // the success of the previous 
>                                                     // create operation.
> ```
> 
> Perhaps create a stored procedure for the clone operation and guard the whole internals of the procedure with a `begin transaction` and a `commit`? Other ideas?

When creating a stored procedure in the database should we just edit the "init_db.sql" file and run a script against the test database or is there a better way of doing this?

**Comment by HGustavs** [comment]
Im not sure there **is** a good way to do this.

I would check beforehand if we probably are allowed to copy visavi the keys, and then initiate a transaction that i close when done with all...

but as to the best way to do this physically....

I think that this is a sort of-explorative issue to test if it is possible to get better than the current solition (not very good and definitively not fast).

**Comment by HGustavs** [comment]
Perhaps the keys-thing and the speeding process upp with transactions should be two different issues?

**Comment by a17robhe** [comment]
@o18marka You have to follow the code stadard, refactoring will break everything. Also, only use @o18marka& @a18conch to commit anything to github. Your work wont be tracked by the teachers if you dont.

**Comment by a18kaswi** [comment]
Safe to close. Should have been closed automatically when linked pull-request got merged. Closing now and investigating automatication closer.

**Comment by a18kaswi** [comment]
Nevermind, automatisation works but seems a little slower than me.
