### ISSUE TITLE
A hidden sectioned line has a too visible cog wheel

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#7777]
A hidden sectioned line has a too visible cog wheel

![Screen Shot 2020-03-25 at 10 23 57](https://user-images.githubusercontent.com/4948661/77524181-33632f80-6e87-11ea-8052-3ca283fa050b.png)

The cog wheel should have the same opacity as the rest of the line

**Comment by HGustavs** [comment]
Also the text is too invisible.

**Comment by HGustavs** [comment]
Either the text has a color that looks the same as some other color (like red and green?), or is it that it is too transparent?

**Comment by a17towan** [comment]
Which course is this screenshot taken from? I'm having a hard time finding it.

**Comment by a97marbr** [comment]
It was taken from the production system. Does the current master have a different implementation?

**Comment by a18oscba** [comment]
![image](https://user-images.githubusercontent.com/62877630/78371989-facefe80-75c8-11ea-8863-ae085c8bed00.png)
So when I change a current course or tab to hidden it still doesn't view as in the image describing the issue.
I suppose from what I can see the text might still need to be more visible?

**Comment by a17towan** [comment]
It seems like both the cogwheel and trash bin have the same opacity when you change a course to hidden
![image](https://user-images.githubusercontent.com/49142028/78531356-89b86280-77e5-11ea-866b-bbff44a45c3b.png)

**Comment by a18oscba** [comment]
Since it does not show as the image describing the issue and looks more like how the solution should look like I'm closing this issue.
