### ISSUE TITLE
The LADOK integration tool in ResultEd needs improvement

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#7778]
The LADOK integration tool in ResultEd needs improvement.

![Screen Shot 2020-03-25 at 10 56 29](https://user-images.githubusercontent.com/4948661/77524311-6dcccc80-6e87-11ea-994c-802e88e5ca3e.png)

* When choosing a particular **delkurs** this should filter the result view to only show those duggas present in that delkurs
* There should be added a checkbox with the option to filter away all the duggas except the **delkurs** dugga. 
* The correct **Betygskala** should be selected
* The deadline with the latest date should be pre selected as **betygsdatum**
* Default selection for **delkurs** should be "alla delkurser" with the **betygskala** and **betygsdatum** greyed out and none selectable
* The export button should conform to LenaSYS button style

**Comment by b18jonli** [comment]
@a97marbr 
The LADOK filters are not currently intended to filter the actual table, should this be changed? Maybe add a button that when clicked copies the LADOK-filtering to the table filtering?

**Comment by a97marbr** [comment]
Yes, changing from for example Laborationer 1,5HP to Analysis 1,5HP **should** re-filter the page to reflect this.

I would not have a button. When changing the LADOK-dropdown the filtering should be done automatically. (Minimize # clicks)

It could (should ?) however be consistent with the other filter functions. So for example, one approach could be to have a table filter `FILTER_X` option that shows a specific moment `X` with all its duggas (X.a, X.b, X.c, etc) -- and simply make the selected filter `FILTER_X` when the LADOK-dropdown been changed to `X`

**Comment by a19isada** [comment]
This is retired and will not be used when integrated with canvas. This will therefore be closed.
