### ISSUE TITLE
Course page link to teacher course system

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7784]
In the section editor teacher view we want to have a link to the course search page for the course.

This way we can easily find the course plan and list of registered students.

The link looks like this
https://personal.his.se/utbildning/kurs/?semester=20201&coursecode=IT385G

I think we already have the information needed in the database. So... what we need is to generate the link and come up with a new icon that is stylistically similar to the existing icons.

Suggestions for icons?

**Comment by a18andtu** [comment]
Lagt till en knapp för att öppna kurssidan (ingen funktionalitet just nu)

**Comment by a18andtu** [comment]
Does "semester=20201" in the url refer to year: 2020 term:1 or to something else?

**Comment by HGustavs** [comment]
I would assume it is study period, so it would mean January to march, presumably.

**Comment by a18antsv** [comment]
There are some problems with this solution which will be solved by issue #8138.
