### ISSUE TITLE
Resultedconstants

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#7785]
someone created a file resultedconstants that should not exist according to code standard....
so removing that and fixing any references to constants in that class.

**Comment by b18alegu** [comment]
This issue is solved and merged into the G2-2020-W14 branch
Issue will be closed

**Comment by a17pioja** [comment]
This issue's solution has been reverted due to merge conflicts during week 15
Re-opening issue

**Comment by b18alegu** [comment]
Reviewers should use the linked pull request #8056

**Comment by b18alegu** [comment]
This issue was merged into the W16 master. I'm closing this one now.
