### ISSUE TITLE
install.php not working for Windows systems

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#7787]
When running install.php on windows the Apache 2 log says:

[Mon Mar 30 12:00:21.221950 2020] [php7:error] [pid 12820:tid 1212] [client ::1:59588] PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in C:\Bitnami\wampstack-7.3.16-0\apache2\htdocs\LenaSYS\install\install.php:70\nStack trace:\n#0 {main}\n  thrown in C:\Bitnami\wampstack-7.3.16-0\apache2\htdocs\LenaSYS\install\install.php on line 70, referer: http://localhost/LenaSYS/install/

One should change posix_getpwuid() on line 70 to something that works on Windows as well. 

Stackexchange provides some hints towards how this could be done:
https://stackoverflow.com/questions/2197366/how-to-install-posix-in-php
On Windows, posix_getpwuid() is not implemented
if you just want the username of the current user, you can use get_current_user().
To properly get the running user, test if function_exists('posix_getpwuid') and if not, assume you're running on Windows and call getenv('USERNAME').

**Comment by a16silph** [comment]
Found a miss in the fix for making installations work on Windows computer. A + sign was missing, which broke things. I've created a new pull request to fix my mistake #8507.
