### ISSUE TITLE
Message of the day covered

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#7789]
After closing the message of the day and then editing the message, it apperas behind the header, making it impossible to see the full message without reloading the page. Make it not appear after change at all or appear at the right place.
![motd](https://user-images.githubusercontent.com/49121839/78128855-e8ad5e80-7416-11ea-839f-711c8f008077.png)

**Comment by a17robhe** [comment]
Mergat mot W14 branchen, inväntar intergration testing
