### ISSUE TITLE
Error when opening Resulted (Error reading user entries Unknown column 'UNK' in 'where clause')

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#7795]
When the resulted is opened (while logged in) an error message is shown, likely due to incomplete testdata or faulty search query.

<img width="1292" alt="Skärmavbild 2020-04-02 kl  10 36 30" src="https://user-images.githubusercontent.com/62876260/78227766-10abc900-74ce-11ea-9863-8c734eec8233.png">

**Comment by c14jonfr** [comment]
It seems like there is an error in an SQL-query on row 740 in resultedservice.php. The query was "SELECT DISTINCT examiner FROM user_course where cid=$cid;" where cid=$cid should be cid=:cid. This make the bindParam fail which makes the query fail and the error message is displayed.

**Comment by HGustavs** [comment]
I know why this happens.

The code reads from $cid but the course ed sends $courseid ...

change thegetop from $cid to $courseid and it should work again

**Comment by c14jonfr** [comment]
Just to clarify, do you mean row 34 "$cid = getOP('cid');"? gettheOP is only used for $visibleUserIDs.

Changing to "$cid = getOP('courseid')" does not seem to make a difference (alert still shows as before change).

**Comment by c14jonfr** [comment]
Our proposed solution (can be seen in linked Pull Request) was to change an SQL query at row 740 "...where cid=$cid;" which is incorrent, $cid should be :cid here. Before the change this would make the bindParam fail which in turn would make the queryexecution fail which displayed the error message.

It's possible the most correct solution would be to apply both of these changes, and possibly replacing courseid with cid (courseid is only used once for a bind at row 89, where it binds :cid to $courseid. Presumably using $cid would be the correct way.

**Comment by b18alegu** [comment]
@HGustavs can you please provide further input on this matter? Just like @c14jonfr stated the actual reason that the error message is shown is solved. If $cid actually should be $courseid I think is unrelated to this issue.

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
