### ISSUE TITLE
unable to access filerecive.php cid != courseid in fileed.php, filerecive.php, fileed.js

### ISSUE THREAD

**Issue by a18felen** [HGustavs/LenaSYS#7806]
The address for courses has been set to as an example `DuggaSys/fileed.php?courseid=3&coursevers=1337` where the `courseid` is the issue. It disables the access to filerecive.php so uploading files is not possible because the `filerecive.php` `fileed.js`, `fileed.php` refers to `courseid`as `cid`. A fix that would work for the files mentioned would be to change to `cid` to `courseid `unless this is a bigger issues and causes problems on other places in the system.

So the best fix would be to agree on whether `cid `or `courseid `should be used of all parts of the code to identify `courseid`.

Related to #7759

**Comment by HGustavs** [comment]
This has been a problem since 2015.

I think the time has finally come to fix it one way or another.

I would change at the bottom i.e. fileed. and not in courseed/sectioned since that would break a greater number of old hyperlinks.

**Comment by HGustavs** [comment]
Even better ... is to support both. If cid is present we use cid if courseid is present we use that ... in that case both versions would work.

**Comment by b18emigu** [comment]
We have commited a temporary fix on our working branch for the issue.
@a18lukto
