### ISSUE TITLE
makeLogEntry() declared twice in showDugga.php

### ISSUE THREAD

**Issue by b12erijo** [HGustavs/LenaSYS#782]
makeLogEntry() is declared in two files. /Shared/basic.php and /DuggaSys/basic.php
When both those files are included there will be an error, as in this case.

**Comment by a13oscwe** [comment]
Several files are essentially duplicates in /Shared/ and /DuggaSys/, it's probably a good idea to root out which files are actually used and start deleting duplicates to make the system more understandable. I.E. always use the file in the Shared folder and DuggaSys specific stuff should be in a file inside /DuggaSys/

**Comment by b12erijo** [comment]
Good idea, i will create an issue for it.
