### ISSUE TITLE
The dropdown icon in the header is not vertically aligned with the rest of the icons

### ISSUE THREAD

**Issue by a18fayha** [HGustavs/LenaSYS#7827]

**Comment by a18fayha** [comment]
![dropdowm](https://user-images.githubusercontent.com/62876354/78353520-7cfbfa80-75aa-11ea-8e1e-cda8f0f6386c.png)
As you can see in the picture the drapdown is not vertiacally aligned with the other icons. I think it's easily fixable by moving the Home and Back buttons slightly upwards.

**Comment by a18jenro** [comment]
This is being fixed in: https://github.com/HGustavs/LenaSYS/issues/7793
