### ISSUE TITLE
Markdown does not like the number 3 

### ISSUE THREAD

**Issue by a18abuah** [HGustavs/LenaSYS#7828]
#5462 
Markdown doesnt show number 3 in the markdown preview.
![image](https://user-images.githubusercontent.com/49142553/78348205-f0e5d500-75a1-11ea-9183-9011012e5d52.png)

**Comment by a18jakme** [comment]
Issue solved. Number 3 is shown in the the right way in list on the preview side. 
![image](https://user-images.githubusercontent.com/49142935/78646437-56df9e80-78b9-11ea-8352-a33ce9512069.png)
