### ISSUE TITLE
Color codes for HTML in Codeviwer should probably be different per tags

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#7836]
The coloring of HTML tags should probably be different for HTML, BODY, HEAD etc.
The current green color is also a bit unreadable with the white background
![image](https://user-images.githubusercontent.com/49141837/78360627-64461180-75b7-11ea-8b8d-e2a309cc3ca2.png)

**Comment by a18jakme** [comment]
@a18abuah Could you please put a screenshot on your result?

**Comment by a18abuah** [comment]
![image](https://user-images.githubusercontent.com/49142553/78555596-a9638100-780d-11ea-818c-fd246236de57.png)
@a18jakme

**Comment by a18jakme** [comment]
<header> and <link tags are in same color. 

![image](https://user-images.githubusercontent.com/49142935/78557690-84710d00-7811-11ea-82dd-1b7919b20ee4.png)

**Comment by a18jakme** [comment]
Header and link are in same color. 
![Skärmavbild 2020-04-06 kl  14 05 12](https://user-images.githubusercontent.com/49142935/78557948-0bbe8080-7812-11ea-8163-75e43da8c2d6.png)

**Comment by a18jakme** [comment]
coloring of "Hello world!" should be black, and "<" </>" of a title is blue.
![Skärmavbild 2020-04-06 kl  14 05 12](https://user-images.githubusercontent.com/49142935/78558053-3ad4f200-7812-11ea-8269-1b3c69911007.png)

**Comment by a18jakme** [comment]
In "HTML_Ex1.html" world and "<" "</" in title tags are blue.
![image](https://user-images.githubusercontent.com/49142935/78558507-fa29a880-7812-11ea-8772-4133bdd2b71a.png)

**Comment by a18abuah** [comment]
![image](https://user-images.githubusercontent.com/49142553/78563924-fc443500-781b-11ea-946b-815da9e682fb.png)
Link and header have diffrent colors.

**Comment by a18abuah** [comment]
![image](https://user-images.githubusercontent.com/49142553/78564030-25fd5c00-781c-11ea-9786-ed4880be0273.png)
And now "World", "<" and ">" have all black colors instead of blue.

**Comment by a18jakme** [comment]
Issue solved, different coloring for specific HTML tags. indentation of the code is ok and the functionality works fine.
![image](https://user-images.githubusercontent.com/49142935/78571838-fb64d080-7826-11ea-9ec1-3970372113b5.png)
