### ISSUE TITLE
Wrong username/name/lastname in update element

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#7846]
After updating username, name or lastname in accessed.php (or just clicking the green tick without changing) and then sorting the table and clicking on a username, name or lastname again, the previously shown name will be shown in the update element instead of the name in the cell clicked.

In this example: 
To begin with the cell of Peter was clicked to get an update element with Peter inside. The green tick of Peter was clicked without changing the name. The table was then sorted by first name by clicking on the first name column, making Alex be the first name in the list. When clicking on Alex in the first name cell, Peter still comes up in the update element. And the previous table order will be used for every row for the update elements. This only happens if the green tick is clicked.
![1](https://user-images.githubusercontent.com/49121839/78377156-8a77ab80-75cf-11ea-9ca1-ba9e5f27bf00.PNG)
![2](https://user-images.githubusercontent.com/49121839/78377162-8b104200-75cf-11ea-977c-653a1d93a709.PNG)

**Comment by b18jonli** [comment]
Duplicate #6068
