### ISSUE TITLE
Closing appearance menu with ESC can lock other shortcut keys in diagram

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#7847]
Clicking backspace or delete should after selecting a symbol or path delete it from the diagram. This works most of the time but there is one circumstance where it does not work which could be worth fixing. After opening the appearance menu for a symbol or path and closing the appearance menu by using the shortcut key ESC, it will no longer be possible to delete a symbol or path from the diagram by using the backspace or delete button after selection. Is the keyboard shortcut ENTER or the red "X" button in the popup used to close the appearance menu, no problem will be caused.

-Make the ESC shortcut key for closing the appearance menu not lock other shortcut keys after use.

**Comment by a18jonpe** [comment]
I'm having trouble finding where in the code it says escape should even close this window. It obviously does so it works, but I can't seem to find where this happens. Is this something done beyond the listeners in diagram.js?

**Comment by a18jonpe** [comment]
The function that allows the window to be closed seems to be closeWindows() in dugga.js. However, I'm having trouble seeing how this could possibly cause problems with deleting objects with delete or backspace. Since pressing delete or backspace only calls two functions, eraseSelectedObject(event); and SaveState();, there could be something going wrong that prevents the objects from getting deleted.

**Comment by a18antsv** [comment]
The problem is that the boolean variable appearanceMenuOpen will still be true after closing the appearance menu with ESC. When this variable is true the function keyDownHandler will stop executing without doing anything to prevent key shortcuts when the menu is open. The enter listener for closing is caused by clickEnterOnDialogMenu, hence are not affected by this.

**Comment by a17robhe** [comment]
New code for the dialog window means that this issue needs to be reworked
