### ISSUE TITLE
Need an icon prior to issue #7766

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#7856]
An icon for 'creating dummy empty files' if one selects create file (+) in fab

**Comment by a17towan** [comment]
Suggestions:
(The icons are off centered but there is an issue for that)

1.                                                      2.
![image](https://user-images.githubusercontent.com/49142028/79206771-1f846b00-7e40-11ea-82cc-ef37b1bc86cd.png) ![image](https://user-images.githubusercontent.com/49142028/79217836-c9b7bf00-7e4f-11ea-82de-b88b4e9afc83.png)




3.                                                      4.
![image](https://user-images.githubusercontent.com/49142028/79210137-aafffb00-7e44-11ea-9d96-848f1ade68fb.png) ![image](https://user-images.githubusercontent.com/49142028/79217408-1ea70580-7e4f-11ea-9e60-dd6976f0d3ce.png)

Personally I prefer 2 or 3.

**Comment by HGustavs** [comment]
My favourite is no 1 or no 2.
No 2 has lines that are too thick compared to the other icons?

**Comment by a17towan** [comment]
Yes, the lines of no. 2 do seem thicker compared to the other icons. 

This is another version of no. 2 with thinner lines. 

![image](https://user-images.githubusercontent.com/49142028/79318805-c41db000-7f07-11ea-8c33-2db000d67212.png)

**Comment by a18lukto** [comment]
I like number two the most, but as @HGustavs say the lines are a bit thick
