### ISSUE TITLE
Notice of MYSQL_VERSION break design

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#7868]
MYSQL_VERSION is already defined sometimes as it is defined every time the pdoConnect function is executed. A global variable should only be defined once otherwise it could cause problems. The design is broken because of PHP giving a notice of this.
This could be a problem only after PHP7 that is used now.
![Skärmklipp](https://user-images.githubusercontent.com/49121839/78542606-b2e1ee80-77f7-11ea-85f5-dfbcaf88c0b3.PNG)

**Comment by a18kaswi** [comment]
Again unclear why the merge hasnt closed this issue. Closing but have to investigate further.

**Comment by a18kaswi** [comment]
Didnt make it to weekly unclear why #7870

**Comment by a18kaswi** [comment]
Didnt make it to weekly unclear why #7870
