### ISSUE TITLE
Fab button opens on "background clicks" in mobile view

### ISSUE THREAD

**Issue by a18jonkl** [HGustavs/LenaSYS#7871]
In mobile view "fab button" opens when you click on the background.
![a4fae0928597a07e16a9c60c3aa9cdb8](https://user-images.githubusercontent.com/43996354/78546214-541f7380-77fd-11ea-911b-b030cf7a37c7.gif)

**Comment by a18oscba** [comment]
Works fine for me, the menu does not show up when I click on anything that isnt the fab button.
