### ISSUE TITLE
Opening Group(s) dropdown in AccessEditor changes the text of the dropdown from empty to "None"

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#7878]
If a user has not been assigned a group the value in the dropdown is empty. If the dropdown is opened but a group is not chosen the dropdown will show "None". This should be changed so that it is consistent. See screenshot where one user has blank in group(s) column while the other has "None".
![groupdropdown](https://user-images.githubusercontent.com/49141758/78554014-9b603100-780a-11ea-902e-cd3edfe4be26.jpg)

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
