### ISSUE TITLE
[accessed] Swedish characters get messed up when updating user data

### ISSUE THREAD

**Issue by a17pioja** [HGustavs/LenaSYS#7886]
![image](https://user-images.githubusercontent.com/49141519/78558866-a2d80800-7813-11ea-8711-fa7e478c588d.png)
___
![image](https://user-images.githubusercontent.com/49141519/78558834-95228280-7813-11ea-8dd7-facdb827b289.png)

When updating a user's data the swedish characters are represented incorrectly in the database.
The database supports swedish characters, but in the process of updating a user's data using the lenasys UI the swedish characters get messed up. 

The characters appear correct again when retrieved from the database to lenasys, but it's impossible to search for a name like "Åsa" using _SELECT * FROM `user` WHERE firstname='Åsa'_

To recreate:

1. Log in as a super user
2. Go to "Webbutveckling - datorgrafik" course
3. Press the padlock in the upper left
4. Update a users name or other detail using at least one swedish character

**Comment by b18alegu** [comment]
This was merged during W15.
