### ISSUE TITLE
It does not work to select the number of the template.

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#789]
Button to change the number of template functions correctly. You can select the number of template that you want. But nothing happens after you have selected, it presents no new templates, it does not remove the template.

In other words the main function to select the template does not work.

#742

**Comment by a13jorla** [comment]
Similar to #817 .

**Comment by a13jorla** [comment]
Solved the problem in editorService.php. One variable was referring to one by wrong name.
