### ISSUE TITLE
Warning of not being logged in is shown on mobile in Codeviewer

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#7898]
The following is shown for mobile users:
![https://i.imgur.com/GArEvTx.png](https://i.imgur.com/GArEvTx.png) 

This message is however not shown for users on a computer.

**Comment by a18abuah** [comment]
Is it better to remove the warning in mobile display or do you want the warning to be shown in front of the codeviewer.

**Comment by a18eliek** [comment]
It must probably solve some sort of purpose, however it's weird that this is only visible for mobile users and not users on desktop. Regarding that case I'd probably suggest it to be removed as it doesn't really serve any purpose.
