### ISSUE TITLE
Too many states of diagram is stored in localStorage

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#7902]
The diagram is saved as a new instance very often and the old one is not overwritten. This will cause localStorage to get full quickly (max 10MB) making it impossible to save new diagram changes to localStorage. The user could lose diagrams that have not been saved on file because of this. 
The way this is handled needs to be changed. Is it really necessary to save every single change as a new diagram in localStorage? Why not just save the latest version to make it possible to recreate it when the page is reloading.

However, undo (Ctrl + Z) and redo (Ctrl + Y) functions are using the localStorage diagram structure (number increment for each new diagram as key) to go between the diagram states. Another solution is needed for undo and redo functions to prevent localStorage from overflowing.

![Skärmklipp](https://user-images.githubusercontent.com/49121839/78638614-dc108680-78ac-11ea-9265-2dc43a4fc679.PNG)

**Comment by HGustavs** [comment]
Not  sure that is the exact problem.

**Comment by HGustavs** [comment]
We want the diagram to contain a reasonably complete state of the diagram up to that point

**Comment by HGustavs** [comment]
This is a KEY feature of this system.

**Comment by HGustavs** [comment]
This should not make use of several megabytes.

**Comment by HGustavs** [comment]
There are LOTS of issues that can be handed out for compressing this information by reducing the data without loss of information.

**Comment by HGustavs** [comment]
Also we want ONE diagram at at time. When we swap diagram it should be synched from file only one instance in local storage at a time.

**Comment by a18antsv** [comment]
@HGustavs That is probably true. The problem is not that the maximum storage capacity is reached. There is some problem though as the errror "Setting the value of diagramXXX exceeded the quota" appears when a certain amount of diagrams is stored in local storage. This error will cause the diagram to disappear for the user on refresh.

**Comment by a18antsv** [comment]
The exact problem should be identified and handled

**Comment by a18antsv** [comment]
@HGustavs Yes, I saw the other issue about that animation feature.

**Comment by b18phibe** [comment]
This issue are split in to several others like #8823 #8819 and #3744 
Closing this one
