### ISSUE TITLE
"Cannot read property" error in AccessEd table when clicking row numbers

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#7907]
<img width="551" alt="Screenshot 2020-04-07 at 10 40 00 AM" src="https://user-images.githubusercontent.com/62876553/78648472-4e3c9780-78bc-11ea-9b39-3e631244e47a.png">

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
