### ISSUE TITLE
Problem with draw line in diagram

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#7910]
This issue is related to issue #7664. When diving deeper into the problem of #7664 another problem was found. The problem occurs when trying to draw a line from UML class to UML class after an attempt to draw a line from UML class to line or UML class to other symbol different from UML class (that should not draw any line) has been made. This problem makes it impossible to draw a line between UML classes until the line drawing tool has been reset by clicking the Create Line icon twice or using Shift + L twice.

This gif illustrates the problem.
![problem](https://user-images.githubusercontent.com/49121839/78652487-16d0e980-78c2-11ea-9865-376e9c77814a.gif)

**Comment by HGustavs** [comment]
This sems like a bug to me?

There used to be the case that one had to push the line tool for each time that one wants to make a lne.

This was changed to be a bit more persistent.

Seems like that fix did not fix the whole problem.
