### ISSUE TITLE
A dialog pops out

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#7918]
When the fab button(https://github.com/HGustavs/LenaSYS/issues/7917) is clicked a dialog then appears that allows the user to write a file name + a file type

**Comment by HGustavs** [comment]
mock-up please.

**Comment by a18mahkh** [comment]
Mock-up example

![Anteckning 2020-04-09 100056](https://user-images.githubusercontent.com/49142349/78872097-09923700-7a49-11ea-9d1c-e158c079f5c5.png)
@HGustavs @mbrohede
