### ISSUE TITLE
Removal of stale branches

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#7921]
There are a lot of stale branches from previous years. I think it is about time to remove them all.

Any issue with that @HGustavs?

**Comment by HGustavs** [comment]
Only remove stale branches that are not documenting some important feature.

for example if someone put time into fixing for example postgres database functionality...
but failed 98% through that work.....

then a stale branch is the way that some torchbearer can continue the quest.

**Comment by b18alegu** [comment]
So far I've removed stale branches by theses criterion:
- More than 1000 changes behind the master branch
- Not able to merge
- Branches that display the following message: "There isn’t anything to compare."

Should I also delete branches that are already closed but are able to be merged to master? @HGustavs

**Comment by b18alegu** [comment]
I'll refrain from removing any more branches for now and will therefore close this issue.
