### ISSUE TITLE
Want to add a pointer-cursor on hover over the exit button. 

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#7923]
![image](https://user-images.githubusercontent.com/49142649/78669118-0ded1180-78dc-11ea-99d1-8d5e4c74d7dd.png)

**Comment by HGustavs** [comment]
Good idea.

Can it be done in css without changing the html?

As I fear that any change of html may result in divergence.

**Comment by b18veran** [comment]
Yes it's possible. I will fix it.

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
