### ISSUE TITLE
Cannot change line type appearance in ER diagrams 

### ISSUE THREAD

**Issue by a18andtu** [HGustavs/LenaSYS#7928]
When using the change appearance option for lines it is possible to preview the changes but when ok is pressed the changes are reverted back to normal.

**Comment by a18antsv** [comment]
Be more specific to which type of line this affects. I tested this and from what I could see, Entity -> Relation is affected by this but not the other two types of lines.

**Comment by a18antsv** [comment]
I am reworking the appearance menu for another issue which hopefully will solve this issue as well.

**Comment by a18antsv** [comment]
I have a feeling this is intentional and not an issue directly. The line should represent what the entity is representing. If the entity is strong then the line should be normal and if the entity is weak then the line should be forced.

**Comment by a18antsv** [comment]
Some kind of message would be good though to inform the user why the changes are reverted.

**Comment by a18kaswi** [comment]
appearanceDiagram
#7677
#7928
#7645
#8067
#6888

**Comment by a18antsv** [comment]
Issue #8387 was created to address further issues with this so this one can be closed.
