### ISSUE TITLE
Not every keyword in codeviewer links to relevant documentation

### ISSUE THREAD

**Issue by a18geoge** [HGustavs/LenaSYS#7933]
Some keywords from HTML and PHP are bugged and do not redirect to the appropriate documentation.
![popupdocumentationbug](https://user-images.githubusercontent.com/62876595/78673954-2ad91300-78e3-11ea-9ece-1a904c53a6df.jpg)

**Comment by a18eliek** [comment]
After some review of the work branch for this issue I've noticed that there's a bit of a limited range of tags that links to the documentation, a bigger list of possible tags that could appear is the following ones:
```br, basefont, hr, input, source, frame, param, area, meta, col, link, option, base, img, wbr, !DOCTYPE, a, abbr, acronym, address, applet, article, aside, audio, b, bdi, bdo, big, blockquote, body, button, canvas, caption, center, cite, code, colgroup, command, datalist, dd, del, details, dfn, dialog, dir, div, dl, dt, em, embed, fieldset, figcaption, figure, font, footer, form, frameset, head, header, hgroup, h1, h2, h3, h4, h5, h6, html, i, iframe, ins, kbd, keygen, label, legend, li, map, mark, menu, meter, nav, noframes, noscript, object, ol, optgroup, output, p, pre, progress, q, rp, rt, ruby, s, samp, script, section, select, small, span, strike, strong, style, sub, summary, sup, table, tbody, td, textarea, tfoot, th, thead, time, title, tr, track, tt, u, ul, var & video```
(list might include tags already included) 

it appears that https://www.w3schools.com/tags/tag_<TAGNAME>.asp can be used to link to most of these tags.
