### ISSUE TITLE
Closing an error message requires clicking on "ok" several times to be closed!

### ISSUE THREAD

**Issue by d18mohal** [HGustavs/LenaSYS#7934]
When  a user clicks on "Edit student result's icon" (see the figure below)
<img width="50" alt="Screenshot 2020-04-07 at 15 22 59" src="https://user-images.githubusercontent.com/47626561/78675900-fd419900-78e5-11ea-896a-6b1889174d20.png"> 
an error message appears to say "Error reading user entries. Unknown column "UNK" in "where clause" " (see the figure below). 
<img width="453" alt="Screenshot 2020-04-07 at 15 23 11" src="https://user-images.githubusercontent.com/47626561/78675905-ff0b5c80-78e5-11ea-9bc8-58c7b848ace7.png">
However, this message does not get closed by clicking "Ok" one time, but instead, the user needs to click several times to get the message closed .
It would be more user friendly if one would be able to close it by clicking "Ok" one time!

**Comment by HGustavs** [comment]
Im thinking it happens multiple times due to refreshes.

Question is why it refreshes the service after the alert.

**Comment by d17marle** [comment]
The error does not appear anymore, must have been fixed during earlier weekly merge!
