### ISSUE TITLE
AccessEd: when adding new users, the letters "åäö" are replaced with e.g. "&ouml;" in the database.

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#7945]
<img width="494" alt="Screenshot 2020-04-08 at 8 48 05 AM" src="https://user-images.githubusercontent.com/62876553/78753165-ab485400-7975-11ea-93d9-a6703a3c710b.png">
<img width="402" alt="Screenshot 2020-04-08 at 8 47 39 AM" src="https://user-images.githubusercontent.com/62876553/78753184-b0a59e80-7975-11ea-985f-ea35fd464075.png">

**Comment by HGustavs** [comment]
This is the way that we want it.

We want to avoid utf-8 characters in database as those characters are stored/retrieved wrong in some cases.

**Comment by HGustavs** [comment]
Was it fixed or made worse?

**Comment by b18jonli** [comment]
This has not been changed, closing the issue as the behaviour is intentional
