### ISSUE TITLE
Missing buttons in mobile view

### ISSUE THREAD

**Issue by a18jonkl** [HGustavs/LenaSYS#7950]
Mobile view:
<a href="https://gyazo.com/137d39543fe94d638fd5b9ebb604e557"><img src="https://i.gyazo.com/137d39543fe94d638fd5b9ebb604e557.png" alt="Image from Gyazo" width="378"/></a>
Desktop view:
<a href="https://gyazo.com/a9a1f44598b8b042e10e771151ab0994"><img src="https://i.gyazo.com/a9a1f44598b8b042e10e771151ab0994.png" alt="Image from Gyazo" width="523"/></a>

There is no way to access the missing buttons in mobile view.
Suggestion is to use a hamburger menu to access the missing buttons. Check issue #7516 for reference to hamburger menu.

**Comment by HGustavs** [comment]
Im fine with the buttons disappearing.

Since most of those buttons make little sense on mobile.

Better to have prioritized degrading with media queries than complicated dropdowns that are rarely used.

Out of those above the most useful in mobile for me would be home back and the drop down.

The other buttons lead to interfaces that make little sense on mobile?

**Comment by a18jonkl** [comment]
In my opinion I like having the same options on a mobile as in desktop view. 
But if you would like, the drop down could be moved up to the header and the newly added bar containing the edit/add course button removed with the bar.

**Comment by a18fayha** [comment]
So what is your conclusion?

**Comment by a18jonkl** [comment]
@HGustavs Would you prefer this solution for mobile view ? Now there is one home, back and the drop down.
<a href="https://gyazo.com/6a86bba8fb9293765e28a97661554aaf"><img src="https://i.gyazo.com/6a86bba8fb9293765e28a97661554aaf.png" alt="Image from Gyazo" width="378"/></a>

**Comment by a18oscba** [comment]
If you want the cog and plus button the navbar has to be extended in height.
Will not look too good.
