### ISSUE TITLE
Ability to create tables in markdown

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#7955]
There's currently no way of creating tables via markdown, this could be done in the following standard that is in markdown:

First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

Based of the following code:
```
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column
```
Description:
You can create tables by assembling a list of words and dividing them with hyphens `-` (for the first row), and then separating each column with a pipe `|`

This issue has been brought up before, but appears to be broken: ![https://i.imgur.com/slX8I8x.png ](https://i.imgur.com/slX8I8x.png)

#3121 has a pullrequest with an example but this is not working anymore.

**Comment by HGustavs** [comment]
I think table rendering may have been removed to handle nested bullet lists better.

Tables would be really nice to have in a consistent manner in .md
