### ISSUE TITLE
CodeViewer: Dropdown menu to control size of windows

### ISSUE THREAD

**Issue by a18jakme** [HGustavs/LenaSYS#7961]
Dropdown menu for every window with specific percent of width.
Screenshot example:
![image](https://user-images.githubusercontent.com/49142935/78767339-c2de0780-798a-11ea-852b-5581fb7d668a.png)

**Comment by HGustavs** [comment]
I dont know about this.

It feels cluttered to me.

**Comment by a18jakme** [comment]
@HGustavs You mean it's an unnecessary function? We discussed the minimize and maximize function. Maybe you don't want the window to be maximize or minimized but something specifik?

**Comment by a18filkr** [comment]
Closing this since customer didn't want this solution.
