### ISSUE TITLE
Settings in edit content should be correct by default

### ISSUE THREAD

**Issue by a16silph** [HGustavs/LenaSYS#7967]
Edit content window should have correct settings by default to display information. For example in **figure 1**, the file in _Webbprogrammering_ course in PHP 1 Example 1: PHP startup. The user has to configure the settings to **figure 2** to make the information from the file display correctly. The solution to the issue is to set/fix the correct settings by default for all edit content windows.

![image](https://user-images.githubusercontent.com/49142660/78563903-f3ebfa00-781b-11ea-9072-70e3fdd775b5.png)
**Fig. 1 - Settings**

![image](https://user-images.githubusercontent.com/49142660/78564141-49280b80-781c-11ea-975f-bdd9aa1f8999.png)
**Fig. 2 - Settings in edit content window**

**Comment by HGustavs** [comment]
Good idea.

However we cant know if for example a .js file is a preview or code... so there has to be some kind of heuristics.

Im guessing that we assume preview if bottom right and code in top right?

Or what are the heuristics?

**Comment by a18abuah** [comment]
I have looked into this issue and i dont find the necessity in changing the function if we cant tell when a file is preview or a code.

**Comment by a18filkr** [comment]
Closing since we decided not to add this.
