### ISSUE TITLE
AccessEd - click outside cell to close does not work after activeElement has been assigned

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#7968]

**Comment by HGustavs** [comment]
Outside cell is unclear, perhaps documenting this with a screenshot would be a good idea for  future reference.

**Comment by b18jonli** [comment]
This was a small fix to pull request #7861, should have linked the issue #7548 for clarity

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
