### ISSUE TITLE
New icon for the new Inline file editor in code viewer

### ISSUE THREAD

**Issue by a18jimol** [HGustavs/LenaSYS#7982]
![newbuttonedit](https://user-images.githubusercontent.com/49142669/78781957-781bba00-79a1-11ea-997c-4a669fe5ce66.PNG)
When creating the inline file editor in codeviewer for issue #7770 the icon from fileed was used. But there should be an new icon that matches the theme and looks better.

**Comment by HGustavs** [comment]
A pen icon is a good choice. 

Try to make it look like other pens in other icons.

**Comment by a18filkr** [comment]
When this is remade (to white as well) it should be resized to 24x24 to match other icons in that button menu.

**Comment by a18filkr** [comment]
This seems to be remade in our group, wait for merge to see if this Issue will be necessary after that remake.

**Comment by a17towan** [comment]
This seems to already be fixed. 

![image](https://user-images.githubusercontent.com/49142028/80575335-af5f1300-8a03-11ea-9bf4-d4c2029fcf78.png)

**Comment by a18jenro** [comment]
I'm assuming that it has been done then. Anyone who is not satisfied with the icon may open the issue again.
