### ISSUE TITLE
CodeViewer: Different sizes of the Titles

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#799]
![different-fontsizes-issue](https://cloud.githubusercontent.com/assets/11715479/7069480/5961f59c-ded9-11e4-847a-cdb3048758c3.jpg)

The fonts are of different sizes, should be a standard size

**Comment by c12jenek** [comment]
This is on exampleid 5;
http://webblabb.iki.his.se:8080/codesys/cv15/CodeViewer/EditorV50.php?exampleid=5&courseid=1&cvers=2013

**Comment by a12jiyba** [comment]
I have changed the font-size so it should be same size now.

**Comment by c12jenek** [comment]
Issue completed and merged into cv15
