### ISSUE TITLE
ResultEd not loading data from database

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#7994]
When opening the ResultEditor a mostly blank page is shown even though there is data in the database that should be displayed.

**Comment by HGustavs** [comment]
is the courseid/version matched correctly?
Are there studens?
Are there tests in this version of course.

I think that it is possible to pass this information to $debug to see what the underlying reason is.

**Comment by c14jonfr** [comment]
@HGustavs The data in the database is "complete" (i.e. there is data that should be displayed).

As can be seen in the linked pull request there was a querystring in an ajaxcall looking for 'cid', but the URL has no value for cid. This was changed to 'courseid' which solved the issue. Sorry if this was not documented properly. This has without a doubt been the issue with highest priority and biggest hurdle for Group 2 so far. Because of this we kind of fast tracked the issue so that we could get it ready for the weekly merge (of course it has been tested thoroughly to make sure nothing breaks).

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
