### ISSUE TITLE
Grading not working properly in ResultEditor

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#7997]
Pressing for example 'U' or 'G' will make a change in the interface but the grade is not inserted into the database.
The Grading window accessed by clicking the fist-icon does not work either.

**Comment by HGustavs** [comment]
Do we get any errors of any kind?

**Comment by c14jonfr** [comment]
@HGustavs I don't remember any errors, but I believe a few people who tested did get an alert about something with UNK and cid.. When refreshing the page none of the gradings were saved (= nothing was inserted into the database). The "Times Graded"-thingy would also not display properly, it would show up as "NaN".

You can see our solution in the linked pull request. We simply replaced every querystring['cid'], with querystring['courseid'] in resulted.js. The URL has a value for courseid but not cid, meaning the querystring couldn't find any value for cid.

**Comment by b18alegu** [comment]
Issue solved last week (W15 2020). I'm now closing this issue.
