### ISSUE TITLE
Faulty command shown to our dear MacOS users during install of LenaSYS

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8000]
Prior to starting the installation of LenaSYS, a warning message is shown with a command that is expected to be run. This command is wrong for MacOS users. In the screenshot below it says that the command should be:
`sudo chgrp -R www-data /…/LenaSYS`
but the correct command for MacOS users is:
`sudo chgrp -R www /…/LenaSYS`

<img width="1467" alt="Skärmavbild 2020-04-09 kl  08 47 15" src="https://user-images.githubusercontent.com/62876260/78867093-d6e44080-7a40-11ea-9384-5491edb0ccce.png">

Please make sure that no other groups are making conflicting changes to the installer before working on this issue.

**Comment by HGustavs** [comment]
This needs to support Windows/Mac/Linux ...

**Comment by b18alegu** [comment]
Of course @HGustavs, if I understand correctly the command shown is for Linux-users?

**Comment by a18kaswi** [comment]
> This needs to support Windows/Mac/Linux ...

So we need support for Windows/Mac/Linux.

This means. 

1. Find out a way to see which O/S the user trying to install the system are using.
2. Create a different modal for each O/S. 
3. Display the modal coresponding to the users O/S.

#7419

**Comment by a18kaswi** [comment]
` <?php
      echo PHP_OS_FAMILY;
?>`

Prints the family of O/S. i.e Windows, Linux or OSX. 

Will formulate different modals for each family in next step. Need to collect info on what to change in Windows first. Afaik I didn't have to change any permissions setting up the WAMP-stack.

**Comment by a18kaswi** [comment]
> This needs to support Windows/Mac/Linux ...

Solution put forward in #8747 supports Windows, OSX 10.2+ (afaik) and Linux. 

@b18alegu maybe you could check the screenshot in above PR and see so it looks right.

**Comment by b18alegu** [comment]
@a18kaswi, it does indeed look right.
