### ISSUE TITLE
ResultEd grading/feedback window looks off.

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8007]
The grading/feedback window in ResultEd (opened by clicking the fist-icon for a specific submission and then the yellow fist) does not look right. The "Previous feedback/Date/Feedback" header thing looks too clumped together. It wasn't until I looked at a submission that actually had previous feedback that I understood what it was trying to convey. 

I would suggest adding some separation between the "Previous feedback" and "Date Feedback", maybe with some margin, or possibly a faint line (similar to the actual date and feedback of previous feedback, see screenshot). Maybe add some top-padding or similar to Previous feedback?

There is also something weird at the top left corner of the Previous feedback thing. Should be removed.

![image](https://user-images.githubusercontent.com/49141758/78873708-9211d700-7a4b-11ea-8224-cb657723de9e.png)

**Comment by b18alegu** [comment]
This issue was merged into the W16 master. I'm closing this one now.
