### ISSUE TITLE
Codeviewer resize is not working like intended and clipboard icon wasnt hiding on resize on some templates properly

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#8008]
Resize is no longer affecting windows on the right side.
See GIF:
![https://i.imgur.com/J2EmScR.gif](https://i.imgur.com/J2EmScR.gif)

**Comment by a18jakme** [comment]
Codeviewer.php want to use fileed.js instead of codeviewer.js. When we remove fileed.js script the resize function works. Problem is when we remove the script function for "Edit file" stop works..
