### ISSUE TITLE
CodeViewer: function seems to do nothing

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#801]
Line 89-91 in codeviewer.js seem to do nothing, at this moment it looks like this;
if(retdata['writeaccess'] == "w"){
	// If write access show settings cog wheel.
}
which makes it seem like dead code

**Comment by c12jenek** [comment]
Same goes for rows 1340-1343;
function updateContent()
{

}

**Comment by a13henhu** [comment]
I've been checking on this issue, and it looks like it has no functionality what so ever at the moment. Any ideas what could be implemented in these functions?

**Comment by c12jenek** [comment]
I'm guessing this has to do with being able to edit the code/comment boxes from the browser?

**Comment by c12jenek** [comment]
This issue is no longer relevant, this has been worked on with issue #1225
