### ISSUE TITLE
Check database for course ID 

### ISSUE THREAD

**Issue by a18frior** [HGustavs/LenaSYS#8011]
Validate new course version and edit course version forms by checking datebase for course ID to make sure that the user doesn't get duplicate key error.

**Comment by a18antsv** [comment]
When courses are fetched from database and elements are created for each course in a list, there is the possibility to add a data-attribute (data-code) for each element with the value of the code for the course represented by that element in the list. These codes could later be extracted from the elements into an array and when validating a check could be made for if the value in the input is equal to any of the values in the array. This way would prevent fetching from database on each validation attempt.

**Comment by a18antsv** [comment]
When editing a course one exception must be taken into consideration. You should be able to save the course with the same course code as the course previously had. If a list of all occupied course codes exists and a check against it is made it would prevent you from saving with the same course code again. The code the course actually has could be passed a data-attribute to the input element when the form is opened. This way it would be possible to make the exception to accept the same course code for the course the form is representing with the code in the data-attribute.

**Comment by a18antsv** [comment]
The fix for this issue will also fix the problem with validation blocking necessary course names.
