### ISSUE TITLE
Resulted: H1-element "Result" does not follow the horizontal scroll of the table

### ISSUE THREAD

**Issue by a18viksa** [HGustavs/LenaSYS#8020]
When you navigate to the right in the table "Result" disappears. It should probably move with resultedFormContainer instead to make it more consistent. 
![image](https://user-images.githubusercontent.com/49142704/78883644-0e131b80-7a5a-11ea-953e-c0e165c0abb9.png)

**Comment by b18alegu** [comment]
This issue was merged into the W16 master. I'm closing this one now.
