### ISSUE TITLE
Deadline tab does not work properly.

### ISSUE THREAD

**Issue by a18jonsj** [HGustavs/LenaSYS#8031]
![untitled](https://user-images.githubusercontent.com/49142617/78890820-9992a980-7a66-11ea-9aae-3a75f4a7c660.png)

When you click the deadline tab it is suppose to minimize/maximize the pie chart and the swimlanes visiable on the page. This is not working.

**Comment by a17towan** [comment]
Hello, I am fixing this issue already as it is part of issue #7999!
