### ISSUE TITLE
CodeView Working Example Editor

### ISSUE THREAD

**Issue by a13alfbe** [HGustavs/LenaSYS#806]
The only thing a user can edit is the examplename, sectionname and runlink at the moment. 
Make it possible to edit the before/after examples and and the important words for the example.

![untitled](https://cloud.githubusercontent.com/assets/11715493/7084031/f18f5726-df68-11e4-9501-408edd451cca.png)

**Comment by c12jenek** [comment]
#796

**Comment by a13alfbe** [comment]
Part of this issue has been solved and merged (#891).
I will continue working on this issue and add functionality for editing Before/After example.

**Comment by c13caral** [comment]
This issue is now solved.
