### ISSUE TITLE
Full screen option for diagram

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8066]
It could be nice with a full screen option for the diagram. This mode could be activated from the View dropdown or by Shift+F11. In this mode only the diagram drawing area should be shown to maximize the area to view and draw diagrams on. No navbar, no toolbar, 100 % of screen to diagram. Small button/keyboard shortcut for hiding and showing toolbar would be good.

**Comment by a18antsv** [comment]
This could make the system achieve nielsen's heuristic #7: Flexibility and efficiency of use. This function will make the system more efficient for experts of the system while novice users do not need to use it until they have learned the system more. The expert could easily use the diagram in fullscreen mode and use keyboard shortcuts to do all functions without having to see the toolbar.

**Comment by b18simla** [comment]
Mostly a note-to-self: I think a button to exit fullscreen will be necessary since shortcut commands can be disabled, which means the user otherwise could get stuck

**Comment by a18antsv** [comment]
If there is a function locking shortcuts that would be necessary, yes.

**Comment by b18simla** [comment]
After the new weekly branch (W18) many of the functions and variables has changed which has caused many bugs with the almost completed solution. Currently there is a bug after exiting fullscreen where the cursor is offsetted around 150 pixels on the Y-axis, meaning visually the cursor appears to be in one spot but fails to select any entities in that location. Anyone has suggestions on how to "reset" the cursor pivot?

The function I made can be found here: https://github.com/HGustavs/LenaSYS/blob/G4-2020-W18-ISSUE%238066/DuggaSys/diagram.js at row 3450. 

Screenshot of the issue: 
![problem](https://user-images.githubusercontent.com/62878243/79978697-9ce35780-84a0-11ea-9fea-91e65513c2fd.png)

**Comment by a18antsv** [comment]
Do you really need to set this. This happens in canvasSize() and the canvas is not resized with how the canvas container element looks like.
`canvas.setAttribute("width", window.innerWidth);
 canvas.setAttribute("height", window.innerHeight);`

**Comment by a18antsv** [comment]
Maybe you can hide header and toolbars. Position the canvas container absolute with top:0; right:0; bottom:0; left:0;. Remove the margin. The container should take the full page size and then run canvasSize() which should make the canvas fill the container.

**Comment by b18simla** [comment]
setAttribute did what I wanted before which is why I used it, but it probably makes more sense to resize container and not the canvas. Though, I tried both resizing container and setting postition to absolute BEFORE the update, but maybe it's different now. (Header and toolbars are already hidden)

I'll try both your suggestions and update here

**Comment by b18simla** [comment]
Getting almost the same result with "absolute" and those settings. Though I dont think I'm setting the dimesions properly, what am I doing wrong?

`var canvas_div = document.getElementById("diagramCanvasContainer");`

`canvas_div.style.height = window.innerHeight;`
`canvas_div.style.width = window.innerWidth;`

Never worked with vh/vw before so no clue about the syntax, sorry. 

This is how it looks for me at the bottom atm: 
![problem2](https://user-images.githubusercontent.com/62878243/79985064-53980580-84aa-11ea-87f9-4bdcdb47c70f.png)

> I miss C++

**Comment by b18simla** [comment]
And yes, I'll remove the border so the scrollbar disappears!

**Comment by a18antsv** [comment]
I think you are missing to add px?
I usually use this syntax for concatenating variables and strings: 
``canvas_div.style.height = ${window.innerHeight}px`;`

**Comment by b18simla** [comment]
Got it. Added "px" and it worked, thanks for all the help!
