### ISSUE TITLE
Global appearance settings only affected with minimum one drawn symbol

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8067]
Global appearance settings are not affected if no symbols are drawn at the moment. Changing the global appearance should always change the global settings for the symbols that will be drawn next, even if no symbols are drawn at the moment of change.
This issue is caused by a loop with code only executing if there are symbols in the diagram. The code for saving global settings should be executed outside of this loop.

**Comment by a18kaswi** [comment]
appearanceDiagram
#7677
#7928
#7645
#8067
#6888
