### ISSUE TITLE
When changing examiner from an examiner to "none", the change doesn't stick if you reload the page

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8077]
I got both these errors (on separate examiner updates)
<img width="548" alt="Screenshot 2020-04-14 at 2 12 01 PM" src="https://user-images.githubusercontent.com/62876553/79223643-07214a00-7e5a-11ea-8db6-0b2e05f88a5d.png">

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
