### ISSUE TITLE
AccessEd table: Group dropdown menus are not updated visually when selecting groups

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8082]
Only an issue after #8071

**Comment by b18jonli** [comment]
Also, after updating and closing a dropdown, it is sometimes impossible to open the same dropdown immediately after. Opening and closing another dropdown moves the problem to that row instead.

**Comment by c14jonfr** [comment]
> Also, after updating and closing a dropdown, it is sometimes impossible to open the same dropdown immediately after. Opening and closing another dropdown moves the problem to that row instead.

This seems to happen because the if-statement at row 554 is only true the first time a dropdown is opened meaning everything inside the if-statement will not be executed (this is where the checkboxes are opened, expanded is set to true etc).

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
