### ISSUE TITLE
Make so UML also has line jumping

### ISSUE THREAD

**Issue by b18phibe** [HGustavs/LenaSYS#8087]
Now ER have line jumping and it would have been nice if UML lines also could line jump.
![er](https://user-images.githubusercontent.com/62876531/79231800-e8758000-7e66-11ea-8d37-37f30dfd0670.PNG)
![uml](https://user-images.githubusercontent.com/62876531/79231808-eca19d80-7e66-11ea-8af1-9b851ff2e4fa.PNG)

**Comment by a18petha** [comment]
To be honest I don't know how we can implement this by reusing the current method for finding a intersection. The current method uses infinite strait lines to determine where the intersection happens. These being bent lines makes this approach rather difficult. @HGustavs @a97marbr You guys have any suggestions for how to approach this issue?

**Comment by a97marbr** [comment]
Could checking every line segment be possible? 

In the above example the orange line consists of 3 line segments. could we check segment 1 against all segments in the blue line for intersections? Then repeat ...

Too slow/processing intens?

**Comment by a18petha** [comment]
@a97marbr sounds like something that could work, would just have to find a way so each intersection is not check twice with that approach. Would also have to make another function to store every sub-line in the UML relationship. Gonna give this approach some testing

**Comment by a18petha** [comment]
@a97marbr @HGustavs  Seems to still be some issue with this approach. Currently we have a version where we can check every sub-line in the UML relationship. Now the issue at hand, as far as I can understand it is that the current function which checks for intersections only works for lines which are overlapping on an angle. These lines which we are trying to check always overlap at a 90° which seems to be a blindspot for the denominator calculation, it always returns a 0 in this scenario. 

Have any suggestions for how we can modify this calculation so it works for 90° angles? 

denominator = ((line2EndY - line2StartY) * (line1EndX - line1StartX)) - ((line2EndX - line2StartX) * (line1EndY - line1StartY));

or how we can do this calculation for straight lines

**Comment by a97marbr** [comment]
My trigonometry isn't that great 🤔 

But if we check two line segments and they:
1. Have the same angle, i.e., are parallell we know the won't intersect
2. Have different angle, the could intersect. More checks are needed. 

Also, perhaps this Stackoverflow could help: https://stackoverflow.com/questions/563198/how-do-you-detect-where-two-line-segments-intersect
