### ISSUE TITLE
File handling not working after weekly merge

### ISSUE THREAD

**Issue by b18emigu** [HGustavs/LenaSYS#8089]
Me and @a18felen spent the majority of the day trying to figure out what broke the file handling after the weekly merge but cant seem to find it. Creating an issue so we can continue on this tomorrow with a clearer goal.

**Comment by a18felen** [comment]
To clarify it works locally on the weekly branch but not on the server

**Comment by b18emigu** [comment]
The issue was the web servers write permissions, after changing them it works as intended.
