### ISSUE TITLE
Gamification requires some database updates

### ISSUE THREAD

**Issue by a13karsi** [HGustavs/LenaSYS#809]
In order to provide the gamification aesthetic and look and feel of using the system the client has requested a number of additions need to be done to the database. I have identified a few possible candidates for this addition, namely, 

1. The database should be able to log when a user started and finished a specific quiz. To calculate the time the user spent on the quiz.
2. The database should be able to log the number of attempts a user has made to a quiz. If this is already possible, maybe  creating a stored procedure or a trigger that can count this easily.
3. The database should contain a number of achievements the user can gain after finishing certain tasks, such as finishing a dugga, perhaps with some additional requirements.
4. The quiz table should be updated to include a 'difficulty' attribute.
5. The database should contain views or stored procedures etc., that can display high score lists, top 10 students for example.

The above list details just some ideas I've come up with after reading over some of the requests from the clients and is not conclusive at the moment. When additions like these have been implemented in the database work can begin on the higher level to implement gamification possibilities at the users perspective. We should discuss this next monday in a meeting and decide which features we want for this part of the system and which we do not determine essential just yet.

**Comment by c13chrjo** [comment]
I agree
