### ISSUE TITLE
Inconsistent coordinates information

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8091]
The information about coordinates shown in the image below can be seen as inconsistent. All three possible pieces of information is a coordinate but they are shown in different format (X=0 & Y=0 or (0, 0)). This format should be the same and preferably be of shortest format to fit as much as possible on small screens. The text is also uninformative, not describing the things with enough meaning. Top-left corner is not a good description of the origo coordinate for example. One of the three also lacks the bold font.

The code for creating this information box is also very redundant and could be simplified a lot to accomplish cleaner code. The elements places on the canvas should also be repositioned to be relative to the canvas container so a fix for this could also be made to solve this issue.

![problem](https://user-images.githubusercontent.com/49121839/79279580-9eb08800-7eae-11ea-9a25-62d23a7a7364.PNG)

Possible solution 1:
This is a solution for having everything on one row.
![problem2](https://user-images.githubusercontent.com/49121839/79279912-60679880-7eaf-11ea-97b5-9a90fb865c6e.PNG)

Possible solution 2:
This is a solution that have separate lines for each type of information. This would probably be the best solution. The screen width will not be a big problem here as less space will be required with the information stacked when also having the short format. Also much easier to read and understand.
![problem3](https://user-images.githubusercontent.com/49121839/79279904-5cd41180-7eaf-11ea-9851-da521657a64d.PNG)

**Comment by HGustavs** [comment]
Do we even need to know where top corner is?
I think that is internal development information that is not very useful when scrolling works?

**Comment by a18antsv** [comment]
@HGustavs I could agree with this. This is developer mode though, so maybe it could be interesting for developers to see where origo is. This gives an idea of the current position in the canvas and how far away from the center you really are. It is possible to see how far away you are with the mouse coordinates though as (0, 0) for the mouse is in origo. This fact could make the actual origo coordinate a waste of space. It could be better to remove it to have less redundant information.
