### ISSUE TITLE
Dropdown menus overlap - Diagram

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8099]
After clicking inside on one dropdown label or inside of the dropdown menu and then hovering over another dropdown label, the previous dropdown menu will still be visible. The previous one should be hidden as soon as the user hovers on a new dropdown label

Image of the issue:
![image](https://user-images.githubusercontent.com/49121839/79319644-dfd58600-7f08-11ea-9ed3-2d466b8136ce.png)

**Comment by a18andtu** [comment]
The dropdowns are held open because of the highlighting of the dropdown that was clicked. This has to do with the functionality of tabbing through the menus and its keeping it marked so you can tab into the alternatives.
