### ISSUE TITLE
Filter and Sorting menus close if user moves cursor slowly from icon/navbar to menu

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8100]
There is a small space between the icon/navbar and the menu with the checkboxes. If the user moves the cursor slow enough the menu will close because the cursor was not over the icon or the menu. This can be seen in ResultEd and AccessEd but possibly in more places (anywhere there is a filter/sorting icon in the navbar, I assume).

Could probably be fixed by removing the space between the navbar and the menu or something similar.

**Comment by b18alegu** [comment]
@duplicate https://github.com/HGustavs/LenaSYS/issues/8122
