### ISSUE TITLE
Icon for "Add Dummy Empty file" is missing and upload icons is not functioning

### ISSUE THREAD

**Issue by a16silph** [HGustavs/LenaSYS#8103]
When looking at **fileed, duggaed** and **accessed**, you should see a plus icon in the lower right side of the screen. When hovering over the plus icon, there will be different icons showing the user different ways to upload different types of files. When using _"Add Dummy Empty File"_  button in all php files, nothing seems to happen. It seems that all of the other upload icons don't seem to work either.

![image](https://user-images.githubusercontent.com/49142660/79235637-2923c800-7e6c-11ea-80bc-c77ec0f9b303.png)
**Fig. 1** - Icon for _"Add Dummy Empty file"_ **is** missing and all the upload icon is not functioning.

**Comment by b18jonli** [comment]
I think "add dummy file" should only exist in fileed, not duggaed and accessed.

**Comment by a18jenro** [comment]
As of right now, the button exists only in filed, as it should. The icon is also there. But the functionality is questionable.

**Comment by a18jenro** [comment]
@b18emigu or @a18felen Is it perhaps that the button does not work due to access rights? What would one have to do to make then dummy button work?

**Comment by a18felen** [comment]
@a18jenro I just think that the code for creating a dummy file is not there. not sure what code exactly that is needed but i think its filerecieve, fileed.php, and fileed.js that needs to have code added and fileedservice for the edditing of buttons.

**Comment by b18emigu** [comment]
All of the icon related bits have been dealt with in other issues however creating dummy files simply has no code for it, like @a18felen said. We will implement the code for uploading the files but i do believe we will need a definition of a **dummy file** in the database as well.

**Comment by b18emigu** [comment]
We have now finished implementing frontend validation as well as some server-side validation. We are now leaving the rest of the issue (creating the dummy files) to @a18jimol and @a18jonsj as they were working on related issues and had already started implementing the creation of files #7856 and #7919
