### ISSUE TITLE
Errors when hoovering/typing in searchbar on "show files" page.

### ISSUE THREAD

**Issue by a18jonsj** [HGustavs/LenaSYS#8104]
If you are logged in as brom and go to a course, for example "webbprogrammering" and then click the "show files" icon, when you get to the show files page and hoover over the searchbar you get the following errormessages: 

![image](https://user-images.githubusercontent.com/49142617/79322232-d4845980-7f0c-11ea-858f-79c5b38f4474.png)

**Comment by a18mahkh** [comment]
Error is gone maybe someone has fixed it because when I hover over the searchbar I don't get any error messages.

![Anteckning 2020-04-22 141632](https://user-images.githubusercontent.com/49142349/79980749-dff2fa00-84a3-11ea-8182-2c50f61443b1.png)
