### ISSUE TITLE
When pressing F12 in files, files disappear on desktop

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#8107]
When pressing F12 in files, files disappear on desktop
![F12 issue](https://user-images.githubusercontent.com/62876507/79322786-963b6a00-7f0d-11ea-99af-9f9893667ba7.PNG)
(There should be files listed in the figure)
It only happens some times, try filtering on the different options: All files, Global, Course local etc. and try pressing F12 a few times to reproduce the problem.
Maybe they are pushed out of the screen?

**Comment by a18jenro** [comment]
Happens also when pressing other keys, like for example F11.

**Comment by a18jenro** [comment]
Easiest way to reproduce:
1. Go to files.
2. Filter on something, for example global.
3. Press F11

**Comment by a18jenro** [comment]
It also happens when resizing the browser Window

**Comment by a18mahkh** [comment]
They are not pushed of the screen.  It automatically activates/triggers the searchinput in navheader.php on window resizing/pressing keys and I don't why it does that, it's a little bit random. 
However if you remove these codes below which has the same functionality as sortFilesByKind() then it will not activate the searchinput field. 
count=0;searchterm='';searchKeyUp(event);

**Comment by a18jenro** [comment]
@a18mahkh If I do that, then when I press F11, F12 or resize the window, then all files are shown, even when I am filtering on specific ones. So this does not appear to be a solution.

**Comment by a18jenro** [comment]
It also happens when sorting the columns. Basically everything one does triggers an update of the table in sortableTable.js and this causes the table to search on some keyword which overrides the filtering.
