### ISSUE TITLE
Redesign and movement of the result heading in resultEd.

### ISSUE THREAD

**Issue by a18ismca** [HGustavs/LenaSYS#8109]
In resultEd in LenaSYS, there is a heading called **Result**. It would be good to rename to heading to a more appropriate name, **for example** "Dugga Results for Students" or "Result Editor". Also, it would be good that the heading is replaced more to the left of the screen, above the LadExport table to increase readability.

The heading affected is "Result" colored in purple.
![image](https://user-images.githubusercontent.com/62876523/79322971-e0245000-7f0d-11ea-9d1a-37ceca61fde5.png)

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
