### ISSUE TITLE
Codeviewer error when trying to resize 

### ISSUE THREAD

**Issue by a18jimol** [HGustavs/LenaSYS#8128]
![codeviewerError](https://user-images.githubusercontent.com/49142669/79336351-e0c7e100-7f23-11ea-850b-2a2ef8527558.PNG)
When opening codeviewer sometimes you can't resize the code-windows and you directly get this error. Sometimes you can resize but you get the error each time you resize.

**Comment by d17marle** [comment]
This happens only on the templates that dont have the clipboard icon when created.  Will be further investigated to solve this issue.
