### ISSUE TITLE
CodeViewer: Line selection

### ISSUE THREAD

**Issue by a13alfbe** [HGustavs/LenaSYS#813]
Is there any interest in having line selection when clicking a line in the CodeViewer?

Example of how it could look like on line 3:
![untitled](https://cloud.githubusercontent.com/assets/11715493/7084380/f8526310-df6c-11e4-8365-c00d5ae47b20.png)

**Comment by c13caral** [comment]
is this something you want to have in code viewer @HGustavs

**Comment by HGustavs** [comment]
Yes, if it is easy to fix.

But if I had to choose between iframe support and this I would go for iframe support.

**Comment by c13caral** [comment]
We already have iframe support

**Comment by HGustavs** [comment]
I think we have this?
