### ISSUE TITLE
Notice: Undefined offset: 1 breaks design - Navheader

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8138]
The notice in the image is breaking the design on servers having notices activated. Values are access directly from an array. Isset would probably fix this problem since we need to know if there will be something on the position that is accessed in the array before accessing it.
![image](https://user-images.githubusercontent.com/49121839/79339914-e3c5d000-7f29-11ea-9802-f60a02bc2626.png)

**Comment by a18kaswi** [comment]
@a18jenro tagging you here so you can follow

**Comment by a18antsv** [comment]
The problem occours when there is no course version does not exist for a course.

**Comment by a18antsv** [comment]
The previous solution for this is not enough I could see now after further investigation. When having multiple versions for a course, the top one is chosen from database by course id and version is not taken into consideration. This means that the link that this is used for could be to the wrong course version.

**Comment by a18antsv** [comment]
In addition, prepared statements should be used for select queries to prevent security issues.

**Comment by a18antsv** [comment]
So an idea here is to not create the button that this is used for when there is no course version for the course in the database.
