### ISSUE TITLE
AccessEd table - All dropdown menus are reset when updating name or username

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8142]
1. set a dropdown to new value
2. update name or username cell (causing the table to re-render)
3. the dropdown should have reset to the previous value

Likely caused by dropdowns not updating sortableTable:myTable correctly. 
Correct (updated) values after a page reload, so the database is correct.

**Comment by b18jonli** [comment]
The SortableTable::updateCellInternal() function that updates name and username (indirectly) calls the reRender() function. This means that the dropdown menus do not update the sortableTable with the new values, and are thus (visually) reset. 

This should probably be done so that the dropdown menus calls updateCellInternal(), which calls updateCellCallback().

**Comment by b18jonli** [comment]
The call to updateCellInternal could be placed in changeOpt and updateAndCloseGroupDropdown() respectively, and then the updateCellCallback should be improved to handle the dropdown menus.

**Comment by b18jonli** [comment]
Maybe updateCellInternal is the wrong way to go because it relies on the sortableTable knowing what cell is being edited, which I don't think it does when editing through the dropdown menus since only name and username editing calls clickedInternal (which sets the "current cell being edited" values).

**Comment by b18jonli** [comment]
I was half-right it seems, the clickedInternal is called by dropdown-cells, but for the cell you click over, which for a dropdown menu is not necessarily the dropdown that is being edited.

**Comment by b18jonli** [comment]
(wrong again) Selecting an option on the normal dropdowns do not generate a clickedInternal call (but opening them does), and checking a checkbox in the group dropdown actually generate two clickedInternal calls for the correct row (the one being edited). 

The problem is when clicking another dropdown to close and save the current dropdown, that click causes the clickedInternal call for the new dropdown, not the old one.

**Comment by b18jonli** [comment]
I think the safest course of action would be to use a function in sortableTable to update the value of a single cell, and call that function in both changeOpt and updateAndCloseGroupDropdown.

**Comment by b18jonli** [comment]
I need a way to get the cell (e.g. row number and column name) for the current dropdown in both the changeOpt and updateAndCloseGroupDropdown functions.

I could do it like in clickedInternal but that would require either a getDelimiter() function or hard-coding the current delimiter which would break if it is ever changed.

**Comment by b18jonli** [comment]
I have a solution, will add pull request when #8141 is merged to group since this is not testable pre-#8141.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
