### ISSUE TITLE
Changing filters requires user to click the checkbox

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8159]
This can be seen in the ResultEditor and the AccessEditor.

This is inconsistent with how the sorting works. The filter-menu requires the user to click the checkbox to toggle a filter while in the sorting-menu a click on the "title" of the option is enough. 

This should be changed so the two are consistent (by letting the user select filters by clicking the "title" of the option).

**Comment by c14jonfr** [comment]
Note: This seems to be specific for the Dugga/delkurs filters in ResultEd and the First Name/Last Name/etc filters in AccessEd. The default filters like Show Students does indeed let the user toggle it by clicking the title.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
