### ISSUE TITLE
Suggestion: only show the "Previous feedback" part of the Feedback/grading if there is previous feedback

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8160]
Currently the "Previous feedback/Date/Feedback"-table is shown even if there is no previous feedback (see screenshot).

This is unnecesary and adds visual bloat. Without the actual tablebody content it kind looks like they are buttons.

![image](https://user-images.githubusercontent.com/49141758/79438221-8d14d080-7fd3-11ea-96c7-be97492d1961.png)

**Comment by HGustavs** [comment]
I discussed this in #8204 without knowing this issue existed.

Im thinking we only show feedback accordion if it exists.

Above the assignment in an accordion that looks the same as the assignment.

**Comment by c14jonfr** [comment]
@HGustavs Maybe the description wasn't clear enough, this issue is about the feedback in the Result Editor, where a teacher can see if they have already given feedback (I'm thinking feedback can be given multiple times if a student fails an assignment for example) while #8204 is the feedback log for each assignment (where feedback is visible to the student).

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
