### ISSUE TITLE
Apply new icon in navheader.php and fix postion bug

### ISSUE THREAD

**Issue by a17pioja** [HGustavs/LenaSYS#8166]
See #8134 for details.

Please replace _tratt_white.svg_ with new icon _filter_icon.svg_ in navheader.php.

Also please fix the positioning error as pointed out [here](https://github.com/HGustavs/LenaSYS/pull/8134#pullrequestreview-394475364) 
Applied changes can be seen in resulted.php
![image](https://user-images.githubusercontent.com/49141519/79446338-5b553700-7fde-11ea-80fc-e213989e3d46.png)

**Comment by HGustavs** [comment]
why are we changing the name of the icon and not making the icon better?

It seems like this is refactorying of icon names rather than fixing the icon?

**Comment by a17towan** [comment]
@HGustavs It would seem like the OP made a new icon before realizing that the navheader is the responsibility of another group, so they kept the new icon in the icon folder but didn't switch it out with the old in the code.

This is the old icon
![image](https://user-images.githubusercontent.com/49142028/80093374-a2a27100-8564-11ea-8c43-29e2a5e052f6.png)

This is the new icon
![image](https://user-images.githubusercontent.com/49142028/80093448-c6fe4d80-8564-11ea-9bdd-56b6af611ce9.png)
