### ISSUE TITLE
Developer information when hovering is partialy covered by the zoom slider 

### ISSUE THREAD

**Issue by a18andtu** [HGustavs/LenaSYS#8169]
Developer information covered by zoom slider in the diagram:
![image](https://user-images.githubusercontent.com/62876581/79447761-a112ff00-7fe0-11ea-81c0-1aca91ab249a.png)

**Comment by a18antsv** [comment]
I am reworking the developer element for issue #8091 to be more consistent and take less space horizontally. See screenshots of possible solution in the #8091. This will probably not fix the problem completely though. Some change of styling needs to be done on smaller screens. Maybe the developer mode could be hidden completely or moved up above the zoom element when the screen is too small to fit them both.

**Comment by a18antsv** [comment]
Wait with this issue until #8091 is fixed and merged

**Comment by a18antsv** [comment]
I have fixed this locally but need to wait for another branch to merge to weekly before a branch can be created for this.
