### ISSUE TITLE
Error when creating new dugga/test in DuggaEditor

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8171]
When creating a new dugga/test in the DuggaEditor this alert is shown (see screenshot) and no new dugga/test is created in the database.

A **very crude workaround, NOT A FIX** is to disable key constraints with "SET GLOBAL FOREIGN_KEY_CHECKS=0;" in the db. This will let you make an insert into the database, but it will not have a cid-value (foreign key). This will have to be set manually.

![image](https://user-images.githubusercontent.com/49141758/79449655-ed137300-7fe3-11ea-9e86-4d91851ed5aa.png)

**Comment by HGustavs** [comment]
"SET GLOBAL FOREIGN_KEY_CHECKS=0;" is not a fix.... it makes it worse.

We want foreign keys otherwise all manner of problems happen.

Do we know the reason for this?

It seems to have to do with cascading foreign keys?

Question is why we have cascading foreing keys, seems a bit dangerous to me.

**Comment by c14jonfr** [comment]
@HGustavs You're right, it's not a fix, or not even a workaround really. But it is a way to force an insert into the database, but you'll have to set the cid (courseid) value manually. I'll update the description to make this a bit more clear.

The issue seemed to be, once again, querystring['cid'] when the URL doesn't contain cid, only courseid. 

I do not know why there are cascading foreign keys (in all honesty, I'm personally not sure what they are).

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
