### ISSUE TITLE
CodeViewer: Template 5 broken

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#819]
Template 5 (4 boxes in a square, example; http://webblabb.iki.his.se:8080/codesys/cv15/CodeViewer/EditorV50.php?exampleid=10&courseid=1&cvers=2013 ) is broken, does't print the fourth box

**Comment by a13jorla** [comment]
The template was not broken. It was just edited in the database and linked wrong. Fixed it.

**Comment by a13jorla** [comment]
Made a pullrequest for this issue vit a fix in init_db.sql.
