### ISSUE TITLE
No message about permissions when installing the server

### ISSUE THREAD

**Issue by a18felen** [HGustavs/LenaSYS#8193]
Before there used to be a really handy message that told you that you had to set permissions on the lenasys folder to make sure that the server can actually read and write. The part about writing is important for uploading files and is something that we in group 3 thought was broken. So a fix need to be made to make the it easier again for the person installing to know how to set permissions.

**Comment by HGustavs** [comment]
Good idea.

**Comment by a18kaswi** [comment]
Unclear why this has been removed, on it.

**Comment by a18kaswi** [comment]
Solved with pr #8647
