### ISSUE TITLE
Resulted: Issue with th-element length. 

### ISSUE THREAD

**Issue by a18viksa** [HGustavs/LenaSYS#8198]
Issue #7518 was fixed by implementing a max length and an ellipsis on overflow text. Although this wasn't really a good fix because the text just disappears now when it gets to long. 

![image](https://user-images.githubusercontent.com/49142704/79498852-4605fa00-802a-11ea-93fc-ba47b9806282.png)

The problem with this is that a dugga with a very long name will be impossible to read. For example there could be a "Transformationsdugga 1" and a "Transformationsdugga 2" and since an ellipsis cuts of the text if it's too long you will never know if it's dugga 1 or 2. 

Also the size of the table head looks really weird when the table is not displayed. 

![image](https://user-images.githubusercontent.com/49142704/79499288-04298380-802b-11ea-8240-7529f9b5ddb2.png)

**Comment by a18viksa** [comment]
A possible fix to this could be to make an onmouseover function that uses innerHTML or something similar to display all of the text that the ellipsis cuts off. Maybe in the form of a dialog square. 

It would also be a good idea to fix the sizing issue when the table is empty. Probably by adjusting the line-height.

**Comment by a18viksa** [comment]
There's also an issue with weird text placement. Caused by added padding to ".list th" in style.css.

![image](https://user-images.githubusercontent.com/49142704/79500764-4653c480-802d-11ea-80bb-35850f754e21.png)

**Comment by HGustavs** [comment]
Adding an alt / title does not solve this?

**Comment by HGustavs** [comment]
We are most interested in the first and last part of the text and not bothered with cut-offs.

We are fine with 
Bit... 1
Bit... 2
Col...1
Col...2
As we remember all of the names of assignments well. We do not need very much feedback.
It is crucial that we do not make the table cells any wider. 

The most important consideration here is to fit as much information on-screen at one time as possible

**Comment by b18fella** [comment]
This issue was closed because the changes were not necessary. There is another small problem that needs to be fixed. But that will be fixed within a new issue to avoid confusion.
