### ISSUE TITLE
Codeviewer: Buttonmenu overlap 

### ISSUE THREAD

**Issue by a18jakme** [HGustavs/LenaSYS#8202]
When resizing the button menu overlap. 
![image](https://user-images.githubusercontent.com/49142935/79538121-023fde80-8084-11ea-9c25-0bf82d866212.png)

**Comment by a18jakme** [comment]
Maybe make a dropdown with the buttons when the window overlap or make a min-max resize on resize window:
![image](https://user-images.githubusercontent.com/49142935/79538928-8f376780-8085-11ea-9517-8940b425bc20.png)

**Comment by HGustavs** [comment]
I would prefer icons for max min and reset, that would resolve the issue with the textual buttons.

The text can be written in a title/alt.

Also all icons should be white.

That dark symbol is a pen?

**Comment by a18filkr** [comment]
![Screenshot_2020-04-20 Validating form data](https://user-images.githubusercontent.com/49142751/79749092-dc7a3a00-830e-11ea-9853-1ace1e2b40fb.png)
Icons can be added instead of Max Min and Res, these were changed to match the size of an icon. Will make a new issue of adding icons for those.
