### ISSUE TITLE
Remove use of .toGMTString (deprecated) and change to .toUTCString in dugga.js

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8203]
On lines 337 and 351 in `dugga.js` the deprecated javascript function `.toGMTString` is used. The use of that function should be swapped out to `toUTCString` instead to ensure future browser compatibility.

**Comment by HGustavs** [comment]
Good idea.

Very useful.

This code pattern is not present anywhere else in the code?

I suggest searching for this pattern throughout the system before closing this issue, and report more issues accordingly.

If we are not careful it may seem as this is fixed for the whole system.

**Comment by b18alegu** [comment]
I'll investigate the codebase and see if it occurs in any other files. I'll expand this issue after pull request #8237 has been merged if necessary. If any uses of `.toGMTString` is found outside of group 2's domain I'll open separate issues for the other groups.

**Comment by b18alegu** [comment]
There are no other occurences of `toGMTString` in the codebase of LenaSYS. Though I'll read up on deprecated functions in Javascript and see if I can find any others that are being used.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
