### ISSUE TITLE
Redesign the feedback in dugga viewer

### ISSUE THREAD

**Issue by a18oscte** [HGustavs/LenaSYS#8204]
![feedbacklog](https://user-images.githubusercontent.com/49142069/79542258-9497b080-808b-11ea-8562-e968f634d1d0.png)
The feedback is at the moment under the navbar and should be moved down. Maybe to the bottom of the page would be a good spot.

This issue may be the same as issue #7667 but a newer version if you look at the screenshot.

**Comment by a18oscte** [comment]
![fee2](https://user-images.githubusercontent.com/49142069/79543599-08d35380-808e-11ea-884b-0a07d998a341.png)
Moved it down and now you can see that the feedback log have a "x" button to close it but it doesnt work so that needs to be fixed.

**Comment by a18oscte** [comment]
![fee3](https://user-images.githubusercontent.com/49142069/79548128-3c65ac00-8095-11ea-8494-5e1cbe01192b.png)
This is how it looks now. When you close the feedback there is no way to see it again unless you refresh the page.

**Comment by HGustavs** [comment]
I think that having the same gray control like for the assignment would be great for feedback...

click to expand click again to contract (accordion type).

If there is no feedback we show no box.

**Comment by HGustavs** [comment]
We do not want the feedback to cover anything. We also do not want the feedback to be at the bottom so making it inside an accordion at the top above the assignment seems like a good compromise.

**Comment by HGustavs** [comment]
Re-using the assignment control keeps the layout more consistent imho

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
