### ISSUE TITLE
FAB-button covers delete button in Dugga Editor

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8205]
This makes it unnecessarily difficult to delete tests, especially the last test in the table.

Could maybe be solved by moving the FAB-button or  adding funcionality to hide the FAB-button temporarily.

![image](https://user-images.githubusercontent.com/49141758/79543950-85663200-808e-11ea-9549-aec8ea5aa7bc.png)

**Comment by HGustavs** [comment]
Prioritize this please.

This is REALLY annoying.

**Comment by c14jonfr** [comment]
@HGustavs Do you have any preferences regarding how this should be implemented?

I was thinking either a toggle where the visibility and clickability of the FAB is toggled with a button. First press turns visibility/clickability down/off, second press sets it back to full visibility/clickability.

OR

The visibility/clickability is turned down/off when a button is pressed down (not a toggle per se, more like a "hold", when button is held down the FAB is disabled, when button is no longer pressed it works as usual").

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
