### ISSUE TITLE
Update testdata for LenaSYS installation

### ISSUE THREAD

**Issue by b18emigu** [HGustavs/LenaSYS#8208]
Currently we have to set the `teacher3` user to a superuser every time we want to test anything File Editor related. It would be good to edit the `testadata.sql` file in `LenaSYS/install/SQL` to make it so `teacher3` always is a superuser, or possibly creating a new user for this specific task in case `teacher3`already is a special case and required for testing other functionality.

**Comment by HGustavs** [comment]
Good idea.

Anything that makes testing easier should be added to the dataset

**Comment by b18emigu** [comment]
I dont think this should be an issue anymore, the main reason we created this issue was because the access levels in `fileed.php` required you to be a **superuser** to even access the page. Now that me and @a18felen have fixed the access levels in our latest issue #8397 

I would suggest closing this unless there is other needed testdata.

**Comment by b18emigu** [comment]
> I dont think this should be an issue anymore, the main reason we created this issue was because the access levels in `fileed.php` required you to be a **superuser** to even access the page. Now that me and @a18felen have fixed the access levels in our latest issue #8397 I would suggest closing this unless there is other need for testdata.

On second thought it might still be useful with some users having specific rights. As well as some users with the **supervisor** access level like discussed in #8397. It would be good to have a user with each of these access levels and possibly some with a combination of them, that would help with testing a lot of stuff related to the file editor. Currently we have to keep editing the existing users on the server for testing.
