### ISSUE TITLE
Logging: full scope

### ISSUE THREAD

**Issue by b17carbr** [HGustavs/LenaSYS#8211]
---
#### logEvent:
There is no file using  logEvent.

#### logUserEvent:
resetpw.php
loginloglout.php
codeviewer.php
+filereceive.php https://github.com/HGustavs/LenaSYS/pull/8308
+filereceive_dugga.php https://github.com/HGustavs/LenaSYS/pull/8330
+sectionservice.php https://github.com/HGustavs/LenaSYS/pull/8295 https://github.com/HGustavs/LenaSYS/pull/8405
+courseedservice.php https://github.com/HGustavs/LenaSYS/pull/8332 https://github.com/HGustavs/LenaSYS/pull/8405

#### logServiceEvent: 
profileservice.php
sectionedservice.php
resultedservice.php
duggaedservice.php
filereceive.php
fileedrevice.php
filereceve_preview.php
showDuggasevice.php
filerecieve_dugga.php
courseedservice.php
accessedservice.php
codeviwerService.php
404.php
+highscoreservice.php https://github.com/HGustavs/LenaSYS/pull/8224
+diagramservice.php  https://github.com/HGustavs/LenaSYS/pull/8224 

#### logClickEvent:
There is no file using  logClickEvent.

#### logMousemovEvent:
There is no file using logMousemovEvent.

#### logExampleLoadEvent:
codeviewer.php

#### logDuggaLoadEvent:
+showDugga.php https://github.com/HGustavs/LenaSYS/pull/8238

---

This is the status of what is current being logged in LenaSYS. Due to the size of this problem and uncertainty of what currently needs logging the issue have to be subdivided. Therfore This issue will most likely have to act as a bulletin board for logging. Please mention any newly created logging issue down below in the comments. Everything with a plus sign is added from this year 2020. 

@a18kaswi , @a18jenro , @a18eripi , @d18mohal Please respond if this is the right way forward or not.

**Comment by a18jakme** [comment]
"sub-Issue" for Service log https://github.com/HGustavs/LenaSYS/issues/8213

**Comment by a18jakme** [comment]
"sub-Issue" for Duggaload log https://github.com/HGustavs/LenaSYS/issues/8230

**Comment by HGustavs** [comment]
If I am interpreting this correctly we are advocating making a separate file for logging services?

we do not want to have a specific file log.php we prefer this to be placed in the basic .php file (this is where it is currently) to reduce the number of inclusions, also this may count as refactoring as an old system may not have this file.

I do support streamlinging and fixing the logging functionality that definitely is crufty by the standards of the rest of the system.

**Comment by b17carbr** [comment]
@HGustavs you may have misinterpreted, this issue is about tracking  where the logging functions are used throughout LenaSYS. This is not about moving the logging functions to their own file or altering them in any way. This issue is about the further usage of these provided functions throughout LenaSYS. This issue is based on what you asked for in https://github.com/HGustavs/LenaSYS/issues/3859 but with more detail about what is currently in place with logging. 

For example the in the issue above this have recently been added:

![Screenshot 2020-04-19 at 18 31 49](https://user-images.githubusercontent.com/62876614/79693640-0e869000-826c-11ea-9d71-c2f70c057983.png)

This means that the function **logDuggaLoadEvent** has been used in showDugga.php, like this: 

![Screenshot 2020-04-19 at 18 37 54](https://user-images.githubusercontent.com/62876614/79693759-e77c8e00-826c-11ea-9efa-93bf4f81cd55.png)

I hope this clarifies this issue for you. Please respond again if this is the right way forward or not. And if I need to explain what I just said more clear in the issue itself.

**Comment by HGustavs** [comment]
I have no problem with what is described above.

**Comment by b17carbr** [comment]
@HGustavs great, would it then be okey to close issue https://github.com/HGustavs/LenaSYS/issues/3859 ?

**Comment by a18jakme** [comment]
"sub-Issue" for User log in Section https://github.com/HGustavs/LenaSYS/issues/8263

**Comment by b17carbr** [comment]
"sub-issue" for user log in fileed  https://github.com/HGustavs/LenaSYS/issues/8264

**Comment by a18jakme** [comment]
"sub-issue" for user log in showDugga https://github.com/HGustavs/LenaSYS/issues/8318

**Comment by b17carbr** [comment]
"sub-isse" for log in courseed https://github.com/HGustavs/LenaSYS/issues/8319

**Comment by a18jakme** [comment]
"sub-issue" for user log in duggaed https://github.com/HGustavs/LenaSYS/issues/8393

**Comment by a18jakme** [comment]
"sub-issue" for user log in accessed https://github.com/HGustavs/LenaSYS/issues/8410

**Comment by b17carbr** [comment]
"sub-issue" for log in sectioned https://github.com/HGustavs/LenaSYS/issues/8364

**Comment by a18filkr** [comment]
Closing this for now, this is still relevant but not an "issue" that needs to be here, most loggings are solved and new ones can be added if necessary.

**Comment by a18kaswi** [comment]
GJ @b17carbr @a18jakme and others involved!
