### ISSUE TITLE
Logging: Services

### ISSUE THREAD

**Issue by a18jakme** [HGustavs/LenaSYS#8213]
logServiceEvent: 
Log the time in milliseconds for how long a service is. Log is happening in these services:
profileservice.php
sectionedservice.php
resultedservice.php
duggaedservice.php
filereceive.php
fileedrevice.php
filereceve_preview.php
showDuggasevice.php
filerecieve_dugga.php
courseedservice.php
accessedservice.php
codeviwerService.php
404.php

There is still services which don’t log:
contributionservice.php
diagramservice.php
highscoreservice.php

**Comment by a18jakme** [comment]
Because of the situation with contribution.php, we didn't find a solution for logging contributionservice.php in pullrequest https://github.com/HGustavs/LenaSYS/pull/8224

**Comment by HGustavs** [comment]
i will package a dataset for testing contribution.php as soon as we have it running for this years data.

Gtihub changed its format a bit this year so progress has been somewhat slow on getting the contribution system running.
