### ISSUE TITLE
AccessEd - Pressing enter with checkboxes open breaks the ability to update name/username with enter.

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8216]
1. open group dropdown:
<img width="119" alt="Screenshot 2020-04-17 at 10 43 49 AM" src="https://user-images.githubusercontent.com/62876553/79550322-797f6d80-8098-11ea-9311-78b6e1319108.png">

2. press enter and get this error: 
<img width="528" alt="Screenshot 2020-04-17 at 10 43 34 AM" src="https://user-images.githubusercontent.com/62876553/79550347-81d7a880-8098-11ea-9f21-62a7ed10e7ef.png">

3. open box for editing e.g. firstname:
<img width="178" alt="Screenshot 2020-04-17 at 10 43 59 AM" src="https://user-images.githubusercontent.com/62876553/79550451-a0d63a80-8098-11ea-9f45-b227672ff090.png">

4. Try to update name with enter, get same error again

**Comment by b18jonli** [comment]
This may already be partially fixed with pull request #8182, the error is still there the first time, but the subsequent errors and the "enter" functionality remains intact. 

I will branch off of #8182 (G2-2020-W17-#8142) and just remove the last (first) error.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
