### ISSUE TITLE
Sorting in resulted does not work.

### ISSUE THREAD

**Issue by a18sebka** [HGustavs/LenaSYS#8217]
Nothing happens when you click the sorting options.

**Comment by HGustavs** [comment]
This is very important functionality.

We have discussed this at length and this is the sorting priotity that we want for results:

i only have this in swedish though. please feel free to paraphrase and translate as appropriate

<img width="1331" alt="Screenshot 2020-04-19 11 20 15" src="https://user-images.githubusercontent.com/6978801/79684203-d6615c00-822f-11ea-9c5d-5c99776c5f78.png">

**Comment by HGustavs** [comment]
The previous sorting rules were a mess this i feel is a more clear arrangement.

**Comment by HGustavs** [comment]
Yellow is the default, most important first, e.g longest waiting time for result.
Then most completed 
Then most failed
Least completed
and then back to default

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
