### ISSUE TITLE
Implement read only functionality

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8218]
The read only checkbox in CourseEd is now working. It puts the right information in the database and is checked or unchecked on page load depending on the information in the database. However, this does not affect anything as of right now, so this is new functionality that should be implemented.

Quoting Marcus [brom] "The whole idea behind the read-only option is so that we could have a hot-standby server. In case of downtime for the main server we could redirect students to the hot-standby and dugga descriptions and previous student submissions would be present (for example 1 day old) ...

But by disabling student submissions (hence read-only) we could maintain consistency regarding student submissions."

Could be implemented by fetching the read only setting from the database when a student tries to upload something and only let the upload go through if read only is not activated. Give a good error message if the user cannot upload because of read only.

**Comment by HGustavs** [comment]
Seems to be a small and localized fix. Seems appropriate

**Comment by a18jonpe** [comment]
What exactly is meant by "when a student tries to upload something"? In a course? An answer to a dugga? Also, any idea what file to begin looking in?

**Comment by a18antsv** [comment]
@a18jonpe The student should not be able to submit any duggas I think. This is the only way a student can push new stuff to the server.

**Comment by a18jonpe** [comment]
Any idea what files to start looking at? @a18antsv
