### ISSUE TITLE
URL in showDugga uses 'cid' instead of 'courseid', which all other pages use.

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8221]
This should possibly be changed for consistency.

**Note: if this change is implemented you have to update the corresponding querystring-statements to use 'courseid' or things will definitely break.** 

1. Screenshot from sectioneditor URL (has courseid, not cid)
![image](https://user-images.githubusercontent.com/49141758/79554377-4213bf80-809e-11ea-9182-51fefa41ceab.png)

2. Screenshot from showDugga URL (has cid, not courseid)
![image](https://user-images.githubusercontent.com/49141758/79554420-51930880-809e-11ea-8901-7bce3ac31873.png)

**Comment by HGustavs** [comment]
for consistency. but, I suggest also supporting the old names to allow for interleaving of old and new files.

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
