### ISSUE TITLE
Make sure codeviewer.php follows the code standard

### ISSUE THREAD

**Issue by b18gussv** [HGustavs/LenaSYS#8232]
This includes everything stated in code_standard.md such as indentation, functions, curly brackets, comments and so on. Due to the nature of codeviewer, changes to codeviewer.js may be necessary as well.

**Comment by HGustavs** [comment]
Try to make this change in baby steps and not do it in one big commit.

If we want to roll back any specific change it is easier if we do not have to roll back all of the changes as one huge commit.

**Comment by HGustavs** [comment]
as always, we are not very finicky when it comes to the indentation and spacing.

We prefer to leave indentation/spacing alone but try to fix things that have to do with the lines e.g. line breaks.

**Comment by a18geoge** [comment]
Got it. Will divide it into smaller changes, e.g. starting with the functions in CodeViewer.js thereafter jQuery etc before following the same format in CodeViewer.php.

**Comment by a18filkr** [comment]
This is now considered done and will be closed.
