### ISSUE TITLE
Cardinality.isCorrectside does not always return the correct value

### ISSUE THREAD

**Issue by a18petha** [HGustavs/LenaSYS#8236]
cardinality.iscorrectside currently returns null every time, this relates to the function "createCardinality" where it seems the if-statements are non functioning, all of them. to solve this issue a redesign for how the program stores the value "lineStartObj" would be needed. or to find a way to restore the if-statements so there functional again.

**Comment by a18petha** [comment]
This issue should be solved before #7361

**Comment by HGustavs** [comment]
This is a priority issue, since relationship symbols are necessary for the diagram component to be useful in any courses.
