### ISSUE TITLE
No way to create a new code example.

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#825]
I do believe (feel free to correct me if wrong) that there is no way to make a new code example in the dugga system.
There must be a way for the dugga-system to interact with the code viewer to create a new code example.

Unsure if this has been reported before.

**Comment by HGustavs** [comment]
It would also be nice to have a way to create an example from an example dialog....e.g. to create the next example for the course without having to return to the course view.

**Comment by c12jenek** [comment]
I made two issues of this one issue as it seems to be two separate requests. Closing this one to limit the possibility of multiple people doing the same issue or one person trying to do the whole thing alone!

**Comment by a17poner** [comment]
@HGustavs Is this still relevant? we feel like there is a way but not sure if the way we think off is good enough or should we let this be closed along with its two sibling parts?
