### ISSUE TITLE
Loaded zoom value goes back to 100% on first change

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8254]
Issue #7679 was recently resolved. This made the zoom value and camera position get saved in local storage. The camera position and zoom value are loaded from local storage and used as the start view on page refresh. This is perfect as the user does not see any changes when comparing the view before and after page refresh.

Right now, it works to load the canvas exactly as it looked like before page refresh. However, when zooming it will always go back to 100% +- 10% depending if you zoom in or out. So if the zoom value after page refresh is 50%, it should be 60% when zooming in, but instead the zoom value is changed to 110% and 90% instead of 40% when zooming out.

This gif illustrates the problem:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/49121839/79672541-55747700-81d3-11ea-9a52-e6bf8e85e227.gif)

**Comment by HGustavs** [comment]
This is a very useful fix.
