### ISSUE TITLE
There would be nice to know which build one is running.

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#826]
Could the build # be added to some descrete part of the first page?

**Comment by a97marbr** [comment]
Allthough Git does not keep track of revisions only hashes there are some ways I can think of getting this done.

```
git rev-parse HEAD
```
will provide a a short hash-string for HEAD. Perhaps this can be used?

Something like this:

* A file, e.g., VERSION, containing "BRANCH-HASH" would be kind of nice.
* A git hook to regenerate at each commit

**Comment by HGustavs** [comment]
Or.

**Comment by HGustavs** [comment]
Putting a week handle or branch name together with the login name in the nav header.
