### ISSUE TITLE
Make it easier to see if a text are a comment

### ISSUE THREAD

**Issue by b18phibe** [HGustavs/LenaSYS#8265]
It could be nice to have some sort of visual indicator that a textbox are a comment? 
some sort of boarder? or a sticky note appearance or something?

**Comment by HGustavs** [comment]
Where is this?

Please a screenshot for the sake of documentation.

**Comment by b18phibe** [comment]
Now it looks like this in diagram
![image](https://user-images.githubusercontent.com/62876531/79961766-76fd8900-8487-11ea-88e4-4f6782c99440.png)

![image](https://user-images.githubusercontent.com/62876531/79961712-65b47c80-8487-11ea-9837-d60ddaf93813.png)
And there are no way to see is the text are marked as a comment or not. This may be confusing. So to have a border or something for comments so you don't have to click every text to se if one are a comment or not.

**Comment by g18marma** [comment]
A mockup of how a comment may look when it is not hidden. This way the user knows if the text is a comment or not without having to check. 

![9d33f15bdffda7f4282afde23dc4bf86](https://user-images.githubusercontent.com/49142301/79966537-dd85a580-848d-11ea-9f29-e34d06148f83.gif)
