### ISSUE TITLE
Login is broken

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/LenaSYS#827]
When trying to login on the master installation I submit my credentials and nothing happens. Login-dialouge is still present. If I refresh the page, however, I am logged in.

**Comment by a97marbr** [comment]
I wonder if there would be a good idea to have the period between the weekly-merge session and before starting the next week's branches include a through testing (and critical bug-fix?) session?

**Comment by c12jenek** [comment]
Login has since been fixed directly to master which was brought up by a pdo connect bug
