### ISSUE TITLE
Error when trying to grade duggor that are grey.

### ISSUE THREAD

**Issue by b18fella** [HGustavs/LenaSYS#8287]
When grading a grey dugga using the fist as shown below, you get the error message shown below.

![resultEdGrey](https://user-images.githubusercontent.com/49142651/79747727-7d1b2a80-830c-11ea-96c0-ac9a32480f28.PNG)
![resultEdGreyError](https://user-images.githubusercontent.com/49142651/79747728-7f7d8480-830c-11ea-95a6-4253c24d50f8.PNG)

This might be because there's no submitted dugga when it's grey. In that case, the option to grade should propably be removed.

**Comment by c14jonfr** [comment]
I _think_ I know why this happens. The grey/striped "assignments" are not really tests/duggas (assignments), but instead moments (for example "Färgduggor", in this moment Färgdugga 1 and 2 are included but "Färgduggor" is not a dugga in itself). Meaning there is no template associated with them, but the system still tries to load it. You can see the file it is trying to load (not clearly visible in the screenshot but I see it in my console), it is looking for a .js file in the template folder, but the .js file has no name.

**Comment by HGustavs** [comment]
This is some type of bug...

hard to classify which part is the bug.

It should not be possible to mark a course that has not been visited at all.

As soon as something has been handed in for some sub-item it should be mark-able.

Unclear if it is possible to know this without changing the information content ...

**Comment by b18jonli** [comment]
Merged to master.
