### ISSUE TITLE
Fix function editImpWords to fit with the code standard

### ISSUE THREAD

**Issue by a18wilis** [HGustavs/LenaSYS#8290]
As a part of dividing issue #8232. This issue focuses on making the function "editImpWords" within codeviewer.js (located on rows 358-395) to fit with the code-standard.

**Comment by HGustavs** [comment]
as always

stay away from changes that update many rows.. e.g. adding space / tabs etc

and only make changes that are local e.g. fixing brackets or paranthesis styles in as few rows as possible.
