### ISSUE TITLE
Sorting does not currently follow all the requirements.

### ISSUE THREAD

**Issue by a18sebka** [HGustavs/LenaSYS#8291]
See https://github.com/HGustavs/LenaSYS/issues/8217 for more info on the requirements.

**Comment by HGustavs** [comment]
I suggest making the first version work and then to up-scale that version to the rest.

It would be nice to have it malleable e.g. by adding a priority order rather than hard coding all of the priorities.

**Comment by a18sebka** [comment]
Similar to https://github.com/HGustavs/LenaSYS/issues/7996
