### ISSUE TITLE
Save/Reset buttons in a bad place on some "duggor"

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8298]
On some duggor like "Biträkningsdugga 1 & 2" and "Färgdugga 1 & 2" in the "Webbutveckling - datorgrfik"-course, the **Save** and **Reset** buttons will hover above the hexadecimal-panel when activated. It behaves in the same way on both Chrome and Firefox.

<img width="1558" alt="Skärmavbild 2020-04-20 kl  15 02 08" src="https://user-images.githubusercontent.com/62876260/79755890-1997f980-831a-11ea-971f-50bc20cbf5c6.png">

I think a much better solution would be to place the  **Save** and **Reset** buttons in relation to the bottom of the screen instead so they won't obfuscate the hexadecimal-panel unless the window is really small. Care has to be taken to ensure it works well on mobile devices as well.

**Comment by HGustavs** [comment]
Im thinking its a styling issue

if the upper box is bigger it should automatically displace buttons unless something is awry

**Comment by HGustavs** [comment]
Unless conviced otherwise I consider this a bug

**Comment by HGustavs** [comment]
we dont want fixed pos buttons

**Comment by a18viksa** [comment]
While testing I found this bug as well. Don't really know what to do about it. 

![issue](https://user-images.githubusercontent.com/49142704/79986537-804d1c80-84ac-11ea-9fca-646bf8beeda4.gif)

**Comment by a97marbr** [comment]
So the accordion widget seems a bit off ... yes I think you should investigate this ...

**Comment by a18viksa** [comment]
Wouldn't it be a good idea to just ensure that the panel always follows the accordions movement? Since everything else does. I've tried this in the development tool and it kind of works, but not really in a good way. @a97marbr

**Comment by a97marbr** [comment]
> ...kind of works, but not really in a good way
Examples? What is missing, what is not working in a good way? Screenshots?

**Comment by a18viksa** [comment]
By removing the "top" from the element style, the problem goes away. 

![image](https://user-images.githubusercontent.com/49142704/80141237-8a087a00-85a9-11ea-80ff-1bf5d07211e3.png)

Although it resets after every time you close the hexadecimal box. With "top" removed it looks like this. And I guess this is the desired behavior. @a97marbr 

![issue2](https://user-images.githubusercontent.com/49142704/80141368-bd4b0900-85a9-11ea-897f-de720cf63eb8.gif)

**Comment by a97marbr** [comment]
Yes this is the desired behaviour

**Comment by c14jonfr** [comment]
Some more examples of Save/Reset being positioned poorly/behaving weirdly.

When opening a linjedugga, the Save/Reset buttons are being pushed down by the "Dugga 3 - Geometri"-window. The buttons are in the middle of the linjearea..
![image](https://user-images.githubusercontent.com/49141758/80193212-b3142380-8618-11ea-94d6-296949f087c8.png)

After closing the "Dugga 3 - Geometri"-window, the buttons are moved but they are still inside the linjearea which could potentially cause issues.
![image](https://user-images.githubusercontent.com/49141758/80193404-01c1bd80-8619-11ea-9c8d-a346ce9f119b.png)

**Comment by a18viksa** [comment]
Wrote a comment in #8447 about a possible solution to the problem with the accordion that is described further up in this comment section.

**Comment by b18alegu** [comment]
Closing this issue after weekly merge.
