### ISSUE TITLE
List standard markdown syntax in markdown.js

### ISSUE THREAD

**Issue by a16silph** [HGustavs/LenaSYS#8300]
1. `Unordered lists can use + with a space as a list qualifier, but markdown.js does not allow that.`

2. `Nested lists do not work in markdown.js. In the standard syntax you can create nested lists by tabbing once before the list element, or with four spaces.`

3. `Ordered lists (1. ,2. etc...) turn into unordered lists in markdown.js.`

Part of #2648

**Comment by a16silph** [comment]
Some new observations. While I was fixing so that the **+** sign could be used in unordered lists, I noticed some strange behaviour in how the list elements act depending on how they are set up.

1. Ordered lists work, but only if they are the first list element of a list "group". 
2. The only thing keeping the outer list being ordered or unordered is the first list element.
43. The number that ordered lists use does nothing other than telling the list to be ordered. This seems to be the same in github's markdown, so it might be how it usually is.
4. Ordered lists have to use a single digit, a dot, and a space to be considered an ordered list. Multiple digits does not work.

5. Nested lists work with two spaces before the same signs that regular lists use.
6. An ordered list can contain a nested unordered list and vice versa (not a problem).
7. Nested lists seem to suffer from the same general issues that regular lists have.

8. If a nested list is the first list element, it will not become nested, but later regular lists will move to the left instead. These strange lists are always unordered.

    9. Nested ordered lists do not use the roman numerical notations that seem to be standard in some markdown. These roman numericals that are used elsewhere seem to need an empty space above the nested list to work.

![Lists](https://user-images.githubusercontent.com/49142660/79990233-184d0500-84b1-11ea-9f1c-dd2238f919d8.png)

**Comment by a97marbr** [comment]
Should one be able to start as a sublist? It seems wrong to me, but perhaps this is a valid case?

**Comment by a16silph** [comment]
Sublists don't usually work as a first element, but right now they are not only working (even if only partially), but also breaking list elements that are created after itself, if they aren't also nested.

**Comment by a97marbr** [comment]
This I don't think we can fix ... 

If we sen in incorrect md ... we cannot expect to get correct text back ... 

Possibly the row with an illegal sublist (i.e, no list is currently started) could be striped of the list property and only be shown as a regular text. In this way we don't break the lists further down in the document.

**Comment by HGustavs** [comment]
We want something that is reasonably easy to program, and that handles the lists reasonably well.

If perfection has a cost in the form of more code we do not need it.
We want the simplest possible code that generates the best possible markup.

It should not matter if we write
1. fff
2. fff
1. fff
5. fff
That should be rendered as a list. So we do not need duble digit numbers
1. fff
2. fff
3. fff
4. fff
5. fff
