### ISSUE TITLE
Fix function "returned" within codeviewer.js to fit with the code standard

### ISSUE THREAD

**Issue by a18geoge** [HGustavs/LenaSYS#8302]
As a part of dividing issue #8232. This issue focuses on making the function "returned" within codeviewer.js (located on rows 77-313) to fit with the code-standard.

**Comment by HGustavs** [comment]
As always.

If the changes affect too many rows (e.g. number of tabs) it is better to leave it as is.... 
but for example 
if()
{
}
we can readily fix to
if(){
}
