### ISSUE TITLE
Template 9 rezizing height not working properly

### ISSUE THREAD

**Issue by a17chrka** [HGustavs/LenaSYS#8305]
A box that is being dragged down can only push down the first box below itself but not the second box.

<a href="https://gyazo.com/e611c029628f0a8b0ff02579ad0ab1e4"><img src="https://i.gyazo.com/e611c029628f0a8b0ff02579ad0ab1e4.gif" alt="Image from Gyazo" width="1916"/></a>

**Comment by HGustavs** [comment]
Seems like a bug.

There is something wrong with that template?

Is the fourth box not the same as the others?
