### ISSUE TITLE
The back button is gone!

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#831]
You should also be able to go one step backwards instead of always going home.

**Comment by a13oscwe** [comment]
Close this? I think this issue is the same as https://github.com/HGustavs/LenaSYS/issues/838

**Comment by c13chrjo** [comment]
It is actually more similar to #849 but since that issue is a reference to our issue since both our codebases should look the same we are keeping this issue up until the issue is fixed on our end.

**Comment by a13oscwe** [comment]
Fixed in #838 , closing
