### ISSUE TITLE
Implement option to select test-data during installation.

### ISSUE THREAD

**Issue by a18kaswi** [HGustavs/LenaSYS#8311]
As stated in #2974 the system needs more test data, ie: an empty course, more duggas, more students assigned to courses etc. In issue #6612 it were put forth that it would be nice if the diagram were available after an install of the system. The customer stated in the issue that the request also were viable for several other views. The customer did not state which one thou, but in #6849 it were stated that also a Contribution-Dugga would be nice. These two could form an foundation for how this new improved installer could be. Then once all has been done, we could discuss further improvements (more available views) with customer.
 
In regards to #6612 an idea have been put forth in #6790 how an implementation of an diagram for educational purpose could be implemented. Finally once again in #7260 the request for better test-data were mentioned. 

The title of #6849 formulates an good idea. That is to make it possible during the installation of the system to be able to select which test-data one would want. 

My estimation is that this would take maybe two days for two developers to investigate, formulate a solution for and implement the collective request of these issues.

#2974 
#7260 
#6612 
#6790 
#6849

**Comment by a18kaswi** [comment]
I'm taking this sprint for my group. 

@JonatanLinberg should be consulted for current work into issue #7260

**Comment by HGustavs** [comment]
Good idea to give some kind of overview of what data we are getting at the very least.

I have literally no idea what actually ends up in the database upon install.

**Comment by a18kaswi** [comment]
LenaSYS\install\SQL\testdata.sql <- Inside here resides the testdata that gets added when running the installer (I think).

Within there are 

"INSERT INTO course (cid,coursecode,coursename,created,creator,visibility,activeversion,hp) VALUES (1,'DV12G','Webbprogrammering',NOW(),1,1,'45656','7.5');" 

which creates the course (row 56).

Within a course which have a courseid (cid), an dugga can reside.

/* Insert tests */
INSERT INTO quiz (id,cid,autograde,gradesystem,qname,quizFile,qrelease,deadline,modified,creator,vers) VALUES (1,2,1,2,'Bitdugga1','dugga1','2015-01-01 00:00:00','2015-01-30 15:30:00',NOW(),2, "97732");

Which creates a dugga and links it to a coursepage through cid.

Question: Is it possible to dynamically edit this file during install? 

Like:

want testdugga: Diagram
possibleDuggas++
want testdugga: Whatever
possibleDuggas++ 

great demopage, very cool.

**Comment by a18kaswi** [comment]
Line 758 f.f
`            /*************** Fill database with test data if this was checked. ****************/
            if (isset($_POST["fillDB"]) && $_POST["fillDB"] == 'Yes' && $initSuccess) {
                addTestData("testdata", $connection);`

**Comment by a18kaswi** [comment]
Pull-request #8744 impements an demo-course that showcases all currently available duggas in the system. Will work more on this when that one gets merged.

**Comment by a18kaswi** [comment]
The earlier mentioned pull-request got approved and are implemented. 

The installer now includes a demo-page. This demo-page showcases all currently available duggas that ships with the installation.

Now it's time to start working on the below request from customer.

> Good idea to give some kind of overview of what data we are getting at the very least.
> 
> I have literally no idea what actually ends up in the database upon install.

Currently there is a brief explenation that one could look up the testdata.sql himself. This is not very convenient, but it also take time to make something more interactive. Maybe we could start with making just a brief testdata.txt that shows testdata in a more 'human-friendly' format than the inserts. 

Further I propose we divide the testdata further into separate testdatafiles as a first step. And implement the option to select what one wants. Maybe something like 

[x] Courses
[x] Duggas
[x] Users
[] Demopage

**Comment by a18kaswi** [comment]
The installer-code is stil a mutated hydra.

So I will focus on finishing this feature after the work with #3698 is done.

**Comment by b18phibe** [comment]
Good job
