### ISSUE TITLE
Derived line is only derived on lowest thickness

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8313]
A derived line should be dashed. This does only work when line thickness is the lowest. In any other line thickness option, the line will not be dashed anymore since the extra thickness covers the dashes. This problem must have appeared from recent changes in the weekly branch since this was not a problem before.

This gif illustrates the problem:
![Action-2020-04-21-01-03-06](https://user-images.githubusercontent.com/49121839/79807819-51c82800-836c-11ea-8ab1-662f8b2d6fca.gif)

**Comment by HGustavs** [comment]
It could either be that the dashes are shorter than the line width or that the dashes "disappear" due to not running dash function.
