### ISSUE TITLE
AccessEd table - dropdown menus are sometimes too short

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8316]
Here it is impossible to determine if it reads HT-15 or HT-14:
<img width="340" alt="Screenshot 2020-04-21 at 8 48 19 AM" src="https://user-images.githubusercontent.com/62876553/79834169-df2b6c80-83ac-11ea-8647-652351d22f87.png">

**Comment by HGustavs** [comment]
is it only when very little data?

**Comment by b18jonli** [comment]
@HGustavs Seems to be a problem on our group branch (G2-2020-W17)

**Comment by HGustavs** [comment]
Can it be solved with some min width css magic?

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
