### ISSUE TITLE
AccessEd table - "optical illusion" where some dropdowns seem (to me at least) to be shorter

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8317]
Because of the gray/white background it can look like the dropdowns change in width depending on the row even if they are the same length: 
<img width="110" alt="Screenshot 2020-04-21 at 8 52 30 AM" src="https://user-images.githubusercontent.com/62876553/79834485-709ade80-83ad-11ea-9091-958d5e9cfd23.png">

**Comment by a18oscte** [comment]
I think that we will solve this issue in issue #8316. So wait to assign this issue to anyone before we are done to avoid merge conflicts.

**Comment by a18oscte** [comment]
Closing Issue because it got solved in issue #8316.
