### ISSUE TITLE
Cookie message can't be closed when in Random CSS Dugga

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8323]
The "OK" button for the cookie message cannot be clicked when inside the Random CSS Dugga. From my testing this seems to be specific for this dugga, it can be clicked/closed in every other dugga.

There is also the issue with the Save/Reset buttons being positioned partly outside the screen. I believe #8298 is looking into this.

![image](https://user-images.githubusercontent.com/49141758/79839909-7bf20800-83b5-11ea-8f7b-6c9675251ca9.png)

**Comment by c14jonfr** [comment]
It seems like this varies between window sizes. Sometimes the button is not clickable at all, sometimes only part of the button is clickable and sometimes it is fully clickable (depending on window size).

**Comment by c14jonfr** [comment]
It is covered by the table used to the Save/Reset buttons.. it uses the navheader class which has a z-index of 8000, cookiemessage only has 1000. Should be a simple fix.

**Comment by HGustavs** [comment]
this is a bug, so I would prioritize this (should be easy to fix also)

**Comment by b18alegu** [comment]
Closed after successful weekly-merge.
