### ISSUE TITLE
No ownership popup in installer

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8324]
The ownership popup doesn't show automatically and cannot be opened manually, this error appears on load:
<img width="552" alt="Screenshot 2020-04-21 at 10 37 13 AM" src="https://user-images.githubusercontent.com/62876553/79844744-5a484f00-83bc-11ea-879e-8d7be95b4c91.png">

**Comment by a18kaswi** [comment]
[

![](https://cdn.discordapp.com/attachments/690517046382821456/702082123225366638/Screenshot_2020-04-21_at_11.03.37_AM.png)
](url)

**Comment by HGustavs** [comment]
Seems like a bug

**Comment by a18kaswi** [comment]
Told by @JonatanLinberg that this will get solved by #8647

**Comment by a18kaswi** [comment]
#8647 merged, this issue is solved.
