### ISSUE TITLE
Incorrect behaviour for mouse over hint for searching in files 

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#8328]
One commit fixed the hint that should be given when mouse overing the search bar in files and another commit redesigned that search bar, causing problems.

![untitled](https://user-images.githubusercontent.com/62876507/79847611-4272ca00-83c0-11ea-9a7a-3919ff55b20c.PNG)

The problem is:
1. The placement of the hint covers the search bar, it should be below it.
2. The hint is only shown when mouse overing some parts of the search bar.

**Comment by HGustavs** [comment]
Also does it work with accessibility tools (for vision impared users?)

I prefer that title/alt is used for that reason.

**Comment by a18jenro** [comment]
Made the accessibility a separate issue: https://github.com/HGustavs/LenaSYS/issues/8366
