### ISSUE TITLE
CodeViewer: Part 2 of issue #825, creating new examples

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#833]
Part two of Henke's issue #825 ;
"It would also be nice to have a way to create an example from an example dialog....e.g. to create the next example for the course without having to return to the course view."

**Comment by a13jansa** [comment]
I will work on the first part of this issue. New button + pop-up box

**Comment by a13henhu** [comment]
I need to focus on one issue at the moment, so I will unassign myself from this issue for the moment

**Comment by a17poner** [comment]
long time has passed not sure if this is still relevant, closing this and the other part and using #825 to ask henrik if this has been "silently fixed" in the last 4 years and/or is still relevant.
