### ISSUE TITLE
Icon hidden in navheader in Edit student results

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#8335]
In "Edit student results" the navheader looks weird and has an icon hidden behind the search bar:

![untitled](https://user-images.githubusercontent.com/62876507/79854049-245d9780-83c9-11ea-8e8e-aa0d995357a1.PNG)

**Comment by HGustavs** [comment]
Bug.

Is that an icon from the section editor?

**Comment by a17towan** [comment]
There seems to be two <img> tags of the same svg with the same styling and everything.
