### ISSUE TITLE
Part one of issue #825

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#834]
Part one of Henke's issue #825 ;
"I do believe (feel free to correct me if wrong) that there is no way to make a new code example in the dugga system.
There must be a way for the dugga-system to interact with the code viewer to create a new code example.

Unsure if this has been reported before."

This is looks like a collab between DuggaSys and CodeViewer!

**Comment by a17poner** [comment]
long time has passed not sure if this is still relevant, closing this and the other part and using #825 to ask henrik if this has been "silently fixed" in the last 4 years and/or is still relevant.
