### ISSUE TITLE
Rework the preview for Zip / Rar file download in showDugga.php

### ISSUE THREAD

**Issue by a18oscte** [HGustavs/LenaSYS#8341]
![hfgkhfghfh](https://user-images.githubusercontent.com/49142069/79859791-d8632080-83d1-11ea-9d3c-96a40a71a162.png)
![22222222](https://user-images.githubusercontent.com/49142069/79859801-dac57a80-83d1-11ea-8a87-f1cc0fca589f.png)
When clicking the link to download the uploaded Zip / Rar file a big preview popsup over the whole page. Maybe rework it so you only need to click the link to download it.

**Comment by HGustavs** [comment]
Yes this preview is more than useless.

I think that this has been an issue numerous times before....

**Comment by b18jonli** [comment]
Merged to master.
