### ISSUE TITLE
Inconsistent design of search bar on multiple pages in navheader

### ISSUE THREAD

**Issue by a17towan** [HGustavs/LenaSYS#8353]
The search bar in the navheader has inconsistent design. It looks different on three different pages, "Edit student results", "Show tests", and "Show files" pages.

![image](https://user-images.githubusercontent.com/49142028/79868440-30088880-83e0-11ea-870a-4a586b51cda2.png)

-------

1. 
![image](https://user-images.githubusercontent.com/49142028/79868461-38f95a00-83e0-11ea-8878-8e255e537653.png)
2.
![image](https://user-images.githubusercontent.com/49142028/79868492-457db280-83e0-11ea-8474-3c3ec2c02f2e.png)
3. 
![image](https://user-images.githubusercontent.com/49142028/79868527-52020b00-83e0-11ea-82dd-50635a714e28.png)

**Please fix it so that every page has the same looking search bar**. No 1 is probably the best. Also, don't mind the icons, just the search bar, as there is a separate issue for the search icon.

**Comment by a18jenro** [comment]
@b18jenli This has been in todo for 14 days, how is it going?

**Comment by a18jenro** [comment]
This seems to be fixed.

**Comment by a18jenro** [comment]
But the positioning is not consistent, which one could fix!
