### ISSUE TITLE
Codeview iframe edit can make for a weird effect when pressing the edit button a couple of times

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#8358]
![Skärmavbild 2020-04-22 kl  08 39 00](https://user-images.githubusercontent.com/49141837/79950214-00f12600-8477-11ea-8e6e-c14be2409f01.png)

**Comment by a18wilis** [comment]
This issue seems to be fixed with the lastest branch, since neither I or any others i've asked to recreate this issue has managed to successfully do it. The iFrame should work as intended right now. Issue will be closed.
