### ISSUE TITLE
Codeviwer: Overlap works only for Code content.

### ISSUE THREAD

**Issue by a18jakme** [HGustavs/LenaSYS#8361]
Overlap should work for preview and document content as well.

**Comment by a18filkr** [comment]
Improving the transition and viewability at the same time as solving this issue, will take some extra time but end result should be better and work in all content.

**Comment by a18jakme** [comment]
The windows is not overlapping anymore. "Title" disappear with an animation, which is a good solution.
Before minimize:
![image](https://user-images.githubusercontent.com/49142935/80185582-dc2eb700-860c-11ea-81de-5135108d09e0.png)

When minimize:
![image](https://user-images.githubusercontent.com/49142935/80185593-e0f36b00-860c-11ea-981a-366b9f1ca195.png)

The solution works on every template and its tested local and on testserver.
