### ISSUE TITLE
Download button is visible in course but should be visible in files instead

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#8363]
A new download all files button is now in the navheader:
![untitled](https://user-images.githubusercontent.com/62876507/79954894-4ebd5c80-847e-11ea-849f-e7fb09200152.PNG)

However, it should be shown in files, rather than in a course.
Also, the spacing is obviously off. Also, investigate that it works properly when moved, if not, open a new issue.

**Comment by a18felen** [comment]
Related issue #8411
