### ISSUE TITLE
Error when opening "Random css dugga"

### ISSUE THREAD

**Issue by b18fella** [HGustavs/LenaSYS#8369]
When opening the dugga shown below. The error that is also shown below pops up.
![random_html_css_dugga](https://user-images.githubusercontent.com/49142651/79957922-980fab00-8482-11ea-814f-ce7160ddecf1.PNG)
![html_css_dugga_error](https://user-images.githubusercontent.com/49142651/79957994-b2498900-8482-11ea-874f-a6d268f3d2af.PNG)

There have been some investigating and the problem is most likely that it's trying to style an element which isn't even there.

**Comment by c14jonfr** [comment]
This is because the feedbackBox is missing an id. Adding "feedbackBox" as an id to the div will solve this (it's the one which has the class feedback-container). The feedback will then be displayed properly if there is feedback and hidden if there is none, with no errors.

**Comment by b18jonli** [comment]
Merged to master.
