### ISSUE TITLE
Delete empty style="" inline tags.

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#8370]
Delete empty style"" inline tags in: 
- duggaed.php
- html_css_dugga.html
- html_css_dugga_light.html
- 3d_dugga.html
- boxmodell.html
- dugga5.html
- feedback_dugga.html

<img width="925" alt="Screenshot 2020-04-22 at 10 12 19" src="https://user-images.githubusercontent.com/49142649/79957508-f5572c80-8481-11ea-8766-c873f403dc17.png">

**Comment by b18jonli** [comment]
Merged to master.
