### ISSUE TITLE
Homebutton is not present on all duggaSYS pages!

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#838]
I believe that this problem resides in ../shared/navHeader.php

**Comment by a13oscwe** [comment]
Started work need confirmation from @c12jenek
See this commit:
https://github.com/HGustavs/LenaSYS/commit/9c5ca06ced50fbbe63e1440956ef10f7336eaed9?diff=unified

**Comment by a13oscwe** [comment]
Added a fix for this that should work for all groups:
https://github.com/HGustavs/LenaSYS/pull/852

**Comment by c13chrjo** [comment]
Is this issue fixed? If so close this issue...
