### ISSUE TITLE
Sorting and filtering together does not work in files

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#8381]
If you have filtered in files on say "course local", if you were to search after that, then all files are searched, not just course local.

![untitled](https://user-images.githubusercontent.com/62876507/79964484-17a17800-848b-11ea-867b-5b2f3f6615d9.PNG)

**Comment by a18lukto** [comment]
This issue have encounters som problems, trying to merge it back in to the weekly branch to fix it
