### ISSUE TITLE
Entity to relation lines not changing automatically anymore

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8387]
Before, the line between entities and relations were changing type automatically when the type for the entity was changed to help the user. At least I imagine seeing this before, but now this does not happen anymore. The code for doing this is still being used, so it is unclear why this does not happen anymore. The intended functionality here is that the line should change to forced when the entity is weak and change to normal when the entity is strong. When the user tried to change line type, the line was reverted to be correct without a message. A message should be given why the revert is made if the intention is to keep this functionality.

I see a whole lot of problems with this functionality though. It is not always wanted to have forced lines connecting to a weak entity. For example, when a weak entity is weak to a another weak entity, the line should not be forced to the first weak entity. See this image to clarify this, the highlighted line should not be forced here. So the previous functionality is a problem. Either the functionality of changing the line type should be removed altogether, or it needs to be reworked to support these kind of situations.
![image](https://user-images.githubusercontent.com/49121839/79969874-60106400-8492-11ea-938f-2b93404c1c7f.png)

**Comment by a18antsv** [comment]
Some customer input would be good here.

**Comment by HGustavs** [comment]
That diagram is wrong so it is difficult to say what should happen.

**Comment by HGustavs** [comment]
And by the way there is a nearly endless set of permutations even if we only go so far as four entities and two relationships.

**Comment by a18antsv** [comment]
Check functions removeForcedAttributeFromLinesIfEntityIsNotWeak and setLinesConnectedToRelationsToForced. They seem to do nothing anymore even if they are called once in drawEntity. Quite heavy loops and conditions exist in these functions so if they currently do not work and the intention is to remove the auto changing of line type, they should be removed.

**Comment by a18antsv** [comment]
I simplified removeForcedAttributeFromLinesIfEntityIsNotWeak and setLinesConnectedToRelationsToForced functions a lot, still keeping the same functionality as many weeks ago when these functions were still working. They were very difficult to understand before. I could reduce the number lines of code from 160 to 20.

I will not use the functionality though since it is not wanted to force something. I will just keep the code in the code base and comment out the only place they were used to both improve performance and not force something.
