### ISSUE TITLE
Appearance menu close when user release mouse outside of menu 

### ISSUE THREAD

**Issue by g18marma** [HGustavs/LenaSYS#8388]
For example when a user selects a text string inside appearance menu and lets go of the mouse outside of the menu-box it closes. 

![85ff98d6b63a8e01ae7eec0d4012b467](https://user-images.githubusercontent.com/49142301/79970130-c2696480-8492-11ea-9d33-9a4fc62caeb5.gif)

The menu should only close when the user clicks outside of the box.

**Comment by a18antsv** [comment]
This is true. The appearance menu should close only when a click is made directly outside in my opinion. If you start the click inside of the appearance menu and drag it outside it should be kept open as it can often happen that the mouse goes outside of the appearance menu when highlighting text, like in the gif.
