### ISSUE TITLE
Logging: logUserEvent - duggaed.php edit dugga

### ISSUE THREAD

**Issue by a18jakme** [HGustavs/LenaSYS#8393]
Log for edit a dugga in duggaed.php needs to be implemented.
![image](https://user-images.githubusercontent.com/49142935/79974334-6d7d1c80-8499-11ea-8263-d6a1e408b594.png)

**Comment by a18jakme** [comment]
We have to take a closer look into this issue. When trying to edit a dugga there is a error message, this might be a problem to implement the logging.

![image](https://user-images.githubusercontent.com/49142935/79985650-39aaf280-84ab-11ea-9540-5832dd4d2955.png)

**Comment by a18filkr** [comment]
Closing, this isn't as relevant as other logs and edit dugga didn't work properly for logging. If customer wants this we have to look at it again.
