### ISSUE TITLE
Replacing empty spots in the result table of resultEd

### ISSUE THREAD

**Issue by a18ismca** [HGustavs/LenaSYS#8406]
This issue is about replacing empty spots in the result table of resultEd, by filling it with for example a bit of text, to increase comprehension of the table overall.

We see empty spots when an individual has not made some of these tests shown to the left.
![image](https://user-images.githubusercontent.com/62876523/79984082-f51e5780-84a8-11ea-928e-03d17af16acd.png)

**Comment by b18jonli** [comment]
Merged to master.
