### ISSUE TITLE
Resulted: Bug in table while toggling students. 

### ISSUE THREAD

**Issue by a18viksa** [HGustavs/LenaSYS#8415]
Stumbled upon this bug while testing the table in resulted. If you toggle all the students and then scroll as far right as you can and then remove all the students the table header just disappears.
I have no idea why this happens, but when you scroll back to the left the table header adjusts itself to a normal state. 

Video below for clarification.

![issue1](https://user-images.githubusercontent.com/49142704/79987813-28afb080-84ae-11ea-8139-e3a3dd5bfaeb.gif)

**Comment by b18jonli** [comment]
Seems to be a styling thing, where the table cells force the header cells to be longer/wider, and without table cells the header "collapses".

**Comment by b18jonli** [comment]
Merged to master.
