### ISSUE TITLE
Files when uploaded are only placed in right course but not in the version of the course

### ISSUE THREAD

**Issue by a18felen** [HGustavs/LenaSYS#8418]
When uploading a file for example course 4 the file will end up in courses/4/versionIndependence/... but they are supposed to end up in courses/4/... and for file that are version independent they should end up in courses/4/*version*/.... This was a change that was made in the last week and caused problems when deleting files. 

There should be no need for versionIndependence when the files that end up there are actually course independence

**Comment by a97marbr** [comment]
Exactly

The file structure in LenaSYS is:

* Global files
* Course Specific Files
* Course Version Specific Files

Also ... if we request a file with a particular name ... "greger.png" the system should look in revers 
order `Course Version Specific Files > Course Specific Files > Global files`
