### ISSUE TITLE
The functionality of the buttons in code viewer doesn't work in the mobile layout

### ISSUE THREAD

**Issue by a18abuah** [HGustavs/LenaSYS#8420]
When clicking the maximize, reset or minimize buttons in mobile layout the functinality is not working. 
![11e8cfa43b365a5a3446baebe63fc877](https://user-images.githubusercontent.com/49142553/79990609-8b567b80-84b1-11ea-911a-3ace07456bd2.gif)

**Comment by d17marle** [comment]
Minimize part of this issue is now complete #8571.

**Comment by d17marle** [comment]
This issue seemed a bit big so it is now split into two individual issues #8772 and #8773
