### ISSUE TITLE
Error message about undefined variable cid in Result Editor

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8423]
Only visible with error messages enabled.

It seems this was introduced during week 17 or during the weekly merge w17->18. There was/is no error on the G2-2020-W17 branch (groupbranch before weekly merge) but it is there on G2-2020-W18 (groupbranch after weekly merge).

See screenshot.

![image](https://user-images.githubusercontent.com/49141758/79993292-e5a50b80-84b4-11ea-90f8-c34399dcf4ee.png)

**Comment by b18jonli** [comment]
Merged to master.
