### ISSUE TITLE
Hexadecimal input box is bloated in "Biträkningsdugga 1 & 2"

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8425]
The hexadecimal input box on **"Biträkningsdugga 1 & 2"** looks bloated compared to the more pleasant look of the same editor in **"Färgdugga 1 & 2"**.

**Biträknigsdugga**
<img width="1151" alt="Skärmavbild 2020-04-22 kl  16 40 20" src="https://user-images.githubusercontent.com/62876260/79996988-5c440800-84b9-11ea-92cd-ecad6ade1998.png">

**Färgdugga**
<img width="1151" alt="Skärmavbild 2020-04-22 kl  16 38 16" src="https://user-images.githubusercontent.com/62876260/79996952-53533680-84b9-11ea-9608-b81d0addaede.png">

Both examples are made using the exact same window width and both screenshots have the same size.

The size of both editors depends on the width of the window, which seems unnecessary and can look ugly. I think the buttons should just be slightly wider than the the current height to look the best. Plus it also makes a below miniscule contribution to fight [musarm](https://en.wikipedia.org/wiki/Repetitive_strain_injury).

**Comment by b18jonli** [comment]
Merged to master.
