### ISSUE TITLE
CourseEd - Incorrect link to course without version

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8429]
If you create a new course, that course will not contain a course version until you create one in the sectionEd, unfortunately the link generated when clicking on the course contains (&coursevers=null) which breaks the sectionEd (removing this from the URL allows you to create a new course version)

This is probably fixed by checking if the course version is null before generating the link. 
Error in sectionEd:
<img width="495" alt="Screenshot 2020-04-23 at 8 33 15 AM" src="https://user-images.githubusercontent.com/62876553/80067124-90f9a300-853d-11ea-8998-2207588f1f41.png">
Generated URL:
<img width="523" alt="Screenshot 2020-04-23 at 8 33 04 AM" src="https://user-images.githubusercontent.com/62876553/80067129-9525c080-853d-11ea-801f-774e591eef7c.png">

**Comment by b18phibe** [comment]
Closing this issue after merge
