### ISSUE TITLE
Empty files in need of deletion still exist in Master and all derived branches!

### ISSUE THREAD

**Issue by a12oskri** [HGustavs/LenaSYS#843]
The empty files #515, #563 and 566 is still in need of deletion and needs to be deleted in ALL branches or needs to be deleted in collaboration with the weekly merge.

**Comment by c12jenek** [comment]
This issue should be resolved during a weekly merge and not by each group on it's own, please comment with which files seems to be part of this issue and this will be considered during the merge

**Comment by a12oskri** [comment]
#515, #563 and 566 is currently the files that are empty and does not have any purpose and have been created during merge of branches.
