### ISSUE TITLE
A scrollbar appears when entering fullscreen

### ISSUE THREAD

**Issue by b18simla** [HGustavs/LenaSYS#8436]
Also: when entering fullscreen the zoom bar in the lower left doesn't allign to the left corner: 
![image](https://user-images.githubusercontent.com/62878243/80074521-965cea80-8549-11ea-9c08-31305e39fb56.png)

The coordination bar does this on the other side and it would look better if they mirror each other.

**Comment by b18simla** [comment]
Also. removing the thin diagram border would make the scrollbar disappear. Should be an easy fix

**Comment by a18antsv** [comment]
This is very easy after a recent fix. You will not need to change anything. I already positioned them relative to the canvas container. This should make them automatically be positioned 4px away from the edge.
