### ISSUE TITLE
Sort “Kind” in Edit files by alphabetical order

### ISSUE THREAD

**Issue by a18jonkl** [HGustavs/LenaSYS#8437]
I would like that when sorting after kind they sort by alphabetical order.
<a href="https://gyazo.com/8b8ed281c09e8956fa2bf58bd027f7e3"><img src="https://i.gyazo.com/8b8ed281c09e8956fa2bf58bd027f7e3.gif" alt="Image from Gyazo" width="1068"/></a>

**Comment by a18lukto** [comment]
Reopen this issues to fix som problems
