### ISSUE TITLE
Showdugga: Problem with accordion 

### ISSUE THREAD

**Issue by a18viksa** [HGustavs/LenaSYS#8447]
In "Biträkningsdugga 1" and "Biträkningsdugga 2" there's a problem with the panel that holds the hexadecimal values. The box that displays when pressing the panel doesn't follow the accordion which everything else in the page does. This allows the following bug to come to life: 

![issue](https://user-images.githubusercontent.com/49142704/80089642-88fe2b00-855e-11ea-87c0-ae4546b1d8ee.gif)

This topic has been discussed in issue #8298.

**Comment by a18viksa** [comment]
And as far as I can see, "Färgdugga 1" and "Färgdugga 2" has the same problem.

**Comment by b18veran** [comment]
There are similar problems with "Linjedugga 2". Sometimes you can't move the lines because of the buttons. 
<img width="573" alt="Screenshot 2020-04-24 at 11 31 39" src="https://user-images.githubusercontent.com/49142649/80197728-55cfa080-861f-11ea-830c-0dbdecdfee3d.png">

**Comment by a18viksa** [comment]
When i remove "top+" from the following code, the panel follows the accordion just like I want and it solves the issue. 

![image](https://user-images.githubusercontent.com/49142704/80382147-38f6cf80-88a2-11ea-9022-f79b59f1204a.png)

![e85784c480c1546fe5f15df197521d48](https://user-images.githubusercontent.com/49142704/80383195-917a9c80-88a3-11ea-8ee3-cf113b5582fd.gif)

But I don't understand what the purpose of the code is. When I remove everything that has with "top" to do, not only "top+", everything works like it should as well. I don't want to remove any of the code when I have no idea what the purpose of the code is. 
The only thing "top" does is make this issue happen.  I've been testing in dugga1.js. 
@HGustavs & @a97marbr

**Comment by a18viksa** [comment]
I realize that "top" just deals with the positioning from the top and with top implemented you can position the panel closer to its main button. It's just how you want it to look basically and I want the panel to be a bit more up. But as soon as top is implemented the panel won't follow the accordion...

**Comment by b18jonli** [comment]
Merged to master.
