### ISSUE TITLE
When only the maximize button is visible it should change to the minimize button if maximized and vise versa

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#8459]
![image](https://user-images.githubusercontent.com/49141837/80107353-41d26300-857b-11ea-9e81-567f3f8c488c.png)

On some of the templates only the maximize button is visible, when clicked on it acts as both a maximize and minimize button, we could use this to dynamically switch out the button to better reflect this instead of always having the maximize button visible.

**Comment by a18filkr** [comment]
Make one or more issues for every template and every button and decide if Max/Min/reset should exist.
