### ISSUE TITLE
Can't copy UML-class objects

### ISSUE THREAD

**Issue by o18marka** [HGustavs/LenaSYS#8462]
UML-Class objects does not seem to appear when copy-pasting them.

**Comment by a18antsv** [comment]
Text objects also have copy problems which will probably be solved at the same time as this. The text inside a text object do not get copied over. Only the name of the text is used but that is not what should be shown in the textarea

**Comment by a18antsv** [comment]
Paths cannot be copied either. When a path is copied an attempt of creating a symbol of it is made. Calling the copySymbol function should be prevented for all selected path objects. Then a different function for copying paths should be created and used on paths instead.

**Comment by a18antsv** [comment]
`function copySymbol(symbol) {
    const clone = Object.assign(new Symbol, symbol);

    const clonedPoints = {
        topLeft: {
            x: points[clone.topLeft].x + 10,
            y: points[clone.topLeft].y + 10
        },
        bottomRight: {
            x: points[clone.bottomRight].x + 10,
            y: points[clone.bottomRight].y + 10
        },
        centerPoint: {
            x: points[clone.centerPoint].x + 10,
            y: points[clone.centerPoint].y + 10
        }
    }

    clone.setID(globalObjectID - 1);
    clone.topLeft = points.push(clonedPoints.topLeft) - 1;
    clone.bottomRight = points.push(clonedPoints.bottomRight) - 1;
    clone.centerPoint = points.push(clonedPoints.centerPoint) - 1;

    if(clone.symbolkind === symbolKind.uml) {
        clone.middleDivider = clone.centerPoint;
    }

    clone.targeted = true;
    symbol.targeted = false;

    diagram.push(clone);

    return clone;
}`

**Comment by a18antsv** [comment]
`function copySymbol(symbol) {
    const clone = Object.assign(new Symbol, symbol);

    const clonedPoints = {
        topLeft: {
            x: points[clone.topLeft].x + 10,
            y: points[clone.topLeft].y + 10
        },
        bottomRight: {
            x: points[clone.bottomRight].x + 10,
            y: points[clone.bottomRight].y + 10
        },
        centerPoint: {
            x: points[clone.centerPoint].x + 10,
            y: points[clone.centerPoint].y + 10
        }
    }

    clone.setID(globalObjectID - 1);
    clone.topLeft = points.push(clonedPoints.topLeft) - 1;
    clone.bottomRight = points.push(clonedPoints.bottomRight) - 1;
    clone.centerPoint = points.push(clonedPoints.centerPoint) - 1;

    if(clone.symbolkind === symbolKind.uml) {
        clone.middleDivider = clone.centerPoint;
    }

    clone.targeted = true;
    symbol.targeted = false;

    diagram.push(clone);

    return clone;
}`

**Comment by a18antsv** [comment]
`function copySymbol(symbol) {
    const clone = Object.assign(new Symbol, symbol);
    const clonedPoints = {
        topLeft: {
            x: points[clone.topLeft].x + 10,
            y: points[clone.topLeft].y + 10
        },
        bottomRight: {
            x: points[clone.bottomRight].x + 10,
            y: points[clone.bottomRight].y + 10
        },
        centerPoint: {
            x: points[clone.centerPoint].x + 10,
            y: points[clone.centerPoint].y + 10
        }
    }

    clone.setID(globalObjectID - 1);
    clone.topLeft = points.push(clonedPoints.topLeft) - 1;
    clone.bottomRight = points.push(clonedPoints.bottomRight) - 1;
    clone.centerPoint = points.push(clonedPoints.centerPoint) - 1;

    if(clone.symbolkind === symbolKind.uml) {
        clone.middleDivider = clone.centerPoint;
    }

    clone.targeted = true;
    symbol.targeted = false;

    diagram.push(clone);
    return clone;
}`

**Comment by a18antsv** [comment]
`
function copySymbol(symbol) {
    const clone = Object.assign(new Symbol, symbol);

    const clonedPoints = {
        topLeft: {
            x: points[clone.topLeft].x + 10,
            y: points[clone.topLeft].y + 10
        },
        bottomRight: {
            x: points[clone.bottomRight].x + 10,
            y: points[clone.bottomRight].y + 10
        },
        centerPoint: {
            x: points[clone.centerPoint].x + 10,
            y: points[clone.centerPoint].y + 10
        }
    }

    clone.setID(globalObjectID - 1);
    clone.topLeft = points.push(clonedPoints.topLeft) - 1;
    clone.bottomRight = points.push(clonedPoints.bottomRight) - 1;
    clone.centerPoint = points.push(clonedPoints.centerPoint) - 1;

    if(clone.symbolkind === symbolKind.uml) {
        clone.middleDivider = clone.centerPoint;
    }

    clone.targeted = true;
    symbol.targeted = false;

    diagram.push(clone);

    return clone;
}
`

**Comment by a18antsv** [comment]
`function copySymbol(symbol) {
    const clone = Object.assign(new Symbol, symbol);
    const clonedPoints = {
        topLeft: {
            x: points[clone.topLeft].x + 10,
            y: points[clone.topLeft].y + 10
        },
        bottomRight: {
            x: points[clone.bottomRight].x + 10,
            y: points[clone.bottomRight].y + 10
        },
        centerPoint: {
            x: points[clone.centerPoint].x + 10,
            y: points[clone.centerPoint].y + 10
        }
    }
    clone.setID(globalObjectID - 1);
    clone.topLeft = points.push(clonedPoints.topLeft) - 1;
    clone.bottomRight = points.push(clonedPoints.bottomRight) - 1;
    clone.centerPoint = points.push(clonedPoints.centerPoint) - 1;
    if(clone.symbolkind === symbolKind.uml) {
        clone.middleDivider = clone.centerPoint;
    }
    clone.targeted = true;
    symbol.targeted = false;
    diagram.push(clone);
    return clone;
}`

**Comment by a18antsv** [comment]
`function copySymbol(symbol) {
    const clone = Object.assign(new Symbol, symbol);
    const clonedPoints = {
        topLeft: {
            x: points[clone.topLeft].x + 10,
            y: points[clone.topLeft].y + 10
        },
        bottomRight: {
            x: points[clone.bottomRight].x + 10,
            y: points[clone.bottomRight].y + 10
        },
        centerPoint: {
            x: points[clone.centerPoint].x + 10,
            y: points[clone.centerPoint].y + 10
        }
    }
    clone.setID(globalObjectID - 1);
    clone.topLeft = points.push(clonedPoints.topLeft) - 1;
    clone.bottomRight = points.push(clonedPoints.bottomRight) - 1;
    clone.centerPoint = points.push(clonedPoints.centerPoint) - 1;

    if(clone.symbolkind === symbolKind.uml) {
        clone.middleDivider = clone.centerPoint;
    }
    clone.targeted = true;
    symbol.targeted = false;
    diagram.push(clone);
    return clone;
}`

**Comment by a18antsv** [comment]
```
function copySymbol(symbol) {
    const clone = Object.assign(new Symbol, symbol);

    const clonedPoints = {
        topLeft: {
            x: points[clone.topLeft].x + 10,
            y: points[clone.topLeft].y + 10
        },
        bottomRight: {
            x: points[clone.bottomRight].x + 10,
            y: points[clone.bottomRight].y + 10
        },
        centerPoint: {
            x: points[clone.centerPoint].x + 10,
            y: points[clone.centerPoint].y + 10
        }
    }

    clone.setID(globalObjectID - 1);
    clone.topLeft = points.push(clonedPoints.topLeft) - 1;
    clone.bottomRight = points.push(clonedPoints.bottomRight) - 1;
    clone.centerPoint = points.push(clonedPoints.centerPoint) - 1;

    if(clone.symbolkind === symbolKind.uml) {
        clone.middleDivider = clone.centerPoint;
    }

    clone.targeted = true;
    symbol.targeted = false;

    diagram.push(clone);

    return clone;
}
```

**Comment by a18antsv** [comment]
This solution could work with the new line connecting function if the connector arrays are cleared first.
