### ISSUE TITLE
Analytic page gone? 

### ISSUE THREAD

**Issue by b17carbr** [HGustavs/LenaSYS#8468]
There are a number of mentions of an analytic page being present in lenaSYS in the past. The reason for its removal needs to be investigated before work on a new analytic page starts up. These issues mention the presence of the analytic page:  https://github.com/HGustavs/LenaSYS/issues/2179 https://github.com/HGustavs/LenaSYS/issues/2179 https://github.com/HGustavs/LenaSYS/issues/496

Further investigation into the history of lenaSYS is required to find an answer. A closer look on the releases from 2016 and forward may uncover something. 

![Screenshot 2020-04-24 at 10 00 35](https://user-images.githubusercontent.com/62876614/80189435-f1a6df80-8612-11ea-92e5-b54e83f75a1a.png)

Trying to find logs regarding this on the current version have resulted in nothing:
![Screenshot 2020-04-24 at 10 06 50](https://user-images.githubusercontent.com/62876614/80189717-6c6ffa80-8613-11ea-9799-4373e5a6a9df.png)

**Comment by a18kaswi** [comment]
Regarding git log, we might need to search with wildcards said Henrik or if it was Marcus on discord.

**Comment by b17carbr** [comment]
In release V0.85 created 2016 all analytics is still present. This can be seen below.  

![Screenshot 2020-04-27 at 10 41 14](https://user-images.githubusercontent.com/62876614/80352407-25347480-8874-11ea-8629-9f6987997d0f.png)

But in the next release V0.9 created 2017 the analytics files are gone.

**Comment by a18filkr** [comment]
Closing this, already solved.
