### ISSUE TITLE
coursevers=UNK in URL after visiting codeviewer and going back to coursepage/sectioned using navbar back button

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8473]
After opening any codeviewer page (for example Webbprogrammering -> PHP Example 1), go back using the back button in the navbar. The coursepage will now have coursevers=UNK in URL and no course content is displayed. See screenshot.

Using the browser's back button works as expected (at least on Chrome).

![image](https://user-images.githubusercontent.com/49141758/80192495-91666c80-8617-11ea-9207-cf9b77094c7c.png)

**Comment by a18jonkl** [comment]
Checked this issue with branch G3-2020-W19 and seems to be working now.
<a href="https://gyazo.com/15b6ea98955fc3cba081ac3802de3040"><img src="https://i.gyazo.com/15b6ea98955fc3cba081ac3802de3040.gif" alt="Image from Gyazo" width="1280"/></a>

**Comment by a18jenro** [comment]
I agree with @a18jonkl, this seems to be working in the current state of master.

**Comment by c14jonfr** [comment]
@a18jonkl it does indeed seem to be working. 

However, it still seems like the URL changes after visiting a codeviewer.

When visiting the coursepage (from courseseed) the url is something like:
![image](https://user-images.githubusercontent.com/49141758/80574186-aa00c900-8a01-11ea-90a0-b49ebf91e85a.png)

After visiting codeviewer and using the navheader back button it is changed to this (it loses coursename):
![image](https://user-images.githubusercontent.com/49141758/80574235-c1d84d00-8a01-11ea-94a1-f83d17201109.png)

Possibly this should be an issue of it's own?
