### ISSUE TITLE
Copy and pasting UML-lines

### ISSUE THREAD

**Issue by o18marka** [HGustavs/LenaSYS#8503]
Recent solution makes it so that ER-lines can be correctly copy and pasted. Next we need a solution which handles UML-lines. This may be tougher due to their breakpoints. Though first issue #8462 must be solved before we can start working towards this.

**Comment by a18antsv** [comment]
The solution for #8462 mostly fixed UML-lines. The only problem left seems to be recursive UML-lines. This could be worth fixing for this issue.

**Comment by o18marka** [comment]
I've developed a solution for this. Waiting to PR it though until weekly merge is done tomorrow!
