### ISSUE TITLE
Trying to sort the Dugga Editor table breaks it

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8516]
Trying to sort the table by clicking one of the table headers (similar to how sorting can be done in Result Editor, Access Editor etc) will break the table. After a refresh the table will not load properly (showing only a blank page). Clearing the localstorage solves/resets this.

If this should be solved by fixing/adding functionality for sorting or simply disabling the table header "buttons" or something similar I do not now.

**Comment by a18oscte** [comment]
It is the same as issue #7996 were there is no compare function. @HGustavs needs to answer my question so we now if we should write a new compare function.

**Comment by c14jonfr** [comment]
@a18oscte was that issue not solved? I can quite clearly remember the Result Editor sorting being broken, but now it works just fine, yet the issue is still open.. I believe it was solved by moving the "newCompare" in sortableTable.js to resulted.js. Here is the issue (and in it the linked Pull Request) #8217.

But yes, this seems like a very similar issue.

**Comment by c14jonfr** [comment]
I've played around with a modified compare-function ("stolen" from fileed.js). It's currently very simple but works just as expected (and desired, I believe) for everything except for the Startdate column which has a few null values. The rows are still sorted but null is always "on top". 

I wonder if this is even a "real" issue (with null values)? When creating a new dugga through the user interface you are forced to enter a Startdate for the dugga or it won't create the new dugga. The duggas from the testdata has null values for the Startdate column (called jsondeadline in the db for some reason), but is there any realistic scenario where duggas will have null values for Startdate, when not using testdata?

**Comment by c14jonfr** [comment]
Update: I was wrong about null values always being placed at the top. They were not moved at all and kind of broke the sorting of the "real" values.

Because of that I added null value handling for my solution. The way it is set up is so that null values will always be placed at the bottom, which makes sense to me. Sorting for all of the columns work just as expected, user can sort ASC/DES for one column at a time, date values are sorted in correct order etc.

Is there anything else I need to keep in mind when solving this?

**Comment by b18jonli** [comment]
Closing since this has been merged.
