### ISSUE TITLE
Visiting the Dugga Editor without right to access user should be redirected to courseseed

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8517]
If a user visits the Result Editor or the Access Editor and does not have right to access, either through a link/URL or if a user with access logs out on one of these pages, they will be redirected to courseseed (LenaSYS homepage). This does not happen for the Dugga Editor.

This should be changed for consistency (and also because a normal user has no reason to be looking at the Dugga Editor, even if it shows only a blank page).

**Comment by b18jonli** [comment]
Merged to master.
