### ISSUE TITLE
Editor titles are a bit inconsistent

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8518]
Here are the different titles for Result, File, Access and Dugga Editor:
1. Result Editor - Edit student results
2. File Editor - Edit files
3. Access Editor - Database Access Editor
4. Dugga Editor - Dugga Modifications Editor

As you can see they don't really follow a common pattern. 1 and 2 are similar, and 3 and 4 are similar. 3 and 4 are more "title"-like and while 1 and 2 are more like instructions or descriptions about what the user can do on these pages.

I suggest these be changed so they all follow a similar pattern.

I suggest something like this:
1. Edit student results
2. Edit files
3. Edit course access 
4. Edit duggas

OR

1. Student Result Editor
2. File Editor
3. Course Access Editor
4. Dugga Editor

Note that these are only suggestions, your judgement about what is fitting is as good as mine.

**Comment by c14jonfr** [comment]
Group 2 will change the titles for Result Editor, Dugga Editor and Access Editor. I believe we will change the titles to something like the first suggestion in the issue. If we change our mind I will leave a new comment here. 

Someone from the group responsible for File Editor (Group 3?) should make the corresponding changes to that editor.

Please make sure to not close this issue before all of the titles have been changed.

**Comment by b18jonli** [comment]
Merged to master.
