### ISSUE TITLE
Edit-windows are not consistent across the system

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8528]
All Edit-windows across the system should look and behave consistently. The first screenshot shows an example from the Edit Dugga-window from the Dugga Editor. The second screenshot is from the Edit Item-window from the Section Editor. The screenshots show how a similar (or even identical) "error" is handled differently for the two windows.

**Edit Dugga/Dugga Editor.** When incorrect/not allowed characters are input the whole text field is marked with a different color and the Save-button is disabled.
![image](https://user-images.githubusercontent.com/49141758/80355320-354e5300-8878-11ea-8aab-a5eb3f7b0464.png)

**Edit Item/Section Editor.** When incorrect/not allowed characters are input only the border of the text field is marked with a different color and the Save-button is NOT disabled, letting the user save even if the text contains incorrect characters (this is a separate issue, #8482).
![image](https://user-images.githubusercontent.com/49141758/80355382-50b95e00-8878-11ea-92a3-973dafd01076.png)

**Comment by a18kaswi** [comment]
Affects more groups than only one. Should be discussed between groups how to solve.

**Comment by b20thelo** [comment]
Conclusion during testing.

The Colouring of the input box still isn't consistent as it colors in different ways. Description text plus error message doesn't follow the same format for all dialogues 

Image from Edit dugga: 
![image](https://user-images.githubusercontent.com/81772705/161766756-ba4e2931-bd76-4938-b9e0-acfd31c0c913.png)

Image from Settings for dugga.
![image](https://user-images.githubusercontent.com/81772705/161768385-a174428f-51c8-41a3-9346-4f6e2d67fcbb.png)


![image](https://user-images.githubusercontent.com/81772705/161768532-93ecdf86-6f71-4603-ab90-3ea51cfd2670.png)

Image from Course edit
![image](https://user-images.githubusercontent.com/81772705/161768665-e52c7d9e-8684-4320-8264-71f8a88729d1.png)

**Comment by i19matla** [comment]
The testing has been done on the old code.

Not the new code that works.
