### ISSUE TITLE
Fix first column to center in Resulted, Duggaed, Fileed and Accessed. 

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#8529]
The first column in Resulted, Duggaed, Fileed and Accessed look much better if the numbers is in center instead of to the left.
<img width="214" alt="Screenshot 2020-04-27 at 11 18 11" src="https://user-images.githubusercontent.com/49142649/80355910-f79dfa00-8878-11ea-9d73-6534c5e1f186.png"> <— From this 
<img width="214" alt="Screenshot 2020-04-27 at 11 18 55" src="https://user-images.githubusercontent.com/49142649/80355907-f7056380-8878-11ea-8781-2bb46d501fff.png"> <— To this

**Comment by b18jonli** [comment]
Merged to master.
