### ISSUE TITLE
Add border in Resulted to the table for consistency. 

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#8533]
In Duggaed, Fileed and Accessed all have a border-left: 2px solid #dbd0d8; border-right: 2px solid #dbd0d8; without Resulted and for consistency should it be on that one too.
<img width="454" alt="Screenshot 2020-04-27 at 11 56 40" src="https://user-images.githubusercontent.com/49142649/80359513-371b1500-887e-11ea-8a97-4451cef3e71f.png">
<img width="460" alt="Screenshot 2020-04-27 at 11 56 56" src="https://user-images.githubusercontent.com/49142649/80359519-384c4200-887e-11ea-8245-6ec09809a826.png">

**Comment by b18jonli** [comment]
Merged to master.
