### ISSUE TITLE
ResultEd table rendering rework

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8535]
The current rendering code of the table in resultEd is messy, inconsistent and does not always work correctly, I propose a rework of, among others, the renderCell function and the filters/views "late submissions", "only pending" and "mini mode".

The code that renders each view is separate and can most likely be reworked to be in a single place, as currently each change/addition to the rendering needs to change the code in multiple places.

Some issues to fix: 
 - "only pending" and "late submissions" do not combine, but instead the table prioritises "only pending" (Img 1)
 - "only pending" do not show all pending submissions (might be an issue of having removed the grade, should these be visible?) (Img 2, 3)
 - the "N/A" text in empty cells (#8406) is not visible in views "only pending" and"late submissions"
 - in "mini mode", the filters "only pending" and "late submissions" filters rows but not cells (e.g. there are still green cells for "G")(img 4)
 - "mini mode" names are styled incorrectly when scrolling (img 5)

1.
<img width="1011" alt="Screenshot 2020-04-27 at 11 57 56 AM" src="https://user-images.githubusercontent.com/62876553/80359644-65005980-887e-11ea-8f49-67696bf45327.png">

2.
<img width="1098" alt="Screenshot 2020-04-27 at 11 51 44 AM" src="https://user-images.githubusercontent.com/62876553/80359488-2ec2da00-887e-11ea-9941-16e2c1c36ac4.png">

3.
<img width="1046" alt="Screenshot 2020-04-27 at 11 51 52 AM" src="https://user-images.githubusercontent.com/62876553/80359506-35515180-887e-11ea-8ef8-4e0cc915c867.png">

4. 
<img width="754" alt="Screenshot 2020-04-27 at 12 06 20 PM" src="https://user-images.githubusercontent.com/62876553/80360367-844bb680-887f-11ea-913a-977484295e29.png">

5.
<img width="689" alt="Screenshot 2020-04-27 at 12 07 10 PM" src="https://user-images.githubusercontent.com/62876553/80360442-a5140c00-887f-11ea-8bdc-ce4017e5b031.png">

**Comment by b18jonli** [comment]
@HGustavs @mbrohede bra/dålig idé?

**Comment by a97marbr** [comment]
I think this is a good summary of a few of the many issues in resulted 😄 

I would use this issue as a starting point to break up into the individual parts of the issue. 

I agree that some of the filtering options are not checkbox options but rather radio button options

**Comment by a18viksa** [comment]
This issue is as far as I can tell finished. There are three separate PRs with fixes related to the problems described in this issue.
