### ISSUE TITLE
Bug in Resulted when click on fist.  

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#8536]
If you click on a fist in resulted for example Biträkningsdugga 2 which is graded. See img. 1
<img width="169" alt="Screenshot 2020-04-27 at 12 20 01" src="https://user-images.githubusercontent.com/49142649/80361572-75fe9a00-8881-11ea-9f45-b91f8ede9d1a.png">  
**img 1.**
Then this box pops up. Which is correct content to the one we click on. 
<img width="1247" alt="Screenshot 2020-04-27 at 12 26 18" src="https://user-images.githubusercontent.com/49142649/80362096-52881f00-8882-11ea-836f-46e60f41ab40.png">
**img 2.**
But if we click on a grey Clippning see img 3. 
<img width="165" alt="Screenshot 2020-04-27 at 12 30 10" src="https://user-images.githubusercontent.com/49142649/80362389-db06bf80-8882-11ea-8a63-643cc2571f28.png">
**img 3.** 
It will be a incorrect popup. That's the one you pressed before. See img 4
<img width="1250" alt="Screenshot 2020-04-27 at 12 29 53" src="https://user-images.githubusercontent.com/49142649/80362600-320c9480-8883-11ea-9b91-d170b3e5f820.png">
**img 4.**

 - Notice in the corner of img 4 it is the right heading but the wrong person and the wrong content.
- If you haven't pressed anyone before, the right headline and person will come up. But without content.

**Comment by b18jonli** [comment]
If this only happens when the second click is on a "moment" (i.e. not a dugga) then it will be fixed by (or at least won't be a problem) after #8501

**Comment by a18viksa** [comment]
This issue has been solved. Closing issue.
