### ISSUE TITLE
The receipt pop-up for when one hands something in is to small for the content 

### ISSUE THREAD

**Issue by a18marax** [HGustavs/LenaSYS#8544]
When you click save receipt the content of the popup gets to big and one needs to scroll both sideways and down to fill in the email adress push send.

It fits at first:
![Skärmbild från 2020-04-27 11-15-38](https://user-images.githubusercontent.com/9322253/80371047-8585df00-8891-11ea-96ad-96ab088e295c.png)

But after one press save:
![Skärmbild från 2020-04-27 11-15-44](https://user-images.githubusercontent.com/9322253/80371288-f3320b00-8891-11ea-83a7-fd826b161e61.png)
![Skärmbild från 2020-04-27 11-15-58](https://user-images.githubusercontent.com/9322253/80371299-f7f6bf00-8891-11ea-8c21-4e264edfccc0.png)

**Comment by b18alegu** [comment]
Closing this issue after weekly merge.
