### ISSUE TITLE
Connect loose lines to objects

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8553]
It is not possible to create loose lines. Lines should be connected to two objects for it to be possible to create them. It is possible to copy a line between two objects though, making it loose. It is not possible to connect the loose line to objects right now, this should be fixed if the functionality of copying lines should remain. Also make decisions regarding the possibility to create loose lines that are not connected to anything.

**Comment by a18antsv** [comment]
Wait with fixing this until all copy paste issues have been resolved.

**Comment by o18marka** [comment]
This issue together with #5057 could possibly be solved by adding a functionality to pull line-ends off their original connection and connect them to another object / another side of the same object. 

It may be more difficult to develop something as i mentioned , but i think it could prove to be a useful functionality.

**Comment by o18marka** [comment]
> This issue together with #5057 could possibly be solved by adding a functionality to pull line-ends off their original connection and connect them to another object / another side of the same object.
> 
> It may be more difficult to develop something as i mentioned , but i think it could prove to be a useful functionality.

To further elaborate, i think line-ends should be movable and "snap" on to objects when close enough to a appropriate point.

**Comment by b18phibe** [comment]
sucsessfully merged
