### ISSUE TITLE
shared/loginbox.php needs fixing in indentation

### ISSUE THREAD

**Issue by a13denli** [HGustavs/LenaSYS#856]
DON'T DO THIS DURING THE WEEK(ONLY DURING WEEKLY MERGE TIME)

**Comment by HGustavs** [comment]
I think that this is a management problem and not a development issue.

Closing issue.

**Comment by HGustavs** [comment]
to clarify... I concur with the need to fix the indentation, but I think we can keep this off the issue tree as it is.... it is more of a review issue and a management issue than a programming issue... so it is probably better as a comment on a merge than on a separate issue.
