### ISSUE TITLE
Login/Logout button in Safari is not following the width of other browsers

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#8565]
<img width="1458" alt="Skärmavbild 2020-04-28 kl  09 48 03" src="https://user-images.githubusercontent.com/49141837/80461447-8f611e00-8935-11ea-82d1-48ed6f84f96e.png">

**Comment by a18jenro** [comment]
To test this, if you don't have access to Safari, which has no new version available for windows, you can download a cross browsing testing tool. There are several free trial versions available for such tools, for example lambdatest. I was able to test this issue on Safari within a few minutes using lambdatest.

**Comment by a18jenro** [comment]
But I wasn't able to figure out a solution before my free tests ran out.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
