### ISSUE TITLE
Fileed not accessible when logged in

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#8566]
When trying to access Fileed we get reddirected to courseed when logged into Toddler & Brom, probably affects all users that should have access to fileed.

After some testing I've found out that this bit of code in fileed.js seems to be the cause of this issue.

```    //Redirects users without write-access to courseed.php
    if (!data.writeaccess) {
		window.location.href = 'courseed.php';
    }

**Comment by c14jonfr** [comment]
See #8519. The linked pull request is supposed to have made it so users without access are redirected. If users who do/should have access are redirected something is obviously wrong. Maybe it wasn't tested properly before being merged?

**Comment by c14jonfr** [comment]
There is no writeaccess in the returned data from fileedservice. Change it to 
```
    if (!data.access) {
		window.location.href = 'courseed.php';
    }
```
and it should work as expected.
