### ISSUE TITLE
Using the enter key to progress through the installer

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8569]
When using the LenaSYS installer I keep on pressing `enter` to go to next step in the process. Using the mouse feels a bit awkward since the rest of the process can be done entirely using the keyboard. I think this functionality should be considered to improve the feel of LenaSYS.

**Comment by a18kaswi** [comment]
https://pastebin.com/RJuqkKE8 <- This code with comment /* You want to be able to press enter to continue, this function fixes this. */ exist within the install.php. 

Unclear why this isn't working for @b18alegu I will look further into it. Maybe it's a local problem, don't know.

**Comment by b18alegu** [comment]
I tried it locally in chrome on a Macintosh. I'll try it out in Firefox as well later today.

**Comment by b18alegu** [comment]
I did not work in Firefox either.

**Comment by a18kaswi** [comment]
Seems that the fix for issue #8193 solves this to. 

Feel free to test on http://group4.webug.his.se:20001/G4-2020-W19-ISSUE%238193/install/install.php to see that I get what your asking for @b18alegu :)

**Comment by a18kaswi** [comment]
Solved with pr #8647
