### ISSUE TITLE
Hexadecimal input boxes can only be closed by selecting a value in duggor

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8572]
After opening a hexadecimal input box by clicking the "selected value box" (the big button/box with default value 0) it's impossible to close the hexadecimal input box without selecting a value. At least for me, the expected behaviour would be that clicking the "selected value box" again, or clicking outside the element would close the input box.

There seems to be no code for this kind of behaviour so I wouldn't consider it a bug but to me it definitely _feels_ like a bug which of course is frustrating.

This can be observed in both Biträkningsduggor and Färgduggor.

![image](https://user-images.githubusercontent.com/49141758/80465796-eff35980-893b-11ea-854d-103cd5353cc7.png)

**Comment by b18jonli** [comment]
This has been merged, closing issue.
