### ISSUE TITLE
Logging: analytic page - "Service Usage" button.

### ISSUE THREAD

**Issue by a18jakme** [HGustavs/LenaSYS#8573]
With older analytic files now moved into current LenaSYS we need to determine whether the functionality of the analytic page is correct.
Determine if the "Service Usage" button is working with the logging system. When navigate through navbar buttons the functionality does not work correctly. For example, sometimes the "Service Usage" page show content from "Service Speed" and vice versa.

![image](https://user-images.githubusercontent.com/49142935/80466152-6a23de00-893c-11ea-895d-0f1a70063fbe.png)

**Comment by d17marle** [comment]
Couldnt replicate the issue where navigating gives the wrong page
