### ISSUE TITLE
Add ~/ to .gitignore

### ISSUE THREAD

**Issue by a18marax** [HGustavs/LenaSYS#8577]
For linux users this will be very helpful since that folder will always be updated and shouldn't be pushed.

**Comment by HGustavs** [comment]
Yes no problem.

Make sure this has no other negative effects.

**Comment by b18jonli** [comment]
Alternatively, if this is a problem created by the location of the LenaSys files locally and not for all linux users, you could add it into you .git/info/exclude file. This fixes the problem locally but won't be synced so it cannot affect other participants negatively. (e.g. if someone has lenasys files in their home folder)
