### ISSUE TITLE
Logging: analytic page - "Service crashes" button

### ISSUE THREAD

**Issue by a18jakme** [HGustavs/LenaSYS#8581]
With older analytic files now moved into current LenaSYS we need to determine whether the functionality of the analytic page is correct.
Determine if the "Service crashers" button is working with the logging system. When navigate through navbar buttons the functionality does not work correctly. 

![image](https://user-images.githubusercontent.com/49142935/80469937-8f671b00-8941-11ea-9340-9cc3eb0d1260.png)

**Comment by d17marle** [comment]
In the description it says to check out "Service Usage" but on the picture "Service speed" is highlighted. Which one is it in this case

**Comment by a18jakme** [comment]
@d17marle Picture changed.
