### ISSUE TITLE
Text outside UML-class when exporting

### ISSUE THREAD

**Issue by o18marka** [HGustavs/LenaSYS#8594]
When exporting diagram as svg, and a UML-class is resized to be smaller then original, text overflows outside UML-class object: 
![issue_textoutside](https://user-images.githubusercontent.com/49142263/80481690-3acc9b80-8953-11ea-8440-068709e371ba.PNG)

**Comment by o18marka** [comment]
Should it even be possible to resize UML-class objects this small?

**Comment by a17robhe** [comment]
@o18marka I couldn't reproduce this issue
![test](https://user-images.githubusercontent.com/62876844/80576660-e0d8de00-8a05-11ea-8029-560a1f5cb0eb.gif)

The transform function seems a bit bugged though.

**Comment by o18marka** [comment]
Like i was onto in my last comment, the actual issue here is being able to resize UML-classes smaller then the actual minimum size of the object.

**Comment by a17robhe** [comment]
The entire resize functionality could probably use a rework
![test](https://user-images.githubusercontent.com/62876844/80592039-0cb48d80-8a1f-11ea-8304-308f6c1e599a.gif)

**Comment by a17robhe** [comment]
It seems like resizing using a point other than the bottom right one causes the min width variable to change.

![test4](https://user-images.githubusercontent.com/62876844/80688655-70e15b00-8acc-11ea-9fae-89f896ec1a67.gif)

**Comment by a17robhe** [comment]
Det verkar som att denna raden kod ändrar minWidth på en inkorrekt sätt
![Untitled](https://user-images.githubusercontent.com/62876844/80693198-f2d48280-8ad2-11ea-93f7-a431ea74c1b7.png)
