### ISSUE TITLE
Image-link broken in "Random css dugga" and "Random clipping dugga"

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8595]
Either the images are missing or the linking of images doesn't work in "Random css dugga", "Random clipping dugga" and likely in other places as well inside other "duggor".

**Random clipping dugga** (Webbutveckling - datorgrafik course)
<img width="505" alt="Skärmavbild 2020-04-28 kl  13 29 10" src="https://user-images.githubusercontent.com/62876260/80482462-8e8bb480-8954-11ea-8cac-298a5834bc6a.png">

**Comment by b18jonli** [comment]
This has been merged, closing issue.
