### ISSUE TITLE
CodeViewer: A new template should be implemented

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#860]
A new template with four windows with a 1+3 structure is needed by the customer;
![new template issue](https://cloud.githubusercontent.com/assets/11715479/7115629/9508678e-e1ea-11e4-9fe0-a7a215d128e7.jpg)

**Comment by a13jorla** [comment]
From issue #501 .

**Comment by a13jorla** [comment]
Have made a merge and closing the two issues.
