### ISSUE TITLE
Generate example UML diagram does not work

### ISSUE THREAD

**Issue by a18jonpe** [HGustavs/LenaSYS#8600]
Trying to generate an example UML diagram gives the following error. 
![image](https://user-images.githubusercontent.com/62878096/80484268-b892a600-8957-11ea-85e9-61bca6afcf63.png)
This is caused by some values missing regarding the cardinality that is added in the "generateUMLExampleCode" function. This can be solved either by adding values manually, or adding this code 
`let boxCorners = this.corners();
        let dtlx, dlty, dbrx, dbry;            // Corners for diagram objects and line

        const cardinality = this.cardinality;

        // Correct corner e.g. top left, top right, bottom left or bottom right
        let correctCorner = getCorrectCorner(cardinality,
                                            boxCorners.tl.x,
                                            boxCorners.tl.y,
                                            boxCorners.br.x,
                                            boxCorners.br.y);

        // Find which box the cardinality number is connected to
        for(var i = 0; i < diagram.length; i++) {
            dtlx = diagram[i].corners().tl.x;
            dtly = diagram[i].corners().tl.y;
            dbrx = diagram[i].corners().br.x;
            dbry = diagram[i].corners().br.y;

            if(correctCorner.x == dtlx || correctCorner.x == dbrx || correctCorner.y == dtly || correctCorner.y == dbry) {
                cardinality.parentBox = diagram[i];
                delete cardinality.parentBox.cardinality.parentBox;
                break;
            }
        }`
This will make sure a parentbox is created for the cardinality.

**Comment by a18antsv** [comment]
#8666
