### ISSUE TITLE
UML-lines invisible after free-draw

### ISSUE THREAD

**Issue by o18marka** [HGustavs/LenaSYS#8615]
UML-lines are invisible after a path/free-draw object has been created. Problem persists until localstorage has been cleared.
![issue3](https://user-images.githubusercontent.com/49142263/80496471-8ab65d00-8969-11ea-898b-3d61bc06b9fc.gif)

**Comment by a18antsv** [comment]
The reason for this seems to be that the value of variable figureType remains as "Free" after creating a free draw object and a line will not be created if this is the current figureType.

**Comment by o18marka** [comment]
Sound like a easy fix if that is the case^
