### ISSUE TITLE
Lines in diagram examples are not connected to the objects

### ISSUE THREAD

**Issue by a18jonpe** [HGustavs/LenaSYS#8622]
The lines in the diagram examples are not connected to the objects, moving an object does not affect any lines. Solve [issue 8600](https://github.com/HGustavs/LenaSYS/issues/8600) before attempting to solve this.

**Comment by a18antsv** [comment]
Why not create a diagram in the actual diagram, export a file and store this file on the server. Load this file instead for the example diagram. This would be much simpler than writing the code yourself. Everything will be handled the same way as you would import a diagram so you should not have any problems with connections and all example diagram code can be removed.

**Comment by a18antsv** [comment]
This could then be a good example diagram.
![image](https://user-images.githubusercontent.com/49121839/81155435-3a508800-8f85-11ea-93e2-b2f957cf18dd.png)

**Comment by a18jonpe** [comment]
I will look into this!
