### ISSUE TITLE
In nav header the search bar and download button appears to the right

### ISSUE THREAD

**Issue by a18lukto** [HGustavs/LenaSYS#8625]
![image](https://user-images.githubusercontent.com/49182858/80572178-1b3e7d00-89fe-11ea-98e7-d6e76d54fc23.png)
When you are logged in as teacher1 the search bar and download all files to zip button will appear to the right. This is inconsistent to the current design of the webb page.

**Comment by b20eripe** [comment]
![Skärmbild från 2022-04-05 13-53-46](https://user-images.githubusercontent.com/102593527/161748261-01e76dd4-fb05-46cb-b577-eb9cd5ecc65b.png)

Issue investigated and seems to be solved @c20adael
