### ISSUE TITLE
Textinput for name in Edit Dugga box  in Dugga Editor is way too wide

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8627]
This issue occured after the W18 merge.

This is what it looked like before the merge:
![image](https://user-images.githubusercontent.com/49141758/80572501-ae77b280-89fe-11ea-93d6-5cb4fbc16d1a.png)

And this is what it looks like now (after the merge):
![image](https://user-images.githubusercontent.com/49141758/80572547-c0595580-89fe-11ea-9633-240d648494c3.png)

The styling is applied by #name from style.css. #name is also used in diagram.php.

One way to solve this issue is to make the styling apply to only the #name in diagram.php by doing something like this (putting #appearanceForm before #name):
![image](https://user-images.githubusercontent.com/49141758/80572747-17f7c100-89ff-11ea-958e-6ee7c79f7452.png)

**Comment by c14jonfr** [comment]
I wasn't sure what labels to put for this. The issue itself affects Group 2 and the Dugga Editor, but the previous changes belong to Group 4 and the Diagram. My suggested change _should_ solve the issue without negatively affecting Group 4's changes in any way but I want to make sure everyone involved knows what's going on.

**Comment by c14jonfr** [comment]
I've left this unlabeled for a few hours now, I'll just smack the Group 2 label on for now.

**Comment by b18jonli** [comment]
Closing since this has been merged.
