### ISSUE TITLE
ShowDugga: Panel placed to low

### ISSUE THREAD

**Issue by a18viksa** [HGustavs/LenaSYS#8678]
The panel is placed too far away from the button. This is because there's no "top" implemented. 

![image](https://user-images.githubusercontent.com/49142704/80600792-35438400-8a2d-11ea-9102-02104f835dad.png)

The goal is to make it look like this, by adding "top: -35px". This is just added in dev tools and not in the actual code, which is a lot harder. 

![image](https://user-images.githubusercontent.com/49142704/80601315-f19d4a00-8a2d-11ea-9dd0-5227ba8afb19.png)

**Comment by b18jonli** [comment]
This has been merged, closing issue.
