### ISSUE TITLE
Separation should take the possibility of removing a separator into account

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8681]
It is possible to edit multiple objects properties at the same time with the new appearance menu functionality. This is possible by a separator as seen in this image. It would for example be possible to change the Person UML class name by changing the text where it says "Person" before the comma separator and so on. The same applies to textareas where different objects are separated by a comma followed by a new line.
![image](https://user-images.githubusercontent.com/49121839/80608457-15b15900-8a37-11ea-8b1b-3e340ad02165.png)

The way indexes are handled for the separation will cause problems and break if a separator is removed. The index needs to be changed in some way. When one separator is removed this needs to be taken into account.

**Comment by a18antsv** [comment]
The solution for issue #8557 just fixed so a separator do not appear after the last object.

**Comment by a18antsv** [comment]
Maybe it would be good to use another separator than comma. Comma might be needed sometimes so ~ or something could be used instead.

**Comment by b18phibe** [comment]
merged
