### ISSUE TITLE
Stats to show who is active and where they are active

### ISSUE THREAD

**Issue by a18eliek** [HGustavs/LenaSYS#8692]
It would be nice to be able to see what users are logged in currently (maybe last 15 minutes) and guests. We could probably make it possible to see what page they are on, and with that data we can see at what times the different courses are being in use.

**Comment by b17carbr** [comment]
@a18eliek This issue might require that we log the uid in page load logging. Currently there is only page logging for codeviewer and showDugga and both lack logging for uid. Below you can see the attributes present in both tables. 

![Screenshot 2020-05-05 at 13 45 08](https://user-images.githubusercontent.com/62876614/81062704-c2c41f80-8ed6-11ea-9e64-58907d217c73.png)

![Screenshot 2020-05-05 at 13 45 16](https://user-images.githubusercontent.com/62876614/81062724-c9eb2d80-8ed6-11ea-835c-c5a3888f41a3.png)

To solve this we might need to create additional tables in basic.php for page logging and add the uid attribute to tables which already log pages. For example these tables need uid assigned to them. 

![Screenshot 2020-05-05 at 14 11 28](https://user-images.githubusercontent.com/62876614/81064649-5519f280-8eda-11ea-91bb-e1308befb5ef.png)

For user events such as creation of files among others we already have quite a lot of logging in the userLogEntries table.
