### ISSUE TITLE
I'd like to see recent feedbacks in the navheader

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#8697]
It would be nice if a modal/dialog slides down with recent feedbacks from teachers so students does not have to scroll down and click on course-moment then scroll down again and then click on feedback-button to see the full feedback.

**Comment by a18mahkh** [comment]
@HGustavs @a97marbr

**Comment by a18mahkh** [comment]
Do you think this is a good feature to implement?

@HGustavs  @a97marbr

**Comment by a97marbr** [comment]
Perhaps a mockup of how this could look?

**Comment by a18mahkh** [comment]
![mockup](https://user-images.githubusercontent.com/49142349/81265421-5c104480-9043-11ea-86b6-380016ccee78.png)


And this will slide down from the navheader

@a97marbr  @HGustavs

**Comment by a18mahkh** [comment]
Overflowed comments will be hidden and linked, to display the full comment on click. 
@a97marbr  @HGustavs

**Comment by a97marbr** [comment]
Ok this might be a useful feature ... let's see how it turns out
