### ISSUE TITLE
New feedback icon

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#8698]
Need an new feedback-icon prior to issue #8697

**Comment by a18jenro** [comment]
@a17towan This has been in progress for a while, how is it going?

**Comment by a17towan** [comment]
I have ideas in store but cannot implement them until the OP has implemented a 'feedback' functionality where I can test the icons.

**Comment by a17towan** [comment]
The icon is now ready for implementation, but issue #8697 needs to be merged into the weekly group branch first.
