### ISSUE TITLE
CodeViewer: Highlight between boxes

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#870]
![weird highlights](https://cloud.githubusercontent.com/assets/11715479/7116508/35147888-e1f2-11e4-80fd-ef5c28c22b59.jpg)
There seems to be a bug where the highlighting doesnt appear in the comment field aswell as the code field when hovered!

**Comment by c12jenek** [comment]
This issue refers to when you're hovering the right box's "elem" it highlights correctly in the left box and not in the right box

**Comment by c12jenek** [comment]
This issue is not a bug but a feature, it's a matter of if the impword is on an important line or not

**Comment by b12simsa** [comment]
Fix for this issue merged in pull-request #870.
