### ISSUE TITLE
Recent announcements in teacher2

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#8700]
This is because to allow instructors to broadcast information out to all members of a course or to all members of sections within a course, so they don't have to send e-mail.

**Comment by a18mahkh** [comment]
@HGustavs @a97marbr

**Comment by a97marbr** [comment]
Not sure what this issue targets, but ...

If we have a broadcast feature (which is great!) we need a way to distinguish finished/non-finished students of a course. I'm guessing that students who has completed the course is'n interested in knowing new re-exam dates etc.

**Comment by a18mahkh** [comment]
It's pretty much what you've guessed. 
The reason why this feature would be great it because of students has to check lots of e-mails and the important ones gets lost among those e-mails e.g important announcements like examination delay, answer general questions asked by students and so on. 
This is much more simpler and concrete way of communication with the students.

**Comment by a18mahkh** [comment]
@a97marbr  @HGustavs
