### ISSUE TITLE
New announcement-icon

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#8701]
Need an new announcement-icon prior to issue #8700

**Comment by a18mahkh** [comment]
We got green light from the customer to continue with issue.

**Comment by a18mahkh** [comment]
@a17towan

**Comment by a18mahkh** [comment]
Fetch the branch G3-2020#8700 before implementing the icon because it's not merged into our weekly branch.

**Comment by a17towan** [comment]
![image](https://user-images.githubusercontent.com/49142028/81280479-d4353500-9058-11ea-888a-e931837844be.png)

@a18mahkh
