### ISSUE TITLE
Making items added from the fab-button appear centered depending on users viewpoint.

### ISSUE THREAD

**Issue by a18jonsj** [HGustavs/LenaSYS#8705]
While working on issue #8271 we solved almost all the functionalites, but theres is still a thing that needs to be fixed. When a user adds a new "item" by clicking on the fab-button, the new items is supposed to appear in the center of the screen if the user has scrolled down, meaing it should not appear at the bottom which is the case right now.

**Comment by b19wilfo** [comment]
@HGustavs @a97marbr We are not quite sure what we are supposed to do on this issue, could we get some clarification?

**Comment by a19isada** [comment]
@b19wilfo When adding a new item, it appears at a specific location of the page. This appears to be the bottom if the page is small enough. However, if the page is long enough, the new items can appear in the middle if the page and be difficult to find. 
This is currently where they are added. 
![image](https://user-images.githubusercontent.com/81559946/114867231-cfded380-9df4-11eb-9780-ce5fdbc49fd8.png)


They should be added more like at this location, in the middle of the screen:
![image](https://user-images.githubusercontent.com/81559946/114867580-47acfe00-9df5-11eb-9fb3-86685c8370c3.png)

**Comment by a19isada** [comment]
I think this only occurs when using this button, the other button seems to be adding items from the top. 
![image](https://user-images.githubusercontent.com/81559946/114868965-c48ca780-9df6-11eb-824e-f31e4fa23011.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
