### ISSUE TITLE
Dugga Editor: renderCell-function cleanup

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8710]
The `renderCell`-function in `duggaed.js` is a bit messy. It has the following issues which should be cleaned up:
-Plenty of `if else`-statements. `switch...case` should be used instead
-Commented code can be removed
-Inconsistent commenting

Will also correct the indentation of the `setup`-function in the same file since it's stupid and annoying at the moment:
<img width="396" alt="Skärmavbild 2020-04-30 kl  11 40 17" src="https://user-images.githubusercontent.com/62876260/80696240-6aa4ac00-8ad7-11ea-8aa9-29f4175d2226.png">

**Comment by b18jonli** [comment]
Closing since this has been merged.
