### ISSUE TITLE
In 'edit item' window you can type in special characters but not "+"

### ISSUE THREAD

**Issue by a17towan** [HGustavs/LenaSYS#8731]
As of right now you are allowed to type in special characters when naming your item, all except the + sign, which doesn't show up. 

![image](https://user-images.githubusercontent.com/49142028/80712068-aa788d00-8af1-11ea-8424-ae2b53089190.png)

![image](https://user-images.githubusercontent.com/49142028/80712113-c11ee400-8af1-11ea-9480-a13ebf6cfb7c.png)

The + sign should probably be allowed to show up.

**Comment by a18jimol** [comment]
The reason why the "+" gets removed is becauce when it gets send to sectionedservice.php it goes through the function getOP in basic.php and in getOP uldecode is used on the name and removes the "+". Do you want us to fix this so you can use "+" in section-names or is this inteaded?

**Comment by a17towan** [comment]
Hm, well yes, I would like it so that the "+" is visible in the dugga name.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
