### ISSUE TITLE
UML line hover breaks after zoom

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#8745]
Recent changes to how UML line hovering works broke it completely after zooming. Hover seems to only be working when the zoom value is at 100% and the camera is exactly in default origo position (Shift + O at 100% zoom value).

**Comment by b18mikfr** [comment]
Fixed, There was an issue too where the hover also broke not only with zoom but when the origin of the canvas was not on the origo point of the map. Two birds, one stone :)
