### ISSUE TITLE
CodeViewer Markdown switch between the markdown and text area for editing it

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#875]
It would be nice if people with editing privileges could switch between markdown and a textarea for editing the markdown. Similarly to how the comments works on gitHub.

**Comment by b12simsa** [comment]
Since this most likely will take to long time to complete, we have decided to not implement this now.

**Comment by HGustavs** [comment]
Can we produce a mockup of this?

**Comment by A15cecal** [comment]
@HGustavs Mockup still relevant? And if so, do you have any input on how you want the design, any suggestions?

**Comment by c16linst** [comment]
This issue is replaced by #4949
