### ISSUE TITLE
Save/Reset-buttons in duggas are not visible on smaller screen/window sizes

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8756]
**This can happen for all devices, not only mobile devices as previously stated. Resizing the window will push the buttons out of screen even for bigger screens.**

See screenshot (from Färgdugga). The Save and Reset buttons are pushed out of screen by the other content. When the hexadecimal input boxes are open the Save and Reset buttons are not visible at all. A "workaround" for the user is to close/minimize the instructions accordion, but this should not be needed. 
![image](https://user-images.githubusercontent.com/49141758/80942093-3df8d900-8de4-11ea-9fb3-bb0ff2a3ecf9.png)

This doesn't seem to be a problem for all duggas, but I'm pretty sure all duggas contain the root problem with the content pushing the buttons out of screen. I haven't looked into it but it could maybe be solved with a few CSS tweaks (which would solve the issue for all the duggas at once, so I would suggest looking into this before trying anything else).

The severity of this issue depends on the device. For example the iPhone X setting in Chrome, the buttons are visible (as long as the hexadecimal input box is not open) but for most other devices the buttons are either partially or fully pushed out of screen.

**Comment by b18veran** [comment]
This is a problem even in computer mode when the hexadecimal input box is open.

**Comment by c14jonfr** [comment]
@b18veran thanks for noticing! I'll update the title/description

**Comment by b18jonli** [comment]
Closing since this has been merged.
