### ISSUE TITLE
Content in Transformationsdugga not positioned properly on smaller screen sizes

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8761]
When doing a Transformationsdugga on smaller screen (or window) sizes the content is not positioned properly. The content should be positioned vertically in some way. Currently it causes the page to scroll sideways, which is almost never a good thing. Additionally, when the screen/window becomes small enough the instructions for the dugga disappears completely.

I believe positioning the content in a better way would make the dugga useable for small screen sizes.

![image](https://user-images.githubusercontent.com/49141758/80945278-be6f0800-8deb-11ea-831e-9bf5f5727184.png)

**Comment by c14jonfr** [comment]
I've played around a bit with both the Chrome and Firefox developer tools and they seem to behave a bit differently compared to each other. For example the breakpoints where things start to look messed up are a bit different between the two browsers which of course makes it hard to judge how it will behave on real mobile devices.

**Comment by b18jonli** [comment]
This has been merged, closing issue.
