### ISSUE TITLE
Minor visual inconsistencies in the Variant Editor

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8786]
In the **Variant Editor** (part of Dugga Editor) there are som mine visual inconsistencies that should be fixed:
- The enumeration column is not centered unlike the main Dugga Editor window
- In some textboxes the text is too close to its left side
- The **looking glass** and **+** icons are not aligned correctly in the vertical axis

<img width="1288" alt="Skärmavbild 2020-05-04 kl  12 02 43" src="https://user-images.githubusercontent.com/62876260/80956209-0e0bfe80-8e01-11ea-86c1-7f7a212c8b7a.png">

**Comment by b18jonli** [comment]
Closing since this has been merged.
