### ISSUE TITLE
Make it possible to install LenaSYS anywhere on Linux systems

### ISSUE THREAD

**Issue by a18marax** [HGustavs/LenaSYS#8805]
At the moment it dosen't seems to be possible to install LenaSYS on Linux except for in the /var/www/html/ directory which forces the developers on that particular platform to run the code editor as root which is inconvenient and also is not recommend. One problem being that a directory with the path ~/ will be able to be pushed the same problem that was reported in issue #8577. If the suggested update was to be pushed then it would need to be nullified since it possibly could make it impossible to push from certain directories.

**Comment by b18alegu** [comment]
This is probably not an issue with LenaSYS but with your local configuration. Under the ["Web Site Content" subheader on this homepage](https://httpd.apache.org/docs/2.4/getting-started.html#content) you'll get some advice on how to configure this to your preferences.

**Comment by a18kaswi** [comment]
As @b18alegu states this has little to do with the LenaSYS(installer).

`# Sets the default security model of the Apache2 HTTPD server. It does
# not allow access to the root filesystem outside of /usr/share and /var/www.
# The former is used by web applications packaged in Debian,
# the latter may be used for local directories served by the web server. If
# your system is serving content from a sub-directory in /srv you must allow
# access here, or in any related virtual host.
<Directory />
	Options FollowSymLinks
	AllowOverride None
	Require all denied
</Directory>

<Directory /usr/share>
	AllowOverride None
	Require all granted
</Directory>

<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>

#<Directory /srv/>
#	Options Indexes FollowSymLinks
#	AllowOverride None
#	Require all granted
#</Directory>`

The key context here being "It does
# not allow access to the root filesystem outside of /usr/share and /var/www." follow further instructions to enable on the linux-system you are using to deploy LenaSYS.
