### ISSUE TITLE
Resulted: Styling rework 

### ISSUE THREAD

**Issue by a18viksa** [HGustavs/LenaSYS#8806]
This issue is a sub-issue to "ResultEd table rendering rework #8535". It was easier to split the issue in to two separate issues. 

This issue is supposed to handle all the styling issues. They are as @b18jonli stated in the original issue: 

- the "N/A" text in empty cells (#8406) is not visible in views "only pending" and"late submissions"

- "mini mode" names are styled incorrectly when scrolling. The normal table has a similar issue as well. 

![image](https://user-images.githubusercontent.com/49142704/80979232-5fc77f80-8e27-11ea-8bef-10dc863aac17.png)

![image](https://user-images.githubusercontent.com/49142704/80979310-75d54000-8e27-11ea-9e32-366e116ffb55.png)

**Comment by b18jonli** [comment]
Closing since this has been merged.
