### ISSUE TITLE
Unsubmitted results breaks rendering

### ISSUE THREAD

**Issue by a18eripi** [HGustavs/LenaSYS#8807]
If time is set to zero on creation of an assignment, as in frågedugga 1, the rendering looks wrong.

This is a related issue to https://github.com/HGustavs/LenaSYS/issues/8632

While solving that issue, instead of date inform, type out that the assignment is not submitted

Co-authored-by: b18fella <b18fella@users.noreply.github.com>

**Comment by b18jonli** [comment]
Closing since this has been merged.
