### ISSUE TITLE
File editor: No margin between radio buttons and table

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8812]
In the file editor there is no margin between the radio buttons and the table which looks a little cramped. Especially on Chrome where the radio buttons are slightly larger. **Suggested value of the margin is 20px** for consistency with the Result, Access and Dugga editors.

An example:
<img width="782" alt="Skärmavbild 2020-05-04 kl  21 58 29" src="https://user-images.githubusercontent.com/62876260/81008851-e85c1500-8e53-11ea-84ce-8578c47b61d1.png">

**Comment by a18jenro** [comment]
@b18alegu I don't have this problem:
![untitled](https://user-images.githubusercontent.com/62876507/81041790-0014b700-8eaf-11ea-8c7f-88f4b25d6876.PNG)

Is it so that this is only a problem when using Chrome on Mac?

**Comment by b18alegu** [comment]
> Is it so that this is only a problem when using Chrome on Mac?

It might add to the problem, the OS might influence the look of the radio buttons...? I am 100% the zoom level was neutral when I took the screenshots.

I still believe there should be a **margin of 20px** between the radio buttons and the table like in the other editors in LenaSYS.

**Comment by a18fayha** [comment]
Something like this? 
![image](https://user-images.githubusercontent.com/62876354/81280393-b1a31c00-9058-11ea-8e21-556b7076a514.png)

**Comment by a18jenro** [comment]
@ba18alegu could you confirm that this looks good on your device: http://group3.webug.his.se:20001/G3-2020-W20%238812/

**Comment by a18jenro** [comment]
This was confirmed ok by a mac user.
