### ISSUE TITLE
Chrome autologin fills search bar and breaks SQL queries.

### ISSUE THREAD

**Issue by a18eripi** [HGustavs/LenaSYS#8815]
If letting Chrome handle autologin to pages, when you navigate to a page with a search bar, chrome attempts to log into the search field with login details.

This happends before everything is properly loaded and seems to break the render function.

To reproduce, go into Autofill in chrome and let it save your password. Then login as Toddler and let chrome save it. Next time you go to a page with a search bar, it will break the page and produce an error in the console:

![sqlBork](https://user-images.githubusercontent.com/43380274/81042174-d14b1080-8eaf-11ea-8d39-cfb6fc9721d0.png)

A suggestion would be to unflag(?) the search field so that Chrome does not try to autofill it.

**Comment by a18oscba** [comment]
For now I am unable to recreate the error. Unsure if it has been fixed or only not working for some people.
