### ISSUE TITLE
Reduce the amount of used storage

### ISSUE THREAD

**Issue by b18phibe** [HGustavs/LenaSYS#8819]
in Issue #7902 one of the problems are that each diagram save takes up to much storage space a comment in that very big issue (now split in to several smaller) is: 

> This should not make use of several megabytes.
> 
> If we add an entity.
> How much should that take up? Lets say for arguments sake 200 bytes.
> Then we can have 5000 entities or 5000 state changes on one entity per megabyte.
> 
> Also we do not want to store every single miniscule update of the diagram... If an entity is moved around a lot, and we place it in 10 different positions before adding the next entity. Perhaps some of those places can be ignored. Perhaps we only store changes every x seconds or only when new items are added.
> 
> Also the information is VERY un-compact.
> 
> We store true/false when we could store 1 or 0 ... making the data 5 times larger for no benefit compared to the space it occupies.
> 
> We can call "symbolkind" "sk" reducing the number of bytes of that property by a fifth.
> 
> We also had discussions last year about omitting "empty" data from the textual version.
> 
> Since neither operations:[] or attributes:[] contain anything I would ommit that data completely, reducing that information from nearly 30 bytes to 0 for storing that (lack of) information.

one more thing to do to lower the amount of storage needed are to not save the diagram all the time but instead every 10 or 20 secounds or every time an new object are added or removed (what ever you thinks will work best). How do you handle ideal time say if a student goes to sleep not closing the diagram tab. 

**Important are to not remove the feature of multiple saves because then the key feature  of replaying the work process of how the diagram was built.**

**Comment by a18antsv** [comment]
Saves should only happen when something actually changes. But this is not enough since local Storage gets full very quickly when the whole diagram, everything, is saved every time. I think we need a solution where only the changes are saved. This would lower the used storage drastically.

**Comment by a18antsv** [comment]
Have a current state. Then different changes should be saved in local storage. A change can be adding an object, deleting an object or changing properties to an object. Maybe all objects can be stored once and brought back by their ID. Then changes can be made for the object ID. This could make it possible to still redo and undo by storing previous value before change and value after change. This would after a change save one property, for example "fillColor": #ffffff; instead of saving the whole diagram. This could reduce the storage by thousands of percent.

**Comment by a18antsv** [comment]
Then we would also need to shorten the property names stored in local storage. We do not want to change all variables in the code. But instead we could create a map, mapping actual variable names to a short string that the stringified json object can be compressed with. When pushing changes to localStorage, a function should be used compressing the string first. When getting from local storage later a function needs to decompress and replace all values to the actual property names being used.

**Comment by a18antsv** [comment]
A symbol also includes a whole lot of properties that are not relevant for the object. It would be good if the not relevant properties would not be included in an object in localStorage. This could be solved by either only putting the right properties into a symbol when the symbol is created depending on the symbolkind or by deleting properties that are not relevant only before pushing to local storage.
