### ISSUE TITLE
One diagram in localstorage at a time.

### ISSUE THREAD

**Issue by b18phibe** [HGustavs/LenaSYS#8823]
As the title says we only want one diagram state.(one save of the diagram) in localstorage at a time then when the new save are taken the old one are to be written to a file in the database. The same file as all other diagram states from this diagram. So in the end this diagram you are working on only has one file in storage making it easyer to late make an animation of the diagram and to download the full progress of the diagram. An idea can be to have a single zip file storing the diagram.
 
We don't want the local storage to look like this.
![image](https://user-images.githubusercontent.com/62876531/81044556-dfe7f680-8eb4-11ea-94da-094bc12f93e6.png)

may not be worth doing before #8819 are done.

**Comment by b18phibe** [comment]
This might brake the undo and redo buttons (ctrl + z / ctrl +y), please check so this functionality still works after this issue has been solved.

**Comment by a18andtu** [comment]
Right now the undo and redo functionality loads diagrams from the local storage based on diagram number. If the intention is to only have one diagram in local storage at one time this has to be reworked before going through with the changes for this issue,

**Comment by a18antsv** [comment]
I think it would be fine to store everything in local storage. We just need a solution where only the changes are saved. Then we can build the diagram by these changes. And it would be possible to undo and redo, going back and forth between the changes. This information could all be stored as one string in local storage. I would say this is necessary if we want to write all information to a file and be able to replay what was done in that diagram project. Right now, only the last seen diagram is saved in files which will make it impossible to implement this animation feature. I am thinking to try to work on this only changes saving for issue #8819. I already solved #9231 which compresses the property keys to a 2 character string. This compression could however be of no big use if I can manage to save only changes.
