### ISSUE TITLE
It is possible to have different marks in dugga and in corresponding "kursmoment"

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#883]
Right now the dugga system suffers from a disparity in how marks are handled between duga and in "delkurs". It is now possible to have "U/G" in a dugga and "U/G/VG" in the corresponding "moment".

The user interface needs to be connected better in some way.

Dugga-entries are rarely changed and need to be safeguarded against accidental deletions (since it must be REALLY REALLY IMPOSSIBLE to (accidentally or on purpose) delete the results of a student after-the-fact).

I liked parts of the suggestion of moving the "dugga" into the "course editor"... but did not like what it did to the user interface.

My suggestion is to go in the opposite direction, to have more access the course information in the "dugga" view.

This way the course interface is still un-cluttered, but the more rarely used dugga interface, allows us to both manage the dugga and connect it to the course elements.

This way the marking can be kept consistent.

**Comment by HGustavs** [comment]
Still not super-keen on having a columed-layout.... but if we can move the second column below or above the first column on higher-than-wide displays, I can live with a two-column layout. As I can see the merits of seeing relevant parts of the course content in the dugga-editor.

**Comment by k14marst** [comment]
Set default grading system on new dugga to same as the moment has. Deletion of results was already resolved. The rest of the issues will be resolved in #2136

**Comment by HGustavs** [comment]
Not necessarily. I think.
