### ISSUE TITLE
Dropdowns in Access Editor opens on hover

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8830]
This can only be seen/tested after https://github.com/HGustavs/LenaSYS/pull/8737 on G2-2020-W19 (group 2's groupbranch). After the W19 weekly branch this should also be seen on the master branch (unless it gets fixed before the merge).

Currently all the dropdowns except the Group dropdown will open on hover. This feels very unintuitive and it's also quite annoying when a bunch of dropdowns open when you're moving the cursor across the screen.

I suggest this be changed to open on click. Clicking a dropdown should open it. Clicking outside of the dropdown, clicking the dropdown again or selecting a value in the dropdown should close the dropdown. If the "new" click is on another dropdown while a first is open, the first should be closed and the new dropdown should be opened.

**Comment by b18jonli** [comment]
Closing since this has been merged.
