### ISSUE TITLE
Change let to var [Group 1: Markdown]

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8832]
According to the `code_standard.md` document, `let` should not be used for variable declarations for browser compatability reasons. Instead `var` should always be used instead.

For group 1 this concerns the following file:
- `markdown.js`

**Comment by a18filkr** [comment]
The customer has been asked if the code standard should stay like this. We might want to hold out for an answer, code standard today should be using let and const instead of var.

**Comment by b18alegu** [comment]
This issue is no longer relevant and will now be closed.

`code_standard.md` will be updated in #9147 to clarify the future uses of variable declarations.
