### ISSUE TITLE
New course version dialog - copy from version

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#885]
I believe that there is no working dialog for creating a new version of a course.

This is a pretty complicated task as it is necessary to copy some contents from the old version to the new version including but not limited to the course layout and any references in that course layout to things such as code examples (which also need to be duplicated).

I think this is a superficially simple issue but I do believe that it is an infinitely deep rabbit-hole.

**Comment by a13oscwe** [comment]
To get this done will be a tight squeeze, putting this as low priority and we'll see next week if somebody has the time/knowledge to get this done.

**Comment by b14kriwe** [comment]
This issue is more or less partially the same as issue #1847 which is though to be resolved. We can consider this issue closed as creating new versions do work, the copy version is waiting for a merge.
