### ISSUE TITLE
Codeviewer: iFrames when watching previews have a weird size

### ISSUE THREAD

**Issue by a18geoge** [HGustavs/LenaSYS#8854]
Refering to issue #7782, when previewing a document the iFrame is sized so that it doesn't completely fill the examplebox. See:

![template10iframewrongbutnotscrollbar](https://user-images.githubusercontent.com/62876595/81076626-24db4f80-8eec-11ea-9f37-9afcf8378d03.jpg)

**Comment by a18filkr** [comment]
Decided to close this as we didn't know if this would solve the issue or if it's even an issue at all.
