### ISSUE TITLE
Create new version of a course feature does not work

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#8866]
I don't know if there is already an issue created for that but anyway 'create new version of a course' feature doesn't seem to work on the local environment.

![Anteckning 2020-05-06 080206](https://user-images.githubusercontent.com/49142349/81142455-04ed6f80-8f70-11ea-8cff-2d0682d4ef37.png)

**Comment by a18jenro** [comment]
This was dealt with in other issues.
