### ISSUE TITLE
The description tag doesn't become visible after the reset button.

### ISSUE THREAD

**Issue by a18abuah** [HGustavs/LenaSYS#8879]
When clicking the reset button after resizing the boxes in codeviewer the description tag sometimes doesn't come back.
[![Image from Gyazo](https://i.gyazo.com/8fc790063f586ac8bbfb5c9bd0979388.gif)](https://gyazo.com/8fc790063f586ac8bbfb5c9bd0979388)

**Comment by a18geoge** [comment]
I was not able to recreate the issue. Is this still a bug?

**Comment by a18abuah** [comment]
The bug takes alot of tries to recreate.

**Comment by a18gusjo** [comment]
The bug seems to be fixed if the code below in the function resetBoxes() is moved outside the if-statements: 
" thisBox = document.querySelector('#box' + 1 + 'wrapper #boxtitlewrapper');
		thisBox.classList.remove('hidden');
		thisBox.classList.remove('visuallyhidden'); "

**Comment by a20sarle** [comment]
Couldn't be replicated on server during testing, seemed to solved already. See branch #11390 for solution suggestion. Closing issue.
