### ISSUE TITLE
Diagram Layer - Fix Drop-down Menu

### ISSUE THREAD

**Issue by a18petha** [HGustavs/LenaSYS#8884]
Diagram layers drop-down menu currently do no refresh the diagram when there active, this needs to be fix. Adding some onmousedown styling should also be done, unclear then you press a layer if it's being selected

This Issue is follow-up on issue
#3750 

Related issues:
#8887 
#8890 
#8885 
#8884
#8891

**Comment by b18phibe** [comment]
working now, closing
