### ISSUE TITLE
Diagram Layer - Smoothing out write to layer drop-down menu

### ISSUE THREAD

**Issue by a18petha** [HGustavs/LenaSYS#8887]
There currently some issues with the write to drop-down menu. we can't change layers without deselecting a active layer.

deselecting a layer should not be a option as this would pose a potential error state within the diagram. intended solution should be that one layer is always active and changing between them should just be clicking on another layer

This Issue is follow-up on issue
#3750

Related issues:
#8887 
#8890 
#8885 
#8884
#8891

**Comment by b18phibe** [comment]
Merged
