### ISSUE TITLE
Improve error handling in codeviewer.js

### ISSUE THREAD

**Issue by a13erisc** [HGustavs/LenaSYS#890]
Right now we are greeted with the "If no content appears here... update your browser, enable javascript and try again." in case we break the code. Perhaps it would be desirable to have improved error handling, for testing and bugfixing purposes.

**Comment by a13jorla** [comment]
How is it with this issue @c12jenek ?

**Comment by c12jenek** [comment]
Right now the error message is "If this text remains this means there is an uncaught error. Please contact the administrators". Error handling has been improved with for example console.logs() so if this feels like it's enough or correct this issue is resolved

**Comment by HGustavs** [comment]
I say we can probably retire this issue.

**Comment by a13jorla** [comment]
Thanks for the comments. So for now i'm closing this issue.
