### ISSUE TITLE
Bug where the last exported date says undefined when copying it to the clipboard.

### ISSUE THREAD

**Issue by b18fella** [HGustavs/LenaSYS#8905]
When clicking on the copy to the clipboard copy button as shown below.
![copyClipboard](https://user-images.githubusercontent.com/49142651/81152969-bf866d80-8f82-11ea-8c20-479f890ff21c.png)

This undefined text comes up.
![copyClipboardUndefined](https://user-images.githubusercontent.com/49142651/81152974-c0b79a80-8f82-11ea-976b-9d6f424f8ae9.PNG)

Co-authored-by: a18eripi <a18eripi@users.noreply.github.com>

**Comment by a18viksa** [comment]
Closing issue after merge to master.
