### ISSUE TITLE
Sorting in Dugga Editor sorts uppercase and lowercase characters separately 

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8908]
When sorting in the Dugga Editor, for example "A" and "a" are sorted differently. Currently uppercase characters are sorted first, so for example "Gruppdugga" will come before "colordugga", see screenshot.

This will probably be solved by transforming everything into uppercase/lowercase before the sorting is applied.

![image](https://user-images.githubusercontent.com/49141758/81176287-3fbdca80-8fa5-11ea-8715-8533523ede57.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
