### ISSUE TITLE
AccessEd - It is not possible to select "None" or similar in the dropdown menus

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8909]
This was possible previously and probably should be again. Also, the various "null"/empty/"None" values should be handled (and look) the same in the table. 

Now:
<img width="220" alt="Screenshot 2020-05-06 at 2 26 48 PM" src="https://user-images.githubusercontent.com/62876553/81176632-b1961400-8fa5-11ea-9fa3-10a724765706.png">

Previously:
<img width="171" alt="Screenshot 2020-05-06 at 2 27 04 PM" src="https://user-images.githubusercontent.com/62876553/81176643-b8248b80-8fa5-11ea-86d2-1cea5c252d2c.png">

**Comment by a18viksa** [comment]
Closing issue after merge to master.
