### ISSUE TITLE
Table in Dugga Editor does not display full date for Startdate

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8919]
The Startdate date is cut off and there is no cut off for seconds in the Last Modified column. Second precision is not needed so the cut off should be applied to all dates using seconds for consistency. See screenshot.

![image](https://user-images.githubusercontent.com/49141758/81178548-a85a7680-8fa8-11ea-82d5-ee27dd4e0d0a.png)

**Comment by c14jonfr** [comment]
I believe renderCell function is missing a switch case around line 705 (for last modified). 

The incorrect cut off on Startdate can probably be solved with an if-statement that checks that celldata.length > 10 (or something similar) so that the cutoff is not applied to dates only consisting of YYYY-MM-DD.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
