### ISSUE TITLE
Announcementbox only opens in sectioneed

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#8920]
Make sure that the announcementbox opens in rest of the pages when logged in a course.
This occurs because of announcementbox only exist in sectioneed so I'd have move the code from sectioneed to a seperate file and then include it in rest of the pages.

![Anteckning 2020-05-06 145129](https://user-images.githubusercontent.com/49142349/81178880-2880dc00-8fa9-11ea-91f0-9c103b44e030.png)

This issue is related to #8700
Fetch the branch G3-2020#8700 to see the changes because this issue is not merged into the weekly or master branch.

**Comment by a18mahkh** [comment]
I was wondering if it's a good idea to able to create an new announcement from every pages?
Or just leave it the way it's now and hide announcement button while browsing between different pages except sectioneed. 

@HGustavs  @a97marbr

**Comment by a97marbr** [comment]
Isn't the create announcement something that could be part of the menu in the purple nav list? What would be the benefit/drawback of putting the button there?

**Comment by a18mahkh** [comment]
We wanted to use the same button that slides down the announcement box for both students and admins but only admins gets access to the 'create announcement' button

Otherwise admins going to need two buttons, one for creating announcement and one for to see the recent announcements.

By this solution we don't have to implement an extra button.

@a97marbr  @HGustavs

**Comment by a97marbr** [comment]
ah ok
