### ISSUE TITLE
Issue with addElement button

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#8921]
Makes sure that the addElement button stays in course header.

![Anteckning 2020-05-06 145130](https://user-images.githubusercontent.com/49142349/81179745-5ca8cc80-8faa-11ea-90df-164a36bb7c55.png)

The button is not a part of announcementbox

**Comment by a18lukto** [comment]
Reopen this issue and fixed the problem with the top fab button not follow the course header
