### ISSUE TITLE
Canvas in Transformationduggas does not scale properly in Firefox on smaller screens

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8922]
See first screenshot. The canvas is the small black square below the instructions accordion.

![image](https://user-images.githubusercontent.com/49141758/81179170-94634480-8fa9-11ea-9726-131409819349.png)

According to the Dev Tools, the size is considerably bigger, but the "true" size of the element is really really small, see the following screenshots.

![image](https://user-images.githubusercontent.com/49141758/81179131-86adbf00-8fa9-11ea-9001-4fcf554de66a.png)

![image](https://user-images.githubusercontent.com/49141758/81179803-72b68d00-8faa-11ea-906d-dc123c30ad52.png)

**Comment by c14jonfr** [comment]
Adding a min-width and min-height to the canvas seems to solve this, on Firefox.. but this creates a new issue on Chrome where the canvas will have a skewed aspect ratio for certain screen size.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
