### ISSUE TITLE
Should not be possible to grade something that is not submitted.

### ISSUE THREAD

**Issue by a18eripi** [HGustavs/LenaSYS#8928]
It is possible to grade an unsubmitted task, which should not be allowed.

![unsubmitted graded](https://user-images.githubusercontent.com/43380274/81189073-6d5f3f80-8fb6-11ea-9fee-1957003fea68.png)

Co-authored-by: b18fella <b18fella@users.noreply.github.com>

**Comment by b18fella** [comment]
This issue is closed because it appeared that it wasn't an issue, to begin with.
