### ISSUE TITLE
Access editor: Check that ssn is in correct format

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#8935]
When adding a new user in the access editor there should be warning if the ssn (personal identity number) does not comply with any of the following criteria:
- Wrong format (should be ########-#### or ######-####)
- Date should be correct (i.e. not 34th of May)
- Date should not be in the future
- The control digit should be be correct according to this [Statistiska Centralbyrån document at page 8](https://www.scb.se/contentassets/8d9d985ca9c84c6e8d879cc89a8ae479/ov9999_2016a01_br_be96br1601.pdf).

The plan is to put a warning triangle next to the the "SSN:"-label when adding a user that will only be shown when anything i wrong with the input and be invisible otherwise. A regular popup text that shows the message while the mouse pointer in on top of the triangle should be sufficient.

Something like this mockup:
<img width="541" alt="Skärmavbild 2020-05-07 kl  06 52 14" src="https://user-images.githubusercontent.com/62876260/81256304-607f3200-9030-11ea-83e1-bbb909894fba.png">

**Comment by b18alegu** [comment]
Any potential warning messages for the SSN will be shown between "email" and the add button instead. @c14jonfr had a great suggestion to implement the error message in the same way as in the dugga editor so that should be implemented in the future. an issue will be made shortly.

**Dugga editor warning**
<img width="478" alt="Skärmavbild 2020-05-13 kl  11 05 12" src="https://user-images.githubusercontent.com/62876260/81793524-c6285e00-9509-11ea-8643-6df78bb95b49.png">

**Comment by a18viksa** [comment]
Closing issue after merge to master.
