### ISSUE TITLE
AccessEd - When setting user to "teacher" a reload is required to choose that user as "examiner"

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8936]
The examiner dropdown menu options should update without requiring a reload.

**Comment by b18jonli** [comment]
@a97marbr @HGustavs 
Currently, the "examiners" that show up as options are all users with teacher-access for _any course_, meaning a teacher from a completely unrelated course can be set as "examiner". 

Is this correct or should it be limited to the teachers for the current course?

**Comment by a18viksa** [comment]
Closing issue after merge to master.
