### ISSUE TITLE
 Remove unnecessary logging 

### ISSUE THREAD

**Issue by b17carbr** [HGustavs/LenaSYS#8940]
logMousemoveEvent and logClickEvent log x and y position of the mouse as seen below. This serves no purpose with the current implementation of analytic. These functions along with their tables should be removed to unclutter logging. 

![Screenshot 2020-05-07 at 09 40 16](https://user-images.githubusercontent.com/62876614/81267470-d4c4d000-9046-11ea-87d1-0f58d54fd838.png)
![Screenshot 2020-05-07 at 09 40 10](https://user-images.githubusercontent.com/62876614/81267476-d8585700-9046-11ea-9356-1e7781819d74.png)

**Comment by d17marle** [comment]
Really good issue!
