### ISSUE TITLE
AccessEd - Sorting by examiner is broken

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#8942]
Trying to sort by examiner doesn't work and gives this error:
<img width="776" alt="Screenshot 2020-05-07 at 9 49 14 AM" src="https://user-images.githubusercontent.com/62876553/81268258-04c0a300-9048-11ea-9fff-8f803ae60cd3.png">

**Comment by a18viksa** [comment]
Closing issue after merge to master.
