### ISSUE TITLE
Save/Reset buttons not positioned correctly in Transformationsduggas on small screens

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8946]
For all the other duggas (at least from what I have been able to gather), the Save and Reset buttons are positioned at the end of the page. This is not true for the Transformationsduggas for some reason. See screenshot.

![image](https://user-images.githubusercontent.com/49141758/81269388-85cc6a00-9049-11ea-9d03-97c2bde5f4b3.png)

**Comment by c14jonfr** [comment]
Looks like this is because the fitToContainer function in dugga4.js sets the height of the duggacontainer (#dugga4Container). This function is called constantly.

Commenting out (or removing) the line which sets the height of the duggacontainer fixes this issue.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
