### ISSUE TITLE
Primary and Partial key lines not dependant on text size or zoom value

### ISSUE THREAD

**Issue by g18marma** [HGustavs/LenaSYS#8971]
The primary and partial key line position are not changed when changing font size or when zooming the canvas. The result of this is displayed in the GIFs below.

![d269d1ca712775fd0439ca91b54dd3b6](https://user-images.githubusercontent.com/49142301/81293106-0baddc80-906d-11ea-9362-b891e848cfc0.gif)

![54316edf344ef65a9f80798f85d510d6](https://user-images.githubusercontent.com/49142301/81293196-3435d680-906d-11ea-89e5-df8d408a9ab2.gif)

**Comment by b18phibe** [comment]
merged closing
