### ISSUE TITLE
Bug when draggin line from ER-attribute to a ER-entity or relationship and attempting copy

### ISSUE THREAD

**Issue by o18marka** [HGustavs/LenaSYS#8983]
When creating a line where the start object is a ER-attribute and the en object is a ER-entity or relationship then attempting to copy-paste this, the diagrams contents disappear and a error occurs in the console. "Cannot set property 'y' of undefined".
![issue7](https://user-images.githubusercontent.com/49142263/81318948-488acb00-908f-11ea-810c-575fecf8445e.gif)

Note: Creating a line from ER-entities or relationships TO a ER-attribute does not cause this bug.

**Comment by o18marka** [comment]
Found that the problem lies within the special case for copying ER-attributes in the copySymbol function.

**Comment by a18antsv** [comment]
True. When I developed the special case I thought the line's bottomRight in this case was always the point for the attribute center point. This is not the case. It depends on which way the line is drawn from.  It could also be the topLeft property being a reference to the attribute's center point.
