### ISSUE TITLE
Change Names input to a placeholder. 

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#8993]
Creating a new edit dugga in Duggaed should change Name input to a placeholder with New Dugga text in. 
<img width="474" alt="Screenshot 2020-05-08 at 09 30 38" src="https://user-images.githubusercontent.com/49142649/81382515-ce019000-910e-11ea-841c-d37f76dece89.png">

**Comment by a18viksa** [comment]
Closing issue after merge to master.
