### ISSUE TITLE
Students should only be able to be part of one group per course

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#8994]
Currently it's possible for a student to be a part of several groups (even all of them) at once. I have discussed this with other developers (who are also students) and we cannot think of any situation where a student would have to be part of several groups at once. This is also supported by the fact that in the database the groups are handled on course-level, not assignment-level. 

We suggest replacing the checkboxes with radio buttons where only one radio button can be selected at once. This will require a rework of the updateAndCloseGroupDropdown function in accessed.js (and possibly more).

**Comment by c14jonfr** [comment]
Good news! It seems we won't even have to rework anything. So far it seems to handle switching from checkboxes to radio buttons seamlessly. We could (and maybe should) change "checkboxes" to "radiobuttons" in most if not all places for semantic reasons but functionality wise a simple switch to radio buttons works.

**Comment by b18jonli** [comment]
It would also be possible now to make the group dropdown use the same dropdown menu system as the rest of the table, since it is now single-choice like the others.

**Comment by c14jonfr** [comment]
@b18jonli Hm, that's true. I guess we could discard our solution and remake it to use the same system as the other dropdowns. Or we could let our solution pass through (as long as it passes reviews, of course) and remake it at a later stage. Consider this a quick fix so people cannot assign a student to more than one group, maybe?

Any thoughts on what action to take?

**Comment by b18jonli** [comment]
I’m not sure, there are many groups compared to say examiners which would cause the group dropdown menu to be quite large, if it looks the same as the others. 

Also, this solution is done and works (reviews permitting), so I don’t know if it is worth the effort to change it simply for code readability.

**Comment by c14jonfr** [comment]
I agree. I think it's still fair to open an issue about it, and consider it low priority. Whoever has some time over can look into it and try it out to see how it would work. Maybe limiting the size of the dropdown and let it scroll on overflow would work?

**Comment by a18viksa** [comment]
Closing issue after merge to master.
