### ISSUE TITLE
Code Viewer: code example 2 doesn't work in google chrome.  

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#901]
It kinda works in firefox but it doesn't work at all in google chrome. All the others exemple works.

**Comment by a12jiyba** [comment]
Example 2 seems to work in chrome.

**Comment by c13caral** [comment]
This issue is now solved. It happened when attempting to solve another issue. But now it is fixed and all examples works as it should. So I will shut down this issue
