### ISSUE TITLE
It should only be possible to export grades that has not been exported yet.

### ISSUE THREAD

**Issue by b18fella** [HGustavs/LenaSYS#9014]
This issue is a little followup from #8962 where an error would pop up in the console. This issue will fix that error and it will also make the exported work better.

Co-authored-by: a18eripi <a18eripi@users.noreply.github.com>

**Comment by b18fella** [comment]
@HGustavs When you export grades, should it export all the grades or just the new grades? And when it comes to gradeLastExported in the database, should it only update those whose grades were exported there and then, or should it update all of them?

Feel free to ask if I'm not clear enough.

**Comment by HGustavs** [comment]
Well, it is better to export only new grades.

But an option to export all would perhaps be a good idea if some grade is inadvertently missed.

**Comment by b18fella** [comment]
@HGustavs Does an export count as an export when you click on the lad export button or does it count as an export when you click on copy to the clipboard?

**Comment by a18viksa** [comment]
Closing issue after merge to master.
