### ISSUE TITLE
database optimization - clear data in table "eventlog"

### ISSUE THREAD

**Issue by a13chrju** [HGustavs/LenaSYS#903]
When the login attempts are counted and implemented correctly into the system a hugh number of data will be stored in this table whenever a user makes an unsuccessful login.

to make the system go faster it would be nice if the database performed a weekly(or something like that) table reset of table "eventlog".

**Comment by a13karsi** [comment]
I'll take a look at it and see what's possible!

**Comment by a13chrju** [comment]
nice job, I'll use your code my my own website too! hehe :+1:
