### ISSUE TITLE
MOTD banner error in courseed.php

### ISSUE THREAD

**Issue by a17towan** [HGustavs/LenaSYS#9050]
This error occurs whenever you close the MOTD banner on the **courseed.php page** (the purple button that says "close"). Please investigate and fix this.

![image](https://user-images.githubusercontent.com/49142028/81412071-95c87480-9143-11ea-8132-b2b38b7c316e.png)

**Comment by a18jenro** [comment]
Seems to not be an issue anymore. Feel free to reopen if this is not the case.
