### ISSUE TITLE
Rulers should adapt to camera position

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#9060]
The values on the rulers should adapt to the camera position. The origo offset can probably be used for this. This is a sub issue for #5943.

This picture shows the rulers. In this case 0 should be at the blue lines and before the lines the values should be minus.
![image](https://user-images.githubusercontent.com/49121839/81485148-36ee2280-924b-11ea-8cb9-6903e1039afd.png)

**Comment by HGustavs** [comment]
Yes both the magnitude and position of the rulers need to match the offset and zoom of the view.
