### ISSUE TITLE
Rulers should adapt to zoom value

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#9061]
The values on the rulers should adapt to current zoom value. This is a sub issue for #5943.
![image](https://user-images.githubusercontent.com/49121839/81485205-a8c66c00-924b-11ea-91be-194c4957acde.png)

**Comment by HGustavs** [comment]
Values and size of numbers should remain the same but the spacing betwen numbers should adapt with zoom.

**Comment by a18antsv** [comment]
As a start the values are changing to be correct depending on zoom value. This is not the intended functionality though as the spacing should be what is changed. How should we do when a very small step is 500 pixels though, as in 0,1 zoom value? Then new values might be needed?
![9c7191d7f65e4b368c156c4f9892e25e](https://user-images.githubusercontent.com/49121839/81611769-f245c100-93db-11ea-889b-389aa48acf1a.gif)

**Comment by a18antsv** [comment]
I am thinking to increase the step from 50 to 100 on around 0,7 and below zoomValue. Then to 200 per step for zoomValue 0,4 and below. Then to 400 per step for 0,2 and below. This would make it always work to see the values without cramped lines and text.

**Comment by a18antsv** [comment]
For zooming in, the values can be kept at 50 without any problems if the spacing is increased like in this gif. It could possibly be intresting to lower the steps little when zooming in?
![9d9b2acc2e1756566ab72cc859501dc0](https://user-images.githubusercontent.com/49121839/81623361-99822280-93f3-11ea-91d5-b72bb8340dd7.gif)

**Comment by HGustavs** [comment]
I agree with removing some numbers when zooming out very far.

But when zooming in I do not want additional numbers to be inserted.
