### ISSUE TITLE
Rulers should show mouse position

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#9062]
There should be a line on both the x-axis and y-axis ruler showing the current mouse position. Sub issue for #5943.

**Comment by HGustavs** [comment]
Good idea.

Make the line below the numbering of the ruler so that id can not easily obscure the reading.

**Comment by a18antsv** [comment]
Created lines looking like this. Little thicker so they are visible and also do not reach the text. It could possible reach the text for the y-axis ruler if the number go above 9999 though but this should not be a big problem.
![f108dab19d49af2abec4686494500b98](https://user-images.githubusercontent.com/49121839/81693098-b48a7c00-945f-11ea-8ce6-189e237ce537.gif)
