### ISSUE TITLE
Dropdowns in Access Editor are a bit clunky and inconsistent in styling

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9070]
The width of the dropdown in the Access Editor varies quite a lot. For some it covers more or less the whole width of the column/cell while others leave a lot of space.

Screenshot 1 shows the Class dropdown with covers more or less the whole width of the column/cell.

![image](https://user-images.githubusercontent.com/49141758/81532321-79efe900-9364-11ea-9869-1b4364ebc056.png)

Maybe they should all be changed to behave similar to the group dropdown? See screenshot 2. The dropdown starts at the end of the cell (so it doesn't cover the cell at all) and spans the whole width of the column/cell.

![image](https://user-images.githubusercontent.com/49141758/81532879-7315a600-9365-11ea-9abc-3ae92f16996f.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
