### ISSUE TITLE
Duggaed: bug in validation.

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#9104]
If you want to add a new dugga to duggaed and start typing in a name that is denied by the validation. And you choose to close the popup (not save)._See img 1._ It remembers that the validation was denied which creates a problem. Because when you click Edit Dugga on one that already exists, it will deny the name of it. Although it does not contain incorrect characters. _See img 2._ Then, for example, you need to insert a space and then remove it for it to be allowed again.
<img width="474" alt="Screenshot 2020-05-11 at 12 15 50" src="https://user-images.githubusercontent.com/49142649/81550961-4bccd200-9381-11ea-9c4e-6d5934ad5d76.png">
_img 1 - Add a new dugga._
<img width="474" alt="Screenshot 2020-05-11 at 12 15 57" src="https://user-images.githubusercontent.com/49142649/81550962-4cfdff00-9381-11ea-87d1-da0104a51a55.png">
_img 2 - Edit existing dugga._
It would have been good if it could be fixed.

**Comment by c14jonfr** [comment]
One way to solve this is to run the validateDuggaName()-function at the end of selectDugga (around line 112 in duggaed.js). This will run the validationfunction as soon as a dugga is selected (in addition to being run onchange as before).

**Comment by a18viksa** [comment]
Closing issue after merge to master.
