### ISSUE TITLE
When editing a dugga in Dugga Editor containing characters åäö in name, these are not handled properly

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9113]
See screenshot. The name of the dugga being edited is "ööö".

![image](https://user-images.githubusercontent.com/49141758/81558789-9acd3400-938e-11ea-8e70-780b0f2d1124.png)

If this dugga is saved (without changing the name), the name will be saved as `"&ouml;&ouml;&ouml;"`.

![image](https://user-images.githubusercontent.com/49141758/81558919-cf40f000-938e-11ea-8935-082f941c7ed7.png)

Additionally, if `"&ouml;&ouml;&ouml;"` is edited again, name in the textbox will be changed to `"&amp;ouml;&amp;ouml;&amp;ouml;"` (this goes on and on if you keep editing and saving the dugga).

One solution to this is replacing the `"&ouml;`" with "ö" using the replace() function (the same goes for Ö, å, Å etc) but maybe there is a different, better solution.

**Comment by c14jonfr** [comment]
After looking into this a bit it seems that decoding the qname-value using html_entity_decode() before the array is returned from duggaedservice.php is the most clean way to solve this.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
