### ISSUE TITLE
User Information: Add page loads

### ISSUE THREAD

**Issue by b17carbr** [HGustavs/LenaSYS#9114]
There should be information regarding the number of times a users has loaded a page. This could for example be added to each page selection. 

![Screenshot 2020-05-18 at 11 41 01](https://user-images.githubusercontent.com/62876614/82198362-7d531980-98fc-11ea-9842-b84d64ccd293.png)

**Comment by a18eliek** [comment]
Do we just want a counter on the page? So based on the screenshot a number 5 displayed somewere?

**Comment by b17carbr** [comment]
@a18eliek yes a counter would great. Displayed above the existing table would probably be good.
