### ISSUE TITLE
tooltipDugga/tooltipTxt in Dugga Editor is badly positioned

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9115]
When typing characters that are not allowed in the Name textfield, a tooltip is shown. This tooltip covers big parts of the textfield. See screenshot 1. This should probably be moved to the left of the text field. One suggesting is something like screenshot 2.

Screenshot 1.
![image](https://user-images.githubusercontent.com/49141758/81559949-afaac700-9390-11ea-9873-baebbeb87552.png)

Screenshot 2.
![image](https://user-images.githubusercontent.com/49141758/81560204-36f83a80-9391-11ea-9689-e297135e0766.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
