### ISSUE TITLE
File Information: Show all files

### ISSUE THREAD

**Issue by b17carbr** [HGustavs/LenaSYS#9119]
Currently only files in loglena4 is accounted for in the dropdown, this should be expanded to all files. This will require retrieving all users from sql db instead.

![Screenshot 2020-05-11 at 14 21 07](https://user-images.githubusercontent.com/62876614/81561018-cc47fe80-9392-11ea-84c5-a75ad255bcd6.png)

**Comment by a18filkr** [comment]
The files should show without having a log for the file in loglena4.db. This is a requirement atm.
