### ISSUE TITLE
Navheader search bar causes an error in AccessEd/ResultEd

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#9124]
The search bar in calls a function `sortAndFilterTogether()` which only exists in fileEd, thus it causes an error (see below) in accessEd and resultEd where there is no such function.
![](https://media.discordapp.net/attachments/690517046382821456/709384332669747270/Screenshot_2020-05-11_at_2.39.48_PM.png)

Since nothing is broken I think the easiest solution is simply to check if the function exists before calling it, by using something like:
`if (typeof sortAndFilterTogether === "function") { sortAndFilterTogether(); }`

**Comment by a18jenro** [comment]
This should already be fixed in group 3. We can open this issue again if it remains after the next weekly merge.
