### ISSUE TITLE
Suggestion: Add visual indicator for selected value in Access Editor dropdowns

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9135]
Currently there is no indicator for which value is/was selected when a dropdown is opened. See screenshot. It would be nice to have some sort of indicator in my opinion. Maybe just a different background color or some small icon to the right?

Note that https://github.com/HGustavs/LenaSYS/pull/9076 changes/fixes the positioning of the dropdowns so that the selected value is visible since the dropdown no longer covers the table cell (this has not been merged yet so the screenshot below is from the "old"/current version).

Since the selected value will be more visible after mentioned pull request has been merged I don't consider this high priority at all. But it would be a nice QOL change.

![image](https://user-images.githubusercontent.com/49141758/81649910-58106800-9431-11ea-8d45-0539d31a6ad1.png)

**Comment by HGustavs** [comment]
Good idea.

Subtle though. How about using the contrast color?

**Comment by a18viksa** [comment]
Closing issue after merge to master.
