### ISSUE TITLE
Can't search for å,ä or ö in Accessed.

### ISSUE THREAD

**Issue by a18sebka** [HGustavs/LenaSYS#9146]
Searching in accessed should probably work as in resulted.

**Comment by HGustavs** [comment]
Is this something that can be ported to sortabletable to make this effect global?

**Comment by a18sebka** [comment]
I will look into it.

**Comment by a18sebka** [comment]
Due to some other changes somewhere else, the previous code now works except ä.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
