### ISSUE TITLE
Update code_standard.md document

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#9147]
Input has been given regarding the use of variable declarations in LenaSYS from now on. `code_standard.md` will be updated according to the preferences of @HGustavs.

> So my suggestion is to allow const (even changing var declarations to const as we are documenting the code further, and at the same time avoiding errors) but to keep using var for all other cases, in the interest of consistency.
@HGustavs in https://github.com/HGustavs/LenaSYS/issues/8831

**Comment by a18viksa** [comment]
Closing issue after merge to master.
