### ISSUE TITLE
Rework how undo/redo works with the local storage 

### ISSUE THREAD

**Issue by a18andtu** [HGustavs/LenaSYS#9158]
Right now the undo and redo functionality loads diagrams from the local storage based on diagram number. This is not compatible with the idea of having only one state at a time saved in local storage mentioned in issue #8823. A solution could be to save previous states in the current state.

**Comment by a18antsv** [comment]
I think my solution to only save changes could solve this issue as well in a good way. I am currently developing it and it looks promising.

**Comment by a18antsv** [comment]
This should be solved at the same time as I work for only saving changes in local storage and building the diagram from them.
