### ISSUE TITLE
Complete htmlEntities() 

### ISSUE THREAD

**Issue by a13alfbe** [HGustavs/LenaSYS#916]
In Shared/dugga.js there is a function called "htmlEntities(str)". This function translates strings to HTML entities to prevent errors when they are selected and outputted from the database. 

Add support for more common characters in this function.

Example characters: ^, ', ´

**Comment by HGustavs** [comment]
Is there not a character white-list function that was added some time ago?
Im thinking that anything that is not in the white-list should be encoded.
