### ISSUE TITLE
Redirecting to newly created course version only work when not copying content

### ISSUE THREAD

**Issue by a18jimol** [HGustavs/LenaSYS#9162]
While working on issue #8874 we solved that error but only managed to get the link to work when choosing "Copy content from None". When copying content from another course-version the page get stuck and nothing happens and after reloading the page the new version exist in the dropdown.

When creating a new course-version and copying content from another version you should get redirected to the new version.

**Comment by a18jenro** [comment]
Apparently this issue has already been fixed.
