### ISSUE TITLE
Tabs not working for items in sectioned except for tests

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#9172]
Tabs work currently for tests, but not other items in sectioned.
@a97marbr or @HGustavs 
Should we make a fix such that tabs work for all different items in sectioned or is this the intended behaviour?

**Comment by a18jenro** [comment]
@a97marbr or @HGustavs bump!

**Comment by a17towan** [comment]
Tabs work for 'Test' (duggas), 'Code', 'Message', 'Link', and 'Group activity' as of right now. This was added in separate issues.

**Comment by a18jenro** [comment]
Great!
