### ISSUE TITLE
Installer: loglena4 needs to reflect table creation in basic.php

### ISSUE THREAD

**Issue by b17carbr** [HGustavs/LenaSYS#9189]
Currently the table creation for loglena4 does not match the table creation in basic.php that will be merged into lenaSYS at this weekly merge, this needs to be corrected. 

How the installer table creation looks now: 

![Screenshot 2020-05-13 at 09 38 08](https://user-images.githubusercontent.com/62876614/81784822-b99e0880-94fd-11ea-9662-baf2df7b4c65.png)

This should instead look like this https://pastebin.com/BANEhUDa .

**Comment by a18eliek** [comment]
This should probably be removed, it's kinda bad to have two copies of the same code in two different places, alternatively we should get the table creation string directly from basic.

**Comment by a18eliek** [comment]
I would also like to point out that the installer should probably force a removal of the sqlite database, this is not currently done and having an non up-to-date version causes errors on the site.
