### ISSUE TITLE
Flash for text objects / Savestate issue with line tool

### ISSUE THREAD

**Issue by g18marma** [HGustavs/LenaSYS#9196]
Right now there's flashes when creating incorrect relations between all object except for text objects. Text objects should also show warning flashes to make it consistent with all other objects.

**Comment by g18marma** [comment]
Also noticed another issue while working with creating lines. When selecting different objects with the line tool the state is saved everytime an object is selected. This should not happen. The state of the canvas should only be saved when something changes in the diagram. 

Gif below of how the state is saved when selecting objects:

![ad6e27d437f97c36bd8d635502b0a909](https://user-images.githubusercontent.com/49142301/81795435-68494580-950c-11ea-9087-1a28af4d83cd.gif)

**Comment by b18phibe** [comment]
very nice solving this issue and reducing to amount of save states
