### ISSUE TITLE
Super tiny "pen" icon in fileed.php

### ISSUE THREAD

**Issue by a17towan** [HGustavs/LenaSYS#9198]
The "pen" icon for editing a file is superduper tiny.
![image](https://user-images.githubusercontent.com/49142028/81790489-c4f53200-9505-11ea-9fa1-34997f4cf561.png)

It needs to grow up.

(Make it larger)

**Comment by a17towan** [comment]
This issue might have been fixed by the latest weekly merge. Look into it.

**Comment by a18fayha** [comment]
The icon seems to be as big as the trashcan which is great! 
![image](https://user-images.githubusercontent.com/62876354/81927203-8b92f400-95e3-11ea-9208-021944c55869.png)
