### ISSUE TITLE
Hidden comments are still movable and clickable

### ISSUE THREAD

**Issue by g18marma** [HGustavs/LenaSYS#9208]
Hidden comments can still be clicked and moved. The objects are invisible but other than that they are just as accessible as any other visable object. This can cause the user to accidentally move the text object by mistake. The hidden comments should not be clickable or movable. 

![adb982d05477f0fbfd637e76ddbca20d](https://user-images.githubusercontent.com/49142301/81801527-dc87e700-9514-11ea-9d68-590412520e4d.gif)

**Comment by a18jonpe** [comment]
I have managed to ensure hidden comments can't be clicked or moved. However, the cursor still changes when hovering over a hidden comment which probably is not wanted behaviour. I am working on this now.
