### ISSUE TITLE
The url changes if you go to "view files"  from a course and then back again via the nav header back button.

### ISSUE THREAD

**Issue by a18jonsj** [HGustavs/LenaSYS#9212]
The url while youre at a course:
![image](https://user-images.githubusercontent.com/49142617/81806349-9d5d9400-951c-11ea-8488-2da9e0aff349.png)

Then you go to "view files" and the go back via the nav-header back button, the coursename has changed to UNK:
![image](https://user-images.githubusercontent.com/49142617/81806287-874fd380-951c-11ea-9dae-a1bc95f310c3.png)

**Comment by a18jonkl** [comment]
I found 2 solutions. The first one is to add 'coursename' in the URL when you click on “show files” or “edit student result” and when you then go back it remembers what the course name was.

The second solution is to remove the alternative `else $_SESSION[‘coursename’] = “UNK”` (row 22 in navheader.php) it then somehow remembers what the coursename is if it cannot be set to ‘UNK’.

Should I go with solution 1 or 2? 
@a18oscba @a18jenro

**Comment by a18jenro** [comment]
I honestly don't know which one is better. I would say, go with either one and test carefully before making a PR.

**Comment by a18oscba** [comment]
No clue either but choose what you think will work and like Jens said test carefully before making a PR.
