### ISSUE TITLE
Icons in fabbutton-buttons are displaced

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#9216]
Tragic:
![untitled](https://user-images.githubusercontent.com/62876507/81807671-cb43d800-951e-11ea-842b-f0ed14e4c62a.PNG)

**Comment by a17towan** [comment]
The icons seem to be more centered after the weekly merge. The lower fab-buttons (in the lower right) look okay but the ones at the top still look slightly off centered. 

![image](https://user-images.githubusercontent.com/49142028/81919150-becf8600-95d7-11ea-9899-00b7f97c2537.png)

**Comment by a18jenro** [comment]
@a17towan the top icons are still a bit off I guess. So it should be fixed.
