### ISSUE TITLE
Create a wiki page with information about different users

### ISSUE THREAD

**Issue by a18jonkl** [HGustavs/LenaSYS#9230]
There are five different levels of access for LenaSYS: Read, Write, StudentTeacher, Supervisor, and Superuser.
These access levels are student, teacher, student-teacher, supervisor, and administrator. It would be good if there was clear information about what users to use for different functionalities.

**Comment by a18jonkl** [comment]
Administrator: brom
Teacher: mestr
Student: keree
Student without any courses: alvik

All users have password ‘password’.

**Comment by a18kaswi** [comment]
If you need to test resetting of password you need to be logged in as non-superuser.

**Comment by a17towan** [comment]
This looks good. The information is concise and explanatory.
