### ISSUE TITLE
Make the saved variables in localstorage take up less space 

### ISSUE THREAD

**Issue by b18phibe** [HGustavs/LenaSYS#9231]
To reduce space needed to store a single diagram. Then we need to reduce to storage space every diagram takes up and we wish to do that by shortening the variable name of the saved variables. But to not make it to difficult for the developers, we wish to have a shortening function/look up table so the diagram only saves one letter variables but the function and developer are working whit full sized variable names.

**Comment by a18antsv** [comment]
I am possibly trying to achieve this when working on #8819.

**Comment by a18antsv** [comment]
I am thinking to just use a range of ASCII characters A-Z, A-z and some extra ranges in case more is needed. Then i could possibly use a delimiter character before the character. Tilde for example (~) to be able to search for all occurrences and replace it back no normal again.
