### ISSUE TITLE
toolbarState in localStorage not working correctly 

### ISSUE THREAD

**Issue by g18marma** [HGustavs/LenaSYS#9245]
When switching to DEV or UML mode the toolbar state gets saved in localStorage. But when updating the page it gets reset to ER mode. The page should load the previously used toolbar mode.

**Comment by a18jonpe** [comment]
I cannot seem to replicate this problem. The toolbar does not change when refreshing the page. Is this still an issue?

**Comment by a18jonpe** [comment]
It seems this issue got solved along with some other issue. Closing.
