### ISSUE TITLE
Validation in Duggaed complain from the beginning. 

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#9249]
Validation in Duggaed complains from the beginning on "Name" because it is empty.

<img width="475" alt="Screenshot 2020-05-14 at 10 49 11" src="https://user-images.githubusercontent.com/49142649/81914228-52518880-95d1-11ea-9e02-830dc385651b.png">

**Comment by c14jonfr** [comment]
A quite simple solution is to check whether the dugga has a qid (if it does it's an existing dugga, if not it's a new dugga) and only run the validateDuggaName() for the already existing ones.

**Comment by c14jonfr** [comment]
Correction/Clarification: new duggas do have a qid, but it is "UNK" (so the check has to be if the qid is "UNK" or not).

**Comment by a18viksa** [comment]
Closing issue after merge to master.
