### ISSUE TITLE
Error when editing dugga information in courseed

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#9255]
When saving a dugga's information, whether changed or not, if enable student feedback is not checked:
![untitled2](https://user-images.githubusercontent.com/62876507/81915389-ce989b80-95d2-11ea-8863-6c44f2eba32d.PNG)
Then the following error is displayed:
![untitled](https://user-images.githubusercontent.com/62876507/81915446-dfe1a800-95d2-11ea-982f-55d2c3cbf5f1.PNG)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
