### ISSUE TITLE
Blue box that highlight items in drop-down menus is too wide

### ISSUE THREAD

**Issue by b18simla** [HGustavs/LenaSYS#9267]
The box should be aligned with the drop-down edges. As of now, the right side sticks out: 
![Namnlös](https://user-images.githubusercontent.com/62878243/81916989-e2dd9800-95d4-11ea-9629-22d713b89e8f.png)

**Comment by a18antsv** [comment]
This was due to box-sizing:border-box; being added to everything. Then the width of the inner element was set to 100% to fix another problem. But now when box-sizing:border-box; was removed again this will cause a problem. This can easily be fixed by setting the width back to 252px.
