### ISSUE TITLE
Color in .access-dropdown-selected is overwritten. 

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#9269]
Color in .access-dropdown-selected is overwritten by .access-dropdown-content div. 
Two options of a solution is: 
- Add !important after. 
<img width="193" alt="Screenshot 2020-05-14 at 11 45 11" src="https://user-images.githubusercontent.com/49142649/81919693-74023e00-95d8-11ea-8aff-dbc9359aa29e.png">

or
- Delete unnecessary line.
<img width="193" alt="Screenshot 2020-05-14 at 11 45 32" src="https://user-images.githubusercontent.com/49142649/81919703-76fd2e80-95d8-11ea-8fe1-07c781f78171.png">

**Comment by a18viksa** [comment]
Closing issue after merge to master.
