### ISSUE TITLE
The announcement feature should be part of courseed page and not sectioned page

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#9275]
With the idea that as soon as the students logs in, they should get the announcements if there is any and they don't have to click on particular course to get the announcements.

With that being said this is a general feature for the entire system that's why this should be moved to the start page/courseed page.

What you need to do is:
- Move the announcement icon to courseed page 
- And make sure the feature works there as it worked in sectioned page

Tips:
- You have  to discuss with group 4 prior to this issue because they are responsible for modification of courseed page.

**Comment by a19isada** [comment]
The announcement feature should be part of the sectioned page because when integrated into canvas, the courseed will rarely be visited and the announcement will not reach the students. This issue is therefore closed.
