### ISSUE TITLE
Date inputs in Dugga Editor not styled consistently with other inputs

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9280]
The date inputs look a bit weird compared to the other inputs since they are smaller (in terms of height) and have rounded corners. See screenshot 1.

I suggest adding the class "textinput". Similar inputs in for example Section Editor has this class. An example of how this would look can be seen in screenshot 2. I would also increase the width of the input a little bit so the date is not cut off. An example of how this could look is the "Result release"-input in screenshot 2.

![image](https://user-images.githubusercontent.com/49141758/81928218-3526b500-95e5-11ea-9f07-f4b3cc801eee.png)

![image](https://user-images.githubusercontent.com/49141758/81928755-1674ee00-95e6-11ea-9a5e-a4bce73168a6.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
