### ISSUE TITLE
'Last Modified' in Dugga Editor still displays seconds

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9281]
This has been changed for both Startdate, Deadline and Result date. To keep it consistent it should be changed for Last Modified as well.

![image](https://user-images.githubusercontent.com/49141758/81929042-8edbaf00-95e6-11ea-8512-b6fef3179642.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
