### ISSUE TITLE
Takes too long time to show text when hovering a button in navheader (at places)

### ISSUE THREAD

**Issue by a18ismca** [HGustavs/LenaSYS#9303]
**This is not happening at all places.** For example, in resultEd this issue does not exists as the navheader in the same page reacts directly when hovering a thing in the same page. However, for example in sectionsEd, the respons is a bit slow when it comes to show text. See below:

![image](https://user-images.githubusercontent.com/62876523/81939677-eda92480-95f6-11ea-9164-d8f53a74e9a5.png)

In this case, **"course page for..."** appears roughly one second after hovering the same icon. It would be good to fix this type of issues att several places if possible, **so that the text appears directly**, which will be more comfortable for me as a user when I am using LenaSYS

**Comment by a20chrjo** [comment]
If the alt-tag is not used, change it to an alt-tag. Otherwise keep the changes, since the screen reader must be able work for accessibility. The performance cannot be changed with the alt-tag.

**Comment by a19isada** [comment]
Alt tags are used and the perfomance can't be changed. This closes the issue
