### ISSUE TITLE
Mobile: Height of windows should be equal to content to avoid scrollbars

### ISSUE THREAD

**Issue by a18filkr** [HGustavs/LenaSYS#9304]
As part of #493 
The window gets a scrollbar when too much code cannot fit, this should instead extend the window so that every row "fits" and the user has to scroll through it, it's not very mobile friendly to adda scroll bar when you're scrolling down on the page.

![bild](https://user-images.githubusercontent.com/49142751/81940935-707eaf00-95f8-11ea-86a8-996b6e245f33.png)

These rows should all be visible.

**Comment by a18filkr** [comment]
Maybe also add so that if the height of template window doesn't fill the screen, the minimum size should be to fill the screenheight.

**Comment by a20sarle** [comment]
Customer did not want functionality.
