### ISSUE TITLE
Navheader: Announcement icon not ideal 

### ISSUE THREAD

**Issue by a18viksa** [HGustavs/LenaSYS#9307]
In my opinion the announcement icon is wrong for its purpose. Now it looks more like a volume button than anything else. This can cause confusion for students/teachers that are not up to date with this new implementation in LenaSYS. 

![image](https://user-images.githubusercontent.com/49142704/81941976-d15ab700-95f9-11ea-8353-eea5f3c75a6f.png)

Maybe it could look something like this? 

![image](https://user-images.githubusercontent.com/49142704/81941831-9bb5ce00-95f9-11ea-8eaa-c89928fc539b.png)
![image](https://user-images.githubusercontent.com/49142704/81943394-9b1e3700-95fb-11ea-83be-0fea1babdd3f.png)

The group in charge of the icons can discuss if they too think this is an issue worth fixing.

**Comment by a19isada** [comment]
After a meeting with the customer, it was decided that the icon should be changed into something more appropriate. The customer thought the last of the pictures above was the best suited.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
