### ISSUE TITLE
Sectioned: Announcement form issues 

### ISSUE THREAD

**Issue by a18viksa** [HGustavs/LenaSYS#9311]
The "announcementFormcontainer" has a problem with too wide input fields as displayed below. 
Just a simple width issue. 

![image](https://user-images.githubusercontent.com/49142704/81944513-25b36600-95fd-11ea-9c82-cb56249bb8d2.png)

I also think it's unnecessary to have a resizable textarea. Just include `resize: none`. 

![image](https://user-images.githubusercontent.com/49142704/81945043-d91c5a80-95fd-11ea-83b1-2b609018ba01.png)

One final thing is that when you click the red X it doesn't clear everything from the page. Although, if you click on the announcement icon everything clears.

X: 

![image](https://user-images.githubusercontent.com/49142704/81945689-b6d70c80-95fe-11ea-9f4a-abf5d8c0aa27.png)

Announcement icon: 

![image](https://user-images.githubusercontent.com/49142704/81945780-ce15fa00-95fe-11ea-9d70-0723ed9d7680.png)

Also, the list view (when you've made an announcement) is too wide which makes the div scrollable.

**Comment by a18mahkh** [comment]
Most of the issues pointed out here is solved. Wait till this week's merge and after that if any of the issues are still there then assign someone to solve these.

**Comment by a18mahkh** [comment]
The red X is not suppose to clear everything. It should only close the announcement form.

**Comment by a18mahkh** [comment]
What you mean by "Also, the list view (when you've made an announcement) is too wide which makes the div scrollable"

Could you maybe send a screenshoot?

@a18viksa

**Comment by a18viksa** [comment]
This is no longer a problem as far as I can see @a18mahkh
