### ISSUE TITLE
Wouldn't it be nice if you get an alert sayng that your login has timedout?

### ISSUE THREAD

**Issue by c13chrjo** [HGustavs/LenaSYS#933]
This concerns when you are automaticaly logged out from inactivity,

**Comment by HGustavs** [comment]
My suggestion is to do it in a nice way... asking for a click in a confirm box for instance after 30 minutes ... and if cancel is pressed or if ok is pressed after more than 40 minutes you are logged out, this way you get a chance to be proactive.

**Comment by HGustavs** [comment]
I get irked by violent no-warning-log-offs.

**Comment by a15freed** [comment]
related to #2417

**Comment by a15tobli** [comment]
Closing issue as #2417 covers this.
