### ISSUE TITLE
Template 8 is having issues with a top being set on box3wrapper

### ISSUE THREAD

**Issue by a17chrka** [HGustavs/LenaSYS#9333]
<a href="https://gyazo.com/b322db9fb3f3cec448f07e1c3dfdee28"><img src="https://i.gyazo.com/b322db9fb3f3cec448f07e1c3dfdee28.gif" alt="Image from Gyazo" width="1916"/></a>

**Comment by d17marle** [comment]
Can't seem to replicate this issue, are you on the correct branch?
