### ISSUE TITLE
The coffee consumption in this world is too high

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#9351]
Change starts with you!

**Comment by a18kaswi** [comment]
Something feels very weird about this issue, probably just the sight of the assignee that gives me this feeling though. #paddingstats2020

**Comment by a18oscba** [comment]
It seems that my consumption has gone down lately, I don't know if it is a bug that people still suffers from this problem.

**Comment by a17towan** [comment]
I second this. It's 3 PM and I've just had my 4th cup of coffee.
