### ISSUE TITLE
Access Editor: Missing cancel button when adding a new user

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#9353]
A cancel button on the add dugga window in the Dugga editor exists and the Access editor should be the same when adding a new user.

Add user in Access editor:
<img width="481" alt="Skärmavbild 2020-05-15 kl  13 48 37" src="https://user-images.githubusercontent.com/62876260/82047648-75546900-96b3-11ea-8e7b-9c2d3c0e6475.png">

The bottom of the add dugga window in Dugga editor:
<img width="481" alt="Skärmavbild 2020-05-15 kl  13 49 40" src="https://user-images.githubusercontent.com/62876260/82047709-91f0a100-96b3-11ea-873d-4f569b7b54e7.png">

**Comment by HGustavs** [comment]
Or, only having the cross in the top left corner, and no cancel button....

I do not remember if the policy is to not have cancel buttons or if it was decided to have hem at some point.

At some early point it was decidied that  we should have no cancel buttons (as the cross closing button performs the same action) ... unclear if that decision was reverted.

**Comment by b18alegu** [comment]
If that is the case @HGustavs, I'll close this issue immediately.
