### ISSUE TITLE
Frågedugga question/answer options not displayed properly

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9357]
Sub-issue of #9310.

Because of an issue with string-splitting in kryss.js the question and answer options are not displayed properly. 

![image](https://user-images.githubusercontent.com/49141758/82050890-2e697200-96b9-11ea-89d0-3e7c34af9eec.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
