### ISSUE TITLE
you can change "moment" by dragging the items around. Remove unecessary "moment-change" that exists when clicking on the cogweel

### ISSUE THREAD

**Issue by a13chrju** [HGustavs/LenaSYS#937]
Linked to: https://github.com/HGustavs/LenaSYS/issues/914

I fixed so you change the moment a test belongs to by jsut dragging it up or down. To make it easier for the admin I only want this function here and remove it from the edit test cogweel. For gamification purposes.

**Comment by a13oscwe** [comment]
Fixed in https://github.com/HGustavs/LenaSYS/issues/914
Closing
