### ISSUE TITLE
Hidden layer objects can be placed on top of shown layer objects

### ISSUE THREAD

**Issue by a18antsv** [HGustavs/LenaSYS#9381]
Objects in hidden layers can be positioned over objects in shown layers making it impossible to move the object as the hidden object is detected by the mouse instead. The objects in hidden layers should not be detected by the mouse at all.
![399507ca413b9b29e66338135b301457](https://user-images.githubusercontent.com/49121839/82131256-8dbba500-97d3-11ea-9413-00214c16b169.gif)

**Comment by a18antsv** [comment]
Related to #9379 and #9380

**Comment by a18jonpe** [comment]
I'm thinking of solving this by removing the "hitbox" on the objects when the layer gets hidden then add them back when the layer gets shown again. Trying to figure out how the layers work since it's pretty new. Need to figure out how to check what objects belong to certain layers.

**Comment by a18jonpe** [comment]
So the issue now is how to "hide" the objects from the mouse. I'm not sure how to approach this, possibilities are to get rid of the hitbox (which I had a hard time figuring out how to do), or perhaps move the objects until the layer is shown again. I would appreciate some ideas on how to move forward here.

**Comment by a18petha** [comment]
Far as I know trying to remove the hitbox from a diagram object would result in removing whole object. as when a object is created it's done with corners where hitbox is set. Think a better approach would be to lock items that are not rendered. perhaps reusing the lock function could be useful for this

**Comment by a18petha** [comment]
There is a "isLocked" variable that checks if said object is locked. implementing this with a isLayerLocked would be how I've approach it.
