### ISSUE TITLE
AccessEd - Sorting by access sometimes sorts incorrectly

### ISSUE THREAD

**Issue by b18jonli** [HGustavs/LenaSYS#9389]
If a user has been set to "teacher" and is then reset to "student" it gets sorted incorrectly.
<img width="181" title='"Students" get sorted both above and below "teacher"/"student teacher"' alt="Screenshot 2020-05-18 at 8 47 44 AM" src="https://user-images.githubusercontent.com/62876553/82182365-7ae4c580-98e4-11ea-8f97-87fc8c09e91c.png">

**Comment by a18viksa** [comment]
Closing issue after merge to master.
