### ISSUE TITLE
Frågedugga missing information about submission/grading in navheader

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9391]
Screenshot 1. Frågadugga, navheader is missing the stoplight and the status of the submission.
![image](https://user-images.githubusercontent.com/49141758/82183308-0743b800-98e6-11ea-894c-5a63af3f62a0.png)

Screenshot 2. Biträkningsdugga, showing what the navheader is supposed to look like.
![image](https://user-images.githubusercontent.com/49141758/82183357-1a568800-98e6-11ea-8bf3-a1d127db32b4.png)

The problem seems to be that the Frågedugga never calls the displayDuggaStatus function (in kryss.js, in returnedDugga) which the other duggas all do.

**Comment by HGustavs** [comment]
This header looks really nice.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
