### ISSUE TITLE
Fix search bar in duggaed

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#9398]
Even after https://github.com/HGustavs/LenaSYS/pull/9397, the search bar in duggaed's navheader still autocompletes and receives suggestions to use saved usernames.

**Comment by HGustavs** [comment]
This is only a problem in chrome?

or are other browsers also affected?

**Comment by HGustavs** [comment]
This is a common issue in (chrome?) that the browser confuses other text inputs as the login and auto-fills those inputs with the login name.

**Comment by HGustavs** [comment]
https://support.google.com/chrome/thread/6787468?hl=en

**Comment by HGustavs** [comment]
https://stackoverflow.com/questions/54711475/chrome-autofills-username-into-random-text-input
