### ISSUE TITLE
Removal of Cancel and Close buttons in Dugga Editor

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#9410]
In the Dugga Editor the following buttons should be removed according to my interpretation of the customers preferences:
- The "Cancel"-button from the "Edit Dugga"-dialog
- The "Close"-button from the "Variant Editor"-dialog

Comment from @HGustavs in issue #9353:
> Or, only having the cross in the top left corner, and no cancel button....
> 
> I do not remember if the policy is to not have cancel buttons or if it was decided to have hem at some point.
> 
> At some early point it was decidied that we should have no cancel buttons (as the cross closing button performs the same action) ... unclear if that decision was reverted.
> 
> But my guess until convinced otherwise is that the cancel button should be removed.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
