### ISSUE TITLE
Add styling on start & enddate i sectioned. 

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#9413]
The boxes with dates should be consistent with add/edit a dugga in dugged. See img 2 & 3.

<img width="475" alt="Screenshot 2020-05-18 at 12 21 44" src="https://user-images.githubusercontent.com/49142649/82202539-57c90e80-9902-11ea-911d-63b3d93b5fc9.png">
img 1 - Before in sectioned. 

<img width="475" alt="Screenshot 2020-05-18 at 12 23 34" src="https://user-images.githubusercontent.com/49142649/82202628-7c24eb00-9902-11ea-81cf-dbb21880964b.png">
img 2 - How it should look in sectioned.

<img width="475" alt="Screenshot 2020-05-18 at 12 24 06" src="https://user-images.githubusercontent.com/49142649/82202634-7e874500-9902-11ea-9d85-9157da5fd197.png">
img 3 - Edit/add in duggaed.

This can be solved by adding this in style.css: 
.inputwrapper #startdate, .inputwrapper #enddate{
  font-family:"Roboto";
  color:#7f7f7f;
}

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
