### ISSUE TITLE
Frågedugga will always display the same variant

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9436]
**Note: to "see" this issue, you will need the fix from https://github.com/HGustavs/LenaSYS/pull/9363**

Frågedugga always displays the same variant (the last one), even if the system has decided that user should receive some other variant (this is done randomly). In the showDuggaService.php file, the variant for a dugga is in the $savedvariant variable. 

Screenshot 1. Shows the variant that is displayed to the user.
![image](https://user-images.githubusercontent.com/49141758/82292213-c19cf300-99aa-11ea-8e24-43ad30f963fb.png)

Screenshot 2. Shows (part of) the response from showDuggaService.php when opening/visiting the Frågedugga. I added '"variant" => $savedvariant' to the response array for demonstrative purposes. Here we can see that this user is supposed to receive/see variant 17.
![image](https://user-images.githubusercontent.com/49141758/82292241-d37e9600-99aa-11ea-871f-7064cf470ad2.png)

Screenshot 3. From Dugga/Variant Editor. Here we see the available variants for the Frågedugga and we can clearly see that variant 17 is NOT the one being shown to the user. The user sees the variant 20 (the last one).
![image](https://user-images.githubusercontent.com/49141758/82292283-ea24ed00-99aa-11ea-8078-2bc91d1a684a.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
