### ISSUE TITLE
Frågedugga question number is not centered vertically

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9440]
**Note: This requires the fix from https://github.com/HGustavs/LenaSYS/pull/9363 to be visible (else the number will not be displayed at all)**

See screenshot. The "1" is centered horizontally but not vertically inside the circle. Should be a simple css fix.

![image](https://user-images.githubusercontent.com/49141758/82296404-6fab9b80-99b1-11ea-9aa5-ac72d8418e74.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
