### ISSUE TITLE
Remove duplicated style in CSS

### ISSUE THREAD

**Issue by a18eripi** [HGustavs/LenaSYS#9443]
Cleaning up the code by removing the duplicated navheader style in sortableTableLibrary/style.css

Co-authored-by: b18fella <b18fella@users.noreply.github.com>

**Comment by a18eripi** [comment]
Examined and established together with @b18fella that the styling css for sortableTable is not used.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
