### ISSUE TITLE
Statistics swimlane in mobile view looks funny

### ISSUE THREAD

**Issue by a17towan** [HGustavs/LenaSYS#9460]
The statistics swimlane in mobile view looks funny when you go below ~350 px in width.
![image](https://user-images.githubusercontent.com/49142028/82305519-054d2800-99be-11ea-9f67-6bdd00897713.png)

Fix this, please.

**Comment by a18jenro** [comment]
@HGustavs or @mbrohede What is the minimum width that LenaSYS should support?

**Comment by a19isada** [comment]
This is no longer an issue since the swimlanes have been moved to the top.
