### ISSUE TITLE
StudentTeacher and Supervisor users can't see hidden items

### ISSUE THREAD

**Issue by a18jimol** [HGustavs/LenaSYS#9461]
Users with StudentTeacher and Supervisor access can right now create new items(headings, code-examples, duggas) in sectioned but can't see them because the new items have the visiblity hidden and ST/SV users can't see hidden items.

Studentteacher: Got 'ST' access for all courses.
mofre

Supervisor: Got SV access for all courses.
ryrey

Password is ‘password’.

**Comment by a18jenro** [comment]
Seems to have been solved by itself.
