### ISSUE TITLE
Fix layout in Random Clipping Dugga.

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#9472]
<img width="1280" alt="Screenshot 2020-05-19 at 11 59 07" src="https://user-images.githubusercontent.com/49142649/82313088-2d418900-99c8-11ea-902c-f0c05a7e821e.png">
<img width="1280" alt="Screenshot 2020-05-19 at 11 59 15" src="https://user-images.githubusercontent.com/49142649/82313093-2dda1f80-99c8-11ea-91c4-038dd0ae0ab6.png">

**Comment by a18viksa** [comment]
Closing issue after merge to master.
