### ISSUE TITLE
Analytics navbar not scaling well

### ISSUE THREAD

**Issue by a18oscba** [HGustavs/LenaSYS#9488]
If you are in mobile view in the analytics page the navbar looks like this:
![image](https://user-images.githubusercontent.com/62877630/82323595-94ffd000-99d8-11ea-8e37-66a632399af1.png)

It would be prefered if it would look more like this:
![image](https://user-images.githubusercontent.com/62877630/82323715-c37dab00-99d8-11ea-8e66-b5f51a4e591b.png)

Solution could be to maybe remove a few buttons if they are not needed or maybe add a second row for those button that don't fit within the navbar?

Other example maybe add a div and make buttons that isnt visible in the navbar visible in the div instead.

**Comment by a17towan** [comment]
Thinking of making a hamburger menu for this.

**Comment by a18oscba** [comment]
Even better!
