### ISSUE TITLE
Users with StudentTeacher, Supervisor or Writeaccess can't edit items i sectioned

### ISSUE THREAD

**Issue by a18jimol** [HGustavs/LenaSYS#9493]
Users with StudentTeacher and Supervisor can create new items in sectioned and users with writeaccess can add and delete items but none of them can edit items. They can all open the window for edit items and change information but when clicking save nothing happens.

Studentteacher: Got 'ST' access for all courses.
mofre

Supervisor: Got SV access for all courses.
ryrey

Password is ‘password’.

**Comment by a18jenro** [comment]
This seems to have fixed itself.
