### ISSUE TITLE
SQL-Migration: Conform LenaSYS\Shared\SQL\init.db to PostgreSQL

### ISSUE THREAD

**Issue by a18kaswi** [HGustavs/LenaSYS#9502]
The init.db file is the one used to create the database. 

The syntax needs to be changed to work with PostgreSQL.

Resource: https://en.wikibooks.org/wiki/Converting_MySQL_to_PostgreSQL

**Comment by a18kaswi** [comment]
Comments starts with -- and ends with */

**Comment by a17robhe** [comment]
updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP not supported by postgres. Triggers need to be used.

See https://stackoverflow.com/questions/1035980/update-timestamp-when-row-is-updated-in-postgresql
