### ISSUE TITLE
SQL-Migration: Conform files in LenaSYS\install\SQL to PostgreSQL

### ISSUE THREAD

**Issue by a18kaswi** [HGustavs/LenaSYS#9503]
In LenaSYS\install\SQL there are several files. These are used by the installer to fill the created database.

The syntax needs to be changed so that it works with PostgreSQL.

Resource: https://en.wikibooks.org/wiki/Converting_MySQL_to_PostgreSQL

**Comment by a18kaswi** [comment]
#9580
#9581
#9582
#9583
#9584
#9585
#9586
#9588

**Comment by a17robhe** [comment]
This is still left to implement in init_db

https://github.com/HGustavs/LenaSYS/issues/9595
