### ISSUE TITLE
Frågedugga submissions/answers not handled properly in Result Editor

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9516]
See screenshot for an example of what a submission from the Frågedugga looks like in the Result Editor.

My understanding of this is:
* The first "Answered:" is the user answers. These are (should be) marked as red if incorrect and green if correct.
* The second "Answered:" is the correct answers for the dugga. Or should be, rather. It seems like it currently shows the correct answers for ALL the duggas in the course which is obviously wrong.

![image](https://user-images.githubusercontent.com/49141758/82416524-7520e880-9a7a-11ea-93e9-59380e7364bd.png)

Aside from fixing the whole issue with the "correct" answers not being shown properly, I suggest changing the second "Answered:" to something more appropriate. "Correct answers:", perhaps?

I also suggest removing the commas from the list of user answers and using a blankspace as a separator between the answers (if there is a Frågedugga with more than one question, in the testdata there are only Frågeduggas with one question but I take it for granted more than one question should be possible). So it could look something like this: "Answered: A B C D".

I think you're supposed to be able to see the actual dugga in the Grading window too. I'm not sure if any work has been put into this, but the instructions accordion is there, so maybe. Either way I consider this a separate issue.

**Comment by c14jonfr** [comment]
The Frågedugga uses the savequizResult function in dugga.js while other duggas use the saveDuggaResult function. I believe the Frågedugga should be able to use the saveDuggaResult as well.

For simplicity's sake any solution to this issue (as in issue 9516) will use the savequizResult function and a new issue will be created at a later date concerning changing the implementation to use saveDuggaResult instead.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
