### ISSUE TITLE
When you add user to access first name get null

### ISSUE THREAD

**Issue by c13andka** [HGustavs/LenaSYS#952]
If you are adding a user to access a course the firstname will get null value

**Comment by HGustavs** [comment]
Are we sure about this bug?

I think @a97marbr  tested this last year, we surely would have noticed if the names were kooky?

**Comment by a12majca** [comment]
Ok, yes you're right Henrik. Took me a while though to understand how to add users the correct way. If you're new at this it's not 100% clear what the format should be like, would it be ok if I just changed the instructions a little bit?

**Comment by a13chrju** [comment]
Issue is not present anymore, closing
