### ISSUE TITLE
Bummer! You have reached a non-navigable link!

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#9521]
When grading a specific dugga, one that can have a file uploaded to it:
![untitled](https://user-images.githubusercontent.com/62876507/82423111-a05c0580-9a83-11ea-9dda-1f8c6f5b4f01.PNG)

You get this message if you open the instructions:
![untitled2](https://user-images.githubusercontent.com/62876507/82423126-a5b95000-9a83-11ea-84a3-86e887c879bd.PNG)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
