### ISSUE TITLE
Random clipping dugga need some fixes. 

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#9522]

**Comment by b18veran** [comment]
There are still problems. See img 1 there are white edges at the bottom. See img 2 when adding more than 19 operations. New issues will be added to it. Otherwise everything should work.

<img width="1280" alt="Screenshot 2020-05-20 at 12 46 53" src="https://user-images.githubusercontent.com/49142649/82438350-32bad400-9a99-11ea-84b5-4734e471c5fd.png">
IMG 1

<img width="1280" alt="Screenshot 2020-05-20 at 12 47 22" src="https://user-images.githubusercontent.com/49142649/82438348-32223d80-9a99-11ea-894d-ecd093feae43.png">
IMG 2

**Comment by a18viksa** [comment]
Closing issue after merge to master.
