### ISSUE TITLE
DuggaEd search bar in navheader is not implemented in NavHeader.php

### ISSUE THREAD

**Issue by a18jenro** [HGustavs/LenaSYS#9528]
Unlike the search bar in accessed.php, resulted.php and fileed.php, the search bar in duggaed.php is not implemented in the file navheader.php. This results in several inconsistencies. For example, when hovering over any of those three search bars, a tool tip is displayed. This is not the case in duggaed.php. 

This would probably take time, but it should be done. Unless there is a very good reason for treating duggaed's search bar differently from all the others.

**Comment by a20behta** [comment]
@a20johba No pull request before weekly merge. redone on current group branch for next weekly branch

**Comment by a20behta** [comment]
merged into master during weekly merge
