### ISSUE TITLE
"Check answers"-button and related functions in Frågedugga are pointless

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9533]
The buttons runs the function checkQuizAnswer and all it does is to show alerts with the checked answer(s). Alerts are disabled for students so for them it does literally nothing. Should be safe to remove.

If it does serve a purpose (or is supposed to, rather) it's very easy to implement again. It's just a button with an onClick-listener. No magic, nothing fancy.

![image](https://user-images.githubusercontent.com/49141758/82429468-3eec6480-9a8c-11ea-9a43-0c67c1907cf1.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
