### ISSUE TITLE
Random css dugga need to adjust to smaller screens. 

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#9542]
When you minimize your screen the content will come outside the view and needs to be fixed. 
<img width="840" alt="Screenshot 2020-05-20 at 13 08 35" src="https://user-images.githubusercontent.com/49142649/82439909-c1305500-9a9b-11ea-9c6b-fcc7d2125b2a.png">

**Comment by a18viksa** [comment]
Closing issue after merge to master.
