### ISSUE TITLE
Inconsistent spacing between icons in the Navheader

### ISSUE THREAD

**Issue by a18fayha** [HGustavs/LenaSYS#9544]
The spacing between the "newCourseVersion" icon and "editStudentResults" seems bigger compared to the others, which looks kind of weird.
![image](https://user-images.githubusercontent.com/62876354/82441771-b9be7b00-9a9e-11ea-80fa-52b75d551319.png)

**Comment by a18jenro** [comment]
This was done intentionally to separate the icons because they do such different things. But one could try to find a better way to separate them.

**Comment by a18fayha** [comment]
I think it would be more clear that they are seperated intentionally if there was more spacing between them. Somethig like this maybe, thoughts?
@a18jenro 
![image](https://user-images.githubusercontent.com/62876354/82443988-c3e27880-9aa2-11ea-99a1-efec9f0dbd95.png)

**Comment by a18jenro** [comment]
I think we should separate them, in some way, without just adding more empry space, because it still looks like a mistake. Perhaps one could draw a line between them or something.

**Comment by a18danli** [comment]
We made the decision to remove the spacing because of better design layout.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
