### ISSUE TITLE
Some Dugga Editor Variant previews are not styled properly

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9550]
Some of the previews are not styled properly. It seems like this is because they are (should be) styled from dugga.css and not only style.css. dugga.css is not linked in duggaed.php. Adding this link fixes the issue for _some_ duggas, but not all. For example the HTML CSS Testdugga/html_css_dugga and kryss/quiz/Frågedugga either do not work or still look a bit messed up. 

First screenshot is the preview from the Dugga Editor, the second is the preview used in the Result Editor (when grading a student).

**Biträkningsdugga**
![image](https://user-images.githubusercontent.com/49141758/82443751-4e76a800-9aa2-11ea-898f-9678b97308db.png)
![image](https://user-images.githubusercontent.com/49141758/82443853-7bc35600-9aa2-11ea-85a6-f9b45cef2ab7.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
