### ISSUE TITLE
Dropdown for templates don't do anything

### ISSUE THREAD

**Issue by a18filkr** [HGustavs/LenaSYS#9552]
When choosing a template you get to choose which default settings you want, even if you change between code/description or anything else nothing of this is used when you click to change template.

![bild](https://user-images.githubusercontent.com/49142751/82447302-63eed080-9aa8-11ea-9aca-98ccb5067ab5.png)

**Comment by a20joabo** [comment]
Changing template seem to overwrite selections in drop downs. 
The functionality for file selection is not implemented.

**Comment by a20joabo** [comment]
Something needs to be added in the `changetemplate()` function in codeviewer.js. 
 There are three feasible options I can think of: 
1. Requesting a confirmation from the user when changing templates. something like  "_Are you sure you want to change? Changes will be lost!_". 
2. Implementing a function that checks if there are any previous changes in the drop downs and remembers them.  **However** it becomes a problem knowing which options should be removed when changing from a template with 3 boxes to a template with 2 boxes.
3. A compromise between the two. First checking if there are any changes and if so warn the user that their changes will be lost upon changing template.

**Comment by a20sarle** [comment]
None of the above suggestions clearly meet customer needs but number 2 is the closest. Customer wants:
- for each CodeViewer example the system should remember which files were the last one to be uploaded and all fields should be auto filled when returning to edit an example.
- when changing from a 3 file template to a 2 file template the last file in the template group should be "removed" however,
- if one regerets the decision and goes back from a 2 file template to a 3 file template the 3rd file should be remembered and auto filled.
With the above said the page should not reload when a new choice of template has been made.

**Comment by a20joabo** [comment]
This issue could be resolved without re-formating the code by defining a list:

- `content = [];` 

Then adding the selected options to it before the drop downs are re-generated:

- `var values = [$("#boxcontent_" + i).val(), $("#filename_" + i).val(), $("#wordlist_" + i).val()]; `

- `content.push(values);` 

The values of whatever has been selected in the drop-downs are now kept in the `content` list. 

I am running into trouble with implementing this list however, as I find no way of changing the selected option after the drop-downs has been regenerated.
