### ISSUE TITLE
Make the "Add User" dialog in AccessEd errors behave/look like the CourseEd

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#9565]
The error messages in the Access Editor looks like this at the moment:
<img width="478" alt="Skärmavbild 2020-05-21 kl  15 25 23" src="https://user-images.githubusercontent.com/62876260/82563490-78e66500-9b77-11ea-93f9-ff7d1cfa8d4c.png">

The error messages in the Course Editor looks so much nicer though:
<img width="478" alt="Skärmavbild 2020-05-21 kl  14 51 39" src="https://user-images.githubusercontent.com/62876260/82563535-8dc2f880-9b77-11ea-8cc2-329ff5b02847.png">

The Access Editor should copy the look and behaviour from the Course Editor. Suggestion initially made by @c14jonfr.

Co-authored-by: @c14jonfr

**Comment by a18viksa** [comment]
Closing issue after merge to master.
