### ISSUE TITLE
When marking group-assignments (and grading the whole group at once), the table is not rendered correctly

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9575]
See screenshot. Assignments from student in the same group are correctly graded (both in the table and in the database) but all students "below" will not be rendered properly, they receive this colored bar instead of the previous "N/A". This is fixed on refresh, meaning this is only a visual error, the database is updated correctly.

![image](https://user-images.githubusercontent.com/49141758/82654006-5a887400-9c20-11ea-87e3-34efdf9c37d7.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
