### ISSUE TITLE
In Result Editor, the resultedLegendContainer will sometimes be covered by the table column headings

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9578]
See screenshot. This seems to happen if the user scrolls all the way to the right and then scrolls down. If not scrolled all the way to the right the LegendContainer will move down so that it is not covered.

![image](https://user-images.githubusercontent.com/49141758/82654505-23669280-9c21-11ea-87ff-b56ace9cd0cf.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
