### ISSUE TITLE
CodeViewer Markdown using "#" in headings

### ISSUE THREAD

**Issue by f12danjo** [HGustavs/LenaSYS#959]
As it is now the input "# ## Hello" would look like:
## Hello
Instead it should look like this:
# ## Hello

You can have "#" in headings if you just don't have a whitespace directly after it, like this: "# ##Hello".
This input would produce:
# ##Hello

The markdown parser should be fixed so that only the first "header symbol" on a line row should be interpreted as markdown. However you should be able to combine header with other markdown styling, like "*".

**Comment by c13caral** [comment]
This issue is now solved! :+1:
