### ISSUE TITLE
CodeViewer: Template 4 & Template 5 breaks when resizing the browser window

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#960]
![39eb2074-e421-11e4-9853-1ff181249f6d](https://cloud.githubusercontent.com/assets/11715450/7183436/b9c20e1c-e457-11e4-8ed4-31394fcf68e3.png)

**Comment by c13caral** [comment]
It also breaks when you open the webbpage and then increase the size of the browser.

![fel](https://cloud.githubusercontent.com/assets/11715450/7184079/8e269008-e45b-11e4-8791-4fd1351f7848.png)

**Comment by a13jorla** [comment]
Merge is done and worked good.
