### ISSUE TITLE
The feedback feature should be part of courseed page and not sectioned page

### ISSUE THREAD

**Issue by a18mahkh** [HGustavs/LenaSYS#9609]
With the idea that as soon as the students logs in, they should see the feedbacks immediately if there is any and they don't have to click on particular course to see the feedbacks.

With that being said this is a general feature for the entire system that's why this should be moved to the start page/courseed page.

What you need to do is:

Move the feedback icon to courseed page
And make sure the feature works there as it worked in sectioned page
Tips:

You have to discuss with group 4 prior to this issue because they are responsible for modification of courseed page.

**Comment by a19isada** [comment]
This is an outdated issue since students should not be able to log in to LenaSYS anymore
