### ISSUE TITLE
CodeViewer: There is some weird overflow behaviour when resizing the browser window.

### ISSUE THREAD

**Issue by c13caral** [HGustavs/LenaSYS#961]
![ed236062-e420-11e4-9e83-8936ab64ef87](https://cloud.githubusercontent.com/assets/11715450/7183464/e46063a8-e457-11e4-8f1a-ebe60e851744.png)

**Comment by HGustavs** [comment]
There used to be a javascript function that was called on resize to handle this.
Unclear exactly why this was needed, as it should not be necessary.

But if disabled the resizing would not work.

Only tested it for 2-split template though.

**Comment by b12alela** [comment]
This has to do with the same problem as issue #960 describes.
