### ISSUE TITLE
Frågedugga preview does not work

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9616]
In the Dugga Editor the user should be able to preview what a dugga/variant looks like by pressing the Play-button. Currently the Frågedugga preview is empty (only shows instructions, not the dugga/variant itself). See screenshot one. Compare this to the Bitdugga 1 in screenshot two. The layout is a bit messed up in the screenshot, ignore this. That is solved in https://github.com/HGustavs/LenaSYS/pull/9551.

There is also a preview in the Result Editor, accessible by pressing the Fist-icon for a submission. The preview does not work there either. I believe the previews are generated the same way, so this should be solved "automatically" if the Dugga Editor preview is solved.

![image](https://user-images.githubusercontent.com/49141758/82787216-403fd780-9e66-11ea-9b2b-c18353ac9859.png)

![image](https://user-images.githubusercontent.com/49141758/82787352-8006bf00-9e66-11ea-8cc3-950451695095.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
