### ISSUE TITLE
CodeViewer: variable appuser, what is it good for?

### ISSUE THREAD

**Issue by c12jenek** [HGustavs/LenaSYS#964]
If you search this repository there's a variable assignment in CodeViewer/editorService.php:
$appuser=(array_key_exists('uid', $_SESSION) ? $_SESSION['uid'] : 0);
It's however never ever used or referenced in any other place.
Another case of forgotten code since last year or code that is to be implemented?

**Comment by c12jenek** [comment]
Same goes for;
$boxid=getOP('boxid');
'boxid' is used directly several times but never the variable

**Comment by HGustavs** [comment]
Appuser is for logging and accountability.

I do believe that the boxid is necessary for getting the box content user interface dialog to work. It was left unimplemented, for example for changing which file is shown in a code view.

**Comment by b14rebst** [comment]
Should we look in to this now or can I close the issue? @HGustavs

**Comment by a17andby** [comment]
Since we can't refactor old code, is this still a issue?

**Comment by HGustavs** [comment]
We can close this.
