### ISSUE TITLE
SQL-migration: Refactor 'groups' to 'lenasys_groups'

### ISSUE THREAD

**Issue by a18jonkl** [HGustavs/LenaSYS#9642]
After changing from MySQL to Postgres table groups had to be changed to lenasys_groups. Refactor this for all database calls for the LenasSYS project.

**Comment by a18jonkl** [comment]
When using a reserved word in Postgres it must be in quotation marks and when writing a query, it would look something like this: ‘ SELECT “groups”.xy FROM “groups” ’.

**Comment by a18kaswi** [comment]
One real choice need to be made in consensus between the use of "user"/"group" OR lenasys_user/lenasys_group. Remember to elaborate on this in final post.

" After changing back to user syntax got extra sad.

In a php file user must be in "user" and for that to happen the string must be in 'SELECET * FROM "user" '. if something is quoted inside the string it must be changed from '' to "" also.
if user is not in "" it will call the ?? default?? database postgres and not find the column you are looking for.

When you are looking for a specific value in user as `user.cid` the correct syntax is 'SELECT "user".uid FROM "user"' "
