### ISSUE TITLE
StudentTeachers and Supervisors should be able to delete items in sectioned

### ISSUE THREAD

**Issue by a18jimol** [HGustavs/LenaSYS#9645]
StudentTeachers and Supervisors are supposed to have the same rights as teachers(writeaccess) see #9423 so the trashcan for deleting items should be visible and work correctly

**Comment by a18jenro** [comment]
@a18oscba Why did you close this issue, nothing was merged?

**Comment by a18oscba** [comment]
network issues idk I did merge

**Comment by a18jenro** [comment]
Yes, now I can see that it was merged. NVM!
