### ISSUE TITLE
In Result Editor, input field for teacher feedback does not show up for all duggas

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9646]
When you click the Fist icon on a submission it opens the "grading window" (I'm not sure what to call it, I hope you understand). If you click the yellow Fist icon another grading window pops up, here you are supposed to be able to leave feedback to the student(s), at least that is my understanding.

This window shows up for all duggas, but some of them are missing the input field for feedback. Screenshot one shows an example for this, the Linjedugga 1. Screenshot two shows the same window for the Färgdugga 1.

If you first open a dugga where it works (such as Färgdugga 1) and then go back to Linjedugga 1 the input field will be available and feedback can be given. See screenshot three.

![image](https://user-images.githubusercontent.com/49141758/82802379-147d1b80-9e7f-11ea-94f2-8d2884a1c79c.png)

![image](https://user-images.githubusercontent.com/49141758/82802460-3aa2bb80-9e7f-11ea-865b-639f8915967d.png)

![image](https://user-images.githubusercontent.com/49141758/82802594-7047a480-9e7f-11ea-91a2-d69b5728ff53.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
