### ISSUE TITLE
The "Kvitto och feedback - Duggasvar" window looks a bit off

### ISSUE THREAD

**Issue by a18marax** [HGustavs/LenaSYS#9671]
![image](https://user-images.githubusercontent.com/9322253/82850330-441e3900-9efc-11ea-873c-af3957f77d25.png)
Seems as the email field is to big for the window also the feed back window seems to act up during my initial fixes of the problem, so I might need to adjust that.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
