### ISSUE TITLE
In Access Editor it is currently impossible to remove a user from a group

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9673]
Because of the group dropdowns now using radio buttons instead of checkboxes it is impossible to remove the user from a group. It's possible to assign a new group (which means the user will be removed from group 1 and moved to group 2), but if a user has been assigned to a group it cannot be removed from groups altogether.

I suggest adding a new option for each dropdown, a "None"-group. I suggest adding this to the top of the dropdown (that's where it makes the most sense to place it in my opinion).

Screenshot showing appearance of group dropdown. Radio buttons do not let you "uncheck" them by clicking them again, like checkboxes work.
![image](https://user-images.githubusercontent.com/49141758/82870369-1d79f580-9f30-11ea-872d-903f59a769c5.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
