### ISSUE TITLE
In Access Editor, dropdown arrows will sometimes rotate without the dropdown opening

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9675]
I am able to rotate several of the arrows yet no dropdowns are opening. This seems to happen when pressing either the top or bottom of cells. See screenshot one for a crude approximation of the area(s).

![image](https://user-images.githubusercontent.com/49141758/82872119-e1945f80-9f32-11ea-9347-fdb99e187532.png)

This seems to correlate with the padding (?) of the td-element. See screenshot below.
![image](https://user-images.githubusercontent.com/49141758/82872299-28825500-9f33-11ea-9d6d-f64beef75706.png)

**Comment by a18viksa** [comment]
Closing issue after merge to master.
