### ISSUE TITLE
Display of red line on objects that are in incorrect position is delayed

### ISSUE THREAD

**Issue by g18marma** [HGustavs/LenaSYS#9684]
Objects that are positioned on the virtual paper are supposed to get a red outline to mark their incorrect position. Right now it's very glitchy and often delayed, and often happens on objects that are in correct position, especially when zooming in and out. An objects outline sometimes changes back to black even though it's still in the wrong position. The GIF below illustrates this.

![1770046b45582655c2af5d76d64d1397](https://user-images.githubusercontent.com/49142301/82882981-1fe54b00-9f42-11ea-8c77-d09cf5b834f9.gif)

The red outline should only be present on objects that are in incorrect position. It should not switch outline when zooming or moving the canvas.

**Comment by g18marma** [comment]
After moving the mouse the outline gets corrected.

![0ce3dfded3615f65a224d48e99daa13d](https://user-images.githubusercontent.com/49142301/82895769-039ed980-9f55-11ea-8b34-19eaed55d2ef.gif)

**Comment by g18marma** [comment]
This is probably caused by the fact that in the updateGraphics function the diagram.draw function gets called before drawVirtualPaper function. That's why the objects don't notice an incorrect position because the virtual paper doesn't exist yet. When moving the mouse the updateGraphics function gets called again and this time the Virtual paper does exist which means the diagram.draw colors the outline red. This issue should be solved by making sure the drawVirtualPaper function gets called before diagram.draw function

**Comment by b18phibe** [comment]
Merged!
