### ISSUE TITLE
SQL-MIGRATION: Code after triggers and functions in init_db.sql are ignored and gives foreign key error.

### ISSUE THREAD

**Issue by a18jonkl** [HGustavs/LenaSYS#9685]
<a href="https://gyazo.com/c4b8343d406d3ed47df1fe0c2b06f764"><img src="https://i.gyazo.com/c4b8343d406d3ed47df1fe0c2b06f764.png" alt="Image from Gyazo" width="1817"/></a>
<a href="https://gyazo.com/e67d3de606597a6169ac8a8b5d6e92c9"><img src="https://i.gyazo.com/e67d3de606597a6169ac8a8b5d6e92c9.png" alt="Image from Gyazo" width="1868"/></a>

**Comment by a18kaswi** [comment]
@a18jonkl @RobinHellgren can you elaborate on conclusions from your research into the problem yesterday?

**Comment by a18jonkl** [comment]
When trying to convert MySQL syntax to Postgres syntax some features as ‘on update CURRENT_TIMESTAMP’ didn't come built-in for Postgres. This error comes after trying to implement the function and trigger to act as MySQL ‘on update CURRENT_TIMESTAMP’’ function.
https://stackoverflow.com/questions/1035980/update-timestamp-when-row-is-updated-in-postgresql

It looks like a foreign key problem(and it is) but the root problem is that all the code after the trigger is unrecognized by the program and that is what causes the problem. (tables and inserts) 

Syntax for creating function/trigger for Postgres v10
https://www.postgresql.org/docs/10/sql-createtrigger.html
https://www.postgresql.org/docs/10/sql-createfunction.html
https://www.postgresql.org/docs/10/plpgsql-trigger.html
