### ISSUE TITLE
Page Information: Replace substr with Json_extract to retrieve courseid 

### ISSUE THREAD

**Issue by b17carbr** [HGustavs/LenaSYS#9693]
Currently substr is being used to retrieve the courseid from refer, this is unintuitive and can now be replace with:
```php
Json_extract(URLParams, '$.cid') AS courseid  
```

The current implementation with substr:

![Screenshot 2020-05-26 at 13 25 34](https://user-images.githubusercontent.com/62876614/82895380-6e034a00-9f54-11ea-842c-3a71b0a721b6.png)

**Comment by d17marle** [comment]
Was already done before but merged into the wrong weekly branch, now it is implemented in the correct one!
