### ISSUE TITLE
Random clipping dugga problem with layout.

### ISSUE THREAD

**Issue by b18veran** [HGustavs/LenaSYS#9732]
Random clipping dugga has a problem with the layout. 
- See IMG 1 it is a white line under the image in "Målbild". 
- See IMG 2 when adding more than 17 options the container "Ritverktyg" will be longer. Until you add more than 19 the it will get a scroll function. 
<img width="1280" alt="Screenshot 2020-05-27 at 08 43 43" src="https://user-images.githubusercontent.com/49142649/82986591-685e4080-9ff6-11ea-94ed-c09c3ddc1587.png">
IMG 1
<img width="1280" alt="Screenshot 2020-05-27 at 08 44 14" src="https://user-images.githubusercontent.com/49142649/82986597-6a280400-9ff6-11ea-8472-2f38859161c6.png">
IMG 2

**Comment by a18viksa** [comment]
Closing issue after merge to master.
