### ISSUE TITLE
In Access Editor, Reset Password buttons are styled with id's instead of class and new-user styling isn't applied

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9735]
One shouldn't use the same id for several elements. It will still render properly but it is not considered valid HTML. 

The id='reset-pw' should be changed to a class instead. 

As for the new-user styling this should be applied when to users considered new, this is done in accessed.js.

The new-user styling is also expecting the button to be an input, since the Access Editor now uses div's for most things (improves performance when many students are in a course) this should be changed to div.

These problems seemed to have begun when https://github.com/HGustavs/LenaSYS/pull/8737 was merged. As far as I can tell the issues presented here should be the last problems coming from that merge.

**Comment by a18viksa** [comment]
Closing issue after merge to master.
