### ISSUE TITLE
In Result Editor, for group assignments, when grading a student in group "None" (= not in a group) all other students who are also not in a group will be graded 

### ISSUE THREAD

**Issue by c14jonfr** [HGustavs/LenaSYS#9752]
Currently the group None is handled like any other group, meaning that users who are in the group None are all considered to be part of the same group, when in reality they should be considered to be in no group at all.

Should be a simple fix, just check (in resultedservice.php is my guess) whether the group is "None" or not. If the group is "None", the other students in that "group" should not be graded.

**Comment by c14jonfr** [comment]
Just to make things a bit more clear:
There is a comment claiming it will work as expected for the 'None'-group (= not grading members of the group if the group is 'None"), this is NOT TRUE. It most likely was when the comment was written but as other changes were implemented something changed and as far as I can tell it now works as described in this issue (which is not how it should work).

Hopefully changing the if statement in this screenshot from resultedservice.php (line 259 at time of screenshot) should be enough to fix this.
![image](https://user-images.githubusercontent.com/49141758/83174291-786f4080-a11a-11ea-9258-d2095fc387ab.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
