### ISSUE TITLE
Validation inside "Create user"-dialog is incomplete

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#9753]
Inside the "Create user"-dialog the level of validation of different attributes differs vastly, and more work needs to be done.

The following attributes are properly validated:
- SSN (see #8935 for details)
- Email (see #9133 for details)

The following attributes might need more work:
- First name
- Last name
- PID

The following attributes have no validation whatsoever at the moment:
- CID
- Ny (???)
- Term

![Skärmavbild 2020-05-27 kl  14 15 59](https://user-images.githubusercontent.com/62876260/83018419-8f803680-a025-11ea-9a06-f3c1d5781ac1.png)
Example of SSN validation message. In this case the 29th of February doesn't exist since 1998 wasn't a leap year.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
