### ISSUE TITLE
Page Information: Nothing appears when there is no values from the database.

### ISSUE THREAD

**Issue by b18gussv** [HGustavs/LenaSYS#9759]
When for example choosing profile I am met with an empty page.
![bild](https://user-images.githubusercontent.com/49142342/83118975-61573100-a0cf-11ea-9611-3e31cfb4ecf5.png)

**Comment by c20adael** [comment]
The pull request was closed without being implemented. Check if the problem still persists.

**Comment by a20behta** [comment]
analytings is removed thereby issue is no longer relevant
