### ISSUE TITLE
Page Information: remove duplicates in dropdown

### ISSUE THREAD

**Issue by b17carbr** [HGustavs/LenaSYS#9760]
Duplicates of profile are present in the dropdown, remove the one with the incorrect value pointing to accessed. 

Dropdown currently:
![Screenshot 2020-05-28 at 10 41 48](https://user-images.githubusercontent.com/62876614/83119319-daef1f00-a0cf-11ea-8455-7ed63a67b34d.png)

Values assigned to dropdown choices: 
![Screenshot 2020-05-28 at 10 43 57](https://user-images.githubusercontent.com/62876614/83119934-a2037a00-a0d0-11ea-90eb-a10ccf3715ab.png)

**Comment by c20adael** [comment]
Analytic has been removed
