### ISSUE TITLE
The button row on the receipt needs a margin to the bottom of the window

### ISSUE THREAD

**Issue by Maxel89** [HGustavs/LenaSYS#9763]
The title really says it all
![image](https://user-images.githubusercontent.com/9322253/83140685-c1a99b00-a0ee-11ea-86aa-f442a05aa8a6.png)

**Comment by a20caros** [comment]
@c20adael

**Comment by a20caros** [comment]
Have looked in the code and the issue should be closed

**Comment by a20behta** [comment]
nicely done
