### ISSUE TITLE
Export popup window does not stay at the same place when you scroll horizontally.

### ISSUE THREAD

**Issue by b18fella** [HGustavs/LenaSYS#9764]
The first screenshot displays where the window is supposed to be at all times.
![correctExport](https://user-images.githubusercontent.com/49142651/83141563-34ffdc80-a0f0-11ea-86be-8bd04cccaaca.PNG)

But if you scroll horizontally to the right, the window moves to the left (See screenshot 2). Instead of this, the window should stay on the same place on the screen at all times as seen on screenshot 1.
![notCorrectExport](https://user-images.githubusercontent.com/49142651/83141575-37facd00-a0f0-11ea-9191-1628db34ea66.PNG)

This should be solved easily by using the same function that makes the export buttons stay in the same place.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
