### ISSUE TITLE
Unsure if the SSN check can handle "samordningsnummer"

### ISSUE THREAD

**Issue by b18alegu** [HGustavs/LenaSYS#9765]
Currently the check of the SSN in the "Create user"-dialog in the Access editor can verify Swedish personal ID-numbers correctly. I'm unsure if it can handle "samordningsnummer" as well though. This should be investigated thoroughly and if needed, implemented.

**Comment by a18willi** [comment]
Through testing we've found that it isn't possible to use a "samordningsnummer", so we'll be working on a fix.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
