### ISSUE TITLE
[live_version] After giving feedback in feedback view, "Feedback" button is not clickable.

### ISSUE THREAD

**Issue by andras-marki** [HGustavs/LenaSYS#9767]
In grading view, when giving feedback on a student submission, when clicking on the button "Feedback" unted "teacher feedback", after you write a feedback the "Feedback" button is not clickable. You need to exit grading view, click on grading again, then the teacher feedback is shown to the right (also an issue) and Feedback is working.

So there is an easy workaround, but it is still annoying.

This is an issue with the live version.

**Comment by HGustavs** [comment]
Not relevant since feedback is handled by canvas

**Comment by c20adael** [comment]
Customer states not relevant. closing this issue.
