### ISSUE TITLE
Contribution National Holidays - barchart

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9768]
National swedish holidays should be displayed prominently in the contribution view.

This way it is possible to see if work has reduced statistically or not during a week.

**Comment by HGustavs** [comment]
A week with 4 working days should count less than a week with 5 working days.

**Comment by a19anjst** [comment]
Create a list of red days to use. Summer and christmas obviously not included. If a day is a red day make the background light pink. In the text that names each week add red day dates to the relevant weeks.
