### ISSUE TITLE
Remove all personal information from hand-ins

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9778]
We need to support hashing of hand-in id including randomized hashes for each hand-in

**Comment by a19gusba** [comment]
Unclear to us students should create functions related to generating and reversing the hashes, where should the hash be used. How does the hand-in id work? Is it provided to us to be used in the hash or should the id be the result of the hash.

**Comment by HGustavs** [comment]
Each time a person presses "save" a new random number is created. This number is hashed so the number can not easily be deduced from the string.

This hash and a random password for this specific assignment hand-in can then be used to return to this exact assignment.

It is this url to this hash that the student hanss in to canvas.

There is thus no way to deduce which student made which hand-in outside of canvas.

**Comment by HGustavs** [comment]
The process is as follows:

1. The student thus goes to an assignment, finishes the assignment, when the student presses "save" the random hash (for example FCE45F37) is generated together with a password the student can use to return to that specific hand-in
2. The student then makes note of the password and hash for that assignment hand-in. 
3. The student then paste-s for example FCE45F37 which the teacher can then asess and mark inside of the canvas installation.

This way the students do not log in to lenasys, and no personal information that can be traced back to the studnet is stored in lenasys. But the teacher can then review the assignment in the normal fashion inside of the canvas installation
