### ISSUE TITLE
File lists for uploaded zip-files

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9782]
If we upload a zip-file, the short-linked preview should show the name of the file and the link but also a directory listing of the zip file.

This way a teacher can see if for example the correct type of files have been uploaded without having to decompress zip file.

**Comment by a13zanal** [comment]
We're working on understanding how zip reading works in JavaScript and how to implement this to dugga.js and resulted.js. We have also asked a question to customer for more clarification _"Should the zip file be able to preview directly in lenasys before downloading? You can do this with Zip.reader but this seems to be a separate library that needs to be implemented. Is this what you are looking for in this issue?"_.

**Comment by b19ponka** [comment]
Since the database structure is not yet defined, going from student ID to hash, we decided to put this issue on hold
