### ISSUE TITLE
Remove assignment pane from course contents

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9783]
As we are moving towards closer integration with canvas we need to support iframe linking of the course pages.

The assignment pane is thus not needed and can be removed from the course view.

<img width="1022" alt="Screenshot 2021-02-24 at 20 39 06 copy" src="https://user-images.githubusercontent.com/6978801/109057436-03995900-76e2-11eb-8bfc-c8177659b081.png">

**Comment by HGustavs** [comment]
Also remove any related css

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
