### ISSUE TITLE
Local storage item for current assignment variant

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9784]
In order to getting the same variant when re-visiting the dugga we need to keep track of the previously used variant when re-visiting the assignment page.

**Comment by HGustavs** [comment]
Since many assignments have different variants, we should try to give the same variant to the same person if that person re-visits the page without saving the assignment.

**Comment by b18jacha** [comment]
Do you mean that in e.g. "Biträkningsdugga 1" the browser should remember which choices the user clicked on through local storage?

**Comment by HGustavs** [comment]
No, not what user clicked, that is taken care of by logging back in to the same assignment after saving

**Comment by HGustavs** [comment]
When the page is called different users get different variants e.g.  representing #fc8 or #888 or #cf8 for example

if we visit the assignment for the first time we get the assignment of turning #fc8 to bits

if we return to the page without saving we should also get #fc8

But if we remove the session variable that stores the allotted assignment number (all personal information will be culled and we will not store anything useful in sessions for students) we need to use local storage to retrieve the same assignment #fc8 if we refresh the page.

**Comment by HGustavs** [comment]
Otherwise we can refresh the assignment until we get a sufficiently simple assignment if there is a perceived difference in difficulty bwtween variants.
