### ISSUE TITLE
Robust change detection in diagram editor

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9787]
Since the data for a diagram contains the full data for (most) previous versions of the diagram, we can decide how often to make a new version of the diagram.

This has been discussed in several previous issues.

[
{version 1 diagram data},
{version 2 diagram data},
{version 3 diagram data}
]

We want to store the current diagram at the last item in the dataset (in this case version 3), which is the diagram shown on screen.

After a number of changes e.g. making an attribute, change name of attribute, move attribute we can decide to make a new version, so that any future updates then happen in {version 4 diagram data} which at first is a copy of {version 3 diagram data}

...

**Comment by a19nikbo** [comment]
I've got some questions:

Is this "new version" supposed to be created by the user or happen automatically after a specified number of changes?

Also, what is the purpose of it? Should the user be able to go back to previous versions? Is it like a manual or auto-save feature with backups?

If we implement an undo functionality, should we allow the user to go back to older versions, and if so, should going back to an older version with undo also undo the new version? E.g. if version 4 is created and the user goes back to a step before version 4 was created, should version 4 be deleted?

**Comment by a19hammi** [comment]
I've discussed this a bit with some of the others and we would like to mention the saving system for our diagram. If we want the state-storage to not be volatile and lost when re-opening the diagram we need to store the state changes when pressing save. This means that if we store BOTH the state system AND the final state we will essentially have two times the data which could stack up pretty fast with a lot of students/teachers. Our solution would be to ONLY save the states and not the final calculated state to reduce redundancy data. Of course, this means that loading time for **opening** a diagram could be a bit higher, depending on the amount of changes and states stored, which could introduce some more loading time. _(We could use a maximum backlog to limit this?)_.

I would like to hear your take on this @HGustavs before I start working on this!

**Comment by a19hammi** [comment]
I'm considering storing each state along something along the line:

    changes = [
        ({ id='ABCDEFG', Type=Types.Element }), ({ moved_x=250, resized_height=-20, changed_name="hello world" }),
        ({ id='12345678', Type=Types.Edge }), ({ created_between=['ABCDEFG', 'HIJKLMN'] })
    ]

**Comment by a19hammi** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/81571224/114844913-8c2ba000-9ddb-11eb-80bd-2b5307672c56.png)

**Comment by a19hammi** [comment]
@a19karwa Varför mergar du in i min branch medan den arbetas på????

**Comment by a19nikbo** [comment]
Fixed
