### ISSUE TITLE
Replacing the diagram module with new diagram core

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9788]
A new diagram core has been created in 

https://github.com/HGustavs/DiagramEngine/

This new svg and html based engine should completely replace the canvas-based engine in the previous diagram module

**Comment by a19hammi** [comment]
Committed change to [Group3-2021-#9788](https://github.com/HGustavs/LenaSYS/tree/Group3-2021-%239788)

**Comment by a19nikbo** [comment]
This issue is solved, closing now
