### ISSUE TITLE
Creating diagram-dugga

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9789]
A dugga needs to be created for submitting diagram duggas.

**Comment by HGustavs** [comment]
A collapsible assignment text, for example "Create a diagram with the following specification" ... followed by abstruse long-winded description of diagram contents.

This should be followed by a collapsible diagram drawing area ... and the standard save button.

**Comment by HGustavs** [comment]
The overarching goal is to be able to support viewing and submitting ER-diagram duggas at the end of the course 2021

**Comment by a19hammi** [comment]
fixed in #10324
