### ISSUE TITLE
Code View: Incorrect HTML in Edit Example box

### ISSUE THREAD

**Issue by a13alfbe** [HGustavs/LenaSYS#979]
![untitled](https://cloud.githubusercontent.com/assets/11715493/7226008/bbf02940-e744-11e4-972a-5aedf4662db4.png)

Colspan is not a proper HTML tag. It is an attribute that is part of the \<td> tag

**Comment by a13jansa** [comment]
I made those changes
left col = <td colspan="1">
right col = <td colspan="2">

**Comment by HGustavs** [comment]
Can we close this issue soon?
