### ISSUE TITLE
Center / Left alignment of text in diagram

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9792]
If text is longer than the space inside the symbol we currently have clipping of the text

The issue with this is that we clip both the beginning and the end of the text.

"Procurement" would read "curem" with the rest of the text clipped away.

We should use centering if the text is short so that "Owns" is centerd in the middle of the attribute or relationship symbol for example.

But if the left edge of the text is to the left of the left edge of the symbol the text should remain to the left.

something like place left edge of text half of the width of the text to the left of the center of the symbol, but if that resulting value is less than the left of the symbol we should assign the position of the left of the text to the left edge of the symbol.

The result is centering until the beginning of the text is occluded, and after that we align the left edge of the text to the left edge of the symbol.

The key line drawing function has a function for the estimation of text length.

**Comment by HGustavs** [comment]
This can partially be done through code BUT I do think we need text measurement.

In cavas we have text measurement, but I am not aware of any way to do this when using SVG without some advanced trickery.

My approach is to make a reasonably competent measuring functionality.... that is mostly guessing correctly. It only works for widths relative to the text size and with this specific font.

https://github.com/HGustavs/DiagramEngine/commit/a5022cf

**Comment by a19nikbo** [comment]
Fixed
