### ISSUE TITLE
Making Access editor Teacher Only

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9794]
The access editor should remove columns for personal numbers an so on and only contain information relevant for teachers

**Comment by b19alest** [comment]
What I can see, personal numbers are already hidden. Is there more information that should be hidden for teachers?

**Comment by HGustavs** [comment]
We want all student information to be removed not only the ssn.

Hiding ssn was not enough to satisfy the internal policy so we need to purge all student information and making the access editor teacher-only.

**Comment by HGustavs** [comment]
Im thinking the users table should still remain but only contain teachers (and for teachers, study programmes, ssn etc. are not relevant)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
