### ISSUE TITLE
Remove color from bulbs in section editor

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9797]
Until more complete integration with canvas has been achieved we need to remove the bulb colors from the section editor.

All bulbs should remain gray even if a student has submitted an assignment since there is no way for lenasys to know if the user has submitted an assignment or not.

Also remove any related parts of the css in order to simplify the css file.

**Comment by a19danla** [comment]
Should we keep the if-statements for later use or remove them?

**Comment by HGustavs** [comment]
I would say remove, since the data is no longer relevant.

**Comment by a20chrjo** [comment]
Sub-issues re finished and closed
