### ISSUE TITLE
Redirection : Url to student assignment

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#9804]
We need a short url to student assignment e.g. dugga.his.se/sh/2fc6e1 that will redirect to saved assignment submission

part of bigger issue #9798

**Comment by a19kevkh** [comment]
Created a unique password generator for 7 characters.
Also created an URL shortener based on the "real" URL. If URL is in the database, that means a shortened URL already exists.

**Comment by a16erilj** [comment]
We have created a solution that relies on a database that have yet been implemented. This database (passwordURL) are currently under development in another issue #9790.
