### ISSUE TITLE
Assignment redirection to course

### ISSUE THREAD

**Issue by a19karwa** [HGustavs/LenaSYS#9805]
Assignment redirection to specific assignment in course e.g. /sh/Databaskonstruktion?ass=MVC in order to arrive to https://dugga.iit.his.se/DuggaSys/showDugga.php?did=1326&cid=4&coursevers=82452&moment=9241&segment=9218&highscoremode=0&comment=null&deadline=2020-12-16%2017:00:00 or https://dugga.iit.his.se/DuggaSys/showDugga.php?did=1326&cid=4&coursevers=82452&moment=9241 with some of the un-needed stuff stripped from the URL.

part of bigger issue [#9798](url)

**Comment by HGustavs** [comment]
I think the highscore mode, comment and deadlines do not need to be in the url?

It seems really strange that the deadline etc is part of the url, is the deadline even used?

Perhaps making a separate issue for the stripping of this from the url when clicking in section editor?

**Comment by a19rebsa** [comment]
Created a separate issue for stripping the url from unnecessary content in issue #9821

**Comment by a19simma** [comment]
Having issues with how the redirect works in /DuggaSYS/sh/index.php . There's an example with header(Location : ......) For Databaskonstruktion but we don't understand how this is triggered? Getting a 404 when trying.
![image](https://user-images.githubusercontent.com/81557282/113699125-78928200-96d5-11eb-967d-1ec8546b9189.png)

**Comment by a19simma** [comment]
We're working on understanding the database and how to retrieve values from the mysql. There's an early commit for some hardcoded redirects for now.
