### ISSUE TITLE
Redirection : Course name to newest version of course

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#9806]
currently the link looks like this https://dugga.iit.his.se/DuggaSys/sectioned.php?courseid=4&coursename=Databaskonstruktion&coursevers=82452 ... the URL shortener should redirect us to that link from /sh/Databaskonstruktion ... when we change from 2021 version of to 2022 version we will arrive at the correct location ... this is so that the link in canvas will not need to be updated

Referencing the second point of this issue #9798

**Comment by HGustavs** [comment]
Im thinking even a partial match of the course name should do... as long as it is unique.

for example XML should be sufficient for XML API as no other course has that combination in the title

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
