### ISSUE TITLE
Generate URL and unique Password to assignment upon submission

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#9807]
When a student submits an assignment by pressing the save button we should generate a URL for the specific assignment along with a password tied to the URL. This should be saved to the database instead of any personal information so that a student can return to the assignment through the URL and resubmit with the password. This issue relates to issue #9790.

**Comment by a19kevkh** [comment]
Created a unique password generator for 7 characters.
Also created an URL shortener based on the "real" URL. If URL is in the database, that means a shortened URL already exists.
