### ISSUE TITLE
Options sidebar overlaps the top panel bar

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9812]
The options sidebar needs to be confined to the height of the diagram container. It currently goes above that and blocks a button on the top panel bar.

**Comment by HGustavs** [comment]
Screenshot please that can be used for testing and for comparison

**Comment by a19chrel** [comment]
**Screenshot of the problem:**
![SideBarLoginButton](https://user-images.githubusercontent.com/62853826/113283169-3093e980-92e8-11eb-8e20-ef660a2251bb.PNG)

**Comment by HGustavs** [comment]
When using in canvas we will not have a top menu bar anyhow, but.... when used by teachers we need it so it needs to be taken into account for that case, when we are not linked through canvas.

**Comment by HGustavs** [comment]
Perhaps a good idea to talk to the other groups to figure out how this is handled in their views I suggest using a standardized approach across the different duggas/pages
