### ISSUE TITLE
The diagram entities overlaps the menu bar

### ISSUE THREAD

**Issue by a19aleda** [HGustavs/LenaSYS#9813]
The entity boxes inside the diagram editor overlaps ontop the menu bar. The entities should probably be below / under the menu bar.
![Skärmklipp](https://user-images.githubusercontent.com/81557207/113281647-24a72800-92e6-11eb-9fa0-1749d37cc5ea.PNG)

**Comment by HGustavs** [comment]
screenshot please so we can judge the progress and also for testing

**Comment by a19nikbo** [comment]
Works correctly now and has been merged
