### ISSUE TITLE
Be able to create new elements and add them to the canvas

### ISSUE THREAD

**Issue by a19aleda** [HGustavs/LenaSYS#9818]
In the current version there is no way to create new elements and add them to the canvas. This issue should maybe be broken down in  smaller sections.

**Comment by HGustavs** [comment]
A simpler version of last years version plz.

I suggest a similar or identical menu to that of the old system, sort of like the tool bar in illustrator for example

<img width="36" alt="toolbar" src="https://user-images.githubusercontent.com/6978801/113291579-84f09680-92f3-11eb-95bc-d8d288b799ed.png">

Then we are in "mouse mode" or "entity mode" "relation mode" "attribute mode" ...

Every click on the canvas should create one object with the default properties for the relevant mode.

**Comment by HGustavs** [comment]
In addition to this we need a "line mode" which creates connectors between objects

In that mode I suggest one of the following: 

* starting a "rubber band" line from the center of the object below the mouse when the mouse is pressed down, and if another object is below the mouse when we release the mouse button we create a link to that object.
* we click on an object, this starts the rubber banding from the center of the object below the mouse and when we click again on another object the line object is created

Unclear which of the two feels most natural.

**Comment by a19nikbo** [comment]
We can now add entities, attributes and relations. Edges (lines) are part of a separate issue.
