### ISSUE TITLE
Template literals in Diagram_IOHandler.js

### ISSUE THREAD

**Issue by a19karwa** [HGustavs/LenaSYS#9826]
Change into template literals in Diagram_IOHandler.js
For example:
In line 85:
![image](https://user-images.githubusercontent.com/81557429/113305626-85912900-9303-11eb-9c5b-4f1ec6fc11be.png)

Write instead --> 
![image](https://user-images.githubusercontent.com/81557429/113305904-ca1cc480-9303-11eb-9ff8-d300c1257181.png)

**Comment by HGustavs** [comment]
This is on the shorter side, if the string is shorter than one line and can be easily readable it is better to not modify the line.
I would say that this is on the edge of what we are looking for, also mainly for markup, primarily not for other strings... so this is for several reasons not the best example.

Any shorter than this, a string should not be modified, as the history for that line is lost when modified.
