### ISSUE TITLE
Diagram flips out when a node is on top of another

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9830]
More specifically, if you drag a relationship/attribute node behind another node two things can happen as far as I know:
    - If you try to move any of the "stacked" nodes, you will grab it but it will have a pretty significant offset from the 
      cursor
    - If you move another node, both of the "stacked" nodes will change positions
    
The first one doesn't seem to happen for entities for some reason, but the second one does. The issue also only occurs if you move a node with a lower z-index "behind" another node, not if you move one in front of another.

![diagram_showcase](https://user-images.githubusercontent.com/81541557/113397441-562efa80-939d-11eb-9f97-4b23b44f5827.gif)

**Comment by a19hammi** [comment]
Shouldn't this issue be closed?

**Comment by a19nikbo** [comment]
Issue fixed
