### ISSUE TITLE
Section editor side bar moving swimlanes to top and bug fix swim lanes

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9832]
When integrating with canvas we lack screen width for the sidebar... also we do not know to what extent assignments have been handed in.

<img width="1000" alt="Screenshot 2021-04-04 at 00 39 52" src="https://user-images.githubusercontent.com/6978801/113493291-5b479300-94de-11eb-958b-f27d997743f3.png">

However the swimlane display at the bottom of the sidebar is still relevant, as it does not show personal information, but rather the current week and assignment deadlines within course.

I would like to see a proposal for a re-designed swimlade display that is suitable for the top of the screen, rather than as a side bar.

I would prefer that we use the full width of the area rather than the limited width of the side bar.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
