### ISSUE TITLE
Section editor swimlane modernization

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9833]
<img width="331" alt="Screenshot 2021-04-04 at 00 44 54" src="https://user-images.githubusercontent.com/6978801/113493376-0a846a00-94df-11eb-915d-c7e1e3853f81.png">

...I do believe that the swim lanes functionality does not work for courses that are longer than 10 weeks (for example the final year project).....

Also if the deadline has not yet been updated for the current year it would be nice if we could still have a "guesstimate" for the deadlines transposed to the current year in the swimlane display, and some kind of display using coloring or other graphics indicating that the deadline has not been updated for the current year yet...

**Comment by HGustavs** [comment]
This would make the swimlane functionality more useful when integrated with canvas.

**Comment by a20chrjo** [comment]
Both sub-issues are complete
