### ISSUE TITLE
Removing access category and group assignment from access editor

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9834]
As students will not appear in the database, only teachers, this means that we can remove the "'access" and "group" columns from the access editor.

Furthermore, in this issue and also in a file in the repository, document which columns and which tables that need to be removed from the database to implement this change.

Due to the no refactoring rule, we can probably not physically remove these columns without disrupting functionality in the sort term, but we can document this in a clear and concise manner for future use.

**Comment by a20chrjo** [comment]
Approved and merged by 20chrjo
