### ISSUE TITLE
Rulers in diagram editor

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9835]
I would really like some photoshop-style rulers in the diagram editor

Including a colored line representing the position of the pointer

<img width="1075" alt="Screenshot 2021-04-05 at 15 51 47" src="https://user-images.githubusercontent.com/6978801/113581606-a15c3e00-9627-11eb-8e3d-66e476820f2d.png">

**Comment by HGustavs** [comment]
Screenshot is in dark mode, but we are working with light colors in the current version of the diagram editor.

**Comment by a19nikbo** [comment]
Fixed
