### ISSUE TITLE
Contribution tool clock

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9837]
I feel that the clock functionality is not very controllable.

The display is very nice in general.

Unclear what the colors mean, and I would really like to see commits / issues / etc as separate areas under the graph

Unclear what the gradient inside the reactangle denotes if anything?

Also it seems that we can not give course weeks and that there strangely enough is only one date setting.

I would prefer to choose course weeks that both start and end the interval (1-6 or 1-10 or 5-10 for example).

**Comment by HGustavs** [comment]
<img width="555" alt="Screenshot 2021-04-05 at 16 13 03" src="https://user-images.githubusercontent.com/6978801/113583591-1b8dc200-962a-11eb-8e70-b743ed3ba844.png">

**Comment by a18willi** [comment]
@HGustavs The colors change depending on if the square represents a comment or an event, currently purple is for comment and red is for event. The gradient denotes that the square represents both comments and events.

Changing the datesettings to be able to choose two courseweeks are currently being worked on.
