### ISSUE TITLE
Edge creation in diagram

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9838]
An edge creation mode that should be selectable from options menu (the vertical menu).
We click on an object, this starts the rubber banding from the center of the object to the mouse and when we click again on another object the edge object is created. If the right mouse button is clicked during this mode is cancels the operation.

This is part of the bigger issue #9818

**Comment by HGustavs** [comment]
The general functionality of how it works in the old lenasys is fine IMHO

<img width="722" alt="Screenshot 2021-04-06 at 13 26 52" src="https://user-images.githubusercontent.com/6978801/113704455-6e27b680-96dc-11eb-8962-6177b21fefc0.png">

**Comment by b19phier** [comment]
En ny issue som behöver hanteras är  alltså att edgen följer muspekaren medans man drar från ena valda entiteten till den andra medans man skapar en edge.

**Comment by a19nikbo** [comment]
Fixed
