### ISSUE TITLE
Empty files still present in the master branch.

### ISSUE THREAD

**Issue by a12oskri** [HGustavs/LenaSYS#984]
The empty files #515, #563 and 566 is still present in the master branch and really should be deleted as they have no function at all. These files should really be deleted in conjunction with the weekly merge.

**Comment by c12jenek** [comment]
Since the master branch at the moment says Marcus was the last to edit 13 days ago it's likely the master branch has been reverted, check if the files are present in your weekly branch.

**Comment by a12oskri** [comment]
Fixed, master was mysteriously rollbacked.
