### ISSUE TITLE
Refined mutli-selection of elements

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#9845]
Currently the multi-selection of elements is a very empty husk.
Need a better multi-selection system that allows holding CTRL to select more than one element at a time in a fluid and smooth way.

**Comment by HGustavs** [comment]
When holding control we skip over clearing the selected object array and just add the clicked object to the array.

We also want a way to multi-select using a selection box which clears the selection array and adds any over-lapping objects to the array using a bounding-box test of some kind.

https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection

The non-trivial usability question is how we detect the difference between scrolling, and box selection ... I suggest having a button in the toolbar for box-selection.

**Comment by HGustavs** [comment]
I am thinking that we in some cases skip over the context=[]; line... depending on whether or not we have control pressed... and we could store this in a global variable if we wanted to ... or as a parameter to the function.

```
//-------------------------------------------------------------------------------------------------
// updateselection - Update context according to selection parameters or clicked element
//-------------------------------------------------------------------------------------------------

function updateSelection(ctxelement,x,y)
{
		// Clear list of selected elements
		context=[];
		
		if(ctxelement!=null){
				// if we pass a context object e.g. we clicked in object
				context.push(ctxelement);
		}else if(typeof x != "undefined" && typeof y != "undefined"){
				// Or if x and y are both defined
		}
}
```
