### ISSUE TITLE
Box-selection tool for selecting multiple elements

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9848]
We can currently select multiple elements in the diagram to drag/manipulate several nodes at a time by clicking them. Another issue is about only selecting multiple elements when holding down Ctrl, but we also need to be able to select through a box-select tool in the options side panel. We want to have a clickable button the the options panel, and when clicked we go into box selection mode, and if the button is clicked again we go back to normal mode.

For example like when selecting multiple files in the Windows Explorer.
![example](https://user-images.githubusercontent.com/81541557/113712108-00808800-96e6-11eb-81f1-64e86df4f03c.png)

For more information see #9845

**Comment by HGustavs** [comment]
<img width="436" alt="Screenshot 2021-04-06 at 15 06 43" src="https://user-images.githubusercontent.com/6978801/113715618-fd879680-96e9-11eb-938c-5afc08afe5dc.png">

Slightly more appropriate screenshot

**Comment by a19nikbo** [comment]
Fixed
