### ISSUE TITLE
deltaExceeded only set for positive values

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#9849]
The variable indicating a long mouse movement only account for deltaX and deltaY being greater or equal to maxDeltaBeforeExceeded, but not less or equal to -maxDeltaBeforeExceeded.

**Comment by HGustavs** [comment]
Absolute value?

What does the specific code that we thing is wrong, look like?

**Comment by a19hammi** [comment]
Group3 main branch, [diagram.js](https://github.com/HGustavs/LenaSYS/blob/Group3-2021-main/DuggaSys/diagram.js).

    if (mb == 1)
    {
        // Compute new scroll position
        deltaX = startX - event.clientX;
        deltaY = startY - event.clientY;
        scrollx = sscrollx - Math.round(deltaX * zoomfact);
        scrolly = sscrolly - Math.round(deltaY * zoomfact);

        // Update scroll position
        updatepos(null, null);

        // Remember that mouse has moved out of starting bounds
        if (deltaX >= maxDeltaBeforeExceeded || deltaY >= maxDeltaBeforeExceeded)
        {
            deltaExceeded = true;
        }
    }
    else if (mb == 8)
    {
        // Moving object
        movingObject = true;
        deltaX = startX - event.clientX;
        deltaY = startY - event.clientY;

        // We update position of connected objects
        updatepos(deltaX, deltaY);

        // Remember that mouse has moved out of starting bounds
        if (deltaX >= maxDeltaBeforeExceeded || deltaY >= maxDeltaBeforeExceeded)
        {
            deltaExceeded = true;
        }
    }

Specifically the condition `(deltaX >= maxDeltaBeforeExceeded || deltaY >= maxDeltaBeforeExceeded)`.

**Comment by HGustavs** [comment]
This is not a super-simple thing.

I would use euclidian distance e.g. Math.sqrt((dx*dx)+(dy*dy))>maxDeltaBeforeExceeded ....

and I would call the constant something shorter.

moveTreshold 

for example

...

Furthermore there are multiple modes here and usability issues....

Click and release inside object - is this select or move of object?
Click and release slightly outside object but release inside an object - is this select or move or small scroll or even box selection?

So if we click down inside an object it should always default to object selection?
If we click down in the background between object should it always default to scroll?

What if we are in box-selection mode?

This is complex, not necessarily a large number of lines of code, but complex interaction-wise.

Another issue is setting the variable deltaExceeeded ... should we not move into some mode there for example mb=4 instead  this way we have a separate state above the movement states in the mb variable??

Or am I missing something?

**Comment by a19hammi** [comment]
This code was significantly modified in last pull-request. It should still be modified to an absolute value though!
mb has been replaced with a new enum system instead.

**Comment by a19hammi** [comment]
Solved in https://github.com/HGustavs/LenaSYS/commit/6145e78865ef3c3db1acdb42168e139a628545da.
Can be closed @a19nikbo @a19karwa 

https://github.com/HGustavs/LenaSYS/blob/4dbd977d9a425779289f95752fee982e2f09f8b7/DuggaSys/diagram.js#L501-L517

**Comment by a19nikbo** [comment]
Fixed in another issue
