### ISSUE TITLE
Save assignment password and assignment URL to database

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#9859]
We need to bind the generated password to the database so that the log in dialog can compare the input. I was considering that together with a generated hash we then find and display the submission data. 

In addition we need to save the shortened URL to allow the redirection function to work.

**Comment by HGustavs** [comment]
Not student password ... assignment password. Each assignment hand-in has a unique password.

If you through some nefarious means, get hold of the password you can only see the contents of one individual hand-in and not the complete history of that student.

**Comment by a19frebo** [comment]
We are thinking of creating a new database table for this issue. But how should this new table be created? Should we create it in "init_db.sql", when we do this we have to reinstall the entire database to get our new table included in the system. This means that everyone that uses this system has to reinstall the database aswell right?

Another solution that we have thought about is to create the table during runtime by using "CREATE TABLE IF NOT EXISTS". But is this the correct way of creating this table?

**Comment by a19kevkh** [comment]
Added columns hash and password to the table userAnswer. The password and hash are now generated and stored in the table for new saved dugga.
