### ISSUE TITLE
Make bulb gray in navbar

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#9862]
Currently, the bulb in the navbar is transparent as we do not have access to dugga.js and therefore can't make changes to the bulb. This needs to be resolved at a later stage. 
![dugga](https://user-images.githubusercontent.com/81559946/113833972-8eae4a00-978a-11eb-8168-996db6fd3438.png)

**Comment by a19isada** [comment]
This is a subissue of issue#9797

**Comment by a19danla** [comment]
Am i right to assume that there should be a standard message or no message in the navbar since canvas can't detect if the assignment has been done or not. If there should be a message, any input on what it should say?

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
