### ISSUE TITLE
Remove color from bulbs in section editor

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#9863]
Until more complete integration with canvas has been achieved we need to remove the bulb colors from the section editor.

All bulbs should remain gray even if a student has submitted an assignment since there is no way for lenasys to know if the user has submitted an assignment or not.

Also remove any related parts of the css in order to simplify the css file.

The navbar lights should not be changed in this issue. It should remain as in the picture below since group 2 does not have access to the dugga.js file at this time. 
This is a subissue of #9797 

![dugga](https://user-images.githubusercontent.com/81559946/113834796-873b7080-978b-11eb-939e-08f2b2c7367f.png)

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
