### ISSUE TITLE
Change name of selected element in side panel

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9872]
We need to add a way to change the name of an element. As you can see below, the preferred method of doing this is by a properties section in the options side panel. For this specific issue, it is enough to add an input field that can be used to change the name property of an element. See below for more information.

**Comment by HGustavs** [comment]
I would like all of this to happen in the sidebar and that the dialog is generic for all diagram elements.

**Comment by HGustavs** [comment]
The solution from previous years was to have a specific dialog for each diagram element and really complex code for storing the contents.

I suggest a simpler approach. 

In the side bar we have inputs for all available properties for all diagram elements and we hide the non-applicable ones.

Since all elements so far have names we never hide the name but for an entiy for example we hide the key checkbox

**Comment by HGustavs** [comment]
Mock-up for when ID-attribute is selected.

<img width="698" alt="Screenshot 2021-04-07 at 13 31 38" src="https://user-images.githubusercontent.com/6978801/113859811-9cbd9400-97a5-11eb-86ac-4122fcaad5b2.png">

Mock up for when more than one element is selected

<img width="690" alt="Screenshot 2021-04-07 at 13 36 26" src="https://user-images.githubusercontent.com/6978801/113860402-47ce4d80-97a6-11eb-9d93-e942defddbbf.png">

**Comment by HGustavs** [comment]
....We probably need a save edits button in the mock-up.... forgot to add that... 

We should only update properties that differ from the value given in the default and / or differ from the current value.

**Comment by a19nikbo** [comment]
Updated information to fit description ^^

**Comment by HGustavs** [comment]
I was thinking something along the lines of this attempt at a generic input handler. 

Some fiddling with the default values was necessary, so it is not perfect.
https://github.com/HGustavs/DiagramEngine/commit/4d216f595

But it is a step towards generic input hanlding for the diagram.

**Comment by a19nikbo** [comment]
Fixed
