### ISSUE TITLE
Swimlanes for deadlines longer than 10 weeks

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#9873]
![image](https://user-images.githubusercontent.com/81559946/113868471-ff1b9200-97af-11eb-9d87-414b90d1a08b.png)

...I do believe that the swim lanes functionality does not work for courses that are longer than 10 weeks (for example the final year project).....

This is part of bigger issue #9833

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
