### ISSUE TITLE
Guesstimate deadlines in the swimlane for unupdated deadlines

### ISSUE THREAD

**Issue by a19isada** [HGustavs/LenaSYS#9874]
![image](https://user-images.githubusercontent.com/81559946/113868627-2a9e7c80-97b0-11eb-8afb-90620bb09925.png)

If the deadline has not yet been updated for the current year it would be nice if we could still have a "guesstimate" for the deadlines transposed to the current year in the swimlane display, and some kind of display using coloring or other graphics indicating that the deadline has not been updated for the current year yet...

This part of bigger issue #9833

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
