### ISSUE TITLE
Template literals in Accessed.js

### ISSUE THREAD

**Issue by a19danla** [HGustavs/LenaSYS#9876]
Change template literals in accessed.js

**Comment by a19isada** [comment]
Part of issue #9785

**Comment by a19danla** [comment]
After some feedback from the client we decided that everything longer than 80-100 characters should be breaken down into several lines. Ex, if a row of code its 1000 character long it should be broken down to 10 rows of 100 character each.
Some variants may appear but focus should be on readability.

**Comment by a20chrjo** [comment]
Approved and merged by @a20chrjo
