### ISSUE TITLE
ctrl-selecting elements is unreliable if first element is selected normally

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9883]
If you select an element without holding down ctrl, and then select a number of elements while holding down ctrl the selections are unpredictable. If you select multiple elements without holding down ctrl, and then ctrl-select an element all the previously clicked elements will be highlighted as well despite supposedly not being multi-selected.

**Comment by HGustavs** [comment]
Isnt this the functionality we want?

* Step 1 Click an object or Box-select a number of objects (they would be added to context list) 

* Step 2 Box-select or Click on additional elements (if control is not pressed we clear context as first step of selection, if control is pressed we add clicked or box-selected objects to the context list)

If the highlight is based solely on the context list this should just work automatically?

**Comment by HGustavs** [comment]
In short: only difference if control is pressed or not shold be skipping over the clearing of the context list i.e. 

```
		// Clear list of selected elements
		context=[];
```

**Comment by HGustavs** [comment]
I am partial to the functionality of illustrator / photoshop, ctrl key for adding to selection set and alt key for removing from selection set.

Some softare uses flipping, alternately adding and removig if ctrl is pressed....this is not very useful especially if we box-select... and a number of items switch state.

**Comment by a19nikbo** [comment]
Fixed
