### ISSUE TITLE
Selecting an "old" element when trying to add a new element on top of it.

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#9887]
When you try to add elements right above old elements you select the old element instead of adding a new. You should have to use "Mouse select" to be able to select the element and you should only be able to create elements in the element modes.

**Comment by HGustavs** [comment]
From a workflow standpoint I feel that this is more or less as we want it.

Create and Individual Object Select / Drag / Move should work independently. Mouse select would be box-selection and individual select without ability to create new objects

Something like this:

1. Click Entity Create Mode
2. Click once to create one entity
3. Clic again to create another entity
4. Whoopsies 2. and 3. are too close, I click in 2 and move it, click in 3 and move it
5. Click in empty area between 2 and 3 to create a new one
...

Or

1. Click Entity Create Mode
2. Click once to create one entity
3. Click in entity to edit name / weak-ness in side bar, press button to save state
4. Click again in empty space to create new entity
...

**Comment by HGustavs** [comment]
My personal work-flow is, creating multiple objects of the same kind e.g. several entities then add e.g. several attributes then connect several attributes. But in between creating new objects I adjust position of existing ones

**Comment by a19frelu** [comment]
Then we leave it as it is for now, closing this Issue.
