### ISSUE TITLE
Make the element selection box dashed to distinguish it from weak entities

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9897]
It can currently be slightly ambiguous whether the selection box denotes a selected element or that the element is a weak entity. Especially in regards to color blindness. We should try making it dashed to make the distinction clearer.

**Comment by HGustavs** [comment]
Dashed or Dotted or Marching Ants. Unclear which is better.

![ants](https://user-images.githubusercontent.com/6978801/114063834-50ec1700-9899-11eb-9f06-b6d73b53c18d.gif)

**Comment by a19nikbo** [comment]
Fixed
