### ISSUE TITLE
Multiple elements can be selected when holding ctrl on Windows, but not with cmd on MacOS

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9900]
Expand the multiple-element-selection functionality to allow holding down the cmd button on Mac, instead of just taking ctrl into account.

**Comment by HGustavs** [comment]
Since macs have both keys, perhaps we can support either key?

**Comment by HGustavs** [comment]
There are still lots of modifier keys to take into account if we want to be exotic.

https://www.rcsri.org/collection/symbolics-keyboards/

**Comment by a19nikbo** [comment]
Fixed
