### ISSUE TITLE
The text box for receipts is resizable

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#9901]
At the moment the text box in the receipt is resizable and is able to break the container like so:
![receiptBreakage](https://user-images.githubusercontent.com/62884391/114037945-b92efe80-9881-11eb-93b2-0c3f64a890ee.PNG)

This is something that would be nice to remedy, I was thinking we could remove the functionality from the element.

**Comment by HGustavs** [comment]
We can probably use a text box or something like the press this button to copy hash to clipboard like for zoom-invites.

**Comment by HGustavs** [comment]
https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript
