### ISSUE TITLE
Randomize assignment variants when not logged in

### ISSUE THREAD

**Issue by a19rebsa** [HGustavs/LenaSYS#9904]
Right now when a student is not logged in and navigates to an assignment, the variant of the assignment probably is the first variant of it. This should be changed so the variant is randomized. So that we make sure that all students do not get the first variant, but randomized ones.

**Comment by HGustavs** [comment]
And we try to keep the same random variant through the use of local storage, but we do not emply any trickery to for example mitigate the effect of incognito mode.

**Comment by e15marol** [comment]
This issue has been resolved through another issue #9784 which uses local storage to keep the same initial random variant, it also works in incognito mode. Would recommend closing this issue.
