### ISSUE TITLE
Remove Random URL generation and replace with hash

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#9905]
Since we've received clarification that the hash generated for a submission should act as the url shortcut, we should remove the current url generator and replace that shortened url with the hash.
![HashIntoURL](https://user-images.githubusercontent.com/62884391/114046223-f5199200-9888-11eb-9d14-206aa0a139bd.PNG)

To note since we're unlikely to be able to use any serverside solution for redirection the new url will need to contain a ?a or &a. e.g.
.../sh/?a="HASH"

**Comment by HGustavs** [comment]
Plz make sure the random hash is in youtube style base64 while you are at it.

https://en.wikipedia.org/wiki/Base64
https://gist.github.com/fizruk/0b049254874bba5f3ccc0cf2e4c5663d
