### ISSUE TITLE
Location of index.php

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#9908]
LenaSYS has had two identical index.php files in the repository's file structure.
 One in `LenaSYS/sh` and another one in `LenaSYS/DuggaSys/sh` 

After week 14's merge the index.php file at LenaSYS/sh/ was removed, I was thinking that since Group-1 retains ownership of the files and several issues will concern this file, as it is used for URL shortening/redirection, I wanted to ensure that we start the weeks work with the file in the right position in the repository.

Should the file be kept in `LenaSYS/DuggaSys/sh` or moved to `LenaSYS/sh` ?

**Comment by a97marbr** [comment]
I would have the redirect service as close to the root as possible.

https://my.lenasys.install.com/sh/?c=32423jkh234234iuiahakjdsuw

**Comment by a18osken** [comment]
Moved index.php to root/sh
