### ISSUE TITLE
Feedback view previews a downloadabe pdf 

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#9909]
In the future a student should not be able to download anything from LenaSys, this means we need to strip all of the download functionality. Currently clicking the feedback button will show two panels, one of these is a preview of a pdf file which allows it to be downloaded.  This functionality should be removed, I would suggest perhaps removing the panel previewing the file

I do, however, remember having heard that LenaSys also should no longer contain feedback and that it should instead be given through Canvas so maybe we should remove the feedback entirely?

**Comment by HGustavs** [comment]
Yes we have no need for the feedback feature of submission for now.

If we get a more complete integration with canvas we can seamlessly store the feedback directly into canvas.

In any case we will not store any feedback locally.

**Comment by b19ponka** [comment]
We left the option for teachers to leave feedback to submissions but removed the possibility for students to download PDF/ZIP-files through the feedback view by removing the previews entirely
