### ISSUE TITLE
CodeView: Examples working properly with only google chrome

### ISSUE THREAD

**Issue by a12jiyba** [HGustavs/LenaSYS#991]
some boxes disappears with other webbrowsers.

**Comment by HGustavs** [comment]
This is a very important issue.

Most important of all.... i would say. 
 If this type of general stuff does not work in all browsers, all of the rest of the work is futile.

**Comment by f12danjo** [comment]
Seems to work exactly the same in chrome, firefox and opera. Not in internet explorer though.

**Comment by a13jorla** [comment]
We have now merged branch CodeView#991 Not working in some browsers and this made it possible to say we fixed this bug.
