### ISSUE TITLE
Make saved assignment relate to hash

### ISSUE THREAD

**Issue by a18osken** [HGustavs/LenaSYS#9910]
We need to make it so that a saved assignment is fetched in the database through its hash instead of any log in.

I am not entirely sure of all the relations in the database but currently the `userAnswer` tables uses `uid` from the `user` table as a foreign key, which I think is what connects the answer to a specific user. This table will not be in use by any student as students no longer should have a user on LenaSys. 

This relation should probably be replaced to make it so that the answer is connected to a specific hash instead. 

Part of issue #9790

**Comment by HGustavs** [comment]
I was imagining that it would be possible to just use the answer hash instead of the user id, and that that minor change would resolve the problem without any more far-reaching consequences.

**Comment by a18osken** [comment]
Some clarification: We want to be able to save assignments without being logged in, essentially we should identify the hand-in with hash instead of uid.
