### ISSUE TITLE
Undo functionality in diagram

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9915]
We'll want the user to be able to go back a step when pressing ctrl + z. I'm not sure how many steps back we should save but we can say about 15 for now to not overdo it. We'll want the old state to be saved when:

  - An element is moved
  - An element is created

In the future we'll want to include when an edge is created and possibly more, but since edge creation isn't fixed yet that'll have to be a future issue.

**Comment by a19nikbo** [comment]
This should probably be broken down into smaller issues.

**Comment by HGustavs** [comment]
This is automatically handled since we will be storing the complete history in the diagram. (there are several historical issues discussing this)

Not only can teachers view how students have drawn their diagram step by step from the start, like a youtube video... undo can be achieved by tossing out the top object in the array.

**Comment by HGustavs** [comment]
How we think this should be handled is described in issue  #9787

**Comment by HGustavs** [comment]
Im thinking of this like creating checkpoints, and we try to minimize the number of checkpoints. If we move the same object several times, we synchronize with the top version, but if we add another entity we create a new version.

And each time we compare with the "defaults" and only store the properties of each object in the history that differ from the defaults and from the previous version in the history.

When we read from the history we start with the default and only add update properties that have been changed.

I am hoping that we thus should be possible to push a play button and view the diagram as a movie from the empty sheet to the finished diagram.

**Comment by a19hammi** [comment]
Will take a look at it but we can expect this to NOT be completed before weekly merge.

**Comment by a19nikbo** [comment]
@a19hammi alrighty

**Comment by a19nikbo** [comment]
Fixed
