### ISSUE TITLE
Add nodes to the edges of selection box in diagram

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9917]
To break it apart into smaller issues this issue is not about the resizing functionality itself, but rather a preparative addition for when we add it later. We might want to add small nodes at the edges of the selection box that will later be used for resizing. I've made a mockup of how it may look, but the nodes might benefit from being slightly bigger.

![mockup2](https://user-images.githubusercontent.com/81541557/114148835-808f3380-991a-11eb-8f48-004d685e688c.png)

**Comment by HGustavs** [comment]
Most of the ER element should be resizable left-to-right but not top-to-bottom (entities and attributes), or not at all (relationship symbols)

So I would only place nodes on left/right sides...  I am not sure if we should put squares in the corners or only mid-line left and right.

<img width="319" alt="Screenshot 2021-04-09 at 10 21 39" src="https://user-images.githubusercontent.com/6978801/114152374-8424b980-991e-11eb-9e06-d451e6741ff8.png">

Col resize cursor would be a nice addition

**Comment by a19chrel** [comment]
If the user has selected multiple entities should it be possible to resize all entites at the same time or just one by one?

**Exempel of one entitie selected**
![bild](https://user-images.githubusercontent.com/62853826/114158368-e385c800-9924-11eb-9f61-59541fe4cf47.png)

**Exempel of multiple entities selected**
![bild](https://user-images.githubusercontent.com/62853826/114158520-0adc9500-9925-11eb-9f40-f58140a01c51.png)

**Comment by HGustavs** [comment]
I would say only for single objects, resizing multiple entities at once seems counter-productive to me.

**Comment by a19nikbo** [comment]
Fixed
