### ISSUE TITLE
Clean up and organize the way the system handles mouse events depending on mouseMode

### ISSUE THREAD

**Issue by a19aleda** [HGustavs/LenaSYS#9926]
Currently we have 4 functions which triggers on mouse clicks and mouse movement, with the introduction of mouse modes such as Entity creation, mouse selection and draw lines the complexity inside the existing mouse event functions are growing. A better way would be to clean this up and let individual functions handle individual mouse modes.

**Comment by HGustavs** [comment]
I really prefer if the mouse modes are handled only in the mouse event functions.

If we add touch events we can call the mouse event functions directly, or if we want hot-keys we can similarly change modes directly with one single line.

e.g. if we have a hot-key e.g. space bar for scrolling we ideally just need to change the mouse mode and it would work automatically. Or if we have a hotkey for changing into line connection mode we only need to change the mode and it would work automatically.

We could have a changemousemode(modenumber) function to make it even more general

**Comment by a19hammi** [comment]
This was more or less fixed in my pull-request #9944. Take a look at it and see if that's what you meant.
