### ISSUE TITLE
Add a desciption of the assignment the student is working on

### ISSUE THREAD

**Issue by a19rebsa** [HGustavs/LenaSYS#9927]
Right now when the student has navigated into an assignment there is a text in the header that says "Dugga not yet submitted" (see picture below). It would be better to have a description there of which assignment the student is working on e.g. "Färgdugga 1". This could probably be changed in dugga.js. 

![dugga](https://user-images.githubusercontent.com/62889999/114162148-1c27a080-9929-11eb-8674-5567476ebf7e.png)

**Comment by a18osken** [comment]
I think we could have the title of the assignment followed by the "Dugga not yet submitted" element.

**Comment by HGustavs** [comment]
Since we wont have the top menu when embedded through iframes, the currently used element will not be there?

**Comment by HGustavs** [comment]
<img width="1439" alt="Screenshot 2021-04-09 at 21 22 41" src="https://user-images.githubusercontent.com/6978801/114230746-d21adb00-9979-11eb-9945-3d75be15f0c8.png">

Currently for file submission assignment we have an accordion at the top. Perhaps placing the title of the assignment where it currently  says "instructions" would allow us to add text into the assignment while having the ability to close the accordion at will.
