### ISSUE TITLE
Include KeyListerner for Zooming in or out

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#9932]
To make the diagram easier to operate i suggest that scrollup and scrolldown should increase and decrease the value of the zoom. This make it possible to change the zoom value whitout accessing the options panel.

**Comment by HGustavs** [comment]
Another key binding to add is ctrl + and ctrl - which should also zoom in and out respectively.

I suggest through a function zoom(direction) which can be called in all places, for example ctrl+ would call zoom(1) and ctrl - would call zoom(-1) this way all zooming is handled in one specific location

**Comment by a19matma** [comment]
Wouldn't ctrl+ and ctrl- interfere with the option to zoom in and out of the whole browser? Or is this option not needed?
I've however fixed so that zooming in the diagram with the mousewheel now works as intended.

**Comment by a19nikbo** [comment]
Fixed
