### ISSUE TITLE
Mac users are unable to delete elements in the diagram.

### ISSUE THREAD

**Issue by a19frelu** [HGustavs/LenaSYS#9943]
While Windows users are able to delete objects in the diagram using the delete key, Mac users are not. This is because the same kind of key on Mac represents the function for backspace. 
To delete objects with a Mac keyboard, usually the "cmd" key in combination with the backspace key are used to perform a delete action.
This could be a way to solve the issue.

**Comment by HGustavs** [comment]
My suggestion is that we suooirt back-space on both platforms for deleting in addition to the delete key. It is also possible to configure a delete key on a portable mac and external keybords on mac also have a delete key just like on a PC.
