### ISSUE TITLE
Attribute properties

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9946]
The distinct states of er attributes are mutually exclusive, an attribute can not be both a multiple value and a key at the same time for instance.

I think we can use a dropdown instead of three individual boooleans, this way we can guarantee that we dont have multiple computed attributes or some other unsupported combination.

We can use the defaults to store the list of options. The first of which we can use as the default value.

https://github.com/HGustavs/DiagramEngine/commit/b8e8f8c

Dropdowns for controlling properties can perhaps be used in other locations for other mutually exclusive properties?

**Comment by a19nikbo** [comment]
Fixed
