### ISSUE TITLE
Diagram: Resize selected entity

### ISSUE THREAD

**Issue by a19chrel** [HGustavs/LenaSYS#9953]
Currently when you have selected an entity, nodes will be shown in the corners of the selected marker. As shown in the picture below.

![bild](https://user-images.githubusercontent.com/62853826/114361349-533ec180-9b76-11eb-93f9-424417fe3c8b.png)

The functionallity to resize the entity when moving one of the nodes should be added.

**Comment by a19nikbo** [comment]
Fixed
