### ISSUE TITLE
Options menu covering the ruler

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#9971]
As seen in the picture below, our options bar currently covers the underlying ruler.
Maybe we should apply a size to the options bar relative to the canvas height?

![image](https://user-images.githubusercontent.com/81571224/114390927-2353e600-9b97-11eb-8b88-3636713f34ec.png)

**Comment by HGustavs** [comment]
Also 

For all duggas, when embedded as an iframe into canvas or if the user clicks a  "full screen" button the purple top menu should also disappear.
