### ISSUE TITLE
Ruler pointer displayed on top of the top-down menu

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#9972]
There's a UI problem with the drop-down menus being rendered under the new ruler that needs to be fixed.

![image](https://user-images.githubusercontent.com/81571224/114391265-8fcee500-9b97-11eb-8dee-1fcb3bc50004.png)

**Comment by HGustavs** [comment]
Do we need the menus?

I think the menu contains only functionality that should apear in side-bar?

**Comment by a19nikbo** [comment]
Menu bar gone, poof
No longer issue
