### ISSUE TITLE
Background grid on diagram

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#9973]
It would be really nice to see a background grid under the elements that is properly aligned with the ruler.
Maybe this should be under a toggle as-well, or put that in another issue?

Something like this?

![image](https://user-images.githubusercontent.com/81571224/114391765-30250980-9b98-11eb-8aa5-888c3f4232cd.png)

**Comment by HGustavs** [comment]
Dotted thin lines that are not visible if grid is not enabled.

**Comment by a19nikbo** [comment]
Fixed
