### ISSUE TITLE
Diagram zoom using scroll-wheel

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#9974]
Currently we need to use the options menu to zoom in/out. It would be really nice if the mouse-wheel and +/- buttons could do the same. For simplicity's sake it would be good if we kept it at the set levels and don't introduce decimal or partial zooming.

**Comment by a19nikbo** [comment]
This already has an issue

**Comment by a19hammi** [comment]
Missed that one when searching. Thank you!
