### ISSUE TITLE
Select edges with mouse selection

### ISSUE THREAD

**Issue by b19phier** [HGustavs/LenaSYS#9975]
One has to be able to select the edges that are created in the diagram with mouse selection to later be able to delete these edges.

**Comment by HGustavs** [comment]
I have some code that I can donate.... because this is not as easy to determine 
as it seems

**Comment by HGustavs** [comment]
this.linedist = function (xk,yk)
		{
				if(this.symbolkind==4){
						var x1=points[this.topLeft].x;
						var y1=points[this.topLeft].y;
						var x2=points[this.bottomRight].x;
						var y2=points[this.bottomRight].y;						
							
						var px = x2-x1;
						var py = y2-y1;
						var len = px*px + py*py;
						var u = ((xk - x1) * px + (yk - y1) * py) / len;						

						if(u > 1){
								u = 1;
						}else if(u < 0){
								u = 0;				
						}
						
						var x = x1 + u * px;
						var y = y1 + u * py;
						px = x - xk;
						py = y - yk;
						
						dst = px*px + py*py;

						return dst;

				}else{
						return -1;				
				}

		}

**Comment by HGustavs** [comment]
From 2020 project allows us to click a certain distance away from the line, since the lines are perfectly thin objects it is otherwise mathematically difficult to click exactly on any line.

**Comment by HGustavs** [comment]
Checking if a line crosses a selection box is also not super-easy

The most common way is to check the bounding box for containment and then check for line crossing using the normal line to line intersection

**Comment by HGustavs** [comment]
<img width="658" alt="Screenshot 2021-04-12 at 17 12 56" src="https://user-images.githubusercontent.com/6978801/114417960-59529380-9bb2-11eb-8347-cabf29a6d699.png">

We have an intersection if either x1,y1 or x2,y2 is inside the box OR
if the line segment crosses either one of the 4 line segments that comprise the box

**Comment by a19nikbo** [comment]
Fixed
