### ISSUE TITLE
Backspace-deletion functionality interferes with removal of characters in input field

### ISSUE THREAD

**Issue by a19nikbo** [HGustavs/LenaSYS#9979]
If you select an element and press backspace it deletes the element. This is how we want it. However, if we have the input field for changing an element's name selected this functionality should be disabled. Otherwise, deleting characters is impossible.

![image](https://user-images.githubusercontent.com/81541557/114395530-c65b2e80-9b9c-11eb-87f0-8a6f0579916d.png)

**Comment by HGustavs** [comment]
True!

**Comment by a19nikbo** [comment]
Fixed
