### ISSUE TITLE
Make it possible to save an assignment when not logged in

### ISSUE THREAD

**Issue by a19rebsa** [HGustavs/LenaSYS#9980]
Right now you have to be logged in to be able to save an assignment as a student (see picture). This should be changed so that you do not have to log in to be able to save the assignment. 

![dugga3](https://user-images.githubusercontent.com/62889999/114396530-f951f200-9b9d-11eb-89ff-69fe447f138e.PNG)

**Comment by HGustavs** [comment]
Yes this is the intention as it will be impossible to log in to the system as that would require personal information
