### ISSUE TITLE
The diagram dugga has a purple top toolbar

### ISSUE THREAD

**Issue by HGustavs** [HGustavs/LenaSYS#9985]
If embedded as an iframe or if a full screen icon is clicked the purple top menu should disappear and the side bar should be top to bottom

<img width="480" alt="Screenshot 2021-04-12 at 17 40 04" src="https://user-images.githubusercontent.com/6978801/114422527-a7699600-9bb6-11eb-8cba-92a043131aac.png">

**Comment by HGustavs** [comment]
Partially related to #9971

**Comment by HGustavs** [comment]
<img width="480" alt="Screenshot 2021-04-12 at 17 40 04" src="https://user-images.githubusercontent.com/6978801/114422481-9b7dd400-9bb6-11eb-8462-a11b542b75ee.png">

**Comment by a19frelu** [comment]
This issue is not relevant anymore, might it be a good day to close it? @a18nadma ?

**Comment by a19hammi** [comment]
@HGustavs Relevant still?

**Comment by a19hammi** [comment]
Will be fixed in #11186
