### ISSUE TITLE
Small fix: If-statement continously growing

### ISSUE THREAD

**Issue by a19hammi** [HGustavs/LenaSYS#9995]
We need a better solution to the growing if-statement inside `exportElementDataToCSS`!
Currently looks like this `if (inContext && !clickedContainer && (notBoxSelection || clickedElement) && !clickedNode)`,
and who knows how long it will eventually grow if we keep going...

Me and @a19chrel have discussed it and believe that removing `deltaX` and `deltaY` from the `element.top` and `element.left` and introduce a new _specific_ delta that is _only_ for moving the element and not used in all the other modes.

This needs to be fixed **ASAP** before we start seeing an even bigger growth in the if-statement.

**Comment by a19nikbo** [comment]
Fixed
